### ISSUE TITLE
Custom games: cancel button not showing

### ISSUE THREAD

**Issue by diegogmx** [ValveSoftware/Dota-2#100]
the button to cancel joining a match when the host takes far too long doesnt appear, if its intended this way at least let it show up after 2-3 min

**Comment by EPadronU** [comment]
If the lack of a `Cancel ` button on that point of the match making (`Host loading`) isn't a bug, it would be great to add one as a feature. I would be very thankful. Cheers.

**Comment by diegogmx** [comment]
I wouldn't let it appear instantly, otherwise impatient morons can wreck a lot of games that last 20 seconds to load

**Comment by gdrewb-valve** [comment]
This isn't a Linux/Mac issue but I talked to the larger team and they said it was deliberate at the moment to prevent people from leaving early.  This could change in the future but as it's not a platform-specific thing it won't be tracked here.
