### ISSUE TITLE
[Linux] No score screen after local bot match.

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#1001]
After underlord update, the score screen does not appear.

Console message:
![2016-08-23-132842_1920x1080_scrot](https://cloud.githubusercontent.com/assets/425930/17906698/a6dcf852-6935-11e6-8298-908a4b6121ed.png)

System specs:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/f1aebe7f205263f85ea3986bcdceee122d137abc/gistfile1.txt

**Comment by gdrewb-valve** [comment]
This is happening on all platforms, the larger team is taking a look.
