### ISSUE TITLE
Severely broken graphics after latest update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1004]
https://imgur.com/a/RCxAM

Debian stable.

```
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09) (prog-if 00 [VGA controller])
    Subsystem: ASUSTeK Computer Inc. Device 181d
    Flags: bus master, fast devsel, latency 0, IRQ 64
    Memory at f6000000 (64-bit, non-prefetchable) [size=16M]
    Memory at e0000000 (64-bit, prefetchable) [size=256M]
    I/O ports at f000 [size=64]
    Expansion ROM at <unassigned> [disabled]
    Capabilities: <access denied>
    Kernel driver in use: i915
```

Everything worked fine yesterday. No recent system updates and rebooting didn't help. Obviously other games work just fine (eg. hl2).

**Comment by ghost** [comment]
Same problem....  http://imgur.com/a/hMaIk  (screenshot in the game)

OS: Debian 8.5 jessie
Kernel: Linux 3.16.0-4-amd64

00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
 Subsystem: Gigabyte Technology Co., Ltd Device d000
Flags: bus master, fast devsel, latency 0, IRQ 41
Memory at fb800000 (64-bit, non-prefetchable) [size=4M]
Memory at e0000000 (64-bit, prefetchable) [size=256M]
I/O ports at ff00 [size=64]
Expansion ROM at <unassigned> [disabled]
Capabilities: < access denied>
Kernel driver in use: i915

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.3.2
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.0

**Comment by george-lukas** [comment]
Uff! I through it was only with me. I got a similar error. Instead black screen I got a visual glitch even after smaller update and steam minor update.
http://pastebin.com/tG7bFkyd
http://imgur.com/a/yxMgn

my system:
http://pastebin.com/HVd8rgYW

**Comment by ghost** [comment]
FYI, there's nothing interesting in the log:

```
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
[2016-08-23 21:37:42] Startup - updater built Aug 23 2016 18:24:59
[2016-08-23 21:37:42] Verifying installation...
[2016-08-23 21:37:42] Verification complete
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Running Steam on debian 8 64-bit
STEAM_RUNTIME has been set by the user to: /home/{username}/.steam/ubuntu12_32/steam-runtime
Refresh rate: 1
Refresh rate: 1
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor Intel Open Source Technology Center
DumpContextInfo: OpenGL renderer Mesa DRI Intel(R) HD Graphics 5300 (Broadwell GT2) 
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
```

**Comment by danginsburg** [comment]
You all seem to be on mesa 10.3.2 which is below the minimum recommended of mesa 10.6.  That being said, if it was working prior to this update I bet it's a bug with GL_ARB_compressed_texture_pixel_storage which we recently added support for.  Can you try running with -gl_disable_compressed_texture_pixel_storage in your Launch Options?  If that fixes it, I'll add a driver detect for mesa 10.3.x to forcibly disable it.  I did test it on Haswell mesa 10.5.8 and it was fine.

**Comment by george-lukas** [comment]
Awesome, talking with friends that use microsoft. they noticed some performance issue. it seems that dota2 is heavier after this last update.

**Comment by ghost** [comment]
@danginsburg That works, thanks

@george-lukas  Not sure about performance, but that would require a new ticket anyway.

**Comment by ghost** [comment]
@danginsburg Thanks!

**Comment by cracolo** [comment]
@danginsburg awesome !!!

te pasaste wn, gracias !!!

**Comment by danginsburg** [comment]
This mesa bug was introduced starting in mesa 10.3.0 and fixed in mesa 10.3.5 in the following commit:

https://lists.freedesktop.org/archives/mesa-commit/2014-December/053540.html

I put in a workaround to disable use of GL_ARB_compressed_texture_pixel_storage automatically on mesa 10.3.x.  It will be in the next Dota 2 update.

**Comment by avcs06** [comment]
@danginsburg Thank you very much, that solved the issue

**Comment by danginsburg** [comment]
The new update contains the workaround to automatically disable GL_ARB_compressed_texture_pixel_storage usage on mesa 10.3.x so I'm closing out this issue.

**Comment by ghost** [comment]
Confirming it works without the launch option workaround. Thanks again.
