### ISSUE TITLE
Vulkan renderer hiccups on latest update

### ISSUE THREAD

**Issue by r3pek** [ValveSoftware/Dota-2#1006]
Didn't found the source of this problem yet, but yesterday after applying the patch the vulkan renderer have massive hiccups to the point of crashing the game. It happens on nvidia's 370.23 driver. I also updated the driver at the same time, so it can be one of the two problems but I can't go further. Right now, i'm using OpenGL again.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Mutter(Budgie)
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 370.23
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 119 Hz
VendorID:  0x10de
DeviceID:  0x1184
Revision Not Detected
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 4240 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15991 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  2844705 Mb
    Largest Free Hard Disk Block:  1964995 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
For the future Vulkan issues should be reported in Dota-2-Vulkan.

**Comment by AbuShawarib** [comment]
I confirm this is a driver issue. Reverting to 367.44 driver makes everything normal. I also tried vkQuake it had crashes (fail vkWaitForFences) and temporally lockup the system with this 370.23 driver, but works normal with 367.44. I guess it's safe to close this issue and go to Nvidia to report this.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
