### ISSUE TITLE
[Linux] Latest update breaks alt-tabbing/ changing resolution

### ISSUE THREAD

**Issue by ReactorofR** [ValveSoftware/Dota-2#1007]
Arch Linux 64bit
i7 3630QM @2.4GHz
GTX 650M
(Driver version : 370.23-2)
Window manager : BSPWM
Compositor : Compton

I believe this started after the latest small update as I distinctly remeber losing mmr with pitlord on my team, however I can't recall if updated to 370.23 before or after that. I'll try reverting to the previous driver in a bit.

The Issue:
Dota launches and seems to work fine as far as I don't switch focus/change desktop or change resolution / window mode, if I do it will stop responding, and in the case of changing window mode lock up my entire system requiring a hard reset.

I tried both vulkan and opengl both showing the same behavior.

I don't have the time right now but I'll report back in an hour or two after I can test a bit more and see if I can narrow down the issue.

**Comment by gdrewb-valve** [comment]
The system lockup strongly suggest this is a driver problem since it's not possible for Dota itself to do that.

**Comment by ReactorofR** [comment]
Downgraded to 3.678 and everything's back to normal. I'm sorry I thought it was a Dota bug.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
