### ISSUE TITLE
[Linux] Game doesn't work after latest update on 2016/08/27

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1009]
The game worked fine yesterday, about 24 hours before this post.
Starting the game through steam: nothing shows up, the game is running. htop output: 

> user   7461  0.0  0.2 102076 44468 ?        S    17:44   0:00 /bin/sh -c '/SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh' -novid -console -cursor_scale_percent 100 -exec -linux.cfg 
> user   7462  0.0  0.2 109828 46796 ?        S    17:44   0:00 /bin/bash /SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh -novid -console -cursor_scale_percent 100 -exec -linux.cfg
> user   7465  0.0  0.3 1215564 61412 ?       Sl   17:44   0:00 /SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 -novid -console -cursor_scale_percent 100 -exec -linux.cfg

It crashes afterwards.
Here is what I get from running from terminal (for better details):

> ./dota.sh 
> Using breakpad crash handler
> **../common/pipes.cpp (769) : Assertion Failed: fatal stalled cross-thread pipe**
> **../common/pipes.cpp (769) : Fatal assert failed: ../common/pipes.cpp, line 769.  Application exiting.**
> 
> **Assert( Assertion Failed: fatal stalled cross-thread pipe ):../common/pipes.cpp:769**
> 
> _ExitOnFatalAssert
> crash_20160827173307_2.dmp[7218]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20160827173307_2.dmp

And

> crash_20160827173307_2.dmp[7218]: Finished uploading minidump (out-of-process): success = yes
> crash_20160827173307_2.dmp[7218]: response: Discarded=1
> crash_20160827173307_2.dmp[7218]: file ''/tmp/dumps/crash_20160827173307_2.dmp'', upload yes: ''Discarded=1'

---

_SPECS (followed by steam system  info report):_

Linux Mint 17 Qiana x86_64 (ubuntu 14.04.1 based) KDE desktop manager
Kernel 3.13.0-24-generic
VGA controller: NVIDIA GK104M [GeForce GTX 670MX]
nVidia binary driver 352.63-0ubuntu0-014.04.1 GLSL 4.50 (latest available)
CPU Intel Core i7-3740QM 2.70GHz, 8 cores, 16GB RAM

```
   Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2701 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670MX/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.63
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x11a1
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 15.04" x 8.46"  (17.24" diag)
                                            38.2cm x 21.5cm  (43.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16009 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  22606 Mb
    Largest Free Hard Disk Block:  7834 Mb
    VR Headset: None detected

Recent Failure Reports:
    Sat Aug 27 14:58:08 2016 GMT: file ''/tmp/dumps/assert_20160827165803_55.dmp'', upload yes: ''CrashID=bp-6dbc102e-ae1a-4d56-8194-a057b2160827''
    Sat Aug 27 15:01:06 2016 GMT: file ''/tmp/dumps/crash_20160827170104_2.dmp'', upload yes: ''Discarded=1''
    Sat Aug 27 15:28:27 2016 GMT: file ''/tmp/dumps/crash_20160827172826_2.dmp'', upload yes: ''Discarded=1''
    Sat Aug 27 15:33:08 2016 GMT: file ''/tmp/dumps/crash_20160827173307_2.dmp'', upload yes: ''Discarded=1''
    Sat Aug 27 15:47:11 2016 GMT: file ''/tmp/dumps/crash_20160827174709_2.dmp'', upload yes: ''Discarded=1''
```

**Comment by gdrewb-valve** [comment]
The terminal output indicates that Dota is trying to talk to the Steam client and is timing out.  Is the Steam client working normally?  Do other Steam games start properly?

**Comment by glubsy** [comment]
Thanks, I restarted the Steam client and tried again. It now works fine. 
I don't recall doing anything in particular back then. Other games worked fine, but maybe they didn't depend on Steam at all (King Arthur's gold was the one I was testing at the time)
Sorry for adding noise. Keep up the good work! :+1:
