### ISSUE TITLE
[linux] cant change resolution in fullscreen

### ISSUE THREAD

**Issue by SuperFlick** [ValveSoftware/Dota-2#101]
It is always native (1366) and ignores "apply" button.  The Issue came with 6/24 update.
Ubuntu 14.04
Intel hd 3000
mesa 10.7

btw Reborn works better via WINE (v1.7 with "-gl" launch option). It's faster, has higher fps, but totaly ignores my keyboard when dota2reborn launched.

**Comment by gdrewb-valve** [comment]
This limitation is expected currently and we'll be removing the fullscreen option in the settings to avoid confusion.

**Comment by ramma** [comment]
Does this mean the "Use my monitor's current resolution" option is essentially full screen? Or is that a borderless window too?

**Comment by gdrewb-valve** [comment]
It's a borderless window, Reborn never uses true fullscreen on Linux right now.

**Comment by ramma** [comment]
Could that have something to do with bug #30 then? I'm pretty sure actual fullscreen captures those types of keys, but borderless window mode won't always capture them. It also happens in source 1 in full screen as well though.

**Comment by gdrewb-valve** [comment]
It's certainly possible.

**Comment by gdrewb-valve** [comment]
The lack of true fullscreen support is already captured in #63 so closing this.
