### ISSUE TITLE
[Linux] Dota 2 won't launch, error in launch config

### ISSUE THREAD

**Issue by fredrikekre** [ValveSoftware/Dota-2#1010]
Dota 2 won't start since ~2 weeks, same problem for after all the updates during this period. This shows up when I launch the game:

![dota2error](https://cloud.githubusercontent.com/assets/11698744/18029380/ff109eb6-6c96-11e6-97b6-9667cf8c07bd.png)

Tried removing and reinstalling the game completely.

```
fredrik@fredrik-desktop ~ $ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory

```

**Comment by gdrewb-valve** [comment]
Your installation is corrupted somehow, it's impossible to say why.

Do you have the file Your_Dota_install_directory/game/dota/cfg/launch.vcfg?  Can you put a gist of that here?

**Comment by fredrikekre** [comment]
Well... all that is in that file is:

`[ˆ©ÛÄ¹&GïÉÑ÷`

EDIT: The first character looks like this in Sublime:
![selection_012](https://cloud.githubusercontent.com/assets/11698744/18030391/9e1cec36-6cb4-11e6-87f6-90958a8911d1.png)

**Comment by gdrewb-valve** [comment]
It should be plain human-readable text, so that garbage is definitely the source of the problem.  If you delete just that file and run Dota does it get recreated?  If you turn off Steam cloud syncing for Dota, delete the file and run Dota does it get recreated?

**Comment by fredrikekre** [comment]
Deleting the `.../launch.vcfg` and restarting Dota worked. The created file looks like this now:

```
"schema"
{
}

```

**Comment by anpel** [comment]
This one just cost me an abandon. Deleting the `launch.vcfg` file worked for me too.

In my case the path for the file was `/home/anpel/.steam/steam/steamapps/common/dota 2 beta/game/dota/cfg/` in case it helps anyone.
