### ISSUE TITLE
[Linux] Dashboard performance and New Post-Game screen

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#1013]
Since the Dark Rift update, the performance of the Dashboard gets worse the more matches are played.

After one match, it works fairly nicely, I can exit the match quickly and the Dashboard comes up pretty soon as well.

However, if 2 or more games are played within the same session (without restarting the game), the post-game screen starts to load very-very slowly, and even if it does, sometimes I have to wait a lot more for the heroes to load, though this doesn't stop me from viewing stats properly, the UI is responsive, but the models don't load, only after a while.

_Also_ after a couple games (2-3, or more), when a new match is found, the game freezes. The cursor doesn't, but everything else does. This is typically bound to the Match-Found window, though fortunately the menu comes back responsive again in time, so I still manage to accept the match before it drops me out from queue.

The actual gameplay itself is not affected at all by these performance issues, I still manage to get the same FPS as normally, no drops whatsoever, only the Menu gets worse.

Here's a gist of my system information: https://gist.github.com/helix42/749ac54d6099c026bbab49fa66f10dbc

Edit: Using the OpenGL version of the game.

The new Post-Game screen also has this weird little thing on the top right corner for some reason:

![postgamescreenuibug](https://cloud.githubusercontent.com/assets/7419656/18227700/0b41bf02-722e-11e6-9cd8-9e335a34a5c4.png)

(Edit: This is not a Linux-related bug, but now that I'm here, I'll let you know this, too:

Visage's Familiar's Stone Form ability sounds are played too early, even before the actual landing. I'm using the Immortal Familiars, but the regular dropping sound comes soon as well. Asked my friend who uses windows and he heard the sounds too early too, so this is great possibly a generic issue.)

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
