### ISSUE TITLE
[Linux] game laggly when playing more than one match

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1015]
Hi.

Before Dark Rift update my dota 2 working fine but after it I have issue.

When I playing one match - all is fine, but when I finish playing one match, all my game laggy. So even main menu response with delay. 
When I start agan match, I can't even normal play. Because after some time I get huge lags and my game for 1-5 seconds freeze (FPS counter show for me 1 FPS). This happens especially when hero cast big spell like ultimate kunka or first skill underlord.

If I reboot my game, lags and freeze go away.

Any idea?

System info:
https://gist.github.com/xpris/2ddbe85024815b9a9977e8e89dcb6570

**Comment by ramma** [comment]
There's been some reddit threads with similar issues after more than one game, so I doubt this is platform specific.[ Their solution](https://np.reddit.com/r/DotA2/comments/50amjy/give_us_a_performance_patch_pls/d72kzkb) was to be sure the learn tab was selected before each game.

**Comment by danginsburg** [comment]
Does switching to the Learn Tab make a difference?  If so, let us know so we can confirm that this is the same issue @ramma mentioned.

**Comment by AngryPenguinPL** [comment]
Yes this is this bug. Solution @ramma fixing my issue. Thanks.

Please let us know, when you fixing it :)

**Comment by abobier** [comment]
Same problem.  
I'll try the @ramma solution tomorrow.

**Comment by abobier** [comment]
Not fixed for me, I can't play. It's just horrible ...

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
