### ISSUE TITLE
[Linux] Alt-tab gets me stuck in the game

### ISSUE THREAD

**Issue by kvblinov** [ValveSoftware/Dota-2#1017]
I have Ubuntu 16.04.1 LTS with stantard Unity desktop. Usually alt-tab works normally, and even in dota itself it works sometimes, but in other cases when I'm trying to alt-tab to desktop or browser I can't. Game keeps on going but I can't click anything there. Even if I kill dota process with ctrl+alt+f1 and top comand and then come back to the main desktop (ctrl+alt+f7) - still there is a dota frozen screenshot there and I can't alt-tab to desktop.
I also have Intel HD Graphics 530 with the latest drivers

**Comment by gdrewb-valve** [comment]
There's a Dota image visible even after you've killed the Dota process and verified that it's gone?  That seems more like a system problem than a Dota problem.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
