### ISSUE TITLE
Second monitor goes blank when starting Dota 2 on the main monitor

### ISSUE THREAD

**Issue by ashishawaghad** [ValveSoftware/Dota-2#1018]
Anyone else face this issue where my second monitor goes blank when starting Dota 2?

**Comment by gdrewb-valve** [comment]
What's your system info?

**Comment by ashishawaghad** [comment]
MacBook Pro 15" late 2013 model

**Comment by gdrewb-valve** [comment]
Which version of OSX are you running?  How is your second monitor connected?  What video settings are you running Dota with?  If you're running exclusive fullscreen and try desktop-friendly fullscreen does that change things?

**Comment by ashishawaghad** [comment]
`desktop-friendly fullscreen` worked. Thanks.

I didn't find any documentation for this anywhere. Anyway, works now (y)
