### ISSUE TITLE
[Linux] Vulkan back-end doesn't work at all

### ISSUE THREAD

**Issue by DyXel** [ValveSoftware/Dota-2#1019]
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux testing (stretch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 12.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 12.20" x 6.85"  (13.98" diag)
                                            31.0cm x 17.4cm  (35.5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC269VB

Memory:
    RAM:  7823 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  26155 Mb
    Largest Free Hard Disk Block:  11367 Mb
    VR Headset: None detected
```

Window Manager: KWin Plasma 5 (Wayland)

I know that this should probably be posted too on the mesa forums but i thought to share this here because this is one of few games that actually supports Vulkan (and also because Valve develops the Vulkan SDK).

The mesa 12.0.2 has arrive to the testing repositories under Debian and with that updates it also comes Vulkan, which doesn't work at all, the games starts up and load everything (you can hear the sounds), but it has heavy graphical issues (only the red screen with the dota logo is shown), also the Steam-overlay doesn't work.

fortunately the non-vulkan back-end work just fine, but i wanted to test out the Vulkan back-end here on my laptop and see if there is better performance...

**Comment by Tele42** [comment]
Hello @DyXel,
Vulkan support on Ivybridge is experimental in mesa 12.0. This needs to be reported to the mesa devs, not Valve devs, however, this is definitely something that's not going to work until mesa's support for Vulkan on Ivybridge has more polish.

This has been previously mentioned at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/153#issuecomment-235257834.

**Comment by DyXel** [comment]
Hello @Tele42,

Thank you for answering, i will just take my time and wait for future releases. They are doing a great job anyways!

**Comment by gdrewb-valve** [comment]
Closing as this is known.
