### ISSUE TITLE
[Linux] dota 2 reborn beta says Update Required but there is no update

### ISSUE THREAD

**Issue by suptimal** [ValveSoftware/Dota-2#102]
![Dota wants update](http://i.imgur.com/RW3i2Ts.jpg)

i restarted:
- Dota
- Steam
- PC

but the update notification stays and steam wont make an update

EDIT: i cant play anything cause the game wants the update

**Comment by blendi-93** [comment]
as usual it just takes longer for linuxusers ;) now the update starts
