### ISSUE TITLE
Unable to assign Win/Meta key anymore

### ISSUE THREAD

**Issue by JimmieCrackCorn** [ValveSoftware/Dota-2#1020]
Running Kubuntu 14.04 LTS. I had the Win/Meta key assigned to picking up items from stash and after noticing that it wasn't working I looked at my hotkeys realized I was unable to assign that key  to anything anymore when I previously had been able to. Using the launch setting to debug it isn't registering any keyboard presses on that key.

**Comment by gdrewb-valve** [comment]
Control, shift and alt all work and show keypress info?  Did anything about your system change or get updated?

**Comment by JimmieCrackCorn** [comment]
Yes, all those keys show up. Nothing that would effect my keyboard inputs to my knowledge.

**Comment by ramma** [comment]
Do you have the option enabled to make the win/super key bindable? It was added a while back, and disabled by default which unbound my binds for it until enabled.

**Comment by JimmieCrackCorn** [comment]
Yeah I have it enabled because I had previously used it. Now all of a sudden it isn't recognized as being pressed at all.

**Comment by JimmieCrackCorn** [comment]
I figured it out. I caught my cats had jumping on my keyboard the other day and if you press F12 and the Fn key you will lock the Win/Meta key. Sorry!

**Comment by gdrewb-valve** [comment]
:-) Thanks for letting us know.
