### ISSUE TITLE
[Linux] Unity Top-Panel moves borderless window

### ISSUE THREAD

**Issue by iMarv** [ValveSoftware/Dota-2#1022]
Ubuntu 16.04
On a screen with the resolution 2560x1080 a borderless window with the resolution 1920x1080 is being moved down by the Top-Panel of unity.
This causes the bottom ledge of the game-screen to be moved out of the screen so camera movement by moving the mouse to the screen ledges does not work.

**Comment by Tele42** [comment]
Hello @iMarv23, you should be able to use desktop-friendly fullscreen to get the behavior you are looking for.

**Comment by gdrewb-valve** [comment]
Let us know if Tele42's suggestion works out.

**Comment by iMarv** [comment]
That works in some way, but it stretches the game over the entire screen, so I see 1920x1080 on a 2560x1080 screen.

I have posted a question for this on StackExchange before submitting this issue: http://askubuntu.com/q/824892/594678 there you will also find screenshots.

Will provide a screenshot of Desktop-Friendly fullscreen when I am back home in about 10 hours.

**Comment by gdrewb-valve** [comment]
Fullscreen modes are supposed to cover the screen so that's expected.  Did you change the Dota video settings to 2560x1080?  There should only be the regular aspect ratio stretching in that case.

**Comment by gdrewb-valve** [comment]
Do you want Dota to cover the screen or be in a window smaller than the screen?  Can you describe exactly what you want to happen?

**Comment by iMarv** [comment]
I want to play dota with a resolution of 1920x1080 as it gives me the desired field of view I need. On 2560x1080 the hud becomes very large and hides a lot of the screen  (I guess because of balancing so that people with smaller screens do not have a disadvantage).
To play the game in 1920x1080 I need to launch it in borderless-window mode. Before using ubuntu, I did exactly this in windows which worked out as the game filled the full height of the screen. On Ubuntu though, the top-panel of the unity interface moves the borderless-window down so it is partly out of my screen. When moving it upwards while holding ALT, I can fit the bottom ledge of the window to the bottom of my screen, but in that case the unity-panel covers the top part of the game-window.

**Comment by gdrewb-valve** [comment]
There's no way to achieve exactly what you want.  When Dota is running in windowed mode it's just a regular window and obeys all of the normal window behaviors, such as whatever Unity wants to do with it.

You can get close, though.  Using the -w and -h launch parameters you can set the window size to whatever you want, so choose a 16:9 size that's small enough to give space for Unity, like 1760x990 (or whatever will make it fit).  That'll be just slightly smaller than what you want.  The launch parameters would be this for windowed borderless 1760x990.

```
-sw -noborder -w 1760 -h 990
```

**Comment by iMarv** [comment]
Alright.
Well then the problem is solved as far as that there is no fix.
Would love to have an option though to have the game fullscreen, but instead of stretching the 1920x1080 just adding black areas left and right of the screen so that one can experience the game in the desired resolution while not being bugged by unity

**Comment by gdrewb-valve** [comment]
There's ongoing work to update the HUD to handle a wider variety of screen sizes and aspect ratios.  That's being carried out by the larger team and won't be tracked here, but should eventually make it out to the world.

**Comment by iMarv** [comment]
The new HUD fixes all my problems, just want to give a shoutout for that. Good job guys!
