### ISSUE TITLE
10v10 wait dialog only show ten players.

### ISSUE THREAD

**Issue by kokutoukiritsugu** [ValveSoftware/Dota-2#1025]
picture:

![qq 20160919221329](https://cloud.githubusercontent.com/assets/5471433/18643159/63a06504-7ed6-11e6-991e-b5c1e3dc8ce3.jpg)

could fix this to show all 20 players ?

**Comment by gdrewb-valve** [comment]
This forum is specifically for Linux/Mac porting bugs.  You'll want to post this at dev.dota2.com
