### ISSUE TITLE
Dota 2 closing after update on Nvidia

### ISSUE THREAD

**Issue by esiemann** [ValveSoftware/Dota-2#1026]
Dota is closing after update. Already I changed the video driver. I have already installed twice the steam and the errors continues. I'm using the 367.44 driver nvidia in Ubuntu 16.04.

warning: The VAD has been replaced by a hack pending a complete rewrite
Generating new string page texture 87: 16x256, total string texture memory is 524,29 KB
Generating new string page texture 88: 384x256, total string texture memory is 917,50 KB
Generating new string page texture 89: 32x256, total string texture memory is 950,27 KB
Generating new string page texture 90: 24x256, total string texture memory is 974,85 KB
ERROR: ld.so: object '/home/xxxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxxx/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20160919222750_1.dmp[8076]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160919222750_1.dmp
/home/xxxxxxxxx/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: linha 104: 7888 Falha de segmentação (imagem do núcleo gravada) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 7888
No cached sticky mapping in ActivateActionSet.Inconsistency detected by ld.so: dl-close.c: 811: _dl_close: Assertion `map->l_init_called' failed!
crash_20160919222750_1.dmp[8076]: Finished uploading minidump (out-of-process): success = yes
crash_20160919222750_1.dmp[8076]: response: Discarded=1
crash_20160919222750_1.dmp[8076]: file ''/tmp/dumps/crash_20160919222750_1.dmp'', upload yes: ''Discarded=1''
pid 8076 != 8075, skipping destruction (fork without exec?)

**Comment by Tele42** [comment]
Possibly related: https://bugzilla.redhat.com/show_bug.cgi?id=1264556

**Comment by rmbleeker** [comment]
Not sure if it's related, but Dota 2 seems to be crashing a lot since yesterday's update when playing Arcade games, specifically Dota IMBA. 

Running Ubuntu 14.04.5 LTS with Nvidia 370.28

```
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
assert_20160920190410_1.dmp[27887]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160920190410_1.dmp
/home/xxxxxxxx/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104: 27739 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 27739 
No cached sticky mapping in ActivateActionSet.assert_20160920190410_1.dmp[27887]: Finished uploading minidump (out-of-process): success = yes
assert_20160920190410_1.dmp[27887]: response: Discarded=1
assert_20160920190410_1.dmp[27887]: file ''/tmp/dumps/assert_20160920190410_1.dmp'', upload yes: ''Discarded=1''
pid 27887 != 27886, skipping destruction (fork without exec?)
Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!
```

**Comment by gdrewb-valve** [comment]
If you can get a failure report with a CrashID (both referenced here were discarded) that'd be useful.

**Comment by vadi2** [comment]
http://www.dota2.com/news/updates/24329 "Fixed a recently introduced crash on exit from some custom games."

**Comment by esiemann** [comment]
Same problem after last update =(

[eduardo_log.txt](https://github.com/ValveSoftware/Dota-2/files/487251/eduardo_log.txt)
[eduardo_stdout.txt](https://github.com/ValveSoftware/Dota-2/files/487252/eduardo_stdout.txt)
[crash_20160921132240_1.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/487253/crash_20160921132240_1.dmp.zip)

**Comment by gdrewb-valve** [comment]
Is this still happening?  The crash dump shows a segfault in Dota code but doesn't have enough information to diagnose the problem.  I don't have any issues running Dota on my Linux box but it's not Ubuntu 16.04 and has an older NVIDIA driver.

**Comment by rmbleeker** [comment]
On Ubuntu 14.04 Dota hasn't crashed on me even once since the update on September 20th that @vadi2 quoted.

**Comment by esiemann** [comment]
After the last update is running smoothly, but Steam and Dota 2 has been updated.

**Comment by gdrewb-valve** [comment]
OK, closing.  If new problems occur in the future just open new issues since it seems like this one is resolved.
