### ISSUE TITLE
[Linux] Client not preventing mouse to leave the game area when Casting a game inside Lobby

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1028]
This has been reported by me almost a year ago and i misreported as fixed. I'm still having this issue now that i got a chance to cast another game inside lobby and on my home linux machine.

I have the game running on monitor 1 (on the right) and when trying to pan the camera to the left (towards monitor 0) the mouse just goes to the other screen.

**Comment by gdrewb-valve** [comment]
I believe this is expected behavior as the window lock does not apply in many non-game situations.  Does the mouse get locked correctly to the window when playing a bot match?

**Comment by Tele42** [comment]
For what it's worth, the old workaround for this kind of issue is to vertically offset one of your two displays, so that the mouse can only transition to the other monitor in a corner.

**Comment by admshao** [comment]
This is not expected behavior. Casting a game is a window lock situation
since you have to control the camera actively and the bug isn't present in
Windows version.

I just tried a bot match and the windows lock is applied correctly. Playing
a game, watching on DotaTV in player` perspective and on Free Camera are
the other situations where the lock is applied correctly.

Just Casting a game inside the lobby that is still missing.

2016-09-21 14:26 GMT-03:00 Tele42 notifications@github.com:

**Comment by gdrewb-valve** [comment]
@admshao, I assume you're running with Dota covering the whole right monitor?  If you use a window that is less than monitor-sized does it lock?

@Tele42, was there a known cause of the behavior you mention? It sounds like an X issue.

**Comment by admshao** [comment]
Yes, i use Fullscreen friendly on my right monitor (not the main), which is
the -sdl_displayindex 1. I can try to run on left monitor maybe way later
tonight or only tomorrow

2016-09-21 15:06 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by Tele42** [comment]
@gdrewb-valve, I do not understand your question.

Most desktop environments only allow a mouse to transition from one display to another at their logical overlap in the X config, which can be adjusted to make a very small transition area of the monitors.
![screenshot from 2016-09-21 15-30-12](https://cloud.githubusercontent.com/assets/3130103/18725948/4e49566c-8010-11e6-8ac5-cd06a6f8db40.png)
In this config, the mouse will hit the edge of the screen except for the top left of the orange monitor, which lets the mouse goto the bottom right of the blue monitor. This is true for any application that does not lock the mouse (particularly useful for some presentation software).

**Comment by gdrewb-valve** [comment]
@Tele42, I thought your initial comment might be indicating some kind of unusual X server behavior where X cursor restrictions didn't work properly if you had two monitors lined up exactly.  When you said "vertical offset" I thought you meant any vertical offset, so setting the monitors one pixel off would fix the problem.  You already cleared that up, so my question is answered.

The reason I was checking on that and why I suggested to admshao to try a regular non-monitor-sized window is that the cursor restriction works fine in a bot game so Dota's cursor restriction code is not completely broken.  The question is then what specific circumstance causes it to break as that might suggest whether it's a system/SDL problem or a Dota problem.

**Comment by admshao** [comment]
For what i can understand, it seems to be that dota isnt setting the lock
when im on caster slot inside lobby because all others scenarios is just
fine. Well, since this doesn't happen on windows i can see what you might
mean with system/sdl but i would say it's unlikelly not to be dota linux
client

**Comment by gdrewb-valve** [comment]
It's certainly possible that it's a Linux-specific issue in the Dota client.  If the lock works when Dota runs in a regular, non-monitor-sized window that makes it less likely.  If the lock doesn't work even for a regular small window, regardless of monitor, that makes it more likely that Dota just isn't requesting the cursor lock.

Also, does switching away from Dota and back to it change anything?

**Comment by admshao** [comment]
No, it dos not change anything. And yes. the lock works just fine for all
other situations.
I'm about to join the lobby to cast another game. Any Specific console args
or anything to me to do?

2016-09-21 21:41 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by admshao** [comment]
That might help bisect the issue

2016-09-21 21:43 GMT-03:00 Fabio Madia admshao@gmail.com:

**Comment by gdrewb-valve** [comment]
I don't know of relevant options but I'll ask around.  There probably won't be much of a response until next week.

Just so I'm sure I understand, when you say that the lock works fine for all other situations you mean it works when windowed and casting and it only doesn't work when in fullscreen and casting?

**Comment by admshao** [comment]
Oh. I never played dota on Windowed mode. All my statments was about
fullscreen friendly.
The other situations that i meant was (playing, spectating dota tv, bot
games and so) and only casting inside lobby i don't hape the expected lock.

2016-09-21 23:39 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
Have you changed the dota_mouse_spectator_window_lock convar?  What is its value?

**Comment by admshao** [comment]
No, i did not change any convar. The current value is 0

2016-09-26 19:36 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
It shouldn't lock if the convar is 0.  If you set it to 1 then does it lock as you expect?

Was it zero on the Windows machine where it locked?

**Comment by admshao** [comment]
I'll try to change the convar next time, I guess the next game is 28 Sep,
18h EDT +-

About the windows machine, I didn't check. Gonna try as well

2016-09-27 2:46 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
Is this still an issue?

**Comment by admshao** [comment]
Hardcoding the window spectate lock convar to 1 did the trick in dotatv
outside lobby.

Unfortunately as PT-BR caster i wasn't able join a lobby of any tournament
so far. This might change this week with esl genting since we got lobby
access. I'll report back.

**Comment by gdrewb-valve** [comment]
I'm going to close for now as it sounds like it's working as expected with the convar.

**Comment by admshao** [comment]
I finally could test today on ESL tournament inside lobby. Manually setting
the window spectate lock convar indeed did the trick.

I would just ask for you to double check if it's being set on all cases and
close this issue.

2016-10-31 17:10 GMT-02:00 Drew Bliss notifications@github.com:
