### ISSUE TITLE
Complements to Valve!

### ISSUE THREAD

**Issue by milovanderlinden** [ValveSoftware/Dota-2#103]
Even though there are bugs, I am very pleased with the new Dota-2-Reborn for in general:
- it runs more smoothly
- starts faster
- closes faster
- doesn't crash when interacting with the desktop so often

On my

Linux 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux

Complements guys! Keep up the good work!

**Comment by gdrewb-valve** [comment]
Thank you!
