### ISSUE TITLE
[MAC OS] Game Constantly Crashing

### ISSUE THREAD

**Issue by Adio1882** [ValveSoftware/Dota-2#1031]
I've been having an issue for the last few months with dota constantly crashing in game, it will crash about once in every 3 games and when it does it's multiple times during the game, I have tried verifying the cache, reinstalling Dota, Clean reinstall of Mac OS and still nothing

My system information is 

>   Model Name: iMac
>   Model Identifier: iMac13,1
>   Processor Name:   Intel Core i5
>   Processor Speed:  2.9 GHz
>   Number of Processors: 1
>   Total Number of Cores:    4
>   L2 Cache (per Core):  256 KB
>   L3 Cache: 6 MB
>   Memory:   8 GB

NVIDIA GeForce GT 650M:

  Chipset Model:    NVIDIA GeForce GT 650M
  Type: GPU
  Bus:  PCIe
  PCIe Lane Width:  x16
  VRAM (Total): 512 MB
  Vendor:   NVIDIA (0x10de)
  Device ID:    0x0fd5
  Revision ID:  0x00a2
  ROM Revision: 3707
  Metal:     #Supported

If there is any other information I can give to help find a solution please let me know.

Edited to show my GPU

**Comment by gdrewb-valve** [comment]
If you look in the Steam system information are there any failure reports with crash IDs?

**Comment by Adio1882** [comment]
> Computer Information:
>     Manufacturer:  Apple
>     Model:  iMac13,1
>     Form Factor: Desktop
>     No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.12.0 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 650M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xfd5
Revision:  0xa2
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.62" x 10.47"  (21.34" diag)
                                        47.3cm x 26.6cm  (54.2cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  953049 Mb
    Largest Free Hard Disk Block:  909643 Mb
    VR Headset: None detected


This is the copy paste of my system infromation from steam, I don't see any errors

**Comment by gdrewb-valve** [comment]
That's unfortunate as it means we have no information on why it's crashing on your system.  It also usually means the crash is in a system component, usually the video driver, but we can't say for sure.

**Comment by Tele42** [comment]
Hello @Adio1882,

This is completely speculative, but you could try nVidia's web driver for Mac and see if you get different results. Apple does not make it easy for this driver to exist by policy and you can use http://www.macvidcards.com/drivers.html to help find a compatible version.

**Comment by Adio1882** [comment]
So I should probably of explained how it crashes, I believe it to be a gpu crash as it has a massively graphical freak out and then crashes, I've installed the Nvidia drivers and the crashes turned from the graphic issues to just freezing and crashing, the only game that I have played that has issues is Dota

**Comment by gdrewb-valve** [comment]
Unfortunately that's much more likely to be NVIDIA's issue than Dota but we'll see if more info can be gathered.

**Comment by Adio1882** [comment]
Damn, hopefully some sort of fix does come out and I can actually play Dota again.

**Comment by gdrewb-valve** [comment]
Did things change with 7.00?
