### ISSUE TITLE
previous matches list showing buggy data in 1v1 matches, and some other issues rehashed

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1032]
it will mix hero models from different matches or show wrong match data for the match including KDA, names (sometimes not showing names at all or just mix from different match), or just not showing any data at all everything will be blank. it stays the same issue when restarting Dota so it is a real issue/bug. it may be server related and not Linux client fault at all but I decided to raise an issue about it anyhow.

about other issues. I still have fps caps at 30 fps and degrading performance over multiple matches maybe due to a memory leak. it gets to the point my computer overheats and Dota crashes midgame and I have to log back into Dota nearly getting an abandon or getting one or we just lose because no one paused the game and they pushed while I was disconnected. I feel like there is a lot of unnecessary things going on in main menu and a lot of game optimizations that need to be made in order to make the problems go away. some of the issues are not as bad as they used to be since Dota reborn first came out with some of the small fixes that were made for lower performance machines but they are still there none the less.

**Comment by ghost** [comment]
3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7520G
OpenGL core profile version string: 4.3.13399 Core Profile Context 15.201.1151
OpenGL core profile shading language version string: 4.40
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.13399 Compatibility Profile Context 15.201.1151
OpenGL shading language version string: 4.40
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:

window manager: KDE

processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 16
model name      : AMD A6-4400M APU with Radeon(tm) HD Graphics
stepping        : 1
microcode       : 0x6001116
cpu MHz         : 1400.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold vmmcall bmi1
bugs            : fxsave_leak
bogomips        : 5389.90
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 16
model name      : AMD A6-4400M APU with Radeon(tm) HD Graphics  
stepping        : 1
microcode       : 0x6001116
cpu MHz         : 1400.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 1
apicid          : 17
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold vmmcall bmi1
bugs            : fxsave_leak
bogomips        : 5389.90
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

**Comment by gdrewb-valve** [comment]
I'm checking with the larger team about the match data.  As for the main menu activity, leaks and perf optimizations those affect all platforms and are being looked at by the larger team, there won't be specific status here.

**Comment by gdrewb-valve** [comment]
The larger team has some ideas on what might be going wrong but no word on when/if a fix will happen.  Closing this out as it's all general and not Linux/OSX specific.
