### ISSUE TITLE
[Linux] Today's update killed the sound

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1033]
hi,
I just got the battle pass update, but apparently that update broke the sound?
Going to tinker a bit with it before I go sleeping.

E 1:
I am using pure alsa, other steam games are not affected by this.
E 2:
In game console logs:
Failed to initialize SDL Audio device!

**Comment by gdrewb-valve** [comment]
It works properly on my Linux system but we took an SDL update so this may be a regression in SDL, assigning to the SDL dev.

**Comment by Turmfalke2** [comment]
Is there any way to increase the log level?

E: any chance that sdl update might have fixed the dbus issue? (tested: it is not)

**Comment by cloudhead** [comment]
Same issue here. It doesn't see any of my devices since the update.

**Comment by rmbleeker** [comment]
For completion, I'm not having any issues.

Running Ubuntu 14.04 LTS on a 4.4 kernel with PulseAudio

**Comment by cloudhead** [comment]
From what I gathered, the issue is ALSA related.

**Comment by ghost** [comment]
I confirm there’s no sound since the last update. Just yesterday when I tested my microphone I could find a lot of devices in the Settings → Audio → Audio → Sound device menu, but now there’s only the ‘Default device’.
My system has pure ALSA.

**Comment by eisenlaub** [comment]
I'm also affected by this issue. My system uses pulseaudio though. I was able to fix it by placing `SDL_AUDIODRIVER="pulse"` in front of the launch options. Hope that helps.

**Comment by Bugattikid2012** [comment]
Can also confirm.  I was using ALSA before this update with the launch setting mentioned above (only set to ALSA obviously), but I had to remove it due to the update.  Works fine with pulse, even though ALSA was set to hand the sound off to Pulse (the reason I was using ALSA was because for whatever reason it removed audio output delay).

**Comment by Turmfalke2** [comment]
Setting SDL_AUDIODRIVE to alsa does nothing for me. While we are it, is there any way to set specific environment variables for each game? I already have to set DBUS_SESSION_BUS_ADDRESS and __GLVND_DISALLOW_PATCHING, if this ends up being another such workaround it would be nice to just use them for dota instead of steam and everything it starts.

**Comment by izmntuk** [comment]
Confirmed soundless with battle pass update on Arch Linux (x86_64), pure ALSA.

Switching to PulseAudio+ALSA for now, which is working fine.  Hopefully this will get fixed from upstream.

**Comment by qantourisc** [comment]
Can confirm it's the SDL update/file, renaming/removing "dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0" fixes this for me.

**Comment by saward** [comment]
Stopped working for me too, but SDL_AUDIODRIVER="pulse" restored sound.  Arch linux.

**Comment by clinew** [comment]
@quantourisc  That hack worked for me, thank you!  Using pure ALSA, no pulse.

**Comment by Tele42** [comment]
This bisects to https://hg.libsdl.org/SDL/rev/9bbe05f2612a as the first bad commit in libSDL2 with my alsa loopback device. Seems like libSDL2 should always enumerate the pcm.!default device for it to work with my setup.

https://hg.libsdl.org/SDL/rev/01b65e6fcf81 does not fix the issue on my system.

**Comment by simisimis** [comment]
I hope this fix will come out soon. It was working so smooth with alsa. Works with pulse as well, but I am getting weirdest sound glitches in game with pulse

**Comment by Tele42** [comment]
Hello @simisimis, I've heard second hand that there is [another unrelated audio issue](https://www.reddit.com/r/DotA2/comments/563z4t/unplayable_audio_glitch/) going on in the game that is potentially cross-platform.

@rcgordon, as a side note, I'm one of those rare (crazy) JACK audio users. Because libSDL2 does not have a JACK backend and the jack plugin for alsa is not serviceable, I'm left with 2 choices for a functional workaround:
libSDL2 -> [(in .asoundrc) !default -> asym -> dmix+dsnoop -> alsa loopback device] -> alsa to jack bridge -> jack
-or-
libSDL2 -> pulseaudio with a config that does not probe real hardware -> JACK

Because I can not use JACK directly, I prefer the alsa loopback device path because it's the lesser technical evil and is consistently reliable.

**Comment by Tele42** [comment]
The following patch fixes alsa sound on my system in Dota 2 with today's upstream libSDL2:

```
--- src/audio/alsa/SDL_alsa_audio.c 2016-10-09 09:38:11.703241851 -0400
+++ src/audio/alsa/SDL_alsa_audio.c.new 2016-10-09 09:41:42.199901117 -0400
@@ -774,11 +774,11 @@
             ALSA_Device *seen = NULL;
             ALSA_Device *prev;
             int i;
-            const char *match = "default:";
+            const char *match = "default";
             size_t match_len = strlen(match);

             /* determine what kind of name to match.  Use "hw:" devices if they
-               exist, otherwise use "default:" */
+               exist, otherwise use "default" */
             for (i = 0; hints[i]; i++) {
                 char *name = ALSA_snd_device_name_get_hint(hints[i], "NAME");
                 if (!name) {
```

Additional note: it appears that hw: is enumerated as sysdefault: on my system.

**Comment by icculus** [comment]
Can I get the output from "aplay -L" from ALSA users hitting this bug?

**Comment by Tele42** [comment]
Sure, here is [my output](https://gist.github.com/Tele42/26fd7ee5291cabc10fc59443ee2256e9). Note: "pcm.mumble" and "pcm.jack" are experiments that are inactive.

**Comment by Turmfalke2** [comment]
For the moment solved/worked around by deleting the shipped sdl.
https://gist.github.com/Turmfalke2/b2fe2a89b8158fc64defb6cd0989b971

**Comment by icculus** [comment]
This is my proposed fix in SDL for this issue:

https://hg.libsdl.org/SDL/rev/84611383c7ef

Passing this around to a few interested parties, so this patch might evolve still. Stay tuned!

**Comment by Tele42** [comment]
@rcgordon, I can confirm that today's build of libSDL2 works with my setup with no audio enumeration abnormalities.

**Comment by Tele42** [comment]
This issue should now be resolved without workaround, please retest and report back.

**Comment by Turmfalke2** [comment]
Sound works using 7e7aa1464fb7a4f4571ed1dba0ad4277  libSDL2-2.0.so.0

**Comment by gdrewb-valve** [comment]
Thanks, closing.
