### ISSUE TITLE
[Linux] Autumn terrain is invisible

### ISSUE THREAD

**Issue by Maxxie** [ValveSoftware/Dota-2#1034]
Seems like autumn terrain is invisible on my debian x64 with mesa 12.0.3 (Other terrains work just fine).
![20161006001651_1](https://cloud.githubusercontent.com/assets/41978/19133920/2ea0a94a-8b5b-11e6-89b2-b2144a08e38c.jpg)

**Comment by gdrewb-valve** [comment]
What GPU are you using?

If you turn off parallax mapping in the video settings does that change anything?

**Comment by AngryPenguinPL** [comment]
Same here.

Im using AMD Radeon HD5650M with Mesa 12.1.

Tomorrow I test it on my PC with HD5850 and Catalyst fglrx driver.

![570_screenshots_20161006011211_1](https://cloud.githubusercontent.com/assets/3121142/19135071/5cf31b50-8b62-11e6-8ed9-8f5d3f809075.jpg)

**Comment by danginsburg** [comment]
OK, it doesn't seem to repro on mesa 10.5.8 Intel Haswell.  I'll have to try it on AMD mesa.  You may want to report this to mesa devs as it could be a driver issue.

**Comment by AngryPenguinPL** [comment]
On AMD Radeon HD5850 with Catalyst 15.9 (fglrx) no issues. Rendering terrain is correct. So look like is bug in Mesa for AMD GPU or for all gpu but only in 12.X branch.

**Comment by danginsburg** [comment]
Actually this is definitely not a bug in mesa, it's an issue with dota.  I remembered last night that on AMD mesa on some GPUs we go down a fallback path for OpenGL implementations with <= 16 texture units per stage.  The new ground parallax shader is using too many textures which is what is causing the bug.  The workaround for now is to disable "Ground Parallax" in the Video Settings.  I'm going to see if I can come up with a fix here.

**Comment by Maxxie** [comment]
Yeah, sorry I forgot the gpu. It's an AMD Radeon HD 6970

**Comment by danginsburg** [comment]
I have a fix for this, it will be in a future Dota 2 update.

**Comment by gdrewb-valve** [comment]
@Maxxie, are you still seeing this problem?

**Comment by gdrewb-valve** [comment]
Presumed fixed, closing.
