### ISSUE TITLE
Pausing a live game: Update delta tick not found

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1036]
Pausing a live game is pretty unreliable in the last few weeks, either disconnecting the spectator session shortly after resumption or spamming the console forever with output similar to the following:

CL:  C_DOTA_ProjectileManager::CreateTrackingProjectile - pSource is NULL without an override loc (handle entity 803)?
Update delta tick <number> not found.

Clicking Go Live immediately cancels the session with "Client Delta Ticks out of order". This used to work just fine. Unfortunately I'm not able to test if this is an issue on other platforms as well.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux unstable (sid) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  LG3D
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 12.0.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x166
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.39" x 7.48"  (15.31" diag)
                                        34.0cm x 19.0cm  (38.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1802

Memory:
    RAM:  7873 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  22064 Mb
    Largest Free Hard Disk Block:  5957 Mb
    VR Headset: None detected

Recent Failure Reports:

This is an issue with STEAM_RUNTIME=0 or 1, so not an issue I've created.

**Comment by gdrewb-valve** [comment]
This affects all platforms and the larger team has been looking.
