### ISSUE TITLE
Catapult models flickering graphical glitch

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1037]
Sometimes, during the whole match, my GPU draws random flickering geometry from the base of the catapult models (only radiant catapult this particular match; will confirm later if it happens with dire catapults too in other matches).

![See screenshot for illustration.](http://i.imgur.com/nJLOC0Z.jpg)

The glitch disappears once the model "sinks" into the ground after the unit dies. 
Restarting the game fixes the issue, until the glitch occurs again for whatever reason (which is not always, and seems to happen from the beginning of the match)
Did not happen on the same machine running Win7 (and slightly older drivers), only in Linux. 

```
Specs: 
Linux Mint 17.3 x64 (Ubuntu 14.04.1 based) i3wm
Kernel 3.19.0-32-generic
CPU: Intel Core2 Quad Q6600 @ 2.40GHz
RAM: 6 GB
GPU: GeForce GTX 560 Ti (MSI Twin Frozr)
GPU driver: nvidia 370.28 (proprietary)
```

Is there a specific console command to reload the models or something? It could be a driver issue and not the game. Sorry for adding noise if that's the case. Just very curious to know what could cause this. Vertex buffer something something?
Also would like to take the opportunity to thank and congratulate all software developers working on this very impressive piece of technology, and impressive support. You are the unsung heroes of our time. Still hoping for a Source2 SDK release too. ;)

**Comment by glubsy** [comment]
I have a strong feeling there is something wrong with my hardware, either RAM or graphics card, or even mother board. I get this glitch quite frequently on different models
I get the following messages in dmesg sometimes, it might be related. 

```
[338940.892037] Corrupted low memory at ffff88000000fff0 (fff0 phys) = 40000000000000
[338940.892043] Corrupted low memory at ffff88000000fff8 (fff8 phys) = 24fc60840020
```

It's just strange it never happened when I was running Windows 7 on the same machine.
You might want to close this now. Sorry for adding noise.

**Comment by gdrewb-valve** [comment]
Thanks for the update, closing.
