### ISSUE TITLE
[MacOS] FPS drops in Desktop Friendly Fullscreen

### ISSUE THREAD

**Issue by jackjen** [ValveSoftware/Dota-2#1039]
I'm finding that since a recent update (a month?) I'm getting a severe FPS drop when moving my mouse around the screen in game.

If pan with up-down-left-right keyboard keys the FPS stay on a solid 45-50 depending on what's on the screen.

If I move the mouse at all (not even edge pan), the FPS drops to 18-19 instantly (Razer Orichi)
If I unplug the mouse and use the touch pad the FPS drops to 24-25 instantly.

Exclusive full screen gives me a solid 55-60 FPS depending on what's on the screen with no FPS drops when moving the mouse.

Like I said, this seems to be a new issue as I've always played with the ability to Cmd-Tab out, but playing in exclusive full screen makes that impossible.

> Hardware Overview:
> 
>   Model Name: MacBook Pro
>   Model Identifier:   MacBookPro11,5
>   Processor Name: Intel Core i7
>   Processor Speed:    2.5 GHz
>   Number of Processors:   1
>   Total Number of Cores:  4
>   L2 Cache (per Core):    256 KB
>   L3 Cache:   6 MB
>   Memory: 16 GB
>   Boot ROM Version:   MBP114.0172.B09
>   SMC Version (system):   2.30f2
>   Serial Number (system): -
>   Hardware UUID:  -
> 
> AMD Radeon R9 M370X:
> 
>   Chipset Model:  AMD Radeon R9 M370X
>   Type:   GPU
>   Bus:    PCIe
>   PCIe Lane Width:    x8
>   VRAM (Total):   2048 MB
>   Vendor: ATI (0x1002)
>   Device ID:  0x6821
>   Revision ID:    0x0083
>   ROM Revision:   113-C5670E-777
>   Automatic Graphics Switching:   Supported
>   gMux Version:   4.0.20 [3.2.8]
>   EFI Driver Version: 01.00.777
>   Metal:  Supported

**Comment by jackjen** [comment]
OK, so I've been sitting on this issue for about a week now trying to figure out which graphics setting caused the issue or if it's a bug, or some software running in the background causing it, only to come to the conclusion that it was a bug in the game.

I was wrong, it was my mouse Accessibility settings. 😨 

Under System Preferences > Accessibility > Display > Cursor Size, I'd dragged the size of the cursor up slightly so I could see it better, which in turn for some reason causes the FPS drops in game only when moving the cursor.

Setting Cursor Size to Normal again has most definitely fixed the issue for me, and now getting a solid 60 FPS in Desktop Friendly Fullscreen. I guess it's a bug, but not a bug? who knows.

**Comment by gdrewb-valve** [comment]
I don't know that we'll be able to establish why the accessibility options affect things but we'll see.

**Comment by gdrewb-valve** [comment]
Our investigations didn't go anywhere, we'd need information from Apple to determine why the system settings have such an effect.  I'd recommend opening a support issue with Apple.
