### ISSUE TITLE
[Linux] Game Fails to Start.

### ISSUE THREAD

**Issue by AriseEVE** [ValveSoftware/Dota-2#104]
Hello, 
Got Dell inspiron 5110 laptop with optiumus intel graphics 3000 + nvidia gt 525m
Game fails to start with nvidia card but works with intel card.
I have bumblebee setup dota 2 runs fine with it.
Os: Arch Linux x64   4.0.6-1 kernel
Using:  nvidia  352.21-1 driver.  
optirun %command% -  launch command. 

Logs:
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198184002245 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198184002245
Setting breakpad minidump AppID = 373300
Fontconfig warning: "/home/eve/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/eve/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x200008
  Serial number of failed request:  99
  Current serial number in output stream:  99
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'librrfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/eve/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150626035324_1.dmp[15087]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150626035324_1.dmp
/home/eve/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 98: 14930 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 14930 
crash_20150626035324_1.dmp[15087]: Finished uploading minidump (out-of-process): success = yes
crash_20150626035324_1.dmp[15087]: response: CrashID=bp-55f86dc6-a1df-4ffa-a9e0-8ff112150625
crash_20150626035324_1.dmp[15087]: file ''/tmp/dumps/crash_20150626035324_1.dmp'', upload yes: ''CrashID=bp-55f86dc6-a1df-4ffa-a9e0-8ff112150625''
pid 15087 != 15086, skipping destruction (fork without exec?)

**Comment by gdrewb-valve** [comment]
This looks like a bad interaction with Bumblebee (the X error is the real problem, the crash is just some bad cleanup code during shutdown).

**Comment by AriseEVE** [comment]
switched to primus as a bridge it works fine, wonder whats the issue with virtualgl.

**Comment by luntik2012** [comment]
still cannot start with ubuntu 15.10 and opensource drivers. yesterday i could run old dota, but with this udpate i cannot play at all

**Comment by gdrewb-valve** [comment]
Is this still active?  One possible source of issues and a suggested workaround are covered in ValveSoftware/steam-for-linux#3506.

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this is a Reborn issue.
