### ISSUE TITLE
Update 2016-10-07 breaks dota 2

### ISSUE THREAD

**Issue by AphidGit** [ValveSoftware/Dota-2#1040]
Updating to the 2016-10-07 patch will not complete for me. 
Message: 

`An error occurred while updating Dota 2 (corrupt update files) :

/[steampath]/steamapps/downloading/570/game/bin/built_from_cl.txt`

Here [steampath] is the steam library installation directory. 

Said file is a tiny 9 byte text file containing a single number. The probability of downloading it wrong or an unrecoverable memory/disk error more than 10 times in a row is vanishingly small.  

Is there some error in the checksumming of this file for linux builds?

**Comment by gdrewb-valve** [comment]
This is a Steam problem and not a Dota problem so this should be in steam-for-linux but we'll see if the Steam team can take a look.

**Comment by melkor217** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/4670

**Comment by gdrewb-valve** [comment]
Closing as the underlying problem in Steam has been identified and is being worked on.
