### ISSUE TITLE
[Linux] Oct 10 2016 breaks replays

### ISSUE THREAD

**Issue by Conzar** [ValveSoftware/Dota-2#1042]
**Summary**
Replays no longer download after the Oct 10th, 2016 update.

**Problem**
Before this patch, I was able to download replays and watch them.  After the patch, after clicking on the download replay button, the button changes and indicates its downloading, but after a minute or so, just resets and reads 'replay' again.  I click on the button and it indicates that its downloading but again the cycle repeats.  So downloading doesn't work.  I don't have any existing replays to try so I am unsure if an already downloaded replay can be viewed.

**System Specs**
- OS: Ubuntu 14.04 LTS
- Steam package version: 1475701795
- CPU: Core i7-4770
- GFX: NVidia Geforce GTX 960
- RAM 16GB
- Disk: 60 GB SSD (dota 2 is installed here for very fast loading times)

**Comment by gdrewb-valve** [comment]
I believe this is happening on all platforms and won't be handled here.

**Comment by Conzar** [comment]
@gdrewb-valve do you have an issue for this ?  I would suggest linking the issue and then close this issue as redundant.

**Comment by gdrewb-valve** [comment]
I meant things like this: https://www.reddit.com/r/DotA2/comments/56w1e8/replays_still_dont_work/

There is no other issue here since this is for Linux-specific bugs.  There is no GitHub for all of Dota, that's the forums at dev.dota2.com where again you can find issues on replays.  I'll check with the larger team tomorrow and close this out based on their feedback.

**Comment by gdrewb-valve** [comment]
Can you get console output for when you're trying to do downloading?  You can see it on a terminal or add -con_logfile to your launch options and grab the console.txt file from 'Dota install'/game

**Comment by Conzar** [comment]
Hum, there is no console output (via the terminal) regarding this issue.  I also noticed that 1 replay I was able to download.  The button for this looked different.  It was a bigger button that read 'download replay'.  While the ones that do not work read 'replay'. 

_Download Replay_
For this button, it just goes through the following status: downloading, uncompressing, and then resolves to watch.  Seems to work.

_Replay_
This button is much smaller than the download replay button.  Note, there is no download replay button.  Its just this one.  When I click on this button, it opens a menu that asks if you want to be notified after the replay has been downloaded.  I click yes.  Then the status reads pending.  Then the button resolves back to replay.  Same process.

Also note, if I click on the popular replays (not my own), than this tends to work.  Like newbee vs LGD.  That worked the same way as the 'Download Replay' button.

**Comment by Conzar** [comment]
I was able to download a replay last night.  So has the recent patch now fixed this issue?

**Comment by gdrewb-valve** [comment]
I didn't hear anything about a specific fix in this area but possibly one went in.  If it continues to work we can close this out.

**Comment by gdrewb-valve** [comment]
No new reports of problems so closing this.
