### ISSUE TITLE
Using Chromium while Dota 2 is running  in the background eventually results in multiple gameoverlayui/render segfaults

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1043]
Observed while browsing in Chromium while Dota is running in the background... within at least two hours or so. No idea. Eventually there are a ton of segfaults in gameoverlayrenderer.so... maybe the gdb output below is just a victim.

The game seems to be fine until I exit... then Steam crashes.

Hopefully this isn't completely useless:
Reading symbols from .steam/ubuntu12_32/gameoverlayui...(no debugging symbols found)...done.
[New LWP 23008]
[New LWP 23007]
[New LWP 23009]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/tod/.steam/ubuntu12_32/gameoverlayui -pid 23003 -manuallyclearframes 0'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf1cf9b1e in ?? () from /home/tod/.steam/ubuntu12_32/chromehtml.so

[Current thread is 1 (Thread 0xf1aacb40 (LWP 23008))]
#0  0xf1cf9b1e in ?? () from /home/tod/.steam/ubuntu12_32/chromehtml.so

No symbol table info available.
#1  0xf1cfd74b in ?? () from /home/tod/.steam/ubuntu12_32/chromehtml.so

No symbol table info available.
#2  0xf1d55ef8 in ?? () from /home/tod/.steam/ubuntu12_32/chromehtml.so

No symbol table info available.
#3  0xf1d4cce7 in ?? () from /home/tod/.steam/ubuntu12_32/chromehtml.so

No symbol table info available.
#4  0xf74f708e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/tod/.steam/ubuntu12_32/libtier0_s.so

No symbol table info available.
#5  0xf74f5714 in ?? () from /home/tod/.steam/ubuntu12_32/libtier0_s.so

No symbol table info available.
#6  0xf74f59b4 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/tod/.steam/ubuntu12_32/libtier0_s.so

No symbol table info available.
#7  0xf74f59fa in CatchAndWriteMiniDumpForVoidPtrFn () from /home/tod/.steam/ubuntu12_32/libtier0_s.so

No symbol table info available.
#8  0xf74f99f3 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/tod/.steam/ubuntu12_32/libtier0_s.so

No symbol table info available.
#9  0xf76d72da in start_thread () from /lib/i386-linux-gnu/libpthread.so.0

No symbol table info available.
#10 0xf76018be in clone () from /lib/i386-linux-gnu/libc.so.6

No symbol table info available.

This is what dmesg spams:
[ 5132.854396] uname[5499]: segfault at 7f9800000000 ip 00007f985a0a4233 sp 00007fff39d1fac0 error 4 in gameoverlayrenderer.so[7f985a09b000+32000]

And one of these, which may be the gdb output above:
[ 5315.175975] steam[22724]: segfault at c ip 00000000f3c51caa sp 00000000ffd1ee80 error 4 in steamui.so[f3907000+1110000]
[ 5316.287055] HTMLController [23008]: segfault at 1a8 ip 00000000f1cf9b1e sp 00000000f1aabf30 error 4 in chromehtml.so[f1ce9000+149000]

In /tmp/dumps assert\* and crash*.dmp are empty files, presumably because Steam crashed so ungracefully.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.11 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.6-grsec+
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  LG3D
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 12.0.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x166
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.39" x 7.48"  (15.31" diag)
                                        34.0cm x 19.0cm  (38.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1802

Memory:
    RAM:  7870 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  22065 Mb
    Largest Free Hard Disk Block:  8179 Mb
    VR Headset: None detected

Recent Failure Reports:

I'm not sure why it says I'm on wheezy, actually using sid.

**Comment by gdrewb-valve** [comment]
Probably some bad interaction with the Steam CEF support, handing off to the Steam folks.

**Comment by ghost** [comment]
I can't reproduce this anymore, but it only happened when the live replays 'tab' was open and updating regularly. Also (sorry), the core dump was due to grsec blocking ptrace so Steam couldn't capture the dump for its log.

It seems the other replay-related bugs have been fixed too after the patch the other day :-). Might we close this?

**Comment by gdrewb-valve** [comment]
Yes, I'll close.
