### ISSUE TITLE
Frequent game freezes.

### ISSUE THREAD

**Issue by FalconOye** [ValveSoftware/Dota-2#1044]
Hi.
I have an issue with the in game freezes. While i'm playing a game, it is freezing so intense with the following console messages:
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
Bailing out of OnBlockForQuery after 0.250 seconds
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
Bailing out of OnBlockForQuery after 0.250 seconds
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
Bailing out of OnBlockForQuery after 0.250 seconds
It is really unplayable, does anyone even know how to resolve that problem? 
Processor: Intel(R) Core(TM)2 Quad CPU Q8400 @ 2.66GHz
Memory: 8 GB 
Graphics: Nvidia GeForce GTS250
OS: Win 7
Temperatures is ok.

**Comment by gdrewb-valve** [comment]
This forum is for bugs that only occur on Linux and Mac.  You'll want to post at dev.dota2.com
