### ISSUE TITLE
Killing pulseaudio while in-game crashes both game and Steam

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1046]
Sometimes I have to do 
`pulseaudio -k` 
to reset my pulseaudio server/daemon because my microphone input doesn't work (after resuming from suspend for example).

Then, going back into the game, I go into options to reset the default audio ouput device (which works). 
**Then, when I bring up the steam overlay and press "Settings", the game crashes, and the Steam client crashes as well.**

Perhaps there is a better way of fixing my pulseaudio issue, but as it stands, bringing the Steam settings  definitely crashes everything.

**Comment by gdrewb-valve** [comment]
Steam issues should go in steam-for-linux, but we'll leave this open for now.

**Comment by Tele42** [comment]
I have a feeling this should be directed at libSDL, I expect it does not know how to recover from a pulseaudio server that has gone away and been replaced with a different instance.

**Comment by gdrewb-valve** [comment]
That's possible but the game settings, which are using SDL, don't crash immediately after the reset.  Instead it's the Steam overlay that ends up crashing and that may be a different kind of issue.

**Comment by glubsy** [comment]
Thanks, indeed this is certainly more Steam overlay/Steam client related. 

And just in case someone is having the same pulseaudio issue with microphone not working after resuming from suspend, a better way to fix it is to switch card profile like this: 
`pactl 'set-card-profile 1 off'`
`pactl 'set-card-profile 1 output:analog-stereo+input:analog-stereo'` 
(I have 2 sound cards so you may want to replace 1 by 0).

**Comment by glubsy** [comment]
Forgot to mention that was on Linux Mint 17.3. Now I'm on Antergos (Arch based) and restarting pulseaudio doesn't crash the game anymore, perhaps because of a more recent version. (also could be because dota is now 7.00)
I do have to select audio channels again of course, but that's to be expected.
