### ISSUE TITLE
[Linux] Right click not registered when left click is pressed at the same time.

### ISSUE THREAD

**Issue by tsoernes** [ValveSoftware/Dota-2#1047]
Right clicking is not registered when left clicking at approximately the same time. The hero does not move and the three arrows pointing to the ground does not show. Works on Windows, same machine, same Dota settings, same mouse.

Linux Mint 18 Cinnamon
Nvidia GTX 770 with 370 drivers running OpenGL

**Comment by gdrewb-valve** [comment]
This works correctly for me on my Linux box, I'm not sure what's going on.

**Comment by admshao** [comment]
I can't tell why...But i had this problem on xfce and cinamon but its just
fine on unity and mutter(my current)

**Comment by tsoernes** [comment]
Maybe it's  Cinnamon then and not Dota itself, is there any way to get an output of what raw input is registered in either Linux or the Dota client? P.S: It's not a laptop so there should be no touchpad(drivers) to mess with anything

**Comment by tsoernes** [comment]
Here we go. In the mouse options for Mint you'll see that clicking left and right mouse-buttons simultaneously simulates middle click, which registers as a virtual mouse device.

[![Screenshot from 2016-10-14 02-48-29.png](https://s17.postimg.org/t2e6gbelr/Screenshot_from_2016_10_14_02_48_29.png)](https://postimg.org/image/h0ism65d7/)

I discovered this by running `xinput` and `xinput test <id>` for the different devices until I found my mouse. Clicking both buttons registered neither but a virtual pointer thing instead.

**Comment by admshao** [comment]
Glad to know that. I might give another shot for xfce
