### ISSUE TITLE
[Linux] Advanced "miscellaneous" options box is misplaced

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1049]
![](http://i.imgur.com/E4Tav90.jpg)

Can't use the "miscellaneous" box as it is misplaced under the Advanced option menu when the resolution is 1280x1024 (in 4:3).
Other resolutions are fine!

Specs: Linux Mint 17.3, i3wm

**Comment by gdrewb-valve** [comment]
This isn't a Linux issue, I've passed this on to the larger team.
