### ISSUE TITLE
[Linux] Fails to Start with Error in Connect() of interface 'GameUI011'!

### ISSUE THREAD

**Issue by HarlemSquirrel** [ValveSoftware/Dota-2#105]
I am running Arch Linux 64-bit with radeonsi open source drivers on a Sapphire R9 270X and AMD FX 8370. When I attempt to start Dota 2 Reborn Beta I get the start animation and I see Dota 2 in my window list on Cinnamon. I can click that to toggle minimization, but after about 30 seconds the game just crashes. In the /tmp/dumps folder is the following in user_stdout.txt. 
https://gist.github.com/HarlemSquirrel/f5a55dd1f5d0e5892075
Of this, I think the most relevant is:

```
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
AppSystemDict: Error in Connect() of interface 'GameUI011'!
Error: LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011'!

```

**Comment by gdrewb-valve** [comment]
This usually means the game is unable to load part of its code, such as #35.  There isn't enough detail in the console messages to say for sure, though.

**Comment by HarlemSquirrel** [comment]
OK, so based on Tele42's comment, I ran `ln -s /usr/lib/libudev.so.1 "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libudev.so.0"` and now I it runs! However, there is a lot of glitching when selecting a hero at the start of a bot match.

**Comment by gdrewb-valve** [comment]
You're likely hitting the graphics issues already reported here.  Closing this since the GameUI issue is resolved.

**Comment by austusross** [comment]
Better to link outside steam directories so cache is not corrupted.  

sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0

**Comment by ghost** [comment]
Thanks @austusross, previous comment helped me

**Comment by firearasi** [comment]
@HarlemSquirrel
Out of so many things only your fix works! Thank

**Comment by vadi2** [comment]
I'm getting this error on one Steam account while another account launches Dota just fine. "sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0" didn't help...

**Comment by maugre** [comment]
I'm on an Arch derivative and installing libudev0 fixed it for me. It's a separate package to libudev1 so that makes sense if Dota depends on the former.

**Comment by RustyRaptor** [comment]
Hey, incase someone is trying to use Vulkan and it's doing this just install the Vulkan support DLC in the properties of the game. k thx
