### ISSUE TITLE
[LINUX] Game freezes for 1-2 seconds, when something appears on the screen 

### ISSUE THREAD

**Issue by B9707C6887CD8B31AB6F62718091A968** [ValveSoftware/Dota-2#1053]
Hello,
I recently installed Gentoo, and I need you help because my game is freezes for 1-2sec, when something appears on the screen, It can be message about bought item, or when enemy cast spell, or I cast spell, it even freezes, when I just try to check enemy's backpack. Game become unplayable, just because it is often. Usually it starts after 10-15 minutes of gameplay.
Previously I used different distro (Arch Linux), and everything was OK with same system hardware. I'm using proprietary driver for my nvidia card, and also I changed running script to be even able start game:
Code:

`__GL_THREADED_OPTIMIZATIONS=0`

So can be there any solutions for my issue? Can I just preload every item icons, and hero spells effects/models? 

I will post any information (config file, commands outupts) you need, just feel free to ask!

**Comment by Tele42** [comment]
Hello @B9707C6887CD8B31AB6F62718091A968, there's a good chance you are using =x11-drivers/nvidia-drivers-361.28, which has a known defective version of libglvnd bundled with it. If that is the case, then either update to a different video driver version, remove libglvnd from the libGL render stack (USE="compat"), or use the `__GLVND_DISALLOW_PATCHING=1` workaround. (from https://github.com/ValveSoftware/csgo-osx-linux/issues/610#issuecomment-224882948)

**Comment by gdrewb-valve** [comment]
If Tele42's guess isn't correct can you post your full system information from Steam?

**Comment by B9707C6887CD8B31AB6F62718091A968** [comment]
Changed according to advice:

```
export __GL_THREADED_OPTIMIZATIONS=1
export __GLVND_DISALLOW_PATCHING=1
```

Game still lagging.

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2801 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.21-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02

Video Card:
    Driver:  NVIDIA Corporation GeForce GTS 450/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.28
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xdc4
    Revision Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 14.80" x 11.85"  (18.94" diag)
                                            37.6cm x 30.1cm  (48.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA Generic

Memory:
    RAM:  7975 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  300324 Mb
    Largest Free Hard Disk Block:  135656 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
