### ISSUE TITLE
[LINUX] Periodic fps drops while in-game

### ISSUE THREAD

**Issue by DuskPiano** [ValveSoftware/Dota-2#1054]
No matter what video settings I use dota drops to exactly 10-12 fps every few minutes and also recovers after some minutes. The game becomes more and laggier during that phase so that the game freezes for some seconds while it keeps showing "fps:10". It only happens while in-game. The CPU usage goes up to around 50% during the fps drop while it's normally at around 20%. Turning V-sync on and off makes no difference.
I also had this problem with Ubuntu 14.04 LTS with Unity DE (now I'm on 16.04 LTS with GNOME).
When I play DotA on my mac partition everything is fine.

System Information:

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 16.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-43-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 12.1.0-devel
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x166
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11,42" x 7,09"  (13,43" diag)
                                        29,0cm x 18,0cm  (34,1cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Cirrus Logic CS4206

Memory:
    RAM:  7889 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  320397 Mb
    Largest Free Hard Disk Block:  139082 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
There are a few similar issues open, such as #934, you might want to take a look at.  They may be totally unrelated but maybe not.

**Comment by DuskPiano** [comment]
My issue isn't connected to the steam overlay. I get the same results with and without it.
I also tried it with intel_pstate=disabled added to my boot parameters as suggested at #934, also no difference.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.

**Comment by ArabianCoconut** [comment]
i found a Increase and less FPS drop.If i uninstall Vulkan on Linux machine, seems like a problem in vulkan or something hindering it. 

Might not work on all Linux Machines but i suggest trying it to remove Vulkan support and play the game it worked for me on Ubuntu 16.10

**Comment by admshao** [comment]
Before 7.00 vulkan was really better then opengl. Now it seems the opengl
is better because vulkan had a regression. Both have 30-50fps drop while
scoreboard is open. Other performance-wise i'm not affected. Fps is the
same as pre 7.00
