### ISSUE TITLE
[LINUX] Unable to add friends in Reborn client.

### ISSUE THREAD

**Issue by sudoforge** [ValveSoftware/Dota-2#1057]
# Overview

I'm no longer able to add friends using any of the contextual menus/buttons in the client. It doesn't matter the method - right click context menu, profile button, etc - I cannot successfully send a friend request. Clicking any of the "add friend" buttons in Dota 2 doesn't send a friend request (or even look like it has successfully sent).
- No, this isn't the initial friend request/accept prevention mechanism. I've been playing for a long time.
- No, I haven't received any bans/mutes/etc that would cause this.
- Yes, hitting the "Add Friend" button that brings up the in-game modal (popup) works.
- Yes, I can accept friend requests in the steam client, but obviously this is less convenient.

This has been an ongoing issue for at least two months.
# System Information

I've included the major things I could think of; please let me know if you need additional information.

``` text
Steam build: Oct 13 2016 at 00:48:25
Steam API: v017
Steam package versions: 1476379980
Dota 2 update: Oct 21st
Dota 2 content BuildId: 1407033
```

``` text
$ lsb_release -a
> LSB Version:  :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
> Distributor ID:   Fedora
> Description:  Fedora release 24 (Twenty Four)
> Release:  24
> Codename: TwentyFour

$ uname -a
> Linux code-1 4.7.7-200.fc24.x86_64 #1 SMP Sat Oct 8 00:21:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ lspci | grep VGA
> 01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)

$ lsmod | grep "kms\|drm"
> nvidia_drm             45056  2
> nvidia_modeset        765952  10 nvidia_drm
> drm_kms_helper        143360  1 nvidia_drm
> drm                   344064  5 drm_kms_helper,nvidia_drm

$ glxinfo | grep -i "vendor\|rendering"
> direct rendering: Yes
> server glx vendor string: NVIDIA Corporation
> client glx vendor string: NVIDIA Corporation
> OpenGL vendor string: NVIDIA Corporation
>     GL_NV_parameter_buffer_object2, GL_NV_path_rendering, 
>     GL_NV_parameter_buffer_object2, GL_NV_path_rendering, 
>     GL_NV_packed_float_linear, GL_NV_path_rendering,
```

**Comment by gdrewb-valve** [comment]
This probably isn't a Linux issue, I'll check with the larger team.

**Comment by sudoforge** [comment]
I appreciate that, @gdrewb-valve. I know of at least two other users who have experienced the same thing.

**Comment by gdrewb-valve** [comment]
Likely unrelated, but just in case:

http://dev.dota2.com/showthread.php?t=270972

**Comment by gdrewb-valve** [comment]
This works properly for me on my Linux box.  Does the Steam overlay work at all?  Can you Shift+Tab to bring up the Steam overlay?

Are you launching the game from within Steam or from a terminal?

**Comment by sudoforge** [comment]
@gdrewb-valve I know the overlay _used_ to work; I think I have disabled it for one reason or another (after this issue first appeared) -- so it's possible that this disabling is the current reason that I cannot add friends in-game. I can check in a few hours and update you here.

I'm launching the game from the Steam client.

**Comment by gdrewb-valve** [comment]
Did you get a chance to check on the overlay?

**Comment by sudoforge** [comment]
@gdrewb-valve Sorry for taking so long to get back to you, haven't had much free time!

Enabling the overlay solves the issue. For future readers, here are the steps necessary to enable the overlay in both the Steam client and in Dota 2:
- Open the Steam client. Click on _Steam -> Settings -> In-Game_.
- Check the box that's labeled _Enable the Steam Overlay while in-game_.
- Press _OK_ at the bottom of the window. This will close the settings window.
- Click _Library_, and right click _Dota 2_. Click _Properties_.
- Check the box that's labeled _Enable the Steam Overlay while in-game_.
- (Re)start Dota 2.

Thanks again for your help, @gdrewb-valve!
