### ISSUE TITLE
[Mac OSX] Command binding doesn't work

### ISSUE THREAD

**Issue by alexchuang72** [ValveSoftware/Dota-2#1058]
The command hotkey binding does not work properly. For example, I would need to hover over a tree to use a tango instead of selecting the tree that I want to tango. Or I would have to hover over the place I want to blink to instead of clicking on the place I want to blink to.

**Comment by gdrewb-valve** [comment]
You mean the Command key by itself, after enabling binding of the Command key, or have you bound something else in conjunction with Command?

**Comment by alexchuang72** [comment]
Hi Drew, I've been using "command + q" for item slot 1 and w,e,a,s,d for items 2-6. It works for items like phase boot because I don't need to select a target. But for items like blink or diffusal blade, i would need to hover my mouse cursor over the target and then do the hot key instead of the other way around. Hope this makes sense.

**Comment by ramma** [comment]
Sounds like quick cast for items got turned on somehow.

**Comment by alexchuang72** [comment]
ramma you're right, i checked the quick cast option and the problem went away. Thanks for the tip.

**Comment by gdrewb-valve** [comment]
Is there an issue remaining or should this be closed?

**Comment by alexchuang72** [comment]
This can be closed, thanks Drew

On Fri, Oct 28, 2016 11:15 AM, Drew Bliss notifications@github.com
wrote:
Is there an issue remaining or should this be closed?
