### ISSUE TITLE
[Linux] Mispositioned gold text on the picking screen

### ISSUE THREAD

**Issue by MaelRL** [ValveSoftware/Dota-2#106]
Hi,

Small issue with the position of the gold (when ticking down) on the picking screen. A screenshot explains it best: 

It happens regardless of the resolution or windowed / fullscreen / etc.

I just noticed it also happens in source 1 dota 2, but I can't find a report in the source 1 tracker so I'm putting it here.

**Comment by gdrewb-valve** [comment]
As this is a long-standing bug and not Linux/Mac specific it's not going to be tracked here.  Unfortunately it's also apparently low priority so I don't know when a fix will be coming from the larger team.
