### ISSUE TITLE
[Linux] Dota2 caused computer to hang randomly

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#1060]
Currently I am unable to play the game anymore, once I launch Dota 2, it will start to freeze/hang my computer completely after a while, I need to do hard reset everytime this happen.

Tested on Vulkan and without it.

OS : Ubuntu 16.04
Graphic : Nvidia GTX 760 TI 
Graphic Driver : 370.28 & 367.57

**Comment by gdrewb-valve** [comment]
Dota by itself can't hang your computer so this isn't directly a Dota issue.  If it isn't hardware It's likely it's a video driver problem, you might want to also contact NVIDIA.

**Comment by rained23** [comment]
I will try the open source driver and other previous version and update about this issue

**Comment by rained23** [comment]
Tested on nouveau , no hang/crash happen just very low fps. 1 - 10 fps No Vulkan.

Tested on nvidia 364.19, Vulkan. Manage to watch 1 game, second game suddenly the game hang, didnt crash my computer.

Driver issue ?

**Comment by admshao** [comment]
Probably Dirver issue. 370.28 proprietary driver is rock solid stable on
vulkan

2016-10-28 14:56 GMT-02:00 rained23 notifications@github.com:

**Comment by gdrewb-valve** [comment]
Closing for now, if you believe there's a Dota issue we can reopen.
