### ISSUE TITLE
[Ubuntu]Can't Zoom Out

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1061]
Hey guys. It's been a while that i've been experiencing this. I can't zoom out in the game.

I made sure the option in main options of the game is Unselected about disable zoom.

And i just tested in a bot match. My scroll foward zooms the game. My scroll backwards just does nothing. I'm stuck on max zoom for the rest of the game. It just happenned that I had to take control of the stream today during Major qualifiers and i had to restart dota to reset the zoom. I can't also zoom out during fights to get a better look. After a couple o restarts i tried to manually use camerazoomin/out in the console and it just worked fine.

What can i do? I was just normal 2-3 weeks ago last time i remeber having to use this feature and i didn't change configs. autoexec or anything.

**Comment by gdrewb-valve** [comment]
Can you post your system info?

**Comment by admshao** [comment]
https://gist.github.com/admshao/8568ee136ae52a6e424623a29258fe5c

2016-10-28 16:15 GMT-02:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
This works properly for me on my Linux box.  If you add -input_message_spew to your launch options and open the console in-game do you see MOUSEWHEEL messages (assuming you're wheeling for scroll) for both directions of scroll?

**Comment by admshao** [comment]
Your assumption is right. I'll try that command later on.

**Comment by admshao** [comment]
Here. I cutted the log to just the mouse input regarding left/right button
and mousewheel. I can provide the  whole 200k lines log file if needed.

https://gist.github.com/admshao/5d9dad7f668169e8be8238aac0bae2c7

2016-10-31 17:10 GMT-02:00 Fabio Madia admshao@gmail.com:

> Your assumption is right. I'll try that command later on.
>

**Comment by admshao** [comment]
Notice that "SDL: got SDL_MOUSEWHEEL" is printed as the same string for
either wheel foward or backwards or up/down dunno the proper way to say it.

2016-11-01 20:52 GMT-02:00 Fabio Madia admshao@gmail.com:

> Here. I cutted the log to just the mouse input regarding left/right button
> and mousewheel. I can provide the  whole 200k lines log file if needed.
> 
> https://gist.github.com/admshao/5d9dad7f668169e8be8238aac0bae2c7
> 
> 2016-10-31 17:10 GMT-02:00 Fabio Madia admshao@gmail.com:
> 
> > Your assumption is right. I'll try that command later on.
> >

**Comment by gdrewb-valve** [comment]
The wheel events are coming in so I'm not sure why things aren't working properly, we'll have to see if we can find a way to repro.

**Comment by admshao** [comment]
This might be related with some king of Bind issues? I tried to "bind '-'
'camerazoomout'" and tested in a bot match. it just works... Then tried the
same hotkey while casting a game with free camera and nothing happened.

2016-11-01 20:59 GMT-02:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
That's possible, although a non-platform issue like that would not get handled here.

**Comment by gdrewb-valve** [comment]
Is this still happening with 7.00?

**Comment by admshao** [comment]
I don't know when i'll be able to test it again. I'm stuck with a windows
box for a while. Probably early january.

I understand if you find out to close this issue due to the 7.00 and delay
to test again.

**Comment by gdrewb-valve** [comment]
I'll close for now, we can always reopen it if you see it again.

**Comment by admshao** [comment]
Out of curiosity. I tested this under windows and i can't zoom out either
once i zoomed in.

 Now i'm fully confused. You saw the input spew console option that the
mousewheel events are normal. So no system/hardware failure. But that bugs
my mind.

Dunno what to say.. Let me know if any other info or procedure is required.

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux issue it won't be handled here.  I'll pass it by the larger team and see if they have any thoughts.

**Comment by admshao** [comment]
I Can't say precisely in which update it fixed for me. But i'm pretty sure it was a week ago or so.
Thx

**Comment by florianstancioiu** [comment]
This still happens even in 2019
