### ISSUE TITLE
[macOS] Too low FPS on NVidia GTX 780M

### ISSUE THREAD

**Issue by icarus-schleg** [ValveSoftware/Dota-2#1062]
Hello. I have already left a message about low macOS performance about a year ago, but nothing was changed.

On the same iMac, Dota 2 runs on 20-30 FPS on macOS and stable 60FPS (vsync) on Windows with the same max graphics settings and same 2560x1440 resolution. It means that I have to use Bootcamp on my Mac to play Dota 2 comfortable. This issue was appeared after some weeks from Reborn Beta launch and still not resolved. May be there is a reason why Valve can't improve performance on macOS?

Thanks and sorry for bad English

**Comment by gdrewb-valve** [comment]
This is a duplicate but holding it open for now.

As with the other open OSX GPU performance issues here we are dependent on Apple to do work on the OSX OpenGL driver.  We have not had any luck in our attempts to engage with them on the issue.

**Comment by icarus-schleg** [comment]
That's very sad. Do you have any possibilites to improve performance in the future? I mean, do you plan to use another API that compatible with macOS?

**Comment by gdrewb-valve** [comment]
If Valve decides to support a new rendering API there'll be some kind of announcement but you'll just have to wait and see if that happens or not.

**Comment by icarus-schleg** [comment]
Thank you for your assistance
