### ISSUE TITLE
Can't download new update

### ISSUE THREAD

**Issue by rudmint** [ValveSoftware/Dota-2#1063]
When I attempt to download today's update I receive this error,

An error occurred while updating Dota 2 (disk write error) : 

/media/steamdrive/steamapps/downloading/570/game/dota/pak01_040.vpk

I've tried validating the install and deleting all local content and reinstalling.  I am getting the same error after each attempt.  Is my hard drive faulty?

System info:

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-42-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.42
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.08" x 11.30"  (23.03" diag)
                                            51.0cm x 28.7cm  (58.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  16006 Mb

**Comment by Tele42** [comment]
@rudmint, no, this is a regression in the 2016-11-01 steam beta client, you should be able to workaround it by opting out of the beta. This issue is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4670 and/or https://github.com/ValveSoftware/steam-for-linux/issues/4686.

**Comment by rudmint** [comment]
I attempted updating again after making this post and it worked without issue.  I did not opt-out of the beta participation.
