### ISSUE TITLE
[Linux] Dashboard-game switch performance is bad

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#1065]
Hi there,

For a couple days/weeks now, the transition between the Dashboard (Menu) and the actual Game gets worse and worse the more games are played sequentially. First game, fine, second game, fine, however, around the 3rd or 4th game, things get tricky.

Either when a match is found, the game freezes for a couple seconds before it shows up the "Accept" button. Usually, I spam the enter key for a while and I'm technically able to enter the game, but it's definitely not responsive for at least 20 seconds.

Or, - which is much more frustrating and has happened to me for the 2nd time now - the game can be accepted, however, the loading takes a relatively really long time, and when it does, it drops me out IMMEDIATELY. The picking has already begun, however, the 5 minute countdown has started, and my time is ticking. I try to load back again, takes a long time, I can see the pickscreen, everyone loaded, then drops me out IMMEDIATELY after loading back, with a "Timed out" message. I had to restart my game so I don't waste any more time, and successfully managed to reconnect with 1 minute still remaining, after the game randomed a hero for me.

The game has constant FPS, nothing fancy, the Dashboard has constant FPS, everything is working fine until one switches to another.

Here's a gist with my system info:
https://gist.github.com/helix42/749ac54d6099c026bbab49fa66f10dbc

**Comment by gdrewb-valve** [comment]
This isn't a platform-specific issue, I've passed it on to the larger team.
