### ISSUE TITLE
Hero selection menu is buggy

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1066]
The Hero selection menu is buggy(graphical bug) when using a 5:4 monitor I'd like to screenshot it but it doesnt work under vulkan.

**Comment by gdrewb-valve** [comment]
This is not a Mac/Linux issue, the larger team will handle it so it won't be tracked here.

**Comment by ghost** [comment]
but this happened under linux.

**Comment by Tele42** [comment]
@nifker, @gdrewb-valve is saying this is a known issue that affects all platforms, so it will be addressed by the larger Dota 2 dev team, not the relatively small group that maintains the mac and linux version.
