### ISSUE TITLE
Having Morphling in the game and someone popping illusions will make FPS drop from 90 to 10

### ISSUE THREAD

**Issue by sakuramboo** [ValveSoftware/Dota-2#1067]
Easily tested in a bot match, select Morphling, play normal, after 25 minutes get manta, pop illusions and watch the FPS plummet.

It gets worse if other bots have manta spawn illusions as well. Waveform and killing the illusions helps but only if you haven't pop manta.

**Comment by gdrewb-valve** [comment]
This isn't specific to Mac/Linux so it's out of the scope of this forum, I'll pass this on to the larger team.
