### ISSUE TITLE
Hero picking phase overlay not covering game screen entirely

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1068]
I have noticed this glitch across several Ubuntu 14.04 systems (Linux Mint 17.3 here).

![Hero picking phase overlay on Linux](http://i.imgur.com/J05XSXg.jpg)

Notice how the bottom of the screen it not covered entirely by the overlay. The mini-map is also interactive, I can ping in it (although team mates don't seem to receive them), and see the green camera view field moving around in the mini-map. 
Don't pay attention to the task bar at the bottom of the screenshot, I forgot to set the game container window into fullscreen, but it's basically the same either way, glitch happens in every window manager I have tried anyway (it's "desktop friendly fullscreen" mode).

SPECS: 
Linux Mint 17.3 x64 (Ubuntu 14.04.1 based) i3wm
Kernel 3.19.0-32-generic (dirty cow! eww!)
CPU: Intel Core2 Quad Q6600 @ 2.40GHz
RAM: 6 GB
GPU: GeForce GTX 560 Ti (MSI Twin Frozr)
GPU driver: nvidia 370.28 (proprietary)

[Steam system info](http://pastebin.com/WNk3NaQT).

Hope this helps. <3

**Comment by danginsburg** [comment]
I suspect this is an issue with 4:3 aspect ratio (running at 1280x1024).

**Comment by ramma** [comment]
It definitely is, which likely means it's not Linux specific.
Interestingly though, the same 1 pixel gap that's on the right of the pick screen in 16:9 aspect is still there in 4:3.

**Comment by glubsy** [comment]
It seems Linux specific to me as I don't recall having had this issue under Windows 7 with the same hardware and resolution. I don't run Windows anymore to test this though, so if anyone is able and willing to test this, please report.

I have tested in **other aspect ratios** and the problem is **not present.** 
However, testing in **4:3 running at any other resolution** (ie 1024x768), there is **no issue** either.
Only 1280x1024 seems to misplace the overlay somehow (setting the resolution on the fly misplaces it to the left too, strangely enough, which also makes the menu button inaccessible, since the whole screen is offset into the void!). 
Running **1280x1024** in **windowed** or **borderless windowed** mode yields the same problem, only the overlay seems to be offset a bit differently and it is resized on-the-fly when resizing the window.

@ramma indeed, that 1 pixel gap has always been there no matter the resolution. Quite intriguing, but not Linux specific that one. ;)

**Comment by Tele42** [comment]
I'm just stating the obvious for a moment, but 1280x1024 is 5:4, not 4:3. The closest 4:3 resolution would be 1280x960.

Maybe (speculatively) an issue with libsdl2's scalar?

**Comment by gdrewb-valve** [comment]
This happens on Windows also so it won't be tracked here.  It's an issue with Dota's handling of 5x4 that the larger team is aware of.

**Comment by glubsy** [comment]
Ah that explains it. I gather that I must have been using the wrong resolution the whole time. :grey_question: 
Anyway, my bad. Thank you! :)
