### ISSUE TITLE
Dota 2 FPS drops on Gnome 3.22

### ISSUE THREAD

**Issue by AlphanumericChars** [ValveSoftware/Dota-2#1070]
I've updated to GNOME 3.22 and since then Dota 2 is suffering FPS drops, input lag for mouse and other annoying stuff such as the mouse pointer moving to the other screen when it reaches the left side.

Is there any way to solve it? Gnome improved a lot this update, it is smoother than never but dota is not good/

**Comment by gdrewb-valve** [comment]
You might have more luck posting on a GNOME forum, but possibly somebody reading this will have advice.

**Comment by BernardoGO** [comment]
I have the same issue. It's probably related to wayland.
Is there a way to make it smoother on xwayland by using any parameter?

**Comment by artemjackson** [comment]
@AlphanumericChars are you using `bumblebee`?

**Comment by BernardoGO** [comment]
@artemjackson I'm using bumblebee.

**Comment by artemjackson** [comment]
@BernardoGO you can try [this](https://wiki.archlinux.org/index.php/bumblebee#Primus_issues_under_compositing_window_managers)
Just add it to launch options like `PRIMUS_SYNC=1 primusrun %command%`

**Comment by gdrewb-valve** [comment]
This sounds more like something on the bumblebee side, is this a Dota issue?
