### ISSUE TITLE
Disconnected from server - Timed out

### ISSUE THREAD

**Issue by ericp1337** [ValveSoftware/Dota-2#1071]
I am running ArchLinux with Gnome 3.22 when loading into a game it will sometimes crash during the loading screen, get disconnected from server during loading screen, or get disconnected/timed out during pick phase. This has been happening for quite a while now and happens both on Vulkan and OpenGL.

[Video](https://youtu.be/fSFNvUWrKNI?t=1m8s)

**Comment by Tele42** [comment]
Hello @computerfr33k, for the crashes, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a gist, then include a link to the gist in this issue report, especially any CrashIDs related to the issue.

**Comment by ericp1337** [comment]
[System Information](https://gist.github.com/computerfr33k/c26be5ce08ea1d60e62296bda51f054a)

I will update this with any crash id's if it crashes again (it's very random).

**Comment by gdrewb-valve** [comment]
This kind of things happens on all platforms so there won't be direct action here.  If you get crash IDs we can look and see if there's anything new popping up.

**Comment by ericp1337** [comment]
Just experience a crash when loading back into a game after being disconnected/timed out.

```
Sun Nov 13 16:03:26 2016 GMT: file "/tmp/dumps/crash_20161113083112_1.dmp", upload yes: "Discarded=1"
```

**Comment by gdrewb-valve** [comment]
If the report was discarded it didn't make it to Valve for us to look. If it has a CrashID we can check it, or if you share the actual dump file.

**Comment by ericp1337** [comment]
[crash_20161113083112_1.zip](https://github.com/ValveSoftware/Dota-2/files/587949/crash_20161113083112_1.zip)

**Comment by gdrewb-valve** [comment]
This is an instance of a problem the larger team is already looking at so there won't be direct status here.

**Comment by gdrewb-valve** [comment]
Does this still happen with 7.00?
