### ISSUE TITLE
[Linux] Steam crashes unexpectedly

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#1076]
Hi there,

So since the last couple days sometimes Steam crashes unexpectedly, therefore freezing the game completely and disconnecting me from the session.

I don't know where to find Steam crash logs (if there's any) or if I'm even posting this on the right board (if not here, where and how should I post this to you?), but this seems like a platform issue?

**Comment by gdrewb-valve** [comment]
The right board would be the steam-for-linux section, which is a peer of Dota-2.  If you run Steam from a terminal you might get some info.  Also if Steam runs long enough to let you go to the Help menu and get the full system information there as you'll need to post that with your report in steam-for-linux.
