### ISSUE TITLE
[Linux] Dota 2 crash in normal match and bot match

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1078]
Hi.

I not playing in dota from one week and now Im starting play again, but I see my dota2 crash often.
When I playing normal match I get few crash in one day (every match or two).
Also today, when I try bot game I have crash in all match.
It also crash when I watch game.

This is crashing dump from last time:
http://www.filedropper.com/crash201611161608441
http://www.filedropper.com/crash201611161402101
http://www.filedropper.com/crash201611101551032

My system steam spec:
https://gist.github.com/xpris/1d36deeb8e62a48b9871069576bfb5c6

Quick info:
Linux Mageia 5 x64, KDE4 + KWIN (composition disabled for fullscreen apps)
Radeon HD5850 with fglrx driver (catalyst 15.9)
4GB RAM
Phenom II X6
Latest Steam stable

**Comment by Tele42** [comment]
Hello @xpris,
First crash dump link is in libscenesystem.so.
Second link is in libscaleformui_4_gl.so (being tracked at #922).
Third link is in steamwebhelper / libcef.

**Comment by gdrewb-valve** [comment]
You'll want to file an issue in steam-for-linux with the steamwebhelper crash.

**Comment by AngryPenguinPL** [comment]
So it is not related to Dota2? Thanks, I report on Steam github.

**Comment by gdrewb-valve** [comment]
One of the three is not related to Dota, the others are.

**Comment by gdrewb-valve** [comment]
Does this still happen with 7.00?
