### ISSUE TITLE
200%+ CPU usage, client completely unresponsive with rendering bugs

### ISSUE THREAD

**Issue by RohanPrabhuNomadly** [ValveSoftware/Dota-2#1079]
This is what my client looks like right now: http://imgur.com/a/NDpMD

And there are other windows over it, because that's just how it is painting, any window on top of it just stays there and the entire client is unresponsive. It takes more than a minute to load and then just stays black for another 2-3 minutes and this is the screen I see after it.

Also, the process is using 2 cores upto 100%. While this does not seem to affect other applications, I simply cannot play Dota 2.. I can't even go to the settings page to try some changes. I have tried reinstalling the client and restarting the machine multiple times (even tried switching between OpenGL/Vulkan renders) and nothing seems to work.

It might help that sometimes the client works, but gives me around 30-40 fps initially (I always used to get 90+ fps on this rig) and then all the textures just seem to disappear and this is how it looks like: http://imgur.com/a/jCPUD

I tried to get a screenshot of `htop`, but I couldn't Alt+Tab till I killed the process, but there were 3 lines with the dota2 binary path (threads maybe), with one of them showing 206% CPU usage and the others around 70-80%.

My system details:

    system         MS-7917 
    bus            Z97 GAMING 5 (MS-7917)
    memory         64KiB BIOS
    processor      Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
    memory         256KiB L1 cache
    memory         1MiB L2 cache
    memory         6MiB L3 cache
    memory         16GiB System Memory
    bridge         4th Gen Core Processor DRAM Controller
    bridge         Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller
    display        GM204 [GeForce GTX 970]
    multimedia     GM204 High Definition Audio Controller

And software:

    OS          Arch Linux (linux 4.8.8)
    Graphics    nvidia-375.20
    Resolution  3840x2160

**Comment by Tele42** [comment]
Hello @RohanPrabhuNomadly, are you able to easily retest with nvidia 375.10? I have heard a rumor that there is one or more regressions in 375.20.

**Comment by RohanPrabhuNomadly** [comment]
Let me try doing a downgrade, it isn't easy.. but not something I haven't done before. Also I did suspect this because this issue started after me upgrading my drivers. I guess, the perils of having a rolling release :(

**Comment by RohanPrabhuNomadly** [comment]
Can confirm that the problem does not persist with `nvidia-375.10`. A downgrade for now works. Looks like nvidia is tracking this as a bug. Hopefully future updates should resolve this issue.
