### ISSUE TITLE
[Linux] Screenshots are completely black (+ Visage effigies)

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#1080]
Hi there,

I just noticed that the screenshot I took on 18th Nov (CET time) is completely black. I wanted to take a picture of my Visage effigy which lost its bodyparts since his model has been broken down. (The effigy only shows the "body" which is the blue-ish effect thing by default.)

Today I wanted to take a screenshot and noticed it was black on the popup notification. I took another and it was black as well. Now I checked the hard drive folder and the pictures are indeed completely black.

Here's a Gist with the Sysinfo: https://gist.github.com/helix42/749ac54d6099c026bbab49fa66f10dbc

The effigy thing is not platform-specific, though, my friend who uses Windows also sees it "naked".

**Comment by Plagman** [comment]
Was the screenshot broken in Vulkan or regular OpenGL mode?

**Comment by u00101010** [comment]
It was in Vulkan mode.

**Comment by Tele42** [comment]
Related to https://github.com/ValveSoftware/Dota-2-Vulkan/issues/141.

**Comment by gdrewb-valve** [comment]
Closing in favor of the Dota-2-Vulkan issue as this is a Vulkan problem and not a Dota problem.
