### ISSUE TITLE
CDN IP geolocation is significantly wrong

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1082]
I live in Paris where I play dota from 2 lines (VDSL and ADSL) at different places in the city. My IAP is Free SAS (IPv4 and native IPv6) on both lines and I'm localized in other cities far away in France (Rennes and Bezier!).
When I'm localized in Bezier, I got even the wrong steam download location (Marseilles) which I needed to manually override to Paris.

Then I'm suspicious I get routed to the wrong "far" servers, because 20 ms is an eternity network wise:
When localized in Rennes (with Parisian VDSL line), France, I get ~30 ms ping on dota servers.
When localized in Bezier (near Marseilles)(with Parisian ADSL line), France, I get ~50 ms ping on dota (and ~45 ms in the middle of the night).

A Parisian friend of mine, using FTTH from Bouygue Telecom IAP, is properly IP geolocalized in Paris and get ~20 ms ping on dota servers.

**Comment by gdrewb-valve** [comment]
This isn't Linux-specific so I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team commented that the server selection is based purely on ping, not geolocation, so any geolocation oddities won't affect server selection.

**Comment by sylware** [comment]
On Sun, Dec 04, 2016 at 09:45:25AM -0800, Drew Bliss wrote:
> The larger team commented that the server selection is based purely on ping,
> not geolocation, so any geolocation oddities won't affect server selection.

It would mean I ping Marseille servers better than Paris servers?? WOW!

Either somethings are not clean on my internet access lines or there is
something quite defective with Free SAS IAP and dota2 servers.

So it's expected I get almost the same ping on West EU than East EU?

**Comment by gdrewb-valve** [comment]
No idea, they didn't provide any more details.

**Comment by DyXel** [comment]
> It would mean I ping Marseille servers better than Paris servers?? WOW!

This always happen, i live on a South American country and i get better ping on US East servers even thought that i am more close to the South American servers; Is like black magic, you never know how exactly it works...

You should do further testing with other servers that are near you and if you find an oddity report it to your ISP, this has nothing to do with the Dota 2 servers, i believe.

**Comment by sylware** [comment]
On Sun, Dec 04, 2016 at 02:18:17PM -0800, Dylam De La Torre wrote:
> This always happen, i live on South America country and i get better ping on
> US East servers even that i am more close to the South America servers; Is
> like black magic, you never know how exactly it works...
> 
> You should do further testing with other servers that are near you and if you
> find an oddity report it to your ISP, this has nothing to do with the Dota 2
> servers, i believe.

Indeed, I do believe that dota servers are not in cause. I do believe indeed
that my IAP, Free SAS, may have something wrong on the lines I use. I'll ask
other dota players in Paris with the same IAP to know how much ping they have
on west EU servers, that to know if it's a global pb with Free SAS or specific
to the lines are used.

There are also the steam download servers, Marseille was selected, which I had
to override to Paris. It would mean I have a better ping to Marseille than in
Paris, which is just, _extremely_ wrong.

I have already ~20 ms ping difference between the 2 lines I use, which is huge
network wise.

-- 
Sylvain
