### ISSUE TITLE
[MacOS] Crash when trying to watch tournament games during picks and bans 

### ISSUE THREAD

**Issue by Najadorel** [ValveSoftware/Dota-2#1083]
If I try to watch a game from tournaments during picks and bans the game just crash and keeps crashing until the last 4 picks and bans.  I have witness this behaviour in the WESG, DreamLeague, The Summit and currently on the Boston Mayor

 

  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Memory:	16 GB

**Comment by Tele42** [comment]
Duplicate of #922.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
