### ISSUE TITLE
Failed to create Opengl context

### ISSUE THREAD

**Issue by G4brym** [ValveSoftware/Dota-2#1086]
I can run dota 2 on linux, it gives this error "Failed to create opengl context", but on windows it runs just fine.
I tryed running dota and steam on the terminal and got this message

`Attempting to create OpenGL context: v3.3 (Core profile)...failed.
Attempting to create OpenGL context: v3.1 (Core profile)...failed.`

My computer is a i5 480m, and im running the cpu integrated graphic card (intel hd graphics)
With linuxmint 18.

**Comment by Tele42** [comment]
Hello @G4brym, this is a long standing steam runtime compatibility issue with mesa where one or more libraries in the steam runtime are too old to be used with mesa. One of the workarounds on https://github.com/ValveSoftware/steam-runtime/issues/13 should work for you.

**Comment by Tele42** [comment]
(Previous comment removed)
Hello @G4brym, your i5 480m is part of the [Ironlake generation](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Fifth_generation) of intel graphics. It does not support OpenGL 3, which is required for Dota 2 on linux.

**Comment by gdrewb-valve** [comment]
@G4brym, Linux OpenGL drivers often do not have the same levels of support as their Windows counterparts.

As Tele42 mentions Dota requires OpenGL 3 so it won't run on your system under Linux.
