### ISSUE TITLE
Cannot join a game

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1087]
When I press ‘PLAY DOTA’ button, eventually a window to accept match popups, I press ‘ACCEPT’ and then see one of the random wallpapers, which are shown before the menu loads. Except that now it doesn’t load – I continue to see the wallpaper and then I am forcefully returned to main menu and cannot neither reconnect not join a new game, because the client thinks I have abandoned previous game. What the hell? Tried three times – first time the client froze while I switched to another desktop. The second time I didn’t switch workspaces, and the client ‘unhanged’ to main menu and got me blocked for two minutes. I have closed dota, closed steam and started them again. The third and the last time I got blocked again, for 17 minutes. 

Also I found strange, that I can see my profile stats in the main menu, but not the latest match details. Though I can see all recent games if I click on the corresponding button. And there’s no red stripe on the top saying about bad connection, inability to connect to local game coordinator or such.

OS: Gentoo ~amd64
x11-drivers/nvidia-drivers-367.27

**Comment by gdrewb-valve** [comment]
Very unlikely to be Linux-specific.  The whole team is going to be working through things for 7.00 and this'll get checked out.

**Comment by gdrewb-valve** [comment]
Does this still happen with 7.00?

**Comment by ghost** [comment]
No, it’s not.
