### ISSUE TITLE
[OSX] New query menu shows black models as overlays.

### ISSUE THREAD

**Issue by milot-mirdita** [ValveSoftware/Dota-2#1089]
This happens in the 7.00 test client:

New query menu shows huge pitch black models as a overlays. 
The dark models are gone when I enable the legacy query menu.

Images: http://imgur.com/a/F1Kss

Sadly I don't have a linux or windows machine here to see if the same issue also happens on other platforms.

The steam hardware information output follows:

```
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro11,1
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2400 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    MacOS 10.11.6 (64 bit)
    
Video Card:
    Driver:  Intel Iris

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xa2e
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.26" x 7.05"  (13.27" diag)
                                            28.6cm x 17.9cm  (33.7cm diag)
    Primary VRAM: 0 MB
    
Memory:
    RAM:  16384 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  238198 Mb
    Largest Free Hard Disk Block:  22733 Mb
    VR Headset: None detected
```

Edit: Apparently someone else had this issue on the dev forum: http://dev.dota2.com/showthread.php?t=273857

**Comment by gdrewb-valve** [comment]
I'm not able to repro on my Mac.  Does this happen with any structure?  Does it happen in any game mode (hero demo, bot match, etc.)?

**Comment by milot-mirdita** [comment]
I tried it in hero demo mode and in a bot match. Make sure that the legacy query view is not enabled. Only happens in the new one.

Also I am using a Macbook without a dedicated GPU (Intel Iris). Maybe it works alright if you have a real GPU?

**Comment by gdrewb-valve** [comment]
The new panel is working correctly for me, with a properly rendered image of the unit at the left of the panel.  We'll see if we can find a repro.

**Comment by milot-mirdita** [comment]
Can I do anything to help debug the issue? I captured an opengl trace using apitrace:
https://mega.nz/#!ossgBIwK!XtAge7XwMN_1LyOtQNX6o4wnjU9MAkYaK8Ho4sE9T7I
Can't replay it on my mac however. Any other ideas?

**Comment by gdrewb-valve** [comment]
I think it's going to need a repro at Valve to track down the cause.  I believe we're close to getting that, though, so hopefully you don't need to do anything further.

**Comment by danginsburg** [comment]
I have this reproduced and am working on a fix.

**Comment by danginsburg** [comment]
I have fixed this bug, it will be fixed in an upcoming update.

**Comment by anko** [comment]
I also see what I suspect is the same bug on Linux in the now-live 7.00 client, both in the menus and when some objects or heroes are selected and shown in the new unit query panel.

For example, here I clicked the fountain:

![1481594070](https://cloud.githubusercontent.com/assets/5231746/21124519/bab01c0e-c0df-11e6-998e-0d598939db17.png)

It goes away when the panel closes.

Eagerly awaiting [that upcoming update](https://github.com/ValveSoftware/Dota-2/issues/1089#issuecomment-266609441). For anyone too hyped to wait, or who is seeing this for some other reason in the future, a workaround for this in-game issue is to tick *Unit query overrides hero control console* in the options so the unit query panel is not used.

**Comment by danginsburg** [comment]
You should also be able to work around it by turning on Shadows in the video settings.  Fix should ship soon though.

**Comment by anko** [comment]
@danginsburg That works better. Thanks!

**Comment by gdrewb-valve** [comment]
This should be fixed now, are you still seeing problems?

**Comment by milot-mirdita** [comment]
Thanks a lot!

**Comment by anko** [comment]
Confirming fully fixed for me too. Thank you! :sparkles:
