### ISSUE TITLE
[Mac] Aspect ratio selectors have wrong values

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#109]
I have a 15 inch retina MBP machine.

Problem 1:
The 16:9 option, rather than having 16:9 resolutions, actually has a combined list from 16:10 and 4:3.

![screenshot 2015-06-25 21 38 41](https://cloud.githubusercontent.com/assets/5674597/8370822/b44afe5a-1b82-11e5-8369-dc19b76759d4.png)
![screenshot 2015-06-25 21 38 45](https://cloud.githubusercontent.com/assets/5674597/8370821/b449bb12-1b82-11e5-9105-6f47dcf61906.png)
![screenshot 2015-06-25 21 38 49](https://cloud.githubusercontent.com/assets/5674597/8370823/b44bacb0-1b82-11e5-94ed-c73403ba9ebe.png)

Problem 2:
16:10 selector has different values under fullscreen and windowed modes.
Repro step: at fullscreen mode select 16:10 selector, change the display mode to windowed. Now the selector values are still the same, we need to switch to 16:9 and back to 16:10 to "refresh" it (which I believe is another bug). Then we can only see 1440*900 or smaller ones. 
![screenshot 2015-06-25 21 47 45](https://cloud.githubusercontent.com/assets/5674597/8370899/e09274ce-1b83-11e5-82f8-807870ebb482.png)
![screenshot 2015-06-25 21 47 59](https://cloud.githubusercontent.com/assets/5674597/8370900/e0930e2a-1b83-11e5-8052-2d2dc05f3deb.png)

**Comment by gdrewb-valve** [comment]
I know you have a separate issue open on more resolution problems but is this addressed after the 6/26 update?

**Comment by SsnL** [comment]
The problem is still there after the 6/26 update.

**Comment by gdrewb-valve** [comment]
Both problem 1 and 2?  Problem 2 should be fixed.

**Comment by SsnL** [comment]
Actually I still can only see resolution above 1440x900 under fullscreen mode. Borderless window & window still have 1440x900 and below.

**Comment by gdrewb-valve** [comment]
Is your desktop at 1440x900 scaled?  Then what you're seeing is correct, window sizes are clamped to your desktop resolution.

**Comment by SsnL** [comment]
Yes. Okay, i see. Thanks! :D

**Comment by gdrewb-valve** [comment]
Which parts of this are still active, then?

**Comment by SsnL** [comment]
Problem 1

**Comment by gdrewb-valve** [comment]
Just to be clear nothing about problem #1 has changed?  With fullscreen selected you still see both 4x3 and 16x10 resolutions?  That shouldn't be possible after the code changes that went in but maybe something else is broken.

**Comment by SsnL** [comment]
Just checked. It actually changed. Now selecting the 16:9 won't change any value in the selector. If I had 4:3 before, I would see 4:3 values. If I had 16:10 before, I would see 16:10 values.

**Comment by gdrewb-valve** [comment]
OK, that makes more sense.  There aren't any 16x9 resolutions supported so the list should be empty (or we disable 16x9), that's easy to fix.

**Comment by SsnL** [comment]
Great! Thanks.

**Comment by gdrewb-valve** [comment]
The next release will indicate when there are no supported resolutions for an aspect ratio.

**Comment by gdrewb-valve** [comment]
Can you try the 6/30 update?

**Comment by SsnL** [comment]
With the 6/30 update, fullscreen works fine. But borderless window and window have some new problems:
![screenshot 2015-06-30 22 35 59](https://cloud.githubusercontent.com/assets/5674597/8448149/967309f0-1f78-11e5-969a-dc13a794251e.png)
![screenshot 2015-06-30 22 36 05](https://cloud.githubusercontent.com/assets/5674597/8448150/9826cb10-1f78-11e5-8d4a-555e084c94a5.png)

**Comment by gdrewb-valve** [comment]
That's expected as the windowed modes will give approximate aspect ratio matches when there are no exact matches.  You don't have any 16x9 so it gives you the 16x10 and 4x3 options.  The 16x10 display looks correct.

**Comment by SsnL** [comment]
I see. Thanks!
