### ISSUE TITLE
[Linux] - Game fails to start after flashing a black screen

### ISSUE THREAD

**Issue by ualvesdias** [ValveSoftware/Dota-2#1091]
Hi! After looking for a possible solution here and in the internet in general, I decided to open this issue... After the last update (I think), My Dota 2 client fails to start. It just blinks a blackscreen for less than a second and then returns to Steam. I have already set the -con_logfile option as you can see below. I don't know if you guys will be able to help me because my OS is Fedora 25 and I know that it isn't officially supported. But I always played this game in Fedora with zero problems. I use the default graphics driver that comes with Fedora. Below are my system specs and the content of console.log generated by the -con_logfile option.

System config:

H/W path                 Device      Class       Description
============================================================
                                     system      GA-970A-UD3
/0                                   bus         GA-970A-UD3
/0/0                                 memory      128KiB BIOS
/0/4                                 processor   AMD Phenom(tm) II X4 965 Processor
/0/4/a                               memory      128KiB L1 cache
/0/4/c                               memory      512KiB L3 cache
/0/b                                 memory      128KiB L1 cache
/0/29                                memory      24GiB System Memory
/0/29/0                              memory      8GiB DIMM 1600 MHz (0,6 ns)
/0/29/1                              memory      8GiB DIMM 1600 MHz (0,6 ns)
/0/29/2                              memory      4GiB DIMM 1600 MHz (0,6 ns)
/0/29/3                              memory      4GiB DIMM 1600 MHz (0,6 ns)
/0/100                               bridge      RD9x0/RX980 Host Bridge
/0/100/4                             bridge      RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0)
/0/100/4/0                           bus         EJ168 USB 3.0 Host Controller
/0/100/4/0/0             usb8        bus         xHCI Host Controller
/0/100/4/0/1             usb9        bus         xHCI Host Controller
/0/100/5                             bridge      RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1)
/0/100/5/0                           multimedia  Sound Core3D [Sound Blaster Recon3D / Z-Series]
/0/100/9                             bridge      RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 4)
/0/100/9/0               enp3s0      network     RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
/0/100/a                             bridge      RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 5)
/0/100/a/0                           bus         EJ168 USB 3.0 Host Controller
/0/100/a/0/0             usb10       bus         xHCI Host Controller
/0/100/a/0/1             usb11       bus         xHCI Host Controller
/0/100/11                            storage     SB7x0/SB8x0/SB9x0 SATA Controller [IDE mode]
/0/100/12                            bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
/0/100/12/1              usb4        bus         OHCI PCI host controller
/0/100/12/1/1                        input       Keyboard
/0/100/12/1/2                        input       Gaming Mouse
/0/100/12.2                          bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
/0/100/12.2/1            usb1        bus         EHCI Host Controller
/0/100/13                            bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
/0/100/13/1              usb5        bus         OHCI PCI host controller
/0/100/13.2                          bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
/0/100/13.2/1            usb2        bus         EHCI Host Controller
/0/100/14                            bus         SBx00 SMBus Controller
/0/100/14.1                          storage     SB7x0/SB8x0/SB9x0 IDE Controller
/0/100/14.3                          bridge      SB7x0/SB8x0/SB9x0 LPC host controller
/0/100/14.4                          bridge      SBx00 PCI to PCI Bridge
/0/100/14.5                          bus         SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
/0/100/14.5/1            usb6        bus         OHCI PCI host controller
/0/100/15                            bridge      SB700/SB800/SB900 PCI to PCI bridge (PCIE port 0)
/0/100/15/0                          display     Barts XT [Radeon HD 6870]
/0/100/15/0.1                        multimedia  Barts HDMI Audio [Radeon HD 6790/6850/6870 / 7720 OEM]
/0/100/16                            bus         SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
/0/100/16/1              usb7        bus         OHCI PCI host controller
/0/100/16/1/2                        input       ROCCAT Kave Headset
/0/100/16.2                          bus         SB7x0/SB8x0/SB9x0 USB EHCI Controller
/0/100/16.2/1            usb3        bus         EHCI Host Controller
/0/100/16.2/1/1                      multimedia  Webcam C270
/0/100/16.2/1/3          scsi6       storage     Expansion Desk
/0/100/16.2/1/3/0.0.0    /dev/sdc    disk        2TB Expansion Desk
/0/100/16.2/1/3/0.0.0/1  /dev/sdc1   volume      1863GiB Windows NTFS volume
/0/101                               bridge      Family 10h Processor HyperTransport Configuration
/0/102                               bridge      Family 10h Processor Address Map
/0/103                               bridge      Family 10h Processor DRAM Controller
/0/104                               bridge      Family 10h Processor Miscellaneous Control
/0/105                               bridge      Family 10h Processor Link Control
/0/1                     scsi0       storage     
/0/1/0.0.0               /dev/sda    disk        1TB ST31000524AS
/0/1/0.0.0/1             /dev/sda1   volume      931GiB Windows NTFS volume
/0/2                     scsi1       storage     
/0/2/0.0.0               /dev/cdrom  disk        BD-RE  WH16NS40
/0/3                     scsi2       storage     
/0/3/0.0.0               /dev/sdb    disk        240GB KINGSTON SUV400S
/0/3/0.0.0/1             /dev/sdb1   volume      290MiB EXT4 volume
/0/3/0.0.0/2             /dev/sdb2   volume      223GiB Linux LVM Physical Volume partition
/1                       virbr0      network     Ethernet interface
/2                       virbr0-nic  network     Ethernet interface

CPU info:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 4
Model name:            AMD Phenom(tm) II X4 965 Processor
Stepping:              3
CPU MHz:               800.000
CPU max MHz:           3400,0000
CPU min MHz:           800,0000
BogoMIPS:              6845.45
Virtualization:        AMD-V
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid eagerfpu pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save

lspci output:

00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02)
00:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 0)
00:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 1)
00:09.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 4)
00:0a.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD890/RD9x0/RX980 PCI to PCI bridge (PCI Express GPP Port 5)
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 SATA Controller [IDE mode] (rev 40)
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:12.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:13.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 SMBus Controller (rev 42)
00:14.1 IDE interface: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 IDE Controller (rev 40)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 LPC host controller (rev 40)
00:14.4 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 PCI to PCI Bridge (rev 40)
00:14.5 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI2 Controller
00:15.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] SB700/SB800/SB900 PCI to PCI bridge (PCIE port 0)
00:16.0 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB OHCI0 Controller
00:16.2 USB controller: Advanced Micro Devices, Inc. [AMD/ATI] SB7x0/SB8x0/SB9x0 USB EHCI Controller
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor HyperTransport Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Miscellaneous Control
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 10h Processor Link Control
01:00.0 USB controller: Etron Technology, Inc. EJ168 USB 3.0 Host Controller (rev 01)
02:00.0 Audio device: Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
04:00.0 USB controller: Etron Technology, Inc. EJ168 USB 3.0 Host Controller (rev 01)
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barts XT [Radeon HD 6870]
06:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Barts HDMI Audio [Radeon HD 6790/6850/6870 / 7720 OEM]

Content of the console.log:

GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 1048576, Total Avail: 2094968, Current Avail: 1048424
Forcing SM30 shaders to workaround mesa bug with sampler bindings > 16.
CreateDevice: Requested DX level 110, clamped to DX level 95
Loaded video settings config from 'cfg/video.txt'
Unable to open GL shader cache TOC /home/odysseus/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/shadercache/gl/shaders.toc file - might not exist yet.
ERROR: HangWatchdogInternal_BeginScope() - Hang watchdog not implemented for this platform!
ERROR: HangWatchdogInternal_EndScope() - Hang watchdog not implemented for this platform!

If I'm missing som info, please let me know! Or if I did something wrong. Thank you!

**Comment by ualvesdias** [comment]
Oh, forgot the output of the ./dota.sh...

Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198041833410 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198041833410
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD BARTS (DRM 2.46.0 / 4.8.12-300.fc25.x86_64, LLVM 3.8.0)
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30
crash_20161212195606_1.dmp[25579]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161212195606_1.dmp
./dota.sh: line 104: 25567 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
[my-user@my-pc game]$ crash_20161212195606_1.dmp[25579]: Finished uploading minidump (out-of-process): success = yes
crash_20161212195606_1.dmp[25579]: response: Discarded=1
crash_20161212195606_1.dmp[25579]: file ''/tmp/dumps/crash_20161212195606_1.dmp'', upload yes: ''Discarded=1''

**Comment by gdrewb-valve** [comment]
Likely a Steam runtime issue and not a Dota issue.  See also #1084.

**Comment by ualvesdias** [comment]
Thank you so much for the quick reply! I'll try to downgrade mesa... If it doesn't work, I'm gonna try the workarround in https://bodhi.fedoraproject.org/updates/FEDORA-2016-70e10c3a84

**Comment by ualvesdias** [comment]
I can start DotA2 now, after downgrading mesa drivers... I'll follow the fedora update link until a proper update comes up. Thank you so much for the help!

**Comment by gdrewb-valve** [comment]
Thanks, closing.
