### ISSUE TITLE
Linux crash in NVIDIA driver using Vulkan

### ISSUE THREAD

**Issue by ryan33020** [ValveSoftware/Dota-2#1092]
The latest patch from a couple hours ago crashes after game launch and reconnecting.
It ran without issues on the updates earler today.

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Opteron(tm) Processor 4274 HE              
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  1gbs
    
Operating System Version:
    "Fedora release 24 (Twenty Four)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.12-200.fc24.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11804000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.20
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 75 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 13.39" x 10.63"  (17.09" diag)
                                            34.0cm x 27.0cm  (43.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: CMI8786
    
Memory:
    RAM:  32238 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  1408218 Mb
    Largest Free Hard Disk Block:  741638 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Tue Dec 13 03:31:08 2016 GMT: file ''/tmp/dumps/crash_20161212213003_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 03:44:53 2016 GMT: file ''/tmp/dumps/crash_20161212213143_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:05:54 2016 GMT: file ''/tmp/dumps/crash_20161212225920_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:06:50 2016 GMT: file ''/tmp/dumps/crash_20161212230612_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:08:19 2016 GMT: file ''/tmp/dumps/crash_20161212230705_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:09:05 2016 GMT: file ''/tmp/dumps/crash_20161212230837_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:10:24 2016 GMT: file ''/tmp/dumps/crash_20161212230957_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:11:44 2016 GMT: file ''/tmp/dumps/crash_20161212231116_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:16:40 2016 GMT: file ''/tmp/dumps/crash_20161212231400_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:17:24 2016 GMT: file ''/tmp/dumps/crash_20161212231656_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:18:14 2016 GMT: file ''/tmp/dumps/crash_20161212231747_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:20:15 2016 GMT: file ''/tmp/dumps/crash_20161212231852_1.dmp'', upload yes: ''Discarded=1''
    Tue Dec 13 05:22:18 2016 GMT: file ''/tmp/dumps/crash_20161212232142_1.dmp'', upload yes: ''Discarded=1''
    

[crash_20161212213143_1.txt](https://github.com/ValveSoftware/Dota-2/files/648086/crash_20161212213143_1.txt)

**Comment by gdrewb-valve** [comment]
Your crash is inside of the NVIDIA 375.20 driver and may be related to using Vulkan.  Do things still crash if you don't use Vulkan?

**Comment by ryan33020** [comment]
Was able to complete a game again disabling Vulkan.  Thank you.

**Comment by ryan33020** [comment]
May have spoken too soon, OpenGL got me through a couple games with ok performance, averaged about 20fps.  It just got another dota update and the crashing started again.  It did not generate a full dump.   Will see if I can get it to dump tomorrow if it will help after full restart of steam and the system.

[stdout.txt](https://github.com/ValveSoftware/Dota-2/files/650984/stdout.txt)

**Comment by gdrewb-valve** [comment]
The latest update broke Linux for everybody so you're not alone.

**Comment by regs01** [comment]
Same on Windows. Not always a Nvidia driver crash. Sometimes game just exists to desktop. But there are also regular Nvidia driver crashes after 7.0 update.

**Comment by kisak-valve** [comment]
Hello @ryan33020, does this issue occur with a different nvidia driver version (375.26 or 375.10)?

**Comment by ryan33020** [comment]
375.26 is working at the moment

**Comment by kisak-valve** [comment]
Thanks for retesting @ryan33020. If you experience this issue again (not with 375.20), please include a CrashID or a minidump (.dmp) of the crash and we can look into this further.
