### ISSUE TITLE
Very low fps after 7.00 update - help?

### ISSUE THREAD

**Issue by kunalex** [ValveSoftware/Dota-2#1093]
Hello,

Everyone knows that Dota2 sucks on a OS device. Now it is worse. Don t know why though, Valve is racist against us. Valve, it is 2016, soon 2017. Can we fix the game for every platform.. please?

In the last few months I have been playing dota2 on my macbook pro with all the setting to low, and quality to 80. I managed to get a constant 45-55 fps. Even in heavy fights.

Now, after the 7.00 update, I get constant 35-40 fps laning and in the fight.. 25 fps. And now I am low setting full on.

This is shit. With the specs of a Macbook, it is a shame and I think Valve is discriminating OS users. We can t play like this. 

Please, respect us enough to get a workaround or something. I don t want to bootcamp Windows. I want to play on my macbook, with lots of specs, at least on low, your game. Please, respect our time and money invested in your game.

Please, respect us. This is unacceptable.

Thank you,

..for nothing.

**Comment by sylware** [comment]
Same on linux based OSes. Severe performance loss (15 ~ 20 fps).
Need cache memory local and assembly code optimization?

**Comment by gdrewb-valve** [comment]
Performance on 7.00 is an issue across all platforms and will be handled by the larger team.  Leaving open #1101 for status.
