### ISSUE TITLE
[700] holding alt does not show hero stats

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1095]
Holding alt does not show the hero stats in the hero panel (smart double tap or not).

**Comment by gdrewb-valve** [comment]
You'll want to post this at dev.dota2.com

**Comment by sylware** [comment]
It's a bug. When you hover the cursor above the attack/armor/speed value (above the inventory), the popup window tells you to hold alt to show the stats (strenght, agility, intel), that it does not.

**Comment by sylware** [comment]
it's fixed in last update
