### ISSUE TITLE
Incorrect update files

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1098]
Hi.

I can't download new 7.00 update to Dota 2 on Linux.

Every times when I trying updating it, steam download 5.8 GB and every time after downloading I get error: Incorrect update files and I need to start download it again and again and again...

Is any solution to fix it? I never have similar issues.

My pc linux spec: https://gist.github.com/xpris/1d36deeb8e62a48b9871069576bfb5c6

**Comment by Tele42** [comment]
Hello @xpris, what filesystem are you using with your home folder? Does closing Steam, deleting the contents of ```~/.local/share/Steam/steamapps/downloading```, and restarting Steam help?

**Comment by AngryPenguinPL** [comment]
In home I have ext4 but game is located on other partition with ntfs "old" dota2 on this partition working well.

After closing steam, removing /steamapps/downloading from all files on partitions with dota2 I download again update but still have this error.

Maybe I should make new installation Dota??

**Comment by Tele42** [comment]
Yes, this is most likely a poor interaction between the steam-for-linux client and the ntfs partition and is not Dota-2 specific.

**Comment by EmmanuelPerezP** [comment]
im having the same problem
when the game finishes downloading steam says "CORRUPT UPDATE FILES" and restarts downloading the game, i tried 3 times already and the same thing happens, everytime i delete local contents to get  a fresh start but it doesnt fix the problem

alrady tried deleting `~/.local/share/Steam/steamapps/downloading`
i also have the dota 2 on a ntfs partition, so thats probably the problem

**Comment by sosiska** [comment]
same problem, i have f2fs file system
I spent searching for solutions about 5 hours
my solution is:
1) close linux native steam client
2) Install windows steam client via wine
3) Install Dota 2 on windows steam
4) make Dota 2 reserve copy via Steam > Backup and Restore game
5) close windows steam
6) open native linux steam
7) Restore game via Steam > Backup and Restore
8) enjoy dota 2 700!

my content_log before solution:
https://gist.github.com/sosiska/bd8436cb30c64782b29c445fe340efc5

I think it is more steam problem, not Dota 2

Looks like this issue https://github.com/ValveSoftware/steam-for-linux/issues/4670

**Comment by EmmanuelPerezP** [comment]
i ran steam from console to see logs and started downloads from zero, apparently the game is not being installed on the default library or something

this is the output on console https://gist.github.com/EmmanuelPerezP/035e59255a671f0f51585f98eb00e4b2

on line 110 it says `xdg-open: file '/mnt/windows2/SteamLinux/steamapps/common/dota 2 beta' does not exist`

but the folder in  `~/.local/share/Steam/steamapps/common/dota 2 beta`
has size 15gb, i dont know why but maybe it has to do something with this

**Comment by AngryPenguinPL** [comment]
Oh just see. It not dota2 related it steam related issue. Today I get CS:GO update and also have CORRUPT UPDATE FILES.

But before latest steam update I never see similar issue. I think something change in steam in latest update (two or three days ago) and now games on ntfs not downloading and updating correctly.

Trying download dota2 update on my old laptop with ext4 and it work.
Now I crate backup and trying restore on my PC on ntfs but still it want download this update...

So only hope for me is create ext4 partition...?

**Comment by AngryPenguinPL** [comment]
ok, after creating new ext4 filesystem and install dota2 all working fine (except performance).

Thanks.

**Comment by kisak-valve** [comment]
Glad to hear you got the game working, closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/4752.
