### ISSUE TITLE
[700] [MAC] > 50% fps drop when scoreboard open

### ISSUE THREAD

**Issue by dufia** [ValveSoftware/Dota-2#1099]
Latest MacOS, GeForce GT 650M 512 MB, SSD, 16GB ram

Fps also drops when ALT button is held but significantly less.
On the side note, spectator chat doesn't work properly. Your own messages aren't displayed.

Cheers, keep up great work!

**Comment by gdrewb-valve** [comment]
Performance on 7.00 is an issue across all platforms and will be handled by the larger team.  Leaving open #1101 for status.

**Comment by dufia** [comment]
@gdrewb-valve 

Thanks, please don't miss the spectator chat issue. It might be Mac/Linux only.

**Comment by Tele42** [comment]
Hello @dufia, in general, this is why there should be one issue per issue report, so that each issue can be tracked properly.

**Comment by gdrewb-valve** [comment]
@dufia, as Tele42 says you should open a separate issue just for the chat.  It's unlikely that it's Mac/Linux-specific but we can get more information on exactly what you're doing.  For example, are you watching live or have you rewound?  Specific details about what you were doing will help us determine what's going on.

**Comment by dufia** [comment]
@gdrewb-valve hey, my suspicion that the unusual characters in my nickname (steam alias) were causing trouble proved correct.

Well. Spectator chat **works fine if I remove ʕ•ᴥ•ʔ from my nickname**.

I will mention that In the previous version of the UI, the ʕ•ᴥ•ʔ was not displayed correctly within game too. It was replaced with some random characters. I never really cared to be honest maybe it's intentional.

I can't tell if the spectator chat was broken before the update, its possible.

Care

**Comment by gdrewb-valve** [comment]
The Jan. 13th update has some macOS fixes for Unicode handling in chat, give it a try.

**Comment by dufia** [comment]
Its much better, thank you. Performance improved too.
