### ISSUE TITLE
[Mac] Aspect ratio setting not working with fullscreen

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#110]
The aspect ratio setting is not working with fullscreen. 

My machine is a 15 inch 2880 \* 1800 retina mbp. At fullscreen mode, setting aspect ratio doesn't work. At windowed mode, changing to fullscreen ignores my current resolution and aspect ratio setting and sets resolution to 1440*900 without actually change the displayed setting values.

**Comment by EPadronU** [comment]
This could be related with #101

**Comment by gdrewb-valve** [comment]
The lack of true fullscreen support from 101 applies to Linux only.

**Comment by gdrewb-valve** [comment]
I know you have a separate issue open on more resolution problems but is this addressed after the 6/26 update?

**Comment by SsnL** [comment]
Confirm fixed.

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by ghost** [comment]
Broken again. Changing resolution in fullscreen _at all_ is simply ignored by the game, and is reset to the default monitor size.
Minimap becomes transparent so restart is required.

**Comment by gdrewb-valve** [comment]
This is a temporary regression, the next update will have yet more changes to video settings.
