### ISSUE TITLE
Performance on 7.00 tracking

### ISSUE THREAD

**Issue by gdrewb-valve** [ValveSoftware/Dota-2#1101]
Performance on 7.00 has changed substantially across all platforms and so isn't being handled by the porting team.  We'll use this issue as a way of collecting information and communicating updates to people following it.  At the moment there is no need to post system specs or +1 comments.

Note to Mac users: there are known performance problems and bugs in Apple’s OpenGL drivers, particularly for Intel integrated graphics.  Valve has not gotten any response from Apple about fixing these.  Valve continues to try and find workarounds but also please consider creating support requests with Apple via https://getsupport.apple.com/ and http://www.apple.com/feedback/macbookpro.html

**Comment by ChristianHersevoort** [comment]
Linux: With Vulkan enabled the menu is not functioning at all. (it feels frozen). Might be the same issue as https://github.com/ValveSoftware/Dota-2/issues/1092 . OpenGL is still working but performance in some fights drop from 120 to 20 fps. When the fight is over the frame-rate restores to about 120. 

Update december 15:
Game seems much better, not sure why
- I updateted nvidia driver to 375.26

**Comment by Vuccappella** [comment]
Any suggestion on how to report the issue to Apple as well? This is really disappointing, I'm sure you guys are doing your best but apple seems not to care about small cases such as this one. Would using nvidia dirvers improve anything?

**Comment by gdrewb-valve** [comment]
It looks like https://getsupport.apple.com/ is their online entry point.  As for using NVIDIA drivers it's hard to say if they'd be better or not as it's going to depend on the exact underlying issue.  If you have time to try it it couldn't hurt.

**Comment by kunalex** [comment]
There is a new update now. Anyone has a changelog?

**Comment by admshao** [comment]
For those on green hardware. Nvidia issued a new Driver update today 375.26 - Although the changelog doesn't say much.

**Comment by justSQL** [comment]
According to multiple reports (and [a phoronix benchmark](https://phoronix.com/scan.php?page=news_item&px=Dota-2-7.00-Linux-Benchmarks)) since 7.00 the Vulkan performance has been somewhat worse and people have encountered ingame texture corruption on all platforms.

I personally do not see these texture corruption issues but my Vulkan performance is still 10-20 fps in general worse than OpenGL performance.

**Comment by admshao** [comment]
Updating after Nvidia driver release on Windows and Linux.

Still regarding Vulkan. On the same PC and on Windows the performance seems "normal" sitting between 150-190fps on my system. Prior 7.00 on Linux + Vulkan resulted in a better performance and now is between 90-110.

I'm on a 8-core PC.
General CPU usage in Windows is CPU 0 almost 100% and 3 other cores only being used. 4 Cores being barely used.
On Linux. OpegGL all 8 cores are almost even used. OpenGL 30-40% overall. and Vulkan sitting between 60-70%.

Gpu usage on both APIs is sitting only in 35-40%. Vulkan used to use 95-100% usage.

On windows i'm not affected by opening the Scoreboard and losing XX% fps. On LInux I am.

**Comment by joshlopes** [comment]
Can anyone tell, if on mac, upgrading from yosemite to sierra has any improvement? Reluctant in upgrading! Last time it did not go so well.

Also i feel the need to let this here: is really sad seeing this kind of upgrades! This clearly was not tested at all using other distros as it is failing all over in all games, its not a bug that happens now and then.. Upgrading to affect the game system just to not compromise whatever release plan is sad and only shows a little of incompetence from valve team! I prefer waiting 2 months more for a stable game than this one which i can't simply play.

**Comment by kunalex** [comment]
Hello. 

I am on Yosemite. After the updates, things improved a little. Like very little. In fights, from 15 fps I have 20 fps now. And roaming, non-active fights, I have 40. Before the 7.00 I had 30 fps in fights and 60 fps roaming. Before and after the update, the settings were always on LOW, all boxes unchecked and recommended rezolution. 

I think Valve simply does not care about the OS users, because the pool of people with PCs is greater than us. 

It is a pity. I paid 3000 euros for a macbook and I am not able to play a game, ON LOW, that my machine is overqualified (in my opinion).

Frustrated or not, it seems that nothing changes. Long live the greed!

A frustrated player & client,

LE. When I toggle on / off the scoreboard I have lags like shit, like 15 fps drop. Toggling between my summonings (like warlock ulti, visage minions) cause fps drops too.

**Comment by joshlopes** [comment]
@kunalex so you have the Sierra version ? I meant upgrading from "El Capitan" not Yosemite.. sorry. 

Just for your information, for me it improved a lot, when i selected advanced settings, and disabled everything, put everything in low and FPS to MAX, is the only way to make it playable, on fights you may struggle a little but still way better.

Regards

**Comment by kunalex** [comment]
What can I do more?
Seriously? With his machine, to play a game like dota2 on low... Uh, I feel disgusted.

![screen shot 2016-12-19 at 21 46 46](https://cloud.githubusercontent.com/assets/20557199/21326773/c3c59eea-c634-11e6-9428-12bbf13d29d6.png)
<img width="245" alt="screen shot 2016-12-19 at 21 11 30" src="https://cloud.githubusercontent.com/assets/20557199/21326774/c3c65da8-c634-11e6-812e-426168436566.png">

**Comment by admshao** [comment]
Chill out dude. You already made your point. Valve knows that something is
up and they already reported to be looking for the issue in everybody's
performance problems...

And to be fair. Have you tried to reach apple for any support? I bet you
think that its all good on their side. Nothing wrong with their new OS
updates or older version of OpenGL and not supporting Vulkan...

Valve is doing their best and there are other bugs that probably and should
have a higher priority.

Easy man...

**Comment by kunalex** [comment]
I have reached out to Apple too. The same response. Nothing.

I am chill man, I am. I have been for a year now, when I made the switch from Win to OS. Didn't knew what I was coming to. And sorry, performance bugs and gameplay bugs were repaired much more master for PC owners. It is ok. The problem is that I love dota, and I will keep playing. Too bad tha Valve and Apple don't care as much as we do about the game.

**Comment by joshlopes** [comment]
@admshao to be fair, valve didn't need to update the game knowing that at very least even knowing that 5% of their community being mac, wouldn't be able to play the game ;) That if they tested mac at all. which doesn't look like the case.

Anyway, looking forward for the fixes / any hack around to fix this issue, i'm off dota meanwhile. Good thing that the update came exactly when people is on holidays from school / work for the xmas (sarcasm!) -- at least we'll socialize more xD

**Comment by joshlopes** [comment]
So i have contacted apple support and they can't do nothing other than tell me to do the feedback here: http://www.apple.com/feedback/macbookpro.html as long as many of you do the same the faster they will take action on this, so share with other mac players and try to get as much tickets on their feedback system as possible. If they filter by Dota 2 and get a nice amount i'm pretty sure they will pay more attention to this and hopefully they can take in consideration this type of games for mac. Can i please ask @gdrewb-valve to place that link on other similar posts with the same issue for mac users? that would help! Thanks.

**Comment by joshlopes** [comment]
Okay to update you guys, after updating to sierra, and having the settings with max fps and playing on cable (Ethernet) everything seems to be running as smooth as the last version! It could also mean they have fixed it. :)

**Comment by gdrewb-valve** [comment]
A recent update added an Effects Quality option in the video settings.  For those of you where it isn't already on low does changing it to low help framerate with complex effects?

**Comment by jgouth** [comment]
No change. 

Please valve, it has been over 9 days and no progress. It is extremely frustrating being such a fan of this game but yet not being able to play because of an update that was not properly tested.

**Comment by gdrewb-valve** [comment]
@jgouth, can you provide more details?  What was your Effects Quality setting at?  Did you change it to low?  What effects did you test out to see if something changed?

**Comment by jgouth** [comment]
My effects quality setting was at high, I changed it manually to low. 

However, after playing ~ 5 games, I've noticed a max difference of 5 fps. I used to get about 50-60 fps easily, now I am getting max 30.

**Comment by gdrewb-valve** [comment]
The Effects Quality will primarily affect performance for spell and ability effects so it's a more localized change.  It would help with hitching when complex affects appear but it isn't a constant improvement.

**Comment by jgouth** [comment]
Any update from valve on what the issue is? 

Is this on apple side or the update?

**Comment by gdrewb-valve** [comment]
The major changes in 7.00 impact different computers in a variety of ways so there is no one single issue.  The larger team is working through things and will continue to do so.  The game view is also larger since the new HUD shows more game area so there's just more being done overall.

Apple's driver problems will always limit frame rate on Macs but that is even more complicated as to how it affects a particular computer.  The hope is that Dota frame rates will get back to something like what they were before but there's no timeframe or guarantee.

**Comment by wahmbulance** [comment]
thanks for trying to fix the problem valve. ill try to get my good friend tim cook to contact lord gaben in hopes of giving out the apple open gl driver source codes to gabe personally.

**Comment by wahmbulance** [comment]
created a support request on imac from apple. i told them to contact you guys about these open gl driver problems. i hope it works out.

**Comment by kolobos** [comment]
As a proud owner of dual core Intel E7200 CPU from 2008, I can confirm regressions on very low-end hardware in 7.00 (Valve Panorama) compared to pre-7.00 (Autodesk Scaleform).

**System:**
OS: Gentoo Linux
CPU: 2 cores, 2 threads Intel E7200 (2008) overclocked to 3163 MHz
GPU: AMD HD7790 (GCN 1.1 Bonaire)
RAM: 4 GB

**Drivers:**
Mesa git, LLVM git, libdrm git, xf86-video-amdgpu git (userspace AMDGPU driver), custom kernel 4.9.0.
```
OpenGL core profile version string: 4.5 (Core Profile) Mesa 13.1.0-devel (git-88b5acfa09)
OpenGL core profile shading language version string: 4.50
```

**Dota 2 settings:**
Everything off/low. Pre-7.00: Render Quality at 100%, Post-7.00: Render Quality at 67%.

**Demo mode with Spirit Breaker, OpenGL:**
Pre-7.00: ~75 FPS
Post-7.00: ~65 FPS

**Matchmaking OpenGL**
Pre-7.00: ~70 FPS
Post-7.00: ~55 FPS
Pre-7.00 40 minutes into the match: ~55 FPS
Post-7.00 40 minutes into the match: ~45 FPS, drops to ~35 with Scoreboard/Chat open.
Pre-7.00 heavy teamfights: ~40 FPS, occasional stutters
Post-7.00 heavy teamfights: ~25 FPS, smooth with bad FPS

**Matchmaking Vulkan (experimental Mesa RADV driver)**
Pre-7.00: ~60 FPS
Post-7.00: ~50 FPS
Pre-7.00 30-40 minutes into the match: 10-15 FPS, heavy stuttering
Post-7.00 30-40 minutes into the match: 10-15 FPS, heavy stuttering

**CPU/GPU usage**
Both CPU cores at 95% according to htop. GPU at ~30% according to radeontop. No changes with patch 7.00.

**System information from Steam**
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  3163 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.0-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11900000
    X Window Manager:  xmonad
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
   
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BONAIRE (DRM 3.8.0 / 4.9.0-gentoo, LLVM 4.0.0)

    Driver Version:  3.0 Mesa 13.1.0-devel (git-88b5acfa09)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Revision Not Detected
    Number of Monitors:  2
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 2104
    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                            50.9cm x 28.6cm  (58.3cm diag)
    Primary VRAM: 997 MB
    
Sound card:
    Audio device: Realtek ALC662 rev1
    
Memory:
    RAM:  3950 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  50779 Mb
    Largest Free Hard Disk Block:  29539 Mb
    VR Headset: None detected
    
Recent Failure Reports:
```

**Comment by kunalex** [comment]
@admshao two weeks passed. guess what? fps still 30-40. 15 in fights. same machine, same iOs. valve? oh well, it is XMas, no time for the little community of mac players.

**Comment by jgouth** [comment]
@kunalex @gdrewb-valve yup same here. Here's hoping there is a fix eventually, i love this game too much to quit, but if it is like this for months I will have no other choice.

**Comment by kunalex** [comment]
@jgouth @gdrewb-valve I still play. Crappy, laggy, but I still do it. It hurts my mmr too. Worked hard for that MMR. Time, sweat, nervers. But who cares. Our community needs to be heard, but it seems that we can't find a catalyst.

**Comment by gdrewb-valve** [comment]
Please note that this is a bug tracker and not a discussion forum.  Also, as mentioned above, problems are happening on all platforms, this is not just a Mac issue.  The larger Dota team is in charge of the investigation and not the porting team that handles this tracker so updates here will be infrequent.

**Comment by c0rru** [comment]
@kunalex please stop the spam. Valve did an amazing job for linux and mac os so far just wait for the fix. If you can't wait try to install windows with bootcamp until it works well again. (Should help)

I asked Apple about vulkan support in general 2 months ago but (sadly) got no answer yet :/ If they really rejected vulcan its really really bad for multi-platform support :/ Does someone got a response from Apple? About Vulkan or the OpenGL driver maintenance?

**Comment by wahmbulance** [comment]
i might have to install windows boot camp on my imac. fml.

**Comment by AngryPenguinPL** [comment]
In my case FPS is also bad. Before 7.00 game on high graphics working with with nice FPS. Now FPS is too low to comfortable playing.
Maybe this most issues is not related to graphics section but for other (maybe CPU?). Why? Because when I set graphics settings to low, I still get almost the same FPS like on high settings.

Can I somehow help in determining the reasons for decrease FPS? Maybe some debbuger or something?

**Comment by joshlopes** [comment]
I can confirm that lately the game has been more stable for OSX on sierra with minimum settings. (didn't try defaults yet). I also opt to use cable instead wifi! not sure if has something to do with it too.

**Comment by admshao** [comment]
After a couple of days of a update that restored some fps for me. I still have to say that my gpu isn't being maxed out like it was before 7.00 and sometimes i still feel the game stutters a little bit whereas wasn't happening before.

It's sitting now between 50-60% and before was almost 100%. Maybe 7.00 changed something about async workloads? I know Dota is way harder on the CPU and Vulkan renderer is still experimental, just felt like sharing my lastest experiences.

**Comment by tomekmarchi** [comment]
The performance has never been worse for me in the current 7 patch on OSX. Tons of frame skips.

**Comment by AngryPenguinPL** [comment]
After today patch http://www.dota2.com/news/updates/27046/ performance for me is very bad.
Yesterday I play with nice FPS and today after latest patch, FPS is very poor on my Linux machie.

**Comment by gdrewb-valve** [comment]
The Jan. 24 update did not have much in the way of complicated changes that might have a large impact on frame rate.  If you verify your install does that change anything?  If you restart Steam and/or your computer does that change anything?  If you double-check your video settings and launch options (if you have any) did anything change?

**Comment by AngryPenguinPL** [comment]
I trying verify game cache but all files are correct. Restarting steam or computer not change my performance. No, my video settings is still the same without any changes.
Don't know why but I have worse FPS.

When match start, I have nice FPS, but when I start fight on the line, fps drop and game is almost unplayable now.

**Comment by Arakash** [comment]
My dota2 performance drops in fps periodically. It's running on 80-100 fps, but then drops to 10 for a few seconds.
I'm using a 960M and i7-5500U on Ubuntu. When disabling my nvidia card, i can play "fine" with the integrated intel card. I get stable fps but they hover around 20-30, so it's not really playable, even on lowest settings.

@nvidia: If I'm experiencing a fps drop, and i quickly look at 'top' Dota2 sits at 160%-200% CPU usage, then goes back to around 30%. 
Maybe increasing the RAM would help. I have 8GB of ram in this machine, but Dota only uses 1.4-2GB - any way i can increase this?

EDIT: I did some testing and i think i found the problem: In my case it's probably thermal throttling.
I'm using the lm-sensors package to check my temps (https://help.ubuntu.com/community/SensorInstallHowto ).

My temperature climb to about 93°C (yikes), then a fps drop occures until the temp is down to about 74°C again (~1,2s), at which the temp begins to climb again. Seems like my laptop has shitty  cooling or my cpus just work overtime for some reason.

**Comment by AngryPenguinPL** [comment]
I found video which shows that disablind HUD dramatically increases game performance on Linux.
Maybe this not help but you can see that most of performance is killed by new HUD. So maybe in future you can get some improvements in hud performance?

Not my video, you can check it here: 
https://www.youtube.com/watch?v=kZtKArPyQ3I

**Comment by phoerious** [comment]
I have a steady 20 FPS with OpenGL, both at my native resolution and a lower 1080p resolution. I don't remember it being this bad when 7.00 came out.
Using the Vulkan backend, I can get up to 120 FPS at 1080p and about 75 FPS at WQHD. Menu and loading screen performance still feels very bad, though.

Arch Linux, Nvidia 378.13

**Comment by gdrewb-valve** [comment]
For people that haven't already turned all of their options down to low there's a Dota performance test that may suggest settings to tweak for higher frame rates.  http://dev.dota2.com/showthread.php?t=277903

**Comment by Ace5040** [comment]
> Not my video, you can check it here:
> https://www.youtube.com/watch?v=kZtKArPyQ3I

I can add some additional information to think off.

My settings all set to minimum (except rendering quality) and I have 120-130 fps with nvidia 750ti on 1680x1050 monitor when game starts

If I open console(full of messages) fps immediately drops to 80-90
Then if I use 'clear' command so the console become empty my fps restores to 120 right away

Next if I open shop and scoreboard and chat at the same time fps drops even more to 50-60
If I now add to all this console (full of messages) fps drops to 40-50

And some more observations the more text in console the more fps lost if console is visible
And at last fps slowing down while game progressing. so at the begin i have 120, at 3 min i have 100, 5-10 min drops to 80-90 then to 60-70

Can some body reproduce this on other setups?

P.S.: my config is archlinux lxqt, fx6300, 750ti, 16gb ram, ssd 850evo

**Comment by phoerious** [comment]
Sorry, if this is slightly off-topic. In addition to my observations about the overly poor performance on OpenGL and mediocre performance on Vulkan, I noticed that I still have screen tearing in Vulkan, even when Vsync is enabled. The tearing only appears in the upper part of the screen. I know that there is (was?) a known bug in the Nvidia driver for Linux. Is this still the same bug or a regression? If it's the same bug, it really needs some fixing after all this time.

**Comment by jeanlain** [comment]
Regarding OpenGL bugs on macOS, good luck having Apple fix these... 
Let's not kid ourselves. OpenGL on the Mac is being abandoned. So the long-term maintenance of Dota 2 on the platform either relies on:
- You guys at Valve porting Source 2 to Metal. Source 2 only powers one Game now, but I suppose you at Valve have bigger plans for it? Unreal and Unity both support Metal, which is reportedly much easier to use than competing APIs.  
- Dota 2 using another engine. I hate to say it, but Unity (which Valve likes a lot) performs circle above Source in Dear Esther (~5-8X faster) in complex scenes on my Mac (GCN 1.0 GPU). Granted, Dear Esther is a Source-1 game, but Source 2 did not bring significant performance gains on the Mac (Dota 2), maybe we can extrapolate.
- Having Apple support Vulkan. Good luck with that too. 

I understand that you at Valve don't want to support a platform-specific API (well, except D3D). But  someone will have to change their plan if Dota2 is to remain on the Mac, and that someone won't be Apple, I can tell you that.

**Comment by anhmiuhv** [comment]
I installed Linux Mint 18.2 on my steam machine with gtx 960 and i5 intel 6400T 2.2GHz 8Gb RAM

My fps is 34 on lowest setting.

On steam os, I got 112 fps on highest settings. Can I do anything about this?

**Comment by AngryPenguinPL** [comment]
Proprietary drivers?

**Comment by gdrewb-valve** [comment]
We're going to be closing this general issue as 7.00 has been out for a while now.  Specific performance issues are open already for more recent things.  Note in particular for Mac users that you should try the Vulkan support and report issues in the Dota-2-Vulkan tracker.
