### ISSUE TITLE
open mic broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1102]
Dash board open mic is broken, push to talk in-game works.

**Comment by gdrewb-valve** [comment]
Likely not system-specific, checking with the larger team.

Please link a gist of your system information in your issues so that we don't have to go to other issues to find it.

**Comment by gdrewb-valve** [comment]
The larger team is aware of this and says it's not platform-specific so they'll take it.

**Comment by sylware** [comment]
fixed
