### ISSUE TITLE
Crash after select Summons (Necro, Forged...)

### ISSUE THREAD

**Issue by aldebaranbm** [ValveSoftware/Dota-2#1103]
After 7.00 update, Dota2 crash in selection (Hotkey or Screen Square). GPU crash after select summons (Necronomicon, Forged Spirit...)

Distro: Debian 8 (Stable Repository)
Kernel: 3.16.0-4-amd64
GPU: AMD Radeon HD 6850
CPU: Prcessor AMD FX(tm)-8350

**Comment by Tele42** [comment]
Hello @aldebaranbm, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. If you find any CrashIDs or mindump (.dmp) files related to this issue, please include them as well.

**Comment by aldebaranbm** [comment]
I uploaded My System Information (Portuguese Language) in this link https://dl.dropboxusercontent.com/u/5700318/SteamSystemInformation

*I tryed find .dmp files (with terminal search, "sudo find / -iname *.dmp") but not found anythint dump from Dota2/Steam

**Comment by gdrewb-valve** [comment]
When you say "GPU crash" do you mean that the system put up specific information saying that there was an issue with the GPU?

**Comment by aldebaranbm** [comment]
My computer simply produces failed images. The sound keeps working... the whole video is compromised. I can not even access other terminal sections (Ctrl + Alt + F1 ... F6).

Hard restart is required.

**Comment by gdrewb-valve** [comment]
Full system failures would be driver or hardware issues and not Dota problems so this may not be something that Valve can address.  You might want to check with the maintainers of your OpenGL driver too.

**Comment by aldebaranbm** [comment]
I uploaded a video to demonstrate the Critical Bug... https://dl.dropboxusercontent.com/u/5700318/Steam/20161213_164239.mp4

PS: Something similar happens when I try to view graphs ...Graphs of departures from my game history or a game that has just ended. This bug in graphics has occurred since their implementation at Reborn, but it has never bothered me since it's not critical.

**Comment by aldebaranbm** [comment]
Whenever some HUD update is released ... such errors occur, after a few days Dota always fixes ... I do not see that there could be problems here.

Maybe a lack of support for Debian Jessie and old AMD cards.

PS: Sorry per my english.

**Comment by gdrewb-valve** [comment]
Dota itself by definition can't crash or hang the machine, any such problem would be a bug in the system's protection against bad processes.  Dota's behavior can certainly influence things, such as exposing bugs in the system, so Dota changes may definitely affect this.  It's possible a Dota update will correct it but it still might be useful to check with your OpenGL driver maintainers.

**Comment by aldebaranbm** [comment]
OK. I will try install proprietary drivers of AMD.

I'm using driver "xserver-xorg-video-ati" because as this was what provided me with a better Dota2 experience.

**Comment by Tele42** [comment]
For what it's worth, Mesa 10.3.2 was released on 2014-10-24. There's a good chance you are encountering a driver bug that is already fixed upstream.

**Comment by aldebaranbm** [comment]
Thanks Tele42 and gdrewb-valve. After the installation of the proprietary drivers (from the Debian repositories), the failure does not occur. Apparently no new bugs ...

This is my new driver...
> Driver: ATI Technologies Inc. AMD Radeon HD 6800 Series
> Versão do driver: 4.5.13399 Compatibility Profile Context 15.201.1151
> Versão do OpenGL: 4.5

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by aldebaranbm** [comment]
With proprietary driver have many lags in Team Fight. Frozing by 1 or 2 seconds...

One more update in Dota2 linux but not resolve the bugs. I back driver and waiting Dota2/Drivers updates =/

**Comment by aldebaranbm** [comment]
**I finally fix** it instaling the package **libgl1-mesa-dri** of Debian **Backports** repository. 

I continue using the **xserver-xorg-video-ati** (Open Drivers) from the **Stable** repository.

I leave here my solution to possibly help other members.

PS: Special thanks to @Tele42
