### ISSUE TITLE
Shop upgrades sometimes get duplicated

### ISSUE THREAD

**Issue by Jaizu** [ValveSoftware/Dota-2#1105]
Sometimes when I want to upgrade an item, upgrade options will get duplicated.

gist with system information: https://gist.github.com/lmao-emerald/312b78390a9fab03254936ad71611345
bug image: http://i.imgur.com/iPgObQA.png

**Comment by gdrewb-valve** [comment]
This forum is for Mac/Linux-only bugs, you'll want to post at dev.dota2.com
