### ISSUE TITLE
Loud noice -> crash

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1107]
hi,
I heard a loud noice and then the game crashed.

[460242.537281] dota2[32031]: segfault at 0 ip 00007ff9e4500188 sp 00007fff6896b090 error 4 in libclient.so[7ff9e2260000+45e1000]

**Comment by gdrewb-valve** [comment]
Can you post your full Steam system info?  Also did you get a crash dump (it'll be referenced in the Steam system info)?

**Comment by Turmfalke2** [comment]
http://pastebin.com/UHeTQFnx

Dump renamed to png because github is being silly.
![crash_20161213200944_1](https://cloud.githubusercontent.com/assets/5174562/21162359/469e7852-c18d-11e6-8f26-2e8b600434f6.png)

**Comment by gdrewb-valve** [comment]
Your crash (BoneFlagsToBitVec) is something that is happening on all platforms and is being investigated by the larger team.  Can you remember exactly what was going on prior to the crash?  What hero were you playing?  What else was visible on the screen?

**Comment by Turmfalke2** [comment]
Even better, I just checked the replay. At 10:42 6 players all over the map crashed. 
2844088232

**Comment by gdrewb-valve** [comment]
Thanks, I'll pass that on.

**Comment by phoerious** [comment]
I can't tell if it's the same issue, but since you reported that multiple players from both teams crashed, I guess it is. We had quite a frustrating evening today. A couple of losses, all of which were scored and a couple of wins non of which were scored because at some point, people randomly crashed. One could say, Dota3 hated us. :-)

Here's my system info. Please check if the crash dumps point to the same issue:

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.12-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.10
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 1440
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1150
    
Memory:
    RAM:  15999 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  1880437 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Tue Dec 13 19:14:18 2016 GMT: file ''/tmp/dumps/crash_20161213200435_1.dmp'', upload yes: ''Discarded=1''
    Wed Dec 14 00:36:08 2016 GMT: file ''/tmp/dumps/crash_20161214002755_1.dmp'', upload yes: ''Discarded=1''
    Wed Dec 14 02:50:05 2016 GMT: file ''/tmp/dumps/crash_20161214032640_1.dmp'', upload yes: ''Discarded=1''
    Wed Dec 14 02:58:05 2016 GMT: file ''/tmp/dumps/crash_20161214035014_1.dmp'', upload yes: ''Discarded=1''

**Comment by gdrewb-valve** [comment]
@Manko10 you'll need to post a dump file for us to look.

**Comment by phoerious** [comment]
Oh, I thought you could look up the id since it says "submitted=true".I'll post it somewhere when it happens again. Are those regular gdb-readable core dumps?

**Comment by Tele42** [comment]
Hello @Manko10, Steam uses Breakpad minidumps by default.

**Comment by gdrewb-valve** [comment]
The "Discarded=1" means that the dump wasn't kept.  Some submissions are discarded to reduce load and storage.

**Comment by gdrewb-valve** [comment]
Has this happened recently? I believe the larger team has fixed the underlying cause.

**Comment by gdrewb-valve** [comment]
Closing as there are no new reports.
