### ISSUE TITLE
Mysterious black line above HUD

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#1108]
There's a black vertical line above the center HUD, next to the portrait.

![visageeffigy](https://cloud.githubusercontent.com/assets/7419656/21162821/a275ae50-c18f-11e6-8295-c6464345c104.png)

(Ubuntu 16.04, i3wm)

Also, the Visage effigies still don't have bodies which would be nice to fix since that's something I actually payed money for and it's been like this for a while now.

**Comment by Tele42** [comment]
Hello @helix42, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

**Comment by u00101010** [comment]
Sorry, here it is:

https://gist.github.com/helix42/749ac54d6099c026bbab49fa66f10dbc

**Comment by gdrewb-valve** [comment]
This is not Linux-specific, the larger team will handle it.
