### ISSUE TITLE
[Linux] No "default" sound device

### ISSUE THREAD

**Issue by svms1** [ValveSoftware/Dota-2#111]
I switch between audio devices a lot since my headset has a different (built-in) sound card than my speakers. Before I accidentally selected a sound device in the settings, I heard the sound on the device that was selected in pulseaudio and there was no device selected in the settings (the dropdown was blank). Now I have to change the settings every time I switch devices.

It would be nice to have a "default" entry with the behaviour of no explicitly selected device.

**Comment by r3pek** [comment]
I can make dota always play on the headset using pulseaudio (that's how i've done it)

**Comment by liquex** [comment]
@r3pek That's exactly what I don't want, I want Dota to use the device I have selected in pulseaudio because I switch between devices a lot (I use my headset when playing with friends and my speakers when playing alone).

**Comment by computerquip** [comment]
What the user is wanting is an option that allows the PulseAudio server to decide what the output device is rather than the application. This way, you can control what device is being output via external controls rather than per application. I think there's a virtual device simply named "Default" in the list of enumerated devices, however, it seems to be explicitly removed from the list. I could be wrong though, It's been awhile since I've explicitly dealt with any sound system's API directly.

**Comment by r3pek** [comment]
But that's what I'm saying... it's just not configured in Dota, it's directly in pavucontrol. I can make Dota output the sound to the headset when I want it (by default it's to the headset).

**Comment by Manko10** [comment]
I'm having a similar issue. No sound device is selected and no sound is played. When I go to the settings and select a device, it either does nothing (selection still blank, no sound) or Dota freezes until I kill it with killall -9 dota2
Using Pulseaudio 6.0

**Comment by Manko10** [comment]
Side node: if I pluge the headset in, start dota, then unplug and replug the head set, sound is working. But only then.

**Comment by davidw-valve** [comment]
This will be fixed in the next update. There will be a "Default Device" available. Selecting that will provide exactly the same selection behavior as Source1 Dota2 used.

**Comment by gdrewb-valve** [comment]
The 6/30 update has the fix.

**Comment by computerquip** [comment]
Can confirm this seems to work. Seems options were confused on first load up since fix though, since the option box was empty. Setting a device seems to persist though. 

Good job!
