### ISSUE TITLE
Linux - game doesn't load, crashes straight up

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#1111]
Console:

```
>>> Adding process 28653 for game ID 570
>>> Adding process 28654 for game ID 570
>>> Adding process 28656 for game ID 570
>>> Adding process 28657 for game ID 570
/home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 104: 28657 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 28652 
No cached sticky mapping in ActivateActionSet.
```

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-53-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.57
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.47" x 11.42"  (23.43" diag)
                                            52.0cm x 29.0cm  (59.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC889
    
Memory:
    RAM:  7966 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  104566 Mb
    Largest Free Hard Disk Block:  14786 Mb
    VR Headset: None detected
    
Recent Failure Reports:
```

**Comment by wuerges** [comment]
Crashing here too. How do I get the console output?

**Comment by sinatosk** [comment]
same... just updated a few minutes ago

> Game update: AppID 570 "Dota 2", ProcID 13802, IP 0.0.0.0:0
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 13802 for game ID 570
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 13804 != 13803, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Application .exe "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2"
is in an unsupported path for game "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota"!
Game base directory " ���]U" doesn't match root dir "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game"
If you have special characters in your install path this may be confusing the game.
../public/appframework/tier1app.h 573 SetModPath():
Application .exe "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2"
is in an unsupported path for game "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota"!
Game base directory " ���]U" doesn't match root dir "/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game"
If you have special characters in your install path this may be confusing the game.

>>> Adding process 13803 for game ID 570
>>> Adding process 13805 for game ID 570
>>> Adding process 13806 for game ID 570
/home/user/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 104: 13806 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 13802 
No cached sticky mapping in ActivateActionSet.

and in my kernel logs ( from dmesg command ) I'm seeing

> [Dec13 17:55] dota2[13349]: segfault at 0 ip 00007f1148355571 sp 00007ffd3bd6c620 error 6 in libtier0.so[7f1148311000+af000]
[ +26.682056] dota2[13414]: segfault at 0 ip 00007f3c6969d571 sp 00007fff6ba8f930 error 6 in libtier0.so[7f3c69659000+af000]
[Dec13 17:56] dota2[13651]: segfault at 0 ip 00007fa92d10d571 sp 00007ffe9e2930b0 error 6 in libtier0.so[7fa92d0c9000+af000]
[Dec13 17:58] dota2[13695]: segfault at 0 ip 00007f1a6240d571 sp 00007ffd7ebcd810 error 6 in libtier0.so[7f1a623c9000+af000]
[  +2.601892] dota2[13707]: segfault at 0 ip 00007f38beebd571 sp 00007fffcd682510 error 6 in libtier0.so[7f38bee79000+af000]
[  +5.794938] dota2[13719]: segfault at 0 ip 00007f8b15c85571 sp 00007ffe684c6a80 error 6 in libtier0.so[7f8b15c41000+af000]
[Dec13 17:59] dota2[13793]: segfault at 0 ip 00007f5651055571 sp 00007ffe4d1b6ab0 error 6 in libtier0.so[7f5651011000+af000]
[  +5.396566] dota2[13806]: segfault at 0 ip 00007ff04cadd571 sp 00007ffdc8e78a30 error 6 in libtier0.so[7ff04ca99000+af000]

**Comment by marshall2056** [comment]
Same issue here, was working before last update few minutes ago:
dmesg
[  255.491765] dota2[3270]: segfault at 0 ip 00007f43e0ff5571 sp 00007ffd56e8ef30 error 6 in libtier0.so[7f43e0fb1000+af000]

uname -a
Linux T460 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zeflap** [comment]
Getting the same thing, running steam in terminal outputs https://gist.github.com/zeflap/b89c7e4e9281f74c63e5fc19f6f361bc

**Comment by phoerious** [comment]
Just got another update which fixed the problem. It's working again.

**Comment by vadi2** [comment]
There's a 130mb update that came out just now, does the issue still happen
if you upgrade?

I'm still downloading.

**Comment by zeflap** [comment]
@vadi2 Fixed for me

**Comment by sinatosk** [comment]
fixed for me

**Comment by gdrewb-valve** [comment]
Thanks, closing.
