### ISSUE TITLE
Game Crashes in Demo Mode (It probably crashes in the real game too though)

### ISSUE THREAD

**Issue by ethandbrand** [ValveSoftware/Dota-2#1112]
Game crashes after playing in demo mode for a brief period of time (1-3 min).

Error is: CThreadMMultiWaitEvent::CThreadMulitWaitEvent(bool)
():
Unable to create event, error 24

I'm on a Mac (if that even matters)

**Comment by nfang** [comment]
Getting the same error after installing the latest patch on Mac OS Sierra.

**Comment by bewater8** [comment]
Same problem Mac OS Sierra<a href="http://imgur.com/a79J9jI"><img src="http://i.imgur.com/a79J9jI.png" title="source: imgur.com" /></a>

**Comment by podliy16** [comment]
Same here El. Capitan

https://gist.github.com/podliy16/956dc078810ef260828b3060971ebb8d

**Comment by shampoobob** [comment]
Same problem on my El Capitan.

**Comment by xrisk** [comment]
Crashing when I'm queuing for a game. 4 times in a row.  Impossible to start a game... 

Here's the detailed stack trace: [gist](https://gist.github.com/xrisk/9983ecaa3de3e6a7febf87ce4ff8dd93)

**Comment by gdrewb-valve** [comment]
The fix is rolling out, should be good on all platforms.

**Comment by gdrewb-valve** [comment]
Closing.  New crashes are hopefully new bugs.  :-)
