### ISSUE TITLE
Items not shown in pregame screen

### ISSUE THREAD

**Issue by ksthiele** [ValveSoftware/Dota-2#1116]
When I buy items in pregame they are not shown in my inventory.

Ubuntu 16.04

**Comment by gdrewb-valve** [comment]
What specific items did you buy?

**Comment by ksthiele** [comment]
Tango, Quelling Blade, Stout Shield, Faerie Fire, but it doesn't really matter what item

**Comment by gdrewb-valve** [comment]
What game mode were you playing in?

**Comment by ksthiele** [comment]
it was on a tutorial

**Comment by gdrewb-valve** [comment]
The larger team says that this can happen on all platforms and they're taking it on.
