### ISSUE TITLE
[hero panel] courrier ultimate appears next to hero ultimate

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1119]
Select courrier, then select your hero: the courrier ultimate is displayed next to the hero ultimate. It does not go away.

**Comment by Turmfalke2** [comment]
From what I heard that also happening on windows. So probably known issue and not relevant on this bug tracker.

**Comment by gdrewb-valve** [comment]
You should post general issues like this at dev.dota2.com

**Comment by sylware** [comment]
I cannot know if it's a general issue.
