### ISSUE TITLE
[Mac] portraits don't animate when previewing heroes in grid view

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#112]
This is on OS X 10.9.5 with a radeon HD 7950.

Portraits don't animate when mousing over heroes in grid view. This is in the "heroes" pane. 
Instead of a video, we get a zoomed pixelated preview which is the same as the portrait (I think, but I'm not on my gaming Mac right now).
This issue does not happen when choosing heroes before a match, in grid view.

**Comment by gdrewb-valve** [comment]
Same underlying issue as #54: the hero movie playback support is not finished for Linux and Mac yet.

**Comment by kon14** [comment]
Still no updates on this one? I mean it's not breaking the game but it's really annoying.
I know you've replied to this in #54, just bumping

**Comment by jeanlain** [comment]
Yeah, the game looks unfinished on Mac and Linux because of this issue. I'm not sure what's taking so long since portrays are animated in the hero selection window.

**Comment by gdrewb-valve** [comment]
The 2/17 update should have the fix.
