### ISSUE TITLE
[Linux] game eat all RAM memory

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1121]
Hi.

After 7.00 patch Dota 2 use all my RAM memory and all swap.
This is what happens while playing "normal" as well as training with bots.

When I start game In main menu I see RAM usage (all ram usage system + dota2) at 1,88 GB, when I start bot match I have at the beginning 2,62 GB usage. After few minutes it use 2,99 GB and after first small team fight it use 3,19 GB. About 20-30 min it use 3,55 GB and more. Now playing is almost impossible (many lags). When game playing still It completly freeze.

I have only 4GB of RAM but old version DOta 2 (before 7.00 patch) working without this issues.

Any hope to fix it?

Steam pc spec info: https://gist.github.com/AngryPenguinPL/1d36deeb8e62a48b9871069576bfb5c6

Quick info:
Linux Mageia 5x64 kde
Kernel: Linux 4.4.36
CPU: AMD Phenom II X6 3GHz (sixcore)
GPU: AMD Radeon HD 5850 (1GB GDDR5) + Catalyst 15.9 driver
RAM: 4 GB
Disc: 500 GB (dota now on ext4 filesystem)

**Comment by gdrewb-valve** [comment]
What tool are you using to get your memory usage numbers?  They are much higher than what I see on my Linux box and I also don't have the high growth.

That said the larger team is working on performance and memory so it's likely that at least some of this will improve over time.

**Comment by AngryPenguinPL** [comment]
System monitor from KDE DE (ksysguard).

Also I trying reproduce this on my notebook but on it I not see this issue. On it I have only much worse performance 19 FPS on start match and in it about 10 FPS. Before patch I get on it about 25 FPS in match. Maybe I can't reproduce it because it use other Linux OS and MESA 13.1 driver instead of Catalyst?

**Comment by AngryPenguinPL** [comment]
Worth to add that when match is end (and not all RAM is used) so I can simply finish it. I see dota after match even in main menu use RAM like on match. For example. I start dota and have about 50% RAM usage. When ending match I have about 80/90% usage and when I back to main menu my RAM usage is still at 80/90%
Only when I close dota2 my RAM usage drop down.

**Comment by gdrewb-valve** [comment]
You mentioned in 1122 that Dota is no longer consuming all of your RAM, is that correct?  If so I'll close this.

**Comment by AngryPenguinPL** [comment]
Yes. Now it use much less RAM.
Thanks.
