### ISSUE TITLE
[Linux] heavy lag when casting spell or use teleports or other things

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1122]
When me or other hero in within sight casts such skill. tidehunter its ultimate "Ravage" or Zeus "Thundergod's Wrath" or any other hero of "heavy" spell i get big lags - performance for few seconds drop to 1 FPS and game look like freeze but after few second FPS back to normal.

It also happens when using teleports, at the time of rebirth after death. This is also during fast of traverse camera to a different area of the map, as well as in many other cases.
It happens during normal matches as well as games with bots.

Unfortunately because of this issue, game is not completely playable for me.
Before patch I have 70 FPS and team fight about 40/50 FPS. Now I have 40 FPS and in team fight 15-25 FPS and every use huge skill it also have big lag and this big lag freeze game for few second. So unplayyable for now.

I have also this issue https://github.com/ValveSoftware/Dota-2/issues/1121

Steam pc spec info: https://gist.github.com/AngryPenguinPL/1d36deeb8e62a48b9871069576bfb5c6

Quick info:
Linux Mageia 5x64 kde
Kernel: Linux 4.4.36
CPU: AMD Phenom II X6 3GHz (sixcore)
GPU: AMD Radeon HD 5850 (1GB GDDR5) + Catalyst 15.9 driver
RAM: 4 GB
Disc: 500 GB (dota now on ext4 filesystem)

**Comment by gdrewb-valve** [comment]
I just tried Tidehunter's Ravage in a hero demo and didn't see anything that extreme.  There's a perf drop, which is expected since the spell causes a bunch of new effects, but it was from 90fps to 75fps while the spell ran.

From 1121 your system looks to be under substantial memory pressure so that may play a part.  As I mentioned in that issue the larger team is looking at all of this across all platforms.

**Comment by AngryPenguinPL** [comment]
After few small Dota 2 updates and disabled in graphics options "grass" today I play few normal matches.
First match my RAM was taken only at the end.
In another about 30-40 minutes.
In next already in about 15 minutes. So I think more or less, but it also depends on the Hero that appear in game. Last match I play Monkey King (I think he is poorly optimized) and in my team I have Underlord. When he casting two still in same time q - Firestorm and w - Pit of Malice, I get screen freeze to 10-15 seconds. After he casting ultimate skill my PC completly frozze (all RAM eaten) and I need reboot.

**Comment by gdrewb-valve** [comment]
A recent update added an Effects Quality option in the video settings.  If it isn't already on low does changing it to low help framerate with complex effects?

**Comment by AngryPenguinPL** [comment]
If this change performance, it does it only a little. During normal matches hardly see any difference. I not make any benchmark yet. So I do not know precise results. But from what I can see the impact is very small.

Also game still eat all RAM. From last days, I only finish two match (from the beginning to the end without rebooting due to use all of the RAM).
Also I see that game laggy not only when heroes use skills or when I use TP but also when I play 10-15 minutes and I press enter to write write something in the chat. Also when I press "~" to see stats and intem my team it now also freeze game to 10-15 seconds. When Im dead and trying selling one of my intem -  game show me message that I can't sell it (because Im dead) and I get massive lag for few seconds.

**Comment by AngryPenguinPL** [comment]
I can add that I trying use another desktop environments - IceWM and I see it use much less RAM. So I have about 300-400 RAM more free RAM. But when play in DOTA2, game eat also this addition RAM. So I don't know If I get more RAM memory, dota not eat it all.

Also this massive lags still appear. So game for me still is almost unplayable.

**Comment by AngryPenguinPL** [comment]
> From 1121 your system looks to be under substantial memory pressure so that may play a part. As I mentioned in that issue the larger team is looking at all of this across all platforms.

I get my old unused 2 GB RAM memory and use it. Now I have 2x2 GB 1800 MHz CL9 + 2 GB 1333MHz CL9. So I lose dual channel but it work for testing.

When I play dota with this exotic 6 GB RAM I have free about +- 2.20 GB RAM but still get massive lags...

**Comment by AngryPenguinPL** [comment]
Hey.
I still have this issue, albeit, FPS is already good. It still annoying me to this heavy lag and in many times my game completly freeze and I need reboot PC.
After adding additional RAM to 6GB. Memory is not use in full, and even not in half!
See my cpu and memory usage from ending playing game and quit game: 
![desktop4](https://cloud.githubusercontent.com/assets/3121142/21940199/84bd40b6-d9c3-11e6-8e05-da4606467f3c.jpeg)

See, after latest patches, game not eat my full RAM but still gives me heavy lag.

Can I help debug this? Or help fix it in other way?

**Comment by gdrewb-valve** [comment]
If your system completely freezes you have a system problem such as a bad driver.  Trying different drivers may change your experience.  That's about all you can do.

The larger team is still looking at perf across all systems.  As it isn't a Mac/Linux problem there won't be a lot of status here but hopefully their work will help your case.

**Comment by gdrewb-valve** [comment]
The March 16th update had a variety of perf changes, did anything improve?

**Comment by AngryPenguinPL** [comment]
I think the performance is better. I played match on Friday, off line 1 vs 2 and FPS varied between 60 FPS. Of course in team fight my FPS dropped a bit, but I can see a noticeable improvement.

Thanks.

**Comment by gdrewb-valve** [comment]
OK, I'm going to close this.  There'll be more perf work over time from the Dota team (not just the porting team monitoring this tracker) and we're going to keep #1101 open.
