### ISSUE TITLE
[hero selection] text hero selection does not work upon entry

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1124]
Once I have a game and reach the hero selection screen, I type the first letters of the hero I want to select, but it does not work: I have to click first on the screen to be able to type the hero name

**Comment by gdrewb-valve** [comment]
This worked properly for me on my Linux box, we'll have to see if we can get a repro (or it has already been fixed).

**Comment by sylware** [comment]
On Thu, Dec 15, 2016 at 01:24:05PM -0800, Drew Bliss wrote:
> This worked properly for me on my Linux box, we'll have to see if we can get
> a repro (or it has already been fixed).

I noticed sometimes it works, sometimes it does not. I cannot figure out a reproductible way.

It seems related to keyboard focus as I noticed a similar issue: while watching
a live game, if I want to see the score board via the key shortcut, sometimes
it won't work till I mouse click on the screen.

**Comment by gdrewb-valve** [comment]
Is this still happening after the latest updates?

**Comment by sylware** [comment]
tested a few times, seems fixed. Both issues.

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by sylware** [comment]
nope it happened again.

I managed to get into a state where it happens again.

**Comment by sylware** [comment]
seems fixed. Cannot reproduce.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
