### ISSUE TITLE
Complete system freeze when selecting summoned units

### ISSUE THREAD

**Issue by velocitea** [ValveSoftware/Dota-2#1128]
The following bug occurs for me **since patch** 7 of Dota2:

**As soon as I want to select summoned units, the whole system freezes. I can not get back to my system, have to force a shutdown.**

Only when the summoned units are selected, the system freeze occurs.

This bug can **always be reproduced** on my system. I tested several kinds of summoned units, the system freeze always occurs. Tested summoned units: Illusions created by Shadow Demon's disruption, serpent wards from Shadow Shaman and Enigma's demonic conversion.

I use a Debian stable system with open source radeon graphic drivers.

Would be very happy, if this issue could get solved, since I can not play any heros with summoned units due to this severe bug.

Thanks in advance!

------ System information ------

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

*-memory
          description: System memory
          physical id: 0
          size: 7965MiB
     *-cpu
          product: Intel(R) Xeon(R) CPU E31230 @ 3.20GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 1964MHz
          capacity: 3600MHz
          width: 64 bits
*-display
                description: VGA compatible controller
                product: Barts PRO [Radeon HD 6850]
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:01:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: vga_controller bus_master cap_list rom
                configuration: driver=radeon latency=0

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD BARTS
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.3.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.0
OpenGL ES profile extensions:

**Comment by gdrewb-valve** [comment]
Dota is a normal user-mode process and cannot cause system lockups so your problem lies elsewhere, most likely in your graphics driver.  Have you tried different drivers or newer versions of Mesa?

**Comment by kisak-valve** [comment]
Hello @skrogul,

This issue was recently seen at #1103. Please update to a newer version of mesa. https://github.com/ValveSoftware/Dota-2/issues/1103#issuecomment-267242055 is what you are looking for in terms of a solution.

@gdrewb-valve, do we want to leave a note somewhere that Debian 8 users need to update mesa if they want to use Dota 2 with that graphics driver?

**Comment by gdrewb-valve** [comment]
Yes, go ahead and add a mention in the tracker description right after the recommendation to use NVIDIA 340 or newer.

**Comment by kisak-valve** [comment]
If updating mesa to 10.5.9 or newer does not help, please let us know and we can look into this further. Closing.
