### ISSUE TITLE
The captain mode window doesn't disappear

### ISSUE THREAD

**Issue by BrandonZV19** [ValveSoftware/Dota-2#1129]
After the draft time, I choose my hero, then the window never took off, I restarted dota client, restarted steam and restarted iMac.

The hero never appeared in game.

The images speak for themselves:

![570_screenshots_20161217123807_1](https://cloud.githubusercontent.com/assets/15038820/21288971/5782d494-c456-11e6-803d-dc0aa0357a31.jpg)
![570_screenshots_20161217122831_1](https://cloud.githubusercontent.com/assets/15038820/21288973/5a0f2d98-c456-11e6-993d-6282aeeacb0d.jpg)
![570_screenshots_20161217123416_1](https://cloud.githubusercontent.com/assets/15038820/21288974/5cd10efc-c456-11e6-9bb8-0cd78307ed89.jpg)
![570_screenshots_20161217122750_1](https://cloud.githubusercontent.com/assets/15038820/21288976/5eadd372-c456-11e6-8aed-d4a34f9c554d.jpg)

http://steamcommunity.com/id/alejandrozv19/screenshots/?appid=570

I can give more details if necessary.

**Comment by gdrewb-valve** [comment]
This is unlikely to be a Mac issue and probably won't be handled here, I'm checking with the larger team.

**Comment by gdrewb-valve** [comment]
This is happening on Windows too so the larger team will take it.
