### ISSUE TITLE
6.88 Replays UI & Other Glitches

### ISSUE THREAD

**Issue by Conzar** [ValveSoftware/Dota-2#1130]
I attempted to watch Game 3 of the OG/AF finals from Boston on a 7.0 client.  There are several problems:

- The UI spells & item icons are missing replaced with numbers
- Heroes appear to hover in some places of the map
- Wards appear to hover in some places of the map

http://imgur.com/a/2saTq

Overall, replays pre-7.0 are unwatchable due to these issues.

**Comment by gdrewb-valve** [comment]
This happens on Windows too and will be handled by the larger team.

**Comment by Conzar** [comment]
I think you should keep this open so that other isers won't create new issues.  Keep open until a fix has been released.

**Comment by gdrewb-valve** [comment]
This tracker is deliberately limited just to Mac/Linux bugs so that people looking for Mac/Linux advice can come here.  If it holds all issues of any kind until they are resolved it would quickly become overwhelmed with non-platform-specific entries.

**Comment by Conzar** [comment]
Can you please point me to the windows tracker for this issue?

**Comment by gdrewb-valve** [comment]
It's dev.dota2.com
