### ISSUE TITLE
dota 2 wont open, this always shows up whenever i try to launch it - how do i fix this

### ISSUE THREAD

**Issue by bregory** [ValveSoftware/Dota-2#1131]
![screen shot 2016-12-18 at 1 26 59 pm](https://cloud.githubusercontent.com/assets/24631183/21291720/d026381c-c525-11e6-917d-09d0eeca54a0.png)

**Comment by gdrewb-valve** [comment]
There's not enough information to go on.  Can you take the Steam system information and post it here as a gist?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
