### ISSUE TITLE
[Linux] Periodic FPS drops

### ISSUE THREAD

**Issue by sindrom91** [ValveSoftware/Dota-2#1133]
Every few minutes FPS drops massively and I can barely see anything happening, it lasts for ~15s and then FPS goes back to normal. I'm running fresh Ubuntu 16.04, on Intel HD graphics 4000 (I can post whole system information if necessary). I tried running with vulkan support, but it's happening that way as well (though spikes seem to last not as long).

I looked at `htop` at the moment of spikes and noticed that usage on all cores goes up by quite a bit (like 70%). Memory didn't seem to be a problem, I have 6GB of RAM and Dota was using around 30%.

I used to play Dota on this machine before 7.0 and this was not happening.

Also, it doesn't seem to be connected to any kind of special effects happening (spells), but more to do with number of units in the scene (not just heroes). I happens when demoing hero and just looking at creeps attacking each other.

Let me know if I can provide more info.

**Comment by gdrewb-valve** [comment]
I haven't seen that occur on my Linux box but my configuration is different.  We'll have to see if other people have the same issue to try and narrow down what might be causing it.

**Comment by sindrom91** [comment]
FPS drops don't actually seem to always be 15s. It looks like they start as 1-2s long and gradually prolong as the game progresses.

**Comment by Arakash** [comment]
hey. I have a similar issue - it's thermal throttling. I posted a comment at #1101 , heres a copy:

```
EDIT: I did some testing and i think i found the problem: In my case it's probably thermal throttling.
I'm using the lm-sensors package to check my temps (https://help.ubuntu.com/community/SensorInstallHowto ).

My temperature climb to about 93°C (yikes), then a fps drop occures until the temp is down to about 74°C again (~1,2s), at which the temp begins to climb again. Seems like my laptop has shitty cooling or my cpus just work overtime for some reason.
```

You can try it yourself. Unfortunately i didn't play on my laptop before 7.00 so i can't say if the dota 7.00  update is causing the heavy cpu load, or if my cooling is just bad.

**Comment by sindrom91** [comment]
I think you're right. I have pretty much the same results.

**Comment by gdrewb-valve** [comment]
@sindrom91 you think this is a cooling issue?  Should this issue be closed?

**Comment by sindrom91** [comment]
Yes, I would say so.

Closing the issue.
