### ISSUE TITLE
[Linux]Steam crashes when chatting in game

### ISSUE THREAD

**Issue by MinervaW1993** [ValveSoftware/Dota-2#1134]
Especially when receiving messages from others, Steam will segfault immediately.

CrashID=bp-f7702933-6911-420a-b709-dcd332161218

=====System information
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3000 Mhz
    32 logical processors
    16 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.13-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11900000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX TITAN/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.26
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1005
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                            59.8cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: USB Mixer
    
Memory:
    RAM:  24070 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  1456803 Mb
    Largest Free Hard Disk Block:  1008881 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Mon Dec 19 01:24:08 2016 GMT: file ''/tmp/dumps/crash_20161218190459_2.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:24:09 2016 GMT: file ''/tmp/dumps/assert_20161218190434_1.dmp'', upload yes: ''CrashID=bp-5af26112-2770-48b1-ad95-2a3b02161218''
    Mon Dec 19 01:24:09 2016 GMT: file ''/tmp/dumps/crash_20161218202409_2.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:24:10 2016 GMT: file ''/tmp/dumps/assert_20161218202409_3.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:24:11 2016 GMT: file ''/tmp/dumps/assert_20161218202410_5.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:26:10 2016 GMT: file ''/tmp/dumps/crash_20161218202432_2.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:26:14 2016 GMT: file ''/tmp/dumps/assert_20161218202418_1.dmp'', upload yes: ''CrashID=bp-f7702933-6911-420a-b709-dcd332161218''
    Mon Dec 19 01:26:15 2016 GMT: file ''/tmp/dumps/crash_20161218202614_3.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:26:18 2016 GMT: file ''/tmp/dumps/crash_20161218202617_5.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:30:12 2016 GMT: file ''/tmp/dumps/crash_20161218202635_2.dmp'', upload yes: ''Discarded=1''
    Mon Dec 19 01:45:09 2016 GMT: file ''/tmp/dumps/assert_20161218203359_1.dmp'', upload yes: ''CrashID=bp-3900ee44-b509-4f58-b406-9a6b82161218''
    Mon Dec 19 01:45:10 2016 GMT: file ''/tmp/dumps/crash_20161218204509_2.dmp'', upload yes: ''Discarded=1''

**Comment by MinervaW1993** [comment]
dmesg output:

[29701.870529] gameoverlayui[13153]: segfault at 0 ip 00000000f27073fb sp 00000000ffcd89d0 error 4 in vgui2_s.so[f2689000+260000]
[29757.084867] steam[12562]: segfault at 0 ip 00000000ef949e09 sp 00000000ffed7c70 error 4 in vgui2_s.so[ef8b7000+260000]

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Dota issue.
