### ISSUE TITLE
OSX no sound when pluggin in lan cable.

### ISSUE THREAD

**Issue by chrissisura** [ValveSoftware/Dota-2#1135]
I know this is nothing big, but maybe its really easy to solve. Basically i have no sounds whenever i plug in my lan cable and have to restart dota. 
macOS Sierra Version 10.12.2 MacBook Pro (Retina 13 Zoll, Early 2015) Processor 2,9GHz Intel Core i5, 8GB RAM 1867 MHz DDR3, Intel Iris Graphics 6100 1536MB

**Comment by gdrewb-valve** [comment]
So sound works up until you plug in your cable and then sound stops working?  Does it work again with your cable plugged in after you've started Dota?

I don't see issues like this with my Mac, I'm not sure why would be going on.

**Comment by chrissisura** [comment]
Seems to be fixed! Ty guys! Working fine now!

**Comment by joshlopes** [comment]
@chrissisura if you are having (which you most have!) fps issues using mac to play the game. Please create a ticket on http://www.apple.com/feedback/macbookpro.html

**Comment by gdrewb-valve** [comment]
Thanks, closing.
