### ISSUE TITLE
issue with latest update 21/12/2016 with built_from_cl.txt

### ISSUE THREAD

**Issue by shadowman79** [ValveSoftware/Dota-2#1137]
issue with latest update 21/12/2016 with built_from_cl.txt

steam reports built_from_cl.txt corrupted and trying to download files again without installation

**Comment by kisak-valve** [comment]
Hello @shadowman79, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Additionally, what filesystem is the game being stored on?

**Comment by gdrewb-valve** [comment]
Also additionally issues with the Linux Steam client should go in steam-for-linux.

**Comment by shadowman79** [comment]
fs: ntfs
https://gist.github.com/shadowman79/4fc7f63a6229d119d68b7e2ac8cb00f5

**Comment by kisak-valve** [comment]
This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4752. Closing as a duplicate.
