### ISSUE TITLE
Adding socket/gem to item crashes game

### ISSUE THREAD

**Issue by rudmint** [ValveSoftware/Dota-2#1139]
The game crashes when you add a socket to an item, and again when you add an inscribed gem.  There is nothing in the Recent Failure Reports, but I found this in kern.log;

Dec 25 13:08:55 razorwolfelite kernel: [276657.399504] traps: dota2[19015] general protection ip:7f0fef85d0a6 sp:7ffcf5596650 error:0 in libclient.so[7f0fec4fe000+4601000]

Dec 25 13:09:23 razorwolfelite kernel: [276685.181949] dota2[19110]: segfault at 0 ip           (null) sp 00007fff06d58aa8 error 14

**Comment by kisak-valve** [comment]
Hello @rudmint, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. Additionally, if you can find a relevant minidump in ```/tmp/dumps```, please compress it, then click and drag it into the comment box of this issue report.

**Comment by gdrewb-valve** [comment]
This is likely a cross-platform issue, I'm checking with the larger team.

**Comment by rudmint** [comment]
https://gist.github.com/rudmint/f51395951911319ed93a16548770d0cc

[crash_20161225130632_1.dmp.gz](https://github.com/ValveSoftware/Dota-2/files/673360/crash_20161225130632_1.dmp.gz)

**Comment by gdrewb-valve** [comment]
The larger team has asked what item you were using, do you remember?

**Comment by rudmint** [comment]
Zeus arcana, adding kills inscribed gem.

**Comment by gdrewb-valve** [comment]
Was this during a hero demo, a bot game or a regular game?

**Comment by rudmint** [comment]
It was not during a game, from the main menu > Heroes tab > Zeus > right click arcana > Item details > add socket (or gem).

**Comment by gdrewb-valve** [comment]
No repro here so far, we'll have to keep trying to make this happen.

**Comment by gdrewb-valve** [comment]
The larger team mentioned that they had made a change in the last update, does this still happen?

**Comment by rudmint** [comment]
This issue has been fixed, thanks.
