### ISSUE TITLE
[Linux] low graphics quality although options are high

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1142]
Hi.

Through Christmas I not played in Dota2. But after xmas, I play few match and I see another bug but don't know in which patch this bug was inserted...

When I start game with almost high graphic quality I see my game look much worse like on low quality (This can be seen particularly in the trees). Quick check on options and I see almost all on high. So going back to game and still I see low quality graphics. So I press F12 to make steam screenshot to seend this as bug and when I press F12 game quality back to high... Strange.
Worth to add I testing it few times and still have this bug and still help for me pressing F12... 
Also when I see this bad quality my performance is like on high - this same or almost same. It not better or worse when I press F12 it is still at the same level.

Proof of low quality: http://images.akamai.steamusercontent.com/ugc/100601835453904773/01208F7337D71C0DE8D7AB1E62CFC3A31CBF942E/

and

http://images.akamai.steamusercontent.com/ugc/100601835449185914/B699A6D9FA64201A9AF2E59DB7FAF5B596BF7211/

My quiality options for today is almost all on high: (rendering 100%, shadow high, textures high and **effect low** also with **no** grass, ambient occlusion, antyaliasing, vsync, specular reflection, blur lights / directional)

My Steam System Spec:
https://gist.github.com/AngryPenguinPL/1d36deeb8e62a48b9871069576bfb5c6

Don't know If this is related to my other issues with heavy lag when casting skill https://github.com/ValveSoftware/Dota-2/issues/1122 or using tp and havy RAM usage https://github.com/ValveSoftware/Dota-2/issues/1121

**Comment by gdrewb-valve** [comment]
If you just wait do things become sharper?  Do things switch between low and high quality and back ever?  Dota has a streaming load system where things can start lower quality and then become higher quality when loading completes.  Additionally there's dynamic GPU memory management where Dota may use lower-quality textures to save space if it feels like GPU memory is filling up.  Your GPU has 1GB, is that correct?  That should be enough to run in high quality so I wouldn't expect a lot of problems from that aspect of things.

**Comment by kolobos** [comment]
There are no shadows in the screenshots, that couldn't be just textures loading dynamically. This issue makes no sense, because no one else is experiencing video settings not applying in-game.

**Comment by danginsburg** [comment]
I'm having a bit of trouble understanding the issue, but I notice @xpris is using Catalyst 15.9 which is the last available AMD Catalyst driver for AMD 5xxx, but is rather old (September 2015).  If you are willing, I suspect you might do better with a recent radeonsi driver which supports Dota quite well on older AMD hardware.  I do recall a bug with an older Catalyst driver that caused shadows not to draw.  I don't have any theory on why grabbing a screenshot with the Steam Overlay is impacting the image.

**Comment by AngryPenguinPL** [comment]
Thanks for the answer.

At the beginning, I'm sorry for the difficulty in understanding my post - English is not my native language.

To illustrate problem I recorded a video from bot game, showing this issue. Look it here: 

https://www.youtube.com/watch?v=OCQFop9AuT8


Now answering questions:

> If you just wait do things become sharper?

No. I can play full match and still it look like this.

> Do things switch between low and high quality and back ever?

Don't know yet. I try it tomorrow.

EDIT: Ok, I trying it today. When I see low quality I trying change all game setting to low and back to high but I this not fix it. Still it look same. Only F12 helping.

> Your GPU has 1GB, is that correct?

Yes 1GB VRAM,

> using Catalyst 15.9 which is the last available AMD Catalyst driver for AMD 5xxx, but is rather old (September 2015). If you are willing, I suspect you might do better with a recent radeonsi driver which supports Dota quite well on older AMD hardware

Yes, Catalyst 15.9. Because my Linux distro - Mageia 5 still support it and it working well for some games like Dying Light (for example DL not working on open source driver). To be correct latest supporting is Catalyst 15.12 but from my tests it gives worse performance for me, so I stay on 15.9. 
Using RadeonSI? If I good remember it it only for HD7000+ and I have 5850 so if I should use open source for my GPU working only 3D driver - r600g but for now better not use it I think, because my distro Mageia 5 (this is stable distro) providing only Mesa 10.5.9 so this is old. For use new mesa 13 I need wait for upcoming Mageia 6 (don't know when it arrived, maybe month, two or more...) Also after Mageia 6 upcoming release only chose for my GPU is open source driver, so I use it for sure but don't know when. Compiling mesa from source? Too hard for me. So for now I need stay for catalyst also according for dota benchmark on phoronix I see hd5830 (similar gpu) gets on open source driver similar FPS compared to my hd5850 with old catalyst. So looking at the performance, I'd rather not have any profit.


> I do recall a bug with an older Catalyst driver that caused shadows not to draw.

I not have this issue before xmas. Last match before this issue appear I play in 22.12.2016, after this dota get few small patch. According to steamdb from 22 to 29 dota get 5 small updates. Maybe one broke somethings?

**Comment by danginsburg** [comment]
Thanks for the video.  So this issue still occurs for you with Catalyst 15.12?  If so, I will try to get setup to repro here.  It does look like when the screenshot is captured in the Steam Overlay that shadows get turned on.  I recall there being a driver bug on AMD OpenGL with shadows that I thought had been fixed (impacted Windows too), but perhaps it is still occurring if you see this on 15.12.  I understand your reasons for not wanting to switch to mesa.

**Comment by danginsburg** [comment]
Actually, I have confirmed this occurs even on AMDGPUPro 16.40 on RX480.  And I can confirm taking the screenshot in the overlay resolves the issue.  I'll look into it.

**Comment by danginsburg** [comment]
This also happens on Windows with AMD OpenGL on RX 480 16.12.1.  I narrowed this down to a glBlitFramebuffer call inside of the Steam Overlay that for unknown reasons causes the shadows to appear.  There is no logical reason why this should be the case, it appears to be an AMD driver bug.  I am going to follow up with AMD.

**Comment by AngryPenguinPL** [comment]
Playing today and yesterday few matchers and not see this issue. Look like it is fixed. Anyone can verify?

**Comment by gdrewb-valve** [comment]
Closing until we see reports that somebody is still affected by it.
