### ISSUE TITLE
[Mac OS] Setting hotkeys via Russian keyboard layout doesn't work

### ISSUE THREAD

**Issue by feelmyjoyfriend** [ValveSoftware/Dota-2#1145]
On Mac OS (any versions) setting hotkeys via Russian (cyrillic) keyboard layout doesn't work. It works only on English keyboard layout.

**Comment by kisak-valve** [comment]
Hello @feelmyjoyfriend,

In the Advanced Hotkeys section of the settings you should be able to check the 'Bind keys based on keyboard position.' Does that setting let you set your keybindings how you want?

Previously reported for linux at #792.

**Comment by gdrewb-valve** [comment]
Closing pending more information.

**Comment by feelmyjoyfriend** [comment]
Guys, it was so obvious and on the surface. Can't believe it. Tnanks, it really helped.
