### ISSUE TITLE
[Linux] no brightness slider

### ISSUE THREAD

**Issue by evaldobratti** [ValveSoftware/Dota-2#1146]
I have found #428, even though it's closed, there is no brightness slider in linux client

Mint 18.1/cinnamon

**Comment by kisak-valve** [comment]
Hello @evaldobratti, the brightness control is part of exclusive fullscreen mode, which is intentionally not provided by SDL on linux, noted at https://github.com/ValveSoftware/Dota-2/issues/63#issuecomment-189018420 for this issue. My current understanding is this is not going to change.

**Comment by evaldobratti** [comment]
I noticed that in windows the option is only available in exclusive fullscreen, but I thought it could be made available on linux in some way

Thanks for your answer and for your time :)

**Comment by vmavromatis** [comment]
@evaldobratti I know this is old, but as a workaround you can always adjust brightness with linux commands as such:

-  `xrandr --output DVI-D-0 --brightness 1.3` (mine is DVI-D-0 but you can get your monitor name with `xrandr -q | grep " connected"`). 

- However I found it's much better to just increase gamma in Dota: `xgamma -gamma 1.3`
