### ISSUE TITLE
[macOS] Can't display Chinese text 

### ISSUE THREAD

**Issue by liuerfire** [ValveSoftware/Dota-2#1147]
Show as the picture
<img width="1261" alt="screen shot 2017-01-06 at 21 02 08" src="https://cloud.githubusercontent.com/assets/745867/21718932/aca0e740-d455-11e6-8389-addeb2af4a8e.png">

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro11,3
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    MacOS 10.12.2 (64 bit)
    
Video Card:
    Driver:  Intel Iris Pro

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xd26
    Revision:  0x8
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                            33.1cm x 20.6cm  (38.9cm diag)
    Primary VRAM: 0 MB
    
Memory:
    RAM:  16384 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475978 Mb
    Largest Free Hard Disk Block:  185141 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
Can you be more specific about what you're expecting to see?  I can't read Chinese but it appears like there is quite a bit of Chinese text in the picture.  If you can point out exactly what's wrong or missing that could help narrow down the issue.  A screenshot of the same thing with English would be good for comparison.

**Comment by liuerfire** [comment]
Hi, @gdrewb-valve thanks for the reply. The text in the red box are missing or shown as mojibake. It should be ”包含于珍藏中“。
<img width="1261" alt="screen_shot_2017-01-06_at_21_02_08" src="https://cloud.githubusercontent.com/assets/745867/21727533/cacd883c-d47c-11e6-9a1d-7ec0554f610b.png">
Below is the screenshot with English
<img width="1152" alt="screen shot 2017-01-07 at 02 03 14" src="https://cloud.githubusercontent.com/assets/745867/21727728/a4f50602-d47d-11e6-9f87-01b8b12fc301.png">

**Comment by gdrewb-valve** [comment]
Are there any other problems or is it only the prices where things have issues?

**Comment by liuerfire** [comment]
Yes. There are several problems that can't display Chinese characters correctly in the game. 
1.  During the pick phase, if a player's name is written in Chinese and he sends some words in the chat box, the characters of his name is shown as "???" instead of the correct ones.
1.  In the game, if someone's statue is destroyed, the game message also can't display the player's name using "????" instead.

I forgot to make a screenshot. I would add the screenshots as long as I have.

**Comment by liuerfire** [comment]
@gdrewb-valve 
<img width="145" alt="screen shot 2017-01-07 at 13 30 11" src="https://cloud.githubusercontent.com/assets/745867/21739703/8713d4be-d4dd-11e6-8f1a-8a7787b8a622.png">
During the pick phase, the player's name disappeared or showed as a mojibake in the chat box.

**Comment by gdrewb-valve** [comment]
The Jan. 13th update has some macOS fixes, can you retest?

**Comment by liuerfire** [comment]
Thanks for the work. It's normal now.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
