### ISSUE TITLE
[macOS] can't connect to games

### ISSUE THREAD

**Issue by xrisk** [ValveSoftware/Dota-2#1148]
I can't load into games after accepting a seek. I can't even spectate any games. I just return to the main screen and get the option to reconnect which does not work.

This problem is only occurring on **one account**. On another account, I can connect to games just fine... There is nothing in the console worth mentioning. What can I do to diagnose the problem?

The only error is: `
[ResourceSystem] Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)`

and some more of the relevant bits from the console are:

```
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[Client] CL:  IGameSystem::LoopActivateAllSystems
[Host] HO:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.001533 seconds
[HostStateManager] Remote Connect (185.25.183.28:28065)
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
[Networking]       client   185.25.183.28:28065[0]:  high packet loss detected flow incoming:    0ms latency,     1/   13 dropped (7.7%)
[WorldRenderer] Long grass load frame: 10.007778 ms for 1578 grass tiles
[WorldRenderer] CWorldRendererMgr::ServiceWorldRequests long frame: 10.054156ms
[WorldRenderer] Long grass load frame: 10.000807 ms for 745 grass tiles
[WorldRenderer] CWorldRendererMgr::ServiceWorldRequests long frame: 10.036772ms
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
[Client] CL:  Receiving uncompressed update from server
Height map file (maps/start.vhcg) not found, this will make ground height traces more expensive! Recompile the map to generate a height map.
WriteSteamRemoteStorageFileAsync( "cfg/chat.cfg" ) -> at 67.848
[Client] CL:  Signon traffic "client":  incoming 175.540 KB [14 pkts], outgoing 35.321 KB [760 pkts]
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS'
[Client] CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_GAME_IN_PROGRESS
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 130 (1134 input number was)
[Client] CL:  Server disconnected: #GameUI_Disconnect_User
[Client] CL:  Disconnecting from server: #GameUI_Disconnect_User
[HostStateManager] CHostStateMgr::QueueNewRequest( Idle (levelload), 3 )
[EngineServiceManager] SwitchToLoop levelload requested:  id [3] addons []
[Client] CL:  IGameSystem::LoopDeactivateAllSystems
WriteSteamRemoteStorageFileAsync( "cfg/chat.cfg" ) -> at 68.429
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 68.431
[Host] HO:  IGameSystem::LoopDeactivateAllSystems
Unloading custom UI:
[Client] CL:  CGameRulesGameSystem::GameShutdown uninstalled game rules
[Client] CL:  CGameRules::CGameRules destructed
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 68.804
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
```

**Comment by gdrewb-valve** [comment]
This isn't a Mac issue, I've passed it on to the larger team.  They might have questions so keeping this open for the moment.

**Comment by gdrewb-valve** [comment]
According to the larger team your client is disconnecting itself (the #GameUI_Disconnect_User line).  If you validate your install does that help?

**Comment by xrisk** [comment]
Yes I have tried that, along with restarting my computer and steam :)

**Comment by xrisk** [comment]
I could paste more stuff from the console, but it seems like there is no way to way to copy large parts of text from the console, as it does not support scrolling while selecting.

**Comment by gdrewb-valve** [comment]
The larger team isn't sure what's going on.  They'll keep looking but there won't be much status here.

**Comment by gdrewb-valve** [comment]
Do you have any kind of .cfg file in use, launch options or any other modifications active?

**Comment by xrisk** [comment]
None. I will try reinstalling Dota though.

 Demo mode seems to work, as does queueing into a game through the lobby. Spectating does not work. I haven't tried to load into another game yet after failing twice, for fear of getting a long timeout. What's weird though is that spectating etc works fine on another account on the same computer. I have not tried loading into a game using the other account though.

**Comment by gdrewb-valve** [comment]
Thanks.  The larger team is going to try and add some more checks to narrow down what's going on, they'll ship in a future update.

**Comment by xrisk** [comment]
Thanks for your help

**Comment by gdrewb-valve** [comment]
Did you get any new messages or errors with recent updates?

**Comment by xrisk** [comment]
Hey, it was my fault all along. I had put `-override_vpk` in my launch settings and forgotten to remove it. Sorry for the inconvenience. 🙁

**Comment by gdrewb-valve** [comment]
Thanks for letting us know.
