### ISSUE TITLE
[Linux] Unpause Desktop Notification

### ISSUE THREAD

**Issue by BrendanBall** [ValveSoftware/Dota-2#1149]
Apparently dota 2 does give a desktop notification on windows when unpausing. However this doesn't happen on Linux. The "game is ready" notification works fine and gets sent through libnotify so I'm pretty sure this is a bug. The fact that I'm using unsupported Linux distro should be irrelevant seen as the "game is ready" notification works. Also I'm pretty sure someone can easily reproduce this on a supported Linux distro. As long as you're using libnotify and have a working notification server running it should work the same on every Linux distro.

Reproduce:
While paused in dota switch to another window so that you're not focused in dota. have someone else unpause dota. Expected behaviour is to get a notification through libnotify, but nothing happens.

System information:
Linux - Arch Linux
Window Manager - i3
Notifications - libnotify

**Comment by gdrewb-valve** [comment]
Jan. 11th's update should add these.

**Comment by admshao** [comment]
Works for me now.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
