### ISSUE TITLE
Hero demo mode not working

### ISSUE THREAD

**Issue by kencals02** [ValveSoftware/Dota-2#1150]
Clicks demo mode, loads then goes back to main menu saying "Unable to load map specified by server."

**Comment by gdrewb-valve** [comment]
Can you post your system info from Steam?  Have you verified your install?

**Comment by kencals02** [comment]
Computer Information:
    Manufacturer:  MICRO-STAR INTERNATIONAL CO.,LTD
    Model:  MS-7529
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Pentium(R) Dual-Core  CPU      E5500  @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2799 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Windows XP (32 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
    
Video Card:
    Driver:  NVIDIA GeForce GT 220

    DirectX Driver Name:  nv4_disp.dll
    Driver Version:  6.14.12.8026
    DirectX Driver Version:  6.14.12.8026
    Driver Date: 3 Aug 2011
    OpenGL Version: 3.3
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GT 220
    VendorID:  0x10de
    DeviceID:  0xa20
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 16.77" x 9.45"  (19.21" diag)
                                            42.6cm x 24.0cm  (48.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 
    
Sound card:
    Audio device: Realtek HD Audio output
    
Memory:
    RAM:  2047 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  476937 Mb
    Largest Free Hard Disk Block:  118093 Mb
    OS Install Date: Apr 10 2015
    Game Controller: None detected
    VR Headset: None detected
    
I verified it twice and reinstalled it once.

**Comment by gdrewb-valve** [comment]
This tracker is only for Mac and Linux-specific bugs, you'll want to report this at dev.dota2.com

**Comment by kencals02** [comment]
Oh ok
