### ISSUE TITLE
[MAC OS] Using Microphone in-game causes huge lag spikes

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#1152]
When I use my microphone in game (demo mode,actual game or anything) the game freezes for a good 2 seconds. 

Recently I updated my operating system to the latest version 10.11.6 (64 bit), perviously I was on 10.11.2 so I suspect something happened in between.

Something else that I might suspect is the update of the Nvidia driver I'm using to work with the newest update of the OS, so I'll later test with native drivers as well.

Here's my steam information:

Computer Information:
    Manufacturer:  Apple
    Model:  iMac13,2
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    MacOS 10.11.6 (64 bit)
    
Video Card:
    Driver:  NVIDIA GeForce GTX 680MX

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x11a3
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.46" x 13.19"  (26.89" diag)
                                            59.6cm x 33.5cm  (68.3cm diag)
    Primary VRAM: 0 MB
    
Memory:
    RAM:  24576 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  2860420 Mb
    Largest Free Hard Disk Block:  670888 Mb
    VR Headset: None detected

**Comment by Vuccappella** [comment]
Issue seems to be resolved after the latest update, not sure how.No lag when using microphone.

**Comment by kisak-valve** [comment]
Thanks for the feedback @Vuccappella, closing for now.
