### ISSUE TITLE
[Ubuntu]Dota is having a hard time registering all users inputs in the game

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1153]
I don't know how to explain this in a better way than this.

Armlet toggle sometimes doesn't tick. Tread switching eventually fails as well. In general, whenever there is multiple inputs almost at the same time eventually a couple of inputs seems to be lost. I had to say it wasn't that evident prior 7.0

**Comment by gdrewb-valve** [comment]
People are reporting this on all platforms, the larger team is investigating.  I don't have any status on what they're doing or if they've found issues, unfortunately, but hopefully future updates will improve things.
