### ISSUE TITLE
Linux - problems installing OpenGL support for DOTA 2

### ISSUE THREAD

**Issue by Kentavr1982** [ValveSoftware/Dota-2#1154]
"Required OpenGL extensoin "GL_ARB_separate_shader_abjects@ is not supported. Please update your OpenGL driver."

**Comment by Kentavr1982** [comment]
Собственно обновляем OpenGL:
$ sudo add-apt-repository ppa:oibaf/graphics-drivers
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install libegl1-mesa libegl1-mesa-drivers xserver-xorg-video-intel libgl1-mesa-dri libglapi-mesa mesa-vdpau-drivers

but... 

Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Заметьте, вместо «mesa-vdpau-drivers» выбирается «mesa-vdpau-drivers-lts-trusty»
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 mesa-vdpau-drivers-lts-trusty : Зависит: libgl1-mesa-dri-lts-trusty но он не будет установлен
E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.

**Comment by gdrewb-valve** [comment]
As this isn't a problem with Dota itself this is outside the scope of this tracker.  I've edited the title to make it more clear it's an OpenGL installation problem and it's possible other users might have advice, but you'll want to ask on forums for your Linux distribution too.

**Comment by kisak-valve** [comment]
Hello @Kentavr1982, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```).

**Comment by Kentavr1982** [comment]
i deinstall ubuntu and reinstall... new problem:

Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for evgeniy: 
Sorry, try again.
[sudo] password for evgeniy: 
..................................................................................................................................
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 libgl1-mesa-glx:i386 : Зависит: libglapi-mesa:i386 (= 8.0.4-0ubuntu0.7)
E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.
Press return to continue:

**Comment by Kentavr1982** [comment]
evgeniy@evgeniy-Inspiron-3542:~$ sudo apt-get install ia32-libs
[sudo] password for evgeniy: 
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 ia32-libs : Зависит: ia32-libs-multiarch
E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.
evgeniy@evgeniy-Inspiron-3542:~$

**Comment by Kentavr1982** [comment]
restart ubuntu:

Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for evgeniy: 
.................................................................................................................................
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 libgl1-mesa-glx:i386 : Зависит: libglapi-mesa:i386 (= 8.0.4-0ubuntu0.7)
E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.
Press return to continue:

**Comment by Kentavr1982** [comment]
In window:

error

You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6

**Comment by Kentavr1982** [comment]
After -- in менеджер обновлений: "launcher for steam software distribution service" --> install it

**Comment by kisak-valve** [comment]
@Kentavr1982, Dota 2 requires at least mesa 10.5.9 to work with the open-source driver. Please update to a distro release that supports this version or newer. Beyond that it appears you are encountering one or more distro-specific packaging issues which is outside the scope of this issue tracker. Please use the forums or reach out to your distribution's community for support.

**Comment by Kentavr1982** [comment]
My version UBUNTU:
 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	**Ubuntu 12.04.5 LTS**
Release:	12.04
Codename:	precise
uname -r
**3.13.0-107-generic**


It's latest version: 

sudo apt-get dist-upgrade
[sudo] password for evgeniy: 
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Расчёт обновлений…Готово
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.

**Comment by Kentavr1982** [comment]
How i install  mesa 10.5.9?
ppa?

my dist support mesa 10.5.9?
