### ISSUE TITLE
Portrait Avatar no longer targetable

### ISSUE THREAD

**Issue by BrendanBall** [ValveSoftware/Dota-2#1159]
I use quickcast so I can't double tap abilities to self cast. Thus I have to use the portrait to self cast as it's the second quickest way to self cast. Imagine my surprise when my glimmer cape isn't working because the avatar is no longer targetable. I found there is a tiny area on the portrait that is still targetable. maybe like 1/15 of the portrait in a random location.
Can we please make the avatar targetable again? It's impossible to play like this when using quickcast.

OS: Linux
graphics: vulkan

**Comment by gdrewb-valve** [comment]
This isn't a Linux issue so it won't be handled here, the larger team will address it.
