### ISSUE TITLE
[Linux] No Microfone Sound when casting inside Lobby on Draft.

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1160]
On the last 3 days during a broadcast inside Lobby some viewers reported that the microfone of casters wasn't working while in the draft in captains mode. 

As soon as the game started all sound was just fine.

**Comment by gdrewb-valve** [comment]
Can you include a reference to a gist of your system info?  It's helpful to have it in every issue.

However this is likely not a Linux issue, I'll check with the larger team.

**Comment by admshao** [comment]
General info-> Ubuntu 17.04, Gnome 3.22, kernel 4.9.4

Steam Info -> https://gist.github.com/admshao/b5e19f1521d20e8ce3fda1d81984f080

**Comment by gdrewb-valve** [comment]
The larger team had a question: did you notice this while watching DotaPit matches?  They also mentioned that it's common for tournaments to have the analysts desk cast the drafting phase then switch to the in-game casters after the draft.

**Comment by admshao** [comment]
While Broadcasting DotaPit. I did the official coverage in PT_BR inside the
lobby so it was our mics that wasn't working while on draft. Our viewers
reported on twitch chat and than i could confirm that while on Draft phase
the Sound indicator on the right corner of the screen was always muted and
as soon as the heroes entered the game all started to work fine.

2017-01-23 18:56 GMT-02:00 Drew Bliss <notifications@github.com>:

**Comment by gdrewb-valve** [comment]
Thanks, I've passed this on and the larger team will take it from here.  I'm not sure if there'll be more direct feedback.

**Comment by admshao** [comment]
Yesterday i could finally cast another game from the lobby, it was DAC AM qualifiers and it was capturing my microfone while on the draft. Dunno if something was changed but i would say its fixed for me.

**Comment by admshao** [comment]
I found out today what must have been the issue after all. As i co-cast the matches i have a bunch of tabs opened in the other monitor to get teams stats live and as i hit ALT TAB the microphone ingame stops being captured.  I only alt tabed while on draft hence our viewers reports on mic issue while on draft.

Since i do have "Sound while another window is active" in sound settings checked. Could i request that the microphone could still be captured as well while on alt tab?

I'm trying to alt tab less while on the draft but it would help me a lot.

**Comment by Cabanur** [comment]
I think an average user would expect the mic to be muted if alt-tabbed with
this option checked.

Un saludo,
Pau Gisbert

2017-02-09 17:54 GMT+01:00 admshao <notifications@github.com>:

**Comment by gdrewb-valve** [comment]
I don't know what the larger team would say but you're welcome to post a feature request at dev.dota2.com
