### ISSUE TITLE
Wrong installscript.vdf

### ISSUE THREAD

**Issue by felipec** [ValveSoftware/Dota-2#1165]
I know this is not a Linux related issue, but I don't know where to report Windows issues, and this one is really easy to fix.

There's an annoying UAC message every time Dota 2 is launched because the installscript.vdf script is wrong, it has the path "%INSTALLDIR%\\DirectX\\DXSETUP.exe" but there's nothing there, so nothing is installed, and so this message pops up again, and again, even though Steam already installs Direct X, probably with CommonRedist or whatever.

On the Internet people suggest editing this file, or the registry, but I think Valve should fix this.

**Comment by gdrewb-valve** [comment]
You'll want to report this at dev.dota2.com
