### ISSUE TITLE
DARK MOON: Unable to load map specified by server

### ISSUE THREAD

**Issue by rmiguelc** [ValveSoftware/Dota-2#1166]
Hello.

When loading the Dark Moon match, the error on title is displayed.

**Comment by kisak-valve** [comment]
Hello @Xingdao-Fan, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Hello @Xingdao-Fan, there is no 32 bit client on Mac or Linux (which is the focus of this issue tracker). Related to http://dev.dota2.com/showthread.php?t=276570.

**Comment by Xingdao-Fan** [comment]
Using winXP sp3 here.

**Comment by Cabanur** [comment]
This issue tracker is focused for the Linux and Mac OS client. Consider reporting your issues at dev.dota2.com instead, as Kisak already said.

**Comment by Xingdao-Fan** [comment]
Ah, I was unaware this was targeted at only those operating systems. My apologies. Thanks for the attention.
