### ISSUE TITLE
[Linux] Corrupt update files

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1169]
Hi.

From week I not play in dota, so today I get to download one or two patch at one - about 800 MB and after steam finish download it I starting dota 2 but dota quit to desktop immediately after the show menu.

So I trying verify game cache and I see that 23 files is corrupt. So steam download 800 MB again but when download is finished I see still error "corrupt update files".

Trying verify four times and still have this issue. Trying delete /SteamLibrary/steamapps/downloading/570/ folder and start steam again and again download update but still have this issue. 
Also trying clearing memory download cache in steam > settings > downloads but still is the same.
Also when I trying launch game from desktop icon, steam start download incorrect files and after fail it I see new window with message: "[...] Corrupt update files: /media/Dane/SteamLibrary/steamapps/downloading/570/game/dota/pak01_070.vpk [...]"

Worth to add, some times ago I have similar issue here: https://github.com/ValveSoftware/Dota-2/issues/1098
but then I had the game on an NTFS partition, then helped install a new game on EXT4. Now my game is still on this new EXT4 and have issue.

Also I see this closed issue https://github.com/ValveSoftware/Dota-2/issues/1163 and @gdrewb-valve said something about checking the file libclient.so, and I see this file not even exist on my game folder.

So is any way to fix it?

Steam PC spec: https://gist.github.com/AngryPenguinPL/1d36deeb8e62a48b9871069576bfb5c6

My latest crashes: 
Ostatnie raporty niepowodzeń:
    Mon Jan 30 16:42:53 2017 GMT: file ''/tmp/dumps/crash_20170130174218_1.dmp'', upload yes: ''Discarded=1''
    Mon Jan 30 16:43:14 2017 GMT: file ''/tmp/dumps/crash_20170130174300_1.dmp'', upload yes: ''Discarded=1''
    Mon Jan 30 16:59:09 2017 GMT: file ''/tmp/dumps/assert_20170130175905_107.dmp'', upload yes: ''CrashID=bp-3187896d-d6fa-471f-af1b-bd1f42170130''
    Mon Jan 30 17:19:11 2017 GMT: file ''/tmp/dumps/crash_20170130181907_28.dmp'', upload yes: ''CrashID=bp-47e78fec-cca5-4fb0-899b-0bb442170130''
    Mon Jan 30 17:42:19 2017 GMT: file ''/tmp/dumps/assert_20170130184213_67.dmp'', upload yes: ''CrashID=bp-f39fe540-4230-4336-98d5-ab62c2170130''
    Mon Jan 30 17:46:24 2017 GMT: file ''/tmp/dumps/assert_20170130184620_26.dmp'', upload yes: ''CrashID=bp-34f39f5e-682d-44e8-af2b-d1a9c2170130''

EDIT:
Also when I run steam in terminal and trying update game (and get corrupt files error) I see this in terminal output:

Installing breakpad exception handler for appid(steam)/version(1484790260)
Installing breakpad exception handler for appid(steam)/version(1484790260)
depotreconstruct.cpp (493) : Assertion Failed: pInfo->nNumWritesFinished > 0
Assert( Assertion Failed: pInfo->nNumWritesFinished > 0 ):depotreconstruct.cpp:493

Installing breakpad exception handler for appid(steam)/version(1484790260)
assert_20170130203043_27.dmp[11793]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170130203043_27.dmp
assert_20170130203043_27.dmp[11793]: Finished uploading minidump (out-of-process): success = yes
assert_20170130203043_27.dmp[11793]: response: CrashID=bp-38155aeb-f2a2-4c2b-b849-6eeb82170130
assert_20170130203043_27.dmp[11793]: file ''/tmp/dumps/assert_20170130203043_27.dmp'', upload yes: ''CrashID=bp-38155aeb-f2a2-4c2b-b849-6eeb82170130''

EDIT 2: Trying use other download region - still the same issue.

EDIT 3: Remove game and deleting all stuff from game id 570 and fresh install also not help. Steam downloading full 7.1 GB and after downloading I get error incorrect game files.

EDIT: 4 Opt to steam beta also not helping.

Edit: 5 Copy game files from my default EXT4 filesystem to unused NTFS - not help.

EDIT: 6 Game update on EXT4 still not want work but I found workaround. So like I said before, I trying moved game files to ntfs but still have the same issue but when I use this solution: https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-271763278 
it start working on NTFS. So when game start working fine, I moved it back to EXT4 and now working fine.
So this is not a fixed but we have small workaround.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Dota issue.
