### ISSUE TITLE
[Linux][Vulkan] Segmentation fault when spectating and sometimes loading up a game 

### ISSUE THREAD

**Issue by LamerTex** [ValveSoftware/Dota-2#1170]
Game crash with a segmentation fault (dumbs file attached) when vulkan is enabled (doesn't seems to crash without vulkan). When entering a game as spectator it crash every time, if i try to load up a lobby or a custom game doesn't happen all the times only some times. In the New Bloom game mode it has never crashed.

[lamertex_stdout.txt](https://github.com/ValveSoftware/Dota-2/files/744559/lamertex_stdout.txt)
[crash_20170201111912_1.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/744570/crash_20170201111912_1.dmp.txt)

System Spec:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3401 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 14.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-107-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.20
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1294
    Primary Display Size: 20,08" x 11,30"  (23,03" diag)
                                            51,0cm x 28,7cm  (58,5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  7936 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  it_IT.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  938771 Mb
    Largest Free Hard Disk Block:  622092 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Wed Feb  1 10:17:52 2017 GMT: file ''/tmp/dumps/crash_20170201111721_1.dmp'', upload yes: ''Discarded=1''
    Wed Feb  1 10:19:45 2017 GMT: file ''/tmp/dumps/crash_20170201111912_1.dmp'', upload yes: ''CrashID=bp-af9c5030-b5e1-4d27-827b-75f102170201''
    Wed Feb  1 10:30:21 2017 GMT: file ''/tmp/dumps/crash_20170201112929_1.dmp'', upload yes: ''Discarded=1''
    Wed Feb  1 10:31:24 2017 GMT: file ''/tmp/dumps/crash_20170201113048_1.dmp'', upload yes: ''Discarded=1''
    Wed Feb  1 10:34:02 2017 GMT: file ''/tmp/dumps/crash_20170201113210_1.dmp'', upload yes: ''Discarded=1''

**Comment by kisak-valve** [comment]
Hello @LamerTex, since this occurs with the vulkan backend, but not the opengl backend, let's track this issue in the Dota-2-Vulkan issue tracker.
