### ISSUE TITLE
observer ward simulator does not work with mesa and catalyst

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1174]
up-to-date beta steamos (mesa 13 or catalyst, AMD GPU TAHITI XT)
up-to-date beta steam client

Once placing a ward, the "observer ward simulator" does not work. Only a circle is displayed.

**Comment by kisak-valve** [comment]
Most likely not an OS-specific issue. Related: https://www.reddit.com/r/DotA2/comments/5sxyg8/the_new_observer_fow_simulator_is_messing_up_on/

**Comment by gdrewb-valve** [comment]
Your title suggests a problem on specific drivers, have you seen it working otherwise on different drivers?

**Comment by sylware** [comment]
On Thu, Feb 09, 2017 at 08:39:40AM -0800, Drew Bliss wrote:
> Your title suggests a problem on specific drivers, have you seen it working
> otherwise on different drivers?

Nope. Just tested it on AMD GPU TAHITI XT with mesa 13 and catalyst. No idea if
it works with anything else.

**Comment by gdrewb-valve** [comment]
OK, it's likely the all-platforms issue that kisak mentions and the larger team will take a look.

**Comment by sylware** [comment]
I managed to make it half-work.

It works the same in catalyst or mesa. You _must_ have at least "med shadows" on, then it will work _only_ for observer wards, but whatever the setting levels are, I cannot get anything for sentry wards.

(for you information, catalyst performance is disastrous compared to mesa, to a ridiculous point easy 30% better with mesa than catalyst)

**Comment by AngryPenguinPL** [comment]
Same here on Catalyst 15.9

**Comment by sylware** [comment]
huhu... actually the simulator does not make any sense on sentries... my bad.

Then people should be told to enable at least "med shadows" in order to get the simulator! 

@AngryPenguinPL do really use mesa instead of catalyst, you'll get a 20-30% faster dota2.

**Comment by gdrewb-valve** [comment]
The problem with the ward display not showing up with shadows disabled is cross-platform and will be fixed by the larger team.  It sounds like that covers things for this issue and this can be closed?

**Comment by sylware** [comment]
yep, fine by me.
