### ISSUE TITLE
Game freezes upon loading

### ISSUE THREAD

**Issue by lewisdiamond** [ValveSoftware/Dota-2#1177]
When launching Dota, the game freezes as it renders the friends list and the account information.

Must `kill -9` to close it.

https://www.reddit.com/r/DotA2/comments/5tx2s4/new_patch_freezes_dota_on_start_volvo_plz_rollback/

**Comment by gdrewb-valve** [comment]
This tracker is only for bugs specific to Mac and Linux and that problem is hitting everybody.  The larger team is working on a fix.

**Comment by lewisdiamond** [comment]
Sure, I needed to make sure the message went across. Thanks for the feedback.
