### ISSUE TITLE
Steam browser is 125-150% scale in Dota2

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Dota-2#1178]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/4863.
@artemjackson posted on 2017-02-16T17:27:26:

#### System information

* Steam client version (build number or date): steam 1.0.0.54-1
* Distribution: ArchLinux Kernel 4.9.8-1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected steam browser to be 100% scale. But the browser is 125-150% scale (see screenshots below) so content doesn't fit the page.

#### Steps for reproducing this issue:

1. Open Dota2 client
2. Visit any of news on main page

![screenshot from 2017-02-16 20-24-34](https://cloud.githubusercontent.com/assets/3768221/23032626/bb71800c-f47d-11e6-9591-e82fd0b92e9d.png)
![screenshot from 2017-02-16 20-24-29](https://cloud.githubusercontent.com/assets/3768221/23032631/bd8b8856-f47d-11e6-9184-444d1782e7e7.png)

**Comment by kisak-valve** [comment]
For what it's worth, on Gentoo Linux I was able to get libcef to zoom in once, with what I assume was ctrl + "+", but I was unable to reliably reproduce this behavior and reloading the page reset it to 100%.

Edit: Ctrl + "+" immediately after clicking the Kiev Major tile causes zoom, then the key combination is disabled.

**Comment by artemjackson** [comment]
@kisak-valve Can confirm the issue
I was able to zoom out (`Ctr` + ` - `)  only  once (from probably 150% to 125% scale) after that key combination is disabled.

Re-opening the page resets the scale to 150% again :(

**Comment by kisak-valve** [comment]
@artemjackson, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

I suspect this is a locale related issue. Does adding `LANG=C %COMMAND%` to the start of the game's launch options change the behavior of this issue?

**Comment by gdrewb-valve** [comment]
Dota uses the ISteamHTML page rendering support so this'll need to be looked at by the Steam team, there may not be many updates here.

**Comment by artemjackson** [comment]
@kisak-valve do you want a joke? Opening `Steam` -> `Help` -> `System Information` cause steam crash :rofl:  See the [log](https://gist.github.com/artemjackson/0f7d25717492d0871d3121339f81eb16) if interesting.

Okay, but I also have `steam-native` package that works without steam runtime but with native libraries. So I was able to check `System Information`. The gist is [here](https://gist.github.com/artemjackson/970d96cc211e9de2aae4e117f086ab75).

Btw, `LANG=C %COMMAND%` doesn't solve the issue.

**Comment by artemjackson** [comment]
Hey, guys, the issue seems to be fixed after the patch v7.06.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
