### ISSUE TITLE
[Linux] Push to talk doesn't work

### ISSUE THREAD

**Issue by carlosg-gh** [ValveSoftware/Dota-2#1181]
- what platform this is occuring on: Linux
- a short, descriptive title: The push to talk key seems like it's not being recognized by the game, thus being unable to use push-to-talk.
- a detailed description of the issue, including any output from the command line: When trying to bind a key to push to talk, everything works fine. However, when you press said key the game seems to not recognize it. This bug differs with #384 because ingame it doesn't show anything at all. The microphone works properly when using open voice chat, so I believe the issue must be caused by the push to talk key. I've tried different solutions: I've tried different keys, both in the team chat and the party chat. I've tried to reset the key bindings, and I've tried to manually map the key with the console using "bind key +voicerecord". None of them worked.
- steps for reproducing the issue: Setting up your microphone to push-to-talk, then trying to speak using said push to talk key

### System information

- [Gist with system info provided from steam here](https://gist.github.com/Kurolox/a93b06c047923e259dd6fc136739c4ce)
- Linux distro: Arch Linux 4.9.8
- Desktop/Window Manager: i3-gaps
- Graphics card: Nvidia GTX 770, using propietary drivers 378.13
- anything else: The microphone model is a samson meteor. It works perfectly in every other application (even in DotA, as long as the setting is set to open voice). I can try to provide logs and any other info if needed. Using pulseaudio. The microphone settings should be configured properly (mostly because, as I stated before, it works when using open voice.) [Here's a gist with the dota 2 console output at startup. It may be relevant.](https://gist.github.com/Kurolox/97451aa7322d9039e1dea7471945ace2)

**Comment by gdrewb-valve** [comment]
This is unlikely to be Linux-specific but we'll get some more info first.

What key are you using for your PTT key?  Does it show up properly in the bindings after you've set it?  If you temporarily test with a simple letter key like V does it work then?

**Comment by carlosg-gh** [comment]
I'm using scroll lock (Well, caps lock, but I've exchanged the functions of scroll lock and caps lock at an OS level). It does show up properly in the bindings. I've tried with other keys (O, P, Numpad5, V) but none of them worked.

**Comment by gdrewb-valve** [comment]
I'm not seeing any problems on my Linux box, but maybe others will chime in here.

**Comment by Cabanur** [comment]
I use Super (Windows key), no problem.

Debian testing (Linux 4.9), KDE Plasma 5.8. Steam beta channel.

**Comment by kisak-valve** [comment]
Hello @Kurolox, since you have a more exotic keyboard configuration, can you select Settings -> Advanced Hotkeys -> Bind keys based on keyboard position, then reset your keybindings and see if that gives you the behavior you are looking for. It's possible SDL2 is getting confused.

**Comment by gdrewb-valve** [comment]
This may be completely unrelated but at #1187 a user reported having microphone problems that spontaneously resolved themselves.  Has anything changed with this recently?

**Comment by gdrewb-valve** [comment]
The latest Steam client beta has some voice support changes, does it help?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
