### ISSUE TITLE
dota 2 wont launch on my imac please help!!!

### ISSUE THREAD

**Issue by sawdap** [ValveSoftware/Dota-2#1182]
Few hours ago, i just installed steam and dota2 on imac and it seems going pretty well until i press play then it said "preparing dota2" and nothing happen. i hv read some comments and tried to apply it but still it cant launch. please help me solve this

**Comment by kisak-valve** [comment]
Hello @sawdap, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gdrewb-valve** [comment]
You'll also want to verify your install of Dota in the Steam client.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
