### ISSUE TITLE
side hero info panel is destroying rendering performance

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1183]
up-to-date beta SteamOS with mesa 13 drivers on AMD tahiti xt GPU.
up-to-date beta steam client.

In a game, click on an hero to get the side hero info panel (must not have enabled the option to display the hero info in the main panel), fps gets a massive 50% drop while the panel is displayed.

**Comment by gdrewb-valve** [comment]
Perf drops happen on all platforms and very widely with the system.  The larger team is looking at these kinds of issues.

**Comment by gdrewb-valve** [comment]
Also you can turn off the side panel if you want to avoid the perf drop.

**Comment by sylware** [comment]
@gdrewb-valve yep, did that.

**Comment by gdrewb-valve** [comment]
Closing this out as it isn't Linux-specific.
