### ISSUE TITLE
[macOS] Crash on ordering user channels

### ISSUE THREAD

**Issue by paskal** [ValveSoftware/Dota-2#1184]
Hello, team.

When I access "Channels" window (on screenshot) and click twice on "Channel Name" or once on "Members" in **Users** tab, client crashes without any error messages.
![image](https://cloud.githubusercontent.com/assets/712534/23320005/0a2bb86c-faea-11e6-9ff9-482d0917b6b1.png)
~Sorting in other tabs working fine.~ I'm sorry, but I didn't found crash report location. OS version is 10.12.3 (16D32).
**Update**: _Regional_ sort by distance works with no problems, by channel name - crash on second click.
_User_ sort by channel name crashes on second click (so I see ABC order, but crash instead of ZYX order) and crash on first click on members column header.
_Custom games_ sort by channel name and members works with no problems.
_Private_ (empty) works with no problems.
If I go to _Custom games_ and sort fields a dozen of times, just a click on _User_ tab crashes the client.

**Comment by gdrewb-valve** [comment]
No repro for me on my Mac.  Can you put your full Steam system information (available from the Help menu in the Steam client) in a gist?

If there aren't any failure reports in the Steam system information it often means it's an OpenGL driver issue.

**Comment by paskal** [comment]
Here it is.
[system_information.txt](https://github.com/ValveSoftware/Dota-2/files/800617/system_information.txt)
