### ISSUE TITLE
Changing official info input value is bugged when you are in a lobby and some other person enters an empty lobby slot

### ISSUE THREAD

**Issue by dharmawankenny** [ValveSoftware/Dota-2#1186]
As the title stated, its a minor bug, yesterday i played on a lobby with my friends, i was already filling an empty slot and i wanted to change my official info so i did.

And then when i was writing on the input boxes, one of my friend joined and fill an empty slot, suddenly my input boxes value changed to my friend's official info.

However, i think its only a visual bug because when i try to save it as is (using my friend official info, it wont save.

How to repro:

make a lobby, join a slot, edit your official info, make other person join the lobby, make them fill an  empty slot, and you will see the input values will be the same as the other person official info (even the team name even though you are not registered to the other person team, your select box value will be that other person team)

Its a minor bug, but i think ill report it here. Thanks

**Comment by gdrewb-valve** [comment]
Thanks.  This isn't likely to be a Mac/Linux-specific bug so it's not the kind of thing that would be tracked here.  I'll pass this on but I'm closing the issue.

**Comment by dharmawankenny** [comment]
@gdrewb-valve ah sorry i didnt understand this is mac/linux specific bug report page, where can i report the general one? I also find another interesting bug the other day, where if i invite a person to my team, and when the person accepts the team invitation, it often crash my game on 3 of 4 attempts. when it was crashing i was twice using the steam ingame browser, and once i just do a fresh dota 2 start, invite a person to my team, he accepts it, and it crash immediately, i am using windows 10 with 4gb ram, an i5 gen 5/6 proccessor, and NVidia GeForce GT940M.

**Comment by gdrewb-valve** [comment]
The general bug tracker is at dev.dota2.com
