### ISSUE TITLE
[OSX Macbook Air] Mic not working since 7.02 patch

### ISSUE THREAD

**Issue by RamcLindstrom** [ValveSoftware/Dota-2#1187]
Since 7.02 the internal mic for the macbook air has not been working for Dota2. When I press the shortcut to use it, it pops up a small red speech bubble with an X'd out mic icon on the right side of the screen and lags me for a few seconds. More recently it has not been lagging me when I test it, but still is not working. The mic works fine otherwise in other games and applications.

**Comment by gdrewb-valve** [comment]
If you look at issue #1181 does that cover the same thing you're seeing?

**Comment by RamcLindstrom** [comment]
More or less. I tried again today and it actually worked after a few
seconds of initially not 'finding' the mic. Hoping whatever the most recent
7.02 patch resolved it, but from the initial 7.02 release until today it
was on the fritz.

**Comment by gdrewb-valve** [comment]
Did you get a chance to try it again?  Is it still working?

**Comment by RamcLindstrom** [comment]
I tried it again just now (solo practice vs bots) and it is working like
yesterday: Approximately 1-2 seconds of 'not finding' the mic while holding
down the button, but then working fine thereafter. After it finds it the
first time all subsequent uses of the mic button work fine for the match.

**Comment by gdrewb-valve** [comment]
That seems odd and as 1181 is still open there may still be underlying issues.  I'll leave this open too.

**Comment by gdrewb-valve** [comment]
The latest Steam client beta has some voice support changes, do they make any difference if you use the beta client?

**Comment by RamcLindstrom** [comment]
I do not, as far as I know, use the Steam Beta client, just the default. I
updated my Steam Client and tried a few test games with Bots just now. The
first game there was a very slight delay and it went right to the 'white'
ok-to-talk mic. The second two it performed correctly. When I turned Dota2
off then back on it again only had a split-second of the disabled mic icon.
It seems like an improvement.

**Comment by gdrewb-valve** [comment]
Thanks, I'm going to close this out.

**Comment by RamcLindstrom** [comment]
Thank you for looking into the matter.
