### ISSUE TITLE
[macOS] Huge FPS drops

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1188]
Hi, my config: https://gist.github.com/RankoR/271dc17ca4ec24cd2f7044028650def8

In fact it's not iMac 17,1, it's custom Hackintosh build. Any other information from report is true.

My GPU is EVGA GTX970 ACX 2.0 SC with latest official NVidia Web Driver.
When I turn off VSync, I have 110-120 FPS on "static" scenes, e.g. when player is standing on place and nothing happens. But when there are some animations such as heroes/creeps moves, FPS is dropping to 30-50, and then rising back to 120 and back to 30 and so on.

If I turn on VSync, I have 59-60 FPS on static scenes, and the same behaviour as above for dynamic scenes.

That's behaviour for any graphics settings, for all-ultra or all-lowest (but on the lower settings FPS drops just to 40, not 30 as on Ultras).

I think that's not good. Are there any fixes?

**Comment by gdrewb-valve** [comment]
#1101 is the general perf issue and that largely supersedes this one.  As that issue mentions the perf issues extend outside of Mac/Linux and aren't owned by the porting team that runs this tracker.  Just from the Mac side of things I don't see such extreme FPS swings on my Mac so it's unclear what's going on with yours.  Can you run the Dota perftest (http://dev.dota2.com/showthread.php?t=277903) twice, once with things static and once when things dynamic (and no pausing as the instructions request) and post a gist of the results here?  They'll likely show that Dota is largely doing the same thing in both cases and won't help narrow down anything but it's easy to run so it's worth a shot.

**Comment by RankoR** [comment]
@gdrewb-valve Hm, I've just noticed that I've forgot to quit OBS. Now with no software running  there are no huge FPS drops, but it seems that few frames are dropped every 2-3 seconds. It occurs almost every time when I move the screen, and as I said before it occurs every time on complex scenes such as fights, and with strange behaviour on non-complex scenes — animations are not smooth. 

For example, when creeps wave just appeared on the screen (on visible part of screen), creeps running animation isn't smooth, but after 1-3 seconds it becomes smooth.

There are my perftests:

1. Hero demo: https://gist.github.com/RankoR/4f1e2a0ed029c3ebebd3af6864fdfeaf
2. Bots — center of river: https://gist.github.com/RankoR/d263a754bbdb4121541685777e2c6c86
3. Bots — moving screen with mouse — https://gist.github.com/RankoR/05e22744096175feb8ff97e1329f9365

To clarify which animation lags I'm talking about — look at this video, at radiant range creep attack animations at 00:23-00:30: https://www.youtube.com/watch?v=viBMp4bq-vg

That's not a video from my PC, but I have the same lags.

**Comment by RankoR** [comment]
@gdrewb-valve I've forgot to ask if it's possible to turn on Vulkan in Dota on macOS?

**Comment by gdrewb-valve** [comment]
Your perftest results don't show much of anything, you're running at your vsync limit of 60 FPS in all three cases so no problems there.  I'll leave this issue open and maybe enough other people with the same issue will respond that we can guess a common cause.

Vulkan is not supported on macOS.

**Comment by FlorianWendelborn** [comment]
I have huge FPS drops when moving the camera via the edge. It goes down to ~25-30 FPS on a GTX 780, i7 6700K, 32 GB RAM hackintosh. Maybe related?

**Comment by RankoR** [comment]
@dodekeract yep, the same behaviour on my GTX970.

**Comment by FlorianWendelborn** [comment]
@gdrewb-valve Anything I can do to make this easier to diagnose? I'd be willing to setup a TeamViewer connection or do some debugging if you tell me what needs to be done.

**Comment by RankoR** [comment]
By the way, I've rechecked on the same PC with Windows 10 — game is extremely smooth. FPS are dropping only on macOS.

**Comment by FlorianWendelborn** [comment]
@RankoR Not a solution for me, I don't let malware into my LAN. 😉

**Comment by FlorianWendelborn** [comment]
It actually seems to be fixed by using the NVIDIA Web Drivers. GTX 780 is supported natively by macOS so I didn't want to install them.

EDIT: Just played a whole match, FPS didn't drop below 60 mostly. Still a bit underwhelming for a GTX 780 but it's fine.

**Comment by RankoR** [comment]
@dodekeract I have the latest web driver installed, because GTX970 has no native support. And I see these drops.

**Comment by gdrewb-valve** [comment]
The March 13 update has some changes around the Monkey King ult and illusions, does it make any difference?

**Comment by RankoR** [comment]
> The March 13 update has some changes around the Monkey King ult and illusions, does it make any difference?

I don't see any difference. And in fact, on the same config I see the same performance on FullHD and 4K display — I have the same frame drops on both resolutions.

**Comment by RankoR** [comment]
BTW, I've played CS:GO on the same PC, and I do not see any frame drops even on 4K display.

**Comment by gdrewb-valve** [comment]
The latest changes were CPU-side optimizations but apparently your MacOS issues stem from some other source, unfortunately.

**Comment by gdrewb-valve** [comment]
Now that the Dota Vulkan support for macOS has released how does it compare on your system?

**Comment by RankoR** [comment]
@gdrewb-valve still playable only with minimal graphics settings and 50% rendering quality and with noticeable fps drops in fights or complex scenes (such as Tinker's machines).

And great performance on Windows with highest settings on the same machine.

**Comment by gdrewb-valve** [comment]
I meant more whether there are still perf drop issues that we should keep this open for?

I understand the perf doesn't match Windows but that's due to many factors.  In particular if you're comparing Windows Vulkan to macOS Vulkan the Valve part of the rendering path is the same and major perf differences arise from elsewhere.  You're welcome to open an issue in Dota-2-Vulkan with comparisons but we won't be keeping issues here in Dota-2 unless it looks game-related.

**Comment by RankoR** [comment]
I don't see any noticeable differences in performance (in my case) on Vulkan or OpenGL comparing to last year on the same machine.

**Comment by gdrewb-valve** [comment]
Do you think there's still something to keep this issue open for?  This issue is titled "huge FPS drops".  Are there still huge FPS drops?  Previous comments indicated they might have been related to other software.

**Comment by RankoR** [comment]
> Are there still huge FPS drops?

FPS still drops when moving screen.

I think it might be related to Nvidia driver (and generally poor performance), I'm planning to replace my GTX970 with some natively supported AMD GPU and re-check. I think you can close this issue, I will re-open it if needed.

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by RankoR** [comment]
Well, I can confirm that FPS drops are still present on my GTX970, but not present on RX580 on the same device.
So, seems to be NVidia's driver issue or nvidia gpu-related issue.
