### ISSUE TITLE
[macOS] Keyboard shortcuts doesn't work on non-en input sources

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1189]
Config: https://gist.github.com/RankoR/271dc17ca4ec24cd2f7044028650def8

I have two keyboard input sources: U.S. and Russian - PC.

When I'm on Russian - PC, I cant use in-games keys, such as qwer, ~, F1-F12, etc. They work for me only on U.S. input source.

**Comment by gdrewb-valve** [comment]
Did you set the option to do key binding by position instead of key name?

**Comment by RankoR** [comment]
@gdrewb-valve Thanks, that helped.
