### ISSUE TITLE
Linux: sometimes window drags instead of map signal

### ISSUE THREAD

**Issue by sinatosk** [ValveSoftware/Dota-2#119]
When holding ALT+Left Mouse Button it causes the window itself ( what dota 2 is rendering in ) to be draggable (dragging while the mouse button is down) instead of dota 2 itself picking up that I want to signal on the minimap...

same with dota source 1 but when not ingame... just on the main menu

I play with multi monitor setup

primary display is 2560x1600
secondary display is 1680x1050

I play in window borderless at 2560x1440 on my primary display. I prefer 16:9 ratio

I use ArchLinux, Xorg and openbox

steam info http://pastebin.com/0BvNJN4x

**Comment by Tele42** [comment]
Please look in the config file (```~/.config/openbox/rc.xml```) for openbox and search for:
```
    <mousebind button="A-Left" action="Drag">
      <action name="Move"/>
    </mousebind>
```
Desktop keybinding should take priority over game keybindings, especially in borderless fullscreen mode.

**Comment by sinatosk** [comment]
while true tele42... the process can take control of that. Valve has to do something in their code that says "I want full focus of the window" which I think is partially not working in dota source 2

when your not ingame, spectating or just on menu... the cursor has all the window operations as usual depending on the desktop enviroment your using

in dota source 1 the mouse cursor does not leave the window and window is not draggable when ingame. In dota source 2 the window is draggable and in some cases the window is not fully focused by dota source 2 which is already reported https://github.com/ValveSoftware/Dota-2-Reborn/issues/74

**Comment by MrTheSoulz** [comment]
Please dont lock window input, it hate it when games do that.
If your are windowed your mouse should be able to leave the window just by moving out...

This is really bad when trying to multitask.

**Comment by sinatosk** [comment]
disagree... like many games before ( ones you experienced have done it wrong I'm assuming ) are locked to the window... but do not lock you from your desktop... in androids case you just press the home button no matter how much control the app has...

accessing the game menu ,alt-tab and/or in some cases ( I think source 1 games does this ) just open console and your cursor can leave...

games dating back to quake 3 arena do this...

playing a game like dota 2, counter strike, team fortress is bad having the cursor leave the window when playing in window mode ( borderless or not )

**Comment by davidw-valve** [comment]
I can't immediately reproduce this. Can you be more specific when you say "sometimes"? Can you simply configure your window manager to allow Dota2 to get the signal?

**Comment by sinatosk** [comment]
well really it's just random

I usually have my thumb ready at "alt" and when needed I ping the map but then the window just starts to be draggable and it stays like that until I restart

**Comment by sinatosk** [comment]
I don't know if you attempted a fix or not but it still happens after last update and now the mouse cursor leaves the window as well and no amount of tab or refocusing fixes it... including configure the environment... restarting the client is the only fix and this does not happen with dota source 1

I can't reproduce it at will... it's random as in sometimes it happens and sometimes it doesn't... don't have this issue with dota 2, team fortress 2, counter strike global offense ( not played it for sometime though )

**Comment by vhda** [comment]
This is still happening, at least when running under icewm available in Debian Sid.

**Comment by dpacmittal** [comment]
Happens with KDE on Kubuntu as well.

**Comment by gdrewb-valve** [comment]
This one is stalled out.  The window is decorated as a fullscreen window and after that it's up to the window manager as to whether it allows WM behaviors or not. It's not clear that there's anything that Reborn can do, although if we can track down a reliable repro (which we at Valve don't have) we might be able to pin down exactly what's going on.

**Comment by Tele42** [comment]
@gdrewb-valve, this is definitely a case of the DE having higher priority in capturing keybindings than the game. Personally I believe this is the correct behavior, but it's unfortunate several DEs have decided to use Alt for several common actions. In this case Alt + left click is a common keybinding for move window (including moving fullscreen opengl windows from one screen to another which is immensely helpful to me). On my KDE system, it was easy enough to switch KDE from using Alt to Meta in the config.

**Comment by gdrewb-valve** [comment]
I agree with behavior being up to the DE, but the strange part about this report is that it only happens sometimes / randomly. If it was just a priority issue I would think that it would be consistent.

**Comment by sinatosk** [comment]
It hasn't happened to me in some months now, I don't remember when but you did an update sometime ago about fixing some input something and since then, not had any issues

after looking at the API of how to capture keyboard inputs... you can't remove that unless you explicitly request it too...

unless your continuously enabling/disabling the capturing during in game ( not spectating ) at times you shouldn't be ( which was my suspicion ) then yeah I guess this is a bug with KDE

**Comment by Tele42** [comment]
@gdrewb-valve, I am fairly sure Alt + Left click and Alt + Left click + any amount of mouse movement can be considered separate actions. Some DEs most likely take no action until the mouse has moved 1 or more pixels.

@sinatosk for reference, the KDE 4 setting I am referring to is at System Settings -> Window Behavior -> Window Behavior (Sidebar) -> Window Actions (Tab) and change the 'Inner Window, Titlebar, & Frame' Modifier key from Alt to Meta.

**Comment by gdrewb-valve** [comment]
I'm going to close this for now.  If somebody has repro steps that aren't related to window manager behaviors we can reopen.
