### ISSUE TITLE
[Linux] Region issues - still swith to automatic

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1190]
Since the beginning of this week. I noticed that the game does not save the region that I choose.
For example, I play Normal game on regions of Western Europe and Eastern Europe.

When I turn off the game and start it again servers are once again set to "automatic" and what's interesting to me is Dota looking games in addition to both EU and also with Russians server ...

**Comment by gdrewb-valve** [comment]
This is happening on all platforms so it's outside the scope of this tracker.

**Comment by gdrewb-valve** [comment]
I heard from the larger team that this is intentional.  The region setting is a temporary override and is supposed to reset.
