### ISSUE TITLE
Dota 2 can't launch for Mac

### ISSUE THREAD

**Issue by lorax123** [ValveSoftware/Dota-2#1193]
Just says I'm in game for 2-3 seconds, then goes back to online. I can access other games but not Dota for some reason.

**Comment by kisak-valve** [comment]
Hello @lorax123, after verifying the game files (right click the game -> `Properties` -> `Local Files` -> `Verify integrity of game files...`), please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
