### ISSUE TITLE
MACBOOK --> SHIFT KEY pop up overlay screen.

### ISSUE THREAD

**Issue by tayhaithian** [ValveSoftware/Dota-2#1194]
Not sure why after yesterday update on my macbook dota2, just "SHIFT" key itself the screen overlay turns up where usually it was "SHIFT + TAB". Now I couldn't type in capital letters and no more quick slot adding. Every now and then when "SHIFT" key is in concerns, the overlay prompt in the middle of the game again. 

This is a serious bug, please help to look into it. 

**** It was fixed for an hour or two this afternoon, then it returned in the evening...

**Comment by gdrewb-valve** [comment]
This isn't a Dota issue so we won't be able to track it here but I'll keep this open for a bit in case the Steam team has some information.

**Comment by gdrewb-valve** [comment]
I haven't heard anything back from the Steam team, unfortunately.  Closing but if I do hear something I'll post here.
