### ISSUE TITLE
Crash Dota by pressing some keys

### ISSUE THREAD

**Issue by Geradot** [ValveSoftware/Dota-2#1198]
I press "Space", "T" — the game crashes. The key "A" generally works as Esc. WTF is this? And this issues is in main menu. This began to be right after the release of 7.03 patch.
OS: Linux Mint 18.1 x64.

**Comment by Cabanur** [comment]
Copying your system information from steam menu to a gist will give the dev
team a better idea about your setup so they can help you.

**Comment by Geradot** [comment]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Athlon(tm) II X4 620 Processor
    CPU Family:  0x10
    CPU Model:  0x5
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 18.1 Serena (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.0-42-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.39
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0xf00
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18,66" x 11,65"  (21,97" diag)
                                            47,4cm x 29,6cm  (55,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT1705
    
Memory:
    RAM:  3950 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  884134 Mb
    Largest Free Hard Disk Block:  665367 Mb
    VR Headset: None

**Comment by gdrewb-valve** [comment]
No problems on my system.  Possibly related to the SDL update.

**Comment by Geradot** [comment]
What can I do for my part to solve this problem?

**Comment by gdrewb-valve** [comment]
If you have libSDL2.so on your system you can try removing the one in the Dota directory (which will not stay that way as the game will try to repair).  Otherwise you'll have to wait and see if other people hit the same problem or if the SDL dev has some ideas.

**Comment by Geradot** [comment]
This did not solve the problem

**Comment by kisak-valve** [comment]
You could try switching Settings -> Advanced Hotkeys -> Bind keys based on keyboard position and see if that makes a difference.

**Comment by Geradot** [comment]
I tried. This did not solve the problem. Furthermore, this bug still working even when the game is minimized: I press "Space" -- the game crashes

**Comment by idespisevalvecoders** [comment]
kisak, everyone realize you just a pakistan refugee, but why in the holy name of fkc, you have to be SO incompetent? This problem occurs on EVERY linux pc hardware regardless. Dota crashes after recent patch when certain keys pressed R, Y, SPACE and some others. Why users should provide you such details? Don't you have beta-test department? Your company income from every battle pass = freaking ~billion. Can you spend sometime not surfing amazon and actually do the process of DEBUGGING.

**Comment by Geradot** [comment]
kisak, none of the methods listed in the your link corrected the problem

**Comment by idespisevalvecoders** [comment]
they now asking for help some chineese freelancers, i guess

**Comment by danginsburg** [comment]
@Geradot I am not able to repro this problem on a couple of my Linux test systems.  When it crashes, could you go to Steam -> Help -> System Information and at the end under "Recent Failure Reports" either post the .dmp file or post the CrashID and we can look it up here.

**Comment by Geradot** [comment]
[crash_20170317161004_1.zip](https://github.com/ValveSoftware/Dota-2/files/851279/crash_20170317161004_1.zip)

**Comment by danginsburg** [comment]
@Geradot Thanks.  The crash is in our inputsystem.  We are still trying to find a repro.  Do you by chance have any joysticks/controllers plugged in?  Does the problem go away if you remove them?  If so, what kind of controller?  Thanks for all the help.  As soon as we can repro the crash we'll figure out what it is.

**Comment by Geradot** [comment]
No, I haven't joysticks.

**Comment by Geradot** [comment]
Maybe this info will be useful:

`$ dmesg | tail -n1`
`
[  124.070569] dota2[1975]: segfault at 45e68 ip 00007f3df60474e6 sp 00007ffd03a71c40 error 4 in libinputsystem.so[7f3df6031000+50000]
`

**Comment by ImRebel88** [comment]
I got the same problem.

> Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3300 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-67-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 550 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.57
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1244
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,08" x 11,42"  (23,07" diag)
                                            51,0cm x 29,0cm  (58,6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  7940 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  ru_UA.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  106660 Mb
    Largest Free Hard Disk Block:  75449 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Sat Mar 18 12:21:28 2017 GMT: file ''/tmp/dumps/assert_20170318142126_21.dmp'', upload yes: ''CrashID=bp-98b92f0c-6ff4-433c-ae5b-9f1c52170318''
    Sat Mar 18 12:21:52 2017 GMT: file ''/tmp/dumps/crash_20170318142131_1.dmp'', upload yes: ''Discarded=1''
    
[assert_20170318142126_21.dmp.tar.gz](https://github.com/ValveSoftware/Dota-2/files/852414/assert_20170318142126_21.dmp.tar.gz)

[crash_20170318142131_1.dmp.tar.gz](https://github.com/ValveSoftware/Dota-2/files/852413/crash_20170318142131_1.dmp.tar.gz)

**Comment by kisak-valve** [comment]
For reference, crash_20170318142131_1.dmp is a SIGSEGV in libengine2.so, coming from libinputsystem.so (Dota 2).

**Comment by Geradot** [comment]
Dear developers, what can you say about this issue? We can't play in Dota for several days already.

**Comment by Olosinsk-commits** [comment]
Geradot, just wondering, do you have this issue on both, Ru and Eng layouts?

**Comment by Geradot** [comment]
Yes,  I  have. It doesn't depend on layout.

**Comment by gdrewb-valve** [comment]
Unfortunately we have not been able to get this to happen at Valve yet so we don't have any news.  We'll keep trying to find out the cause.

**Comment by Geradot** [comment]
I think you (maybe and Valve) remember that this problem is not for me alone

**Comment by danginsburg** [comment]
@Geradot We are aware others are seeing the problem, we just haven't figured out a way to reproduce the issue yet.  If anyone has further info/repro instructions beyond what's here already please add to the bug.

**Comment by Geradot** [comment]
I tried to install Ubuntu 16.04 - the problem is not solved :(

**Comment by danginsburg** [comment]
@Geradot Can you post the output of the locale command on your system?  Maybe it is to do with system language settings.

**Comment by Geradot** [comment]
I did it in third message on this page. Else what do you mean?

**Comment by Cabanur** [comment]
Open your terminal, type: 

    locale

and press enter. Whatever shows up afterwards, copy it here.

**Comment by danginsburg** [comment]
Drop to a terminal and type locale.  You should see output like this:

locale 
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by Geradot** [comment]
`$ locale
LANG=ru_RU.UTF-8
LANGUAGE=ru:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_UA.UTF-8
LC_TIME=ru_UA.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_UA.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_UA.UTF-8
LC_NAME=ru_UA.UTF-8
LC_ADDRESS=ru_UA.UTF-8
LC_TELEPHONE=ru_UA.UTF-8
LC_MEASUREMENT=ru_UA.UTF-8
LC_IDENTIFICATION=ru_UA.UTF-8
LC_ALL=
`

**Comment by Geradot** [comment]
$ locale
LANG=ru_RU.UTF-8
LANGUAGE=ru:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_UA.UTF-8
LC_TIME=ru_UA.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_UA.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_UA.UTF-8
LC_NAME=ru_UA.UTF-8
LC_ADDRESS=ru_UA.UTF-8
LC_TELEPHONE=ru_UA.UTF-8
LC_MEASUREMENT=ru_UA.UTF-8
LC_IDENTIFICATION=ru_UA.UTF-8
LC_ALL=

**Comment by Geradot** [comment]
I tried do
$ LC_ALL=en_US.UTF-8 steam
but the problem is not solved

**Comment by danginsburg** [comment]
Yeah, that does not appear to be the problem, I tried forcing Russian on my machine and still could not reproduce.  Sorry and thank you for all the responses.  If you don't mind, one last thing: can you put -con_logfile in your Launch Options and post ~/.steam/steam/steamapps/common/dota 2 beta/game/console.log.  I'm noticing that some machines crashing with a similar callstack have this at the beginning:

initializing SDL joystick 0 A4TECH USB Device

You said you don't have a joystick, but I wonder if one of your USB devices is being detected as one.  The log will give us info if so.  

Thanks for your patience.

**Comment by Geradot** [comment]
Did it.
[console.log.zip](https://github.com/ValveSoftware/Dota-2/files/859239/console.log.zip)
This text string is present in this logfile!
What can I do now?

P.S. I did the command
`$ cat /proc/bus/input/devices`
and look it

I: Bus=0003 Vendor=09da Product=90c0 Version=0111
N: Name="A4TECH USB Device"
P: Phys=usb-0000:00:02.0-4/input0
S: Sysfs=/devices/pci0000:00/0000:00:02.0/usb2/2-4/2-4:1.0/0003:09DA:90C0.0004/input/input8
U: Uniq=
H: Handlers=sysrq kbd event5 leds **js0** 
B: PROP=0
B: EV=12001f
B: KEY=3007f 0 0 4c3ffff17aff32d bf54445600000000 c00000000000001 130c130b17c007 ffa67bfad951dfff febeffdfffefffff fffffffffffffffe
B: REL=40
B: ABS=ffffff01000701ff
B: MSC=10
B: LED=1f

My keyboard detected as joystick!

**Comment by ImRebel88** [comment]
me too have keyboard A4tech g800v, so thats the problem?

**Comment by Geradot** [comment]
So, this line has been since the installation of Linux. And the game worked correctly before 7.03

**Comment by ImRebel88** [comment]
Same for me, game begin crash after  7.03

**Comment by Geradot** [comment]
I'm talking about the same thing)

**Comment by danginsburg** [comment]
It looks likely related, this is in your console.log:

Opening joystick 0 : A4TECH USB Device

@Geradot Exactly what mouse or keyboard do you have so that we can get one to repro?  It sounds like @IMRebel88 has the bug with A4Tech G800MV Keyboard.

See this thread: https://bbs.archlinux.org/viewtopic.php?id=189901 for possible workarounds.  We'll have to get one of the offending pieces of hardware and track down the bug.  It may be some regression related to us picking up the latest SDL, but so far it's unclear.  If you are able to swap mouse/keyboard as a quick test would be interested to hear definitively that is the problem.

**Comment by Geradot** [comment]
@danginsburg I have A4Tech G800V Keyboard. And I can't to swap keyboard...

So, I tried https://bbs.archlinux.org/viewtopic.php?id=189901 but after computer's reboot all is reset by default.

**Comment by ImRebel88** [comment]
@danginsburg with simple PS/2 kayboard all fine, no crash.
So its problem with KB+7.03

**Comment by danginsburg** [comment]
OK, thanks.  At least we've solved the mystery of what is triggering the crash.  We'll get the hardware here so we can track it down.

**Comment by danginsburg** [comment]
I have the keyboard and have the bug reproduced.  I'm working on a fix.  We're still trying to figure out whether to fix SDL or source2.  In the meantime, this repository has a workaround that should fix the problem:

https://github.com/denilsonsa/udev-joystick-blacklist

The problem stems from the A4Tech G800V keyboard 09da:90c0 being detected as ID_INPUT_JOYSTICK in udev.  SDL ends up reporting every key press as a joystick event which causes problems in source2.  The /etc/udev/rules.d/51-these-are-not-joysticks.rules includes a workaround in it for that device (along with others that have the problem).

**Comment by danginsburg** [comment]
A fix for this has been checked in.  It will ship in the next Dota 2 Update.  I'll update the bug when it ships.

**Comment by Geradot** [comment]
Thank you. Сan you inform here about when will the update that corrects this error? Or this information will be in the patchnote?

**Comment by danginsburg** [comment]
I will post here when it ships.  It missed the window for yesterday's update, but it should make the next one.

**Comment by danginsburg** [comment]
The fix for this shipped in the March 24th update.  Should be fixed now.

**Comment by Geradot** [comment]
Thank you, man. I will write about this later.

**Comment by Geradot** [comment]
Yes, this issue has been solved!
