### ISSUE TITLE
Mouse Input on Ubuntu No Longer Captured in Window

### ISSUE THREAD

**Issue by martindale** [ValveSoftware/Dota-2#1199]
Doesn't matter what setting I use, mouse input is no longer captured inside the window while in-game... game unplayable.  Uninstalling! </s>

**Comment by gdrewb-valve** [comment]
Possibly related to the SDL update.

**Comment by kisak-valve** [comment]
Noted in #1056, Gnome 3.22 is affected, KDE may not be affected. Additionally, Gnome 3.14 was mentioned as affected on an irc channel.

**Comment by icculus** [comment]
> Uninstalling!

Does fullscreen mode work for you, as an option while we figure out what went wrong?

**Comment by Leibide** [comment]
I encountered something similar - I could scroll up on the map by moving the mouse pointer up, but couldn't scroll any other direction.
I've uninstalled this game.
system:
Linux Ubuntu 16.04.02
Intel Pentium G4560
2x4 GB RAM
Radeon RX460

**Comment by martindale** [comment]
@rcgordon no, the only thing that works is disabling my other displays _and_ enabling fullscreen.  Fullscreen on a single display in a multi-monitor setup fails to capture the mouse.

**Comment by Cabanur** [comment]
On Debian Testing with KDE this is not an issue for me. I have two monitors, a main 1920x1200 and a secondary 1680x1050. 

In fact, I sometimes have to alt-tab twice because the first time it seems like the cursor is still locked. The cursos ir not locked while on the menu or spectating games, but is correctly locked when playing. I think I have desktop-friendly full-screen, but I'm not sure. I can check next time I play if somebody thinks that's relevant.

**Comment by martindale** [comment]
Latest patch seems to fix this.

**Comment by vmavromatis** [comment]
I also have an issue with the cursor in dual screen. I start it (in primary) with **-phased_window_create** in options and set **dota_mouse_window_lock=1** in console. The cursor locks in game, however, it extends into the edge of the secondary monitor whenever I move it to the right edge. It's not a devastating bug, but still needs fixing. I confirm it in two setups (Ubuntu 16.04.2/Gnome, Mint 18.1/Cinnamon).

My driver is Nvidia 378.13 and card is GTX970. Workaround is to switch off the second monitor while playing.

**Comment by martindale** [comment]
It seems like exiting fullscreen mode returns the bug as well; full-screen on a triple-head display captures mouse during the game, but windowed mode does not.

**Comment by danginsburg** [comment]
We just shipped an update with a potential fix for this bug in the March 21st update.  Can those who were seeing the problem please retest and let us know if it is any better?  Thanks.

**Comment by vmavromatis** [comment]
I confirm that mouse is captured in all 3 video modes. However the visual glitch of having the cursor extending into the secondary monitor still exists for me. 

FWIW, left monitor is ASUS VS247H-P, right is LG 24MT46D
![img_20170323_082021](https://cloud.githubusercontent.com/assets/8668731/24238385/fe412c4a-0fa1-11e7-87ca-d6f1b90293cc.jpg)

**Comment by gdrewb-valve** [comment]
The rendering of the cursor is a system issue and not a Dota issue, so it sounds like this can be closed out?

**Comment by kisak-valve** [comment]
I agree, in my experience other fullscreen opengl applications allow for the cursor to render on other monitors, it's just more visible with Dota 2's larger cursor.

**Comment by vmavromatis** [comment]
Yes, you are right, it does not only happen with Dota. I just noticed it, because this was not an issue in Windows AFAIK.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
