### ISSUE TITLE
Custom Game Doesnt Launch

### ISSUE THREAD

**Issue by spalfs** [ValveSoftware/Dota-2#12]
I've installed overthrow and have tried matchmaking and creating my own private game and the loading screen comes up for overthrow but then the game force closes down.

On Debian Testing 64bit.

**Edit for more information**
I'm running i3 window manager with a GTX 550 ti with no problems on legacy dota.
I've tried running it with MATE with no difference.

**Comment by gdrewb-valve** [comment]
We're going to need some more info to try and figure out what's going on.  Do you have any failure reports in your Steam system information?  Do you have any dump files in /tmp/dumps?  If you're familiar with gdb can you try and get a gdb backtrace?

**Comment by MajorTom6** [comment]
I believe I have the same issue as https://github.com/ValveSoftware/Dota-2-Reborn/issues/10 
Unless that was fixed in the patch that came out today, because I am still experiencing the error.

**Comment by gdrewb-valve** [comment]
No, #10 has not been fixed yet.

**Comment by MajorTom6** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5176580/8346575/663e1a76-1ac4-11e5-83fa-c9aa618192d1.png)

**Comment by MajorTom6** [comment]
sor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Athlon(tm) II X2 260 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 3200.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate npt lbrv svm_lock nrip_save vmmcall
bogomips	: 6428.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Athlon(tm) II X2 260 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate npt lbrv svm_lock nrip_save vmmcall
bogomips	: 6428.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

I don't know what of it is relevant.

**Comment by gdrewb-valve** [comment]
The lack of SSSE3 is the relevant bit, making this the same thing as #10.

**Comment by MajorTom6** [comment]
Okay cool, th
Glad I could help !

**Comment by MajorTom6** [comment]
Fixed with latest patch.
