### ISSUE TITLE
jugg arcana omnislash crashes my game every time

### ISSUE THREAD

**Issue by tulgak1996** [ValveSoftware/Dota-2#1200]
jugg arcana ulti crashes my game. its making dota unplayable. pls fix. on mac os x

**Comment by kisak-valve** [comment]
Hello @tulgak1996, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you happen to find any CrashIDs or minidumps related to this issue, please include them as well.

**Comment by tulgak1996** [comment]
hi, thank you responding kisak
here is the gist of my system info from steam https://gist.github.com/tulgak1996/1bb46eb2039a9c05f008787b73dbf48d
i also made a gist of the Crashid apple gives me after dota crashes https://gist.github.com/tulgak1996/61851885cc5af4df1c3ec774f5dcc892 
idk if its any help as it is very long and im not that tech savvy.

**Comment by tulgak1996** [comment]
also i went to console and found this 
![screen shot 2017-03-20 at 12 49 02 pm](https://cloud.githubusercontent.com/assets/26515277/24086918/ca5ec032-0d6b-11e7-8eb4-804fd6f969f3.png)

**Comment by gdrewb-valve** [comment]
The crash is in Apple's OpenGL driver so Valve may not be able to do anything directly about it.  We'll take a look.

**Comment by tulgak1996** [comment]
hi i have just updated my OS X software to sierra and tested the arcana. it seems to have gotten rid of the crash but i still have heavy fps drops during the ulti

**Comment by gdrewb-valve** [comment]
Closing as the crash appears to have been a system issue.  Perf is already covered in a couple of open issues, such as #1101.
