### ISSUE TITLE
Huge fps drops and missing cooldown animations since 7.00

### ISSUE THREAD

**Issue by GosuGamerL** [ValveSoftware/Dota-2#1204]
Hi! Here is my system: https://gist.github.com/GosuGamerL/0be27320aac70e8397e0099c03b029c4
So since 7.00 i have been getting huge fps drops in fights up to 15 fps, regardless of which setting i choose.(max and min produce same results). I tried reinstalling dota 2 and video drivers but it did not help.

Moreover, If I enalbe -dx11 in launch options, i do not have cooldown animations(for skills, items, shop etc). I know that issues like this persists in vulkan, but I have not encountered it on dx11 before. 
I attach 2 screenshots for those who don't understand what I mean.  Pay attention my W skill, ward cooldown or hero level bar.

So is there any fix to this? Was it encountered before?
![20170326192738_1](https://cloud.githubusercontent.com/assets/25803559/24333502/94600f4a-1261-11e7-83aa-ebd943d4460d.jpg)
![20170326192710_1](https://cloud.githubusercontent.com/assets/25803559/24333503/946437aa-1261-11e7-8f18-a21cee8f05aa.jpg)

**Comment by gdrewb-valve** [comment]
This tracker is only for Mac and Linux bugs, you'll want to post at dev.dota2.com
