### ISSUE TITLE
Incorrect Game Overview after watching 1V1 mid

### ISSUE THREAD

**Issue by tarriel** [ValveSoftware/Dota-2#1205]
After watching some games of DAC in game, I watched the first 1v1 mid, RTZ vs Miracle- and instead the summary showed 1437 vs KuroKy  This used to happen in games before but I haven't seen it for a while, probably because this is the first 1v1, the second 1v1 match also did not show the correct contestants. and so on.
![dota2 dac solo mid - kuro vs 1437](https://cloud.githubusercontent.com/assets/1488285/24451089/c80f68ca-14c0-11e7-86f1-b2883c1e76cc.png)
![rtz vs miracle 2017-03-29 20 34 57](https://cloud.githubusercontent.com/assets/1488285/24451097/cf0785a4-14c0-11e7-829a-aa08eee39caf.png)

**Comment by gdrewb-valve** [comment]
This tracker is for issues that only happen on Mac/Linux and this kind of thing would affect all platforms.  You can post general bugs at dev.dota2.com

**Comment by tarriel** [comment]
I don't have access to a windows platform, makes it a bit hard to check.

**Comment by gdrewb-valve** [comment]
That's fine, if you don't know just open them here and we'll close them out if we know.

Also in the future please include a gist link to your system info.
