### ISSUE TITLE
game and computer crashes if any of the social feature is used.

### ISSUE THREAD

**Issue by yugimutou92** [ValveSoftware/Dota-2#1206]
this is started to happen recently, whenever i keep my steam status offline, steam overlay and other steam notifications disabled i can play dota as much as i can, but if i turn on any of these above it just crashes at main menu.

**Comment by kisak-valve** [comment]
Hello @yugimutou92, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you happen to find any CrashIDs or minidumps related to this issue, please include them as well.

**Comment by yugimutou92** [comment]
[here](https://gist.github.com/yugimutou92/9e87dab94bb994bdfbba258a6a9f514d)

**Comment by gdrewb-valve** [comment]
There aren't any failure reports, unfortunately, so we don't have any information on what's going on with your system.  Often when things crash like this and Dota doesn't have a report it means system software is crashing, such as your OpenGL driver.  Trying different driver versions (if possible) may make a difference.

**Comment by yugimutou92** [comment]
after few unsuccessful attempts with video driver changes only thing i can tell is the problem is dota specific. i used nvidia 340, nouveau and some nvidia 33* s to test and tried on dota, csgo, darkest dungeon, modded minecraft even some windows games on wine. only dota have this issue, since the last saturday. can it be originated from "desktop friendly fullscreen"? im gonna try it and post results when i can

**Comment by gdrewb-valve** [comment]
Unfortunately it's hard to say what it might be since we have no information on the crash.  #1207 reports a regular crash so there may be other information coming in.

**Comment by Turmfalke2** [comment]
What do you mean with the computer crashes? As in the screen freezes or does it shutdown? Can you still connect through ssh, switch to an tty or kill X using magic sysrq keys?

**Comment by yugimutou92** [comment]
@Turmfalke2 complete shutdown

**Comment by kisak-valve** [comment]
This sounds like something is going wrong in the kernel or a kernel module.

It may be worthwhile to get systemd to keep the last boot's log similar to http://unix.stackexchange.com/questions/159221/how-do-i-display-log-messages-from-previous-boots-under-centos-7 or setup netconsole to see if the system can send the dying message to another system.

**Comment by Turmfalke2** [comment]
Well this definitely appears to be an issue outside of dota2. It could be a bug in nvidia kernel driver that dota happens to trigger, but even in that case I would expect to see a kernel panic.  

This sounds more like something overheating, but I highly doubt you can suddenly overheat something using steam's social features.

What is the output of cat /proc/sys/kernel/panic? Maybe it reboots before you are able to see the panic.

**Comment by yugimutou92** [comment]
i dont know if you did something related to it or not but this recent update fixed it. i tried so hard to crash it but dota works so good now, thank you, have a nice day.
