### ISSUE TITLE
differenciate ally health bar does not work

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1209]
up-to-date beta steamos
up-to-date beta steam client

AMD GCN1 (TAHITI XT) with mesa

The yellow ally HP bar does not work with differentiate ally HP bar option enabled.

**Comment by gdrewb-valve** [comment]
There are some posts around that this feature doesn't work (https://www.reddit.com/r/DotA2/comments/50rv9f/is_the_differentiate_ally_health_bars_option_not/), I'll pass it by the larger team.

**Comment by gdrewb-valve** [comment]
The larger team will take a look at this at some point.
