### ISSUE TITLE
[Mac] Issues when trying to join lobby from lobby list

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#121]
I don't know if this is a bug or I am just really unlucky. But from my many attempts to join a lobby from lobby list, I have never succeeded. I would get an error message saying the lobby I wanted to join doesn't exist anymore, although when I refreshed the page it was still there. 

Another issue is I can spam the join lobby button. Then it seems my client will send multiple join lobby requests because I got more than one alert boxes saying the error message I mentioned above.

The third problem is trivial. The placeholder text in the filter input is not at correct y position.
![screenshot 2015-06-26 19 06 31](https://cloud.githubusercontent.com/assets/5674597/8390030/8a450006-1c36-11e5-94e9-fc51a627aa4d.png)

**Comment by gdrewb-valve** [comment]
Your first issue looks like a dup of #27.  The others are not Linux/Mac issues and I've passed them on to the larger team.

**Comment by gdrewb-valve** [comment]
As #27 is now fixed and the other issues are not Linux/Mac (the larger team acknowledged them but they're not at the top of the priority list) I'm closing this.
