### ISSUE TITLE
Some HUD bugs, and dota interface bugs.

### ISSUE THREAD

**Issue by coldskybrz** [ValveSoftware/Dota-2#1210]
https://www.youtube.com/watch?v=jtCJ8-55TS4
Here it is.
Whats wrong with game?
All others games working normaly. Latest drivers installed. Russians supports can't help.
gtx 650 Ti, i3-2100. Was working 5 mounths ago.

**Comment by kisak-valve** [comment]
Hello @coldskybrz, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Additionally, please confirm that you have verified the game's files. (Game properties -> local files -> verify integrity of game files)

**Comment by gdrewb-valve** [comment]
Can you also give specific details about the issues you think are present?  We can't be sure of what exactly your concerns are from just the video.

**Comment by coldskybrz** [comment]
Steam info: https://gist.github.com/coldskybrz/2b2899051b88f6f062fe52ec7f7f3b03
Verified 100 times, reinstalled videocard drivers and tried anything:)
When i clicking on interface things like "exit", its not showing dialog.
When i starting play, its not showing interface untill i use ctrl+click in random place, where skills and its will update and show skill, then when i get level i will unable to see skills interface again. Same with items hud.
i can't add to friends, i can't use steam overlay, So seems its some GUI bugs and problems with drawing some objects. And i can't edit video settings personaly. And i can't accept group query, when some friend inviting me, but if i click right or shoot enter maby - it will add me to group. When screen loading you can see in the end how its flashing purple. So many problems with interface drawing.

**Comment by gdrewb-valve** [comment]
This tracker is only for bugs specific to Mac and Linux.  You'll want to post at dev.dota2.com
