### ISSUE TITLE
[macOS] Stuck in the loading screen

### ISSUE THREAD

**Issue by liuerfire** [ValveSoftware/Dota-2#1214]
When a game was matched and clicked the accept button, the game just stuck in the loading screen for a while, then returned to the main window and told me that you just refused the game!!

Here is the video shows what happened: https://youtu.be/hvnpc4kBJR4 (use a lobby game instead of a normal match in case of the punishment)

this is the console.log
https://gist.github.com/liuerfire/0847ba137fdfb7bedde45f0bc025c555

this is my system information:
https://gist.github.com/liuerfire/5bebdc679facf2022ed3f73b728e65ea

**Comment by gdrewb-valve** [comment]
Probably the same as #1109.
