### ISSUE TITLE
[Linux] Accept on matchmaking sometimes loads but does not connect

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#1216]
Today it happened already 2 times:
Pressed "Play DOTA" found a match - accepted it and it starts loading.
The screen shows up with the 10 player names and colors on top but then it falls back to the main menu and says "I failed to ready up".
1st time i got 5 minutes - 2nd time 20. I doubt its my fault as I not really did something wrong.
Just waited clicked the correct buttons but it failed.

****************
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 9.0 (stretch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.0-2-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11902000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.39
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1b81
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                            53,1cm x 29,9cm  (60,9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: AV200
    
Memory:
    RAM:  32144 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  53884 Mb
    Largest Free Hard Disk Block:  21677 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Sun Apr 23 10:12:25 2017 GMT: file ''/tmp/dumps/crash_20170423121223_22.dmp'', upload yes: ''CrashID=bp-314560c2-a388-4aed-a49a-99ee42170423''
    Sun Apr 23 10:44:00 2017 GMT: file ''/tmp/dumps/crash_20170423124358_6.dmp'', upload yes: ''Discarded=1''
    Sun Apr 23 10:44:00 2017 GMT: file ''/tmp/dumps/assert_20170423124359_66.dmp'', upload yes: ''CrashID=bp-104211ad-6f5b-4613-8fa3-d497f2170423''
    Sun Apr 23 10:44:00 2017 GMT: file ''/tmp/dumps/assert_20170423121212_1.dmp'', upload yes: ''CrashID=bp-47e7f787-bf6c-4b8d-a85b-595d82170423''

**Comment by kisak-valve** [comment]
Most likely a newer report of #745.

**Comment by gdrewb-valve** [comment]
These kinds of problems generally aren't Linux/Mac specific so they aren't handled here.  I'll pass this on to the larger team.

**Comment by feratechinc** [comment]
To update, this specifically happens when you are in the process of watching a game and it's loading while the accept comes up. This is pretty consistent and I can reproduce it each time.
