### ISSUE TITLE
[Mac] Cannot view infos about "ready" players

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#122]
![screenshot 2015-06-26 18 58 34](https://cloud.githubusercontent.com/assets/5674597/8390031/a42f6ede-1c36-11e5-96b2-05efc2c574df.png)
I could only see the detailed info about the player who didn't press "ready". When I hovered my mouse on other "ready" players' avatars, there was no such view displayed.

**Comment by gdrewb-valve** [comment]
Likely not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
This happens on Windows too, I've passed it on to the larger team.
