### ISSUE TITLE
Connection to server timed out

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1221]
Hi. Since the last one or two updates (I haven’t played in March and April) the game started to lag, but it’s not graphics lags: I see stable 60 FPS. The screen just freezes, then it either unfreezes after like 5–10 seconds and I am where I was/was going to move (if I’m still alive, heh), or I see the message ‘Timed out.’ and reconnect lasts around 20 (20!!) seconds, I am teleported to the base. It happened at least twice in the start of the match ID 3147184248. The result was very unpleasant – I was 4–6 levels behind my enemies, while playing on the mid. 

I thought about what I changed in my system since I was playing  when everything was okay, and killed pulseaudio server. Surprisingly, I’ve seen no ‘Timed out’ errors since then. Though later the game lagged once for a couple (but literally just for a couple) of seconds, when Leshrac decided to enable ulti near the fountain, but as I see, there’s already a bug posted about downgraded graphics performance.

I’ve played on Europe West, and my connection to Lisbon is 27/62 Mbit down/up, so the network can hardly be an issue.
![untitled](https://cloud.githubusercontent.com/assets/2245254/25558114/02fc249a-2d31-11e7-8181-e8079e255c61.png)

**Comment by gdrewb-valve** [comment]
There are similar reports on all platforms but we have no reliable repro to investigate.  The larger team has this on their radar and there won't be an investigation by the porting team but I'll leave this open for a bit.

If you experiment with reenabling pulseaudio and have problems which then go away when killing pulseaudio please let us know.  I can assign to the SDL dev then for them to investigate.

**Comment by gdrewb-valve** [comment]
Closing as the connect issue is not Mac/Linux specific and there's no further info on pulseaudio.
