### ISSUE TITLE
[Linux] Dota is unresponsive in docker or LXC container

### ISSUE THREAD

**Issue by Kalaww** [ValveSoftware/Dota-2#1222]
Hi,
I am trying to run Dota 2 in a container (docker or LXC) and in both case, it end up the same way : the game load into the client dashboard, and after a few seconds it becomes unresponsive (game is frozen, mouse and keyboard inputs don't work). Both happens in docker and LXC containers.
I have no idea what may cause this, the game doesn't crash, so no dump file.
Dota 2 is running fine on the computer (not in a container).
I tried with CSGO in the same container, and the game was running well.
And I reproduce the same issue on an other computer (this one has no gpu)

Steam terminal output, console.log and system informations are here :
https://gist.github.com/Kalaww/e90607b1dec0e96a2fef50e2c9443a91

Thanks for reading

**Comment by gdrewb-valve** [comment]
You may get more info posting in forums related to the containers.

**Comment by Kalaww** [comment]
I managed to get Dota 2 running by doing this before launching steam (#921).
No idea what that did and if it's a good workaround.
```
export DBUS_SESSION_BUS_ADDRESS="foo"
```

Maybe is there a device needed by Dota from the system I must bind to the container ?

**Comment by gdrewb-valve** [comment]
The issue in #921 was related to dbus usage for IME support and not a device, but I've assigned this to the SDL dev in case he has more info.

**Comment by Kalaww** [comment]
Thanks for the support @gdrewb-valve !
