### ISSUE TITLE
cursor background size computation seems buggy

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1225]
up-to-date beta steamos 
up-to-date beta steam client

GFX hardware: AMD TAHITI XT(still radeon linux module :(( ), driver mesa.

The background of the blue cusor set from the international is white instead of being transparent. The other cursor sets are fine.

**Comment by gdrewb-valve** [comment]
Likely the same as #896.

**Comment by sylware** [comment]
update: with the 'performance update', all the cursor sets have the same pb, _only_ if set to a size of 100% (or automatic)

**Comment by sylware** [comment]
Tested a bit more. It's now kind of random: if you play with the cursor size option and the automatic size setting, you get sometimes a wrong size for the cursor background, which you can see while hovering the cursor on some units in-game. All the cursors I tested failed to work properly.

**Comment by sylware** [comment]
seems fixed.
