### ISSUE TITLE
Dota 2 Console getting spammed with errors continuously

### ISSUE THREAD

**Issue by Infamous540** [ValveSoftware/Dota-2#1226]
MacBook Pro
 MacBookPro11,3
 Intel Core i7
  2,5 GHz
Intel Iris Pro

Dota 2 getting spammed with 

CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.

Sometimes I get ALOT of those cswap errors and they spamming my console and making me spike n get crap fps, some games I have 3-5 fps just unplayable.

ALSO

[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 100 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 53 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 53 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 88 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 53 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 79 (115 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 102 (115 input number was)
`trimmed by moderator`
[Client]  1233: 0.802137 msec change 'OnCellChanged()' on field m_cellY(path=12/1) for ent npc_dota_creep_lane(C_DOTA_BaseNPC_Creep_Lane) name='npc_dota_creep_lane'
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 52 (122 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 54 (119 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 51 (119 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 106 (116 input number was)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 109 (116 input number was)
`trimmed by moderator`

Desperate for any help with this, tried to find out and solve it myself but I can't find any help for it

**Comment by kisak-valve** [comment]
Hello @Infamous540, noted in https://github.com/ValveSoftware/Dota-2/issues/1212#issuecomment-295431978, the panarama messages are just an indicator that things are running slowly.

**Comment by Infamous540** [comment]
Yea I've read that before and when I was testing while I was making this thread, I got like 20-30 panorama logs within seconds of each another and it didn't take any of my fps, but I'm pretty sure the cswap is ruining my fps and in general the game is just running so awfully shit it shouldn't be possible on that computer? everything is on its lowest and I've done everything I can to tweak and try improve the game but there is something really wrong aswell

**Comment by gdrewb-valve** [comment]
General performance issues are being collected under #1101.  As is mentioned there all platforms have FPS complaints and the larger team works on general performance so there won't be direct responses here.
