### ISSUE TITLE
Issue with loading update from steam from last week - download has been interrupted after 15%

### ISSUE THREAD

**Issue by shadowman79** [ValveSoftware/Dota-2#1227]
Issue with loading update from steam from last week - download has been interrupted after 15%

even if downloading starts again, the issue appears with 15% threshold. Also I've tried to remove downloading folder - to starts update again. Still unable to download client update.

System info - http://pastebin.ca/3809929

**Comment by kisak-valve** [comment]
Hello @shadowman79, this sounds like a [steam](https://github.com/ValveSoftware/steam-for-linux) issue. That said, what filesystem is Dota 2 installed on?

**Comment by shadowman79** [comment]
Ext4

**Comment by shadowman79** [comment]
Hello @kisak-valve, please let me know if need move this one to stream (or just wait) ;-). Also if needed, I can comment after it is resolved.

**Comment by gdrewb-valve** [comment]
Yes, you should open Steam issues in the steam-for-linux tracker.  There may be similar issues already open there also.
