### ISSUE TITLE
Weird behavior while /etc/resolv.conf contains unreachable nameservers

### ISSUE THREAD

**Issue by pwnfoo** [ValveSoftware/Dota-2#1228]
I keep changing my DNS settings and I noticed that Dota 2 client acts weird when the DNS settings are not correct. Steam and Dota 2 launches just fine but Dota client freezes when I attempt to watch a game for quite a while (~1-2min) before recovering from it without throwing any error message. 

### Steps to Reproduce

* Make sure Steam and Dota 2 is not running. Change nameserver in `/etc/resolv.conf` to something unreachable.
* Launch Steam and Dota 2. They work just fine.
* Watch any game or find a match. When the match is accepted / getting ready to watch, the client freezes.

**Comment by gdrewb-valve** [comment]
Is there something you think Dota should do?  It's going to make requests for name resolution and if the networking system hangs because of bad information that doesn't seem like a Dota issue.

**Comment by pwnfoo** [comment]
@gdrewb-valve, DotA shouldn't freeze up. It really confuses people. Everything else works, you are online, you can chat with friends, and everything else but DoTA just freezes up and the only solution is to kill the DotA2 process. It'd be great if DoTA can pop up a message saying 'Could not connect so server` or something as an error message. 

Note that nothing is active during the freeze. I can't even open up the console.

**Comment by gdrewb-valve** [comment]
The freeze isn't happening in Dota though, it's happening in system networking code because the system's configuration is bad.  If you make the change above and ping www.google.com does ping immediately fail with an error?
