### ISSUE TITLE
Imac mid 2011 OS X El Capitan 10.11.6 vision ward bug  

### ISSUE THREAD

**Issue by zero-man001** [ValveSoftware/Dota-2#1229]
Good day. 
Few days ago faced with ward bug problem. As you can see on screen shots blue range of 
 the observer ward permanently freezed on my screen. Any ideas how to solve it? 
Thanks.
![2017-05-12 21 35 01](https://cloud.githubusercontent.com/assets/28658258/26012049/e6edfe9c-375b-11e7-8a22-8998ac300f67.png)
![2017-05-11 13 42 14](https://cloud.githubusercontent.com/assets/28658258/26012065/ef0797e6-375b-11e7-8fdd-c25ae098986f.png)

**Comment by gdrewb-valve** [comment]
This is happening across all platforms and the larger team is taking a look.

**Comment by gdrewb-valve** [comment]
Reopening as the fix rolled out but people are still seeing it, but only on Macs.

**Comment by Vuccappella** [comment]
Replying to the the bug that was closed and merged here:

Yes, I can still see this on Mac. A temporary fix in game for whoever is playing is to hoover with a ward on terrain outside of the map which removes the blue highlights until you show them again or just any terrain that you cant place wards on.

**Comment by zero-man001** [comment]
Still no fix as of today.

**Comment by gdrewb-valve** [comment]
This issue will be updated when there's a change.

**Comment by zero-man001** [comment]
Ok, it's fixed. 
Thank you.

**Comment by gdrewb-valve** [comment]
The latest May 15 update has the fix so closing.
