### ISSUE TITLE
Ward vision bug

### ISSUE THREAD

**Issue by faithxslayer** [ValveSoftware/Dota-2#1230]
I'm playing on Mac and for the past 2 days I had this bug, When I place a ward, there is always the vision field in blue and it goes away only when the ward expires.
It's the same whenever I place an observer on the map

my system info https://gist.github.com/faithxslayer/635cb75238f2f5ef0b12e57c3b61bf88

**Comment by kisak-valve** [comment]
Hello @faithxslayer, "This is happening across all platforms and the larger team is taking a look." (from https://github.com/ValveSoftware/Dota-2/issues/1229#issuecomment-301160441)
