### ISSUE TITLE
Really annoying  ward bug from latest updates.  - Mac.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#1231]
https://www.youtube.com/watch?v=tNIsX8P6AQw&feature=youtu.be 

Seems to happen only on mac from what I can tell, none of my friends on windows have this issue.

If you place a ward with normal cast, before placing it it will display you the vision it would give you in blue and highlight it.

When you place the ward or simply deselect it and not place it or change your action the highlighting should be gone but that does not happen anymore.

This happens in real games and in demo mode and It's pretty annoying. If you select another ward then the highlight will stick around it instead

OS X El Capitan 10.11.6 (15G1212)

27-inch, Late 2012)
3.2 GHz Intel Core i5
24 GB 1600 MHz DDR3
NVIDIA GeForce GTX 680MX 2048 MB

This has been happening before the most up-to date update that Fixed the Monkey King immortal's missing icon.

It was in one of the updates before that.

.

**Comment by kisak-valve** [comment]
Hello @Vuccappella, "This is happening across all platforms and the larger team is taking a look." (from https://github.com/ValveSoftware/Dota-2/issues/1229#issuecomment-301160441)

**Comment by gdrewb-valve** [comment]
This fix for this has already been released.  You are fully up-to-date with a validated install and you're still seeing the problem?

**Comment by Vuccappella** [comment]
Yes, still seeing this.
