### ISSUE TITLE
Pinging is now moved to alt instead of cmd (Mac OS)

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#1233]
Am I loosing it or did the new update changed pinging ? 

Before it was on cmd and X ping was CMD + alt now it's on alt and X ping is on alt+ctrl, intended ?

An option to turn this back on perhaps?

**Comment by gdrewb-valve** [comment]
From what I heard there weren't any changes in this area.  Did you have the Alt modifier customized in your settings?  Do you use any Mac programs to swap Command and Alt on your keyboard?  Does other stuff that traditionally shows on alt, like tower attack ranges, show on alt?  Did it show on Command for you before?

**Comment by gdrewb-valve** [comment]
Also the default has been Alt as far as I know, my Mac does everything on Alt.

**Comment by Vuccappella** [comment]
You can close this, the issue was with me as somehow my built in swap function on mac os wasn't working.

>My Bad.
