### ISSUE TITLE
Dota2 "Universal Access" is turned on Mac and in-game still prompt the message !!!!

### ISSUE THREAD

**Issue by tayhaithian** [ValveSoftware/Dota-2#1236]
ISSUE
Dota2 "Universal Access" is turned on Mac and yet in game still prompt up the message to turn on "Universal Access". I can no longer purchase items, add friend, open up tab to chat under steam window. 

OS
Mac OS Yosemite

STEPS & RESULTS
Turned on via "System Preferences" -> "Security & Privacy" -> "Privacy(tab)" -> "Accessibility" -> "Steam(Checked)"

Screenshot:-
http://imgur.com/a/REINd

Error when right click on friend list and "Accept friend request".

Screenshot of Error pops up in game:-
http://imgur.com/a/fsweb

EXPECTED
We should be able to add friends in game and purchase items or even open the tab window to chat with friends under "Mac OS". 

Please rectify the above. Thank you.

PS:- Posted at Steam Community on this as well. As I'm having difficulty to even purchase a battle pass with this issue around. :/ Very inconvenient.

**Comment by gdrewb-valve** [comment]
This is a Steam issue and not a Dota issue but I'll pass it on.

**Comment by tayhaithian** [comment]
I have posted at least 3 places and none have even bother to take a look. (Given you a like for being responsible and helpful)

**Comment by gdrewb-valve** [comment]
One thing mentioned is that this does not apparently happen on newer versions of macOS.  If you were thinking about upgrading that might be something to try, otherwise you'll have to just wait for some change from the Steam team.

**Comment by LinconFive** [comment]
@tayhaithian this could be work around ...  
you can add outside dota2, which means just enter steam client, and then see your mail box on the top right corner of steam, there might be invite, click on it, and accept the friend invite.

**Comment by gdrewb-valve** [comment]
I believe the current version of the Steam client has changed to no longer require access.  @tayhaithian, is this still an issue?

**Comment by gdrewb-valve** [comment]
Closing in the hope that this no longer applies.
