### ISSUE TITLE
Can't open battle pass

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1237]
hi,
Maybe I am stupid, but no amount of clicking on "Battle Pass" opens it. Did I minimize it somehow?
![battlepass](https://cloud.githubusercontent.com/assets/5174562/26365813/060e72e4-3fe9-11e7-917a-883add29f73b.png)

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Turmfalke2** [comment]
I didn't think my system information would matter for this, but it appears that the battlepass just returned. So I assume it was something on your end?
