### ISSUE TITLE
Performance reduced with the latest update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1238]
Today's "Client Performance Update" reduced the performance on my machine. Prior to the update my FPS was around 90-95 in the mid lane, during the laning phase, now is around 70-75, a drop of about 20 FPS.

System specs: Core i7-3770, 16GB RAM, GTX 760 (driver version 375.66).
OS: KDE Neon User Edition (based on Ubuntu 16.04)

**Comment by gdrewb-valve** [comment]
Every platform has been affected by the update, the larger team is handling things.
