### ISSUE TITLE
[Mac] Cursor when custom game begins

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#124]
Before a custom began, at the screen where the host can arrange teams, I had my cursor hovering above the input. The cursor changed into something like ![image](https://cloud.githubusercontent.com/assets/5674597/8390297/e7ac866e-1c41-11e5-8d45-3bd418064776.png). Then I didn't move my mouse and the host started the game. My cursor remained like ![image](https://cloud.githubusercontent.com/assets/5674597/8390297/e7ac866e-1c41-11e5-8d45-3bd418064776.png) even after hero picking. I used the top left button to go to main screen and went back to game, cursor was changed to normal though.

I was able to reproduce the issue.

**Comment by Tele42** [comment]
For reference, that is a 'text cursor.'

**Comment by SsnL** [comment]
:D learn new things every day.

**Comment by gdrewb-valve** [comment]
Likely not a Mac/Linux issue.

**Comment by gdrewb-valve** [comment]
This happens on Windows too so I've passed it on to the larger team and it won't be tracked here.
