### ISSUE TITLE
[Linux] failed to dlopen "libpangoft2-1.0.so" error=/usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found

### ISSUE THREAD

**Issue by emikulic** [ValveSoftware/Dota-2#1241]
$ cat /etc/debian_version 
9.0

/steam/main/steamapps/common/dota 2 beta/game$ ./dota.sh
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197978336979 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197978336979
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 970/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
 failed to dlopen "/steam/main/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/steam/main/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "libpangoft2-1.0.so" error=/usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /steam/main/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpangoft2-1.0.so)
 failed to dlopen "libpangoft2-1.0.so" error=/usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /steam/main/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpangoft2-1.0.so)
text/uitextlayoutpango.cpp 348 CheckDeepLoadModule():
Unable to load 'libpangoft2-1.0.so', your game install may be corrupted or you may have a system conflict

crash_20170525221804_1.dmp[15203]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170525221804_1.dmp
crash_20170525221804_1.dmp[15203]: Finished uploading minidump (out-of-process): success = no
crash_20170525221804_1.dmp[15203]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20170525221804_1.dmp[15203]: file ''/tmp/dumps/crash_20170525221804_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
./dota.sh: line 104: 15190 Segmentation fault      ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

$ ls -l /usr/lib/x86_64-linux-gnu/libpng*     
lrwxrwxrwx 1 root root     10 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng.a -> libpng16.a
lrwxrwxrwx 1 root root     11 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng.so -> libpng16.so
lrwxrwxrwx 1 root root      9 Mar 14  2016 /usr/lib/x86_64-linux-gnu/libpng12.so.0 -> libpng.so
-rw-r--r-- 1 root root 328198 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng16.a
lrwxrwxrwx 1 root root     19 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng16.so -> libpng16.so.16.28.0
lrwxrwxrwx 1 root root     19 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng16.so.16 -> libpng16.so.16.28.0
-rw-r--r-- 1 root root 206768 Jan 10 05:50 /usr/lib/x86_64-linux-gnu/libpng16.so.16.28.0

I was able to work around this with:

$ sudo debootstrap --components main,restricted,universe,multiverse precise ubuntu-chroot
$ cp ubuntu-chroot/lib/x86_64-linux-gnu/libpng12.so.0 /steam/main/steamapps/common/dota\ 
2\ beta/game/bin/linuxsteamrt64/

**Comment by kisak-valve** [comment]
I took a look at this on my Debian 9 test box. Visible at https://packages.debian.org/search?keywords=libpng12, this version of Debian does not have a package that bundles libpng12.so.0 and you have symlinked it to libpng.so -> libpng16.so, which is abi incompatible.

When launching from steam, this dependency should be resolved by the steam runtime, but it's picking up your symlink due to `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1` (the default).

If you want to run Dota 2 from outside of steam, you need to make sure all dependencies are resolved. One method is to include the steam runtime with the convenience script at `~/.steam/bin/steam-runtime/run.sh` followed by the game.

Closing as this is a system issue.

**Comment by emikulic** [comment]
Sorry, the ./dota.sh bit was misleading. I get the same behaviour when launching from inside Steam. Is the correct solution for me to disable host libraries?

Also, thanks for the steam-runtime pointer; I can confirm the following works:
$ ~/.steam/ubuntu12_32/steam-runtime/run.sh /steam/main/steamapps/common/dota\ 2\ beta/game/dota.sh

**Comment by kisak-valve** [comment]
In my opinion, the correct action is to remove the `/usr/lib/x86_64-linux-gnu/libpng12.so.0` symlink that should not be there.

**Comment by emikulic** [comment]
That also fixes the problem. This seems to be the result of a normal "apt-get dist-upgrade" (it's not a link I created) although no package owns it anymore. Weird.

Anyway, thanks for your help!
