### ISSUE TITLE
[Linux] "In-game font is not shown" problem

### ISSUE THREAD

**Issue by dorcilio** [ValveSoftware/Dota-2#1242]
Hello,
Since I decided to return to playing Dota 2, my game opens normally, but does not display fonts, only text boxes appear.

I reinstalled the game and checked for system updates.
I currently use Linux / Fedora 25 / Kernel 4.10.16-200

System Information in Steam:
`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:        Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 25 (Twenty Five)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.10.16-200.fc25.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11903000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile 

    Driver Version:  3.0 Mesa 17.0.5
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 5206 x 1080
    Primary Display Size: 18,90" x 10,63"  (21,65" diag)
                                            48,0cm x 27,0cm  (55,0cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC269VB
    
Memory:
    RAM:  15863 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  pt_BR.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  53642 Mb
    Largest Free Hard Disk Block:  24622 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Wed May 24 22:07:12 2017 GMT: file ''/tmp/dumps/assert_20170524190708_24.dmp'', upload yes: ''CrashID=bp-ff4bc1ea-7520-4f93-bb22-bb8ad2170524''
    Thu May 25 15:32:22 2017 GMT: file ''/tmp/dumps/crash_20170525123204_1.dmp'', upload yes: ''Discarded=1''`

Print Screen: http://imgur.com/a/mRmsU

Thank you very much in advance!

**Comment by kisak-valve** [comment]
Most likely the same issue as #1195.

**Comment by gdrewb-valve** [comment]
Please let us know if the workaround in #1195 helps for you.

**Comment by gdrewb-valve** [comment]
Closing under the assumption that this is the same as 1195.  If the poster responds with more info that it's different we can reopen.
