### ISSUE TITLE
[Linux] Crash after startup loading screen After updates

### ISSUE THREAD

**Issue by 1m-Arthur** [ValveSoftware/Dota-2#1244]
Hi, i am getting a problem this morning. When i decided to open dota2. the Problem is suddenly dota2 game that I usually play. Now can not be opened again, with crash problems after startup loading screen. after this morning updates 2/6/17.

I've done steam reinstall and backup-restore dota2.
But nothing happened.

> Here is my system Information in Steam:
[systeminfo.txt](https://github.com/ValveSoftware/Dota-2/files/1046895/systeminfo.txt)

> and this my crash .dmp file:
[crash_20170602124037_5.dmp](https://www.dropbox.com/s/vub2ew20shm4lpo/crash_20170602124037_5.dmp?dl=0)

Thank you very much in advance!

**Comment by Zacxxx** [comment]
I'm upping this, if anyone has found a fix

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

**Comment by Zacxxx** [comment]
What do you mean ? 
Do you have any idea how to fix this, or will it be patched soon ?
I can't play my favorite game with my team mate, literally watching them play on windows while we could play together. Anyway, it's sad.

**Comment by Zacxxx** [comment]
Up

**Comment by 1m-Arthur** [comment]
@kisak-valve ups wrong upload. ok, so I tried to launch it again just now and here is the dump. 
[crash_20170602211242_1.dmp](https://www.dropbox.com/s/c9209fqxiezoqzf/crash_20170602211242_1.dmp?dl=0)

> @Zacxxx it's ok bro, i'm just wrong upload file. btw, thanks for helping me

**Comment by kisak-valve** [comment]
I reproduced this issue with my OpenSUSE 42.2 test box and completely closing steam followed by running steam with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal worked around the issue for me, so this is an issue with system libraries interacting with steam. Possibly gcrypt related. Other games are affected.

**Comment by kisak-valve** [comment]
For reference, the second minidump is a SIGABRT mostly in libc and the system libgcrypt.so.20.0.1.

**Comment by Zacxxx** [comment]
Do you want to see the crash report from the steam terminal when i launch Dota ?
https://pastebin.com/raw/YXwcreJE

**Comment by 1m-Arthur** [comment]
@kisak-valve Thank you so much!
`"STEAM_RUNTIME_PREFER_HOST_LIBRARIES = 0 steam"` I have run this command in the terminal and it works, thanks a lot :)

## `Case Closed`

**Comment by 1m-Arthur** [comment]
@kisak-valve Okay, last question. Should i do that command to run dota2? Because when I run dota2 without the command, it crashes as before

**Comment by kisak-valve** [comment]
Until someone figures out exactly what's causing the issue here, yes, you can use that workaround.
Personally, I suspect libgcrypt.so.20 is being dynamically loaded when libgcrypt.so.11 is expected. Let's track this issue at https://github.com/ValveSoftware/steam-for-linux/issues/5000 and it may also be worthwhile to bring this issue to the attention of your distro's package maintainer for steam.
