### ISSUE TITLE
[Mac OS]Unable to connect after confirm the game

### ISSUE THREAD

**Issue by Thunder-mx** [ValveSoftware/Dota-2#1245]
Always can't search game

**Comment by gdrewb-valve** [comment]
Please add a gist of your full system specs.  Also can you add console output from your game session (you can run with -con_logfile to get this)?

**Comment by gdrewb-valve** [comment]
Also has this ever worked?  If so when did it change?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
