### ISSUE TITLE
[Linux] Dota-specific Steam Overlay features not working

### ISSUE THREAD

**Issue by wfrced** [ValveSoftware/Dota-2#1247]
Xubuntu 17.04
When I press 'View Steam Profile' button, default overlay opens but nothing happens. Game Groups, Workshop, Guides, Discussions and Community hub are not working too. Every other feature works. Verifying game files (and purging-reinstalling Steam and the game) doesn't help. Enabling/disabling compositor (compton) doesn't help.

**Comment by kisak-valve** [comment]
Hello @wfrced, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4957. Closing as a duplicate.
