### ISSUE TITLE
[Linux] Chat Wheel issue when having more then 1 screen

### ISSUE THREAD

**Issue by grasdaggel** [ValveSoftware/Dota-2#1248]
Ubuntu 16.06

I'm having weird problems using the chat wheel. Game is on screen2, and when the popup appears it seems that the application is trying to put the cursor on the middle of screen1, whereas always the most left sentence gets used.

**Comment by kisak-valve** [comment]
Hello @grasdaggel, this issue is already being tracked at #1201. Closing as a duplicate.
