### ISSUE TITLE
Dota 2 crashing randomonly on Linux

### ISSUE THREAD

**Issue by ricardoalcaraz** [ValveSoftware/Dota-2#1249]
Title explains it all, my game crashes at random points while playing. Doesn't last even an hour before it crashes. Here's a gist of my system info and the console output:
https://gist.github.com/tinyRickMotherfucker/46f2064badede4cf32ebe9e3753c4115

I'm also attaching the dump files that I have gotten recently. 

What I have tried so far: Validating steam files(multiple times), reinstall nvidia drivers both 32bit and 64bit, -vulkan launch option

[dumps.zip](https://github.com/ValveSoftware/Dota-2/files/1072816/dumps.zip)

**Comment by kisak-valve** [comment]
For reference, the first crash is a SIGSEGV in libGLdispatch.so.0.0.0 (part of the nVidia driver). The second crash is a SIGSEGV in libanimationsystem.so (part of Dota 2). The third, fourth, sixth, and seventh crash is a SIGSEGV in an unmapped address range coming from Dota 2. The fifth is a SIGSEGV in libclient.so (part of Dota 2).

**Comment by gdrewb-valve** [comment]
The larger team is looking at crash issues that affect all platforms and there won't be a lot of immediate status here.

**Comment by ricardoalcaraz** [comment]
Turns out the issue was on my end. The crashes were a result of instability in my CPU which I discovered by running a stress test. I disabled the core and now the game runs perfectly.
