### ISSUE TITLE
[Linux] Can't spin to Bloodseeker by typing BL when selecting hero

### ISSUE THREAD

**Issue by hrzhu** [ValveSoftware/Dota-2#125]
Not sure if it's Linux specific, I just find this when I play on Linux. Typing BL when selecting hero, it stops at Bane.

**Comment by gdrewb-valve** [comment]
Appears to work on Windows.

**Comment by Cheogh** [comment]
I don't have this problem on archlinux in the bot game i tried.

**Comment by gdrewb-valve** [comment]
Not able to repo on Linux either.  Does this always happen?  Could it be that it's missing keystrokes sometimes?

**Comment by davidw-valve** [comment]
It will show the letters you typed on the screen. Do you see "BL" indicating that both the "B" and "L" were registered, or just "B"?

**Comment by hrzhu** [comment]
I think I saw BL on the screen. I tried multiple times, in mm game and local bot. It did happen but I can't reproduce it now.

**Comment by hrzhu** [comment]
Well, it happens again.
Type BE first, it spins to Beast Master.
![2015-06-30_00003](https://cloud.githubusercontent.com/assets/2360542/8423186/0e3b8bd0-1f18-11e5-8140-496a3b93888c.jpg)
Then type BL, it goes back to Bane.
![2015-06-30_00002](https://cloud.githubusercontent.com/assets/2360542/8423192/227002fc-1f18-11e5-91ce-0f1e2b970e28.jpg)

**Comment by supereddie** [comment]
Bloodseeker is disabled in certain custom games (for example, Overthrow) as the hero would be OP. If you look closely at the first screenshot, Bloodseeker should come after Beastmaster, but instead you find Bounty Hunter.

**Comment by hrzhu** [comment]
You're right. BS is banned in overthrow. But I also once had this problem in local bot game, I start a bot game to test this. I might remember it wrongly...

**Comment by hrzhu** [comment]
You're right. BS is banned in overthrow. But I also once had this problem in local bot game, I start a bot game to test this. I might remember it wrongly...

**Comment by gdrewb-valve** [comment]
Closing for now, but if you find a new repro post here and we'll reopen.

**Comment by hrzhu** [comment]
I reproduce the bug in a local bot game, you can see BS is there but can't spin to it.
![2015-07-01_00003](https://cloud.githubusercontent.com/assets/2360542/8446784/e0dc3c14-1fe1-11e5-9aa0-2a5da0b3f195.jpg)
I've played a overthow game before that, maybe it triggers the bug.
This time it's on Windows, so it's not a Linux specific bug.

**Comment by gdrewb-valve** [comment]
I'll pass this on to the larger team.
