### ISSUE TITLE
[Vulkan][Linux] LoadSystemAndDependencies(): AppSystemDict: Error in Connect () of interface 'GameUI011'!

### ISSUE THREAD

**Issue by davay** [ValveSoftware/Dota-2#1252]
I have not encountered this before, not sure when it started happening. The last time I tried Vulkan was quite a while ago and it worked, albeit with some bugs like that not being able to type in steam overlay bug (which has been fixed according to changelog).

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:        Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.31-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  i3
    Steam Runtime Version:  <Runtime disabled>
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.66
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 119 Hz
    VendorID:  0x10de
    DeviceID:  0xfd4
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 2806 x 900
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT1802
    
Memory:
    RAM:  16005 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  368089 Mb
    Largest Free Hard Disk Block:  42363 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Fri Jun 16 01:36:43 2017 GMT: file ''/tmp/dumps/crash_20170615144415_1.dmp'', upload yes: ''Discarded=1''

**Comment by kisak-valve** [comment]
Hello @davay, please copy a log snippet of Dota 2 trying to start up which you can find in `/tmp/dumps/<username>_stdout.txt` and put it in a [gist](https://gist.github.com/) and attach a link to the gist in this issue report.

**Comment by danginsburg** [comment]
Can you also try running vulkaninfo and putting the output on a gist?  This might help confirm whether Vulkan is working at all on your system.

**Comment by davay** [comment]
@kisak-valve https://gist.github.com/davay/9789dc3a324c3cc2d1dddb9476e29c26

**Comment by davay** [comment]
@danginsburg "bash: vulkaninfo: command not found" is there a package I need to download for vulkaninfo? I have nvidia drivers and nvidia-utils

**Comment by davay** [comment]
Hey guys, I got it fixed somehow after reinstalling a lot of the nvidia packages. Thanks.
