### ISSUE TITLE
[Linux Mint] Dota 2/Steam crashes - Experience is unplayable.

### ISSUE THREAD

**Issue by moraesmark** [ValveSoftware/Dota-2#1253]
Over the last few days, Dota 2/steam has been crashing a few times. This has resulted, in 3 abandons, trying to get myself out of LP due to the crashes. In a way, I'm at my hair's end. The experience of the stability is terrible for me. 

This is my system information below:

https://gist.github.com/moraesmark/257e19da707eeb5c8eed21b6acb85bf9

Notes: 
1. My Dota 2 settings are at the lowest, with all add-on settings not selected.
2. Attached - Dmp files from steam settings -> https://we.tl/Pzj0yMeHzX
3. Attached - Dota 2 log snippet from the tmp folder --> https://gist.github.com/moraesmark/869f9ccba7dca58f4b47a5b8db7f0ed9

I'm new to reporting errors, if there's any info needed, let me know. Is there a way that my LP games be removed. I'm honestly just tired of being in LP due to these crashes.

Thanks.

**Comment by kisak-valve** [comment]
Hello @moraesmark, for reference, the majority of attached minidumps are DUMP_REQUESTED in crashhandler.so (part of Steam). It appears that steam is dying from underneath Dota 2 and the game is just the victim in this case.

Based on the ...`assertion "connection->generation == _dbus_current_generation" failed`... spam in your log this issue may be a variation of https://github.com/ValveSoftware/steam-for-linux/issues/4856, which you can try completely closing steam, then running steam with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal and see if it helps.

**Comment by moraesmark** [comment]
Thanks for the quick reply @kisak-valve. So, I started steam, with the terminal command, and so far it looks good. 

This is my terminal output: https://gist.github.com/moraesmark/c7723a18e35ee6a42c11929bc3f3960e
I saw a lot of warnings, and I'm not sure, of what to make of it. 

Thanks!

**Comment by kisak-valve** [comment]
`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` is an env variable. You can set it in any of the common places provided by your distro or make a desktop shortcut that calls `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`.
