### ISSUE TITLE
[linux] Periodic freezing every minute

### ISSUE THREAD

**Issue by mathewmclaren** [ValveSoftware/Dota-2#1256]
For the past 10 days or so in every online game I have (both normal and custom games) there is a ~2 second freeze exactly every minute until the game ends. During the freeze nothing is responsive and there are no animations/sounds. I think the effect begins upon loading into match as it happens in the pick phase. Nothing shows in the Dota 2 console and the effect isn't present in offline games. I tried on both EU West and US East and there is no difference and I've connected to a custom game on Stockholm with the same issue.

I've restarted my router, PC, validated Dota files as well as deleted and reinstalled Dota, tried the low-quality network setting (although I have a 100Mb connection) and nothing has changed. I've also tried installing Dota on my Windows partition and that works with no issues. I don't see anything similar happening in other online games (L4D2). I've tried repeatedly pinging both my router and external servers to confirm that it isn't a local connection issue and neither show any freezes.

Finally, I tried a tcpdump taken during an Overthrow match to see if it provided any information. I've attached the whole thing but the relevant timestamps are xx:xx:38-40. The freeze would happen at 38s and it would typically unfreeze at 40-41s. The first one that I noticed (i.e. ingame) was at 10:27:38 and the game probably started loading around 3 minutes beforehand.
[tcpdump.txt](https://github.com/ValveSoftware/Dota-2/files/1099850/tcpdump.txt)

Please let me know if you want any further information, I've also attached my system info just in case.
[sysinfo.txt](https://github.com/ValveSoftware/Dota-2/files/1099852/sysinfo.txt)

**Comment by mathewmclaren** [comment]
Just an update on this, after several days of this issue I checked again this evening and it looks like it's stopped. Nothing's changed on my end so I'm still not entirely sure what caused it in the first place!

**Comment by Pigeomancer** [comment]
I am having this problem, yet I am on windows. Freezes same time every minute for like 3 seconds. Only online games does this happen. I have tried Dota 2  and resetting my router+modem, yet nothing has worked.

**Comment by gdrewb-valve** [comment]
OK, closing.

**Comment by tmewett** [comment]
Interestingly, I seem to be having the same issue. It *could* be my network setup (I'm using out-of-kernel drivers), but I don't have this freezing in any other real-time online game. I haven't timed the freezing exactly, but it lasts ~2s as described, and it never feels more frequent than every minute. Nothing relevant comes up in the console, though there is a regular message about the particle system.

**Comment by tmewett** [comment]
After some more conscious testing today, it seems the frequency of the freezing has gone down. I had only 4 instances of it in a 30min game. I also had uninterrupted communication in external voip while it was frozen. Some animations still played, ie the client didn't hang. I opened the console quickly after each instance, and there was always a SteamNetSockets message about session switching at the bottom. Is there a way to narrow this down further, @gdrewb-valve? Still willing to accept it's on my end, but atm it looks Dota-related.

```
Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.33-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
```

**Comment by gdrewb-valve** [comment]
It's hard to say since there isn't much information to go on.  I'll pass the comment about steam networking on to the larger team and see if they have any thoughts.

**Comment by gdrewb-valve** [comment]
Note also that there are people like http://dev.dota2.com/showthread.php?t=282717 with exactly the same issue on Windows so the issue is beyond the scope of this tracker.

**Comment by tmewett** [comment]
Ok, thanks

**Comment by gdrewb-valve** [comment]
One that that has come out of the investigation is to check the size of localconfig.vdf in your Steam directory.  Some people are seeing it grow to 100's of megabytes and if it does get that big it can cause glitching.
