### ISSUE TITLE
Dota Application won't launch -> Error dota.sh: line 101. 

### ISSUE THREAD

**Issue by bensohyh** [ValveSoftware/Dota-2#1258]
I'm facing a recent problem with dota not able to launch. Please help...!

Running Steam on centos 7 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)

(steam:7958): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:7958): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)

** (steam:7958): WARNING **: Unknown device type 13

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:7958): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:7958): WARNING **: Unknown device type 14

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type

** (steam:7958): WARNING **: Unknown device type 13

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:7958): WARNING **: Unknown device type 16

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID: Caching Steam ID: 76561198177984301 [API loaded no]

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Unknown setting 'bridge'

** (steam:7958): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Unknown setting 'bridge'

** (steam:7958): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1496897923)

(steam:7958): GLib-GObject-WARNING **: gsignal.c:2516: signal 'child-added' is invalid for instance '0xf84a40e8' of type 'GtkMenu'
Installing breakpad exception handler for appid(steam)/version(1496897923)
roaming config store loaded successfully - 708 bytes.
migrating temporary roaming config store
Failed to init SteamVR because it isn't installed
Installing breakpad exception handler for appid(steam)/version(1496897923)
ExecCommandLine: "'/home/bsoh/.local/share/Steam/ubuntu12_32/steam'"
Installing breakpad exception handler for appid(steam)/version(1496897923)
System startup time: 4.09 seconds
Generating new string page texture 73: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 76: 32x256, total string texture memory is 540.67 KB
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 87: 8x256, total string texture memory is 548.86 KB
ExecSteamURL: "steam://openurl/http://store.steampowered.com/app/633890?snr=1_41_4__42"
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 121: 128x256, total string texture memory is 679.94 KB
Generating new string page texture 122: 128x256, total string texture memory is 811.01 KB
Generating new string page texture 124: 48x256, total string texture memory is 860.16 KB
Generating new string page texture 131: 384x256, total string texture memory is 1.25 MB
Generating new string page texture 132: 24x256, total string texture memory is 1.28 MB
Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8104, IP 0.0.0.0:0

Adding process 8104 for game ID 570
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8106 != 8105, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8108 != 8105, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to Completed with ""
Adding process 8105 for game ID 570
Adding process 8107 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8104
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8117, IP 0.0.0.0:0
Adding process 8117 for game ID 570
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8119 != 8118, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8121 != 8118, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to Completed with ""
Adding process 8118 for game ID 570
Adding process 8120 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8117
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 6] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 6] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8229, IP 0.0.0.0:0
Adding process 8229 for game ID 570
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8231 != 8230, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8233 != 8230, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to Completed with ""
Adding process 8230 for game ID 570
Adding process 8232 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8229
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 139: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 140: 256x256, total string texture memory is 1.54 MB
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 8] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 8] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8238, IP 0.0.0.0:0
Adding process 8238 for game ID 570
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8240 != 8239, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8242 != 8239, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to Completed with ""
Adding process 8239 for game ID 570
Adding process 8241 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8238

**Comment by bensohyh** [comment]
Sorry, but has this been resolved?

**Comment by kisak-valve** [comment]
Hello @bensohyh, no, this issue is currently open as indicated directly below the title at the top of the issue report. If you are reading the in-line closed indicator, that is saying steam-for-linux#5043 is currently closed.

**Comment by Turmfalke2** [comment]
Maybe try the following:
Launch steam from a terminal (I assume that is what you did for the output above)
Open '/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh' and insert a new line with "set -x" after the first line ("#!/bin/bash").
Then attempt to launch dota and post the new output.

set -x should echo every command of the bash script as it execute, hopefully showing why the argument list so ridiculous long.

**Comment by bensohyh** [comment]
Thanks kisak-valve for the update!
Sorry, I haven't been responsive.  But I have taken steam off centos onto ubuntu instead.
Since Turmfalke2 replied, I decided to give centos another try and oddly it worked again even without the bash. I guess it was somehow fixed. Thanks again everyone!

**Comment by bensohyh** [comment]
df -u
