### ISSUE TITLE
[Arch Linux] Dota2 has a longer than expected black splash screen upon loading

### ISSUE THREAD

**Issue by ngkaho1234** [ValveSoftware/Dota-2#1263]
Hi,
After an update on 7/7, Dota2 only showed a black screen upon loading. I tried to run the game by directly running the executable and see if there's anything wrong. I could only quit the black screen by killing dota2 with SIGKILL. I was not sure what was going wrong. 
https://gist.github.com/a74e7f99dc602e078de64c861085d4e5

Here is the output of glxinfo: 
https://gist.github.com/626e70d4a9ea9bbe041dde967759ad4b

and the output of uname -a
https://gist.github.com/ff1317b32af8a1565204e7b050119534

**UPDATES:** 
Actually the dota2 logo will be shown and the game will start to load into the welcome screen after waiting for about 45 seconds.

Thanks

**Comment by ngkaho1234** [comment]
Just now I tried to run the game through gdb, and here is the output of "info threads" command:
https://gist.github.com/ngkaho1234/a953064901623b41bea20b0bfb8b74e2

**Comment by nextdimension** [comment]
Same thing I'm on Ubuntu, black screen on boot of dota 2.

**Comment by safocl** [comment]
I'm all right. archlinux, nvidia proprietary drivers

**Comment by kisak-valve** [comment]
Closing per the OP's update.

**Comment by kisak-valve** [comment]
I'm going to go ahead and re-open this issue per @yash1610's comment on #1260. The original post indicated that the game was failing to start and the update indicated that it just took longer than expected. The most common cause of this kind of long start is if a game needs shaders compiled the OpenGL driver and has to wait for this to complete. This can happen on some game updates, if the video driver version has changed since the last run of the game, or if the OpenGL driver does not support a shader cache. On drivers that support a shader cache, this generally clears up after one run of the game.

Apparently there may be something else slowing down the game's start.

**Comment by gdrewb-valve** [comment]
Possibly related: lots of reddit comments across all platforms about getting stuck at the loading screen, although those are for spectating.

**Comment by yash1610** [comment]
@kisak-valve thank you for being so open to feedback. I'd love to provide any and all manner of info that you may need to diagnose this issue; so just let me know what you need.

[This is the output for when the game is launched from the terminal](https://gist.github.com/yash1610/ca71d635f520a63a9ce9a60089920c93)

[And this is when the game is run with the -vulkan argument](https://gist.github.com/yash1610/cc282e8429440898d09f87524a80e981)

`uname -a
Linux yash1610 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
`
`Nvidia Driver Version: 381.22`

[Steam System Info](https://gist.github.com/yash1610/4d38045b188275ac75ee39711410b898)

P.S the issue remains irrespective of OpenGL or Vulkan. I quit dota as soon as the game loaded into the main menu so the run times for the commands should be fairly accurate with the margin of error being +-1 second

P.P.S @gdrewb-valve have no issues with load times once I am inside the game, no load times grater than 5 seconds. Just the initial loading of the game takes 1+ min.

**Comment by ngkaho1234** [comment]
I try to run the game on a laptop with HD530 as primary GPU and GTX 960M as secondary GPU (Optimus), and the behaviour exhibited is the same as the machine with GTX 1070 as primary GPU: The game now takes much longer time to boot than expected everytime.

Here is the output from dota2 executable running on HD530 (mesa version: 17.1.4-1): https://gist.github.com/ngkaho1234/2b5765bc396297f1efc542e2d18203b4
The time taken to boot and manually quit the game (measured by time from zsh): 57.67s user 1.09s system 100% cpu 58.556 total

The output from dota2 running on GTX 960M via bumblebee method (primusrun): https://gist.github.com/b62cce76e7231250aea50f6c8c696b73
Time taken: 56.73s user 1.28s system 99% cpu 58.588 total

Both machine has the same nvidia driver version installed as @yash1610 .

EDIT: pretty much as @yash1610 described, it is only that booting into the welcome screen everytime takes about a minute (plain black screen for about 40-50 seconds before the dota2 icon appears) .

**Comment by UgoM** [comment]
Same as @ngkaho1234 and @yash1610, since some days, Dota takes one full minute to load instead of 5 sec (stuck on the pre-load black screen).
Using Ubuntu 16.04 though not arch, and nvidia drivers 375.66

**Comment by Taiko2k** [comment]
Also experiencing this issue. Dota now consistently takes about a minute to start while showing a black screen. I'm using Arch Linux with radeon/mesa drivers.

**Comment by danginsburg** [comment]
I was able to repro this here on Ubuntu 16.04.2 on RADV.  Investigating.

**Comment by sylware** [comment]
up-to-date beta steamos
up-to-date stable steam client

Often, when I want to watch a live game (was looking at iceiceice games), I get stuck at the loading screen(dota logo for me) and I must kill the game in the steam overlay.

(I'm adding this note: I'm currently in the steam overlay writting this line, wanted to watch iceiceice game, I'm locked on dota2 logo, I have the watch bottom panel with the game time moving forward)

**Comment by danginsburg** [comment]
The slow startup prior to the loading screen has been fixed, it will ship in the next Dota 2 update.

**Comment by nextdimension** [comment]
Seems this is fixed in the update just now. At least for me.

**Comment by UgoM** [comment]
It works ! You are awesome :) Thanks for the responsiveness.
