### ISSUE TITLE
[Linux] Console input font not showing

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#1266]
![2017-07-07-164035_1920x1080_scrot](https://user-images.githubusercontent.com/425930/27979417-28b82ffc-6333-11e7-8ba2-54797098cb4a.png)

System Info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/53057670a0b1b884c03ad3b7a9ec2f6c0bdef677/gistfile1.txt

Since the last update, you can't see what you're typing in the console. My theory is that the line height or something is set so high that text is being pushed out of the input box. There's weird padding on the autocomplete text.

**Comment by gdrewb-valve** [comment]
There's a fix coming in the next release which likely will help with this.

**Comment by gdrewb-valve** [comment]
Please retest with the update that just came out.

**Comment by jazztickets** [comment]
Works great now, thanks.
