### ISSUE TITLE
web market broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1267]
up-to-date beta steamos
up-to-dato beta steam client (big picture)
web market broken: in the last few weeks the steam web component has been totatly broken, cannot even use the market to buy stuff from dota2.

**Comment by gdrewb-valve** [comment]
I'll pass this on to the Steam team.

**Comment by kisak-valve** [comment]
Hello @sylware, can you also test against the current steam stable client.

**Comment by sylware** [comment]
The current steam stable client has a web component working.
USB mic (as the 3rd audio device on my system) for steam voice is still broken though.
I'll check the beta client on a regular time basis to see when it's fixed.

**Comment by gdrewb-valve** [comment]
This can be closed then as it isn't a Dota issue?

**Comment by sylware** [comment]
Sure, but the weird thing is I have to go through the dota2 team to get
something "solved" by the steam client team (there is an issue an the steam
client project).
:(

**Comment by gdrewb-valve** [comment]
Did you post something in steam-for-linux?  They should have picked it up there.

**Comment by sylware** [comment]
On Sat, Jul 08, 2017 at 04:00:11PM -0700, Drew Bliss wrote:
> Did you post something in steam-for-linux?  They should have picked it up there.

I did.

**Comment by gdrewb-valve** [comment]
Hmm, I guess it got overlooked.  Anyway at least there's a better idea on what's going on.
