### ISSUE TITLE
The server is unconnectable and cannot find match

### ISSUE THREAD

**Issue by wongzigii** [ValveSoftware/Dota-2#1268]
The Dota-2 server is totally unconnectable. Please help! I try to find the match and connect to game server but then I got banned for 1 hours , then 24 hours for nothing!

Same issue can be  found here: http://steamcommunity.com/app/570/discussions/0/1457328392106097963/?tscn=1499520530
http://dev.dota2.com/showthread.php?t=282536

<img width="773" alt="2017-07-09 2 02 34" src="https://user-images.githubusercontent.com/7384288/27988021-d4b1c8aa-644a-11e7-8ab0-4bd13d6425d4.png">

**Comment by gdrewb-valve** [comment]
This issue tracker is for porting bugs specific to Mac and Linux.  dev.dota2.com is the right place to post and it looks like there's already something there.

**Comment by wongzigii** [comment]
Please report this issue to dota-2 dev team asap! We have suffered for this and got banned but there isn't any hotfix or patch for these day.
