### ISSUE TITLE
latest steam client update broke again dota2 web market

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1269]
Wow, got an update of the stable steam client today which broke (crash) again the web component significantly, then dota2 web market. Wonder what's happening there?
up-to-date beta steamos
up-to-date _stable_ steam client
You should really talk to linux steam client team about the issues with their web component.

**Comment by gdrewb-valve** [comment]
You'll want to post this in steam-for-linux.

**Comment by sylware** [comment]
On Tue, Jul 11, 2017 at 05:41:55PM +0000, Drew Bliss wrote:
> You'll want to post this in steam-for-linux.

steam-for-linux Issue updated. I may post a new one as it seems ignored.
