### ISSUE TITLE
[Mac] Weird resolution issue

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#127]
Thanks for enabling 2880x1800 on retina screens. But there are some bugs related to it. I couldn't screen shot on some places so I took photos.

I have a 1440x900 retina 15inch mbp.

Repro step:
Issue 1:
0. Set draw minimap on right.
1. Set display to fullscreen 2880x1800.
2. Start a bot game, select hero and enter game. 
3. Set resolution to 1440x900. The minimap is drawn on the wrong side:
![photo jun 26 9 21 48 pm](https://cloud.githubusercontent.com/assets/5674597/8390567/5e64ee38-1c4f-11e5-9935-aeb48ac9b93b.jpg)
4. Change display to borderless window fixes it.

PS: it seems that 1440x900 first then 2880x1800 under fullscreen causes the same problem.

Issue 2:
1. Set display to fullscreen 2880x1800.
2. Click "restore default". Problem:
![photo jun 26 9 26 21 pm](https://cloud.githubusercontent.com/assets/5674597/8390570/8b9651bc-1c4f-11e5-8f2a-dbfaa3c7b317.jpg)
2. Click "restore default" again. Problem:
![photo jun 26 9 26 32 pm](https://cloud.githubusercontent.com/assets/5674597/8390571/9233d7ec-1c4f-11e5-9f5b-e4aad24a0111.jpg)

Issue 3:
1. Set display to fullscreen 2880x1800.
2. Change the selector to "windowed". Note that the resolution still stays at 2880x1800.
3. Click "apply". Problem:
![photo jun 26 9 23 24 pm](https://cloud.githubusercontent.com/assets/5674597/8390573/b3959542-1c4f-11e5-8103-9072a6d60882.jpg)
4. Click "restore default". Problem: black screen.

Minor issue 4:
Button texts are not centered:
![screenshot 2015-06-26 21 50 14](https://cloud.githubusercontent.com/assets/5674597/8390574/c4089168-1c4f-11e5-8ff5-12c674a94dc2.png)

Suggestion:
Make the cursor larger on high pixel density screens so it would look the same as on normal screens.

**Comment by SsnL** [comment]
Btw, really thank you @gdrewb-valve ! The dev forum isn't half as responsive as you guys here. There is no way to see if a bug is recognized or not.

**Comment by SsnL** [comment]
Another resolution issue:
1. Set display to 1024x786 borderless window.
2. Set display to 1440x900 borderless window. Problem:
![screenshot 2015-06-27 10 12 14](https://cloud.githubusercontent.com/assets/5674597/8393116/7138d2e8-1cb5-11e5-8d07-59dbaed8157a.png)
[This is my full screen]

**Comment by SsnL** [comment]
Another one:
1024x640 actually is 1024x768 under fullscreen.

**Comment by SsnL** [comment]
Another one:
1. Set display to 1024x768 fullscreen
2. Click "restore defaults". Problem:
![screenshot 2015-06-27 10 25 42](https://cloud.githubusercontent.com/assets/5674597/8393153/2b0f80d0-1cb7-11e5-836c-83f66932b49e.png)
3. Change resolution to 1440x900, apply.
4. Click "restore defaults". Problem:
![screenshot 2015-06-27 10 27 05](https://cloud.githubusercontent.com/assets/5674597/8393155/47ac2c7a-1cb7-11e5-89fd-1dc17e749598.png)

**Comment by gdrewb-valve** [comment]
The next release will hopefully fix some of the "Reset to defaults" issues, but we'll have to see how it works for you when it comes out.

**Comment by gdrewb-valve** [comment]
Can you try the 6/30 update?

**Comment by SsnL** [comment]
From 2880x1800 fullscreen, restore default gives me:
![screenshot 2015-06-30 22 38 32](https://cloud.githubusercontent.com/assets/5674597/8448167/d3f4a108-1f78-11e5-91ff-9c97ace12fc7.png)

**Comment by gdrewb-valve** [comment]
If you quit and restart does it come up too big again?  If you hit restore defaults again does it stay this way?

**Comment by SsnL** [comment]
This seems to only happen with I start at larger than 1440x900 resolution and click "restore defaults". I cannot quite normally since I can't see the top right button. When I killed the process and restarted the game, it was 1440x900 borderless window.

**Comment by gdrewb-valve** [comment]
The 7/2 update has another change for this, is this still happening?

**Comment by ssnl** [comment]
Just tried. Not fixed. The behavior is different thought. I started at 2880x1800 fullscreen, clicked restore default, ended up borderless window showing:
<img width="1440" alt="screenshot 2015-07-03 11 36 21" src="https://cloud.githubusercontent.com/assets/5674597/8503683/da998860-2177-11e5-8ce5-58dd8257848f.png">

**Comment by danginsburg** [comment]
This has been fixed.  The fix will be in the next release.

**Comment by danginsburg** [comment]
Fix is in 7/20 release.  Closing this bug, let us know if you still see the problem.
