### ISSUE TITLE
[Linux] FPS drop when switched from Steam Os to Linux Mint 18.2

### ISSUE THREAD

**Issue by anhmiuhv** [ValveSoftware/Dota-2#1271]
I installed Linux Mint 18.2 on my Steam Machine with gtx 960 and i5 intel 6400T 2.2GHz 8Gb RAM

My fps is 34 on lowest setting.

On steam os, I got 112 fps on highest settings. Can I do anything about this?

 GTX 960 driver: 4.5.0 NVIDIA 384.47

``

**Comment by kisak-valve** [comment]
Hello @anhmiuhv, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by anhmiuhv** [comment]
The gist: https://gist.github.com/anhmiuhv/71beb5f531a98978c1b3217f7b8c09c7

**Comment by anhmiuhv** [comment]
Nevermine, I downgrade my NVIDIA driver from version 384.47 to version 381.22 . And after the immortal 3 update it run fine. Thank you guys.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
