### ISSUE TITLE
Can't get steam info. Help -> System Info.

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1272]
With my steam in pt-BR everytime i click to colect system info steam crashes. 100% reproductible.
nothing on dmesg

Arch linux, nvidia blob on gnome 3.24 with intel cpu.

**Comment by kisak-valve** [comment]
Hello @admshao, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4964. You might be able to get better behavior by adding the steam-native-runtime package and running steam-native instead of steam-runtime.

Closing as a duplicate.

**Comment by admshao** [comment]
Oh. I see. Working fine on Native.

2017-07-14 11:06 GMT-03:00 kisak-valve <notifications@github.com>:
