### ISSUE TITLE
[Linux] Game goes down to 15 fps when certains heroes are on screen

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1273]
Hey, i get it. It's absolutely specific and weird but its happening.

Since a couple of weeks ago it started to happen and every match it's a specific and different hero. I was casting TI qualifiers iirc when i first saw this (took long to report because wasn't on linux pc anymore) I can spectate any match on Watch tab and still at least 1 hero per game will slow my fps down to 15fps. Exactly 15. my gpu usage from 50% (150 fps+) goes down to 3...4% and while the hero is in the screen its chopped down. Another thing i noticed is that if the hero is stunned the fps goes back to normal for the duration of the stun.

I tested on the same pc on Windows and it doesn't happen there.

Nothing wrong on console or any warning messages.

I was able to quickly get the info from my system before it instantly crashed as previously reported.
https://gist.github.com/admshao/137d89e0a9d35e635d9282285bcf2031

**Comment by gdrewb-valve** [comment]
Do you have a match ID and a time window for something you were spectating that shows the issue?

**Comment by admshao** [comment]
Hey, I finally could fire up dota again and retested all matches i remembered to see this happen. Mostly SG matches on TI closed qualifiers. 3282193242 for example. But watching the replay now gave me no fps issues. Something after the Treasure III update seems to fixed the issue for me. I had no System update in the meantime
