### ISSUE TITLE
[Linux] Game randomly crashed on main menu after leaving options

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1274]
dmesg:
[  969.594124] traps: dota2[12834] trap stack segment ip:7f67d756295e sp:7ffcff31aa70 error:0 in libtcmalloc_minimal.so.0[7f67d754d000+21000]

System Info:
https://gist.github.com/admshao/137d89e0a9d35e635d9282285bcf2031

**Comment by gdrewb-valve** [comment]
I wasn't able to get this to happen.  If you can narrow it down to a more repeatable cause that would help a lot.

**Comment by admshao** [comment]
iirc i was disabling Animated Portrait in the menu when that happened. I tried to click every setting possible and couldn't trigger it again. It was indeed very random crash that never happened before. I'll close this and reopen if i got a crash again.
