### ISSUE TITLE
Mouse wheel issue

### ISSUE THREAD

**Issue by Patrick-Edouard** [ValveSoftware/Dota-2#1276]
Hi guys.

# Disclaimer
 My issue is maybe linked to this one : https://github.com/ValveSoftware/Dota-2/issues/1264 but I'm not sure so not to polute this dude thread, I make my own.

# The issue
So I got a dual monitor and when I play dota on my primary screen and click the mouse wheel, it makes my mouse cursor move to the right. and I can't move it in any way until I release the mouse wheel and thus trigger the message on the right.
If I do the same thing on my 2nd monitor, the correct behavior is happening.

CF :
Mouse wheel pushed on the 2nd monitor
http://imgur.com/PwABZtS
Few second after using the mouse wheel on the primary monitor :
http://imgur.com/PwABZtS 

# Config
- Fedora (25 & 26)
- Gnome
- Nvidia 970 gtx
- Driver 381.22
- Vulkan enabled

### System info from steam

> Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

> Operating System Version:
    "Fedora release 26 (Twenty Six)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.11.9-300.fc26.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11903000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

> Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 381.22
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.87" x 11.81" (23.98" diag)
                                            53.0cm x 30.0cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

> Sound card:
    Audio device: USB Mixer

> Memory:
    RAM:  16006 Mb

> Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  423777 Mb
    Largest Free Hard Disk Block:  28866 Mb
    VR Headset: None detected

While none blocking it's a bit painfull not to be able to use this. 

Cheers and keep up the good work on your linux support.

**Comment by gdrewb-valve** [comment]
As you mention multimon in the past this has been related to SDL not getting accurate monitor positions.  Assigning to the SDL dev to take a look.

**Comment by admshao** [comment]
It still affects all dual-monitors players. The work around we are using is to set on launch options this string. sdl_displayindex # (where # is the index of your monitor)

**Comment by gdrewb-valve** [comment]
Just for clarity in this issue the need for sdl_displayindex is a completely separate thing than what happens with the mouse wheel.

**Comment by admshao** [comment]
That's interesting. I just ever used that command line to that my mouse
wheel doesn't behave exactly as he reported. No command crazy mousewheel.
with commend perfect mousewheel

2017-07-20 14:51 GMT-03:00 Drew Bliss <notifications@github.com>:

**Comment by gdrewb-valve** [comment]
That would be something like #286.  @Patrick-Edouard, can you confirm whether using -sdl_displayindex affects your mousewheel behavior?

**Comment by Patrick-Edouard** [comment]
Hi, sorry for some reason this notification ended up in spam.

So this -sdl_displayindex # works great thanks you.

**Comment by Patrick-Edouard** [comment]
Actually after restarting the game, I can't put it on my main screen anymore.

Tried with both -vulkan and without and with # from 0 to 3.

**Comment by gdrewb-valve** [comment]
Try adding -phased_window_create also.

**Comment by Patrick-Edouard** [comment]
Seems to depend a lot on the display setting now. It's really effective with desktop friendly mode but not with the windowed anymore.

Thanks for the help.

**Comment by Patrick-Edouard** [comment]
@gdrewb-valve Any chance this could mow work on Vulkan thanks to this commit https://hg.libsdl.org/SDL/rev/a9bd2625fa01 ?

**Comment by gdrewb-valve** [comment]
Dota's Vulkan support doesn't go through SDL so it wouldn't be affected.
