### ISSUE TITLE
[Linux Mint] LoadSystemAndDependencies(): AppSystemDict: Error in Connect () of interface 'GameUI011'

### ISSUE THREAD

**Issue by moraesmark** [ValveSoftware/Dota-2#1277]
Hello, I guess I'm back again, with another issue, as title says.

the dump-log-txt file -> https://gist.github.com/moraesmark/5824bb84494fe9d69d84139fef539d52
the system info-> https://gist.github.com/moraesmark/31177965ff47ee3664c2ce35c2af7b67

I checked previous issues with the same title, and the solutions put forward in the past did not work for me.

**Comment by kisak-valve** [comment]
Hello @moraesmark, in your log, `failed to dlopen "/home/elzero/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so" error=libudev.so.0: wrong ELF class: ELFCLASS32` is the strongest indicator of what's gone awry here.

Can you confirm that Dota 2 can find a 64 bit variant of libudev.so.0?

**Comment by moraesmark** [comment]
For some reason, steam won't even start up anymore for me. 
If i get it started up, any suggestion on how i could confirm that dota 2 can find the libudev.so.0 variant?

**Comment by danginsburg** [comment]
@moraesmark libudev.so.0 should be in the steam runtime

~/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libudev.so.0
~/.steam/steam//ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libudev.so.0

I wonder if you are hitting an issue with STEAM_RUNTIME_PREFER_HOST_LIBRARIES.  You could try running steam with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0.

**Comment by moraesmark** [comment]
Alright, so:
1) ~/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libudev.so.0 -> amd64 folder does not exist, along with the subdirectories.
2) ~/.steam/steam//ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libudev.so.0 -> does exist
3) I am currently running my steam with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0, but the error still persists.

Also updated my nvidia driver again, 381.22. But nothing has changed.

**Comment by danginsburg** [comment]
The lack of the amd64 directory is likely the problem.  I'm not sure how you ended up in that state.  Can you try reinstalling steam?

**Comment by kisak-valve** [comment]
It should be noted that `steam --reset` in a terminal should give the intended re-bootstrap of steam in this case, not purging and re-installing the steam package.

**Comment by moraesmark** [comment]
Alright, Success! The re-bootstrap of steam worked. And Dota is playable. The lib files are back where they need to be.

Thank you, @kisak-valve and @danginsburg! 

Please close the issue :) thanks again!

**Comment by kisak-valve** [comment]
Closing per the last comment.
