### ISSUE TITLE
[mac] dota 2 does not propose high resolutions on 5K iMac

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#1279]
The selectable resolution is capped at 1440x2560 while my display is 2880x5120.

config: iMac with radeon pro 580, macOS sierra 10.2.5.

A workaround is to disable scaling @2X in the macOS monitor settings. Only then are higher resolutions proposed, but it's not a satisfying solution (considering that other source games do propose max resolution without the need to mess with monitor settings).

**Comment by kisak-valve** [comment]
This is functionally the same issue as #1197. Closing in favor of the existing issue report.
