### ISSUE TITLE
[Mac] Newest update broke CMD+TAB and CMD+Q

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#128]
Originally upon the release of Dota2Reborn for Mac there was a bug where CMD+TAB and CMD+Q and other global shortcuts like (CMD+SHIFT+3) wouldn't work in dota and then it got fixed, after the newest update, those commands do not work again.

**Comment by gdrewb-valve** [comment]
Is this in fullscreen like the still-open #6?

**Comment by Vuccappella** [comment]
Yes, sorry for creating the new topic. The issue was fixed, prior to this update but after the update these commands aren't working anymore.

**Comment by gdrewb-valve** [comment]
There wasn't an intentional change, thus #6 was never closed as fixed.  I'll close this as a duplicate.

I assume you're running at your monitor resolution?  If you switch between fullscreen and borderless window but keep the same res do the keys work in one mode and not the other?

**Comment by Vuccappella** [comment]
@gdrewb-valve Yes I'm running dota on my monitor's resolution. Also, Borderless Window does fix the issue. These commands did work for the past 2-3 days on Fullscreen as well, unintentionally I guess.

**Comment by gdrewb-valve** [comment]
If you're running at monitor res using a borderless window (or just the top radio option "Use my monitor's resolution") is usually the better bet anyway since it allows better cooperation with your desktop.  We'll still keep #6 open for fixing fullscreen mode, though.

**Comment by Vuccappella** [comment]
I had problems with borderless window on Source 1 and at the very first release of Reborn (dock was showing etc) so I just stick with Fullscreen but now Borderless Window seems like the way to go.
