### ISSUE TITLE
[Linux Mint] Dota and Steam crash

### ISSUE THREAD

**Issue by moraesmark** [ValveSoftware/Dota-2#1280]
Alright, I'm back again.

So within 24 hours of my last post [https://github.com/ValveSoftware/Dota-2/issues/1277], I had in-game connection disconnect, so I closed Dota 2, and shut down steam, and restarted my router, and restarted steam, steam initiates and closes. Then, I start it again and it starts updating, and steam log-in appears, and all my steam settings are reset to default, and Dota is no longer installed. So I go back to the steam file where Dota 2 was previously installed and its empty. 

Now I'm really confused, as to how this is possible. Did the steam crash force steam to reinstall itself and delete the game files? I ran the re-bootstrap for steam, steam now works, and i used a copy of dota that I stored on the back up external HDD. 

PC info -> https://gist.github.com/moraesmark/31177965ff47ee3664c2ce35c2af7b67
Log file -> https://gist.github.com/moraesmark/960079f2f24be90bc42a8ee4fbdddaf8

Extra Note: Because of my last steam issue #1277, I received an abandon in game. Today, I received another abandon in game. And, I'm in Low Priority. Can I please have an admin reset this?
(2.) If there's more info required please feel free to let me know.

Thanks

**Comment by gdrewb-valve** [comment]
I'm not sure if you're reporting a Dota issue or a Steam issue.  It sounds like this is a Steam issue in that Steam forgot state after the crash?  Did Dota work properly after that?  If so you'll want to file this in steam-for-linux.

You can post a request to get your LP changed at dev.dota2.com although I haven't seen that happen very often.

**Comment by moraesmark** [comment]
I'm not sure where the report belongs to either, because I'm not sure if the in-game disconnect was valid, when my internet was working fine, since i had discord active. But I have been experiencing regularly in game server disconnects randomly. And the steam issue follows that. I have forward this post in the steam-for-linux, and dev.dota2.com.

Feel free to close this then

**Comment by kisak-valve** [comment]
The steam part of this might be related to https://github.com/ValveSoftware/steam-for-linux/issues/5030 / https://github.com/ValveSoftware/steam-for-linux/issues/5035.

**Comment by gdrewb-valve** [comment]
Steam losing your install state should be a separate thing so having them take a look separately is good.  Game disconnects are happening on all platforms and the larger team is looking at that so I'll close this out.
