### ISSUE TITLE
macOS: replays of matches on local host do not appear in the list

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#1281]
I played several games (against bots) on my iMac set as local server.
Replay files are saved in the correct folder, but do not appear in the watch/downloads section.

Curiously, some replays appear. Those that do have names like "2536724802.dem". Some that do not are named like "auto-20160730-0028-dota-Jeanlain.dem"
If I rename the latter like the former, the replay file appears in the list, but does not show the correct heroes and the right date. 

macOS 10.12.6, iMac 5k radeon pro 580.

**Comment by gdrewb-valve** [comment]
I passed this on to the larger team and the response was that it's expected behavior.  The only replays that will show up by default are those with a real match ID and that doesn't include local auto-recorded replays.
