### ISSUE TITLE
[macos] Unable to watch friends game stuck in loading screen and gets timed out after 2 min or more

### ISSUE THREAD

**Issue by visrey** [ValveSoftware/Dota-2#1282]
When I try to spectate the match of anyone in my friend list dota stuck on loading screen for very long time and get Timed out dialog after long time. Not able to interact with dota after stucked in loading screen.

**Comment by gdrewb-valve** [comment]
Issues like this are reported on all platforms so the larger team will handle it and there won't be a lot of status here.  Can you post a gist of your system info from Steam plus a summary of what your internet connection is like?  Also a console log of attempting to spectate might show interesting error messages.

When there's more information I'll pass it on to the larger team.

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by visrey** [comment]
I am not facing this issue now after the update.
