### ISSUE TITLE
MIC NOT WORKING

### ISSUE THREAD

**Issue by sidzxxy** [ValveSoftware/Dota-2#1283]
My mic is not working in the game even though it shows the bar movement in the test mic in steam settings and the audio tab of Dota 2 but it doesn't work in online matches and shows a diagonal red line on the mic icon.

**Comment by kisak-valve** [comment]
Hello @sidzxxy, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
