### ISSUE TITLE
[Mac] Dota2 Lost connection to steam.

### ISSUE THREAD

**Issue by 8e7** [ValveSoftware/Dota-2#1285]
Recently I've had problems loading my dota2, I then called steam support and they told me to use the steam beta client. I did and then my dota2 loaded, but it had an error message on top saying "Lost connection to steam". I've restarted my computer and steam, made sure this problem is dota2 specific, even re-downloaded dota2, but nothing works. Please help!

<img width="1440" alt="2017-07-29 11 17 55" src="https://user-images.githubusercontent.com/30542113/28741725-975da7b6-744f-11e7-8269-b186373c849f.png">

**Comment by gdrewb-valve** [comment]
I'll pass this on to the Steam team.

**Comment by Antiiee** [comment]
Same issue here, I tried steam beta update because steam repeatedly prompted "Steam client out of date" when starting the dota 2 client. That made it possible to start, but not connect to steam. I tried reinstalling steam and Dota 2 but nothing seems to help. I can play on a ubuntu pc on the same network but not on my macbook. 

<img width="1440" alt="screen shot 2017-08-22 at 19 43 09" src="https://user-images.githubusercontent.com/4190245/29579343-d7db602c-8772-11e7-92b9-0c48a418fca6.png">

**Comment by sianyu1** [comment]
Having the same issue. Scoured the web for a solution but there doesn't seem to be one. Seems like this has been going on for some time now.

**Comment by gdrewb-valve** [comment]
Is this still an issue?

**Comment by N-ReZA-A** [comment]
As a quick fix go to Dota 2 in your library, right click, select properties and go to launch options and type '-clientport 27015' then restart your steam and it should work fine.

**Comment by Ayub-Khan** [comment]
@gdrewb-valve yes.

**Comment by zpostfacto** [comment]
Is there anything in the Dota console log?  Can you launch with -vconsole to make sure you get the complete log from the beginning?

**Comment by thomaschan9328** [comment]
I am having this issue as well. -clientport 27015 solution is not working. Restarting steam is not working. Do you need me to send you anything?

**Comment by kisak-valve** [comment]
Hello @thomaschan9328 to workaround the recent regression, opt out of Steam's beta client, allow it to update the steam client, then quit and relaunch the steam client.

**Comment by thomaschan9328** [comment]
@kisak-valve I tried doing this and it didn't work. I just tried again and still no luck. Any other suggestions?

**Comment by kisak-valve** [comment]
Per "This release fixes an issue starting certain games that began after the July 10th Steam Beta release. To apply the fix you will need to reboot your computer after installing this Steam Beta update." in the [2018-07-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) Steam client beta update, please retest this issue.

If the above does not resolve the issue, double check that any launch option workarounds have been removed and verify the game's files.

**Comment by 121watts** [comment]
@kisak-valve can confirm that issue is resolved on my machine after [this](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) update to the Steam Beta Client!  Thank you.

**Comment by thomaschan9328** [comment]
Not sure what fixed my problem, but I just came home and re-enabled steam beta. I restarted steam, and received a dota update as well. Everything worked fine after that. Thanks all

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed in the [2018-07-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) Steam client beta update.
