### ISSUE TITLE
[Mac] Cancel behavior at "create lobby" setting 

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#129]
Actually this is more of a suggestion. 

Current behavior:
When I click on the "cancel" button, the background dark view first disappears with a fade time about 0.5s and then the setting box suddenly disappears.

It feels like that "cancel" button was bugged and didn't respond at first.

Suggested behavior:
The setting box disappears first and then the background view gradually disappears.

**Comment by gdrewb-valve** [comment]
This isn't Mac/Linux specific so I've passed it on to the larger team and it won't be tracked here.
