### ISSUE TITLE
No Valve default guides on macOS

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1293]
There are no no Valve's default hero guides on macOS Sierra for most (or maybe all) heroes (see screenshots).
https://i.imgur.com/mxuSq2b.jpg
https://i.imgur.com/hcHXdcg.jpg

**Comment by gdrewb-valve** [comment]
I doubt this is a Mac-specific issue, I'll check with the larger team.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by gdrewb-valve** [comment]
Closing pending feedback.

**Comment by RankoR** [comment]
@gdrewb-valve when I've last played about a week ago there were no official guides. I will recheck later.
