### ISSUE TITLE
Dota2 reconnect never works.

### ISSUE THREAD

**Issue by kxxoling** [ValveSoftware/Dota-2#1298]
I cannot reconnect to any game since an update before TI7, it just stuck at "start new connection" screen and still not fixed yet. I've been reported several times because of this!

```
OS: macOS 10.12.4.
CPU: 2.7 GHz Intel Core i7
MEM: 16 GB 2133 MHz LPDDR3
Grap: Radeon Pro 460 4096 MB / Intel HD Graphics 530 1536 MB
```

**Comment by gdrewb-valve** [comment]
Connection issues like this occur on all platforms and the larger team is handling them.  You can post at dev.dota2.com or check the other existing posts there.
