### ISSUE TITLE
[Linux] Chat de-focuses when typing the letter 'h'

### ISSUE THREAD

**Issue by WtGuy** [ValveSoftware/Dota-2#1299]
Hello,

For some reason, when using the letter **h** in any chat box, whether it be the chat in game, in picking phase, or at the main menu, the chat boxes de-focus (IE, close or exit out of). It's akin to pressing the **escape key** and is preventing me from ~~flaming~~ talking in game in any way. I've added a gif to help represent this.
Note that in this gif, I attempt to type the word 'publish' with **h**. Note that no abnormalities appear in the console when this occurs. This issue appears in both the native steam and runtime steam environments.

https://gfycat.com/HeavenlyLeafyDarwinsfox

I've attempted to rebind and unbind **h** and in each case, the **h** key did the function it was bound to but also would still close the chat box.

Below is my Systems Information pulled directly from Steam (Note that I attempted to upload a txt instead to prevent a mass amount of text, but github got mad and wouldn't let me upload it).

<details> 
  <summary>System Information </summary>

**Computer Information:**
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

**Processor Information:**
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

**Operating System Version:**
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.12.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  <Runtime disabled>

**Video Card:**
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.50.0 / 4.12.4-1-ARCH, LLVM 4.0.1)
    Driver Version:  3.0 Mesa 17.1.6
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary VRAM: 3072 MB

**Sound card:**
    Audio device: Realtek ALC892

**Memory:**
    RAM:  15994 Mb

**Miscellaneous:**
    UI Language:  English
    LANG:  en_CA.UTF-8
    Total Hard Disk Space Available:  138557 Mb
    Largest Free Hard Disk Block:  94026 Mb
    VR Headset: None detected
</details>
<br>
Thank you,
<br>
WtGuy

**Comment by gdrewb-valve** [comment]
No repro for me.  This is likely some SDL input weirdness, assigning to the SDL dev.

**Comment by phoerious** [comment]
I can reproduce this issue. I can't type h anymore. On the pick screen, it starts searching for heroes as soon as I type h and in game it does weird shit. I don't dare typing anymore.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.12.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.59
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 1440
    Primary Display Size: 23.50" x 13.23" (26.97" diag)
                                            59.7cm x 33.6cm (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15997 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  1834334 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by ghost** [comment]
Same problem on Arch. Really annoying.

EDIT: also using ckb-next.

**Comment by benhili** [comment]
Same issue can be resolved by reconnecting keyboard for me still annoying though

**Comment by KuriKai** [comment]
I was using a logitech k270 wireless keyboard, never had a problem. Bought a new corsair k70 lux rgb today. and it has this issue.

**Comment by WtGuy** [comment]
Good call. I was also using a corsair k70 with the [ckb-next](https://github.com/mattanger/ckb-next) software. Today, out of the blue, my keyboard was not functioning on startup and I had to restart a couple of times and unplug my keyboard before I got full functionality back into my mechanical keyboard. Upon loading Dota, my keys were working just fine, including the 'h' key.

Very good tip from @BenHili.

**Comment by bliz937** [comment]
Same issue here. Corsair k70 lux rgb.

When I run the [notification](https://github.com/mattanger/ckb-next/wiki/CKB-Daemon-Manual#notifications) output, I can see that the h key is being pressed and released. 
My laptop h key works perfectly though.

Trying to disconnect and reconnect the keyboard (while in Dota) seems to work, but when I restart Dota, the issue appears again.

I've had this issue for quite some time.

edit:
I've also not had this issue with this keyboard.

Running the same keyboard (non-rgb) on Windows doesn't seem to have the issue.

**Comment by KuriKai** [comment]
So, It doesn't allow you to type "h" in the in game chat.
You can type "h" in the steam overlay when chatting to friends

Instead of having to unplug the keyboard and plug it back in, you can use the switch at the back of the keyboard to change the poll rate and then back again

Issue doesn't seem to happen when the ckb-next daemon is not running

**Comment by ajele** [comment]
same problem for k65 rgb lux, using ckb, ever since few days ago
probably due to new update on 17.10 ubuntu

switching pool rate makes my keyboard not work anymore, but unplugging and plugging keyboard back in, works

**Comment by benhili** [comment]
@KuriKai that's much easier than switching the keyboard off, I have a k70 so it seems the keyboard itself is having issues with dota

**Comment by WtGuy** [comment]
Hello everyone. I've created a linked issue in the ckb-next repo. Please head on over and provide any information to the developers so that we can resolve this issue. I'm inclined to believe it's a ckb-next issue over a Dota 2 issue, but in case it isn't, I'm leaving this issue open

Edit: Don't be confused by the title of the ckb issue. It was renamed when the source of the problem was narrowed down on

**Comment by WtGuy** [comment]
Problem has a work around solution in the issue listed above. Head on over and make sure it works for you guys.
