### ISSUE TITLE
[MAC] Disconnected after Establishing Connection loading page whenever I accept a Match

### ISSUE THREAD

**Issue by yiytan92** [ValveSoftware/Dota-2#1300]
I'm having the same issue as #1109 

I had no problem playing games 24 hours ago, so i'm not exactly sure what had changed that I suddenly can't connect to games after accepting matches. I was playing on SEA servers with my party of friends, after that when I choose the auto region, which is US West in my case, I can't connect to games I accepted anymore. Has there been any updates on fixing this?

My system specs on my 2017 Macbook Pro

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB

Firewall Settings:

  Mode:	Limit incoming connections to specific services and applications
  Applications:
  com.bittorrent.uTorrent:	Allow all connections
  com.bluejeans.nw.app:	Allow all connections
  com.skype.skype:	Allow all connections
  com.valvesoftware.steam:	Allow all connections
  unity.Blizzard Entertainment.Hearthstone:	Allow all connections
  Firewall Logging:	Yes
  Stealth Mode:	No

**Comment by gdrewb-valve** [comment]
Closing duplicate.

**Comment by yiytan92** [comment]
Is there any update on the fix? Has there been an influx of this problem recently? Why is this happening all of a sudden when I could play normally just yesterday?

**Comment by gdrewb-valve** [comment]
As mentioned in #1109 there won't really be status here since the team running this tracker isn't involved in the work.  The larger team looks at failures regularly and hopefully will find something.

**Comment by yiytan92** [comment]
I don't know if this will help, but even when I try to create a lobby that's connected to US West servers, I'm having the same problem. Maybe if you could forward them this error log, it would help them? Thanks. Pasting the console output here:


[Console] Deleting lobby data from disk.
Telling Steam it is safe to update the app
[SplitPacket]       client =[A:1:4169393160:8982[0]:  split packet seq #26 restarting, just received packet 1, split packet payload will probably be dropped
[SplitPacket]       client =[A:1:4169393160:8982[0]:  split packet seq #27 restarting, just received packet 0
[SplitPacket]       client =[A:1:4169393160:8982[0]:  split packet seq #28 restarting, just received packet 0
[Networking] #GameUI_Disconnect_ServerShutdown[NetSteamConn] Closing Steam Net Connection on socket 'client' to =[A:1:4169393160:8982], handle 20000 (0 (null))
[Networking] Summary of connection to [A:1:4169393160:8982]:
[Networking]     End-to-end connection: closed by remote host, reason code 1069.  (#GameUI_Disconnect_ServerShutdown)
[Networking]         Remote host is in data center 'eat'
[Networking]         Current rates:
[Networking]             Sent: 119.1 pkts/sec   3.7 K/sec
[Networking]             Recv:  11.0 pkts/sec  11.1 K/sec
[Networking]             Ping:32ms    Max latency variance: 2.3ms
[Networking]             Quality: 57.0%  (Dropped:43.0%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:      3,752 pkts         121,428 bytes
[Networking]                 Recv:        362 pkts         373,401 bytes
[Networking]                 Recv w seq:        359 pkts
[Networking]                 Dropped   :        227 pkts  38.74%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (5 total samples)
[Networking]                   0-25  :    0    0%
[Networking]                  25-50  :    5  100%
[Networking]                  50-75  :    0    0%
[Networking]                  75-100 :    0    0%
[Networking]                 100-125 :    0    0%
[Networking]                 125-150 :    0    0%
[Networking]                 150-200 :    0    0%
[Networking]                 200-300 :    0    0%
[Networking]                   300+  :    0    0%
[Networking]             Ping distribution:
[Networking]                 50% of pings <=   32ms
[Networking]                 75% of pings <=   33ms
[Networking]             Connection quality histogram: (6 measurement intervals)
[Networking]                  100  :    0    0%   (All packets received in order)
[Networking]                  99+  :    0    0%
[Networking]                 97-99 :    0    0%
[Networking]                 95-97 :    0    0%
[Networking]                 90-95 :    0    0%
[Networking]                 75-90 :    0    0%
[Networking]                 50-75 :    6  100%
[Networking]                  <50  :    0    0%
[Networking]                 dead  :    0    0%   (Expected to receive something but didn't)
[Networking]             Connection quality distribution:
[Networking]                 50% of intervals >=  61%
[Networking]                 75% of intervals >=  57%
[Networking]             Latency variance histogram: (191 total measurements)
[Networking]                  <1  :    156   82%
[Networking]                 1-2  :     25   13%
[Networking]                 2-5  :      9    5%
[Networking]                 5-10 :      1    1%
[Networking]                10-20 :      0    0%
[Networking]                 >20  :      0    0%
[Networking]         Rate stats received from remote host 13.0s ago:
[Networking]             Sent:  20.1 pkts/sec  21.6 K/sec
[Networking]             Recv: 120.0 pkts/sec   3.8 K/sec
[Networking]             Ping:33ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         No lifetime stats received from remote host
[Networking]     Primary router: lax#70 (162.254.195.71:27048)  Ping = 3+29=32 (front+back=total)
[Networking]         Current rates:
[Networking]             Sent: 119.1 pkts/sec   4.8 K/sec
[Networking]             Recv:  10.4 pkts/sec  10.5 K/sec
[Networking]             Ping:3ms    Max latency variance: 2.4ms
[Networking]             Quality: 53.0%  (Dropped:47.0%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:      4,172 pkts         197,519 bytes
[Networking]                 Recv:        772 pkts         487,281 bytes
[Networking]                 Recv w seq:        748 pkts
[Networking]                 Dropped   :        227 pkts  23.28%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (26 total samples)
[Networking]                   0-25  :   26  100%
[Networking]                  25-50  :    0    0%
[Networking]                  50-75  :    0    0%
[Networking]                  75-100 :    0    0%
[Networking]                 100-125 :    0    0%
[Networking]                 125-150 :    0    0%
[Networking]                 150-200 :    0    0%
[Networking]                 200-300 :    0    0%
[Networking]                   300+  :    0    0%
[Networking]             Ping distribution:
[Networking]                  5% of pings <=    2ms
[Networking]                 50% of pings <=    3ms
[Networking]                 75% of pings <=    4ms
[Networking]                 95% of pings <=    6ms
[Networking]             Connection quality histogram: (10 measurement intervals)
[Networking]                  100  :    4   40%   (All packets received in order)
[Networking]                  99+  :    0    0%
[Networking]                 97-99 :    0    0%
[Networking]                 95-97 :    0    0%
[Networking]                 90-95 :    0    0%
[Networking]                 75-90 :    0    0%
[Networking]                 50-75 :    6   60%
[Networking]                  <50  :    0    0%
[Networking]                 dead  :    0    0%   (Expected to receive something but didn't)
[Networking]             Connection quality distribution:
[Networking]                 50% of intervals >=  65%
[Networking]                 75% of intervals >=  60%
[Networking]             Latency variance histogram: (569 total measurements)
[Networking]                  <1  :    447   79%
[Networking]                 1-2  :     81   14%
[Networking]                 2-5  :     39    7%
[Networking]                 5-10 :      2    0%
[Networking]                10-20 :      0    0%
[Networking]                 >20  :      0    0%
[Networking]         Rate stats received from remote host 13.0s ago:
[Networking]             Sent:  20.1 pkts/sec  21.9 K/sec
[Networking]             Recv: 120.0 pkts/sec   4.8 K/sec
[Networking]             Ping:8ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         No lifetime stats received from remote host
[Networking]     Backup router: sea#46 (205.196.6.135:27024)  Ping = 28+5=33 (front+back=total)
[Networking]     
[Client] CL:  Server disconnected: 69: #GameUI_Disconnect_ServerShutdown
[HostStateManager] CHostStateMgr::QueueNewRequest( Idle (levelload), 5 )
[NetSteamConn] Tried to send ad-hoc to address =[A:1:4169393160:8982], but address is not in list of steam net connections!
[HostStateManager] Discarding pending request 'Remote Connect (=[A:1:4169393160:8982]), 4'
[Client] CL:  Disconnecting from server: #GameUI_Disconnect_Request_HSIdle
[EngineServiceManager] SwitchToLoop levelload requested:  id [5] addons []

**Comment by zpostfacto** [comment]
@yiytan92, it looks like you are getting really high packet loss (47%!) coming back from the relay.  All of your packets appear to be reaching the relay successfully.  So the question is where is that packet loss happening, and why has it gotten worse recently?

There are a few clues that point me in a particular direction.  First, the fact that the packet loss is only from the relay to you, and not from you to the relay.  The other is the fact that it's is so close to 50%.  It makes me wonder if there is some sort of link aggregation (multiple physical connections acting as a single logical link), and one of those physical links is bad.  Another possibility is an MTU problem.

Could you please share this information:
* A link to your steam community profile?  (Or your dota "friend ID"?)
* A traceroute to the relay.  Please share the output of this command:

traceroute --udp --mtu 162.254.195.71

**Comment by yiytan92** [comment]
@fletcherdvalve 
http://steamcommunity.com/id/yiyang92

This is the output from running traceroute 162.254.195.71, I couldn't run it with --udp and --mtu because it wasn't one of the available commands, reading online people are suggesting mac users use the ping command to find the MTU

Usage: traceroute [-adDeFInrSvx] [-A as_server] [-f first_ttl] [-g gateway] [-i iface]
	[-M first_ttl] [-m max_ttl] [-p port] [-P proto] [-q nqueries] [-s src_addr]
	[-t tos] [-w waittime] [-z pausemsecs] host [packetlen]
Yis-MacBook-Pro:~ yiyangtan$ traceroute 162.254.195.71
traceroute to 162.254.195.71 (162.254.195.71), 64 hops max, 52 byte packets
 1  setup.ampedwireless.com (192.168.1.1)  2.461 ms  0.981 ms  1.005 ms
 2  33.71.170.68.belairinternet.com (68.170.71.33)  2.687 ms  4.998 ms  2.367 ms
 3  10.225.3.41 (10.225.3.41)  2.148 ms  3.983 ms  1.945 ms
 4  10.251.16.65 (10.251.16.65)  2.128 ms  1.985 ms  2.073 ms
 5  10.251.60.114 (10.251.60.114)  3.122 ms  2.886 ms  2.170 ms
 6  10.251.92.73 (10.251.92.73)  2.358 ms  2.720 ms  2.143 ms
 7  10.202.0.145 (10.202.0.145)  159.112 ms  3.726 ms  206.857 ms
 8  v313.core1.lax2.he.net (65.19.189.53)  3.344 ms  12.335 ms  11.740 ms
 9  any2ix.coresite.com (206.72.211.129)  5.147 ms  3.803 ms  3.261 ms


Please let me know if I can give you more information

**Comment by zpostfacto** [comment]
Well running a traceroute back to you from the relay definitely shows a bunch of packet loss in the other direction.  I'm asking the guys who run our network if they understand what's going on.

**Comment by zpostfacto** [comment]
There have been some problems with the Coresite Internet Exchange in LA, and it got a lot worse last week.  We've changed some routing, and I'm not seeing that packet loss coming back to you.  Try again!

We're working on better monitoring so we can detect these sorts of localized problems, which occur constantly around the world, but right now we don't really know about them quickly enough.

**Comment by yiytan92** [comment]
@fletcherdvalve I can confirm that I can create a lobby on the US West servers and connect to it now. Thank you so much for following up so diligently on this. This is actually my first time encountering a server side issue, they're always difficult to handle that's why it's important for us gamers to report things with much specificity as possible. Again, thanks so much to you and the valve server devs.

**Comment by zpostfacto** [comment]
Yeah networking is really complicated to debug.  Thanks for providing good technical information.  It's really frustrating to see people complaining and having a bad time, and at the same time providing zero useful information to help diagnose the problem.
