### ISSUE TITLE
[Linux] Cannot reconnect after disconnect

### ISSUE THREAD

**Issue by tukkek** [ValveSoftware/Dota-2#1301]
I cannot reconnect into a match after I disconnect for any reason - either manually or automatically (connection loss, for example). This happens 100% of the time and has been happening at least for months now. The green button to reconnect is shown as normal, with the "abandon" red button right above it but clicking to reconnect shows "connecting..." without any further effects, even if I wait for something to happen.

Manually **restarting the client and then clicking reconnect works as intended 100% of the time** (which is why I didn't think of reporting this earlier and probably what everyone has been using to work around this bug). So, thankfully, it must be a small "current application state" bug, since the functionality itself is working fine after a manual client restart, allowing a match to be joined again.

I'm reporting this as a Linux-specific bug because I fully believe that if this was happening in all platforms for months then it would have been reported and fixed already (many months ago, probably)...

This should be trivial to reproduce. I have only tried this on online matches (ranked / unranked all-pick, which is all I ever play) but any sort of disconnect will trigger the bug 100% of the time, and restarting the client allows me to reconnect every time as well (thankfully ^^). If needed I can do further testing on my machine or send out logs but I think any developer will be able to reproduce it by himself in a couple minutes on Linux.

This issue tracker has been awesome in my personal experience and I want to thank everyone at Valve for the great technical support and great game overall! Hope everyone over there has a nice week :)

**Comment by tukkek** [comment]
My system information:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX-8320E Eight-Core Processor              
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3200 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Debian GNU/Linux testing (buster) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.11.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 710/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 375.66
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x128b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 16.14" x 9.06" (18.50" diag)
                                            41.0cm x 23.0cm (47.0cm diag)
    Primary Bus: PCI Express 8x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  3937 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  253416 Mb
    Largest Free Hard Disk Block:  7553 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by tukkek** [comment]
Renaming to follow the same standard as other issues on the tracker.

**Comment by gdrewb-valve** [comment]
It's extremely unlikely that this is Linux-specific, people report connection issues on all platforms regularly.  I'll send this on to the larger team and see if they want to take a look.

**Comment by tukkek** [comment]
Will you reconsider this statement, please? I don't think this is a connection issue at all. I think for some reason the Linux client isn't even attempting to reconnect due to some interface bug. This is clear by the fact that upon restarting the client the reconnection works fine (it's not a connection issue) and this doesn't seem to be happening on any other platform.

Of course, I know nothing about DotA's internals and it's your game but I'm sure that if any of the Linux developers over there take a look at this ticket beyond a mere review they'll be able verify it that's the case or not in a matter of minutes - so no harm in trying? It's not gonna waste anyone's day or something like that.

I would not post this here if I didn't think this is a platform-specific issue (as I explain above) so please don't just disregard it because it has "connection" in the thread title. This doesn't seem to be a connection issue at all since I can reconnect normally after restarting the client. Thanks you.

**Comment by gdrewb-valve** [comment]
It's most definitely a connection issue in the sense that you clicked on the button to connect and it didn't work.  The underlying cause could be anything, of course, but the user-facing description of the problem is a connection issue.  The reason I stress this is because the many people report connection issues and are not doing any technical analysis of the problem, they just know that when they try and connect it doesn't work.  They may be experiencing the same issue.  Consider http://dev.dota2.com/showthread.php?t=283619&highlight=can%27t+reconnect.  There's no platform posted but as most players are on Windows it's likely this is a Windows user with an issue extremely close to what you describe (can't reconnect after a disconnect).  Why do you say that it doesn't seem to be happening on any other platform?

Also the issue isn't being disregarded; as I mentioned I'm sending it on to devs to see if they want to take a look.

**Comment by tukkek** [comment]
Well, you are disregarding it as a Linux issue, which I strongly believe to be the case - but of course you're the one familiar with Dota and the client port, not me, I'm just an outsider looking in. This doesn't seem to be the same issue as the one you linked for me because I am able to reconnect to the game.

The reason why I think this must be a Linux issue is that if absolutely nobody on Windows was able to reconnect to games 100% of the time then I think it would have raised some seriously big red flags on your end - surely there must be some sort of monitoring for that, including spikes and such, or at the very least user feedback, which would result in dozens of people on the forums, not just one single post with no reply that you've linked me to. As I said before _this has been happening since I started playing Dota_ (many months) and I never seen any complaint about it on reddit or elsewhere so I can't fathom at all it is affecting all clients and systems.

I know this isn't a hard fact to go on but all it takes is 10 minutes to boot the game on Windows and Linux and verify what's happening, since it is reproducible 100% of the time. It could be done in the time I took to write this :) (I have no Windows install here or I'd have done it already)

Anyway, thanks for the quick reply and best of luck with whatever course of action you decide to take, I just hope my report has helpful in getting this fixed soon!

**Comment by gdrewb-valve** [comment]
The devs found what they believe to be the issue -- and it turned out to be Linux-specific -- and an upcoming update will have a fix.

**Comment by ghost** [comment]
Great, thanks for letting us know :).

**Comment by tukkek** [comment]
> it turned out to be Linux-specific

Called it ;) thanks again for the great tech support here on GH, hope it didn't waste much of anyone's time to figure that out! Have a great weekend Drew!

**Comment by DelBianco** [comment]
I had this issue once or twice, i thought it was my connection, but is the same case, close dota2 then run it again i could connect again.

Looking up for the fix :) 

Thanks.

**Comment by tukkek** [comment]
This has been fixed for a couple of days now and the reconnect button is working as intended! Thanks for everyone involved in the fix and I'm happy to have been part of getting this solved on the Linux client.

As the original reporter, I'm closing this bug. Sorry if this isn't standard Valve procedure but of course any Valve dev is welcome to reopen it if necessary (goes without saying, really...)

**Comment by gdrewb-valve** [comment]
Actually having the OP close an issue after verifying the fix is best since then we can be sure it did actually fix their problem.  Thanks for closing the loop.
