### ISSUE TITLE
OS X: [Panorama] DispatchAsyncEvent

### ISSUE THREAD

**Issue by lewishack** [ValveSoftware/Dota-2#1302]
`[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth:`

I keep getting this message endlessly popping up in console, usually 10 minutes into a game and it makes the game really choppy. The game starts stuttering frame-by-frame and doesn't stop.

[Specs](https://support.apple.com/kb/sp620?locale=en_US)

**Comment by gdrewb-valve** [comment]
The message is displayed because the game is running slowly, not the other way around.  There are several OSX perf issues open here already, a couple discussing a similar perf loss over time, so I'm going to close this out.
