### ISSUE TITLE
[macOS] Can't minimize when Steam overlay is active

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1304]
When Steam overlay is active, I can't minimize the game window with Cmd+H shortcut in exclusive mode (see https://github.com/ValveSoftware/Dota-2/issues/1197). If I close the overlay, it works fine.

**Comment by gdrewb-valve** [comment]
Please post at http://steamcommunity.com/groups/SteamClientBeta/discussions/
