### ISSUE TITLE
Frequent libpangoft* segfaults while spectating

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1306]
Dota frequently segfaults while spectating games, with messages such as below spamming the console:

Error in GetKernedCharWidth FT_Load_Glyph of 0x44 / 0x25 in Dota Hypatia Bold (symbol 0): 0x83
Error in GetCharRGBA FT_Load_Glyph of 0x6e / 0x51 in Verdana (symbol 0): 0x86

Also, the minimap option to display heroes as text either doesn't render the text at all or it's missing characters, such as "  ga i en" for Naga Siren.

I have the Liberation font installed, but the crash happens with ttf-mscorefonts-installer or no Arial font at all. Currently on Debian Stretch but I've observed the issue in Arch Linux as well.

There's another issue regarding Pango open on here but that one involves Primus, whereas I'm only on the onboard Intel.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Debian GNU/Linux 9.1 (stretch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.12.9
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11902000
    X Window Manager:  EXWM
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 13.0.6
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13.39" x 7.48" (15.31" diag)
                                            34.0cm x 19.0cm (38.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: VIA VT1802

Memory:
    RAM:  7431 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  371666 Mb
    Largest Free Hard Disk Block:  331341 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
These suggest problems in the font data on your system as they're core Freetype font handling errors.  Validate your Dota install, although that may not help.  It's also possible this is another manifestation of #922, the known scaleform problems when spectating.

**Comment by ghost** [comment]
Managed to get a crash that wasn't discarded:
Mon Sep  4 21:11:42 2017 GMT: file ''/tmp/dumps/crash_20170904141036_1.dmp'', upload yes: ''CrashID=bp-f7029e1b-6270-484d-b946-332822170904''

I set  "+r_sync_scaleform_frame_and_render 1" and disabled the Steam overlay but the issue still persists.

I also tested my system versions of libpango* and libfreetype* but that didn't do anything except make the fonts bigger. ;)

**Comment by gdrewb-valve** [comment]
That crash is in libfreetype.so.6.11.1 so it looks like corrupt state that crashes multiple versions of Freetype.  It could be your font cache or the fonts themselves but you'd have to check on a Freetype forum to get more info there.

I'd recommend again that you validate your install if you haven't already.

**Comment by ghost** [comment]
I can't reproduce this anymore.

libfreetype.so.6.12.3

Not sure what fixed it. Upgraded graphics stack to Mesa 18something too.

**Comment by gdrewb-valve** [comment]
Thanks for the update, I'll go ahead and close this.
