### ISSUE TITLE
[Linux] Lost connection to Steam

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1308]
hi,
Since today, when ever I start Dota 2 it just shows me a "Lost connection to Steam" message and everything in the UI is filled with place holders. Outside the game I can see my friends steam just fine and navigate the shop without issues.
Since there is no reddit thread with thousands of upvotes, I assume this is not an issue with the server/all platforms.

![dota_placeholder](https://user-images.githubusercontent.com/5174562/29941270-586c22be-8e92-11e7-902e-7cf68162eaa1.png)

E: My config seems also be missing, is it stored on the server?

E2: From the console:
[Server] SV:  CGameRulesGameSystem::GameInit installed game rules
[ResourceSystem] Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)
[SchemaSystemUtils] WARNING: Schema upconversion occuring for large data (14kb): models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vphys
[Server] SV:  Spawn Server: hero_demo_main
[Server] CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[Server] SV:  Connection to Steam servers successful.
[Server] SV:  VAC secure mode is activated.
[VScript] Hero Demo game mode loaded.
[VScript] sHeroSelection: npc_dota_hero_alchemist
[Server] CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
[Client] CL:  CWaitForGameServerStartupPrerequisite done waiting for server
[Client] CL:  CCreateGameClientJob creating client connection to 'loopback'
[Client] CL:  Connected to 'loopback'
[Server] SV:  Sending server info to client 'unnamed' at loopback
[Server] SV:  WriteInitialSpawnGroups sending 1 groups
[Client] Game: "Dota 2"
[Client] Map: "hero_demo_main"
[Client] Players: 1 (0 bots) / 64 humans
[Client] Build: 7560 (revision 4118443)
[Client] Server Number: 2
[SignonState] CL:  CNetworkGameClient::ProcessServerInfo

E3:
Launching steam from a terminal I see plenty of:
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.

Even before I entered my password (steam keeps forgetting my login details)

**Comment by gdrewb-valve** [comment]
What version of the Steam client are you running?  Have you applied any Steam client updates recently?

**Comment by gdrewb-valve** [comment]
Also do any other Steam games that offer Steam features, particularly 64-bit ones, work?

**Comment by Turmfalke2** [comment]
Steam built is from Aug 28 2017 at 11:55:28, I haven't manually applied any updated, but I guess the one from 28 was automatic?

Not sure what you consider "work" in this context. I can launch Civ V, but I don't think that requires a special steam connection.

**Comment by gdrewb-valve** [comment]
Right, you'd need to try a different game which actually uses a Steam connection, such as showing your Steam friends or Steam store items or the like.  Then you'd look and see if you're getting SteamAPI_Init errors there too.

**Comment by Turmfalke2** [comment]
I mean I am already getting them outside of the game, even before I log in. Assuming this is a network connectivity issue, can you tell me the ip it is trying to reach?

**Comment by zpostfacto** [comment]
Info like that can be found in [steam_folder]/logs/connection_log.txt.  Can you share that, as well as a link to your steam community profile?  We can compare your records on our backend.

**Comment by Turmfalke2** [comment]
[connection_log.txt](https://github.com/ValveSoftware/Dota-2/files/1268406/connection_log.txt)

http://steamcommunity.com/profiles/76561198117772231

**Comment by zpostfacto** [comment]
Doesn't look like it's a networking problem.  I don't see any actual connection issues.  In your steam client, at the bottom, you will see "No connection" if you get disconnected from Steam.  I think the real problem is that it isn't able to initialize the APIs for some reason, and the client is interpreting that as "not logged into steam".  I think it's confused about the AppID that is running or something.

You shouldn't need a steam_appid.txt file if you launch from Steam.

I presume you've already done the standard things like verifying your local game files?  (And delete steam_appid.txt file.)

**Comment by Turmfalke2** [comment]
E: Can't ping:
CM01-TYO.cm.steampowered.com (45.121.186.10)
CM-01-WAW1.cm.steampowered.com (155.133.230.34)

Can ping:
cm03-ord.cm.steampowered.com (162.254.193.46)
cm01-ord.cm.steampowered.com (162.254.193.6)
cm02-ord.cm.steampowered.com (162.254.193.7)
CM02-LON.cm.steampowered.com (162.254.196.41)


The steam client considers me connected, I haven't deleted steam_appid.txt, looking into that next.

No I haven't verified my local game files, but given that the API issue exists already before I even log in, I think verifying my local game files is unlikely to fix it. I will try it anyway.

**Comment by zpostfacto** [comment]
Would be interested in the contents of content_log.txt after you verify, if it thinks any files mismatched and needed to be re-fetched.

**Comment by Turmfalke2** [comment]
After removing ".steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/steam_appid.txt" and restarting steam I get this:
[2017-08-31 22:24:28] Verifying installation...
[2017-08-31 22:24:28] Performing checksum verification of executable files
[2017-08-31 22:24:29] Verification complete
[2017-08-31 22:51:15] Shutdown
turmfalke@Industria ~ $ steam 
Setting up Steam content in /home/turmfalke/.local/share/Steam
rm: cannot remove '/home/turmfalke/.steam/steam': Is a directory
Running Steam on gentoo 2.2 64-bit
STEAM_RUNTIME is enabled by the user
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1503954609)

and it gets stuck/fails to display the login window.

E: restoring the file did not fix this, guess I have to --reset

E2: --reset did nothing

E3: Checking something, I think I know what is causing the steam not launching issue.

**Comment by Turmfalke2** [comment]
Ok, the issue with steam not launching was related to me doing some updates in background, including the nvidia driver. This is no finished and steam starts again, unfortunately the --reset killed the log directory.
However the original issue still persists, as in SteamAPI_Init fails.

Validating Dota 2 found one 1 file that failed to validate.
[content_log.txt](https://github.com/ValveSoftware/Dota-2/files/1268613/content_log.txt)
Not sure what was wrong with the steam.sh, I might have had a debug echo in it. However replacing that seemed to have no impact on the SteamAPI issue.

**Comment by gdrewb-valve** [comment]
The Steam team mentioned that they thought you might have a corrupt Steam install.  If you want to try, can you completely remove Steam and reinstall it?

**Comment by Turmfalke2** [comment]
Isn't that what --reset does? I am not looking forward to downloading all games again, but I could do that if necessary.

**Comment by kisak-valve** [comment]
You should be able to move the ~/.local/share/Steam folder somewhere safe, and test its replacement without deleting your steamapps folder. If that does not help, you can either move it back into place or copy the steamapps folder into the new instance while steam is not running to avoid redownloading all your games.

**Comment by Turmfalke2** [comment]
Doing that right now, given that it is getting late it might have to wait until tomorrow evening (in ~18h)

**Comment by Turmfalke2** [comment]
Moving ~/.local/share/Steam away didn't fix the issue:

[S_API FAIL] SteamAPI_Init() failed; Sys_LoadModule failed to load: /home/turmfalke/.steam/sdk64/steamclient.so
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

However ~/.local/share/Steam is now at 8.2M compared to the 2G it was before considerably smaller.

**Comment by Turmfalke2** [comment]
OK, I also moved ~/.steam away and recreated it, ~/.steam/steam is now a symlink to ~/.local/share/Steam unlike before. I guess at some point in the last few years this changed and would explain why steam was always trying to remove ~/.steam/steam.

It appears that after restoring steamapps I have once again a working steam installation and Dota 2 no longer has trouble connecting to the SteamAPI. I quick glance over the terminal output reveals some lines like:  
registry.cpp (250) : Assertion Failed: on disk registry has changed and is marked dirty - we're about to lose data.
Assert( Assertion Failed: on disk registry has changed and is marked dirty - we're about to lose data. ):registry.cpp:250
 failed to dlopen "/home/turmfalke/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/turmfalke/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory


If those are of no concern feel free to close this issue.


And thank you for your help.

**Comment by gdrewb-valve** [comment]
The librenderdoc error is expected and harmless.  Does the registry assert occur every time you start?

**Comment by Turmfalke2** [comment]
No, I can't reproduce it.
I just get a dbus asserts now:
process 1889: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
This is normally a bug in some application using the D-Bus library.

**Comment by gdrewb-valve** [comment]
Thanks.  There are a number of dbus issues open in steam-for-linux so I'm going to close this out.
