### ISSUE TITLE
No Hero Selection When Creating a Lobby With Game Mode: Limited Heroes

### ISSUE THREAD

**Issue by Findam** [ValveSoftware/Dota-2#1310]
This is on Linux, but I have seen the same issue on a friends Mac.

When creating a Lobby, if I set the Game Mode to Limited Heroes I get the following issue:

* The DOTA2 logo is a simple two tone version (red background, dark red logo, black bar across the bottom of the screen).
* The time when I would be picking a hero the screen is briefly black, then I can see a faint, dark instance of the map. I can scroll around this map using the edge panning, and can zoom further in using the scroll wheel.
* After the time that it would usually take to pick heroes I load into the game but have no hero. My portrait at the top is blank, and I have no HUD at the bottom except the mini map.

To reproduce the issue:

1. Launch DOTA2
2. Click PLAY DOTA
3. Click CREATE LOBBY
4. Click EDIT for the LOBBY SETTINGS
5. Select the GAME MODE: Limited Heroes
6. Select LOBBY VISIBILITY: Unlisted
7. Click OK

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-93-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2
    Driver Version:  4.4.0 NVIDIA 340.102
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 17.05" x 10.63" (20.08" diag)
                                            43.3cm x 27.0cm (51.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: %s1

Memory:
    RAM:  15987 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  234595 Mb
    Largest Free Hard Disk Block:  166203 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by Turmfalke2** [comment]
I can confirm this, but I somewhat doubt this is a linux/mac only issue. Unfortunately limited heroes has a reputation for being horribly buggy. If you are a new player you are probably better of playing all pick and avoid picking heroes marked with a complexity of 3.

**Comment by gdrewb-valve** [comment]
This happens on Windows also, the larger team will take a look at some point.
