### ISSUE TITLE
[MacOS] Huge framedrops on new iMac 27" (2017)

### ISSUE THREAD

**Issue by mrexot** [ValveSoftware/Dota-2#1317]
Hi, I have huge framedrops and freezes in dota (150-30 FPS) on my new iMac 27" 2017 (i5 7500, 3,4Ghz, 24GB RAM, 500GB SSD, Radeon Pro 570 4GB), macOS Sierra 10.12.6.

Game is almost unplayable in big fights, its impossible to quickly select multiple units using mouse etc. Need to fix this, I read numerous of similar reports for Dota under Mac. Tnx.

**Comment by gdrewb-valve** [comment]
Closing duplicate.

**Comment by jodaka** [comment]
@gdrewb-valve what's the original issue to watch? I'm also experiencing huge frame drops (from 70 to 10-15) on latest macbook pro 15". And haven't experienced such problems on older macbook pro 13" from 2015, so I'm not even sure who to blade, Apple or Dota.

**Comment by mrexot** [comment]
I tested Dota 2 on my older Macbook Pro 15 on El Capitan and the situation is the same. I think, its problem of Dota itself, not Mac OS. Before, I was playing dota for 3 years without problems.

**Comment by gdrewb-valve** [comment]
@jodaka , search for "mac fps" on this tracker and you'll see a bunch of open issues.
