### ISSUE TITLE
[MacOS Sierra] Stuttering, FPS drops, unplayable

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1319]
Hi

On my machine on Windows 10 i get steady 120fps on ultra settings 1920x1080.
On MacOS 10.12.6 the game is unplayable, i get about 50-70 fps on ultra settings (sometimes they go up to 100), sometimes they drop to 20, They game also stutter alot.

Same problem exist for me in CS GO, but all non-Valve games work perfectly.

I am on Nvidia web driver newest version (378.05.05.25f01).

OS: Mac OS X 10.12.6 16G29
Process: 64-bit, OS: 64-bit
Nvidia GTX 970 Evga
8GB ram
i5-4690k
SanDisk SSD

Oh and also if i lower settings i still get stutter which is really weird.

**Comment by gdrewb-valve** [comment]
As you have issues in CS:GO the problem isn't a Dota issue.  As mentioned in the other Mac perf issues here there are known problems with Apple's OpenGL support that may explain what you're seeing.  You will want to report this to Apple also.
