### ISSUE TITLE
[Mac] Custom game search bar indicator

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#132]
Displaying the searching indicator shouldn't make the search bar shorter.

Original:
![screenshot 2015-06-26 23 52 21](https://cloud.githubusercontent.com/assets/5674597/8390897/7a937830-1c5f-11e5-9a32-7668626ce8e4.png)

Searching:
![screenshot 2015-06-26 23 57 10](https://cloud.githubusercontent.com/assets/5674597/8390898/81cfd828-1c5f-11e5-826d-99c5735b7027.png)
Note how the indicator "replaces" the left part of the search bar.

Search finished:
![screenshot 2015-06-26 23 52 34](https://cloud.githubusercontent.com/assets/5674597/8390899/8b2ac73e-1c5f-11e5-9e01-ae6aaeb5ca59.png)

**Comment by gdrewb-valve** [comment]
Likely not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
Confirmed that this happens on Windows too, I'll pass it on to the larger team.
