### ISSUE TITLE
[Linux] [AMD] keeps crashing multiple times during one game

### ISSUE THREAD

**Issue by imp1sh** [ValveSoftware/Dota-2#1321]
Hi,

I have the following setup:

Ubuntu 17.04
Sapphire Nitro+ Radeon RX 580 Special Edition (not deluxe edition)
amdgpu-pro-17.30-465504
Kernel: 4.10.0-35-generic
Dota 7.06f with parameters "-vconsole -vulkan"
Intel i5-4460
Cinnamon Display Manager
Steam System Information: https://gist.github.com/imp1sh/2a42318098962ab0114d151486b2833c

I have major issues playing. Just did a game and I had 5(!) crashes. Hardly a game without crash. One or two crashes per game is where I assume the average is.
What can I do to give you more debugging information?

I play on two other environments using Linux:
Fedora 26 with Intel Iris Plus i7 7560 and
Fedora 26 with Nvidia GTX 660.

The amount of crashes is bigger on my AMD platform by far (!).

**Comment by kisak-valve** [comment]
Hello @imp1sh, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, please include any CrashIDs or minidumps related to this issue.

**Comment by imp1sh** [comment]
Thank you. I updated the issue. The only thing I don't know how to find is where I can find CrashIDs or minidumps.

**Comment by kisak-valve** [comment]
Minidumps generated by steam and steam games are commonly found in /tmp/dumps. You may find some CrashIDs in the log at ~/.steam/error.log

**Comment by gdrewb-valve** [comment]
If you run without -vulkan does that reduce the frequency of crashes?

**Comment by imp1sh** [comment]
Haven't tried without -vulkan, yet. Here are the files you referred to kisak-valve.
[error.log](https://github.com/ValveSoftware/Dota-2/files/1326545/error.log)
[dota_crash_dump.tar.gz](https://github.com/ValveSoftware/Dota-2/files/1326544/dota_crash_dump.tar.gz)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libpanorama.so (part of Dota 2).

**Comment by imp1sh** [comment]
I just removed amdgpu-pro and tried the non vulkan-ready amdgpu driver. It's more stable for sure. Still waiting for my first dota crash to come :-)

**Comment by imp1sh** [comment]
With admgpu driver also having crashes, frequency dropped a bit but still really annoying sporadic crashes. I will try to burn in my components even though I'm seeing those crashes in dota exclusively.

**Comment by imp1sh** [comment]
Well this didn't help much. I threw the AMD GPU away, also Linux. Same system running macOS Sierra with Nvidia hardly any crashes.
