### ISSUE TITLE
Unable to join Matchmaking due to VAC

### ISSUE THREAD

**Issue by Storm-Engineer** [ValveSoftware/Dota-2#1324]
I returned to the game after a long break.

I cannot play because I get a popup telling that "something is blocking VAC". I'm clueless about this.

 - Running official Steam for Linux
 - I did not temper with Dota or Steam files
 - I don't have any cheat program (for any game) installed
 - I was never VAC banned
 - Tried verifying game files to no avail

Arch Linux 64 bit

Apparently a huge number of people have this issue but all the suggestions I found are for Windows. Some people said that VAC doesn't work anymore for 64 bit but that wouldn't make sense.

**Comment by Storm-Engineer** [comment]
UPDATE: Found the cause for me.

Under DLCs the old "Reborn Beta" was still ticked. I tested several times, if ticked, I get VAC error, if unticked, all works fine.

**Comment by tycho** [comment]
What's your Steam ID? I'll check what's going on in the backend.

**Comment by Storm-Engineer** [comment]
My id is "stormhun".

Someone else also reported in a thread I made that unticking Reborn Beta fixed the issue for them. See here: http://steamcommunity.com/app/570/discussions/0/1489987634007440912/#c1489987634008667401

**Comment by tycho** [comment]
Aha. I think your issue may be caused by something else that was fixed just a couple of days ago. Let us know if it comes back.

**Comment by Storm-Engineer** [comment]
Just to confirm, it is fixed indeed. I can now search for game while the Reborn Beta DLC is enabled.

P.s.: Does the Reborn Beta DLC still actually do anything at this point? I see no change.

**Comment by tycho** [comment]
I believe the checkbox does nothing right now. So unchecking it was kind of a combined timing+placebo effect.

**Comment by Storm-Engineer** [comment]
I don't think so. After unchecking fixed matchmaking, I checked it again to test and got error again - I repeated this 3-4 times and it was completely consistent.

But oh well. For now it works and that's the point. :)
