### ISSUE TITLE
Muting ignores people

### ISSUE THREAD

**Issue by Patrick-Edouard** [ValveSoftware/Dota-2#1325]
Hi,

I don't think the following is linux specific. I'm running on 

- Fedora 26
- Gnome 3
- Nvidia 970 + latest blob driver

So I usually play with a couple of friends using third party chat application. Not to hear each other twice, we use to mute ourselves in the dota game.

It appears that using this features also ignores the muted friend, so wgile still seeing each other in our friendlist, we don't recieve any invitation to join a party anymore.

Now that we know where it comes from, we mannually un ignore each other.. But at start we spent quiet some time figuring out why the invitation weren't working (blaming the game coordinator thingy and so on, restarting game, steam and even the system).

Point is, this 'feature' seems to bring more issues than anything to me, and I would like to disable it (and can bring more issue to people not aware of it). 

Regards.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
The initial response from the Dota team was that this was working as expected so that people you are ignoring can't harass you with Steam messages.  If you want to request changes to how things work you can post at dev.dota2.com
