### ISSUE TITLE
Game Cordinator kicking me from game

### ISSUE THREAD

**Issue by arthurmalakian** [ValveSoftware/Dota-2#1328]
I do keep losing my connection from game... the message that keeps poping up is "No Steam Logon" something like that. What do I do?

I think it got something to do with Ubuntu, i never had this issue when I used to run Windows

**Comment by gdrewb-valve** [comment]
Please post a gist with your full system info from the Steam client and also with console output from running a game.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
