### ISSUE TITLE
[Linux] Dota opens on wrong monitor with no way of changing it. 

### ISSUE THREAD

**Issue by Joelthezombie** [ValveSoftware/Dota-2#1329]
OS: Mint 18.2 sonya
Kernel: x86_64 Linux 4.10.0-37-generic
Shell: bash 4.3.48
Resolution: 3840x1080
DE: Cinnamon 3.4.6
WM: Muffin
CPU: Intel Core i5-6600K CPU @ 3.9GHz
GPU: GeForce GTX 980 Ti
RAM: 16GB

Whenever I go to play Dota 2 it starts on my secondary monitor and the only way I've been able to fix it is to either change my primary monitor setting to be my secondary monitor (Which messes up my entire setup) or to disable my secondary monitor and reset it but that doesnt persist when I restart dota. 

I have when into the monitors.xml and made sure my main monitor is the primary and it is, I also added the launch command "-sdl_displayindex [0 -1]" and that does nothing. I've also tried going to windowed, then moving the window over to the main monitor and then going back to fullscreen but it just always goes to my secondary monitor. 

I've looked at a number of google results for it and tried all their fixes with nothing to show for it in the end. I also made a post on the /r/dota2 subreddit to no avail.

**Comment by gdrewb-valve** [comment]
Are you using OpenGL or Vulkan?  If you aren't using Vulkan and you add -phased_window_create to your launch options does that help?

**Comment by Joelthezombie** [comment]
That worked thank you so much! 

For anyone who may have this issue in future, I turned off vulkan support and my launch options look like this. 

-sdl_displayindex 0 -phased_window_create -opengl

**Comment by admshao** [comment]
just -sdl_displayindex # solves the issue as reported before here a few
times. Even on vulkan

2017-10-23 20:17 GMT+00:00 Joelthezombie <notifications@github.com>:

**Comment by gdrewb-valve** [comment]
Some desktop environments need -phased_window_create and some people have specific problems with Vulkan (such as #962).  Closing this as the other issues are already open here.

**Comment by foxmike** [comment]
-phased_window_create works for me.  thanks!

**Comment by mastertheknife** [comment]
@gdrewb-valve in Left 4 Dead 2 its possible to select the display screen, and it works beautifully.
Please add that to Dota 2 as well, it would have saved me 5 minutes of searching for this solution and will help others with the same issue.
P.S: I used "-sdl_displayindex 1"

**Comment by Ulti-FD** [comment]
What master said, this really should be an in game option.

**Comment by simplystic** [comment]
Using just "-phased_window_create" worked like a charm!

**Comment by samuelborn** [comment]
> Are you using OpenGL or Vulkan? If you aren't using Vulkan and you add -phased_window_create to your launch options does that help?

You find the launch options in Steam: Library > Dota 2 > Right Click > Properties > General > At the bottom

**Comment by NiKeYiGuN** [comment]
Using just "-phased_window_create" worked like a charm!
