### ISSUE TITLE
[Mac] Aliasing in the minimap

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#133]
There is no antialiasing in the minimap. This may be new to the 26/6 update, since I haven't noticed this issue before. 
This is regardless of the antialising setting. 

Radeon 7950, OS X 10.9.5.

**Comment by danginsburg** [comment]
This issue is not Linux/OSX-specific as it appears on Windows/DX9 as well.  I have let the larger team know about this issue, but will not track it here.
