### ISSUE TITLE
[macOS] XP progress of player appears on the first enemy in list

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1331]
I've noticed that in some games I can see my own XP progress on the first enemy in players list (see legion commander and WK).

![image](https://user-images.githubusercontent.com/71142/32219365-0262cea4-be3f-11e7-9c75-9c2cd7b36b97.png)

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.
