### ISSUE TITLE
[macOS] the mouse is virtually unusable in the 7.07 test client

### ISSUE THREAD

**Issue by aenglisc** [ValveSoftware/Dota-2#1332]
It feels as if the mouse would randomly have its left button stuck in the pressed position.

**Comment by gdrewb-valve** [comment]
Are you still seeing this with the full release today (Oct. 31)?

**Comment by aenglisc** [comment]
Nope, the release version works fine.

**Comment by gdrewb-valve** [comment]
Thanks, closing (the test client will stay broken until the next time it updates).
