### ISSUE TITLE
[Linux] Client will crash-to-desktop periodically

### ISSUE THREAD

**Issue by YabosMcGee** [ValveSoftware/Dota-2#1335]
Since the 7.07 update the client will crash-to-desktop periodically. I believe it's happening when there are a lot of effects on screen, but it's hard to say. In my last game it happened during the hero pick screen, and then about 3-4 more times during the game before I gave up. I haven't had any crash-to-desktop issues on this system in a long time. 

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.13.9-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11905000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 17.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x1616
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 12.20" x 6.69" (13.90" diag)
                                            31.0cm x 17.0cm (35.3cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Broadwell HDMI

Memory:
    RAM:  7862 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  43472 Mb
    Largest Free Hard Disk Block:  3871 Mb
    VR Headset: None detected

Recent Failure Reports:
```

I'm not sure what logs, or other output, I can provide. So, please advise what additional information you need.

**Comment by gdrewb-valve** [comment]
If you get anything listed in the Failure Reports section in the Steam info those would be useful.  As you don't appear to have anything there that typically means the crash is in system software like the OpenGL driver.

**Comment by WagnasT** [comment]
Seem to be having the same issue, also happen to be using  Manjaro but haven't had any issues up until this update.  Unfortunately I don't see any .dmp or .mdmp files anywhere and my recent failure reports section is also empty.  It's pretty easy to reproduce, is there a way to create a debug log or anything while the game is running?

**Comment by lewisdiamond** [comment]
I have the same issue on Archlinux.

**Comment by timitch1** [comment]
Same issue Ubuntu 17.04. Amdgpu-pro drivers. Was fine before the update

**Comment by WagnasT** [comment]
I'm using mesa radeonSI, but on an older HD6500 card

**Comment by YabosMcGee** [comment]
Also, due to my current issue with Vulkan in #1334 I'm currently running the game with no launch options, and therefore using OpenGL.

**Comment by WagnasT** [comment]
Launched from CLI and got this right before it crashed:
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
crash_20171031222744_1.dmp[10762]: Uploading dump (out-of-process)
/tmp/dumps/crash_20171031222744_1.dmp


now I know where the dmp files are, going to zip a few and upload

**Comment by WagnasT** [comment]
[dumps.zip](https://github.com/ValveSoftware/Dota-2/files/1432942/dumps.zip)
attached are my dmp files.

**Comment by lewisdiamond** [comment]
I tried with `-vulkan` option and I also get crashes.

No `Recent Failure Reports` available for some reason.

**Comment by admshao** [comment]
I've had the same issue


[crash_20171101010928_23.zip](https://github.com/ValveSoftware/Dota-2/files/1433018/crash_20171101010928_23.zip)
[shaolin_stdout.txt](https://github.com/ValveSoftware/Dota-2/files/1433019/shaolin_stdout.txt)

**Comment by gdrewb-valve** [comment]
For anybody who wants to collect console output you can run Steam from a terminal or you can put -con_logfile in your options, in which case there'll be a console.log in your Dota directory.

I believe there are two (or more) separate issues here.  Is everybody seeing a regex_error like SergeantWagner, particularly @YabosMcGee?

**Comment by YabosMcGee** [comment]
@gdrewb-valve Yes, I'm seeing the same regex_error as @SergeantWagner.

**Comment by WagnasT** [comment]
for what it's worth, I can usually reproduce the crash by watching high mmr games in client and just waiting a few minutes.  I had a game I was watching minimized and it didn't seem to crash for an extended period of time, but then when I viewed the game again it crashed within a couple of minutes.

**Comment by ap4y** [comment]
Same here. Getting:

```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
```

in terminal. Happened several times on the main screen while I was in queue and while watching dota tv matches.

**Comment by gdrewb-valve** [comment]
We believe we understand at least one source of the problem and an upcoming update will avoid the issue.  Whether this will solve everybody's problem is unclear but it should help.

**Comment by WagnasT** [comment]
Thanks Drew.  Glad valve still cares about us down here in the tiny 0.60% market share.

**Comment by gdrewb-valve** [comment]
There is a new update available, are people seeing any improvement with it?  Specifically are the regex errors still occurring?

**Comment by ap4y** [comment]
Been stable for 15min, previously it crashed within 10min, looks like regex issue is fixed.

**Comment by ap4y** [comment]
Been in the game for a couple hours, no crashes. Thanks a lot Drew!

**Comment by WagnasT** [comment]
Haven't been able to reproduce and it would have surely happened by now. Seems to be fixed. Commends all around.

**Comment by gdrewb-valve** [comment]
I'm going to assume that this is fixed for YabosMcGee also, closing.

**Comment by YabosMcGee** [comment]
@gdrewb-valve Sorry, I haven't had a chance to test yet. I'll be testing in the next hour or so. I'll update to confirm one way or the other.

**Comment by YabosMcGee** [comment]
@gdrewb-valve I believe it's resolved. I made it through a game without a single crash. Thanks.
