### ISSUE TITLE
[Linux] Version number for new hero guides don't seem to follow standard convention

### ISSUE THREAD

**Issue by tukkek** [ValveSoftware/Dota-2#1338]
Creating new guides on the new "hero guide" interface gets me a version number of `23.112` instead of the usual `7.07` I see from other recent guides. I am assuming this is the name for the Unix build of the game. Even if it is though, it should follow the proper convention because "23.112" isn't meaningful except for Unix-based developers, I'd imagine. It can't be easily compared with official version numbers - either by people on other platforms looking at my guide or by myself trying to see which version of the game this was written for (as I too am only aware of the "official" naming convention).

Sorry if I got the version names wrong because I don't have Dota open right now but if these are not the exact version numbers, they are still illustrative of this issue. This has happened to 100% of my guides as I created new ones or published old ones to the Steam Workshop.

Almost all other recent guides (assumedly created on the Windows platform) show the proper Dota version number for Dueling Fates but I have seen one other guide yesterday that, like me, had this other naming attached to it - so I know this is not happening to me exclusively. Here is one of my guides as an example: you can see it has been uploaded to Steam with what I assume to be the internal version number and not the "7.07" Dueling Fates one http://steamcommunity.com/sharedfiles/filedetails/?id=1188486713

Thanks again for the great customer service you have been putting out on this GitHub tracker - it's been really top quality and good to know I can always count on you all to take a look at these issues :) I'm having a lot of fun with the Dueling Fates update even though I have been having issues (pointed out in another ticket) and would like to thank everyone who has worked on making the great Linux client a reality!

**Comment by gdrewb-valve** [comment]
This isn't a Linux issue, it's broken on all platforms.  I've passed this on to the larger team and an upcoming update will have a fix.
