### ISSUE TITLE
Hero can walk through siege creeps

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#134]
The player can walk through allied siege creeps as if they didn't exist. This is on OS X 10.9.5.
I haven't tested enemy siege creeps and I haven't looked at bots.

**Comment by gdrewb-valve** [comment]
Likely not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
Actually I wasn't able to repro on Mac or Windows.  Does this always happen?

**Comment by gdrewb-valve** [comment]
In talking with the larger team about this it may be connected to running with lowered rendering settings.  Have you selected advanced rendering options and set the render quality lower than 100% or selected a faster basic rendering tick?

**Comment by jeanlain** [comment]
I play at the highest settings except ambient occlusion. I will try to reproduce the issue. I was playing as Sniper in a lobby. I'm not sure it alway happens since I didn't try to cause it on purpose. I just noticed on a couple of occasions that my hero walked through a siege creep.

**Comment by gdrewb-valve** [comment]
OK, when we pin down a repro we can dig in more.

**Comment by jeanlain** [comment]
Ok, it's not a if siege creeps didn't exist, but the hero can walk trough them to a large extent. I would take a screenshot if the key were working.

**Comment by jeanlain** [comment]
After all, this is probably the same behavior as it standard Dota 2.
