### ISSUE TITLE
[macOS] Top right tile in main menu is not clickable

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1340]
(tile with ability draft and turbo advertising). It's hoverable, but not clickable.

**Comment by gdrewb-valve** [comment]
It works OK here.  What resolution and mode are you running at?

**Comment by RankoR** [comment]
@gdrewb-valve 3840w exclusive fullscreen
Any other card works ok

**Comment by gdrewb-valve** [comment]
3840 x 2160?  Also when you say "other card" do you mean other resolutions?

**Comment by RankoR** [comment]
@gdrewb-valve yep, 3840 x 2160.
Other card = any other tile in menu. Any other main screen element is clickable.

**Comment by gdrewb-valve** [comment]
If you switch to windowed mode with a smaller resolution, but still 16x9 aspect, does it change?

**Comment by RankoR** [comment]
@gdrewb-valve i've tried 1280*720 (windowed, 16x9), and it seems that click translates to "play" button (see video: https://youtu.be/B-XCKLvOsCU) :)

**Comment by gdrewb-valve** [comment]
Clicking on the tile is supposed to open the play options so that's working as expected.  It only does that in windowed mode and not exclusive fullscreen?  Are there any macOS system options that are triggered in the corners of the screen where the system may be eating clicks?

**Comment by RankoR** [comment]
> Clicking on the tile is supposed to open the play options so that's working as expected

Okay, I thought it will open webview.

> It only does that in windowed mode and not exclusive fullscreen

Yes

> Are there any macOS system options that are triggered in the corners of the screen where the system may be eating clicks?

No

**Comment by jeffreythen** [comment]
I'm having the same problem. my screen only shows the top left of the holding page. 
[URL=http://s298.photobucket.com/user/jeffreythen/media/IMG_0016.jpg.html][IMG]http://i298.photobucket.com/albums/mm251/jeffreythen/IMG_0016.jpg[/IMG][/URL]

**Comment by gdrewb-valve** [comment]
@jeffreythen you appear to have a different problem as the post here can see the screen, it just doesn't activate the play state.

**Comment by RankoR** [comment]
Seems to be fixed in current version.
