### ISSUE TITLE
High health regeneration performance issues. Health integer overflow possible. 

### ISSUE THREAD

**Issue by AphidGit** [ValveSoftware/Dota-2#1341]
When a unit is given a massive amount of strength (esp. in the new patch with the modified regeneration rate), it will cause some major framerate issues, but only while it is visible.

To test: 
- Create a unit (ex. with the map editor) with 10,000,000 hp regeneration.
While the unit is visible, the framerate will drop significantly (as if a particle effect applies for every 'X' hp of regen), to the point where the game can become unusable.

Integer overflow bug with HP: 
- Units should probably be limited to 100,000,000 STR. Giving them more than 107,374,182 STR will cause a very strange glitch:  when the unit is the player's hero, the model will 'freeze' in play. Any action the player tries to undertake (moving, using abilities) will result in the message 'Dead'. 

The hero isn't actually really dead though; some things still apply, such as gaining XP, while other things do not. The hero will be stuck at 0 of -2,147,483,635 HP.  

To Test: Create a hero with the following stats: 

107,374,182 STR, 10 AGI, 10 INT. 
Give the hero 1 more strength (e.g. buy an ironwood branch). 

To fix this: clamp stats so that an overflow cannot be triggered. A similar problem occurs with intelligence due to mana pool overflow, or AGI where e.g. damage can overflow. Minimum limits should be thus about 100M str, about 150M int, and about 2B agi.

**Comment by gdrewb-valve** [comment]
Is there a reason that you think this is a Mac or Linux issue?

**Comment by gdrewb-valve** [comment]
Closing as this doesn't seem to be a Mac/Linux thing.
