### ISSUE TITLE
dota 2 broke on my linux mint

### ISSUE THREAD

**Issue by portalgamer626** [ValveSoftware/Dota-2#1344]
hello friend and fellow gamers! i have issue with dota 2 on steam ! see this 'vac error' on the game which not let me play! 
![ulllyqm5m94fmfifg6xjqdhhz0nt8bkv83h3yquyvhe](https://user-images.githubusercontent.com/33560107/32682711-b4212d1a-c633-11e7-8887-073db267a943.jpg)

further .. kisak no reply on irc.. bug? please
![2017-11-10-162528_488x89_scrot](https://user-images.githubusercontent.com/33560107/32682756-0444a57e-c634-11e7-9778-d3db4543d6c3.png)

kisak plesae help!

**Comment by fletcherdvalve** [comment]
Could you please share a link to your steam community profile, or your Dota friend ID, so that we can locate your Steam account?

**Comment by portalgamer626** [comment]
my link !!! -----------------> http://steamcommunity.com/id/treyb822/  < ---------------------- MY link ! :))

**Comment by alyx-vance** [comment]
There's some other people having this issue too, 

look at https://www.reddit.com/r/DotA2/new/

**Comment by portalgamer626** [comment]
i never cheat in dota.. this is a bug r?

**Comment by alyx-vance** [comment]
I cheat in other games, but not Dota. Hopefully their not mad....

**Comment by fletcherdvalve** [comment]
Are either of you guys opted into the beta Steam client?

**Comment by portalgamer626** [comment]
no sir!

**Comment by portalgamer626** [comment]
i h ave vac ban on call of duty, this interfere with dota 2 vac?

**Comment by portalgamer626** [comment]
never mind , i use VAC blocker from unknown cheats, thanks guys!

**Comment by alyx-vance** [comment]
Mine start to work now too. Thanks

**Comment by Cabanur** [comment]
I am not affected by this. Latest beta (2017-11-10, 1510357240) on Debian Testing. [Full System Info](https://gist.github.com/Cabanur/3cc871309a8b4f1ccd527f8fad3fb5cf)

**Comment by gdrewb-valve** [comment]
Closing.
