### ISSUE TITLE
[Mac] Played hero voice volume is too low

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#135]
The voice volume of the played hero is too low, and is much lower than the voice of non-played heroes (bots in my case). (I'm not talking about voice chat here, just to be clear.) Tested on Sniper. 

OS X 10.9.5, 2006 Mac Pro with headphones plugged on the line-out jack port.

**Comment by davidw-valve** [comment]
I tried to reproduce this on a Mac, using Sniper in a bot match -- his voice sounded at normal level.

Exactly how quiet is it for you? Are you using any non-standard settings? Do you have unit voice set to 100%?

**Comment by jeanlain** [comment]
I don't think I use any non-standard setting and the sound level is 100% for everything. I'll try again, but immediately noticed during my first match that the voice sound was lower than in source 1 dota, and lower than other heroes. I can still hear it clearly though.

**Comment by davidw-valve** [comment]
Do you still have this issue? Do you have it for all heroes?

**Comment by jeanlain** [comment]
It seems the sound level is now adequate.
