### ISSUE TITLE
Dark willow and pangolier getting drawn way to often.

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1353]
hi,
For some reason when using the back key, in my case it is a mouse button, the game adds another dark willow&pangolier to duelling fates promotion widget. This is noticeable because are all slightly out of sync.
![dw pang](https://user-images.githubusercontent.com/5174562/33235504-af59e7c4-d239-11e7-9e30-6c431c5328fe.png)

**Comment by Geradot** [comment]
This problem is present in any OS (MacOS, GNU/Linux (any), Windows).

**Comment by gdrewb-valve** [comment]
Confirming that this happens on Windows also, I'll pass this on to the larger team.
