### ISSUE TITLE
[Linux] MMR Badge animation in menus causes extreme slowdown

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#1355]
When clicking the Watch tab, or a friend's replay, the UI will slow down to crawl as the MMR badge animation plays. This same slow down occurred during a game and I believe it may be related.

When running with Vulkan, there's a tiny bit of stutter but the problem isn't as severe. Seems to only occur with opengl.

Here are some video captures of the problem. I move the mouse around so you can see that the UI is lagging and not the system.

https://www.youtube.com/watch?v=BBvc0kkJU7Y
https://www.youtube.com/watch?v=x9OtCcYRQYc

System specs:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/22c7dc61b4a7d9694ea78efdbbfe35ca2482616f/gistfile1.txt

DE is XFCE with compositing disabled.

Log of console:
[console.txt](https://github.com/ValveSoftware/Dota-2/files/1520506/console.txt)

**Comment by zezaocapoeira** [comment]
Hello.
(sorry bad english)

After the latest game updates, the same problem reported or author to topic occurs.

There is also a fall of fps, from 80 to 1, it stops the game for a few moments.

Before the updates of this week the game was normal.

Description of the hardware I use:

https://pastebin.com/raw/HHjwLsZ7


PS:
I apologize to the author of the topic for intrusion.

Thanks for listening.

**Comment by danginsburg** [comment]
I notice that you are both using the NVIDIA 387.34 driver.  Can you check if downgrading the driver helps?  NVIDIA has said there are known performance regressions with this driver: https://devtalk.nvidia.com/default/topic/1026874/linux/huge-performance-losses-with-newer-nvidia-drivers/post/5223375/#5223375

**Comment by danginsburg** [comment]
I was able to reproduce this on 387.22.  Looking into it.

**Comment by eplgr** [comment]
Same thing happens to me with ATI open source drivers. 

This only happens when the badges are loading, after some seconds when they are fully loaded, the slowdown goes away.

**Comment by Taxellool** [comment]
Same issue with Arch Linux and Intel graphics.

The initial slowdown happens on loading badges and will follow for about 10 sec on anywhere else afterwards

started after last 117 MB update

**Comment by danginsburg** [comment]
Thanks for the reports, it is not GPU-specific (nor OpenGL-specific, happens on Vulkan too).  We are looking into it.

**Comment by Taxellool** [comment]
Just need to mention that the problem is not just related to badges loading. happened to me multiple times during a game (where there's no badge) and totally ruined the game. 
does not happen in every game though.

**Comment by mosulache** [comment]
The same apply to me. I changed nothing to my system (16GB, nvidia 970, ssd, i7-4790K CPU @ 4.00GHz) and the game behaves like in the videos above. Also in game from time to time (when there is a fight, more often) has massive FPS drop.
I use ubuntu with xfce (Ubuntu Studio). Never had any performance issues up till now.
I reduced graphic quality but no help.


I have an observation:
My processes list shows  (i switch alt+tab to system monitor) sh -c uname -m (started by dota2 process)!
Allot of these entries!

This is a bug in itself, dota should remember the architecture was installed on .. I believe it is for debugging, maybe? However there must be hundreds or thousands such processes during a game

Long ago, steam shoes an error like 'uname -a' crashed or could not be executed. So it is a long term issue. Can anyone confirm the correlation between these stupid processes spawned by dota2 and the periods with very poor performance?

Regards,
M

**Comment by ghost** [comment]
This seems to only happen when you start Dota first time after boot

**Comment by mikze** [comment]
Ive got same issue on Linux Mint. It happens even in game FPS drops from 200 to 5 for few sec.

**Comment by null-patcher** [comment]
Hi guys,

Ubuntu 16.04
Desktop - Unity

Maybe it will help, but I've checked the error log in steam and when I hit the watch tab, I get this: 
https://gist.github.com/GosuTeacher/9d4f3db92bc0fa0bd86307cfeed29880

Hope it helps.

**Comment by Plagman** [comment]
There was a bug with this panel spawning many processes on Linux and causing these slowdowns. It'll be fixed in the next release, thanks for reporting.

**Comment by Patrick-Edouard** [comment]
Thanks for the fix.

It was the same issue for in game and in the menu?

A bit sad it happened right when we get a shot at recalibrating our mmr :(

**Comment by mikze** [comment]
yea I lost two games cus of fps drop.

**Comment by galenzh** [comment]
Same problem. Linux mint 18.2

**Comment by sysrpl** [comment]
Same problem here. After clicking on the "Watch" tab the entire UI becomes unrecoverably unresponsive. Also happens sometimes during a game dropping the frame rate to 1 fps for maybe 10 seconds then it recovers.

**Comment by danginsburg** [comment]
This update has shipped.  Please give it a try and confirm that it has been fixed.  Thanks.

**Comment by eplgr** [comment]
Yeah, it's working properly now.
Nice, thank you.

**Comment by sysrpl** [comment]
The "Watch" tab is now fixed. I'm sure sure if the other slow downs are fixed as well. I need to test further.
