### ISSUE TITLE
Client slowdown after clicking "Watch" tab in the client

### ISSUE THREAD

**Issue by RichMartel** [ValveSoftware/Dota-2#1356]
Bug Description:
When I click the watch tab, the games to view are all rendered like a slideshow or 1 or 2 fps.  It's very noticeable in the animated heroes on the left.  If I click out of the watch tab, the client still performs very badly but not quite as bad as the watch tab.

Your Steam Profile Link:
steamcommunity.com/id/richmartel/

Other helpful information:
Linux vulkan version.  I have not tested with any other setup.

**Comment by r3pek** [comment]
Dup of #1355 and #1352 ?

**Comment by kisak-valve** [comment]
Hello @RichMartel, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gdrewb-valve** [comment]
Very likely the same thing as #1355.

**Comment by gdrewb-valve** [comment]
Did the Dec. 5 update help?

**Comment by RichMartel** [comment]
Yes, Dec. 5 update seemed to correct the problem.  I have another issue during gameplay that I required me to exit the game and re-enter to stop a stuttering problem with the rendering.  I will open up another ticket when I understand the circumstances better.
