### ISSUE TITLE
Match overview- player select - scoreboard - overview again  display bug (see  attached pictures)

### ISSUE THREAD

**Issue by mosulache** [ValveSoftware/Dota-2#1357]
Dear Dota-2 devs (?!)
last update for linux introduced some other bugs than the most frustrating performance drop experiences since the medals are displayed bellow the user (btw these worked for a little while?!)

After watching a game, i looked into player statistics (click on hero in the overview menu).
Went to scoreboard and back again.
You can see in the picture that statistics are displayed on top of the player list (like the forrmer player is still selected but only partly displayed on top)

![20171203_012617](https://user-images.githubusercontent.com/16856437/33520877-9ebcee60-d7cb-11e7-8c94-876198f81457.jpg)
![20171203_012638](https://user-images.githubusercontent.com/16856437/33520879-aa56b1fc-d7cb-11e7-92e1-eee716bfa059.jpg)

Using:
    Ubuntu 17.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.10.0-41-lowlatency
    X Server Vendor:  The X.Org Foundation
 Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.90

**Comment by gdrewb-valve** [comment]
Likely not Linux-specific.

**Comment by mosulache** [comment]
I don't get it. 
In 1359 you reference this as duplicate, here you reference 1359 and close this.
Was it fixed?
tnx,

**Comment by danginsburg** [comment]
This happens on Windows as well, I'll pass it along to the larger team.
