### ISSUE TITLE
[Linux] Dota has started to have random lags

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1358]
inxi -F here https://imgur.com/iH3XH3H

2 days ago Dota has started to have client side lag spikes. I have no idea what causes this so I'll update with video when it happens again.

**Comment by joshuapassos** [comment]
I have this problem too with and without  vulkan :/ 

I use Nvidia driver 381.22
Ubuntu 17.04 w/ i3wm  
GeForce GT 740M

**Comment by gdrewb-valve** [comment]
Possibly the same as #1355.

**Comment by ghost** [comment]
Seems to be. I added my 2 cents to the conversation.
EDIT: Mine also happens ingame so it's not completely the same.

**Comment by skibz** [comment]
i can confirm that this is a duplicate of #1355

**Comment by conormcg13** [comment]
Mines was only happening in the UI but now in game I am getting huge spikes as well. On Ubuntu 16.04 LTS. RX 480, Mesa 17.2.4

**Comment by conormcg13** [comment]
@gdrewb-valve Drew I just played a game with tab exclusively on 'Learn' with no lags or spikes so this may be able to narrow the issue down to the watch tab and the new emblems.

Edit: This may not be the case, had spikes again (even in Learn tab) so it may be when packets are sent from the server regardless of what tab.

**Comment by ivanpepelko** [comment]
Just to add an input from my perspective: it seems like the GUI is lagging when significant update from server is received. Reasons for this conclusion is that the issue occurs:
- after game launch and switch to 'watch' tab (live games list and details)
- when multiple enemies appear from fog

FPS drops from ~100 to ~20 (or even less), PING is always at 22ms.

Arch Linux
i7-6700HQ, NV-GTX1060, 16GB ram, NVMe SSD
lib32-nvidia-utils 387.34-1
lib32-opencl-nvidia 387.34-1
nvidia 387.34-7
nvidia-settings 387.34-1
nvidia-utils 387.34-1
opencl-nvidia 387.34-1

EDIT:
What I tried:
- verify game cache
- upgrade all packages
- verify after upgrade
- cleaning disk space (from ~5gb free to ~17)

**Comment by sylware** [comment]
Same here, in-game or in dash-board, vulkan or GL renderer.
linux 4.14.3
drm/llvm/mesa(GL+vulkan)/xserver git from this weekend
AMD GPU TAHITI XT
AMD CPU FX 9590

**Comment by a-litsov** [comment]
I also have freezes in game (in the end almost every game and at random time in the game fps drops from 80-90 to 10-20 for 3-10 seconds) and in watch tab (when players rank medals loading one by one with pretty big delay).. haven't seen this before dueling fates update. Using OpenGL, inxi -F [here](https://i.imgur.com/YKIWZ2w.png)

**Comment by csirbu** [comment]
Have the same problem, goes from ~80 fps to ~12. I tried reinstalling, didn't helped.

**Comment by dearlygparted** [comment]
I'm also getting massive FPS drops in the game. They seem to be random. Graphics card is Nvidia GTX 1060 with 384.98 drivers, and using Vulkan.

**Comment by danginsburg** [comment]
An update just shipped with a fix for #1355 which may be the same issue people are reporting here.

**Comment by sylware** [comment]
There were 2 issues:
 - massive slow downs.
 - mini freezes.

both seem to be fixed... testing...

**Comment by sysrpl** [comment]
Seems fixed.
