### ISSUE TITLE
[macOS] Player details overlays match info

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1359]
Scenario:

1. Go to match details
2. Select certain player to see the details
3. Go somewhere out of this page, for example, main menu
4. Open match again (for example, from profile -> match)

Result: player details overlap other info (see screenshot: https://i.imgur.com/8SeHgRv.jpg)

**Comment by gdrewb-valve** [comment]
This seems to be a duplicate of #1357, does that cover what you're seeing?

**Comment by RankoR** [comment]
@gdrewb-valve yep, that's a duplicate, sorry.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
