### ISSUE TITLE
When I watch a video record can't see the selected heros on linux mint.

### ISSUE THREAD

**Issue by galenzh** [ValveSoftware/Dota-2#1360]
When I watch a video record can't see the selected heros on linux mint 18.2. Sorry for my bad english.
![2017-12-07 21-52-10](https://user-images.githubusercontent.com/3645554/33718929-0ea802d8-db9a-11e7-8969-aa3d581ee333.png)

**Comment by kisak-valve** [comment]
Hello @zhangshuzhen, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, did you jump forward while watching or did you let the replay play back from the start to this moment?

**Comment by galenzh** [comment]
Hello @kisak-valve ,Yes, I can see the problem only when I jump forward or play back. And, I have the same problem on a computer with  window 7 system.  I think it is not the problem about System Compatibility.

my linux mint Info:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 18.1 Serena (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-97-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BONAIRE (DRM 2.43.0, LLVM 3.8.0)
    Driver Version:  3.0 Mesa 11.2.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x665f
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary VRAM: 2048 MB

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15947 Mb

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Total Hard Disk Space Available:  218071 Mb
    Largest Free Hard Disk Block:  52101 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
As you mention your problem is not specific to Linux/Mac so you'll want to post at dev.dota2.com
