### ISSUE TITLE
"CUSTOM ERROR" (exact message) when using Q skill on Viper

### ISSUE THREAD

**Issue by 1xch** [ValveSoftware/Dota-2#1363]
I just had a game where I could not use Vipers Q skill

Every time I tried to use it I would get tiny no go beep and a message that says "CUSTOM ERROR"

See picture

https://imgur.com/a/i2w0k

Linux, Ubuntu can edit for more detailed information

**Comment by Turmfalke2** [comment]
Afaik that is affecting all platforms and therefore not for this bug tracker. However I have no idea how this update broke viper, maybe the new cosmetic for viper has a custom animation for the q?

**Comment by gdrewb-valve** [comment]
Closing as this has already been addressed by the larger team.
