### ISSUE TITLE
Dota 2 : Swap primary and secondary mouse buttons in-game

### ISSUE THREAD

**Issue by 3dgie** [ValveSoftware/Dota-2#1364]
I have tried swapping the primary and secondary mouse buttons in Dota 2 in vain.

What I have tried:

1) Swapping the buttons via desktop settings. This works with pretty much all applications including Dota 2 game menu but does not swap the buttons ingame.

2) Tried editing the file ~/.steam/steam/steamapps/common/dota 2 beta/game/dota/cfg/user_keys_default.vcfg to add

 MOUSE1 "+attack2"
 MOUSE2 "+attack"
Doesn't work either.

Is there any known workaround this ?!

**Comment by gdrewb-valve** [comment]
This worked properly for me when I tried it.  A system button swap should be handled completely outside of the game so I'm not sure how it'd only work partially.  Can you post a gist of your system information?

**Comment by 3dgie** [comment]
Okay, you're right. Swapping the button from the desktop settings swaps them in-game.

I think I should rephrase my question, I'm left handed and would like to switch the functionality of the mouse buttons in-game such that the button which by default selects a hero should instead be used to move and vice versa. 

Is this possible?

**Comment by gdrewb-valve** [comment]
I don't believe there's anything that allows rebinding just in-game.  You can post a request at dev.dota2.com
