### ISSUE TITLE
Please help us at moddota bug tracker git

### ISSUE THREAD

**Issue by darklordabc** [ValveSoftware/Dota-2#1365]
I know valve has forsaken Dota 2 custom games but I still hold out hope that some soul at valve cares. Please, can somebody at valve spend a couple of hours, or devote an employee to help us. We have a bugtracker, we just need somebody to help us. We can pay valve employees can we get some attention, we are seriously that desperate that we could gather up money just to pay for some bug fixes. Oh god help us.

**Comment by gdrewb-valve** [comment]
All I can do is pass this on.  Also I have to ask you and everybody else to please not abuse this tracker with off-topic issues.  We don't want people to see this as a way to contact Valve about anything other than the Linux/Mac issues it exists for.

**Comment by darklordabc** [comment]
Considering the horrendous treatment Valve has put the modding community through during this Frostivus competition, I think its only fair you guys have to deal with a little inconvenience of receiving a notification in the wrong window. Also, maybe tell your company to actually reply to the dozens of emails we send looking for help and clarification.
