### ISSUE TITLE
Incorrect Voice Language when using -language launch option

### ISSUE THREAD

**Issue by DanielReeLee** [ValveSoftware/Dota-2#1367]
I have downloaded the Korean DotA voice pack but it does not work if I am using the -language launch option. When not using the -language launch option I find that then the appropriate voice pack language is used.

**Comment by gdrewb-valve** [comment]
Can you post your system information?  This probably isn't a Mac/Linux issue and will be passed on to the larger team.

**Comment by DanielReeLee** [comment]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.8-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Openbox
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 950M/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 387.34
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x139a
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.73" (23.94" diag)
                                            53.1cm x 29.8cm (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC255

Memory:
    RAM:  7882 Mb

Miscellaneous:
    UI Language:  English
    LANG:  C
    Total Hard Disk Space Available:  953867 Mb
    Largest Free Hard Disk Block:  683273 Mb
    VR Headset: None detected

Recent Failure Reports:
I am running a dual boot system so I will also post specs from Windows later.

**Comment by DanielReeLee** [comment]
Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  N552VX
    Form Factor: Laptop
    Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2304 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  Intel(R) HD Graphics 530
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  21.20.16.4550
    DirectX Driver Version:  23.21.13.8871
    Driver Date: 11 11 2016
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: NVIDIA GeForce GTX 950M
    VendorID:  0x10de
    DeviceID:  0x139a
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.73" (23.94" diag)
                                            53.1cm x 29.8cm (60.8cm diag)
    Primary Bus: PCI Express 8x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Headphones (Realtek High Defini

Memory:
    RAM:  8090 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  1066040 Mb
    Largest Free Hard Disk Block:  682781 Mb
    OS Install Date: Dec 31 1969
    Game Controller: None detected
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
This tracker only handles Mac/Linux issues, the general bug forum is dev.dota2.com
