### ISSUE TITLE
[MacOS]

### ISSUE THREAD

**Issue by jelostenan** [ValveSoftware/Dota-2#1374]
Game crashes after Dota 2 Update - MAIN CLIENT - January 16, 2018. It crashes right after main menu screen

**Comment by markhughes** [comment]
See #1375

**Comment by danginsburg** [comment]
Closing as duplicate of #1375.  Fix incoming.

**Comment by jelostenan** [comment]
Thanks!)

Ср, 17 янв. 2018 г. в 0:56, Dan Ginsburg <notifications@github.com>:
