### ISSUE TITLE
MAC: Dota crash the moment it shows the main menu at launch

### ISSUE THREAD

**Issue by azokwvn** [ValveSoftware/Dota-2#1375]
As stated in the title. DOTA opens and shows the main menu and at that exact moment it crashes. 

Playing on: macOS Sierra (Version 10.12.6)

Seems it's happening after the latest Dota update.

**Comment by Juliaandavid** [comment]
Same here.

macOS High Sierra (Version 10.13.2).

**Comment by danginsburg** [comment]
Thanks, we're aware of this and working on a fix.

**Comment by kpamu** [comment]
@danginsburg dauni ebanie

**Comment by cachineropro** [comment]
it crashes at the same time i see the menu and it is the same in other accounts

**Comment by foners** [comment]
I have this problem too.
im Re-instal game and w8........

**Comment by foners** [comment]
Dota2 Test working!

**Comment by gu3st** [comment]
@foners Test will work as it's fairly out of date compared to main.  The issue everyone's experiencing is a new issue from the patch released a little while ago.  The valve folks are working on a fix. Reinstalling won't help as it's a defect in the latest update.

**Comment by vichug** [comment]
same here (yosemite 10.10.5)
if it helps, l have this in console log : 
```16/01/2018 23:30:48,117 dota2[734]: 
23:30:48.117 WARNING:   >compload> AudioComponentPluginLoader.cpp:445: ParseInfoPlistArray: Curve2.component -- file:///Library/Audio/Plug-Ins/Components/: trouble parsing Info.plist's AudioComponents; entry: <CFBasicHash 0x7f996f34d580 [0x7fff79a28ed0]>{type = mutable dict, count = 7,
entries =>
	2 : <CFString 0x7f996f34d6a0 [0x7fff79a28ed0]>{contents = "manufacturer"} = <CFString 0x7f996f34d8e0 [0x7fff79a28ed0]>{contents = "Cabl"}
	7 : <CFString 0x7f996f34d810 [0x7fff79a28ed0]>{contents = "factoryFunction"} = <CFString 0x7f996f34d730 [0x7fff79a28ed0]>{contents = "CurveAUFactory"}
	8 : <CFString 0x7f996f34d9e0 [0x7fff79a28ed0]>{contents = "subtype"} = <CFString 0x7f996f34da20 [0x7fff79a28ed0]>{contents = "CGC2"}
	9 : <CFString 0x7fff799fc400 [0x7fff79a28ed0]>{contents = "description"} = <CFString 0x7f996f34b910 [0x7fff79a28ed0]>{contents = "Curve2"}
	10 : <CFString 0x7f996f34dae0 [0x7fff79a28ed0]>{contents = "type"} = <CFString 0x7f996f34db20 [0x7fff79a28ed0]>{contents = "kAudioUnitType_MusicDevice"}
	11 : <CFString 0x7f996f34d970 [0x7fff79a28ed0]>{contents = "name"} = <CFString 0x7f996f34d890 [0x7fff79a28ed0]>{contents = "Cableguys: Curve2"}
	12 : <CFString 0x7f996f34db80 [0x7fff79a28ed0]>{contents = "version"} = <CFNumber 0x2050337 [0x7fff79a28ed0]>{value = +132355, type = kCFNumberSInt64Type}
}
```

**Comment by gu3st** [comment]
@vichug That seems like something specific to your machine.  Quick google turns up this software: http://www.cableguys.com/curve.html

**Comment by vichug** [comment]
@gu3st well, it's possible, but i have had this plugin installed & untouched alongside dota with no trouble for an eternity up to this update ; and the dota crashing behaviour is exactly the one described above.
(Now it's possible this message has always been there and harmless, just that i never had a need to check the console... so in fact this may indeed be unrelated to the issue at end, as you say)

**Comment by gu3st** [comment]
@vichug I think it's unrelated given the other issues that Valve are currently fixing.   Doesn't seem like an error, just a warning.

**Comment by Zucca01** [comment]
Same here :C🌵

**Comment by vichug** [comment]
@danginsburg will the fix possibly include uncompatibility with older systems (like 10.10.5) ? i wanna be prepared pyschologically

**Comment by magnetoid** [comment]
i have same problem..

**Comment by elieandraos** [comment]
same problem
```    
    Manufacturer:  Apple
    Model:  MacBookPro11,2
    Form Factor: Laptop
    No Touch Input Detected
```

**Comment by Hursofid** [comment]
Hello, same here

```$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G18013

 Model Name: MacBook Air
      Model Identifier: MacBookAir6,2
      Processor Name: Intel Core i5
      Processor Speed: 1,3 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 3 MB
      Memory: 4 GB

$ ./dota.sh 
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Users/constructed/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Uploading pending dumps
Uploaded 1 pending dumps
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198028997990 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198028997990
SteamID:  76561198028997990, universe Public
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL vendor Intel Inc.
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL renderer Intel HD Graphics 5000 OpenGL Engine
void COpenGLDriverEntryPoints::DumpContextInfo(): Using OpenGL context version 4.1
void COpenGLDriverEntryPoints::DumpContextInfo(): Context supports GLSL version 4.10
 failed to dlopen "/Users/constructed/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librenderdoc.dylib" error=dlopen(/Users/constructed/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librenderdoc.dylib, 9): image not found
 failed to dlopen "librenderdoc.dylib" error=dlopen(librenderdoc.dylib, 9): image not found
Fontconfig warning: "/Users/constructed/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/Users/constructed/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected

**Comment by featured14** [comment]
Same issue . 
macOS Sierra 10.12.6 on MacBookPro11,4

**Comment by injectios** [comment]
Just updated a second ago - **works again**. Thanks

**Comment by magnetoid** [comment]
yes, thanks guys  





On Wed, Jan 17, 2018 12:09 AM, Dmitriy L notifications@github.com  wrote:
Just updated a second ago - works again. Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Marko Tiosavljević
Chief Executive Officer
marko.tiosavljevic@cloud-industry.com

cloud-industry.com | Web Development Agency

This message is confidential. It may also be privileged or otherwise protected
by work product immunity or other legal rules. If you have received it by
mistake, please let us know by e-mail reply and delete it from your system; you
may not copy this message or disclose its contents to anyone. Please send us by
fax any message containing deadlines as incoming e-mails are not screened for
response deadlines. The integrity and security of this message cannot be
guaranteed on the Internet.

**Comment by gdrewb-valve** [comment]
The latest update should fix this.  We'll leave this open for a bit to get reports but assuming that things go well we'll close it out.

**Comment by abensur** [comment]
fixed on macOS High Sierra

**Comment by ilkedemir** [comment]
Works again! Thanks for the quick update.

**Comment by gu3st** [comment]
Confirmed no CTD on my 2015 MBP

**Comment by foners** [comment]
FIXEd MAcbook pro 2011

**Comment by danginsburg** [comment]
Thanks for the confirmations, the fix was shipped and it should be working again after you get the latest update.  Closing.

**Comment by regs01** [comment]
when are we going to have an ability to ban players from custom lobbies? trolls are not going away.

**Comment by gu3st** [comment]
Not relevant to this issue tracker tbh.

**Comment by regs01** [comment]
where is it relevant then? devs are totally ignoring custom games issues everywhere.

**Comment by gu3st** [comment]
Dev forum?  Spamming it in every place you feel a Valve eye might see it won't help the cause.  The end result will be that Valve communicates less and closes down avenues like this which provide value to various segments of the community.  Not to say that the custom game issues aren't valid, but there are better avenues available for that.   

Maybe Valve should open an issue tracker similar to this one for DOTA 2 custom games?  That's not for me to say, but I know that spamming in any available channel won't evoke the desired response.

**Comment by mwaqarshahid** [comment]
Issue resolved on my MAC after latest update. Thanks.
