### ISSUE TITLE
Cursor is stuck on the top left corner of the screen  

### ISSUE THREAD

**Issue by Random-txt** [ValveSoftware/Dota-2#1378]
Whenever I alt+tab during a game or on the main menu my cursor is stuck in a corner. I have to force quit the game and relaunch it again. It's fine if I alt+tab in other games though
I don't know if it is my system problem or a bug.

**Comment by gdrewb-valve** [comment]
Are you running on Windows?

**Comment by gdrewb-valve** [comment]
I'm assuming this is from Windows, in which case you'll want to post at dev.dota2.com

**Comment by Random-txt** [comment]
oh thanks. Am new to this stuff, sorry
