### ISSUE TITLE
[Mac] All objects not responding to single inputs - intermittent relative to application launch

### ISSUE THREAD

**Issue by gramathy** [ValveSoftware/Dota-2#138]
Happens in menus and ingame. Restarting the application can resolve issue. 

In menus single clicks are nonfunctional. Double clicking most elements allows for navigation, with some exceptions - it seems like the second mouseup event is unusual (multiple events being fired?) and causes other things to happen that I can't quite pin down. If repro'd, clicking on the navigation arrows at the top of the menu is a decent example of the odd 2nd mouseup behavior. Some items (due to the weird mouseup) do not behave and moving the mouse off them before the second mouseup allows them to function normally. Input buffer issue is speculation on my part.

Ingame impact is much more significant - cannot use hotkeys at all, or drag scroll. Mouse works for character movement (with only every other click registering in the game world for commands) or interacting with UI elements in the same "double click" manner (forgot to try minimap) as menus.

**Comment by gdrewb-valve** [comment]
Can you post your system info?

**Comment by gramathy** [comment]
System info:

https://gist.github.com/gramathy/5996562

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by gramathy** [comment]
I haven't had it happen lately that I remember. If it crops up again I'll necro the issue but I think it's not happening anymore.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
