### ISSUE TITLE
Game crashes after using Monkey King's Primal Spring

### ISSUE THREAD

**Issue by cyrq** [ValveSoftware/Dota-2#1380]
title

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?

**Comment by Shrugtal** [comment]
This is a non-system specific issue, this occurs on Windows systems too.

**Comment by gdrewb-valve** [comment]
Closing at this tracker only handles Mac/Linux specific issues.  The larger team is aware of this problem and looking into it but there won't be further status here.
