### ISSUE TITLE
Dota 2 Freezes on loading screen in

### ISSUE THREAD

**Issue by Dota2Fanboy** [ValveSoftware/Dota-2#1383]
Dota 2 when I start it up goes to the black screen then goes to to black screen with logo in the middle and doesn't go any further. I am in full screen if that has anything to do with it. Hopefully u can help it started last last update

**Comment by Dota2Fanboy** [comment]
I'm also on a Mac and never had a problem like this before

**Comment by kisak-valve** [comment]
Hello @Dota2Fanboy, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Are you using any launch options with Dota 2? Also, how long did you let the game try before you gave up?

**Comment by Dota2Fanboy** [comment]
Computer Information:
    Manufacturer:  Apple
    Model:  iMac14,1
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.9.5 (64 bit)

Video Card:
    Driver:  Intel Iris Pro
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xd22
    Revision:  0x8
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.62" x 10.47" (21.34" diag)
                                            47.3cm x 26.6cm (54.2cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  953049 Mb
    Largest Free Hard Disk Block:  169804 Mb
    VR Headset: None detected

Also gave it around 2 hours and im not using any launch options that I know of

**Comment by Dota2Fanboy** [comment]
Besides full screen

**Comment by gdrewb-valve** [comment]
Have you validated your Dota install in the Steam client?

**Comment by Dota2Fanboy** [comment]
Yes still same problem
