### ISSUE TITLE
Game Randomly Pauses

### ISSUE THREAD

**Issue by blazingbags** [ValveSoftware/Dota-2#1386]
Hey guys, for the past day or so my Dota and CS:GO have been randomly freezing. 

I figured out that the game isn't actually crashing, it just keeps Pausing. (Pausing as in the Linux Pause signal)

A fix to this is to just unpause it.

```
killall -18 dota2/csgo_linux64
```
It works temporarily until the next pause.

It's annoying though, and again this is a recent thing. I don't think my system information is relevant, but I can post it if you want. I haven't done anything with my system lately.

**Comment by kisak-valve** [comment]
Hello @blazingbags, yes, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by blazingbags** [comment]
Here you go,

https://gist.github.com/blazingbags/c3dc09e65c3cba239e709c37d9a452bc

**Comment by gdrewb-valve** [comment]
As this isn't specific to Dota this isn't the right place for the issue.  This may be related to the Steam client, did you get any updates for it recently?  If you turn off the Steam overlay does that change anything?

**Comment by blazingbags** [comment]
Reproducing it is kind of random, but I did some digging in my logs and found that this occurs when it freezes 

```
[34758.176302] ptrace attach of "/home/blaze/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64 -steam"[16194] was attempted by "/home/blaze/.local/share/Steam/ubuntu12_32/steam"[16197]
```
(There are ones in there for Dota too)
I first experienced the issue while playing Dota and I was queueing for CS:GO while writing this, my bad.

I don't remember if there were any steam client updates.

**Comment by gdrewb-valve** [comment]
This does seem like something on the Steam side, reassigning.

**Comment by tycho** [comment]
@blazingbags Does the issue still repro? I made some changes last night that may have fixed it.

**Comment by cluoma** [comment]
Same thing happening for me since a couple days ago.

https://gist.github.com/cluoma/ffbb413b97d961f2807a2531cd0bb821

**Comment by blazingbags** [comment]
@tycho 
30 minutes into Dota, so far so good

**Comment by tycho** [comment]
Awesome, thanks for testing!

**Comment by blazingbags** [comment]
@tycho 
I tried CS:GO and it seems to be working too, thanks.

In Dota, I tried to queue for another game and the Accept button freezes the game, I think the other issue is separate.  #1387
