### ISSUE TITLE
Game freezes when matchmaking game is ready

### ISSUE THREAD

**Issue by RogerDodger** [ValveSoftware/Dota-2#1387]
Happened 3 times in a row. Freeze occurs simultaneously with the inotify message appearing. Don't know how to reproduce nor debug since I can't queue anymore. Arcade games work fine.

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.13-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 387.34
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1c03
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 5280 x 1080
    Primary Display Size: 16.06" x 10.04" (18.94" diag)
                                            40.8cm x 25.5cm (48.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  11950 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  216646 Mb
    Largest Free Hard Disk Block:  80354 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by eplgr** [comment]
Same here on Debian, happened twice in a row. 15 minutes ban so far. I think I won't try to find a game until a confirmed fix is here, I don't wanna get a 24 hours ban.

Also, I think the freeze occurs as soon as the match is found: there's no "match is ready" sound, no pop-up window, I only get the notification from xfce.

**Comment by jfhjfh** [comment]
Same here. Seems to happen on a re-queue but not the first game after launching the game.

I am getting a segfault showing up in dmesg.
`segfault at 9 ip 00007fd1ddd7200f sp 00007ffd4ab5e4e0 error 4 in librendersystemempty.so[7fd1ddd39000+17e000`

**Comment by eplgr** [comment]
@dimitri-koussa Does that mean that the client un-freezes itself for you? I had to kill the process, I never had the chance to re-queue.

**Comment by jfhjfh** [comment]
@eplgr, I had to kill the process after it crashed too. What I meant was that the first match I play after launching the game works (3 times now). After the first game it would crash (3 times here too) then I could kill and relaunch.

I'm on Unity/Ubuntu 16.04 fwiw.

**Comment by danslo** [comment]
Confirming this issue. Currently banned 4 hours from matchmaking due to this happening repeatedly.

**Comment by u92time** [comment]
Same here Ubuntu 16.04 banned for 4 hours :(

**Comment by kisak-valve** [comment]
Possibly related to #1386. If anyone happens to have the game in the quirk state, please check if `killall -18 dota2` has an effect.

**Comment by jfhjfh** [comment]
@kisak-valve killall -18 didn't help. stayed frozen (still frozen now).

I did redirect stderr/stdout and I did get this line around the time it froze:
`ERROR: ld.so: object '/home/dimitri/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

**Comment by eplgr** [comment]
Just now, it froze randomly while spectating a game. `killall -18 dota2` didn't help either.

**Comment by WagnasT** [comment]
Same here on Fedora.  Would love to dig up a crash report or something but currently banned for 4 hours.

**Comment by cluoma** [comment]
Same thing happening for me since a couple days ago, and reconfirmed just now. The client freezes when the 'Accept' box appears.

https://gist.github.com/cluoma/ffbb413b97d961f2807a2531cd0bb821

**Comment by conormcg13** [comment]
Can confirm, 4 hour ban.

**Comment by AutoAwesome** [comment]
Can confirm this bug. Same issue here.

**Comment by mrgsv** [comment]
Can confirm same bug. Manjaro

**Comment by glubsy** [comment]
Same here on Antergos (Arch Linux). I only play Turbo, ~~happens very often, especially when the dota2 window is not in focus (alt-tabbed out, on i3 window manager in a different workspace). Started happening today.~~ edit: irrelevant, it happens also when the window is active / focused.

The infuriating thing is that it counts as a failure to ready up, which adds to the ban preventing from searching another game. :(

It does indeed seem to not happen during the first matchmaking queue. Only in subsequent matchups.

I don't see anything in system logs, but that's probably because I kill the two dota2 processes before the core dumps can even happen? edit: looking at the steam logs, some core dumps seem to have been uploaded after restarting the Steam client.

**Comment by u92time** [comment]
+ 4 hour ban again :( . 
I can confirm that the first game after I open dota goes without any issue.
The issue start to happen after a game played or after someone failed to load on Hero Selection (after accept screem) then the next time when matchmaking is about to load the Accept screen everything freezes no button clickable. 
p.s. the killall -18 dota2 doesn't work.

**Comment by gdrewb-valve** [comment]
See also #1109.

**Comment by tukkek** [comment]
Confirming this, happened twice today and I'm banned from matchmaking. I don't mean to complain but it's unacceptable that we're being banned and possibly put into low-priority when the only thing misbehaving is the official game client, not us as players. 

Please fix this as soon as possible so we can get back to playing DotA - no Linux user should be queuing until this is confirmed as fixed.

Also I have had the game crash on several instances (instant crash to desktop), which in my experience would mean something like a segmentation fault. This has been happening for a week or two now but only rarely, has anyone else seen the same? Has a report been opened already?

I have seen the quality of @gdrewb-valve's work and others here and am hoping that this time too this is put into highest priority as it literally makes matchmaking unplayable for us penguins.

**Comment by glubsy** [comment]
But in this case, it seems that the game crashes as soon as the notification is sent to the notification server/daemon, in which case the user can't even click on accept (since the window is frozen). @ https://github.com/ValveSoftware/Dota-2/issues/1387#issuecomment-359060565

**Comment by tukkek** [comment]
Just wanted to add that this doesn't happen every single time but for me it seems to only happen after I have already played a matchmaking match before. Cannot confirm if this is indeed a requisite for the bug to happen or not since trying to play further will only get me banned from matchmaking for who knows how long.

**Comment by gdrewb-valve** [comment]
Did anybody get console output from a session where this happened?

**Comment by cakesale** [comment]
If you lift my ban I'll try to get some output code :(

**Comment by WagnasT** [comment]
Yeah, it's hard to troubleshoot when we get banned for longer periods of time.  I suppose I could create a throwaway account and mildly inconvenience 9 other players for science!

**Comment by WagnasT** [comment]
Really appreciate the dev responses to this as well as previous issues.  I played all day yesterday with no issue and didn't notice an update today.  Not saying there wasn't an update, just that I didn't notice one, which makes me suspect it isn't a change on the client side.

**Comment by glubsy** [comment]
@gdrewb-valve Here's a Steam client log: https://gist.github.com/glubsy/2612d8fdd295ce2a007f17f720b79b07

Not much going on it seems. I add that this bug occured both with OpenGL and Vulkan renderers. 

Can't test anymore now, banned for 4 hours. :(

**Comment by gdrewb-valve** [comment]
Thanks for the log, you're right that it doesn't give any useful information.  We'll continue to investigate here and see if we can get a repro.

**Comment by glubsy** [comment]
Tomorrow I'll try to get a Dota2 client log. 

I should also add that I have not upgraded my system (Arch Linux) in 20 days, as the last system-wide upgrade was done on 2017-12-29. So I assume it's most likely a change in the dota2 client itself or in the backend somewhere.

**Comment by blazingbags** [comment]
I started the game in console, started searching, the accept button worked and I played a game.

Queueing the 2nd game is where it freezes when the accept button appears.

Nothing new in the console.

The process state in ps aux is ` tl+`, trying to resume it doesn't help.

I restarted the game and queued again and it worked first time

**Comment by Denwid** [comment]
Can confirm same happening here. First game no problem. Temporary fix to prevent bans: Restart game before every queue.

**Comment by gdrewb-valve** [comment]
A change has been made on the server side which may affect this.  We only want a very small number of people to try it to avoid a bunch of penalties if it doesn't help.  @SergeantWagner or @tukkek or @glubsy, if you want to try it out can you exit Dota and Steam and then try a match?  In this particular case I should be able to remove penalties if you give me your Steam account.

**Comment by WagnasT** [comment]
apparently there is an update, going to try it on a throwaway account.

**Comment by tukkek** [comment]
@gdrewb-valve thanks, I'll give it a try, always glad to help! Looking at my match history for today it sounds like it happened pretty close to 50% of the time so if I can get a few matches in a row without it recurring then it should be a good indication that it's indeed fixed.

**Comment by WagnasT** [comment]
1st game works, gunna stomp these noobs then queue again

**Comment by tukkek** [comment]
@gdrewb-valve can you remind me again if there's a default location for a client log? If the game freezes I won't be able to use `condump` to get you any relevant information and I don't want to restart the client and just lose any previous data either if I can help it.

**Comment by gdrewb-valve** [comment]
If you put -con_logfile in your launch options the console output will go to a console.log file in your dota directory under game/dota.

**Comment by gdrewb-valve** [comment]
Besides console output, which so far hasn't been too helpful, when Dota hangs check ps aux to see if the dota2 process is in a tracing state (usually tl+).

**Comment by JohanAR** [comment]
Happened to me 7 minutes ago. This I know because I have 8 minutes left on my 15 minutes ban. Second time today and never before, played 2 games yesterday though only 1 of them was matchmaking.

Xubuntu 17.10, Nvidia, only launch option is "-console"

**Comment by sytranvn** [comment]
> If you put -con_logfile in your launch options the console output will go to a console.log file in your dota directory under game/dota.

@JohanAR  Can you try to get the log and post it here. I'm on 4hrs ban and don't want to get an other 24 :sob:

**Comment by JohanAR** [comment]
@sytranvn I would like to play a game with my friend before getting a 4 hour ban :) If nobody has tested it when we're finished I'll give it a go

**Comment by ghost** [comment]
same problem and got 4 hour ban

**Comment by inzru** [comment]
Can also confirm; am on Ubuntu 16.04 with 15 minute ban now. Super frustrating, thanks gdrewb for your help. So the official recommendation is to just wait until we get more reports of improvement?

**Comment by gdrewb-valve** [comment]
From what has been reported here you are fine to play as long as you exit and restart Dota between games. If you want to be completely safe then I'd hold off until SergeantWagner reports on whether he was able to play a second game.

**Comment by akrashe** [comment]
First queue after game opens works fine, 2nd queue always crashes when accept window comes up.  Happened 3 times, 4 hour ban :/  For now just always restart game after every game I guess.

**Comment by glubsy** [comment]
I have just tested with a secondary account, and the crash didn't happen during the second match making. So perhaps that server fix did the trick.

**Comment by WagnasT** [comment]
got stomped.  default controls are so bad.  queuing second game

**Comment by WagnasT** [comment]
2nd queue worked fine. apparently not paired up with noobs with new account =P  archon 5's and I'm normally crusader 3.

**Comment by eplgr** [comment]
@gdrewb-valve No, my client freezes every time a game is found (the accept window doesn't even pop up).

In fact, I wanted to see if it was the case for me that the first game would work since 1 or 2 people were talking about that (this was ~2 hours ago), and now I'm on a 4 hours ban as the result.

**Comment by gdrewb-valve** [comment]
If you have exited Dota and Steam and restarted both and your game hangs on accept the very first time please open a new issue as you're hitting something separate.  Please run with -con_logfile and include a gist of your system information from Steam and the console.log file.  Also include any information about what has changed since the last time Dota worked for you.

**Comment by WagnasT** [comment]
i think I'm good.   Devs commended.  Managed to stomp the second game noobs.  I'll get time to play again later today and try to queue a bunch of times.

**Comment by JohanAR** [comment]
I could queue for a second game after winning the first. Second game was turbo mode and I had Dota focused. When it froze earlier Dota was unfocused and I was watching twich on second monitor if that matters

**Comment by WagnasT** [comment]
Yeah, I usually watch the top players in the client while I queue, didn't occur to me that watching is about the same as playing the first game.

**Comment by jmsauret** [comment]
Can also confirm. Ubuntu 16.04 64 bits ; Nvidia driver version 384.111
Since last Dota update (this night) when i am starting Steam, 1st Dota game is good, 2nd game is crashing when ready. If i restart Steam and Dota, same issue (1st Dota game is good, 2nd game is crashing). Other steam games (War thunder, Portal, Shadowrun chronicles) are fine.

**Comment by gdrewb-valve** [comment]
@jmsauret, are you confirming something you just experienced?  Is it actually a crash or does Dota hang (you can check the hang state with ps aux).  A couple of people who were experiencing the original hang reported here no longer have it so you may be seeing something else.  If so open a new report.  lease run with -con_logfile and include a gist of your system information from Steam and the console.log file. Also include any information about what has changed since the last time Dota worked for you.

**Comment by jmsauret** [comment]
sorry i can't reproduce it and verify if it's a crash or a hang : too much crashs so i'm baned for 4 hours

**Comment by jmsauret** [comment]
I searched in my /var/log/dpkg.log file. Last update last night (01h55 AM) : before this update all was fine

> libpython2.7:amd64 2.7.12-1ubuntu0~16.04.2 2.7.12-1ubuntu0~16.04.3
> libc-bin:amd64 2.23-0ubuntu10
> libegl1-mesa-dev:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libwayland-egl1-mesa:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgbm1:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgles2-mesa-dev:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgles2-mesa:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgl1-mesa-dev:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgl1-mesa-glx:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgl1-mesa-glx:i386 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> mesa-common-dev:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libglapi-mesa:i386 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libglapi-mesa:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgl1-mesa-dri:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libgl1-mesa-dri:i386 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> libxatracker2:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4
> mesa-vdpau-drivers:amd64 17.2.4-0ubuntu1~16.04.2 17.2.4-0ubuntu1~16.04.4

**Comment by tukkek** [comment]
@gdrewb-valve I played three games in a row and had no problem in any of them. I wouldn't be so quick to dismiss everybody else as having a new problem instead since a lot of confirmations have come after the attempted server-side fix... could be just dumb luck that we didn't get the issue and the "first match is fine, second crashes" is pure speculation, especially because people have reported the first game crashing in one of the first comments in this issue (before the fix).

This has been more than enough DotA for me today (although I'm glad to help :) ) I'll play some extra matches tomorrow and let you people know how it went.

I did come across an entirely separate bug again, that wasn't even the other one I mentioned in my first comment here, which I had totally forgot about. It's pretty much a freeze too so it might be related (#1390). Unfortunately the Linux client has been anything but stable in the past couple weeks or so.

**Comment by eplgr** [comment]
My 4 hours ban is gone and yeah, I could successfully accept my first game.

**Comment by gdrewb-valve** [comment]
If people are still having a problem with the process being in a tracing state it's definitely something different from what was fixed server-side for this issue.  That's not a dismissal, it's a request to open a separate issue.  If we hear from @RogerDodger about things working for him I'm going to close this one so people will want their own issues for their problems.

**Comment by gdrewb-valve** [comment]
Also as people might be noticing matchmaking bans have been cleared.

**Comment by tukkek** [comment]
> If people are still having a problem with the process being in a tracing state it's definitely something different

Can you explain when should we continue on this issue and when to open a new one? It's unclear to me.

**Comment by gdrewb-valve** [comment]
Make sure you have exited Dota and Steam and restarted.  This particular tracing hang is resolved so basically anybody that's still hanging on match accept after restarting has a different issue from this one.  There can be one new "hang on accept match" issue so look and see if one has been created.  In any new issue please include the gists I mentioned above.  Note also that hangs on accept have been occurring on all platforms for a while (see #1109).

If you want to gather info do 'ps aux' in a terminal and see if the dota2 process state (typically the STAT column) starts with 't'.  If so you seem to be hitting the same issue as this, but that shouldn't happen.

**Comment by RogerDodger** [comment]
Did the following today and experienced no freezes:

1. Restart steam/dota
2. Spectate a game
3. Queue and accept a matchmaking game
4. Queue and accept another matchmaking game

So it seems to be fixed now.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
