### ISSUE TITLE
Game freeze on notification

### ISSUE THREAD

**Issue by Patrick-Edouard** [ValveSoftware/Dota-2#1388]
Hey guys, I hope someone will read this before the week end !

So since yesterday update, I'm having crash on dota when the game issues me a notification (aka party invite, game found, ...)

There is maybe an issue with the connection with GNOME 3 since I usually get a pop up in my shell when dota do such a thing

Since I just got a 5 minutes ban from not accepting a ranked due to this crash, I hope you'll be able to patch it quickly :/ It make my buddy feels like Linux ain't a reliable gaming solution.

there is my set up:

OS: Fedora release 27 (Twenty Seven) x86_64
Host: MS-7A12 1.0
Kernel: 4.14.13-300.fc27.x86_64
Uptime: 2 hours, 42 mins
Packages: 2573
Shell: bash 4.4.12
Resolution: 1920x1080, 1920x1080
DE: GNOME
WM: GNOME Shell
WM Theme: Adwaita
Theme: Adwaita [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-6700K (8) @ 4.200GHz
GPU: NVIDIA GeForce GTX 970
Memory: 4894MiB / 16002MiB

Thanks,

**Comment by kisak-valve** [comment]
Hello @Patrick-Edouard, this issue is already being tracked at #1387. Closing as a duplicate.

**Comment by Patrick-Edouard** [comment]
Ok my bad ! Thanks for the heads up
