### ISSUE TITLE
Lags with ping ~50 and 0/0.

### ISSUE THREAD

**Issue by anmacik** [ValveSoftware/Dota-2#1389]
Since 707c(mb earlier) after 7-8pm(utc+0) have 1-2% packet loss always(not critical to play, but not comfortable) + sometimes strong packet loss + sometimes strong ping spikes. When it happens to me it always happens with somebody else in current game. ue west/east, russia servers. Is there any way to fix it or valve want to kill dota 2 so much that they make it unplayable at all?

About fps panel. There was a game in wich i couldn't use BB for 5-7 second because of lags. At that moment enemys destroy the throne. Whole game i saw 50+- ping and (0-1)/0 packet loss. So it happens always. Except for rare moments i always see 50+- ping and 0/0 packet loss.

**Comment by gdrewb-valve** [comment]
You'll want to post this at dev.dota2.com
