### ISSUE TITLE
No option to launch reborn linux.

### ISSUE THREAD

**Issue by LineoLemon** [ValveSoftware/Dota-2#139]
There is no way for me to launch dota reborn.I do not get this window that asks me if i wanna play reborn or normal dota 2 when i start the game.It instantly starts normal dota 2.I also can not start reborn by right clicking dota in the library.There is no option for that.I downloadet the dlc and all.And it is installed, because it is marked as installed and the reborn content is in the games folder.I tried many things, like redownloading the game and the dlc mutiple times.I verified the game cache.I reinstalled steam.I resetted steam.Also normal dota 2 now starts in windowed mode.I was not able to play reborn since it was released for linux.Everyone i asked had no solution for this problem, so i finally decided to post it on github.

**Comment by gdrewb-valve** [comment]
Are you running 64-bit?  The game is 64-bit only.  Can you post your system info?

**Comment by LineoLemon** [comment]
Hm i did not know that.I am using 32-bit.So this is why i don't get the window that asks me?

**Comment by gdrewb-valve** [comment]
Correct, since you can't run the game it doesn't give you the option.

**Comment by gdrewb-valve** [comment]
#18 covers being more clear about the 64-bit requirement, so closing this out.

**Comment by LineoLemon** [comment]
Thank you, for your help.
