### ISSUE TITLE
[Linux] Client freezes when exiting game

### ISSUE THREAD

**Issue by tukkek** [ValveSoftware/Dota-2#1390]
I have had this happen multiple times in the last one or two weeks. Basically when you try to exit the client (after your match is over with and already disconnected, from the starting screen) the client freezes. This isn't critical since it's trivial for me just to kill it (Ctrl+Alt+Esc) but I'm reporting it since it might be related to #1387

**Comment by gdrewb-valve** [comment]
Are you still seeing this after the fix for #1387?  If so can you post a console log here and also check on the dota process status with ps aux?

**Comment by tukkek** [comment]
Just like #1387, killing the process still leaves something hanging because I cannot exit Steam cleanly after that ("Waiting for Dota 2 to shut down..."). Even if I restart Steam it still won't let me restart Dota ("only one instance of the game can be running at one time").

If I close my current user session (on KDE), then I can log back in and start Steam and Dota normally again.

@gdrewb-valve yes, see my last comment on the other issue. I'll be posting my logs here in a second. I can see that you're on top of the entire thing, your hard work is really appreciated, let me know if I can do more to help.

**Comment by gdrewb-valve** [comment]
If you get in this state do a ps aux and see if there's a dota2 process still around.  There most likely will be and that's the instance that's preventing you from starting a second one.  The state of that hung process would be interesting.

**Comment by tukkek** [comment]
This is my `console.log`. I was trying to help with #1387 so it's not clean and I played a few games in that session before exiting the client and having the client freeze. Zipped because it's 5MB uncompressed.

[console.zip](https://github.com/ValveSoftware/Dota-2/files/1648389/console.zip)

**Comment by tukkek** [comment]
Output of `ps aux` before killing the frozen client window.

[ps aux.txt](https://github.com/ValveSoftware/Dota-2/files/1648391/ps.aux.txt)

**Comment by tukkek** [comment]
After killing the process and posting these messages, I still have 3 dota related processes running (`sh, dota.sh, dota2`). Here's a new `ps aux` after the window was killed in case it helps any: 

[ps aux.txt](https://github.com/ValveSoftware/Dota-2/files/1648393/ps.aux.txt)

**Comment by tukkek** [comment]
Finally, my system information from the Steam Client, for completeness' sake: [system info.txt](https://github.com/ValveSoftware/Dota-2/files/1648394/system.info.txt)

**Comment by gdrewb-valve** [comment]
The console log looks clean, nothing of note there.  The ps aux logs are interesting as they show dota2 sleeping and not traced like #1387.  Dota is apparently waiting for something to happen but there's no way to tell exactly what.  If you can remember the exact (and hopefully minimal) steps that lead to this that would help us isolate a repro.

**Comment by tukkek** [comment]
I have had this happen a few times to me already in the last days but it's pretty rare (anywhere up to a couple weeks ago, not sure, I haven't kept track). My use-case with the Dota client is pretty much always the same: open client, play one or more ranked matchmaking (All Pick only) and then quit the game. Sometimes the game will freeze upon quitting, sometimes not - more often it'll leave as intended.

I know how important reproducible steps are to troubleshooting and debugging but that's the most I can help with at this time since my very typical "workflow" doesn't reliably reproduce the error. If there is anything else that I can look into when the error pops up, let me know and I'll make sure to try it next time it shows itself.

**Comment by gdrewb-valve** [comment]
No problem, we'll also try and catch it.

**Comment by 3141bishwa** [comment]
Interestingly, this happened to me a couple of times today. I was just done with one match and was finding another match when the client froze. I did not realize it until my friends told me to accept the match but there was no way to accept it. Even though the client froze, I was somehow still in the party finding the match.

**Comment by tukkek** [comment]
@3141bishwa This report is about quitting the game, you may want to look into #1387 instead.

**Comment by ezojg** [comment]
This happened to me about twice this past week. The screen goes grey but I still can see the panel (in eOS). If I change workspace the problem goes away, oddly.

**Comment by ghost** [comment]
This is still happening and it's very annoying. When exiting it freezes for about 20 seconds after which it continues to produce stuttering, distorted sound and lag.

`plasmashell` has been keeping one of my CPU cores at 100% until I restarted it.

**Comment by tukkek** [comment]
EDIT: ignore this comment, see the next one instead.

This hasn't happened to me in a long time now. It's fixed on my end.

Celofan, maybe try to produce a log. When it used to happen to me it never hung the CPU or any other side effect so this could be a new issue?

**Comment by tukkek** [comment]
OK just because I said so it happened to me today xD and yes, it was hogging one of my cores. Was there a recent update that maybe reintroduced this issue (or a similar one)? Because I really can't recall this happening to me lately.

Also, from the fact that I noticed my cooling fans were running stronger than usual before the client froze, it might be entirely possible that DotA was hogging a core before I even attempted to quit the client. A dangling thread in an infinite loop (or equivalent) would explain the game failing to quit as well, if it's waiting for said thread to finish (which it never does).

Sorry but I had not logging active. If it happens again soon I'll look up how to do that again.

**Comment by tukkek** [comment]
My computer seems to be running uncommonly hot today so maybe that last observation is not that helpful (not necessarily directly related to the bug).

**Comment by amitavmohanty01** [comment]
@kisak-valve @gdrewb-valve I have uploaded crash dump details when it happened. Please check those and tell me what more information will be useful in debugging this problem.

**Comment by rexmtorres** [comment]
I'm still also experiencing this on Fedora 25 (GNOME).  I have to kill the process every time I want to exit the application.

**Comment by RichMartel** [comment]
I have this issue as well on Manjaro Gnome.  I have to do this to exit:
`killall -s KILL dota2`

**Comment by bkacjios** [comment]
I haven't been on my Linux install for awhile, but I don't remember this happening before. It locks up and freezes 100% of the time every time I exit now. I'm on Arch Linux with KDE has my DE.

System info: https://gist.github.com/bkacjios/065d8157adddb684e86dbe697f47dce2
ps aux: https://gist.github.com/bkacjios/2b74016a6e0da52c6688f90dbe13c1a2
console.log: https://gist.github.com/bkacjios/f82b8155e9aa97112b2f39dd1cdfa38d

**Comment by kisak-valve** [comment]
Hello, at this point, the feedback on this issue report is too old to be investigated. If you're using the NVIDIA 495 series video driver and see something similar, then you're looking for the issue being tracked at #2006.

Closing as outdated.

**Comment by xelnagamex** [comment]
Looks like an issue is still actual back again on my Arch Linux x86_64

**Comment by segidev** [comment]
> Looks like an issue is still actual back again on my Arch Linux x86_64

Ubuntu 20.04 for me

**Comment by roworu** [comment]
Same here on Fedora 35
