### ISSUE TITLE
[Win 10] Microphone issue specific to Dota 2

### ISSUE THREAD

**Issue by bdockery81** [ValveSoftware/Dota-2#1392]
Dota 2 displays a crossed-out mute icon whenever voice chat is attempted, and voice chat cannot be transmitted. This occurs even though the microphone audio is detected successfully via viewing the 'level' feedback bar in the Dota 2 client audio settings.  The microphone audio works correctly throughout the rest of the operating system, and Steam, as well.

**Comment by gdrewb-valve** [comment]
This tracker only handles bugs specific to Mac and Linux, you'll want to post at dev.dota2.com
