### ISSUE TITLE
[Linux] Can't Alt-tab in fullscreen

### ISSUE THREAD

**Issue by tkossak** [ValveSoftware/Dota-2#1395]
When i run the game in full screen mode the alt-tab combination doesn't work at all. Instead of switching the windows it sometimes blocks the "alt" key, so whenever I right click on the map i ping it, instead of moving my hero there.
Please help

os: Linux Mint 17 x64 Cinnamon
[My System Info](https://gist.github.com/tkossak/1b22784b7c10714bc00d)

**Comment by SHOTbyGUN** [comment]
To fix "cannot ALT + Mouse1 to ping map" in Linux Mint: Cinnamon

1. System Settings
2. Windows
3. On the bottom: Special key to move and resize windows: <Alt>
Change it to disabled, or something else.

Xfce workaround: http://askubuntu.com/questions/270032/how-do-i-disable-window-move-with-alt-left-mouse-button-in-xubuntu

**Comment by theartas** [comment]
Thanks a lot!!!! SHOTbyGUN 
It worked excellent. I was getting desperate xD

Distro:
Debian Cinnamon

**Comment by tkossak** [comment]
It works for me too - alt + tab or alt+LMB/RMB. Thank you.
