### ISSUE TITLE
Dota2 Scripting API - SetPoseParameter

### ISSUE THREAD

**Issue by Juicebox360** [ValveSoftware/Dota-2#1396]
Posted this over on the dev.dota2 forum, but getting more visibility wouldn't be bad. SetPoseParameter seems like it doesn't work, which is odd because in the model editor, I can manipulate and demo pose parameters just fine.

I have a model that I created a Lua animation script for, and assigned it two pose parameters - move_x and move_y. I use these to adjust the movement of the model along the x and y axis respectively. First, I initialise the model by object:StartGestureWithPlaybackRate( gesture, rate ) and then object:SetPoseParameter( paramName, fValue ). However the function seems to have no effect on the visual whatsoever.

Thanks in advance

**Comment by kisak-valve** [comment]
Hello @Juicebox360, this issue tracker is limited to the Mac and Linux ports of Dota 2. Issues that cover all three platforms is handled at dev.dota2.com and there most likely won't be any updates on this issue report.
