### ISSUE TITLE
Game crashing on entering a game.

### ISSUE THREAD

**Issue by dinomacri** [ValveSoftware/Dota-2#1397]
My game crashes when entering a game. I have tried playing a public match and crashed, from then I have been testing my game in an offline-bots match. I have reinstalled my "video-amdgpu" driver, and have also completely reinstalled the game.

I am using a i7-960, RX 480 with the video-amdgpu driver, 4.14.15-1 kernel on Manjaro.

If there are any logs or information which I could supply, let me know.

**Comment by kisak-valve** [comment]
Hello @dinomacri, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please include them (commonly found in `/tmp/dumps`) in an archive.

**Comment by mastercoms** [comment]
System info: https://gist.github.com/mastercoms/dad032220ab36849f8f9ed22c25bc510

```
Process 5133 (dota2) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 5133:
                                                  #0  0x00007f1b73ecba3f n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so)
                                                  #1  0x00007f1b73ecc2a9 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so)
                                                  #2  0x00007f1b73ecc631 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so)
                                                  #3  0x00007f1b73956106 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so)
                                                  #4  0x00007f1b73b307e1 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so)
                                                  #5  0x00007f1b900a0125 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #6  0x00007f1b9009bd61 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #7  0x00007f1b90092e57 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #8  0x00007f1b900889ec n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #9  0x00007f1b90089035 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #10 0x00007f1b9007376e n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #11 0x00007f1b90076e26 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #12 0x00007f1b90077149 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
                                                  #13 0x000055c1bee5618f n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2)
                                                  #14 0x00007f1b93606f4a __libc_start_main (libc.so.6)
                                                  #15 0x000055c1bee56225 n/a (/home/mastercoms/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2)
```

https://mega.nz/#!elN2HAjJ!e-T2haCoC5Drq-fOZzD-Gz7kq2BcJunWFBrAMZKjBeg

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libclient.so (part of Dota 2).

**Comment by mastercoms** [comment]
Also, this crash happens on both the OpenGL and Vulkan renderers.

**Comment by Seeboooo** [comment]
Also having the same problem (stopped working somewhere in the past 2 weeks or so). I can launch the client but the game close soon after I start a game (not even reaching the loading screen). 

rx 580 (amdgpu) with ryzen 1600x - 4.15.0 kernel

[https://gist.github.com/Seeboooo/6f36045368a95bce42af9b2312fbad47](https://gist.github.com/Seeboooo/6f36045368a95bce42af9b2312fbad47)

edit:
something finally showed up in /tmp/dumps
[https://gist.github.com/Seeboooo/2badda3ddde3e8a2cc955cfd6c88972b](https://gist.github.com/Seeboooo/2badda3ddde3e8a2cc955cfd6c88972b)

**Comment by Seeboooo** [comment]
Oddly enough, I can join games if I lunch dota through the dota.sh script with the debugger active (debugged logs attached). The game does feel a lot slower than usual. Any clue to which module wasn't loaded and that might be causing the issue?

[https://gist.github.com/Seeboooo/ffdb6174640cab82c5b8e94dfb69b39b](https://gist.github.com/Seeboooo/ffdb6174640cab82c5b8e94dfb69b39b) 
(started dota, joined a game twice then closed dota)

**Comment by dinomacri** [comment]
System information: https://gist.github.com/dinomacri/57467b62e1efb1cc1c5b77d9a1959314

Snippets from /tmp/dumps related to dota: https://gist.github.com/dinomacri/59bc6e812122924dc5b96d3cfd6252c6

Output when running dota.sh (refuses to open at all, as compared to launching through the steam client): https://gist.github.com/dinomacri/0589bbc09d081d9b27ddfda0626755ab

Edit: Okay, I've just done a system upgrade (I believe the kernel and things related to my graphics driver were updated) and I have successfully gotten into a bots game without a crash, seems to be fixed.

**Comment by Seeboooo** [comment]
@dinomacri the last stable update to the graphic stack seems to have fixed the issue for me (using 4.15 kernel).

[https://forum.manjaro.org/t/stable-update-2018-02-03-kernels-libreoffice-browsers-thunderbird-php-haskell/39663/55](https://forum.manjaro.org/t/stable-update-2018-02-03-kernels-libreoffice-browsers-thunderbird-php-haskell/39663/55)

mesa 17.3.3-1.1 --> 17.3.3-2
vulkan-radeon 17.3.3-1.1 --> 17.3.3-2
xorg-server 1.19.6+13+gd0d1a694f-0.1 --> 1.19.6+13+gd0d1a694f-1

downgrading mesa back to 17.3.3-1.1 leads to the same bug (dota crashing when loading a game)

**Comment by mastercoms** [comment]
Still not fixed for me.
I tried on both nvidia 387.34-21 and 390.25-3 and on kernels linux 4.14.15-1, linux-zen 4.15.0-1, linux-zen 4.15.1-1.

**Comment by gdrewb-valve** [comment]
Make sure to validate your Dota install from the Steam client.

**Comment by mastercoms** [comment]
Seems like the issue was fixed for me by deleting my `dota/cfg` folder and then verifying game cache.

**Comment by kisak-valve** [comment]
Thanks for the follow up. Closing as the issues reported appear to have been resolved.
