### ISSUE TITLE
[Mac] Lowest graphics settings show no tree / tango outline appears

### ISSUE THREAD

**Issue by deplorableword** [ValveSoftware/Dota-2#140]
Steps to reproduce. 

Run the Mac client on lowest setting using the slider. 
Buy a tango. 
Try to use a tango on a tree, no outline / selection outline appears.

Changing the slider to any other settings shows the outline

**Comment by danginsburg** [comment]
This happens on Windows as well.  The issue being pointed out here is that if the "Additive Light Pass" is disabled then no selection glow appears.

**Comment by danginsburg** [comment]
This is not Linux/Mac specific, but I've passed this on to the larger team and is being fixed.  It won't be tracked here.
