### ISSUE TITLE
[7.08] Dota client freezes on taking a screenshot (steam hotkey)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1400]
Gentoo Base System release 2.4.1

mesa-17.2.0_rc4
nvidia-drivers-375.82
steam-client-meta-0-r20161126
steam-games-meta-0-r20160812
steam-launcher-1.0.0.54-r3
steam-meta-0-r20160817

WM: i3
Kernel: 4.9.75

**Comment by kisak-valve** [comment]
Hello @deterenkelt, this issue is not limited to Dota 2 and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4928. Closing as a duplicate.
