### ISSUE TITLE
[LINUX] Dota 2 closes after logo

### ISSUE THREAD

**Issue by alanpoon** [ValveSoftware/Dota-2#1402]
Here is my crash dump.
https://gist.github.com/anonymous/8de2464259c5db1e168859265ddc4793

**Comment by kisak-valve** [comment]
Hello @alanpoon, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alanpoon** [comment]
Hi, here is the link. https://gist.github.com/alanpoon/f53b7f1ff7bd48f59e2620e058510957

**Comment by gdrewb-valve** [comment]
Make sure to validate your Dota install from the Steam client.

**Comment by alanpoon** [comment]
Validated 100%, still cannot

**Comment by kisak-valve** [comment]
Probably worth mentioning that OpenSUSE Leap 42.2 has reached its [end of life](https://lists.opensuse.org/opensuse-security-announce/2018-01/msg00103.html) upstream. You should consider updating your system, but that is separate from this issue.

**Comment by alanpoon** [comment]
I have a line that says NET: not connected. Could this be the problem?

**Comment by alanpoon** [comment]
Fixed with: STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
