### ISSUE TITLE
How to remove Dota 2 from notifications High sierra

### ISSUE THREAD

**Issue by avxkim** [ValveSoftware/Dota-2#1407]
![image](https://user-images.githubusercontent.com/5739191/36342232-83416f3a-1425-11e8-8d2f-915973f38a1c.png)

Is it possible to remove this from Notifications settings?

**Comment by gdrewb-valve** [comment]
I don't think that you can since Dota registers as a notification source.  Is it that you don't want to see notifications or is having Dota in the list causing an issue somehow?

**Comment by avxkim** [comment]
No, it just was my curiosity. You can remove it using CMD + Backspace, but when you launch Dota 2 again, it automatically adds to notifications once again.

**Comment by gdrewb-valve** [comment]
OK, closing this out.
