### ISSUE TITLE
[MacOS] Dota unplayable

### ISSUE THREAD

**Issue by Th3NightHawk** [ValveSoftware/Dota-2#1410]
* System information: https://gist.github.com/Th3NightHawk/9ca5223717ceb84f48c0ebc1fedb8210
* Have you checked for system updates?:  Yes, none available
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

When running anything in game (Even hero demo mode) my frame rate drops dramatically (down to +/- 10fps). This is when graphics are set to the highest settings. The only way to get to any playable/watchable fps I have to set my graphics to the lowest.

My last MacOS update was installed on the 11 Feb (10.12.6) however I've used the client without any issues up until this weekend.
![shot_0000](https://user-images.githubusercontent.com/22588521/36432140-18775fe0-1662-11e8-891a-3e80adbc1f23.jpg)

![image](https://user-images.githubusercontent.com/22588521/36431782-21084b5c-1661-11e8-8014-937737a4b16f.png)

**Comment by danginsburg** [comment]
I am not aware of anything that changed recently that would impact performance in this way.  Are you sure it is running on your AMD Radeon 555?  To confirm, you can start the game from the command-line (with Steam already opened):

From this folder:
```
/Users/dang/Library/Application Support/Steam/steamapps/common/dota 2 beta/game
```
run:
```
$ ./dota.sh
```

You should see something in the output like this:

```
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL vendor ATI Technologies Inc.
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL renderer AMD Radeon HD - FirePro D500 OpenGL Engine
void COpenGLDriverEntryPoints::DumpContextInfo(): Using OpenGL context version 4.1
void COpenGLDriverEntryPoints::DumpContextInfo(): Context supports GLSL version 4.10
 f
```

If it is using the Intel Integrated GPU instead of AMD you could try forcing it to the AMD Radeon 555 using gfxCardStatus (https://gfx.io/).

**Comment by Th3NightHawk** [comment]
Docker Mac App which was installed yesterday removed. Performance back to acceptable levels... fml

**Comment by Th3NightHawk** [comment]
Thanks for the feedback @danginsburg . I did verify that the AMD Radeon was being used though, even forced it. Still didn't change until the Docker app was removed. Not sure why it had such a dramatic effect. If I figure out why I'll update this post.
