### ISSUE TITLE
[Linux] Can not start dota 2 game since feb 22

### ISSUE THREAD

**Issue by robertpro** [ValveSoftware/Dota-2#1412]
#### Your system information

* System information from steam: [gist](https://gist.github.com/robertpro/38d0e8c563ecd752b63895c5fa41ba3c)
* Have you checked for system updates?: `Yes`
* Are you using the latest stable video driver available for your system? `Yes`
* Have you verified the game files?: `Yes`

#### Please describe your issue in as much detail as possible:
I can not start the game using the Steam UI, it just shows a dialog like normal loading but after 3 seconds (normal here) it usually open the game (like yesterday) but today the game is not opening.

I ran dota.sh file (/home/roberto/.steam/steam/steamapps/common/dota 2 beta/game/dota.sh)
```bash
./dota.sh 
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198100539603 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198100539603
Setting breakpad minidump AppID = 373300
 failed to dlopen "/home/roberto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
 failed to dlopen "librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory
 failed to dlopen "libpangoft2-1.0.so" error=libbz2.so.1.0: cannot open shared object file: No such file or directory
 failed to dlopen "libpangoft2-1.0.so" error=libbz2.so.1.0: cannot open shared object file: No such file or directory
text/uitextlayoutpango.cpp 348 CheckDeepLoadModule():
Unable to load 'libpangoft2-1.0.so', your game install may be corrupted or you may have a system conflict


crash_20180222220826_1.dmp[3491]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180222220826_1.dmp
./dota.sh: line 104:  3412 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
[roberto@roberto game]$ crash_20180222220826_1.dmp[3491]: Finished uploading minidump (out-of-process): success = yes
crash_20180222220826_1.dmp[3491]: response: Discarded=1
crash_20180222220826_1.dmp[3491]: file ''/tmp/dumps/crash_20180222220826_1.dmp'', upload yes: ''Discarded=1''
```

Also I tried to fix the problem by linking `libdbus-1.so.3` like this: https://github.com/ValveSoftware/Dota-2/issues/1336#issuecomment-341278305
```bash
ln -s ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3 ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libdbus-1.so.3
```

This worked for me before, but not this time

**Comment by kisak-valve** [comment]
Hello @robertpro, your system information is indicating you're using llvmpipe, which is mesa's faster software renderer. Please check that your video driver is healthy and working properly outside of steam.

**Comment by robertpro** [comment]
Well, I can play other games, like tf2 or csgo 

![image](https://user-images.githubusercontent.com/8595170/36649110-187041cc-1a60-11e8-85b8-f9685ff4fec8.png)

![image](https://user-images.githubusercontent.com/8595170/36649144-6929d466-1a60-11e8-914d-3e6614acb1ca.png)

But I feel some bad perfomance... will check again for the Nvidia driver

**Comment by robertpro** [comment]
Well I can see there are no updates, and I can see Nvidia driver in use:

```bash
lspci -s 0a:00.0 -k
0a:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device 8572
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

Should I reinstall the driver ?

**Comment by robertpro** [comment]
I am sorry for opening this issue, the problem was "something" (am not sure what) about the system update, I updated fedora, and it broke Nvidia driver, so I have reinstalled the driver and it is working ok again, thanks! @kisak-valve
