### ISSUE TITLE
Mac: Interaction with f.lux is broken

### ISSUE THREAD

**Issue by eXcuvator** [ValveSoftware/Dota-2#1413]
#### Your system information

https://gist.github.com/eXcuvator/c92e766abc6e683a255f09f1da6c7bce* Have you checked for system updates?:  Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
f.lux is an app that allows you to remove blue colors from your screen, for example in the evenings before going to bed.

Since the Vulkan update, interaction with f.lux (https://justgetflux.com) is broken. Whenever tabbing into DotA, or out of dota, f.lux holds for a second, the screen gets blue again, before blue colors are removed. Before this update (28.02.), all fullscreen versions of dota were interacting with flux the way they are supposed to. All other applications still work with f.lux

#### Steps for reproducing this issue:

1. Install and run f.lux
2. Run dota in fullscreen mode (Desktop-friendly fullscreen)
3. Tab in and out of dota

**Comment by danginsburg** [comment]
This may be related to us updating SDL but has nothing to do with Vulkan.  Not sure this is a dota bug as opposed to a bug with f.lux.

**Comment by eXcuvator** [comment]
Yes, I only observed it happening yesterday (28th feb) for the first time, and assumed that it was coming from the Vulkan change.

**Comment by hipunk** [comment]
Possible workaround: flux is now built in into macOS. Open notification center (top right corner of the screen), scroll up and enable night shift.

**Comment by eXcuvator** [comment]
With a recent update (cannot say exactly when) it's working again -- I guess this can be closed.
