### ISSUE TITLE
[Linux] Game does not launch

### ISSUE THREAD

**Issue by SingularityCat** [ValveSoftware/Dota-2#1414]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/SingularityCat/37fbfa4905fb8da53e4727a1ee254209
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes (Mesa 17.3.6)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Game fails to load, complains about failing to load `librenderdoc.so`.

This happens when running both with and without the Steam runtime.

https://gist.github.com/SingularityCat/4019ce64ea64a457a09c236abfd40aac

#### Steps for reproducing this issue:

1. Attempt to launch the Linux build.

**Comment by SingularityCat** [comment]
I should probably mention that Dota worked fine a few days ago.

**Comment by SingularityCat** [comment]
~Downgraded Mesa to 17.3.5 and it works, this looks like a Mesa issue.~
Mesa 17.3.5 gets to the main menu, but fails to enter any kind of game.

**Comment by kisak-valve** [comment]
Hello @SingularityCat, Mesa 17.3.6 is an emergency release for outstanding issues with the Intel stack. There are no AMD changes between 17.3.5 and 17.3.6. This issue should be brought to the attention of your distro's package maintainer(s) for Mesa.

Closing as this can't be an issue with Dota 2 with the symptoms described.

**Comment by SingularityCat** [comment]
Hi @kisak-valve, I've just discovered that downgrading mesa allows me to get to the menu, but I fail to successfully load into a game.

Similarly, entering the hero demo screen fails.

**Comment by kisak-valve** [comment]
Can you add `-con_logfile` to Dota 2's launch options, reproduce the issue, then throw `<dota 2 install dir>/game/dota/console.log` in a [gist](game/dota/console.log) and include a link in this issue report?

If you can find any CrashIDs or minidumps in `/tmp/dumps` related to this issue, please include them as well.

**Comment by SingularityCat** [comment]
@kisak-valve it seems Dota literally just had an update pushed, and I can no longer reproduce this crash, on either the OpenGL or Vulkan version.

**Comment by gdrewb-valve** [comment]
Closing as per the last comment.
