### ISSUE TITLE
How can change the name font.（not steam name）

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1416]
Linux linux 4.15.7-1-MANJARO #1 SMP PREEMPT Wed Feb 28 20:35:31 UTC 2018 x86_64 GNU/Linux

As you see the name too high,it blocked the health bar.and look like very ugly.so I want to change the font or adjust the height。

![screenshot_20180311_144413](https://user-images.githubusercontent.com/11383988/37250580-3c3f775e-253b-11e8-8af0-5dd3756d5323.png)

**Comment by gdrewb-valve** [comment]
There isn't a simple way to customize it.  As this isn't a Linux-specific thing (it's kind of related to Linux since fonts are more variable on Linux but the underlying issue affects everything) I've passed this on to the larger team.
