### ISSUE TITLE
[LINUX] Dota 2 crashes after starting bot match with default bots

### ISSUE THREAD

**Issue by hayyan71** [ValveSoftware/Dota-2#1418]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/hayyan71/748ff27d7c1a3b14f90f9c79847f220b
* Have you checked for system updates?: Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I cannot start bot matches after 12 march update. last time I've played vs bots in the same day before update and it was working.
if you select another bot scripts (e.g Ranked matchmaking AI), it works fine. co-op matches are working too. just default bots option has this issue.

#### Steps for reproducing this issue:

1. click on PLAY DOTA >> PRACTICE WITH BOTS
2. select solo and default bots
3. click on start
after a few secs, game will crash

**Comment by gdrewb-valve** [comment]
Can you post a gist of the console log?  You can add -con_logfile to your launch options and it'll create a console.log file in your Dota install under game/dota.

**Comment by hayyan71** [comment]
@gdrewb-valve 
here:

https://gist.github.com/hayyan71/2709e9bfc197ca6ec9087dcd05b8f647

**Comment by kisak-valve** [comment]
Looks like OpenSUSE Leap 42.3 ships glibc 2.22, but this hint looks like a red herring as the described scenario works on my OpenSUSE 42.3 test box.

**Comment by gdrewb-valve** [comment]
I'm not having any troubles on my Linux system either, we'll have to see if other people hit it and we can establish a common configuration.

**Comment by kisak-valve** [comment]
@hayyan71, if you can find any CrashIDs or minidumps (commonly found in `/tmp/dumps/`) related to your issue, please put them in an archive and include them in this issue report.

**Comment by hayyan71** [comment]
[crash_20180315105150_1.tar.gz](https://github.com/ValveSoftware/Dota-2/files/1814350/crash_20180315105150_1.tar.gz)

**Comment by hayyan71** [comment]
[failed to dlopen libtensorflow.so error=/lib64/libm.so.6: version `GLIBC_2.23' not found] but GLIBC version in Leap 42.3 is 2.22.

Upgrading from 42.3 to Tumbleweed (GLIBC 2.27) solved the problem for me

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in ld-2.22.so.

**Comment by gdrewb-valve** [comment]
The failure to load libtensforflow.so is not an issue, the game doesn't require that to succeed.  I can force that failure on my Linux box without any game crashes.  As the crash is in the system loader itself, though, I wonder if on some versions the failure causes something bad to happen in the system?

**Comment by tpruzina** [comment]
Can you add some option which will stop training NN clientside, I had no idea it was doing that, but now I kinda understand why gpu is being utilized even when alt-tabbed on background. Does this have any purpose for non-plus subscribers? Or it's just eating electricity for no good reason?

**Comment by gdrewb-valve** [comment]
It isn't training and in fact is mostly unused.  The larger team is probably going to pull the library from the install in an upcoming released.

**Comment by tpruzina** [comment]
@gdrewb-valve thanks

**Comment by gdrewb-valve** [comment]
The March 20 update has made changes in this area, can people retest bot matches?

**Comment by hayyan71** [comment]
@gdrewb-valve 

Re-installed openSUSE Leap 42.3, and seems bot matches working again for me.

**Comment by gdrewb-valve** [comment]
OK, I'm going to close this for now.
