### ISSUE TITLE
[Linux] Random crashes in Ranked & Unranked All Pick only (Matches with DotaPlus features)

### ISSUE THREAD

**Issue by d4ve89** [ValveSoftware/Dota-2#1419]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Dve89/029ff49ba22de20d147eead2de4f8245
My distro is Arch Linux and I am running dota in the default gl mode.
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes] (nvidia 390.42)
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Random crashes of the Dota2 client during **Ranked & Unranked All Pick Matches**. 
_NO issues when_: Playing **Bot Games**, playing **Turbo Mode** or watching via **DotaTV**, probably because these don't have DotaPlus features.

Maybe it has something to do with DotaPlus, since there are fewer DotaPlus features (no Hero Level or Hero Challenges) when playing Turbo.

stdout when the crash happens:
```
crash_20180316152208_1.dmp[14142]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180316152208_1.dmp
>>> Adding process 14141 for game ID 570
crash_20180316152208_1.dmp[14142]: Finished uploading minidump (out-of-process): success = yes
crash_20180316152208_1.dmp[14142]: response: Discarded=1
crash_20180316152208_1.dmp[14142]: file ''/tmp/dumps/crash_20180316152208_1.dmp'', upload yes: ''Discarded=1''
pid 14142 != 14141, skipping destruction (fork without exec?)
/home/david/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: Zeile 104: 13141 Speicherzugriffsfehler  (Speicherabzug geschrieben) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "", ProcID 13141 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
```
There are no unusual error messages before this, only the common _gameoverlayrenderer.so_ ELFCLASS error and the missing _librenderdoc.so_ that can be ignored. These are more like warnings that came up also before I had any issue.

Because my system has German Locale, one line has some German words. Translation of it:

`/home/david/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104: 13141 segmentation fault  (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

Here is an archive of my /tmp/dmps that were created when I crashed 6 times during one (!) game that I kept on reconnecting (stdout.txt included):

[crash_dumps_2018_03_16.zip](https://github.com/ValveSoftware/Dota-2/files/1819885/crash_dumps_2018_03_16.zip)

#### Steps for reproducing this issue:

1. Subscribe to DotaPlus (because I dont get the crashes when in game modes without)
2. Join a Ranked or Unranked Normal Game (no Turbo or Botgame)
3. Play for about 10 minutes until Dota2 freezes and crashes
4. Reconnect and crash again within the next 10 minutes

**Comment by MasterZapple** [comment]
Same problem.
My gist: https://gist.github.com/MasterZapple/3840961a9c8527f088fdfb26e7d1519e


This doesn't happen to me every game, but some games it's near-impossible to play. It just closes the game every 1-5minutes after reconnecting.

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are SIGSEGV coming from libclient.so (part of Dota 2).

**Comment by Eignar17** [comment]
I have the same problem at all times in the menu and in the game

**Comment by timosaure** [comment]
I can confirm the same issue. Started happening after I activated DotaPlus.

The timespan between crashes varies, but I couldn't determine an action yet that reliably causes the crash.

System: [gist](https://gist.github.com/timosaure/a7b5f620597a0e8c8ca81f01e9ef76dd)

I added the `-con_logfile` option and will try to supply that later, when the crashes happen again.

**Comment by CharlesDN** [comment]
Same issue on the latest version of MacOS(High Sierra 10.13.3). This issue does not exit after the first update for Dota Plus, but happens after the [second update on 15th of March](http://www.dota2.com/news/updates/38245/).

The first crash comes at ~12mins after the game started. No crash when playing bot game.

**Comment by grantnicholas** [comment]
Same problem on ubuntu 16.04 and I can confirm it did not happen with the first dotaplus update, but with the second update on March 15th 

Here is more information to help debugging (system information + some crash logs from /tmp/dumps):

https://gist.github.com/grantnicholas/cf43de329d85a07fb653fa8bdbedf9be

**Comment by eviltoast** [comment]
Hello, I have the same issue since one of the last updates (but not the first update that introduced Dota plus) - the game freezes for a few seconds and crashes after about 15 minutes into the game. Then the crashes become more frequent throughout the game. Tested in All Pick Normal game with Dota plus.
Crash log attached.




[crash_20180317163734_1.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/1821799/crash_20180317163734_1.dmp.zip)

sysinfo:
https://gist.github.com/eviltoast/f0f6061be61841574bb368f240aa41d2

**Comment by magist3r** [comment]
Same here on openSUSE 42.3 with DotaPlus activated. I think that hero quests causes this (I got crash only with Lanaya with specific quest).

**Comment by d4ve89** [comment]
> I think that hero quests causes this 

@magist3r this could explain why some people said on reddit that they don't have any issues. Some people said they got this issue in only a few games, while I have them always. Maybe we selected hero quests with issues, while others were lucky because they never picked problematic quests. Could you look into this @triage-valve ?

**Comment by gdrewb-valve** [comment]
The March 20 update made some changes in this area.  People that have posted here should update and retest.

**Comment by reportados123** [comment]
I'm still getting random crashes in ranked. Although somewhat less frequently it seems?

System information from steam: https://gist.github.com/reportados123/a046c1bd6b3877274b0ce825216a5f93
My distro is Arch Linux and I am running dota in the default gl mode.
Have you checked for system updates?: [Yes]
Are you using the latest stable video driver available for your system? [Yes] (nvidia 390.42)
Have you verified the game files?: [Yes]

I got 3 crashes on my second game of ranked.

[crash.zip](https://github.com/ValveSoftware/Dota-2/files/1831973/crash.zip)

**Comment by Hashwagon** [comment]
Just crashed 5 times in one ranked all pick game. Ubuntu 16.04 (KDE Neon). AMD 8350 CPU, AMD 7970 (Opensource Drivers).

**Comment by hashwagon** [comment]
Just crashed 5 times in one ranked all pick game. Ubuntu 16.04 (KDE Neon). AMD 8350 CPU, AMD 7970 (Opensource Drivers). Had to boot into Windows :'(

**Comment by d4ve89** [comment]
For me it's the same like reportados123. At first I thought it was fixed, because I finally was able to play 3 games without any trouble. Then it happened again on the fourth game (before March 20 patch, it happened to me in every game).

**Comment by kisak-valve** [comment]
For reference, @reportados123's second and third minidumps look similar to the earlier minidumps in this issue report. The first is a DUMP_REQUESTED in crashhandler.so.

**Comment by bemug** [comment]
Seem to happen only when activating a quest, since I tried both.
Tried with the Rubick assists quest.

Edit: Nevermind. It's not all the quests.

**Comment by AngryPenguinPL** [comment]
Hi.

I have this same issue on my Linux Mageia5.

Worth to add:

1. This problem started when I bought dota plus.
2. The game crashes many times, even several or a dozen times in one match (tested only unranked)
3. After few days, this issue just gone but today just appeared again.
4. For what I can see, this can be issue with "quest". Why?
I had a quest to kill creeps and ancients. Crash appeared only when I came to kill the ancients. After re-joining the game, the crash appeared randomly.
The next match, also the crash started when I killed ancients. After re-joining the game, the crash began to appear randomly.
Next few days without crash, but today crash appear again. When? When I started killing ancients for quest... and again re-joining to game and crash appeared randomly.

My steam info: https://gist.github.com/AngryPenguinPL/1ef4edad83d509e5ca1b912bfcca00bc

Crashes from /tmp/dump/ (only from today one match)
[crash_20180322152845_5.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/1838443/crash_20180322152845_5.dmp.zip)
7 crashes log from one match in one zip archive here.

**Comment by reportados123** [comment]
If I recall correctly, I also crashed when I chose the creeps/ancient quest after 20-30 mins on Arc Warden.

EDIT: I've been playing games (3 so far in ranked) without picking quests and so far I haven't experienced a crash.

**Comment by megatog615** [comment]
I have noticed it crashing when meeting quest requirements. I've been trying to get Wraith King to level 3 lately and was trying to get my 3 wins for the week, and it only appeared to crash while I had the creeps/ancient quest selected.

**Comment by reportados123** [comment]
Yup. Just got 3 more crashes from actually picking a quest and completing one. I was playing Shadow Demon and picked the "Get 3 / 6 / 9 Assists before the game reaches 15:00" and then as soon as I completed it (got the required assists by 15:00) and crashed. To be more precise, I was 2/2/2 and got my 3rd assist at 13:45 where I crashed shortly after. After that, I continually crashed every few mins (basically as I got more and more assists?)

I was played 4 games prior to this without picking any quests, and had no problems playing at all.

[crash2.zip](https://github.com/ValveSoftware/Dota-2/files/1844038/crash2.zip)

**Comment by AntouanK** [comment]
> This doesn't happen to me every game, but some games it's near-impossible to play. It just closes the game every 1-5minutes after reconnecting.

Exactly same problem. Happens on more than half of the games for the last few days.
Also joined dota plus since day 1.

Running Arch/i3wm , nvidia GTX 1070 and the default gl version. ( I see there's an option for Vulcan, would that bypass the crashes? )

How can we provide a crash log or something?
( my system information https://gist.github.com/AntouanK/e37eee62f0c4267691ded71defe3f296 )

**Comment by AngryPenguinPL** [comment]
>  I see there's an option for Vulcan, would that bypass the crashes? 

Maybe. Just try it and let us know.

> How can we provide a crash log or something?

After crash u can find dump in this location /tmp/dump/

**Comment by AntouanK** [comment]
It's a bit frustrating that we paid to get dota plus, and now we cannot play because of it :/ 

I want to try with vulcan, but on the other hand I don't want to ruin other's games ( or get abandons ).
Is there any feedback at all from valve on this issue?

I suppose this response is from valve? 
> The March 20 update made some changes in this area. People that have posted here should update and retest.


edit:
latest match where I got multiple crashes (as kotl) : https://www.dotabuff.com/matches/3797722841

**Comment by driebe** [comment]
Your system information

    Steam client version (build number or date): Mar 22 2018, at 16:58:48 (package 1521764535)
    Distribution (e.g. Ubuntu): Ubuntu 16.04
    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes, system up to date
    Hardinfo can be found in the attached TXT file

Systems details can be found at the end of the post.
Please describe your issue in as much detail as possible:

Game crashes, supposedly at random, during normal or ranked DOTA matches. This could be analyzed in match with the ID 3797693691 (I was Crystal Maiden) played on March 24, 2018.
Steps for reproducing this issue:

    As the crashes to desktop appear at random and neither the DOTA nor the Steam client returns a crash report, I cannot give an explanation on how to reproduce this error.

It may or may not be connected to the issues people see with the achievements...

**Comment by cuteredpwnda** [comment]
I can confirm I still have the same issue on Arch Linux. It was better after the 20th of March update, but Today I crashed two times out of a game and have to restart my PC once.

I also had the Ancient Creep/Creep farming challenge selected.

**Comment by AntouanK** [comment]
Some logs from my crashes today as Silencer https://www.opendota.com/matches/3799685211
https://drive.google.com/file/d/1v2AhY0Voglj0RN6fCV7Qyil-cfPuyZGZ/view?usp=sharing

Seems like they all end with `Hang watchdog not implemented for this platform!` if that means something.
_also, using vulkan makes no difference_ :(

**Comment by Zhouball** [comment]
Same issue on Ubuntu 17.10. Random game crashes with no crash report.

**Comment by eier7** [comment]
Crashes with the assist quest for Shadow Demon. Reveal heroes with dust and shadow poison quests worked, but when i play with the assist quest it freezes all the time.

**Comment by bemug** [comment]
This could be an issue with assist quests since I've only been able to reproduce the bug with these kind of quests.
Can anyone else confirm?

**Comment by AntouanK** [comment]
I had the problem with other quests as well.

**Comment by AngryPenguinPL** [comment]
> This could be an issue with assist quests since I've only been able to reproduce the bug with these kind of quests.
> Can anyone else confirm?

Few post above I wrote that I have a problem during the execution of quests. So YES, I can confirm it.

Today, I see more: crash start when my quest is done (for one star or more). Just when I reach the another star. So like today with drow ranger quest for killing creeps and ancients. So when I kill 9 ancients (0 crash) but when kill 10 crash instant appear. And more 11-19 ancients - 0 crash, when killing 20 - instant crash...

"Gib my money back :/"

**Comment by bemug** [comment]
That's strange because I've been crashing with rubick + assist quests even if I didn't get any assists.
Crashing every 2-3 min or so. Seems to be more frequent in late game.

**Comment by Krrl** [comment]
Seems to be related to assists quest with AA when AA ults after 15minutes

**Comment by AntouanK** [comment]
Any update on this issue?
I will get tired of playing ability draft eventually :P

**Comment by AngryPenguinPL** [comment]
Dota is constantly crashing. Today, two match, both with few crashed. Yesterday few matches, almost all with crash. One again when I make quest for killing ancients (crash when get star). Second when I need assit in kills (crash when I take one star and then crashing every new assist, until expired time to end my quest. After that 0 crash). Next match Viper (deal magic damage), one star (no crash). Next match assist in kill as shadow shaman (crash every assist). Next match kill with BKB jugger (no crash because I did not buy bkb :] )

Is any way to disable Dota plus? Or I need create new accout to play few matches without crashing? Any hope for refund money from dota plus?

**Comment by adrfantini** [comment]
I can also confirm this. Completely unplayable, Dota crashes every 5 minutes. Does not happen if no quest is selected. Assists quest with Jakiro triggers very frequent crashes.

**Comment by AntouanK** [comment]
Can anyone confirm that the bug is still occurring with the new update?

https://www.reddit.com/r/DotA2/comments/87ma2y/dota_2_update_main_client_march_27_2018/

**Comment by AngryPenguinPL** [comment]
`Can anyone confirm that the bug is still occurring with the new update?`

Nah. Shadow Shaman today and two crash in one match.

**Comment by eier7** [comment]
Still crashing

**Comment by AntouanK** [comment]
Ok, thank you.

I'm amazed that no one from valve comments on a critical bug like this one.
I hope it's not because they have no idea what causes it.

**Comment by eier7** [comment]
I'm running Arch, here is my dmesg
[173425.575566] dota2[25921]: segfault at 6e0000006f ip 0000006e0000006f sp 00007fff687782b0 error 14
[174540.806336] dota2[26330]: segfault at 6e0000006f ip 0000006e0000006f sp 00007fffd42a4c90 error 14
[175224.132910] dota2[26713]: segfault at 6e0000006f ip 0000006e0000006f sp 00007ffe3e1da180 error 14
[175937.851264] dota2[26827]: segfault at 6e0000006f ip 0000006e0000006f sp 00007ffe47dfebb0 error 14

I'm going to get banned if this continues

**Comment by AntouanK** [comment]
Stop playing all pick and ranked. Just play turbo or other modes. I play ability draft.
But yes, it's frustrating that no one answers from valve.

**Comment by adrfantini** [comment]
I got this in ranked RD with Jakiro with quests, but not in ranked RD with WW without quests. Maybe the quests are to blame?

**Comment by MasterZapple** [comment]
I had it a while ago with Arc doing the "get X creepkills and at least X ancient creep kills" quest and had nonstop crashes. A couple of days ago I played him again and was crashing again, I had the same quest selected.
I'm also guessing it's quest or hero+quest or hero specific.

**Comment by LDD19** [comment]
Looks like the  "get 3/6/9 assists before the game timer reaches 15:00" quest will crash your game at 15:00 minutes. I'm glad I'm not the only one having this problem. I haven't had any problems with other quests so far.

**Comment by eier7** [comment]
Did anyone else get a 14.1MB update a few hours ago?

**Comment by AntouanK** [comment]
@eier7  https://www.reddit.com/r/DotA2/comments/87y1t1/patch/

Must be adding the DAC stream link in the main view :/

**Comment by eier7** [comment]
Still freezing. Tried with the sd assist quest

**Comment by AntouanK** [comment]
I regret getting the 12 months of Dota plus. :/

If you have the monthly one, just cancel it and you should be able to play just fine ( I assume ).

**Comment by eier7** [comment]
I also have 12months :/

**Comment by AntouanK** [comment]
`7.12` out
https://www.reddit.com/r/DotA2/comments/881kk7/dota_712/
doubt it fixed the bug though.

**Comment by cluoma** [comment]
Still present in 7.12. Crashed 3 times playing Shadow Shaman in ranked doing the assist quest.

**Comment by Markussss** [comment]
Had this happen to me tonight, the first time I did an assist-quest. Crashed three times during one game. Forgot to copy the crashdumps and the messages in dmesg before restarting the system (as it was required to get back control of my computer from Steam and Dota). Here's a gist of my system information, since it's not as volatile as the crash dumps and dmesg messages: https://gist.github.com/Markussss/89d1db9225450c43a2a453fe81837a39

@kisak-valve, @gdrewb-valve can you update us on the status on this issue? When can we expect a fix?

**Comment by adrfantini** [comment]
It definitely is connected to quests. If I don't select quests, it does not crash.

**Comment by AntouanK** [comment]
@adrfantini How can you now select a quest?? It randoms one by default anyway.

**Comment by adrfantini** [comment]
@AntouanK uh? Not for me, I just do not select any of the three quests offered and close the quests tab by pressing the downward arrow. Just played with SS and SB last night with no problem.

**Comment by AntouanK** [comment]
when you are in-game, can you see the golden `+` logo at the top left corner?
IRC I didn't select any quest with kotl, but when I went in-game, I saw `0/3000` at the top left corner. It selected the arcane boots quest on it's own.
I'll try again later.

**Comment by adrfantini** [comment]
@AntouanK mh, I do not know, do you happen to have a screenshot of what you mean? I cannot play for a while so cannot check.

**Comment by AntouanK** [comment]
@adrfantini Watch this video at  8:00 https://www.twitch.tv/videos/244550151
He picks riki, and whithout touching the quests, in a few seconds it selects one on it's own.
And then you can see the `0/2` in-game so the quest is enabled.
![screenshot_2018-03-30_09-35-08](https://user-images.githubusercontent.com/4569111/38131129-c2209a6c-33fd-11e8-85ca-3987cf3f111b.png)

**Comment by AntouanK** [comment]
Played 3 games with WD yesterday. ( 2 unranked AP and 1 ranked AP ).
Didn't select any quest, but it chose on it's own. I actually completed two of them, so they were 100% selected by the game.
That said, it didn't crash at all.
No idea what that means.
Can anyone else play with WD and see if it crashes?

**Comment by adrfantini** [comment]
Can everybody confirm that it crashes with Assists quests only? Never had it crash with any other quest myself.

**Comment by AntouanK** [comment]
@adrfantini I really hope that's the case.
To add to my comment, those were the quests I got completed in the last 3 games

![screenshot_2018-03-31_09-38-02](https://user-images.githubusercontent.com/4569111/38161475-5a4999fa-34c7-11e8-91dc-4eadff7dd042.png)

**Comment by MasterZapple** [comment]
@adrfantini For me, it consistently crashed with the "get X cs and Y of those have to be ancients" quest on Arc Warden.

**Comment by LDD19** [comment]
@MasterZapple Can confirm, I'm crashing on both of those 2 quests. On the "get X cs and Y of those have to be ancients" quest my game crashes once I hit 15 ancient kills.

**Comment by Markussss** [comment]
I had a similar crash the other day when playing Vengeful Spirit, with the «Deal x/y/z damage to enemy heroes with Mask of Madness active» (cant remember the exact wording) quest active.

**Comment by gdrewb-valve** [comment]
The April 3 update had some changes which may affect this.

**Comment by chaosk** [comment]
No crashes with assist quest so far.

**Comment by gdrewb-valve** [comment]
Closing as this appears to be fixed.  For people still seeing crashes this issue and fix was specific to ranked/unranked all-pick with Dota Plus.  If you're still seeing crashes you likely have a different problem and will want to open a separate issue.
