### ISSUE TITLE
[Mac] Main Menu Unusable - Intel HD 3000 Integrated Graphics

### ISSUE THREAD

**Issue by TheJaymowShow** [ValveSoftware/Dota-2#142]
Main menu slow/unusable. Seen several reddit threads where users have the same issue. If I wait it out and get into an actual bot match, the game slows to the point where a Mac restart is the only solution.

Macbook Pro 13", early 2011
2.3 Ghz Intel i5
Intel HD 3000 Integrated Graphics
4 GB 1333 Mhz DDR3

**Comment by gdrewb-valve** [comment]
You have the 6/26 update?

**Comment by TheJaymowShow** [comment]
Yes. I'm validating the game now just to be sure, but I got the update yesterday.

**Comment by TheJaymowShow** [comment]
Validation just finished. All files are up to date.

**Comment by gdrewb-valve** [comment]
Closing as #9 is already open and still active.
