### ISSUE TITLE
Terrible Frame Spikes, especial at game end

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#1421]
#### Your system information

* System information from steam: https://gist.github.com/phoerious/b4f596f1ed10872aa56edd9f8f035088
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Recently I've been getting terrible frame spikes. I thought this might be related to #1339, but most of the time, my frame rate is stable at 60FPS (vsync enabled). Only sometimes when things happen (team fights etc.) and especially when the ancient blows up in the end, my game freezes for several seconds. At game end it can even so terrible, my whole operating system almost crashes.

Using Nvidia driver 390.42 on Arch Linux.

#### Steps for reproducing this issue:

1. Play a game
2. Blow up ancient
3. Wait a minute for your PC to recover

**Comment by kisak-valve** [comment]
Possibly related to #1417.

**Comment by gdrewb-valve** [comment]
If you could check memory usage that'd be interesting info.

**Comment by phoerious** [comment]
I'll check next time it happens.

**Comment by phoerious** [comment]
Update: I just had a game and while I didn't have the terrible breakdown at the end, I had occasional frame spikes. However, memory was pretty stable the whole time. I have 16GB RAM and Dota used 10% of that when I started and slowly climbed to 13.6% (and it didn't go back to 10% after the game). So there is most likely a memory leak somewhere, but it's probably not responsible for the FPS spikes.

**Comment by cuteredpwnda** [comment]
Today I experienced a problem with my FPS spiking while in the game and PC freezing.
Now after reading this, I realised that my RAM usage is like @phoerious, not too high.

Also wrote in #1417, Problem still persist.
my system info: https://gist.github.com/cuteredpwnda/3196aafeb66b03620f43f44a75d02fb7

**Comment by gdrewb-valve** [comment]
Is anybody still seeing the extreme frame spikes (system freezing level)?  Less severe frame rate variations happen on all platforms and we won't keep this open for that kind of thing.

**Comment by phoerious** [comment]
What I noticed is that the most severe lags maay to be connected with KDE's file indexer. When the baloo_file_extractor process is running, I see these long freezes on startup, on game end and sometimes in between when stuff is going on a lot more often. When I kill the process, I'm only getting these pesky micro freezes that exist on all platforms.

**Comment by gdrewb-valve** [comment]
I'm going to close this for now until we get more evidence of a Mac/Linux-specific problem.
