### ISSUE TITLE
[Linux] Playing Dark Willow crashes the game after Dota+ release

### ISSUE THREAD

**Issue by dervus** [ValveSoftware/Dota-2#1423]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/dervus/3ec7713bd757b9eab35ced249761b258
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

It seems to crash most often when somebody is getting killed, but not always. I also had one game on Dark Willow (out of 5 or so) without crashes at all. It actually looks like freezing, but it's likely due to core dump generation because coredumpctl shows a number of recent dumps for dota2.

I'm using OpenGL renderer. Haven't tried it with Vulkan yet.

#### Steps for reproducing this issue:

1. Queue for All Pick (both Normal and Ranked)
2. Pick Dark Willow
3. Play for some time

**Comment by gdrewb-valve** [comment]
Do you have any recent failure reports in your Steam system information?

**Comment by dervus** [comment]
Well, at the time of this report there was none as you can see.
I reinstalled the system recently, and I have new clean Steam installation as well. Not sure when I'll be able to test it again.
