### ISSUE TITLE
downloads occurring while playing dota 2 

### ISSUE THREAD

**Issue by lynx29** [ValveSoftware/Dota-2#1427]
#### Your system information

* System information: https://gist.github.com/lynx29/5aae64175abdf7d8592242038c81da2f
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When playing dota 2 there is a process that downloading something eating most of my data allocation for the day and sometimes experiencing ping spikes during game. This behavior happens after 3/21/2018 update .This is from wireshark log showing downloading is happening when playing. 

dst ip 220.242.1.25  GET /depot/570/chunk/b03ff2ee409cef60af61a84b84b36b5b9b4493c3? 
Full URI steam.apac.qtlglb.com/depot/570/chunk/b03ff2ee409cef60af61a84b84b36b5b9b4493c3?

dst ip 220.243.200.109 GET /depot/570/manifest/3228004818171658722/5?
Full URI steam.apac.qtlglb.com/depot/570/manifest/3228004818171658722/5?

This is just sample of many downloads happening. 

#### Steps for reproducing this issue:

1. play  dota 2 games
2. run wireshark
3. run iftop checking for any http or port 80 connection. ( take note the ip address )
4. from wireshark check for that ip address

**Comment by gdrewb-valve** [comment]
This doesn't look to be a Linux/Mac issue but I'm going to hold it open for a bit.

**Comment by AlejandroC90** [comment]
Is happening to me too, it consumes all my 2MB connection and I can't play, in my case it happens when there is a heavy team fight and then non stop from there, closing the game, opening it again and it fixes it until there is another heavy teamfight

**Comment by kisak-valve** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5417 is the start of the discussion of this issue and will be handled the same as this issue report.

**Comment by gdrewb-valve** [comment]
Closing in favor of the Steam issue as this isn't a Dota problem.
