### ISSUE TITLE
[macOS] Dota client not pulling in player/server variables

### ISSUE THREAD

**Issue by camclay** [ValveSoftware/Dota-2#1431]
#### Your system information
Computer Information:
    Manufacturer:  Apple
    Model:  Macmini7,1
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.12.6 (64 bit)

Video Card:
    Driver:  Intel Iris
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0xa2e
    Revision:  0x9
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 3200 x 1800
    Primary Display Size: 17.36" x 9.76" (19.88" diag)
                                            44.1cm x 24.8cm (50.5cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  952704 Mb
    Largest Free Hard Disk Block:  500770 Mb
    VR Headset: None detected

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes. I have also uninstalled and reinstalled the client twice. Once by deleting local files, and once by uninstalling from steam, and reinstalling.

#### Please describe your issue in as much detail as possible:

Client loads, but after it loads am presented with the base UI, and no variables are pulled in, and large sections of the client are empty, and am unable to join a game/press the Play Dota button.

#### Steps for reproducing this issue:

1. Open client, wait for it to be usable, encounter empty variables.
![screen shot 2018-03-28 at 9 53 30 pm](https://user-images.githubusercontent.com/8294484/38065998-ec28119e-32d3-11e8-8c29-d50a06c5c3be.png)
 
Didn't see any others reproducing this, can pm user name if needed.

Thanks,
Cam

**Comment by gdrewb-valve** [comment]
You don't appear to have a Steam connection, is the Steam client running normally?

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear to be a Dota issue.

**Comment by camclay** [comment]
Heya, issue is resolved when I went to play this evening.
Steam had an update, which had mac patches which may have resolved this issue.

I was online, and was able to access other games from Steam. I did not try a multiplayer game that evening. I had tried for about a week including restarting Steam, and verifying it was online, before posting.

Thanks for all the work you do!
