### ISSUE TITLE
I got a crash without any characteristic

### ISSUE THREAD

**Issue by TomatoFryEggs** [ValveSoftware/Dota-2#1434]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

System: MacOS 10.13.3 
MacBook Pro (Retina, 15-inch, Early 2013)

* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
When I playing games I get a force close suddenly.
This my system logs about the crash of dota2,
![](https://ws1.sinaimg.cn/large/006tKfTcly1fpvd8kqfg9j31kw0bk426.jpg)
#### Steps for reproducing this issue:
I can't reproducing it .
1. 
2. 
3.

**Comment by gdrewb-valve** [comment]
Can you post your full system information from Steam as a gist, as requested?  That will show if Dota caught any problems and logged them.  Without that we'll have to close this since we have no information on what happened and no repro.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
