### ISSUE TITLE
Dota freezes every 3 minutes or so during match

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1437]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/ceLoFaN/dc17c2adfca8b971462ac980a37d8d10
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

I must also add that this seemingly random freeze pattern happened on my other PC (Ryzen 1600 / GTX 1070 / same OS) last week, during 2 games, but didn't happen at all during the game I've played in between (all 3 were consecutive games). I haven't played for a few days back then and I thought it got fixed as it didn't happen again afterwards, but apparently not.

#### Please describe your issue in as much detail as possible:
The game randomly freezes and doesn't recover. My system takes up to 10 seconds to respond to my commands.

I'm not necessarily pushing buttons, I'm not making achievements/quests or whatever the Dota Plus stuff is called, although I have activated Dota Plus.

During the same game I switched from OpenGL to Vulkan and also restarted the PC, with the same results.

I haven't pinned the older matches where my game froze, but I have this latest one: https://www.opendota.com/matches/3810842176

```
apr 01 12:49:50 conserva systemd-coredump[8904]: Process 1700 (dota2) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 1700:
                                                 #0  0x0000002000000074 n/a (n/a)
apr 01 12:55:39 conserva systemd-coredump[10996]: Process 9812 (dota2) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 9812:
                                                  #0  0x0000002000000074 n/a (n/a)
apr 01 13:03:26 conserva systemd-coredump[13705]: Process 13137 (dota2) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 13137:
                                                  #0  0x0000002000000074 n/a (n/a)
```
Crash dump: https://gist.github.com/ceLoFaN/3bd9a6f190daf07d1be72fe9e7f1b29b

#### Steps for reproducing this issue:

1. Play a random ranked game.
2. Crash every 3 minutes or so.
3. Tank the abandon / reports and enjoy playing with toxic players for the next 10 matches.

~How can I provide better logs guys? There is no info on how to do this in the README, except for getting the System Informations.~ Nevermind, I read another issue where you pointed to /tmp/dumps. I still think this should be in the README though.

**Comment by kisak-valve** [comment]
Hello @ceLoFaN, can you put that minidump in an archive and drag and drop it to the comment box. It got mangled when it went into a gist.

**Comment by ghost** [comment]
Unfortunately I won't be able to do that until Thursday.

**Comment by gdrewb-valve** [comment]
Does this happen in hero demo or a local bot match?  If it's restricted to just DotaPlus-active games this is likely a duplicate of the other issues here since a DotaPlus quest is chosen for you in DotaPlus-active games.

**Comment by ghost** [comment]
I see. I just saw that Drow has the creeps/ancients kills quest which other people said is one of the quests that causes the crashes, so I assume I must have randomed the lucky one. That being said, sorry for opening a duplicate issue.

Could we get a temporary fix that allows us to disable quests?

Edit: Forgot to mention I played a ranked game with Mirana since, and at the end of the game it said I completed a quest.

**Comment by gdrewb-valve** [comment]
Overall control of quests is outside the scope of this bug tracker, but you can post at dev.dota2.com

**Comment by Eignar17** [comment]
@gdrewb-valve  is problem in steam and environment within the game

**Comment by Eignar17** [comment]
dota 2+ steam create bug

**Comment by gdrewb-valve** [comment]
The April 3 update should help with this.

**Comment by Eignar17** [comment]
@gdrewb-valve not fix error

**Comment by gdrewb-valve** [comment]
Whether it's fixed or not is going to depend on @ceLoFaN's feedback.  The crash information he posted above looks a lot like the problem that was addressed in the April 3 update.

**Comment by Eignar17** [comment]
new update not fix error

**Comment by ghost** [comment]
About the crashdump I promised, I noticed it was erased from the tmp directory a few days ago.
Anyway, I haven't encountered the error during the last week, although I haven't followed what quests I was being assigned.
As far as I'm concerned, this issue may be closed. Maybe @Eignar17 can provide some logs related to his problems.

**Comment by gdrewb-valve** [comment]
Eignar17 presumably has a different problem if he's still encountering it and yours is fixed, so he should open a separate issue and provide concrete information.  I'll go ahead and close this.
