### ISSUE TITLE
[Linux] OpenGL failing to launch. Segmentation Fault

### ISSUE THREAD

**Issue by Qfl3x** [ValveSoftware/Dota-2#1439]
#### Your system information
* [System Information](https://gist.github.com/IceColdMind/e81d0d28fc109d2d4dbbfbac34842dde)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I'm running Dota on Solus, and the game will crash after ~1second logo. [Terminal logs](https://gist.github.com/IceColdMind/bfdca7d64358c608d96818446a296354).

**Comment by AngryPenguinPL** [comment]
Maybe this is your problem:

> Steam Runtime Version:  Runtime disabled

Try run steam with steam-runtime enabled and then check dota2.

**Comment by gdrewb-valve** [comment]
You also might want to try older drivers if you're on a cutting-edge driver.  Checking with Vulkan could be interesting too to see if the problem is specific to OpenGL.

**Comment by Qfl3x** [comment]
I just rechecked with Vulkan, works wonderful. Will just contempt my self with it at the moment.  ( ~150 fps stable at max )

Enabling Steam-Runtime requires downloading some drivers. And I sadly don't have the space for it.

**Comment by danginsburg** [comment]
We'll close this issue for then.  You really should run with the Steam Runtime.  If you do ldd librendersystemgl.so without the steamrt in your path you might be able to see what library you are missing.  My wild guess would be it's libudev.so.0.  You can symlink libudev.so.0 -> libudev.so.1 if so and it will fix it. 

But it's meant to be run inside the steamrt, so you shouldn't really expect it to work :)  So I'll close this out.
