### ISSUE TITLE
[Mac] 11th player

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#144]
I was looking through the lobby list and decided to join a lobby. After clicking the "join" button, I had the lobby chat window appeared, along with a reconnect button. I clicked the reconnect button and found myself as the 11th player in the lobby.

![screenshot 2015-06-27 12 34 38](https://cloud.githubusercontent.com/assets/5674597/8393549/1e487a52-1cc9-11e5-8676-cf8b494715ef.png)

Maybe not a Mac/Linux issue...

**Comment by gdrewb-valve** [comment]
Not a platform issue.  I've passed this on to the larger team and it won't be tracked here.
