### ISSUE TITLE
Graphical artefacts after latest mesa update

### ISSUE THREAD

**Issue by Veske** [ValveSoftware/Dota-2#1441]
#### Your system information
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/Veske/62737d55cbbd29e9c41888535d7a7f5e
Mesa: ➜  ~ pacman -Q mesa
mesa 18.0.0-2
Game is running with -vulkan parameter

* Have you checked for system updates?: [Yes/No]: Yes
* Are you using the latest stable video driver available for your system? [Yes/No]: Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

The are strange graphical glitches in some scenarios. Happens with game ready screen for instance.
![screenshot from 2018-04-06 23-04-41](https://user-images.githubusercontent.com/5602603/38444042-7e1f60f6-39f6-11e8-85cb-458b159a0046.png)

#### Steps for reproducing this issue:

1. Que for game
2. Wait for game ready message
3. Observe result

**Comment by Veske** [comment]
Not sure if it's game issue or mesa issue, but reported it here just in case. Maybe you guys can have a look.

**Comment by gdrewb-valve** [comment]
We haven't seen other reports of issues like this so it seems likely to be a Mesa issue.  You'll want to report it with them also.

**Comment by danginsburg** [comment]
I see that you filed an issue with mesa, thanks.  Tracked also here, which is the right place for it: https://bugs.freedesktop.org/show_bug.cgi?id=105942

We'll keep it open here for now.

**Comment by danginsburg** [comment]
This has been bisected to a specific commit (ad11fc3571e025b22d9feed80a7f499665f7a255) over on https://bugs.freedesktop.org/show_bug.cgi?id=105942 so not a Dota 2 bug.  Closing here, check the mesa bug for any updates.

**Comment by Veske** [comment]
Thanks! Seems that they fixed this issue in a quick manner.
