### ISSUE TITLE
[BUG]  Dota freezes on using a map ping, in certain circumstances with a linux PC.

### ISSUE THREAD

**Issue by codedcosmos** [ValveSoftware/Dota-2#1443]
#### System information
Ryzen 7 1700
8 Gigs of DDR4 RAM
Asus Strix RX 470

OS: Arch Linux 64 bit
Steam and DOTA are latest version

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1700 Eight-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.15-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  X.Org Radeon RX 570 Series (POLARIS10 / DRM 3.23.0 / 4.15.15-1-zen, LLVM 6.0.0)
    Driver Version:  3.0 Mesa 18.0.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.78" x 10.55" (21.54" diag)
                                            47.7cm x 26.8cm (54.7cm diag)
    Primary VRAM: 4073 MB

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  7976 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  468427 Mb
    Largest Free Hard Disk Block:  250729 Mb
    VR Headset: None detected

Recent Failure Reports:

Have checked for system updates.
Using latest version of video driver, not 100% sure if it is stable variant, but should be reasonably stable as it works on every other game.
Have verified local game files

#### Issue
DOTA 2 freezes when pinging I'm on my way. It doesn't matter who pings it as long as the ping location is visible on the screen (not the map the main world area) the game freezes instantly.

#### Steps for reproducing this issue:
Steps can be accomplished by any player on the same team:
1) Alt, then select the ping I'm on my way.
2) If I am within the ping location crash

#### Notes
For some reason this does not occur when outside the ping location, it also does not occur with any other ping's which is very odd.

**Comment by gdrewb-valve** [comment]
Does it happen in bot games?  Is there a problem if you're the one pinging?  I just did a quick test on my Linux box where I started a bot game and did an on-my-way ping where I was and there weren't any issues.

**Comment by codedcosmos** [comment]
It does not appear to happen in bot games, at least not currently. Since yesterday there have been a xorg update and a dota 2 update so it may have been patched, but I never tested in in a bot match. I'm not willing to use that ping in real matches to test it at the moment because I am in LP because of it.

**Comment by codedcosmos** [comment]
Also to answer the second question, yes it did freeze when I was the one pinging. This is a weird bug to be sure.

**Comment by gdrewb-valve** [comment]
OK, we'll have to see if it keeps happening or not.

**Comment by codedcosmos** [comment]
OK, I think this issue might be closed, the bug no longer occurs in any instance. It appears to have disappeared as quickly as it came. My guess it was probably a weird issue with xorg. But not sure.

I will comment here again if it returns.

**Comment by kisak-valve** [comment]
Closing per the last comment.
