### ISSUE TITLE
【macOS】How clould I can enable vulkan for dota2 on mac?

### ISSUE THREAD

**Issue by TomatoFryEggs** [ValveSoftware/Dota-2#1447]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by gdrewb-valve** [comment]
There isn't any Vulkan support on macOS yet.

**Comment by TomatoFryEggs** [comment]
https://www.extremetech.com/gaming/264694-khronos-brings-vulkan-macos-ios-apple-refuses

@gdrewb-valve

**Comment by gdrewb-valve** [comment]
The support has not been released to the public yet.

**Comment by TomatoFryEggs** [comment]
When will you release it to the public？@gdrewb-valve

**Comment by gdrewb-valve** [comment]
I don't think there's any announced schedule.
