### ISSUE TITLE
[Linux] Purple and black checkerboard on screen while paused or dead if Vulkan is used

### ISSUE THREAD

**Issue by YabosMcGee** [ValveSoftware/Dota-2#1452]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/YabosMcGee/2497ed43afea1e23048d337991a36149
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When the game is paused, or my hero is dead, the main playable map area turns into a purple and black checkerboard pattern. I'm still able to move the camera around (playername tags still show through, and the mini-map still functions). The border also appears normally.

![dota_check_bug](https://user-images.githubusercontent.com/13436293/39839862-921e7b2c-53ab-11e8-91d3-098a24079c21.png)

This only happens when Vulkan is used. When I switch to OpenGL the checkerboard doesn't appear during pause/death. 

#### Steps for reproducing this issue:

1. Use "-vulkan" start option
2. Pause game or be dead
3. System uses Intel lib-mesa drivers (friend on same distro Manjaro with AMD Radeon drivers does not experience this issue)

**Comment by gdrewb-valve** [comment]
In the future you'll want to report Vulkan-specific issues at Dota-2-Vulkan.

**Comment by danginsburg** [comment]
Can you please run with -con_logfile and post the contents of steam_install_dir/steamapps/common/dota 2 beta/game/dota/console.log.  What you are seeing there is the error texture being chosen, it might help me triage it with the log.

**Comment by YabosMcGee** [comment]
> Can you please run with -con_logfile and post the contents of steam_install_dir/steamapps/common/dota 2 beta/game/dota/console.log. What you are seeing there is the error texture being chosen, it might help me triage it with the log.

@danginsburg Here is the log https://gist.github.com/YabosMcGee/44876eb047cc884fbe4c88e9f3d532de

**Comment by danginsburg** [comment]
Thanks, I have a fix for this issue.  This bug is Vulkan-specific, but not specific to your driver.  It happens at graphics settings level 1 so you can workaround for now by decreasing or increasing your graphics settings.  The fix will be in the next update though.
