### ISSUE TITLE
Big frame loss when viewing certain immortals on Fedora 28

### ISSUE THREAD

**Issue by Markussss** [ValveSoftware/Dota-2#1453]
* System information from steam: https://gist.github.com/Markussss/d7b0d25187cc3fe90e58a9c653c2ba39
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: No
* glxinfo: https://gist.github.com/Markussss/a29e7e967f8b2f33418da76651fe7e35
```
$ loginctl show-session 2 -p Type
Type=wayland
```

#### Please describe your issue in as much detail as possible:
One or several of the Immortals from the Immortal Treasure I causes lag/FPS-loss/whatever you want to call it on my Fedora 28, running Wayland on a Ryzen 5 2600X and R9 390.

When previewing the treasure in «View all»-mode, the whole game is notably slower, going from a pretty constant 120 FPS to around 50 FPS. It seems like it makes everything process slower, as I have to make larger physical movements with the mouse to move the on-screen mouse cursor than what is normal. It doesn't feel like 50 FPS, but more like 15 FPS. 

Youtube: https://www.youtube.com/watch?v=l0Gy2PQ3bTw
Dropbox: https://www.dropbox.com/s/9gcrz7mwqxfjuin/Screencast%20from%2005-10-2018%2003%3A05%3A44%20PM.webm?dl=0

I took a video of this and uploaded it to Dropbox and YouTube to show this in effect. I'm not sure what FPS the recording is running at, but pay attention to the FPS-counter in the top right corner while I move through the immortals. Going left, I stay at each immortal for about 5 seconds, while only staying for about 3 seconds going right.

For your convenience, here is an overview of the ish FPS for each immortal:

| Immortal  | ish FPS |
| ------------- | ------------- |
| Emblem of the Crystal Echelon  | 120  |
| Codicil of the Veiled ones  | 110  |
| Golden Edict of Shadows  | 90  |
| Glare of the Tyrant  | 80  |
| Savage Mettle  | 70  |
| Edict of Shadows  | 60  |
| Shatterblast Core  | 55  |
| Span of Sorrow  | 50  |
| Mournful Reverie  | 50  |
| Emerald Conquest  | 55  |

From this, it looks like there is something going on with either Span of Sorrow or Mournful Reverie, but I don't know how to find out if it's a trouble with the game or with my computer.

**Comment by gdrewb-valve** [comment]
You should verify your Dota install just to eliminate that as a variable.  If you add -con_logfile to your launch options and run Dota and go through the immortals, then exit there'll be a console.log file in your Dota install directories.  Can you attach that as a gist here?

**Comment by gdrewb-valve** [comment]
Also are you using OpenGL or Vulkan?

**Comment by Markussss** [comment]
@gdrewb-valve 
The validation came back OK.

console.log: https://gist.github.com/Markussss/4394693cbb72ca03d2ad9895ea3a6d8d

I am using OpenGL.

**Comment by danginsburg** [comment]
I presume what you are commenting about here is the long stutters towards the end of the video and not the FPS counter, which looks reasonable to me.

Given the framerate is not fluctuating I'm not sure if this is something dota itself is doing as opposed to something with the compositor or windowing system.

**Comment by gdrewb-valve** [comment]
The fact that the frame rate is lower when looking at the left side of the figures and is higher when looking at the right is something that happens on all platforms and the larger team will take a look.  I think that's the only thing you're reporting here, correct?  If so I'll close this out.

**Comment by gdrewb-valve** [comment]
It's also not connected to the Immortals themselves, just how they're being displayed in that piece of the UI.

**Comment by Markussss** [comment]
@danginsburg No, the long stutters towards the end is a result of the recording software acting weird. The problem is the left side of the immortals effectively halving framerate, compared to the right side. The framerate is also halved in zoomed out mode.

@gdrewb-valve Yes, that is the only thing I'm reporting here. I just assumed it was Linux specific, as I did not notice any posts about it on r/DotA2 on reddit or on the dev forums.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
