### ISSUE TITLE
Dota 2 Vive controller orientation appears to have a swapped axis

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Dota-2#1455]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/kisak-valve/a23f7dec7f06618bd7c8a919986a5378
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? No (Bleeding edge)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
The orientation of the Vive controllers does not match the physical device in Dota 2 VR mode. When I hold a controller pointed away from myself, with the touchpad facing upward, the rendered model's orientation is pointed upwards with the touchpad on the far side.

Tested with Gentoo and Ubuntu 18.04

#### Steps for reproducing this issue:

1. Run Dota 2 VR mode with a Vive on linux.

**Comment by danginsburg** [comment]
I have fixed this issue.  It should be fixed in the next Dota update.

**Comment by kisak-valve** [comment]
Closing confirmed fixed. Thanks a bunch!
