### ISSUE TITLE
[linux][alsa] "underrun occured" are back

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1459]
While playing dota2, I get tons of the following log msg:
ALSA lib /root/nyanlinux/src/alsa-lib-1.1.6/src/pcm/pcm.c:8424:(snd_pcm_recover) underrun occurred
linux amd-staging-next (4.16)
alsa-lib 1.1.6 (pinned)
SDL_AUDIODRIVER=alsa
Realtek ALC892/HDA ATI SB
I also have the mic from my USB webcam used for steam voice.

**Comment by sylware** [comment]
I did narrow it down: dmix at default 48000Hz, buffer underrun occurs, at 44100 Hz(dmix or native direct) no buffer underrun occurs.
Something seems wrong with dota2 resampler.

**Comment by sylware** [comment]
the buffer underrun seems gone

**Comment by kisak-valve** [comment]
Closing per the last comment.
