### ISSUE TITLE
[General] Team Composition not working

### ISSUE THREAD

**Issue by kinosang** [ValveSoftware/Dota-2#1462]
Sorry for posting general issue here, but the dev forum does not work well (see #1461).

The Team Composition in the strategy screen shows nothing since some months ago, it seems caused by the Dota Plus feature.

Here's some thread talking about this issue:

https://www.reddit.com/r/DotA2/comments/86t45j/team_composition_feature_is_broken_since_dota/
https://steamcommunity.com/app/570/discussions/0/1698293703769889810/
https://steamcommunity.com/app/570/discussions/0/2828702372996377870/

I've tried to contact the support, but they ask me to submit the issue in the Steam Community or dev.dota2.com.

No one gives any response in the community and the dev forum prevent me from submitting anything.

Sorry again for bothering.

**Comment by gdrewb-valve** [comment]
I've passed this on but there won't be any status here.
