### ISSUE TITLE
Establishing connection Dota 2 problems

### ISSUE THREAD

**Issue by FaresJandali** [ValveSoftware/Dota-2#1463]
Hello,

So for the last 2 weeks I have been having trouble establishing connection to Dota 2 servers at specific times of the day, I live In Lebanon and I mostly play on Europe servers. My issue seems to appear mostly at night times and specially from 12 am to 3 am, I figured that I could test my internet before connecting to a match by making a lobby in LUX, in order to avoid getting banned for x minutes, anyway Im hoping someone could help me understand if the issue is on my behalf or the servers behalf or my internet service provider behalf. If its required I could post the information written in my console as im trying to connect, I don't think my laptop specifications are important because it's probably a connection problem, ill post the information im getting in my console and see what happens, thank you !

[Client] Sending connect to =[A:1:687491083:10017]
[SteamNetSockets] Selecting fra#432 (162.254.197.165:27056) as backup #1 for connection 1536669711.  Ping = 78+3=81 (front+back=total).
[Client] Received S2C_CHALLENGE [863144364 auth 3] from =[A:1:687491083:10017]
[Client] Sending C2S_CONNECT [47 protocol 863144364 auth 3] to =[A:1:687491083:10017]
[Client] Received S2C_CONNECTION from =[A:1:687491083:10017] [addons:'', SNP=0]
[Client] CL:  Connected to '=[A:1:687491083:10017]'
[SignonState] CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
[Client] CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
[EngineServiceManager] SwitchToLoop levelload requested:  id [2] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[Client] LoadingDisplay changed from NONE to PRE_LOADING (map="")
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( levelload : success )
[SignonState] CL:  Permit INetchannel::Transmit()
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [2] addons []
[Client] CL:  CNetworkGameClient already exists for connection to '=[A:1:687491083:10017]'
[Client] CL:  connection to '=[A:1:687491083:10017]' already started
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #1 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #2 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #3 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #4 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #5 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #6 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #7 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #8 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #9 restarting, just received packet 0
[Networking]       client =[A:1:687491083:10017[0]:  high packet loss detected flow incoming:    0ms latency,     9/   19 dropped (47.4%)
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #10 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #11 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #12 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #13 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #14 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #15 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #16 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #17 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #18 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #19 restarting, just received packet 0
[Networking]       client =[A:1:687491083:10017[0]:  high packet loss detected flow incoming:    0ms latency,    10/   20 dropped (50.0%)
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #20 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #21 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #22 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #23 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #24 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #25 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #26 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #27 restarting, just received packet 0
[Console] Deleting lobby data from disk.
Telling Steam it is safe to update the app
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #28 restarting, just received packet 0
[SplitPacket]       client =[A:1:687491083:10017[0]:  split packet seq #29 restarting, just received packet 0
[Networking] #GameUI_Disconnect_ServerShutdown[NetSteamConn] Closing Steam Net Connection on socket 'client' to =[A:1:687491083:10017], handle 30002 (0 (null))
[Networking] Summary of connection to [A:1:687491083:10017]:
[Networking]     End-to-end connection: closed by remote host, reason code 1069.  (#GameUI_Disconnect_ServerShutdown)
[Networking]         Remote host is in data center 'lux'
[Networking]         Current rates:
[Networking]             Sent: 159.8 pkts/sec   5.0 K/sec
[Networking]             Recv:  21.8 pkts/sec  22.4 K/sec
[Networking]             Ping:61ms    Max latency variance: 14.0ms
[Networking]             Quality: 95.6%  (Dropped:4.39%  WeirdSeq:0.00%)
[Networking]             Est avail bandwidth: 97656.3KB/s  
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:      5,404 pkts         175,069 bytes
[Networking]                 Recv:        653 pkts         675,202 bytes
[Networking]                 Recv w seq:        650 pkts
[Networking]                 Dropped   :         41 pkts   5.93%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (600 total samples)
[Networking]                   0-25  :    0    0%
[Networking]                  25-50  :    0    0%
[Networking]                  50-75  :  162   27%
[Networking]                  75-100 :  126   21%
[Networking]                 100-125 :  174   29%
[Networking]                 125-150 :   87   15%
[Networking]                 150-200 :   39    7%
[Networking]                 200-300 :   12    2%
[Networking]                   300+  :    0    0%
[Networking]             Ping distribution:
[Networking]                  5% of pings <=   61ms
[Networking]                 50% of pings <=  102ms
[Networking]                 75% of pings <=  124ms
[Networking]                 95% of pings <=  162ms
[Networking]                 98% of pings <=  196ms
[Networking]             Connection quality histogram: (6 measurement intervals)
[Networking]                  100  :    0    0%   (All packets received in order)
[Networking]                  99+  :    0    0%
[Networking]                 97-99 :    0    0%
[Networking]                 95-97 :    3   50%
[Networking]                 90-95 :    2   33%
[Networking]                 75-90 :    1   17%
[Networking]                 50-75 :    0    0%
[Networking]                  <50  :    0    0%
[Networking]                 dead  :    0    0%   (Expected to receive something but didn't)
[Networking]             Connection quality distribution:
[Networking]                 50% of intervals >=  94%
[Networking]                 75% of intervals >=  93%
[Networking]             Latency variance histogram: (553 total measurements)
[Networking]                  <1  :     29    5%
[Networking]                 1-2  :     16    3%
[Networking]                 2-5  :    122   22%
[Networking]                 5-10 :    346   63%
[Networking]                10-20 :     35    6%
[Networking]                 >20  :      5    1%
[Networking]             TX Speed histogram: (32 total samples)
[Networking]                  0 - 16 KB/s:   32  100%
[Networking]                 16 - 32 KB/s:    0    0%
[Networking]                 32 - 64 KB/s:    0    0%
[Networking]                64 - 128 KB/s:    0    0%
[Networking]               128 - 256 KB/s:    0    0%
[Networking]               256 - 512 KB/s:    0    0%
[Networking]              512 - 1024 KB/s:    0    0%
[Networking]                   1024+ KB/s:    0    0%
[Networking]             Transmit speed distribution:
[Networking]                  5% of speeds <=    0 KB/s
[Networking]                 50% of speeds <=    0 KB/s
[Networking]                 75% of speeds <=    0 KB/s
[Networking]                 95% of speeds <=    0 KB/s
[Networking]             RX Speed histogram: (32 total samples)
[Networking]                  0 - 16 KB/s:   32  100%
[Networking]                 16 - 32 KB/s:    0    0%
[Networking]                 32 - 64 KB/s:    0    0%
[Networking]                64 - 128 KB/s:    0    0%
[Networking]               128 - 256 KB/s:    0    0%
[Networking]               256 - 512 KB/s:    0    0%
[Networking]              512 - 1024 KB/s:    0    0%
[Networking]                   1024+ KB/s:    0    0%
[Networking]             Receive speed distribution:
[Networking]                  5% of speeds <=    0 KB/s
[Networking]                 50% of speeds <=    0 KB/s
[Networking]                 75% of speeds <=    0 KB/s
[Networking]                 95% of speeds <=    0 KB/s
[Networking]         Rate stats received from remote host 12.6s ago:
[Networking]             Sent:  22.0 pkts/sec  22.5 K/sec
[Networking]             Recv: 166.1 pkts/sec   6.3 K/sec
[Networking]             Ping:162ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         No lifetime stats received from remote host
[Networking]     Primary router: lux#145 (146.66.154.23:27045)  Ping = 62+0=62 (front+back=total)
[Networking]         Current rates:
[Networking]             Sent: 158.5 pkts/sec   6.3 K/sec
[Networking]             Recv:  21.6 pkts/sec  22.1 K/sec
[Networking]             Ping:62ms    Max latency variance: 14.1ms
[Networking]             Quality: 95.6%  (Dropped:4.39%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:      5,419 pkts         229,489 bytes
[Networking]                 Recv:        667 pkts         677,658 bytes
[Networking]                 Recv w seq:        653 pkts
[Networking]                 Dropped   :         41 pkts   5.91%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (18 total samples)
[Networking]                   0-25  :    0    0%
[Networking]                  25-50  :    0    0%
[Networking]                  50-75  :   17   94%
[Networking]                  75-100 :    0    0%
[Networking]                 100-125 :    1    6%
[Networking]                 125-150 :    0    0%
[Networking]                 150-200 :    0    0%
[Networking]                 200-300 :    0    0%
[Networking]                   300+  :    0    0%
[Networking]             Ping distribution:
[Networking]                 50% of pings <=   62ms
[Networking]                 75% of pings <=   65ms
[Networking]             Connection quality histogram: (6 measurement intervals)
[Networking]                  100  :    0    0%   (All packets received in order)
[Networking]                  99+  :    0    0%
[Networking]                 97-99 :    0    0%
[Networking]                 95-97 :    2   33%
[Networking]                 90-95 :    4   67%
[Networking]                 75-90 :    0    0%
[Networking]                 50-75 :    0    0%
[Networking]                  <50  :    0    0%
[Networking]                 dead  :    0    0%   (Expected to receive something but didn't)
[Networking]             Connection quality distribution:
[Networking]                 50% of intervals >=  94%
[Networking]                 75% of intervals >=  91%
[Networking]             Latency variance histogram: (553 total measurements)
[Networking]                  <1  :     29    5%
[Networking]                 1-2  :     16    3%
[Networking]                 2-5  :    122   22%
[Networking]                 5-10 :    346   63%
[Networking]                10-20 :     35    6%
[Networking]                 >20  :      5    1%
[Networking]             No connection transmit speed distribution available.  (0 measurement intervals)
[Networking]             No connection recieve speed distribution available.  (0 measurement intervals)
[Networking]         Rate stats received from remote host 12.0s ago:
[Networking]             Sent:  22.7 pkts/sec  23.6 K/sec
[Networking]             Recv: 166.0 pkts/sec   6.7 K/sec
[Networking]             Ping:61ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         No lifetime stats received from remote host
[Networking]     Backup router: fra#432 (162.254.197.165:27056)  Ping = 78+3=81 (front+back=total)
[Networking]     
[Client] CL:  Server disconnected: 69: #GameUI_Disconnect_ServerShutdown
Disconnection during connection phase. Sign-on state: 2. Disconnect reason: 69.
[HostStateManager] CHostStateMgr::QueueNewRequest( Idle (levelload), 3 )
[NetSteamConn] Tried to send ad-hoc to address =[A:1:687491083:10017], but address is not in list of steam net connections!
[HostStateManager] Discarding pending request 'Remote Connect (=[A:1:687491083:10017]), 2'
[Client] CL:  Disconnecting from server: #GameUI_Disconnect_Request_HSIdle
[EngineServiceManager] SwitchToLoop levelload requested:  id [3] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[Client] LoadingDisplay changed from PRE_LOADING to NONE (map="")
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[Client] LoadingDisplay changed from NONE to LOADING (map="")
[HostStateManager] Idle (levelload)
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [3] addons []
[Server] CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[Server] SV:  maxplayers set to 1
Initializing script VM...
...done

**Comment by gdrewb-valve** [comment]
This isn't the right place to get general networking help, that'd be dev.dota2.com

If you believe this is a Mac/Linux specific problem please post your system information.

**Comment by zpostfacto** [comment]
What is your friend ID?  I'll dig through logs and see if I can understand the packet loss better.

One thing: you might try setting "cl_use_snp 1".  This switches the networking to use a new reliability layer that's in beta.  (We are probably going to start rolling this out soon.)  It *should* be a lot better dealing with really bad packet loss like you are getting.  Give it a try and let me know!

**Comment by FaresJandali** [comment]
233284121 that's my friend ID, I will let you know if the setting you mentioned helped tonight. Thank you

**Comment by FaresJandali** [comment]
I would like to note something that is when it works sometimes to join the lobby and start the game at night time ( after many tries )  ( when the issue is happening ) I don't have packet loss in game or ping issues neither while spectating games, as it seems only when i'm trying to connect to games or creating a lobby game.

**Comment by gdrewb-valve** [comment]
Closing as this issue is out of scope for this tracker.  You're welcome to continue passing information back and forth.

**Comment by FaresJandali** [comment]
wow that setting actually worked, thank you so much!
when I set it to 1 I can connect when I turn it back to 0 it doesnt let me. thank you guys.
