### ISSUE TITLE
Scaled Content - Steam Browser

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/Dota-2#1464]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5531.
@annacmr posted on 2018-06-15T22:15:52:

#### System Information

* Steam API: v018
* Distribution: Ubuntu 16.04.3 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Detailed Issue:

Hello y'all! Although my computer is very simple I can play DoTA 2 perfectly fine. I have this issue a long time, but it now started to bother me: my steam browser inside DoTA 2 is expected to be at a 100% scale, but it's actually at 125-150% for some contents! 

![screen](https://user-images.githubusercontent.com/13593456/41491533-2a1c2f1e-70e9-11e8-9702-1e2c7e1a1ba1.png)

Is there anything I can do? [This post](https://github.com/ValveSoftware/Dota-2/issues/1178) says this issue was resolved in June, 2017, but the problem still remains for me. Thank you!

**Comment by gdrewb-valve** [comment]
As mentioned in #1178 this is something that we'll need to pass by the Steam team so there may not be much feedback here.

**Comment by resendeacm** [comment]
Thank you @kisak-valve and @gdrewb-valve, I appreciate the help. :)

**Comment by gdrewb-valve** [comment]
Do you have multiple monitors or just one?  What is the monitor resolution and what mode and screen resolution are you playing Dota in?

**Comment by resendeacm** [comment]
I use a monitor attached to my notebook. I play using the "Desktop-Friendly Fullscreen" mode, and my monitor resolution is the same as my screen: 1360 x 768 (AR: 16:9).

![screen](https://user-images.githubusercontent.com/13593456/41598295-4c509ca4-73bf-11e8-8d4b-bdc47feee394.png)

![valve](https://user-images.githubusercontent.com/13593456/41598224-1a186f32-73bf-11e8-834d-8ecb3bec07db.png)

**Comment by gdrewb-valve** [comment]
What are the physical dimensions of your monitor?  The image you attached shows it being identified as a 7" monitor.  You can run "xrandr" in a terminal and the first few lines will show monitor dimension info. If your monitor is really being detected as something with a 7" diagonal then 1360x768 is high DPI and it's expected that web elements will be scaled and fixing the monitor detection should fix the problem.

**Comment by annacmr** [comment]
Hi @gdrewb-valve, what do you mean by "fix the monitor detection"?

anna@atlas:~$ xrandr
Screen 0: minimum 8 x 8, current 1360 x 768, maximum 32767 x 32767
eDP1 connected (normal left inverted right x axis y axis)
   1366x768      60.00 +  48.01  
   1360x768      59.80    59.96  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   680x384       60.00  
   640x360       60.00  
HDMI1 connected primary 1360x768+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1360x768      60.02*+
   1920x1080     60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

**Comment by resendeacm** [comment]
Hi @gdrewb-valve, what do you mean by "fix the monitor detection"?

![valve2](https://user-images.githubusercontent.com/13593456/41628886-1f5d91f0-7416-11e8-8ab7-1ad60e5c23e9.png)

**Comment by gdrewb-valve** [comment]
The output says that the monitor is 160mm x 90mm in size.  I'm assuming that's wrong so that's the part that needs to be fixed.  Dota can't do anything better when given incorrect information.

As to how you would fix that I have no idea, somehow the monitor information is wrong.  You could ask on a forum about your distribution.  For example here is a thread discussing a very similar issue on Arch. https://bbs.archlinux.org/viewtopic.php?id=171374

It looks like some people suggest using DVI instead of HDMI.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear to be a Dota issue.
