### ISSUE TITLE
Audio captions are just a bunch of ???s

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1465]
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist]https://gist.github.com/tjackson/1ad7aed880d4279f4b8aef5c3c4d1ed9
I don't know if it's relevant to this issue but this is a dual GPU system using reverse Prime so the modesetting driver is involved too.

* Have you checked for system updates?: [Yes/No]
Yes

* Are you using the latest stable video driver available for your system? [Yes/No]
Debian Jessie's long-lived branch for Nvidia is probably a little outdated

* Have you verified the game files?: [Yes/No]
Yes

I'm using the client in English and audio captions don't seem to work anymore. It just shows a bunch of question marks across the whole screen. Turning them off makes the popup disappear.

#### Steps for reproducing this issue:

1. Turn on audio captions in settings
2. Demo a hero
3. Observe the question marks

Maybe relevant: $LANG is en_US.UTF-8 but LC_COLLATE=C

**Comment by gdrewb-valve** [comment]
This was working the past but broke recently?  Does it happen on all heroes you demo?  Can you list some specific ones that you've tried so that we can test the same ones?

**Comment by gdrewb-valve** [comment]
We found an issue that is likely what you're hitting, the next release will have a fix.

**Comment by ghost** [comment]
Thanks!

Yeah, I demoed a bunch of heroes and it happens on all of them. Last I tested it was working about a month ago, maybe two.

**Comment by gdrewb-valve** [comment]
I believe the fix was in the June 18 update, does this still happen for you?

**Comment by ghost** [comment]
Awesome, it's fixed now with a 374.9 MB update and then some other tiny update.
