### ISSUE TITLE
[macOS] Steam High CPU usage after game

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1467]
#### System information

* System information from steam https://gist.github.com/RankoR/271dc17ca4ec24cd2f7044028650def8 (old config; the only difference is system version — 10.13.5).
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Steam utilizes about 10-20% of CPU (i7-7700K) even if when IDLE even if Dota 2 is **not** running after any game and Dota lags (game and UI).

Reproduces in every game mode in OpenGL/MoltenVK.

#### Steps for reproducing this issue:

1. Run Dota 2, play a game in any mode (tested in Ranked/Turbo).
2. UI is lagging (for instance, game mode right side menu). Huge FPS drops in game. High CPU utilization by Steam (see attached screenshot).
3. If you restart Dota, it still lags. The only fix is to completely restart Steam after every played game.

[Screenshot](https://kek.gg/i/5MjXgw.png)

**Comment by gdrewb-valve** [comment]
This sounds like a Steam issue and not a Dota issue?  I'll assign to a Steam dev but there may not be much status here.

**Comment by RankoR** [comment]
Seems to be fixed, at least did not happen last few days.

**Comment by gdrewb-valve** [comment]
OK, closing for now.
