### ISSUE TITLE
[macOS] Unable to restore minimized game with MoltenVK 

### ISSUE THREAD

**Issue by RankoR** [ValveSoftware/Dota-2#1468]
#### Your system information

* System information from steam https://gist.github.com/RankoR/271dc17ca4ec24cd2f7044028650def8 (current version is 10.13.5 actually)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

As I'm using 4K display, the only available mode is exclusive fullscreen. And the only way to switch windows is Cmd+H, as Cmd+Tab does not work in this case.

Cmd+H works fine, window minimizes, but then I'm not able to restore it back — it hangs WindowServer for about half a minute and then I see black screen with Umbrella cursor and Dock over it. The only way to restore the game is to force quit and then relaunch.

OpenGL version works fine.

**Comment by kisak-valve** [comment]
Hello @RankoR, the first half of this issue is already being tracked at #1326, so we'll only track the second half in this issue report.

**Comment by RankoR** [comment]
@kisak-valve yep, the second half is main one :)

**Comment by gdrewb-valve** [comment]
For the future Vulkan bugs should be filed in Dota-2-Vulkan.

**Comment by danginsburg** [comment]
I have a fix for this bug, it should make it in to the next Dota 2 Update.

**Comment by danginsburg** [comment]
This fix shipped in today's update.  You should be able to CMD+H in exclusive fullscreen and restore it back without issue now on a retina display.  Please test and confirm.

**Comment by danginsburg** [comment]
Closing since I believe this is fixed.
