### ISSUE TITLE
[Mac] Lobby list "sorted by" arrow is not at correct position

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#147]
This is fine:
![screenshot 2015-06-27 16 04 55](https://cloud.githubusercontent.com/assets/5674597/8394321/6d8a9d94-1ce6-11e5-92ec-0377566c7145.png)
But not this one:
![screenshot 2015-06-27 16 04 59](https://cloud.githubusercontent.com/assets/5674597/8394322/6d9bce48-1ce6-11e5-80ad-9c0f8a0eee2a.png)

**Comment by gdrewb-valve** [comment]
What resolution is this at?  I'm assuming it will happen on all platforms at low res.

**Comment by SsnL** [comment]
1440x900

**Comment by gdrewb-valve** [comment]
That's not particularly low res.  What changed in between the two screenshots?  Did other text on that line update or something?  Was it just "Installed" vs. "Not Installed?"

**Comment by SsnL** [comment]
The column width didn't change so I doubt that text was the issue. The only difference I can think of was just sorting in increasing and decreasing orders.

**Comment by SsnL** [comment]
Btw, it seems that only "connection" column has this issue.

**Comment by gdrewb-valve** [comment]
This looks to occur on Windows also so I have passed this on to the larger team.
