### ISSUE TITLE
LINUX - Can't find or watch match

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1472]
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/admshao/775f42764242a714d999a03faaa9564b
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

An hour ago or so, just finished my match. Tried to find match again and the "find match" button just went grey. Can't watch any match either.
"Check your Internet connection. Unable to download the network configuration from CDN."

I can find or watch match just fine on Windows.

**Comment by kisak-valve** [comment]
Also reported at https://github.com/ValveSoftware/steam-for-linux/issues/5545. Opting out of Steam's beta client should workaround the issue.

**Comment by admshao** [comment]
i was just about to close and comment i found this work around as i would post this on steam-for-linux tracker. Sorry i didn't check there before.
