### ISSUE TITLE
[Linux] Steam beta client makes in-game region servers unreachable

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#1474]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Pharmasolin/f796925a8fe662ead39f88511d5e3b5e): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Steam beta client makes in-game region servers unreachable, if restore regular steam client, servers become reachable and the game is playable.

#### Steps for reproducing this issue:

1. Change steam version to steam beta
2. Open dota2 game
3. Press "play dota" and try to choose some regional servers to open servers frame, you will see that non of them are reachable.

**Comment by Pharmasolin** [comment]
It seems it is steam dev team fail, noticed similar reports
https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1727575977552752049/

**Comment by kisak-valve** [comment]
Also reported at https://github.com/ValveSoftware/steam-for-linux/issues/5545.

**Comment by gdrewb-valve** [comment]
Closing in favor of the Steam issue.
