### ISSUE TITLE
Localhost lobby game crashes on Linux 

### ISSUE THREAD

**Issue by ellysh** [ValveSoftware/Dota-2#1475]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/ellysh/726f82c5e19e2c22e9c56e502a6eead4
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Expected behavior:
Lobby game with default bots and the "local host" option of the "server location" filed starts correctly.

Actual behavior:
After the picking stage, Dota 2 client crashes without any error messages.

Notes:
Lobby game with the "EU West" option of the "server location" starts properly.
The issue happens after todays minor game client update (30.06.2018). Yesterday it has worked well.

#### Steps for reproducing this issue:

1. Launch Dota 2 client.
2. Create a lobby.
3. Choose the "local host" option of the "server location" filed.
4. Check "Fill empty slots with bots".
5. Press OK button to start a game.

**Comment by gdrewb-valve** [comment]
There was another update released on June 30 that addressed something like this, are you still seeing issues?

**Comment by ellysh** [comment]
Thank you for information. Now it works well.
