### ISSUE TITLE
[Linux] Cannot ping the matchmaking servers within the client?

### ISSUE THREAD

**Issue by d4ve89** [ValveSoftware/Dota-2#1476]
#### Your system information
I am running dota2 on an Arch Linux machine with the newest kernel, newest drivers etc, and am using the beta release of the Steam runtime.
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Dve89/164e692380219a67f30368b6edbd5338
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I cannot connect to the matchmaking servers within the dota 2 client in Linux. When I press "Find Match", the button gets greyed out. When I try to select the match making region, all servers are shown as "Ping: Calculating". Somehow the client cannot connect to the match making servers?

#### Steps for reproducing this issue:

1. Start Dota
2a. Press "Play" -> Press "Find Match" (any mode). The button will get greyed out, but the game will not start queueing. In order to be able to do something again, you have to quit Dota.
2b. Press "Play" -> Press "REGIONS". The connection to all servers in the Region Selection window are shown as "Ping: Calculating". 
2c. Press "Arcade". You will notice that there are no lobbies shown in the list. I can browse through normal Dota Lobbies though, and I can also browse and use all features of the Battle Pass, see the status of my friends.
2d. When I try to watch a game of my friends or from the "WATCH" tab, it says: "Check your Internet connection. Unable to download the network configuration from CDN".

I thought this might be an internet connection / port issue of my router, but there are no problems on other machines in my network. When I use "ping lux.valve.net" or other matchmaking servers from the same machine, there is no problem:
```
$ ping lux.valve.net
PING lux.valve.net (146.66.152.2) 56(84) bytes of data.
64 bytes from fw0.lux.valve.net (146.66.152.2): icmp_seq=1 ttl=57 time=19.7 ms
```

Also, when I start dota on the same machine (and in the same network) but within a WINE environment, the game will connect to the servers correctly and shows me the ping to there (and I am able to queue for games). Thus, I think it cannot be a firewall issue.

**Comment by kisak-valve** [comment]
Hello @Dve89, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5545. For the time being you can work around this issue by switching to Steam's stable client.

Closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/5545 (and also a duplicate of #1474 and https://github.com/ValveSoftware/csgo-osx-linux/issues/1678).
