### ISSUE TITLE
Lost connection to steam in Dotaclient while Steamclient is connected and working

### ISSUE THREAD

**Issue by LouisBoulas** [ValveSoftware/Dota-2#1478]
#### Your system information

* https://gist.github.com/LouisBoulas/b7873f8dea8565a1d5674360b132758a
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

The steam client works fine and as expected, shows that I am connected and online. I can also see my entire friends list. When I open Dota2, the dota2 client says "Lost connection to Steam." My in game profile and friends list does not load in game. I am unable to do anything in the Dota2 client from seeing who's online to finding a game.

#### Steps for reproducing this issue:

1. I am unsure how to reproduce this issue. Dota was working fine for me a couple hours ago and now I can't do anything with it. I have attached a couple images showcasing the problem. Any help would be much appreciated.. Steam support has been unable to help me. Note: i have also tried logging into a different steam account on the same laptop and have the exact same problem. Not sure if the problem is on my end or Dota2 end.

2 screenshots:
Dota2 Client --
<img width="1280" alt="screen shot 2018-07-10 at 11 20 42 pm" src="https://user-images.githubusercontent.com/17864021/42553138-956bafec-84ad-11e8-8e46-06a7aab82e27.png">

Steam client --
<img width="317" alt="screen shot 2018-07-10 at 11 21 59 pm" src="https://user-images.githubusercontent.com/17864021/42553149-a3c7274c-84ad-11e8-9877-3c60ab1425df.png">

**Comment by riffus** [comment]
Not sure what causes this corruption/malfunction but it appears that **every** game -either online or offline is affected by latest update for Steam Beta Client on some (if not all) *nix OSes. I'm on macOS High Sierra and checked every log, open port, process etc. but ended up with only two clues.

1. libsystem_network.dylib throws an nw_path_close_fd warning, hinting possible library access issue?
2. Most of the games gracefully work like they're in offline mode, no access to even local saved data, but a few of them popped up a warning that they require Steam as if the client is not running, thus crashing or simply closing itself.

**What I tried**
I opted out from Steam Beta and reverted back to regular client. Same problem.

**What worked for me**
I moved/renamed Steam Client data folder (~\Library\Application Support\Steam on macOS) and let Steam Client download itself again. After logging in, I pointed Steam Client to my non-default Steam Library, let it discover my installed games and now I'm back online.

**What I didn't try**
After fixing my issue and going back online, I stayed out of Steam Beta. Therefore I can't say if Beta Client will work as intended after this fix, but regular client does.

Hope this helps.

**Comment by zpostfacto** [comment]
Is there anything in the Dota console log that might give a clue?  (Can you attach it?)

**Comment by zpostfacto** [comment]
Same bug as #1285

**Comment by riffus** [comment]
@fletcherdvalve Unfortunately no (didn't save previous logs), but I checked them thoroughly and didn't spot any clear sign of process attachment or network issues. Also clientport didn't work, so it may seem like the same issue as #1285 but probably not as network layer access seems fine (although I can't say that I'm 100% sure).

Probably not even related to Dota, but Steam Client ;)

**Comment by zpostfacto** [comment]
Oh, sorry I just now grasped the bit where you opted back out of the steam client beta and it didn't fix it.  So reproducing it would be a lot of work.

**Comment by riffus** [comment]
@fletcherdvalve Actually, give me a couple minutes. I didn't delete my old data (in case), let me see if I encounter the same issue when I replace the folder with working one.

**Comment by riffus** [comment]
@fletcherdvalve Alright, here's my how to guide for reproducing this issue :)

1. Made sure clean, working non-beta release Steam Client doesn't have this issue.
2. Quit client and moved back suspected Steam folder.
3. Launched client, logged in.
4. Launched Dota, works perfectly, connects to coordinator etc.
5. Opted in for Steam Beta, relaunched.
6. Issue re-appeared (Dota 2 console log attached below).
7. Opted out from Steam Beta, relaunched. Issue still there.

[dota_console_log.txt](https://github.com/ValveSoftware/Dota-2/files/2185275/dota_console_log.txt)

Moved clean installation folder back, and it's working again, didn't want to corrupt that folder too with Beta but I assume it will.

One side note: Beta client launches Dota 2 way slower than public client, also launches way slower than yesterday (before client update). Didn't time it but feels like 2x-2.5x slower.

**Comment by riffus** [comment]
@fletcherdvalve Silly me, I just noticed "no ISteamClient interface" warning in the console logs...

**Comment by zpostfacto** [comment]
Yeah it's failing to get all of the interfaces it needs, so init failed for some reason.

Thanks!  We'll see if we can reproduce.

**Comment by LouisBoulas** [comment]
Thank you very much, got it back up in working. I did also have the problem where it would launch dota2 at a much slower rate.

I did it a bit differently but it worked in the end. instead of renaming the steam file i just got rid of it. 
1. opted out of beta
2. deleted steam
3. reinstalled steam

thanks again for the help guys ^^
