### ISSUE TITLE
Linux - Crashing Steam and Dota2 during start up

### ISSUE THREAD

**Issue by ralacerda** [ValveSoftware/Dota-2#1479]
* System information
https://gist.github.com/RenatoLacerda92/bbb3ec75ddd203e80f8670048440cedb

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Issue:

While dota is loading up, before the "Main" page, steam crashes, and dota2 soon follows. I tried both opt-in and opt-out of steam client beta.

It worked fine after the first update of the day ("Dota plus summer"), bug started after the second update.

**Comment by kisak-valve** [comment]
Hello @RenatoLacerda92, this issue is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5564 and can be worked around by opting out of Steam's beta client.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where Steam could crash when running Steamworks-enabled games, or where Steamworks functionality wouldn't work properly in the game." in the [2018-07-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) Steam client beta update.
