### ISSUE TITLE
Completely crash/freezing OS on loading screen after today's update

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [ValveSoftware/Dota-2#1480]
#### Your system information
Opensuse Leap 15.0 x64 (all up to date) Nvidia, KDE, Xrender for compositer, Allow apps to block compositing
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:
1. Had no problem prior to update but crashed twice consistently
2. Queue a rank game after the update on 12th July.
3. Game crashes on VS/loading screen and need hard reset OS.

**Comment by kisak-valve** [comment]
Hello @GreatBigWhiteWorld, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, if there you can find any CrashIDs or minidumps (commonly found in `/tmp/dump/`) related to this issue, lease include them as well.

**Comment by gdrewb-valve** [comment]
Apps can't freeze up the system so this typically indicates a problem in a system component such as a graphics driver (possibly triggered by Dota but still a bug in the driver).  You might also want to check this out with NVIDIA or your distro.

**Comment by GreatBigWhiteWorld** [comment]
I solved this by changing vulkan to opengl.
