### ISSUE TITLE
Can't watch replay 

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1481]
Hi.

I can't watch replay. Downloading a replay from a professional match or from match my friend then I can't watch it. Just download --> decompresing --> watch and nothing happens. Still see only watch button and can click on it multipe times but without any success.

but when download my own replay, then when I click on watch -  my replay is displayed.

**So issue occurs only on replays of other players. My own work.** 
I think it was a good idea to check if the problem also occurs on Windows with OpenGL.

Tested on OpenGL render. Linux box (for now only on poor laptop, I can check on the PC only after the weekend).

Quick info:
Kernel: 4.14.50
Filesystem: ext4
Display server: X - x11-server-xorg-1.19.5
OpenGL: via Mesa 17.3.9
Steam overlay: enabled
Steam-runtime: latest - enabled

Temporary hardware/software details: https://gist.github.com/AngryPenguinPL/9425cf4bf8a0bb091523ac7fa5577b03

**Comment by danginsburg** [comment]
This happens on all platforms and is being fixed.  I won't track this further here since this tracker is specifically for Linux/macOS issues.  Thanks.
