### ISSUE TITLE
Extremely low frame rate on Debian Sid

### ISSUE THREAD

**Issue by DoctorApparatus** [ValveSoftware/Dota-2#1482]
#### Your system information
[gist]https://gist.github.com/DoctorApparatus/390cc0e74c8a4d255be16c120b3fcc14
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After I upgraded to Debian Sid the frame rate in Dota 2 dropped to maybe 2fps?
The Drivers are working with other benchmarking software but every Steam game doesn't seem to work.

#### Steps for reproducing this issue:

1. Install Debian Stretch
2. Install Steam + Drivers
3. Upgrade to Sid

**Comment by kisak-valve** [comment]
Hello @DoctorApparatus, `Driver: VMware, Inc. llvmpipe (LLVM 6.0, 128 bits)` in your system information indicates that you are using llvmpipe, mesa's faster software renderer. This means that your system isn't configured to use a real video card and you should re-install your video driver. You can use `glxinfo | grep OpenGL` from `mesa-utils` to quickly check which opengl driver stack is in use.

**Comment by DoctorApparatus** [comment]
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 6.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 18.1.3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

Is the following output. That is quite weird since I installed the latest propietary driver via:
sudo apt-get install nvidia-driver after adding "non-free" to the sources.list in /etc/apt/

**Comment by kisak-valve** [comment]
Closing as low framerate is expected when not using a GPU for 3D rendering.
