### ISSUE TITLE
quitting dota 2 leading to crash - not responding [application not closing properly - need to force quit every time]

### ISSUE THREAD

**Issue by rohanharikr** [ValveSoftware/Dota-2#1484]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro9,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.13.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 11.77" x 10.16" (15.51" diag)
                                            29.9cm x 25.8cm (39.4cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  10240 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  475656 Mb
    Largest Free Hard Disk Block:  158319 Mb
    VR Headset: None detected

* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Quit Dota 2 > Dota 2 Crashes

**Comment by ghost** [comment]
Another symptom is the huge lag spikes it creates across the system. (for me)

**Comment by glubsy** [comment]
Can you post your system logs when the crash happens? It's been happening for me too for the past few days, both OpenGL and Vulkan. 

Also, have you tried waiting for the game to close itself? Sometimes it takes a few minutes while it generates the crash dump and uploads it. 

In my system logs, it seems to be related to libvideo.so, and It does a coredump. I might open a new ticket.

**Comment by Bednar87** [comment]
same here: https://gist.github.com/Bednar87/67c71c99966a6a6b1b7ae93328df8d99

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.4-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76" (24.02" diag)
                                            51.8cm x 32.4cm (61.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT2020

Memory:
    RAM:  7938 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Total Hard Disk Space Available:  104481 Mb
    Largest Free Hard Disk Block:  25897 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by Metisav** [comment]
im have problem with thath too

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:          Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.65-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2
    Driver Version:  4.4.0 NVIDIA 340.107
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xe22
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.04" x 11.26" (22.95" diag)
                                            50.9cm x 28.6cm (58.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7896 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Total Hard Disk Space Available:  225724 Mb
    Largest Free Hard Disk Block:  73329 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by ghost** [comment]
Is there any progress on this? It's pretty annoying to wait 1 minute for my PC to recover everytime I close Dota.

**Comment by glubsy** [comment]
You guys did not post any of your system logs, so I'll cross reference my thread from the Vulkan repo: https://github.com/ValveSoftware/Dota-2-Vulkan/issues/279

If you don't post any relevant information, don't expect a prompt magical fix.

**Comment by zeroedout** [comment]
Still happening, still annoying. Any updates? I'm happy to post my logs too, but I doubt it would be helpful at this point.

**Comment by vmavromatis** [comment]
Still happening, do you guys have enough logs at this point or need me to post mine?

**Comment by rohanharikr** [comment]
Fixed!

**Comment by glubsy** [comment]
Yes, I can also confirm this problem is not happening anymore. Thanks developers! (would love to learn a bit about what caused it too)
