### ISSUE TITLE
Cant use fcitx input method in game

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1485]
#### Your system information
Linux linuxhost 4.17.5-1-MANJARO #1 SMP PREEMPT Sun Jul 8 19:26:38 UTC 2018 x86_64 GNU/Linux

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.17.7-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.1.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x416
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.39" x 7.48" (15.31" diag)
                                            34.0cm x 19.0cm (38.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15927 Mb

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Total Hard Disk Space Available:  400135 Mb
    Largest Free Hard Disk Block:  127971 Mb
    VR Headset: None detected

Recent Failure Reports:

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

 I can use fcitx normally on other application(such as chromium).

**Comment by gdrewb-valve** [comment]
Dota uses the IME support from SDL so this is a feature request for SDL, assigning to SDL dev.

**Comment by gdrewb-valve** [comment]
It appears SDL should support fcitx so it's unclear why it wouldn't work, hopefully the SDL dev will have some thoughts.

**Comment by ghost** [comment]
@gdrewb-valve one week age.It's work,recently it brokened,BTW I use steam beta version.

**Comment by gdrewb-valve** [comment]
Did it stop working at any particular time or update?  Was it a Dota update or a Steam update?  If you use the non-beta Steam version does that help?  If you turn off the Steam overlay does that help?

**Comment by ghost** [comment]
non-beta Steam version doesn't help.
turn off Steam overlay doesn't help.

**Comment by ghost** [comment]
command line I used.
primusrun %command% -perfectworld -language schinese

**Comment by ghost** [comment]
Sorry my bad,I forget to check /etc/enviroment.It's may be changed by myself at some time.now it worked.
