### ISSUE TITLE
Screen Resolution Bug In Display Settings

### ISSUE THREAD

**Issue by rohanharikr** [ValveSoftware/Dota-2#1486]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
Manufacturer: Apple
Model: MacBookPro9,2
Form Factor: Laptop
No Touch Input Detected

Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
CPU Family: 0x6
CPU Model: 0x3a
CPU Stepping: 0x9
CPU Type: 0x0
Speed: 2500 Mhz
4 logical processors
2 physical processors
HyperThreading: Supported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

Operating System Version:
MacOS 10.13.5 (64 bit)

Video Card:
Driver: Intel HD Graphics 4000
Driver Version: 1.2
Driver Date: 0 0 0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x8086
DeviceID: 0x166
Revision: 0x9
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 11.77" x 10.16" (15.51" diag)
29.9cm x 25.8cm (39.4cm diag)
Primary VRAM: 0 MB

Memory:
RAM: 10240 Mb

Miscellaneous:
UI Language: English
Media Type: DVD
Total Hard Disk Space Available: 475656 Mb
Largest Free Hard Disk Block: 158319 Mb
VR Headset: None detected

* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

What was expected to happen: Changed resolution from (example) 1080p to 720p. Restart Dota, see the changed resolution (720p) in display settings. 

What did happen: Changed resolution from (example) 1080p to 720p. Restart Dota, the resolution option in the display settings indicates 1080p (although I made the change to 720p). There is just an error in displaying the resolution although the resolution is 720p, but shows up as 1080p. 

#### Steps for reproducing this issue:

1. Change resolution (example from 1080p to 720p)
2. Restart Dota
3. Resolution in display settings tab remains (1080p) the same although the resolution has changed (720p - what I wanted).

**Comment by kisak-valve** [comment]
Possible duplicate of https://github.com/ValveSoftware/Dota-2/issues/1287#issuecomment-327026176.

**Comment by rohanharikr** [comment]
@kisak-valve The resolution is correct, only what is displayed in the display settings tab is wrong.

**Comment by danginsburg** [comment]
Thanks, I have a fix for this issue coming in a future Dota update.

**Comment by rohanharikr** [comment]
@danginsburg Cool!

**Comment by danginsburg** [comment]
Update has shipped.  Please reopen if you still see the issue.

**Comment by rohanharikr** [comment]
@danginsburg Ok
