### ISSUE TITLE
Not able to play because no update is available

### ISSUE THREAD

**Issue by gabrielboliveira** [ValveSoftware/Dota-2#1488]
#### Your system information

* System information from steam: https://gist.github.com/gabrielboliveira/6a871a76b34ca004b22831839b1afd10
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
On macOS and Linux, we can't play because it says the game is not up to date, however on Steam it doesn't have any update.

#### Steps for reproducing this issue:

1. Open Steam
2. Try to play Dota2
3. Can't play because no update is available

![image](https://user-images.githubusercontent.com/11093090/43492714-9dccb0f6-9500-11e8-9afc-211b4f07d843.png)

**Comment by danginsburg** [comment]
This was happening on all platforms.  It should be fixed now.  If not, you can try Steam Settings -> Downloads -> Clear Download Cache.
