### ISSUE TITLE
[LINUX] Dota 2 crashes on previous match screen - Vulkan

### ISSUE THREAD

**Issue by mewt666** [ValveSoftware/Dota-2#1490]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/mewt666/e320da50af75740789aecaab94e1d055): 
* Have you checked for system updates?: [Yes/No] - Yes
* Are you using the latest stable video driver available for your system? [Yes/No] - Yes
* Have you verified the game files?: [Yes/No] - Yes

#### Please describe your issue in as much detail as possible:
Expected: Game does not crash
Actual: Game freezes at the end of a match or when viewing past match result.

#### Steps for reproducing this issue:

1. Enable vulkan using the -vulkan flag startup commands 
2. Start Dota 2
3. Click on Profile
4. Click on match in `Previous Match performance`
5. Game crashes, usually not completing the drawing of ranks below hero portraits

Issue does not present itself when -vulkan is removed from startup commands. Game freezes and uses 2/4 cores to 100% usage.

**Comment by kisak-valve** [comment]
Hello @mewt666, since this issue does not happen with the opengl backend, let's track this issue in the Dota-2-Vulkan issue tracker at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/273.
