### ISSUE TITLE
New Rubick item crashes linux client while using Vulkan. 

### ISSUE THREAD

**Issue by u83rmensch** [ValveSoftware/Dota-2#1491]
#### Your system information

kubuntu 18.04  x64
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
NVIDIA Corporation GK104 [GeForce GTX 770] (rev a1)
NVIDIA Driver Version: 396.51 

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

the new item for Rubick seems to crash the game for linux users running via Vulkan. The same crash does not happen when loading via OpenGL.

#### Steps for reproducing this issue:

1. Open Dota 2
2. Be on Vulkan opposed to OpenGL
3. Look at the new item for Rubick, "Crux of Perplex", either while previewing the Trove Carafe 2018 chest or looking at items for Ruick in the "Heroes" tab. 
4. system locks up. 

I switched between TTy 1 and 2 switching between an init 5 session and an init 3 session, upon going back to the init 5 session the game seems to have closed and I get an error message that the graphics server was restarted. this may just be limited to my distro and DE)

**Comment by amitbar05** [comment]
happens to me to.

**Your system information**
Ubuntu 16.04 x64
Intel® Xeon(R) CPU X5450 @ 3.00GHz × 8 
NVIDIA Corporation GK206 [GeForce GTX 960]
NVIDIA Driver Version: 396.51

**Comment by danginsburg** [comment]
Thanks.  I have a fix for this, it will be in a future Dota 2 update.  It does only impact Vulkan, present on both Windows and Linux.

**Comment by danginsburg** [comment]
The latest Dota 2 Update should fix this.  I'll close this out, please comment if you still see it and I can reopen.
