### ISSUE TITLE
New Hero introduction crash

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1493]
hi,
So I just launched dota2 to have a look at the new hero and apparently what ever you did for his introduction makes the nvidia driver seriously unhappy. First the screen was black for a prolonged time and the mouse stopped moving. The WM also stopped responding, but I was able to switch to a tty after some delay. I then checked dmesg and saw a bunch of nvidia driver errors. At some point the new hero started talking and I was able to switch back to a seriously distorted main menu.

[dmesg.txt](https://github.com/ValveSoftware/Dota-2/files/2320375/dmesg.txt)

According to https://docs.nvidia.com/deploy/xid-errors/index.html that is a bunch GPU stopped processing, GPU memory page fault and Graphics Engine Exceptions. There are also some segfaults in libclient.so in there. 

I am aware that you can't fix the nvidia driver, but most of the xid errors are also marked as potentially a user app error.

[minidump.zip](https://github.com/ValveSoftware/Dota-2/files/2320385/minidump.zip)

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/Turmfalke2/c2b4c2c912db6bd903b2edb4caa9726c

* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] No (going to update)
* Have you verified the game files?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
The game to launch without any issues.

Prior to rebooting I was able to reproduce it, now it appears to work just fine. Presumably there was still some bad state in nvidia driver/card.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libclient.so.

**Comment by danginsburg** [comment]
Did updating to the latest NVIDIA driver fix it?  So far I've been unable to reproduce the issue.

**Comment by Turmfalke2** [comment]
Well no, or yes. I wasn't able to reproduce this after rebooting. It was 100% reproducible prior to the reboot and have had zero issues since rebooting.  I suspect that what every bugged out store a bad state in the graphic driver.

Unless you can see something that obviously wrong or could be improved by better error handling around the segfault in libclient.so I think it is fine to close this and blame nvidia.


later that evening I did update my kernel&nvidia driver, but I don't think that changed anything.
