### ISSUE TITLE
[Linux] Game eats all memory and freezes after some time of playing

### ISSUE THREAD

**Issue by marshall2056** [ValveSoftware/Dota-2#1495]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [https://gist.github.com/marshall2056/b476da4425b56c819b6603b543271993](https://gist.github.com/marshall2056/b476da4425b56c819b6603b543271993): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After some time of playing the game, game itself starts using too much memory, in my case it can go up to 32GB ram. 
From beginning of the game, game will be laggy but will continue to work, after some time, it can take up to two or three games for game to start lagging very bad after which I will loose the sound (sound will king of repeat itself) and than game and the system will stop responding;

While game is about to die it can be two outcomes:
1. Game will freeze, and I will need to hard reset my laptop, or;
2. System will kill process;

dmesg output when system kills the game:
Out of memory: Kill process 7782 (dota2) score 915 or sacrifice child
Killed process 7782 (dota2) total-vm:37274152kB, anon-rss:30292072kB, file-rss:0kB, shmem-rss:1015212kB

#### Steps for reproducing this issue:

1. Just play the game (I am usually playing turbo)
2. Sometimes if I do change graphics settings it can speed up the process

**Comment by kisak-valve** [comment]
Hello @marshall2056, you may have better success with a newer version of mesa.

**Comment by marshall2056** [comment]
Hello, thank you for such fast response, tho please note that mesa drivers were installed couple of months ago and game itself was running just fine until couple of days ago, which brings me to the game itself. 

Even if mesa is older (but for my system is last and stable), does not explain why game itself is taking 32GB after 1 hour of playing?

EDIT:
I have done test game run, game itself while started take around 6GB memory, 10 minutes after it's still playable but it takes 18GB memory, after 15ish minutes it's at 30GB memory usage.

It seems it's that dota has some memory leak.

Please let me know if I can gather up some kind of logs for you.

**Comment by marshall2056** [comment]
UPDATE: 
I have installed mesa 18.1.5 after which issue still persist, BUT later I have installed mesa-utils which seems to fix the problem, now the game runs around with 700MB RAM stable usage.

So the fix should be not only mesa drivers but mesa-utils package.

NOTE: I did not try mesa-utils package with older version of mesa.

Case can be closed as fixed.
