### ISSUE TITLE
[Mac][El Capitan] Game crashes every time on launch. 

### ISSUE THREAD

**Issue by nascob** [ValveSoftware/Dota-2#15]
As a developer - I am running El Cap Build 1. 
I just installed Dota 2 Reborn, but it seems to crash straight after the UI shows up on the screen.

Crashlog - http://pastebin.com/HmyY2MLk

I know it's still in beta  - just thought this might be helpful.

**Comment by mstg** [comment]
Yes, happens to me too. El Capitan build 1

**Comment by mstg** [comment]
Looks like it is a env variable issue. If you create /Users/USER/Library/Application Support and symlink ~/Library/Application Support/Steam to it, it shows an another error message (which is probably because of the symlink)

**Comment by bxio** [comment]
Just updated to El Capitan Beta 2, Still crashes after a few seconds.

**Comment by vladdaneliuc** [comment]
+1 crash on El Capitan beta 2

**Comment by gdrewb-valve** [comment]
Can you try with the 6/25 update?

**Comment by gu3st** [comment]
Doesn't crash on launch on one of my computers running Beta 2.  Will test further functionality.

**Comment by atanasbozhkov** [comment]
Same here - crash has been fixed.

**Comment by mstg** [comment]
Fixed now! Thanks!
