### ISSUE TITLE
[Linux/radeonsi] Minimap and ground textures flickers

### ISSUE THREAD

**Issue by DarkDefender** [ValveSoftware/Dota-2#150]
The icons on the minimap flickers for me in Dota2 Reborn.

If I enable normals in the video settings, some parts of the ground also flickers.

To demonstrate the issue I have uploaded two avi files here:
https://github.com/DarkDefender/dota2_reborn_issue
Notice that the mini map flickers in both cases. I have tried to disable every video option to see if that helps, but it does not.

I also had the health bars above units flicker and become corrupted sometimes.

After playing some more I also see a problem with the hero portraits in that the vertices on the face of the models seems to get small incorrect offsets. On Pudge for example, this face looks like it's make of jelly as the verts waves around a bit. It kinda looks like the old PS1 games where there were interpolation issues because the vertex position were stored as integers (IIRC).

System info:

```
Processor Information:

    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:

    Network Speed:    

Operating System Version:

    "NAME=Gentoo" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.0-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11799000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2015-01-06   

Video Card:

    Driver:  X.Org Gallium 0.4 on AMD HAWAII
    Driver Version:  3.0 Mesa 10.7.0-devel (git-c97105e)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                            51,8cm x 32,4cm  (61,0cm diag)
    Primary VRAM Not Detected

Sound card:

    Audio device: ICE1724 - multitrack 

Memory:

    RAM:  11970 Mb

Miscellaneous:

    UI Language:  English
    LANG:  sv_SE.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  1288894 Mb

Installed software:

Recent Failure Reports:

```

**Comment by ChristophHaag** [comment]
There are several bugs with textures and flickering open...

Here's a video I made with mesa git and HD 7970M (pitcairn, SI): https://www.youtube.com/watch?v=oafFg3GZGSk

Flickering things: Shadows, the bright red color in health bars (!!), corrupted (?) textures

**Comment by sylware** [comment]
I'm getting exactly the same gfx glitches on tahiti xt (SI)
with a state of the art 3D radeon stack (my bug is #160)

**Comment by danginsburg** [comment]
Are you guys seeing these issues with older versions of mesa?  For example, I have not seen it on mesa 10.3.2 or 10.5.8.  Can you test one of those and see if the problem still occurs?  If it does not, can you file a bug with mesa instead of here?

**Comment by DarkDefender** [comment]
Seems like this is indeed a problem with newer versions of mesa. After downgrading the xorg stack so I could have mesa 10.6.1 installed, the problems seems to be gone.
I'll open a mesa bug ticket once I've tried the git version once again.

I'll edit this to include a link to it.

**Comment by sylware** [comment]
If you confirm the bug, the AMD devs probably won't do anything: they'll ask
you to bisect and find the guilty commits.
Since we need hours to compile that c++ brain damaged llvm... I hope we get
lucky.
If confirmed, we could coordinate ourself to bisect the bug.

**Comment by danginsburg** [comment]
Please post a linke to the mesa bug here so I can keep track of it.  Thanks!

**Comment by DarkDefender** [comment]
With the latest git stack the problem appears again.

@sylware it seems like LLVM is not to blame in this case. I tried to only downgrade LLVM to 3.6.1 and keep everything else on git master. While it did help a bit (the flickering just happened less frequently) it didn't resolve anything.

So unless there is some unholy combination with LLVM and mesa that triggers this bug, I guess that the problem is introduced somewhere between mesa 10.6.1 and the git version.

I'll try to bisect some more before I file out a mesa bug ticket

**Comment by sylware** [comment]
Whatever is culprit, you must keep llvm and mesa relatively in sync: That will
force you to configure/compile again that horrifying llvm if you are too much
back in time. Hope we get lucky.

**Comment by DarkDefender** [comment]
I've found the commit the broke it and created a ticket here:
https://bugs.freedesktop.org/show_bug.cgi?id=91193

**Comment by sylware** [comment]
On Thu, Jul 02, 2015 at 09:55:08AM -0700, DarkDefender wrote:
> I've found the commit the broke it and created a ticket here:
> https://bugs.freedesktop.org/show_bug.cgi?id=91193

Nice work! Once I get a llvm build which works with those mesa commits, I'll confirm it.
(see you in several hours or days...)

**Comment by danginsburg** [comment]
Thanks @DarkDefender.  All of our shaders output gl_ClipDistance[0] and enable glEnable( GL_CLIP_DISTANCE0 ) with the exception of the scaleform shaders.  Looks like it is likely related to that.

**Comment by ChristophHaag** [comment]
@sylware Have you thought about simply `git revert af4b9c7c2e119d373f9684119b833a8b62cbb756` on mesa master?

I can confirm by the way that reverting this commit makes the flickering going away. Looks fine now.

**Comment by sylware** [comment]
> @sylware Have you thought about simply `git revert
> af4b9c7c2e119d373f9684119b833a8b62cbb756` on mesa master?

I did use revert once. I don't really recall why (probably something related to
the linux kernel). There was so much non-orthogonal code creating conflicts, I
dropped its use and have forgotten about it.
But for those mesa commits, just one little conflict! Nice indeed.

> I can confirm by the way that reverting this commit makes the flickering
> going away. Looks fine now.

Same here. The flickering went away.

**Comment by ChristophHaag** [comment]
kdiff3 merged it automatically and did this: https://github.com/ChristophHaag/mesa-mesa/commit/7d27b6ea35fdab46190605232ae6fe3dcaadec33

It removes only three cases, so a trivial thing to test would be to test whether it's really clipdist which is responsible for the glitches. But I'm getting some sleep for now.

**Comment by ChristophHaag** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=91193#c6
http://cgit.freedesktop.org/mesa/mesa/commit/?id=248b26429f52d0f19949a083aa3e0aeebcbe2138

**Comment by DarkDefender** [comment]
Yupp, I think this can be closed now. :)

**Comment by phoerious** [comment]
Is this fix only for Radeon? Shadow flickering also occurs with NVIDIA cards.

**Comment by sylware** [comment]
On Tue, Jul 07, 2015 at 02:46:50AM -0700, Janek Bevendorff wrote:

> Is this fix only for Radeon? Shadow flickering also occurs with NVIDIA cards.

This is non-sense, this is totally specific to radeon SI hardware.

Expect if nvidia has the same hardware with the same driver bugs...

**Comment by phoerious** [comment]
That's what I thought. The issue is slightly different. Shadows always flicker, regardless of whether normal mapping is turned on or not. I see it in the trees and on the flowers on the ground. It's pretty annoying. It also depends on the angle at which you look at the object. Shadows of objects to the side of the screen tend to flicker more than those of objects viewed almost from the top, i.e. objects in the center.

Maybe open another issue for that?

**Comment by sylware** [comment]
Sorry nvidia is quite open source non-friendly, they can go die in hell.

This is another matter, you should open another issue and ask nvidia driver support.

**Comment by DarkDefender** [comment]
@Manko10 this specific github issue is only related to radeonsi cards. 
IIRC there were some similar problems with Nvidia cards when using older drivers on them. So updating to the lastest driver release may solve it. If not, you can open an other issue about that here.

**Comment by phoerious** [comment]
I have the latest stable driver. I guess I'll open another issue then.

**Comment by gdrewb-valve** [comment]
Can this issue be closed then?

**Comment by DarkDefender** [comment]
Yes, it seems like it is solved for me now.

**Comment by sylware** [comment]
For me too.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
