### ISSUE TITLE
game mode not visible

### ISSUE THREAD

**Issue by pavildon** [ValveSoftware/Dota-2#1501]
#### Your system information

* https://gist.github.com/aindigo/2efcbc6f87c80fa782daeef07788f74f
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Ranked Role matchmaking is not visible. It just disappeared overnight. 
It seems that the **best thing that happened to the dota2 community** 
is no longer visible anymore. its hidden?

#### Steps for reproducing this issue:

1. Start the game to enjoy a game without role related drama.
2. The button is not there anymore.

**Comment by kisak-valve** [comment]
Hello @aindigo, you'll want to post this on https://dev.dota2.com.
