### ISSUE TITLE
Dota doesn't launch on Mojave 10.14

### ISSUE THREAD

**Issue by asand04** [ValveSoftware/Dota-2#1503]
System information

*Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro9,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.14.0 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.22" x 7.01" (13.23" diag)
                                            28.5cm x 17.8cm (33.6cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  1907528 Mb
    Largest Free Hard Disk Block:  607221 Mb
    VR Headset: None detected

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

 **Issue** 

I was able to play until yesterday when I updated Dota.
Right after the update when I press the play button, the dota 2 icon appears on the dock and then disappears without launching. My current content BuildID is 312067.

#### Steps for reproducing this issue:

1. Launch Steam
2. Go to library 
3. Select Dota2 and press play

**Comment by kisak-valve** [comment]
Hello @asand04, this is most likely the same issue as #1502. Closing as a duplicate.
