### ISSUE TITLE
[Windows 10] Disconnected after accepting matches in client

### ISSUE THREAD

**Issue by liamb1** [ValveSoftware/Dota-2#1508]
#### [Your system information](https://gist.github.com/liamb1/7c707b2f5cd2cf5ab4bd1eac3dc91ed2)

* Have you checked for system updates?: [**Yes**/No]
* Are you using the latest stable video driver available for your system? [**Yes**/No]
* Have you verified the game files?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
Connecting to the Australian server from Malaysia allows me to accept matches, but then fails to connect to the server itself. This issue began yesterday, and I have been playing on Australian servers from some time with no issues. I have checked my ports and disabled my computer's firewall, yet nothing seems to change the lack of received data from the server.
[Link
](https://gist.github.com/liamb1/734d8b5066527ca422ee51a27fcc088c)
#### Steps for reproducing this issue:

1. Connect to Australian server from SEA
2. Accept match
3. Fail to connect

**Comment by kisak-valve** [comment]
Hello @liamb1, you'll want to post this at https://dev.dota2.com.
