### ISSUE TITLE
Some relay servers answer with private IP addresses.

### ISSUE THREAD

**Issue by FeatheredSerpent** [ValveSoftware/Dota-2#1510]
I don't know where else to report this. It's nothing affecting Dota 2 directly. It's just very odd.

If you do a traceroute to some Dota 2 relay servers ("lux" and "bom" e.g.) a few hops before something manages to answer with a private IP address (from the 192.168.0.0/16 block) over the internet(!), which is quite surprising, to say the least.

It does not appear to be a regional problem (as you can verify using [lg.he.net](https://lg.he.net)) and appears to affect only certain relays, like "lux" and "bom" for example.

Here is an example, using [lg.he.net](https://lg.he.net) to traceroute lux.valve.net (146.66.152.2):
> core3.fmt1.he.net> traceroute 146.66.152.2  source 216.218.252.128 numeric
>   
> Tracing the route to IP node (146.66.152.2) from 1 to 30 hops
> 
>   1    12 ms    1 ms    1 ms 72.52.92.65 
>   2    18 ms    2 ms    1 ms 72.52.92.157 
>   3    68 ms   76 ms   70 ms 184.105.81.217 
>   4   136 ms  168 ms  170 ms 72.52.92.165 
>   5   135 ms  143 ms  144 ms 195.66.226.130 
>   6    *       *       *     ? 
>   7   168 ms  165 ms  157 ms 162.254.196.137 
>   8   169 ms  207 ms  175 ms 146.66.154.218 
>   9   164 ms  174 ms  447 ms **192.168.130.3**
>  10   201 ms  160 ms  166 ms 146.66.152.2 
> 

And for "bom" (155.133.233.98):
> core1.fra1.he.net> traceroute 155.133.233.98  source 216.218.252.174 numeric
>   
> Tracing the route to IP node (155.133.233.98) from 1 to 30 hops
> 
>   1    21 ms   10 ms   <1 ms 80.81.192.64 
>   2    16 ms   16 ms   20 ms 62.216.128.13 
>   3   172 ms  173 ms  172 ms 85.95.26.153 
>   4    *       *       *     ? 
>   5    *       *       *     ? 
>   6    *      142 ms  143 ms 220.225.70.149 
>   7   182 ms  164 ms  191 ms **192.168.163.5** 
>   8   147 ms  154 ms  148 ms 155.133.233.98 

[RFC 1918](https://tools.ietf.org/html/rfc1918) states:
> Because private addresses have no global meaning, routing information
> about private networks shall not be propagated on inter-enterprise
> links, and packets with private source or destination addresses
> should not be forwarded across such links. Routers in networks not
> using private address space, especially those of Internet service
> providers, are expected to be configured to reject (filter out)
> routing information about private networks. If such a router receives
> such information the rejection shall not be treated as a routing
> protocol error

PS: I initially found out about this using the internet connection at home - so it isn't a problem related to a specific ISP. And I did verify that the replies actually came from a 192.168.X.Y address by capturing packets directly on the DSL-interface of my router.
To me it looks like some of Valve's equipment or that of the datacenter they are hosted in might be misconfigured (and everything I was ever taught about private IP addresses is a lie ;) - Valve, please fix.

**Comment by kisak-valve** [comment]
Hello @FeatheredSerpent, you'll want to post this at https://dev.dota2.com for the larger Dota 2 team.

**Comment by zpostfacto** [comment]
@FeatheredSerpent, that's OK, don't worry with posting anywhere else.  Was just looking at this.

Pretty sure that's OK for private addresses to be used for internal hops, and is intentional and totally OK.

**Comment by FeatheredSerpent** [comment]
The thing is that those hops send packets to the internet which have a private IP address set as the source address in the IPv4 header. Which is, as far as I know, not OK. ;)

**Comment by zpostfacto** [comment]
I think the only packets that use a private address as either a source or destination are going to be the ICMP replies that are generated as a result of the traceroute.  I don't think this breaks anything or is violation with any standard.

**Comment by zpostfacto** [comment]
I confirmed it's intentional.
Thanks for checking, though!
