### ISSUE TITLE
System Freeze Completely - Non Responsive

### ISSUE THREAD

**Issue by Podesta** [ValveSoftware/Dota-2#1511]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Podesta/f05bed339f84469ca8b1fb89151bee2c
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
While playing Dota 2, it sometimes freezes the system completely. The monitor displays the "No input" message and goes black, indicating the video card is not outputting any image. The audio continues to play on a loop, usually the background music, but if it happens mid skill cast, sometimes it continues to play that tune on a loop instead.

It does not respond to any commands, not even trying a shutdown, changing tty, etc. The only solution is a reset. Since it is not a "clean crash" there are no error messages or log dumps.

I've had this issue at least as far back as 6 months ago on the same machine. I've stopped playing for a bit and have since reinstalled to a different distro (It did not happen on Windows). It happens randomly. Usually around the 3rd or 4th game I'll get a crash, but sometimes it also happens on the first game I play. Just now I had a crash on the game results screen after I alt tabbed out and back, which was a first. The other crashes are unrelated to alt tabbing, and I usually have nothing open other than Dota and steam.

Another "graphics intensive" game that I often play for hours on end and never encountered any issues is XCOM 2.

#### Steps for reproducing this issue:
Somewhat random.

**Comment by kisak-valve** [comment]
Hello @Podesta, are you running Dota 2 with OpenGL or Vulkan? In general no OpenGL application should be capable of completely freezing the system, which hints this is a video driver issue.

When the freeze happens, are you able to ssh into the system and check `dmesg` if there's any related output near the time of the freeze?

**Comment by Podesta** [comment]
@kisak-valve yeah, it is the opengl version, as my gpu is in the 500 series, and vulkan support starts only with the 600. Here is the dmesg log:

```
[ 3345.214971] NVRM: GPU at PCI:0000:01:00: GPU-de4b7962-0085-326f-9981-716e25a8ee50
[ 3345.214974] NVRM: Xid (PCI:0000:01:00): 79, GPU has fallen off the bus.
[ 3345.214976] NVRM: GPU at 0000:01:00.0 has fallen off the bus.
[ 3345.214983] NVRM: A GPU crash dump has been created. If possible, please run
               NVRM: nvidia-bug-report.sh as root to collect this data before
               NVRM: the NVIDIA kernel module is unloaded.
[ 3355.534247] nvidia-modeset: ERROR: GPU:0: Failed to query display engine channel state: 0x0000857c:0:0:0x0000000f
[ 3355.534830] nvidia-modeset: ERROR: GPU:0: Failed to query display engine channel state: 0x0000857c:0:0:0x0000000f
```
I've got the `nvidia-bug-report.log`, if it is relevant to you guys.

**Comment by Podesta** [comment]
Confirming crash still present on version 7.20
