### ISSUE TITLE
Effigy not displaying correctly

### ISSUE THREAD

**Issue by FeatheredSerpent** [ValveSoftware/Dota-2#1512]
When effigies were new I made an effigy which looked like this : https://youtu.be/RGNW_dmLPC8?t=248

Now it looks like this (her staff is missing and her hair is in the wrong place) : 
https://i.imgur.com/H4N47ff.jpg

It's been like that for years, possibly since Dota 2 reborn? 
Same result on Linux and Windows (current, as well as 2-3 yo versions - dx9/dx11/vk/gl)

Is there a way for me to privately send you my Steam/Dota ID?

**Comment by kisak-valve** [comment]
Hello @FeatheredSerpent, you'll want to post this on https://dev.dota2.com for the larger Dota 2 team.
