### ISSUE TITLE
Weird pause and unpause during in game .

### ISSUE THREAD

**Issue by prinzegg** [ValveSoftware/Dota-2#1513]
I have already checked for system updates, verified game files and here is my system information below

This is my system information. I literally cannot play the game, i tried in bots match, create a lobby and still the same. The system spams pause and unpause it again, i removed the f9 key for pause and not putting any keys for it but still the same. Already the 4th day, i cant resolve the problem using verify files also.

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2128 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce 310M    
    DirectX Driver Name:  nvd3dum.dll
    Driver Version:  8.17.12.5887
    DirectX Driver Version:  8.17.12.5887
    Driver Date: 7 4 2010
    OpenGL Version: 3.3
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce 310M    
    VendorID:  0x10de
    DeviceID:  0xa75
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 18.98" x 10.67" (21.73" diag)
                                            48.2cm x 27.1cm (55.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 512 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Speakers (High Definition Audio

Memory:
    RAM:  6006 Mb

![20181027202409_1](https://user-images.githubusercontent.com/44545029/47615066-f3a6e580-dae4-11e8-90e4-effc5da2c7da.jpg)
![20181027202424_1](https://user-images.githubusercontent.com/44545029/47615068-f43f7c00-dae4-11e8-9275-d8ad0e553f53.jpg)
![20181027202354_1](https://user-images.githubusercontent.com/44545029/47615065-f30e4f00-dae4-11e8-86ed-0f80dfda8df4.jpg)

**Comment by kisak-valve** [comment]
Hello @prinzegg, you'll want to post this at https://dev.dota2.com for the larger Dota 2 team.
