### ISSUE TITLE
Dota 2 cannot launch on Mac

### ISSUE THREAD

**Issue by hansgao7** [ValveSoftware/Dota-2#1517]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Processor 2.53Ghz Intel Core 2 Duo, 8 GB 1067Mhz DDR3, NVIDIA GeForce 9400M 256 MB
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In Steam, after downloading latest update, Dota 2 can't launch when clicked. Just the dialog box opens up for few secs and nothing happens. I have tried deleting all Dota folders/files and reinstalling, set launch options -autoconfig and -safe, launch dota.sh with terminal to no avail.

Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. When click "Play" in Steam
2. Dialog Box "Preparing to launch Dota" shows up
3. Then nothing else happens

![screen shot 2018-11-11 at 10 13 34 am](https://user-images.githubusercontent.com/44935406/48308242-f69cde00-e59a-11e8-94b5-17c19d0ba335.png)

**Comment by joshg2k** [comment]
I am getting this exact same issue. I've been trying to start Dota for about an hour now. I've tried all the same resolution steps that @hansgao7 mentioned above.

**Comment by hansgao7** [comment]
Just to add, regarding system info:

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro5,4
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2530 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.9.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce 9400M
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x863
    Revision:  0xb1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 12.95" x 8.15" (15.28" diag)
                                            32.9cm x 20.7cm (38.8cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  952729 Mb
    Largest Free Hard Disk Block:  52627 Mb
    VR Headset: None detected

**Comment by NotifydLLC** [comment]
@hansgao7 hey I was able to fix my issue. I upgraded to macOS Mojave (10.14) and I'm no longer having issues launching. I also saw that you could launch Dota from terminal by opening Terminal and running this command:

`exec ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh`

**Comment by joshg2k** [comment]
@hansgao7 hey I was able to fix my issue. I upgraded to macOS Mojave (10.14) and I'm no longer having issues launching. I also saw that you could launch Dota from Terminal by opening Terminal and running this command:

exec ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh

**Comment by yoanvb** [comment]
I have the exact same problem since today, running on Yosemite 10.10.5.
Double clicking directly on the dota2.app does not work either.
When going through "~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh", I have this log :
```
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Users/yoan/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamID:  0, universe Public
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198074915526 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198074915526
SteamID:  76561198074915526, universe Public
Setting breakpad minidump AppID = 373300
SteamID:  0, universe Public
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL vendor NVIDIA Corporation
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL renderer NVIDIA GeForce 320M OpenGL Engine
void COpenGLDriverEntryPoints::DumpContextInfo(): Using OpenGL context version 3.3
void COpenGLDriverEntryPoints::DumpContextInfo(): Context supports GLSL version 3.30
 failed to dlopen "/Users/yoan/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librenderdoc.dylib" error=dlopen(/Users/yoan/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librenderdoc.dylib, 9): image not found
 failed to dlopen "librenderdoc.dylib" error=dlopen(librenderdoc.dylib, 9): image not found
Fontconfig warning: "/Users/yoan/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/Users/yoan/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Signal handler for "SIGALRM" (14) changed by other code. Expected 0x0, was 0x1
```

The game launches but once in a game everything is blur except for the HUD.

**Comment by tabanger** [comment]
I'm having the same issue with being unable to launch Dota 2.  I am on OS X 10.10.5 also.  Have the system requirements been silently bumped to 10.11+ without notification?  Or is this a build mistake?

**Comment by hansgao7** [comment]
Tried this, still didn't work. "exec ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh"

![screen shot 2018-11-12 at 9 36 04 am](https://user-images.githubusercontent.com/44935406/48321599-6aec8580-e65e-11e8-8134-6e8785ced907.png)

Not sure is the OS version issue since others on higher OS is facing the same issue. Thanks for any help and assistance.

**Comment by tabanger** [comment]
> Not sure is the OS version issue since others on higher OS is facing the same issue. Thanks for any help and assistance.

How do you figure the OS isn't the problem?  We've got two reports in this thread on 10.10, you on 10.9, and one more on a (presumably) old OS who upgraded to 10.14, which resolved the issue.  No other reports from other users, who are all presumably running more modern versions (I'm guessing 10.11+). OS version is absolutely the most likely culprit right now.

The question is, is this exclusion an inadvertent build issue (Steam still says minimum OS required is 10.9)?  Or is this a yet-unannounced increase in minimum OS requirements, maybe because of a new requirement for, say, Metal, first introduced in 10.11?

**Comment by kisak-valve** [comment]
Hello, per https://steamcommunity.com/discussions/forum/2/1752358461536110859/ please opt into Steam's beta client and retest this issue.

**Comment by tabanger** [comment]
Thanks.  Updating to Steam beta dated Nov. 9 allowed Dota 2 to launch and run properly.

**Comment by hansgao7** [comment]
I followed the steam thread, they fixed the public client and all is working well now so far. Thanks again for your great help!

**Comment by kisak-valve** [comment]
Closing as fixed in the [2018-11-09](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1711826064890402846) Steam client beta update.

**Comment by shirish-heller** [comment]
I am getting this exact issue. i just reinstalled the game after 3 weeks and now on clicking play nothing happens

**Comment by chayakornjj** [comment]
I'm getting this issue as well, Using my old laptop Macbook Pro 2015 15' Just installed Steam and downloaded the game but got same as this issue.

**Comment by mukk85** [comment]
@kisak-valve This seems to be an issue again. I was able to play last week, it may have been the recent OSX update to 11.2.3 that caused it. I also dont see the Vulkan DLC in the store anymore, which I had downloaded previously.

Now, the game starts to launch then exits with the attached dialog.
![Screen Shot 2021-03-24 at 7 07 08 AM](https://user-images.githubusercontent.com/1731299/112324057-97bdf800-8c6f-11eb-8d9c-9e35ffc9ea74.png)

**Comment by nicksav** [comment]
The same issue here....

**Comment by somethvictory** [comment]
Running on Mac OS Big Sur 11.6, still having the same issue

**Comment by rafehsh** [comment]
OS Monterey same issue unable to load Dota 2.

How do I fix this? plz help

**Comment by AndreyTelipko** [comment]
I have got the same issue still on Catalina.
