### ISSUE TITLE
[Linux] Video settings are not saved, hang when going Windowed <-> Borderless

### ISSUE THREAD

**Issue by MatthewWalker** [ValveSoftware/Dota-2#152]
Borderless window also minimizes when it loses focus.

System information:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 680/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 340.76
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1180
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20.91" x 11.73"  (23.94" diag)
                                        53.1cm x 29.8cm  (60.8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  15935 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  56192 Mb
    Largest Free Hard Disk Block:  9183 Mb

Installed software:

Recent Failure Reports:
    Sun Jun 21 05:24:02 2015 GMT: file ''/tmp/dumps/crash_20150621031819_1.dmp'', upload no: ''HTTP response code said error''
    Mon Jun 22 00:38:38 2015 GMT: file ''/tmp/dumps/crash_20150622005454_1.dmp'', upload no: ''HTTP response code said error''
    Mon Jun 22 00:47:33 2015 GMT: file ''/tmp/dumps/crash_20150622014526_1.dmp'', upload yes: ''CrashID=bp-6cbea6c9-2ee3-4301-ac25-b21c62150621''
    Mon Jun 22 22:16:37 2015 GMT: file ''/tmp/dumps/crash_20150622231253_1.dmp'', upload no: ''HTTP response code said error''
    Mon Jun 22 22:26:29 2015 GMT: file ''/tmp/dumps/crash_20150622232534_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jun 26 12:14:55 2015 GMT: file ''/tmp/dumps/crash_20150626130125_1.dmp'', upload yes: ''CrashID=bp-6ee0981c-bf5a-4c35-bf10-083df2150626''
    Fri Jun 26 12:14:55 2015 GMT: file ''/tmp/dumps/crash_20150626131347_13.dmp'', upload yes: ''CrashID=bp-56204b11-1f58-4ec8-8113-be0af2150626''
    Sun Jun 28 06:46:40 2015 GMT: file ''/tmp/dumps/crash_20150628074311_1.dmp'', upload no: ''HTTP response code said error''
    Sun Jun 28 06:47:13 2015 GMT: file ''/tmp/dumps/crash_20150628074643_1.dmp'', upload no: ''HTTP response code said error''
    Sun Jun 28 06:49:10 2015 GMT: file ''/tmp/dumps/crash_20150628074742_1.dmp'', upload no: ''HTTP response code said error''
    Sun Jun 28 06:50:14 2015 GMT: file ''/tmp/dumps/crash_20150628074913_1.dmp'', upload no: ''HTTP response code said error''

**Comment by Kirov123** [comment]
I have had this issue as well.

**Comment by gdrewb-valve** [comment]
@MatthewWalker, does this happen every time?  I can't repro, here is what I'm doing:
1. Start Reborn.  I start in borderless window.
2. Open video settings, select windowed and apply.  The title bar is added.
3. Select borderless window and apply.  The title bar goes away.

As for the focus issue it looks like you're using a borderless window the size of your monitor, correct?  It's expected that it will minimize on focus loss to get out of the way.  If you use a size smaller than your monitor does it minimize on focus loss (it shouldn't and doesn't for me)?

**Comment by gdrewb-valve** [comment]
@Kirov123, can you give more details on your configuration and what you're doing when you have the problem?

**Comment by MatthewWalker** [comment]
@gdrewb-valve, here's a video of it hanging changing from Borderless -> Windowed and changing from  "Use my monitor's.." -> Windowed.

https://www.dropbox.com/s/t3z99z18ust93h3/reborn-video-settings.ogv?dl=0

If I use a smaller borderless window it doesn't minimize when changing focus for me either.

Dota 2 Source 1 borderless window doesn't minimize on focus loss and I prefer it that way (so I can tab to windows on another screen while still having dota visible).

Possibly relevant: Source 1 Dota starts on a different screen to Source 2.

Backtrace:

``` gdb
#0  0x00007fb93a8dce8d in poll () from /usr/lib/libc.so.6
#1  0x00007fb9367a0a64 in ?? ()
   from /home/matthew/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fb9367a271f in xcb_wait_for_event ()
   from /home/matthew/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fb936c04ba8 in _XReadEvents ()
   from /home/matthew/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007fb936bec390 in XIfEvent ()
   from /home/matthew/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007fb93b319a34 in XIfEvent () from /home/matthew/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#6  0x00007fb932c55103 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#7  0x00007fb92d4b03f5 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so
#8  0x00007fb93499f54b in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#9  0x00007fb93499f744 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#10 0x00007fb9349094f1 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#11 0x00007fb9349058a5 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#12 0x00007fb9347d0905 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#13 0x00007fb9347d0f21 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#14 0x00007fb9347c79b2 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#15 0x00007fb9347ca338 in ?? ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#16 0x00007fb9347ca4da in Source2Main ()
   from /home/matthew/.dota_library/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#17 0x00007fb93b7520c1 in ?? ()
#18 0x00007fb93a81e790 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x00007fb93b7521bd in _start ()
```

**Comment by gdrewb-valve** [comment]
Thanks for the extra info.  Please open a separate enhancement request for control over the focus behavior.

**Comment by Kirov123** [comment]
System information:

OS:
Kubuntu 15.04
-Version-
Kernel		: Linux 3.19.0-22-generic (x86_64)
C Library		: Unknown
Default C Compiler		: GNU C Compiler version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 
Distribution		: Ubuntu 15.04
Desktop Environment		: KDE (plasma)

Processor:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 30
Model name:            Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Stepping:              5
CPU MHz:               2660.022
BogoMIPS:              5320.04
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-3

Video:
-Display-
Resolution		: 2944x1280 pixels
Vendor		: The X.Org Foundation
Version		: 1.17.1
-Monitors-
Monitor 0		: 1024x1280 pixels
Monitor 1		: 1920x1080 pixels
Vendor		: NVIDIA Corporation
Renderer		: GeForce GTX 660/PCIe/SSE2
Version		: 4.5.0 NVIDIA 346.59
Direct Rendering		: Yes

Memory:
5959 Mb

**Comment by Kirov123** [comment]
I just tested, and there is no longer a hang. I do not know if it is due to my window rules making Dota be fullscreen or if it is not hanging for some other reason.

**Comment by gdrewb-valve** [comment]
OK, thanks.

**Comment by gdrewb-valve** [comment]
@MatthewWalker, are you still seeing a hang?

**Comment by MatthewWalker** [comment]
@gdrewb-valve, it's still hanging. Turns out that it will stop hanging if you Alt+Move the window.
I have another video showing the functionality: https://www.dropbox.com/s/7td4vs9v7qwm669/reborn-video.mkv?dl=0

I've noticed the Dropbox webplayer seems to encode the videos pretty horribly.

It seems like Borderless Window acts exactly like Fullscreen if it has the same resolution as the screen
(as you can see by me alt+dragging the window in the video). The settings even get saved as
"Use my monitor's current resolution". I guess it's possible that KWin is causing that? I have some weird issues with KDE5 so who knows. 

Once the window has lost the window decorations they never return until you restart dota even after
switching to Windowed.

**Comment by gdrewb-valve** [comment]
Thanks for the update, we'll keep investigating.

**Comment by CommanderAlchemy** [comment]
I also experienced the hanging when switching from borderless window to window mode. I also changed resolution at the same time because of #213 that defaulted to 1024x768 And the game just hanged.

**Comment by gdrewb-valve** [comment]
The apparent hang in SDL is SDL bug 3052.

**Comment by gdrewb-valve** [comment]
The 8/14 update has a new SDL that might fix this, can you try again?

**Comment by gdrewb-valve** [comment]
I'm assuming this is fixed, closing.
