### ISSUE TITLE
failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Torxed** [ValveSoftware/Dota-2#1520]
#### Please describe your issue in as much detail as possible:

This is less of a traditional issue and more a question, why?
I'm completely aware that I'm lacking a couple of linked libraries, one of which being tensorflow.
What I'm wondering is, what exactly does Dota2 need tensorflow for, and what behavioral data is Dota2 capturing in order to learn something.. Is it my player movements? Is it what I'm doing in the UI? Is it strictly to do with bot movements and interactions?

I guess this is me going full on tin foil hat over here, but this is a pretty odd library to try and link in, unless I've missed something that you can use tensorflow for other than behavioral data..

#### Steps for reproducing this issue:

1. From a command-line, start steam
2. Start Dota2 and watch the debug output

**Comment by kisak-valve** [comment]
Hello @Torxed, Dota 2 has calls to a couple libraries that are useful for development, but are not used in the release build. They are generally not used in the public version and it is safe to ignore this these log messages.
