### ISSUE TITLE
[Windows 10] intermittent stuttering in game

### ISSUE THREAD

**Issue by scarlettDiMa** [ValveSoftware/Dota-2#1523]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  
MSI Desktop PC Trident 3 
Trident 3 Arctic VR7RD-048US 
Intel Core i7 7th Gen 7700 (3.60 GHz) 16 GB DDR4 1 TB HDD 256 GB SSD NVIDIA GeForce GTX 1070 Windows 10 Home 64-Bit

* Have you checked for system updates?: [Yes/No] 
YES
* Are you using the latest stable video driver available for your system? [Yes/No]
YES
* Have you verified the game files?: [Yes/No]
YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

After 7.20 update I am experiencing fps spike and stuttering every mins. My normal fps with video setting to high is around 100 fps and it will drop to 30 for 1s and go back to 100. I can confirm that this issue was not there before 7.20 and I don't experience this issue in other games (PUBG, csgo)

Regardless of settings, this intermittent stutter/hitching lasts around a second. This seems to be completely random, happens multiple times per game, and bears no relation that I can see to what's happening on screen at the time. 

I think it is related to dota2 client and not sth I can solve by myself. I do see a lot of other people experiencing similar problem on reddit:
https://www.reddit.com/r/DotA2/search?q=fps&restrict_sr=1&sort=new

Things I have tried:

1. Changing graphics settings, from potato to max;
2. All graphics APIs, DX9-Vulkan;
3. Vsync disabled;
4. Verifying cache;
5. Uninstalling and reinstalling steam and dota;
6. Variety of nVidia driver packages, up to latest 416.94;
7. Twiddling app compatibility settings (Administrator, Win7, etc).

#### Steps for reproducing this issue:
Even watching games would make me suffer from that stuttering.

**Comment by scarlettDiMa** [comment]
And I think this issue is not limited to windows. I see complains from Mac user and Linux user as well.

**Comment by kisak-valve** [comment]
Hello @scarlettDiMa, you'll want to post this at https://dev.dota2.com for the larger Dota 2 team.
