### ISSUE TITLE
[Linux] Constant Random Crashes 

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1526]
So, its been days (maybe weeks already) that Dota is randomly crashing, Its impossible to play or watch any game.

From draft to any stage on the game.

latest crash (on libclient.so, had crashses on libparticlesystem, and on libvulkanrenderer (also hapens on OpenGL))

https://gist.github.com/admshao/08681d7ab16f77c6c0f6e529226e8777

Worth adding that its happening ONLY to Dota, I'm playing Artifact and CS GO among other games with Steam Pronton and its all fine.

CPU usage < 40%, GPU usage vary from 60-70%, Temps < 60c

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/admshao/aed7a37ddfab924c6fdee2ca974d8625
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I would expect Dota to not crash and i could play/watch a game.

#### Steps for reproducing this issue:

1. Watch/Play any match
2. Wait for the crash.

**Comment by admshao** [comment]
This one happened after an Alt Tab but important to notice that the majority of the crashes happens while playing/watching

https://gist.github.com/admshao/8c0fe4f2bb8c795249c14b4c3f051dff

**Comment by admshao** [comment]
Just wanted to let you guys now, Its been a couple of days since my last crash,

In the mean time i had upgraded my kernel to 4.19.8-arch1-1-ARCH, nvidia to 415.22, reinstalled dota and steam update.

In case i don't have any other crashes until the weekend i think it will be safe to close this.

**Comment by admshao** [comment]
I got a word from a friend of mine that had similar issues on Windows a couple of weeks ago, He also has a Nvidia gpu and had Windows big update and a nvidia update and his crash is also gone.

I think its safe to close it for now. I'll let you know of any updates

**Comment by kisak-valve** [comment]
Closing per the last comment.
