### ISSUE TITLE
Dota 2 Crashing after new patch

### ISSUE THREAD

**Issue by Chocrates** [ValveSoftware/Dota-2#1530]
#### Your system information

*  [System Info](https://gist.github.com/Chocrates/7def40a17aba1c1feea5b5b9d6487ff7)
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
On Ubuntu 18.04 Dota instantly crashes after start.  Working great yesterday, but with the new patch last night it is crashing.

**Comment by aTK1987** [comment]
Same. Mac 10.10.5

**Comment by mismash1** [comment]
+1 Mac OS X 10.14.1
Open steam.  Launch DOTA 2.  Loads to the HUD / Root menu screen then looks like it is being "swiped" to the right, closes to OS desktop.  

I have reinstalled Steam / Dota and tried -safe start options.

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by Slimmons** [comment]
Same issue here, Ubuntu 18.04 Most recent driver, and I've checked everything else recommended.

Gist of system info [here](https://gist.github.com/Slimmons/2ac57fb52eb64ff60af27ca23f8af527)

**Comment by Chocrates** [comment]
Anybody had any luck getting dota to run via the command line so we can get a crash dump?

**Comment by Slimmons** [comment]
Dump file attached.  Zipped using gzip.
[crash_20181207224322_1.dmp.gz](https://github.com/ValveSoftware/Dota-2/files/2659412/crash_20181207224322_1.dmp.gz)

**Comment by Chocrates** [comment]
> Dump file attached. Zipped using gzip.
> [crash_20181207224322_1.dmp.gz](https://github.com/ValveSoftware/Dota-2/files/2659412/crash_20181207224322_1.dmp.gz)

Great thanks.  Can you walk me through how you got this one?

**Comment by Slimmons** [comment]
If you start the game normally, but have a terminal up with the command `tail -f /var/log/syslog`, it will show you where the dump goes.  Mine was `/tmp/dumps/`.

**Comment by mismash1** [comment]
Adding config and dump files.
[Archive.zip](https://github.com/ValveSoftware/Dota-2/files/2659423/Archive.zip)

**Comment by Chocrates** [comment]
Looks like it is a steam issue (rather than a dota issue) https://steamcommunity.com/app/570/discussions/0/1745605598710908098/#c1745605598710927384

Opting out of steam beta gets me a bit further.  Game is still loading, but its not crashing at least.

**Comment by aTK1987** [comment]
> Looks like it is a steam issue (rather than a dota issue) https://steamcommunity.com/app/570/discussions/0/1745605598710908098/#c1745605598710927384
> 
> Opting out of steam beta gets me a bit further. Game is still loading, but its not crashing at least.

Gets me to the main menu. Thanks for the update!

**Comment by RichMartel** [comment]
This problem happened as soon as my steam beta client upgraded to the latest (sometime in the last 8 hours).  I'm also running dota 2 with Vulkan launch option, and using Feral's gamemode linux performance booster.

**Comment by YangtseSu** [comment]
Crashing with steam beta.

**Comment by Th3NightHawk** [comment]
Running on MacOS 14.1, opting out of the beta client didn't resolve anything for me.

**Comment by Chocrates** [comment]
> Running on MacOS 14.1, opting out of the beta client didn't resolve anything for me.

Sorry to hear that.  Opting out of beta got me playing again on Ubuntu.

**Comment by hitchho** [comment]
Same here on Deepin OS 15.8 :(

**Comment by maximea1r** [comment]
The game only crashed for me if i were to view someone's profile.(ingame)

But otherwise the rest of the game worked fine (even on vulcan)

**Comment by jonathanborges** [comment]
I got the same in ubuntu 18.04.

1 - Run dota via terminal ~/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota
2 - Watch the error and install required libs. Like libpng12 libpangoft2... etc
3 - After install libs some errors keep comming, no problem. Just uninstall dota via steam and remove "Dota 2 beta" folder in steamapps.
4 - Download dota again.

This solve for me!

**Comment by Th3NightHawk** [comment]
New Steam client update resolved my Dota 2 crash issue on MacOS.

**Comment by Chocrates** [comment]
@kisak-valve  Thanks for reviewing this.  Let us know if you want us to opt-in to beta again and get you any more info.

**Comment by kisak-valve** [comment]
Was everybody who saw this issue using Steam's beta client? Per `This update was re-released on December 8th with a fix for a crash in Dota` in the [2018-12-08](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1705073202075628993) Steam client beta update, please make sure the Steam client up to date and retest this issue.

**Comment by RichMartel** [comment]
This problem happened for about 1/2 day and was later fixed.  I honestly didn't notice if my client was updated or not.

But YES, it was steam beta.  It appears (for me) that the steam fix for the crash in Dota fixed my problem, and I probably didn't notice that my client was updated.

**Comment by mareksimunek** [comment]
I got still issues (dota randomly crashing when playing) even when I have normal/ beta/ new beta steam client. 

![screen shot 2018-12-10 at 00 47 03](https://user-images.githubusercontent.com/8159699/49704589-24665880-fc15-11e8-8df1-b54f1c487dae.png)

![screen shot 2018-12-10 at 00 45 27](https://user-images.githubusercontent.com/8159699/49704676-3dbbd480-fc16-11e8-941d-0d20a65a1eea.png)


I will try upload dump as soon as I can (maybe tomorrow). But from quick check I found this in syslog about dota
`dota2[5905]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug`

**Comment by mareksimunek** [comment]
So I found out I do it myselft with shortcut cmd + q (which i have for item activation). It now quits whole dota.

**Comment by Lchiffon** [comment]
Same issue in Ubuntu 14.04.
Lastest version and run dota beta:
```shell
~/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2
FATAL: /home/chiffon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
	dlerror(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/chiffon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
```

I checked this file` /usr/lib/x86_64-linux-gnu/libstdc++.so.6` got:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXX
...
GLIBCXX_3.4.19
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

In another file `sudo strings /home/USERNAME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6.0.21 | grep CXX` have `CXXABI_1.3.8`:
```
..
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_TM_1
CXXABI_FLOAT128
```

But copy and rename not working.

**Comment by Lchiffon** [comment]
Same issue in Ubuntu 14.04.
Lastest version and run dota beta:
```
~/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2
FATAL: /home/USERNAME/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
	dlerror(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/chiffon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
```
I checked this file `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` got:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXX
...
GLIBCXX_3.4.19
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

In another file `sudo strings /home/USERNAME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6.0.21 | grep CXX` have CXXABI_1.3.8:
```
..
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_TM_1
CXXABI_FLOAT128
```
But copy and rename not working.

**Comment by kisak-valve** [comment]
I'm going to cut off this issue report here. The OP's issue is resolved and @Lchiffon's issue is being tracked at #1532. It's likely more unrelated issues are going to end up in here if it remains open.

@mareksimunek, please open a separate issue report for the issue you are seeing.
