### ISSUE TITLE
CXXABI_1.3.8 not found for libengine2.so

### ISSUE THREAD

**Issue by Fristaila** [ValveSoftware/Dota-2#1532]
#### system information ( https://gist.github.com/Fristaila/9c691414114201bc0f1ae3113b117fad )

* Steam client version (NOV 26 2018 at 20:15): 
* Distribution (Ubuntu 14.04): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
After launch dota 2 at terminal I have error:
ERROR: ld.so: object '/home/rus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/rus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 570, ActionID 12] : LaunchApp changed task to Completed with ""
pid 17166 != 17165, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/rus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/rus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FATAL: /home/rus/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
	dlerror(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/rus/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)

and the game is not starting. yesterday dota2 was started ok, today -not.
#### Steps for reproducing this issue:

1. launch steam
2. go to library
3. click play dota2

**Comment by raihanfajri** [comment]
same issue with me

this is my log

GameAction [AppID 570, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/asus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/asus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to Completed with ""
pid 7467 != 7466, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/asus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/asus/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FATAL: /home/asus/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
	dlerror(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/asus/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)

**Comment by azrothe** [comment]
I was having the same issue, and was able to solve it by following some of the steps as described at [https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found](url)

Namely, installing the package gcc-4.9 as decribed by Vipin Jain allows Dota to start. I did mess around with a bunch of other stuff first, so YMMV.

**Comment by dearlygparted** [comment]
>     * Distribution (Ubuntu 14.04):

Try running Steam like this:

`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`

Your system libraries are probably too old. You should upgrade to a newer release.

**Comment by dearlygparted** [comment]
```
 * Distribution (Ubuntu 14.04):
 ```
 
 Try running Steam like this:

 `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`
 
 Are the other people with this issue using outdated distros?

**Comment by ruliane** [comment]
> 
> 
> ```
> * Distribution (Ubuntu 14.04):
> ```
> 
> Try running Steam like this:
> 
> `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`
> 
> Are the other people with this issue using outdated distros?

I couldn't launch Dota2 on Linux Mint 17.3. ("version `CXXABI_1.3.8' not found")
Upgrading to Mint 19 (latest stable release) resolved my issue.

**Comment by kisak-valve** [comment]
Can everybody affected check if `realpath` is installed on your system? Steam's library pinning logic needs realpath to work, but it's not installed by default on Ubuntu 14.04.

You should be able to check with `apt policy realpath` in a terminal.

If it's not installed, please do so with `sudo apt install realpath`, then make sure steam is completely closed, then move / remove `<steam dir>/ubuntu12_32/steam-runtime/pinned_libs_*` so that Steam regenerates the pinned library folders.

If that does not help, you can try manually pinning the 64 bit steam runtime variant of libstdc++ with something like `ln -s ~/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6` (distro provided steam variant) or `ln -s ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6` (Valve provided steam variant).

**Comment by Fristaila** [comment]
https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found - helped
azrothe - thx!

**Comment by pandareen** [comment]
> Can everybody affected check if `realpath` is installed on your system? Steam's library pinning logic needs realpath to work, but it's not installed by default on Ubuntu 14.04.
> 
> You should be able to check with `apt policy realpath` in a terminal.
> 
> If it's not installed, please do so with `sudo apt install realpath`, then make sure steam is completely closed, then move / remove `<steam dir>/ubuntu12_32/steam-runtime/pinned_libs_*` so that Steam regenerates the pinned library folders.
> 
> If that does not help, you can try manually pinning the 64 bit steam runtime variant of libstdc++ with something like `ln -s ~/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6` (distro provided steam variant) or `ln -s ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libstdc++.so.6` (Valve provided steam variant).

Thank you @kisak-valve ... I installed realpath and restarted steam... It works now!
