### ISSUE TITLE
CMD+Q Issue

### ISSUE THREAD

**Issue by rezda** [ValveSoftware/Dota-2#1538]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/rezda/53a0b109d17dcbea47fc444772a1a118
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Key bind items to CMD+Q ends up quitting the game rather than using the item. Expect it to not quit game and instead use the item.

#### Steps for reproducing this issue:

1. Bind CMD+Q to use item
2. Use CMD+Q in game
3. See game quit

**Comment by kisak-valve** [comment]
Hello @rezda, system hotkeys should always take priority over application hotkeys and this is not a bug.

https://discussions.apple.com/thread/7634486

**Comment by mtnaked** [comment]
@kisak-valve Thanks for the answer. I have been dealing with this for 2 weeks now and haven't found a solution.
Before that the CMD+Q was bindable and only started from an update 2 weeks ago for the Dota client.
Is it possible that the client updated the priority for the system hotkeys?

As for the link you provided - it doesn't necessarily fix the problem for Dota2 as it cannot be specified for that application. I have tried many combinations to make it as workable as possible, yet there is no adequate or comfortable way to make it work.

**Comment by Tsourdox** [comment]
Check out my post in this thread for a permanent solution for both `cmd + q` and `cmd + w`:
https://steamcommunity.com/app/570/discussions/0/1745605598712418168/
