### ISSUE TITLE
Dota 2 not starting after the steam update

### ISSUE THREAD

**Issue by pandareen** [ValveSoftware/Dota-2#1543]
#### Your system information
Ubuntu 14.04 LTS
RAM 8G
Core i3 8thG
Geforce GTX 1050Ti

* Steam client version (build number or date): 26th Nov 2018
* Distribution (e.g. Ubuntu): 14.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No]: No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Problem: After 26th Nov, my dota 2 is not starting. When I try to run dota 2 binary from the terminal it shows the following error message: [Link to message](https://gist.github.com/pandareen/742230a614b75cfb861e2614bc1d02df)

#### Steps for reproducing this issue:

1. Log in to steam
2. Click on start dota 2

**Comment by kisak-valve** [comment]
Hello @pandareen, give #1532 a read.

**Comment by pandareen** [comment]
Thank you.. the issue is resolved after installing `realpath`
