### ISSUE TITLE
Crashing upon activation of ANY active item

### ISSUE THREAD

**Issue by LewisEro** [ValveSoftware/Dota-2#1544]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

https://gist.github.com/LewisEro/efdc702c14366767e1728f7692739e21

* Have you checked for system updates?: [Yes/No]

YES

* Are you using the latest stable video driver available for your system? [Yes/No]

YES

* Have you verified the game files?: [Yes/No]

YES

#### Please describe your issue in as much detail as possible:

So since the last patch my game has been crashing under oddly specific conditions. Many reported the "looking at someone's profile in the client causes crash" issue, which was one of mine. Changing from Vulkan to OpenGL fixed this for me. Another issue I personally had, which seemingly nobody else had was using certain items causing crashes. I didn't realise this at first and thought I was just crashing randomly some time into the games.

 Eventually the crashes put me into low priority, which lead me to stop queueing and proceed to do some testing versus bots. I discovered that (in the case of the match i was doing testing in at the time, radiant morphling vs. bots) using Manta Style caused the game to crash. I could recreate this issue reliably. So of course I thought it must be an illusion related issue, something that in the past has often caused issues to players (personally I never had issues exceeding low fps). However the game that put me into low priority I was playing Naga Siren and happily spammed illusions until roughly the 15 minute mark at which I obtained a Manta Style and the game crashed upon the first use.

 Testing around with other illusion heroes I quickly confirmed that illusions themselves (as well as illusion runes, no matter if bottled or just picked up) were not the issue, but rather activating manta style itself. I tried reinstalling steam and dota, verifying game files, updating drivers and everything and at first it seemed that Manta was now working. However I then crashed by using a Tome of Knowledge. Frustrating.. I reopened the game and noticed that now any items would cause a crash. Even a wand with zero charges. Restarting my computer would fix this issue for a few minutes, after which pretty much any item would cause a crash. It appears that the crashes are caused by the activation of items. 

I tried changing hotkeys but this changed nothing. I confirmed this by manually activating the items with left mouse clicks in the inventory.

I believe it has something to do with how the engine reacts to an item being activated. It is noteworthy to repeat that this only happens some minutes into the game and *usually* things are fine at the start of the game. So something eventually causes this some minutes into a match.

The issue occurs on both Vulkan and OpenGL.

#### Steps for reproducing this issue:

1. Load into the game (Demo mode/Bot game/Real game)
2. Play for some time and try using a variety of different active items.

**Comment by LewisEro** [comment]
It's command + Q, as another user reported... AKA my most commonly used hotkey. It's not a crash but *obviosly* the mac shortcut to quit a program. I find it very confusing that this has not closed dota for me previous to this patch... I would delete the OP if I could as this is rather embarrassing...

It does suck that this gave me low prio but then again this is the equivalent of using Alt + F4 as a hotkey for years and then it suddenly works as intended i guess. I would love to be able to keep using the hotkey in dota though as it's ingrained in my muscle memory.

**Comment by kisak-valve** [comment]
Hello @LewisEro, this issue is already being tracked at #1536. Closing as a duplicate.

**Comment by ggnasir** [comment]
> It's command + Q, as another user reported... AKA my most commonly used hotkey. It's not a crash but _obviosly_ the mac shortcut to quit a program. I find it very confusing that this has not closed dota for me previous to this patch... I would delete the OP if I could as this is rather embarrassing...
> 
> It does suck that this gave me low prio but then again this is the equivalent of using Alt + F4 as a hotkey for years and then it suddenly works as intended i guess. I would love to be able to keep using the hotkey in dota though as it's ingrained in my muscle memory.

Bro this helped me a lot. Been searching for this problem for days. Thank you!
