### ISSUE TITLE
(MacOs) Dota 2 crashes immediately after Frosthaven update

### ISSUE THREAD

**Issue by egMarshall** [ValveSoftware/Dota-2#1547]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist]Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro14,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.13.6 (64 bit)

Video Card:
    Driver:  Intel Iris Plus Graphics 650
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x5927
    Revision:  0x6
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1080
    Desktop Resolution: 2560 x 1080
    Primary Display Size: 31.57" x 13.15" (34.17" diag)
                                            80.2cm x 33.4cm (86.8cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  476802 Mb
    Largest Free Hard Disk Block:  351747 Mb
    VR Headset: None detected

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I was playing as usual before the update but than Dota started to crash after started.

**Comment by danginsburg** [comment]
Thanks, working on it.  You should be able to workaround it by deleting ~/Library/Application Supports/Steam/steamapps/common/dota 2 beta/game/dota/shadercache/vulkan/shaders.cache  or running with -vulkan_disable_pipeline_cache.  Should have a fix pushed out shortly though.

**Comment by egMarshall** [comment]
Thanks danginsburg! I'll wait the fix uptade!

**Comment by danginsburg** [comment]
Fix is on its way for next update.  In the meantime you can overwrite your copy of libMoltenVK.dylib in ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64 with the attached version.
[libMoltenVK.dylib.tar.gz](https://github.com/ValveSoftware/Dota-2/files/2696911/libMoltenVK.dylib.tar.gz)

**Comment by danginsburg** [comment]
Fix has shipped, closing.
