### ISSUE TITLE
fail to start dota2 on linux 14.04

### ISSUE THREAD

**Issue by tonghe90** [ValveSoftware/Dota-2#1549]
Hi Below is my system version, but I cannot log in the dota2. Every time I click play, it doesn't crash, but has no response. Any idea how to fix this?
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 14.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-72-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2018-11-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.130
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1b81
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.78" x 10.55" (21.54" diag)
                                            47.7cm x 26.8cm (54.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: %s1

Memory:
    RAM:  7928 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Total Hard Disk Space Available:  881099 Mb
    Largest Free Hard Disk Block:  166224 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by tonghe90** [comment]
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 570, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "", ProcID 5092, IP 0.0.0.0:0
>>> Adding process 5092 for game ID 570
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/tonghe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/tonghe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 5095 != 5094, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/tonghe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/tonghe/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
FATAL: /home/tonghe/dota2/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
	dlerror(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/tonghe/dota2/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
>>> Adding process 5093 for game ID 570
>>> Adding process 5094 for game ID 570
>>> Adding process 5096 for game ID 570
>>> Adding process 5097 for game ID 570
Game removed: AppID 570 "", ProcID 5092 
No cached sticky mapping in ActivateActionSet.

**Comment by kisak-valve** [comment]
Hello @tonghe90, please check if https://github.com/ValveSoftware/Dota-2/issues/1532#issuecomment-446599112 is relevant for you.

**Comment by tonghe90** [comment]
solved
