### ISSUE TITLE
[Linux] CTRL key doesn't work

### ISSUE THREAD

**Issue by yash1610** [ValveSoftware/Dota-2#1551]
#### Your system information

* System information from steam (Steam -> Help -> System Information) in a [gist](https://gist.github.com/yash1610/784c236828e150a0ad48972f93e62daf)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
CTRL Key, doesn't work for somethings but works for other things? I expected to be able to draw on the minimap with CTRL key, or upgrade hero skills with CTRL + Skill_Keybind, or to issue unified orders to all controlled units with CTRL key (the option is enabled). All of this did work around a month or two ago, but I took a break and when I came back it all stopped working.

If I go into keybinds and hold down CTRL key and some other key (say Q) nothing happens it doesn't bind anything. 

#### Steps for reproducing this issue:

1. Try binding something to CTRL + ANY_KEY
2.  Or draw on minimap using CTRL
3. Level up skills using CTRL + Skill_key

**Comment by kisak-valve** [comment]
Hello @yash1610, your desktop environment is most likely intercepting some hotkeys like control q and control w - https://wiki.gnome.org/Design/OS/KeyboardShortcuts. In general any application should not block system-wide shortcuts, but you might be able to unbind them in a gnome setting to let Dota 2 have a chance of using them.

Related to #1536.

**Comment by yash1610** [comment]
That does make sense, but I checked again I have nothing bound to CTRL at all (and any shortcuts that did use CTRL as a modifier I disabled). Although that should still not stop me from drawing on the map with CTRL or issuing unified orders to units I control since I am not using CTRL+ Key combo?

**Comment by yash1610** [comment]
Just to clear up I don't think my issue is related to #1536 since, CTRL+Q does nothing. I just used it as an example because q is the first key on the keyboard. I don't have this weird thing where if I press CTRL+ some_key something else happens in the OS. it's just nothing happens in dota. It's as if Dota can't even recognise that there is a CTRL key.

Right now my main problem is that I can't issue unified orders with CTRL key at all. Since it doesn't work. Please help

**Comment by yash1610** [comment]
FIXED: I had pointer location turned on in Gnome-tweaks. The default key for which is just CTRL.
