### ISSUE TITLE
Segfault while trying bot match

### ISSUE THREAD

**Issue by laurentiuco** [ValveSoftware/Dota-2#1553]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) : [system_info](https://gist.github.com/laurentiuco/ee28bc8f0bfd9288f03e3b42cffed7a9)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Start Dota 2.
2. Start bot match.
3. Untill hero pick screen loads the game crashes.

Additional info:
Running dmesg into terminial gives the following output:

> [ 4465.650541] dota2[2099]: segfault at 550000000000 ip 00007f2a3aacf846 sp 00007ffc49f96750 error 4 in libnetworksystem.so[7f2a3a8ae000+48a000]

Please note that I'm using Ubuntu 18.04 LTS with opensource amd driver.
Here is the distro info:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

**Comment by laurentiuco** [comment]
As far as I can see it this is not reproducible anymore. Maybe there was a broken process before or something went bad and caused this as it didn't happen after I created the ticket. This can be closed from my side.
Sorry for the trouble.

**Comment by kisak-valve** [comment]
Closing per the last comment.
