### ISSUE TITLE
[Linux] Dota 2 Crash on EXIT

### ISSUE THREAD

**Issue by Bednar87** [ValveSoftware/Dota-2#1554]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Bednar87/e64b7f70b6d9ee8d0125cfe19a8c584e
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

The game hangs and crashes on EXIT. I can reproduce it easily as it always happens irrespective of which renderer I use. 

> >>> Adding process 18981 for game ID 570
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game update: AppID 570 "", ProcID 18980, IP 0.0.0.0:0
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198012562328 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198012562328
Setting breakpad minidump AppID = 373300
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
Installing breakpad exception handler for appid(steam)/version(1544834093)
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
Installing breakpad exception handler for appid(gameoverlayui)/version(20181214221845)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 970/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
 failed to dlopen "/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Fontconfig warning: "/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
[0102/151723.454307:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Storage.SetString with 2 arguments
 failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
JS method call SharedConnection.SendMsg with 2 arguments
ERROR: ld.so: object '/home/bednar/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20190102151722_1.dmp[19048]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190102151722_1.dmp
>>> Adding process 19047 for game ID 570
crash_20190102151722_1.dmp[19048]: Finished uploading minidump (out-of-process): success = yes
crash_20190102151722_1.dmp[19048]: response: CrashID=bp-ef7212f3-ab5c-4864-b9b8-d3d662190102
crash_20190102151722_1.dmp[19048]: file ''/tmp/dumps/crash_20190102151722_1.dmp'', upload yes: ''CrashID=bp-ef7212f3-ab5c-4864-b9b8-d3d662190102''
pid 19048 != 19047, skipping destruction (fork without exec?)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
Installing breakpad exception handler for appid(steam)/version(1544834093)
/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104: 18980 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "", ProcID 18980 
No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
shadercachemanager/shadercachemanager.cpp (427) : Assertion Failed: ( localHitBuffer.TellPut() % sizeof( LocalHitCacheEntry_t ) ) == 0
shadercachemanager/shadercachemanager.cpp (427) : Assertion Failed: ( localHitBuffer.TellPut() % sizeof( LocalHitCacheEntry_t ) ) == 0
Installing breakpad exception handler for appid(steam)/version(1544834093)
assert_20190102151837_49.dmp[19073]: Uploading dump (out-of-process)
/tmp/dumps/assert_20190102151837_49.dmp
JS method call Storage.SetString with 2 arguments
assert_20190102151837_49.dmp[19073]: Finished uploading minidump (out-of-process): success = yes
assert_20190102151837_49.dmp[19073]: response: CrashID=bp-018972c3-0def-477e-9d28-7fa182190102
assert_20190102151837_49.dmp[19073]: file ''/tmp/dumps/assert_20190102151837_49.dmp'', upload yes: ''CrashID=bp-018972c3-0def-477e-9d28-7fa182190102''

> 

EDIT:

This appears to be a crash in libvideo:

> Jan 02 15:19:00 arch-Bednar systemd-coredump[19051]: Process 18980 (dota2) of user 1000 dumped core.
                                                   
                                                     Stack trace of thread 18980:
                                                     #0  0x00007f313e910040 n/a (/home/bednar/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvideo.so)
>-- Subject: Process 18980 (dota2) dumped core
> -- Defined-By: systemd
> -- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> -- Documentation: man:core(5)
> -- 
> -- Process 18980 (dota2) crashed and dumped core.
> -- 
> -- This usually indicates a programming error in the crashing program and
> -- should be reported to its vendor as a bug.
>

**Comment by kisak-valve** [comment]
Hello @Bednar87, this issue is already being tracked at #1524. Closing as a duplicate.
