### ISSUE TITLE
Dota fails to launch on ubuntu 14.04

### ISSUE THREAD

**Issue by jaydoubleuw** [ValveSoftware/Dota-2#1555]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

 https://gist.github.com/jaydoubleuw/dfe03c6aa6c02a5b91b5bee805f938a2#file-gistfile1-txt

* Have you checked for system updates?: [Yes/No]

yes

* Are you using the latest stable video driver available for your system? [Yes/No]

yes

* Have you verified the game files?: [Yes/No]

yes and deleted/reinstalled

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

After the latest Dota 2 update, the game no longer launches.  When I click "Play", I get the preparing to launch pop up window, and the the game immediately goes to "syncing" status, without launching.  Until now, no issues running Dota 2 on my linux machine. 

#### Steps for reproducing this issue:

1. install dota 2 on ubuntu 14.04
2. launch game
3. witness crash

**Comment by kisak-valve** [comment]
Hello @jaydoubleuw, please give https://github.com/ValveSoftware/Dota-2/issues/1532#issuecomment-446599112 a read.

**Comment by jaydoubleuw** [comment]
Ty!  works like a charm :)

**Comment by kisak-valve** [comment]
Thanks, closing.
