### ISSUE TITLE
Coredump during shutdown

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/Dota-2#1556]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/amitavmohanty01/590e766165ff364a2f4ad8a6413a8452
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I quit Dota 2, the game freezes. After some time the app stops.

#### Steps for reproducing this issue:

1. Play Dota 2
2. Quit

[gameoverlayui.log.zip](https://github.com/ValveSoftware/Dota-2/files/2729853/gameoverlayui.log.zip)
[stdout.zip](https://github.com/ValveSoftware/Dota-2/files/2729855/stdout.zip)
[dumps.zip](https://github.com/ValveSoftware/Dota-2/files/2729856/dumps.zip)

**Comment by kisak-valve** [comment]
Closing as a duplicate of #1541 and #1524.
