### ISSUE TITLE
Shader issue on January 9th update

### ISSUE THREAD

**Issue by RichMartel** [ValveSoftware/Dota-2#1558]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/RichMartel/f1e9680fa6bd945175eec31415fd8e46
* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Since January 8th/9th update, I've had "blocky" shader issues on the main screen after starting the dota 2 client.  Locations that seem to have shader effects (sorry if I'm wrong on that, just seems that way), such as the "Finding Match" area at the bottom right, or sometimes the Dota 2 logo at the top left.  This is a new issue that I have never seen on the linux client before.

#### Steps for reproducing this issue:

1. Just starting the client, it happens immediately, and consistantly, but surprisingly it's not always the same element that has the issue.  Almost like it ran out of resources to display things properly.
2. 
3.

**Comment by phoerious** [comment]
Having the same problem here. Not only on the main screen, but also in game. It appears around all particle effects (sometimes it also appears around my mouse click circles on the ground) and looks like some masks are not applied properly.

Here's an example of Shaman wards.

![image](https://user-images.githubusercontent.com/911270/51077127-4df62200-16a2-11e9-9a95-9e5d51b91551.png)

**Comment by RichMartel** [comment]
Forgot to mention that I am running Dota 2 with Vulkan flag.

**Comment by phoerious** [comment]
Sorry for nagging about this, but can we get this fixed please? It's been over a week now and this is kinda game breaking or at least stupidly annoying.

**Comment by ghost** [comment]
This happens for me in-menu with the home dota-icon button. Using OpenGL though.

**Comment by dearlygparted** [comment]
This still occurs. In one game it was the effects around the shrines, in the next game it happened to the cursor (when you click to move the arrow animation turned into a green block). Happened with native system libraries and with the Steam runtime.

**Comment by RichMartel** [comment]
Not sure when this was corrected, but I don't seem to have this graphic glitch anymore.

**Comment by danginsburg** [comment]
Yeah, I did push a fix for this a while back, but forgot to close the bug.  Will close, thanks for updating.
