### ISSUE TITLE
[Mac] Game freezes when activating Mission Control

### ISSUE THREAD

**Issue by DiskPoppy** [ValveSoftware/Dota-2#1562]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/DiskPoppy/fc95ea9ce433b2c06311291e71d415b5): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I'm using Vulkan API - it doesn't seem to occur when using OpenGL, at least when trying to reproduce using these steps. When the bug occurs the video is static - there are no animations and it doesn't respond to user input. The music still plays, even when the game is on a different desktop. It can unfreeze after switching between desktops repeatably. However, it could also hang-up with a spinning wheel but I can't reliably reproduce it.

#### Steps for reproducing this issue:

1. Launch Dota 2 with Vulkan.
2. Use Desktop-friendly Fullscreen.
3. Activate Mission Control (F3 or fn-F3 by default)
4. Deactivate it. When activated from a different desktop, select the Dota 2 desktop.

**Comment by kisak-valve** [comment]
Hello @DiskPoppy, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/284. Closing as a duplicate.
