### ISSUE TITLE
Possible bot scripts in turbo matches

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/Dota-2#1566]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Not needed for this concern
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
https://www.youtube.com/watch?v=MjIyNG-wqUY shows a match which had a 5 person party in opposition. The way they played seemed like the opponents were bot scripts. Their frame of view and their actions were not like real players

#### Concerns and discussion points:

1. Is there a flaw in the system that is allowing these scripts to come in regular unranked or turbo matches?
2. Valve should collect more such matches and analyze them for understanding the potential flaw.
3. Can Valve expose an anonymized dataset of matches to the community for creating AI/ML based detection of bot scripts?

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, please post this over at https://dev.dota2.com/. This issue tracker is for the Mac and Linux Dota 2 client.

**Comment by amitavmohanty01** [comment]
@kisak-valve registrations are closed for the site you mentioned above. Why did you point me there?
