### ISSUE TITLE
PİCA BAN PLEASE

### ISSUE THREAD

**Issue by kadir** [ValveSoftware/Dota-2#1567]
MY DEAR GAME DEVELOPERS AND ADMINS. LAST GAME WE HAVE "PİCA" He was Sattı? ÇOK FENA SATTI
My GAME NOT CRASH BUT MY BRAIN CRASH. I AM Cancer Now. PAy my Cemotherapy PAYMENT OR BAN THIS PICA DUDE. DO SOME CODE REVIEWS AND BAN HIM

**Comment by kisak-valve** [comment]
Hello @Kadir, bans are not handled on this issue tracker.
