### ISSUE TITLE
Game screen flickering with Mars animation after start

### ISSUE THREAD

**Issue by eXcuvator** [ValveSoftware/Dota-2#1568]
#### Your system information

System information: https://gist.github.com/eXcuvator/c878a526cbef3be71c5afd4452bbf4e6
Steam updates: Checked.
Latest stable video drivers
Verified game files

#### Please describe your issue in as much detail as possible:

Started Dota after the Mars update. 
Screen keeps flickering between the background animation/screen, and the usual menu. Cant click anything. Cant escape. Restart does not help.
 
#### Steps for reproducing this issue:

1. Wait for client to update Dota 2 on my system 
2. Run dota 2
3. Profit.

**Comment by ncortines** [comment]
same here, game is pretty much unplayable on my mac

**Comment by anthonyalviz** [comment]
Getting same issue here.

**Comment by tabanger** [comment]
Yup, exact same thing here.  Running on Mac Pro with Xeon W3680, 48 GB RAM.  macOS High Sierra 10.13.6 (17G5019).  Nvidia GeForce GTX 1070Ti 8GB, using Nvidia Web Driver 387.10.10.10.40.118.

**Comment by ghost** [comment]
Same thing, im running a iMac with macOS High Sierra 10.12.6 (16G29).
NVIDIA GeForce GTX 970, i7-6700K CPU @ 4.00GHz

It looks like this
https://monosnap.com/file/MQhl5y6uR7ZsGLSxus1XH4HmFjuB2Y

**Comment by danginsburg** [comment]
I've got a fix for this that will be in the next update.  For the time being, you can use +gl_disableStaticBuffer 0 on your Launch Options to fix it.  I recommend removing that once the fix ships though because it may negatively impact perf, especially for older integrated GPUs.

Also, for those of you still using OpenGL - if your system supports Metal I strongly recommend switching to Vulkan, the perf is much better than the OpenGL version (and also has less hitching after shader cache warming).

**Comment by tabanger** [comment]
> Also, for those of you still using OpenGL - if your system supports Metal I strongly recommend switching to Vulkan, the perf is much better than the OpenGL version (and also has less hitching after shader cache warming).

Sorry for going off-topic, but last time I tried Vulkan (2 months ago), performance was worse (stuttering every few seconds), and colors were all washed out compared to OpenGL.  That's why I stuck with OpenGL.  Is that normal, or has that been fixed?

**Comment by ghost** [comment]
> > Also, for those of you still using OpenGL - if your system supports Metal I strongly recommend switching to Vulkan, the perf is much better than the OpenGL version (and also has less hitching after shader cache warming).
> 
> Sorry for going off-topic, but last time I tried Vulkan (2 months ago), performance was worse (stuttering every few seconds), and colors were all washed out compared to OpenGL. That's why I stuck with OpenGL. Is that normal, or has that been fixed?

i can confirm this, the performance with Vulkan is very poor. I did not noticed washed out colors but the game definitly performs better on OpenGL for me

**Comment by jfabre** [comment]
yep I actually tried Vulkan this week and reverted because the game would completely halt for like 5+ sec once in a while. And yeah, it's broken for me too.

Edit (specs):

MacBook Pro (Retina, Mid 2012)
2.3 GHz Intel Core i7
8 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1024 MB
Intel HD Graphics 4000 1536 MB

OS: Mojave 10.14.3

Also, ty for the current fix it works like a charm.

**Comment by danginsburg** [comment]
Hmm, the only NVIDIA GPUs I have for testing are the GTX 650M and GTX 750M and I've seen consistent improvement there.  @tabanger  you are on a GTX 1070 Ti - is that through an eGPU enclosure?  Maybe we've got an issue running on eGPUs I'm not aware of.  If you want to open another issue on the perf problems open it here: https://github.com/ValveSoftware/Dota-2-Vulkan/issues  If it's impacting eGPUs/hackintosh I may not be able to look at it anytime soon though.

**Comment by ncortines** [comment]
@danginsburg, sorry for the silly question. I'm using Mojave 10.14.3. How do I switch to Vulkan?

**Comment by ncortines** [comment]
@danginsburg, I just got the update and the game is playable again. I also figured out how to switch to Vulkan. Thanks

**Comment by tabanger** [comment]
> Hmm, the only NVIDIA GPUs I have for testing are the GTX 650M and GTX 750M and I've seen consistent improvement there. @tabanger you are on a GTX 1070 Ti - is that through an eGPU enclosure?

No, sorry, I should've specified it's a Mac Pro 2010.  Thunderbolt/eGPU is not even an option.  It's just in the regular primary graphics slot.

I just tried Vulkan again (while OpenGL was broken), and the issues persist.  The FPS performance/rendering may be on-par with or slightly better than OpenGL, but the micro-stuttering interrupts the game where micro-second reactions count, and makes it a total non-starter.  The stuttering is especially egregious during the first couple minutes of a match.  It seems to settle down after a while, but rears its head in a big way when you move your view to a new part of the map.

As for the color washout, here's an example, with Vulkan first, and OpenGL second (no settings changed between the games, besides the rendering engine):
https://imgur.com/a/01RMICC
You can clearly see in the color of the water, the grass, the pink trees, the fire, everything.

**Comment by danginsburg** [comment]
> The FPS performance/rendering may be on-par with or slightly better than OpenGL, but the micro-stuttering interrupts the game where micro-second reactions count, and makes it a total non-starter.

Yeah, I know the stuttering is very bad at first as new shaders get compiled for the first time.  However, whereas Mac OpenGL does not support binary shader caching (GL_ARB_get_program_binary), once shaders get warmed on MoltenVK we store them to disk and it gets much better, whereas the OpenGL path always stutters.  I understand it's bad on first run and needs warming.  It's something we have a fix for on other platforms, but not macOS right now.

If you could open another issue on the color washout issue I'll take a look.

**Comment by danginsburg** [comment]
Closing this issue since the original bug is fixed.
