### ISSUE TITLE
[Mac OS] Game unplayable after the update from 5. March 2019

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1569]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

> Computerinformationen:
>     Hersteller: Apple
>     Modell: iMac14,2
>     Formfaktor: Desktop
>     Keine Touch-Eingabe erkannt
> 
> Prozessor:
>     CPU-Hersteller: GenuineIntel
>     CPU-Marke: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>     CPU-Familie: 0x6
>     CPU-Modell: 0x5e
>     CPU-Stepping: 0x3
>     CPU-Typ: 0x0
>     Geschwindigkeit: 4009 MHz
>     8 logische Prozessoren
>     4 technische Prozessoren
>     HyperThreading:  Unterstützt
>     FCMOV:  Nicht unterstützt
>     SSE2:  Unterstützt
>     SSE3:  Unterstützt
>     SSSE3:  Unterstützt
>     SSE4a:  Nicht unterstützt
>     SSE41:  Unterstützt
>     SSE42:  Unterstützt
>     AES: Unterstützt
>     AVX: Unterstützt
>     CMPXCHG16B: Unterstützt
>     LAHF/SAHF: Unterstützt
>     PrefetchW: Nicht unterstützt
> 
> Betriebssystem:
>     MacOS 10.12.6 (64 Bit)
> 
> Grafikkarte:
>     Treiber: NVIDIA GeForce GTX 970
>     Treiberversion: 1.2
>     Treiberdatum: 0.0.0
>     OpenGL-Version: 2.1
>     Desktopfarbtiefe: 32 Bit per Pixel
>     Monitor-Aktualisierungsrate: 60 Hz
>     Anbieterkennung: 0x10de
>     Gerätekennung: 0x13c2
>     Revision: 0xa1
>     Anzahl der Monitore: 1
>     Anzahl der logischen Grafikkarten: 1
>     Prim. Anzeigeauflösung: 3440 x 1440
>     Desktopauflösung: 3440 x 1440
>     Prim. Anzeigegröße: 31.54" x 13.19" (34.17" diag)
>  80.1cm x 33.5cm (86.8cm diag)
>     Primärer VRAM: 0 MB
> 
> Speicher:
>     RAM: 32768 MB
> 
> Weitere Daten:
>     UI-Sprache: Deutsch (Deutsch)
>     Medium: DVD
>     Verfügbarer Festplattenspeicher insgesamt: 1431023 MB
>     Größter freier Festplattenspeicherblock: 238176 MB
>     VR-Headset: Keines gefunden

* Have you checked for system updates?:  **YES**
* Are you using the latest stable video driver available for your system? **YES**
* Have you verified the game files?: **YES**

#### Please describe your issue in as much detail as possible:
The whole game is flickering after the update for the new hero Mars, i did not changed nothing on my system (no driver updates available) and i was playing the game this morning and everything was just fine. I just recorded a video for you guys, to show you what im talking about

Video with the issue:
https://monosnap.com/file/MQhl5y6uR7ZsGLSxus1XH4HmFjuB2Y

Thread with other mac users reporting the very same problem:
https://www.reddit.com/r/DotA2/comments/axovnn/update_broke_graphics_completely_anyone_else/

#### Steps for reproducing this issue:

Run Dota 2 on a Mac

**Comment by kisak-valve** [comment]
Hello @daftdog, this issue is already being tracked at #1568. Closing as a duplicate.

**Comment by ghost** [comment]
Thanks i will just post my video there
