### ISSUE TITLE
[Mac] Viewed area polygon in "showcase view" is not drawn properly

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#157]
The green overlay polygon representing the area that is currently viewed in the minimap of the "showcase view" can get too big if you move the camera at certain angles.
See attached screenshot. 
![capture d ecran 2015-06-28 a 18 34 50](https://cloud.githubusercontent.com/assets/4463576/8397243/58550830-1dc5-11e5-860c-3c71fbf7ed85.png)

**Comment by gdrewb-valve** [comment]
This isn't a Linux/Mac issue, there's already an open issue in the general forums.  I'll make sure the larger team is aware and then close this out.
