### ISSUE TITLE
Error in Russian translation.

### ISSUE THREAD

**Issue by valeologist** [ValveSoftware/Dota-2#1577]
#### Your system information

* Computer Information:
    Manufacturer:  System manufacturer
    Model:  System Product Name
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3192 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 750
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  25.21.14.1935
    DirectX Driver Version:  25.21.14.1935
    Driver Date: 3 1 2019
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 750
    VendorID:  0x10de
    DeviceID:  0x1407
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17.44" x 9.80" (20.00" diag)
                                            44.3cm x 24.9cm (50.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Динамики (USB Audio Device)

Memory:
    RAM:  8156 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  1191175 Mb
    Largest Free Hard Disk Block:  302321 Mb
    OS Install Date: ??? 01 1970
    Game Controller: None detected
    VR Headset: None detected

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Steps for reproducing this issue:

1. Launched the game.
2. chose the section "heroes"
3. chose a hero.
4. chose the section "heroes"
![Uploading screenshot.jpg…]()
![Снимок экрана (1)](https://user-images.githubusercontent.com/44038528/54934500-4915e000-4f27-11e9-8481-2c64ee61993d.png)

**Comment by kisak-valve** [comment]
Hello @valeologist, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. You'll want to post this at https://dev.dota2.com/.

**Comment by unity2015** [comment]
Know all that kisak-valve with a sense of self-importance and he doesn’t care about users! problems are not solved at all!
