### ISSUE TITLE
Can't access dev.dota2 forums: "missing key"

### ISSUE THREAD

**Issue by valeologist** [ValveSoftware/Dota-2#1578]
And when will it be fixed ?? And why does VALVE ignore everyone, and close the topic, when the error has not yet been fixed ??? WHAT are you for the developers that you do not want to correct? You show your navlivatelno attitude towards us all !!!

( @kisak-valve Do not dare to close the topic if the error has not been fixed for what month! And then you closed my topic "Error in Translation. # 1577" knowing that you can’t go through checking your account because YOU and your developers do not want to do anything! Come Work and do not close the topic! Will you close the topic? I will again create a new one !!! )
![Снимок экрана (2)](https://user-images.githubusercontent.com/44038528/54938043-49fe4000-4f2e-11e9-984c-83086918c93a.png)

**Comment by kisak-valve** [comment]
Hello @valeologist, picking a fight on an issue tracker will never give a positive outcome. Your hostile attitude has earned you a 1 week time out.

This issue is already being tracked at #1516. Closing as a duplicate.
