### ISSUE TITLE
[Mac] Cannot take screenshots

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#158]
This is on OS X 10.9.5. 
The screenshot key has no effect (even after assigning the function to another key).

**Comment by gdrewb-valve** [comment]
Not sure this is a Linux/Mac issue.

**Comment by Vuccappella** [comment]
What are you taking screenshots with, if its the command CMD+SHIFT+3 (or 4) and you're in fullscreen that doesn't work. Try borderless window.

**Comment by jeanlain** [comment]
I try taking screenshot by typing the key assigned to the function in the "options" pane (F6 by default).

**Comment by gdrewb-valve** [comment]
This doesn't seem to work on any platform, I've let the larger team know and it won't be tracked here.

**Comment by Vuccappella** [comment]
Meanwhile if you're not on fullscreen you can still take screenshots with CMD+SHIT+3 or +4 if you want only part of the image, they get saved to your desktop.
