### ISSUE TITLE
Dota 2 crashes

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/Dota-2#1582]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/amitavmohanty01/0a2956e5f8989621a5a84f6a83547271
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I started the game. The initial Dota loading screen came and then the process crashed.

**Comment by amitavmohanty01** [comment]
The minidump is attached.
[crash_20190414234444_1.zip](https://github.com/ValveSoftware/Dota-2/files/3077707/crash_20190414234444_1.zip)

**Comment by amitavmohanty01** [comment]
Launching it from the command line gives the following warnings

```
Fontconfig warning: "/home/dknight/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/dknight/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
```

**Comment by amitavmohanty01** [comment]
The warnings were easy to fix but I have no idea about the core dump.

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/303. Closing in favor of the existing issue report.

You should be able to workaround the issue by adding `-gl` to the game's launch options.
