### ISSUE TITLE
[Arch Linux] Crash when starting game with vulkan

### ISSUE THREAD

**Issue by ttc0419** [ValveSoftware/Dota-2#1587]
# Hardware Info
## Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

## Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0xb
    CPU Type:  0x0
    Speed:  4600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

## Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.9-1-ck-skylake
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  <Runtime disabled>

## Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics (Whiskey Lake 3x8 GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 19.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x3ea0
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 11.42" x 6.69" (13.23" diag)
     29.0cm x 17.0cm (33.6cm diag)
    Primary VRAM Not Detected

## Sound card:
    Audio device: Realtek ALC3254

## Memory:
    RAM:  15760 Mb

# System Log:
```
[ 1292.875756] VKRenderThread[7828]: segfault at 0 ip 00007fec0d45c2eb sp 00007fec031359d0 error 4 in libtcmalloc_minimal.so.0[7fec0d44a000+21000]
[ 1292.875762] Code: db ce ff ff 44 39 e3 7c a6 31 f6 31 d2 45 85 e4 74 2e 48 8b 75 00 41 83 fc 01 48 89 f2 7e 13 b8 01 00 00 00 0f 1f 00 83 c0 01 <48> 8b 12 44 39 e0 75 f5 48 8b 02 48 89 45 00 48 c7 02 00 00 00 00
```

# Package Version:
```
vulkan-intel 19.0.2-1
vulkan-intel 19.0.2-1
vulkan-icd-loader 1.1.101-1
lib32-vulkan-icd-loader 1.1.101-1
mesa 19.0.2-1
```

**Comment by ttc0419** [comment]
Keep crashing even gperftools and lib32-gperftools are intalled.  Tried to link libtcmalloc_minimal.so.0 to libtcmalloc_minimal.so.4.5.3.

**Comment by kisak-valve** [comment]
Hello @Galaxy0419, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/303. Closing as a duplicate.
