### ISSUE TITLE
[Linux][OpenGL/Vulkan] Missing fonts

### ISSUE THREAD

**Issue by astroty** [ValveSoftware/Dota-2#1588]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.githubusercontent.com/astroty/056066d800d1e4814c984aec7b534f90/raw/2fa463c6231334680b5ee076f44c7c8a4c33d89a/system.txt
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Fonts are gone. Tried both OpenGL and Vulkan without success
![image](https://user-images.githubusercontent.com/1356321/56519955-a480c100-6519-11e9-843e-52ca13cf6687.png)

Last time played was on Saturday. So I decided to rollback to one of my earlier snapshots (btrfs) to verify if it wasn't a system update-related breakage. Game worked up until I commited this OS update:
https://gist.github.com/astroty/b5d887a23121a033e36534ac6d5f68dd

Dota terminal log included in that link

**Comment by kisak-valve** [comment]
Most likely a distro packaging issue with multilib/steam-manjaro-1.0.0.59-1, the same as https://github.com/ValveSoftware/csgo-osx-linux/issues/2074 and related to https://bugs.archlinux.org/index.php?do=details&task_id=62095.

**Comment by kisak-valve** [comment]
Can you include the full stdout log including Steam's startup? In particular, I'd like to know if the Steam runtime is enabled and if you have the `steam-native` package installed. If you have that package installed please remove it or try completely closing Steam, then running `STEAM_RUNTIME=1 steam` from a terminal and retesting. (from https://forum.manjaro.org/t/cs-go-no-text-being-rendered/84245/8)

**Comment by astroty** [comment]
Yeah, I somehow missed the steam-native package during my testing, thinking I had tested with and without it and with and without the runtime active. Apparently I was wrong.

Anyway, I got a log of Steam and dota running with steam-native installed and STEAM_RUNTIME=0

[steamlog.txt](https://github.com/ValveSoftware/Dota-2/files/3105131/steamlog.txt)

I noticed these two errors here

> ERROR: ld.so: object '/usr/lib/libgio-2.0.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib/libglib-2.0.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

Which then led me to find this commit made around one week ago

https://gitlab.manjaro.org/packages/multilib/steam-manjaro/blob/master/0003-manjaro-steam-native.patch

Wanting to see if this was indeed the problem, I did

`STEAM_RUNTIME=1 LD_PRELOAD="/usr/lib/libgio-2.0.so.0 /usr/lib/libglib-2.0.so.0" steam`

Which booted up steam just fine, but gave me the broken font rendering. So yeah, it's an issue with Manjaro packaging after all. They tried to fix the web thingy and in doing so, broke something else.

**Comment by kisak-valve** [comment]
Thanks for retesting, that makes this not a Dota issue and needs to be resolved by the package maintainer.

Closing because all dependency issues must be resolved by the distro's package maintainer for Steam if the Steam runtime is disabled.
