### ISSUE TITLE
Network information overlay won't hide when the game is over

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#159]
When the network information overlay option is enabled, the overlay stays active when the game is ended, and the rest of the UI is hidden. Not sure if intended.

![Picture of the issue](http://i.imgur.com/PoGMES0.png)

Specs:

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x2a
>     CPU Stepping:  0x7
>     CPU Type:  0x0
>     Speed:  3800 Mhz
>     8 logical processors
>     4 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     "Arch Linux" (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.0.6-1-ARCH
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11702000
>     X Window Manager:  <Unknown>
>     Steam Runtime Version:  steam-runtime-release_2015-01-06
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce 8400GS/PCIe/SSE2
> 
>    Driver Version:  3.3.0 NVIDIA 340.76
>      OpenGL Version: 3.3
>      Desktop Color Depth: 24 bits per pixel
>      Monitor Refresh Rate: 60 Hz
>      VendorID:  0x10de
>      DeviceID:  0x10c3
>      Number of Monitors:  1
>      Number of Logical Video Cards:  1
>      Primary Display Resolution:  1920 x 1080
>      Desktop Resolution: 1920 x 1080
>      Primary Display Size: 20.91" x 11.77"  (23.98" diag)
>                                              53.1cm x 29.9cm  (60.9cm diag)
>      Primary Bus: PCI Express 16x
>      Primary VRAM: 128 MB
>      Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Realtek ALC889
> 
> Memory:
>     RAM:  7946 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  1511771 Mb
>     Largest Free Hard Disk Block:  164864 Mb
> 
> Installed software:
> 
> Recent Failure Reports:
>     Sun Jun 28 17:10:47 2015 GMT: file ''/tmp/dumps/crash_20150628190738_1.dmp'', upload yes: ''CrashID=bp-53b10e97-5253-404d-a805-8454f2150628''

**Comment by gdrewb-valve** [comment]
Probably not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
I passed this on the larger team and they said it's supposed to do this.
