### ISSUE TITLE
Dota Running on Steam but not Launching

### ISSUE THREAD

**Issue by WaelT** [ValveSoftware/Dota-2#1590]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/WaelT/f4814730d419514f5de038511e0f4e5c
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. 
https://gist.github.com/WaelT/66bff57bb5ea8ab7d6a0c1553f50278e

#### Steps for reproducing this issue:

1. Install Steam
2. Install Dota2
3. Launch Dota2

**Comment by kisak-valve** [comment]
Hello @WaelT, this issue tracker is limited to the Mac and Linux clients of Dota 2. You'll want to post this at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/en/) for the larger Dota 2 team.
