### ISSUE TITLE
Chat wheel always go to Right

### ISSUE THREAD

**Issue by Apple-Lion** [ValveSoftware/Dota-2#1591]
#### Your system information

https://gist.github.com/Apple-Lion/0702c1db84218767977aea18b3ca368c

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

When you press chat wheel, you should be able to use it, but it doesnt work.  The error is still here for the past five years. Multiple computers.  Any sane persion would expect this to be fixed by now.
It is identical to error 128, except it goes to the right.

#### Steps for reproducing this issue:

1. Open Dota on any multiple setup with 3 monitors in linux or windows 10, this is a new system with completely new hardware and the same issue as i had a year ago on an older system.
2. Play Dota
3. Use Chat wheel
4. Watch mouse go off screen to the right and only activate the 3pm chat.

**Comment by kisak-valve** [comment]
Hello @Apple-Lion, this reads like the same issue as #1201 / #1448, but with a different monitor configuration. Closing in favor of the existing issue reports.
