### ISSUE TITLE
Freeze during shut down

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/Dota-2#1592]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/amitavmohanty01/85a7976cee129ed50892cfeb0025be7c
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I shut down Dota 2, it freezes for some time then shuts down.

Xorg version: 1.20.4-1

The mini dump is attached
[dumps.zip](https://github.com/ValveSoftware/Dota-2/files/3144464/dumps.zip)

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, this issue is already being tracked at #1390. Closing as a duplicate.
