### ISSUE TITLE
keyboard doesn't work if my keyboard layout was set to a language that doesn't use latin script at the moment of launching the game

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Dota-2#1594]
#### Your system information

* System information from steam :
https://gist.github.com/aligodlike/2687921cf50fa289539ce4b3e79b2997
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
keyboard doesn't work if my keyboard layout was set to a language that doesn't use latin script at the moment of launching the game

#### Steps for reproducing this issue:

1. set keyboard layout to something like "persian"
2. open dota 2 and start a game and keyboard doesn't work

**Comment by kisak-valve** [comment]
Hello @aligodlike, this reads like #792. Does the setting mentioned there help?

**Comment by Weirdo1312** [comment]
> Hello @aligodlike, this reads like #792. Does the setting mentioned there help?

yes it just fixed
ty
