### ISSUE TITLE
Dota2 on Macbook Crashes when Launching Games

### ISSUE THREAD

**Issue by SwagDad** [ValveSoftware/Dota-2#1596]
I have a Macbook Pro and now can not join matches after downloading the 2019 Battle Pass. I have no clue what to do, and I'm hoping someone with more knowledge who's having the same problems can lead me to a solution. Cheers.

**Comment by kisak-valve** [comment]
Hello @SwagDad, #1597 came in a few minutes after your issue report with the same symptoms, but has a bit more information, so let's track this issue there. Closing in favor of #1597.
