### ISSUE TITLE
[PC] random game crashes 

### ISSUE THREAD

**Issue by Velthari** [ValveSoftware/Dota-2#1599]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Velthari/a4e2af8ac59d267b369b8889ccbef8f4): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#1 Game can crash on launch goes to white screen and eventually starts running.
#2 Game Randomly Crashes. Can run for 10 seconds, can run for 2 days with out any crash but mainly crashes about 1-4 times a game.

Have tried reinstalling windows
Updated all drivers
reinstalled game
tried dx9 dx11 opengl and vulkan crashes the same on all of them

#### Steps for reproducing this issue:

1. Open game 
2. ???
3. Crash

**Comment by kisak-valve** [comment]
Hello @Velthari, this issue tracker is limited to the Mac and Linux port of the Dota 2 client. You'll want to post this on https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/en/) for the larger Dota 2 team.

Closing as out-of-scope.
