### ISSUE TITLE
alsa buffer underun

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#160]
Sometimes I get crunchy alsa sound output, which I could solve with dota2 source 1 using the console command "snd_restart 1".
Since the console is "empty" in reborn, I cannot restart the sound system to clear the buffer underrun.

**Comment by presianbg** [comment]
#126 Duplicate ?

**Comment by sylware** [comment]
after reading the comments, yes, it seems to be related
to the same issue. I posted a comment over there.
