### ISSUE TITLE
Dota client crashes when `command` + `q` or `command` + `w` was pressed.

### ISSUE THREAD

**Issue by brianbodollo** [ValveSoftware/Dota-2#1600]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/brianbodollo/3a3153029d32fd64bf3f3b37c1325b22
* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
**It shouldn't close the Dota client after pressing `command` + `q` or `command` + `w`. As a player who uses these hotkeys, it really is a bother.** 

#### Steps for reproducing this issue:

1.  Launch Dota 2.
2. When you entered the game, press `command` + `q` or `command` + `w`.
3. It should quit the game after doing so.

**Comment by kisak-valve** [comment]
Hello @brianbodollo, these are system-wide keyboard shortcuts on Mac to close an applications. #1536 is tracking this issue and I've adjusted it to make it more discoverable. Closing as a duplicate.
