### ISSUE TITLE
[linux] poor performance in the new versus screen 

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Dota-2#1607]
#### Your system information

* System information from steam
https://gist.github.com/aligodlike/3720815029a4c5c4d01d58dcf45d9dc8
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
poor performance in the new versus screen (especially on the radiant screen)
i tested it on gtx 970 with the newest nvidia proprietary driver with both vulkan and opengl
and intel hd 4600 with latest mesa driver
and problem did exist on every one of them

#### Steps for reproducing this issue:

1. open dota 2
2. find a match
3. wait for the versus screen

**Comment by Weirdo1312** [comment]
after ending the versus screen performance goes normal

**Comment by glubsy** [comment]
Perhaps you should give more details about what you call "poor performance". Is it a big frame-per-second decrease compared to during the game?

On my side, these new screens do seem to have a very slight performance hit, my GPU temps tend to go a bit higher than during the game but the frames per second are overall the same.

Not really fond of these new versus screens anyway, I preferred the previous ones. ;)

Current system information: [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/bfb094255a0435a903c0f608a291009a6220251b)

**Comment by Weirdo1312** [comment]
> Perhaps you should give more details about what you call "poor performance". Is it a big frame-per-second decrease compared to during the game?
> 
> On my side, these new screens do seem to have a very slight performance hit, my GPU temps tend to go a bit higher than during the game but the frames per second are overall the same.
> 
> Not really fond of these new versus screens anyway, I preferred the previous ones. ;)
> 
> Current system information: [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/bfb094255a0435a903c0f608a291009a6220251b)

when it goes to versus screen it starts stuttering and fps goes low when it ends everything goes back to normal

**Comment by Weirdo1312** [comment]
for some reason this does not happen anymore i'm not sure if it's because of dota2 updates or because of downloading pre-Caching content from steam but this does not happen anymore, GOOD.

**Comment by kisak-valve** [comment]
Closing per the last comment. If you encountered a testing fluke and this is not the case, let me know and I can re-open.
