### ISSUE TITLE
Linux Keyboard Issue

### ISSUE THREAD

**Issue by OlegEryomin** [ValveSoftware/Dota-2#1611]
When you start dota 2, you must set the English keyboard layout. It would not be bad if dota itself checked the layout before launch.

**Comment by kisak-valve** [comment]
Hello @OlegEryomin, what keyboard layout are you using and does going to the in-game settings -> Advanced hotkeys -> enable `Bind keys based on keyboard position` help with how you're trying to configure the game?

**Comment by OlegEryomin** [comment]
> Здравствуйте @OlegEryomin , какую раскладку клавиатуры вы используете и переходите к игровым настройкам -> Расширенные горячие клавиши -> Включить `Bind keys based on keyboard position`справку о том, как вы пытаетесь настроить игру?

**Comment by OlegEryomin** [comment]
Hello kisak-valve !!! 
Linux, unlike Windows, does not perceive the position of a button, but its value. If I use the Russian keyboard layout to enter the game, it will not recognize the position of the keys, but will recognize their meaning. It would not be bad if the developers made a layout check before entering the game or at least warned about it because all Linux users using it use two or more keyboard layouts, often they don’t understand what their problem is and stop playing this beautiful game. Thank.
