### ISSUE TITLE
Some ability icons become transparent when leveling up

### ISSUE THREAD

**Issue by anko** [ValveSoftware/Dota-2#1615]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/anko/e9d5043ddad2356d8f6ee12e53d8c57f
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes] (430.14)
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

When a hero levels up and gains a skill point, some of the ability icons become transparent.

![shot](https://user-images.githubusercontent.com/5231746/59160112-59733b00-8ad2-11e9-8748-79deb6971817.png)

If any of the affected abilities are used, the icon flickers rapidly during the cooldown.

This happens on both Vulkan and OpenGL graphics modes, with or without cosmetics, with and without X11 compositing enabled. It happens with the same regularity even if I restart the game or OS.

Non-ability icons are unaffected.

#### Steps for reproducing this issue:

1. Load into demo mode as any hero.
2. Put a skill point into any ability.
3. Press the level up button.

It always happens to a seemingly random number of abilities, so sometimes you'll have to repeat steps 2 and 3 a few times.

**Comment by jaroslawksiezuk** [comment]
In my case this happens only on Vulkan

Vulkan Instance Version:
1.1.101

System information from steam:
https://gist.github.com/J-a-r-e-k/88160417afb76ef9ebfdb0698b44dca2

Images:
https://imgur.com/a/D0Axykg

**Comment by anko** [comment]
Found [a Reddit thread with a Windows user also seeing this bug](https://www.reddit.com/r/DotA2/comments/ccnjbh/summer_scrub_two_small_bugs/).

**Comment by glubsy** [comment]
I have been experiencing this issue or a few weeks to, but only with the Vulkan renderer. This doesn't happen with OpenGL.

The video posted in that reddit thread illustrates the problem very well.

[Specs](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/36f04ab1d7dda412cc1d2b86cb519308b15e57d6).

**Comment by anko** [comment]
I haven't seen this issue anymore, for so long that I forgot it existed, so I will close this. If anyone still sees this, please comment.
