### ISSUE TITLE
Stopped opening with vulkan

### ISSUE THREAD

**Issue by josinaldobarbosa** [ValveSoftware/Dota-2#1620]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/josinaldobarbosa/2ec12518f88195e786b47ec7d7c9c5f4
* Have you checked for system updates?: [Yes/No] yes
* Are you using the latest stable video driver available for your system? [Yes/No] no
* Have you verified the game files?: [Yes/No] yes

#### Steps for reproducing this issue:

The game does not open but I see that it is as "running" in steam(and process)
forced to open with -gl and worked

**Comment by kisak-valve** [comment]
Hello @josinaldobarbosa, this issue is already being tracked at #1619. Closing as a duplicate.
