### ISSUE TITLE
[Linux] Can't Launch with Vulkan.

### ISSUE THREAD

**Issue by SuperCashMash** [ValveSoftware/Dota-2#1621]
#### Your system information

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 2700X Eight-Core Processor         
    CPU Family:  0x17
    CPU Model:  0x8
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3700 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 19.1 Tessa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  X.Org Radeon RX Vega (VEGA10, DRM 3.27.0, 5.0.0-16-generic, LLVM 9.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.2.0-devel - padoka PPA
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x1002
    DeviceID:  0x687f
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.54" x 13.23" (26.97" diag)
                                            59.8cm x 33.6cm (68.5cm diag)
    Primary VRAM: 8176 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16026 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  468426 Mb
    Largest Free Hard Disk Block:  382612 Mb
    VR Headset: None detected

Recent Failure Reports:

#### Please describe your issue in as much detail as possible:

Well, what should happen is that the game should launch. xD

What happens is that Steam says it's running, but it never even gets to the logo. Sometimes, an error flashed. I managed to capture it once:

"AllocInternal(): 
CUtlLinkedList overflow! (exhausted memory allocator)"

The game runs fine if I run it on "-gl", but Vulkan seems to have an issue.

 At first, I thought it was my drivers since I had some problems installing the 5.0.0.16 kernel, but I removed all my graphics drivers, installed the kernel and then reinstalled the recommended ones for SteamPlay (I run this game on native, but have other games that require the feature). I haven't had a problem with the computer since.

Another thing worth noting is that the game worked fine with Vulkan just yesterday. I also tried Doom 2016 on Vulkan and it still worked. I tried a native game (Talos Principle) and it worked as well, so I don't think it's my drivers this time around.

I have the Vulkan support package checked and installed, I have also tried fresh installing Dota and I have tried restarting the computer. The problem persists.

#### Steps for reproducing this issue:

1. Launch with "-vulkan" as a launch option

Also, I checked some other threads where it didn't start, but I couldn't find one with the relevant issue that hadn't been resolved by something I already mentioned. Still, apologies if a report like this already exists.

Thank you!

**Comment by kisak-valve** [comment]
Hello @SuperCashMash, this issue is already being tracked at #1619 / https://github.com/ValveSoftware/Dota-2-Vulkan/issues/311. Closing as a duplicate.

Adding `-vulkan_disable_steam_shader_cache` to the game's launch options should workaround this issue.

**Comment by nascheme** [comment]
Try cleaning the shadercache:
```
cd <STEAMAPPS>
find shadercache -type f -print0 | xargs -0 rm
```
Be careful to run that in the correct folder.
