### ISSUE TITLE
Dota2 process is starting, but the game is not runnig in foreground

### ISSUE THREAD

**Issue by todorvelichkov** [ValveSoftware/Dota-2#1623]
#### Your system information

* [System information from steam](https://gist.github.com/todorvelichkov/2b1084148b881458330f3681fbd86d6f)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? No: using Nvidia 418, but there also seems to be 430, haven't tested that one.
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
This is a problem which happens last night, no such issues before that. The game starting in background (according to Steam and OS) and cannot turn it into foreground.

When I start the game I expect to see the game window, but nothing is showing up. Steam reports that the game is already running and the OS have a dota2/dota.sh process which is using 1GB of memory w/o any CPU usage.

I've tried to kill the process and run the game again, no effect. I've tried restarting the machine, no effect. System is up to date.

#### Steps for reproducing this issue:

1. Start Steam
2. Click Play on Dota2

Note: I don't have any special startup options
Note2: I've no such issues in CS:GO.

**Comment by kisak-valve** [comment]
Hello @todorvelichkov, this reads like the issue being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/311. Adding `-vulkan_disable_steam_shader_cache` or `-gl` to the game's launch options should workaround this issue while we wait for the next Dota 2 update.

Closing as a duplicate.

**Comment by todorvelichkov** [comment]
Yes I can confirm adding `-gl` help. Thank for the help, and sorry for not finding this already open issue.
