### ISSUE TITLE
[macOS] Random crashes during online game

### ISSUE THREAD

**Issue by christopherkerry** [ValveSoftware/Dota-2#1625]
Your system information: https://gist.github.com/christopherkerry/a81fcda7d57784b4e67e502e73c0ad0a

* Have you checked for system updates?: YES
* Are you using the latest stable video driver available for your system? YES
* Have you verified the game files?: YES

Please describe your issue in as much detail as possible:
Dota randomly crashes during online play.  Straight to the desktop, without warning.  The odd game completes without any issues.  Occurs when using Vulkan and Open GL on lowest settings.  Occurs when running dual screen + single screen with external monitor, and also when running natively on the MacBook.   Seems to happen more often when playing versus heroes with illusions or detailed animations - but cannot confirm.

#### Steps for reproducing this issue:

1. Install Dota 2 on Mojave 10.14.5
2. Turn all video settings off, other than additive light pass, texture quality (medium), shadow quality (medium).
3. Join online game.

**Comment by kisak-valve** [comment]
Hello @christopherkerry, this issue is already being tracked at #1624. Feel free to add your findings there. Closing as a duplicate.
