### ISSUE TITLE
[Linux] Dota 2 fails to start - Error StartupSubsystems()

### ISSUE THREAD

**Issue by grandon** [ValveSoftware/Dota-2#1626]
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [System Information](https://gist.github.com/grandon/d03fb097b81b64cbf4757b0c874d5c67#file-steam-system-information-txt)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 fails to start from a SteamLibrary on a NTFS partition with the following message:

```
StartupSubsystems():
Panorama requires a full rendersystem, please check your launch options
```
![image](https://user-images.githubusercontent.com/65187/59983597-dac5e400-9621-11e9-8bf3-d4a72b49a92d.png)

Complete reinstall was performed and game files were verified. Running Dota 2 from my ext4 partition works fine. Other games, like Dota Underlords are starting from the NTFS partition.

#### Steps for reproducing this issue:

1. Install Dota 2 on a NTFS partition
1. Start Dota 2

**Comment by kisak-valve** [comment]
Hello @grandon, as noted in the error message, do you have any launch options set for the game? Does adding `-gl` or `-vulkan` to the game's launch options have an effect?

**Comment by ryanleecode** [comment]
Running with `-vulkan` works for me

**Comment by grandon** [comment]
Hey @kisak-valve, no launch options were set.

I have now reinstalled it on the NTFS partition.
The option `-gl`, as well as `-vulkan` are both working!

It seems that this issue not related to the file system... Setting up a different steam library on my ext4 partition with the game content of the NTFS partion results in the same issue, where either `-vulkan` or `-gl` must be set.

The installation on the ext4 partition was completely fresh and does not require any launch options to work, while the one on the NTFS partition was initially installed a long time ago on Windows.

Additionally, I tried to activate the "Dota 2 - Vulkan support" checkbox and no launch options, which had no effect other than a ~300MB download done.
![image](https://user-images.githubusercontent.com/65187/60051450-516eea00-96d3-11e9-93f6-f9ef52c80902.png)

Thank you for the support!

**Comment by grandon** [comment]
Alright, so without launch options it will use OpenGL.
![image](https://user-images.githubusercontent.com/65187/60055735-e3302480-96de-11e9-82df-e86374dbb446.png)
If I set `-vulkan` in the launch options it stays on OpenGL.

The DLC is required for Vulkan to work and either use the launch option `-vulkan` or select it in the drop down box in the settings menu:
![image](https://user-images.githubusercontent.com/65187/60055847-373b0900-96df-11e9-83fa-832fd27791f2.png)

Thought I might leave this here for other users. Big thanks to Valve for supporting Linux!

**Comment by kisak-valve** [comment]
Thanks for testing @grandon, sounds like Dota 2 was configured to start with Vulkan without the Vulkan support downloaded, most likely as a side-effect from the shared Steam library content between OSes. Cross-OS Steam libraries are not supported as noted in https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md and can lead to unexpected behavior.

**Comment by Ulti-FD** [comment]
Why is this closed? This is still an issue. Sure, opening the game with -gl (or -vulkan after downloading the vulkan dlc) works just fine, but why should you have to do this in the first place? The game should at the least default to opengl (on linux/mac at least, I don't think this is an issue on win). Making the user _have to_ look up the _known_ problem instead of just implementing the solution in the game by default is really not that great.

**Comment by skorpions2000** [comment]
What is the problem in Linux? Don't work in Linux...
