### ISSUE TITLE
Almost every 5 member party we get bots. Can we disable this somehow? I typed in dota_bot_disable 1 and it didn't help. Its really not fun playing bots during party games. This is in turbo mode.

### ISSUE THREAD

**Issue by iamdarkmatter** [ValveSoftware/Dota-2#1627]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @iamdarkmatter, this issue tracker is limited to issues with the Mac and Linux port of Dota 2 client. This sounds like feedback to give to the larger Dota 2 team at https://dev.dota2.com.
