### ISSUE TITLE
Game history missing games

### ISSUE THREAD

**Issue by sg4rb0** [ValveSoftware/Dota-2#1629]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  4500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.1.9-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.26
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 100 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3440 x 1440
    Desktop Resolution: 3440 x 1440
    Primary Display Size: 31.42" x 13.19" (34.06" diag)
                                            79.8cm x 33.5cm (86.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1220

Memory:
    RAM:  24061 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  375695 Mb
    Largest Free Hard Disk Block:  267898 Mb
    VR Headset: None detected

Recent Failure Reports:

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
At the end of my last game it said something along the lines of, high load bla bla bla.  The game has not showed up in my history.  This also happened 2 games ago when I played ursa.  So out of the last 3 games I played, only one of them have showed up in my history.  I really need this sorting because I need that mmr.

#### Steps for reproducing this issue:

1.  play the game
2. wait for it to say something along the lines of high load after you win
3. game wont show

**Comment by kisak-valve** [comment]
Hello @sg4rb0, this doesn't sound like an issue with the Linux client. You'll want to post this on https://dev.dota2.com for the larger Dota 2 team.
