### ISSUE TITLE
Black sky in showcase view, spectator mode

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#163]
When spectating a game in "showcase view", the sky appears black. There is no bluish fog, contrarily to the showcase view from a player perspective (i.e., not a spectator). 
This is regardless of the time of day. 
Note also that the viewing distance is greater since there is no fog (but I don't see that as an issue). At some point everything becomes black, abruptly. 

EDIT : this may be intended behavior. After all there is no reason to limit the view distance of spectators (if not for performance reasons), hence the absence of fog. However, it would be better if the sky reflected the time of day (blue with a few clouds during daytime, and black with stars at night).

**Comment by gdrewb-valve** [comment]
This isn't Linux/Mac-specific so I've passed this on to the larger team.
