### ISSUE TITLE
[Linux] Error after today update (YieldWait) - 06.07.2019

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#1631]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/AngryPenguinPL/26dfb99ecc693e0bff1260ae754c9e9e/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
After today update (06.07.2019) dota2 start but when game "menu" appears, it displays a prompt about error - like in screenshot. Look 
![Screenshot_20190706_215036](https://user-images.githubusercontent.com/3121142/60761178-94ba4880-a043-11e9-8cfb-105e8904a377.png)

When I click ok, dota closes and goes to the desktop.

#### Steps for reproducing this issue:

1.  Install today update
2.  Run and see error message
3.  Cry xD

**Comment by gdrewb-valve** [comment]
Is this still happening with the latest Dota update?

**Comment by AngryPenguinPL** [comment]
It is fixed now.
Thanks.
