### ISSUE TITLE
loopback & invalid file references

### ISSUE THREAD

**Issue by davidmproia** [ValveSoftware/Dota-2#1632]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
[https://gist.github.com/davidmproia/257a5514c18cbf33f029b3a530bfd2d0](url)

* Have you checked for system updates?: [Yes/No]
Yes

* Are you using the latest stable video driver available for your system? [Yes/No]
Yes

* Have you verified the game files?: [Yes/No]
Yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Issue is constant disconnects right as games are ending. Also, it seems sometimes people auto-invite me and they play against me or will start writing on my screen as scribbles and then dc me at end of game. I will log on to game and will have bans that aren't from me as I haven't left/dc but maybe 1 game in a year+. Most times I have issues hearing people chatting and they are not blocked. My game from the log files wants to run scripts when it starts up. I put down the current log information as when I look it seems like I'm part of a few chat groups with invites I cannot revoke that I didn't initiate.

1) models/props_gameplay/ti9_consumables_monkey.vmdl
[Particles] WARNING: Particle system 'particles\econ\events\ti9\ti9_monkey_clap.vpcf' with missing path was not found in existing particle system list.

(No monkey king in fight or i don't know what that means)

2)
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [19] addons []
[ResourceSystem] Error loading resource file "panorama/images/heroes/npc_dota_hero_base_png.vtex_c" (Error: ERROR_FILEOPEN)

3)
Groups from which console shows after match ended. 

[Server] SV:  Sending server info to client 'idgaf' at loopback:0
[Server] SV:  WriteInitialSpawnGroups sending 1 groups

#### Steps for reproducing this issue:

1.  Log on and start of every game
2.  Cheats seem to load upon game as well which I didn't authorize and I was referencing https://developer.valvesoftware.com/wiki/List_of_DOTA_2_Cvars
3.  File does not exist as only place it looks like it would go is core but there is not an images directory.

**Comment by kisak-valve** [comment]
Hello @davidmproia, this issue tracker is limited to the Mac and Linux clients of Dota 2. You'll want to post this on https://dev.dota2.com for the larger Dota 2 team.
