### ISSUE TITLE
My compendium level is stop to grow up

### ISSUE THREAD

**Issue by Fawkes23Rus** [ValveSoftware/Dota-2#1633]
After lst update with the mo'rokay i have played few mo'rokay games, then i earned battle points, but after next mo'rokay game my battle pass level has been stoped to changed as like battle points count too. even if my week mo'rokay points limit has been ended, i didn't receive points even with treasures in the game.
p.s. when each game been ended, i saw the message about added battle points to my battle pass level, but with closing it and going to battle pass from main menu here is was not changes. 
p.s.s. steam reboot didn.t helps me as like just dota reboot
can u help me with that and return broken points?

here is my profile link - https://steamcommunity.com/id/Freetovan/
dota 2 id - 129954493

my OS is - Win 10 Home x64

**Comment by kisak-valve** [comment]
Hello @Fawkes23Rus, this issue tracker is limited to Mac and Linux client issues with Dota 2. Account issues are not handled here.

You'll want to post this on [Steam Support](https://help.steampowered.com/) or https://dev.dota2.com for the larger Dota 2 team.
