### ISSUE TITLE
Vulkan API Performance Issues on macOS [constant fps drops and crashes]

### ISSUE THREAD

**Issue by rohanharikr** [ValveSoftware/Dota-2#1635]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro15,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.14.5 (64 bit)

Video Card:
    Driver:  Intel Iris Plus Graphics 655
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x3ea5
    Revision:  0x1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.22" x 7.05" (13.23" diag)
                                            28.5cm x 17.9cm (33.6cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  239072 Mb
    Largest Free Hard Disk Block:  107238 Mb
    VR Headset: None detected

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Just performance issues

**Comment by kisak-valve** [comment]
Hello @rohanharikr, there are some issue reports that are already tracking this (#1618 / #1624 / https://github.com/ValveSoftware/Dota-2-Vulkan/issues/308). Closing in favor of the existing issue reports.
