### ISSUE TITLE
[OS X] Segfault on Startup

### ISSUE THREAD

**Issue by madjak5** [ValveSoftware/Dota-2#164]
On starting DOTA 2 Reborn from the menu, the game will appear to load before abruptly closing.
The console output:

6/28/15 8:58:37.511 PM [0x0-0x4f74f7].com.valvesoftware.steam: /Users/hellbender123/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 98: 43614 Segmentation fault: 11  ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

6/28/15 8:58:37.560 PM ReportCrash: Saved crash report for bash[43614] version ??? (???) to /Users/hellbender123/Library/Logs/DiagnosticReports/bash_2015-06-28-205837_Connors-MacBook-Air.crash

Crash report contents: 

Process:         bash [43614]
Path:            /bin/bash
Identifier:      bash
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  bash [43611]

Date/Time:       2015-06-28 20:58:37.180 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9
Sleep/Wake UUID: 33A60817-3B1E-4B36-ADE6-58241D0ECFBA

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4092342
    thread_create: 0
    thread_set_state: 0

**Comment by nickmunson** [comment]
***** I get 7 console messages every time I attempt to launch Dota 2 Reborn Beta that appear in the same order and with the same timing. *****

6/28/15 9:30:24.625 PM [0x0-0x1e01e].com.valvesoftware.steam: Game update: AppID 570 "Dota 2", ProcID 522, IP 0.0.0.0:0
6/28/15 9:30:24.783 PM ReportCrash: Failed to create CSSymbolicatorRef for bash[525]
6/28/15 9:30:24.891 PM ReportCrash: Failed to create dSYM-less CSSymbolicatorRef for bash[525]
6/28/15 9:30:25.002 PM [0x0-0x1e01e].com.valvesoftware.steam: /Users/johndoe/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 98:   525 Segmentation fault: 11  ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
6/28/15 9:30:25.039 PM ReportCrash: Saved crash report for bash[525] version ??? (???) to /Users/johndoe/Library/Logs/DiagnosticReports/bash_2015-06-28-213025_Computer_Name.crash
6/28/15 9:30:26.896 PM [0x0-0x1e01e].com.valvesoftware.steam: Game removed: AppID 570 "Dota 2", ProcID 522 
6/28/15 9:31:27.011 PM com.valvesoftware.steam.ipctool: Error: ClaimLock by [304] on already claimed lock [304]: /BSem/d5664012 [SteamChrome_ClientStream_304_13565952_server_written.BinSemLock]

***** The crash report mentioned in the 5th message contains the following: *****

Process:         bash [525]
Path:            /bin/bash
Identifier:      bash
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  bash [522]

Date/Time:       2015-06-28 21:30:24.672 -0400
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 573
    thread_create: 0
    thread_set_state: 0

***** The game never appears in the dock, and presents no windows. My status does briefly change to 'Playing Dota 2 Reborn Beta' before returning to just 'Online'. *****

**Comment by gdrewb-valve** [comment]
The crash report doesn't have enough info to determine what the problem is here, so we'll have to wait and see if it presents in some other way.

**Comment by gdrewb-valve** [comment]
Actually on looking at this again I see you're running on 10.7.  The beta requires 10.9 or above.
