### ISSUE TITLE
Kernel panic on MacOS 10.10.5

### ISSUE THREAD

**Issue by kotoOo** [ValveSoftware/Dota-2#1643]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/kotoOo/b1ae44d13955fe0499f844e28840a446
* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:

System freezes after 1 min in game, showing kernel panic screen, then reboots. Sure there was no such issues two days before, sure I've got nothing changed in software / hardware config of the machine, SO it's totally because of recent update, and there are 40 people on Steam's forum with the same problem - everyone running Yosemite or El Captain.

Please, stop referring to video drivers or something else - the game WAS working and now it's NOT. And reviews like "Probably duplicate of #..." are not helping too. You just cannot roll on such an unstable patches for the AAA class game, guys!!!

What can help? Please, find the one who is responsible for patches last 48 hours and ask him, what it was! Rollback the patches and ask him to do the job good again. Save the product, because it's unique.

#### Steps for reproducing this issue:

1. Take Macbook Pro 13 running Yosemite, w/o graphics accelerator.
2. Run DOTA 2.
3. See Kunkka dwelling around the map. 1-2 minutes later you'll get a kernel panic screen.

**Comment by cdtapay** [comment]
Possible duplicate: https://github.com/ValveSoftware/Dota-2/issues/1640

**Comment by kotoOo** [comment]
Which is Possible duplicate of #1616... That's fine, then let's do something about this =)

**Comment by Hursofid** [comment]
dupilicate of #1640

**Comment by kisak-valve** [comment]
Hello @kotoOo, this issue is already being tracked at #1642. Closing as a duplicate.
