### ISSUE TITLE
Ring OF Health and Void Stone Duplicate Items in Learn > Items

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#1644]
In Learn > Items Ring of Health and Void stone appear twice, maybe add a test to check that only 1 item exists.

**Comment by kisak-valve** [comment]
Hello @gselsidi, this issue tracker is for issues with the Mac and Linux Dota 2 clients and this doesn't read like an OS-specific issue. You'll want to post this at https://dev.dota2.com for the larger Dota 2 team.
