### ISSUE TITLE
Feature: Allow MatchMaking with both ranked roles and other ranked options.

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#1645]
Would be great if you could queue both options together especially when playing off hours and ranked roles might take a very long time to find a match.

**Comment by kisak-valve** [comment]
Hello @gselsidi, this issue tracker is for issues with the Mac and Linux Dota 2 clients and feature requests are better handled over at https://dev.dota2.com for the larger Dota 2 team to consider.
