### ISSUE TITLE
MAC OSX crashing. Seems better today than previous couple days. July 18th update. Slightl improvement July 22nd.

### ISSUE THREAD

**Issue by sherb2k** [ValveSoftware/Dota-2#1646]
I have had this issue for 4-5 days now. It seems like it has gotten better and I believe the report was different from what I saw in other threads regarding this issue with mac users.

People with mac who cant upgrade to latest os are getting issues. The whole mac restarts. Up until today I would spectate a game and within 1 minute I would crash. Sometimes at the loading screen it would crash before I get a chance to spectate.

Tonight it seems a little better as it would not crash for a couple minutes if you leave it at the loading screen. So I tried to spectate 2 games and it would spectate the game for about 3-5 minutes before crashing now.

The report for these crashes are below.

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/sherb2k/ed6d4032f57faaef9e8357ea89b0fbf7
Mac OSX 10.9 I cant update to newer OS due to hardware being too old.
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Load DOTA
2. Spectate Game
3. Up to 1 min spectating a game and itll crash and restart my mac. 7/18-21
    Up to 5 min spectating a game and itll crash and restart my mac 7/22

It can crash at any moment after you open Dota from steps 1 - 3.

Anonymous UUID:       315BE0BA-B942-085C-EABA-8A5B35ACA43C

Mon Jul 22 22:08:09 2019
Panic(CPU 1): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff802abd1340, spinlock owner: 0xffffff80275f8b20, current_thread: 0xffffff80275f8b20, spinlock_owner_cpu: 0x1
RAX: 0xffffff802e1750b8, RBX: 0x0000000000000001, RCX: 0xffffff802e1750b8, RDX: 0xffffff802e1750b8
RSP: 0xffffff801ee43ec0, RBP: 0xffffff801ee43f70, RSI: 0xffffff802e1750f0, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff801ee43dd0, R11: 0x0000000000000190
R12: 0x00000000fffffffe, R13: 0xffffff802e1750a8, R14: 0xffffff802abd1338, R15: 0xffffff802abd1338
RFL: 0x0000000000000246, RIP: 0xffffff80155c7536, CS:  0x0000000000000008, SS:  0x0000000000000000
Backtrace (CPU 1), Frame : Return Address
0xffffff80be4b6f50 : 0xffffff80152e2cc1 
0xffffff80be4b6f80 : 0xffffff80152dc05f 
0xffffff80be4b6fd0 : 0xffffff80152f4649 
0xffffff801ee43f70 : 0xffffff80155c7a50 
0xffffff801ee43fb0 : 0xffffff80152d7c67 

BSD process name corresponding to current thread: dota2

Mac OS version:
13F1911

Kernel version:
Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64
Kernel UUID: 8926E512-6714-34FC-B27C-6AE90EB51D5E
Kernel slide:     0x0000000015000000
Kernel text base: 0xffffff8015200000
System model name: MacBook5,1 (Mac-F42D89C8)

System uptime in nanoseconds: 5385553428596
last loaded kext at 82239104461: com.apple.driver.AudioAUUC	1.60 (addr 0xffffff7f96979000, size 28672)
last unloaded kext at 2863180645044: com.apple.iokit.IOUSBMassStorageClass	3.6.0 (addr 0xffffff7f95e44000, size 69632)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	6.0.6
org.virtualbox.kext.VBoxNetFlt	6.0.6
org.virtualbox.kext.VBoxUSB	6.0.6
org.virtualbox.kext.VBoxDrv	6.0.6
com.apple.driver.AudioAUUC	1.60
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.iokit.IOUserEthernet	1.0.0d1
com.apple.iokit.IOBluetoothSerialManager	4.2.7f5
com.apple.driver.AppleUpstreamUserClient	3.5.13
com.apple.driver.AGPM	100.14.34
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.GeForceTesla	8.2.4
com.apple.driver.AppleHDA	2.6.3f7
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleMikeyDriver	2.6.3f7
com.apple.driver.AppleBacklight	170.4.11
com.apple.driver.AppleSMCLMU	2.0.4d1
com.apple.driver.AppleHWAccess	1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleLPC	1.7.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.2.7f5
com.apple.driver.AppleMCCSControl	1.2.5
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleIRController	325.7
com.apple.BootCache	35
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeLZVN	1.0.0d1
com.apple.iokit.SCSITaskUserClient	3.6.7
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.6.0
com.apple.driver.AirPort.Brcm4331	700.20.22
com.apple.driver.AppleUSBHub	683.4.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleAHCIPort	3.0.5
com.apple.nvenet	2.0.21
com.apple.driver.AppleUSBEHCI	660.4.0
com.apple.driver.AppleUSBOHCI	656.4.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	2.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	217.92.1
com.apple.security.quarantine	3
com.apple.nke.applicationfirewall	153
com.apple.driver.AppleIntelCPUPowerManagement	217.92.1
com.apple.iokit.IOSurface	91.3
com.apple.iokit.IOSerialFamily	10.0.7
com.apple.AppleGraphicsDeviceControl	3.6.22
com.apple.iokit.IOBluetoothFamily	4.2.7f5
com.apple.nvidia.classic.NVDANV50HalTesla	8.2.4
com.apple.nvidia.classic.NVDAResmanTesla	8.2.4
com.apple.driver.DspFuncLib	2.6.3f7
com.apple.vecLib.kext	1.0.0
com.apple.iokit.IOAudioFamily	1.9.7fc2
com.apple.kext.OSvKernDSPLib	1.14
com.apple.driver.AppleBacklightExpert	1.0.4
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleHDAController	2.6.3f7
com.apple.iokit.IOHDAFamily	2.6.3f7
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.IOPlatformPluginFamily	5.7.1d6
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.2.7f5
com.apple.driver.AppleSMBusController	1.0.12d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleSMC	3.1.8
com.apple.kext.triggers	1.0
com.apple.driver.AppleUSBMultitouch	240.10
com.apple.iokit.IOUSBHIDDriver	660.4.0
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.6.7
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.driver.AppleUSBMergeNub	650.4.0
com.apple.driver.AppleUSBComposite	656.4.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.6.7
com.apple.iokit.IO80211Family	640.36
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOUSBUserClient	660.4.2
com.apple.iokit.IOAHCIFamily	2.6.5
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOUSBFamily	686.4.1
com.apple.driver.NVSMU	2.2.9
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.TMSafetyNet	7
com.apple.security.sandbox	278.11.2
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOReportFamily	23
com.apple.driver.DiskImages	373
com.apple.iokit.IOStorageFamily	1.9
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	2.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
panic(cpu 0 caller 0xffffff80155c65b5): "Spinlock acquisition timed out: lock=0xffffff802abd1340, lock owner thread=0xffffff80275f8b20, current_thread: 0xffffff8025250b20, lock owner active on CPU 0x1, current owner: 0xffffff80275f8b20"@/SourceCache/xnu/xnu-2422.115.15/osfmk/i386/locks_i386.c:365
Backtrace (CPU 0), Frame : Return Address
0xffffff80c589bd90 : 0xffffff8015223139 
0xffffff80c589be10 : 0xffffff80155c65b5 
0xffffff80c589bf20 : 0xffffff80155c64c4 
0xffffff80c589bf50 : 0xffffff8015641983 
0xffffff80c589bfb0 : 0xffffff80152f4c86 

BSD process name corresponding to current thread: dota2
Model: MacBook5,1, BootROM MB51.007D.B03, 2 processors, Intel Core 2 Duo, 2 GHz, 5 GB, SMC 1.32f8
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142323837344448312D4346382020
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1067 MHz, 0x830B, 0x4E54344743363442384847304E532D444920
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WD2500BEVT-00ZCT0, 250.06 GB
Serial ATA Device: HL-DT-ST DVDRW  GS21N
USB Device: Built-in iSight
USB Device: USB OPTICAL MOUSE
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
Thunderbolt Bus:

**Comment by kisak-valve** [comment]
Hello @sherb2k, this issue is already being tracked at #1642. Feel free to add your findings to that issue report. Closing as a duplicate.
