### ISSUE TITLE
Feature Request: Console Command to Close Box in Upper Right Corner of Replay

### ISSUE THREAD

**Issue by RylanSchaeffer** [ValveSoftware/Dota-2#1648]
This is a feature request. When watching a replay, there is a box in the upper right hand corner of the window that can be toggled away by pressing the "eye" button. I'd like a way to do this via console.

The box I'm talking about:
![image](https://user-images.githubusercontent.com/8942987/62095942-d26f5300-b236-11e9-9252-14c7d632c29b.png)

**Comment by kisak-valve** [comment]
Hello @RylanSchaeffer, [Feature Requests](https://github.com/ValveSoftware/Dota-2#feature-requests) are not being tracked in this issue tracker, you'll want to suggest this on https://dev.dota2.com for the larger Dota 2 team.

**Comment by RylanSchaeffer** [comment]
My dev.dota2.com account was closed inexplicably a few weeks ago, with no
reason given. If I can't post here and can't post there, where am I
supposed to post?
