### ISSUE TITLE
[Mac] Terrain texture blurring

### ISSUE THREAD

**Issue by toastdriven** [ValveSoftware/Dota-2#165]
As of the June 26th patch, I occasionally get an odd blurring of the lane textures around the T1 tower of Radiant bot. If I l center on the path, it blurs, but it I start to move the viewport up into the jungle, the textures unblur & look normal. Go back, blurred once again.

From a programming standpoint, it's an extra wonderful "happens intermittently", in that it only appears this way sometimes. Seems like it's towards the beginning of the match of the first game I play once I've loaded S2 up, but that may not be super-accurate (& I haven't had much chance to try to repeat it).

Late 2013 MBP 15" i7 2.3Ghz 16 Gb RAM Intel Iris Pro 1536 Mb. Running at 1600x900 (fullscreen), with the graphics slider on the second lowest setting.

![screen shot 2015-06-28 at 1 55 14 am](https://cloud.githubusercontent.com/assets/2449/8400320/295f8434-1de2-11e5-8484-244618c4507f.png)

**Comment by danginsburg** [comment]
I have not been able to repro this yet.  It is common that on the first load as the texture streaming brings the textures into memory you might see a blurry version at first.

**Comment by toastdriven** [comment]
It gets weirder still. First off, it lasts all throughout the matches. For example, this terrain was rendering correctly earlier in the game, but would turn "muddy" upon looking at it later:

![screen shot 2015-06-30 at 1 15 11 am](https://cloud.githubusercontent.com/assets/2449/8438392/2749e294-1f2b-11e5-95ba-22158ca02b9d.png)

Weirder still, the ground textures outside the base started "flowing" like the water in the river. Wish I had a video, but comparing these shots (taken in quick succession) might help.

![screen shot 2015-06-30 at 1 15 28 am](https://cloud.githubusercontent.com/assets/2449/8438411/44dbf1da-1f2b-11e5-8974-a2f1067e32a7.png)
![screen shot 2015-06-30 at 1 15 28 am 1](https://cloud.githubusercontent.com/assets/2449/8438412/46c1fda0-1f2b-11e5-98d1-fbdacdcd77a8.png)
![screen shot 2015-06-30 at 1 15 29 am](https://cloud.githubusercontent.com/assets/2449/8438414/4852c3c0-1f2b-11e5-9aa7-805df2ad8d32.png)

**Comment by danginsburg** [comment]
I have still not been able to repro this issue.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by gdrewb-valve** [comment]
Assuming this is no longer active.
