### ISSUE TITLE
[MacOS] Post match screen freeze

### ISSUE THREAD

**Issue by udithishara** [ValveSoftware/Dota-2#1651]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/udithishara/e20c8d1436872663c2f57304947659d5
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After every game post match screen freezes.
Cannot click anything, Post match hero animations (idle animation in the overview page) stops, only thing possible to do is Command + Tab to desktop and kill the process by going to `Apple Icon -> Force Quit`

#### Steps for reproducing this issue:

1.  Play a match
2. Finish the match and wait till MVP and Dota+ screens to go away
3. Post match overview screen will come and after 2-4 seconds it'll freeze

**Comment by kisak-valve** [comment]
Possibly related to #1595 / #1636.

**Comment by AyushyaChitransh** [comment]
This is no longer an issue with macos. I faced similar issue in ubuntu in 2017. As of 2019 in macos, this issue has not been seen even once.

**Comment by udithishara** [comment]
I don't play on MacOS anymore, so i can't verify if this is still happening, closing the issue
