### ISSUE TITLE
Naix is able to infest snowball of enemy's team Tusk

### ISSUE THREAD

**Issue by osleg** [ValveSoftware/Dota-2#166]
Just in one of the matches N'aix from enemy team was able to infest snowball when I was casting it on him

**Comment by gdrewb-valve** [comment]
Probably not a Mac/Linux issue.

**Comment by osleg** [comment]
Totally not, but since I have no other place to submit the ticket I though this might be a good place as well.
Your dev forum is broken and returns errors on register, also, you guys do an awesome job but you have worst kind of bug tracker ever (not github's but dev.dota2)

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team so it won't be tracked here.
