### ISSUE TITLE
FPS Drop when pulling cursor into bottom right corners

### ISSUE THREAD

**Issue by nicklozon** [ValveSoftware/Dota-2#1663]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/nicklozon/df01c69f281e2a3e8e311d09ddf56aee
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
FPS Drops when moving mouse cursor to bottom right corner

#### Steps for reproducing this issue:
1. Disable Edge Pan (not necessary, but makes it easier to reproduce by not having the screen move, could also move camera to very bottom right of map)
2. Disable V-Sync (V-Sync reduces the chance of it happening)
3. Use full-screen or borderless windows mode (Can also use windowed mode, but window must be placed in bottom right hand corner of monitor)
4. Demo any hero, or spectate a game with Free Camera (Other camera modes do not "snap" mouse to window, so the issue does not occur)
5. Pull mouse to bottom-right corner of the screen, continue pulling the mouse consistently and the FPS drop will persist until the mouse has stopped moving toward the bottom right corner.

#### Proof
Here is a screen capture of me reproducing the issue. I had to use my phone because OBS did not properly capture the mouse movement. I have the game running in Windowed mode and placed in the bottom right corner of the monitor - the window border shows the mouse position. I pull the mouse into the corner and the FPS drops from 200 to 29. As I continue to pull the mouse down into the corner the FPS drop is constant. The cursor position is actually being pulled back and forth despite the movement of the mouse is to the bottom right. The faster I pull the mouse into the corner the more it approaches it, the slower I pull it actually gets pulled back 40 or 50 pixesl to the left. Something within DotA or Windows is actually fighting with the position of the mouse. It's as if DotA is allowing my mouse to travel to the bottom right corner, but then another process within DotA is overriding and repositioning the mouse.

[![Volatile Mouse Movement](https://img.youtube.com/vi/B46t6iubYNA/0.jpg)](https://www.youtube.com/watch?v=B46t6iubYNA)

The FPS drop occurs because the CPU usage drops - DotA must be wasting valuable cycles on mouse position rather than the main loop of the game? Here is what my CPU usage looks like before and during the FPS drop - sits at a solid 40% when rendering at 200fps, then drops to 10% when rendering at 29fps.

![CPU Usage](https://i.imgur.com/wHznjzI.png)

#### Workarounds
- Make cursor 205% size or larger
- Play in Window mode without the game touching the bottom right corner of the monitor
- V-sync - Reduces chance of the FPS drop occuring. One thing to note with this is that WHEN the FPS drop does NOT occur, the mouse position DOES NOT move back 40-50 pixels to the left, it remains in the very bottom right corner. Since V-sync is essentially telling the DotA process to wait until the previous frame is drawn, DotA bypasses whatever mouse position logic that is causing the FPS drop. In other words, V-sync off makes sure that the issue always happens because the main loop of DotA never skips. (I could be wrong, I'm just applying my basic knowledge here that makes sense)

#### Things that did not help
- Disabling all overlays
- Disabling multiple monitors
- Using a different mouse
- Updating GPU drivers
- Updating OS
- Verifying file integrity
- Completely reinstalling the OS
- Resetting all GPU settings
- Killing almost every process running on the machine
- Moving the taskbar
- Disabling Game DVR

**Comment by kisak-valve** [comment]
Hello @nicklozon, this issue tracker is limited to issues with the Mac and Linux port of the Dota 2 client. You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team.
