### ISSUE TITLE
Steam Voice Settings Link Not Up to Date with Friends List

### ISSUE THREAD

**Issue by David-S-Smith** [ValveSoftware/Dota-2#1666]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: N/A
* Are you using the latest stable video driver available for your system? N/A
* Have you verified the game files?: N/A

#### Please describe your issue in as much detail as possible:
The in the Audio menu meant to direct you to Steam voice settings opens up the old pre-friends-UI-revamp steam settings window. Intended behavior should be that I bring up the "Friends List Settings" window reachable from the settings icon on friends list. I also was unable to change my microphone settings from that menu, but I believe that's may be an unrelated issue.

#### Steps for reproducing this issue:

1. Open DotA 2.
2. Navigate to Settings, then to "Audio"
3. Under "Voice," click the link for "Steam voice settings".
4. This will direct you to the incorrect menu in overlay.

**Comment by kisak-valve** [comment]
Hello @David-S-Smith, this issue is already being tracked at #1552. Closing as a duplicate.
