### ISSUE TITLE
Steam Workshop Alpha tools and custom game lobbies.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#1666]
This isn't an issue but more of a question, I'm sorry if this isn't the place for me to ask it but I'd love some more information regarding this. I'm on a mac and I'd love to try and play custom lobbies but it's still not possible to instal the alpha tools on my system, is this a planned feature , will mac users be able to ever play custom games and if yes, is it coming along the general update of source 2 and the release of custom lobby games in general because if it is, I can wait like everyone else but if it's not planned at all or planned for after that update, then I'd better install boot camp, although I'd be just installing a whole new operating system just for 1 game.

**Comment by Plagman** [comment]
Hello, yes, having the custom games client available on all platforms where Dota 2 is currently supported is our eventual goal, but it might not all come before the Alpha is over. Thanks!

**Comment by Vuccappella** [comment]
Thanks for the reply!
