### ISSUE TITLE
[macOS] Rubick Crash Game

### ISSUE THREAD

**Issue by wtferror** [ValveSoftware/Dota-2#1667]
#### Your system information

* System information from steam 
https://gist.github.com/wtferror/efda7154d4328a63c6288d0c0591a3b3
* Have you checked for system updates?
Yes
* Are you using the latest stable video driver available for your system?
Yes
* Have you verified the game files?
Yes

#### Please describe your issue in as much detail as possible:
My game crash when enemy or friendly rubik appear on screen and do something ( I not sure what they do but my game have 100% chances of crash in 2 minutes if rubik are on screen. )

In not sure where i can found crash logs on MAC.

I have at less 30 crashs last 2 weeks 

#### Steps for reproducing this issue:
1. start game.
2. Have an active rubik playing. 
3. Only see rubik playing (dont need select rubick).

**Comment by kisak-valve** [comment]
Hello @wtferror, this issue is already being tracked at #1542. Closing as a duplicate.

**Comment by wtferror** [comment]
dont need click on rubic. so it is another problem.
