### ISSUE TITLE
[Linux] PING cant be re-assigned to another key

### ISSUE THREAD

**Issue by bytes-max** [ValveSoftware/Dota-2#167]
Hi guys,

Ive played around with my configuration and wanted to have the PING command on my ^-key. However, there's nothing I can do in order to get it away from ALT.

That also prevents my configuration from being usable. I have Selfcasts with modifier key stroke at ALT, which has worked fine in Source 1.

I'm on Linux 14.04 LTS

**Comment by gdrewb-valve** [comment]
It's theoretically possible to rebind the alt modifier to a different key but that would affect anything checking alt, there's no way to limit it to ping.  Ping also would always require a left click.

What exactly was working in source 1?  Changing the alt binding?

**Comment by gdrewb-valve** [comment]
Closing for now.
