### ISSUE TITLE
has potentially attempted to crash the server

### ISSUE THREAD

**Issue by Whysowrong** [ValveSoftware/Dota-2#1671]
I get this warning sometimes and lose control over my hero. I see people are still complaining bout this on reddit!
Can you *****ing remove your pseudo-fix for those crashers and fix them appropriately?

**Comment by kisak-valve** [comment]
Hello @Whysowrong, this issue tracker is for issues with the Mac and Linux client of Dota 2 and this reads like a server issue.

You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team.
