### ISSUE TITLE
Problem with resolution in Desktop-friendly full screen

### ISSUE THREAD

**Issue by A1daron** [ValveSoftware/Dota-2#1675]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

Computer Information:
    Manufacturer:  Apple
    Model:  iMac18,3
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.14.6 (64 bit)

Video Card:
    Driver:  Radeon Pro 570
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision:  0xc5
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 3200 x 1800
    Primary Display Size: 23.70" x 13.43" (27.20" diag)
                                            60.2cm x 34.1cm (69.1cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  963109 Mb
    Largest Free Hard Disk Block:  123980 Mb
    VR Headset: None detected

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

In Mac OS you can use smart scaling in settings. You can lower resolution, it make whole interface bigger, but it doesn't affect sharpness of interface. But if I use this setting and try to use desktop-friendly interface in Dota, I see, that maximum resolution is lower, than in Mac OS interface.

#### Steps for reproducing this issue:

1. Go to system settings
2. Set Bigger text ("looks like 1900x600)
3. Go in Dota 2
4. Set desktop friendly interface
5. See that maximum resolution is only 1900x600

I'd like to see ability to choose higher resolutions in desktop friendly interface.

**Comment by kisak-valve** [comment]
Hello @A1daron, desktop-friendly fullscreen does not change the display's resolution, which allows faster switching between applications, but that limits the game's resolution to the desktop's settings. In this case the game is behaving as intended.

Use exclusive fullscreen if you want to use a resolution higher than the desktop settings.

**Comment by A1daron** [comment]
The problem is that I can't use another resolution on my iMac, because of my bad eye-vision. I'm sure you know, that's on MacOS resolution setting changing size of interface, not the resolution itself (all elements becomes bigger, but sharpness doesn't go lower).

So I was hope, that Dota 2 do the same trick: making interface bigger, but without losing sharpness. I know, that I can use fullscreen mode, but it's very uncomfortable, because I need leave game every time, when I need to switch to another window.

**Comment by kisak-valve** [comment]
You should be able to use cmd + H to return to the desktop at any time. (from #1326)
