### ISSUE TITLE
[Linux] Autocast animation around spell icons don't work

### ISSUE THREAD

**Issue by MrSunshyne** [ValveSoftware/Dota-2#1677]
#### Your system information

https://gist.github.com/MrSunshyne/4bfe227d127ad8c3f6aacd3757d9988c

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
There's usually a ring around autocast icons, such as drow frost arrow or bloodlust. 

But on my linux manchine the animation around the ability icon doesn't appear. 

#### Steps for reproducing this issue:

1. Pick Hero with Autocast ability(row)
2. Skill frost arrow
3. Right-click first ability to activate autocast.
4. Autocast activated but no clear indication it is active.

**Comment by kisak-valve** [comment]
Hello @MrSunshyne, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/320. Are you using OpenGL or Vulkan?

**Comment by MrSunshyne** [comment]
thanks @kisak-valve. I'm using Vulkan indeed

**Comment by kisak-valve** [comment]
Thanks for checking, let's track this issue in the existing issue report. Closing in favor of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/320.
