### ISSUE TITLE
Dota 2 Client crashes for ubuntu when playing Lina

### ISSUE THREAD

**Issue by renatosierra** [ValveSoftware/Dota-2#1677]
When you are playing with Lina suddenly the screen freezes and you cannot do anything else

Ubuntu 14.01 
HP Probook 4530s

**Comment by deri82** [comment]
Are you sure it only happens with lina

**Comment by renatosierra** [comment]
No, it seems to be randomly with all heros it may be the configuración of vídeo adapter
