### ISSUE TITLE
Witch doctor face looks broken when he talks in the game

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Dota-2#1679]
#### Your system information

* System information from steam: https://gist.github.com/barfin/ab2b3cd6a4f08d1b2a3f4b0c494cdf19
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Witch doctor face looks broken when he talks in the game
i use vulkan btw, not sure if it has any affect on it

#### Steps for reproducing this issue:

1. play dota2
2. choose Witch doctor
3. look at his self portrait when he talks

![dcface](https://user-images.githubusercontent.com/37030489/65842417-3ea22c00-e338-11e9-84ce-a71c8af050c2.PNG)

**Comment by danginsburg** [comment]
This one is happening on other platforms as well.  I will pass it along to the larger team, but not track it here since it's not Linux/macOS-specific.
