### ISSUE TITLE
Video artifacts

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#168]
Ubuntu 14.10
![2015-06-29_00001](https://cloud.githubusercontent.com/assets/13041082/8412744/83d103b8-1e94-11e5-9be6-6aa6369aecee.jpg)
![2015-06-29_00002](https://cloud.githubusercontent.com/assets/13041082/8412745/83d7ea0c-1e94-11e5-94fe-e967690196ff.jpg)

Playing on all on low settings: 80%
Anything else: off

Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Desktop x86/MMX/SSE2
Mesa 10.7.0-devel (git-20dca37 2015-06-23 utopic-oibaf-ppa)

**Comment by Pharmasolin** [comment]
After i gave jugger 3 skill (with silencer) he press his 1 skill and this "aura" were on him all game.

**Comment by danginsburg** [comment]
@Pharmasolin It is unclear to me how to reproduce this issue.  Can you please provide more detailed reproducer instructions?

**Comment by Pharmasolin** [comment]
Hi i will try to find replay of this match.

**Comment by Pharmasolin** [comment]
@danginsburg match id 1593454369 it is downloading but dont recreating game, i'm pressing show game but nothing heppens (wine and native steam for ubuntu)

I remember that this were on mid, may be i gave him 3 skill he press 1st go up from river in fog (while on his 1st skill) then come back from fog again still in his 1st skill, but i don't remember, sorry. Need to check game replay, the anwer is in first 13 minutes of game.

**Comment by Pharmasolin** [comment]
@danginsburg 
I have fletched game replay from here http://dotabank.com/replays/1593454369/download/
it is hosting also here http://rghost.ru/8DWtL4yTF

I'm to lazy to switch on Windows to check there this dem.

**Comment by danginsburg** [comment]
@Pharmasolin Thanks I got your demo, but haven't been able to repro the bug.  What time in the demo does it occur?

**Comment by Pharmasolin** [comment]
@danginsburg i can't open demo to check it, i think from 8 to 13 minute when i have gave jugger 3rd skill with silencer something happend.

**Comment by danginsburg** [comment]
@Pharmasolin I found the part of the demo you are talking about, but the visual issue does not repro.  In any case, this is probably highly unlikely to be Linux-specific.  Going to close it for now.
