### ISSUE TITLE
most closed captions are shown twice, once with hero's picture on the left and once without the hero picture

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Dota-2#1680]
#### Your system information

* System information from steam: https://gist.github.com/barfin/ab2b3cd6a4f08d1b2a3f4b0c494cdf19
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
most closed captions are shown twice, once with hero's picture on the left and once without the hero picture

#### Steps for reproducing this issue:

1. launch dota2
2. enable closed captions
3. play the game and you'll see most closed captions are shown twice, once with hero's picture on the left and once without the hero picture

![dasdasdsad](https://user-images.githubusercontent.com/37030489/65842627-b02eaa00-e339-11e9-8d50-63149a365e49.png)

**Comment by danginsburg** [comment]
This is unlikely a Linux/macOS-specific bug, but I'll pass it along to the larger team.
