### ISSUE TITLE
Support for ibus (CJK) on Linux

### ISSUE THREAD

**Issue by Saladin1812** [ValveSoftware/Dota-2#1684]
Gnome now uses ibus as default input method and to input japanese and other CJK languages we simply need to change the setting and it works nicely with all apps running on the shell but Dota 2 ibus input is not working. Please support ibus as Gnome only now uses ibus as an input method.
We cant type CJK without no ibus support.

**Comment by Saladin1812** [comment]
Its working now in dota this can be closed 🙂

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by yueduz** [comment]
> 现在在dota可以关闭了

可以输入了吗，为什么我还是无法输入？ IBus 1.5.22
