### ISSUE TITLE
[OSX] Mouse not locking to screen

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#1685]
I'm on Catalina 10.15.1, and have a dual monitor setup. 

Previously when in a dota 2 match, my mouse locks to the dota 2 application (or window), but now it moves freely between monitors. 

My display mode is desktop friendly full screen.

dota_mouse_window_lock 1 / dota_camera_edgemove 1 doesn't help.

**Comment by kisak-valve** [comment]
Hello @kierien, this issue is already being tracked at #1612. Closing as a duplicate.
