### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1688]
I run vulkan dota2. I have been getting random crashes since a little while (don't recall exactly how long ago).
I run a state of the art x11/mesa(GL/vulkan) stack on AMD tahiti xt.
Once it starts to crash, usually, it keeps crashing for sereral times in a row.
The kernel log shows:
GlobPool1[1282]: segfault at 7f789ec4e5ea ip 00007f78942ea2f8 sp 00007f789c4580c8 error 4 in libvulkan_radeon.so[7f78931b0000+1e08000]

I noticed the offset (here 1e08000) in libvulkan_radeon is stable among the crashes. And it crashes always in libvulkan_radeon.

**Comment by sylware** [comment]
managed to get the same random crash starting dota underworld. Same offset in vulkan driver.
(for your information, this is the offset in a debug build: the offset does not map to any code known into mesa, using addr2line from the binutils)

**Comment by sylware** [comment]
bad news: I get random crashes with opengl dota2 too.

**Comment by sylware** [comment]
it seems that, before each crash there is a burst of things happening. For instance in dota, it could be a burst of spells. It can be also right before entering the dash board after starting the game. Also, the sound upon crashing is crackeling. My system use a vanilla dmix alsa 1.1.9 (pinned).

**Comment by sylware** [comment]
got the dota2 update of today, and the crash did move, namely in the kernel log I get:
[ 2164.863983] GlobPool5[7690]: segfault at 3000000058 ip 00007f3537bdb572 sp 00007f354b929a50 error 4 in libparticles.so[7f3537aa8000+327000]
[ 2164.863992] Code: d2 74 08 4c 89 f7 e8 1d da ff ff 45 8b 4e 6c 45 85 c9 0f 84 ea 01 00 00 48 8b 15 51 b7 45 00 48 8b 05 0a b6 45 00 44 8b 42 58 <8b> 40 58 45 85 c0 0f 84 6f 06 00 00 3d b8 0b 00 00 ba b8 0b 00 00

and the crash did happen when some action  burst did happen "offscreen". I only could hear it, not see it. It hints now torwards a sound mixing issue (and I have been having alsa underrun messages). Alsa dmix is 48kHz, maybe the dota2 sound frequency resampler has some troubles?

(I did "slow" down my system. Did not help)

The other hint: particules computation issues (I run the compute shaders, I will do some testing without them even though it did crash using the opengl renderer)

**Comment by sylware** [comment]
nothing did change and the random crashes are back in libvulkan_radeon which I cannot debug: I have a debug build of libvulkan_radeon but the offset of the crash does not belong to any code as it seems (using glibc addr2line). I am stuck. Any ideas?

**Comment by Saladin1812** [comment]
https://github.com/ValveSoftware/Dota-2/issues/1694

I guess its the same issue one issue can be closed track it in one issue..

**Comment by Saladin1812** [comment]
Many have the same issues after the outlanders  update. Tommorow I will test playing it using the Steam Linux runtime container lets see it changes something or not.

**Comment by sylware** [comment]
My old system did melt. I have other crashes with my new beefy system. Closing this one.
