### ISSUE TITLE
6.83c - Unable to enter game

### ISSUE THREAD

**Issue by lewisdiamond** [ValveSoftware/Dota-2#1693]
Dota will crash instantly after loading the game:

''CrashID=bp-f5753d3f-71d2-45aa-9bf1-901db2150210''
    Thu Feb 12 22:58:37 2015 GMT: file ''/tmp/dumps/crash_20150212175606_1.dmp'', upload yes: ''CrashID=bp-6b4d8cda-0fbb-4a0c-88a0-5207f2150212''
    Thu Feb 12 23:00:12 2015 GMT: file ''/tmp/dumps/crash_20150212175838_1.dmp'', upload yes: ''CrashID=bp-c288986f-f1e7-40ff-a00a-3a2a82150212''
    Thu Feb 12 23:01:46 2015 GMT: file ''/tmp/dumps/crash_20150212180008_1.dmp'', upload yes: ''CrashID=bp-1254652c-9721-401d-a23c-a1c872150212''

**Comment by lewisdiamond** [comment]
I finally managed to join a game after clearing the GLCache folder:
rm -rf ~/.nv/GLCache/

Can't say if it's permanent yet.

**Comment by lewisdiamond** [comment]
Scratch that. It crashes still:
    Thu Feb 12 23:29:26 2015 GMT: file ''/tmp/dumps/crash_20150212182743_1.dmp'', upload yes: ''CrashID=bp-8818a24f-5e25-4fec-9398-d61d62150212''

**Comment by AllahThealmighty** [comment]
Segfaults on my 64-bit Arch. https://gist.github.com/AllahThealmighty/6123450f53fbaad03bbf.

**Comment by lewisdiamond** [comment]
Might be related: #1684

**Comment by davidw-valve** [comment]
Have you tried verifying the integrity of the game cache or deleting and redownloading Dota2?

**Comment by lewisdiamond** [comment]
I have tried redownloading dota 2 for #1684 but not since the patch. Note that I'm now able to play and get occasional crash (requiring glcache clearing), about daily.

**Comment by davidw-valve** [comment]
What version of the NVidia drivers do you have? If you haven't I would recommend updating to the latest drivers.

**Comment by lewisdiamond** [comment]
I have the latest supported drivers for my card on my Linux distro (304.125). Even if nvidia's website says the 340 supports the GTS 250, it doesn't.

**Comment by Tele42** [comment]
This should also be reported to nvidia as the 340 series really _should_ support your card.

**Comment by davidw-valve** [comment]
I appreciate you posting your card. Any other users who experience the same problem should also post the model of their NVIDIA card as a reply to this. We want to work out what cards it occurs with so we can try to get a fix.

**Comment by davidw-valve** [comment]
@lewisdiamond: I would suggest contacting NVIDIA for support; the right solution is for you to be using the 340 branch for your card.

**Comment by lewisdiamond** [comment]
340.76 Now works. Unfortunately I can't find the error I had but for anyone else who couldn't get his GTS 250 working on early 340, the latest now works!

**Comment by davidw-valve** [comment]
Okay. I'm closing this bug out. File a new bug if you still have problems.
