### ISSUE TITLE
Dota 2 crashing randomely on main menu after outlanders update

### ISSUE THREAD

**Issue by Saladin1812** [ValveSoftware/Dota-2#1694]
After the recent outlander update all linux users are crashing randomly on main menu. 
My friend's distro - Pop OS 18.04, Fedora 31
My Distro - RHEL 8

**Comment by Saladin1812** [comment]
We all use Vulkan, I am not sure if this happens in opengl or not havent tested. we all have nvidia GPU.

**Comment by Turmfalke2** [comment]
Gentoo, nvidia gpu and no crashes.

**Comment by Saladin1812** [comment]
@Turmfalke2 maybe not on gentoo but we are expiriencing this on pop fedora and RHEL i can confirm. Also are you using vulkan ? Maybe its vulkan specific.also how long did you played? It crashes at random

**Comment by Turmfalke2** [comment]
I am using the vulkan dlc and have played a few dozen games.

Maybe lets start with figuring out were it crashes. Could please try running **dmesg** in a terminal after a crash? I am not sure about the security settings for dmesg on RHEL, you may have to run it as root. Try without first. One of the last lines should be about your crash and mention in which part driver/library/dota it self it crashed. You may also be able to find some information in /tmp/dumps.

**Comment by Saladin1812** [comment]
@Turmfalke2 also someone https://github.com/ValveSoftware/Dota-2/issues/1688  also has an issue i dont think its RHEL specific also this issue displays the logs all tho i will try to provide logs tommorow when i will be at home.

**Comment by Saladin1812** [comment]
Also im NOT expiriencing this issue in other games only dota on various distros so its not distro specific. This started after the outlanders update.

**Comment by Alecsandroma** [comment]
I had the same problem 
Trying use Ubuntu 18.04 Deepin and fedora 31
Also tried in two different machine

**Comment by Saladin1812** [comment]
Its fixed  closing this
