### ISSUE TITLE
[OS X] CM Arcana does not display properly in loadout/preview

### ISSUE THREAD

**Issue by gwark10** [ValveSoftware/Dota-2#1695]
![cm1](https://cloud.githubusercontent.com/assets/11008561/6205223/0a5f7a28-b535-11e4-989c-2301982a39d1.png)
![cm2](https://cloud.githubusercontent.com/assets/11008561/6205224/0a6066ae-b535-11e4-8e96-c3fc75afb2ae.png)

See above.

**Comment by davidw-valve** [comment]
Should be fixed now.

**Comment by gwark10** [comment]
Confirmed. Thanks!
