### ISSUE TITLE
Dota 2 crash after find jungle item Third Eye

### ISSUE THREAD

**Issue by shpinog** [ValveSoftware/Dota-2#1696]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/shpinog/66a7237e6e441f73faa152b456d378ab

* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
mesa from valve repo
* Have you verified the game files?: [Yes/No]
Yes

#### Steps for reproducing this issue:

1. Open dota2
2. enemies and maybe allies find new item Third Eye.
3. Crash

This problem began to occur after one of the minor patches 7.23b +.
After the opponent finds a new Third Eye item, I get an error (see screenshot).
After clicking on “ok” the game client closes.
If you re-enter the game and click reconnect, it can go in and play for 0-3 seconds, after which I get the same error = low priority because of this.

Error: ![Alt Text](https://i.imgur.com/MKFkmMW.png)

Close: 
a complete reinstallation of the game client, before that translated Steam into English, it helped and the problem is no longer reproduced in the lobby. 
When switching the language in steam to English, things like voice acting remained in Russian, only the complete removal of the client changed the language completely.
I don’t know what exactly solved the problem, but this is the only difference I noticed.

**Comment by shpinog** [comment]
The problem is still relevant. Found an easier way to reproduce it. I am attaching a video with an example.
1) Create a lobby, create a Third Eye item.
2) The same with vulkan
3) Inability to reconnect
4) The problem does not play in "Demo hero"

Video:
https://drive.google.com/file/d/1u6UfzEHr1EBSrtZs2yLsoTV6dPOCfn4k/view

Crash damp:
https://github.com/shpinog/Log-dumps/blob/master/crash_20191205210102_1_dota2.dmp

**Comment by danginsburg** [comment]
Thanks for the repro video, we'll look into it.

**Comment by danginsburg** [comment]
This looks like it is because your client is out-of-date.  Can you try restarting Steam and making sure you do updates before launching?

**Comment by shpinog** [comment]
I received the latest Steam update recently, after recording a video. After the update, nothing has changed.

Video:
https://drive.google.com/open?id=18E100VMimo0En2dDaNRI0jj91JrzGOTm

dmp:
https://github.com/shpinog/Log-dumps/blob/master/crash_20191205224810_1.dmp


The Dota 2 client does not need to be updated, the latest update today is about 60mb (it seems).

upd: Steam in native runtime mode also throws this error.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libtier0.so coming from libengine2.so.
