### ISSUE TITLE
very wrong regional detection

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1697]
I live in Marseille/France and I am detected in Paris/France!

**Comment by kisak-valve** [comment]
Hello @sylware, this reads like a general Dota 2 issue, and not specific to the Mac/Linux port.

You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team.

**Comment by sylware** [comment]
On Thu, Dec 05, 2019 at 09:02:00AM -0800, kisak-valve wrote:
> You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team.

done.
