### ISSUE TITLE
[SteamCloud] Settings Not Saved

### ISSUE THREAD

**Issue by computerquip** [ValveSoftware/Dota-2#17]
Hotkeys and preferences should be saved in the cloud. They currently are not (as my settings from Windows was not saved). I'm not sure if it's intended or not yet so I'm defaulting to a report.

**Comment by davidw-valve** [comment]
We don't currently save to the cloud. We will consider this feature for the future.

**Comment by gdrewb-valve** [comment]
This isn't a Mac or Linux specific issue so you'll want to report this as dev.dota2.com instead.
