### ISSUE TITLE
Date language not according to UI

### ISSUE THREAD

**Issue by r3pek** [ValveSoftware/Dota-2#170]
Hi... I'm from Portugal and I _do_ have LC_TIME set to "pt_PT.UTF-8" on my system (default to en_US.UTF-8) but the mixed language on the UI looks weird ;)

![image](https://cloud.githubusercontent.com/assets/3050556/8414944/e5437a2c-1e8a-11e5-9a98-a91b809dd013.png)

I don't know if it should stay like this or make it use the same language overall.

**Comment by gdrewb-valve** [comment]
Not a Linux/Mac issue.  I'll pass it on to the larget team.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team and it won't be tracked here.
