### ISSUE TITLE
Can't uninstall Arcade files (Library "Download Queued", clicking uninstall never works

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/Dota-2#1700]
#### Your system information

* https://gist.github.com/romulasry/f088a3639dd5c3cb91f8e93f2cc90b2a
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
You should be able to remove downloaded/updated files in the Arcade tab in game.

#### Steps for reproducing this issue:

1.  Go to Arcade
2. Download Open Angel Arena
3.  It never download and you can't cancel (on my system)

**Comment by stoburnyou** [comment]
Did you find a solution to this? I wrote to support team, and they are not writing back!

**Comment by romulasry** [comment]
@stoburnyou No fix, yet, sorry.

**Comment by nickolaos** [comment]
I can verify that this still has not been fixed.

**Comment by romulasry** [comment]
Works now > RIght click Dota2 > Properties > Workshop.
