### ISSUE TITLE
Dota Arcade is broken, no Couriers, no passive Gold

### ISSUE THREAD

**Issue by Schokokex** [ValveSoftware/Dota-2#1701]

**Comment by Schokokex** [comment]
All the old mods became useless, because there are no couriers anymore.
Mod Developers now have to manually implement a courier.

**Comment by kisak-valve** [comment]
Hello @Jochnickel, this issue tracker is limited to issues with the Mac and Linux ports of Dota 2. You'll want to post general Dota 2 issues at https://dev.dota2.com for the larger Dota 2 team.
