### ISSUE TITLE
[Linux] Trying to Ping with ALT makes borderless windows to be moved

### ISSUE THREAD

**Issue by grasdaggel** [ValveSoftware/Dota-2#171]
Problem is in title. If I start a new game and want to ping from time to time the window gets moved, instead of a ping. Reproduceable if you can see the drag-cursor ingame.

**Comment by gdrewb-valve** [comment]
Is this a duplicate of #119?

**Comment by kingalca** [comment]
Yes! can be closed. You're a issue hero, Drew!
