### ISSUE TITLE
[Linux] Crash on Custom Games ( Dota Imba )

### ISSUE THREAD

**Issue by madIlama** [ValveSoftware/Dota-2#1710]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/madIlama/af3cc8ec4eea9e03f78214522f9bc91f
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes,even reinstall

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1.  Subscribe Dota Imba on https://steamcommunity.com/sharedfiles/filedetails/?id=1350425247
2.  Query for 5v5 or 10v10
3.  Wait at loading screen,and then it will crash to desktop

Important journal log

```
Feb 06 00:03:22 Process 30479 (dota2) of user 1000 dumped core.
                                                     Stack trace of thread 30479:
                                                     #0  0x00007fd2c3f8ae50 n/a (/home/topkek/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpangoft2-1.0.so + 0x8ae50)
```

Steam tmp dump:
https://gist.github.com/madIlama/6fb1843471b6989767ddc90ebc639348

I am experiencing this since last update that bring abbandon button smaller

Other friend (windows) did not experiencing this
Before last update i was (with linux) not experiencing this

**Comment by bluemeda** [comment]
Confirmed.
System Information: https://gist.github.com/bluemeda/6aea0d4aee6887d9aa9ebb0d5da28161
Steam Log: https://gist.github.com/bluemeda/abea99dbddd413ed2a330685dd15a540
journalctl: 
```
Feb 08 16:30:58 pseudocircle systemd-coredump[2968]: Process 2522 (dota2) of user 1000 dumped core.
                                                     
                                                     Stack trace of thread 2526:
                                                     #0  0x00007f8bcb871cee _Znwm (libtcmalloc_minimal.so.0 + 0x18cee)
                                                     #1  0x00007f8bc8bfc8b6 n/a (libvstdlib.so + 0x138b6)
                                                     #2  0x00007f8bc9413429 n/a (libengine2.so + 0x259429)
                                                     #3  0x00007f8bc941487d n/a (libengine2.so + 0x25a87d)
                                                     #4  0x00007f8bc5f98f44 n/a (/home/bluemeda/.local/share/Steam/linux64/crashhandler.so + 0xcf44)
```

**Comment by madIlama** [comment]
You can also reproduce by watching game, it will crash after a while in loading screen

I want to highlight again,that i never experiencing this before,its normal before official Dota 2 Update

I already did rollback my driver,install new driver,trying latest dev (mesa-git stack) build. The crash still there

**Comment by elovin** [comment]
I have the same problem, the game crashes during connection when starting a custom game (tested with dota imba). I tried mesa 19.3.4 and the latest mesa master version both opengl and vulkan, so it seems that this is not related to the graphics driver. 

I will add some logs and test on another pc with a nvidia gpu later. (Last time I looked at the steam output after a crash there was something about a segmentation fault)

**Comment by madIlama** [comment]
i kinda jealous at other issue that newer than this get more review / dev comment

**Comment by lobo-tuerto** [comment]
I can confirm it crashes with Dota IMBA.
Other custom games play OK.

**Comment by crapthings** [comment]
custom game crashes on Mac

like element td

and OMG mode crashes a lot

**Comment by madIlama** [comment]
Any news about this?

in recent update,i notice that sometimes i can watch dota imba game
sometimes with endless loading screen
but most of time it will crash

joining/loading the game still automatically crash to desktop

this happen in OpenGL or Vulkan mode

**Comment by WoodyWizard** [comment]
same to me  ArcoLinux

**Comment by madIlama** [comment]
![image](https://user-images.githubusercontent.com/1744593/75733094-ed52fa00-5d26-11ea-91ba-57d6cdcd0197.png)

latest patch still crash to desktoop

**Comment by WoodyWizard** [comment]
When you will resolve problem? Several custom games(which i to played) crashes or doesn't work correctly
Log in console from "Custom Hero Chaos":

[ResourceSystem] Error loading resource file "panorama/layout/custom_game/barebones_notifications.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/ability_order.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/taunt.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/chat_wheel.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/player_lose.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/barrage.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/quest_line.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/ability_select.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/hero_card.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/lottery.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/inventory.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/rank_panel.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/pvp_brief.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/pvp_bet.vxml_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "panorama/layout/custom_game/top_menu.vxml_c" (Error: ERROR_FILEOPEN)

**Comment by danginsburg** [comment]
The crash is inside libfreetype and while I haven't entirely root caused it, it stems from an error getting glyphs from the "Arial Black" font.  We will try to get in touch with the developer about using a different font, as fixing in freetype is likely not going to be feasible.

**Comment by madIlama** [comment]
i downgrade freetype  just for check,the problem still exist

more observation at my pc show that using steam-runtime will imidieatly create dump,and crash to desktop

while steam-native will just infinitely stuck at load screen

**Comment by n1ghtdev** [comment]
crashed on loading screen in Dota IMBA custom game

System Information: https://gist.github.com/n1ghtdev/b79ac1c3412210f14916018b34f95bc2
backtrace log: https://gist.github.com/n1ghtdev/0ef4bc367fb63b5f36e6eb82b4781dd3

**Comment by madIlama** [comment]
Remember,this only happen in 5v5 or 10v10 IMBA Mode that of course need a lot of processing power
If u try IMBA Demo Mode or 1v1 Mode,it can launch just fine (for me)

I think that need to be investigate further

**Comment by Weirdo1312** [comment]
i experience this issue but game doesn't crash it just freezes but background dota music keeps going
most of the time in versus screen with huge amount of skins on heroes
but it can also happen after versus screen with all default skins
however it will happen once per game and when i kill the dota2 process and return to the game everything will be normal 
i experienced this issue in bunch of custom games including "attack on hero 2 rebalanced"

my system info: https://gist.github.com/barfin/e3010fc48c6c94a74e2be1102d7726c1

**Comment by barfin** [comment]
i experience this issue but game doesn't crash it just freezes but background dota music keeps going
most of the time in versus screen with huge amount of skins on heroes
but it can also happen after versus screen with all default skins
however it will happen once per game and when i kill the dota2 process and return to the game everything will be normal 
i experienced this issue in bunch of custom games including "attack on hero 2 rebalanced"

my system info: https://gist.github.com/barfin/e3010fc48c6c94a74e2be1102d7726c1

**Comment by crystaldaking** [comment]
Custom hero chaos also crashed on Ubuntu 19.10

**Comment by madIlama** [comment]
This is not first time freetype crash in dota2
#1306 
#1443
#1504

Something did changes on January/February

**Comment by kostka-dev** [comment]
I confirm that Linux has several problems with custom games. They crash to desktop during loading (probably the map?). I also suspect that libfreetype is causing the problem, as it cannot parse some characters in Arial Black for some reason.

**Comment by kostka-dev** [comment]
I had a workaround in which I was breaking Microsoft fonts in demo mode (I was uninstalling them while hitting the dummy target, which was causing exactly the same errors in the console), but the workaround does not work anymore.

**Comment by Weirdo1312** [comment]
Please fix this
it's so rare for dota2 to not crash in custom games
it makes playing custom games literally unplayable

**Comment by Weirdo1312** [comment]
Any update on this? It's impossible to play normal custom game without crashing, it annoys the hell out of me
each time my game freezes or crashes and I relaunch the game I'll see that everyone else is also disconnected, because they think i don't wanna play anymore, it's horrible just fix this please

**Comment by ankworld** [comment]
@barfin Can you use 'Steam Linux Runtime' at compatibility tool?
Let me know if it's work.

**Comment by Weirdo1312** [comment]
> @barfin Can you use 'Steam Linux Runtime' at compatibility tool?
> Let me know if it's work.

no it didn't change anything however i forgot to mention that custom item icons won't load until it freeze and i relaunch it
also when i start the game as the server these issues don't exist and custom icons load properly and game doesn't crash or freeze

**Comment by olivatooo** [comment]
Someone already found a fix?

**Comment by Weirdo1312** [comment]
> 
> 
> Someone already found a fix?

I found a fix
since custom games are important to me and vale simply doesn't care about fixing it
I deleted my arch linux and installed windows
NICE JOB VALVEEEEEE

**Comment by olivatooo** [comment]
I put these launch options: `-novid -console -high -map dota`
I'm using:

OS: Arch Linux x86_64
Kernel: 5.7.10-21-tkg-pds
WM: i3

And everything is working
