### ISSUE TITLE
[alsa] /usr/share/alsa is hardcoded somewhere

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1712]
For in-game voice, I did discover alsa is complaining in the log because /usr/share/alsa does not exist (dota2 is using my alsa lib which is "pinned" by the steam kluient)

Please honor the ALSA_CONFIG_DIR environment variable (which seems to be the case for the new steam client voice chat)

**Comment by sylware** [comment]
there is "old" alsa-lib static code in dota2: configuration files are tightly coupled with alsa-lib code.
To "workaround" the issue of configuration files harcoded location, I did setup a link (/usr/share/alsa -> /$whatever/alsa). Now  I get in the log a message that it cannot read the configuration files because of a file parsing issue (I use alsa-lib git). It is expected since the configuration files have things which will break "old" alsa-lib code.
The right(tm) way to use the alsa-lib for closed source apps is to dynamically load the lib and resolve the used symbols (like vulkan)

**Comment by sylware** [comment]
still around.

Should it be moved to the steam-for-linux as it seems related to the in-game voice support?

The system alsa-lib should be dynamically loaded or/and honor the ALSA_CONFIG_DIR environment variable

**Comment by sylware** [comment]
Have not retested, but I add more info to it:
alsa-lib-1.2.8/src/conf.c line 596, the function snd_config_topdir shows the usage of the environment variable ALSA_CONFIG_DIR, hopefully used everywhere it needs to.

But the definitive solution is to libdl the system libasound.

**Comment by sylware** [comment]
This seems related to steam voice, not dota2.

Should I open a ticket elsewhere? Steam client or steam runtime?

**Comment by sylware** [comment]
Ok, I did open an issue in what seems a better location for this.

**Comment by kisak-valve** [comment]
Hello @sylware, in the future, give me a ping requesting a transfer of the issue report and explain why it would be better off in the other issue tracker instead of splitting the discussion.
