### ISSUE TITLE
Chat Wheel(and other) are bugged is some multimonitor environment. 

### ISSUE THREAD

**Issue by jedrzejowski** [ValveSoftware/Dota-2#1714]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/jedrzejowski/565a49699285ecce143efad3ea16177a): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Steps for reproducing this issue:

1. Have Gnome 3 Desktop
2. Have 2 monitor setup
3. Set `right` monitor as main, set `left` as secondary
4. On the `right` screen there is nothing wrong
5. On `left` screen chat wheel is bugged

#### Please describe your issue in as much detail as possible:

In some circumstances chat wheel is unusable. Lets say that u have Dota o left screen, while your main screen is right. When using wheel, mouse sets position at center between two screen making it selecting most `right` options.
Here is [screen shoot](https://imgur.com/a/1lyyeJ9).

Edit: bug is present from 2014, when is started playing

**Comment by kisak-valve** [comment]
Hello @jedrzejowski, this issue is already being tracked at #1201 / #1448. Closing as a duplicate.
