### ISSUE TITLE
Can't link steam with dev.dota2.com

### ISSUE THREAD

**Issue by e-motiv** [ValveSoftware/Dota-2#1715]
#### Your system information

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: No

#### Please describe your issue in as much detail as possible:
I want to report a bug of not being able to connect to the game after confirming to join the game after finding match, but I can't manage to get a real login in dev.dota2.com. This has happened 3 times the last year (the bug as well as the inability to login dev site.)
The problem is that I cannot link steam with my dev.dota2 login, so I can't login.
1 It says I need to verify my account
2. The browser goes to "Verify account" page from dev.dota2.
3. I click the button "Sign in through Steam".
4 Browser goes to steam site "Sign into dev.dota2.com using your Steam account".
5. I click "Sign in" with my account
6. Browser goes back to "Verify Account" (number 2 above).
STaying in this loop forever, never getting in the site.

**Comment by aploskov** [comment]
Duplicate #1516
