### ISSUE TITLE
custom game is missing resources

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1716]
hi,
I am writing this under the assumption that custom games should work OS independent. 

I tried playing [Custom Hero Chaos](https://steamcommunity.com/sharedfiles/filedetails/?id=1999002498), but none of the custom overlays (ui and such) load. This makes the game pretty much unplayable.

From the ingame console and confirmed by strace the game is looking for files in `/home/turmfalke/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/layout` like `/home/turmfalke/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/panorama/layout/custom_game/hero_card.vxml_c`. However when checking in the filesystem panorama/ has no layout directory. 

What is going wrong here? I would assume it should load the files from `steamapps/workshop/content/570/1999002498/1999002498.vpk`.

System is fairly uptodate (currently building qt..), but I don't think this matters for this bug here.

**Comment by mallikarjun-b-r** [comment]
The same issue persists for me please fix this

**Comment by WoodyWizard** [comment]
Same for me in many custom games

**Comment by madIlama** [comment]
well,let me sub to this too
its been 2 month we got this crash

dunno if this caused by freetype font too

**Comment by ivanmasf** [comment]
same issue for me in pretty much all custom games

**Comment by ivanmasf** [comment]
No news in this issue? It's been months we can't enjoy custom games. Can we get some help please?

**Comment by Turmfalke2** [comment]
@danginsburg can you please have a look at this or tell us what we are supposed to do? can we unpack the files somehow and move them around manually?

**Comment by Turmfalke2** [comment]
Not sure when, but apparently this got fixed.
