### ISSUE TITLE
[Linux] Add monitor selection to resolution settings in video

### ISSUE THREAD

**Issue by Kirov123** [ValveSoftware/Dota-2#172]
This would help solve multi-monitor issues on Linux, and would be particularly useful to people who have more than 2 monitors. A drop-down menu would probably work best.

**Comment by gdrewb-valve** [comment]
The 7/20 update adds a crude way of controlling this via launch options.  -sdl_displayindex # will force Reborn to start on a non-primary monitor.

**Comment by wiseone13** [comment]
FYI, this does fix it (for me at least), but if I change my resolution, it goes back to the other monitor. I only had to change it because it still had the other monitor's resolution. I shouldn't have to change my resolution again. Thank you!

**Comment by gdrewb-valve** [comment]
A future update will have some more multimon fixes.

**Comment by gdrewb-valve** [comment]
@stealthpants, the 7/23 update should fix your issue, does it?

**Comment by gdrewb-valve** [comment]
The feature request here is not Linux/Mac specific so I've passed it on to the larger team.
