### ISSUE TITLE
Tooltip problem, ranked classic or ranked roles in spanish language

### ISSUE THREAD

**Issue by alainhb2000** [ValveSoftware/Dota-2#1722]
Files:
dota_latam.txt
"ranked_calibration_games"	"Quedan {i:solo_calibrating_games} partidas clasificatorias de calibración"

dota_spanish.txt
"ranked_calibration_games"	"Quedan {i:solo_calibrating_games} partidas clasificatorias de calibración"

dota_english.txt
"ranked_calibration_games"				"{i:calibration_games_remaining} Ranked Calibration Games Remaining"

**Comment by kisak-valve** [comment]
Hello @alainhb2000, this issue tracker is limited to the Mac and Linux client of Dota 2. This reads like a general game issue and you'll want to post this at https://dev.dota2.com for the larger Dota 2 team to evaluate.

**Comment by alainhb2000** [comment]
Tried to registrate on dev.dota.com but when i'm trying to associate account with Steam, i receive this error: Auth failed - missing key. I suppose the problem is i'm not members of Dota 2 beta program.

**Comment by alainhb2000** [comment]
Thanks, for the quick answer.
