### ISSUE TITLE
macOS using vulkan causes world/map to become darkened and goes black when mouse hovering over units

### ISSUE THREAD

**Issue by SimonHattoriWilson** [ValveSoftware/Dota-2#1723]
#### Your system information

* System information from steam [gist](https://gist.github.com/SimonHattoriWilson/dc5208df69e7c272c530b9d339696fc1)
* Have you checked for system updates? Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files? Yes

#### Please describe your issue in as much detail as possible:
When using Vulkan:
The world appears darker, like a fog of war tint, and when mouse hovering over units, it causes the the entire world to go black with the exception of your hero, all health bars, and the unit being mouse hovered. All HUD elements are also still visible.

The problem does not persist when using OpenGL. 

The bug was pretty recent, I think it happened after patch 7.23-7.24

#### Steps for reproducing this issue:

1. Try running dota on macOS with Vulkan. 
2. World map should appear as described.

Please look at the video demonstrating the bug.
https://imgur.com/a/ZK8hg16

**Comment by kisak-valve** [comment]
Hello @SimonHattoriWilson, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328. Closing as a duplicate.
