### ISSUE TITLE
"Current recording level" preview bar doesn't update on mic input level change

### ISSUE THREAD

**Issue by swilliams96** [ValveSoftware/Dota-2#1728]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a gist: https://gist.github.com/swilliams96/f6e1361a26c62d39e7df99052330685d
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
In the audio tab of settings, the "Current recording level" bar doesn't update when speaking, except when other parts of the UI are updated (for example by hovering over them). Expected behaviour is that the preview bar constantly updates based on microphone input level regardless of whether other parts of the window are being hovered over or not.

![image](https://user-images.githubusercontent.com/26005963/78509727-26e4ae00-7788-11ea-9d65-1ccdff7d44a7.png)

I imagine this is because the UI is programmed to not update when not necessary to improve performance and a change in microphone input level is not set as a trigger for a UI window rerender, when it probably should do in this particular case.

#### Steps for reproducing this issue:

1. Ensure you have a microphone plugged in and configured, then open Dota 2.
2. Open the settings menu from the cog icon in the top left of the main menu.
3. Click the "Audio" tab.
4. Start speaking into your microphone without moving your mouse. The "Current recording level" preview bar near the bottom left on the window does not change.
5. Continue to speak as you move your mouse and hover over various other UI elements in the audio settings menu window. The "Current recording level" bar will update for a short time after you hover over each new UI element, but will stop when you cease moving your mouse.

**Comment by kisak-valve** [comment]
Hello @swilliams96, this issue tracker is limited to issues with the Mac and Linux port of Dota-2. You'll want to post this at https://dev.dota2.com for the larger Dota 2 team.

**Comment by swilliams96** [comment]
@kisak-valve I tried to register for https://dev.dota2.com but it is failing to link my Steam account - I'm getting a consistent "Auth failed - missing key" error message. I know this complaint isn't really relevant to you but if you could pass that information onto the relevant party in Valve that would be great.

Until I can successfully complete my registration I have no way of reporting this bug, so I'm afraid that this bug report will die here (and I'm sure many others have given up trying to report a bug at this stage too). It would be great if the wider Dota 2 team would use this Github repo to track bugs as well, maybe using different labels to differentiate between the different operating systems so your separate teams can continue to easily find the bugs that are relevant to them.
