### ISSUE TITLE
[Linux] Disconnecting repeatedly from certain matches.

### ISSUE THREAD

**Issue by hartigan43** [ValveSoftware/Dota-2#1729]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/hartigan43/64699d64ba21ee52fae03c941c93b5ba
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/). 

I'm randomly repeatedly getting disconnected from servers.  It is not on every game, and the severity varies.  It seems to occur at random intervals and sometimes it behaves similarly to lag/packet loss and only lasts a few seconds.  More often, lasts until it forces a disconnect, or I manually disconnect as once the alert about disconnecting comes up, I always end up disconnecting.  Manually disconnecting and reconnecting is just faster.

I searched in the issues that are open and closed and they all seem to have adverse affects like forcing steam offline, dropping internet connections, etc.  I'm not experiencing any of that, I can still browse the internet while disconnecting, chat on voice via external apps, stream twitch, etc.  I did find a post somewhat relevant and tried using the suggested launch options: `-console -con_logfile +net_maxroutable 600 +net_showudp 1 +net_showsplits 1 +log_verbosity splitpacket detailed`

The game otherwise runs great.  120-165fps stable.  Never seeing any packet loss, outside of it occasionally reporting 1:1 when it freezes up and/or displays the disconnect warning.

Here is a partial log (using the above launch options) as uploading the full log crashes the gist uploader. [Console.log Gist](https://gist.github.com/hartigan43/93a181eb304388650fc4838740b9494a/raw/30001502001947ea5856bb968550c9bd01157809/console.log)

#### Steps for reproducing this issue:

1. Connect to any match.
2. Play for a random amount of time.
3. Experience a bit of freezing similar to packet loss, or a complete freeze with a disconnect warning.

**Comment by hartigan43** [comment]
[Single game partial log](https://gist.github.com/hartigan43/09d44fdb9020c9b3f56fec2df69d92de)

Above is my most recent game where I had both the minor hangups, and the complete disconnect, at 16:11 match time.

Please let me know if I can provide any more information or send full logs in another manner as they are large.  Thanks!

**Comment by hartigan43** [comment]
This issue seems to have resolved itself, perhaps a kernel update or patch did it.  I'll close for now.

**Comment by JuanJ67m** [comment]
1+, with last patch i have same problem
