### ISSUE TITLE
bug with legion and meepo

### ISSUE THREAD

**Issue by akevalion** [ValveSoftware/Dota-2#1732]
#### Any system

* akevalion in steam
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

- In game play legion, 
- put a meepo enemy at level 4 at least.
- Duel one meepo A.
- kill meepo C.
- legion will not win the duel damage

**Comment by kisak-valve** [comment]
Hello @akevalion, this issue tracker is limited to issues with the Mac and Linux clients of Dota 2. You'll want to post this at https://dev.dota2.com for the larger Dota 2 team.
