### ISSUE TITLE
Microphone and Dota2 on Mac

### ISSUE THREAD

**Issue by TheGP** [ValveSoftware/Dota-2#1733]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro10,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:        Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.2 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 650M
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0xfd5
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11" (15.31" diag)
                                            33.1cm x 20.6cm (38.9cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  476902 Mb
    Largest Free Hard Disk Block:  6580 Mb

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Microphone doesn't work in Dota or Steam, I don't see either of them in the tab Privacy => Microphone as they didn't request access to it.

#### Steps for reproducing this issue:

1. Install Steam
2. Install Dota
3. Mics doesn't work in both (both build-in and headphones)

**Comment by kisak-valve** [comment]
Hello @TheGP, this issue is already being tracked at #1514. Closing as a duplicate.

**Comment by TheGP** [comment]
@kisak-valve So why its not resolved?
