### ISSUE TITLE
FPS loss on linux with latest update

### ISSUE THREAD

**Issue by abdullahkhalids** [ValveSoftware/Dota-2#1736]
#### Your system information

* System information from steam: [gist](https://gist.github.com/abdullahkhalids/093c1b235d637da7c5ca8f9ee1448013)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Till last month, I had 35-40 FPS. One of the last few updates (around 7.26a) resulted in a FPS drop to 10-15 FPS. I did a full system update (Debian buster), reinstalled steam and dota from scratch, with no change. 

#### Steps for reproducing this issue:

1. Play Dota on 7.25 patch: Observe 35 FPS.
2. Update to lastest version of Dota. Observe 10-15 FPS.

**Comment by abdullahkhalids** [comment]
I updated my system to Debian testing. No change

Your system information

* System information from steam: [gist](https://gist.github.com/abdullahkhalids/9c62a777948b6b1d2f4e3933aa772f1c)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Console text when I run .steam/debian-installation/ubuntu12_32/steam-runtime/run.sh   .steam/debian-installation/steamapps/common/dota\ 2\ beta/game/dota.sh 
[console.txt](https://github.com/ValveSoftware/Dota-2/files/4595022/console.txt)

Not sure what else I can do? Will installing Ubuntu help in anyway? Or has my hardware been deprecated by steam/Dota?

**Comment by sylware** [comment]
yep, severe performance loss (GL or vulkan, min or max settings).

It gets nasty in heavy teamfights making tought to read what's happening and... when I hold the alt key in order to display the augmented map info!
