### ISSUE TITLE
[Mac] Game is detecting phantom inputs.

### ISSUE THREAD

**Issue by gramathy** [ValveSoftware/Dota-2#174]
I don't have a good way of explaining this in detail so i'm going to just link the video I took. Persists between restarts of game, Steam, and computer. Unplugged mouse, continues to happen. In general I don't think it's an input issue on my end as it can be seen happening in the background right after the "Heroes" tab is clicked.

Video: 

https://www.dropbox.com/s/2iascjyxj1jwy5h/2015-06-30%2019-15-07.mp4?dl=0

System information:

https://gist.github.com/gramathy/5996562

**Comment by computerquip** [comment]
Almost looks like your keyboard's at fault although I'm not sure what's being pressed at the main menu to cause that. 

Try unplugging your keyboard ;)

**Comment by ArnaudAndre** [comment]
The diagonal sliding makes me think of what you'd get from a plugged in gamepad. If this was source 1 you could put `-nojoy` in the game's launch options but I don't know if they kept that in source 2.

**Comment by gramathy** [comment]
Console is also spamming 

CSosOperatorSystem::StartSoundEvent Unable to find soundevent focus_change_fail

but unsure if related.

**Comment by gdrewb-valve** [comment]
I don't know what would trigger this and I haven't seen it pesonally so investigation will be difficult.  Can you get out of this state?  You mention it persists across restarting Reborn, so you mean you can exit Reborn and when it starts again it immediately has input problems?  Does any other program show similar issues?

**Comment by gramathy** [comment]
Restarting reborn results in the same behavior as the video, I.e. It's not intermittent with respect to restarting the game.

I actually haven't restarted my machine but I can try that when I get home. I don't think it's related to my hardware as it only showed up after the most recent patch and only seems to trigger upon entering the Heroes tab.

**Comment by gdrewb-valve** [comment]
Just to be clear, it only affects Reborn once you go to the Heroes tab?  If you exit Reborn and restart Reborn things function correctly until you go to the Heroes tab again (if there's an easy way to determine that without going to the Heroes tab)?  It would make more sense if it's something about the Heroes tab that causes it.

**Comment by gramathy** [comment]
Okay, narrowed down the cause

I *do* have a joystick plugged in as Arnaud says, on a G13 which didn't occur to me. As long as it was plugged in at some point between startup and launching Reborn (not necessarily at the point Reborn in launched) this happens. 

So as long as I leave the G13 unplugged I'm fine. Can't find where to put -nojoy (if it's even still an option) in the launch script to test that as a flag. Not sure if this affects all joysticks or just me.

**Comment by ArnaudAndre** [comment]
to add command line parameters : in your steam library right click dota 2 -> *properties* -> the *general* tab has a *set launch options* button

**Comment by gramathy** [comment]
That didn't work.

**Comment by gdrewb-valve** [comment]
-nojoy is supposed to still be supported so if that's not working for you it's unclear what exactly is going on.  At least you've isolated it to the joystick.

**Comment by gramathy** [comment]
Seems to happen with any joystick and can be resolved by moving the joystick. Like there's a default position that will move the selection that gets cleared when you change the joystick input at all. Combined with #85 could explain the "sticking" heroes tab as it processes more events as if the heroes tab was still open when it's not.

**Comment by gdrewb-valve** [comment]
Does that happen with -nojoy also?  That's supposed to turn off joystick input in the engine.

**Comment by gramathy** [comment]
Yes, -Nojoy is on in the launch options (it's actually my only launch option atm). The joystick continues to work despite this. Tested using a SNES controller that has the dpad hardware mapped to joystick axes and the G13 from earlier.

**Comment by gdrewb-valve** [comment]
That's odd as then Reborn itself shouldn't be looking at joysticks at all.  We'll still need to try and repro this at Valve.

**Comment by gramathy** [comment]
Curiosity and testing show that the G13 is the cause of the "permanent" screwiness and that the SNES!joystick works fine once you do something with it while the G13 keeps doing unexpected stuff.

**Comment by MeioJo** [comment]
My 'Hero Screen is Freaking out" has been closed but I need to report a new wrinkle...

Main Page > Friends > Offline the system will not let me scroll thru my offline friends... it keeps forcing the scroll to be above the offline level.

**Comment by gdrewb-valve** [comment]
You should open a new issue for that and we can check if it's the same thing or different.

**Comment by gdrewb-valve** [comment]
After the May 18 update if you use -nojoy in your launch options does that have any effect?

**Comment by aaronleao** [comment]
@gdrewb-valve , can we close this?

**Comment by kisak-valve** [comment]
Closing per the last comment.
