### ISSUE TITLE
xinput and chatwheel on Linux

### ISSUE THREAD

**Issue by mvrozanti** [ValveSoftware/Dota-2#1741]
#### Your system information

http://ix.io/2lpf
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Discrete graphics
* Have you verified the game files?: clicked "Check integrity"

#### Please describe your issue in as much detail as possible:
After using `xinput` to change mouse sensitivity, all cursor interactions in game work, except for the chat wheel. Whenever I move the cursor while the chatwheel is visible it goes to either top left direction or bottom right depending on my `xinput` device properties, and it also displaces the cursor position by itself when the pointer is moved by the user.

I've seen a few existing issues around here about xinput and the chatwheel, but I'm not sure if this is a duplicate.

#### Steps for reproducing this issue:

1. Install xorg-xinput on a Linux machine with xorg 
2. Execute 
```
sensitivity=2; xinput list | grep -i mouse | sed -e 's/.*id=\(..\)\s.*/\1/' | xargs -n1 -I{} xinput set-prop {} 161 $sensitivity 0 0 0 $sensitivity 0 0 0 1
```
3. Open Dota
4. Try to use the chatwheel

**Comment by betovidal** [comment]
Why is this closed? What's the workaround? I'm having this behavior too.
