### ISSUE TITLE
Dota2 White Noise Bug

### ISSUE THREAD

**Issue by xmorpheu5x** [ValveSoftware/Dota-2#1741]
I have been hearing random white noises while viewing my own dota profile and that of others.It doesn't stop there while gaming i keep hearing the annoying noise which spoils gameplay.Please look into this and solve it ASAP.
Thanks !

**Comment by Turmfalke2** [comment]
I just came here to report the same issue, I had it happen the first time yesterday. It happened prior the 6.84 update, maybe it is related to a steam update?
If you need any additional information please let me know.

**Comment by DarkwaveMD** [comment]
As a temporary solution I muted Game Volume in Audio/Video setting.

**Comment by Turmfalke2** [comment]
From what I have found here https://github.com/ValveSoftware/steam-for-linux/issues/3823 it might be related to the steam beta.

**Comment by ramma** [comment]
Downgrading to the stable version of steam is the current workaround for this. Typing snd_restart in console has temporarily fix it for some on the Beta branch though.

As @Turmfalke2 said, the bug is reported at the link above, and it has been reviewed by the Steam client devs.

**Comment by davidw-valve** [comment]
This should be fixed now. Make sure you have the latest version of Steam ( File -> Check for Updates).
