### ISSUE TITLE
[Linux] Ingame Store checkout does not work

### ISSUE THREAD

**Issue by jimmylinux** [ValveSoftware/Dota-2#1742]
Hello,
I want to buy the compendium, but checkout doesn't work. If I click the green "checkout" button on the shopping cart page, the page just reloads again and again. Impossible to proceed and buy something.

I am using Opensuse 13.2 with KDE. Systeminformation here:
https://gist.github.com/jimmylinux/f02e6ed2748d4192a99e

**Comment by jimmylinux** [comment]
I bought it now through the website:
http://www.dota2.com/store/

but I guess the shop should work also inside the dota 2 client.

**Comment by davidw-valve** [comment]
Does the Steam Overlay work for you in-game? Do you have it enabled? (i.e. does pressing alt+tab while in-game bring up the Steam Overlay?) The game uses the Steam Overlay to complete the purchase.

**Comment by jimmylinux** [comment]
Thx for the reply. Enabling Steam Overlay resolves the problem (for me (KDE?), shift-tab brings up the steam overlay, with alt tab I browse through the active windows). 

I didn't know that Steam Overlay has to be enabled for the store. Issue solved.

(by the way, thank you a lot for the great linux version of dota 2! It works very well)
