### ISSUE TITLE
French translation missing - battlecup advert.

### ISSUE THREAD

**Issue by abobier** [ValveSoftware/Dota-2#1746]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/abobier/d3676390219faf71746a64e132282968
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Ticket price of battle cup is not good displayed with the french translation ({s:ticket_price}).
![dota2_fr_translation_pb](https://user-images.githubusercontent.com/418482/82730063-3484d180-9cfd-11ea-8c28-38e2fbe744ca.png)

#### Steps for reproducing this issue:

1. Launch Dota2 from Steam where battle cup is available (weekend)

**Comment by danginsburg** [comment]
Thanks, I've passed this along to the larger team as it is unlikely to be platform specific.
