### ISSUE TITLE
After patch of BP TI 10 Mac Problem with Brightness and with creeps

### ISSUE THREAD

**Issue by zeroberus1** [ValveSoftware/Dota-2#1749]
After updating the patch of the new TI 10 this happened to my game.
it became dark even with max brightness and everytime i put my cursor into a creep or hero it becomes dark.
i also used -vulkan to launch the game because after the patch it doesnt let me get into the game

**Comment by kisak-valve** [comment]
Hello @zeroberus1, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328. Closing as a duplicate.
