### ISSUE TITLE
error panorama:RquiredCallFailed for 'GuildsContainer'

### ISSUE THREAD

**Issue by KerzaGG** [ValveSoftware/Dota-2#1751]
#### Your system information

* System information from steam https://gist.github.com/KerzaGG/afa503f753ee332133121f66a15a9fa7
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I open dota 2 and an error shows https://i.imgur.com/y9OcHXr.png I have uninstalled and re-installed and verifying game files does not fix it either.

#### Steps for reproducing this issue:
I can't explain any steps to reproduce this issue, I just updated the game and tried to opened it.

**Comment by kisak-valve** [comment]
Hello @KerzaGG, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team.

**Comment by KerzaGG** [comment]
Will do, apologies. Thank you for correcting me,
