### ISSUE TITLE
[Unable to start the game] Game Crashes after showing DotA logo,

### ISSUE THREAD

**Issue by arunstop** [ValveSoftware/Dota-2#1753]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in https://gist.github.com/arunstop/4bb07feabe270b5984cacdfbc040d4d9
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes (Using latest intel hd graphics driver)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

- I started the game

- Waited couple seconds as the DotA in the middle 

- It shows this ![download](https://user-images.githubusercontent.com/10150211/82851401-e86aa480-9f29-11ea-9322-83dc5962c3ee.png)

- The game closes

Note : I also noticed something after i hover on some blank space(in this case i accidentally hovered to my friend's account in the friend list tab in the bottom left) then the status/preview of his dota account popped like normal, I couldnt take a screen shot because the game closes immediately

### Steps for reproducing this issue:

1.  Starts dota in win 7 x64

**Comment by arunstop** [comment]
Update : 

- Tried this [VULKAN thing](https://github.com/ValveSoftware/Dota-2/issues/1747#issuecomment-633700575) **didn't work**

- Tried to delete all new webm videos [like in this reddit thread](https://www.reddit.com/r/DotA2/comments/gqlwma/for_my_potato_pc_gang/) **didn't work**
Please valve, I've been thankful enough to have dota at my side, escaping my life for some hours, now i can't play this game, especially in these hard pandemic time, when everything goes south, it is so depressing at this point.

**Comment by Deathtale27** [comment]
i feel you bro, still waiting and hoping for the fix to come soon.

**Comment by kisak-valve** [comment]
Hello @arunstop, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team. As a side note, Your Intel HD 3000 isn't capable with Vulkan.

**Comment by arunstop** [comment]
Hi @kisak-valve thank you for the feed back, i tried to go to https://dev.dota2.com i couldn't register, well technically i registered, but i cannot log in with steam it says 
![image](https://user-images.githubusercontent.com/10150211/82854737-8adb5580-9f33-11ea-917c-ecb341383c3f.png)

**Comment by araujo-fabio** [comment]
Had a problem with Win 7 x64 and I can't also login into https://dev.dota2.com :(
