### ISSUE TITLE
[Windows] Game doesn't start after Battle Pass update

### ISSUE THREAD

**Issue by araujo-fabio** [ValveSoftware/Dota-2#1754]
(First, I know this is supposed to be on www.dev.dota2.com as it's a Windows problem but the forum is closed to anyone who doesn't have "auth key", so me and others that are experiencing this can't post on there. I'm sorry for using here but it's the only way I can be sure Valve know about this.)

#### Your system information

* System information from steam: https://gist.github.com/araujo-fabio/d7409a0e1300c1eb120574b01d022e99
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

So after the Battle Pass update the game doesn't open. It says it's running, then it closes and create a <.mdmp> file at <.../dota 2 beta/game/bin/win64>. I picked three of these files and made a zip. This happens also on Artifact 2.0 Beta, so I put a file from there also (starts with dgc). The zip: https://drive.google.com/file/d/1kdP_V_c8NTaHfhiaKfy49d2_H1rUMj4G/view?usp=sharing

#### Steps for reproducing this issue:

1.Try to open Dota 2

**Comment by sergeypa18** [comment]
have you found a fix for this ?

**Comment by araujo-fabio** [comment]
> 
> 
> have you found a fix for this ?
No and I still can't login into https://dev.dota2.com :(
