### ISSUE TITLE
[MacOS][Mojave] Screen becomes black when mouse hover over creep units.

### ISSUE THREAD

**Issue by Nmerey** [ValveSoftware/Dota-2#1755]
Using -gl also tried -vulkan.

When mouse is hovered above creep unit or over some heroe in particular screen becomes black except for that unit mouse is hovered upon.

**Comment by danginsburg** [comment]
Is this the same issue as this? https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328

Are you sure it happens with both OpenGL and Vulkan?  Please post system information and ideally a video or screenshot.  Thanks.

**Comment by Nmerey** [comment]
Yes it is the same issue sorry for not checking previous answers!

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookAir7,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  1800 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.14.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 6000
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x1626
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.22" x 7.01" (13.23" diag)
                                            28.5cm x 17.8cm (33.6cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  115511 Mb
    Largest Free Hard Disk Block:  4805 Mb

**Comment by danginsburg** [comment]
That's OK but my impression from the other bug was that it was exclusive to Vulkan and doesn't happen with OpenGL, but you're saying it happens on both, correct?

**Comment by Nmerey** [comment]
I can confirm that it was because of -vulkan. I had same problem though when I switched in-game to -gl. But when I unchecked Vulkan box in DLC settings it worked normally.

**Comment by danginsburg** [comment]
Ah, it requires a restart if you change the rendering API.  OK I'm going to close this in favor of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328.  It seems it's happening only on Iris 6xx
