### ISSUE TITLE
[macOS] All the bars margin top is not on the correct position in the game interface

### ISSUE THREAD

**Issue by adrianhihi** [ValveSoftware/Dota-2#1756]
macOS Catalina Version 10.15.3

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Detail: all the rating bars padding/margin-top are not on the correct position related to the bar track.

#### Steps for reproducing this issue:

1. Launch Dota
2. goto the "STATS" tab
3. You can see the  hero's rating bar displays weird
4. The same as TEAMMATES tab's rating bar

**Comment by danginsburg** [comment]
Can you please provide a screenshot and include your system information?

**Comment by kisak-valve** [comment]
Closing pending feedback.
