### ISSUE TITLE
dota 2 will not launch with vulkan while using EGPU , works with OpenGL

### ISSUE THREAD

**Issue by olevistnes** [ValveSoftware/Dota-2#1757]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Computer Information:

[gistfile1.txt](https://github.com/ValveSoftware/Dota-2/files/4682296/gistfile1.txt)

<details><summary>System Information</summary><p>

```
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.4 (64 bit)

Video Card:
    Driver:  Radeon RX 580
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision:  0xe7
    Number of Monitors:  2
    Number of Logical Video Cards:  3
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 2880
    Primary Display Size: 23.46" x 13.19" (26.89" diag)
                                            59.6cm x 33.5cm (68.3cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  239072 Mb
    Largest Free Hard Disk Block:  21120 Mb
```

</p></details>

* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] N/A
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

The game has worked with the setup (Mac-thunderbolt-gaming box(https://www.gigabyte.com/Graphics-Card/GV-RX580IXEB-8GD#kf)-display port-external monitor) since I got it last year. 

After TI10 battle pass update however: the game will launch with -vulkan when the EGPU  is DISconnected, and Im using the internal monitor, but when I connect the EGPU (through Thunderbolt with DisplayPort connecting the external monitor) the icon bounces once in the dock and game never launches.

If I use the extension -gl in the launch options, the game launches with the EGPU and external monitor, but with significantly lower performance, and the in-game video menu states im running OpenGL API. 

#### Steps for reproducing this issue:

1. connect EGPU Gaming Box Radeon RX580 through thunderbolt, use external monitor
2. enable -vulkan in launch options
3. start game

**Comment by danginsburg** [comment]
Can you run with -con_logfile in your launch options and upload ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/console.log to this bug report?  I don't have an eGPU setup here that I can test with, but perhaps we can diagnose from the console.  One thing to try is doing -adapter 1 on the command line to see if that works.  I need to see how the GPU is getting reported to Vulkan.

Thanks.

**Comment by olevistnes** [comment]
Thanks for your reply! here is the log file:

[console.log](https://github.com/ValveSoftware/Dota-2/files/4684655/console.log)

Did you mean I should try the -adapter 1 ? If so, what is the command line? :) and how to put it there? :)

Thanks again!

**Comment by danginsburg** [comment]
That console.log was with -gl, can you do it with -vulkan?  I meant in the "Launch Options", that puts it on the command line.

**Comment by olevistnes** [comment]
I tried now to use the launch options: -con_logfile -vulkan 

and the game will not start, and the log file is empty, zero byte.

**Comment by rodion-b** [comment]
having exactly same issue, log file is empty as well.

**Comment by danginsburg** [comment]
Can you try launching from the command line then in a terminal?  ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota.sh and paste the output?

It's not getting very far if there is no console output.

**Comment by rodion-b** [comment]
please have a look at the console output when running dota.sh
https://gist.github.com/rodion-b/0e48f484e3d2238c869b118af3663b27
the process exits after 
Created VkInstance with the following 3 Vulkan extensions enabled:

**Comment by olevistnes** [comment]
@danginsburg Did @rodion-b reply give you the required info? My apologies, but my tech insight is limited, so I would need a more detailed guide to do what you asked.

**Comment by danginsburg** [comment]
Yes, but unfortunately I'm not sure what is happening.  Based on some crash dumps I'm seeing here I suspect it is failing in vkCreateDevice in MoltenVK.  Can you try overwriting your libMoltenVK.dylib with the attached version and see if it gets further?  This should be placed in ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/ (overwriting the existing version - you may want to make a backup).

[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/4688606/libMoltenVK.dylib.zip)

**Comment by olevistnes** [comment]
Hi. 

I set the launch options to -vulkan -con_logfile, and replaced the libMoltenVK.dylib file. When I tried to open the game it refused to open with the message that the developer was unconfirmed 
(norwegian here, sorry:)

<img width="416" alt="image" src="https://user-images.githubusercontent.com/65955967/83023316-07059400-a02d-11ea-8d6d-dbaa5ec76085.png">
 
I then tried to click "Cancel" , but the message popped up again. After pressing "cancel" 6 times  the game started. Then , in the game under the video settings, it stated that the API used was OpenGL. 

The console.log looked like this after that:

[console.log](https://github.com/ValveSoftware/Dota-2/files/4688958/console.log)

**Comment by longd3** [comment]
same issue here, please check the output of the launch bash https://gist.github.com/longd3/df2fefc99b010992604a83a6c48d862d

**Comment by rodion-b** [comment]
> Yes, but unfortunately I'm not sure what is happening. Based on some crash dumps I'm seeing here I suspect it is failing in vkCreateDevice in MoltenVK. Can you try overwriting your libMoltenVK.dylib with the attached version and see if it gets further? This should be placed in ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/ (overwriting the existing version - you may want to make a backup).
> 
> [libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/4688606/libMoltenVK.dylib.zip)

Hi, 

this fix worked for me.

Please let me know if you need any more dumps

**Comment by olevistnes** [comment]
@rodion-b did you have to make that permission exeption for it to launch?

edit: I fixed permissions for libMoltenVK.dylib and the game started with Vulkan as API. The performance is significantly lower than before however. 

this is the log:

[console.log](https://github.com/ValveSoftware/Dota-2/files/4690282/console.log)

**Comment by rodion-b** [comment]
@olevistnes no i didnt encounter any permission issues.

Also regarding performance seems back to original levels of around 140 fps vs 60 with open gl... try to reduce the settings as they are going back to default when changing API.

**Comment by danginsburg** [comment]
So something regressed in MoltenVK with respect to initialization with an external GPU.  I'm going to need to bisect the change that caused the problem here.

**Comment by danginsburg** [comment]
Might be related to https://github.com/KhronosGroup/MoltenVK/issues/875

**Comment by danginsburg** [comment]
We believe this will be fixed by https://github.com/KhronosGroup/MoltenVK/pull/889 .  The next Dota update will have the new version of MoltenVK.

**Comment by danginsburg** [comment]
This should be fixed with the most recent update.  Let me know if not.

**Comment by rodion-b** [comment]
great thanks a lot
