### ISSUE TITLE
[MacOS] UI buttons are not responding

### ISSUE THREAD

**Issue by irclam** [ValveSoftware/Dota-2#1759]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/irclam/b6b54fb8b7bbbf53b6de7ce08695f8bc
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I am unable to click on most of the buttons in the Dota2 client. I cannot open my friends list or guild from the bottom left corner and cannot click on Play Dota to open list of game modes. I am able to receive party invites but cannot click accept. The home, heroes, store and watch tab are working but the the Learn and Arcade tabs are not. Within each tab, most of the UI is also not working. UI components that are working are working quickly (like opening the settings).
The problem seems to be limited to the right and bottom 3/4 of the screen based on which heroes I can select in the heroes tab.
I have tried uninstalling and re-installing and using Vulkan DLC with -vulkan in startup options but the same problem repeats.

#### Steps for reproducing this issue:

1. Open Dota 2 from Steam with or without Vulkan DLC

**Comment by kisak-valve** [comment]
Hello @irclam, this issue is already being tracked at #1750. Closing as a duplicate.
