### ISSUE TITLE
[Mac] Exiting full screen doesn't bring Dota to its previous space

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#176]
When exiting fullscreen, a Mac app is supposed to come back to its previous space. Dota 2 does not and stays in a space with a uniform grey background and no desktop icons. 
OS X 10.9.5.

**Comment by gdrewb-valve** [comment]
How are you exiting fullscreen?

**Comment by jeanlain** [comment]
By selecting windowed mode in the graphic options.

**Comment by gdrewb-valve** [comment]
I don't see that.  Here's what I did:
1. Start the game and go to video settings (I started with a borderless window).
2. Select 1280x800 fullscreen and apply.  Reborn takes the whole screen.
3. Select borderless window (leaving 1280x800) and apply.  Reborn goes back to a window on my desktop.

**Comment by jeanlain** [comment]
Ok the issue only occurs when full screen resolution is 1680*1050, which is the native resolution of my display.

**Comment by gdrewb-valve** [comment]
Does the 7/2 update change this?

**Comment by jeanlain** [comment]
No it doesn't.

**Comment by danginsburg** [comment]
This has been fixed.  The fix will be in the next release.

**Comment by danginsburg** [comment]
Fixed in 7/20 release.  Closing this bug, let us know if you see it again.
