### ISSUE TITLE
Mac Issues with Dota Client

### ISSUE THREAD

**Issue by chabbott09** [ValveSoftware/Dota-2#1762]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist]
https://gist.github.com/chabbott09/ab7be8be9dd4ce810bc6a4c1492c4b25
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Started with consistently being taken out of queue after trivia questions answered, got into a game but was unable to click the minimap or open shop using clicks. Ended up abandoning game but now have issues in client even after abandon penalty. Inability to left click certain tabs on Mac such as exiting Dota, Learn, Arcade, Play Dota, view player profiles, and Accept/Decline party invitations. This is not a mouse issue as some tabs can be opened and I have tried one 3 different working mice that open tabs on non-Mac computers.

#### Steps for reproducing this issue:

1. Open Dota 2 from Steam Client with no launch settings
2. Can only click on certain tabs (My own profile, heroes, store)
3. No response when clicking on tabs mentioned in description of error

**Comment by kisak-valve** [comment]
Hello @chabbott09, this sounds like the issue being tracked at #1750 which should have [a fix lined up](https://github.com/ValveSoftware/Dota-2/issues/1750#issuecomment-634228890).

Closing in favor of the existing issue report.
