### ISSUE TITLE
Can't take Dota Plus reward

### ISSUE THREAD

**Issue by WhisperSign** [ValveSoftware/Dota-2#1766]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/WhisperSign/c00a4be58acabc28c1c665c337471c08
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Im trying to get reword from Dota Plus for wining 300 games. But game says that "there is error number 6, because you have no internet." But my internet is ok.

<img width="682" alt="Снимок экрана 2020-05-28 в 19 43 10" src="https://user-images.githubusercontent.com/58968947/83170152-c38a5300-a11c-11ea-83ea-c1601b9d205e.png">

<img width="515" alt="Снимок экрана 2020-05-28 в 19 43 02" src="https://user-images.githubusercontent.com/58968947/83170433-33004280-a11d-11ea-8c79-01371bd7103e.png">

**Comment by danginsburg** [comment]
Thanks this issue is not platform-specific and the larger team is working on it.
