### ISSUE TITLE
Switching window mode reverts to initial resolution

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#177]
Repro steps:
(here under OS X 10.9.5)
Launch the game, go to the graphic settings. Change resolution (don't apply yet). Then switch from windowed to fullscreen or vice verse (don't apply). Watch the resolution drop-down menu go back to its previous value.

**Comment by gdrewb-valve** [comment]
This is expected as the resolution list can vary between screen modes and is reset from your desktop resolution.

**Comment by jeanlain** [comment]
But if the new resolution is compatible with the new mode, it should stay selected. It's not.

**Comment by gdrewb-valve** [comment]
That's not the way it's set up, but I'll mark this as an enhancement request.

**Comment by gdrewb-valve** [comment]
This happens on Windows also and was passed on to the larger team a while ago.
