### ISSUE TITLE
GPU wont keep boosted on High-end graphics cards

### ISSUE THREAD

**Issue by org30h** [ValveSoftware/Dota-2#1776]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/org30h/2b768cda9d7f38f019c505cdf2204edc): 
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available  for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
GPU usage is low (~25%) and thus won't trigger GPU boost. During all time GPU is struck at base clock (which is 1350 Mhz for my Gigabyte 2080 Ti gaming OC). CPU is 10% usage, 4.3GHz all core boost, steady at 60°C, and GPU is steady ~50°C with 20% power draw. Nothing is throttling. I'm playing under 1440p with average framerate of 110FPS.

#### Steps for reproducing this issue:

1. Limit the max FPS to 169 (cuz I have a 144Hz monitor) then launch DOTA2. Main menu shows GPU usage <30%, runs at base clock without GPU boost.
2. Play a game, record the average FPS (120 frames per second).
3. Remove the FPS cap, re-launch DOTA2. The framerate immediate reaches 240Hz with GPU usage of 60%, triggers GPU boost and 2080 Ti runs at 2000Mhz (OC mode).
4. Play a game, the average FPS (now 180 frames per second).

**Comment by kisak-valve** [comment]
Hello @org30h, this issue tracker is limited to issues with the Linux and Mac variants of the Dota 2 client. You'll want to post this at https://dev.dota2.com for the larger Dota 2 team.
