### ISSUE TITLE
[Linux] Dota exits to desktop instead of advancing to hero selection screen after TI10 update

### ISSUE THREAD

**Issue by pwiecha** [ValveSoftware/Dota-2#1777]
https://gist.github.com/pwiecha/80043e77ac7f6f0bed94af6f95671ca8
Gist includes:
**System information generated from steam
Error.log from .steam/
Console.log from steamapps/common**

**Crash dmp file**: 
[crash.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/4725620/crash.dmp.zip)

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Yes
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 exits to desktop after loading into the match (w/ bot or normal) after TI 10 and following updates.
When starting the bot match or accepting the normal game, Dota 2 logo on black background appears which should be followed by Hero Selection screen. Instead, game exits to desktop w/o any error message or sound.
Tried running Dota from Steam GUI and terminal (steam steam://run/570).

Dota 2 options: -console -vulkan  -high -novid (TI 10 video lags a lot) -con_logfile (for debug info) 
#### Steps for reproducing this issue:

1. Launch Dota 2
2. Start a solo bot match
3. Wait for game to exit to desktop instead advancing to hero selection screen

**Comment by kisak-valve** [comment]
Hello @pwiecha, the minidump you attached is a SIGSEGV in libvulkan_radeon.so, which makes this a video driver crash and mesa 18.0.5 is a couple years out of support.

If possible, please update to a newer distro release and retest.

**Comment by pwiecha** [comment]
Thanks @kisak-valve for looking into that. 
From what I've gathered, mesa 18.0.5 is the latest stable for my Elementary OS distro based on Ubuntu 16.04 LTS  which is supported until 2021. Unfortunately distro upgrade to newer Elementary OS requires reinstall instead of simple dist upgrade.

Changing all video settings to low or starting w/o -vulkan switch is not helping. 

I will try to install newer mesa from some PPA.

Thanks again.

**Comment by pwiecha** [comment]
Unable to update to a newer drivers, closing.
