### ISSUE TITLE
vulkan workaround does not work

### ISSUE THREAD

**Issue by jamielsharief** [ValveSoftware/Dota-2#1778]
New patch does not work, now two windows come up 1 this error and a constant allow dota through the firewall, despite it already being configured.
```
bool CAppSystemDict::LoadSystemAndDependencies(CUtlVector<CAppSystemDict::AppSystemRequest_t> &, ErrorResponse_t)():
AppSystemDict: Error in Init() of interface 'RenderDeviceMgr001'!
```

**Comment by kisak-valve** [comment]
Hello @jamielsharief, this issue is already being tracked at #1760 / #1765 / #1774. Closing as a duplicate.
