### ISSUE TITLE
[Windows 10] Game crash 

### ISSUE THREAD

**Issue by Melknix** [ValveSoftware/Dota-2#1779]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/Melknix/710b22c7442c691e2893e2cb14faccc7

* Have you checked for system updates?: YES (autoupdate)
* Are you using the latest stable video driver available for your system? YES (autoupdate)
* Have you verified the game files?: YES (verified, downloaded again and verified again)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Every time start a game, when I land in pick screen the game crash. This issue happend after compendium update since day one of release. I waited until now to open this issue because I was confident that next updates solve the problem, but nothing change.
I tried with any video settings, DirectX (both), OpenGL and Vulkan, but the problem is the same with every kind of video driver.

I'm confident in a solution.

#### Steps for reproducing this issue:

1.  Start Dota
2. Start any kind of game type (I use bot for no penality)
3. When land in pick screen game crash

**Comment by Turmfalke2** [comment]
> Tracker for issues specific to Linux and Mac in the Reborn client. If you have a general issue or non-system-specific feature request please go to dev.dota2.com

**Comment by kisak-valve** [comment]
Hello @Melknix, as noted by @Turmfalke2, this issue tracker is limited to Mac and Linux issues in the Dota 2 client. You'll want to use https://dev.dota2.com or Steam Support for the feedback to get to the larger Dota 2 team.

**Comment by Melknix** [comment]
My mistake, thanks
