### ISSUE TITLE
[Linux] Having short freezes during game

### ISSUE THREAD

**Issue by Samega7Cattac** [ValveSoftware/Dota-2#1781]
#### Your system information

* [System information from steam](https://gist.github.com/Samega7Cattac/cc0ced739a4c523d088177b182bee965)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: No

#### Please describe your issue in as much detail as possible:
Having short freezes (from 3 to 5 secs duration) during game and then gets back to normal, but quite often. During that time one of the CPU cores was at 100% and the frametime spike.
The system is still responsive.
Mouse control still works.

#### Steps for reproducing this issue:

1. Playing a normal match.

#### Screenshot

![Screenshot_20200613_103503](https://user-images.githubusercontent.com/25128554/84566199-4d662d00-ad67-11ea-8244-51dc23b9005e.png)
FPS is capped to 60 and normally is always around there.
Normal frametime is 16.5ms (it's normal a bit of inconsistent against bots but not 30ms)
(ignore the GPU usage)

**Comment by kisak-valve** [comment]
Hello @Samega7Cattac, this reads like the video driver is compiling shaders for the game as they are needed. If that is true, then you should be able to go to Steam -> Settings -> Shader Pre-Caching and enable both `Enable Shader Pre-Caching` and `Allow background processing of Vulkan shaders` to mitigate this.

Expect that the first run and after video driver updates to take a fair amount of time, and pre-caching updates should be relatively quick.

**Comment by Samega7Cattac** [comment]
I have both enabled since always but still

**Comment by Samega7Cattac** [comment]
There's a drop in my GPU usage, no usefull info on `dmesg`.
On dota console: `[Entity System] ExecuteQueuedCreation() took 1180us [ Spawned: 1, Activated 1, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]` (idk if related)
No unusual usage in disk, memory or disk cache

**Comment by Mayurifag** [comment]
Having same issue

Probably thats not related to Linux but all the OSes

**Comment by Samega7Cattac** [comment]
Maybe related to [this fossilize issue](https://github.com/ValveSoftware/Fossilize/issues/84), since it's an issue I have related to shaders, rn using the workaround (`RADV_DEBUG=nomemorycache`) and uncap the fps seems to help but still happens.

**Comment by Samega7Cattac** [comment]
The fossilize issue was solved but the freezes still happen, more often since last update making it literally unplayable

**Comment by Samega7Cattac** [comment]
@Mayurifag what OS ur using?

**Comment by Mayurifag** [comment]
@Samega7Cattac I have ArchLinux with all required latest packages. I have i7-8565U / 16GB RAM / SSD / no discrete videocard setup

in my situation it doesnt seem to be related for the issue you have mentioned, but still thanks for information :smile:

**Comment by Samega7Cattac** [comment]
GPU usage have a dump every time it happens:
![Screenshot_20200913_031028](https://user-images.githubusercontent.com/25128554/93008976-32c46f80-f573-11ea-9692-d10167e5b74a.png)

and on CPU one of the cores goes to 100% and the other also have a dump:
![Screenshot_20200913_031618](https://user-images.githubusercontent.com/25128554/93008993-4a9bf380-f573-11ea-86f3-d0ab6bbb87b8.png)

**Comment by Samega7Cattac** [comment]
![IMG_20200913_033853_HDR.jpg](https://user-images.githubusercontent.com/25128554/93009044-ceee7680-f573-11ea-9456-a5af2807c8e9.jpg)

System was too unstable so switched to another tty
Idk if it's normal for dota to be using +2Gb of ram and ~60% of my CPU just on post-game screen too(same thing on main menu)

@kisak-valve it's been 3 months already, if u need any more info just ask.

**Comment by Samega7Cattac** [comment]
got a new SSD and moved the game to there, since then I didn't have this issue so I will close this for the time being
