### ISSUE TITLE
[Windows] CAppSystemDict:Unable to load interface VMediaFoundation001 from valve_wmf

### ISSUE THREAD

**Issue by GlassGhost** [ValveSoftware/Dota-2#1782]
Upon launching Reborn Beta in Windows 7 x64 I get the following error.

![CAppSystemDict:Unable to load interface VMediaFoundation001 from valve_wmf](http://i.imgur.com/finZLXQ.png)

**Comment by gxgani** [comment]
https://github.com/ValveSoftware/Dota-2/blob/master/README.md
