### ISSUE TITLE
[Reborn][El Capitan] Crashes every time on launch screen 

### ISSUE THREAD

**Issue by atanasbozhkov** [ValveSoftware/Dota-2#1785]
As a developer - I am running El Cap Build 1. 
I just installed Dota 2 Reborn, but it seems to crash straight after the UI shows up on the screen. 

Crashlog - http://pastebin.com/HmyY2MLk

I know it's still in beta - just thought this might be helpful.

**Comment by gdrewb-valve** [comment]
You can leave this but please open Reborn issues in Dota-2-Reborn.

**Comment by atanasbozhkov** [comment]
Sorry did not realise that there was a new repo. I followed the link from the dota dev website.
