### ISSUE TITLE
[LINUX] Reborn Starts up on wrong monitor

### ISSUE THREAD

**Issue by Disk1of5** [ValveSoftware/Dota-2#1786]
It seems that Dota 2 - Reborn doesn't use the main monitor, original Dota 2 works correctly.

It would be nice to choose what display to use in a multi display setup.

**Comment by gdrewb-valve** [comment]
You can leave this but please open Reborn issues in Dota-2-Reborn.

**Comment by gdrewb-valve** [comment]
Closing now that this is in the Reborn repo.
