### ISSUE TITLE
Mac version of dota very slow

### ISSUE THREAD

**Issue by Stravalition** [ValveSoftware/Dota-2#1789]
Was really excited to find that reborn was finally available on mac, loaded it up and I was instantly hit with excruciatingly painfully slowness. One mouse clock wouldn't register for minutes, I can't play any kind of game and I tried changing setting but it does nothing and it takes ages to do.

**Comment by gdrewb-valve** [comment]
Please post Reborn issue in the Dota-2-Reborn repro (which already has multiple perf reports).
