### ISSUE TITLE
[Windows] DotA crashes in picking phase or opening cavern crawl map

### ISSUE THREAD

**Issue by arunstop** [ValveSoftware/Dota-2#1789]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/arunstop/4bb07feabe270b5984cacdfbc040d4d9): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Usually it happens CONSTANTLY when i got into a game ranked/non-ranked, the picking phase screen comes, then something like this pop-out of nowhere 
![Screenshot_148](https://user-images.githubusercontent.com/10150211/86203839-2e9dce00-bb90-11ea-8e9f-070c82cacfd1.png)
then the game crashes, after that i try to reconnect into the game the same thing happen again and again until the system picked me a random hero, and i got 2hrs abandon + 3 lp games right after that, i've experienced this 2 times, after the battle pass update, before that my dota was running normally.

It also happens when i tried to open any battle pass content, the cavern crawl usually crashes the game the most initialized with the same pop-out. I've tried to search any fix from reddit, other github issues and i couldn't find any fix, usually the "fix" is to add "-vulkan" to the launch option but my vid driver doesn't support that. Also before this battle pass update, i was using the video driver version of 2013 because it was super stable on my device, could run dota smoothly with 0 problem, but since the same thing same error happened i tried to update it to the newest version of it(2015), but it didn't change a thing, i tried to roll it back to the 2013, the same error still there.

In a hard times like this playing dota is my escape from the bitter reality, but after this errror, it is so hard for me wanting to play ranked dota while having anxiety disorder and experiencing this surge of anxiety thinking that my game possibly will crash and i will get 2hrs abandon + 3 lp games. I hope i can fix this error here

#### Steps for reproducing this issue:

1.  Start dota
2.  Queue into games
3.  Picking screen shows up, the error pop-up shows up, application crashed
OR
1. Start dota
2. Click  the cavern crawl icon on  the left section
3. The error pop-up shows up, application crashed

**Comment by kisak-valve** [comment]
Hello @arunstop, this issue tracker is limited to the Linux and Mac client of Dota 2. You'll want to post this at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
