### ISSUE TITLE
Hud displays artifacts in the gaps between hud pieces.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/Dota-2#179]
Artifacts from other UI  such as health bars and player names will appear within the gaps between the hud pieces.

Example - http://steamcommunity.com/sharedfiles/filedetails/?id=472927914
Looking next to the inventory and at the very bottom of the image below the spells is the issue I'm referring too.

System specs - https://gist.github.com/ramma/925cc19fb6fd7805979e

**Comment by danginsburg** [comment]
I see this on Windows/DX9 at 1920x1080 as well so this is not a Linux/OSX-specific issue.

**Comment by danginsburg** [comment]
I have reported this issue to the larger team, but will not continue to track it here since it is not Linux-specific.
