### ISSUE TITLE
Dota 2 Crash on viewing Profile Page

### ISSUE THREAD

**Issue by eoaeoa** [ValveSoftware/Dota-2#1791]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/eoaeoa/47aa272914cc49a23f7b976cc02a6b99
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

 My Dota crashes whenever I view any profile page.(Mine or others).
Though, this issue only seems to be occuring while using dx11, no issue when using dx9. I even reinstalled steam and Dota, but issue still persists

#### Steps for reproducing this issue:

1. Open Dota (with dx11).
2. Open any profile page(own or others).
3. The Profile page loads(at least from what i can see), and then immediately dota crashes(just direct quits).

**Comment by eoaeoa** [comment]
Let me know if u need any more info.

**Comment by kisak-valve** [comment]
Hello @eoaeoa, this issue tracker is limited to the Linux and Mac client of Dota 2. You'll want to post this at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
