### ISSUE TITLE
Windows - Game crashes when opening a profile

### ISSUE THREAD

**Issue by Ersain** [ValveSoftware/Dota-2#1794]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Ersain/38bd538856e7cbf9d8a4caebde318fa1): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/)
I updated my video card drivers and since then the game crashes every time when I open a profile.

#### Steps for reproducing this issue:

1. Launch the game
2. Click on game profile

**Comment by kisak-valve** [comment]
Hello @Ersain, this issue tracker is limited to the Linux and Mac client of Dota 2. You'll want to post this at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the feedback to get to the larger Dota 2 team.

**Comment by ersain** [comment]
Sorry for late reply. Anyone who is facing the same issue should try launching the game in directx 9 (put -dx9 to your launch commands), at the time of my issue I was playing the game without discrete GPU
