### ISSUE TITLE
Mac - Strange rendering of Text and Overlays in Dota 2 Reborn

### ISSUE THREAD

**Issue by SerialForBreakfast** [ValveSoftware/Dota-2#1795]
OSX  10.10.3 (14D136)

When entering the game, text becomes unreadable, and controls do not function normally.

![sysinfo](https://cloud.githubusercontent.com/assets/1834967/8364059/27a89bd2-1b38-11e5-8539-d3e7b5d2994f.png)

http://imgur.com/a/CRMlT
![screenshot 2015-06-25 10 52 17](https://cloud.githubusercontent.com/assets/1834967/8364050/16cb60d8-1b38-11e5-99a9-963797cdd363.png)
![screenshot 2015-06-25 10 52 59](https://cloud.githubusercontent.com/assets/1834967/8364051/16cc29e6-1b38-11e5-8057-357e131528e9.png)
![screenshot 2015-06-25 10 56 23](https://cloud.githubusercontent.com/assets/1834967/8364049/16cb40bc-1b38-11e5-8394-f7c638863e1e.png)

**Comment by gdrewb-valve** [comment]
Please file Reborn issues in the Dota-2-Reborn repro.  This problem is already covered there, so closing this one out.
