### ISSUE TITLE
On Linux Dota 2 Reborn opens on my secondary monitor and Dota 2 opens on my main

### ISSUE THREAD

**Issue by dubcanada** [ValveSoftware/Dota-2#1797]
Hello,

I seem to be having a problem with dual displays, on my computer with nvidia drivers Ubuntu 14 regular Dota 2 opens on my main monitor. And Reborn opens on my secondary monitor.

Is there a way to force Reborn to open on my main monitor? I've tried everything including random SDL command line options. My only option seems to be turn off my secondary monitor, start dota, turn on secondary monitor.

**Comment by gdrewb-valve** [comment]
There is a separate Dota-2-Reborn repo for Reborn issues.  This is already captured there, so closing.
