### ISSUE TITLE
crash at the end of Aghanim's Labyrinth

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1800]
hi,
At the end of every Aghanim's Labyrinth run the games crashes for me. It doesn't matter whether I win or lose, it is a 100% reliable crash. Even watching someone else play and lose triggers the crash.

`dota2[44526]: segfault at 560fae5ee318 ip 00007ff0f1804e26 sp 00007ffce6ed00b0 error 4 in libworldrenderer.so[7ff0f17cc000+108000]`

[crash_20200718011027_1.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/4940704/crash_20200718011027_1.dmp.txt)

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/Turmfalke2/846b08702f77c1bdd679ad397a4165e4
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Steps for reproducing this issue:

1.  Play the event
2. lose or win

**Comment by Turmfalke2** [comment]
I just played 2 rounds without it crashing, did you change anything?

E: and back to crashing.

**Comment by jacobcraner** [comment]
Mine is randomly crashing too.

**Comment by burjui** [comment]
Same problem
https://gist.github.com/burjui/4cb35a8d6c80b2f53d52b73d3de5fc4e

**Comment by awstanley** [comment]
Add my system to that list.  Has been happening for the whole event seemingly unrelated to who people are playing.  Fortunately it's just the end of the event, and awards are given.  But constantly having to re-launch and re-party is a drag.

https://gist.github.com/awstanley/b0396d6323e6a90ef54662ecc5292c02

Have you checked for system updates?: Yes
Are you using the latest stable video driver available for your system? Yes
Have you verified the game files?: Yes

I'm using the Vulkan renderer and the minidumps are always access violations.  Significant points being:

> ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
> FAILURE_BUCKET_ID:  INVALID_POINTER_READ_AVRF_c0000005_worldrenderer.dll!Unknown

From the latest crash:

```
STACK_TEXT:  
00000071`706ff140 00007ffb`71488e60 : 00000000`000006aa 00000187`28220a00 00000186`6a5c0320 00000000`0000053b : worldrenderer+0x12987
00000071`706ff180 00007ffb`71481645 : 00000186`c0ce0200 00000000`00000001 00000000`00000000 00000000`00000000 : worldrenderer+0x18e60
00000071`706ff1b0 00007ffb`7148cf58 : 00000000`00000001 00007ffb`715a12c0 00000000`00000000 00007ffb`7148d13d : worldrenderer+0x11645
00000071`706ff1f0 00007ffb`7148bb7c : 00000000`00000000 00000186`00000000 3f800000`00000003 c5800000`80000000 : worldrenderer+0x1cf58
00000071`706ff240 00007ffb`47235a12 : 00000000`00000017 00000185`caa80000 00007ffb`5be34457 00007ffb`bc7fa880 : worldrenderer+0x1bb7c
00000071`706ff280 00007ffb`47235c44 : 00000000`00000016 00007ffb`843ab5d1 00000071`00000003 00000000`00000016 : client+0x195a12
00000071`706ff2b0 00007ffb`47236592 : 00000186`673b3928 00000186`673b3928 00000000`00000000 00000000`00000000 : client+0x195c44
00000071`706ff2e0 00007ffb`47237966 : 00000000`00000000 00007ffb`0000001a 00000186`7f9e00c0 00007ffb`48a66480 : client+0x196592
00000071`706ff350 00007ffb`47237f15 : 00000186`00000000 00000000`0000001a 00000186`673b38e0 00000000`00000000 : client+0x197966
00000071`706ff4e0 00007ffb`47796cf0 : 00000185`965f01e0 00000186`37542300 00000000`00000006 00000000`00000000 : client+0x197f15
00000071`706ff510 00007ffb`5bb4d654 : 00000071`706f017e 00000186`26d50180 00007ffb`5bf7c238 00000071`706ff630 : client+0x6f6cf0
00000071`706ff550 00007ffb`5bb4b957 : 00000186`26d50180 00000000`00000003 00007ffb`5bf7c238 00000186`26d50180 : engine2!Source2Main+0xaab4
00000071`706ff580 00007ffb`5bb5060e : 00000000`00000000 00000186`26d50180 00007ffb`5be34457 00000000`00000001 : engine2!Source2Main+0x8db7
00000071`706ff5b0 00007ffb`5bb4707a : 3f8eca0a`3c765054 3f8eca0a`7aa80000 00000000`0322eb7b 00000186`42d66810 : engine2!Source2Main+0xda6e
00000071`706ff5e0 00007ffb`5bb469eb : 000000ff`00000000 00000000`0322eb7b 00000071`706ff7a9 00007ffb`00000000 : engine2!Source2Main+0x44da
00000071`706ff6e0 00007ffb`5bb3e5a2 : 000000ff`b5746a9f 00000071`706ff7a9 00000000`00000000 00007ffb`a7634c59 : engine2!Source2Main+0x3e4b
00000071`706ff740 00007ffb`5bb3f3cc : 00007ffb`00000000 00000000`00000003 00000000`00000053 00000000`00000000 : engine2+0x14e5a2
00000071`706ff810 00007ffb`5bb42d68 : 00007ff6`848b0000 00000000`00000000 00000000`0000000a 00007ffb`5be77d70 : engine2+0x14f3cc
00000071`706ff8b0 00007ff6`848b1313 : 00000000`0000000a 00000000`00000000 00000185`c7de5115 00000000`00000000 : engine2!Source2Main+0x1c8
00000071`706ff940 00007ff6`848b15f7 : 00000000`0000000a 00000000`00000000 00000000`00000000 00000000`00000000 : dota2+0x1313
00000071`706ffa90 00007ffb`bc626fd4 : 00000000`00000000 00000000`00000000 00000000`00000000 00007ffb`a77d0000 : dota2+0x15f7
00000071`706ffad0 00007ffb`bc7fcec1 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000071`706ffb00 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

**Comment by Turmfalke2** [comment]
Closing this since the even it is over and such the bug isn't reproduce able anymore.

**Comment by Turmfalke2** [comment]
Bug appears to be fixed in the new Labyrinth, so far every crash has been during the game instead of at the end of it.
