### ISSUE TITLE
Only fucking retards play dota 2

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/Dota-2#1801]
How the hell is it possible that in every fucking game there is someone who complains others and wants them to be reported and they themselves play like some fucking retards?

**Comment by deri82** [comment]
Then when you want to leave such a game, then you are banished as low priority.

Are the people at valve fucking retards themselves too?

**Comment by Tele42** [comment]
@deri82 You're obviously violating the code of conduct, this is not a forum to vent frustration.

**Comment by jaholliman** [comment]
I second that @Tele42. He must be butthurt. This issue needs to be closed.

**Comment by MrSchism** [comment]
Closing and locking.  Knock this off.
