### ISSUE TITLE
[Linux] Visible nodraw brush in Aghanim's labyrinth

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1802]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/468db42e8971f4af8640114ebdd8151ed4836ad5)
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: no

#### Please describe your issue in as much detail as possible:
A lot of nodraw are clearly visible all around in Aghanim's labyrinth. 
Is this a Linux only issue? Edit: after asking a few players, it seems some see them, some don't, most likely Windows users too.
This used to be a problem in the underwater Dota2 map until the fog got added and masked it.

![2020-07-18_21-50-35](https://user-images.githubusercontent.com/12895548/87861039-ba5e7b00-c942-11ea-9df1-f4b5bbbfeadd.png)
![2020-07-18_21-40-47](https://user-images.githubusercontent.com/12895548/87861040-bfbbc580-c942-11ea-86d8-c416cfba8a6c.png)
![2020-07-18_21-35-59](https://user-images.githubusercontent.com/12895548/87861043-c4807980-c942-11ea-8115-596be22ae2ea.png)
![2020-07-15_18-08-15](https://user-images.githubusercontent.com/12895548/87861047-c8140080-c942-11ea-847d-5fb89c9359ef.png)
![2020-07-18_22-43-30](https://user-images.githubusercontent.com/12895548/87861813-301a1500-c94a-11ea-813c-beae944627e1.png)

**Comment by kisak-valve** [comment]
Hello @glubsy, this issue is already being tracked at #1798. Closing in favor of the older issue report.
