### ISSUE TITLE
Cant launch dota since battlepass update

### ISSUE THREAD

**Issue by agendar** [ValveSoftware/Dota-2#1803]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/]
* Are you using the latest stable video driver available for your system? [Yes/]
* Have you verified the game files?: [Yes/]

Ok so how to start. I cant launch game since battlepass update. I tried everything possible u could try so here is the list:

Re-installed windows several times (WIN 10 2004, WIN 10 1709, EVEN WINDOWS 7 !!!)

Tried several gpu and motherboard drivers.

Tried to run bios default settings.

Tried dx9

Tried dx11

Tried opengl

Even tried VULCAN

Re-installed DirectX, re-installed all visual c++ , re-installed all frameworks from 3.5 to 4.8.

Running in administrator privileges

Tried windows 7 compatibility mode

Tried two different sound cards

Tried motherboard "sound card"

Tried messing with different video settings with amd software

and after all this, game just instantly crash after start.

Only os i was able to launch dota was ubuntu. I had dual boot for ubuntu just for dota and today after almost more than month i tryed again to perform clean windows install with no results.

I noticed something really interesting, if you remove videos folder from panorama folder and you will launch dota it will works. This only applies to Windows 7 but after short time dota will verify game files and it will create that files again so you wont be able to launch dota again.

In windows 10 (currently running 1709) things get even worse, if you do same procedure with videos folder game will not launch anyway unless you use -nosound launch option.

So all this started with battlepass update and it is not still fixed.

Win 10 video: https://www.youtube.com/watch?v=1ah1LtPvu40&

Win 7 video: https://www.youtube.com/watch?v=0kiG7eZdoPo

screenshot of debugger before game crashs https://imgur.com/a/ekGYggN

PC specs

i7 9700k , aorus z390 pro, rx 570 8gb, 16 gb ram, dota on ssd .

**Comment by agendar** [comment]
debugger screenshot , few seconds before gaming crashes https://imgur.com/a/ekGYggN

**Comment by kisak-valve** [comment]
Hello @agendar, this issue tracker is limited to the Mac and Linux client of Dota 2. You'll want to post this at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
