### ISSUE TITLE
Display bugs while trying to play in D2 Reborn Beta

### ISSUE THREAD

**Issue by ccjunior9** [ValveSoftware/Dota-2#1803]
![screenshot from 2015-07-01 10 16 59](https://cloud.githubusercontent.com/assets/13135618/8455347/56b75eee-1fda-11e5-9bf4-bac998cee8c5.png)
![untitled](https://cloud.githubusercontent.com/assets/13135618/8455451/21cd9b8e-1fdb-11e5-8b6d-24116eea51b9.jpg)

**Comment by ccjunior9** [comment]
(Sorry for my bad english, trying to learn as second language).

**Comment by ArnaudAndre** [comment]
Valve created a different repository for reborn. It's at https://github.com/ValveSoftware/Dota-2-Reborn

As seen in the readme there, reborn requires version 340 or higher of the nvidia driver and you seem to be running 331.

For reporting system specs you can use the sytem info tool in the steam main app -> help menu -> System Information.

**Comment by ccjunior9** [comment]
Oh. I'm sorry how many times I was wrong. Thanks for the patience.

**Comment by ArnaudAndre** [comment]
No worries. And anyway, there's a valid bug report here. They need to give better warning/visibility on the new requirements for reborn before moving it out of beta.

**Comment by gdrewb-valve** [comment]
You can open a request in Dota-2-Reborn for driver version notification but that gets difficult with the variety of configurations that Linux can have.
