### ISSUE TITLE
[MAC] Dota 2 Reborn graphical issues.

### ISSUE THREAD

**Issue by EchoKaph** [ValveSoftware/Dota-2#1806]
I am having a graphical issues with dota 2 reborn. I am not sure whether it is my graphics card at fault or the Dota 2 reborn client. The graphical issues only occur in the dota 2 reborn client and not the normal dota 2 cilent. Specs and pictures of issue are located below.

Processer: 3.06 GHz Intel Core i3
RAM: 4 GB 1333 MHz DDR3
Graphics Card: ATI Radeon HD 4670 256 MB

![screen shot 2015-07-06 at 7 10 44 pm](https://cloud.githubusercontent.com/assets/13199148/8521131/6f2821ec-2413-11e5-88d6-23fa6b5f96ff.png)
![screen shot 2015-07-06 at 7 08 12 pm](https://cloud.githubusercontent.com/assets/13199148/8521132/70496900-2413-11e5-9798-c392603ea608.png)

**Comment by gdrewb-valve** [comment]
There's a specific repo for Reborn, Dota-2-Reborn.  I believe this is the same as issue 24 there.
