### ISSUE TITLE
Penalty in SEA Region

### ISSUE THREAD

**Issue by Shawon91sust** [ValveSoftware/Dota-2#1806]
You guys should provide less penalty in SEA region since we live in 3rd world country and it's normal scenario that load shedding occurs in this region so much. I have been placed in low priority pool though all my fault was my country's electricity distribution is poor like my country's economic background. And just today i got so much report but i had an accident with my monitor that i seemed to express in the whole game. But still you guys penalized me for no wrong done by me in the game.

Irony is that many abusers, cheaters get away with no penalty while honest players like us gets lp and time punishment. Sad it is.....

**Comment by kisak-valve** [comment]
Hello @Shawon91sust, this issue tracker is limited to issues with the Mac and Linux port of the Dota 2 client. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the feedback to reach the larger Dota 2 team.
