### ISSUE TITLE
Huge CPU/GPU Usage when window is supposedly minimized

### ISSUE THREAD

**Issue by RUSshy** [ValveSoftware/Dota-2#1810]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/RUSshy/c328db938ccf21276175216e7916db77
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

When i minimize the game, i expect it to use minimal ressources

But with dota it seems to ignore that state

OR

Your engine doesn't handle cases where game is minimized

I expect the following to happen in the main menu:

```
IF NOT minimized THEN
    update()
    render()
    poll_window()
ELSE
    poll_window()
```

#### Steps for reproducing this issue:

1. Start game
2. While in main menu, try to minimize the window
3. check CPU/GPU usage, they don't change

The same happen in all OSes (macOS tested on hackintosh)

**Comment by RUSshy** [comment]
Let's make out planet great again by not wasting ressources while i ALT tab waiting for matchmaking/people

**Comment by kisak-valve** [comment]
Hello @RUSshy, this issue tracker is limited to issues with the Linux and Mac client of Dota 2. Since all platforms are equally affected, you'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for your feedback to reach the larger Dota 2 team.
