### ISSUE TITLE
Let us Resize/Maximize the window in windowed mode

### ISSUE THREAD

**Issue by RUSshy** [ValveSoftware/Dota-2#1811]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/RUSshy/c328db938ccf21276175216e7916db77
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

I can't resize the window in windowed mode

#### Steps for reproducing this issue:

1. Start game
2. Switch to windowed mode
3. Resize button is grayed

The same happen in all OSes (macOS tested on hackintosh)

**Comment by kisak-valve** [comment]
Hello @RUSshy, this issue tracker is limited to issues with the Linux and Mac client of Dota 2. Since all platforms are equally affected, you'll want to post this over at https://dev.dota2.com or use Steam Support for your feedback to reach the larger Dota 2 team.
