### ISSUE TITLE
Dota 2 reborn is often freezes after last patch

### ISSUE THREAD

**Issue by xdevelnet-inc** [ValveSoftware/Dota-2#1818]
Dota 2 freezes when I
1) close ending table with match results
2) use "disconnect" command via console
3) use disconnect function from UI
4) Alt+Tab

Before last patch dota2 reborn was VERY stable&smooth.

Linux Mint 17.1, nvidia gtx560, nvidia-driver 352.21

**Comment by gdrewb-valve** [comment]
Please log Reborn issues in the Dota-2-Reborn repo.  There's already an open issue there on hangs.
