### ISSUE TITLE
Dota 2 - Viewing Profile Crashes

### ISSUE THREAD

**Issue by OxTanjaxO** [ValveSoftware/Dota-2#1821]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  <script src="https://gist.github.com/OxTanjaxO/1eb241826326b94e5b259f6039995a16.js"></script>
* Have you checked for system updates?: [Yes/No]: Yes
* Are you using the latest stable video driver available for your system? [Yes/No]: Yes
* Have you verified the game files?: [Yes/No]: Yes

#### Please describe your issue in as much detail as possible: Well I wiped my laptop with a fresh install of Windows 10 (I had dota 2 running perfectly fine before) and now that I redownloaded steam and installed dota2 again everytime I try to either click on my profile or other peoples profiles the game automatically closes with no error. I can view profile on dx9 but it is beyond terrible trying to play dota on that. I am currently running dota2 on dx11

Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).: I expect the ability to view my/other peoples profiles on the game again...

#### Steps for reproducing this issue:

1. Open Steam
2. Library > Dota 2
3. Click on Dota 2 Profile Image
4. Dota 2 Crashes

**Comment by kisak-valve** [comment]
Hello @OxTanjaxO, this issue tracker is limited to the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
