### ISSUE TITLE
[Mac OS X Yosemite] Dota2 Reborn Beta full screen mode not working

### ISSUE THREAD

**Issue by xmorpheu5x** [ValveSoftware/Dota-2#1821]
![screen shot 2015-07-21 at 20 32 12](https://cloud.githubusercontent.com/assets/12004849/8804097/29fa97cc-2fe8-11e5-9632-e050a8444b1e.jpg)

This happened right after the 1.8 GB update that enables ranked matches on reborn beta.

**Comment by gdrewb-valve** [comment]
Please open Reborn issues in the Dota-2-Reborn repo.  In this case go to your video settings and switch to a borderless window, then back to fullscreen or desktop-friendly fullscreen.  Does that fix it?

**Comment by OSnapz** [comment]
Checking "Use my monitor's current resolution fixed the issue". OsX Yosemite

**Comment by xmorpheu5x** [comment]
Thank you.I figured it out later.I'm using "Desktop-friendly fullscreen" mode at the moment. BTW i would've posted this on dev.dota2.com but i can't create a new account when i click "register" and i get the following error : 
![screen shot 2015-07-22 at 12 19 06](https://cloud.githubusercontent.com/assets/12004849/8819688/fc39086c-306b-11e5-9861-19bd44d6d94e.jpg)
