### ISSUE TITLE
Dota 2 Linux builds seem completely unstable

### ISSUE THREAD

**Issue by Kedstar99** [ValveSoftware/Dota-2#1825]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/Kedstar99/2684490578f1f28ceba082a8726a61db
* Have you checked for system updates?: [Yes]

* Are you using the latest stable video driver available for your system? [Yes]

* Have you verified the game files?: [Yes]

**What HAPPENS?**

So far with the new update I get regular crashes with anything involving particle effects, pudge arcana, loading screens. Every game I can guarantee at least one crash. When I reconnect, sometimes I can't get into the main menu because the cinematic loaded at the beginning just crash. This is with just OpenGL/Vulkan and has been for weeks.

The menu items don't work, the buttons for reconnecting don't work. I have played the game since 2012 and have abandoned somewhere around 20 games out of 4000. These updates has resulted in 2 unfair abandons caused out of my control.

Even exiting the game is painful and I am forced at times to use kill -9 and to wait an extended period.

My setup is not unusual, this is Ubuntu 20.04 with Nvidia RTX 2070 on a Ryzen 3600. This is having used both the native recommended Nvidia driver and one from Canonical's ppa gaming drivers.

It should be possible and just general practice to perhaps just buy two machines using a standard Ubuntu install with one Nvidia/AMD setup and see if you can record an hour or two gaming without issues. Heck this could be tested just by watching a dota replay. I am noticing a few other issues with symptoms similar to me.

Can I at least have some pointers to how to turn off some of this new graphical nonsense relating to the battle pass?

**What I expect?**

Not having dota 2 crashing every game. Being able to open the program reliably without having to attempt 3 times pkilling the process before getting into the game. Graphical effects like invoker spells, gyro spells not crashing the game. Being able to exit the game without it crashing because it's loading the pudge arcana. The list can go on.

#### Steps for reproducing this issue:

1. Just play the game with Nvidia on Vulkan or OpenGL latest graphics or otherwise.
2. 
3. 

Here is a copy of a dump when running opengl. https://gist.github.com/Kedstar99/44905d06c55f8214f978a4b3589c7e93

**Comment by tvelich** [comment]
Sounds like a duplicate of https://github.com/ValveSoftware/Dota-2/issues/1824

**Comment by Kedstar99** [comment]
Nope, it's been problematic/unstable since a a few weeks before the pudge persona, it's just become significantly worse with windranger update because now i can't even reliably open the game. Also I am referring to Ubuntu 20.04 not OS X.

**Comment by tvelich** [comment]
I am running Linux Mint 19.3 which is Ubuntu-based (albeit 18.04, not 20.04) and have not had any of those issues in the last few days. I just received my first crash in a long time a little bit ago which seems to coincide with the MacOS issue reports as well.

**Comment by Kedstar99** [comment]
That doesn't seem conclusive at all one way or another. Certainly not enough to duplicate or link the topics. I could be using a completely different compositor, graphics driver, hardware. AFAIK Mac hardware doesn't even have nvidia graphics cards. Just because you experienced some stability doesn't absolve my instability.

**Comment by tvelich** [comment]
I'm not saying it's conclusive, I'm just saying I haven't had any issues with the Linux build until the issue that started a few hours ago which is why I linked it. Good luck solving your issue.

**Comment by RichMartel** [comment]
I just want to report that I have a similar issue since the Windrunner arcana patch.  Arch Linux, Vulkan, Nvidia

**Comment by Kedstar99** [comment]
The only way I seem to somewhat play is by setting graphics to low. Even at the lowest settings it still crashes on opengl.

This shouldn't be the case with a ryzen 5 3600, rtx 2070 and 32gb of RAM machine.

**Comment by StefanTT** [comment]
Same problem here on two computers
one  Arch Linux, Vulkan, Nvidia
the other Arch Linux, Vulkan, AMD.

**Comment by Kedstar99** [comment]
@kisak-valve Can someone please look into this? It's pretty easy to reproduce with a nvidia graphics card, opengl/vulkan on any settings (opengl, vulkan highest or lowest graphics) Ubuntu 20.04 or Arch?

It's been weeks with crashes regularly.

**Comment by Saladin1812** [comment]
Not nvidia specific issue also on AMD since the update takes long to even load the valve animation and completely unstable it stucks between and rarely but yes crashes... I am on fedora.. this issue not distro specific.. valve updates this battlepass were soo bad because i couldn't even play..

**Comment by Saladin1812** [comment]
Since last few updates dota 2 stucks on pick phase not every time but every 4-5 games.. I got an LP because of dota bugs..  Long loading times and its just soo unstable these days.

**Comment by RichMartel** [comment]
I have problems if I use Vulkan, but Vulkan performance is so much better
than OpenGL.  So if I get stuck, I have to reboot, then remove the launch
options, start dota in opengl, close, put back the launch options (-high
-vulkan etc), then start it again (after shaders are updated).  Long
process, but once I'm in after that, it's stable, until I exit and my PC
sleeps.  If I were to restart dota it would lock up again.

**Comment by Kedstar99** [comment]
Can I suggest to make sure to use the -novid flag. There are a few crashes that occur with the introvideo which are eliminated with that flag.

**Comment by Kedstar99** [comment]
The latest 450 driver seems a lot more stable to me.

**Comment by RichMartel** [comment]
Things have been more stable for me as well.

**Comment by Kedstar99** [comment]
I'm gonna close this because at least the problem I was seeing was solved.
