### ISSUE TITLE
[Subject redacted]

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/Dota-2#1826]
Whatkind of fucking game is this?

**Comment by Tele42** [comment]
@deri82 why are you trying so hard to get yourself banned from this github issue tracker?  This is not acceptable or constructive behavior.

**Comment by gdrewb-valve** [comment]
I have blocked this user.  If you see anything more like this let me know.

**Comment by MrSchism** [comment]
Thank you @gdrewb-valve.  Will do.
