### ISSUE TITLE
Bonus treasure not available to claim

### ISSUE THREAD

**Issue by zee-1998** [ValveSoftware/Dota-2#1827]
#### Your system information
Computer Information:
    Manufacturer:  To Be Filled By O.E.M.
    Model:  To Be Filled By O.E.M.
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 3600 6-Core Processor              
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3593 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 1660 SUPER
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  27.21.14.5148
    DirectX Driver Version:  27.21.14.5148
    Driver Date: 6 21 2020
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 1660 SUPER
    VendorID:  0x10de
    DeviceID:  0x21c4
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.74" x 10.55" (21.50" diag)
                                            47.6cm x 26.8cm (54.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6143 MB
    Supported MSAA Modes:  2x 4x 8x 

Memory:
    RAM:  16313 Mb

*******************************************

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I have recycled immortal items for the bonus treasure, but haven't received anything. neither the treasure nor the Relai's Spin Wheel. Also, a window that shows the immortal recycling window is missing therefore I cannot track my recycling progress and cannot claim the bonus treasure. 

#### Steps for reproducing this issue:

1. Recycle the immortals for the bonus treasure
2. Recycle 4-5 immortals
3. Go back to claim the treasure
4. Be shocked for not receiving any treasures nor can see the progress. 

I attached 2 pictures for the visuals. The first picture (1) shows what I see in my game client and the second picture (2) shows what others see in their game clients.
![1](https://user-images.githubusercontent.com/70866047/92338141-50c63780-f07c-11ea-8195-611ee97ef96d.jpg)
![2](https://user-images.githubusercontent.com/70866047/92338143-528ffb00-f07c-11ea-9c00-76741254d370.jpg)

**Comment by kisak-valve** [comment]
Hello @zee-1998, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com for the larger Dota 2 team or use [Steam Support](https://help.steampowered.com/).
