### ISSUE TITLE
Steam helper eating up entire CPU usage after I updated Steam Client

### ISSUE THREAD

**Issue by adrianhihi** [ValveSoftware/Dota-2#1828]
I am using macOS Catalina version 10.15.6

MacBook Pro (15-inch, 2016)
2.9 GHz Quad-core Intel Core i7
16 GB memory
Radeon Pro 460 4GB Graphics

After I updated Steam client today, I launched steam, my mac started to be slow. I opened Activity Monitor and found that Steam Helper CPU usage increased up to 500%, which is too high. Besides, after I launched steam, the kernel_task increased rapidly as well.

**Comment by kisak-valve** [comment]
Hello @adrianhihi, please use [Steam Support](https://help.steampowered.com/) for your feedback about the Steam for Mac client.
