### ISSUE TITLE
Dota 2 - Reborn

### ISSUE THREAD

**Issue by keyxmakerx** [ValveSoftware/Dota-2#1829]
OS : Elementary based on Ubuntu 14.04
CPU : Intel i7-3820QM CPU
GPU : Intel 4000HD
Updated the drivers already, 

Getting error. 
Required OpenGL extension "GL_ARB_seperate_shader_objects" is not supported. Please update your OpenGL Driver. 

keyxmakerx@Tanzanite:~$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.0
OpenGL ES profile extensions:

**Comment by gdrewb-valve** [comment]
Reborn has its own repo, Dota-2-Reborn.  However in this case you'll need to find a source of a newer Mesa which supports the extension as Reborn can't run without it.
