### ISSUE TITLE
[Linux]'Random Hero' button on pick screen

### ISSUE THREAD

**Issue by supereddie** [ValveSoftware/Dota-2#183]
There are a few issues with the ''Random Hero' button on the hero pick screen.
First: the hit-test and tooltip trigger are slightly too high - you can press the button (and the tooltip shows) without an mouseover.
Second: After I have pressed the random button on the hero pick screen, the button changes to 'Browse Heroes' but not the tooltip. Moving the mouse doesn't fix it. Also, since the hit-test for Random was slightly too high, weird things happen when I click above the 'Browse Heroes' button (hint: the pick timer moves up) .

![dota2-random-tooltip](https://cloud.githubusercontent.com/assets/7723579/8456535/659d7556-200c-11e5-86da-f379d3bdc393.png)
_In the screenshot you see the X-windows mousepointer because I can't use the F6 key to take a screenshot - so I had to use an external program that apparently doesn't caputre a skinned mousepointer. The mouse position is accurate though._

**Comment by gdrewb-valve** [comment]
This happens on Windows also.  I've passed it on to the larger team and it won't be tracked here.
