### ISSUE TITLE
Why do I have to process vulkan shaders when im launching the game in OpenGL mode? 

### ISSUE THREAD

**Issue by u83rmensch** [ValveSoftware/Dota-2#1830]
this is actually just more of a question than a bug or an issue, see title. 

Why do I have to process vulkan shaders when im launching the game in OpenGL mode?

**Comment by kisak-valve** [comment]
Hello @u83rmensch, in general, Steam doesn't know in advance what graphics api a game is going to use. The shader pre-caching step can be expedited by enabling background processing of the shaders or avoided by disabling the feature in Steam entirely if it causes you any trouble.

**Comment by u83rmensch** [comment]
i was just curious. should consider adding an option to turn this on and off on a pergame basis then as it sounds like I wouldnt need it for dota but would probably still be good for any other proton/vulkan title.
