### ISSUE TITLE
[Linux] Degraded performance with nvidia latest stable drivers

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1831]
#### Your system information

* System information from steam: [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/809f160737ae68d3bc029750e39b52d3527b615d) 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: No

#### Please describe your issue in as much detail as possible:
Using both the OpenGL or Vulkan renderers, I see severe hitching in game since I updated my nvidia drivers from 440.100 to 450.66 (and upgrading the kernel from 5.7.7 to 5.8.8, on Arch Linux). I used to have near constant 60 FPS (+fps_max 64) but now I dip down between 45~55 FPS sometimes going down in the 30's FPS. 
I will downgrade my drivers and see if this makes a difference.

#### Steps for reproducing this issue:

1. Upgrade to latest proprietary nvidia drivers, (steam runtime or not, same result)
2. Start a game (with bots or online, same result)
3. Terrible performance with

**Comment by glubsy** [comment]
I can confirm that performance is back to normal after downgrading to nvidia-440.100 and downgrading to kernel 5.6.15 (had to use the [.run installer from the nvidia website](https://us.download.nvidia.com/XFree86/Linux-x86_64/440.100/NVIDIA-Linux-x86_64-440.100.run) because downgrading via Arch packages didn't work for some reason, this driver is such a mess). 

Yet another [report to the nvidia forum](https://forums.developer.nvidia.com/t/degraded-performance-in-dota2-with-latest-driver-450-66). Sheesh, so depressing. Surely next time I'll buy AMD.

**Comment by Kedstar99** [comment]
This is the same problem I am having on #1825 . I hope it gets fixed soon, but it's kind of concerning how there has been no response from Valve.

**Comment by glubsy** [comment]
@Kedstar99 I don't see how the two are related. In this case here, the game is not crashing. Considering the game runs fine with previous versions of the GPU driver and Linux kernel, it's possible this has nothing to do with the game itself. 

There is no response "from Valve" because Valve employees are most likely very busy already. Keep in mind they are a small team, and they probably stress a lot by just trying to fulfill their assigned tasks.

**Comment by glubsy** [comment]
Upgraded to driver version 455.23.04 and the performance is now much better, back to the usual 60FPS. 
However there is some serious hitching which may warrant its separate bug report. 

I get a lot of these errors which seem to match the hitching:
```
[Entity System] ExecuteQueuedCreation() took 2662us [ Spawned: 0, Activated 0, PostDataUpdate: 19, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
[Entity System] ExecuteQueuedCreation() took 1755us [ Spawned: 0, Activated 0, PostDataUpdate: 18, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
[Entity System] ExecuteQueuedCreation() took 1445us [ Spawned: 0, Activated 0, PostDataUpdate: 20, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
[Entity System] ExecuteQueuedCreation() took 3423us [ Spawned: 0, Activated 0, PostDataUpdate: 16, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
```
I also get these occasionally: 
```
Overflow of the sheet cache texture. Releasing and starting over. This is ok in asset browser, not so ok if the game is triggering this!
```
Need to investigate a bit more I suppose.
Also, sometimes there is a new very noticable hitching during opening / closing the chat dialog during the game. FPS count drops down to ~20FPS or so. It doesn't occur every game, but when it does, it happens every time the dialog is opened/closed until the end of the match. Very strange.

**Comment by glubsy** [comment]
I'm not experiencing this issue anymore since using nvidia driver 455.28 (and Linux kernel 5.4.72). Thanks!
