### ISSUE TITLE
Overflow error on linux dota 2 reborn

### ISSUE THREAD

**Issue by heabmi** [ValveSoftware/Dota-2#1833]
Had issues with overflow error maybe every fouth game or so. Loading screen seems to be missing graphics and when reconnecting the character animation loops.

**Comment by CalMlynarczyk** [comment]
I'm getting this every game now on 10.11 (it was working in 10.11 fine just a few days ago). A game would launch, then after everyone loads, all the avatars on the right disappear. I can only get the hero screen to appear after this if I alt-tab out of Dota, and alt-tab back in again. 

However, then my controls become unresponsive. Trying to select a hero or send a chat message is delayed by 45 seconds. Even when it does finally load my hero choice and I enter the match, the game just gets stuck looping on the same half-second of frames, making it completely unplayable. 

After awhile, it will just exit back to the main menu with an "Overflow error". Reconnecting to the game still just gives me the looping frames issue.

**Comment by heabmi** [comment]
Yeah, this started after the last update. I wish i could provide more info but that would mean five games in the low pool so I cant help with logs.

**Comment by gdrewb-valve** [comment]
Reborn has its own repo at Dota-2-Reborn.  This is already logged there as issue #306.  Some fixes have already been rolled out and more are coming.
