### ISSUE TITLE
Various problems and abnormal feedback of TI10 Zhibao skin

### ISSUE THREAD

**Issue by meihuajieaa** [ValveSoftware/Dota-2#1834]
The fact is that the unlocking method of Skeleton King’s Arcana 2 is a very failed design. This failed design makes it impossible to unlock Skeleton King’s Arcana 2, unless cheating is taken to unlock the style 2.

Also, the reflective design of Queen TI10's treasure skin is obviously a failure. Queen TI10's treasure skin is extremely reflective in many maps. For example, in the TI8 map, the queen TI10's treasure skin looks strange green all over.

When the treasure of Queen TI10 stands still in the game, the flame special effect of one foot will be missing and cannot be displayed.

The above issues are all important issues closely related to the interests of players and consumers. If V agency really values the rights of players and consumers, they will definitely be resolved. Therefore, you don’t have to trust what others say. You only need to follow the facts of V agency’s next actions. It is completely possible to know whether the attitude of V agency towards players is good or bad. This is the correct way to understand the truth.
![20200924115957_1](https://user-images.githubusercontent.com/72068206/94527971-59b8bc00-026a-11eb-8ce2-1cffb07ac1a3.jpg)
![20200924115955_1](https://user-images.githubusercontent.com/72068206/94527974-5a515280-026a-11eb-94ac-fdc775ffa0fc.jpg)
![20200924114021_1](https://user-images.githubusercontent.com/72068206/94527990-60473380-026a-11eb-8934-a9d8aeb1e624.jpg)
![20200924113926_1](https://user-images.githubusercontent.com/72068206/94528013-66d5ab00-026a-11eb-8f53-768e1c473711.jpg)

**Comment by kisak-valve** [comment]
Hello @meihuajieaa, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. This reads like general feedback for the game and you'll want to post this on https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
