### ISSUE TITLE
Behavior score on new account Issue

### ISSUE THREAD

**Issue by yoyohcx** [ValveSoftware/Dota-2#1838]
**Hello!**
![11](https://user-images.githubusercontent.com/72908316/96085117-fe710580-0ec8-11eb-8113-647a9a557e96.jpg)

I played on new account, 10 games in All pick, and 4 games in turbo mode, my start behavior score is 1.995! why i get this behavior when i dont have any reports and 12 commends on account! See Screenshot 11.jpg

**Comment by kisak-valve** [comment]
Hello @yoyohcx, this issue tracker is limited to issues with the Linux and Mac client of Dota 2. This looks like a general game question, and not a bug. You'll want to post this over at https://dev.dota2.com or the Steam community forums.
