### ISSUE TITLE
console has no font

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#184]
Console without font: no text, no typing, nothing.
I start reborn with -console command line switch

**Comment by gdrewb-valve** [comment]
You're running on Linux, correct?

**Comment by sylware** [comment]
yep

**Comment by weirddan455** [comment]
Check issue #120.  You will probably need to either install Microsoft Fonts or use the workaround I posted (2nd to last comment from the bottom at the moment.)

**Comment by sylware** [comment]
Damn I'm bad at search the issue database

Yes this bug is a duplicate of #120

**Comment by gdrewb-valve** [comment]
I don't believe this is a duplicate since #120 is fixed and you mention there you're still having issues.

**Comment by gdrewb-valve** [comment]
Actually reading your latest post it does sound like a duplicate, closing.
