### ISSUE TITLE
[Linux] number of held taffies incorrectly displayed in DireTide

### ISSUE THREAD

**Issue by glubsy** [ValveSoftware/Dota-2#1843]
#### Your system information

* System information from steam in a [gist](https://gist.github.com/glubsy/db894f0cc6359b3dc166530305864add/e5cedc469d4711c29e58b104ec47a3607110ae74)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: No

#### Please describe your issue in as much detail as possible:
In a DireTide game mode, the number of held taffies is not correctly displayed above each hero's head. 
It might be a font issue?
This also affects Roshan's requested taffies.

![2020-10-30_16-51-14](https://user-images.githubusercontent.com/12895548/97741745-8408ce00-1ae3-11eb-90dd-0707156962c2.png)

![2020-10-30_18-11-06](https://user-images.githubusercontent.com/12895548/97741806-9d117f00-1ae3-11eb-9df3-98469a062fa4.png)

**Comment by glubsy** [comment]
It seems to be fixed now. Thanks.

**Comment by glubsy** [comment]
Reopening because this is happening again.

![2020-11-04_18-09-45](https://user-images.githubusercontent.com/12895548/98142985-db82b180-1ec8-11eb-8009-aa88441d7221.png)
![2020-11-04_18-08-54](https://user-images.githubusercontent.com/12895548/98142990-dcb3de80-1ec8-11eb-9fa7-5b747ff74255.png)

Same game, in some cases it works, other times it doesn't:
![2020-11-04_18-13-22](https://user-images.githubusercontent.com/12895548/98143279-2f8d9600-1ec9-11eb-8cf4-bc0257a642d8.png)

![2020-11-04_18-13-53](https://user-images.githubusercontent.com/12895548/98143275-2e5c6900-1ec9-11eb-8f94-3a3784d4be49.png)

**Comment by danginsburg** [comment]
We are aware of this bug on Windows as well.  We are still having some difficulty reproducing it.  If you or anyone happens to come up with reliable repro steps please let us know.

**Comment by glubsy** [comment]
It seems to happen consistently when playing a "normal" dota2 game before playing a "diretide" game.

This problem never occurs, when playing a diretide game right after starting the game,

**Comment by glubsy** [comment]
I believe this doesn't occur anymore. Thank you!
