### ISSUE TITLE
After 30 october 2020 update fps drops to 15-30 fps in dota main menu and fps drops from 120 to 30-60 in a match on debian buster

### ISSUE THREAD

**Issue by koreanfan** [ValveSoftware/Dota-2#1844]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): steam:i386 1.0.0.59-4 4.19.0-12-amd64 ValveSoftware/steam-for-linux#1 SMP Debian 4.19.152-1 x86_64 GNU/Linux
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] YEs
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Launch dota
2. Fps drop to 15-30 in main menu
3. Play match, fps drops randomly form 120 to 30-60

**Comment by glubsy** [comment]
You did not provide enough information. You did not provide the correct system information.

**Comment by danginsburg** [comment]
We shipped some perf improvements for the main menu, please retest and see if it's better.  There also isn't enough in this bug for me to reproduce anything specific so I'm going to close it out.
