### ISSUE TITLE
[AMDGPU]Dota 2 crashes after diretide update - unplayable

### ISSUE THREAD

**Issue by Bednar87** [ValveSoftware/Dota-2#1845]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
YES
* Are you using the latest stable video driver available for your system? [Yes/No]
YES
* Have you verified the game files?: [Yes/No]
YES

journalctl: https://gist.github.com/Bednar87/37e408ef36d6d2af24d1a8c3b7ab1d5f
full system info - https://gist.github.com/Bednar87/3a140a44fdb15fbc021893d0726a2129

The game crashes and causes irrecoverable error. The only way to regain control of the computer is hard reset. It happens always when loading the dire tide game mode or when looking at sets in the new Halloween treasure. 100% reproducible - can't play the game at all on Linux.

**Comment by kisak-valve** [comment]
Hello @Bednar87, it looks like you've got more than one Vulkan driver installed. Are you running the game with radeonsi (OpenGL), mesa/radv (Vulkan), or amdvlk (Vulkan), and is the issue with one driver or more than one?

**Comment by Bednar87** [comment]
Hi @kisak-valve 

I am running the game using mesa/radv vulkan driver. I have not tested any other drivers.

**Comment by danginsburg** [comment]
Can you report back if this is still happening with the latest update?  I did find and fixed some Vulkan validation errors that theoretically could have caused this and that shipped in the latest Dota 2 update.

**Comment by kisak-valve** [comment]
~@danginsburg, https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7426 might also be related to this.~ Apparently unrelated based on local testing.

**Comment by Bednar87** [comment]
@danginsburg 

I just played through a diretide game without issues. browsing through sets in the new treasure does not cause the crash anymore either so I guess it's relatively safe to say SUCCESS! 

Thank you!

**Comment by danginsburg** [comment]
Glad to hear it, thanks for the follow up!
