### ISSUE TITLE
[Linux] [NVIDIA] Selecting multiple units at once in Diretide crashes the GPU's driver and freezes DotA's rendering thread.

### ISSUE THREAD

**Issue by eloquenza** [ValveSoftware/Dota-2#1847]
#### Your system information

* System information from steam in a gist:
https://gist.github.com/eloquenza/95920f0a07c1311e84fc560d32933a64
* Have you checked for system updates?
Yes
* Are you using the latest stable video driver available for your system?
Yes, I am using NVIDIA's newest driver, version 455.38 (nvidia-dkms package)
* Have you verified the game files?
Yes

#### Please describe your issue in as much detail as possible:

DotA2 (and only DotA2, no other game has done this) is crashing NVIDIA's driver under a few specific actions. ~This is reproducible for me by picking up an illusion rune or creating illusions via Manta Style in the Diretide Game Mode. This does not happen in other game modes which is why I suspect this has something to do with the cel-shade shader used in Diretide. I don't have earned that shader effect yet, so I cannot test it in other modes.~
After having earned the Diretide shader effect, I have tried to reproduce this in demo mode or a normal mode. I could not reproduce it.
The only time this crash happens is inside the Diretide game mode.
I have further narrowed this down to not spawning illusions but rather the selection of multiple (summoned) units at once via a box select or simply using the hotkey "Select All Other Units". I have confirmed this by playing Shadow Shaman and spawning Serpent Wards via his ultimate or Lycan and his wolves.

This crash manifests as DotA2 stopping to render any more frames, still playing sound and seemingly still accepted input as a friend confirmed for me while I was issuing move commands. The game does not exit by itself and I do not disconnect.  
The only way for me to fix this issue is to send a SIGKILL to DotA2 and restarting it. 

A `dmesg -wH` command shows the following when that crash occurs:

```
Nov 06 02:02:04 pcquenza kernel: NVRM: GPU at PCI:0000:01:00: GPU-1cfc27a8-d06f-825a-3fd5-fe5d6cf7c324
Nov 06 02:02:04 pcquenza kernel: NVRM: GPU Board Serial Number:   
Nov 06 02:02:04 pcquenza kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=194, Graphics Exception on GPC 0: 3D WIDTH ZT Violation. Coordinates: (0x30, 0x0)  
Nov 06 02:02:04 pcquenza kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=194, Graphics Exception: ESR 0x500420=0x80000004 0x500434=0x30 0x500438=0x20000 0x50043c=0x0  
Nov 06 02:02:04 pcquenza kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=194, Graphics Exception on GPC 1: 3D WIDTH ZT Violation. Coordinates: (0x38, 0x0)  
Nov 06 02:02:04 pcquenza kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=194, Graphics Exception: ESR 0x508420=0x80000004 0x508434=0x38 0x508438=0x20000 0x50843c=0x0  
Nov 06 02:02:04 pcquenza kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=26685, Graphics Exception: ChID 006f, Class 0000c197, Offset 00001a2c, Data 00000000  
```

#### Steps for reproducing this issue:

1. Queue for Diretide.
2. Pick Shadow Shaman/Lycan (with these heroes I have been able to reproduce it consistently, have not checked any other heroes).
3. Cast Serpent Wards or summon Lycan's wolves
4. Select them via a box select or using the hotkey "Select All Other Units"
5. Game render thread seems to freeze/crash, as no more frames are being rendered.

The picture below shows how such a crash manifests for me. I box selected all the Serpent Wards and NVIDIA's driver crashed with the following message:

```
[Nov14 01:43] NVRM: Xid (PCI:0000:01:00): 13, pid=1, Graphics Exception on GPC 0: 3D WIDTH ZT Violation. Coordinates: (0x28, 0xc)
[  +0.000008] NVRM: Xid (PCI:0000:01:00): 13, pid=1, Graphics Exception: ESR 0x500420=0x80000004 0x500434=0xc0028 0x500438=0x20000 0x50043c=0x0
[  +0.000011] NVRM: Xid (PCI:0000:01:00): 13, pid=1, Graphics Exception on GPC 1: 3D WIDTH ZT Violation. Coordinates: (0x24, 0x8)
[  +0.000006] NVRM: Xid (PCI:0000:01:00): 13, pid=1, Graphics Exception: ESR 0x508420=0x80000004 0x508434=0x80024 0x508438=0x20000 0x50843c=0x0
[  +0.000147] NVRM: Xid (PCI:0000:01:00): 13, pid=113695, Graphics Exception: ChID 0056, Class 0000c197, Offset 00001a2c, Data 00000000
```

![dev](https://user-images.githubusercontent.com/11320658/99134816-4d6ca080-2617-11eb-9ffd-43ee380ebe86.jpg)

#### Other thoughts

I have not yet been able to check if this occurs in an older driver version, or to perform a RAM test or other system checks.
According to [0], XID 13 could mean everything from driver error to thermal issue.
I have not observed any high temperatures neither is this happening in other games, which is why I am creating this issue here.  

[0] https://docs.nvidia.com/deploy/xid-errors/index.html

**Comment by danginsburg** [comment]
Are you running on OpenGL or Vulkan?

**Comment by eloquenza** [comment]
I am running Vulkan.

Here is a picture showing all my rendering options:
![dev](https://user-images.githubusercontent.com/11320658/98381480-dac15b00-2041-11eb-945d-d3847ae55986.jpg)

I also do not have "Auto Select Summoned Units" activated, which was a source of FPS loss when spawning a large amount of illusions, i.e. with the hero Phantom Lancer. So it is specifically the spawning of these illusions.

**Comment by danginsburg** [comment]
OK, thanks for all the info - this is very useful for reproducing bugs.  Unfortunately, so far I can't get this to happen on NVIDIA using your settings.

**Comment by eloquenza** [comment]
Thanks for all your time, I hope I am not wasting it. 

I had time to test it out again:  
I had another crash, this time as Silencer in Diretide. I picked up an illusion rune - driver did not crash, I tried to select them by drawing a box over them, driver crashed. Same error:

```
[Nov 7 01:26] NVRM: GPU at PCI:0000:01:00: GPU-1cfc27a8-d06f-825a-3fd5-fe5d6cf7c324
[  +0.000002] NVRM: GPU Board Serial Number: 
[  +0.000003] NVRM: Xid (PCI:0000:01:00): 13, pid=4294942763, Graphics Exception on GPC 0: 3D WIDTH ZT Violation. Coordinates: (0x4c, 0x1c)
[  +0.000007] NVRM: Xid (PCI:0000:01:00): 13, pid=4294942763, Graphics Exception: ESR 0x500420=0x80000004 0x500434=0x1c004c 0x500438=0x20000 0x50043c=0x0
[  +0.000011] NVRM: Xid (PCI:0000:01:00): 13, pid=4294942763, Graphics Exception on GPC 1: 3D WIDTH ZT Violation. Coordinates: (0x4c, 0x20)
[  +0.000015] NVRM: Xid (PCI:0000:01:00): 13, pid=4294942763, Graphics Exception: ESR 0x508420=0x80000004 0x508434=0x20004c 0x508438=0x20000 0x50843c=0x0
[  +0.000143] NVRM: Xid (PCI:0000:01:00): 13, pid=36274, Graphics Exception: ChID 003f, Class 0000c197, Offset 000017f4, Data 00060000
```

I am starting to suspect that this is something very specific to my system setup. But so far, I could not find anything.  
If this is still irreproducible for you, we should close this issue and I am going to notify you when I am going to find the source of the problem, just to provide you some peace of mind. :)

**Comment by eloquenza** [comment]
After receiving the Diretide shader effect, I have tried to narrow the problem down. 
I have updated the original post with additional info and changed the title to reflect what actually produces the crashes.

This might not help you, but I still wanted to keep you updated.
If you still cannot reproduce this, I am going forward with thinking this is a system-specific issue under which only I suffer.

**Comment by bahazilla** [comment]
Hello! 
I have the same Issue, and now all dota 2 games looks with render issues, even when I am just watching games.
![imagen](https://user-images.githubusercontent.com/40525878/99595048-a773ba00-29b9-11eb-9d7d-b400ebb6268e.png)
All started since Diretide.

**Comment by Kitsunow** [comment]
Unfortunatly, i have the exact same issue since todays update. First thought it would be my setup and reverted some packages to the state before i did an update today, but unfortunately the issue persisted. It is also bound to selecting units, e.g. Juggernauts healing ward.

```
[Jan19 21:53] NVRM: GPU at PCI:0000:01:00: GPU-f206c43f-585f-94f9-2d53-289b82eb0b7c
[  +0,000003] NVRM: Xid (PCI:0000:01:00): 13, pid=427, Graphics Exception on GPC 0: 3D WIDTH ZT Violation. Coordinates: (0x80, 0x0)
[  +0,000006] NVRM: Xid (PCI:0000:01:00): 13, pid=427, Graphics Exception: ESR 0x500420=0x80000004 0x500434=0x80 0x500438=0x20000 0x50043c=0x0
[  +0,000008] NVRM: Xid (PCI:0000:01:00): 13, pid=427, Graphics Exception on GPC 1: 3D WIDTH ZT Violation. Coordinates: (0x80, 0x8)
[  +0,000005] NVRM: Xid (PCI:0000:01:00): 13, pid=427, Graphics Exception: ESR 0x508420=0x80000004 0x508434=0x80080 0x508438=0x20000 0x50843c=0x0
[  +0,000102] NVRM: Xid (PCI:0000:01:00): 13, pid=977, Graphics Exception: ChID 0039, Class 0000c197, Offset 00001a2c, Data 00000000
```

I'm running on Linux 5.10 with nvidia 460.32 with vulkan.

**Comment by danginsburg** [comment]
@Kitsunow I checked in a fix for this that was in a recent update.  Give it a try again.

**Comment by Kitsunow** [comment]
@danginsburg Seems to work now. Ty!

**Comment by SirFireball3521** [comment]
I would like to re-open this because my game is also crashing in Diretide whenever I use manta style or pick up an illusion rune. I have not tested other types of multiple-unit selecting.

System info: [here](https://gist.github.com/SirFireball3521/fd8d230afefc0dc833f88368911584a0)

I am also running on Vulkan and Nvidia. I do have "auto-select summoned units" on.

**Comment by eloquenza** [comment]
Auto-selecting summoned units was enough the last time too. Any type of selecting multiple units at once was triggering this, including this option.
It is just back because of the Diretide shader, it is not Diretide game mode specific.
As @kisak-valve/@danginsburg fixed this before, I am sure they can do it again. :)

**Comment by mocxi** [comment]
my game keeps crashing  from last update and I added this option `-vulkan -vulkan_disable_graphics_pipeline_library` https://github.com/ValveSoftware/Dota2-Gameplay/issues/4851#issuecomment-1304560627

now it's freezed when I seletect multiple units...

**Comment by kisak-valve** [comment]
Hello, please open a new issue report so that your issue can be tracked properly. Too much time has passed for this to be evaluated as a regression.
