### ISSUE TITLE
Reborn - Mouse not fully captured borderless window

### ISSUE THREAD

**Issue by mikelat** [ValveSoftware/Dota-2#1847]
Desktop environment is KDE5, did not test other operating systems (windows, mac) could be an issue there too.

Settings are: Multimoniter setup, borderless window, and in KDE5 the window is set to fullscreen (it just overlaps my taskbar when the game is in focus).

Steps to reproduce:
1. At the beginning of loading into a new game, switch focus to another window.
2. When the game is loaded, return to the game. The mouse is not bound to the game window, and will leave the window to the second monitor if I try to pan the game in the direction of the second monitor.

I can fix it by quickly leaving back to the main menu then returning to game. If I keep the window focused while the game is loading, the game will properly lock the cursor to the window. This bug doesn't happen on the regular client, just reborn.

**Comment by Tele42** [comment]
Please file Reborn issues in https://github.com/ValveSoftware/Dota-2-Reborn.
