### ISSUE TITLE
Cannot connect to dota 2 servers

### ISSUE THREAD

**Issue by AETolouee** [ValveSoftware/Dota-2#1848]
#### Your system information

* Steam client version: 22 Aug 2018
* Distribution: Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### My issue:
I'm Experencing same issue as [5545](https://github.com/ValveSoftware/steam-for-linux/issues/5545) but none of the workarounds work for me.

My issue is connecting to dota 2 servers. when I click on "Find Match" button becomes gray and nothing happens. in Regions under all server it prints "Ping: Calculating ..." and when I try to watch a game, it says:

> Check your Internet connection. Unable to download the network configuration from CDN

What I've tried so far and didn't work:

- Setting LC_ALL to "C" and "en_US.UTF-8"
- Opting out of steam beta participations.
- Changing steam download server.
- Deleting all directories and files inside steam directory except steamapps

**Comment by kisak-valve** [comment]
Hello @AETolouee, are you still experiencing this issue on an up to date system?

**Comment by AETolouee** [comment]
No. I solved it randomly after I think a year. Apparently, Dota tries to get some necessary information to work with from a server, And that server is blocked in my country for some reason (Iran). After running steam through a vpn just once, It starts working.

**Comment by kisak-valve** [comment]
Thanks for the feedback. I'm going to tentatively close this issue because you found a solution, but if you figure out what server(s) were involved, we can reopen this issue for a Dota 2 dev to ponder.
