### ISSUE TITLE
linux mint 17.1, dota reborn graphic problems

### ISSUE THREAD

**Issue by suhis** [ValveSoftware/Dota-2#185]
Hello!

I have tried dota 2 reborn in my linux mint 17.1 and it has a lot of graphical issues, normal dota 2 works fine and there are no problems.  In character selection screen can't see any characters or buttons, just map and some empty boxes.

anyone else seen this kind of bugs?

![screenshot from 2015-07-01 17 40 30](https://cloud.githubusercontent.com/assets/13136806/8457219/c8bb53ea-2018-11e5-95db-4b2a7d6c379f.png)

![screenshot from 2015-07-01 17 35 31](https://cloud.githubusercontent.com/assets/13136806/8457052/ed0cc61c-2017-11e5-8664-19402ebd2f4a.png)

**Comment by gdrewb-valve** [comment]
There are a number of issues here covering various kinds of graphics problems.  A number of the worst are fixed and may have info for you.

Can you post your Steam system information?

**Comment by suhis** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3501 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux Mint 17.1 Rebecca (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-37-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.113
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x11c6
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 5760 x 1080
    Primary Display Size: 18,78" x 10,55"  (21,54" diag)
                                            47,7cm x 26,8cm  (54,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  7927 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  103759 Mb
    Largest Free Hard Disk Block:  74633 Mb
    
Installed software:
    
Recent Failure Reports:
    Tue Jun 30 20:01:36 2015 GMT: file ''/tmp/dumps/crash_20150630162959_1.dmp'', upload no: ''HTTP response code said error''

**Comment by gdrewb-valve** [comment]
Can you update your drivers to 352?  331 is known not to work.

**Comment by suhis** [comment]
ok, now it seems to work after driver update

**Comment by gdrewb-valve** [comment]
Thanks, closing.
