### ISSUE TITLE
Dota 2 drop FPS on MacOSX After Upgrade to Big Sur

### ISSUE THREAD

**Issue by alandwiprasetyo** [ValveSoftware/Dota-2#1850]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/alandwiprasetyo/aedff7eceea956af3408265e7278da51): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Dota 2 was running smooth on OSX Catalina with LOW FPS
Since the update to Big Sur, it has become unplayable FPS DROP

FPS drops on random locations
- Mouse clicks results in millisecond freezes
- moving the mouse on the map make FPS Drop

#### Steps for reproducing this issue:
1. Install Big Sur 
2. Install Steam + Dota
3. Play Game
4. Moving mouse to top/right/left/right on the map
5. drop FPS

**Comment by wangrunxinyes** [comment]
true, even with an egpu

**Comment by leonamjlpaula** [comment]
I'm facing this exact problem. I tried every possible configuration and tried reinstalling Dota 2 but the game remains unplayable. I have a macbook pro mid 2015!

**Comment by Bralva** [comment]
@leonamjlpaula dude, the same issue! but im playing on hackintosh with rx vega 56 GPU and when i move mouse in any direction my fps drop down...

I remember when i played with nice performance without any issue, it was 6 months ago maybe

I use mojave on my pc

**Comment by leonamjlpaula** [comment]
I'm investigating a lot and contacting apple also. If I discover anything I will describe here.

**Comment by kupe517** [comment]
Same problem here. Upgraded to Big Sur and my FPS is awful. Makes the game unplayable at the moment.

**Comment by leonamjlpaula** [comment]
I have tried these things and none solved my issues:

1. Reset NVRAM
2. Reset SMC
3. Remove graphics automatic adjustment for power supplies
4. Clean my fans (I was very necessary and improved overall performance)
5. Format my SSD and reinstall Big Sur.

But I still can't play the game.

**Comment by jimmygns** [comment]
same, fps glitch on big sur.

**Comment by justinharrell** [comment]
If you are using a usb gaming mouse it could be related to high polling rates (1000hz). Supposedly there are some improvements in 11.1 for the issue, but still advisable to lower the mouse polling rate to say 125hz.

I did this on my Razer Deathadder (Had to plug it into a Windows computer to run Razer Synapse) and set polling to 125hz, seemed to solve Dota performance issues and reduce CPU usage across the board. If you watch activity monitor and move the mouse back and forth you will see 100+% cpu in WindowServer, after the polling change its below 30%.

See:

https://discussions.apple.com/thread/252047056

https://www.reddit.com/r/mac/comments/juqcrd/calling_all_big_sur_users_here_check_windowserver/

**Comment by leonamjlpaula** [comment]
> If you are using a usb gaming mouse it could be related to high polling rates (1000hz). Supposedly there are some improvements in 11.1 for the issue, but still advisable to lower the mouse polling rate to say 125hz.
> 
> I did this on my Razer Deathadder (Had to plug it into a Windows computer to run Razer Synapse) and set polling to 125hz, seemed to solve Dota performance issues and reduce CPU usage across the board. If you watch activity monitor and move the mouse back and forth you will see 100+% cpu in WindowServer, after the polling change its below 30%.
> 
> See:
> 
> https://discussions.apple.com/thread/252047056
> 
> https://www.reddit.com/r/mac/comments/juqcrd/calling_all_big_sur_users_here_check_windowserver/

Amazing! I had downgraded to Catalina again to make things work, but this already enhanced a lot! I'll give it a try on Big Sur again but I'm pretty sure this will fix there either.

**Comment by justinharrell** [comment]
> Amazing! I had downgraded to Catalina again to make things work, but this already enhanced a lot! I'll give it a try on Big Sur again but I'm pretty sure this will fix there either.

Yes I guess MacOS can't handle fast mouse polling very well in general, but Big Sur has a really big problem with it making it very noticeable. However even in previous versions it is recommended to lower polling rate.

**Comment by alandwiprasetyo** [comment]
> If you are using a usb gaming mouse it could be related to high polling rates (1000hz). Supposedly there are some improvements in 11.1 for the issue, but still advisable to lower the mouse polling rate to say 125hz.
> 
> I did this on my Razer Deathadder (Had to plug it into a Windows computer to run Razer Synapse) and set polling to 125hz, seemed to solve Dota performance issues and reduce CPU usage across the board. If you watch activity monitor and move the mouse back and forth you will see 100+% cpu in WindowServer, after the polling change its below 30%.
> 
> See:
> 
> https://discussions.apple.com/thread/252047056
> 
> https://www.reddit.com/r/mac/comments/juqcrd/calling_all_big_sur_users_here_check_windowserver/

Its work well! I use Razer Deathadder v2, and change pooling rate from 1000hz to 125hz, the problem has been solved!
Thank you
