### ISSUE TITLE
[macOS] user cannot login Steam or Dota right now

### ISSUE THREAD

**Issue by adrianhihi** [ValveSoftware/Dota-2#1853]
macOS Big Sur Version 11.0.1
#### Steps for reproducing this issue:

1. Dota landing page displays that "offline" mode
2. checked wifi which is online
3. Logged out steam and re-try to login, failed

**Comment by kisak-valve** [comment]
Hello @adrianhihi, Valve's servers get restarted every Tuesday. This isn't a Dota 2 bug.
