### ISSUE TITLE
[Linux] Console spam when Effects Quality set to Medium or High

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#1855]
#### Your system information

* System information from steam: https://gist.githubusercontent.com/jazztickets/f07f40cf0896a257b911325fc21f5e1a/raw/a2733f55306e58e4b407f2e9058d8c54fbccb0aa/main%2520system%2520info
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
The console will spam the following message, rendering the console almost useless. It only happens if effects quality isn't set to low.

```
[SceneSystem] Error: View "Player 0", layer "GlowDepthStencil": 
	Unable to allocate space for scratch render target "output_depth_back_buffer...." 
	(type = copy, MSAA = off, Size = 1920x1080, Fmt = D24S8, Flags = 0x00000001)!
	(If you are in tools mode, you can add SVF_TOOL_VIEW to your view to allow dynamic allocations.)
```

#### Steps for reproducing this issue:

1. Set Effects quality to Med/High.
2. Open console

**Comment by danginsburg** [comment]
I've got a fix for this, will be in the next Dota update - it impacts AMD on Vulkan.
