### ISSUE TITLE
Unable to connect to any region after most recent update

### ISSUE THREAD

**Issue by tesmond** [ValveSoftware/Dota-2#1857]
#### Your system information
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 2600 Six-Core Processor            

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce RTX 2070
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  27.21.14.5638
    DirectX Driver Version:  27.21.14.5638
    Driver Date: 9 14 2020
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: NVIDIA GeForce RTX 2070
    VendorID:  0x10de
    DeviceID:  0x1f02
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 3840 x 2160
    Primary Bus: PCI Express 16x
    Primary VRAM: 8191 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Speakers (16- K3)

Memory:
    RAM:  24507 Mb

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After selecting Play Match and choosing region selector all regions are stuck on "Calculating ping"

The internet connection appears to be working as expected I am for example able to manually ping vie.valve.net and receive a response.

https://gameserverping.com/dota2 reports that I can ping all servers without issue.

#### Steps for reproducing this issue:

1. Open Dota
2. Select Play Match
3. Select Choose region

If I select auto select region and then play game the Play button does not change to the Finding match and it is stuck with a slightly lighter green and can no longer be selected.

![image](https://user-images.githubusercontent.com/2111102/102683459-0602a280-41c9-11eb-89a3-fa2e2b4d95f4.png)

**Comment by kisak-valve** [comment]
Hello @tesmond, this issue tracker is limited to the Linux and Mac Dota 2 client. You'll want to post this at https://dev.dota2.com or [Steam Support](https://help.steampowered.com) for the larger Dota 2 team.
