### ISSUE TITLE
[macOS] dota quits on bot games

### ISSUE THREAD

**Issue by birkin** [ValveSoftware/Dota-2#1858]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a gist: [My gist](https://gist.github.com/birkin/d8f34a2c7b9cdc7157a7ee755cc0e931). Also, the Dota "Properties" menu shows: "Current content BuildID: 5993849"
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a Github Gist.

- I cannot reliably reproduce this, but nearly all of the time, playing a solo bot game quits. Sometimes 2 minutes in, sometimes 20 minutes in, or anywhere in-between. I have been able to complete 2 full games out of about a dozen attempts.
- Dota **_was_** working fine playing solo bot games with `Big Sur 11.0.1` on `Dota-Diretide`.
- This week I updated both to` Big Sur 11.1` and `Dota-Mistwoods`. All other apps are working as expected on `Big Sur 11.1`.

#### Steps for reproducing this issue:

I cannot reliably reproduce the error with specific steps.

---

**Comment by birkin** [comment]
Update: problem continues.

- "Properties" no longer shows a BuildID, the most recent info: "Installed content release date: Dec 26, 2020 at 8:48 PM".
- Confirmed on additional MacBook Pro, with `Model Identifier` of `MacBookPro11,5`, also running Big Sur `11.1`.
- Over the past week, 2 completed bot games and 10 quits. Most quits were in the first 5 minutes, others were between 15 and 30 minutes.

---

**Comment by birkin** [comment]
Update: problem continues.
- Settings -> About shows `Version: 4,617`.
- Since 2020-12-27-Sun update, completed 2 bot games and had 7 quits.

---

**Comment by birkin** [comment]
Update: problem continues. Today:
- Setting -> About shows `Version: 4,650`; Properties shows: Jan 22, 2021 at 3:33pm
-  3 quits; 2 successful games.

**Comment by birkin** [comment]
Update: problem continues. This past weekend...

- `Version: 4,669` `(Jan 29, 2021 at 4:18pm)`
    - Macbook Pro model `MacBookPro11,3`
        - 1 quit
        - 3 successful games
    - Macbook Pro model `MacBookPro11,5`
        - 3 quits
        - 1 successful game

---

**Comment by mikekeda** [comment]
I have same problem, after some time screen flashes with red for a half second and game just disappear without any error.

Version: 4,669

MacBook Pro (Retina, 15-inch, Mid 2015)
AMD Radeon R9 M370X 2 GB

Mac OS Big Sur
Version 11.1

**Comment by birkin** [comment]
- Working as of `Version: 4,730`; `Build ID: 6337868`; `Installed content release date: Mar 5, 2021 at 1:31 PM`. 
    - (may have begun working in an earlier version) 
- Working on both `MacBookPro11,3` and `MacBookPro11,5`.
- Closing issue.
