### ISSUE TITLE
[Linux] Game ready popup not working

### ISSUE THREAD

**Issue by vhda** [ValveSoftware/Dota-2#186]
Game ready popup available in the original game is not working.

**Comment by ArnaudAndre** [comment]
Your OS (& version) may be useful in figuring why it's not working on your computer. Also, you didn't mention if the match-found sound is properly playing ?

**Comment by gdrewb-valve** [comment]
There's also a change in the next update that might affect this.

**Comment by gdrewb-valve** [comment]
Also essentially a duplicate of #69.

**Comment by vhda** [comment]
Did not find that issue yesterday, sorry. I'll update it there.
