### ISSUE TITLE
neutral, tp, slots and sliders are dark

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1860]
I did notice the neutral, tp slots and the sliders are now very dark (GL and vulkan)
expected?

**Comment by Turmfalke2** [comment]
that was an platform independent issue that has been fixed by now. 

Are you still affected by this?

**Comment by Turmfalke2** [comment]
@kisak-valve can be closed probably.

**Comment by kisak-valve** [comment]
Closing per the last comment.
