### ISSUE TITLE
Dota2 crashes when someone on my team use "on my way" ping

### ISSUE THREAD

**Issue by zzrdwj** [ValveSoftware/Dota-2#1864]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/zzrdwj/17a40086c38e2cbcf376c127c1dde1a1
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
There is a possibility that Dota2 will crash when someone on your team are using "on my way" ping. Even when I'm an observer if someone in the match used that ping my Dota2 will crash.
#### Steps for reproducing this issue:

1. Start a match
2. Ask your teammates to use "on my way" ping
3. Your game will crash.

**Comment by kisak-valve** [comment]
Hello @zzrdwj, this issue tracker is limited to issues with the Linux and Mac client for Dota 2. You'll want to post this over at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
