### ISSUE TITLE
[m1 macOS big sur] Screen freezes at random times during game, rendering computer unresponsive.

### ISSUE THREAD

**Issue by aslak01** [ValveSoftware/Dota-2#1865]
#### Your system information

* [System information from steam (`Steam` -> `Help` -> `System Information`)gist](https://gist.github.com/aslak01/bdf1ff7b08147c1a7b044a754b053e1a).
* Have you checked for system updates?: ✓
* Are you using the latest stable video driver available for your system? ✓
* Have you verified the game files?: ✓
#### Please describe your issue in as much detail as possible:

I'm on a new M1 Mac mini, so I expect there to be some bugs, but this one is the worst I've had in close to a decade of playing Dota 2 on a Mac. 

Screen freezes at random times during game, rendering computer unresponsive. Music (from Spotify) and game sounds continue, but screen is frozen and I am unable to alt-tab or use any system functions. Only fix I've found is to force shut down the computer and restart. Mainly happened during gameplay, but last time it occurred was right as post game stats loaded. 

I'm using the Vulcan API. Haven't tried to use OpenGL, but from watching some games when just testing stuff, OpenGL is quite laggy in team fights.

**Comment by aslak01** [comment]
Same bug just happened with OpenGL graphic option.

**Comment by Zvon** [comment]
Yes! this exactly this!

**Comment by aslak01** [comment]
Just confirmed it still happens on macOS 11.2.

**Comment by Zvon** [comment]
I'll add that I'm on a MacBook Pro M1 - 16GB RAM model.  macOS 11.2.

Monitor is an LG 38" USB-C.  Problem happens regardless of how the monitor is plugged in and into which port.  I do have a cal digit TS3 as well, but problem happens with it plugged in or not.  
Using Vulcan API as well.

I have not tested without external monitor at this point.


Mouse moves and all system audio works, interestingly I believe mouse clicks still work on the frame your on - or even possibly mic coms work as I've been able to tell team "im crashing please pause".  

Happens randomly even at the launch screen at times.

**Comment by aslak01** [comment]
Yeah, it seems pretty random, but I just had a game as PL vs Zoo (Beast and Lycan) and it happened 5-6 times, instead of the regular 1-2 times, so that leads me to believe it's not completely random.

**Comment by aslak01** [comment]
If anyone is reading this thread, I've discovered that lowering graphics settings to minimum reduces the frequency of crashing. I've played 3 games after setting quality to lowest (with the coarse grained automatic slider setting), and only had one crash in those 3 games. Down from at least once, usually twice, per game, with a max of 5-6 in the PL game mentioned above.

**Comment by aslak01** [comment]
Just confirmed it still happens on 11.2.1.

**Comment by aslak01** [comment]
Bug still happening on MacOS 11.2.2, although it seems to more often freeze my 2nd display now than make the game unplayable, leaving the main monitor alone. Computer is unstable when quitting the game and 2nd display doesn't reactivate, so still need to reboot.

**Comment by Zvon** [comment]
aslak, do you perhaps have bluetooth devices? 

I'm running 11.2 right now

My list includes:

Logitech MX Master 3
Apple Keyboard
Edifier Speakers

Strangely the freezing was more prevalent while I was having some bluetooth issues with my mouse freezing, which forced me to use a wired mouse for a while. 

The only bluetooth I use now is the Keyboard and mouse, speakers are plugged in via audio cable.

Freezing has been far less frequent - but it didn't happen last night once during a game.  Still very random.

**Comment by aslak01** [comment]
@Zvon Yeah, I'm using a new Apple BT keyboard and an offbrand BT mouse. Freezing frequency dropping seems to potentially have coincided with upgrading from a 2013 Apple BT keyboard. Never used bluetooth speakers tho, always cabled headphones. While main screen locking is less frequent now, my 2nd display (MacBook Pro integrated) basically freezes every time I play atm.

**Comment by podrezo** [comment]
I get about 45 fps with graphics turned a bit down, making the game still playable and somewhat looking still OK but I'm getting this issue happening sometimes 2-3 times per game. Same as you described - freezes the machine entirely and can't fix it without restarting the entire computer.  MacBook Pro (13-inch, M1, 2020) running big sur 11.2.2 (20D80). Have not found a way to fix this so far, hoping a fix is released soon!

**Comment by aslak01** [comment]
@podrezo I recommend turning graphics down some more, it reduced frequency of screen locks quite a bit for me.

**Comment by podrezo** [comment]
Thanks @aslak01, I will try that. I also found that disconnecting my external display and only using the Mac's built in display also helped stability somewhat though it's still rather slow at rendering even if it doesn't freeze.

**Comment by Zvon** [comment]
I have played about 6 games where I had the laptop connected to external display, but the laptop lid closed and no crash so far.   Just a small update - if I have the laptop screen opened it seems to happen more frequently.  Can you guys try testing that setup?

**Comment by troughton** [comment]
This is also occurring on a Vega 64 iMac Pro on Big Sur 11.2.3 (Vulkan/Metal API) – game freezes up intermittently, scaled framebuffer appears frozen over the top-left part of the screen (since I have the render scale at 70%), then it either resumes after a few seconds, disconnects, or occasionally causes a system crash to the window server/login window.

**Comment by aslak01** [comment]
@troughton That sounds like a different issue. The M1 issue does allow you to use the computer without cutting power and restarting. 

@Zvon I've tried a few games closing the laptop lid now, and I've also had no crash so far. Seems like there's something to that. 

In a related note, I've also had the freeze happen when playing some https://github.com/ihhub/fheroes2/ so it's unlikely that this is up to Valve alone to fix.

Edit: didn't mean to close issue… I was trying to check the preview.

**Comment by steakscience** [comment]
As long as it's an issue with M1 emulation, I doubt there's anything Valve can do.

**Comment by Zvon** [comment]
I can confirm that since laptop lid has been closed no crashes what so ever.  Played at least 30 games to test this

**Comment by steakscience** [comment]
I think laptop lid closing/not closing is besides the point since it seems to be more of a performance issue. Closing the lid would help with performance since you are using 1 screen instead of 2.

OP has a Mac mini and is still getting this issue. So the only reliable "fix" is to reduce the settings low enough to never reach a point where emulation struggles and chokes up?

**Comment by aslak01** [comment]
Hey,

On the mini it did seem to happen both with one and two displays connected, but I'm not 100% sure about that. I've been using a MacBook Pro more recently and it has not happened since I started closing the lid on the laptop. Although Dota 2 does cause the fans to ramp up on my MacBook, I'm not convinced it's to do with emulation struggling and choking the system, as it also happened in the main menu for both me and @Zvon. I also had the same system freeze happen once playing open source Heroes of Might and Magic 2 (with both displays on at the time). I suspect it's due to the somewhat dodgy display support of the M1 chipset, which causes them to still support fewer displays than initially advertised, but that's just a guess.

**Comment by tommyqian128** [comment]
I have been playing Dota2 on my M1 Macbook Air. Every Time I am using Vulcan API, the game would froze from time to time. When I use OpenGL, no problem ever happened.

**Comment by tiso7** [comment]
I can confirm that using OpenGL doesn't crash the game anymore on my Mac Mini with M1 chip. Vulkan API makes the game smoother but freezes from time to time. OpenGL makes the game lags sometimes but no freeze. However, both still have problems with Arcade games. I still need to restart Dota every time I start an Arcade game.

**Comment by steakscience** [comment]
@tiso7 Arcade games are a separate problem. Even on Intel Macs, Arcade games will usually crash on start.

**Comment by AStaroverov** [comment]
Same problem. But I don't think that problem inside dota. In my case, civ6 also freezing. Civ6 works under metal also.

**Comment by AStaroverov** [comment]
In different places ppl talk that VSync fix this issue

**Comment by legcan** [comment]
Are you guy still having issues? I'm on a M1 Air  11.4. I got this MBA about 2-3 weeks ago and I've been playing Dota2 basically everyday since I got it. I've never had the game freeze or crash.  I've played on the laptops' main display as well as on a 23inch 1080p external monitor (laptop lid closed)

However, the Steam application does freeze and become unresponsive, requiring a force quit from time to come

**Comment by steakscience** [comment]
> Are you guy still having issues? I'm on a M1 Air 11.4. I got this MBA about 2-3 weeks ago and I've been playing Dota2 basically everyday since I got it. I've never had the game freeze or crash. I've played on the laptops' main display as well as on a 23inch 1080p external monitor (laptop lid closed)
> 
> However, the Steam application does freeze and become unresponsive, requiring a force quit from time to come

IIRC by default Dota uses OpenGL, which doesn't have issues on M1.

When using Vulkan, you will get issues.

**Comment by Zvon** [comment]
I have had no issues running dota on 11.3 with laptop lid open and external display.  Earlier versions of macOS were clearly the issue.

**Comment by aslak01** [comment]
Yeah it does appear to have been resolved. I have had a couple of screen freezes in another game prior to updating to 11.4, but I was able to reactivate the computer by closing and reopening the laptop.

**Comment by lanchuanqi** [comment]
Happens on my Mac Pro as well. with graphics Radeon Pro Vega 56 8 GB, on Big Sur 11.4

**Comment by FlorianWendelborn** [comment]
Happens on my system as well, but only with Vulkan enabled. With OpenGL, it just slows down for 1-2 seconds and then recovers.

I don’t have an M1 though. Just an Intel i7-6700K + Vega 64.

**Comment by kisak-valve** [comment]
Hello @lanchuanqi, @FlorianWendelborn, can one of you please open a new issue report so that we can properly track your Mac + AMD Vega random hang?

Closing because it looks like the issue in the opening post has been resolved.

**Comment by cesarfarias** [comment]
Same here with a M1 Pro I remember at my old imac27 used to be very smooth... I had 32gb of ram tho only difference i see is RAM.

m1 Pro is a brand new laptop FPS is like 100+ however it keeps on lagging randomly, it isn't the system or due low hardware, is just something related to the software i can feel it lol

**Comment by Beatloc** [comment]
Have this exact same issue on Intel MacBook Pro Monterey 12.2. Game freezes even in Home screen. I don't know why this was closed since the issue was not solved but rather a workaround was discussed (to close the lid and use external display)

**Comment by phyze** [comment]
Same here with Intel Macbook pro 2020 Monterey that make my screen freeze.
