### ISSUE TITLE
Downloaded Replay - No match Details

### ISSUE THREAD

**Issue by churchymayer** [ValveSoftware/Dota-2#1866]
When I go to the downloaded replays tab, every replay has No Match Details. I can watch them just fine, but I just can't see any details. Heroes, etc
I want to add that I have copied over some old replays (Source 2) that I backed up. Newly downloaded replays make no difference for the missing match details. All of them are affected. I have tried to verify game files with no effect.
I have no second PC to test if this is a hardware or account bound issue. 

OS: Windows 10

**Comment by kisak-valve** [comment]
Hello @churchymayer, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
