### ISSUE TITLE
[Mac] New update broke hosting custom games.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#187]
Since the new update 2/07 I can't host custom game lobbies. Whenever I host any map and the game starts it just says Waiting For Host... and then it sits like that for about 2 minutes and the game doesn't start, after which the game just disappears.

Update: Ok so for some reason, whichever map I host it's just displayed as Map:Error isntead of the actual game I'm hosting, probably related.

**Comment by gdrewb-valve** [comment]
Are you seeing 'host loading'?  There was some automatic host selection stuff that may mean you aren't actually hosting.

**Comment by Vuccappella** [comment]
Yes. I see the problem. When I click Create Custom Lobby on a Custom Game mode it auto selects a Error map isntead of the actual map, manually selecting the map should fix it.

**Comment by gdrewb-valve** [comment]
These aren't Mac/Linux issues so I've passed them on to the larger team and they won't be tracked here.
