### ISSUE TITLE
Heroes partially fail to render in the postgame screen.

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1870]
I think this bug is also new.
![dota_hero_render](https://user-images.githubusercontent.com/5174562/105231624-76556880-5b67-11eb-9e1a-688d1deea84a.png)

It is reproduceable in that I can restart my client and it still looks broken. This bug occurs for all my recent games. The exact point at which the hero gets cut of appears to be random, but persistent with the match/hero composition. 

This is with the vulcan renderer.
I am still on nvidia 455 due to some cuda compatibility issues.

E: 
The console only shows some missing resources for spell icons.

**Comment by danginsburg** [comment]
Ugh, this is a regression I introduced when I fixed https://github.com/ValveSoftware/Dota-2-Vulkan/issues/363.  Fix will be in the next update, thanks for the report.

**Comment by danginsburg** [comment]
Fix for this has shipped in the most recent Dota update.

**Comment by Turmfalke2** [comment]
Can confirm it is fixed.
