### ISSUE TITLE
Game crashes when clicking on profile in the game, mine or even friends

### ISSUE THREAD

**Issue by davidxvier** [ValveSoftware/Dota-2#1872]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Hi, after the recent update to the new main page. I can't seem to view my profile or even friends. The game crashes/closes immediately. Rest of the pages (heroes, watch, store etc. all have no issues) I have reinstalled steam, reinstalled dota 2 and even verified files etc but nothing seems to be working to fix this issue.

A second question I have is regarding Vulkan. I have always seen the Vulkan dlc in the setting page but seems to have disappeared, and yet when I open dota to look at the settings it says i'm running on vulkan. Could you help explain why that may be?

My launch options are only these 3:
-novid
-high
-vulkan

I'm very new to this forum, so thanks for understanding. I am using MacOSX just so you know. If you have more questions please do feel free to ask.

Thanks.

Best Regards,
David

#### Steps for reproducing this issue:

1. Open Dota
2. Click on player profile (mine or friends)
3. Game crashes

**Comment by filipejunqueira** [comment]
I'm having a similar problem. It happens when clicking on profile of friends. Game freezes for me and I need to kill the process. 
I also noticed similar crashes/freezes whilst opening the video settings or opening the right bottom menu to find matches.

**Comment by filipejunqueira** [comment]
To the devs: This might be related or be the same as this bug related here https://github.com/ValveSoftware/Dota-2/issues/1837

**Comment by alandwiprasetyo** [comment]
same here

**Comment by iL00p** [comment]
I had this issue. Changing render option to OpenGL from Vulkan fixed it for me. I can see many other Vulkan related issues reported as well.

**Comment by shawncarps** [comment]
Guys what's up! looks like I'm joining the club too! haha! I'm having the same probs! apparently my Mac is an old version MacBook Air 2015 but I updated everything macOS Catalina, I literally tried everything, to be honest, should we inform steam about this issue? I really can't view my profile in Dota 2 it literally crashes every time it happens especially when I'm viewing the hero stats wins and lose, hope someone has an answer to this issue would really mean a lot! cheers!

**Comment by danginsburg** [comment]
I've checked in a fix for this. In addition, if you want a temporary workaround until the next Dota update ships you can overwrite the attached libMoltenVK.dylib into ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/bin/osx64/libMoltenVK.dylib.
[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/5900452/libMoltenVK.dylib.zip)

**Comment by danginsburg** [comment]
By the way, what made this a little difficult to hunt down is that it only happens on Macs with GPUs prior to macOS_GPUFamily2_v1 that don't support MSAA layered rendering.

**Comment by kisak-valve** [comment]
Hello @danginsburg, unfortunately, your uploaded file did not lock into place before you sent your comment.

**Comment by danginsburg** [comment]
The update with the fix for this has shipped.
