### ISSUE TITLE
[Mac] Friends UI issue

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#188]
![screenshot 2015-07-01 19 35 03](https://cloud.githubusercontent.com/assets/5674597/8468974/7ff658a2-2028-11e5-93aa-46611d5b38c0.png)
notice the text overlap

**Comment by gdrewb-valve** [comment]
Likely not a Mac/Linux issue.

**Comment by Vuccappella** [comment]
got the same thing going on my Mac as well.

**Comment by gdrewb-valve** [comment]
Confirmed that this happens on Windows also, I've passed this on to the larger team.
