### ISSUE TITLE
Shadow/God rays flicker

### ISSUE THREAD

**Issue by KirmesBude** [ValveSoftware/Dota-2#1880]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/KirmesBude/d0b3a4d0b81a213a3dcb1af24f1b20b7
* Have you checked for system updates?: Yes - up to date
* Are you using the latest stable video driver available for your system? Yes - up to date
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Visual showcase: https://www.youtube.com/watch?v=Sav1q0tki1k
Shadows should not flicker. But they do regardless of shadow quality. 
Also happens when actually in-game. Especially noticeable on god rays on Reef's Edge and The Emerald Abyss.

#### Steps for reproducing this issue:

1. Start Dota2 with either -vulkan or -gl
2. Turn on shadows with either low, medium or high quality settings
3. See shadows and god rays flicker

### Steps taken to fix the problem: 

1. Start Dota2 with -gl; same issue
2. Using Steam Linux Runtime; same issue

**Comment by Turmfalke2** [comment]
I have same issue, but with an nvidia card.  
https://gist.github.com/Turmfalke2/6fac0a34b18fb4a4fb0cfcccc0825585

I didn't notice it in game, but I just use the desert terrain without weather effects.
