### ISSUE TITLE
Game crashes on viewing anybody's profile on macOS (Vulkan)

### ISSUE THREAD

**Issue by ishanjalan** [ValveSoftware/Dota-2#1882]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/strobel1ght/6e3c8854fcdc72d4dcffcc6de32ff2ed

![image](https://user-images.githubusercontent.com/44338423/106361267-030bdd80-6343-11eb-8dd7-a607d68a02c5.png)

* Have you checked for system updates?:
Yes
* Are you using the latest stable video driver available for your system?
Yes
* Have you verified the game files?:
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Whenever I try to view someone's profile (haven't found any exceptions), the game immediately crashes. Some other pages cause this crash too, but I can't remember which ones. This started since we had the full screen hero preview for the Last Match. Post 7.28 patch. I use Vulkan graphics and it ran amazingly well before the update.

#### Steps for reproducing this issue:

1. Go to someone's profile from any source
2. ??
3. Crash

**Comment by kisak-valve** [comment]
Hello @strobel1ght, this issue is already being tracked at #1872. Closing as a duplicate.

**Comment by danginsburg** [comment]
Keeping this open for now.  I've been having trouble repro'ing #1872 and there has been  lack of system information on that bug so I asked reddit users who are reporting this to start posting system information.  If others who are seeing this could share system information that would be great.  I also would like to figure out if it's specific user profiles or all user profiles.

**Comment by danginsburg** [comment]
OK, this seems to be an Intel-only bug perhaps.  I've got it to repro now on Intel HD 4000.  I'll have a look at this first thing on Monday.

**Comment by danginsburg** [comment]
I've got this reproduced now, will investigate.

**Comment by danginsburg** [comment]
OK, I've narrowed this down to a bug in MoltenVK which has been fixed in https://github.com/KhronosGroup/MoltenVK/commit/223545883867bf4380346c9ce48c8a3fbfa31a08#diff-3f57aee751e226f4060d24a9c2aac44bbb53307d6009476acbbe174f63a69708

**Comment by danginsburg** [comment]
I've checked in a fix for this.  In addition, if you want a temporary workaround until the next Dota update ships you can overwrite the attached libMoltenVK.dylib into ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/bin/osx64/libMoltenVK.dylib.

[Uploading libMoltenVK.dylib.zip…]()

**Comment by danginsburg** [comment]
Closing now in favor of #1872.

**Comment by ishanjalan** [comment]
Thanks Dan!
