### ISSUE TITLE
[Linux(?)] Weird Circle-like Around Medusa

### ISSUE THREAD

**Issue by computerquip** [ValveSoftware/Dota-2#189]
Not sure what triggered this... but Medusa suddenly started having a weird oblong line drawn around her: ![Oblong Thingy](http://images.akamai.steamusercontent.com/ugc/440574088297532279/F66B3DDA2FDFD62741C9050FDB421C2FF7D2C9C2/)

This persisted throughout the rest of the match. I'm not sure what triggered it but I think I hovered my mouse over Medusa when it first happened. Take with a grain of salt. Can't seem to immediately reproduce.

**Comment by danginsburg** [comment]
I have never been able to repro this issue.  Have you been able to determine a reliable repro?

**Comment by gdrewb-valve** [comment]
Closing pending repro info.
