### ISSUE TITLE
Crash when attempting to ban a hero.

### ISSUE THREAD

**Issue by SirFireball3521** [ValveSoftware/Dota-2#1899]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a N/A, multiple people.: 
* Have you checked for system updates?: Y
* Are you using the latest stable video driver available for your system? N/A
* Have you verified the game files?: Y

#### Please describe your issue in as much detail as possible:

This is happening in multiple lobbies across a tournament. Whenever someone attempts to ban a hero, their game crashes. 

#### Steps for reproducing this issue:

1. Open private game in captain's mode
2. Ban a hero.

**Comment by kisak-valve** [comment]
Hello @SirFireball3521, without any system details to ponder, this issue is a duplicate of #1896. Closing in favor of the older issue report.
