### ISSUE TITLE
[OpenGL] Green Screen

### ISSUE THREAD

**Issue by computerquip** [ValveSoftware/Dota-2#19]
The first frame or so when starting the game up using the OpenGL renderer shows a very quick but out-of-place green screen. It does this on Windows as well.

**Comment by kon14** [comment]
That's also the case for me, it's trivial though it would be nice to have this one noted.

**Comment by danginsburg** [comment]
Please provide your system information so I can repro the issue.

**Comment by danginsburg** [comment]
Actually, I found the problem and have fixed it.  Fix will be available in the next release.

**Comment by computerquip** [comment]
danginsburg, thank you. Apologies for not posting information.

**Comment by gdrewb-valve** [comment]
This should be resolved in the 6/25 update.

**Comment by computerquip** [comment]
Thanks. It is indeed resolved.
