### ISSUE TITLE
[Mac] "disconnect in xxs" red alert doidn't disappear after I was out of the lobby

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#190]
![screenshot 2015-07-01 20 33 34](https://cloud.githubusercontent.com/assets/5674597/8470545/e6c2a478-2041-11e5-9cbf-51106b3d3e62.png) 
This is a screenshot of what I saw when I got kicked out of a lobby, probably because host disconnected. I knew I was out of the lobby because the bottom right button says Play Game, instead of Reconnect

**Comment by gdrewb-valve** [comment]
This occurs on all platforms so I've passed it on to the larger team and it won't be tracked here.
