### ISSUE TITLE
Bot name typo in scenario

### ISSUE THREAD

**Issue by mastercoms** [ValveSoftware/Dota-2#1905]
Storm Spirit's name in the Status Effects tutorial has a shift typo, where he is named Storm SPirit instead of Storm Spirit.

**Comment by kisak-valve** [comment]
Hello @mastercoms, this reads like a general, cross-platform issue with Dota 2. You'll want to post this on https://dev.dota2.com/ or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
