### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by aws5295** [ValveSoftware/Dota-2#1909]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/aws5295/b40aff0f416e7fb3b3fcf41084a3d435
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I was sure that I was running into #1906 but I continue to see crashes on startup even though that issue has been fixed via patch. When I launch my game, I get to the home screen very briefly and then the game crashes after about 1 second.

Dumps:
[dumps.tar.gz](https://github.com/ValveSoftware/Dota-2/files/6217246/dumps.tar.gz)
[tail of dump](https://gist.github.com/aws5295/efcea9e2699c1eb631a614fe534ced35)

#### Steps for reproducing this issue:

1. Launch dota from steam (using `-vulkan` or `-safe` launch option)
2. Splash screen appears
3. Home screen loads
4. Crash

-- or --

1. Launch dota from cmd line: `~/.steam/debian-installation/ubuntu12_32/steam-runtime/run.sh /media/seagate/SteamLibrary/steamapps/common/dota\ 2\ beta/game/dota.sh`
2. Splash screen appears
3. Home screen loads
4. Crash

```
...
...
Fossilize WARN: Referenced Pipeline layout 332ece41f12c8251, but it does not exist.
This can be expected when replaying an archive from Steam.
If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
Fontconfig warning: "/media/seagate/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/media/seagate/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
 failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory
crash_20210328074323_1.dmp[69055]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210328074323_1.dmp
/media/seagate/SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh: line 109: 68961 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
➜  ~ crash_20210328074323_1.dmp[69055]: Finished uploading minidump (out-of-process): success = yes
crash_20210328074323_1.dmp[69055]: response: CrashID=bp-7c43fed6-c5ac-47bf-8c36-4f0be2210328
crash_20210328074323_1.dmp[69055]: file ''/tmp/dumps/crash_20210328074323_1.dmp'', upload yes: ''CrashID=bp-7c43fed6-c5ac-47bf-8c36-4f0be2210328''
```

I also uninstalled and reinstalled locally out of paranoia.

**Comment by kisak-valve** [comment]
For reference, the first two minidumps are SIGSEGV in libtcmalloc_minimal.so.0 coming from libvulkan_radeon.so. The third minidump is a SIGSEGV in libtcmalloc_minimal.so.0 coming from libpango-1.0.so.

It's a weak hint, but `libvulkan_radeon.so` is mesa/radv, so it might be interesting to ppa-purge the oibaf PPA and test if the game has the same behavior without a bleeding edge build of mesa.

**Comment by aws5295** [comment]
This was exactly the issue!
Thanks as always for your rapid and continual support to this community.

**Comment by kisak-valve** [comment]
It would be a good idea to report the driver regression to upstream mesa if it hasn't been already.
