### ISSUE TITLE
Glitched ground with "High Water Quality" enabled

### ISSUE THREAD

**Issue by bemug** [ValveSoftware/Dota-2#1917]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [Here](https://gist.github.com/bemug/8ca0cb8e59af51721f507bdd1230276f)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When "High Quality River" is set, and only with Vulkan render (not opengl), there are some weird lines visible in the dirt. This is very noticeable in the bottom lane right next to the radiant jungle, or in the top of the demo mode.
Here with High Quality River (glitch):
https://steamcommunity.com/sharedfiles/filedetails/?id=2453109147
Here Without (no glitch):
https://steamcommunity.com/sharedfiles/filedetails/?id=2453109316

I run latest mesa on AMD RX580, latest Arch Linux.

#### Steps for reproducing this issue:

1. Switch to vulkan renderer
2. Enable high quality water
3. Go to demo hero
4. Look at the dirt as in my screenshot above

**Comment by jazztickets** [comment]
Same thing on a 5700XT, AMDGPU drivers

System Info: https://gist.githubusercontent.com/jazztickets/f07f40cf0896a257b911325fc21f5e1a/raw/947c5576887a8dec26895dbf067c48acd9afd9c0/main%2520system%2520info

https://user-images.githubusercontent.com/425930/115303600-0e3fff80-a121-11eb-97ef-993150943e86.mp4

**Comment by hakzsam** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/commit/1d3542694bd26d6a912e558af6421aef8e62758f should fix it.

**Comment by bemug** [comment]
Fixed with mesa-21.1.0-1.
Thanks a ton.
