### ISSUE TITLE
[Mac][Suggestion] Auto-start toggle

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#192]
Can we have an option to toggle auto-start? And, if possible, have that option disabled by default. 

The current behavior causes lots of problems. For instance,
say I have 3 friends and I want to play a 4-player map. I have them in my party and I clicked "create lobby". Then a lobby showing only me will appear and in one second, I would see the accept/reject popup. I have no way to see if I am actually with my 3 friends. Although I know that should be the case, it looks like that only I got into the lobby.

**Comment by gdrewb-valve** [comment]
Just clariying, did you see the issue with a regular game lobby or a custom game lobby (or both)?

**Comment by ssnl** [comment]
Custom lobby. I haven't tried regular game lobby though.

**Comment by gdrewb-valve** [comment]
Thanks.  As this isn't a Mac/Linux issue I've passed it on to the larger team.
