### ISSUE TITLE
Arch Linux - Dota launch on the secondary monitor

### ISSUE THREAD

**Issue by ctxquentin** [ValveSoftware/Dota-2#1921]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/ctxquentin/d1564169e85225316c3201d38991d336
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
The game launch on the secondary monitor, even thought my monitors are correctly setup. It happens with Dota 2 ONLY. Any other games ( even steam game like cs:go ) open in my primary monitor. The current workaround i am using right now is to open the game and move it to my primary monitor, but it´s a bit annoying since every time i ALT+TAB to another window the game move back to my secondary screen.

#### Steps for reproducing this issue:
Honestly i don´t know why it happens so i don´t know how to reproduce. But here is some details about my environment : 

I am using Arch Linux with Gnome, x11. Both monitor are connected to my GPU, a Nvidia GTX 1660 Ti. The primary one with HDMI and the secondary with Display Port. Whenever the secondary screen is off or in portrait mod, the game launch/switch on the primary screen.

**Comment by kisak-valve** [comment]
Hello @ctxquentin, this issue is already being tracked at #962. Adding `-phased_window_create` to the game's launch options may workaround the issue.

Closing as a duplicate.
