### ISSUE TITLE
Spotlight in item preview flickers

### ISSUE THREAD

**Issue by Lambdara** [ValveSoftware/Dota-2#1923]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  [Click here](https://gist.github.com/Uwila/89f0069eb678e58f2e9e9db2946afd4f)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Expected: When looking at a hero as selected from the 'heroes' page in the client, and hovering over an available item or set, it should show a preview of that set with a steadily shining spotlight on the hero.

What happens: The spotlight doesn't steadily shine, but instead flickers, as shown here:

https://user-images.githubusercontent.com/9699777/115152880-5dc7f200-a073-11eb-8121-cec0cca3ad11.mp4

#### Steps for reproducing this issue:

1. Go to the heroes page in the client.
2. Select any hero with multiple items or sets available for purchase.
3. In the bar at the bottom with the title 'AVAILABLE', hover over some item or set which is not currently equipped on that hero.

**Comment by Turmfalke2** [comment]
likely related/duplicated #1880

**Comment by VelorumS** [comment]
@Uwila is it still flickering for you? Because for me it doesn't flicker any more in item preview, but now it flickers in the main screen (the new one with the hero from the last game).

**Comment by Lambdara** [comment]
Everything works fine for me right now.
