### ISSUE TITLE
Arabian nickname breaks the Dota 2

### ISSUE THREAD

**Issue by inzanty** [ValveSoftware/Dota-2#1926]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/inzanty/f865bdf715a6467a54265415651769f3
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes/No
* Dota 2 Patch Version: 7.29b *

#### Steps for reproducing this issue:

If my language don't arabian and i have arabian nick it's breaks the Dota 2.
There are lot of examples of this bug which i saw:
![Screenshot_32](https://user-images.githubusercontent.com/53940590/115514860-3a788f00-a28d-11eb-846a-fde5bd13e61a.png)
![Screenshot_33](https://user-images.githubusercontent.com/53940590/115514959-50864f80-a28d-11eb-8e84-0027421ad2cb.png)

Also this bug reverse text in chat:
![Screenshot_34](https://user-images.githubusercontent.com/53940590/115516739-16b64880-a28f-11eb-8ce2-3ec97f44603b.png)

Bug confirmed on Windows and Linux.

**Comment by kisak-valve** [comment]
Hello @inzanty, this issue tracker is limited to issues with the Mac and Linux port of Dota 2. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the feedback to reach the larger Dota 2 team.
