### ISSUE TITLE
Dota 2 isn't working on my Mac Book since the newest update.

### ISSUE THREAD

**Issue by Iliketoplaygames2** [ValveSoftware/Dota-2#1927]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

I've been playing on a Mac Book pro for a few years now, little to no problems. Ever since the recent major patch update (7.29), I haven't been able to get into Dota.

Steam works fine. However, when I try to open/play Dota 2, I get an error message that says "A game file appears to be missing or corrupted. In the Steam client go to game's properties. In 'Local Files' tab select 'Verify Integrity of Game Cache' to have Steam double-check the game's installation." Followed by a long error code message (both included below). 

I've redownloaded both Dota 2 and Steam, but neither seemed to fix the problem. I have verified the game files and it says they're verified with no problem. I tried restarting my computer. No fix.

Any advice would be greatly appreciated.

<img width="352" alt="Screen Shot 2021-04-22 at 6 12 16 PM" src="https://user-images.githubusercontent.com/83041604/115791415-5ae04080-a396-11eb-8618-946a725604f9.png">

<img width="466" alt="Screen Shot 2021-04-13 at 9 15 23 AM" src="https://user-images.githubusercontent.com/83041604/115790469-c1645f00-a394-11eb-87f2-5979d783ad67.png">
<img width="545" alt="Screen Shot 2021-04-13 at 9 19 05 AM" src="https://user-images.githubusercontent.com/83041604/115790472-c2958c00-a394-11eb-91e8-b42e8d6e9872.png">

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Iliketoplaygames2, this issue is already being tracked at #1918. Closing as a duplicate.
