### ISSUE TITLE
Dota 2 will not start on windows 10

### ISSUE THREAD

**Issue by mark-ad** [ValveSoftware/Dota-2#1930]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
  https://gist.github.com/mark-ad/9dad45a4c08f493cf8805e666dc814b6
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Please describe your issue in as much detail as possible:

When I click play Dota 2, i get a steam dialogue box that says "updating configuration" which disappears after about 2 seconds, during this time steam says Dota 2 is running, after about 10 seconds the game goes from running to not running. During this time windows creates no new proccesses and it appears that nothing is happening at all.'

things i have tried:
- reinstall dota 2 ( 3 times)
- verify game files (multiple times each install)
- restarting computer (after each install)
- install on different hard drive
- install from different download region
- launch game with -autoconfig
- launch game with -safe 
- launch game with -gl
- launch game with steam in administrator mode
- clear download cache

#### Steps for reproducing this issue:

1.  click dota 2 play button
2. Steam creates a dialogue box that says "updating configuration"
3. dialogue box closes, dota 2 is not running, nor was it ever running.

**Comment by kisak-valve** [comment]
Hello @mark-ad, this issue tracker is limited to issues with the Mac and Linux port of Dota 2. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the larger Dota 2 team.
