### ISSUE TITLE
Dota2 always crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by andy12241025** [ValveSoftware/Dota-2#1938]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
    https://gist.github.com/liberiulx/0050fa4c9af93b9d10771ccf8272f7f3
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Dota2 on ubuntu 20.04 always crashes randomly when playing around 10 ~ 20 mins. It just exits without any error msgs reported. A .dmp file under /tmp/dumps/ was generated along with each crash. The crash dmp files are attached here.

[crash_dmp_files.zip](https://github.com/ValveSoftware/Dota-2/files/6565836/crash_dmp_files.zip)

#### Steps for reproducing this issue:

Start the game and it would always crash after playing for a while.

**Comment by kisak-valve** [comment]
For reference, all attached minidumps are a SIGSEGV in libscenesystem.so, except for the fourth, which is a SIGSEGV in librendersystemvulkan.so.

**Comment by andy12241025** [comment]
Thanks. Any advice to turn this around? Just let me know if any more info is needed for further troubleshooting.

**Comment by andy12241025** [comment]
Any update?
