### ISSUE TITLE
showcase view: clicking a new hero in the top list does not update the HUD

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#194]
This is not specific to the reborn client and probably not OS-specific, but I'm not sure where to report it. 
In showcase view, selecting another hero by clicking its portray in the list on top does move the camera to this hero, but the HUD is not updated and still corresponds to the previous hero. If it's intended behavior, it doesn't make much sense to me...

**Comment by gdrewb-valve** [comment]
That doesn't sound correct to me either, I've passed this on to the larger team.
