### ISSUE TITLE
chatting makes dota2 stutter

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1941]
It seems that when I chat somewhat a lot with my party in the dashboard, it makes the client stutter increasily. I restart the client to make the stutter go away.
Leak? Man-in-the-middle attack :) ?

**Comment by Turmfalke2** [comment]
That has been an issue for a long time. I would assume it is related to rendering messages that aren't visible anymore. Best to just leave the post game chat when the blame game starts. 

E: Also I think this isn't Linux/MacOSX related, I have heard windows users complain about it.

**Comment by sylware** [comment]
oh, I'll try a /clear then

**Comment by sylware** [comment]
still around

**Comment by sylware** [comment]
It seems I cannot reproduce this.

**Comment by zeroedout** [comment]
If I recall it only affects older cards, AMD RX 5xx and below. Though maybe not... 

I have this issue on Linux and I recall a Windows user complaining as well. Likely not OS related.

**Comment by Turmfalke2** [comment]
Issue is getting tracked here https://github.com/ValveSoftware/Dota2-Gameplay/issues/141 for when Jeff comes back.

**Comment by sylware** [comment]
doh, did reproduce. Still around.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/Dota2-Gameplay/issues/141 since this is a cross-platform issue..
