### ISSUE TITLE
Dota 2 doesnt work when i push the button "Play"

### ISSUE THREAD

**Issue by EgiEgi1** [ValveSoftware/Dota-2#1943]
#### Your system information

* System information from steam :
https://gist.github.com/EgiEgi1/e50e79faee275d184e58fa4316600c4a
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [No]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Dota 2 doesnt work when i push the button "Play"

#### Steps for reproducing this issue:

1. Push the button "Play"

**Comment by kisak-valve** [comment]
Hello @EgiEgi1, blind guess, does adding `-gl` to the game's launch options have an effect? (#1886)

**Comment by EgiEgi1** [comment]
Oh, yeah!!!!!
Thanks!!!!!!!!!

**Comment by kisak-valve** [comment]
Thanks for checking, like #1886, your ATi HD 4850 does not support Metal and the behavior matches the older issue report. Let's treat it as the same issue.

Feel free to add your experience to #1886. Closing in favor of the older issue report.
