### ISSUE TITLE
After Update of Steam Dota 2 crashes after opening

### ISSUE THREAD

**Issue by Rajesh007x** [ValveSoftware/Dota-2#1944]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. After a steam update and restarted the steam
2. Tried opening Dota 2 in macbook pro 
3. The game continuously crashes after opening ( tried re-installing Dota 2 and steam again , also verified the games file integrity )

**Comment by livestd** [comment]
i have the same problem.

System Information
https://gist.github.com/livestd/57d63dd2505d78dbc88337756b68a07c

i've checked for updates and reinstalled dota2, but the game is still crashing on load (when dota logo is showing)

**Comment by rustykobra** [comment]
I confirm this.
https://gist.github.com/rustykobra/ce9ea3499e875c3561d9355f40d90bc5

**Comment by CaptNemo-ghub** [comment]
I am facing the same issue. None of the other games are launching as well, i tried reinstalling steam and dota but the problem continues to persist. Any idea how to install the older version of steam client ?

**Comment by rustykobra** [comment]
Ok, players found out that the problem is with Vulkan. You can either launch with "-gl" (OpenGL), or launch from Terminal (with Vulkan):
~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh

**Comment by Rajesh007x** [comment]
I had tried with -gl in my set launch options of Dota 2 , it did not work ,
but its working when opening with terminal and running dota2.sh file.

**Comment by danginsburg** [comment]
We have this reproduced here.  It appears to be related to a recent Steam Overlay change and is impacting at least macOS 10.13 and 10.14.  As mentioned above, you can workaround it temporarily for now by launching dota.sh directly from the command-line or using OpenGL.  We are working on debugging it and getting a fix out.

**Comment by danginsburg** [comment]
A fix for this is incoming in the next Steam update.

**Comment by danginsburg** [comment]
This has been fixed in the latest Steam Client Beta - June 8

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3033717534724305324

**Comment by Rajesh007x** [comment]
Thank you all , now the bug is fixed and its working fine now. Update to the latest steam version.
