### ISSUE TITLE
Dota Update 8th June causes the Dota 2 game to Crash on Mac IOS Mojave 

### ISSUE THREAD

**Issue by limgerald2** [ValveSoftware/Dota-2#1945]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes

* Have you verified the game files?: [Yes/No]
Yes 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

The recent steam / dota update on 8th June 2021 doesn't allow the dota to be opened anymore. Once i click on play dota it opens up the screen with the dota logo and closes it immediately. As a result, data can't be played. This is quite a common issue with many Mac users in the steam community forum 

#### Steps for reproducing this issue:

1. Updated system, steam, and dota. Click on Play and it doesn't open. 
2. Verified integrity of files, reset and uninstall and then re install again and still doesnt work
3.

**Comment by limgerald2** [comment]
This problem has be resolved in the latest update of steam for mac

**Comment by kisak-valve** [comment]
Hello @limgerald2, this issue was previously evaluated at #1944 and opting into the Steam client beta is the best solution until the beta variant of the Steam client gets promoted again.
