### ISSUE TITLE
[Linux] Flickering light shafts on the main menu screen with the hero or guild home screen with the guild's banner

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#1946]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/ChipmunkV/674dc69503f6908442520e7e9a8434d4): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Yellow diagonal light shafts near the hero on the main menu screen should glow without flickering.

If I untick either "Additive Light Pass" or "Antialiasing" in dota video settings then flickering stops.

Before the patch that added a hero to the main screen there was a similar problem with the flickering light shafts when looking at previews of cosmtics sets available on the market from inside the game. Now the sets previews are fine, the lightshafts above the heroes don't flicker.

#### Steps for reproducing this issue:

1. Run Dota.
2. See the yellow diagonal light shafts near the hero on the main menu screen flicker.

**Edit**: main menu was replaced by Nemestice menu, so the flickering light can be found on the guild home screen on the right where the light shines on the guild's banner.

**Comment by kisak-valve** [comment]
Possible duplicate of #1923.

**Comment by Lambdara** [comment]
I'm not experiencing this issue on my Linux installation; [gist](https://gist.github.com/Uwila/89f0069eb678e58f2e9e9db2946afd4f). Perhaps this could be helpful in figuring out for which hardware/software this is a problem.

**Comment by VelorumS** [comment]
If I untick either "Additive Light Pass" or "Antialiasing" in dota video settings then flickering stops. @Uwila you've got all enabled?

**Comment by Lambdara** [comment]
I have both 'Additive Light Pass' and "Anti-Aliasing' enabled.

**Comment by kisak-valve** [comment]
I didn't see this with the Nemestice main menu background. Please retest.

**Comment by VelorumS** [comment]
Well, technically it doesn't flicker on the main screen now just because it's a different main screen.

But the flickering is still present on the guild home screen on the right where the light shines on the guild's banner. I'll add this to the title of the issue.

**Comment by ghost** [comment]
Have the same issue, the banner in the guild profile flickers and so does the moonlight weather effects. Unticking "Antialiasing" makes it stop. I use  Nvidia GTX 1070 470.57.02 on linuxmint 20.2. Both computers with this setup have the exact same issue.

**Comment by danginsburg** [comment]
A fix for this is coming in the next release.
