### ISSUE TITLE
Dota 2 Crashes after launch on EndevourOS.

### ISSUE THREAD

**Issue by gennarocc** [ValveSoftware/Dota-2#1948]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [SYSTEM INFO](https://gist.github.com/gennarocc/df34cbc8addc3296c39c17839c7a688b)
* Have you checked for system updates?: YES
* Are you using the latest stable video driver available for your system? YES
* Have you verified the game files?: YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Dota 2 shows logo briefly then crashes. Tired launching with both `-gl` and `-vulkan`. I have playing hundreds of games this configuration on arch distros in the past. I also was able to play for about a week on this OS before I started running into issues.

#### Steps for reproducing this issue:

1. Launch Dota 2 with `-gl` or `-vulkan` flag. (or none).

**Comment by kisak-valve** [comment]
Hello @gennarocc, it looks like you're using AMDVLK. Can you test if running the game with mesa/RADV (from `vulkan-radeon`) instead has an effect?

**Comment by gennarocc** [comment]
Im not positive that I did this correctly, but I am still experiencing the same Issue.

Here is my system information after uninstalling `amdvlk` and installing `vulkan-radeon` (was already installed but reinstalled it anyways). I rebooted my system after as well : [System Info](
https://gist.github.com/gennarocc/ba356097d62a1eeca31b22be1f080c55)

**Comment by gennarocc** [comment]
Still no luck,

I have tried forcing the game to run using the mesa driver as described in [this reddit post](https://www.reddit.com/r/linux_gaming/comments/h8b7zv/amd_gpu_vulkan_driver_how_to_easily_switch/).

I also attempted to launch the game with the flowing launch options.
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json %command% -gl`

**Comment by gennarocc** [comment]
Fixed by uninstalling steam, all video drivers and reinstalling with `vulkan-radeon`.
