### ISSUE TITLE
DOTA 2 Economy - Ultra Rare untradeable item. 

### ISSUE THREAD

**Issue by Rastheraz** [ValveSoftware/Dota-2#1949]
Good day, 

I have bought Collector's Cache II 2019 and managed to get an ultra rare drop, the Jagged Honor Set. It is indicated that it should be Tradeable/Marketable after a year from the date of purchase or at the end of the international. After opening, only the Jagged Honor mask is marketable, the rest are untradeable/unmarketable. Can you help in fixing this issue. Thank you!

I have uploaded screenshots of proof of inventory. Feel free to check the history of my account and inventory.
![jagged honor 1](https://user-images.githubusercontent.com/19542382/122677397-ae470180-d214-11eb-98da-9af8b4043cfc.PNG)
![jagged honor 2](https://user-images.githubusercontent.com/19542382/122677400-b010c500-d214-11eb-943b-40dbad9bc4ec.PNG)
![jagged honor 3](https://user-images.githubusercontent.com/19542382/122677404-b0a95b80-d214-11eb-85f2-94d536522cbe.PNG)
![jagged honor 4](https://user-images.githubusercontent.com/19542382/122677406-b141f200-d214-11eb-8d35-222004d3a2c4.PNG)
![jagged honor 5](https://user-images.githubusercontent.com/19542382/122677411-b30bb580-d214-11eb-9242-29812e79a974.PNG)
![jagged honor 6](https://user-images.githubusercontent.com/19542382/122677414-b43ce280-d214-11eb-9fb1-e35cba76f569.PNG)

**Comment by kisak-valve** [comment]
Hello @Rastheraz, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. This reads like a general Dota 2 issue and you'll want to post this at https://dev.dota2.com or use [Steam support](https://help.steampowered.com/) for the feedback to go to the larger Dota 2 team.
