### ISSUE TITLE
[Linux] Mouse buttons 4 and 5 not being shown as bound in options menu

### ISSUE THREAD

**Issue by nekuro-dev** [ValveSoftware/Dota-2#195]
As you can see in the options menu, for item 1 and voice chat the boxes are blank. Clicking the box to bind and pressing mouse button 4 and/or 5 leaves the box blank

![2015-07-02_00001](https://cloud.githubusercontent.com/assets/3646809/8475985/fece3aca-20bc-11e5-9164-d9454b8407d4.jpg)

In game however, button 4 correctly works for item 1, as seen in the screen shot below, and mouse 5 is working for voice.

![2015-07-02_00002](https://cloud.githubusercontent.com/assets/3646809/8476007/3fadd352-20bd-11e5-8b19-b78c20ea7875.jpg)

**Comment by gdrewb-valve** [comment]
Confirmed that this happens on Windows also so this won't be tracked here.

**Comment by boskar** [comment]
Still an issue?
