### ISSUE TITLE
Dota 2 hangs on start

### ISSUE THREAD

**Issue by Jwsonic** [ValveSoftware/Dota-2#1950]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) is [here](https://gist.github.com/Jwsonic/810d0d2a28d8a559bbc89ebeca35b6da): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After the nemestice update when I start dota 2 it hangs at the dota 2 logo. I've verified game files and completely re-installed dota just in case. Dota was working earlier in the day as I played several games pre-patch.

#### Steps for reproducing this issue:

1. Start dota 2

**Comment by sethdusek** [comment]
I'm having the same issue. This is the output if I add "konsole -e %command" to the launch options to see what's going on 

```
[S_API] SteamAPI_Init(): Loaded '/home/kamal/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198112110089 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198112110089
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
Fontconfig warning: "/home/kamal/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/kamal/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
 failed to dlopen "/home/kamal/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so" error=/home/kamal/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so: cannot open shared object file: No such file or directory
 failed to dlopen "libcairo.so" error=libcairo.so: cannot open shared object file: No such file or directory
```

**Comment by MichaelArthurLong** [comment]
Same issue on Arch even with `-safe`

Was using Steam Linux Runtime
![image](https://user-images.githubusercontent.com/13504249/123273873-9681bd00-d535-11eb-9b05-4d81d5ee712f.png)

Game started fine after disabling it.

**Comment by sethdusek** [comment]
> Replying to https://github.com/ValveSoftware/Dota-2/issues/1950#issuecomment-867650753

Same, unticking "force the use of a specific steam play compatibillity tool" fixed it for me too.

**Comment by D4ndellion** [comment]
Same issue as OP on NixOS, steam linux runtime isn't set

**Comment by p-h** [comment]
This seems to be a NixOS issue. See https://github.com/NixOS/nixpkgs/issues/128021#issuecomment-868001423 for a potential workaround.

**Comment by Jwsonic** [comment]
This does seem to be a NixOS issue. I'll close this issue and continue there. Thanks for the help!

**Comment by sethdusek** [comment]
> This does seem to be a NixOS issue. I'll close this issue and continue there. Thanks for the help!

I am getting the issue on Solus OS with Steam Linux Runtime enabled. Disabling the runtime fixes it.

**Comment by h4ckedneko** [comment]
I'm also getting the same issue on Pop!_OS. Disabling the Steam Linux Runtime also fixes it for me.

**Comment by tommitah** [comment]
I'm also getting this issue on ArcoLinux. Disabling the Steam Linux Runtime fixes the issue, but I think it might have affected my performance.
