### ISSUE TITLE
disconnect + cannot reconnect , evver since most recent update battle pass last week occured. hopefully dev can fix this or pass to someone who can 

### ISSUE THREAD

**Issue by jay562** [ValveSoftware/Dota-2#1956]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* https://gist.github.com/jay562/fa29fdcf94b19913395c50564223a23f
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Steps for reproducing this issue:. 
+ 

Hi I honestly dont know if this is the right section to post this in, but i cannot find help anywhere else, ive attempted to post on reddit, dota 2 dev forum, steam community forum, and still no help. I am not the only one experiencing this issue, many have commented on my post on other forums, along with re-producing their own threads asking for help.

Pretty much this all started after the battle pass update that occured last week. At first, games were disconnected and everyone would disconnect, and about 8 of my games would not record or show on the timeline for recent games. That was fine , cause i did not get abandon.. now its getting worse!

Now when i cannot even finish a game without getting disconnected, then when trying to reconnect it shows a red dota logo and back to home page screen. Whats even more odd is when i try another computer, same issue, *AND* when i checked the replay once game was over, amazingly I WAS NOT DISCONNECTED IN GAME, i just looked like i was AFK to others, but on my end i was stuck on home screen UNABLE TO RECONNECT AT ALL. Also i been noticing my game report summary has not updated, and none of my abandons are showing, but obviously i am getting abandoned because i am in low priority now because of it and i am scared to even play because i dont want a perma ban.

I opened up console and everytime i tried to reconnect, this is what was coming out, im no coder so i have no idea what it means, although half way through it you will see a section where it says 

"[Client] CL:  CNetworkGameClient already exists for connection to '=[A:1:3578015754:17825]'
[Client] CL:  connection to '=[A:1:3578015754:17825]' already started
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] closed by peer (2007): NETWORK_DISCONNECT_STEAM_INUSE"

I dont know what that means, but it seems to fit my issue of as it says "connection already started", as i mentioned before when i checked replay, i never disconnected to everyone else, just myself, and i remained in game, but obviously got an abandon because i could not even move or play because i was actually on homepage stuck! 

Below is the entire console code that came up, also i tried reconnecting with connect command in console, not even sure if i used the right ip address, but regardless no luck.. My username is "wellcboutit" so if ur wondering why that keeps coming up thats because thats my username.
Hopefully this can be passed on to someone who can fix this issue over at valve :[ , Also this is happening on my windows computer, but i know its happening to others ive spoekn to on other forums ( not sure what operating system they are using )

[Networking] Steam datagram ticket found to connect to '=[A:1:3578015754:17825]'
[HostStateManager] CHostStateMgr::QueueNewRequest( Remote Connect (=[A:1:3578015754:17825]), 14 )
[EngineServiceManager] SwitchToLoop remoteconnect requested:  id [14] addons []
[Client] CL:  IGameSystem::LoopDeactivateAllSystems {
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 401.596
[Client] CL:  } IGameSystem::LoopDeactivateAllSystems done
[Client] CL:  Disconnecting from server: NETWORK_DISCONNECT_LOOPDEACTIVATE
[NetSteamConn] Closing Steam Net Connection on socket 'client' to loopback:1, handle #3876976314 (2055 NETWORK_DISCONNECT_LOOPDEACTIVATE)
[NetSteamConn] CloseSteamNetConnection handle #3876976314 (userdata 1)
[NetSteamConn] Disassociating NetChan       client                      [-1] (unknown) from Steam Net Connection handle #3876976314 (userdata 1)
[SteamNetSockets] [#3876976314 pipe] closed by app, entering linger state (2055) NETWORK_DISCONNECT_LOOPDEACTIVATE
[SteamNetSockets] [#99724519 pipe] closed by peer (2055): NETWORK_DISCONNECT_LOOPDEACTIVATE
[NetSteamConn] Removing Steam Net Connection for loopback:1, handle #3876976314
[Networking] Closing 'client' poll group
[stringtables] CL:  CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[Server] SV:  IGameSystem::LoopDeactivateAllSystems {
[Host] HO:  IGameSystem::LoopDeactivateAllSystems {
[Host] HO:  } IGameSystem::LoopDeactivateAllSystems done
[Server] SV:  } IGameSystem::LoopDeactivateAllSystems done
[Server] SV:  Server shutting down: NETWORK_DISCONNECT_LOOPDEACTIVATE (55)
[Server] CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
[Server] SV:  Disconnect client 'wellcBOUTit' from server(1): NETWORK_DISCONNECT_SHUTDOWN
[SignonState] Client 1 'wellcBOUTit' signon state SIGNONSTATE_FULL -> SIGNONSTATE_NONE
[NetSteamConn] Closing Steam Net Connection on socket 'server' to loopback:0, handle #99724519 (1001 NETWORK_DISCONNECT_SHUTDOWN)
[NetSteamConn] CloseSteamNetConnection handle #99724519 (userdata 0)
[NetSteamConn] Disassociating NetChan  wellcBOUTit                      [-1] (unknown) from Steam Net Connection handle #99724519 (userdata 0)
[NetSteamConn] Removing Steam Net Connection for loopback:0, handle #99724519
[Networking] Closing 'server' poll group
[stringtables] SV:  CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 401.740
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( remoteconnect : success )
CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 401.755
CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 401.755
[NetSteamConn] Steam Net connection #99724519 pipe closed by peer, reason 2055: NETWORK_DISCONNECT_LOOPDEACTIVATE
[NetSteamConn] CloseSteamNetConnection handle #99724519 (userdata -1)
[NetSteamConn] Opened Steam Net Connection on socket 'client' to =[A:1:3578015754:17825], connection #3347310802 SDR server steamid:90148553917476874 vport 0
[Networking] Created poll group for socket 'client'
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Requesting session from lax#23 (162.254.195.70:27037).  Ping = 77 = 13+64 (front+back).
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Selecting lax#23 (162.254.195.70:27037) as primary.  (Ping = 77 = 13+64+0 (front+interior+remote).)
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Requesting session from dfw#7 (155.133.253.38:27021).  Ping = 93 = 51+42 (front+back).
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Selecting dfw#7 (155.133.253.38:27021) as backup #1 (Ping = 93 = 51+42+0 (front+interior+remote).)
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] connected
[Client] Sending connect to =[A:1:3578015754:17825]
[Client] Received S2C_CHALLENGE [3974218504 auth 3] from =[A:1:3578015754:17825]
[Client] Sending C2S_CONNECT [47 protocol 3974218504 auth 3] to =[A:1:3578015754:17825]
[Client] Received S2C_CONNECTION from =[A:1:3578015754:17825] [addons:'']
[NetSteamConn] Associating NetChan       client =[A:1:3578015754:1782[0] (=[A:1:3578015754:17825]) with Steam Net Connection handle #3347310802 (userdata 0)
[Client] CL:  Connected to '=[A:1:3578015754:17825]'
[SignonState] CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
[Client] CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
[EngineServiceManager] SwitchToLoop levelload requested:  id [14] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[Client] LoadingDisplay changed from NONE to PRE_LOADING (map="")
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( levelload : success )
[SignonState] CL:  Permit INetchannel::Transmit()
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [14] addons []
[Client] CL:  CNetworkGameClient already exists for connection to '=[A:1:3578015754:17825]'
[Client] CL:  connection to '=[A:1:3578015754:17825]' already started
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] closed by peer (2007): NETWORK_DISCONNECT_STEAM_INUSE
[NetSteamConn] Steam Net connection #3347310802 SDR server steamid:90148553917476874 vport 0 closed by peer, reason 2007: NETWORK_DISCONNECT_STEAM_INUSE
[Networking] NETWORK_DISCONNECT_STEAM_INUSE
[NetSteamConn] Closing Steam Net Connection on socket 'client' to =[A:1:3578015754:17825], handle #3347310802 (0 (null))
[NetSteamConn] CloseSteamNetConnection handle #3347310802 (userdata 0)
[NetSteamConn] Disassociating NetChan       client =[A:1:3578015754:1782[0] (=[A:1:3578015754:17825]) from Steam Net Connection handle #3347310802 (userdata 0)
[Networking] Summary of connection [#3347310802 SDR server steamid:90148553917476874 vport 0]:
[Networking]     End-to-end connection: closed by remote host, reason code 2007.  (NETWORK_DISCONNECT_STEAM_INUSE)
[Networking]         Remote host is in data center 'iad'
[Networking]         Current rates:
[Networking]             Sent:   0.0 pkts/sec   0.0 K/sec
[Networking]             Recv:   0.0 pkts/sec   0.0 K/sec
[Networking]             Ping:77ms    Max latency variance: ???ms
[Networking]             Est avail bandwidth: 78.1KB/s  
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:         11 pkts           1,627 bytes
[Networking]                 Recv:          5 pkts             688 bytes
[Networking]                 Recv w seq:          3 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             No ping distribution available.  (3 samples)
[Networking]             No connection quality distribution available.  (0 measurement intervals)
[Networking]             Latency variance histogram: (2 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        2       0       0       0       0       0
[Networking]                   100.0%    0.0%    0.0%    0.0%    0.0%    0.0%
[Networking]         No rate stats received from remote host
[Networking]         Lifetime stats received from remote host 0.0s ago:
[Networking]             Totals
[Networking]                 Sent:          4 pkts               0 bytes
[Networking]                 Recv:          6 pkts           2,048 bytes
[Networking]                 Recv w seq:          5 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             No ping distribution available.  (4 samples)
[Networking]             No connection quality distribution available.  (0 measurement intervals)
[Networking]             Latency variance histogram: (4 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        1       1       2       0       0       0
[Networking]                    25.0%   25.0%   50.0%    0.0%    0.0%    0.0%
[Networking]     Primary router: lax#23 (162.254.195.70:27037)  Ping = 14+64=78 (front+back=total)
[Networking]         Current rates:
[Networking]             Sent:   0.0 pkts/sec   0.0 K/sec
[Networking]             Recv:   0.0 pkts/sec   0.0 K/sec
[Networking]             Ping:14ms    Max latency variance: ???ms
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:         13 pkts           1,916 bytes
[Networking]                 Recv:          7 pkts             826 bytes
[Networking]                 Recv w seq:          4 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             No ping distribution available.  (1 samples)
[Networking]             No connection quality distribution available.  (0 measurement intervals)
[Networking]             Latency variance histogram: (2 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        2       0       0       0       0       0
[Networking]                   100.0%    0.0%    0.0%    0.0%    0.0%    0.0%
[Networking]         No rate stats received from remote host
[Networking]         Lifetime stats received from remote host 0.0s ago:
[Networking]             Totals
[Networking]                 Sent:          5 pkts           1,024 bytes
[Networking]                 Recv:         11 pkts           2,048 bytes
[Networking]                 Recv w seq:          9 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             No ping distribution available.  (1 samples)
[Networking]             No connection quality distribution available.  (0 measurement intervals)
[Networking]             Latency variance histogram: (8 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        3       1       4       0       0       0
[Networking]                    37.5%   12.5%   50.0%    0.0%    0.0%    0.0%
[Networking]     Backup router: dfw#7 (155.133.253.38:27021)  Ping = -1+42=41 (front+back=total)
[Networking]     
[NetSteamConn] Removing Steam Net Connection for =[A:1:3578015754:17825], handle #3347310802
[NetSteamConn] Tried to send ad-hoc to address =[A:1:3578015754:17825], but address is not in list of steam net connections!
[Networking] client SendMessage unreliable failed with EResult: 2, bytes written 3
[Console] Server shutting down
[Client] CL:  Server disconnected: 3: NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[Client] LoadingDisplay changed from PRE_LOADING to NONE (map="")
Disconnection during connection phase. Sign-on state: 2. Disconnect reason: 3 (NETWORK_DISCONNECT_DISCONNECT_BY_SERVER).
[Client] CL:  Disconnecting from server: NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
[Networking] Closing 'client' poll group
[HostStateManager] CHostStateMgr::QueueNewRequest( Idle (levelload), 15 )
[HostStateManager] Discarding pending request 'Remote Connect (=[A:1:3578015754:17825]), 14'
[EngineServiceManager] SwitchToLoop levelload requested:  id [15] addons []
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[Client] LoadingDisplay changed from NONE to LOADING (map="")
[HostStateManager] Idle (levelload)
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [15] addons []
[Server] CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[Server] SV:  maxplayers set to 1
Initializing script VM...
...done
CSpeechScriptBridge was double-initialized: tearing down and rebuilding
[ResourceSystem] Error loading resource file "scripts/misc.vdata_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "scripts/precipitation.vdata_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "scripts/grenades.vdata_c" (Error: ERROR_FILEOPEN)
[Server] SV:  Spawn Server: <empty>
[Server] CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[Server] CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
[Client] CL:  CWaitForGameServerStartupPrerequisite done waiting for server
[Client] CL:  CCreateGameClientJob creating client connection to 'loopback'
[SteamNetSockets] [#4079343128 pipe] connected
[SteamNetSockets] [#1949606376 pipe] connected
[Networking] Created poll group for socket 'client'
[Networking] Created poll group for socket 'server'
[Networking] Connected loopback client=f325d618@loopback:1 <-> server=7434a1e8@loopback:0
[NetSteamConn] Associating NetChan  wellcBOUTit            loopback:0[1] (loopback:0) with Steam Net Connection handle #1949606376 (userdata 0)
[NetSteamConn] Associating NetChan       client            loopback:1[0] (loopback:1) with Steam Net Connection handle #4079343128 (userdata 1)
[Client] CL:  Connected to 'loopback:1'
[Server] SV:  Sending server info to client 'wellcBOUTit' at loopback:0
[Server] SV:  WriteInitialSpawnGroups sending 1 groups
[Client] Game: "Dota 2"
[Client] Map: "<empty>"
[Client] Players: 1 (0 bots) / 1 humans
[Client] Build: 9008 (revision 6639965)
[Client] Server Number: 8
[SignonState] CL:  CNetworkGameClient::ProcessServerInfo
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.001183 seconds
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_4_2699_9835.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_6_2699_9821.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_1_2699_9829.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_3_2699_9825.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_2_2699_9827.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_5_2699_9833.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_1_2699_9839.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_9848.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_9851.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_25701.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_25707.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_26396.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_8_2699_26645.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_7_2699_27172.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_7_2699_27175.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_5_2699_27178.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_4_2699_9823.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_6_2699_27320.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_2_2699_9841.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_9_2699_27340.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_8_2699_27461.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_9_2699_27484.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_3_2699_9837.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/roshan_location_2699_27790.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_27805.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_27807.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28052.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28056.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28058.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28060.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28066.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_4090_43.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_4090_49.vmdl_c" (Error: ERROR_FILEOPEN)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_2431_58.vmdl_c" (Error: ERROR_FILEOPEN)
[Client] CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
[Client] LoadingDisplay changed from LOADING to NONE (map="<empty>")
[Server] SV:  IGameSystem::LoopActivateAllSystems {
[Host] HO:  IGameSystem::LoopActivateAllSystems {
[Host] HO:  } IGameSystem::LoopActivateAllSystems done
[Server] SV:  } IGameSystem::LoopActivateAllSystems done
[Server] SV:  Game started
[Client] CL:  IGameSystem::LoopActivateAllSystems {
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000571 seconds
[Client] CL:  } IGameSystem::LoopActivateAllSystems done
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
[Server] SV:  Sending full update to client wellcBOUTit (reason:  initial update)
[Client] CL:  Receiving uncompressed update from server
[Networking]       client            loopback:1[0]:  NetChan Setting Timeout to 30.00 seconds
[Client] CL:  Signon traffic "client":  incoming 52.786 KB [17 pkts], outgoing 720 bytes [12 pkts]
[Networking]  wellcBOUTit            loopback:0[1]:  NetChan Setting Timeout to 20.00 seconds
Encountered entity that cannot be used in portrait maps - env_deferred_spot_light
Encountered entity that cannot be used in portrait maps - env_deferred_spot_light
Encountered entity that cannot be used in portrait maps - ent_dota_game_events
Encountered entity that cannot be used in portrait maps - info_player_start_goodguys
Encountered entity that cannot be used in portrait maps - info_player_start_badguys
[Entity System] ExecuteQueuedCreation() took 2205us [ Spawned: 8, Activated 8, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
[AnimResource] Model models/heroes/invoker_kid/invoker_kid_5336712f.vseq: unable to find bone reference "bicep_L"
[AnimResource] Model models/heroes/invoker_kid/invoker_kid_5336712f.vseq: unable to find bone reference "bicep_R"
[Entity System] ExecuteQueuedCreation() took 1161us [ Spawned: 5, Activated 5, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Discarding inactive session dfw#7 (155.133.253.38:27021).  ConnectionShutdown
[SteamNetSockets] [#3347310802 SDR server steamid:90148553917476874 vport 0] Discarding inactive session lax#23 (162.254.195.70:27037).  ConnectionShutdown
[SteamNetSockets] Received Stats from dfw#7 (155.133.253.38:27021) using incorrect/stale connection ID 3347310802.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from lax#23 (162.254.195.70:27037) using incorrect/stale connection ID 3347310802.  Rejecting wth NoConnection reply.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
[SteamNetSockets] Received Stats from dfw#7 (155.133.253.38:27021) using incorrect/stale connection ID 3347310802.  Rejecting wth NoConnection reply.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
[GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
[GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 322 bytes
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
ProtoBufHelper::ParseJSON: Ignoring extra JSON key 'success', which is not found in protobuf message 'CMsgDOTATeamInfoList'!
ProtoBufHelper::ParseJSON: Ignoring extra JSON key 'message', which is not found in protobuf message 'CMsgDOTATeamInfoList'!

**Comment by jay562** [comment]
hopefully someone can pass this off to a dev or someone who can fix this on dotas end, sure its not happening to everyone, but ive been posting on multiple forums and ive spoken to at least 30 others who are in this same situation. Im seriously about to cry lol, also i tried making a new account cause i figured im most likely getting banned perma if this continues, and it does same thing

**Comment by kisak-valve** [comment]
Hello @jay562, this issue tracker is limited to issues with the Mac and Linux port of Dota 2. It sounds like you already have posted this issue over at https://dev.dota2.com for the larger Dota 2 team, which is the right place for feedback that affects Dota 2's Windows client.

**Comment by jay562** [comment]
Hi , the odd thing is I have a macbook and this bug is still showing on my
macbook .
So I know it’s not my computer , everytime this happened on my main windows
computer I hopped on my Mac to see if I could reconnect , no luck .
Same red dota image then back to Home Screen .
