### ISSUE TITLE
[Linux] Various crashes when trying to start a custom game.

### ISSUE THREAD

**Issue by drager** [ValveSoftware/Dota-2#196]
When I tried to play a game of Pudge Wars the game crashed right after everyone was done loading. After that I started the game again and the game just crashed right away (after startup). Starting dota once again and trying going to the in-game bug reporter resulted in this image:

![2015-06-27_00002](https://cloud.githubusercontent.com/assets/1957563/8484437/0f1212cc-20f8-11e5-893d-beffaf422ab2.jpg)

```
    Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series

    Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 20,51" x 11,54"  (23,50" diag)
                                            52,1cm x 29,3cm  (59,7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  12016 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  213119 Mb
    Largest Free Hard Disk Block:  152113 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
We're going to need more info to try and figure out what's going on.  Is this the latest Steam system info?  If your crashes were in Valve code they should be caught and turned into a failure report.  Do you have dump files in /tmp/dumps that match the time of the crashes?

**Comment by drager** [comment]
Yes, this is the latest system info. I do not currently have any crash logs unfortunately... I'll try to reproduce this and provide crash logs.

**Comment by gdrewb-valve** [comment]
If you're familiar with gdb a backtrace might let us at least pinpoint the component that is crashing.

**Comment by AngryPenguinPL** [comment]
Hi,
I don't have crash but have smillar graphics in dota2 reborn.
I play with bots and when I minimalize game and come back to play I see this graphics corruption:

http://steamcommunity.com/sharedfiles/filedetails/?id=474268015

http://steamcommunity.com/sharedfiles/filedetails/?id=474267654

http://steamcommunity.com/sharedfiles/filedetails/?id=474267324

My Steam system info:
https://gist.github.com/xpris/a225f4cb2bf376d945fd

**Comment by gdrewb-valve** [comment]
@xpris, can you open a separate issue for the graphics corruption, even though it's the same as what drager is seeing?  We'll keep this issue just for the crash.

**Comment by gdrewb-valve** [comment]
Closing pending more information.
