### ISSUE TITLE
Dotaplus level renders with black background when high quality dashboard is disabled.

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#1963]
hi,
After the nemestice patch I disabled 'high quality dashboard' in the hope of regaining some lost fps.

However the only obvious difference I see is that the dota+ level is rendered with a black background. Is this intended?

![screen03](https://user-images.githubusercontent.com/5174562/125318380-141d3980-e33a-11eb-9693-fc7746b03959.png)

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Turmfalke2/32b8180eef8884092cd9b3703c3b7c88
* Have you checked for system updates?: No
* Are you using the latest stable video driver available for your system? No
* Have you verified the game files?: No

**Comment by steakscience** [comment]
This seems to be a Mac - Safari thing

I think Safari has issues with transparent video

**Comment by Yetoo1** [comment]
@steakscience Turmfalke2 gist shows this issue occurred on Linux rather than Mac. Are you also experiencing this on Mac?

**Comment by steakscience** [comment]
@Yetoo1 I've had this on Mac for quite a while now

**Comment by danginsburg** [comment]
This bug happens on Windows/DX11 too.  I've passed it along to the Dota Team but will close it out here.
