### ISSUE TITLE
Game crashing on every single launch with different options

### ISSUE THREAD

**Issue by Hursofid** [ValveSoftware/Dota-2#1974]
#### Your system information

* System information from steam
https://gist.github.com/Hursofid/263ac5bac2410d98bdaa3ef05cad79b6

* Have you checked for system updates?: YES

* Are you using the latest stable video driver available for your system? System is up-to-date using stable repositories

* Have you verified the game files?: YES

#### Please describe your issue in as much detail as possible:
Yesterday (12.09) I've been playing Dota2 for a while and then closed it, upgraded all packages, and after a while I was unable to launch the game using my system.
I've tried to verify local files, tried to remove launch parameters, but all of that didn't helped.
I'm able to play game on macOS, but not on linux anymore, Is it just me?

Here's a terminal output for launch: https://gist.github.com/Hursofid/45a93700008263cc942dabc61adaa9b7

#### Steps for reproducing this issue:

1. Install latest steam client
2. Install Dota2
3. Click "Play" button

**Comment by Hursofid** [comment]
I've also tried to reinstall Dota2 completely but it had no effect

**Comment by Hursofid** [comment]
I've also tried to reinstall Dota2 completely and it had no effect, issue the same
P.S. I've accidentally closed issue, sorry about that

**Comment by danginsburg** [comment]
Why are you using the heavy runtime?

**Comment by Hursofid** [comment]
> Why are you using the heavy runtime?

What does that mean?
Running game from terminal? If that's what you mean, the answer is only to provide log/verbosity output - I don't run the game like this usually

**Comment by danginsburg** [comment]
Yeah, the command line you were using is using the heavy runtime instead of the scout runtime, and you also need to launch it from dota.sh rather than directly running dota2 in order to correctly configure LD_LIBRARY_PATH.  Can you try this instead and post the log?

````
~/.steam/steam/ubuntu12_32/steam-runtime/run.sh .steam/steam/steamapps/common/dota\ 2\ beta/game/dota.sh
````

**Comment by Hursofid** [comment]
It still crashes, here you go:
https://gist.github.com/Hursofid/e9c0068c8b7021d2bbe806e31b96eaf4

**Comment by danginsburg** [comment]
Thanks.  So your crash is in the mesa RADV Vulkan driver version 18.3.6.  Are you able to update to a more recent version of mesa?

**Comment by Hursofid** [comment]
Thanks for tip!

I got following installed (newer versions):

`apt install libdrm-amdgpu1=2.4.104-1~bpo10+1 mesa-vulkan-drivers:amd64=20.3.5-1~bpo10+1 libdrm2=2.4.104-1~bpo10+1 libdrm-common=2.4.104-1~bpo10+1`

But when launching steam it requires:

`Steam needs to install these additional packages:
    libgl1-mesa-dri:i386, libgl1:i386, steam-libs-i386:i386`

And further then I get broken dependencies :(

**Comment by Hursofid** [comment]
And then following request:

`apt install libgl1-mesa-dri:i386=20.3.5-1~bpo10+1 libdrm-amdgpu1:i386=2.4.104-1~bpo10+1 libdrm-intel1:i386=2.4.97-1 libdrm-nouveau2:i386=2.4.97-1 libdrm-radeon1:i386=2.4.97-1 libdrm2:i386=2.4.104-1~bpo10+1 libglapi-mesa:i386=20.3.5-1~bpo10+1`

removes steam-launcher, xwayland, ffmpeg, thunderbird, gnome-shell and the other half of the system

Time to upgrade to Debian 11? I'm not sure if that would help

**Comment by kisak-valve** [comment]
Hello @Hursofid, what you're trying to do should be possible, but it looks like you're trying to frankenstein multiple versions together.

1- Debian's multiarch support requires that arch variants of a package must have exactly the same version, so if you're manually selecting package version, you should be updating the installed :i386 and :amd64 variant at the same time, with the same target version.
2- All installed libdrm related packages should match (`2.4.97-1` -> `2.4.104-1`), they're not meant to be mixed.
3- All installed mesa packages should be updated at the same time, not just parts of it.

If apt is asking you to remove packages, then something's been excluded that needs to be in the set.

**Comment by AutoAwesome** [comment]
Not the OP but I had the same issue today. Since I run gentoo I could try your fix to update mesa. 

I've updated media-libs/mesa-21.1.7 to media-libs/mesa-21.2.1 and dota started to work again.

**Comment by Hursofid** [comment]
@kisak-valve many thanks for explaining this, that day I have learnt something new :)
I've decided to install Debian 11 and it's running smooth now
