### ISSUE TITLE
Fullscreen Windowed not overlapping task bar.

### ISSUE THREAD

**Issue by TroyKomodo** [ValveSoftware/Dota-2#1979]
#### Your system information

https://gist.github.com/TroyDota/d2afb6ab15895d67bef4428125152e62
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Fullscreen Windowed Mode does not hide the taskbar.
I use GNOME with DashToPanel

#### Steps for reproducing this issue:

1. Open Dota
2. Place in fullscreen windowed

**Comment by AnzoDK** [comment]
Same issue on Arch Linux with Nvidia 495.44 and Zen kernel Happens only on GNOME 40+
