### ISSUE TITLE
Chat wheel always go to left

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#198]
Whenever I press Y to toggle the chat wheel it will always go to the left command, default is "Stun now!!" 
System Information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.6-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.21
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x     
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7874 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  882448 Mb
    Largest Free Hard Disk Block:  482448 Mb

**Comment by gdrewb-valve** [comment]
Do you have a joystick or controller plugged in?

**Comment by budimanjojo** [comment]
No I don't, using mouse and keyboard

**Comment by budimanjojo** [comment]
I've got another finding now. This issue "only happens" if I open up Dota 2 Reborn on the right monitor. When I change the window to lower resolution borderless the issue is gone. Then I tried starting Dota 2 Reborn on my secondary monitor (which is left monitor) using full resolution, the problem is gone.
So it only happens on right monitor (primary) on full monitor resolution.

**Comment by gdrewb-valve** [comment]
Thanks for the extra info, we'll try and repro.

**Comment by msjyoo** [comment]
Also experiencing this issue, however in my case the chat wheel always points up which is "Push Now!".

I have tried removing Ubuntu's fake joystick, using `sudo rm /dev/input/js*`, however this did not help.

I can also confirm that the issue is gone if the resolution is changed to a lower resolution in borderless windowed mode.

System information:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series

    Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 3120 x 1920
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15957 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  189907 Mb
    Largest Free Hard Disk Block:  3656 Mb

Installed software:

Recent Failure Reports:

```

**Comment by budimanjojo** [comment]
Latest update doesn't fix the issue

**Comment by budimanjojo** [comment]
Still not fixed, please this bug is really annoying. I can't say anything to my teammates

**Comment by gdrewb-valve** [comment]
We will comment here when this issue is fixed.  As we do not have a repro at Valve I can't say when a fix might be coming.

**Comment by budimanjojo** [comment]
I can repro it everytime. How can I help? The console shows nothing

**Comment by gdrewb-valve** [comment]
Nobody has a theory on why it would be happening, particularly only in the specific situation you're seeing it in, so it's hard to say where investigation should be focused.  At some point we'll try and recreate your configuration and hopefully that'll show something but I don't know when that will happen.

Does the new desktop-friendly fullscreen mode differ from borderless window mode?

**Comment by budimanjojo** [comment]
It happens when the primary monitor is on the right side with fullscreen. Yes, I'm now using desktop-friendly fullscreen and the issue still exist.

**Comment by gdrewb-valve** [comment]
Does it happen with a monitor-sized borderless window?

**Comment by budimanjojo** [comment]
Yeah it happens. But not in small size borderless window

**Comment by gdrewb-valve** [comment]
Thanks for the extra info, we'll look more here at some point.  Unfortunately that will probably not be soon.

**Comment by msjyoo** [comment]
My primary monitor is on the left side and this still occurs. Looks like this issue happens on an Ubuntu distribution on a setup with dual monitors. Just try this issue on a dual monitor setup with Ubuntu live CD to repro? The Reborn Beta is practically unplayable with this issue.

**Comment by budimanjojo** [comment]
No it's not Ubuntu issue, I'm using Manjaro. It's also not desktop environment issue, tested on xfce and kde. It looks like mouse grabbing issue because when you press chat wheel command the mouse tries to go to the other monitor causing the bug (because it happens in game which grabbing the mouse). It's not joystick problem because I've told the kernel my mouse is not a joystick by making an udev rule. This bug is weird because some report it keeps going top, right, left and we are all multi monitor users.

**Comment by gdrewb-valve** [comment]
This is good information, thanks for trying to narrow things down.  We'll keep exploring here too.

**Comment by gdrewb-valve** [comment]
OK, I was just able to reproduce this on Windows, although it took some doing.  The issue is that when the chat wheel pops up the game moves the mouse cursor to the center of the chat wheel (which you can't see since the cursor is off).  When filling the screen it computes the center position based only on the screen size and then sets the cursor position so if the game is not at 0,0 it'll put the cursor in the wrong spot.  It's easy to fix.

**Comment by budimanjojo** [comment]
Nice then. Hope the next update can fix it. Thanks drew

**Comment by gdrewb-valve** [comment]
I'm not sure which release it will make it into; I'll post here when an update goes out with the fix.

**Comment by budimanjojo** [comment]
I've got a workaround for this issue using KDE. I changed the dota 2 video settings to monitor sized resolution borderless window (now it works after the addition of desktop-friendly fullscreen). After that, to make it fullscreen I made a window rule for dota 2 using kwin settings. See pictures
![2015-07-23_00002](https://cloud.githubusercontent.com/assets/13085918/8846440/6e7e81aa-3151-11e5-99a4-2e7c057f8e75.jpg)
![snapshot1](https://cloud.githubusercontent.com/assets/13085918/8846439/6e7b6a88-3151-11e5-883a-4c0a1f8d08ea.png)
![2015-07-23_00003](https://cloud.githubusercontent.com/assets/13085918/8846488/d79ff95c-3151-11e5-80b7-6778280c2b9b.jpg)

**Comment by gdrewb-valve** [comment]
There is a chance the 7/23 update picked up the fix, give it a try.

**Comment by budimanjojo** [comment]
No it's not fixed yet.

**Comment by budimanjojo** [comment]
Here's another finding. The problem in this issue is not just that. Look at these screenshots:
![2015-07-24_00001](https://cloud.githubusercontent.com/assets/13085918/8870906/c0fdc5ba-321b-11e5-910f-8c2c2c6c3895.jpg)
![2015-07-24_00002](https://cloud.githubusercontent.com/assets/13085918/8870911/ce5679a0-321b-11e5-8e2f-5021a5448fc7.jpg)
See the mouse cursor (not captured idk why) position. Before I press the "Y" button which is chatwheel hotkey, the mouse cursor is at the middle of the map. After pressing the chatwheel hotkey, the mouse cursor moves itself to the left edge of the screen (and will stay there until I release the "Y" key).

Now, let's compare it to the chatwheel WHEN it is functioning properly. After changing to borderless window, I pressed "Y" key. Then I try moving the mouse to the left side of the screen (while holding the "Y"). What I see now is the command "Stun!" is highlighted but THE SCREEN DOESN'T MOVE at all.
So the weird thing here is why the chatwheel also move the map even when the position of the cursor is the center of the screen instead of the monitor (like gdrew mentioned before). I think the code should be cleaned up a bit there, Valve. Hope this can be fixed really soon :)

**Comment by msjyoo** [comment]
Let me know which specific build contains the patch and I'll try it and report if I can still reproduce the bug.

**Comment by gdrewb-valve** [comment]
It'll be the next update but I don't have firm details on when exactly that'll be.

**Comment by gdrewb-valve** [comment]
Oops, looks like they did another update today, it's not in that one.

**Comment by budimanjojo** [comment]
Yeah. I just saw it, small update to fix some gameplay related bug. No problem I already told my mind that next big update should be at least another 10 days or so :)

**Comment by budimanjojo** [comment]
Confirmed the latest update fixed this bug. Thanks gdrew :)

**Comment by budimanjojo** [comment]
Closing this issue now

**Comment by gdrewb-valve** [comment]
Possibly happening again.

**Comment by MaikuMori** [comment]
Yeah I'm still having this, even after the last patch.

Some info:
Old Dota 2 correctly starts on the left screen (primary). Reborn starts on the right screen. I'm used to moving it to the left screen (using gnome overview screen). And I just tested that if I don't do that, it works correctly, but if I move the window the chat wheel will not work correctly.

So two points:
- Game starts on non-primary screen.
- Seems like window information is not updated when I move the window which makes this bug to show up again.

OS: Archlinux
WM: Gnome 3.16.3

**Comment by gdrewb-valve** [comment]
Closing as the new reports are more to do with #286 than the chat wheel problem here.

**Comment by budimanjojo** [comment]
I'm still downloading the update, 1 hour to go. I'll report again soon to see if the problem is happening again.

**Comment by budimanjojo** [comment]
I can confirm that this is not happening even after the update. All is good

**Comment by ghost** [comment]
I am running KDE, and have this issue (mouse-wheel always points up). Playing in windowed mode as fullscreen interferes with my panel and therefore does not allow me to edge-pan to the bottom.

**Comment by budimanjojo** [comment]
How does fullscreen interferes with your panel? 
It's weird because before it was fixed on me it only happened in fullscreen mode and not in windowed mode.

**Comment by ghost** [comment]
How fullscreen interferes with my panel: https://github.com/ValveSoftware/Dota-2/issues/435

**Comment by budimanjojo** [comment]
Did you try disabling fullscreen compositing and unredirect fullscreen on kde?

**Comment by ghost** [comment]
I am quite new to Linux so I am not 100% sure, but I believe you might be referring to the option "Suspend desktop effects for fullscreen windows" which I do have checked. Is it possible to move this conversation to #435?

**Comment by msjyoo** [comment]
I am also (still) experiencing this issue on windowed mode.

**Comment by gdrewb-valve** [comment]
sekjun9878, what window size are you using and on what size monitor?  Are you using a window border or not?

**Comment by gdrewb-valve** [comment]
@sekjun9878, what window size are you using and on what size monitor? Are you using a window border or not?

**Comment by gdrewb-valve** [comment]
For anybody still affected by this can you respond with info on what video mode, window size and window border you're using, plus how many monitors you have and their sizes?

**Comment by admshao** [comment]
I have this too

Left monitor (primary) 1920x1080@60
Right monitor (where dota runs) 1920x1080@120
Dota video is Fullscreen Friendly with all maxed and VSync Off.

i have no launch parameters that affect window

2015-10-15 17:48 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
@admshao, if you switch to a monitor-sized borderless window does Reborn start on the primary?  If you make the window smaller than the monitor does it start on the primary?  I'm wondering if this is another symptom of #556.

**Comment by admshao** [comment]
I'm not @my rig atm.

It is working as i expected to open on the other monitor, but i guess i'll
have to use those -sdl_monitor # to achieve the same effect.

I'll update later with more info.

2015-10-15 18:01 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by admshao** [comment]
@gdrewb-valve  OK. FullScreen Friendly is always going to left.

Borderless window works properly

Windowed with a lower resolution the chat whell goes crazy. If you move your mouse more than a inch it acts like crazy. You have to move it really carefully to be able to get something out of it. It`s fun.

Switching back to Fullscreen got my dota to be always black. The full window.. And now i can`t play lol. I'll redownload the game.

**Comment by gdrewb-valve** [comment]
The bug with bordered windows is a known SDL bug where it misreports the window position.  You aren't using -sdl_displayindex, are you?  I don't think so, and the fact that fullscreen is opening on the wrong monitor (non-primary) suggests #556 is happening and then throwing off the mouse cursor position, which affects the chat wheel.

I'm not sure what happened with switching back to fullscreen.  If you add -sw -noborder to your launch options you can force it back to borderless windowed mode and then experiment with settings again.  You can also use -w <number> and -h <number> to set a width/height if you need to.  You shouldn't need to reinstall.

**Comment by admshao** [comment]
Already reinstalled.
So main monitor is left one with 60hz. Right one is 120hz

a.out from sdl monitor infos ->
https://gist.github.com/admshao/58ec732a8aeebcfca894

Playing with -sdl_displayindexes:

0 i got on right monitor but with 60hz ingame feel, chat wheel broken
1 i got on right monitor with 120hz just fine, chat wheel broken (same as
no parameters at all)
2 or + i got on left monitor @ 60hz and chat wheel working.

I`ll try with the -sw -noborder params.

2015-10-15 21:49 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by admshao** [comment]
I had no lucky using -sw -noborder -w1920 -h1080
But after switching back to fullscreen it fixed my chat cheel.

When i restarted dota. The chat whell went broken again.

**Comment by gdrewb-valve** [comment]
Try a space between -w / -h and the number.  Thanks for the experiments, it does seem like you're affected by #556.  For some reason in that case it doesn't seem like SDL or Reborn knows about the move to the other monitor so things are bad.  We're discussing it with the SDL devs but it'll take a while to get more info.

**Comment by admshao** [comment]
OH. i did with and without the space after the -w and -h. Same results>
It`s fine. 1 more thing to w8. #Vulkan FTW

2015-10-15 22:10 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by admshao** [comment]
For Further info i`ll comment on #556. Ty for your time!

2015-10-15 22:20 GMT-03:00 Fabio Madia admshao@gmail.com:

**Comment by gdrewb-valve** [comment]
Is anybody having a different issue?  It seems like #556 is sufficient now and I'll be closing this out.

**Comment by Apple-Lion** [comment]
It's two years later, and I'm having this exact same issue with Solus.  Center monitor, and chat wheel, regardless of keybinding, causes the same issues.  Can we reopen this?

**Comment by gdrewb-valve** [comment]
You should open a new issue,  Please include full system info, your monitor sizes and positions and the video settings and launch options you're using.

**Comment by adrien-berchet** [comment]
> I've got a workaround for this issue using KDE. I changed the dota 2 video settings to monitor sized resolution borderless window (now it works after the addition of desktop-friendly fullscreen). After that, to make it fullscreen I made a window rule for dota 2 using kwin settings. See pictures
> ![2015-07-23_00002](https://cloud.githubusercontent.com/assets/13085918/8846440/6e7e81aa-3151-11e5-99a4-2e7c057f8e75.jpg)
> ![snapshot1](https://cloud.githubusercontent.com/assets/13085918/8846439/6e7b6a88-3151-11e5-883a-4c0a1f8d08ea.png)
> ![2015-07-23_00003](https://cloud.githubusercontent.com/assets/13085918/8846488/d79ff95c-3151-11e5-80b7-6778280c2b9b.jpg)

Thanks it works for me!
