### ISSUE TITLE
(Cache issue?) game crashes on launch or during match

### ISSUE THREAD

**Issue by regulator-g** [ValveSoftware/Dota-2#1981]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
Gist: https://gist.github.com/regulator-g/114b50b3f2fc74288749ae15a83bb2c4
Arch with KDE
5.14 kernel
6700xt
Mesa 21.2.2

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

1. When I launch dota 2 I get a lot of warnings like this
```
If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
Fossilize WARN: Referenced Render pass fd3905f897474fb9, but it does not exist.
```
2. sometimes the game will not launch and sometimes it will launch

if i disable or delete the cache (-vulkan_disable_steam_shader_cache) the game works for an hour then crashes to desktop

3.  works fine and can play for 2 hours on OpenGL

Console log and dump file snippet
https://gist.github.com/regulator-g/a2ebf1383b7548be8e62491849576cb8

additional notes:
-every day dota2 downloads an 880mb update
-recently reinstalled OS, restoring profile folder and using existing steam install

**Comment by kisak-valve** [comment]
Hello @regulator-g, your system is configured to use AMDVLK. Can you test if the same behavior happens with mesa/RADV?

**Comment by regulator-g** [comment]
> Hello @regulator-g, your system is configured to use AMDVLK. Can you test if the same behaviour happens with mesa/RADV?

oh, this is embarrassing, had no idea it was using AMDVLK! will switch over and test..

**Comment by regulator-g** [comment]
hey @kisak-valve 
All good now, I had both AMD and Mesa Vulkan implementations installed. just had to set this environment variable

`AMD_VULKAN_ICD=RADV`

Is AMD vulkan not supported? 
I made an edit on one of the arch wiki's saying to make sure Mesa vulkan is in use

**Comment by psypherium** [comment]
Here is the terminal command to run Steam without AMDVLK: `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json steam`

This workaround will prevent other games from running (For example, Warframe, which complains that "DirectX11 is not installed")

I was hoping initially that I could just uninstall AMDVLK and not have to do any workaround, but AMDVLK is a dependency of the Steam package on Arch Linux. And even then, other games seem to require it to run.

I would recommend re-opening this issue until the RADV supports other games in Proton, or until Dota2 is runnable under AMDVLK.

**Comment by regulator-g** [comment]
Yeah, I agree.. Reading your other post I think if Valve is going to remove OpenGL they need to either support AMDVLK or force Dota2 to check/use Mesa's Vulkan
