### ISSUE TITLE
Unable to launch dota2 with OpenGL flag

### ISSUE THREAD

**Issue by LuyeT** [ValveSoftware/Dota-2#1983]
#### Your system information

  * System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
  * https://gist.github.com/LuyeT/d8aea2daff779f3d32fcd6aac0918546
* Have you checked for system updates?: [Yes/No]
* yes
* Are you using the latest stable video driver available for your system? [Yes/No]
* yes
* Have you verified the game files?: [Yes/No]
* yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I've been unable to launch dota2 while using the -opengl flag, which is necessary as the vulkan implementation is incapable of running for more than 10 minutes without crashing. This has been occurring starting today (suspect since the update which was downloaded at 2AM CEST). Since this afternoon, I've done a full system update, validated game files, clearing download cache, deleting app manifest, full reinstall of the game and tried running it both through steam-runtime and steam-native to no avail. Client crashes as soon as it gets to the point of launch when the TI swirling clouds background appears.

On steam-native I was able to launch the game using vulkan, but as been the case for 1-2 years now, the game will crash after 2-10 minutes of gameplay (though the lobby seems stable). For steam-runtime, game crashes on launch, with or without vulkan.

#### Steps for reproducing this issue:

1. add "-opengl" to launch properties
2. Launch dota.
3.

**Comment by kisak-valve** [comment]
Hello @LuyeT, my understanding is that Dota 2 has an `-gl` launch option to ask the game to use OpenGL, not `-opengl`. Please check if `-gl` behaves the same.

For the Vulkan side of your feedback, it looks like your system is configured to use AMDVLK. Are the crashes you're seeing with the Vulkan backend of Dota 2 with AMDVLK or mesa/RADV as the video driver and can you test how it behaves with the other driver?

**Comment by LuyeT** [comment]
Hi Kisak, thank you very much for your swift response. It seems you were correct about the -gl flag, the game is running after changing the flag to that. Though I only started poking around with the launch flags after the game would repeatedly fail to launch, so I would surmise that -opengl was a valid flag up until recently as that's what I've been playing with.

Regarding Vulkan drivers, I actually have both installed. Though based on https://wiki.archlinux.org/title/Vulkan#Selecting_Vulkan_driver , it's been defaulting to AMDVLK. After launching with the parameters for RADV, shader compilation for dota ensued, which suggests i have indeed been using AMDVLK. It will take some time before I can comment on whether use with RADV is stable.

Thanks again.

**Comment by regulator-g** [comment]
Hi @kisak-valve 
Same issue I had.. Can Valve either support vulkan used by AMDVLK or include a check/override at startup to use Mesa's vulkan?

LuyeT my game has been running perfectly since setting Mesa's Vulkan as the default.

**Comment by LuyeT** [comment]
I've done a few games now with RADV, and I've experienced no crashes so far. This is good news of course, but I find it somewhat problematic that this doesn't seem to be documented anywhere. This is an issue that has been plagueing the linux client (seemingly) since the release of vulkan for dota2.
I feel the most straight forward way to bring it to linux user's attention would be some sort of warning notification from the steam client at launch, or in-game. There are multiple threads about instability with VK on github, without any mention of this fix.

This comes to mind, though I've definetely seen a few others across the years while trying to find a solution, one of them which suggested OpenGL for stability which I ended up using.
https://github.com/ValveSoftware/Dota-2/issues/1916#issue
And like me, many others were also driven to attempt to run the windows client through proton:
https://www.protondb.com/app/570
Some have even gone as far as dual-booting for the purpose of running dota.

I'll spread the word wherever appropriate, but I really feel some mainstream information about Dota2 dependencies should be in place.

**Comment by LuyeT** [comment]
@kisak-valve Would like to update that I'm getting far fewer crashes when using the RADV vulkan backend (about 2 crashes pr 5-6 games), compared to crash every 5-10 min with AMDVLK. On AMDVLK, the renderer just freezes and I can switch workspaces and send SIGKILL from htop (SIGTERM is irresponsive).

However, the crashes with RADV are much more severe, the screen goes completely black, the fans start spinning at max RPM, and I can't switch workspaces or even TTY. Computer must be restarted with REISUB. Somewhat peculiar to this is that audio is still running perfectly during this (all gamesounds, even voices of teammates). 

The original problem of this issue is resolved though (using -gl instead of -opengl), so perhaps this should be closed and I should open a new one with the snippets related to Vulkan for easier reading?

**Comment by kisak-valve** [comment]
Sounds reasonable. It may be worthwhile to also mention the driver-specific behavior to the video driver vendors.

**Comment by metaory** [comment]
https://github.com/ValveSoftware/Dota-2/issues/2264#issuecomment-1565910588

**Comment by kisak-valve** [comment]
Hello @metaory, OpenGL is no longer supported with Dota 2 and this was communicated a couple times, most recently with:

As we mentioned when we launched [Battle Pass: Part II](https://steamcommunity.com/linkfilter/?url=https://www.dota2.com/newsentry/3398555399443921912), this update has removed support for OpenGL. For macOS customers, the minimum requirement is now macOS 10.13.6 with a Metal-capable GPU (AMD GCN-based GPU or newer; NVIDIA Kepler-based GPU or newer; or Intel HD 4000 or newer). For Linux customers, AMD GCN+, NVIDIA Kepler+, or Intel HD 5000-series or newer is required. (https://www.dota2.com/newsentry/3659774959159800240)

This issue report is outdated and regarded the command line syntax that Dota 2 responded to years ago.
