### ISSUE TITLE
[Linux/Arch(EndeavourOS)/i3wm] Random crashes ingame

### ISSUE THREAD

**Issue by bernifresh** [ValveSoftware/Dota-2#1985]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) deleted
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

I use a Arch and the distro is EndeavourOS. Everything is up to date. CSGO btw is running without any problems. I had some years/months ago something similar like that but it just disappear after some months. I'm using i3 as WM. 

#### Please describe your issue in as much detail as possible:
I just start the game and in game it just shutdown without any error message. So everything works fine until I'm really in game. I rejoin the game and randomly it shutdowns again. The time between that crashes/shutdowns are really different, so there is no interval.

#### Steps for reproducing this issue:
Not possible ?!

**Comment by jiampong212** [comment]
same here except im using bspwm. why has no one addressed this issue yet?

**Comment by ChrisLauinger77** [comment]
I have the same problem. 
Sometimes it runs for hours and sometimes it crashes during the same game multiple times.
It caused me 2 abandons in the last week - and now I am in low prio. Behaviour score is over 9800 though. I did even finish the 2 matches but still they are accounted as abandon :(
I never abadoned a game on purpose - no matter how bad it was :( Please fix asap - ruins the experience.
Gist:
https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb

**Comment by bernifresh** [comment]
So my feeling is that Valve really don't care about some issues, idk why the Steam Support said I should go to the github repo and ask there. To be honest, if there is no real support from Valve site, why should I waste my time to write a issue if there is no response. Would be enough just to say "We don't care about that problems.".
