### ISSUE TITLE
SteamDatagramServer_Init failed. Can't get steam interface 'SteamGameServer014'

### ISSUE THREAD

**Issue by huoshizhe** [ValveSoftware/Dota-2#1989]
win10
Dota2 robot gam
![QQ截图20211031031201](https://user-images.githubusercontent.com/51113968/139555787-d339091b-2abf-4959-8b28-e8787c2e65c1.png)
e

**Comment by kisak-valve** [comment]
Hello @huoshizhe, this issue tracker is limited to issues with the Mac and Linux port of Dota 2. Please use https://dev.dota2.com for issues with the Windows client of Dota 2.

Closing as out-of-scope for this issue tracker.

Setting that aside, if I had to guess, I suspect that your Steam client is outdated and missing steamworks sdk 1.52 support.
