### ISSUE TITLE
CPU and RAM usage is beyond control again since 29/06 update

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#199]
![screenshot_2015-07-03_16-26-34](https://cloud.githubusercontent.com/assets/13085918/8496679/4ab99dbe-21a1-11e5-8a54-d1a04e6fcd3c.png)

This is the cpu usage after alt+tab back to desktop and took the screenshot immediately. Usage is above 70% when in game, which is really high.

System Information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.6-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.21
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x     
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7874 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  882448 Mb
    Largest Free Hard Disk Block:  482448 Mb

**Comment by gdrewb-valve** [comment]
Is this with the input problems you're having?  That would generate continuous extra work.

**Comment by budimanjojo** [comment]
I don't know. The input problem is caused by my mouse or keyboard? Maybe I can try using other input to try it out?

**Comment by gdrewb-valve** [comment]
It's hard to say what the input problem is, although if your mouse and keyboard are working in other applications it seems more like a Reborn problem.

Does Source 1 Dota 2 work?

**Comment by budimanjojo** [comment]
No one here with the same issue? The forum has someone with the same problem as me
http://dev.dota2.com/showthread.php?t=173221
Source 1 works

**Comment by gdrewb-valve** [comment]
The 8/14 update had a few tweaks to sleep and wakeup, did that change usage for you?

**Comment by budimanjojo** [comment]
Yeah, before it was 70% even in menu. Now it only takes 11% of usage in menu and goes up to 60% ingame.

**Comment by gdrewb-valve** [comment]
OK, I'm going to close this.

When the game is running it'll try to use all resources possible, there is no upper limit to the CPU usage in that case.  The menu shouldn't be that bad, though, so hearing that it has dropped back to 11% is good.

**Comment by budimanjojo** [comment]
Ok thanks gdrewb
