### ISSUE TITLE
Constant Freezing

### ISSUE THREAD

**Issue by bhavaygg** [ValveSoftware/Dota-2#1991]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* [Link](https://gist.github.com/Chokerino/8c33b2ea7e029f2329f5284ed2a33af6)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
The game freezes randomly and takes like 10-15 seconds to recover or sends me to reconnect or crashes completely. This sometimes happens on the main menu as well but does not seem to crash then. This issue seems to automatically resolve itself with some updates to the game but comes back after others. 

- Tested both on WIn 11 and 10.
- Tested new and old nvidia drivers.

**Comment by kisak-valve** [comment]
Hello @Chokerino, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this at https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for the larger Dota 2 dev team.

**Comment by bhavaygg** [comment]
@kisak-valve I have tried to go through Steam Support but they were unable to help.  Could this issue be forwarded internally because it has been around for months and there hasn't been any permanent solution and no communication regarding it?
