### ISSUE TITLE
I can no longer ping sgp-1.valve.net and sgp-3.valve.net

### ISSUE THREAD

**Issue by wildcard-f8** [ValveSoftware/Dota-2#1993]
I used to ping sgp-1.valve.net, sgp-2.valve.net and sgp-3.valve.net to check the latency and for any packet loss before playing. Now I can only ping sgp-2.valve.net. What happened to the other two. My reason is, the ping test in the client doesn't check for packet loss and sometimes it shows that I have good ping but when I get into the game I have packet loss. Now I can't check before playing. If I remember correctly sgp-1 and sgp-2 are Singapore and sgp-3 was Japan. In game the SEA server and JPN servers are the only ones that I have good connection with. How can I check for packet loss to these servers before actually playing?

P.S. Apologies if this isn't the right venue to ask this question, but I've tried everywhere, including the dev forum and have gotten nothing for over a year now. I just want to check ping and packet loss before playing. If you can add the ping and packet loss info before actually playing a match, I'd be happy to no longer ping your servers from the command line.

**Comment by kisak-valve** [comment]
Hello @wildcard-f8, this issue tracker is limited to issues with the Mac and Linux versions of the Dota 2 client. You'll want to use https://dev.dota2.com or [Steam Support](https://help.steampowered.com/) for your feedback to reach the larger Dota 2 dev team.
