### ISSUE TITLE
Dota2 is Crashing after updating OS to U20.04.4 due to incompatible libtcmalloc_minimal.so.0 shipped with Dota2

### ISSUE THREAD

**Issue by JaxLinAMD** [ValveSoftware/Dota-2#1999]
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3 with 20.04.4 updates with AMDVLK driver
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Dota2 crash on ubuntu 20.04.4 with AMDVLK driver

#### Steps for reproducing this issue:

1. Set up ubuntu 20.04.4 system
Ubuntu 20.04.4 Instructions (Using Impish Repos):
1) Install Ubuntu 20.04.3 from ISO
Update system via:
sudo apt update && sudo apt dist-upgrade
Reboot system via:
sudo reboot
2) Add Impish repositories:
sudo bash -c "echo 'deb http://archive.ubuntu.com/ubuntu impish main restricted universe multiverse' > /etc/apt/sources.list.d/hirsute.list" && sudo apt update
Update repos via:
sudo apt update
3) Install 5.13 kernel via:
sudo apt install linux-generic-hwe-20.04-edge linux-headers-generic-hwe-20.04-edge linux-image-generic-hwe-20.04-edge linux-tools-generic-hwe-20.04-edge systemd
Reboot system via:
sudo reboot
2. install AMDVLK driver from https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2021.Q4.1
3.  run ./dota2 -console -vulkan and observe following error: failed to release invalid pointer : 0xxxxxxxxxx

Notes:
Issue is not observed on RADV because RADV doesn't use aligned_alloc
Issue is not observed if replace libtcmalloc_minimal.so.0 with distro one (apt install libtcmalloc-minimal4 and then replace it)

**Comment by Kai-AMD** [comment]
Thanks @kisak-valve for transferring it from steam-for-Linux to Dota-2 issue, please let us know if you need any more information.

**Comment by Kai-AMD** [comment]
Happy New Year! I would appreciate it if anyone could provide any update on this issue. :)

**Comment by amdvlk-admin** [comment]
issue is not observed after steam update

**Comment by JaxLinAMD** [comment]
issue is still observed.

**Comment by rifat-h** [comment]
i moved back to linux after a long time. Installed dota 2. after clicking play nothing happens.

**Comment by rifat-h** [comment]
> issue is still observed.

Have you solved the issue ?

**Comment by Kai-AMD** [comment]
> 

No, still working on that.

**Comment by accerqueira** [comment]
I have the same issue. Replaced libtcmalloc_minimal.so.0 and now it works!
Thanks for the workaround @JaxLinAMD!

Edit1: Actually, it didn't crash on load, but it did crash on match/hero demo.
Edit2: And I'm on Arch, not Ubuntu...

**Comment by Zesko** [comment]
The same issue, Dota 2 does not launch with the option `-vulkan` after the update of Arch based linux, but the option `-gl` works.

I think, this issue is caused by the Arch update from `glibc` 2.33 to 2.35 that broke Dota2 and CS:GO https://github.com/ValveSoftware/csgo-osx-linux/issues/2887

The log:
```log
src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x5605f5b49750
crash_20220224184014_2.dmp[37269]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220224184014_2.dmp
/home/zesko/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 109: 37235 Aborted                 (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20220224184014_2.dmp[37269]: Finished uploading minidump (out-of-process): success = yes
crash_20220224184014_2.dmp[37269]: response: CrashID=bp-5fbf4da8-d016-4e85-b21b-c5ae92220224
crash_20220224184014_2.dmp[37269]: file ''/tmp/dumps/crash_20220224184014_2.dmp'', upload yes: ''CrashID=bp-5fbf4da8-d016-4e85-b21b-c5ae92220224''

```

**Comment by accerqueira** [comment]
I got it to work with vulkan by adding `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` to the environment (export it from ~/.profile or set launch options for dota2: `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json %command%`).

I think the problem happened because I have amdvlk and vulkan-radeon installed.
Apparently, amdvlk is not supported by Dota2, and AMD_VULKAN_ICD=RADV is being ignored now, so Dota2 picked amdvlk ICD (`/usr/share/vulkan/icd.d/amd_icd64.json`) and crashed.

**Comment by Kai-AMD** [comment]
We've got a fix for AMDVLK, hopefully it can be released in the upcoming version.

**Comment by presianbg** [comment]
Dota does not load on Solus either (amdgpu opensource kernel driver).

**Comment by NuSuey** [comment]
I seem to to be having the same issue as was mentioned (using Manjaro), seems that closing steam and running steam via `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json steam`
solved the issue for me

**Comment by ghost** [comment]
> I seem to to be having the same issue as was mentioned (using Manjaro), seems that closing steam and running steam via `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json steam` solved the issue for me

It's not working for me. It creates CS:GO window and it crashes.

**Comment by cppcooper** [comment]
> The same issue, Dota 2 does not launch with the option `-vulkan` after the update of Arch based linux, but the option `-gl` works.

I don't know if anyone else is seeing this, but I get this message when I try launching with -vulkan instead of -gl
```
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x556dd3135220
```
Seems like maybe it's a possible cause for whatever pointer being invalid.

**Comment by Zesko** [comment]
@cppcooper 

Did you add `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` in `/etc/environment`, then reboot?
It need the installation of the package `vulkan-radeon`.

**Comment by ShayanAkhun** [comment]
> i moved back to linux after a long time. Installed dota 2. after clicking play nothing happens.
 same here it was working fine a few days ago now when i click the play button nothing happens !!!!

**Comment by Kai-AMD** [comment]
Yes, it should have been fixed in AMDVLK recent release.

**Comment by kisak-valve** [comment]
Closing per the last comment.
