### ISSUE TITLE
UI not loading in game (Xubuntu 15.04, Nvidia)

### ISSUE THREAD

**Issue by tstarboy** [ValveSoftware/Dota-2#2]
UI not loading in game. Using Xubuntu 15.04, kernel 3.19.0-14, Nvidia proprietary 352.21 drivers on a GTX 970, at 2560x1440 resolution fullscreened.

![2015-06-22_00003](https://cloud.githubusercontent.com/assets/680229/8297174/96b3b69a-1928-11e5-809c-dde186ae1d10.jpg)

To me it seems like only the top-left 1920x1080 section of the screen is showing the UI?

The issue does not present itself when the resolution is set to 1920x1080 on the same machine: 
![2015-06-22_00004](https://cloud.githubusercontent.com/assets/680229/8297312/f6846564-1929-11e5-9b59-e8d83c3b52f1.jpg)

**Comment by Plagman** [comment]
Does the issue also happen in windowed or borderless windowed mode, or is it specific to fullscreen?

**Comment by tstarboy** [comment]
The full UI loads in borderless windowed, but the map does not entirely fill its region:
![2015-06-22_00005](https://cloud.githubusercontent.com/assets/680229/8297344/789b1048-192a-11e5-9e9f-eb5e0902ec98.jpg)

**Comment by gankbanger** [comment]
Got the same issue on all three modes: Fullscreem, Windowed and Borderless.

NVidia GTX570, 331.113 drivers. Linux Mint 17.1 Cinnamon.

**Comment by computerquip** [comment]
I'm using an Nvidia GTX 770 with proprietary driver 352.21 and I do *not* have this issue. 
I'm using an up to date Arch Linux, which is unfortunately not useful here. ;/ Still, shows that it's not a driver issue.

**Comment by xfalcox** [comment]
This doesn't happen to me. Using kubuntu 15.04, dual monitors (2560x1440 with dota and one 1920x1080 in portrait) full screen. Gtx 780 and tried both 340 and 352 drivers.

One thing to note I have disabled kde compositor.

**Comment by gdrewb-valve** [comment]
Does the 6/26 update improve this?

**Comment by tstarboy** [comment]
No. The UI is now broken in borderless windowed, and the fullscreen option is gone entirely. 
![2015-06-27_00001](https://cloud.githubusercontent.com/assets/680229/8393194/e23ffba2-1cd2-11e5-97ca-e6e8a3d99ae3.jpg)
![2015-06-27_00002](https://cloud.githubusercontent.com/assets/680229/8393195/e246f61e-1cd2-11e5-9768-dc80d58b6bfb.jpg)
![2015-06-27_00003](https://cloud.githubusercontent.com/assets/680229/8393196/e2546150-1cd2-11e5-89ee-c5bc9f2496e3.jpg)

**Comment by gdrewb-valve** [comment]
OK, thanks.  The removal of the fullscreen option is deliberate (it was a borderless window anyway).

**Comment by danginsburg** [comment]
Did the 6/30 update fix this problem?

**Comment by tstarboy** [comment]
The UI is fixed, but the map is not.
![2015-07-02_00002](https://cloud.githubusercontent.com/assets/680229/8490147/42962b20-20f2-11e5-8a24-a1cb074acec9.jpg)
![2015-07-02_00001](https://cloud.githubusercontent.com/assets/680229/8490148/4298dd34-20f2-11e5-8218-c56d7857665a.jpg)

**Comment by danginsburg** [comment]
@tstarboy Are you still seeing the minimap sized incorrectly?

**Comment by tstarboy** [comment]
Yes.
![2015-07-15_00001](https://cloud.githubusercontent.com/assets/680229/8713460/ce2ee084-2b36-11e5-97b4-e8594e431d2b.jpg)

**Comment by danginsburg** [comment]
@tstarboy I am unable to repro this on a 2560x1440 monitor.  Can you please post precise repro instructions?  Please include your exact multi-monitor config, your in-game resolution settings, which monitor you run on, and what exactly you do to trigger the minimap bug.

**Comment by tstarboy** [comment]
It appears that the issue has been fixed in the patches since I last tried.
![2015-08-24_00002](https://cloud.githubusercontent.com/assets/680229/9450189/44ab7436-4a75-11e5-8b59-1063e253557e.jpg)

My apologies for not reporting this earlier (I do not actually play Dota myself).
