### ISSUE TITLE
OS X: Corrupt text in-game

### ISSUE THREAD

**Issue by yaakov-h** [ValveSoftware/Dota-2#20]
![screen shot 2015-06-23 at 2 58 38 pm](https://cloud.githubusercontent.com/assets/426009/8300384/843a289c-19c7-11e5-9a72-c4d75180718f.png)

MacBook Pro (Retina, 13-inch, Late 2013) / MacBookPro11,1
OS X Yosemite Version 10.10.3 (14D136)

```
Intel Iris:

  Chipset Model:    Intel Iris
  Type: GPU
  Bus:  Built-In
  VRAM (Dynamic, Max):  1536 MB
  Vendor:   Intel (0x8086)
  Device ID:    0x0a2e
  Revision ID:  0x0009
  Displays:
Color LCD:
  Display Type: Retina LCD
  Resolution:   2560 x 1600 Retina
  Retina:   Yes
  Pixel Depth:  32-Bit Color (ARGB8888)
  Main Display: Yes
  Mirror:   Off
  Online:   Yes
  Built-In: Yes
```

**Comment by unrealhoang** [comment]
Same problem, this seems to happen with Retina Display

**Comment by mkocs** [comment]
@unrealhoang not only on Retina. I have a resolution of 1280x800 on my MacBook and I have this problem too.

**Comment by albingeorge** [comment]
I am having the same issue with 1280x800 on my Macbook pro. But I could not confirm that this issue is related to #51 as @unrealhoang have mentioned above. Since this issue was happening with bot match, I was pretty sure the same would happen with a live match. I wish there was a way to confirm this without  getting stuck in low-priority pool.

**Comment by yzlnew** [comment]
Same problem on my MD101 with OS X EI Captain beta 2.

**Comment by danginsburg** [comment]
This is a manifestation of the same problem as #4.  A fix has been put in and it will be in the next release.

**Comment by khaschuluu** [comment]
:arrow_up:
Same problem in linux
Ubuntu 14.04 LTS 64-bit
5.4 GiB Memory
Intel Core i3-2328M 2.20GHz × 4 CPU
Intel Sandybridge Mobile Graphics

**Comment by ghost** [comment]
Hi @khaschuluu did this problem fix for you? I have the problem same in Debian Jessie.

**Comment by danginsburg** [comment]
@khaschuluu If you can upgrade to mesa 10.5.9+ it will fix the issue on Sandybridge.  You can use the xorg-edgers ppa or oibaf ppa if you are daring.

**Comment by khaschuluu** [comment]
@el4tomo no. If I did, I'll notice you ;)
@danginsburg thank you for your reply. I can't install mesa in my system caused package dependencies problem. And when I tried to install from source code, problems was appears that I can't fix. I need to upgrade my system version to Ubuntu 14.10 or higher, I guess. Wasting time on that.

**Comment by ghost** [comment]
@danginsburg Any other workaround? I am having the same text problem in Kali GNU/Linux 2.0 (Debian) and mesa 10.5.9 is not available in wheezy AFAIK.
System Details:
Kali GNU/Linux 2.0 (sana) 64-bit
7.7 GiB Memory
Intel Core i5-2450M CPU @ 2.50GHz × 4 
Intel Sandybridge Mobile
