### ISSUE TITLE
Heroes tab will spin the heroes selection non stop

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#200]
Tittle says it all, can't select hero, it keeps spinning on its own.

System Information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.6-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.21
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x     
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7874 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  882448 Mb
    Largest Free Hard Disk Block:  482448 Mb

**Comment by gdrewb-valve** [comment]
Possibly the same input problem as #198.

**Comment by budimanjojo** [comment]
Should I put the console log here? Or how can I help?

**Comment by gdrewb-valve** [comment]
I'm not sure the console log will show anything but go ahead and post it.

For some reason your system appears to be getting spurious input (at least Reborn thinks that), I'm not sure what would cause that.  I don't see anything unusual in your system specs.  Does the Source 1 version of Dota 2 work?  You're using the Steam runtime?

**Comment by budimanjojo** [comment]
Here's the log:
CSosOperatorSystem::StarSoundEvent Unable to find soundevent focus_change_fail
CSosOperatorSystem::StarSoundEvent Unable to find soundevent focus_change_fail
CSosOperatorSystem::StarSoundEvent Unable to find soundevent focus_change_fail
Source 1 version runs good, using steam runtime.
Btw I can't copy paste from the console to browser (here), another bug?

**Comment by gdrewb-valve** [comment]
That's most likely a side effect of the input issue in that phantom input is probably trying to do UI operations that are failing and causing error sounds.

In the full console log are there any messages that look like errors or failures?  Anything that might relate to the input situation?

**Comment by budimanjojo** [comment]
That message is spamming the console all the time, no other message beside it.
Another thing I just found, the chat wheel problem only happens on fullscreen, borderless window fixed the chat wheel problem, but the heroes tab is spinning on whatever condition unless I press the Settings button and exit the Settings menu.

**Comment by gdrewb-valve** [comment]
There is no fullscreen option on Linux, how are you selecting it?

**Comment by budimanjojo** [comment]
Use desktop resolution, it is basically fullscreen in my system with that option

**Comment by gdrewb-valve** [comment]
So really it's desktop-sized vs. non-desktop-sized?  The size of the window shouldn't matter but it's good to know the differing cases.

**Comment by budimanjojo** [comment]
Desktop sized, monitor is 1920x1080, resolution is 1920x1080 if that's what you mean

**Comment by budimanjojo** [comment]
Now I think I know what's causing the problem, it's my mouse.
When I tried disconnecting the mouse from the system, the error log in the console stopped.
Then I try reconnecting it again, the console shown something like "joystick connected" and then the error log spams again.
So maybe the issue is because Dota 2 Reborn recognize my mouse as a joystick.
Then I remembered that I have a "-nojoy" launch option set. I launch dota 2 without the -nojoy option and the error log spamming is gone and the heroes tab stops spinning. So this issue is gone.
But the other issues (chat wheel going left all the time and high cpu usage) are still there, so they are unrelated.
BTW my mouse is A4TECH X7

**Comment by budimanjojo** [comment]
I don't know if this will get fixed because it's all because of my mouse detected as joystick and I already made an udev rule to tell the kernel it is not a joystick and tried re adding the -nojoy launch option without having this similar issue anymore. You can close this issue if you think this is not Dota 2 problem, gdrewb

**Comment by gdrewb-valve** [comment]
It's not possible to say if it's a Reborn problem or not since we don't know exactly what's causing the spurious input.  It could be your mouse, it could be the system's handling of your mouse or it could be Reborn's handling.  At some point we'd have to track down such a mouse and try and isolate the issue.  That's not likely to happen any time soon but I'll leave this issue open.

**Comment by budimanjojo** [comment]
Have you guys try connecting to a real joystick and see if that issue happen? Or it only happen on my mouse? I don't have other mouse to try, sorry

**Comment by gdrewb-valve** [comment]
I don't know that anybody has specifically tried to repro your problem but I assume the larger team has done some joystick testing.  At some point we will track down a joystick and give it a shot.

**Comment by budimanjojo** [comment]
I think this issue is fixed as it's no longer happen even if I don't have the udev rule. Closing
