### ISSUE TITLE
Dota is not starting after the continuum conundrum update "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by aghoz-i** [ValveSoftware/Dota-2#2004]
#### Your system information

* System information from steam: [here](https://gist.github.com/aghoz-i/1b79b7b94d17c532371284bba1d47e25)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 is not starting after the latest update (aghanim's labyrinth the continuum conundrum).
Running `./dota.sh` on terminal gives this output:
```
./dota.sh: line 109: 30642 Illegal instruction     (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
Dmesg gives this output:
```
[10232.832637] traps: dota2[30435] trap invalid opcode ip:7f9ff39da490 sp:7ffd2ffdb900 error:0 in libtier0.so[7f9ff38ec000+227000]
[10748.960226] traps: dota2[30538] trap invalid opcode ip:7fbae1fb8490 sp:7ffed75e6440 error:0 in libtier0.so[7fbae1eca000+227000]
[10929.990243] traps: dota2[30642] trap invalid opcode ip:7fccba528490 sp:7ffc2b2a9d40 error:0 in libtier0.so[7fccba43a000+227000]
```
Tried deleting `libtier0.so`, and then verifying the game files to download it again (i thought maybe it was corrupted), but the problem still there.
I usually use `-gl` launch options, but i also tried `-vulkan` launch option to see if this fix the problem, and unfortunately it didn't.

#### Steps for reproducing this issue:

1. Starts Dota 2 by pressing "Play" button on Steam client, or by running `./dota.sh` on terminal.

**Comment by kisak-valve** [comment]
Hello @aghoz-i, this issue is already being tracked at #2003. Since your issue report also has some information to ponder, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Dota-2/issues/2003#issuecomment-994835679.
