### ISSUE TITLE
[Linux] Reliably low FPS (Arch Linux, i7-4760HQ Haswell mesa 10.6.1)

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#201]
I'm running on Arch with Mesa 10.6.1 on an i7-4760HQ (Haswell), using the integrated graphics. In Source 1, I reliably get full frame rates, but in Reborn, I get a maximum of about 22fps (including in hero selection), dropping down to single digits whenever anything interesting happens on screen, completely independent of quality settings and whether compositing is enabled. CPU usage is low. The update discussed in #53 does not appear to have fixed this for me.

I'm using KWin 4.11.21 in both compositing and non-compositing mode and the standard Mesa Intel drivers for the integrated GPU.

**Comment by danginsburg** [comment]
What do you see when you do: 

```
watch -n1 "lscpu | grep 'MHz' | awk '{print $1}'"
```

I'm testing on a i7-4770R CPU and depending on the CPU frequency my framerate varies from 45fps -> 120fps.  I tend to disable cpu frequency scaling when I am benchmarking.

**Comment by gdrewb-valve** [comment]
Also can you try disabling the Steam overlay and seeing if that affects your FPS?

**Comment by chrylis** [comment]
@gdrewb-valve I've already had the overlay disabled.

@danginsburg Looks like I have a different `lscpu`, because your awk expression didn't get anything useful for me. Just watching without it, I have a hardware min/max of 800/3300 (presumably including Turbo). During launch, lobby UI, loading, and the 20fps bot match, I'm reliably using about 50% load on one core at 2.1-3.0GHz, which is less than Firefox routinely grabs.

**Comment by chrylis** [comment]
I tried the latest update, and the problem is now even worse; with high quality settings (the equivalent of what I normally play Source 1 at), I get a max of 18fps. Turning the video quality to minimum gets me to 50-60fps with graphics that look something like Super NES.

**Comment by chrylis** [comment]
With compositing disabled, the latest version doesn't look like a flipbook but is still barely playable (around 30fps).

**Comment by danginsburg** [comment]
@chrylis So if I follow, you are saying that framerate has increased from 18fps -> 30fps at max settings with the latest update, but you still find this to be unplayable?  What are you getting in source1 at the same resolution at max settings?

**Comment by chrylis** [comment]
30fps is playable, just barely so, and that's with significantly lower settings than I have in Source 1, where I'm getting around 60. I have also frequently experienced major frame rate dropoffs when things get busy (exactly when you need responsiveness), ~~but I haven't encountered that yet with the latest update~~ and I've had the rate get down to 7fps in a teamfight.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
