### ISSUE TITLE
after many games, icons get shifted

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#2014]
After many games, the icons get shifted: see the URL with the screenshot, in the bottom right, look at the icons of boosters.

**Comment by sylware** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2729838302

https://steamcommunity.com/sharedfiles/filedetails/?id=2729838105

**Comment by sylware** [comment]
I don't see that happening anymore

**Comment by kisak-valve** [comment]
Closing per the last comment.
