### ISSUE TITLE
Nyx Assassin 3D-model causes the game to crash on Vulkan

### ISSUE THREAD

**Issue by starwavex** [ValveSoftware/Dota-2#2016]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/starwavex/34498b1c22af9a2c346ac69c414b8c15
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes, multiple times
* Additional comment: No performance issues during the gameplay - iGPU works very well!

#### Please describe your issue in as much detail as possible:
Nyx Assassin 3D-model (or something closely related to it) causes the game to crash specifically on Vulkan. This happens everywhere: in heroes menu (just right after selecting Nyx Assassin), matchmaking, replays, etc.

I found and successfully reproduced that bug after a match in which the game was continuously crashing on each attempt to connect to the match. I asked my friend to share the replay ID to investigate if any playable hero 3D-model causes the game to crash, and then out of 10 the only one guilty was Nyx. I also checked all heroes for this issue - no one else is affected by the bug except Nyx.

By guessing I discovered that this issue can be temporarily "fixed" by deleting `[steam folder]/steamapps/shadercache/570/fozpipelinesv6/steam_pipeline_cache.foz`
This would work until Steam repeats "Processing Vulkan shaders". After that, the crashing would happen again if Nyx model is loaded anywhere.

This issue DOESN'T occur on OpenGL rendering API. It does only on Vulkan.

I hope this information could be useful.
On your request, I could provide detailed crash dumps of the game from `/tmp/dumps`.

#### Steps for reproducing this issue:
1. Start Dota with Vulkan, wait till processing Vulkan shaders finish (or do `shader_build 570` in steam console)
2.
- Select Nyx Assassin in heroes menu 
OR
- Select a replay with this hero
OR
- Try to play a match in which one of the players selects Nyx

3. Experience game crashes.

**Comment by kisak-valve** [comment]
Hello @starwavex, please update to mesa 21.3.5 (or newer) and retest. Specifically for [this shader cache fix](https://cgit.freedesktop.org/mesa/mesa/commit/?h=21.3&id=f15d2c8d3a2b37d57fe2f018dd4566bfde9b31bb) in the video driver.

**Comment by starwavex** [comment]
Hello @kisak-valve. I upgraded `mesa` to the latest. Spent some time mixing "crash conditions" to test. Seems like Nyx 3d-model doesn't crash the game anymore.

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as a video driver issue which has been fixed on their side.
