### ISSUE TITLE
140mb update from 31.1.2022 breaks linux compatibility?

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#2017]
hi,
Just downloaded the patch and now I get this when I try to start dota 2:

![screen04](https://user-images.githubusercontent.com/5174562/151881843-e9c7d7ca-7edb-4632-a440-5de51da58701.png)

Apparently it is trying to use wine to launch dota2? After pressing continue I got a notice that it is downloading a linux environment and then it got stuck on the launching game screen.

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Turmfalke2/c773dd49a0553b201b6b83303f6bbd2f
* Have you checked for system updates?: no
* Are you using the latest stable video driver available for your system? no
* Have you verified the game files?: no

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, if you go to the game and click the ⓘ button on the right side, does it have a line with `Runs on this computer via Steam Play. Steam Linux Runtime selected by Valve testing.`? This goes along with the Linux Runtime Update section of https://www.dota2.com/newsentry/4978168332488878344 and is still a Linux native version of Dota 2. Wine is not being used with that configuration.

Please let Steam finish gathering the extended diagnostics information in the System Information dialog box and update your gist.

**Comment by domadden** [comment]
I was seeing the same thing. I just reinstalled and now I am not getting the steam play prompt. But I'm not sure if that is because I had clicked continue previously or because it is working now.

**Comment by TTimo** [comment]
The message prompt is misleading, please ignore (it only shows once). It is showing because the container runtime for Linux is the same technology that powers Steam Play (and it used to *only* power Steam Play).

Dota 2 is still a native Linux game by default, but the configuration changed to use the container tech in preparation for more upgrades.

**Comment by Turmfalke2** [comment]
> Hello @Turmfalke2, if you go to the game and click the ⓘ button on the right side, does it have a line with `Runs on this computer via Steam Play. Steam Linux Runtime selected by Valve testing.`?   

It does.  

> This goes along with the Linux Runtime Update section of https://www.dota2.com/newsentry/4978168332488878344 and is still a Linux native version of Dota 2. Wine is not being used with that configuration.   

Oh sorry, I thought Steam Play was the marketing name for some patched wine. Especially considering it says platform compatibility.

> Please let Steam finish gathering the extended diagnostics information in the System Information dialog box and update your gist.  

It appears the game is running now. No idea why it got stuck the first time. There was no visible progress. 



Is there any difference I should notice? I assume it now using namespaces instead of the LD_PRELOAD hack?

**Comment by Turmfalke2** [comment]
Long gist if in case it is still desired: https://gist.github.com/Turmfalke2/28a08ae1990fa4165a7dfc8a479ce498

**Comment by kisak-valve** [comment]
Steam Linux Runtime uses pressure vessel to setup a container environment which can be directly compared to Flatpak. I'm not the best person to answer questions in detail about it, but there is a bunch of details at https://github.com/ValveSoftware/steam-runtime/blob/master/doc/possible-designs.md if it interests you.

Closing per the last couple comments.

**Comment by TTimo** [comment]
> Is there any difference I should notice? I assume it now using namespaces instead of the LD_PRELOAD hack?

Yep. Should be no difference.

**Comment by Turmfalke2** [comment]
read the design document, I assume dota 2 is now using "2018 LD_LIBRARY_PATH scout runtime + newer Platform + scout again". Is there anyway to see which one a given game is using and whether home is unshared? I guess I could try writing a file from within the game's console.

E: looks like the game can directly write to my home directory.

**Comment by TTimo** [comment]
@Turmfalke2 if you go to Properties -> Compatibility, it will show 'Steam Linux Runtime' (which is the original/legacy runtime, nicknamed 'scout').

By default we are not isolating the home directory, as that was breaking too many games (I don't know if it breaks Dota 2, we haven't tested that). There is an environment variable in the documentation that you can set to force the home directory to be isolated.

**Comment by Turmfalke2** [comment]
> @Turmfalke2 if you go to Properties -> Compatibility, it will show 'Steam Linux Runtime' (which is the original/legacy runtime, nicknamed 'scout').

It does not, there is an unchecked box for 'force the use of a specific Steam Play compatibility tool'. I assume this is the case because I did not force it my self, but was picked for some A/B testing.

> By default we are not isolating the home directory, as that was breaking too many games (I don't know if it breaks Dota 2, we haven't tested that). There is an environment variable in the documentation that you can set to force the home directory to be isolated.  

I assume this on a per game basis using the launch options. In the docu I only see a mentioned '--unshare-home' parameter, will have a closer look at that tomorrow. Getting late here.

**Comment by Turmfalke2** [comment]
Found it. It was a bit of a goose chase, but I found the environment variable. The possible-design docu doesn't appear to match what was implement. I am still unsure what the difference is between pv-bwrap and pressure-vessel-wrap is. Anyway for everyone else who might be reading this, steam needs to be launched with `PRESSURE_VESSEL_WRAP_GUI=1`. With that there will be an additional gui to modify the container creation when launching dota. 

I did not encounter an obvious crashes related to unsharing home. I have tested:
- launching local aghanim lab
- demo mode
- bot lobby on euw
- downloading custom game 'Overthrow 2.0' from the arcade
- launching a solo lobby of 'Overthrow 2.0'

Custom games always have some issues with loading resources, an old one I tested first even crashed on me after a failed string interpolation when looking up something. I saw a few screens in the Overthrow game that looked like they had missing pictures, but that was also the case with a shared home.  

Overall I would say it looks promising, hope this can be enabled in the future. The option to create a new pid namespace is also intriguing, but I don't see that being realistic in the near future. Making use of a subuid/subgid would also be nice, but at this point I am dreaming.

**Comment by smcv** [comment]
> `PRESSURE_VESSEL_WRAP_GUI=1`

This is an unsupported developer tool which I use to test potential pressure-vessel changes. Good luck! :-)

The changes you can make by using that tool should all be equivalent to setting individual environment variables, and the more direct option to unshare the home directory is `PRESSURE_VESSEL_SHARE_HOME=0`.

Unsharing the home directory is also not really supported at the moment, but in principle it should work (although obviously it will break games that assume they can access the whole of your home directory).

Note that this is a convenience/tidying feature, not a sandbox or a security boundary: there are lots of ways that the game could "escape" if it wanted to. If you don't want to trust Steam and Steam games, I would suggest running them with a separate user account that does not have access to your personal files.

> The option to create a new pid namespace is also intriguing, but I don't see that being realistic in the near future. Making use of a subuid/subgid would also be nice

I would say these are unlikely. The interface between Steam and Steam games assumes that they are in the same uid and pid namespace, and unpicking that sort of assumption without breaking compatibility is really hard to do.

**Comment by Turmfalke2** [comment]
> `PRESSURE_VESSEL_SHARE_HOME=0`

Thanks, launching dota with `PRESSURE_VESSEL_SHARE_HOME=0 %command%` in the launch options works.

> Note that this is a convenience/tidying feature, not a sandbox or a security boundary: there are lots of ways that the game could "escape" if it wanted to. 

I am aware of that, it would still help against someone accidentally running a recursive delete while interpolating an uninitialized variable.

> If you don't want to trust Steam and Steam games, I would suggest running them with a separate user account that does not have access to your personal files.

The issue with that is doing it on a per game basis. I trust some of them more than others. Would be interesting to have some of them run as an ephemeral user, but I am not sure a unprivileged user can do that without the help of namespaces.
