### ISSUE TITLE
[Linux] Size of borderless window is no longer borderless and closes when clicking on a second monitor

### ISSUE THREAD

**Issue by bytes-max** [ValveSoftware/Dota-2#202]
This ones new, within the last patch a bug appeared, where you cannot move your mouse outside of the client without having the client to be minimised. 

A few days ago it was possible to have the client on screen two while clicking around on the screen on monitor one without having the client to be minimised. This now appears automatically.

Please make it possible to have the client available on the monitor even if youre not actively in the client again

**Comment by budimanjojo** [comment]
Try reducing the resolution of the borderless window. As far as I know borderless window with the max resolution of monitor is basically a fullscreen window that isn't placed above the panel or dock. And dota will minimize when you alt tab if it is in fullscreen.

**Comment by bytes-max** [comment]
But it worked fine before. I had a fullscreen window which was able to stay on the very top even if I alt-tab out. This was extremly userfriendly and I remember that the same thing was possible on Windows, too, however, I switched to Ubuntu like 2 years ago.

**Comment by budimanjojo** [comment]
How did you get it fine before? Been playing Dota using Linux for half a year and never get it working.  What's your distro and your desktop environment?

**Comment by bytes-max** [comment]
Note that we are not talking about Source 1, which wasn't able to stay on screen.

Source 2 did it, am on Ubuntu 14.04 with 1920x1050 resolution

**Comment by bytes-max** [comment]
Duplicate #182

**Comment by budimanjojo** [comment]
You mean you're using 1920x1050 resolution borderless on a 1920x1080 monitor? Your Unity dock is on your left monitor and you're playing Dota in your right monitor? I tried it on my system and alt tab worked without minimizing Dota 2 Reborn. But I'm using xfce on Manjaro

**Comment by bytes-max** [comment]
I don’t use Unity, I backed up to Gnome2. Unity is ugly af IMHO. :) 

Von:  budimanjojo
Antworten an:  ValveSoftware/Dota-2-Reborn
Datum:  Freitag, 3. Juli 2015 15:55
An:  ValveSoftware/Dota-2-Reborn
Cc:  Atropos GmbH
Betreff:  Re: [Dota-2-Reborn] [Linux] Size of borderless window is no longer borderless and closes when clicking on a second monitor (#202)

You mean you're using 1920x1050 resolution borderless on a 1920x1080 monitor? Your Unity dock is on your left monitor and you're playing Dota in your right monitor? I tried it on my system and alt tab worked without minimizing Dota 2 Reborn. But I'm using xfce on Manjaro

**Comment by budimanjojo** [comment]
Try setting the Dota 2 settings to 1600x900 borderless and see if it still minimized? It worked for me

**Comment by bytes-max** [comment]
If I do so the borderless Window does not fill out the screen completely thus taking my attention away from Dota2. Not an option to lower the resolution besides fullscreen resolution. 

However, this works and the screen don’t minimize anymore, but thats not what players want (see #182). The new behavior is unwanted, it also worked fine in the revision before. 

Von:  budimanjojo
Antworten an:  ValveSoftware/Dota-2-Reborn
Datum:  Freitag, 3. Juli 2015 15:58
An:  ValveSoftware/Dota-2-Reborn
Cc:  Atropos GmbH
Betreff:  Re: [Dota-2-Reborn] [Linux] Size of borderless window is no longer borderless and closes when clicking on a second monitor (#202)

Try setting the Dota 2 settings to 1600x900 borderless and see if it still minimized? It worked for me

**Comment by budimanjojo** [comment]
I don't know if it worked before. Maybe try setting from the launch option? Use something like this:
-windowed -noborder -w 1919 -h 1079. This way it will "almost" fill out the screen. As a workaround as the developers try to fix it for some time :)
