### ISSUE TITLE
Update on 31.01.2022 broke compability with Linux Mint.

### ISSUE THREAD

**Issue by SleepyKolosLolya** [ValveSoftware/Dota-2#2020]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/SleepyKolosLolya/8c3a881905960a1aa5b7bed30b6335e0
* Have you checked for system updates?: [Yes/No] No
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The game should start but it crashes on launch after 31.01.2022 update (https://www.youtube.com/watch?v=unzGro79Hd8)

#### Steps for reproducing this issue:

To reproduce the crash start the game using `-gl` in args using default runner (without Steam Linux Runtime).

**Comment by kisak-valve** [comment]
Hello @SleepyKolosLolya, `"*** stack smashing detected ***: terminated",` at https://gist.github.com/SleepyKolosLolya/8c3a881905960a1aa5b7bed30b6335e0#file-gistfile1-txt-L2614 and https://gist.github.com/SleepyKolosLolya/8c3a881905960a1aa5b7bed30b6335e0#file-gistfile1-txt-L2650 tells us you've encountered the same issue as https://github.com/ValveSoftware/steam-runtime/issues/420.

Officially, NVIDIA stopped supporting mobile Kepler generation GPUs like yours after the 418.xx driver series, however, some users have had success using the 470.xx driver series, which is the last series to support the desktop variants of Kepler.

Please update your video driver and retest.

Closing in favor of https://github.com/ValveSoftware/steam-runtime/issues/420.
