### ISSUE TITLE
Dota 2 fails in steam on launch but the executable works fine

### ISSUE THREAD

**Issue by sakisaka603** [ValveSoftware/Dota-2#2022]
Your system information

System information from steam :
Computer Information:
    Manufacturer:  Micro-Star International Co., Ltd
    Model:  B450 GAMING PLUS MAX (MS-7B86)
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 3600 6-Core Processor              
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4208 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Garuda Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.16.8-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101003
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce RTX 2060/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 510.47.03
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1f08
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3280 x 1080
    Primary Display Size: 20.79" x 11.69" (23.82" diag)
                                            52.8cm x 29.7cm (60.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: NVIDIA GPU 93 HDMI/DP

Memory:
    RAM:  15983 MB
 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
updated dota and my pc; Booted up dota failed in steam but if I run the raw executable it runs fine with a few stutters and unable to use store and such.

and this is the content in my crash ( I used Kate so if i messed up tell me I will fix):

MDMP§ ö!b`8	q
cJíL¢ðWINEwine-6.3Linux5.16.8-zen1-1-zen(á?HÛcž$ÐÕKà3+_í3+F"=ÜCäKqCäPÛcðôCäPÛcPÛcFšBäð¶Bä"=ÜCä íÿÿÿ?ÿ?hÞù3óµ÷?fÞù3óµþ?%%%%%%%%%%%%%%%%ÿÿÿÿÿÿÿiew: Assertion `_PTR)base & page create_view: As/dlls/ntdll/unixbin\win64\dota2. %shelpUsage:Þ]Âüps"@@@ü©ñÒMb@?SXPFD@ÿÿ`0ûÿÿ0ûÿÿÐðùÿÿ@

**Comment by kisak-valve** [comment]
Hello @sakisaka603, this is the same issue as https://github.com/ValveSoftware/steam-runtime/issues/490.

Running Steam with the Steam runtime disabled is not a supported configuration. Please run Steam with `steam-runtime`. Closing in favor of the older issue report.
