### ISSUE TITLE
Some textures are missing, debuff counter on opponent's head missing (Batrider, Shadow Demon etc)

### ISSUE THREAD

**Issue by ong-andrew** [ValveSoftware/Dota-2#2025]
AFTER 7.31 UPDATE

#### Your system information

* 510 nvidia driver
* Have you verified the game files?: Yes
* Using Vulkan
* Pre-shader content enabled

#### Please describe your issue in as much detail as possible:
PROBLEMS:
1. Missing shadow poison trail.
2. Missing shadow demon counter on top of opponent's head

Video: https://youtu.be/UlsoocbUb0Y

ps. Problem only occurs on Vulkan. OpenGL is ok.

**Comment by danginsburg** [comment]
I have a fix for this, it will be in the next dota update.  Thanks for including the video in the report.

**Comment by danginsburg** [comment]
Update with fix for this has shipped.
