### ISSUE TITLE
Game consistently crashes after ~2 min of gameplay on Steam Deck

### ISSUE THREAD

**Issue by m-liu** [ValveSoftware/Dota-2#2028]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`): [gist](https://gist.github.com/m-liu/05fe9c406961d8bf08a60c6e48bf9d43)

* Have you checked for system updates?: [Yes/No]
Yes

* Are you using the latest stable video driver available for your system? [Yes/No]
Yes

* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Game crashes ~2 minutes in on the Steam Deck. Tried both openGL and Vulkan. Tried several different game modes. They all crash at around the 2 min mark. 

Crashdump: [crashdump.tar.gz](https://github.com/ValveSoftware/Dota-2/files/8150926/crashdump.tar.gz)

#### Steps for reproducing this issue:

1. Launch the game
2. Play solo with bots
3. Wait about 2 minutes -> crash

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV coming from steamclient.so.

**Comment by m-liu** [comment]
This appears to be fixed with the latest system update

**Comment by danginsburg** [comment]
Thanks for following up, yes we shipped a Steam Deck system update with the fix.
