### ISSUE TITLE
Latency since recent update

### ISSUE THREAD

**Issue by cppcooper** [ValveSoftware/Dota-2#2029]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
https://gist.github.com/cppcooper/abc99a93786bad45ff47b70fe4cc5c6d
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
```
local/glu 9.0.2-2
    Mesa OpenGL Utility library
local/lib32-glu 9.0.2-2
    Mesa OpenGL utility library (32 bits)
local/lib32-mesa 21.3.7-1
    An open-source implementation of the OpenGL specification (32-bit)
local/lib32-opencl-mesa 21.3.7-1
    OpenCL support for AMD/ATI Radeon mesa drivers (32-bit)
local/mesa 21.3.7-1
    An open-source implementation of the OpenGL specification
local/mesa-demos 8.4.0-7
    Mesa demos
local/mesa-utils 8.4.0-7
    essential Mesa utilities
local/opencl-mesa 21.3.7-1
    OpenCL support for AMD/ATI Radeon mesa drivers
```
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Since an update last week (22-02-26 I think) I've been experiencing huge fps spikes that prevent normal play. I may have performed a system upgrade `pacman -Syu` around the same time, I have certainly done so since though and I've recently switched from pulseaudio to pipewire. The problem affects not just the dota client but my entire system, everything I do while dota is open has a great deal of latency added.

Inside dota the lag often is accompanied by console lines `CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.` Not always though. Here is a gist of my console output from opening dota and typing this issue message: https://gist.github.com/cppcooper/1cf930e663c3c32fd9de86d6a2182d5c

The problem persists on any graphical settings low, high, medium, windowed. I haven't tested on vulkan.. primarily because dota does not launch with vulkan enabled (vulkan packages installed, vulkan support enabled).

Latency on my system disappears immediately upon closure of dota.

#### Steps for reproducing this issue:

1. Launch dota

**Comment by TTimo** [comment]
Hello @cppcooper,

Your system information suggests you have disabled the steam runtime (possibly by selecting Arch's "native runtime" version of Steam, which unsupported by Valve).

Please see if you can reproduce this issue when Steam is running in the official 'scout' runtime configuration.

**Comment by cppcooper** [comment]
Just tried both, and there was no difference between the two. Although the other day I had run dota, and it was massively better than what I just experienced (I had trouble actually closing the game). The other day I had run the game after a fresh reboot, today about an hour after waking from sleep; I don't know if that's related I haven't verified.. just sharing info. I must note though that while the other day it was better, there was still micro lag stuttering the fps from 150-200 down to 30-50 every so often. Today I didn't get far enough to see what the FPS was as I was still in the main menu and it felt like single digits.

**Comment by cppcooper** [comment]
I'll test further, but the issue appears to have been rooted with a bug in kde that has been patched. I'll close the issue in a few days after I've had a chance to test.

**Comment by cppcooper** [comment]
Ok, maybe not.. or it was and there is a less severe problem as well. I just played a match and the fps wasn't great, but it was playable. FPS was about 30-50 average probably was closer to 50. It looked like it was some sort of network thread locking issue here are the logs: https://gist.github.com/cppcooper/5d45db01e079ece77bd058aae3bbdcb5

**Comment by cppcooper** [comment]
Seems like the recent update fixed the spikes
