### ISSUE TITLE
libnotify desktop notifications no longer being sent from Dota

### ISSUE THREAD

**Issue by stahara** [ValveSoftware/Dota-2#2031]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/stahara/04f415e89a9a2826ca1c49a8746960dc
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Expected: libnotify/notify-send notifications for party invite, ready check, game ready, and game unpausing events.
Actual: None of these events are sending notifications anymore.

#### Steps for reproducing this issue:

1. Queue for matchmaking
2. Switch to another virtual desktop to do work/browse internet/shop the Steam Store
3. Switch back to Dota and weep upon realizing that you've failed to accept yet another game due to the lack of a notification >8*(

**Comment by TTimo** [comment]
this is a container runtime fix - tracked here: https://gitlab.steamos.cloud/steamrt/tasks/-/issues/98

**Comment by stahara** [comment]
Thanks!  However, the issue link returns a 404.

**Comment by TTimo** [comment]
sorry about that - I thought this was one of our public trackers. in any case - thanks for the report, we're tracking this

**Comment by stahara** [comment]
Great!  Thank you very much.  I love this feature and really did rely on it heavily when it was working.

**Comment by smcv** [comment]
This hopefully works again with today's new beta of the "Steam Linux Runtime - Soldier" container runtime (in a fixed version, `SteamLinuxRuntime_soldier/VERSIONS.txt` will say `depot 0.20220329.31` or later).

[How to use a Steam container runtime beta](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version)

**Comment by stahara** [comment]
It works!  THANK YOU!

**Comment by smcv** [comment]
@TTimo has promoted beta 0.20220329.31 to stable, so I think this issue can be closed now.
