### ISSUE TITLE
Client freezes after the game

### ISSUE THREAD

**Issue by zub0r** [ValveSoftware/Dota-2#2036]
When I switch between tabs like graphs, player items after the game, the client always freezes after recent updates.
Needs to be killed with -9

<details>
<summary>System info</summary>
<br>

```
Computer Information:
    Manufacturer:  Gigabyte Technology Co., Ltd.
    Model:  B450 I AORUS PRO WIFI-CF
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 1600X Six-Core Processor           
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 20.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-94-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12013000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20211207.0

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 460.91.03
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c81
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.75" x 11.65" (23.78" diag)
                                            52.7cm x 29.6cm (60.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 80 HDMI/DP

Memory:
    RAM:  16015 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  sk_SK.UTF-8
    Total Hard Disk Space Available:  225212 MB
    Largest Free Hard Disk Block:  7281 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

```

</details>

**Comment by pwiecha** [comment]
Same here but randomly every 3-4 games on a random post-game tab. @kisak-valve is there a dota option to store game log somewhere so we can track what happens before crash?

**Comment by kisak-valve** [comment]
Hello @pwiecha, I'm not really familiar with the debug options of Dota 2, but maybe try `-condebug` in the game's launch options and check the game folder for `console.log`?

**Comment by kisak-valve** [comment]
Ubuntu Linux post-game screen Player Items tab crash

Issue transferred from https://github.com/ValveSoftware/Dota-2/issues/2067.
@WillMatthews posted on 2022-06-12T05:51:17:

This issue has been moved from jeffhill/dota2 to here as I believe it is Linux-specific.

Dota 2 consistently crashes when clicking on clicking "Player Items" in the graphs tab when looking at a past match's 'postgame view'. Sometimes it occurs when changing tab out of the player items tab.

Both my system (18.04, detailed below) and my friend's system (20.04) have this problem, we both have multiple display configurations but different window managers (GNOME for me, XMonad for him). Both systems use NVidia.

The game freezes and I have to send a SIGKILL to it for it to close, it's totally unresponsive to anything else.

If there's anything else I can add please let me know, many thanks.

OS: Ubuntu 18.04.6 LTS x86_64
Kernel: 5.4.0-107-generic
Uptime: 11 days, 18 hours, 44 mins
Packages: 3495
Shell: zsh 5.4.2
Resolution: 1920x1080, 1920x1080
DE: GNOME 3.28.4
WM: GNOME Shell
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Ubuntu-mono-dark [GTK2/3]
Terminal: x-terminal-emul
CPU: AMD Ryzen 5 3600X 6- (12) @ 3.8
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 24473MiB / 32036MiB

**Comment by kisak-valve** [comment]
Changing between post game summary tabs crashes the game

Issue transferred from https://github.com/ValveSoftware/Dota-2/issues/2079.
@tom-bird posted on 2022-06-23T10:08:45:

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/tom-bird/f07518b28593a11d05bb19714892a330
* Have you checked for system updates?: No
* Are you using the latest stable video driver available for your system? Don't think so, but it will be closeish
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
In the post game screen, if I switch from the performance to the graph tab then dota freezes and becomes unresponsive. I have to kill the process via terminal to even get it to close, closing it through steam does not work (there is always one process that lives on).

The issue does seem specific to the those tabs - I can browse the other tabs fine. In fact I think it is specific even to the order in which you go between them! I think it is performance -> graph only that causes it to crash, pretty weird.

Also, it doesn't always happen when switching between the tabs. If I go to an old match summary and click around between the tabs then I can go usually go from performance -> graph, but as I click around at some point relatively quickly it will crash, and always on the transition between performance and graph. It may also require you to change quickly from performance to graph, clicking in relatively quick succession, although I am not certain about this.

#### Steps for reproducing this issue:

1. Go to a post game screen (doesn't have to be straight after the game)
2. Open performance tab and then try and (maybe quickly) open the graph tab (might have to click around between the tabs for a little bit)

**Comment by tdgroot** [comment]
I am experiencing the same issues when going to the graphs in the post game overview and enabled the debug logging. For what it's worth, here's the logging when I experience such issues:
```
...
06/25 17:00:39 [GCClient] Recv msg 8689 (k_EMsgGCToClientAccountGuildEventDataUpdated), 20 bytes
06/25 17:00:39 [GCClient] Send msg 8713 (k_EMsgClientToGCRequestActiveGuildChallenge), 23 bytes
06/25 17:00:39 [GCClient] Send msg 7078 (k_EMsgGCSubmitPlayerReport), 36 bytes
06/25 17:00:40 [GCClient] Send msg 7078 (k_EMsgGCSubmitPlayerReport), 36 bytes
06/25 17:00:40 [GCClient] Recv msg 8714 (k_EMsgClientToGCRequestActiveGuildChallengeResponse), 39 bytes
06/25 17:00:41 [GCClient] Recv msg 7388 (k_EMsgDOTAGetEventPointsResponse), 206 bytes
06/25 17:00:41 [GCClient] Recv msg 7388 (k_EMsgDOTAGetEventPointsResponse), 206 bytes
06/25 17:00:42 [GCClient] Recv msg 26 (k_ESOMsg_UpdateMultiple), 244 bytes
06/25 17:00:42 [GCClient] Recv msg 7079 (k_EMsgGCSubmitPlayerReportResponse), 27 bytes
06/25 17:00:42 [GCClient] Recv msg 26 (k_ESOMsg_UpdateMultiple), 244 bytes
06/25 17:00:42 [GCClient] Recv msg 7079 (k_EMsgGCSubmitPlayerReportResponse), 27 bytes
06/25 17:01:07 [GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
06/25 17:01:07 [GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
06/25 17:01:07 [GCClient] Recv msg 26 (k_ESOMsg_UpdateMultiple), 303 bytes
06/25 17:01:07 [GCClient] Send msg 7272 (k_EMsgGCLeaveChatChannel), 13 bytes
06/25 17:01:08 [GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
06/25 17:01:09 [GCClient] Recv msg 8747 (k_EMsgGCToClientGuildMembersDataUpdated), 33 bytes
06/25 17:01:13 [GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
06/25 17:01:13 [GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 327 bytes
06/25 17:01:37 [GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
06/25 17:01:37 [GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
06/25 17:01:40 [GCClient] Send msg 8268 (k_EMsgProfileRequest), 22 bytes
06/25 17:01:40 [GCClient] Send msg 7521 (k_EMsgClientToGCGetAllHeroProgress), 22 bytes
06/25 17:01:41 [GCClient] Recv msg 8269 (k_EMsgProfileResponse), 590 bytes
06/25 17:01:41 [GCClient] Recv msg 7522 (k_EMsgClientToGCGetAllHeroProgressResponse), 77 bytes
06/25 17:01:56 [GCClient] Send msg 7274 (k_EMsgGCGetHeroStandings), 8 bytes
06/25 17:01:56 [GCClient] Recv msg 7275 (k_EMsgGCGetHeroStandingsResponse), 1422 bytes
06/25 17:02:00 [GCClient] Send msg 8082 (k_EMsgGCGetHeroStatsHistory), 10 bytes
06/25 17:02:01 [GCClient] Recv msg 8083 (k_EMsgGCGetHeroStatsHistoryResponse), 106 bytes
06/25 17:02:13 [Filesystem] Unknown read error 21
06/25 17:02:13 [ResourceSystem] Error loading resource file "panorama/images/items/dota_base_ability_png.vtex_c" (Error: ERROR_FILEOPEN: File not found)
06/25 17:02:13 [ResourceSystem] Error loading resource file "panorama/images/spellicons/dota_base_ability_png.vtex_c" (Error: ERROR_FILEOPEN: File not found)
06/25 17:02:14 [GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
06/25 17:02:14 [GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 330 bytes
06/25 17:02:26 CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
06/25 17:02:26 [RenderSystem] FrameSync() - bailing out of vkWaitForFences( fenceCount = 1 ) after 0.250003 seconds, error = VK_TIMEOUT
06/25 17:02:27 CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
06/25 17:02:27 [RenderSystem] CSwapChainVulkan::SwapBuffers(): the main thread is more than 3 frames ahead which means no swap queue images are available.  Waiting for outstanding frames...
06/25 17:02:27 [RenderSystem] FrameSync() - bailing out of vkWaitForFences( fenceCount = 2 ) after 0.250003 seconds, error = VK_TIMEOUT
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueSubmit( pQueue, 1, &submitInfo, pFence->Get() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueSubmit( VulkanQueue(), 1, &submitInfo, presentFence.m_pFence ) )
06/25 17:02:27 [RenderSystem] FrameSync() - bailing out of vkWaitForFences( fenceCount = 3 ) after 0.000001 seconds, error = VK_ERROR_DEVICE_LOST
06/25 17:02:27 [RenderSystem] CSwapChainVulkan::SwapBuffers(): the main thread is more than 3 frames ahead which means no swap queue images are available.  Waiting for outstanding frames...
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] CSwapChainVulkan::SwapBuffers(): waited for 0.51 seconds
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
06/25 17:02:27 [RenderSystem] ERROR! VK call failed! result = VK_ERROR_DEVICE_LOST ( vkQueueWaitIdle( VulkanQueue() ) )
...
```

And then it keeps on logging that `VK_ERROR_DEVICE_LOST` message, but I think the errors that take place before that specific message are particularly interesting.

**Comment by WillMatthews** [comment]
Did some more testing - the game client crashes after you exit the player items tab and click on xp, net worth or level tags, it does not crash if you change to scoreboard, overview etc.

**Comment by Bronsky** [comment]
This happens to me in Debian Sid, and also when trying to set the Fantasy League, not sure if it's related

**Comment by WillMatthews** [comment]
> the game client crashes after you exit the player items tab

I noticed that this is not strictly true. sometimes it crashes on click of the player items tab.


> This happens to me in Debian Sid, and also when trying to set the Fantasy League, not sure if it's related

This probably is related - I'm starting to think it's a Vulkan issue but I'm struggling to make any progress.

**Comment by WillMatthews** [comment]
I believe this is fixed with the latest patch. Can anyone else check to confirm?

**Comment by kisak-valve** [comment]
Closing per the last comment.
