### ISSUE TITLE
[Linux] Game freezes occasionally for few seconds

### ISSUE THREAD

**Issue by dhiru1602** [ValveSoftware/Dota-2#204]
**My PC Specs**
Intel Core I7 920 3.5Ghz
16GB RAM
Nvidia 9600GT 1GB
Arch Linux with 4.0.7 kernel
Nvidia Proprietary 340xx (340.76-10) GPU driver

I have occasional game freezes which range from 2 seconds to upto 10 seconds while playing with bots or players. It's not just the game, but my whole system appears to be freezing. Checking the dmesg, I get the following:

<4>[107525.637702] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107527.638283] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107530.744332] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107532.744912] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107534.806754] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107536.807336] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107539.178012] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107541.178591] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107553.849461] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107555.850044] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107584.980659] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107586.981240] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107600.849068] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107602.849648] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107623.929385] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
<4>[107625.929970] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context

I have done a GPU Stress test to rule out any possible issues with GPU overheating and power supply. Furthermore, I haven't had this issue with Dota 2 even when I have played at maxed settings. I have dual booted windows and Dota 2 Reborn works perfectly fine, but I am unable to play the game on Linux.

**Comment by gdrewb-valve** [comment]
Seems like a message related to the NVIDIA driver.  If you update the NVIDIA drivers to version 352 does it still happen?

**Comment by dhiru1602** [comment]
I cannot upgrade to 352 driver because my GPU is supported only by legacy 340xx driver. I have tried the same driver (340) on windows and it works fine. Interestingly, the issue only occurs with Dota 2 Reborn on Linux.

**Comment by gdrewb-valve** [comment]
We're checking with NVIDIA to see what can be done.

**Comment by gdrewb-valve** [comment]
As you know NVIDIA no longer supports your GPU so we're not sure we're going to get anywhere on the driver issue.  We'll leave this open and see if other people are seeing the same thing and maybe we can see some underlying commonality.

**Comment by dhiru1602** [comment]
Thanks for your prompt response. I am suspecting this issue maybe because of the kwin compositor in KDE. I have disabled desktop effects and the game seems to run fine so far. It appears that the compositors vsync handling is not playing well with the game. This is probably related to https://github.com/ValveSoftware/Dota-2-Reborn/issues/205

I will test it more over the next few days and report back. 

**References**
http://www.phoronix.com/scan.php?page=article&item=kde_kwin_effected&num=1
http://steamcommunity.com/app/221410/discussions/0/864960354038123798/

**Comment by phoerious** [comment]
Maybe Dota2 should set _NET_WM_BYPASS_COMPOSITOR=1 to tell the window manager to suspend compositing? Then we don't have to define custom window rules for it.

**Comment by gdrewb-valve** [comment]
http://forums.libsdl.org/viewtopic.php?t=9171&sid=3374c819e18df779e17b4ce5a49fdd15 suggests that SDL may be using this hint already but I'll check with the SDL devs.  I don't believe dota2 would do this directly.

**Comment by dhiru1602** [comment]
Looks like the patch for kwin never got merged. https://git.reviewboard.kde.org/r/110088/

**Comment by phoerious** [comment]
According to Martin's blog post here: http://blog.martin-graesslin.com/blog/2011/04/turning-compositing-off-in-the-right-way/ KWin has such a property. I just don't know if it is exactly this one. But he wrote that he hoped to get his property into the NETWM specification.

**Comment by gdrewb-valve** [comment]
I just heard back from the SDL devs that SDL is setting this should it should be there.  @dhiru1602, are you saying the _NET_WM_BYPASS_COMPOSITOR won't work on KWin?

@Manko10, I see _NET_WM_BYPASS_COMPOSITOR in the freedesktop docs.

**Comment by phoerious** [comment]
Maybe ask Martin Gräßlin about it. He'll be able to answer why it doesn't work and which property KWin uses.

**Comment by dhiru1602** [comment]
@gdrewb-valve The kwin patch for the bypass flag that was submitted to kde was not merged according to https://git.reviewboard.kde.org/r/110088/ . So I think kwin doesn't support the _NET_WM_BYPASS_COMPOSITOR flag which is required to bypass window compositing.

@Manko10  The blog post is quite old and I am not sure how much of the info that Martin provided would hold true today. According to WM specification: http://standards.freedesktop.org/wm-spec/latest/ar01s05.html#idm139870829920368 _NET_WM_BYPASS_COMPOSITOR is a window flag that can be set to notify the window manager to bypass composition for that particular window. kwin **should** support this flag since it's a part of the specification, but I don't think it does. 

I have tested Dota 2 Reborn with xprop and it appears that Dota indeed sets the _NET_WM_BYPASS_COMPOSITOR flag to bypass window composition, but looks like kwin is the culprit here. I always had issues with desktop effects and compositing with kwin when playing dota.

![snapshot16](https://cloud.githubusercontent.com/assets/1326273/8509067/50fc66e4-229f-11e5-9f02-e455fbe9cd41.png)

**Comment by gdrewb-valve** [comment]
Thanks for the detailed investigation.  Sounds like this should be closed?

**Comment by dhiru1602** [comment]
Just a heads up. This issue has been fixed in the 5.20 kwin release.

**Commit:** https://quickgit.kde.org/?p=kwindowsystem.git&a=commit&h=2a5b7943a020f2154049d28a33216149b6220d53

**Bug Report:** https://bugs.kde.org/show_bug.cgi?id=349910
