### ISSUE TITLE
Game crashing on Windows using Nvidia Card.

### ISSUE THREAD

**Issue by buggypos** [ValveSoftware/Dota-2#2041]
#### Your system information

Nvidia GTX 1080ti, i7 4790k, Windows 10 64 bit (10.0.19044 Build 19044), latest Nvidia Drivers (512.15).

#### The issue:
Dota freezes randomly and crashes. It happens under DirectX11 and Vulkan. This doesn't happen on other games. With Vulkan, it seems to be worse (shows artifacts on screen, can actually disable one of my monitors temporarily until I reconnect it etc). I have to alt tab into the task manager and kill the dota process. The computer can become very unresponsive until it's done. If there's monitoring process running (MSI Afterburner, Zotac Firestorm or even the task manager tab that shows resource usage, with the GPU memory use being monitored), then that process also becomes unresponsive until it's killed (in the case of task manager, you have to switch to another tab).

I've tried changing graphics settings (min, max, disable a few), add flags to the initialization (-high, -prewarm etc), remove backgrounds in the autoexec cfg. Reinstall drivers, play on fullscreen instead of borderless window, you name it. Every time the game crashes this way, the Error in Event Log has Event ID 1002 (Application Hang, hang type: top level window is idle).

Steps to reproduce:
1. Play the game, it freezes randomly.

I realize this Github is here for Linux issues, but the actual Dota dev forums are deserted and actually filled with spam by bots (eg https://dev.dota2.com/forum/bugs/performance-technical-support/270848-dota-2-app-crash-no-error). I don't have a reddit account, and even if I did, it doesn't look like anyone would look there either, unless I got lucky. There have been reports for this there too, but the problem persists. I literally cannot play the game and I can't reach Valve in any way, so I'm trying this issue here.

**Comment by kisak-valve** [comment]
Hello @buggypos, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/) for the feedback to reach the larger Dota 2 team.
