### ISSUE TITLE
Mouse Cursor missing if game started in Virtual Desktop A and quickly switched to Virtual Desktop B

### ISSUE THREAD

**Issue by ryuukk** [ValveSoftware/Dota-2#2042]
**OS:** Windows 10 x64

You disabled registration on dev forum, so i am forced to report here

# Reproducer

1. Be in Virtual Desktop A 
2. Open the game
3. Once the icon is in your task bar, switch to Virtual Desktop B
4. Wait a little
5. Go back to Virtual Desktop A
6. Cursor is missing

**Comment by kisak-valve** [comment]
Hello @ryuukk, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com/).
