### ISSUE TITLE
[Linux] menu not fluid and freezes regularly when navigating in the menus

### ISSUE THREAD

**Issue by SlugSleepy** [ValveSoftware/Dota-2#2049]
#### Your system information

* System information from steam => https://gist.github.com/SlugSleepy/ee20e7f74526b76ded0e6c96b7dafd40 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

hello menu not fluid and freezes regularly when navigating in the menus, it goes through the selection of character, the opening of chest, the opening of a tab of the menu or simply to open the parameters of the game.
i made a video showing the problem =>
https://www.youtube.com/watch?v=ciZ7e5ciWG4

the game outside of the menus is extremely fluid, except for the loading which is a little slow and the launching of a game and run perfect at 144 fps.

#### Steps for reproducing this issue:

1. run the games thats all

**Comment by TTimo** [comment]
Hello @SlugSleepy. The system information report is incomplete, please wait for the checks to complete before copying it out.

This could be the same issue as https://github.com/ValveSoftware/Dota-2-Vulkan/issues/406

**Comment by SlugSleepy** [comment]
hello ! i updated my information and yes, it look very similar to my problems !
i also have stuttering/lag/freeze on selection menu, starting game etc 
i didnt know there was a second github for dota !
besides that i forgot mention i use -map dota as command line

**Comment by TTimo** [comment]
closing in favor of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/406
