### ISSUE TITLE
[Linux] Performance drop after toggling between running game and settings

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#205]
When starting Dota2 reborn with disabled compositing in KWin (important, otherwise you don't get a playable framerate!) everything runs smoothly. The whole UI feels quite a bit sluggish, but overall it runs fine with not really amazing but playable 30fps. It's not quite comparable to the old Dota2 in Wine (smooth 60fps) but certainly a lot better than the old native Linux version (unplayable at full resolution).

If I'm in a game, though, and click the arrow button in the upper left corner to toggle between dashboard view and game view and then open the settings, performance drops massively to a constant 6fps.
The only way to fix this is to pause the game and restart Dota.

System information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2801 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xfc6
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  3754419 Mb
    Largest Free Hard Disk Block:  96397 Mb

Installed software:

Recent Failure Reports:
    Fri Jul  3 16:21:40 2015 GMT: file ''/tmp/dumps/crash_20150703181758_1.dmp'', upload no: ''HTTP response code said error''

**Comment by danginsburg** [comment]
Does this happen independent of the resolution you run at?  Independent of video settings (i.e. "Fastest")? With NVIDIA 352.21?

**Comment by phoerious** [comment]
I can't downgrade the graphics driver. But I just tried again with 1920x1080. This is ugly because there is no fullscreen option and now I have a rectangle in the middle of the screen. But it overall doubles the framerate (60 instead of 30fps) and I can't reproduce the issue. So I guess it has something to do with insufficient video memory or so. It should not happen at all, though.

**Comment by danginsburg** [comment]
Does setting Texture Quality "Medium" or "Low" at high res help?  It sounds like what's happening is that textures are being evicted when the full game + the UI is loaded.

**Comment by phoerious** [comment]
I'm messing around with the video settings right now. I'm back at full resolution and with everything turned off and textures to minimum, I get something between 100+ and 80fps.

Now I turn certain effects back on. At 4 effects I notice a slight lag when opening settings, but everything's still fine when going back into the game. But with the 5th option, I always run into the issue above. The only difference low, medium or high textures make is whether I end up with 5, 6 or 10fps.
It also seems like it doesn't matter which 5 options I turn on. I think vsync is one of the worst options (gives me a smooth 60fps on it's own, but seems to introduce lag faster together with other options, might be wrong, though), but overall I can turn on any 5 options to kill the game performance.
Once I'm at that 5fps level, Dota also hangs when exiting to the desktop until I kill it with killall -9 dota2.

**Comment by phoerious** [comment]
Oh, interesting side node I just discovered: while in settings, no matter how many options I have turned on, when I disable and then re-enable vsync and then go back into the game, it seems to restore the framerate from 5 to 60fps.
So the act of opening the settings drops the framerate, but toggling vsync off and back on resyncs it. The game then keeps this framerate until I reopen the settings. I can only do this a few times, though, before I do have to restart anyways.

EDIT: doesn't seem to work reliably. :-\
Also noticed that the framerate drop does not only occur when entering the settings, but also when going to the dashboard's Heroes tab which renders three high-detail hero models.

**Comment by dhiru1602** [comment]
Do you use dual displays? I am seeing the same issue with KDE on Dota 2 and reborn too. I suspect the issue has to do with kwin compositor. Toggling the vsync on or off fixes the issue temporarily without requiring a client restart.

**Comment by phoerious** [comment]
Yes, as you might see from the system information provided above, I use two displays with 2560x1440px each. Dota2 is running on the primary display.

**Comment by gdrewb-valve** [comment]
Important information about the KWin compositor not interacting well with Reborn at #204, this may not be a Reborn issue.

**Comment by phoerious** [comment]
As I said above, I have disabled compositing, so KWin shouldn't interfere with its own OpenGL context.

**Comment by phoerious** [comment]
I got a new motherboard, a new CPU and 8GB more RAM (now 1600 instead of 1333). I upgraded from first-gen Core i7-860 and H57 chipset to a fourth-gen Core-i7-4790K on a Z97 chipset.
Frames now only drop to 30fps instead of 5. Restoring to 60fps by toggling VSync off and back on still works most (or some) of the time.
The issue that Dota hangs on exit until I kill it with killall -9 dota2 still persists.

New system information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xfc6
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2797211 Mb

Installed software:

Recent Failure Reports:
    Fri Jul 10 18:10:08 2015 GMT: file ''/tmp/dumps/assert_20150710200446_19.dmp'', upload yes: ''CrashID=bp-62d2ecbc-9c07-44c5-ae81-410a12150710''
    Fri Jul 10 18:18:28 2015 GMT: file ''/tmp/dumps/assert_20150710201618_47.dmp'', upload no: ''HTTP response code said error''

**Comment by ghost** [comment]
I'm guessing this is the same issue that I have.

When I start the game I get around 150-220 FPS which then drops to 60-90 when I visit the Heroes menu. From there I select a hero and then I use the Demo hero option. In game I have a framerate of 40-60 in general. However, when I open the menu it directly drops to 10-20 FPS. The problem is that the framerate never goes back up when I close the menu. Sometimes it even drops lower if I open the menu again.

The only options I have enabled in advanced video settings is: animate portrait, additive light pass, high quality water and shadows. The texture quality is set to high and game screeen render quality to 100%.

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3200 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.7-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 275/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 340.76
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x5e6
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23,50" x 13,23"  (26,97" diag)
                                            59,7cm x 33,6cm  (68,5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 896 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: AV200

Memory:
    RAM:  7988 Mb

Miscellaneous:
    UI Language:  English
    LANG:  sv_SE.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  114472 Mb
    Largest Free Hard Disk Block:  57383 Mb

Installed software:

Recent Failure Reports:


```

**Comment by Tele42** [comment]
So, if I'm seeing this right, the common trend is 1GB of vram or less. It's possible the game is maxing out the vram and something is getting bumped over to the system ram, which is significantly slower. If that is true, anything to lower the vram usage could improve the behavior being seen.

**Comment by phoerious** [comment]
That would at least explain why my new PC only drops to 30 instead of 5 FPS.

**Comment by phoerious** [comment]
After getting a new mainboard and CPU (as said above) which mitigated the issue a bit, I now also got a new graphics card (GTX 960, 4GB RAM). With this new graphics card, I have no frame rate drop at all. So this is most likely an issue with lower profile graphics cards which obviously have less RAM to work with.

**Comment by budimanjojo** [comment]
@Manko10 The release note of the latest update seems like this issue is fixed. Tried myself it transitioned perfectly smooth now

**Comment by ghost** [comment]
Seems to be fixed here too. The framerate when playing is now around 50-60 for me and opening the menu now only drops to around 40 FPS. But the greatest thing is that it goes back up to 50-60 when closing the menu.

Thanks!

**Comment by phoerious** [comment]
Great, then I guess this can be closed.

**Comment by danginsburg** [comment]
Closing as this appears to be resolved.
