### ISSUE TITLE
DOTA 2 don't start

### ISSUE THREAD

**Issue by lommaks777** [ValveSoftware/Dota-2#2055]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:
System information from steam
    Производитель: Apple
    Модель: iMac12,2
    Тип: Настольный
    Сенсорный ввод не поддерживается

Процессор:
    Производитель процессора: GenuineIntel
    Производитель процессора:         Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Семейство процессора: 0x6
    Модель процессора: 0x2a
    Степпинг процессора: 0x7
    Тип процессора: 0x0
    Тактовая частота: 3100 МГц
    Логических процессоров: 4
    Физических процессоров: 4
    Hyper-Threading: Не поддерживается
    FCMOV:  Не поддерживается
    SSE2:  Поддерживается
    SSE3:  Поддерживается
    SSSE3:  Поддерживается
    SSE4a:  Не поддерживается
    SSE41:  Поддерживается
    SSE42:  Поддерживается
    AES: Поддерживается
    AVX: Поддерживается
    AVX2: Не поддерживается
    AVX512F: Не поддерживается
    AVX512PF: Не поддерживается
    AVX512ER: Не поддерживается
    AVX512CD: Не поддерживается
    AVX512VNNI: Не поддерживается
    SHA: Не поддерживается
    CMPXCHG16B: Поддерживается
    LAHF/SAHF: Поддерживается
    PrefetchW: Не поддерживается

Версия ОС:
    MacOS 10.13.6 (64 бит)

Видеокарта:
    Модель:  AMD Radeon HD 6970M
    Версия драйвера не установлена
    Версия OpenGL: 4.1
    Глубина цвета: 32 бит/пиксель
    Частота обновления: 0 Гц
    ID производителя: 0x1002
    ID карты:  0x6720
    Версия неизвестна
    Кол-во экранов:  1
    Количество логических видеокарт:  1
    Разрешение осн. экрана:  2560 x 1440
    Разрешение рабочего стола: 2560 x 1440
    Размер осн. экрана: 23.46" x 13.19" (26.89" diag)
 59.6cm x 33.5cm (68.3cm diag)
    Осн. видеопамять: 1024 МБ

Память:
    Оперативная память:  16384 МБ

Устройства VR:
    Шлем виртуальной реальности: не обнаружен

Разное:
    Язык интерфейса:  Русский
    Тип носителя:  DVD
    Места на диске: 228736 МБ
    Наиболее свободный диск: 172180 МБ

Место на диске:
    Число SSD: 0
    Число жёстких дисков: 0

Have you checked for system updates? Yes
Are you using the latest stable video driver available for your system? Yes
Have you verified the game files?: Yes

iMac-Aleksej:~ aleksejlomakin$ sh ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/Users/aleksejlomakin/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Users/aleksejlomakin/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Uploading pending dumps
Uploaded 1 pending dumps
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamID:  0, universe Public
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198074701935 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198074701935
SteamID:  76561198074701935, universe Public
SteamID:  0, universe Public
Setting breakpad minidump AppID = 373300
2022-06-06 21:23:08.245 crash_report_sender[2564:66520] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
Breakpad Uploader: Send Error: Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSUnderlyingError=0x7fde3760a560 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSErrorFailingURLStringKey=http://crash.steampowered.com/submit, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://crash.steampowered.com/submit}}, NSErrorFailingURLStringKey=http://crash.steampowered.com/submit, NSErrorFailingURLKey=http://crash.steampowered.com/submit, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.}
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
2022-06-06 21:23:08.451 dota2[2561:66400] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4a35766b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff715a5942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4a37119d -[__NSArray0 objectAtIndex:] + 93
	3   libMoltenVK.dylib                   0x0000000087d90af7 mvkMTLResourceOptions + 14679
	4   libMoltenVK.dylib                   0x000000008810de27 _ZN3mvk19SPIRVToMSLConverter7convertERNS_33SPIRVToMSLConversionConfigurationEbbb + 3210519
	5   ???                                 0x0000000011b04ac6 0x0 + 296766150
	6   ???                                 0x0000000011b04cf6 0x0 + 296766710
	7   ???                                 0x0000000011b00218 0x0 + 296747544
	8   ???                                 0x0000000011aff34e 0x0 + 296743758
	9   ???                                 0x0000000011aff3e2 0x0 + 296743906
	10  ???                                 0x0000000011af33e5 0x0 + 296694757
	11  ???                                 0x0000000011afc0a8 0x0 + 296730792
	12  libdyld.dylib                       0x00007fff721bdd86 dlopen + 86
	13  librendersystemvulkan.dylib         0x0000000086739937 BinaryProperties_GetValue + 939735
	14  librendersystemvulkan.dylib         0x000000008670bc84 BinaryProperties_GetValue + 752164
	15  libengine2.dylib                    0x0000000009600953 pcre_free_study + 12355
	16  libengine2.dylib                    0x0000000009601c00 pcre_free_study + 17136
	17  libengine2.dylib                    0x000000000942926a Source2Main + 1010746
	18  libengine2.dylib                    0x0000000009428eb4 Source2Main + 1009796
	19  libengine2.dylib                    0x0000000009428a85 Source2Main + 1008725
	20  libengine2.dylib                    0x000000000932ee95 BinaryProperties_GetValue + 357141
	21  libengine2.dylib                    0x0000000009332706 Source2Main + 214
	22  dota2                               0x000000000926ddf0 dota2 + 15856
	23  dota2                               0x000000000926dd66 dota2 + 15718
	24  libdyld.dylib                       0x00007fff721bc015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kisak-valve** [comment]
Hello @lommaks777, `Модель: AMD Radeon HD 6970M` in your system information and ` libMoltenVK.dylib` in your call stack are the key details here. The AMD Radeon HD 6970M video card is part of the Terascale 2 generation, which does not support Vulkan on Windows and Linux, and does not support Metal on Mac.

You can try to add `-gl` to the game's launch options to tell Dota 2 to use the OpenGL render path.

That makes this the same issue as #1886. Closing as a duplicate.
