### ISSUE TITLE
Dota2 cheaters

### ISSUE THREAD

**Issue by ZZhaiDev** [ValveSoftware/Dota-2#2057]
I have been seeing this cheater multiple times recently, I have reported, but his account still not getting banned. Not sure where I can get help!

Here is the details, plz help!
https://youtu.be/nLwTfYZKL5k

replay id and exact time:
[6603849928]
At 12:45, and 13:15
[6605380663]
23:50 and 33:58

**Comment by kisak-valve** [comment]
Hello @zijiazhai, this issue tracker is intended for Mac and Linux Dota 2 client issues. Account issues are not handled here. I'm guessing that you'll want to post this over at https://dev.dota2.com or maybe use [Steam Support](https://help.steampowered.com/) for the feedback to reach the larger Dota 2 tean, but I'm not really sure what the appropriate feedback method is for this specific topic.

Closing as out of scope for this issue tracker.
