### ISSUE TITLE
Dark seer lv1 Vacuum is 10 dmg instead of 100

### ISSUE THREAD

**Issue by CalebmKopp** [ValveSoftware/Dota-2#2058]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/CalebmKopp/abe3ecf4fcfa5b67f0a6b9c4497c285e
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dark Seer Vacuum damage is supposed to be 100 level one, with the new patch. it is 10 instead.

#### Steps for reproducing this issue:

1. Go into hero demo
2. Pick dark seer
3. use Vacuum on dummy and it registers as 7.5 damage

**Comment by kisak-valve** [comment]
Hello @CalebmKopp, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. General gameplay issues are out of scope for this issue tracker. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.

Alternatively, there's also a feedback experiment being tried at https://github.com/jeffhill/Dota2/ where this has already been mentioned https://github.com/jeffhill/Dota2/issues/859.
