### ISSUE TITLE
[Mac] Vsync kills frame rate

### ISSUE THREAD

**Issue by Najadorel** [ValveSoftware/Dota-2#206]
When Sync is active frame rate drops bellow 20 fps and when is disable I get 100 FPS, this is a a new issue than wasn't happening before.

I'm playing on a:
  Model Name:   MacBook Pro 11,3
  Processor Name:   Intel Core i7
  Processor Speed:  2.5 GHz
  Video Card: NVIDIA GeForce GT 750M 2GB
  Memory:   16 GB

**Comment by ssnl** [comment]
I also experienced this.

**Comment by danginsburg** [comment]
Does this happen both in fullscreen and windowed mode?  What resolution and settings?  I haven't been able to repro this on any of my Macs here.  Vsync behaves as I would expect (capping the framerate at the vertical refresh rate).

**Comment by Najadorel** [comment]
In full screen resolution 1920x1200

**Comment by jeanlain** [comment]
I too have described this issue with additional details. 
https://github.com/ValveSoftware/Dota-2-Reborn/issues/248

**Comment by danginsburg** [comment]
Duplicate of #248.  Closing.  I'm about to post an update there.
