### ISSUE TITLE
Mouse doesn't work in dota 2.

### ISSUE THREAD

**Issue by troteiro** [ValveSoftware/Dota-2#2060]
3 days ago my mouse suddenly stopped working in dota 2. It happened randomly, my system is win 10x64, i9 11900k 3070ti, win updates and drivers are up to date, dota is up to date, steam etc. I tried reinstalling, didn't help.
Mouse randomly stops working, i cant see the cursor and cant click any menu buttons. And i have to alt+f4 the game, then i have to use launch parameters like -vulkan -noborder or -dx11 -noborder to make it work again until i restart dota. Then, mouse stops working again for some reason. Maybe it has to do with windows function gamebarpresencewriter (no sure or the exact name), which  have disabled, maybe it is steam controller settings (i have read the potentional solutions on internet whivk included steam controller settings), maybe its windows game mode...i don't know.
Also, dota sometimes doesn't save video and other parameters that were set in game.
My dota worked fine and other games currently work fine, and i never had this issue on the same system until 3-4 days ago.

**Comment by kisak-valve** [comment]
Hello @troteiro, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.
