### ISSUE TITLE
Featured heros showing wrong equipped items

### ISSUE THREAD

**Issue by Konseyy** [ValveSoftware/Dota-2#2062]
#### Your system information

* System information from steam:  [here](https://gist.github.com/Konseyy/4b03b5787a81d658f2c93c93db5cd730)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system?: Yes
* Have you verified the game files?: No

#### Please describe your issue in as much detail as possible:
As of the most recent update with the ability to change the immortal item effects, the item displayed on the hero in the featured heros section is the one whose effect is currently selected, not the item that's currently equipped on the hero

Below is an example from my currently equipped items
#### Steps for reproducing this issue:

1.  Have the following items for monkey king: "Staff of the demon trickster" and "Staff of Gun-Yu"
2.  Equip "Staff of the demon trickster"
3.  Put Monkey King in featured heroes
4. Open featured heroes - current showcased item is the one equipped
5. Equip the immortal effect of "Staff of Gun-Yu" and leave the equipped weapon as is
6. Open featured heroes - current showcased item is "Staff of Gun-Yu" even though in hero armory screen it's "Staff of the Demon Trickster"

**Comment by kisak-valve** [comment]
Hello @Konseyy, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. General issues affecting all platforms are not tracked here.

You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.
