### ISSUE TITLE
Enemy Illusions cannot be selected when whatching game without delay

### ISSUE THREAD

**Issue by SpeedyGonzaless** [ValveSoftware/Dota-2#2063]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When I watching my friends game without delay (using dota plus) I cannot select illusions, so potentially I can give him information where the real enemy is.

#### Steps for reproducing this issue:
1.  Start watching friend's game without delay
2.  Try to select enemies illusion
3.  It is not selected

**Comment by kisak-valve** [comment]
Hello @SpeedyGonzaless, this reads like a general cross-platform issue. This issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com or maybe use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.
