### ISSUE TITLE
Revert quickcast vector "fix" or at give players options please :)

### ISSUE THREAD

**Issue by shalashaka** [ValveSoftware/Dota-2#2064]
#### Your system information

N/a not a bug, more of a feature revert request

#### Steps for reproducing this issue:

1. in 7.31, quick cast was revised again for  vector target spells. instead of tapping Q and then left clicking to use a vector spell precisely, quick cast now works off of holding and releasing. For heroes who use quick cast vector but need precision (Dark Seer, Pango, Marci) this becomes problematic
2. people seem split on the issue; some love it and some hate it (https://www.reddit.com/r/DotA2/comments/tomnx5/who_ever_made_this_new_quickcast_option_fucking/)
3. requesting some way to choose how we want to use vector targeted quick cast, either the existing way, or the pre 7.31 way
4. cheers and love, and thanks for doing this :)

**Comment by kisak-valve** [comment]
Hello @shalashaka, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. General game play issues are not tracked here.

You'll want to post this over at https://dev.dota2.com for the feedback to reach the larger Dota 2 team.

Closing as out of scope for this issue tracker.
