### ISSUE TITLE
Random Crashes since 7.31d

### ISSUE THREAD

**Issue by BrodieSutherland** [ValveSoftware/Dota-2#2065]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/BrodieSutherland/61c61aa75254d6dcdebb5fa2b6fc81fb): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Getting some random crashes since 7.31d that weren't present before, hoping I can help you guys find whats up here.

Game crashes when spectating or playing a live game, but not when spectating a replay (at least from my experience anyway). I crashed 3 times in my example Match ID (during the final fight too, RIP), no commonality between them in terms of behaviour immediately before crashes. I have attached the last crash's dump file here:

[crash_20220611224522_2.dmp.zip](https://github.com/jeffhill/Dota2/files/8884892/crash_20220611224522_2.dmp.zip)

Things I've tried:
Validating game integrity
Full game reinstall
Disabling any and all overlays
Running the game on lowest graphical settings
Switching renderer from Vulkan to OpenGL
Running Dota via Proton (didn't launch at all via this method actually lol)
Crying

Example Match ID (and possibly Timestamp)
6612040440 - 1:05, 40:00, 43:20

#### Steps for reproducing this issue:

1. Play Dota
2. Spectate live game or play a game
3. Wait for something to go wrong

**Comment by ghost** [comment]
I am also getting freezes every 3 minutes or so since latest patch. With Vulkan or not.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libanimationsystem.so.

**Comment by BrodieSutherland** [comment]
3 more dump files here from some tests I was doing vs bots, didn't make it to 8 mins in any game:

[dump_files.zip](https://github.com/ValveSoftware/Dota-2/files/8888379/dump_files.zip)

**Comment by stryan** [comment]
I also seem to be crashing every 5-10 minutes starting today, though I have played two games before today that seemed fine (both before today).

Sysinfo gist:https://gist.github.com/stryan/d42c3f84773240b349010509c7bd78eb
[crashes_20220613.zip](https://github.com/ValveSoftware/Dota-2/files/8896015/crashes_20220613.zip)

**Comment by stryan** [comment]
Gave it another go last night and now I seem to be stable while running in OpenGL. Still no luck with Vulkan.

**Comment by BrodieSutherland** [comment]
Mine's still crashing this morning, but I will note that yesterday i played about 3 bot games with no issue, and got through a pub game with only 1 crash during laning so :shrug:

**Comment by stryan** [comment]
Just had a match where I crashed about 4 times in the first ten minutes: 6623181197. Still on OpenGL so no idea what's happening. Maybe related to the packet loss ticket?

**Comment by mumblerit** [comment]
Definetely seems like it crashes early in the game, if I can get past the 1-4 crashes in the first 15 minutes it seems ok.

Eventually it just works, even for multiple games in a row.

**Comment by ghost** [comment]
Any progress on this? It's really not a playable experience atm.

**Comment by V01dgazer** [comment]
Mine is freezing every other game several times a match. Totally unplayable right now.

**Comment by stryan** [comment]
ceLoFaN and Selvdrap, can you add sysinfo gists and dump files? Gotta make sure we're all having the same bug.

I was able to play multiple matches last night with no crashes and only one crash the day before, so not sure where this is going.

**Comment by V01dgazer** [comment]
[Sysinfo gist](https://gist.github.com/Selvdrap/0eb24bbbc333bc963062b43723fb426f)

[crash_20220621.zip](https://github.com/ValveSoftware/Dota-2/files/8952106/crash_20220621.zip)

**Comment by ghost** [comment]
[sysinfo](https://gist.github.com/ceLoFaN/0148d18b49e6b6de03626af7cf2cbdf2)

~I haven't found anything in `/tmp/dumps`, but I'll look there the next time it happens. The game takes a while to crash for me, it just stays there frozen for a while, so I `kill -9` it quick to reconnect. Maybe that's why I haven't found anything.~

Actually I found a few dumps with `coredumpctl`, but one is about 3.5Gb when not zstd-ed. Should I upload that somewhere?

**Comment by V01dgazer** [comment]
@ceLoFaN I have the same pattern - the game takes some time to crash, so I kill the process manually. Still got dumps though.

The crash is a bit random: I can play just fine few games in a row and then I'm crashing 10 times a match.

**Comment by BrodieSutherland** [comment]
Still getting the same behaviour as @Selvdrap on linux, ive been just running on a dual booted windows instead while I wait for a fix

**Comment by lewisdiamond** [comment]
I also have a lot of issues with Dota 2 crashing randomly. I have several coredumps.

**Comment by waylon531** [comment]
Please fix this soon, crashing this often makes dota basically unplayable

**Comment by waylon531** [comment]
I seem to experience much less crashing on the flatpak version of steam, I wonder if this is due to some library incompatibility. My normal system is Arch/Artix

**Comment by dgiorgio** [comment]
same problem here
Dota has been unplayable for a few months now.
Sometimes I can play 3 games without a problem, and sometimes the game crashes more than 10 times in a game.
The problem happens on both OpenSUSE and Fedora.
I've already tried to do a clean install of Steam, and run by Flatpak.
It doesn't help, it's always the same problem, from general protection fault libanimationsystem.so
I've run all the stress tests on the PC, and no problems.
All games run fine, including heavier games, only Dota is giving this problem.

```
[sex jul 29 02:44:56 2022] show_signal_msg: 55 callbacks suppressed
[sex jul 29 02:44:56 2022] GlobPool/3[21881]: segfault at 7f8099f793f0 ip 00007f8099f793f0 sp 00007f8099f793e0 error 15
[sex jul 29 02:44:56 2022] Code: 00 00 30 51 7c 9c 86 55 00 00 00 00 00 00 c8 87 d4 3e f0 93 f7 99 80 7f 00 00 0a 00 00 00 00 00 00 00 ff 27 1e 7c 00 00 00 00 <00> 94 f7 99 80 7f 00 00 37 4d 73 7f 80 7f 00 00 b0 b4 f7 99 80 7f
[sex jul 29 02:47:58 2022] traps: GlobPool/3[25327] general protection fault ip:7fe422934b34 sp:7fe43c1fa3e8 error:0 in libanimationsystem.so[7fe422400000+65c000]
[sex jul 29 03:25:06 2022] traps: GlobPool/0[26687] general protection fault ip:7fd7c2339841 sp:7fd7dcff1368 error:0 in libanimationsystem.so[7fd7c1e00000+65c000]
[sex jul 29 03:25:54 2022] traps: dota2[30531] general protection fault ip:7f170b334b34 sp:7ffd4101dc48 error:0 in libanimationsystem.so[7f170ae00000+65c000]
[sex jul 29 03:26:54 2022] traps: dota2[30961] general protection fault ip:7f6863734b34 sp:7fffae4976c8 error:0 in libanimationsystem.so[7f6863200000+65c000]

```

https://github.com/ValveSoftware/Dota-2/issues/2095

**Comment by waylon531** [comment]
A couple weeks ago flatpak started having the same issues for me, after a system update. I get the same segfault in libanimation.so again.

**Comment by dgiorgio** [comment]
Amazing how the support was abandoned by Valve. By any chance, was Dota deprecated?

**Comment by V01dgazer** [comment]
Still reproducible.

**Comment by waylon531** [comment]
I've found a decent workaround now. If you go to the Compatibility settings of the game and click the "Force the use of a specific Steam compatibility tool" checkbox, you can force Steam to run the Windows version of the game with proton. It's kind of stupid but it does at least make Dota playable again.

The only issue I ran into doing this is that holding Alt to self cast stopped working, but I was able to fix this by binding and unbinding the "Alt Modifier" key. Everything worked fine after that and the game is quite smooth.

**Comment by dgiorgio** [comment]
> I've found a decent workaround now. If you go to the Compatibility settings of the game and click the "Force the use of a specific Steam compatibility tool" checkbox, you can force Steam to run the Windows version of the game with proton. It's kind of stupid but it does at least make Dota playable again.
> 
> The only issue I ran into doing this is that holding Alt to self cast stopped working, but I was able to fix this by binding and unbinding the "Alt Modifier" key. Everything worked fine after that and the game is quite smooth.

Nice, I will test.

**Comment by V01dgazer** [comment]
> I've found a decent workaround now. If you go to the Compatibility settings of the game and click the "Force the use of a specific Steam compatibility tool" checkbox, you can force Steam to run the Windows version of the game with proton. It's kind of stupid but it does at least make Dota playable again.
> 
> The only issue I ran into doing this is that holding Alt to self cast stopped working, but I was able to fix this by binding and unbinding the "Alt Modifier" key. Everything worked fine after that and the game is quite smooth.

Which proton version did you try? The game doesn't even start for me with this mode.

**Comment by dgiorgio** [comment]
> > I've found a decent workaround now. If you go to the Compatibility settings of the game and click the "Force the use of a specific Steam compatibility tool" checkbox, you can force Steam to run the Windows version of the game with proton. It's kind of stupid but it does at least make Dota playable again.
> > The only issue I ran into doing this is that holding Alt to self cast stopped working, but I was able to fix this by binding and unbinding the "Alt Modifier" key. Everything worked fine after that and the game is quite smooth.
> 
> Which proton version did you try? The game doesn't even start for me with this mode.

here it didn't work either, I tried several versions of proton, I cleaned the configuration and cache files.

**Comment by waylon531** [comment]
I'm using proton experimental, with the launch options `-novid -vconsole`

**Comment by V01dgazer** [comment]
> 

Nope, doesn't work. :C

**Comment by ds0nt** [comment]
I'm on manjaro. Crashes all day. Losing MMR here.

**Comment by ds0nt** [comment]
Also I want my 100 MMR back.

**Comment by ds0nt** [comment]
What kind of trash software crashes and punishes it's users for it.

**Comment by ds0nt** [comment]
Warcraft 3 never crashed.

**Comment by stryan** [comment]
If you're going to complain, at least make it useful and upload the crash dumps and system specs so someone can figure out what's going on. If it's crashing all the time (i.e. the crashes continue after the first 10-15minutes of the first match played) you could be experiencing a different bug from this one.



> Warcraft 3 never crashed.

You and I must have had very different copies of Warcraft 3.

**Comment by V01dgazer** [comment]
I think it is actually a bit better now, it crashes much less frequently. It can happen once or twice during the first 10-20 minutes of the game. I usually try to play with bots first rounds to see if it crashes.

**Comment by dgiorgio** [comment]
For the first time, I played a match without closing the dota. 
Maybe they fixed it in the international update.

**Comment by stryan** [comment]
I also haven't had a crash in three separate sessions.

**Comment by MiriJ15** [comment]
I get random fps drops and mangohud shows that my GPU usage is dropping to 0%. I am using the native version with latest Nvidia drivers on the latest stable Manjaro kernel ( tried lts and custom ones).

**Comment by waylon531** [comment]
I haven't gotten any crashes in the native linux version of the game recently, I've played about 10 games so far without any problems

@MiriJ15 if you're not getting crashing then it sounds like a different issue, you should probably open a new issue

**Comment by dgiorgio** [comment]
> I get random fps drops and mangohud shows that my GPU usage is dropping to 0%. I am using the native version with latest Nvidia drivers on the latest stable Manjaro kernel ( tried lts and custom ones).

Check FPS limit in game settings.
There are two options, the game's FPS, and the panel's FPS.
If the game's FPS is 120, and the panel is 60, it will drop frames to 60 every time you open the items panel or any other panel.

**Comment by kisak-valve** [comment]
Closing as fixed.
