### ISSUE TITLE
Faceless Void time walk range issue (explanation is in the reproduce section) 

### ISSUE THREAD

**Issue by DialoN666** [ValveSoftware/Dota-2#2069]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Buying Aghanim's Scepter on Faceless Void removes the Time Walk range indicator.
2. If you try to use the ability Time Walk without Aghanim's Scepter once you click the button for it (assuming it is not on quick cast) you can see the range of the ability, once the Aghanim's Scepter is bought the range is no longer visible it is quite misleading for me.

**Comment by kisak-valve** [comment]
Hello @DialoN666, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. General gameplay issues are out of scope for this issue tracker. You'll want to post this over at https://dev.dota2.com/ or use [Steam Support](https://help.steampowered.com/) for the feedback to reach the larger Dota 2 team.
