### ISSUE TITLE
[Mac] objects don't block light halos

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#207]
See screenshot, the light halo from the candles at the left of the camp shines through the tree. It's not due to sparse foliage. Stones wouldn't block light halos either. This affects all sources of lights, including the fountain, fireballs, etc. 
This issue used to affect some source 1 games on the Mac and was resolved. See http://store.steampowered.com/news/4211/
Maybe it's known in dota 2 and left unsolved because it's not visible very often given the typical angle of view. In showcase view though, it can be quite visible. 

OS X 10.9.5 radeon 7950.

![capture d ecran 2015-07-04 a 08 25 07](https://cloud.githubusercontent.com/assets/4463576/8506781/5c1e0c2c-2226-11e5-8a16-b9de460d050b.jpg)

**Comment by danginsburg** [comment]
This occurs on Windows DX9/DX11/GL as well.

**Comment by danginsburg** [comment]
I have reported this to the larger team.  Will not track this issue here since it is not OSX/Linux specific.
