### ISSUE TITLE
Allied owned outposts can be captured repeatably with a-click

### ISSUE THREAD

**Issue by Ori-Pixel** [ValveSoftware/Dota-2#2072]
Hi. More of a gameplay problem than a system one. If your team owns an outpost, you can re-channel the capturing animation and get a team message if you a-click the outpost.

Expected result:
A-click should either cancel with a popup (like when you cannot a-click your own T-2 towers that have protection). How it is right now can interrupt teamfights around your own outpost. I've seen teammates stop attacking enemies and start channeling an owned outpost.

Steps to reproduce:
1) Have a controlled allied outpost.
2) a + click (attack move without smart attack move) the outpost
3) watch as you channel the outpost and get the animation and team message at the end.
4) Repeat

**Comment by kisak-valve** [comment]
Hello @Ori-Pixel, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. General gameplay issues are out of scope for this issue tracker. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.

Alternatively, there's also a feedback experiment being tried at https://github.com/jeffhill/Dota2/ where this has already been mentioned at https://github.com/jeffhill/Dota2/issues/657.
