### ISSUE TITLE
Dota 2 crash upon finding match

### ISSUE THREAD

**Issue by syn4pse3** [ValveSoftware/Dota-2#2073]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/syn4pse3/df5fbd7343c10196ff497fc4abb06a76
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 crashes upon finding a match. It happens even before the loading screen shows. Upon re-opening the game, I try to reconnect but the game still crashes until the match is abandoned (-30 MMR just like that...). Afterwards, I can find a game without any issues.

The issue happens randomly (happened to me twice in 2 weeks). Most of the time I am able to find a match without any problems.

#### Steps for reproducing this issue:

1. Find ranked match
2. Press 'Accept' once a match has been found
3. Game crashes before loading screen shows
4. Re-open the game to reconnect
5. Game crashes
6. Repeated steps 4 to 5 until I get abandon

**Comment by kisak-valve** [comment]
Hello @syn4pse3, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.

Closing as out of scope for this issue tracker.
