### ISSUE TITLE
All Random Deathmatch matches crash after 36 - 39 minutes

### ISSUE THREAD

**Issue by Rob4ix1337** [ValveSoftware/Dota-2#2077]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
 https://gist.github.com/Rob4ix1337/1566e01c0fd53971d01d6ed26c1cda00
* Have you checked for system updates?: [Yes/No]
 Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
 Yes
* Have you verified the game files?: [Yes/No]
 Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

All Random Deathmatch matches always crash after a certain amount of time in game (around 36 - 39 minute mark). A connection error occurs to everyone in the game, and the game crashes afterwards.

**Comment by kisak-valve** [comment]
Hello @Rob4ix1337, this issue tracker is limited to issues with the Mac and Linux Dota 2 client. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 team.
