### ISSUE TITLE
Changing between post game summary tabs crashes the game

### ISSUE THREAD

**Issue by tom-bird** [ValveSoftware/Dota-2#2079]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/tom-bird/f07518b28593a11d05bb19714892a330
* Have you checked for system updates?: No
* Are you using the latest stable video driver available for your system? Don't think so, but it will be closeish
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
In the post game screen, if I switch from the performance to the graph tab then dota freezes and becomes unresponsive. I have to kill the process via terminal to even get it to close, closing it through steam does not work (there is always one process that lives on).

The issue does seem specific to the those tabs - I can browse the other tabs fine. In fact I think it is specific even to the order in which you go between them! I think it is performance -> graph only that causes it to crash, pretty weird.

Also, it doesn't always happen when switching between the tabs. If I go to an old match summary and click around between the tabs then I can go usually go from performance -> graph, but as I click around at some point relatively quickly it will crash, and always on the transition between performance and graph. It may also require you to change quickly from performance to graph, clicking in relatively quick succession, although I am not certain about this.

#### Steps for reproducing this issue:

1. Go to a post game screen (doesn't have to be straight after the game)
2. Open performance tab and then try and (maybe quickly) open the graph tab (might have to click around between the tabs for a little bit)

**Comment by kisak-valve** [comment]
Hello @tom-bird, this issue is already being tracked at #2036. Since this issue report adds a bit more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/Dota-2/issues/2036#issuecomment-1164361665.
