### ISSUE TITLE
[Linux] Illusions can't be differentiated from the real hero

### ISSUE THREAD

**Issue by dhiru1602** [ValveSoftware/Dota-2#208]
**My PC Specs**
Intel Core I7 920 3.5Ghz
16GB RAM
Nvidia 9600GT 1GB
Arch Linux with 4.0.7 kernel
Nvidia Proprietary 340xx (340.76-10) GPU driver

Illusions appear exactly like the hero when **Additive Light Pass is disabled**. This makes it really hard to identify the real hero and differentiate between Juxtapose and Manta Style illusions for Phantom Lancer. Tested Phantom Lancer, Chaos Knight, Naga Siren, Terrorblade and they all have the same issue.

![snapshot10](https://cloud.githubusercontent.com/assets/1326273/8507018/53a79286-2242-11e5-87b2-77f3e1cf2bf0.png)

**Comment by budimanjojo** [comment]
As far as I know the illusions are differentiated by the health bar, so what do you mean by "differentiated"?

**Comment by dhiru1602** [comment]
**PHANTOM LANCER - Additive Light Pass enabled**
![snapshot15](https://cloud.githubusercontent.com/assets/1326273/8508592/8bc61346-2287-11e5-8565-f37df664c247.png)

**PHANTOM LANCER - Additive Light Pass disabled**
Notice how there is no difference between the Manta Style illusions and Juxtapose Illusions. They all look the same.
![snapshot14](https://cloud.githubusercontent.com/assets/1326273/8508595/929b2b7a-2287-11e5-9f37-b508e05d92e2.png)

**CHAOS KNIGHT - Additive Light Pass enabled**
![snapshot13](https://cloud.githubusercontent.com/assets/1326273/8508578/ece7eea2-2286-11e5-9791-5eeaf6521227.png)

**CHAOS KNIGHT - Additive Light Pass disabled**
![snapshot12](https://cloud.githubusercontent.com/assets/1326273/8508577/ece113e8-2286-11e5-9f2d-178121797552.png)

**Comment by rodlorric** [comment]
This is happening on the Windows client too.
Just tested it with both DX9 and DX11 options and Additive Light Pass disabled.

Windows DX9 - 32 bits
![Windows DX9 - 32 bits](http://i.imgur.com/W3MxJr8.jpg)

Windows DX11 - 64 bits
![Windows DX11 - 64 bits](http://i.imgur.com/5DMyWG7.jpg)

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux issue we'll pass this on to the larger team and it won't be tracked here.

**Comment by gdrewb-valve** [comment]
The larger team says a fix will be in an upcoming update.
