### ISSUE TITLE
Dota 2 suddenly crashes after I open

### ISSUE THREAD

**Issue by vmxt** [ValveSoftware/Dota-2#2080]
My Dota2 always crashes when I launch it; it usually crashes in the start menu. It seems strange that if I minimize the application, it does not crash, but when I idle/watch the game, it crashes.

I've been researching ways to avoid this problem, such as launch options:
`-novid -safe` or `-autoconfig` didn't work either.

** My drivers are already up to date (RTX 3060), and I tried reinstalling and changing the directory, but the problem persists. Do you have any solutions for this type of problem? thanks

**Comment by Billie34** [comment]
> My Dota2 always crashes when I launch it; it usually crashes in the start menu. It seems strange that if I minimize the application, it does not crash, but when I idle/watch the game, it crashes.
> 
> I've been researching ways to avoid this problem, such as launch options: `-novid -safe` or `-autoconfig` didn't work either.
> 
> ** My drivers are already up to date (RTX 3060), and I tried reinstalling and changing the directory, but the problem persists. Do you have any solutions for this type of problem? thanks

I have the same problem as you, I tried to find a way to fix it but it doesn't seem to work. @[phoodle](https://phoodle.io/)

**Comment by vmxt** [comment]
### **This issue was fixed**

The only issue here was that the antivirus itself had to be uninstalled and reopen dota2 and it works properly. @Billie34, If you're using a monitored antivirus  I would recommend utilizing free antivirus or the default windows security. I was using a workplace laptop and they removed the restrictions for a reason, which is why my Dota2 works perfectly today.
