### ISSUE TITLE
lowskill dev's

### ISSUE THREAD

**Issue by EgoHughes** [ValveSoftware/Dota-2#2081]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Start the dota
2. choose role
3. click to button "looking game"
4.Try to play
5. lost game Because the player selection system on my account is tweaked and picks up players incorrectly, thus I lost more than 4 thousand rating because of your crooked tweaked system.
As well as scripts that deliberately accept all reports in which there is no objective explanation of the ruined game.
6. Read a manual for C/C+/C#/Java/Python for AI writeing, stupid u are dev's.
Stop the ruined my rating ! let me normal guys ! i tired play with sub-humans only !

**Comment by kisak-valve** [comment]
Hello @EgoHughes, this is non-constructive feedback and an inappropriate way to communicate with anyone.

You've been given a 24 hour timeout for disregarding the issue tracker conduct policy: [`Do not insult, harass, or demean anyone.`](https://github.com/ValveSoftware/Dota-2/#conduct)
