### ISSUE TITLE
Crash when game popped as pack was opening

### ISSUE THREAD

**Issue by chrisrrowland** [ValveSoftware/Dota-2#2083]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

- * https://gist.github.com/chrisrrowland/d0138cb65672b21d158f34deb6318c3c

* Have you checked for system updates?: [Yes/No]

- * Yes

* Are you using the latest stable video driver available for your system? [Yes/No]

- * Yes

* Have you verified the game files?: [Yes/No]

- * Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Queued for match
2. Went to open dota 2 fantasy card pack
3. Pack was opening and match popped, hit accept
4. game crashed, placed in abandoner queue

**Comment by kisak-valve** [comment]
Hello @chrisrrowland, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. You'll want to post this over at https://dev.dota2.com or use [Steam Support](https://help.steampowered.com) for the feedback to reach the larger Dota 2 dev team.

Closing as out of scope for this issue tracker.

**Comment by chrisrrowland** [comment]
Apologies I google for the dota2 github issue tracker and it sent me here instead of https://github.com/jeffhill/Dota2/issues
