### ISSUE TITLE
Game camera does not move to right when playing in a wayland session.

### ISSUE THREAD

**Issue by lisboaigor** [ValveSoftware/Dota-2#2085]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/lisboaigor/8069628609b167528f56c971ddbd080d): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system?: Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Game camera does not move to right when using Wayland. When using X.org, it works.

#### Steps for reproducing this issue:

1. Open the game in a Wayland session. 
2. Test a hero or create a custom game.
3. Try move the camera to right.

**Comment by kisak-valve** [comment]
Hello @lisboaigor, from your system information:
```
    Primary Display Resolution:  1360 x 768
    Desktop Resolution: 1366 x 768
```
Your desktop resolution is 6 pixels wider than your display. It's possible that the desktop environment is having the game's fullscreen window render the right edge slightly off screen and not allowing your mouse to reach it.

**Comment by lisboaigor** [comment]
> Hello @lisboaigor, from your system information:
> 
> ```
>     Primary Display Resolution:  1360 x 768
>     Desktop Resolution: 1366 x 768
> ```
> 
> Your desktop resolution is 6 pixels wider than your display. It's possible that the desktop environment is having the game's fullscreen window render the right edge slightly off screen and not allowing your mouse to reach it.

Thank you for the answer, @kisak-valve! But I think the system is switching these informations. When opening the game, I see 6 pixel blank gap from the right edge, both in X.org and Wayland. I can't move to right just on Wayland.

![image](https://user-images.githubusercontent.com/46612620/178109691-1a48db21-90a4-44dc-9958-aef94c170b56.png)

**Comment by nuranov04** [comment]
@lisboaigor, Do you fix this bug?

**Comment by lisboaigor** [comment]
> @lisboaigor, Do you fix this bug?

Unfortunately not. I stopped playing the game on Linux.

**Comment by izzatzr** [comment]
Install libxcvt0_0.1.2-1 then restart the system works for me

**Comment by RyuzakiKK** [comment]
@izzatzr Which operating system are you using? And which version? `libxcvt` is a library that should be picked up automatically as a dependency of XWayland, when a relatively new XWayland is in use.

**Comment by izzatzr** [comment]
> @izzatzr Which operating system are you using? And which version? `libxcvt` is a library that should be picked up automatically as a dependency of XWayland, when a relatively new XWayland is in use.

I use ubuntu 22.04 LTS

**Comment by RyuzakiKK** [comment]
> I use ubuntu 22.04 LTS

AFAICT Ubuntu 22.04 is shipping with XWayland `2:22.1.1-1ubuntu0.5` and libxcvt0 `0.1.1-3`.
libxcvt0 `0.1.2-1` is only for Ubuntu 22.10.

@izzatzr where did you pick `libxcvt0_0.1.2-1` from? Does that mean that you previously had `libxcvt0 0.1.1-3` from the official Ubuntu repositories, and once you upgraded libxcvt0 the issue disappeared?

**Comment by izzatzr** [comment]
> > I use ubuntu 22.04 LTS
> 
> AFAICT Ubuntu 22.04 is shipping with XWayland `2:22.1.1-1ubuntu0.5` and libxcvt0 `0.1.1-3`. libxcvt0 `0.1.2-1` is only for Ubuntu 22.10.
> 
> @izzatzr where did you pick `libxcvt0_0.1.2-1` from? Does that mean that you previously had `libxcvt0 0.1.1-3` from the official Ubuntu repositories, and once you upgraded libxcvt0 the issue disappeared?

yes indeed, my machine is fresh installed ubuntu 22.04 LTS with libxcvt0 0.1.1-3 shipped. i found and try the solution from https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5694, they suggest installing libxcvt0 0.1.2-1

**Comment by kisak-valve** [comment]
If Ubuntu LTS is shipping a mildly defective package, then that should be reported to the distro's package maintainer(s) for libxcvt so they can ponder if they want to update or patch the library they're providing.

**Comment by killdrm** [comment]
have the same problem, installed those libraries, it is still not solving the problem.

**Comment by killdrm** [comment]
have ubuntu 22.0.4 LTS
