### ISSUE TITLE
bug, MMR !

### ISSUE THREAD

**Issue by EgoHughes** [ValveSoftware/Dota-2#2086]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1.hello dumb rickets )
Dota is already 14 years old, how long before some moron developer learns how to write player matching code?
are you seriously such premature fuckheads?
bitch, stop smothering my account ! you can't keep giving me the same shit about your peers, i.e. talentless motherfuckers !!!!
Bitch, learn how to code artificial intelligence, you piece of shit!
and if you can't, i'll send you a manual to read how to write a simple AI system in 1 hour, which is a billion times more productive than the stupid shit you have in your game called balance player selection !!!!

Translated with www.DeepL.com/Translator (free version) 
2. hello dumb rickets )
Dota is already 14 years old, how long before some moron developer learns how to write player matching code?
are you seriously such premature fuckheads?
bitch, stop smothering my account ! you can't keep giving me the same shit about your peers, i.e. talentless motherfuckers !!!!
Bitch, learn how to code artificial intelligence, you piece of shit!
and if you can't, i'll send you a manual to read how to write a simple AI system in 1 hour, which is a billion times more productive than the stupid shit you have in your game called balance player selection !!!!

Translated with www.DeepL.com/Translator (free version)
3. hello dumb rickets )
Dota is already 14 years old, how long before some moron developer learns how to write player matching code?
are you seriously such premature fuckheads?
bitch, stop smothering my account ! you can't keep giving me the same shit about your peers, i.e. talentless motherfuckers !!!!
Bitch, learn how to code artificial intelligence, you piece of shit!
and if you can't, i'll send you a manual to read how to write a simple AI system in 1 hour, which is a billion times more productive than the stupid shit you have in your game called balance player selection !!!!

Translated with www.DeepL.com/Translator (free version)
hello dumb rickets )
Dota is already 14 years old, how long before some moron developer learns how to write player matching code?
are you seriously such premature fuckheads?
bitch, stop smothering my account ! you can't keep giving me the same shit about your peers, i.e. talentless motherfuckers !!!!
Bitch, learn how to code artificial intelligence, you piece of shit!
and if you can't, i'll send you a manual to read how to write a simple AI system in 1 hour, which is a billion times more productive than the stupid shit you have in your game called balance player selection !!!!

Translated with www.DeepL.com/Translator (free version)

**Comment by kisak-valve** [comment]
This kind of abusive behavior is not tolerated.
