### ISSUE TITLE
Skilling talents with voicechat keybind can turn voice chat on

### ISSUE THREAD

**Issue by LucadeRaad** [ValveSoftware/Dota-2#2088]
#### Your system information

This happens across multiple computers.

#### Please describe your issue in as much detail as possible:
If you bind your voice chat to team as the 1 key, and you press 1 while there is a talent it can make it so you're voice chatting 24/7. If you hold your voice chat again it turns it off but that's the opposite of what to do

#### Steps for reproducing this issue:

1. Rebind your voice to 1
2. Have a talent ready to be leveled and press 1

**Comment by kisak-valve** [comment]
Hello @LucadeRaad, this issue is already being tracked at https://github.com/ValveSoftware/Dota2-Gameplay/issues/949. Closing as a duplicate.
