### ISSUE TITLE
[Linux] Graphics corruption after minimalizing game

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#209]
Hi.
I play with bots and when I minimalize game and come back to play I see this graphics corruption (not always but sometimes):

http://steamcommunity.com/sharedfiles/filedetails/?id=474268015

http://steamcommunity.com/sharedfiles/filedetails/?id=474267654

http://steamcommunity.com/sharedfiles/filedetails/?id=474267324

My Steam system info:
https://gist.github.com/xpris/a225f4cb2bf376d945fd

Quick info:
AMD Radeon HD 5850 with Catalyst 15.5
AMD Phenom II X6
DE: KDE 4.14.5 without compositions

As I wrote in the story: where the author had a similar problem graphical and crash (which I do not have): https://github.com/ValveSoftware/Dota-2-Reborn/issues/196#issuecomment-118309490

**Comment by budimanjojo** [comment]
Happened to me when I alt tab while on the picking hero scene or when the game is loading. The screen is black and I need to redoing alt tab to get the screen rendered

**Comment by danginsburg** [comment]
I have tried to repro this on AMD 7950 with Catalyst 15.7 on Ubuntu 14.10 x64 in Unity and have not been able to reproduce it.  It does not look to me like an application issue, but I'm not sure because I haven't been able to repro it.  Does it only happen in KDE?  Only at particular resolutions?

**Comment by AngryPenguinPL** [comment]
For now I don't have this issue anymore, maybe some patch fixed it quietly?
BTW. I tested it only on KDE.

Im let you know, if I see this coruption again.

**Comment by danginsburg** [comment]
I will close this for now, let us know if you see the corruption again.  I suspect it is not an application issue either way.
