### ISSUE TITLE
Segfault crash in early game

### ISSUE THREAD

**Issue by wetware-angel** [ValveSoftware/Dota-2#2093]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist]: https://gist.github.com/Quade-Amador/99f76d488a5772088860d04afd159534
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
So for the past few months on multiple distros (Ubuntu, Pop, current one) that I've tried to play Dota on Linux, I've been having the game freeze and then crash for me, though only in the early game (Before the in-game timer hits 20 minutes typically). After that point, it will be fine and run as expected without further crashes. It will also lock my mouse cursor to the window, meaning that I will have to wait for it to actually crash, though as of recent I've been keeping a terminal window running `top` open, alt-tabbing over and killing it with 9 to get out quickly.

Oddly enough, it seems that whenever a new patch is pushed the issue flares up again and becomes more common, with the longer it's been since the last causing the issue to appear less and less. For example, after a recent one I had this issue occur a good 5 times in one match, while a week prior I had only one in total. Link below is the result of the launch option `%command% &> ~/dota2-crash.txt`

https://gist.github.com/Quade-Amador/452acd1994398e9976bfdcf08be5c292

#### Steps for reproducing this issue:

1. Launch game and start match OR watch match live (have not tried with either coaching or default, delayed spectating)
2. Proceed with gameplay (or spectating) as normal until freeze and inevitable crash occurs.

**Comment by wetware-angel** [comment]
Worth noting that I did try what's suggested in https://github.com/ValveSoftware/csgo-osx-linux/issues/2659#issuecomment-962417347= to see if that helps. So far it has yet to reoccur after following the listed instructions, though will keep posted.

**Comment by stryan** [comment]
Possibly related or the same as #2065?

**Comment by wetware-angel** [comment]
Possibly, though I have no idea. I have only had it happen pre 20 mins though. Other guy seems to have it just kinda happen whenever.

**Comment by stryan** [comment]
I think the general consensus in that thread is that it usually happens pre-10 min, occasionally up to 20ish. I'll have to try the csgo method to see if it helps

**Comment by kisak-valve** [comment]
Hello @stryan, are you still experiencing this issue on an up to date system?

**Comment by stryan** [comment]
Whoop, forgot I had commented in this issue. No, I've been as stable as usual since the 7.32 patch (or whichever fixed it over in #2065).

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as fixed.

**Comment by kisak-valve** [comment]
Whoops, my eyes tricked me. I should have asked @Quade-Amador if they're also still seeing this issue (which I am now). Re-opening.

**Comment by wetware-angel** [comment]
Nope, it's become a lot better since around that time on my end as well. Granted, I will occasionally crash for other issues but nowadays it's mostly the steam client itself crashing rather than just dota. Mind you it does still wind up killing dota in kind because of that but it happens far less frequently and is a different issue entirely. This one's gone for me.

**Comment by stryan** [comment]
(Glad to see I'm not the only one having the steam client crashing issue)

**Comment by kisak-valve** [comment]
Thanks again for the feedback. Closing as fixed.
