### ISSUE TITLE
Reborn opens with dock and top bar but cant click anything to change to full screen (Mac)

### ISSUE THREAD

**Issue by Crayyu** [ValveSoftware/Dota-2#21]
When ever I open dota it opens fine, but it has the dock up still and the top bar and I can't click anything in the client to change it.

**Comment by gdrewb-valve** [comment]
What happens when you click the gear icon in the upper-left to go to settings?  In the video settings can you select fullscreen?

**Comment by Crayyu** [comment]
I can't click it to change the settings, I can't click anything. Nothing happens it just sits there

**Comment by yaakov-h** [comment]
I assume this is the same as #22?

**Comment by Crayyu** [comment]
Yea same problem I guess I didn't write it out properly

**Comment by gdrewb-valve** [comment]
The next release will switch things so a monitor-sized borderless window will take over the screen.

**Comment by gdrewb-valve** [comment]
How are things working after the 6/26 update?

**Comment by Crayyu** [comment]
It is fixed now, thank you
