### ISSUE TITLE
Chen walk animation is broken / too fast

### ISSUE THREAD

**Issue by nixi-awoo** [ValveSoftware/Dota-2#210]
I faced this problem in my last game whilst playing Chen. Other heroes were fine, but I am not sure whether only Chen is affected. Two of my friends saw the bug as well (on Windows).

My hero (as in entity) was walking at the right speed, but the hero model was too fast. It looked as if he was walking at max walking speed. The model was faster than the health bar and green circle around the hero entity moving away from it and was getting 'teleported' back to the right location in roughly one second intervals.

.gifv of the bug: http://i.imgur.com/95iBYeJ.gifv

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux issue I'll pass it on to the larger team and it won't be tracked here.

**Comment by gdrewb-valve** [comment]
The larger team says they understand the problem and a fix will be coming but it won't be tracked here.
