### ISSUE TITLE
[Feature Request] Apple Silicon native support and Metal API support

### ISSUE THREAD

**Issue by levihuayuzhang** [ValveSoftware/Dota-2#2103]
Thanks for the great works on MacOS! 

However, currently due to steam's API, dota2 hasn't have any way to build a native arm64 (Apple Silicon native) dota2. And the Rosseta work "fine" for most people. But there may still a lot of room to improve the performace (like the stability of FPS while team fight. Even M1 Max the FPS could drop from 100 to 50 suddenly, which could cause significant lag of input)

And M series Mac is still using Vulkan or openGL in dota 2 but `Metal` which is native of Apple should ship better performance and power effeciency.

Mac users may very excited to see this wondeful game have powerful Metal build on ARM platform (just like x86 DX11 build).

Is there any chance add these to the long-term dev plan? Very looking forword to it! 

Cheers!

**Comment by kisak-valve** [comment]
Hello @levihuayuzhang, the request for an ARM native build for MacOS M series hardware is already being tracked at #1908. Dota 2 is already using the Metal render path via MoltenVK on MacOS. Vulkan support is not provided directly by the video drivers available on Macs.

Closing as a duplicate.
