### ISSUE TITLE
Opening battlepass crashes game

### ISSUE THREAD

**Issue by Ori-Pixel** [ValveSoftware/Dota-2#2118]
#### Your system information

* System information from steam: https://gist.github.com/Ori-Pixel/4a3c5ac1588879142e7402e6401939d7
* Have you checked for system updates?: Yes (the first battlepass update worked fine, the second small update started the crashes)
* Are you using the latest stable video driver available for your system? Yes (NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Expected battlepass to be viewable as it was on the initial battlepass release, the battlepass now specifically crashes the game

#### Steps for reproducing this issue:

1. Launch game
2. Click the battlepass icon or "view" below the icon
3. Game stutters and crashes

Here's the terminal output of the crashing: https://gist.github.com/Ori-Pixel/4a91eb37b95e77bf96e0a9fe4d22723a

edit: and one of the dmp files which i initially forgot: https://github.com/Ori-Pixel/public_files/blob/main/assert_20220901181333_43.dmp

**Comment by WillianJunior** [comment]
+1

**Comment by Shimanim** [comment]
+1

**Comment by israx** [comment]
+1

**Comment by WillMatthews** [comment]
Tried with both Vulkan and OpenGL options in the settings. Crashes instantly on clicking "View Battlepass".

**Comment by VladislavNekto** [comment]
+1, i use Linux (OpenSuse), native version. Crashes after really short moment opening Battle Pass

**Comment by AlcantaraMC** [comment]
+1

**Comment by VladislavNekto** [comment]
Fixed.

**Comment by Shimanim** [comment]
Fixed.

**Comment by Ori-Pixel** [comment]
@kisak-valve The issue is resolved on my end, battlepass loads correctly and does not crash the game.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
