### ISSUE TITLE
Mouse Cursor not trapped in fullscreen

### ISSUE THREAD

**Issue by SirFireball3521** [ValveSoftware/Dota-2#2120]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/SirFireball3521/201ac5186105ea43da6b5fb58f89d11b
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I have 2 monitors, I play Dota on the left one. Normally, when I move my cursor to the right edge of the screen, it stays there and does not continue onto my right monitor. However, since the battle pass update, it will sometimes not be trapped by the edge of the window. This is annoying because it causes me to click outside of the game, unfocusing it and forcing me to alt-tab back.

I have noticed that after alt-tabbing into the game it will work as expected until I click somewhere, after which it will stop working again.

#### Steps for reproducing this issue:

1. Open Dota in fullscreen on one monitor
2. Find match (or demo hero)
3. Click anywhere
4. Move mouse onto other monitor

**Comment by CaptainVal** [comment]
Yeah same is happening for me. Seems similar to issue 503.

**Comment by sundell7** [comment]
Same here. For me It seams that clicking right or left mouse buttons allows cursor to leave the screen. Going back it's trapped until next time i click, wich is a lot.

**Comment by tfhavingfun** [comment]
Same problem for me on Linux / DE: Gnome. Setting `dota_window_mouse_lock true` in console doesn't help.

**Comment by SirFireball3521** [comment]
Temporary solution: Turn off all side monitors. I really wish I had another option though

**Comment by tfhavingfun** [comment]
Issue is fixed for me with the latest update.

**Comment by nascheme** [comment]
Fixed for me with a recent update.  Was broken with Battlepass update.

**Comment by stryan** [comment]
Fixed for me

**Comment by sundell7** [comment]
Update fixed the problem for me as well.

**Comment by kisak-valve** [comment]
Closing per the last several comments.

**Comment by hippogaga** [comment]
Got this issue in 2024, it drives me crasy

**Comment by Rikard-Vedin** [comment]
> Got this issue in 2024, it drives me crasy
I have it too. Not sure when it started but It's so annoying having to disable my second monitor in order to play.

I'm on Fedora 39 and haven't experienced this in any other game so it seems dota related. Tried verifying game files and reinstalling.  Tried changing between full screen and borderless window but the mouse just never locks in the window.

**Comment by hippogaga** [comment]
> > Got this issue in 2024, it drives me crasy
> > I have it too. Not sure when it started but It's so annoying having to disable my second monitor in order to play.
> 
> I'm on Fedora 39 and haven't experienced this in any other game so it seems dota related. Tried verifying game files and reinstalling. Tried changing between full screen and borderless window but the mouse just never locks in the window.

Hey, I finally fixed this issue by updating my GEFORCE drivers to the latest version. Not sure if it fixes your problem.

**Comment by Rikard-Vedin** [comment]
> > > Got this issue in 2024, it drives me crasy
> > > I have it too. Not sure when it started but It's so annoying having to disable my second monitor in order to play.
> > 
> > 
> > I'm on Fedora 39 and haven't experienced this in any other game so it seems dota related. Tried verifying game files and reinstalling. Tried changing between full screen and borderless window but the mouse just never locks in the window.
> 
> Hey, I finally fixed this issue by updating my GEFORCE drivers to the latest version. Not sure if it fixes your problem.

That's great news! I hear the new nvidia drivers are doing wonders with Wayland as well. Fingers crossed!

**Comment by areebbbb** [comment]
Hey, This is still an issue
