### ISSUE TITLE
New battlepass 2022 crashing with Vulkan, not using proton

### ISSUE THREAD

**Issue by Shimanim** [ValveSoftware/Dota-2#2121]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/Shimanim/d68612e224f9c32e56845ab8397e15cb
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Open the 2022 Battlepass and my game crashes. Very easy to replicate, after restart pc, verify, update, still happens every time.

#### Steps for reproducing this issue:

1. Open Dota 2
2. click the battle pass
3. opens for a second, freezes and crashes.

**Comment by SJSalekin** [comment]
Same for me. Every time I try to view the BP rewards, dota crashes to desktop.

**Comment by Shimanim** [comment]
Realise someone beat me to this an hour ago but don't know how to delete this, sorry for the duplication.

**Comment by kisak-valve** [comment]
Hello @Shimanim, as you've noted, this issue is already being tracked at #2118. Closing as a duplicate.
