### ISSUE TITLE
DOTA 2 crash with Demo Hero

### ISSUE THREAD

**Issue by AlcantaraMC** [ValveSoftware/Dota-2#2122]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): **https://gist.github.com/MinminRepo/b2d2ff5311281b90572157a498407e03**
**https://gist.github.com/MinminRepo/3dee8cf81689b517c41b96629ac5c238**

* Have you checked for system updates?: [Yes/No] **YES**
* Are you using the latest stable video driver available for your system? [Yes/No] **YES**
* Have you verified the game files?: [Yes/No] **YES**

#### Please describe your issue in as much detail as possible:
DOTA 2 just randomly crashes, especially when I preview the latest Battle Pass.
I just updated to the latest version of dota 2 (battle pass as of the date of writing is included in this update). 
The game just craches randomly. A sure event though, that makes it crash is when I interact with the Battle Pass.

#### Steps for reproducing this issue:

1. Update to the latest version in the time of writing.
2. Start steam and dota 2.
3a. Click on battle pass or click "Preview". (Crashes).
3b. Go to "Demo Hero." (Crashes).

**Comment by kisak-valve** [comment]
Hello @MinminRepo, the battle pass related crash is already being tracked at #2118. Let's use this issue report to focus on the issue you're seeing with demoing heroes.

**Comment by AlcantaraMC** [comment]
Hi. For some reason, the demo hero issue resolved itself.
I have to re-download the entire game though. :(
Thanks much! :)

**Comment by kisak-valve** [comment]
Closing per the last comment and in favor of #2118.
