### ISSUE TITLE
Dota 2 Client stuck at boot/startup (Dota 2 logo screen) after the Battle Pass Update

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota-2#2123]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/deanrih/72da4722d51347c6a4322f1ba3b4804b
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system?: Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After the Battle Pass update the game is stuck when opened either from Steam or directly through dota.sh

The game was perfectly fine the day before, here is my last match id: 6735217136.

It is specifically stuck at the Dota 2 Logo Screen and nothing happened.

#### Steps for reproducing this issue:

1. Update the game
2. Verify the local files
3. Open the game either through Steam or directly

**Comment by sdarougheh** [comment]
Can confirm have the same issue.

**Comment by deanrih** [comment]
> #### Your system information
> * System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/deanrih/72da4722d51347c6a4322f1ba3b4804b
> * Have you checked for system updates?: Yes
> * Are you using the latest stable video driver available for your system?: Yes
> * Have you verified the game files?: Yes
> 
> #### Please describe your issue in as much detail as possible:
> After the Battle Pass update the game is stuck when opened either from Steam or directly through dota.sh
> 
> The game was perfectly fine the day before, here is my last match id: 6735217136.
> 
> It is specifically stuck at the Dota 2 Logo Screen and nothing happened.
> 
> #### Steps for reproducing this issue:
> 1. Update the game
> 2. Verify the local files
> 3. Open the game either through Steam or directly

False Positive,
For me it was because some app (I suspect EasyEffect) holding up some process/event thus Dota 2 was stuck at Logo Screen, I realize this when trying to open YouTube, its video player is stuck at the very beginning even though the buffer was already completed, and I began closing each running program until EasyEffect (weird delayed sound starts to play, like discord notification and sound effectss, and what I mean by delayed is, that notifications or sound effects audio should've been played minutes or even hours ago when I received the notification, not when closing the EasyEffect client, and all of them in an instant at that), then YouTube plays normally and of course now Dota 2, so I suspect EasyEffect with the aforementioned delayed sound being played is holding off some audio processing/event so YouTube (browser) and Dota 2 can't create or request Audio Device or at least waiting for the request to be completed resulting in 'hang'

I'll close this issue if there's no one else with this issue but a different cause or is not solved by the step I took.

**Comment by alandwiprasetyo** [comment]
I have same issue about this, please fix it

**Comment by Dzhug1** [comment]
I have the same issue on Mac.

Few tips from the testing journey I had:

1. Setting “-gl” in launch options helps to at least see the the Logo on a launch screen.
2. Adding “-novid” and “-safe_mode” did let me launch the game once and see a battle pass Report for a previous season.
3. but after I close the game - same workaround doesn’t work again.

**Comment by israx** [comment]
I have the same issue on Mac. Please give a quick solution

**Comment by nenadviranov** [comment]
same issue on Mac aswell, saw few posts on reddit aswell, i guess its a macOs issue, fix please.

**Comment by FanFanFantastic** [comment]
2018 macbook with no luck

**Comment by caijiong** [comment]
same issue on macOS. Fix please.

**Comment by dsrenesanse** [comment]
same issue on MacBook Pro 2017 with intel i5

**Comment by d3alexa** [comment]
iMac intel i7 isnt working as well.

**Comment by smh-freelancer** [comment]
same issue.
I'm using Hackintosh.
in Hackintosh big Sur, dota2 works correctly, but after the update to Monterey, dota2 not responding...

**Comment by JeffreyCheong** [comment]
Same issue

**Comment by israx** [comment]
any updates? The valve team hasn't said anything yet

**Comment by danginsburg** [comment]
I am furiously trying to repro but not having any luck so far on my test machines.  What would be helpful is if people on macOS could provide details Steam -> Help -> System Information.  Make sure Steam Client is up-to-date.  Also, could people report back if putting -nosteam on their Dota command line makes any difference?

**Comment by steven-le-thien** [comment]
Steam Client is up-to-date.
Putting -nosteam in launch option doesn't help (stuck at dota2 logo then not responding).
No external monitors, windowed mode.
Verified and reinstall from steam client as well.

Yesterday I managed to get pass loading screen (dota2 logo) once with the exact same setting, but game crash when I alt tab. Has not get passed loading screen again since (with same setting).

<details><summary>System info:</summary>

```

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro15,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.7 (64 bit)

Video Card:
    Driver:  Radeon Pro 555X
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x1002
    DeviceID:  0x67ef
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 12.99" x 8.11" (15.31" diag)
                                            33.0cm x 20.6cm (38.9cm diag)
    Primary VRAM: 4096 MB

Memory:
    RAM:  16384 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  1192614 MB
    Largest Free Hard Disk Block:  482299 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

```

</details>

**Comment by JeffreyCheong** [comment]
Same

**Comment by d3alexa** [comment]
<details><summary>System information</summary>

```
Computer Information:
    Manufacturer:  Apple
    Model:  iMac20,1
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    CPU Family:  0x6
    CPU Model:  0xa5
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3800 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 12.5.1 (64 bit)

Video Card:
    Driver:  AMD Radeon Pro 5500 XT
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x7340
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 23.39" x 13.15" (26.81" diag)
                                            59.4cm x 33.4cm (68.1cm diag)
    Primary VRAM: 8176 MB

Memory:
    RAM:  16384 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  9060901 MB
    Largest Free Hard Disk Block:  126010 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0
```

</details>

**Comment by idkhtcma** [comment]
Same problem on my mac, I can't go any further than logo screen. Is there anything helped so far out of starting preferences list or no solutions yet?

**Comment by atefth** [comment]
Same on mine, specs below:

macOS Monterey (v12.5.1 (21G83))
MacBook Pro (15-inch, 2018)
Processor 2.6 GHz 6-Core Intel Core i7
Memory 16 GB 2400 MHz DDR4
Graphics Intel UHD Graphics 630 1536 MB

**Comment by sfaragnaus** [comment]
Same issue here:

<details><summary>System information</summary>

```
Computer Information:
    Manufacturer:  Apple
    Model:  iMac12,2
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.13.6 (64 bit)

Video Card:
    Driver:  AMD Radeon HD 6770M
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x1002
    DeviceID:  0x6740
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.46" x 13.19" (26.89" diag)
                                            59.6cm x 33.5cm (68.3cm diag)
    Primary VRAM: 512 MB

Memory:
    RAM:  12288 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  915515 MB
    Largest Free Hard Disk Block:  836623 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0
```

</details>

**Comment by MaximBudnik** [comment]
Same issue on MacBook Pro (16-inch, 2019) Monterey 12.1

**Comment by ectudor** [comment]
I can play like before the BP update in mac m1 mini.

I just replaced -gl with -safe_mode. No other flags.

I also play with exclusive full screen.

**Comment by souljorje** [comment]
Same issue.

```
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro11,5
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.14.6 (64 bit)

Video Card:
    Driver:  AMD Radeon R9 M370X
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x1002
    DeviceID:  0x6821
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11" (15.31" diag)
                                            33.1cm x 20.6cm (38.9cm diag)
    Primary VRAM: 2048 MB

Memory:
    RAM:  16384 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  476902 MB
    Largest Free Hard Disk Block:  20217 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

```

Logs for ` ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh`:

```
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libengine2.dylib, got 0x7fa974d0c290
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/Users/jorje/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Users/jorje/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamID:  0, universe Public
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198183972289 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198183972289
SteamID:  76561198183972289, universe Public
SteamID:  0, universe Public
Setting breakpad minidump AppID = 373300
Loaded libSDL2-2.0.0.dylib, got 0x7fa977c11c90
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libtier0.dylib, got 0x7fa974c05e50
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libfilesystem_stdio.dylib, got 0x7fa977c38d20
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libinputsystem.dylib, got 0x7fa977b3b6c0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/liblocalize.dylib, got 0x7fa977b3bbd0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librendersystemgl.dylib, got 0x7fa977b4dc60
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librendersystemvulkan.dylib, got 0x7fa977b4d6d0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libresourcesystem.dylib, got 0x7fa977b559a0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libschemasystem.dylib, got 0x7fa977b560a0
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
[mvk-info] MoltenVK version 1.1.0. Vulkan version 1.1.154.
	The following 62 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v9
		VK_EXT_debug_utils v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_robustness2 v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v28
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: AMD Radeon R9 M370X
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x6821
		pipelineCacheUUID: 00002774-0000-2715-5D1E-B17068167C85
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
		macOS Read-Write Texture Tier 2
[mvk-info] GPU device:
		model: Intel Iris Pro Graphics
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x0d26
		pipelineCacheUUID: 00002774-0000-2714-5D1E-B17068167C85
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance with the following 4 Vulkan extensions enabled:
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_surface v25
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v28
[mvk-info] Using MTLFence for Vulkan semaphores.
[mvk-info] Created VkDevice to run on GPU AMD Radeon R9 M370X with the following 9 Vulkan extensions enabled:
		VK_KHR_create_renderpass2 v1
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_EXT_memory_budget v1
[mvk-info] Created 3 swapchain images with initial size (1440, 900).
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libmaterialsystem2.dylib, got 0x7fa95065b790
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libmeshsystem.dylib, got 0x7fa953022040
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libworldrenderer.dylib, got 0x7fa953085870
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libvscript.dylib, got 0x7fa9502eeb50
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libnetworksystem.dylib, got 0x7fa950643c50
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libanimationsystem.dylib, got 0x7fa9530ad3a0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libvphysics2.dylib, got 0x7fa950787ce0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libsoundsystem.dylib, got 0x7fa9507884f0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libscenesystem.dylib, got 0x7fa9507b15b0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libparticles.dylib, got 0x7fa9530bb840
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/bin/osx64/libserver.dylib, got 0x7fa953428ef0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/bin/osx64/libclient.dylib, got 0x7fa9507b2ef0
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libpanorama.dylib, got 0x7fa95360f040
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libpanorama_text_pango.dylib, got 0x7fa95320e310
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libv8system.dylib, got 0x7fa953732280
Loaded libmpg123.dylib, got 0x7fa9533fb130
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libfreetype.dylib, got 0x7fa95320dec0
Fontconfig warning: "/Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, got 0x0
 failed to dlopen "/Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib" error=dlopen(/Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, 9): image not found
Loaded libcairo.dylib, got 0x0
 failed to dlopen "libcairo.dylib" error=dlopen(libcairo.dylib, 9): image not found
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libengine2.dylib, got 0x7fa974d0c290
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/bin/osx64/libhost.dylib, got 0x7fa953614c90
Loaded /Users/jorje/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libscenefilecache.dylib, got 0x7fa953616490
```

**Comment by nonsense9** [comment]
MacBook Pro (15-inch, 2018) same issue

**Comment by shrakuma** [comment]
+1

**Comment by shrakuma** [comment]
Ok this is what works for me. 
1. removed all launch options from the general tab 
2. Set launch option to -gl and -safe_mode . 
3. Opened dota . It showed the logo but failed. Force quit 
4. Remove all launch options again and restart and it worked 

This will get you to the main screen and then things fail again

**Comment by o-shydlovskyi** [comment]
+1

**Comment by sfaragnaus** [comment]
renaming cairo.dylib into libcairo.dylib in ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game//bin/osx64 get rid of missing libcairo error, but game still not launching...

**Comment by mikeavvad** [comment]
i guess it's time to call volvo... https://www.volvocars.com/

**Comment by alfer-aws** [comment]
this is so silly...major release and they broke 2 OS plus some in game functionalities. Valve is not like a local butcher programming in his spare time so i would have expected a much higher quality. Very disappointing

**Comment by Zoktog** [comment]
More than 20 hours have already passed since the players reported the problem, but no one from the company contacted the players, did not fix it, did not admit the errors and did not inform about the timing of when they will fix it.

**Comment by steven-le-thien** [comment]
i suggest we take the rants to reddit and keep this place for actual constructive discussions

**Comment by Zoktog** [comment]
> i suggest we take the rants to reddit and keep this place for actual constructive discussions

Can you link to the discussion on reddit?

**Comment by SubhanHakverdiyev** [comment]
https://www.reddit.com/r/DotA2/comments/x3kp39/dota_compendium_update_wont_load_on_latest/

**Comment by shrakuma** [comment]
There has been no assignee to this issue and not even decent set of comments from anyone from valve prioritizing it. This is where companies like valve fail users and community. Shows the level of customer obsession they have

**Comment by israx** [comment]
> There has been no assignee to this issue and not even decent set of comments from anyone from valve prioritizing it. This is where companies like valve fail users and community. Shows the level of customer obsession they have

Yeah this is pretty disappointing.  No customer obsession at all. I was thinking to buy the battlepass  but with this problem no way I'm doing that.

**Comment by atif-rehman-ideofuzion** [comment]
Lucky for me because I won't be robbed for the same battle pass as the past 2 years at least.
Millions go into battle pass each year, hire two customer support people valve? If it's too expensive maybe try training the quality assurance people to test version upgrades or maybe fire the ones you have (if you have any) as it feels like only 2 devs are pushing Dota 2 updates.

**Comment by loinor** [comment]
its started 2 days from battle pass and problem still actual, gj, gj

**Comment by knigadima** [comment]
Hey. The same problem, Dota 2 not opening after battle pas 2022 update. Reinstalled Dota but it did not work :(

OS: macOS Catalina 10.15.7
Device: MacBook Air (13-inch, 2017)
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
Processor: 1,8 GHz double core Intel Core i5

@kisak-valve @ValveSoftware FYI

**Comment by israx** [comment]
@kisak-valve any updates? There has not been any response from Valve at all!

**Comment by kisak-valve** [comment]
Hello @israx, friendly reminder that I'm a moderator for Valve's issue trackers on Github and not a Dota 2 developer myself. We'll need to hear from a Dota 2 dev for any insight.

> There has not been any response from Valve at all!

This isn't true, however, as far as I know, there's nothing worth trying as a workaround at this point while we wait for a fix.

**Comment by danginsburg** [comment]
We've been working on it all day.  It's a really tricky problem with some low level memory allocator changes but I think we're coming to a solution.  It also didn't repro on most of our machines.

**Comment by Rasoulsa** [comment]
> I am furiously trying to repro but not having any luck so far on my test machines. What would be helpful is if people on macOS could provide details Steam -> Help -> System Information. Make sure Steam Client is up-to-date. Also, could people report back if putting -nosteam on their Dota command line makes any difference?


Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro9,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.7 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.22" x 7.01" (13.23" diag)
                                            28.5cm x 17.8cm (33.6cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  10240 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  238296 MB
    Largest Free Hard Disk Block:  16709 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

**Comment by akashsinghkunwar** [comment]
Its fixed. You can play on MAC now

**Comment by alandwiprasetyo** [comment]
Still got issue. dota force close when banned phase

**Comment by o-shydlovskyi** [comment]
Fixed for me.
Also this one is fixed with the latest update:
https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328

**Comment by kisak-valve** [comment]
Hello @alandwiprasetyo, please open a new issue report so that your issue can be tracked properly.

**Comment by MohmmadSawalha-ios** [comment]
Fixed for me on the latest patch. 
mac os - 12.5.1 
intel i7 chip.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
