### ISSUE TITLE
Linux OpenGL Dota doesn't get rendered right: Black map, no minimap

### ISSUE THREAD

**Issue by mhash1m** [ValveSoftware/Dota-2#2126]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/mHash1m/9b4d57bcc5e57a156ce1ddddf84cfa54
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Linux OpenGL Dota doesn't render graphics right. Screen is as if your whole view is fog. You dont see your portrait or items or levels of heroes. You cant see minimap. 

#### Steps for reproducing this issue:

1. Play or Watch a game on Linux with OpenGL

**Comment by kisak-valve** [comment]
Hello @mHash1m, this issue is already being tracked at #2119. Closing as a duplicate.
