### ISSUE TITLE
Mac OS bug, can not launch game

### ISSUE THREAD

**Issue by loinor** [ValveSoftware/Dota-2#2129]
Mac OS Monterey 12.3.1
MacBook Pro 15` 2019
Intel Core i9 2,3GHz
16GB
Intel UHD Graphics 630 1536 МБ

As soon as I start the game, a black screen appears and the game hangs, it does not start further, if you enter additional launch options (-gl, -safe), then it may move, but it will not reach the cut scene, it also crashes, I found a way that starts the game at least in the window, but this it also stopped working, and as soon as you open the battle pass, everything immediately crashes 
(-vulkan -autoconfig -safe -high -prewarm)
I bought BP, I can't play, it's been more than a day, and the reaction is 0, there are no explanations, there are not even guidelines for how long to wait, if the developers leave for the weekend now, full fiscal, the whole forum in steam is clogged with the fact that you broke the game on Mac OS and Linux, even on Windows the game cannot be minimized, otherwise it will fly out, give at least some guidelines when to wait for a fix

**Comment by Ruslanchyk01** [comment]
Та у Valve усім начхати на гравців. Коли це пофіксять, усі і далі продовжать грати в це сміття

**Comment by MohmmadSawalha-ios** [comment]
@kisak-valve  please advise all intel chip macbooks are blocked, any update on this

**Comment by kisak-valve** [comment]
Hello @loinor, this issue is already being tracked at #2117 / #2123. Closing as a duplicate.

Hello @MohmmadSawalha-ios, friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a Dota 2 developer myself. We'll need to hear from a relevant dev for any updates.
