### ISSUE TITLE
[Linux] Cannot select correct resolution after update

### ISSUE THREAD

**Issue by CommanderAlchemy** [ValveSoftware/Dota-2#213]
After some recent update recently I cannot longer select my resolution from the list. Tried also "use my monitor's current resolution" but it fails with the same resolution as in the picture below.

**_Forcing resolution**_ with launchoptions work however:
`-windowed -w 1920 -h 1080`

![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8509842/50d3e736-22be-11e5-834c-59266e0349a2.png)

**Comment by gdrewb-valve** [comment]
There's a fix coming for this.

**Comment by gdrewb-valve** [comment]
The July 8 update should address this, are you still seeing problems?

**Comment by CommanderAlchemy** [comment]
@gdrewb-valve It did change what resolutions I get, however its still not correct. 

![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8587022/a21148ba-25f6-11e5-9b11-7fe22554fb37.png)

**Comment by gdrewb-valve** [comment]
You want to use 1920x1080, correct?  What resolution is your desktop?  You won't see windowed resolutions larger than your desktop.  Also, if your window has a border it can't be the exact size of your desktop.

**Comment by CommanderAlchemy** [comment]
@gdrewb-valve My desktop is 3 monitors (1080x1920, 1920x1080*, 1920x1080)      *Primary

But yes you are correct after switching from Window to Borderless 1920x1080 appears in the list, (game did hang when i switched but that's another issue). Resolution below 1920x1080 behaved like Borderless Window while 1920x1080 seems to snapped to the monitor and behaves as a Fullscreen Window. (As intended i think)

**Comment by gdrewb-valve** [comment]
Correct, a monitor-sized borderless window functions as close to fullscreen as Reborn allows on Linux.

It sounds like things are all working as expected.  OK to close this?

**Comment by CommanderAlchemy** [comment]
@gdrewb-valve For me this is OK I already force the correct resolution through launchoptions because of #214, but other users may get confused not seeing their native resolution when set to windowed mode. (Don't think other games actually does this).

**Comment by gdrewb-valve** [comment]
At least the bugs preventing the resolutions from showing are fixed.

It's possible there will be confusion, we'll see how user feedback goes.
