### ISSUE TITLE
**Linux** Steam Dota2 with `-perfectworld` can't pay with store.steamchina.com

### ISSUE THREAD

**Issue by CroMarmot** [ValveSoftware/Dota-2#2135]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): Ubuntu 22.04.1 LTS https://gist.github.com/CroMarmot/8b3bbb39034f54c2f348c346b736e468 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I have already recharge money in **steamchina**, and have used money in dota in steam in **Windows** in year 2021

1. Enter Dota2 and click `buy TI11 BATTLE PASS`, the dialog show use **steam** wallet instead of **steamchina** wallet
 
![image](https://user-images.githubusercontent.com/24691835/188291460-3c983d3c-653e-4991-8937-51fe7e374e1e.png)

2. however when click `充值(recharge)` it jump to china steam which is `store.steamchina.com` 

![Screenshot from 2022-09-04 08-10-26](https://user-images.githubusercontent.com/24691835/188291530-9f09591c-95bb-4e91-83d3-0a3e1a240a85.png)

however in Windows11 instead of Ubuntu it can use **steamchina** wallet in first step

#### Steps for reproducing this issue:

0. config dota2 start parameter `-perfectworld`

1. Enter Dota2 and click `buy TI11 BATTLE PASS`, the dialog show use **steam** wallet instead of **steamchina** wallet

#### More Info

in china's forum , it looks like someone else with MacOS user also can't pay with steamchina : https://tieba.baidu.com/p/8000295875

#### What I expect

if with `-perfectworld` , it should be pay with `steamchina` and recharge with `steamchina` in Windows/Linux/MacOS

if without `-perfectworld` it should work as default, pay with `steam` and recharge with `steam` in Windows/Linux/MacOS

**Comment by kisak-valve** [comment]
Hello @CroMarmot, `In-game purchases on Mac and Linux will now use the updated purchase approval dialog` in the [2022-09-13](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3380537195892063927) Steam client beta update might help with this issue.

Please opt into Steam's client beta and retest this issue.

**Comment by CroMarmot** [comment]
Not work for me (Ubuntu 22.04), I have no mac computer so i can't test Mac

Game is updated and the version id is 9510145

![image](https://user-images.githubusercontent.com/24691835/190171519-b7b63cce-b61a-4bd0-be88-2b766994a962.png)

in Ubuntu with start parameter `-perfectworld`, when i click `buy battle level`, it open the dialog is still using **steam** wallet (which is the **unexpected** behavior), Same screenshot as the first image above

and click the recharge button, it is still jump to **steamchina.com** (which is the expected behavior with `-perfectworld`), Same screenshot as the second image above

---

and in windows with `-perfectworld`, when i click `buy battle level`, it just open in-game web browser and jump to steamchina (which is the expected behavior)

<img width="536" alt="屏幕截图 2022-09-14 215659" src="https://user-images.githubusercontent.com/24691835/190175324-ed5fb90e-0d67-4b2c-9a53-ba035974524f.png">

---

p.s.

I successfully purchased the "TI11 Battle Pass" on steamchina.com a few days ago, in **windows**, right after I opened this issue.

**Comment by kisak-valve** [comment]
Thanks for retesting.

Just in case something got lost in translation, can you double check the Steam client version (`Steam` -> `Help` -> `About Steam`)? I expect that you'll see a line with `Built: Sep 14 2022, at 00:06:33` and `Steam package versions: 1663116601` (may be newer date / higher package version if another Steam client update rolls out before you get a chance to check).

**Comment by CroMarmot** [comment]
![image](https://user-images.githubusercontent.com/24691835/190183200-846ec79c-3175-46d5-9713-3a4e12adf40a.png)

---

![image](https://user-images.githubusercontent.com/24691835/190183949-166b2ab1-f74b-419f-8995-82c6d3196912.png)

![image](https://user-images.githubusercontent.com/24691835/190184098-fd6cf7dc-50e8-4340-a427-72411c34a203.png)

**Comment by CroMarmot** [comment]
I've tried use the **beta version** steam client which is `1663116601`, and it works correctly, this bug is solved in Linux. I have no Mac computer. thx.
