### ISSUE TITLE
Failed to create an OpenGL context

### ISSUE THREAD

**Issue by Wusch** [ValveSoftware/Dota-2#2145]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Wusch/7770fd93a90a5edc2b14d4651b501e30
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After clicking on Play in Steam i get the error "Failed to create an OpenGL context."
![Bildschirmfoto vom 2022-09-15 21-48-39](https://user-images.githubusercontent.com/2745704/190495693-e3a82316-aa7d-492f-874b-142bc3bfa7d7.png)

Yesterday everything was fine.

**Comment by kisak-valve** [comment]
Hello @Wusch, looking at your system information, something's gone wrong with the Flatpak environment you're running Steam inside and there are no 64 bit OpenGL or Vulkan video drivers for Steam or Dota 2 to use.

**Comment by Wusch** [comment]
I installed steam from the steam website and it's working again. Thank you.

**Comment by sdhanraaj12** [comment]
hello, I am having the same issue. I have tried reinstalling steam as wusch did but it didn't work for me.
![Screenshot 2022-10-03 at 11 31 38 PM](https://user-images.githubusercontent.com/18560906/193647422-a196907c-5ed0-4761-bddd-ec1c50bc4c1f.png)
 can someone please help me with this issue?

**Comment by kisak-valve** [comment]
Hello @sdhanraaj12, the issue reported here is an OS-specific system config issue. #2099 is a closer match to the issue you're seeing.

**Comment by sdhanraaj12** [comment]
@kisak-valve Thanks for the quick reply, I restarted my system after reinstalling steam, and it fixed the issue. thanks

**Comment by kisak-valve** [comment]
Closing because this was a general video driver in Flatpak issue, and not Dota 2 issue.
