### ISSUE TITLE
[Linux] Quickly scrolling the mousewheel sometimes causes mouse4/mouse5 events

### ISSUE THREAD

**Issue by jomihaka** [ValveSoftware/Dota-2#215]
##### Operating System Version
- Linux (64 bit)
- Kernel Name:  Linux
- Kernel Version:  4.0.7-2-ARCH
- X Server Vendor:  The X.Org Foundation
- X Server Release:  11702000
- X Window Manager:  Xfwm4
- Steam Runtime Version:  steam-runtime-release_2015-01-06
###### Following system libraries used instead of steam-runtimes
- libgcc_s.so.1
- libstdc++.so.6
- libxcb.so.1
- libfreetype.so.6
##### Reproducing
- bind mouse4 "say test"
- bind mouse5 "say test2"
- Spam your mousewheel up & down as quickly as possible.
##### Notes

Cannot be a mouse issue, since it doesn't happen in desktop applications like browser and xinput --test doesn't show relevant buttons being pressed. Same as csgo issue 307 and happens in normal dota2, too.

**Comment by gdrewb-valve** [comment]
This appears to be an issue in SDL, we're following up with the SDL devs.

**Comment by Gordon01** [comment]
Same for me

**Comment by budimanjojo** [comment]
It also happens in the main menu. To reproduce try scolling the custom games lobby list quickly. It will go back and forward the menu opened

**Comment by gdrewb-valve** [comment]
SDL bug #2987.

**Comment by gdrewb-valve** [comment]
The SDL devs have fixed this and the 8/14 update has the updated SDL.  Are you still seeing this?

**Comment by jomihaka** [comment]
Yes, still happens.

/proc/<pid>/maps shows this sdl is being used: ~/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0

**Comment by gdrewb-valve** [comment]
That's the right libSDL.  Can you check the time and size of that file?

**Comment by jomihaka** [comment]
size: 1080019
date: 14. 8. 04:02
md5sum: ded718e3a36c3dc580aa938e7f982b74

**Comment by gdrewb-valve** [comment]
That's the latest file.  I'll let the SDL devs know that their fix may not have worked.

**Comment by gdrewb-valve** [comment]
Can you try once more after the 8/18 Reborn update?

**Comment by jomihaka** [comment]
Seems to be fixed now. Please update csgo, too.

**Comment by gdrewb-valve** [comment]
Thanks.  I'll let the CS:GO team know but it's up to them to get the fix.
