### ISSUE TITLE
Pop!OS game client crashes after launch

### ISSUE THREAD

**Issue by hardy-ta** [ValveSoftware/Dota-2#2151]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/hardy-ta/1294785c8246c18fda9a1c22259f9562): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I know there are many issues of this type but I tried many things from different issues of this type and none worked. Seems like there is no unique solution.
When I click play, the client starts, I can see the DotA logo and soon after my cursor changes to ingame cursor. Pop!OS warns me that 'steam_app_570' is not responding. I can wait or force quit. I tried clicking wait and I tried just doing nothing at all- same outcome for both. Just as the DotA logo disappears, the game crashes. I'm using Proton Experimental, but I have tried Proton 7 as well. Neither worked. I would have liked to add the logs, but I don't know where to find them. If you can point me there, I'll gladly add that later.

#### Steps for reproducing this issue:

1. Literally every time I start DotA 2 it crashes right before it gets to the main menu
2. 
3.

**Comment by kisak-valve** [comment]
Hello @hardy-ta, running Dota 2 with the Proton compatibility tool is not supported and issues with that configuration are not tracked in this issue tracker. Please use the native linux variant of the game.

**Comment by hardy-ta** [comment]
that fixed it. I had the checkbox set for 'force use of a specific compatibility tool' and disabling that fixed it
