### ISSUE TITLE
[Linux] Enhancement: Either implement a check to not make me "Custom Lobby Host" or forbid it when I set "Network Quality" to "Low"

### ISSUE THREAD

**Issue by shaddow2k** [ValveSoftware/Dota-2#216]
Right now there is no control over becoming lobby leader in a custom game. While I have a powerful PC, my internet connection is quite limited. Either implement a checkbox to disable becoming lobby host or make it bound to the network quality setting low. Thoughts?

**Comment by gdrewb-valve** [comment]
Sounds reasonable to me.  This isn't a Mac/Linux issue but I'll pass it on to the larger team.

**Comment by gdrewb-valve** [comment]
Closing as won't be tracked here.
