### ISSUE TITLE
Dota fails to start on latest nvidia stable driver. Stuck on dota logo.

### ISSUE THREAD

**Issue by astroty** [ValveSoftware/Dota-2#2170]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
 https://gist.github.com/astroty/5ed13f12bedd9c3ce61951272c9cfb71
* Have you checked for system updates?: [Yes/No]
 Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Dota 2 stays stuck on the dota logo, displaying the game's cursor. Alt tabbing the screen makes it visible that the game isn't working, as it just reflects what was on top of it instead of redrawing the image again.

#### Steps for reproducing this issue:

1.  Start Dota 2 on the latest nvidia driver on Vulkan mode
2.  See your game fail to start, getting stuck after the cursor changes to the ingame cursor 

Additional information:
This issue is present in Nvidia drivers 515.49.19 (Vulkan beta) and 520.56.06 (Latest driver released). This issue wasn't present in the previous stable driver 515.76. This leads me to believe some modification on the vulkan beta driver, that wasn't on the 515.76 stable, lead to the game being unable to launch on it. And that change was then upstreamed to stable.

The game boots with the -gl flag, leading me to believe that it's a vulkan specific issue

Error code obtained from DKMS: ``[15226.831633] NVRM: Xid (PCI:0000:01:00): 69, pid=97800, name=dota2, Class Error: ChId 0141, Class 0000b197, Offset 00002380, Data 00000000, ErrorCode 00000004``

Dota.sh log: https://gist.github.com/astroty/b0aacf1c71befe2557884c08cc714663

**Comment by kisak-valve** [comment]
Hello @astroty, this reads like the issue being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/413. Can you check if setting the game's launch options to `-vulkan_disable_graphics_pipeline_library` works around the issue?

**Comment by asserh** [comment]
I have the same issue, I updated to Nvidia driver 520.56.06 and Dota would no longer launch. I can confirm that adding ` -vulkan_disable_graphics_pipeline_library ` in launch options fixes the problem.

**Comment by astroty** [comment]
I can confirm that this launch option makes the game able to launch again.

**Comment by kisak-valve** [comment]
Thanks for checking, closing in favor of https://github.com/ValveSoftware/Dota-2-Vulkan/issues/413.
