### ISSUE TITLE
Linux: game won't pass the dota 2 logo

### ISSUE THREAD

**Issue by andrelbc** [ValveSoftware/Dota-2#2175]
#### Your system information
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/andrelbc/c3762883f1e447e18db20c546755a24f): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Today the game started to close right after the dota 2 logo appears(can't even reach the menu). This is happening with -vulkan or -gl as launch options, I also tried reinstalling the game and tried with the steam official package and the flatpak one.
When I run the game with proton, it is a bit delayed but still happens.

#### Steps for reproducing this issue:
1. Go to steam library
2. Select Dota 2
3. Click on the Play button

EDIT: unplugging my xbox controller did the trick lol. I don't now why, but if my controller is plugged the game starts to crash apparently .

**Comment by maplepy** [comment]
No controller plugged in here but I still can't go pass the dota 2 logo loading screen

**Comment by maplepy** [comment]
Using `-vulkan_disable_graphics_pipeline_library` fixed the issue for now

**Comment by dmolin93** [comment]
Same issue with no controller plugged in, can confirm that with `-vulkan_disable_graphics_pipeline_library` the game works

**Comment by kisak-valve** [comment]
Hello @maplepy, @dmolin93, your issue is being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/413 and is unrelated to this issue report.

**Comment by maplepy** [comment]
> Hello @maplepy, @dmolin93, your issue is being tracked at [ValveSoftware/Dota-2-Vulkan#413](https://github.com/ValveSoftware/Dota-2-Vulkan/issues/413) and is unrelated to this issue report.

Not exactly

1. we (at least I) don't have these launch parameters
2. my issue is from a day ago, not from the 9th of June
3. I didn't enabled VK_EXT_graphics_pipeline_library extension support

**Comment by samuelborn** [comment]
`-vulkan_disable_graphics_pipeline_library` did help. Thank you.

**Comment by Dramcryx** [comment]
I'm sure this is something related to either 6.0 kernel or mesa update. I've been sitting on Arch w/o updates for ~25 days and it worked. I updated today and it also fails for me w/o `-vulkan_disable_graphics_pipeline_library` key. And I also have Nvidia GPU unlike author.

UPD: Oh, actually https://github.com/ValveSoftware/Dota-2-Vulkan/issues/413 is exactly about the issue

**Comment by Cuniq** [comment]
I'm on Manjaro, 5.15 kernel and latest nvidia proprietary drivers. Haven't played for couple months but was working fine before. The only things that have changed are nvidia drivers and dota 2 updates. 
`-vulkan_disable_graphics_pipeline_library` solves it tho

**Comment by krasende** [comment]
having the same issue on
```
kernel: 6.0.6-1-MANJARO x86_64
cpu: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
gpu: NVIDIA GeForce GTX 1060 6GB
driver version: 520.56.06
```

solved for now with `-vulkan_disable_graphics_pipeline_library`

**Comment by maplepy** [comment]
Thanks I covered the command already, no need to spam comments about it thanks

It just adds comments that devs will have to read for nothing and notifies users who commented.

**Comment by samuelborn** [comment]
I had the Issue on Fedora 36 with Nvidia Graphics and xorg (fixed by the given command here).
Now on Fedora 37 with same setup but Kernel 6.0.8-300.fc37.x86_64 everything works fine again.

**Comment by maplepy** [comment]
> everything works fine again.

so it works without the argument ?

**Comment by samuelborn** [comment]
Yes. I don't need the argument anymore.

**Comment by maplepy** [comment]
Great thanks! @andrelbc you may close the issue if its working back to normal

**Comment by KevinH2810** [comment]
issue re arise for me, 
command `-vulkan_disable_graphics_pipeline_library` didn't solved the issue but `-gl` solved it for now,
but still the graphics and frame rate is kinda suck 

Macbook M1 OS VEnture 13.1 16GB Ram
