### ISSUE TITLE
Unused hotkeys act as if they were set to their default binding

### ISSUE THREAD

**Issue by nixi-awoo** [ValveSoftware/Dota-2#218]
Let us take item bindings for instance.
These are the hotkeys I use:

![hotkeys](http://i.imgur.com/tLQw16D.jpg)

Notice that I do not have B or N assigned to anything. Those unassigned keys work as if they were set to default and activate items set to C and V. Both keys C (set by me) and B activate any item in slot 5.

I use B for my Mumble PTT and I accidently activate items because of this. Other keys work fine since they are assigned by me and only the keys that are unused and are binded by default to something are doing this.
## 

_x86_64 Linux 4.0.7-2-ARCH_

**Comment by davidw-valve** [comment]
I am afraid I cannot immediately reproduce this. I set the bottom-middle item with C as its hotkey and did not assign B to anything else. Pressing C activates the item, B does nothing for me.

Are there any more specifics to this bug that you can think of that might enable me to reproduce it? Does it happen every time for you or just sometimes?

**Comment by nixi-awoo** [comment]
Actually, I seem to have fixed it by simply rebinding everything from scratch. It used to happen all the time: In custom gamemodes, normal matches and in the hero showcase as well. 

The issue might have been caused by an import of my configuration from the Source 1 version of Dota.

**Comment by davidw-valve** [comment]
Okay. Since we don't have any clarity as to why this happened I am going to close out the bug. If you reproduce it in future please file a new bug report and we can try to get it fixed!

**Comment by nixi-awoo** [comment]
@davidw-valve 

A small update: 
A friend of mine just told me that he has the same problem on his Windows machine. 
Perhaps this is not a Linux-only issue afterall.
