### ISSUE TITLE
Linux Mint 20.3 DOTA 2 exits after processing Vulkan shaders...no errors or complaints

### ISSUE THREAD

**Issue by midigark** [ValveSoftware/Dota-2#2182]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/midigark/dfcd9162f547fe502b81bb7b50659965
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]   The recommended release from LM
* Have you verified the game files?: [Yes] I have  also wiped Steam and all Steam files and reloaded everything, twice._

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Expected DOTA   2 to start.
Watched blank  screen as DOTA 2  exited the  process list after processing the  Vulkan Shaders with  no errors or obvious complaints.

#### Steps for reproducing this issue:

1. Start DOTA 2
2. Watch Vulkan Shaders process
3. Watch as DOTA 2 exits from process list after shaders process
There are no error messages or complaints of any kind,
Other  Linux  games work

p.s. Valve sent me here after reviewing the data  and complaint.
(hot potato, hot potato...)

**Comment by kisak-valve** [comment]
Hello @midigark, your video card does not support Vulkan, and your NVIDIA 340 series video driver is expected to have encountered the same issue as https://github.com/ValveSoftware/steam-runtime/issues/420.

Sorry, but even if you updated to the NVIDIA 390 series video driver, which is the last driver series to support your video card, you'd still encounter that issue.

Closing in favor of the older issue report.

**Comment by midigark** [comment]
> Hello @midigark, your video card does not support Vulkan, and your NVIDIA 340 series video driver is expected to have encountered the same issue as [ValveSoftware/steam-runtime#420](https://github.com/ValveSoftware/steam-runtime/issues/420).
> 
> Sorry, but even if you updated to the NVIDIA 390 series video driver, which is the last driver series to support your video card, you'd still encounter that issue.
> 
> Closing in favor of the older issue report.

Well, ya know it might be a good idea for someone to take a look at the minimum system requirements so we users can waste our valuable time elsewhere doing other stupid stuff.
It cited FX series Nvidia cards, probably worked. Didn't someone ax the OpenGL driver mode for this program?

**Comment by kisak-valve** [comment]
Dota 2's OpenGL render path on Mac and Linux is deprecated, but not yet removed at this point. The issue you encountered is with the setup of the Steam Linux Runtime container environment which Dota 2 is run inside, instead of Dota 2 itself, and that only affects some legacy and proprietary NVIDIA driver series.
