### ISSUE TITLE
Does not work Dota 2 Workshop Tools

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#2185]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Does not work Dota 2 Workshop Tools, they just close (checked on several computers)

#### Steps for reproducing this issue:

1. Open Dota 2 Workshop Tools

**Comment by kisak-valve** [comment]
Hello @vladhvorost, this issue tracker is limited to issues with the Mac and Linux client of Dota 2. Dota 2 Workshop Tools is only available on Windows, noted at https://github.com/ValveSoftware/Dota-2/issues/305#issuecomment-139794936, which makes this issue out of scope for this issue tracker. If you're using Windows, I would recommend reporting your issue through [Steam Support](https://help.steampowered.com/).

**Comment by ghost** [comment]
@kisak-valve Sorry, but in support there are only the items "I have problems with items" and "not in the library", and dota tools broke literally after yesterday's DireTide update, and I asked my friends if they don't work for them either, although everything worked before this update , file integrity check doesn't help, dota just crashes without any errors

**Comment by baaannnaaannn** [comment]
pls add a linux version
