### ISSUE TITLE
Dota 2 Audio Crackling with High DAC Sample Rate

### ISSUE THREAD

**Issue by PS1TD** [ValveSoftware/Dota-2#2186]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/PS1TD/4f5adc07dd4402ad3a684e7d43aa696d): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 Audio started crackling after the BP2 update.
I narrowed down the issue to running your audio DAC with anything higher than 32bit 48kHz.
Here is the output from souninfo:

```
[SoundSystemLowLevel] SDL Audio Device: #OS_Default_Device (status: 1, driver: wasapi)
[SoundSystemLowLevel] Channels:	2
[SoundSystemLowLevel] Bits/Sample:	32
[SoundSystemLowLevel] Rate:		384000
[SoundSystemLowLevel] Status:		7350, 6757 (mix channels:2)
[SoundSystem] Device active: 78.45s.  Active Voices: 2
[SoundSystem] Catch up mixing failed: 1 times
[SoundSystem]   0: sounds\music\valve_ti5\music\ui_startup_01.vsnd (80000001 :: 80000001)  [74.2s]
[SoundSystem]   1: sounds\ui\menu\shortwhoosh.vsnd (80000027 :: 80000027)  [0.7s
```

Catch up mixing fails different amount of times depending on which menu I run the command in.

#### Steps for reproducing this issue:

1. Set DAC sample rate to anything higher than 48kHz in windows audio settings.
2. Launch Dota

**Comment by PS1TD** [comment]
The issue also causes frame drops and sometimes speeds up/slows down audio.
I have to set my DAC to lower rate therefore decreasing audio quality from other applications.
I double checked that my DAC indeed supports 384kHz and it does. Works in everything but Dota.

**Comment by paboum** [comment]
Same on Linux, build ID 9895872.

**Comment by paboum** [comment]
5 days and no fuck was given. What is the SLA for this paid service support?

**Comment by paboum** [comment]
Build ID 10092296, I'm uninstalling this game and buying my xmas package on gog.

**Comment by ilyanep** [comment]
I think I might be experiencing this issue on Windows as well. Definitely been having a crackling issue for a few months now and I have my audio device set to 32-bit, 192khz

EDIT: I'm able to confirm that switching the device to 32-bit, 48khz resolves the issue. As previous reporters have said, I'd rather not lower the bitrate for the sake of DotA sound working.

BTW, the crackling is sporadic both in game and in the menus, but I think specific sounds might trigger it. One way I've found that does it pretty reliably is to watch the promo animation for the Conduit of the Blueheart set.

**Comment by dorinstratulat** [comment]
Hi,

OS: Windows 11 PRO
DAC Fiio NEW K3

With 32-bit 384k, I got the crackles. I then tried with 32-bit 48khz and this indeed solved the issue. 
Then, I tested different settings and found out that up to **32-bit 192k** the crackles are gone in my case.

**Comment by Kakaowydziubek69** [comment]
I got same problem after Greveling update and still no one fix this, before this patch everything works well. No one fix it in last 3 months. I got creative g6 and like said before its unplayble higher then 48khz bitrate cause sound is poping. I make a movie about it so maybe you got a same type of sound issue as me. Of course windows, drivers and dota is updated. https://www.youtube.com/watch?v=Pth7-uGrZx8

**Comment by Kakaowydziubek69** [comment]
Ok i think now its fixed

**Comment by ilyanep** [comment]
I agree it seems fixed for me from a very quick test. Tried:
- Main menu for about 20 seconds
- Demo mode (including maxing level on Luna and using her ult) for about a minute
- Clicking into the expired battlepass and watching the Conduit of the Blueheart demo as above

Didn't hear any noticeable crackling. Thanks to the dev team for taking a look!

**Comment by Kakaowydziubek69** [comment]
> I agree it seems fixed for me from a very quick test. Tried:
> 
> * Main menu for about 20 seconds
> * Demo mode (including maxing level on Luna and using her ult) for about a minute
> * Clicking into the expired battlepass and watching the Conduit of the Blueheart demo as above
> 
> Didn't hear any noticeable crackling. Thanks to the dev team for taking a look!

I put a lot of effort into fixing this problem. I advise you to write to valve right away, social steam forums are useless
 But ye good something read our problems nad fix it. Dota has really nice sound.

**Comment by PS1TD** [comment]
Can confirm - IS FIXED!
Finally high quality music in the background while playing high quality Dota👌

**Comment by Kakaowydziubek69** [comment]
I spend some time on testing with my budget audiophile gear audio technica ath550z and creative g6. And thats what i can said. Orginal dota theme work perfect, sound of games works great. But there is only one problem with "Battle pass 2022 music pack" I still hear cracking sound in this music pack, 95% players never hear that but in my opinion its not so good recorded like orginal music or there is another problem, dunno. If you dont trust me look in test map, pick this music pack and disable other sounds. Btw i search this 2022 music theme on youtube and it sound ok, so this is still problem in game.

**Comment by PS1TD** [comment]
Ill test the bp music tomorrow with my setup.

**Comment by dorinstratulat** [comment]
> Hi,
> 
> OS: Windows 11 PRO DAC Fiio NEW K3
> 
> With 32-bit 384k, I got the crackles. I then tried with 32-bit 48khz and this indeed solved the issue. Then, I tested different settings and found out that up to **32-bit 192k** the crackles are gone in my case.

Hey guys!

I can confirm that this is fixed for me as well! I have opened a ticket to Valve on Feb 12th and I hope this helped our cause!
![WhatsApp Image 2023-02-26 at 11 01 03](https://user-images.githubusercontent.com/29310583/221715941-f206a7c8-902c-4824-8070-de036928fcce.jpeg)

**Comment by PS1TD** [comment]
I have tested the 2022 Battle Pass music and I have no crackling.

**Comment by Kakaowydziubek69** [comment]
> I have tested the 2022 Battle Pass music and I have no crackling.

Lol This game to start me mad i just bought "TheFatRat - Warrior Songs music pack" and has same problem. Its valve fault, i make another movie about it its same problem like before but only with music packs. You need headphones to listen this cracking. i listen on 32/384khz but problem is on any quality. https://www.youtube.com/watch?v=IARRO0wFeq8

**Comment by paboum** [comment]
Seems fixed for me too. And since 40k cheaters were banned, I immediately won two games in a row after months of no training. Will give this game another chance.

**Comment by Kakaowydziubek69** [comment]
> Seems fixed for me too. And since 40k cheaters were banned, I immediately won two games in a row after months of no training. Will give this game another chance.

To bad i left 2 times in a row and they give me punish. Of course it was my fault. They want me to WIN 4 games, i play week and i cant won those 4 games. You will ask why? Becouse they send me guys all time who pick 4 carrys, or a guys who left at begin and i cant even left and search another match cause valve matchmaking system dont let you leave a match even when someone not playing 30 min.  I play dota as a fun but after this ban for 4 games its pure suffer. Btw some soundpacks are still bugged as i said, its not big problem, some works perfect, orginal soundtrack works perfect so you can pick orginal and enjoy good audio. I lost motivation to play it on my orginal account.

**Comment by paboum** [comment]
Regression with the latest update. Build ID 10723004.

**Comment by paboum** [comment]
Had to work around these losers:
In `/etc/pulse/daemon.conf`:
```
default-sample-format = s16le
default-sample-rate = 48000
```
Then `pulseaudio -k` and restart dota.

**Comment by Kakaowydziubek69** [comment]
Did someone has a rattling sound in that muerta patch when you need to make a "deal" with someone and you got this new sound who ratling or cracking i dunno?

**Comment by PS1TD** [comment]
Yes, I have the same problem as well even with low bitrate. It seems like those sounds are just recorded like that.

**Comment by Kakaowydziubek69** [comment]
> Yes, I have the same problem as well even with low bitrate. It seems like those sounds are just recorded like that.

So new sound guys in valve from dota 2 dont do their job well. Still fatrat sound pack and compendium 2022 have same problem as i type in previous post. In my opinion its not problem with bad recorded sound, its bad implementation. People said when you make this thread you can fix it when you set 32/48khz, in my opinion you just dont hear this problem cause lower detailts but problem was even on 48khz.  Of course its just one sound and only 2 soundpacks but someone need make more care about it. New patch with new sounds=new problem.  It hurt me cause fatrat pack and compendium 2022 was my favorite and was a reason why i bought all soundpacks possible.

**Comment by Artekkor** [comment]
I don't know if i'm experiencing the same issue as you lads, but this has been haunting me for months now.
EVERYTHING fucking crackles in this game. Any other game? Perfect smooth sound, but DOTA is driving me insane. Its not, like, horrible that it makes it intolerable - but i can CLEARLY hear it.

And btw? Apparently my sound is 16 bit 48hz. So the only solution mentioned in this thread doesn't even work for me.
I do not know what's wrong with this game.

**Comment by Kakaowydziubek69** [comment]
> I don't know if i'm experiencing the same issue as you lads, but this has been haunting me for months now. EVERYTHING fucking crackles in this game. Any other game? Perfect smooth sound, but DOTA is driving me insane. Its not, like, horrible that it makes it intolerable - but i can CLEARLY hear it.
> 
> And btw? Apparently my sound is 16 bit 48hz. So the only solution mentioned in this thread doesn't even work for me. I do not know what's wrong with this game.

You can record it in game by nvidia experience so we can see do you got same problem like us
