### ISSUE TITLE
Dota 2 crashes playing diretide constantly in team fights or on big spells

### ISSUE THREAD

**Issue by mhash1m** [ValveSoftware/Dota-2#2187]
#### Your system information

* System information from steam : https://gist.github.com/mHash1m/9b4d57bcc5e57a156ce1ddddf84cfa54
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system: Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Dota 2 crashes playing diretide constantly in team fights or on big spells.

#### Steps for reproducing this issue:

1. Find match in diretide
2. got to team fights
3. DC
4. Feed
5. Reconnect
6. repeat step 2

**Comment by kisak-valve** [comment]
Hello @mHash1m, this issue is already being tracked at #2184. Closing as a duplicate.
