### ISSUE TITLE
Mac M1 FPS is unbearable after update | FPS Spikes

### ISSUE THREAD

**Issue by alindumitruffgroup** [ValveSoftware/Dota-2#2191]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1.  System information
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro18,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  VirtualApple
    CPU Brand:  Apple M1 Max
    CPU Family:  0x6
    CPU Model:  0xc
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2400 Mhz
    10 logical processors
    10 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 13.0.0 (64 bit)

Video Card:
    Driver:  Apple M1 Max
    Driver Version:  227.2.40
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 120 Hz
    VendorID:  0x106b
    DeviceID:  0x0
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 13.58" x 8.74" (16.14" diag)
                                            34.5cm x 22.2cm (41.0cm diag)
    Primary VRAM: 32768 MB

Memory:
    RAM:  32768 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  949197 MB
    Largest Free Hard Disk Block:  392274 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

2. Yes, the system is up to date. I have a mac, there isn't much I can do about drivers.
3. Yes

For regular games I am averaging at 70 FPS, down from 100ish. This wouldn't be a problem if I would not get constant FPS spikes whenever spells are casted.

For Diretide is even worse. Like the spike are constantly, it's unplayable. If I add the Diretide shader, the game becomes.. unplayable.

**Comment by legcan** [comment]
I think this is fixed now? When BP2 was released my fps was low and frames were terrible even with graphics on low! 

It seems to be playable now but I haven't changed the graphics settings back

**Comment by kisak-valve** [comment]
Closing per the last comment.
