### ISSUE TITLE
Dota 2 always crash in massive fights. Debian 11/12

### ISSUE THREAD

**Issue by koreanfan** [ValveSoftware/Dota-2#2196]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): debian 11, debian 12, fx-8300, rx560, 8gb ram
* Have you checked for system updates?: [Yes/No] yes
* Are you using the latest stable video driver available for your system? [Yes/No] yes
* Have you verified the game files?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. launch dota with opengl renderer
2. start match
3. dota crash in massive fights
4. relaunch dota
5. reconnect to the match
6. dota crash in massive fights
7. reconnect to the match
8. dota crash in massive fights
9. etc

**Comment by adrfantini** [comment]
Probably a duplicate of #2184

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
