### ISSUE TITLE
OS X: Game does not start full-screen

### ISSUE THREAD

**Issue by yaakov-h** [ValveSoftware/Dota-2#22]
The menu bar and dock are still visible. I tried clicking on the game surface and on the dock icon, but the menu bar and dock remained.

Given that the minimum requirements for Reborn is OS X 10.9, it would be nice if Source could use the new fullscreen mode that was introduced in OS X 10.7.

![screen shot 2015-06-23 at 2 58 08 pm](https://cloud.githubusercontent.com/assets/426009/8300400/d8b15e4a-19c7-11e5-9974-092d0fd96807.png)

MacBook Pro (Retina, 13-inch, Late 2013) / MacBookPro11,1
OS X Yosemite Version 10.10.3 (14D136)

```
Intel Iris:

  Chipset Model:    Intel Iris
  Type: GPU
  Bus:  Built-In
  VRAM (Dynamic, Max):  1536 MB
  Vendor:   Intel (0x8086)
  Device ID:    0x0a2e
  Revision ID:  0x0009
  Displays:
Color LCD:
  Display Type: Retina LCD
  Resolution:   2560 x 1600 Retina
  Retina:   Yes
  Pixel Depth:  32-Bit Color (ARGB8888)
  Main Display: Yes
  Mirror:   Off
  Online:   Yes
  Built-In: Yes
```

**Comment by wliment** [comment]
i have the same problem  state dota2 reborn with a menu bar 
macbook pro  late 2014  
OS X Yosemite Version 10.10.3 
nvidia 750m video card

**Comment by danginsburg** [comment]
I have this repro'd here, I will investigate and fix.

**Comment by danginsburg** [comment]
So I think the issue here is that it starts in Borderless Window mode and not Fullscreen, is that what you are reporting?  Can you confirm that the dock and menubar clear when you switch from Bordeless Window -> Fullscreen in the video settings?

**Comment by yaakov-h** [comment]
I can confirm that if I switch from Borderless Window to Fullscreen, the dock and menubar clear.

Unfortunately I can't use Mission Control when fullscreen like I can with other fullscreen apps, but it is working to the same standard as Source 1.

**Comment by gdrewb-valve** [comment]
The next release will switch things so a monitor-sized borderless window will take over the screen.

**Comment by gdrewb-valve** [comment]
How are things working after the 6/26 update?

**Comment by yaakov-h** [comment]
I killed video.txt and it started monitor-sized borderless and is working as expected. Thanks, Drew!
