### ISSUE TITLE
Crash on voice

### ISSUE THREAD

**Issue by bananarne** [ValveSoftware/Dota-2#2202]
Hey,

DotA 2 crashes(and steam with it) whenever use voice with the most recen steam version. [36682.433158] CIPCServer::Thr[18417]: segfault at 0 ip 00000000f721677f sp 00000000df1fd0b0 error 4 in libunwind.so.8.0.1[f7214000+9000]
[36682.433167] Code: c4 10 85 c0 0f 88 96 db ff ff 83 ec 08 56 8d b4 24 c8 01 00 00 56 e8 50 db ff ff 83 c4 10 85 c0 0f 88 7a db ff ff 8b 44 24 14 <c5> fa 7e 00 8b 78 0c 8b 40 10 83 ff 01 19 ed 89 44 24 18 8d 44 24.

**Comment by bananarne** [comment]
closing this, because this seems to be a steam / environment issue rather than a dota issue

**Comment by JakeTheSnake** [comment]
@bananarne can you elaborate on this please? I'm experiencing the same issue. Game and steam also crashes when I open settings.

**Comment by bananarne** [comment]
@JakeTheSnake uhm, i just checked yesterday and i am still having this issue. I got around it by using the flatpak version of steam & deactivate steam play in it (even though dota2 doesn't use it, but it it influences the runtime-container stuff of steam, which is another issue). 

https://github.com/ValveSoftware/steam-for-linux/issues/8930

**Comment by JakeTheSnake** [comment]
@bananarne thanks! I opted out of steam beta like mentioned in the thread you linked, and now it works fine again.
