### ISSUE TITLE
Weird rainbow like thing when using voice chat to team

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#221]
![2015-07-08_00001](https://cloud.githubusercontent.com/assets/13085918/8566171/6b87882e-2586-11e5-86ce-27b8f11daf35.jpg)
I don't know how did I get it, only happen in one game but it stays there whenever I use voice chat in that game.

**Comment by gdrewb-valve** [comment]
We'll need to try and find a repro to get more information.

**Comment by Tele42** [comment]
@budimanjojo, what video driver are you using?

**Comment by budimanjojo** [comment]
I'm using nvidia gtx970 with the latest driver on Manjaro Linux

**Comment by budimanjojo** [comment]
Closing this issue since it's not happening again
