### ISSUE TITLE
[OpenSuse] Completly Unstable

### ISSUE THREAD

**Issue by VladislavNekto** [ValveSoftware/Dota-2#2210]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/VladislavNekto/b8f0b7accfd1a247f51bb8b96f4e98ec): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Hey. Why dota UNSTABLE on X11, on Waylang, on GL, on Vulkan, in Gamescoup, without it, with args, without args. Why? It's has been REALLY stable, while i don't update whole system (with nvidia driver) and, i think, it's not system related problem, because everything else works just fine. I got ban in search and couple Low Priorite games because game very often crashes in Pick Phase. I am beta tester and even got banned, lol.

It's usually not crashes in menu, in demo hero, but crashes in staff that related to steam overlay (disabled, crashes anyway), alt-tabing (i need it) and just game (pick phase usually, if be honest).

I want to provide dump logs, but at the beginning I need to crash again, so for now without them.

#### Steps for reproducing this issue:

1. Buy Nvidia
2. Install Linux
2. Just try to play in this peace of beta test

**Comment by VladislavNekto** [comment]
O, catch one when i just test hero. I do nothing, just stay and it's crashed. [dump](https://gist.github.com/VladislavNekto/2e162777216bc8b20e8f2b264a6bfdd6). 

I have this params: 
`-novid -high -vulkan -vulkan_disable_steam_shader_cache -vulkan_disable_graphics_pipeline_library`

**Comment by VladislavNekto** [comment]
[assert_20221129235654_110.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10115883/assert_20221129235654_110.dmp.txt)
[crash_20221129235646_15.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10115884/crash_20221129235646_15.dmp.txt)
[crash_20221129235644_5.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10115885/crash_20221129235644_5.dmp.txt)
Dumps. It's different from [this](https://github.com/ValveSoftware/Dota-2/issues/2184#issue-1435872791), because it's started after i update system, not diretide part 2

**Comment by VladislavNekto** [comment]
I try again start game and it's just stuck again at pick phase, before it's stacked when i got spawned. And it's don't have dump logs for unknown reason, I was forced to kill the process

Hey, valve, btw, don't you want hire TESTER? For example, me. Only $1000 per month. Will test X11, Wayland, Gnome, KDE, AMD, NVidia, all, that you really need.

**Comment by VladislavNekto** [comment]
[crash_20221130002234_15.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10115997/crash_20221130002234_15.dmp.txt)
Start dota with `-gl`, go to lobby with bots, pick a hero, got spawned and aggressive alt-tabing and shift-tab to overlay

**Comment by VladislavNekto** [comment]
```Attempting to create OpenGL context: v3.3 (Core profile)...success. 
Checking entry points...success.
Loaded /mnt/sdd/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so, got (nil)

 failed to dlopen "/mnt/sdd/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/mnt/sdd/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
Loaded librenderdoc.so, got (nil)
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
Fossilize INFO: Overriding serialization path: "/mnt/sdd/SteamLibrary/steamapps/shadercache/570/fozpipelinesv6/steamapprun_pipeline_cache".
```

Can this crash a game? I try to start game with Vulkan, btw. [No, can't](https://github.com/ValveSoftware/Dota-2/issues/1260), but yeah, it's something common here, except this one has been in 2017
[o.txt](https://github.com/ValveSoftware/Dota-2/files/10116273/o.txt)

It's not crushes, it's like freeze. It's even doesn't have dump logs usually. And it's strange, because mangohud shows like GPU laoded to 99% even at low settings and it's have fps lock at 75
I did nothing, but it's not crushing, but fps it's lower and load on gpu 99% all time

**Comment by anaesthete** [comment]
Same thing on latest Tumbleweed, but on AMD-based machine (CPU: AMD Ryzen 5 3600, GPU: Radeon RX 6700 XT), so it seems like this bug might be Tumbleweed or Kernel v6 specific? There are also a lot of reports of dota crashing for mac/linux users  in the last month. 

Tried with every possible cli option, nothing useful in logs and crashdumps so far (i think they are generated because of `killall -9 dota`, and not because of freeze). Dota just crashes randomly, like every 3-10 minutes in game.

I also tried disabling shaders (they actually were disabled in my case steam-wide, because of lags previously), enabling shaders, removing ` ~/.cache/mesa_shader_cache`, removing dota 2-specific shaders in install dir and validating game files, reinstalling, nothing helped, the symptoms are just the same as OPs.

**Comment by Captain-Kopeikin** [comment]
I was actually meaning to reply -- I am having the same issue, and I am also using Tumbleweed OpenSUSE. I rolled back to November 27th with Snapper the other day, and Dota 2 works again. It's definitely a problem with a recent release.

**Comment by Falsonn** [comment]
Same problem on Tumbleweed with AMD (AMD Ryzen 5 3600, AMD RX 580). 

I can play for a few seconds or sometimes a minute then it just crashes. I had to switch to tty to kill it. Maybe it's the new kernel? There have been lots of mesa updates too.

I rolled back to the 24th of November with snapper and now Dota 2 works fine.

**Comment by anaesthete** [comment]
Today a new mesa release came to tumbleweed, but nothing has  really changed. I also tried adding `MESA_DEBUG` to both steam client and dota command (with `MESA_DEBUG=1 %command% -map dota -novid -high -vulkan -con_logfile` ), but i don't see any extra logs. Is there any way to debug it further to get to the cause of the error? Rolling back won't magically fix errors. Also i'd like to raise a ticket on opensuse bugtracker, but they would certainly like to see more logs

**Comment by VladislavNekto** [comment]
If someone just want to play and finding way to, try Gamescope. It's little unstable (and don't start at first try). And it's more strange, because for some reason game works, so just telling us that it's not graphics stack, but something like DE or WM? I use KDE.

**Comment by Captain-Kopeikin** [comment]
I updated earlier today and I was able to play a 30 minute game without crashing. I noticed the recent update had some x11 rollbacks. I would be happy to learn that the issue is fixed for others, too.

**Comment by VladislavNekto** [comment]
> I updated earlier today and I was able to play a 30 minute game without crashing. I noticed the recent update had some x11 rollbacks. I would be happy to learn that the issue is fixed for others, too.

I can confirm

**Comment by VladislavNekto** [comment]
Hey, @kisak-valve, if it's crashes one time in 30 minutes it's doesn't mean, that it's stable. Before updates dota 2 was almost completely stable, but now it's works only on GL and not so stable, vulkan crashes very often still

**Comment by daveknippers** [comment]
Let's not get too hasty on saying it's fixed, I'm having what I think is the same issue on gentoo testing and I'm unsure what package I should be rolling back to fix it.

**Comment by VladislavNekto** [comment]
@daveknippers, and rolling back this not resolution for this problem

**Comment by anaesthete** [comment]
Can confirm, works on latest Tumbleweed (played one 30 minute bot game, no issues). If it has something to do with X - https://build.opensuse.org/request/show/1040432 might be interesting

**Comment by daveknippers** [comment]
I rolled back x11-libs/libX11 from 1.8.2-r1 to 1.8.1 and I'm happy to report it's fixed.

**Comment by stryan** [comment]
I can confirm I had the same problem using a TW snapshot from last week, upgrading today seems to have resolved it.

**Comment by kisak-valve** [comment]
Hello @VladislavNekto, libX11 1.8.2 and 1.8.3 have been identified as having regressions consistent with this. It looks like OpenSUSE Tumbleweed was using 1.8.2 around the time you reported this issue and the OpenSUSE package maintainers have since decided to revert to 1.8.1 until those regressions can be resolved upstream.

We have to take the distro-provided libX11 as part of the graphics drivers that come from the host system and this specific issue needs to be resolved in upstream libX11.

Closing as not a game bug.
