### ISSUE TITLE
I can't see terrain in certain parts of the map after update (16.12.2022)

### ISSUE THREAD

**Issue by theflockers** [ValveSoftware/Dota-2#2217]
#### Your system information

* System information from steam:  https://gist.github.com/theflockers/ccae187f9fccde032e9e4596ff901c9e#file-gistfile1-txt
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Nothing much. Just play and you see what I decribed below. Happened after the update on 16.12.2022.

#### Steps for reproducing this issue:

1.  From the Radiant, go until the Dire mid tower.
2. You can't see the terrain and the players.
3. Go until Radiant triangle - also can't see the terrain
![dota-after-update](https://user-images.githubusercontent.com/223489/208187023-1464bd12-4ca0-4083-95c8-37230c384329.png)
![Screenshot from 2022-12-16 21-24-04](https://user-images.githubusercontent.com/223489/208187056-86638540-f4c5-43c6-827a-2ee3e2893794.png)

**Comment by kisak-valve** [comment]
Hello @theflockers, it looks like you're using AMDVLK. Can you check how the game behaves with mesa/RADV?

**Comment by theflockers** [comment]
Sure. I will check. thanks so far.

**Comment by theflockers** [comment]
@kisak-valve all good using RADV. Thanks man! Closing it.

**Comment by kisak-valve** [comment]
It might be worthwhile to also mention this issue to your video driver vendor.
