### ISSUE TITLE
Dota totally frozen some seconds after starting game with libX11 1.8.3

### ISSUE THREAD

**Issue by Eniotan** [ValveSoftware/Dota-2#2218]
#### Your system information

* System information :
[steam info](https://gist.github.com/Eniotan/e5beecdfb432a06817ab494252ac2f3f) 
[steamInfo.txt](https://github.com/ValveSoftware/Dota-2/files/10249507/steamInfo.txt)
* Have you checked for system updates?: 
Yes
* Are you using the latest stable video driver available for your system? 
Yes
* Have you verified the game files?
Yes

#### Please describe your issue in as much detail as possible:
Dota game totally frozen after starting a game. 
Same after lowering video settings at the minimum. 
Same in ranked game or in game vs bots.

#### Steps for reproducing this issue:

1. start a dota game
2. move your hero
3. after some seconds (1-10), it is totally frozen 

I get some lines in console : 

```
Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
dota2: xcb_io.c:833: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
```
 
or

```
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
dota2: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' faile
```

so I reinstalled all my xcb-related packages. Same.

**Comment by godcrying** [comment]
I have the same issue. My system is Archlinux and Nvidia GPU. The Dota2 game freezes after a few seconds. I think it is due to the latest updates.  Everything was going well yesterday, until it updates today.

**Comment by KennFatt** [comment]
I have the same similar issue and this is annoying. Here some logs:
```
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
dota2: xcb_io.c:833: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
crash_20221217170335_2.dmp[16172]: Uploading dump (out-of-process)
/tmp/dumps/crash_20221217170335_2.dmp
crash_20221217170335_2.dmp[16172]: Finished uploading minidump (out-of-process): success = yes
crash_20221217170335_2.dmp[16172]: response: CrashID=bp-d5a4f256-c115-4b77-b1d0-5a4a82221217
crash_20221217170335_2.dmp[16172]: file ''/tmp/dumps/crash_20221217170335_2.dmp'', upload yes: ''CrashID=bp-d5a4f256-c115-4b77-b1d0-5a4a82221217''
pid 16172 != 16171, skipping destruction (fork without exec?)
```

System information:
```
Linux <username> 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux
```

I tried to run the game with OpenGL or Vulkan with Intel GPU and no luck.

**Comment by hrwn** [comment]
I've same issue, 
add some information

journalctl :
```
systemd-coredump[4253]: [🡕] Process 4077 (dota2) of user 1000 dumped core.
                                                   Stack trace of thread 4077:
                                                   #0  0x00007fa5df4a164c n/a (/run/host/usr/lib/libc.so.6 + 0x8864c)
                                                   ELF object binary architecture: AMD x86-64
```
dmesg : 
```
[  838.937863] audit: type=1701 audit(1671272155.502:190): auid=1000 uid=1000 gid=1000 ses=1 pid=4077 comm="dota2" exe=2F6D656469612F7373642F537465616D4C6962726172792F737465616D617070732F636F6D6D6F6E2F646F7461203220626574612F67616D652F62696E2F6C696E7578737465616D727436342F646F746132 sig=6 res=1
```

edit: yeah, libx11's issue, works fine on wayland, played with 50 minutes of gameplay

**Comment by zeparu** [comment]
can confirm the same issue here since i updated my arch linux yesterday i guess, even using the steam-runtime-environment compatibility tool wont fix it, nor running steam-runtime instead of steam-native

**Comment by rohanprabhu** [comment]
So luckily, I might be able to offer some insight into which exact package upgrade has broken this. I had a dota 2 update today and I played the game just fine, after which I did an arch update and I'm facing this exact issue with 100% repro. My last pacman upgrade resulted in the following packages being updated:

```
clojure-1.11.1.1208-1  deno-1.29.0-1  gupnp-1:1.6.3-1
              haskell-ipynb-0.2-64  lib32-mesa-22.3.1-1  libnm-1.40.8-1
              libx11-1.8.3-1  luajit-2.1.0.beta3.r464.g8625eee7-1  mesa-22.3.1-1
              networkmanager-1.40.8-1  nodejs-19.3.0-1  pandoc-2.19.2-36
              rust-1:1.66.0-1  smbclient-4.17.4-1
```

From the looks of it, and the error messages posted by other commenters, it does seem like `libx11` and/or `mesa` update might have broken this.

**Comment by godcrying** [comment]
@rohanprabhu Thanks ! I downgrade my libx11 to 1.8.2 and it works :D

**Comment by rohanprabhu** [comment]
Oh wow - @godcrying - did it break other things for you? I have a triple display setup (laptop + 2 external displays) and I'm always so scared of downgrading anything related to graphics :D

**Comment by KennFatt** [comment]
Thanks a lot @rohanprabhu such a life saver xD. Yep @godcrying I can confirm too.
Here's what I did to downgrade if anyone wondering:
```
sudo pacman -U https://archive.archlinux.org/packages/l/libx11/libx11-1.8.2-2-x86_64.pkg.tar.zst
sudo pacman -U https://archive.archlinux.org/packages/l/lib32-mesa/lib32-mesa-22.2.3-1-x86_64.pkg.tar.zst
sudo pacman -U https://archive.archlinux.org/packages/m/mesa/mesa-22.2.3-1-x86_64.pkg.tar.zst
```
I'm not really sure if downgrading `mesa` is necessary, but it's work now.

**Comment by lindevel** [comment]
> Thanks a lot @rohanprabhu such a life saver xD. Yep @godcrying I can confirm too. Here's what I did to downgrade if anyone wondering:
> 
> ```
> sudo pacman -U https://archive.archlinux.org/packages/l/libx11/libx11-1.8.2-2-x86_64.pkg.tar.zst
> sudo pacman -U https://archive.archlinux.org/packages/l/lib32-mesa/lib32-mesa-22.2.3-1-x86_64.pkg.tar.zst
> sudo pacman -U https://archive.archlinux.org/packages/m/mesa/mesa-22.2.3-1-x86_64.pkg.tar.zst
> ```
> 
> I'm not really sure if downgrading `mesa` is necessary, but it's work now.

Confirm. This work

**Comment by rohanprabhu** [comment]
Yeah, went ahead and took the plunge myself. I use [downgrade](https://aur.archlinux.org/packages/downgrade), so a `downgrade libx11` and selecting `1.8.2` worked for me.

P.S. - Downgrading `mesa` does not seem to be necessary, I did not downgrade `mesa` and just `libx11` downgrade fixed it for me

**Comment by Eniotan** [comment]
Ok we can close: distro issue, not dota2. Thanks to all! Sorry for opening issue here and not in Arch .

**Comment by zeparu** [comment]
well it could still be an issue with dota, because i could play binding of isaac (proton) and FFXIV (wine) completely fine with libx11 1.8.3, bug reports should still be opened on both ends

**Comment by rohanprabhu** [comment]
Yeah, I agree with @zeparu  - what we know so far is that there is a regression, but if it was purely an issue with `libx11`, then we should have seen more chatter on places like arch bbs. I think it might make more sense to keep it open and get some clarity on this from the Dota 2 devs

Edit:
There does seem to be a bit more chatter:

https://bbs.archlinux.org/viewtopic.php?id=282105
https://bbs.archlinux.org/viewtopic.php?id=281823

**Comment by Eniotan** [comment]
So,  I switch back to «open» following above comments

**Comment by rohanprabhu** [comment]
@Eniotan - I guess you were right - this is a distro issue :D - https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/176 ; now just need to wait for this to get into the arch repos

**Comment by amaanq** [comment]
Bisected and found likely cause, see [#174](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/174) on libx11's gitlab

**Comment by ArikRahman** [comment]
Per @rafael-arreola, Dota started working with me by downgrading


$ paru -Syu --noconfirm downgrade

$ sudo downgrade libx11

-> and select the version libx11-1.8.2-2

**Comment by bastienleonard** [comment]
It works for me today after I updated packages.

**Comment by Eniotan** [comment]
new libx11-1.8.3-3 solves the issue, I close.

**Comment by Zesko** [comment]
`libx11 1.8.3-4` has this issue again and freezes Dota2 when using KDE wayland.

**Comment by Zesko** [comment]
`libx11 1.8.3-5` fixed the issue.
