### ISSUE TITLE
Bundled libGL.so doesn't supported latest RX 7900 XT(X) GPU's

### ISSUE THREAD

**Issue by simvux** [ValveSoftware/Dota-2#2225]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
  https://gist.github.com/simvux/de71e6f377299c35d7906af2120a70ac
* Have you checked for system updates?: [Yes/No]
  yes
* Are you using the latest stable video driver available for your system? [Yes/No]
  yes
* Have you verified the game files?: [Yes/No]
  yes

#### Please describe your issue in as much detail as possible:

Dota 2 silently crashes on startup, with no window even opening. 
The STDOUT yields the error `did not find extension DRI_Mesa version 1`

As a temporary work-around, LD_PRELOAD'ing the system's libGL allows the game to launch properly.
`LD_PRELOAD=/usr/lib/libGL.so.1.7.0 %command% -vulkan`

#### Steps for reproducing this issue:

1. Run a system with RX 7900 XT(X) and at least mesa-22.3.1
2. Launch the game

**Comment by kisak-valve** [comment]
Hello @simvux, your issue is with `/usr/local/lib/libGL.so.1.2.0` (https://gist.github.com/simvux/de71e6f377299c35d7906af2120a70ac#file-sysinfo-json-L2394). You're overriding that instead of a game bundled variant of this library.

**Comment by simvux** [comment]
Oh i see, huh strange. I had to manually compile the mesa drivers so I suspect there's probably some ramenents of the old drivers hanging around, should make sure to remove and/or symlink the correct ones to that directory. 

Thanks!
