### ISSUE TITLE
[Archlinux] Game freezes, background music keeps playing.

### ISSUE THREAD

**Issue by betovidal** [ValveSoftware/Dota-2#2229]
#### Your system information

* System information from steam: [gist](https://gist.github.com/betovidal/7ac23eb0169bc3be011bbdb9a2fee9c6)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Game freezes in match (video freezes, but background music keeps playing). I tried passing the -gl and the -vulkan flags on different tries and the same thing happened. Match replay doesn't seem to freeze.

Running steam from console shows a bunch of these lines:

`Xlib: sequence lost (0x10000 > 0xc504) in reply type 0xc!`

#### Steps for reproducing this issue:

1. Join a match
2. Play for a minute
3. Video freezes

Edit: The problem seems to be related to libx11-1.8.3-4. A workaround is downgrading to libx11-1.8.2-2.

**Comment by SirFireball3521** [comment]
I'm having the same issue. Here is my system info: https://gist.github.com/SirFireball3521/de066d181323f6ed66f91ac62483fa6e 
and here is a zip containing a .dmp from one of the freezes: https://github.com/ValveSoftware/Dota-2/files/10365565/crash_20230106222233_14.zip

**Comment by betovidal** [comment]
Looks similar to #2218, reported 3 weeks ago. There's even a follow up in [libx11 dev repo](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/173).

**Comment by betovidal** [comment]
No more crashes after downgrading libx11 to version 1.8.2-2 as stated in [this comment](https://github.com/ValveSoftware/Dota-2/issues/2218#issuecomment-1356854309).

**Comment by SirFireball3521** [comment]
I downgraded, it stopped freezing, but 9 minutes into my first game trying it again, it did. Here's the .dmp.
[crash_20230106235111_36.zip](https://github.com/ValveSoftware/Dota-2/files/10365662/crash_20230106235111_36.zip)

I tried another demo game, and it came back again at around the 9 min mark and my game froze.

**Comment by Zesko** [comment]
`libx11 1.8.3-4` has this issue and freezes Dota2 when using KDE wayland.

`libx11 1.8.3-3` has no issue.

**Comment by kisak-valve** [comment]
This is an upstream libX11 regression and your feedback should go to the libX11 issue tracker or your distro's package maintainer(s) for libX11 if someone hasn't already done so. You may have more luck with Arch's `libx11 1.8.3-5` package.

**Comment by SirFireball3521** [comment]
Using `libx11 1.8.3-5` I still see the `Xlib: sequence lost` messages in the console, but I haven't crashed yet even after a few minutes in demo. According to libx11 issue tracker this should be fixed, so I'm hopefully optimistic.

**Comment by betovidal** [comment]
> This is an upstream libX11 regression and your feedback should go to the libX11 issue tracker or your distro's package maintainer(s) for libX11 if someone hasn't already done so. You may have more luck with Arch's `libx11 1.8.3-5` package.

Agreed! Closing issue and I'll try 1.8.3-5. Will comment on libx11 instead if needed.
