### ISSUE TITLE
[Linux] ability draft: missing courier and other glitches

### ISSUE THREAD

**Issue by SexyFlanders** [ValveSoftware/Dota-2#223]
While playing ability draft, the courier is not being loaded correctly (just showing "error"). There are also other textures not loading correctly.

My system:
https://gist.github.com/SexyFlanders/22d8bcb02d1ef981ec65

![bildschirmfoto1](https://cloud.githubusercontent.com/assets/4339297/8581824/6ded94ea-25c3-11e5-9f3d-aee9e0c205e6.png)
![bildschirmfoto3](https://cloud.githubusercontent.com/assets/4339297/8581840/7d4e96fa-25c3-11e5-9c8c-ecb79cc9c11c.png)

**Comment by gdrewb-valve** [comment]
I believe this occurs on Windows also.

**Comment by SexyFlanders** [comment]
I don't know, i don't use windows :-)

**Comment by gdrewb-valve** [comment]
I tried this, not a full game but enough to buy a courier, and it worked properly on both Windows and Linux.  Does this happen every time for you?  Do you have problems with any game mode other than Ability Draft?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
