### ISSUE TITLE
[Linux] Dota 2 crashes on alt tab or workspace switching.

### ISSUE THREAD

**Issue by ghabit** [ValveSoftware/Dota-2#2231]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/ghabit/a26575d094e7ada8d47d7fac52e49781
* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Integrated GPU, no discrete GPU
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
Expectations: Playing Dota2, loosing some MMR.
Reality: Dota 2 crashes
#### Steps for reproducing this issue:

1. Start Dota 2
2. Playing
3. Doing an ALT+TAB keys for windows switching or workspace switching
4. Dota randomly crashes at this point

Attached created dump file.

Thank you!

[crash_20230107115839_15.zip](https://github.com/ValveSoftware/Dota-2/files/10365853/crash_20230107115839_15.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGABRT in libc.so.6 coming from libX11.so.6.4.0. Both these libraries come from system packages and there's been some regressions upstream affecting Arch users.

What libX11 version are you using? If it's 1.8.3, then please try 1.8.2 or 1.8.1. If you completely close Steam, then run `steam-runtime` from a terminal, are there any hints in the terminal spew when you reproduce the issue?

**Comment by ghabit** [comment]
Thank you a lot. Looking like downgrading to 1.8.2 did the job! <3
How can I know when I'll be able to remove package from downgrade list?

**Comment by kisak-valve** [comment]
It's an upstream regression. Your best option is to check if it's already been reported in the libX11 issue tracker and follow whatever issue report is relevant there.

**Comment by esnfps** [comment]
I upgraded libx11 to version 1.8.3-5 and it stopped freezing.

**Comment by ghabit** [comment]
I was encountering the issue with 1.8.3-5, crashes for me.

**Comment by Zesko** [comment]
This issue with libx11 ` 1.8.3-5` does not affect KDE Wayland or Xorg. 
That could be, Gnome Wayland is related to the compatibility issue with libx11 `1.8.3-5`.

**Comment by ghabit** [comment]
> This issue with libx11 ` 1.8.3-5` does not affect KDE Wayland or Xorg. That could be, Gnome Wayland is related to the compatibility issue with libx11 `1.8.3-5`.

Do you think I have to fill issue on some GNOME part? Or just wait for a while and just check the versions and behavior some weeks later?

**Comment by Zesko** [comment]
`libx11` is designed for X11 client side.

Can you test it on Gnome X11?

**Comment by fveracoechea** [comment]
It's happening for me as well, I'm using Ubuntu 23.10, any ideas how to fix it?
I have an AMD video card and `libx11 v1.8.6`

**Comment by geez0x1** [comment]
I believe I am affected by the same issue. If I stay in-game, I have not seen crashes. Ubuntu 23.10, up-to-date, GNOME on Wayland, Steam through flatpak.

Another thing that triggers a crash (a lot of the time) is changing the volume - it appears the GNOME volume change thing being displayed triggers the crash.

Interestingly, it seems to affect both dota2 and CS2, as well as Steam itself, but that crashes randomly. All these started happening at the same time.

**Comment by sdjnes** [comment]
Having the same issue in DotA 2 specifically. Also noticed it crashed when I received a Steam notification of someone playing a game.

Alt tabbing is a roll of the dice whether it crashes or not, sometimes it does but not always.

**Comment by dtorrero** [comment]
Same issue on Manjaro.  `libx 1.8.7-1`
DMESG: 
`[10793.513087] dota2[5676]: segfault at 6f01005e ip 00007f36e6b8eb47 sp 00007ffccf904810 error 4 in libvulkan_radeon.so[7f36e6a85000+46d000] likely on CPU 0 (core 0, socket 0)`
`[10793.513096] Code: 41 ff 94 24 f8 01 00 00 48 8b 4b 20 49 89 c6 48 85 c9 0f 84 a3 00 00 00 48 8b 45 78 48 83 b8 b0 11 00 00 00 0f 84 19 01 00 00 <48> 8b 71 50 48 85 f6 74 2a 48 8b 06 48 89 4c 24 08 48 89 ef 48 89`

**Comment by geez0x1** [comment]
~~This was fixed quietly :) I *think* by Valve (as nothing else was crashing), but could also have been an OS update.~~

Scratch that.. CS2 just started crashing on alt tab again. Dota however doesn't seem to.

**Comment by kisak-valve** [comment]
Closing per the last comment.

If you're seeing a look-alike issue with Counter-Strike 2, then check if there's an issue tracking that on the csgo-osx-linux issue tracker and follow up there.
