### ISSUE TITLE
Some hero skins are invisible, can't click (Oracle, Pudge)

### ISSUE THREAD

**Issue by nleo** [ValveSoftware/Dota-2#2237]
Версия ОС:
    Linux Mint 19.3 Tricia (64 бит)
    Название ядра: Linux
    Версия ядра: 5.0.0-32-generic
    Поставщик X-сервера: The X.Org Foundation
    Версия X-сервера: 11906000
    Менеджер окон X Window System: Mutter (Muffin)
    Версия клиента Steam: steam-runtime_0.20221019.0

Видеокарта:
    Модель:  Intel Open Source Technology Center Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
    Версия драйвера:  3.0 Mesa 20.0.8
    Версия OpenGL: 4.6
    Глубина цвета: 24 бит/пиксель
    Частота обновления: 60 Гц
    ID производителя: 0x8086
    ID карты:  0x5917
    Версия неизвестна
    Кол-во экранов:  1
    Количество логических видеокарт:  1
    Разрешение осн. экрана:  1920 x 1080
    Разрешение рабочего стола: 1920 x 1080
    Размер осн. экрана: 12.17" x 6.81" (13.94" diag)
 30.9cm x 17.3cm (35.4cm diag)
    Размер видеопамяти не определен

![Screenshot from 2023-01-20 13-50-22](https://user-images.githubusercontent.com/800970/213678948-3b03d608-34c6-4ae5-af92-a66e733cb5e0.png)
![image](https://user-images.githubusercontent.com/800970/213679150-ffe01b04-828a-4b18-9591-be2553c3649c.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6070, issue mentioned in the main Dota 2 Bug Tracker.

**Comment by bwvalve** [comment]
Duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/6070
