### ISSUE TITLE
Can use showcase view on enemy heroes

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#224]
I'm not sure if it's new to the 8/07 update and it's probably not Mac-specific.
If you activate the showcase view on a friendly unit, and then click on an enemy hero portait on the top list, the showcase view will shift to the enemy hero. 
This cannot be done when the hero is not visible on the map, so it may not be an issue. However, since the showcase view cannot be activated on enemy heroes when clicking the dedicated button in the hero portait, there is an inconsistency.

**Comment by gdrewb-valve** [comment]
I'll pass this on to the larger team.
