### ISSUE TITLE
Demo hero button leads to "all pick"

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#225]
Upon clicking the "demo hero" button, it is expected that the demo map loads with the currently viewed hero. Instead, the player gets to choose a hero in "all pick" mode.

**Comment by gdrewb-valve** [comment]
Probably not a Mac/Linux issue.

**Comment by gdrewb-valve** [comment]
I was not able to repro this on Windows or Linux.  My steps:
1. Start game, go to heroes list.  Pick Juggernaut.
2. Select "Demo Hero".  Game goes directly to demo.

Are those the right steps?  Does this happen every time for you?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by jeanlain** [comment]
This happened just once. It seems to be fixed.

**Comment by jeanlain** [comment]
Actually it's happening again. I did the step you describe and it leads me to "all pick". This creates a game in the demo Map as if it was a match (without the options of the demo panel on the left). 
Note that I often create lobbies (not hosted locally) in "all pick" mode.

**Comment by gdrewb-valve** [comment]
Reopening, but still not happening for me.  We'll have to try and pin down a repro.

**Comment by jeanlain** [comment]
The issue doesn't happen when the game is in offline mode (no internet connection).

**Comment by jeanlain** [comment]
The issue appears to be linked to the creation of a lobby in "all pick" mode prior to demoing a hero.

**Comment by gdrewb-valve** [comment]
Ah, OK, thanks for the extra info.  I was able to confirm a problem on Windows and I've passed this on to the larger team.
