### ISSUE TITLE
Game stop open

### ISSUE THREAD

**Issue by josinaldobarbosa** [ValveSoftware/Dota-2#2250]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/josinaldobarbosa/4c5ef88c616a26fa6245847caec9adda
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Don't open

#### Steps for reproducing this issue:

1. Play

**Comment by jneos** [comment]
Is this issue related to https://github.com/ValveSoftware/Dota-2/issues/2257 ?

**Comment by josinaldobarbosa** [comment]
ValveSoftware/Dota-2#2257
