### ISSUE TITLE
dota2.sh "which"->"command -v"

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#2260]
line 12 of the dota2.sh startup script: 'which' is not the "right" command to lookup for a command, it is 'command -v'.

Could you replace it? (I have not built 'which' in years since it was replaced by 'command -v')

**Comment by danginsburg** [comment]
I assume it still ran correctly, it just printed a warning to the console?  That was added as macOS fix but should still fallback to the right uname binary on Linux.

**Comment by danginsburg** [comment]
A fix for this will be in the next Dota client update.

**Comment by sylware** [comment]
Verified dota2 files.

Tested, fixed.

Please consider moving to !/bin/sh with custom script helper programs, or bluntly distribute a statically linked bash binary with the game.

Thx!
