### ISSUE TITLE
Failed to initialize Vulkan.

### ISSUE THREAD

**Issue by ii8** [ValveSoftware/Dota-2#2267]
#### Your system information

* [System info](https://gist.github.com/ii8/4a77bbbaabf1bccb2a0543b04916c13c/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Since the recent update 7.32e, when launching dota the game does not start, instead a dialog appears that reads:
```
Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan.

To disable Vulkan, remove -vulkan from your launch options.
If you chose Vulkan in the video settings, please add -safe_mode to your launch options to allow the game to start with the default rendersystem.
```
Have tried the lauch options it suggests, using shadercache and not using it, launching from inside steam and from console, the same error persists in all cases.

Running dota like this:
```
GAME_DEBUGGER=gdb ubuntu12_32/steam-runtime/run.sh steamapps/common/dota\ 2\ beta/game/dota.sh
```
produces the following error on the console(only printed when using the debugger):
```
No display adapters found. Falling back to software rasterizer. (nAdapterCount=0, nAdapter=0)
```
And shows the same dialog.
Notably there are no dlopen errors.
[full log in gist](https://gist.github.com/ii8/1b18374c8459dbf40582a1fdb32fb4ef)

Another thing I should maybe add is that launching steam takes a very long time since recently, likewise dota takes a very long time to launch if running it from inside steam, when running it from the console it gets to the dialog fast.
During the delay before dota tries to start a process called `CIPCServer::Thr` is running at 100% cpu usage. Once dota fails to start this process disappears again.

**Comment by kisak-valve** [comment]
Hello @ii8, you have an AMD Southern Island (SI) generation video card. By default, the Linux kernel uses the `radeon` kernel module with your video card, but that kernel modules is not compatible with Vulkan. https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games is equally valid in this case as it is with Proton and should be worth reading.

**Comment by ii8** [comment]
Thanks, I should have probably figured that out myself, oops.
