### ISSUE TITLE
[OS X] Freezing and other issues using El Capitan public beta.

### ISSUE THREAD

**Issue by michaelkclements** [ValveSoftware/Dota-2#227]
While I realise it is a public beta for an operating system, I figured I should raise the issues I'm seeing just in case it goes unnoticed.

I'll write the different issues I've had below.
- First off, the steam overlay doesn't seem to work. I have it activated.
- Cmd + Tabbing out of Dota is fine but either cmd tabbing back or clicking the app icon does nothing. Have to 3 finger slide along on the trackpad to get back.
- The home screen panels are all empty http://i.imgur.com/SuG2Pw3.jpg 
- Entering a game or closing a game seems to freeze the game for a long time, like 5-7 minutes, but then it returns http://i.imgur.com/cOvJBSz.jpg

These might be chalked up to the public beta, but I'll leave it up to the devs to decide if they're Dota bugs.

**Comment by scottlow** [comment]
To add to this, the steam overlay was working pre developer beta 3/public beta. It seems to be something Apple added recently that broke it.

**Comment by bxio** [comment]
I can confirm that the steam overlay is broken on beta 3. Toggling Steam in Accessibility and/or restarting the Steam client does not fix the overlay.

Also, the overlay works in other games such as Civilization V, but is broken in Dota2 and CS:GO.

**Comment by michaelkclements** [comment]
Both the home panel problem and the freezing issue seem to have resolved. Think the freezing might've been a one off that day?

**Comment by gdrewb-valve** [comment]
I've passed the Steam overlay issue on to the Steam team.

The only active issue would then be Cmd+Tab?  What video mode are you running in?

**Comment by michaelkclements** [comment]
Borderless window.

**Comment by gdrewb-valve** [comment]
OK, thanks.

**Comment by jie-lyu** [comment]
I'm using OS X 10.10.4.
Freezing happens when entering and closing games with high probability.
Anyone has the same problem or just me?

**Comment by presianbg** [comment]
Same on Linux - Fedora 22 and Arch Linux (all up to date). Did not happened before, I'm talking about the freezing when starting (while players are accepting the game  10/10) and when quitting the game (final score board, leaving, disconnection... etc.) Nothing in the logs :(

**Comment by gdrewb-valve** [comment]
I believe the freezing should be addressed now.  Are you still seeing it?

**Comment by presianbg** [comment]
@gdrewb-valve 
Now game is running fine under Linux (Fedora and Arch). Thank you :)

**Comment by bklooster** [comment]
I am also running the 10.11 beta and since the last patch the only problem I have is the steam overlay which affects all games. It appears Apple redid their accessibility control panel, so I figure getting a steam overlay working again will be a good chunk of work for the Steam team.

The command-tab thing was explained in #6 as that is the SDL windowing that they're going with. 

As of the last patch all of the store panels appear to appearing.

I think the freeze when closing thing was a cross-platform issue as Windows users were reporting the same problem and I'm not experiencing it in the latest beta.

**Comment by gdrewb-valve** [comment]
michaelkclements was using a borderless window so I think Cmd+Tab should have worked.

**Comment by michaelkclements** [comment]
Yeah sorry I didn't reply sooner. The cmd tab is working. Differently (like the genie in the bottle way), but it's working fine.

It seemed fine when I loaded it on the Public Beta 2 as well, except the shift tab overlay. I'll let you guys know if anything else pops up. Thanks very much.

**Comment by gdrewb-valve** [comment]
So everything is OK at the moment?  I'll close this out, then.

**Comment by mohsin** [comment]
No steam overlay still doesn’t work. That’s a big issue that needs to be patched soon
+1

**Comment by gdrewb-valve** [comment]
This isn't a Steam bug tracker so the overlay issue isn't being monitored here.  The last I heard from the Steam team they are waiting for Apple to address the issue since it is new Apple software that has broken Steam.

**Comment by mohsin** [comment]
Ah alright. Thanks for the info. I suppose Apple would fix it by the time El Capitan official version comes out or hopefully in the next update 😄

**Comment by ghost** [comment]
@gdrewb-valve I talked to Apple they said Valve needs to update their code and that this is why they have a developer preview. OSX 10.11 is now GM so its up to Steam Team to update the steam overlay code to support the new OSX 10.11 permissions can you check the status?

**Comment by bxio** [comment]
Steam overlay is back up as of September 18, 2015. Freezing issue is still there, though. Every so often the game lags so badly it's impossible to see what's going on.

Ranked games have turned into a game of chance - the team who lags during fights is the team that loses.

**Comment by mohsin** [comment]
Is that right? I’m on OS X 10.11 (15A282a) -- the El Capitan GM one and it doesn’t appear to work.

**Comment by kschoener** [comment]
My overlay still doesn't work on El Capitan. Has anyone found a solution yet?

**Comment by danginsburg** [comment]
See #526.
