### ISSUE TITLE
Failed to Initialize Vulkan Error Message 

### ISSUE THREAD

**Issue by D3VOH** [ValveSoftware/Dota-2#2272]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

[920e4495bba1e5cb2a09df7b489438b5-e805c33335eebc36a3318b13fc2f486a65ee0725.zip](https://github.com/ValveSoftware/Dota-2/files/10944395/920e4495bba1e5cb2a09df7b489438b5-e805c33335eebc36a3318b13fc2f486a65ee0725.zip)

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible

Upon trying to launch dota, there is an error message ever since the latest Dota update. It reads that:

Unable to start game
Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan.

To disable Vulkan, remove -vulkan from your launch options.
If you chose Vulkan in the video settings, please add -safe_mode to your launch options to allow the game to start with the default rendersystem
![Screen Shot 2023-03-07 at 10 02 40 AM](https://user-images.githubusercontent.com/127501618/224308598-31ffa476-0a54-47bf-b9f9-70a2729e3303.png)

I have verified the files, reinstalled the game, etc. 
I have been told to wait for the next updates as I am an OS user and this has happened in the past. However, it seems that since the major update there have been minor updates since then, none of which resolved the issue. 

If anyone can help that would be appreciated!

**Comment by kisak-valve** [comment]
Hello @D3VOH, as requested in the issue report template, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by D3VOH** [comment]
> Hello @D3VOH, as requested in the issue report template, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Done thanks.

**Comment by kisak-valve** [comment]
That's significantly less information than was requested, but regardless, it looks like you have a mid 2011 model iMac with a Sandy Bridge generation Intel GPU (Intel HD 3000 series) and a Terascale 2 Generation AMD GPU.

Both of these GPUs do not support Apple's Metal graphics API on MacOS, which means that Dota 2 can't use MoltenVK to translate Vulkan in the game to Metal for their video driver.

Sorry but the error message is accurate and your hardware is not supported after "As we mentioned when we launched [Battle Pass: Part II](https://steamcommunity.com/linkfilter/?url=https://www.dota2.com/newsentry/3398555399443921912), this update has removed support for OpenGL. For macOS customers, the minimum requirement is now macOS 10.13.6 with a Metal-capable GPU (AMD GCN-based GPU or newer; NVIDIA Kepler-based GPU or newer; or Intel HD 4000 or newer). For Linux customers, AMD GCN+, NVIDIA Kepler+, or Intel HD 5000-series or newer is required." in [The Dead Reckoning Update](https://www.dota2.com/newsentry/3659774959159800240) of Dota 2.

**Comment by D3VOH** [comment]
Significantly more snarky a response than asked for. Not everyone is a
technical expert. Don’t have to act like a clown about it
