### ISSUE TITLE
Buying the Dead Reckoning Chest key crashes the game

### ISSUE THREAD

**Issue by brianlee** [ValveSoftware/Dota-2#2274]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/brianlee/f094bf6ec2c6df5a6dacfbec24a739e2): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

When I try to buy the Dead Reckoning Chest keys in game, it crashes the game. 
Overlay in game is enabled. Game is up to date. Mac OS (13.2.1 (22D68)) is up to date.

#### Steps for reproducing this issue:

1.  Start Dota 2
2. Click on the Dead Reckoning Chest on the left panel under "Recent Treasures"
3. Click "$2.49" under the Buy Key menu
4. Click Purchase
5. Game crashes

Similar problem happens when you try to buy supporter's club pack. Repro steps:
1. From the loading screen, Click Watch > "JOIN A SUPPORTER'S CLUB"
2. Select any team
3. Click on any of the money button (e.g. "$19.97")
4. Game crashes

**Comment by paboum** [comment]
Lol, don't purchase anything, simple as that. Shouldn't have reported this. Now they fix this one and leave the other bugs untouched.

**Comment by BuffyTheCat** [comment]
same

**Comment by BigSchmoopie** [comment]
I have the same issue, I'm on a mac pro m1 and every time i open the overlay to buy something it crashes

**Comment by pedrofonseca12** [comment]
Same issue here.
I'm on a mac mini m1, macOS Ventura 13.2.1 (22D68)

**Comment by pedrofonseca12** [comment]
just an update for those who might still have this error.

if i buy the Dead Reckoning Chest key from '**In game**' - '**Treasury**' - '**Browse**' - select '**Key of the Dead Reckoning**' - '**Purchase**', it works and no crash happens.

if i try to buy directly from Main Screen, '**View Treasure**' - '**Buy Key**', the game crashes.

Hope that helps

**Comment by tabartorche** [comment]
> just an update for those who might still have this error.
> 
> if i buy the Dead Reckoning Chest key from '**In game**' - '**Treasury**' - '**Browse**' - select '**Key of the Dead Reckoning**' - '**Purchase**', it works and no crash happens.
> 
> if i try to buy directly from Main Screen, '**View Treasure**' - '**Buy Key**', the game crashes.
> 
> Hope that helps

This didn't work for me. (or I may be missing something?)
Could you please explain what you mean by **'In game'**? Do you mean an actual match then drop down arrow to access the store?

also, I thought I almost had it when I did the following:
1. Tap 'STORE'
2. Tap 'BROWSE'
3. Tap the green 'C$ 3.39' button on the Key of the Dead Reckoning
4. Transaction overlay appears with transaction page
5. Click the green 'AUTHORIZE' button
6. Dota 2 crashes

Normally it just crashed without the transaction page.

**Comment by danginsburg** [comment]
We just shipped a fix for this.  Can you retest?

**Comment by brianlee** [comment]
@danginsburg Just tested and it works. Thanks!

**Comment by paboum** [comment]
Aaand, as I predicted above, #2273 is still occuring. Cash flow restored, nobody cares about the product stability.

**Comment by brianlee** [comment]
@paboum A perf issue on a very small number of people vs. UI issue that has less than 2 weeks of the event deadline for the most of Mac users. I think the latter has the bigger scope. Also, if the company is not profitable, you won't have this game.
