### ISSUE TITLE
Please stop stealing focus.

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [ValveSoftware/Dota-2#2281]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/GoLD-ReaVeR/b1f193df05db9fd8ec65d66328449ef7
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

Please stop taking focus from other applications. When I left the window I did so intentionally, do not request it back; ever. It's extremely annoying to work with and it serves no purpose.

**Comment by kisak-valve** [comment]
Hello @GoLD-ReaVeR, this issue is already being tracked at #1911. Closing as a duplicate.
