### ISSUE TITLE
Dota 2 In-Game Overlay Crash for Mac

### ISSUE THREAD

**Issue by rk562** [ValveSoftware/Dota-2#2284]
**Dota 2 In-Game Overlay Crash**

Whenever I try to open the In-Game Overlay through multiple ways to buy items, the whole game crashes and gives me a crash report which I have attached. 

Crash Report:
[Translated Crash Report.pdf](https://github.com/ValveSoftware/Dota-2/files/11054398/Translated.Crash.Report.pdf)

I have tried opening Dota2 and pressing shift+tab to open it: crash
In the game store section when I click a price CTA button: crash
Trying to buy a treasure key: crash

I've done all the steps of the suggested remedies:
- Check the In-Game overlay is activated on both Steam and Dota2 settings
- Restart my computer multiple times
- Verifying the integrity of game files
- Use Steam beta mode
- Update Steam and my operating system to the latest version
- Reinstalling Steam

I am wondering is there a way that we can buy items through a web browser and not an in-game overlay?

#### Your system information

* System information from steam: Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro18,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  VirtualApple
    CPU Brand:  Apple M1 Pro
    CPU Family:  0x6
    CPU Model:  0xc
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2400 Mhz
    10 logical processors
    10 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 13.2.1 (64 bit)

Video Card:
    Driver:  Apple M1 Pro
    Driver Version:  227.2.45
    OpenGL Version: 4.1
    Desktop Color Depth: 64 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x106b
    DeviceID:  0x0
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3360 x 1890
    Desktop Resolution: 3360 x 1890
    Primary Display Size: 27.52" x 15.35" (31.50" diag)
                                            69.9cm x 39.0cm (80.0cm diag)
    Primary VRAM: 16384 MB

Memory:
    RAM:  16384 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  948584 MB
    Largest Free Hard Disk Block:  531619 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0
    

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

**Comment by danginsburg** [comment]
Can you try overwriting your local copy of `~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/libMoltenVK.dylib` with the attached copy?

We're working on getting the fix public, but I believe this should workaround it for now.

Thanks.
[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/11066225/libMoltenVK.dylib.zip)

**Comment by danginsburg** [comment]
We just shipped a fix for this.  Can you retest?

**Comment by kisak-valve** [comment]
Closing as fixed.
