### ISSUE TITLE
Hotkeys don't works on Linux after entering the game with keyboard layout othen than English.

### ISSUE THREAD

**Issue by YahorHr** [ValveSoftware/Dota-2#2286]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/YahorHr/6838e6cc29c70528638055463cf4b2ad): 
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Please describe your issue in as much detail as possible:
Hotkeys do not work after entering the game with a keyboard layout other than English. But keyboard works fine for chat. Switching keyboard layout in game doesn't have any affect.
Environment: Archlinux, KDE
This issue was opened by me on https://github.com/ValveSoftware/Dota2-Gameplay/issues/7699 but guys redirect me to this tracker.

#### Steps for reproducing this issue:

1.  Switch keyboard to ru layout
2.  start steam 
3.  start dota2
4.  start new game
5. hotkeys for skills don't work. chat works well
switching keybord to EN also doesn't fix issue.

**Comment by YahorHr** [comment]
I have this issue may be 5 month

**Comment by kisak-valve** [comment]
Hello @YahorHr, can you go to Dota 2 -> Settings gear icon -> To Advanced Hotkeys -> enable `Bind keys based on keyboard position` and test if that gives you the behavior you're looking for?

**Comment by YahorHr** [comment]
Seems It works fine. Tnx for help.
