### ISSUE TITLE
Rotating UI elements no longer spin a full circle since the Muerta update

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#2287]
#### Your system information

* https://gist.github.com/u00101010/9c341a97208097bb034d2034eb8fc9c3

#### Please describe your issue in as much detail as possible:

UI elements that are supposed to be constantly spinning around only spin halfway through and then move backwards to the original position, then repeat. This affects the loading indicator circle and the in-game courier delivery status indicator in the bottom right corner as well, and probably some others that work similarly. This happens all the time with no exceptions.

**Comment by epssy** [comment]
Ha, yup, definitely not spinning all of the way around. :laughing: 

**Replication Steps**
1. Load any hero in demo mode
2. Request courier delivery
3. Observe bottom right indicator

**Comment by u00101010** [comment]
[As per this changelog](https://store.steampowered.com/news/app/570/view/4442333890575598739?l=japanese) and after having retested I can now confirm that this is now fixed.
