### ISSUE TITLE
[OS X] Survival Coop crashes.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#229]
Hi, I am not sure what the policy for crashes with mods. I submit this hoping you'll delete it if its not a dota bug. :)

Process:               dota2 [16145]
Path:                  /Users/USER/Library/Application Support/Steam/*/dota2
Identifier:            dota2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [16142]
Responsible:           steam_osx [15915]
User ID:               501

Date/Time:             2015-07-17 01:37:11.240 -0400
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        7FB7401D-CACC-B0E4-83E7-07E82A294D71

Sleep/Wake UUID:       32A876EF-68E9-40AF-A53C-61219281CC74

Time Awake Since Boot: 180000 seconds
Time Since Wake:       31000 seconds

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000052000b

VM Regions Near 0x52000b:
--> 
    __TEXT                 0000000003ef8000-0000000003ef9000 [    4K] r-x/rwx SM=COW  /Users/USER/Library/Application Support/Steam/*

Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libclient.dylib                 0x00000000a5c12fb3 CAnimationLayer::SetSequence(HSequence, SetSequenceBehavior_t, LayerChangeBehavior_t) + 51
1   libclient.dylib                 0x00000000a5103d0c CDOTAAnimState::AddToGestureSlot(int, int, bool, HSequence, float, float) + 332
2   libclient.dylib                 0x00000000a5083527 C_TEUnitAnimation::RunUnitAnimation(C_DOTA_BaseNPC_, CDOTAUserMsg_TEUnitAnimation_t const&) + 183
3   libclient.dylib                 0x00000000a5083451 C_TEUnitAnimation::RunQueueUnitAnimation(CEntityHandle, CDOTAUserMsg_TEUnitAnimation_t_) + 97
4   libclient.dylib                 0x00000000a50836ec CFunctor2<void (*)(CEntityHandle, CDOTAUserMsg_TEUnitAnimation_t*), CEntityHandle, CDOTAUserMsg_TEUnitAnimation_t*, CRefCounted1<CFunctor, CRefCountServiceBase<true, CRefMT> > >::operator()() + 28
5   libclient.dylib                 0x00000000a4f19649 ExecuteClientSimulationCallQueue() + 105
6   libclient.dylib                 0x00000000a5c7ab9e CLoopModeGame::OnClientSimulate(EventClientSimulate_t const&) + 14
7   libengine2.dylib                0x000000000417a75e CEvent_Dispatch<CEventIDManager_Default, EventClientSimulate_t, 1>::DispatchEvent(EventClientSimulate_t const&, bool, ISchemaBinding const_) + 174
8   libengine2.dylib                0x000000000417a75e CEvent_Dispatch<CEventIDManager_Default, EventClientSimulate_t, 1>::DispatchEvent(EventClientSimulate_t const&, bool, ISchemaBinding const_) + 174
9   libengine2.dylib                0x000000000417560e CLoopTypeClientServer::Update(EngineLoopState_t const&, double, double) + 5694
10  libengine2.dylib                0x000000000405d49a CEngineServiceMgr::_MainLoop(double, double) + 890
11  libengine2.dylib                0x000000000405d0ef CEngineServiceMgr::MainLoop(double, double) + 15
12  libengine2.dylib                0x000000000405707c MainLoop(SwapChainHandle_t___, PlatWindow_t___, InputContextHandle_t___) + 396
13  libengine2.dylib                0x000000000405767e Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 718
14  libengine2.dylib                0x00000000040578a0 Source2Main + 208
15  dota2                           0x0000000003ef8d91 main + 497
16  libdyld.dylib                   0x00007fff8e5015c9 start + 1

**Comment by gdrewb-valve** [comment]
Ideally the engine wouldn't crash even with a bad mod.  I doubt this is a Mac-specific issue but we'll take a look.

**Comment by p-groarke** [comment]
That's pretty much what I thought. May lead to unassigned memory or missing checks etc. This crash happened to the whole team, many times in a row. So somehow the game was in a bad state. Anyways, time for some dota strikers :D

**Comment by gdrewb-valve** [comment]
Does this occur every time you play with that mod or was it just the once?

**Comment by p-groarke** [comment]
It has happened a few times afterwards. But I have not experienced this on the new update.

**Comment by gdrewb-valve** [comment]
OK, we can reopen if you see it again.
