### ISSUE TITLE
Dota2 - New Frontiers Game Not Loading on Mac

### ISSUE THREAD

**Issue by dotagoat** [ValveSoftware/Dota-2#2292]
Macbook/OS users can not load the game after the New Frontiers patch.

**Comment by dotagoat** [comment]
Nor play a game.

**Comment by dotagoat** [comment]
I know this is typically the same issue after EVERY major patch. I suspect we'll just have to wait a few days but really quite annoying that it happens every time. Lots of people game on Macs now.

**Comment by TheNubleet** [comment]
Extremely annoying how this happens every patch. I hope it takes less than a few days for them to fix though...

**Comment by Krit-K** [comment]
As a Mac user after opening the game the game just quit itself. Never had this issue until the 7.33 update. Valve please see and fix this :(

**Comment by whoami5555** [comment]
Same here.. hope they fix it fast

**Comment by FanFanFantastic** [comment]
Broken again for Mac, even basic test cases should cover for Windows and Mac. Did the QA at Dota 2 even bother opening the game for Christ's sake

**Comment by danginsburg** [comment]
Can you please include Steam -> Help -> System Information so we can narrow this down to the affected Mac configurations?  Thank you.

**Comment by TheNubleet** [comment]
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro12,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.13.6 (64 bit)

Video Card:
    Driver:  Intel Iris Graphics 6100
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x162b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.26" x 7.05" (13.27" diag)
                                            28.6cm x 17.9cm (33.7cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  8192 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  239172 MB
    Largest Free Hard Disk Block:  48634 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

**Comment by danginsburg** [comment]
For those affected, can you try unziping the attached copy of libMoltenVK.dylib and overwriting the copy in `~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64` and report back if the crash is fixed?

[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/11311612/libMoltenVK.dylib.zip)

**Comment by TheNubleet** [comment]
If I had any idea how to do that I would.

**Comment by danginsburg** [comment]
It's OK, other users have verified the fix.  It will ship in the next Dota 2 update that goes out.

**Comment by danginsburg** [comment]
Fix for this has shipped.
