### ISSUE TITLE
[Linux] game crashes when any allies alt-clicks a watchers "lit" status.

### ISSUE THREAD

**Issue by MarcusDunn** [ValveSoftware/Dota-2#2293]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/MarcusDunn/18b08b7160b87982cbd40267c78b905a): 
* Have you checked for system updates?: [Yes/No]
I am on fedora 37, 38 is available - but was released a couple days ago and I do not want to upgrade. I highly doubt it would fix the issue.
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes.
* Have you verified the game files?: [Yes/No]
Yes (plus duplicated with friend)

#### Please describe your issue in as much detail as possible:

I alt-clicked a watcher's "lit" status. It instantly crashed my game and a friends (also on linux), our windows friend also tried which also resulted in us both of the linux users (both fedora) crashing.

I was expecting it not to crash my system. It did :(.

#### Steps for reproducing this issue:

1. Alt Click a watchers lit status
2. Watch as a `CBufferString::CheckForUnsafeInputString: unsafe pointer provided as a modification input.` dialog stops your computer from working until you `SEGKILL` dota.
3. Also crashes other Linux users (allies) on the same server.

**Comment by defaultzon3** [comment]
**Reproduced in the match by ID 7117311737.** (created same issue on #2297, without seeing this report)

At 9:25 minutes of game time, I (Pudge) capture the outpost and try to ping the Lit effect, after 9:39 the dota freezes.
I got even more low priority, I would like to be removed, xd. [(id: rzerman228)](https://steamcommunity.com/id/rzerman228/)

**Comment by defaultzone** [comment]
Same effect when trying to alt-click `Invulnerable` status.

**Comment by nathank-valve** [comment]
Fix will be included in the next hotfix

**Comment by kisak-valve** [comment]
A hotfix has shipped for the game, closing per the last comment.
