### ISSUE TITLE
Won't launch after the New Frontiers Update

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/Dota-2#2294]
#### Your system information

* System information from steam: https://gist.github.com/LiamDawe/86cd86562aa7cea4b763bde84f2e5d24
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When I try to launch it, the game doesn't open. Won't launch at all now. Other games work fine.

Full Steam Log of trying to run it: https://gist.github.com/LiamDawe/c365bb8ec3bfb857e1af8cd6722a8024
Crash dump: [crash_20230421111520_2.zip](https://github.com/ValveSoftware/Dota-2/files/11295018/crash_20230421111520_2.zip)

**Comment by kisak-valve** [comment]
Hello @LiamDawe, this looks like https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22600. Can you test the game with mesa rebuilt with that merge request or temporarily disable lavapipe with something like `sudo mv /usr/share/vulkan/icd.d/lvp_icd.x86_64.json /usr/share/vulkan/icd.d/lvp_icd.x86_64.json.disabled`?

**Comment by LiamDawe** [comment]
I'm on NVIDIA so I'm not using Mesa?

**Comment by kisak-valve** [comment]
The merge request should avoid an issue with enumerating available Vulkan drivers, not with using them to render the game.

**Comment by LiamDawe** [comment]
I can confirm disabling lavapipe as suggested does fix it.

**Comment by kisak-valve** [comment]
Thanks, that makes this a duplicate of #2285. Closing in favor of the older issue report.
