### ISSUE TITLE
[Linux] Dota crashes after trying to ping `Lit` effect on watcher. 

### ISSUE THREAD

**Issue by defaultzone** [ValveSoftware/Dota-2#2297]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/defaultzon3/76f4001ca16ddca7c49676b4c86f0b5b
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When you try to ping the `Lit` effect on an watcher, the Dota freezes, it only helps to stop the game process.
In `htop`, Dota 2 proccess has signal `D`.

#### Steps for reproducing this issue:

1. In any game with a new map, we capture any observer **(it doesn’t matter which hero or side)**.
2. Clicking or highlighting a watcher, trying to ping its `Lit` effect.
3. Dota freezes, only stopping the process helps. In `htop`, the process has a `D` signal.

**Comment by kisak-valve** [comment]
Hello @defaultzon3, this issue is already being tracked at #2293. Closing as a duplicate.
