### ISSUE TITLE
[Ubuntu] Hot-keys set/use don't work, game unplayable

### ISSUE THREAD

**Issue by neimovirne** [ValveSoftware/Dota-2#2298]
#### Your system information

* System information from Steam: https://gist.github.com/neimovirne/35764c82697bb661db6a69a5fa63290a
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system?: Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I expected that Dota2 will work perfectly after a fresh install, as it was many times before on previous patches before 7.33 on Ubuntu 22.10/22.04/21.10/etc

#### Steps for reproducing this issue:

1. Install Dota2
2. Start any ranked/demo/unranked game
3. try to use any A-Z/space/shift/ctrl keys as hotkeys for any hero
4. try to change any hotkeys in settings to A-Z/space/shift/ctrl keys - u can't

**Comment by neimovirne** [comment]
I can only use keys TAB/ALT and 1/2/3/4/5/6/7/8/9/0 (but not on a numpad)

**Comment by kisak-valve** [comment]
Hello @neimovirne, can you go to Dota 2 -> Settings gear icon -> To Advanced Hotkeys -> enable `Bind keys based on keyboard position` and test if that gives you the behavior you're looking for?
