### ISSUE TITLE
[Linux/Steam Deck] Dota 2 crashes when opening a case to review

### ISSUE THREAD

**Issue by NuSuey** [ValveSoftware/Dota-2#2299]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/NuSuey/e946787a9924e182594caf3be1632d5b): 
* Have you checked for system updates?: Y
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
As it is clear from the description clicking the button should open the Overwatch case review, it shows some basic fast forward controls on the top right corner, but then proceeds to crash (tried multiple times). Can't know if this would have occurred before the new patch, since I rarely had Overwatch cases to review 

#### Steps for reproducing this issue:

1. Click **Review case**
2. Click **Download**
3.  Click **review case** - Game then crashes and produces a dump file 
[assert_20230421165110_34.zip](https://github.com/ValveSoftware/Dota-2/files/11296967/assert_20230421165110_34.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

**Comment by NuSuey** [comment]
Just in case uploading every dump that was generated in the /tmp/dumps/ if that helps
[crash dumps.zip](https://github.com/ValveSoftware/Dota-2/files/11297354/crash.dumps.zip)
can't test any further though since I don't have cases to review anymore

**Comment by kisak-valve** [comment]
For reference, the first three and fifth crash_ minidump is a SIGSEGV in libtier0.so coming from libengine2.so and libnetworksystem.so. The fourth is a SIGSEGV in "0xff" coming from libvstdlib_s.so. The assert_* minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by ghost** [comment]
the same Problem Here [Platform: Windows v11]

whenever i click Review Case, i get the following Error...
[
CNetworkGameClientBase::ReadEnterPVS():
CopyNewEntity: invalid class index (307), classname 'CDOTA_Clinkz_PiercingArrow'
]
with a single Botton [OK] which force the game to be closed.

**Comment by cdonatom** [comment]
In my case I get this error on Fedora 38

' ' ' ReadEnterPVS():
CopyNewEntity: invalid class index (1519), classname 'CTriggerBuoyancy' ' ' '

**Comment by paboum** [comment]
Same for me. There is absolutely no reason to provide more reproduction data, Valve should at least employ QA engineers if they don't want to hire Overwatch officers and outsource it to players.

**Comment by KleinerKobold** [comment]
Got the same Problem

Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  ROG STRIX B550-A GAMING
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 5900X 12-Core Processor            
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4950 Mhz
    24 logical processors
    12 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "EndeavourOS Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.2.12-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101008
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20230118.0

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 530.41.03
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x1c03
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 84 HDMI/DP

Memory:
    RAM:  32005 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  589490 MB
    Largest Free Hard Disk Block:  57389 MB

Storage:
    Number of SSDs: 4
    SSD sizes: 1000G,480G,256G,120G
    Number of HDDs: 0
    

... please wait for Steam Runtime System Information report:

**Comment by cdonatom** [comment]
This issue seems to be fixed on the latest patch! (Fedora 38)

**Comment by NuSuey** [comment]
Can confirm, tried it on my Steam Deck (desktop mode) and I've finished doing two separate Overwatch cases.
Good job, fixing it so quickly👌Thanks

**Comment by KleinerKobold** [comment]
Game just show Dota logo, cursor changes, nothing else happends

Reinstall doesn't helps anymore

[assert_20230426091506_123.zip](https://github.com/ValveSoftware/Dota-2/files/11330117/assert_20230426091506_123.zip)

**Comment by KleinerKobold** [comment]
Game is working now, had to update kernel, driver and vulkan

**Comment by KleinerKobold** [comment]
And same problems again, I also changed operating system. Now the error also opccurs on Ubuntu 23.04. Other 3D from Steam are running fine

**Comment by NuSuey** [comment]
Is this related to the specified problem with opening cases? From what I gathered from your description you have problem with launching the game, if so, please create another issue for it (if this is about that you have the issue you described when opening the case to review, then ignore what I said)

**Comment by KleinerKobold** [comment]
Ill open my own :)

**Comment by kisak-valve** [comment]
Closing as fixed.
