### ISSUE TITLE
[Linux/Steam Deck] Dota 2 has mini freezes while typing in chat

### ISSUE THREAD

**Issue by NuSuey** [ValveSoftware/Dota-2#2301]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/NuSuey/e946787a9924e182594caf3be1632d5b): 
* Have you checked for system updates?: Y
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I have had these mini freezes before, but I thought they were caused by me playing Dota 2 from an external drive from my Steam Deck (and I thought the drive is too slow) but after moving Dota 2 to the internal drive now, the issue still occurs. It seems it might be caused by the virtual keyboard trying to be opened up. In Steam Deck gameUI it frezes for a second and opens up the virtual keyboard. In the desktop mode it doesnt show the keyboard, but if you start typing, pressing enter freezes the game for a sec, then if you press enter to send it, it freezes it again. Also does more freezes for each time you try to post an emoji. if you press the Meta key or alt tab while you are typing in the chat "line", it will show the virtual keyboard (see screenshot). Otherwise it seems to be hidden
![image](https://user-images.githubusercontent.com/22767916/233675727-00055de4-fd51-4432-a059-fd2716484052.png)

Even just pressing enter to enter the chat and then enter to leave it,  does this in the terminal:
```
ExecCommandLine: "'~/.steam/root/ubuntu12_32/steam' 'steam://open/keyboard?XPosition=0&YPosition=0&Width=0&Height=0&Mode=1'"
ExecuteSteamURL: "steam://open/keyboard?XPosition=0&YPosition=0&Width=0&Height=0&Mode=1"
ExecCommandLine: "'~/.steam/root/ubuntu12_32/steam' 'steam://close/keyboard'"
ExecuteSteamURL: "steam://close/keyboard"
```

Also, something that I didn't experience before (don't normally post in these). After starting the game I cannot write in the various channels, I can paste clipboard though, virtual keyboard doesn't seem to be opening in the Desktop mode. Haven't tried in GameUI

#### Steps for reproducing this issue:

1. On Steam Deck, enter a match or Demo mode
2. Press Enter - Freeze, press enter to send - Freeze
3.  Try to write any emoji (press ":") - Freeze

**Comment by NuSuey** [comment]
Also another observation:
I had "Desktop-friendly fullscreen minimizes on focus loss" turned off. I had it reverted due to a problem I had, and then I found out, that if you have it enabled and when you try to type anything in the chat, it minimizes Dota 2, each time when you try to type (probably trying to run the virtual keyboard, outsite of dota 2) happens every time

**Comment by Micmonta** [comment]
I also always had this issue, Dota installed on internal SSD. Exactly the same steps to reproduce. The issue does not happen on windows on my steam deck with windows running on an external SSD. The FPS is also much better on Windows on Deck.

**Comment by djcarryout** [comment]
this issue started for me after the Muerta patch

**Comment by shearwavesplitter** [comment]
This is driving me mad. Also on steam deck in desktop mode

Pressing enter to chat will or clicking on the search button in shop will minimise dota for me and often disconnect me from the game 

Same issue as [https://github.com/ValveSoftware/Dota-2/issues/2268](https://github.com/ValveSoftware/Dota-2/issues/2268)

**Comment by NuSuey** [comment]
@shearwavesplitter  turn off "Desktop-friendly fullscreen minimizes on focus loss" in the settings
Would love if somebody could look at it. 
Currently the only real "workaround" is just not to use the native version. Playing via Proton doesn't have the "virtual keyboard" freezes that I mentioned

**Comment by INNKCake** [comment]
Same issue here

**Comment by NuSuey** [comment]
After a few months of playing via Proton and then a smaller pause from Dota 2, I ran it again natively and the issue seems to be gone. Can somebody else also confirm this? Thanks

**Comment by INNKCake** [comment]
@NuSuey yes, it seems to be fixed recently, probably with the last update. Although now the Cyrillic input is now broken, resulting in adding additional characters to some letters:
`йцук?'?е?'?нгшщл?@\р?@\п?@\а?'?`
But that can be a completely unrelated new bug.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
