### ISSUE TITLE
Dota 2 not launching since upgrade to Fedora 38

### ISSUE THREAD

**Issue by laurentpellegrino** [ValveSoftware/Dota-2#2302]
#### Your system information

* System information from steam:
  https://gist.github.com/lpellegr/52bcb186ea7b44c5081a59a62c380570 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

The game crashes upon start, almost immediately.

#### Steps for reproducing this issue:

1. Run Dota 2 from Steam or from CLI: ~/.local/share/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh

Here is the command line output:

https://gist.github.com/lpellegr/d96d60587e639ed331e2af239333b7eb

The dump file (/tmp/dumps/crash_20230421203504_2.dmp) contains references to "Attempt to free invalid pointer" and "Attempt to realloc invalid". So I guess it is related to an incompatible library used on Fedora 38.

Any solution or workaround is welcome.

**Comment by cdonatom** [comment]
Try this: 
``` sudo mv /usr/share/vulkan/icd.d/lvp_icd.x86_64.json /usr/share/vulkan/icd.d/lvp_icd.x86_64.json.disabled ```

**Comment by kisak-valve** [comment]
Hello @lpellegr, this issue is already being tracked at #2285. Closing as a duplicate.

**Comment by laurentpellegrino** [comment]
Thanks for your help. The workaround is running nicely.
