### ISSUE TITLE
New patch - constant crashes

### ISSUE THREAD

**Issue by a3v5** [ValveSoftware/Dota-2#2305]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Y
* Are you using the latest stable video driver available for your system? Y
* Have you verified the game files?: Y

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1.
2. 
3. 

![01](https://user-images.githubusercontent.com/121069777/233774644-7b65c566-8a6a-4f63-b4ad-9faba07b189a.jpg)
![02](https://user-images.githubusercontent.com/121069777/233774648-407ed138-6e10-4dba-951f-0942610bf861.jpg)

[dota2_2023_0422_114338_0_error.zip](https://github.com/ValveSoftware/Dota-2/files/11300805/dota2_2023_0422_114338_0_error.zip)

**Comment by kisak-valve** [comment]
Hello @a3v5, the update of game files is handled by Steam, not the game. Since it looks like you're using the Steam client for Windows, please report this issue to [Steam Support](https://help.steampowered.com).
