### ISSUE TITLE
7.33 Patch is not working on ANY MAC. FIX THIS ASAP 

### ISSUE THREAD

**Issue by interprise20** [ValveSoftware/Dota-2#2307]
VALVE, why cannot just publish a new major patch with thinking of Mac users as well? It just instantly quits the game after the VALVE intro. The last time when the major patch was out, you had the same issue. This is now more than 30 hours in, and the problem still persists and has not been fixed.

**Comment by kisak-valve** [comment]
Hello @interprise20, this issue is already being tracked at #2292. Closing as a duplicate.
