### ISSUE TITLE
[MAC] Dota2 Reborn Crashed When I Accept A Match and Exit match

### ISSUE THREAD

**Issue by peter21581** [ValveSoftware/Dota-2#231]
It happens every time when i accept a match or exit match(at the end). 
Here is the crash info.  

Full crash info here: http://d.mzpeter.co.uk/nTAw+
System information here: http://d.mzpeter.co.uk/1jjcW+
Video record: http://d.mzpeter.co.uk/14OdB+

Date/Time:       2015-07-19 00:08:56 +0700
OS Version:      10.10.4 (Build 14E46)
Architecture:    x86_64h
Report Version:  21

Command:         dota2
Path:            /Users/USER/Library/Application Support/Steam/*/dota2
Version:         ??? (???)
Parent:          bash [889]
Responsible:     steam_osx (Steam) [505]
PID:             892

Event:           hang
Duration:        1.20s (process was unresponsive for 8 seconds before sampling)
Steps:           13 (100ms sampling interval)

Hardware model:  MacBookPro11,5
Active cpus:     8

Fan speed:       6157 rpm

---

Timeline format: stacks are sorted chronologically
## Use -i and -heavy to re-report with count sorting

Heaviest stack for the main thread of the target process:
  13  start + 1 (libdyld.dylib + 13769) [0x7fff8cef15c9]
  13  main + 497 (dota2 + 3473) [0x655bd91]
  13  Source2Main + 208 (libengine2.dylib + 391328) [0x66b68a0]
  13  Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 718 (libengine2.dylib + 390782) [0x66b667e]
  13  MainLoop(SwapChainHandle_t___, PlatWindow_t___, InputContextHandle_t___) + 396 (libengine2.dylib + 389244) [0x66b607c]
  13  CEngineServiceMgr::MainLoop(double, double) + 15 (libengine2.dylib + 413935) [0x66bc0ef]
  11  CEngineServiceMgr::_MainLoop(double, double) + 2107 (libengine2.dylib + 416091) [0x66bc95b]
  11  CLoopTypeClientServer::OnLoopDeactivate(EngineLoopState_t const&, CEventDispatcher<CEventIDManager_Default>_) + 9 (libengine2.dylib + 1553865) [0x67d25c9]
  11  CLoopTypeBase::OnLoopDeactivate(EngineLoopState_t const&, CEventDispatcher<CEventIDManager_Default>_) + 71 (libengine2.dylib + 1542471) [0x67cf947]
  11  CLoopTypeClientServerService::OnLoopDeactivate(EngineLoopState_t const&, CEventDispatcher<CEventIDManager_Default>_) + 96 (libengine2.dylib + 1591344) [0x67db830]
  11  CLoopModeGame::OnLoopDeactivate(EngineLoopState_t const&, CEventDispatcher<CEventIDManager_Default>_) + 232 (libclient.dylib + 15332584) [0xa514f4e8]
  11  IGameSystem::LoopDeactivateAllSystems(EngineLoopState_t const&, bool) + 162 (libclient.dylib + 14882178) [0xa50e1582]
  11  void IGameSystem::DispatchEventReverseOrder<EventGameDeactivate_t>(EventGameDeactivate_t const&) + 208 (libclient.dylib + 14884080) [0xa50e1cf0]
  11  CBaseGameStats_Driver::GameDeactivate(EventGameDeactivate_t const&) + 180 (libclient.dylib + 1530708) [0xa4425b54]
  11  CBaseGameStats_Driver::SendData() + 201 (libclient.dylib + 1530073) [0xa44258d9]
  11  CUploadGameStats::UploadGameStats(char const_, unsigned int, unsigned int, void const_) + 388 (libengine2.dylib + 2391556) [0x689ee04]
  11  Win32UploadGameStatsBlocking(TGameStatsParameters const&) + 2711 (libengine2.dylib + 2390023) [0x689e807]
  11  __recvfrom + 10 (libsystem_kernel.dylib + 90938) [0x7fff82d7433a]
 *11  hndl_unix_scall64 + 22 (kernel + 2315126) [0xffffff8000435376]
 *11  unix_syscall64 + 662 (kernel + 6601814) [0xffffff800084bc56]
 *11  recvfrom_nocancel + 234 (kernel + 6441146) [0xffffff80008248ba]
 *11  ??? (kernel + 6453115) [0xffffff800082777b]
 *11  soreceive + 2319 (kernel + 6383439) [0xffffff800081674f]
 *11  sbwait + 310 (kernel + 6415270) [0xffffff800081e3a6]
 *11  msleep + 98 (kernel + 6142690) [0xffffff80007dbae2]
 *11  ??? (kernel + 6143785) [0xffffff80007dbf29]
 *11  lck_mtx_sleep + 134 (kernel + 1276342) [0xffffff80003379b6]
 *11  thread_block_reason + 175 (kernel + 1319343) [0xffffff80003421af]
 *11  ??? (kernel + 1329236) [0xffffff8000344854]
 *11  machine_switch_context + 367 (kernel + 2176511) [0xffffff80004135ff]

**Comment by gdrewb-valve** [comment]
Is this a crash where the game exits?  The report info you have here is for a hang, the same hang as #230.  That should be addressed now, are you still having problems?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this is different from the resolved hang.
