### ISSUE TITLE
[OS X] [Feature] Add firewall exception.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#232]
Since mods often use a players computer as server host, the OS X firewall popup to allow incoming connections comes up a lot. The problem with it, is it doesn't save your prefs. I've tried adding rules manually, but it seems I don't have the right executable or what-not.

Anyways, would be nice to simply add a rule when you install dota/start it up. This requires user password, but should be good in the long run, to make sure no-one skips the allow incoming connections dialog. Thank you and have a great day.

**Comment by rained23** [comment]
#211

**Comment by gdrewb-valve** [comment]
The end result of this is the same but there two different things being discussed.  In #211 what the larger team will be looking at is not cycling listening sockets so much so that if you get a permission dialog you'll only get one per process execution.  This particular issue would be an even bigger fix in that adding a firewall exception would suppress all future prompts and would make the larger team's work unnecessary.  However it's unclear which will come first.

**Comment by p-groarke** [comment]
After doing a little research on this topic, it seems the actual problem is code-signing the application. The OS X firewall allows incoming connections by code signed applications by default. Obtaining a valid certificate for Valve seems trivial (if you don't already own one). I guess since the executable hierarchy is very different running through Steam, fixing this might be more involved than just using the codesign utility.

**Comment by rained23** [comment]
@Socapex is there a possible way to bypass this on OS level for now ? If you have mind to share ?

**Comment by p-groarke** [comment]
I haven't been able to no. I haven't found a way googling either. I've added ~/Library/Application Support/Steam/SteamApps/common/dota 2 beta/game/bin/osx64 to the firewall, and the old executable was already there. This is the executable running when I checked with Activity Monitor, but it wont work. I'm thinking the firewall wants the certificate.

**Comment by rained23** [comment]
@Socapex maybe its not osx64 that host a game, there might be something running. I will try this too. Because I never had any firewall permission asked when I run as example mysqld or something that listening to a port.

**Comment by gdrewb-valve** [comment]
I'm not sure if this would help or not but it seemed interesting.  http://robcottingham.ca/2008/03/os-x-applications-constantly-asking-permission-to-accept-incoming-connections-heres-a-fix/

**Comment by rained23** [comment]
@gdrewb-valve can I know which binary that actually trying to accept the incoming connection ?

**Comment by gdrewb-valve** [comment]
The executable is dota2 in game/bin/osx64.  The particular dylib is most likely networksystem.dylib.
