### ISSUE TITLE
DOTA2 consumes all cpu's

### ISSUE THREAD

**Issue by eeyrjmr** [ValveSoftware/Dota-2#2323]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): unable to - bug in beta client
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Since saturday update, dota2 will consume all cores and excessive threads while being extremely laggy

### Screenshots
![2023-05-01_14-05-1682947750](https://user-images.githubusercontent.com/4564448/235458225-8e7a0f9b-41da-4699-bb6a-4bbf0146a6a5.jpg)

This is just at the main screen. This is unplayable
```
ps -eo pcpu,pid,user,args | tail -n +2 | sort -k1 -r -n | head -10
 436 11151 jrb      /home/jrb/.local/share/Steam/ubuntu12_64/steamwebhelper --type=renderer --disable-seccomp-filter-sandbox --log-file=/home/jrb/.local/share/Steam/logs/cef_log.txt --field-trial-handle=177762469
 251 11140 jrb      /home/jrb/.local/share/Steam/ubuntu12_64/steamwebhelper --type=renderer --disable-seccomp-filter-sandbox --log-file=/home/jrb/.local/share/Steam/logs/cef_log.txt --field-trial-handle=177762469
 181 11083 jrb      /home/jrb/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama
 179 11146 jrb      /home/jrb/.local/share/Steam/ubuntu12_64/steamwebhelper --type=renderer --disable-seccomp-filter-sandbox --log-file=/home/jrb/.local/share/Steam/logs/cef_log.txt --field-trial-handle=177762469
 4.1  4263 jrb      /usr/bin/pipewire -c pipewire-pulse.conf
```

**Comment by eeyrjmr** [comment]
ok its the steam client beta. Downgrade and its all back to normal.
bug in the client

![2023-05-01_14-05-1682949088](https://user-images.githubusercontent.com/4564448/235461403-e360108a-acdd-4ced-b1d1-d320bad619df.jpg)

**Comment by kisak-valve** [comment]
Hello @eeyrjmr, if you completely close Steam, then run `steam` from a terminal, does that have an effect?

**Comment by eeyrjmr** [comment]
> Hello @eeyrjmr, if you completely close Steam, then run `steam` from a terminal, does that have an effect?

hi, tried that, no change :( 
It looks like the new steam-beta client and the steamwebhelper process eating IO

**Comment by Turmfalke2** [comment]
I recommend starting steam with `-no-browser +open steam://open/minigameslist`, doing so gives me much higher fps in the game. Also avoid using the arrow in the top left corner that switches to the dashboard. That tends to degrade performance until the game gets restarted.

**Comment by eeyrjmr** [comment]
> I recommend starting steam with `-no-browser +open steam://open/minigameslist`, doing so gives me much higher fps in the game. Also avoid using the arrow in the top left corner that switches to the dashboard. That tends to degrade performance until the game gets restarted.

Thankyou for your reply, I am already doing this to squeeze every last drop out :) 
This issue is totally different though where a STEAM process consumes all resources

**Comment by ahadtk89** [comment]
> ok its the steam client beta. Downgrade and its all back to normal. bug in the client
> 
> ![2023-05-01_14-05-1682949088](https://user-images.githubusercontent.com/4564448/235461403-e360108a-acdd-4ced-b1d1-d320bad619df.jpg)

Hey, how do I go back to an old client. I’m also facing this issue where dota 2 is constantly stuttering and dropping fps even on idle

**Comment by eeyrjmr** [comment]
I am closing this, when the "beta" was promoted to stable there must have been a change (somewhere) and the behaviour is as expected.
