### ISSUE TITLE
[OS X] Crash when zooming on hero.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#233]
So this was a pretty hard crash, playing GreenTD Reborn. Happened instantly when zooming on hero (I'm pretty sure I hit the console key at the same time).

Process:               dota2 [2130]
Path:                  /Users/USER/Library/Application Support/Steam/*/dota2
Identifier:            dota2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [2127]
Responsible:           steam_osx [1840]
User ID:               501

Date/Time:             2015-07-19 02:03:35.283 -0400
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        7FB7401D-CACC-B0E4-83E7-07E82A294D71

Sleep/Wake UUID:       0A3B930A-4C45-40D9-80FE-5EAC72268926

Time Awake Since Boot: 91000 seconds
Time Since Wake:       29000 seconds

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000001c

Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libclient.dylib                 0x00000000a517dde4 CBaseCamera::PostThink() + 36
1   libclient.dylib                 0x00000000a539722e CDOTACameraManager::Think() + 14
2   libclient.dylib                 0x00000000a51842f0 OnFrameSimulate() + 224
3   libclient.dylib                 0x00000000a51845de CSource2Client::FrameStageNotify(ClientFrameStage_t) + 654
4   libengine2.dylib                0x0000000001474aba CNetworkGameClient::OnClientFrameSimulate(EventClientFrameSimulate_t const&) + 250
5   libengine2.dylib                0x0000000001462eec CNetworkClientService::OnClientFrameSimulate(EventClientFrameSimulate_t const&) + 348
6   libengine2.dylib                0x000000000145a15e CEvent_Dispatch<CEventIDManager_Default, EventClientFrameSimulate_t, 1>::DispatchEvent(EventClientFrameSimulate_t const&, bool, ISchemaBinding const_) + 174
7   libengine2.dylib                0x0000000001459b35 void CLoopTypeBase::DispatchEvent<EventClientFrameSimulate_t>(CEventDispatcher<CEventIDManager_Default>_, EventClientFrameSimulate_t const&, CEventRegistry&) + 69
8   libengine2.dylib                0x0000000001456010 CLoopTypeClientServer::Update(EngineLoopState_t const&, double, double) + 8256
9   libengine2.dylib                0x000000000133d49a CEngineServiceMgr::_MainLoop(double, double) + 890
10  libengine2.dylib                0x000000000133d0ef CEngineServiceMgr::MainLoop(double, double) + 15
11  libengine2.dylib                0x000000000133707c MainLoop(SwapChainHandle_t___, PlatWindow_t___, InputContextHandle_t___) + 396
12  libengine2.dylib                0x000000000133767e Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 718
13  libengine2.dylib                0x00000000013378a0 Source2Main + 208
14  dota2                           0x00000000011dcd91 main + 497
15  libdyld.dylib                   0x00007fff95ef25c9 start + 1

**Comment by gdrewb-valve** [comment]
This happens on Windows also so I've passed it on to the larger team.
