### ISSUE TITLE
Vulkan Annoying White Square

### ISSUE THREAD

**Issue by fractaltr33** [ValveSoftware/Dota-2#2330]
#### Your system information

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
When I select Vulkan render, during the game and even in the menu, with each LMB click a white square appears on the left in the middle.
![4AAQSkZJRgAB](https://github.com/ValveSoftware/Dota-2/assets/109732308/b395735e-41ab-41e5-9005-8810bab93101)

#### Steps for reproducing this issue:

1. Choose Vulkan render
2. Restart game
3. Click LMB

**Comment by kisak-valve** [comment]
Hello @fractaltr33, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by fractaltr33** [comment]
I'm sorry. The problem was solved by installing the latest Nvidia drivers)
