### ISSUE TITLE
gl_arb_separate_shader_objects is not supported [Ubuntu 14.04]

### ISSUE THREAD

**Issue by oBerrypunch** [ValveSoftware/Dota-2#234]
Sorta new to ubuntu, no idea how to fix this issue.

**Comment by CommanderAlchemy** [comment]
@oBerrypunch start by reading the README.md in this repo: https://github.com/ValveSoftware/Dota-2-Reborn

**Comment by danginsburg** [comment]
@oBerrypunch It is very likely you do not have updated drivers or you are running with unsupported hardware.  GL_ARB_separate_shader_objects is a required OpenGL extension and is supported by mesa along with closed source NVIDIA and AMD drivers.  Please post your system information and we can point you to the correct driver.

**Comment by oBerrypunch** [comment]
How do I find system information that doesn't list everything down to the usbs and isn't a pain to copy?

**Comment by danginsburg** [comment]
In Steam, go to Help -> System Information

**Comment by daren25** [comment]
Having the exact same problem
I have an r9 280 video card running on linux mint
Here is the system information output

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2800 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.1 Rebecca (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-37-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x68f9
Number of Monitors:  3
```

 Number of Logical Video Cards:  2
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 4480 x 1080
    Primary Display Size: 13,31" x 10,67"  (17,05" diag)
                                            33,8cm x 27,1cm  (43,3cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7901 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  137674 Mb
    Largest Free Hard Disk Block:  68181 Mb

**Comment by ArnaudAndre** [comment]
Both mint 17.1 and ubuntu 14.04 come with the 10.1.x branch of mesa. Mesa 10.1 is one year and a half old, it's not going to run reborn. Afaik nothing before 10.5 can run reborn. (not even sure 10.5 is good enough, 10.6 may be necessary)

**Comment by DeepDlueIV** [comment]
14.04 is going with mesa 10.3 
But not, i dont know how to update to 10.6 xorg-edgers ppa should have this package, but synaptic can't find him

**Comment by daren25** [comment]
Thanks for the help, I used the oibaf ppa 
sudo add-apt-repository ppa:oibaf/graphics-drivers

and everything works.

**Comment by danginsburg** [comment]
Right, so mesa 10.1 is not supported because it does not have GL_ARB_separate_shader_objects.  mesa 10.3.2 works, but there is a bug that causes shadow flickering, see: #55.  That bug report has a patch for the shadowmap flickering which is now in mesa master.

**Comment by oBerrypunch** [comment]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3500 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-57-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 13.31" x 10.63"  (17.01" diag)
                                        33.8cm x 27.0cm  (43.2cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7967 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  142017 Mb
    Largest Free Hard Disk Block:  58880 Mb

**Comment by WhiteAxe** [comment]
this is what my open gl info is and I get that exact error it says update your open gl drivers
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30

**Comment by ghost** [comment]
Last night's Dota 2 update broke on my machine.  I'm now greeted with:

Required OpenGL extension "GL_ARB_separate_shader_objects" is not supported. Please update your OpenGL driver.

I see earlier comments suggesting upgrading to Mesa 10.5 or higher, but Mesa 10.1.3 is the latest package available in Ubuntu 14.04.  How can I go back to pre-Reborn Dota 2 which worked?

Here is my system information:

Processor Information:
Vendor: GenuineIntel
CPU Family: 0x6
CPU Model: 0x1a
CPU Stepping: 0x4
CPU Type: 0x0
Speed: 2668 Mhz
8 logical processors
4 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed: 

Operating System Version:
Ubuntu 14.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 3.13.0-63-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11501000
X Window Manager: Openbox
Steam Runtime Version: steam-runtime-release_2015-06-12

Video Card:
Driver: X.Org Gallium 0.4 on AMD RV770

Driver Version: 3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x1002
DeviceID: 0x9440
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20.91" x 11.73" (23.94" diag)
53.1cm x 29.8cm (60.8cm diag)
Primary VRAM Not Detected

Sound card:
Audio device: Analog Devices AD1989B

Memory:
RAM: 12007 Mb

Miscellaneous:
UI Language: English
LANG: C
Microphone: Not set
Total Hard Disk Space Available: 5548021 Mb
Largest Free Hard Disk Block: 4696291 Mb

$ sudo apt-get dist-upgrade
[sudo] password for mbrown: 
Reading package lists... Done
Building dependency tree 
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tiburcillo** [comment]
No panic, if you have some experience with adding PPA's just add the following:
https://launchpad.net/~xorg-edgers/+archive/ubuntu/ppa

Then your Mesa will be updated to 10.6 and you will be able to run Reborn fine.

*I am not responsible for any broken systems

**Comment by josephmate** [comment]
tiburcillo's advice (except I used a different PPA) worked for me but you have to becareful:

On the sudo apt-get upgrade step, you might see:

```
sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-get update
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer
    required:
  account-plugin-windows-live libupstart1
Use 'apt-get autoremove' to remove them.
The following packages have been kept back:
  libdrm-dev libdrm-intel1 libdrm-intel1:i386 libdrm-nouveau2
  libdrm-nouveau2:i386 libdrm-radeon1 libdrm-radeon1:i386 libdrm2     libdrm2:i386
  libegl1-mesa libegl1-mesa-drivers libgbm1 libgl1-mesa-dev libgl1-mesa-dri
  libgl1-mesa-dri:i386 libgl1-mesa-glx libgl1-mesa-glx:i386 libglapi-mesa
  libglapi-mesa:i386 libgles1-mesa libgles2-mesa libosmesa6 libosmesa6:i386
  libva1 libwayland-egl1-mesa mesa-common-dev xserver-xorg-video-intel
```

The key part is that the upgrade I wanted to do didn't happen:

```
The following packages have been kept back:    
```

You will have to:

```
sudo apt-get install <list of packages kept back>
```

I ended up doing:

```
sudo apt-get install libegl1-mesa libegl1-mesa-drivers xserver-xorg-video-intel libgl1-mesa-dri libglapi-mesa 
```

For more information on this problem see: http://askubuntu.com/questions/501560/how-to-update-opengl-driver-on-ubuntu-14-04-lts/672301#672301

**Comment by ghost** [comment]
Thanks tiburcillo & josephmate.  For others hitting this the following worked for me:

$ sudo add-apt-repository ppa:xorg-edgers/ppa
$ sudo apt-get update
$ sudo apt-get dist-upgrade
$ sudo reboot

**Comment by tiburcillo** [comment]
Yeah I was in a hurry so couldn't give extended information. Basically the difference between the xorg-edgers and the oibaf ppa's is that the former generally uses the latest released Mesa GL drivers while the latter is a daily developer alpha/beta build for people that like living on the edge. :)

**Comment by Ace321** [comment]
I haven't been on my computer in a while so my drivers are outdated. I was just wondering if these packages could potentionally harm my computer if not done correctly and how to do it correctly. My system information is: 
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CAPE VERDE

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x683d
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                        59.8cm x 33.6cm  (68.5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  3814 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  464864 Mb
    Largest Free Hard Disk Block:  422321 Mb

Installed software:

Recent Failure Reports:

**Comment by nisbahmumtaz** [comment]
Running Windows 7 x64, realized I never updated Windows.
After running Windows Update, got the same problem.
http://files.catbox.moe/f53806.png

Updating drivers didn't help. Running a mobile Nvidia card (GT750M), on i7-4100MQ.

**Comment by milanb441** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2601 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6840
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12.17" x 6.85"  (13.94" diag)
                                        30.9cm x 17.4cm  (35.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3845 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  464897 Mb
    Largest Free Hard Disk Block:  261378 Mb

Installed software:

Recent Failure Reports:

**Comment by Tele42** [comment]
@milanb441 mesa 10.5.9 or newer is supported for Dota 2 on intel graphics.

**Comment by SupremeCommanderOfTheAsgardHighCouncil** [comment]
So i just got Linux too and download Dota 2 and now i am receving this problem:

"Required OpenGL extension "GL_ARB_separate_shader_objects" is not supported. Please update your OpenGL driver."

Here is my system information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3001 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Zorin OS 9 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-77-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Desktop x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x152
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,78" x 10,55"  (21,54" diag)
                                        47,7cm x 26,8cm  (54,7cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  3853 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  934839 Mb
    Largest Free Hard Disk Block:  858327 Mb

Installed software:

Recent Failure Reports:

**Comment by mauer01** [comment]
I have this Computer System:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.3 Rosa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-38-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xa16
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13,54" x 7,64"  (15,51" diag)
                                        34,4cm x 19,4cm  (39,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  3889 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  152896 Mb
    Largest Free Hard Disk Block:  38536 Mb

and getting this Problem when i try to run dota 2: "Required OpenGL extension "GL_ARB_separate_shader_objects" is not supported. Please update your OpenGL driver."

I'm not used to be a noob in handling Linux, but pls threat me like one because i haven't found a way to fix this problem yet and need definitly your help.

**Comment by CommanderAlchemy** [comment]
Like previous posts, you guys need to update mesa. All of you are running an older version.

@nisbahmumtaz, um have you updated your nvidia driver from nvidia.com? Probably an optimus issue on Windows that runs the game on the Intel card instead.

**Comment by ggaaooppeenngg** [comment]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x12
    CPU Model:  0x1
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  1500 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-65-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD SUMO

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x9647
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12.17" x 6.81"  (13.94" diag)
                                        30.9cm x 17.3cm  (35.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3421 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  465322 Mb
    Largest Free Hard Disk Block:  174622 Mb
    VR Headset: None detected

I have the same problem
