### ISSUE TITLE
Binding to Circumflex-key does not work with german keyboard layout

### ISSUE THREAD

**Issue by Wuerstchen** [ValveSoftware/Dota-2#235]
Binding any command to the circumflex key does not work with German keyboard layout. In the chat it's working, though.

**Comment by gdrewb-valve** [comment]
Can you post your system info?  Are you changing your keyboard layout at any time or are you booting with a German layout?

**Comment by Wuerstchen** [comment]
I'm booting with a german layout and do not change it at any time. All my friends have that issue on Windows 7 and Windows 8.1, too.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Xubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-22-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 349.16
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x13c0
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 14,80" x 11,85"  (18,94" diag)
                                        37,6cm x 30,1cm  (48,1cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7919 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  217214 Mb
    Largest Free Hard Disk Block:  70157 Mb

**Comment by gdrewb-valve** [comment]
OK, as this doesn't sound like a Mac/Linux issue I'll pass it on to the larger team.

**Comment by schamanski** [comment]
Hi everyone,
this seems to be still active. Having the issue on Linux though.

1. Starting Dota 2
2. Going to hotkey settings
3. Want to bind any action hotkey to circumflex key on german layout keyboard

Expected behaviour: Seeing the circumflex key as hotkey for chosen action and being able to use it in game.
Actual behaviour: Seeing a blank field as hotkey for chosen action and not being able to use it in game.

Integrity Check brought up nothing.
"^" is working fine.
Same behaviour on different pc with Manjaro-Linux and german layout.
Changing to english(us) keyboard layout lets me bind a hotkey to the backtick (`) key.

If you want me to open a new issue i will gladly do so.
Thanks for any help in advance.
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 5800X 8-Core Processor             
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3800 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.9.16-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12010000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20201203.1

Video Card:
    Driver:  NVIDIA Corporation GeForce 8800 GT/PCIe/SSE2
    Driver Version:  3.3.0 NVIDIA 340.108
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x611
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76" (24.02" diag)
                                            51.8cm x 32.4cm (61.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALCS1200A

Memory:
    RAM:  32119 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  937572 Mb
    Largest Free Hard Disk Block:  767112 Mb
```
