### ISSUE TITLE
[OS X Yosemite] Unable to download custom game

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#236]
Hi,

From previous update caused Install will stuck at Download Queued.

![image](https://cloud.githubusercontent.com/assets/907309/8789005/7a539538-2f71-11e5-81cb-16fe77078175.png)

Checking Steam showing the Steam Workshop are in infinite loop of Update Required & In Queue.

![image](https://cloud.githubusercontent.com/assets/907309/8789024/9cb4a2d4-2f71-11e5-9e0d-f1d83db15b53.png)

I need to close Reborn to finish the download, probably this is Steam bug, but affect Reborn.

Before it works.

Specs
![image](https://cloud.githubusercontent.com/assets/907309/8802805/39105e6e-2ff6-11e5-8cea-8dae9e85896b.png)

For Steam setting, I have Allow download during gameplay ticked and Steam Overlay enabled.

**Comment by p-groarke** [comment]
rained23, you should black out the serial number! gday

**Comment by rained23** [comment]
@Socapex removed.

**Comment by gdrewb-valve** [comment]
Are you running the Steam client beta?  If not can you opt into it and see if that helps?

**Comment by gdrewb-valve** [comment]
@rained23, did you check on which Steam client you are running?

**Comment by rained23** [comment]
Opting beta fix this, not sure update or opt in, but currently its working now.
