### ISSUE TITLE
[OS X] Desktop friendly or exclusive don't allow workspace switching.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#237]
First of all, HUGE update! Congrats :D Of course there are a few issues.

Both new fullscreen modes seem worst than before. You can no longer switch workspace (ctrl + arrow left). I personally never had issues with how it was. The game was extremely dual-screen friendly. Keep those updates coming :)

This doesn't really seem like a huge problem, but at first launch: http://i.imgur.com/SZ9wF9B.jpg

**Comment by gdrewb-valve** [comment]
The old fullscreen option is unchanged so this may be a result of no longer using spaces.

**Comment by bklooster** [comment]
Can confirm that when launching the game with Exclusive Fullscreen set the menubar remains at the top of the screen. If I go through to video settings and hit apply it will correctly display on top. If I use "use desktop settings" it will appear correctly on top of the menubar. 

I am running the 10.11 beta so that may be related. (system information https://gist.github.com/bklooster/6026046)

**Comment by gdrewb-valve** [comment]
Does the exclusive fullscreen issue occur on repeated launches or was it only the first launch after the update?  I believe this might be an issue upgrading the settings to account for the new fullscreen mode.  If it occurs multple times does it occur once you change your video settings and then relaunch?

**Comment by bklooster** [comment]
For me, it occurred every time I launched the game. It happens to me in both desktop friendly fullscreen and exclusive fullscreen. On launch even when set to exclusive mode my secondary monitor wouldn't blank until I hit the apply button in settings. 

The only time I could game to launch fullscreen in front of the menubar is when I saved the setting to the "use desktop settings"  radio button (or whatever the automatic option is above the manual setting). It launched correctly in front of the menubar in a non-exclusive mode.

**Comment by gdrewb-valve** [comment]
I can repro and I believe I've found the problem.  The next update will have a fix.

**Comment by bklooster** [comment]
Whoops I think I completely hijacked this bug report, sorry! I thought the original poster was referring to the menubar, but I think the original poster was referring to the empty space (that I believe was a server issue that was fixed for the store). So you may not want to close this ticket until the first issue about command-tab/space management is fixed.

**Comment by gdrewb-valve** [comment]
No worries, this will stay open so that we can resolve the spaces/not-spaces issue.

**Comment by p-groarke** [comment]
Just to make it clear. The issues is Mission Control Spaces (multiple desktops) not working anymore in any fullscreen mode. Hope that makes it more clear :)

Before update: ctrl + left arrow worked (Switches Desktop Space).
Now: doesn't work (absolutely have to alt-tab out of game if you need to access desktop).

Oh, and just because I need to mention it somewhere, OH MY GOD THE PERFORMANCE ON OSX IS CRAZY!!!11!!111 I don't know what kind of voodoo magic trick you pulled off, but I haven't been able to run Dota at these settings in forever! Thank you :)

**Comment by gdrewb-valve** [comment]
That's clear.  We were using the SDL mode which puts fullscreen apps in their own space but that was causing problems so we turned it off.  I believe that's the cause of the change affecting you.  We're working with the SDL devs to see if we can fix the underlying problems and then we'll be able to turn separate spaces back on.

**Comment by p-groarke** [comment]
<3 SDL

**Comment by alkore** [comment]
Sorry to hijack this thread but maybe it's related ; I can't seem to be able to CMD + TAB while in fullscreen ? Is it the way it's supposed to be ?

**Comment by gdrewb-valve** [comment]
Yes, see #6.

**Comment by gdrewb-valve** [comment]
SDL bug #3066.

**Comment by davidef** [comment]
@gdrewb-valve Any chance to get this fixed ? It's quite annoying not being able to easily switch between desktop & dota. On SDL's Bugzilla is seams there was a patch to be tested in August.

**Comment by danginsburg** [comment]
SDL bug #3066 has been fixed.  We have integrated the fix into Source 2 and it will be in a future release.  This will allow you to switch spaces when in Desktop Friendly Fullscreen mode.

**Comment by p-groarke** [comment]
Great news! Thank you for updating these bug reports. Just for the record, the later addition of dual screen helped a lot in this regard. The combination of both the spaces fix and dual-screen will be an even better outcome :) Keep it up!

**Comment by mfilej** [comment]
Awesome! :heart_decoration:

**Comment by danginsburg** [comment]
Fix has been released.  Closing.
