### ISSUE TITLE
[OS X] If mouse cursor isn't overridden, clicks don't register.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#238]
This happened when first launching the game. I tried to record a video, but as that removes focus from the window, the custom cursor gets applied and the clicks register.

If the game doesn't override the cursor, than many clicks don't register.

Fix, lose focus of window and refocus (ex: minimize window). Then custom cursor kicks in and works as expected.

**Comment by gdrewb-valve** [comment]
So the repro is just to start the game and clicks don't work?

**Comment by p-groarke** [comment]
Yes exactly. I think it has to do with the first launch. Somehow the fullscreen is bugged until you change it. I will test with borderless window and windowed mode to see if the custom cursor is applied (no custom cursor, no clicks).

edit: It happens when fullscreen is in effect too (I am using the desktop friendly version).
Launch Dota, if the custom cursor isn't applied, many clicks aren't registered.
I guess the best fix is just to make sure the cursor is overridden, however you do that :)

**Comment by p-groarke** [comment]
Video demonstration. Double-clicks kind-of register: https://youtu.be/AO-1qcJYnq0

edit: Please use fullscreen, as the smaller youtube video player crops out 16:10 ty

**Comment by gramathy** [comment]
This is the issue I thought was fixed - He's right, it is kinda a first-launch thing (it happens after an update) though it didn't happen all the time.

**Comment by gdrewb-valve** [comment]
I'm not able to get it to happen but that may because it only happens after updates and I don't have the right state.  We'll try and find a repro.

**Comment by bklooster** [comment]
This happened again after today's update. Launching the game the first time after the update and the mouse moves fine, but the mouse does not register the mouse buttons. It seems to handle button states fine in terms of hovered, but the actual input seems to be getting confused.

**Comment by rained23** [comment]
This happen to me too, each launch will cause your mouse not working, I need to move and press randomly anywhere until the mouse icon turn to Reborn cursor. Most of the time I just keep pressing exit reborn button or go to the top right corner repeatedly until the desktop cursor turn into reborn (focus into reborn).

**Comment by ghost** [comment]
Thanks for the link - it was unfortunately happening every launch after a recent update. Completely uninstalling the client and redownloading it resolved it somehow, figured it was worth a shot and it worked.

**Comment by zhestkov** [comment]
This bug appears me after 01/09 patch.

**Comment by jeanlain** [comment]
I'm having this issue as well, as every launch. It's as if the game wasn't the front app, even though it takes the whole screen. At launch, the cursor isn't updated, clicks aren't registered and the music doesn't play. I have to cmd-tab out and back to bring the game to the front. I'm using-user friendly fullscreen.

**Comment by gdrewb-valve** [comment]
Is this still happening?  I saw something from the larger team that they had made a fix related to restoring a cursor grab after losing focus.

**Comment by p-groarke** [comment]
It has happened again yes, though I'm not sure when that was.

**Comment by gdrewb-valve** [comment]
The Oct. 16th update has another attempt at addressing this, after updating do you see the issue?

**Comment by gdrewb-valve** [comment]
Closing pending a response that this is still happening.
