### ISSUE TITLE
[OS X] Music fader doesn't work anymore.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#239]
May be related to custom music packs?

**Comment by gdrewb-valve** [comment]
Do you mean the music volume control in settings?

**Comment by p-groarke** [comment]
Well, I was going to record a screen share for this, and was able to reproduce #238 on video :)

So, here is this bug: https://youtu.be/_l-QzER9vGc

**Comment by bklooster** [comment]
I think it's just a problem with the Reborn music being put under Game Sounds. Windows users seem to be reporting the same problem on reddit. https://www.reddit.com/r/DotA2/comments/3e1bom/dota_2_reborn_music_is_counted_as_game_sound/

**Comment by gdrewb-valve** [comment]
Thanks for the video.  This is a core bug and not a Mac/Linux issue so I've passed it on to the larger team.
