### ISSUE TITLE
Game crashing when casting spells on enemy silencer

### ISSUE THREAD

**Issue by w8eight** [ValveSoftware/Dota-2#2399]
#### Your system information

Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: ROG STRIX X670E-I GAMING WIFI
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 7800X3D 8-Core Processor
CPU Family: 0x19
CPU Model: 0x61
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 5049 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.4-arch1-1
X Server Vendor: The X.Org Foundation
X Server Release: 12301002
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: AMD AMD Radeon RX 7900 XTX (gfx1100, LLVM 15.0.7, DRM 3.52, 6.4.4-arch1-1)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 174 Hz
VendorID: 0x1002
DeviceID: 0x164e
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 2
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3440 x 1440
Primary Display Size: 31.89" x 13.78" (34.72" diag), 81.0cm x 35.0cm (88.2cm diag)
Primary VRAM: 24576 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 63433 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 1901594 MB
Largest Free Hard Disk Block: 1713587 MB
Storage:
Number of SSDs: 1
SSD sizes: 2048G
Number of HDDs: 0
Number of removable drives: 0

#### Please describe your issue in as much detail as possible:
Game was randomly crashing after using a spell on enemy silencer. Rebooting didnt help, veryfing game files too.
[crash dump and steam runtime console output](https://gist.github.com/w8eight/6bbb6c3eb39de2f157d35e8a2f3d9206)

#### Steps for reproducing this issue:

1. Play the ranked game as enigma
2. Someone cast a targeted spell on enemy silencer
3. Game crashes

I saw 98% memory load in the output which seems odd:

```
System Memory:
Memory load: 98%
Total physical memory: 63433.39 MiB
Free physical memory: 1086.68 MiB
Total page file: 4096.00 MiB
Free page file: 4087.75 MiB
```

**Comment by w8eight** [comment]
I am able to reproduce this bug consistently on my machine in demo mode even. To add, while try to run processing vulkan shaders, my PC just crash at 30 or some %.

**Comment by w8eight** [comment]
Also whole system now crashes for me with any game download

**Comment by w8eight** [comment]
> 

What kernel version are you on currently?

**Comment by w8eight** [comment]
To remove stability issue with shader processing I had to tune down Curve Optimizer, but the issue with casting Malefiece on Silencer prevails

**Comment by danginsburg** [comment]
It looks like we have a Vulkan validation error that is crashing the RADV driver specifically when using Malefiece on Silencer..  Thanks for the report, I'll look into fixing this:

```
`VK ERROR : VALIDATION - Message Id Number: 695119215 | Message Id Name: VUID-RuntimeSpirv-maintenance4-06817
	Validation Error: [ VUID-RuntimeSpirv-maintenance4-06817 ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x296ead6f | vkCreateGraphicsPipelines(): pCreateInfos[0] starting at Location 4 Comonent 0 the Output (VK_SHADER_STAGE_VERTEX_BIT) has a Vec4 while Input (VK_SHADER_STAGE_FRAGMENT_BIT) as a Vec3 Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors The Vulkan spec states: If maintenance4 is not enabled, any OpTypeVector output interface variables must not have a higher Component Count than a matching OpTypeVector input interface variable (https://vulkan.lunarg.com/doc/view/1.3.246.1/windows/1.3-extensions/vkspec.html#VUID-RuntimeSpirv-maintenance4-06817)

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
VK ERROR : VALIDATION - Message Id Number: 695119215 | Message Id Name: VUID-RuntimeSpirv-maintenance4-06817
	Validation Error: [ VUID-RuntimeSpirv-maintenance4-06817 ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x296ead6f | vkCreateGraphicsPipelines(): pCreateInfos[0] starting at Location 4 Comonent 1 the Output (VK_SHADER_STAGE_VERTEX_BIT) has a Vec4 while Input (VK_SHADER_STAGE_FRAGMENT_BIT) as a Vec3 Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors The Vulkan spec states: If maintenance4 is not enabled, any OpTypeVector output interface variables must not have a higher Component Count than a matching OpTypeVector input interface variable (https://vulkan.lunarg.com/doc/view/1.3.246.1/windows/1.3-extensions/vkspec.html#VUID-RuntimeSpirv-maintenance4-06817)

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
VK ERROR : VALIDATION - Message Id Number: 695119215 | Message Id Name: VUID-RuntimeSpirv-maintenance4-06817
	Validation Error: [ VUID-RuntimeSpirv-maintenance4-06817 ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x296ead6f | vkCreateGraphicsPipelines(): pCreateInfos[0] starting at Location 4 Comonent 2 the Output (VK_SHADER_STAGE_VERTEX_BIT) has a Vec4 while Input (VK_SHADER_STAGE_FRAGMENT_BIT) as a Vec3 Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors The Vulkan spec states: If maintenance4 is not enabled, any OpTypeVector output interface variables must not have a higher Component Count than a matching OpTypeVector input interface variable (https://vulkan.lunarg.com/doc/view/1.3.246.1/windows/1.3-extensions/vkspec.html#VUID-RuntimeSpirv-maintenance4-06817)

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
VK ERROR : VALIDATION - Message Id Number: 602160055 | Message Id Name: UNASSIGNED-CoreValidation-Shader-InputNotProduced
	Validation Error: [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x23e43bb7 | vkCreateGraphicsPipelines(): pCreateInfos[0] VK_SHADER_STAGE_FRAGMENT_BIT declared input at Location 1 Comonent 2 but it is not an Output declared in VK_SHADER_STAGE_VERTEX_BIT

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
VK ERROR : VALIDATION - Message Id Number: 602160055 | Message Id Name: UNASSIGNED-CoreValidation-Shader-InputNotProduced
	Validation Error: [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x23e43bb7 | vkCreateGraphicsPipelines(): pCreateInfos[0] VK_SHADER_STAGE_FRAGMENT_BIT declared input at Location 5 Comonent 3 but it is not an Output declared in VK_SHADER_STAGE_VERTEX_BIT

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
VK ERROR : VALIDATION - Message Id Number: 602160055 | Message Id Name: UNASSIGNED-CoreValidation-Shader-InputNotProduced
	Validation Error: [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object 0: handle = 0xc087b00000241ab, name = hero.vfx_vs, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xec32b900003599f7, name = hero.vfx_ps, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x23e43bb7 | vkCreateGraphicsPipelines(): pCreateInfos[0] VK_SHADER_STAGE_FRAGMENT_BIT declared input at Location 2 Comonent 3 but it is not an Output declared in VK_SHADER_STAGE_VERTEX_BIT

	Objects - 2
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 0C087B00000241AB, Name "hero.vfx_vs"
		Object[1] - VK_OBJECT_TYPE_SHADER_MODULE, Handle EC32B900003599F7, Name "hero.vfx_ps"
```

**Comment by w8eight** [comment]
> 
I also saw some stutter with casting it on other heroes, but no crashes.
Other targetable spell that were crashing the game for me was LC's duel, so it might not be bug linked to one ability. 
Any temporary ways to fix it, besides not playing dota until fixed?

**Comment by danginsburg** [comment]
> Any temporary ways to fix it, besides not playing dota until fixed?

I'm not aware of a way to workaround it unfortuantely.  But I have fixed it here locally and we're working on getting it shipped into an update.

**Comment by w8eight** [comment]
> > Any temporary ways to fix it, besides not playing dota until fixed?
> 
> I'm not aware of a way to workaround it unfortuantely. But I have fixed it here locally and we're working on getting it shipped into an update.

Swift as the wolves of Icewrack.
Thanks for actioning it so fast

**Comment by danginsburg** [comment]
The update yesterday contained the fix.  Can you confirm it's no longer crashing for you?

**Comment by w8eight** [comment]
> The update yesterday contained the fix. Can you confirm it's no longer crashing for you?

It works! I have some small spikes when casting it first time, but no crashes

**Comment by danginsburg** [comment]
Thanks!
