### ISSUE TITLE
[MAC] -enable_addons not working not working properly ?

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#240]
Nothing in resources > flash3 is working for me on reborn. I have custom item icons, custom HUD, custom Cursors. I've copied everything to the same folders from the old client to the new one, they're supposed to replace the default item icons,cursor,hud but they aren't working. I have -enable_addons set to my launch options, but there is no way to set it individually for reborn to my knowledge since both clients are launched from the same place, so I figured this should be enough. Are there new locations for the files to be placed at, is it not working properly or ?

**Comment by gdrewb-valve** [comment]
I'll ask the larger team.

**Comment by gdrewb-valve** [comment]
This apparently isn't implemented yet but will done at some point by the larger team.  It won't get tracked here.

**Comment by Vuccappella** [comment]
Thanks for the response.
