### ISSUE TITLE
Generated Vulkan Shader Cache automatically get cleared on game launch

### ISSUE THREAD

**Issue by ShashiSrinath** [ValveSoftware/Dota-2#2403]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`):  [gist](https://gist.github.com/ShashiSrinath/4470f6c619e25e97b2d9883c616cf990) 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

While the client generating vulkan shader cache, i can see the size of cache folder getting increased and new files getting added ( in this folder: SteamLibrary/steamapps/shadercache/570/nvidiav1)

around 99% completion, the folder size will reach about 3.7GB.

But everything get cleared on 100%, this folder size coming back to 4KB.

ingame im experiencing fps drops from 100 to 10 in regular intervals. 

so i'm guessing something is going wrong with the shaders.

(tried to re create this multiple times but still facing the same issue)
the folder data also get cleared if i choose to skip shader generation 

#### Steps for reproducing this issue:

1. Clear the current shader data using shader precaching toggle
2. Launch the game and wait for the shader compilation
3. Notice the cache folder "SteamLibrary/steamapps/shadercache/570/nvidiav1" size getting increased while the shader compilation is happening
4: on game launch, everything inside shader cache folder getting cleared "SteamLibrary/steamapps/shadercache/570/nvidiav1"

**Comment by kisak-valve** [comment]
Hello @ShashiSrinath, the NVIDA 535.54.03 driver is known to have a broken shader cache. Please retest with NVIDIA 535.86.05 (or newer) when it becomes available via your distro's normal update process.

**Comment by ShashiSrinath** [comment]
Hi @kisak-valve 
I can confirm that this issue is no longer there on 535.86.05 driver
