### ISSUE TITLE
Game is not launching.

### ISSUE THREAD

**Issue by oleksii-hradinar** [ValveSoftware/Dota-2#2404]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/kmasl0v/ab9bedd3f91ad4c5c85bd72969aafa47
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes, also reinstalled 

When launching from steam, launching button switches back to 'play' after 5 seconds. When launching from game library I get 'Unable to load module panorama_text_pango' error popup. 
I had this problem 2 weeks ago, it resolved by switching to Steam Linux Runtime, today it appeared again. 

Steam Runtime System Information: https://gist.github.com/kmasl0v/61d5c045b207215119dd6daa5c6a877f

This is output of running from terminal.
[log.txt](https://github.com/ValveSoftware/Dota-2/files/12182956/log.txt)

**Comment by smcv** [comment]
There are two main things that could be going wrong here:

1. Dota 2 being launched in the wrong environment (not using the Steam Linux Runtime 3 'sniper' container runtime)
2. Dota 2 being launched in the correct Steam Linux Runtime 3 'sniper' environment, but it doesn't work

Based on your Steam Runtime System Information, the container runtime seems to work correctly on your system, so (1.) seems like a more likely cause. We should make sure that's correct first, and if it is, then we can get into diagnosing (2.).

**Comment by smcv** [comment]
## Ensuring Dota 2 is launched in the sniper runtime

If you run Steam from a terminal or with its output going to a log or the Journal, you should see a command something like this when you try to launch Dota 2:

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun --
.../dota 2 beta/game/dota.sh +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama
\0
```

(It will be logged as one very long line, and `...` will be replaced by paths to your Steam installation and Steam library - I've broken it into shorter lines and abbreviated the paths here to make it more readable.)

If you do not see a command something like that, then that's the first thing you'll need to solve to get Dota 2 to launch correctly.

If the command looks more like this:

<details><summary>a wrong command (no container runtime)</summary>

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../dota 2 beta/game/dota.sh ...\0
```

</details>

or this:

<details><summary>another wrong command (scout-on-soldier container runtime)</summary>

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun --
.../SteamLinuxRuntime/scout-on-soldier-entry-point-v2 --
.../dota 2 beta/game/dota.sh +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama
\0
```

</details>

then that is not expected to work.

> I had this problem 2 weeks ago, it resolved by switching to Steam Linux Runtime

If you mean Properties -> Compatibility -> Force the use of -> Steam Linux Runtime, please turn off (uncheck) "Force the use of a specific compatibility tool". The fact that it is possible is [a Steam bug](https://github.com/ValveSoftware/steam-for-linux/issues/9844): that option shouldn't be available for games that require the newer Steam Linux Runtime 3 'sniper', which now includes Dota 2.

Other Steam client issues that can cause similar problems include ValveSoftware/steam-for-linux#9852 (workaround: ensure the "Enable Steam Play for supported titles" option is enabled, which is the default) or ValveSoftware/steam-for-linux#9835 (workaround: completely exit from Steam, then start it again).

**Comment by oleksii-hradinar** [comment]
Although it worked before! It didn't start now because it was in /usr ("binding directories that are located in under /usr is not supported"), after i moved game into other directory, it runs perfect now.

[steam_log.txt](https://github.com/ValveSoftware/Dota-2/files/12185019/steam_log.txt)
