### ISSUE TITLE
ALT clicking on buyback, hp/mana, items in shop, etc, does not work

### ISSUE THREAD

**Issue by reportados123** [ValveSoftware/Dota-2#241]
Hi, I'm on Arch Linux, with the window manager BSPWM, and when I try to alt click on several different spots that should work on Windows, it does not work.

Alt clicking your spells work (either it being ready or on cooldown), but alt clicking items in the shop indicating how much gold you are away from a certain item or that you will purchase it, does not work. Also, alt clicking your gold to show your current buyback status or your hp/mana, doesn't work either.

This also happens on the main Dota 2 client, not just for Dota 2 Reborn.

**Comment by Cheogh** [comment]
I was having an alt click problem on another game using kde, I found that one of the settings in the window manager(?) needed to be disabled or switched to another key. I remember having a similar problem in ubuntu pre or post unity.

**Comment by reportados123** [comment]
I see, the thing is though, with my window manager, I do not have any keybinds that should mess with the game at all. BSPWM is a minimalistic tiling window manager and should not get in the way of the user. SXHKD, a program created by the author of bspwm, is responsible for these said keybindings. However, all of my keybinds require the use of the windows modifier key.

I forgot to mention that almost every ALT clicking spot does work. For example, alt clicking the heroes at the top of the screen does indicate that they are missing. Alt clicking your spells does indicate that they are ready. Alt clicking your items in your inventory does indicate that they are ready. Alt clicking an enemy's item in their inventory does indicates that they have that certain item.

The ones I'm aware of that DOES NOT work are alt clicking your gold to show your buyback status, alt clicking in the shop, and your HP/Mana bar.

If there are any other alt clicking feature spots that I'm not aware of, please tell me.

**Comment by gdrewb-valve** [comment]
As this isn't specific to Reborn we might have to try and duplicate your config to repro, which will take a while.

**Comment by ghost** [comment]
I had the same problem with alt+right click(button3) on Ubuntu 15.04. I changed < Alt >Button3 to another keybind in the "general options" of "compizConfig settings manager" and now it works.

**Comment by davidw-valve** [comment]
I cannot readily reproduce this. When it occurs does alt-clicking make you grab the window or otherwise perform some action on it?

**Comment by reportados123** [comment]
No other action is performed on the areas that do not work. Alt clicking does not make me grab the window. Also, I've found that alt-clicking the buffs/debuffs on your hero does not work.

I'm playing in fullscreen mode. I've tried changing the resolutions, the window type from fullscreen to window and borderless window, however, the problem still persists. I thought it might have to do something with where I was clicking, but that did not seem to be the case.

**Comment by tiburcillo** [comment]
Have you tried if CTRL+ALT clicking works. I noticed the same ALT-issue on the regular client on Linux Mint Cinnamon, while CTRL+ALT was still working. If so we might be talking about the same problem.

**Comment by reportados123** [comment]
CTRL + ALT clicking does not do anything. However, I've found the reason why it has not been working correctly for the above issues. I've been using the ALT key on the right side of the keyboard, if I were to use the ALT key on the left side of the keyboard, everything works fine.

As a result, alt clicking your buyback status, items in shop, hp/mana bar, and buffs/debuffs on your hero with the RIGHT alt click does not work. Using the left ALT key with any alt-clickable spot works fine.

The reason for me not using the left ALT key is because I switched all of my keybindings to the right side of the keyboard instead of the classic QWER.

Also, the problem of the right alt key persists in both clients, main client and reborn client.

**Comment by wuschLOR** [comment]
Dota normal works for me without any problems - but reborn is buggy.
Somtimes alt+click works and sometimes it doesn't. When it doeesn't it tryes goes to moving window mode (running 14.04 lts with KDE and AMD gpu). 
To fix this i used the method provided here https://github.com/ValveSoftware/Dota-2-Reborn/issues/13#issuecomment-131616211 : 
0. go to the video options 
1. check use advanced settings
2. save the default options
then alt+click works without a problem 
![fix](https://i.imgur.com/SR7ft80.jpg)

**Comment by reportados123** [comment]
Have you tried using the right ALT key on your keyboard? That one is the one that doesn't work for me as stated above. Everything works fine on my end if I use the left ALT key. The problem only happens when I press the alt key on the right side of the keyboard.

**Comment by gdrewb-valve** [comment]
Does anybody have a consistent repro for this?  Can anybody else confirm the left Alt vs. right Alt behavior that reportados123 mentions?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
