### ISSUE TITLE
on my iMAC can`t start play Dota2. error: "Failed to initialize Vulkan.

### ISSUE THREAD

**Issue by geoblizzard** [ValveSoftware/Dota-2#2410]
When i start to play Dota2 there is error: "Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan.

To disable Vulkan, remove -vulkan from your launch options.
If you chose Vulkan in the video settings, please add -safe_mode to your launch options to allow the game to start with the default rendersystem."

2. I have macOS High Sierra version 10.13.6
Computer Information:
Manufacturer: Apple
Model: iMac12,2
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
CPU Family: 0x6
CPU Model: 0x2a
CPU Stepping: 0x7
CPU Type: 0x0
Speed: 3400 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
MacOS 10.13.6 (64 bit)
Video Card:
Driver: AMD Radeon HD 6970M
Driver Version Not Detected
OpenGL Version: 4.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID: 0x1002
DeviceID: 0x6720
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.46" x 13.19" (26.89" diag), 59.6cm x 33.5cm (68.3cm diag)
Primary VRAM: 1024 MB
Memory:
RAM: 24576 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: DVD
Total Hard Disk Space Available: 1453636 MB
Largest Free Hard Disk Block: 952416 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0
  
3. 
![Screen Shot 2023-08-13 at 4 08 50 PM](https://github.com/ValveSoftware/Dota-2/assets/142185292/eed9e2ba-e841-4998-82bb-0fe627e13f18)

in Launch option i try everything

Please Help.
If need more info tell me

**Comment by kisak-valve** [comment]
Hello @geoblizzard, my understanding is that Dota 2 for Mac uses MoltenVK to translate Vulkan to Metal. This requires that the hardware support Metal. The oldest generation of Intel hardware to support Metal should be Ivybridge, and your i7-2600 is part of the Sandybridge generation, which is one generation older than Ivybridge making it unsupported. Separately, pondering the AMD Radeon HD 6970M, this is Terascale 2 generation GPU. All Terascale generation GPUs do not support Metal (or Vulkan).

Unfortunately, that means that Dota 2 is accurately telling you that your hardware lacks the support needed to run Dota 2 and there's no easy fix or workaround.

**Comment by geoblizzard** [comment]
Thank u @kisak-valve for reply, but what can i do now to fix this prob

**Comment by kisak-valve** [comment]
As I noted, unfortunately the problem you're seeing is a lack of hardware features needed to use the Metal graphics API and this can't be solved with your current system.

**Comment by geoblizzard** [comment]
@kisak-valve 

could you tell me please, if I instal Windows 10 and its drivers on my iMac, is it possible to solve this problem?
