### ISSUE TITLE
10nth anniversary update freezes game

### ISSUE THREAD

**Issue by voronind** [ValveSoftware/Dota-2#2415]
#### System information
https://gist.github.com/voronind/8806f42e1840eda1c93d07ae09c0aec0

#### Steps for reproducing this issue:
After 10nth anniversary update game freezes. I suspect that problem in video.
1. Run game.
2. Game loaded. I see all ui elements except of promo screen.
3. After few seconds game freezes and there is no response on my actions.
4. Close using Steam available only.
5. I suspect promo screen. I add to args "+map_enable_background_maps 0"
6. Game loaded.
7. These is no freezes. I see no promo screen and can not see new models.
8.  I starts match.
9. After drafting and map loading game freezes.

I repeat it several times.

**Comment by kisak-valve** [comment]
Hello @voronind, based on https://github.com/ValveSoftware/Dota-2/issues/2414#issuecomment-1683634724, it might be interesting to test how the game behaves with the NVIDIA 535 series video driver.

**Comment by voronind** [comment]
> Hello @voronind, based on [#2414 (comment)](https://github.com/ValveSoftware/Dota-2/issues/2414#issuecomment-1683634724), it might be interesting to test how the game behaves with the NVIDIA 535 series video driver.

I update NVIDIA drivers from 525 to 535 and problem is gone. There is another problem. I need to win 5 single draft mathes with low priority.
