### ISSUE TITLE
BlackJAck stick

### ISSUE THREAD

**Issue by ArtemkaBL** [ValveSoftware/Dota-2#2417]
![image](https://github.com/ValveSoftware/Dota-2/assets/56271413/cfd2cec6-6f9c-45c1-8e40-42b56c5d309b)

**Comment by kisak-valve** [comment]
Hello @ArtemkaBL, this issue tracker is limited to issues with the Mac and Linux port of Dota 2. Your previous issue report at #2416 didn't read like it was OS-specific feedback, so it was transferred to the Dota2-Gameplay issue tracker at https://github.com/ValveSoftware/Dota2-Gameplay/issues/10800.

Closing as a duplicate.
