### ISSUE TITLE
[Ubuntu] Dota 2 Launch fail

### ISSUE THREAD

**Issue by Mikhail038** [ValveSoftware/Dota-2#2418]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Mikhail038/e4bff8416aca1026a8fea3ef95f699d1): 
* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I tried to open Dota2 as usual. I clicked button PLAY, so it turns to CANCEL. But after few seconds button CANCEL turns back to PLAY (launch silently crashes). 
The steamapps/common/SteamLinuxRuntime_sniper/var/slr-latest.log  is in a [gist](https://gist.github.com/Mikhail038/399ea4d5a2f2115cf984caefe7e8d115)

#### Steps for reproducing this issue:

1. Open Steam
2. Try to launch Dota2
3. No success

**Comment by kisak-valve** [comment]
Hello @Mikhail038, these look like some lines of interest from your log:
```
Console History (reversed)

46(0.425554):  Engine2PreBreakpadDumpFunction: Building comment.
45(0.425545):  Engine2PreBreakpadDumpFunction
44(0.388311):  memstd.cpp (966) : Assertion Failed in function NoteAlloc():
false
WARNING: Large alloc of 300126135 bytes of memory (limit 209715200)
```

This has some similarity to #2098 and it might be worth pondering the notes left on the older issue report.

**Comment by Mikhail038** [comment]
https://github.com/ValveSoftware/Dota-2/issues/2098 same problem solved
