### ISSUE TITLE
recently I after a while my fps goes from 60 to 9-15fps and back.

### ISSUE THREAD

**Issue by rezad1393** [ValveSoftware/Dota-2#2421]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/rezad1393/e36661a3782aa0f573931f9da367f8e4
* Have you checked for system updates?: [Yes/No]
yes
* Are you using the latest stable video driver available for your system? [Yes/No]
* yes
* Have you verified the game files?: [Yes/No]
yes

#### Please describe your issue in as much detail as possible:
recently (maybe from last month?) when I play dota after a while my framerate drops suddenly from 60 to 10 and stays there for  while then sometime later goes back to 60 and then after while does that again.
is affects my system outside of dota too, like when I use mpv player to play a audio file it seems to get stuck and then resume when that framerate drops in dota. it is not audio player that cuases it, I can only have dota open and have the bug (frame drop) and then when I open an audio file in mpv it gets stuck too. my desktop seems slower too when that happens.
.
as if some cache somewhere gets filled and then emptied. 

I think this is a hardware/software issue that dota creates but affects my whole system.

I accidentally noticed that when that bug happens if I change power profile of my system (poewer save/balanced/performance)  and go back to dota, the frame rate goes back to 60 for about 5-7 seconds then drops again.

I don't see anything is system journal for any errors.
but I forgot to check dmesg.

#### Steps for reproducing this issue:

1. play dota
2. after a while frame drops and stay there.

**Comment by kisak-valve** [comment]
Hello @rezad1393, the behavior you've described is consistent with thermal throttling. I would keep an eye on temperatures and CPU speeds while this happens.

An older note on the same topic: https://github.com/ValveSoftware/csgo-osx-linux/issues/141#issuecomment-1016483190.

**Comment by rezad1393** [comment]
> Hello @rezad1393, the behavior you've described is consistent with thermal throttling. I would keep an eye on temperatures and CPU speeds while this happens.
> 
> An older note on the same topic: [ValveSoftware/csgo-osx-linux#141 (comment)](https://github.com/ValveSoftware/csgo-osx-linux/issues/141#issuecomment-1016483190).

I have checked and you are right.

but why now?
I never had this before.
is this a bug?
should I report it anyhwhere? maybe new kernel/mesa driver caused this?
I hear the fan running, could it be my laptop fan has dirt in it and doesnt work right?
running dota alone should overheat my laptop that much?

![2023-08-21_18-51](https://github.com/ValveSoftware/Dota-2/assets/7523164/49fb0a40-8d4a-49d6-9fd5-ae3d6d10d171)

**Comment by rezad1393** [comment]
the weird thing is that this is new.

when I try a stress test with "stress-ng --cpu 16" I get 100% cpu on 100 cores but my cpu temps is under 80 because I have set my power profile to "power save".

if I move it to performance then yes, my cpu temp goes upto 100.

it seems amd driver or dota changed something that makes it so that dota doesn't work with power profiles.
I see it on both normal and lts kernel linux-lts 6.1.47 linux 6.4.12.arch1

**Comment by rezad1393** [comment]
it seems to have been linux related that happened with both lts and normal kernels so maybe kde/wayland was at fault.


after some more tests with benchmarks the issue was present in other heavy tasks. 
it seems that tasks didn't follow my power profile and would boil the APU. 

it seems to be fixed now.
