### ISSUE TITLE
Restoring connection, losing connection to steam

### ISSUE THREAD

**Issue by KZM00** [ValveSoftware/Dota-2#2422]
Iam not gonna bother writing new ticket, I did one couple of months ago and got transferred and ignored, at this point its just easier to uninstall the game to save my self the headache since I've been contacting support for over a year and they just don't care enough. 
Here is  the link to the old ticket,

https://github.com/ValveSoftware/Dota2-Gameplay/issues/9079

**Comment by kisak-valve** [comment]
Hello @KZM00, please do not intentionally open duplicate issue reports.

Looking at your previous issue report, I transferred your issue report because this issue tracker is limited to issues with the Mac and Linux client of Dota 2 and you're using Windows.
