### ISSUE TITLE
How can I start reborn from a shortcut or CLI?

### ISSUE THREAD

**Issue by letharion** [ValveSoftware/Dota-2#243]
I can't seem to figure out how to start reborn without going through the steam ui. Launching regular dota is easy, but how do I launch reborn?

**Comment by gdrewb-valve** [comment]
It's simpler and safer to launch from Steam, but if you want to the executable for Reborn is in the app directories under game/bin/arch.  arch would be linuxsteamrt64 for Linux, osx64 for OSX, etc.  There's also a dota.sh just up from the arch directories that will set library paths and such for you.

Note that the main client has its own dota.sh and binaries so you'll have multiple around if you're poking around looking at things.

**Comment by gdrewb-valve** [comment]
I'm going to assume this is answered, closing.

**Comment by letharion** [comment]
@gdrewb-valve Yes, thank you, that works. I was simply confused because nothing is obviously named "reborn" or similar, so I didn't find the file to run.
One follow up though, why/how is it "safer" to launch from Steam?

**Comment by gdrewb-valve** [comment]
If you launch from Steam you can be sure that the environment is set up properly.  For example the Steam client makes sure that the Steam runtime paths are set up for execution on Linux.  You don't necessarily need what Steam does but if you run from Steam you don't need to think about it.
