### ISSUE TITLE
Full screen mode not working

### ISSUE THREAD

**Issue by tofutych** [ValveSoftware/Dota-2#2432]
After "The Summer Client Update" the full screen mode stopped working correctly (linux).
<img title="image" alt="Alt text" src="https://i.ibb.co/ZT1tvvy/Screenshot-from-2023-08-31-01-08-41.png">

**Comment by alou-S** [comment]
The fact that you are managing to getting Linux client to start is surprising. Its not starting for me.

Post fixing the missing libpangoft2-1.0.so issue it just gets stuck on black screen after opening the game.

**Comment by bierpreis** [comment]
Have the same issue here, its annoying. Hope volvo will fix. :D

**Comment by bierpreis** [comment]
Found a simple fix for me: Go to options / graphics / select "use advanced mode" - the problem then dissapieread. Strange - i changed no option there.

**Comment by JetRunner** [comment]
Same for macOS. See here: https://github.com/ValveSoftware/Dota2-Gameplay/issues/11241

@danginsburg Please help!

**Comment by JetRunner** [comment]
I can confirm it hasn't been fixed with the latest update. Honestly it should be a one-line fix.. For me, this is making exclusive full-screen mode not playable as I lose the cursor everytime I move the cursor to the top (menu bar). 
@kisak-valve @danginsburg

**Comment by JetRunner** [comment]
@tofutych Why are u closing this issue? Is it fixed for you?
