### ISSUE TITLE
Full screen mode rapidly switches between monitors

### ISSUE THREAD

**Issue by SamanthaClarke1** [ValveSoftware/Dota-2#2435]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/SamanthaClarke1/8d2c5230ee0aed659e7b59984ffb7816
* Have you checked for system updates?: YES
* Are you using the latest stable video driver available for your system? YES
* Have you verified the game files?: YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
After the summer client update, dota2 full screen no longer works with multiple monitors.
If I open dota 2 with multiple monitors, it rapidly opens in both of them, back and forth, at once.
I'm using two monitors, a 25'' samsung and a 27'' samsung.

#### Steps for reproducing this issue:

1. Have two monitors on linux.
2. Open dota 2.
3. Watch as it rapidly ping-pongs between the two monitors.

Only solution I've found so far is to not have multiple monitors.

**Comment by kisak-valve** [comment]
Screen flickering when starting Dota 2 on Linux

Issue transferred from https://github.com/ValveSoftware/Dota-2/issues/2436.
@rmbleeker posted on 2023-08-31T00:40:11:

#### Your system information

* System information from steam: https://gist.github.com/rmbleeker/182cf5b30f91d24a5fac9f47fd699f97
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Starting Dota 2 results in both my screens flickering, along with the Pop!_OS taskbar, Steam client and mouse cursor which are displayed back and forth between the 2 screens in a flickering pattern. This continues throughout the loading screen until the Dota 2 main menu is reached. Sometimes it happens again when I switch to another virtual desktop or use the expose mode (SUPER + D). 

Once it's all done the game works normally though, no graphical issues during gameplay.

#### Steps for reproducing this issue:

1. Update Dota 2 with the Summer Client Update
2. Start Dota 2
3. Have a seizure 
4. Play Dota 2
***
@rmbleeker commented on 2023-08-31T00:42:16:

Looks like the same issue as #2435, they should probably be merged.

**Comment by rmbleeker** [comment]
I can confirm that Dota 2 behaves normally when I unplug one of my monitors. They are identical 25 inch 1440p ASUS monitors.

Seizure mode is back once I plug my secondary monitor back in. I've also noticed that starting up the Dota client takes considerably longer with 2 screens connected than with a single screen.

**Comment by SamanthaClarke1** [comment]
Found a weird workaround of sorts.
Open dota2 with one monitor.
Switch to borderless windowed / fullscreen.
Replug in the other monitor.
WHATEVER YOU DO, do not alt tab or ANYTHING or the seizures will begin again.
Otherwise, it'll behave for a bit :)

**Comment by kshammer** [comment]
+1 
Operating System: Pop OS 
Graphics Card: GeForce RTX 3070 Ti 
Graphics Driver Version: 535.104.05 
Monitors: LG 2k 144hz 

Reproduce: 
Open dota 2 
Alt-tab
Dota2 flickers back and forth across the two monitors.

**Comment by danginsburg** [comment]
I tried to reproduce this on Ubuntu 22.04.2 LTS using NVIDIA GTX 1070 535.104.05 and have not been able to get it to happen (also using two monitors).  I also tried it with an AMD Vega GPU and RADV on the same machine and no luck.  I'm not sure yet what is needed to reproduce the issue.  So far all reporters have been on NVIDIA.

**Comment by axelf08** [comment]
Edit: This issue has been fixed for me after the latest update

Same issue
Operating System: Linux Mint 21.2
Graphics Card: GeForce GTX 1070
Graphics Driver Version: 535.86.05
Monitors: MSI 1080p 144hz connected with DisplayPort, Philips 1080p 60hz connected with HDMI, Dell 1280x1024 5:4 75hz monitor.

Reproduce:
Open Dota 2
Watch client jumps between two monitors

What I have noticed is that it jumps between two screens, so if I have all 3 connected it will jump between the 1080p monitors. When multiple monitors are detected it will not move past the splash screen for me. It did work if I disconnected other monitors, but would continue if one of the monitors were reconnected. 

I tried downgrading to Graphics Card Drivers to 525.125.06 with no change is results.
I tried disabling Vulkan shader pre caching and it did not solve the issue

**Comment by danginsburg** [comment]
Ah, I was able to reproduce this - It seems I had to have both monitors at the same resolution to get it to happen.  So it seems the bug is if you have it set to Desktop-Friendly Fullscreen and both monitors are the same resolution it will jump around.  For now, you can workaround it by setting something like `-sw -w 1920 -h 1080` in your Launch Options, then in the Video Settings you can set it to "Borderless Windowed" at the resolution you want and that seems to work OK.  I'll work on fixing this though.

**Comment by danginsburg** [comment]
I've checked in a fix for this, it will ship in the next Dota 2 Client update.

**Comment by Valeronlol** [comment]
Same issue.
Fixed for me with `-bw -w 3840 -h 2160` Launch Options in Steam -> Dota2 -> Properties -> General

**Comment by johndrinkwater** [comment]
Not the initial reporter, but I also had this behaviour and the patch that landed a few hours ago appears to fix it, for me.

**Comment by rmbleeker** [comment]
> I've checked in a fix for this, it will ship in the next Dota 2 Client update.

Also here to report that it appears fixed. Thanks

**Comment by johndrinkwater** [comment]
This has now reappeared with the latest client update.

**Comment by rmbleeker** [comment]
Can confirm, I'm also seeing this happen again with the latest update (The International 2023 Celebration Update). I've verified my local game files to be sure it wasn't something else.

**Comment by kisak-valve** [comment]
Hello @johndrinkwater, @rmbleeker, please use #2482 for feedback on this topic as it is the natural continuation of this issue.

**Comment by gankbanger** [comment]
I get the same issue ONLY when not running Dota 2 on the primary display.

Fix:
Open Dota 2 properties on Steam, under the General tab, on the Launch Options, add:

`-sdl_displayindex 1` 

Display indexes are 0-based; the `1` above is the 2nd display.
