### ISSUE TITLE
Screen flickering when starting Dota 2 on Linux

### ISSUE THREAD

**Issue by rmbleeker** [ValveSoftware/Dota-2#2436]
#### Your system information

* System information from steam: https://gist.github.com/rmbleeker/182cf5b30f91d24a5fac9f47fd699f97
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Starting Dota 2 results in both my screens flickering, along with the Pop!_OS taskbar, Steam client and mouse cursor which are displayed back and forth between the 2 screens in a flickering pattern. This continues throughout the loading screen until the Dota 2 main menu is reached. Sometimes it happens again when I switch to another virtual desktop or use the expose mode (SUPER + D). 

Once it's all done the game works normally though, no graphical issues during gameplay.

#### Steps for reproducing this issue:

1. Update Dota 2 with the Summer Client Update
2. Start Dota 2
3. Have a seizure 
4. Play Dota 2

**Comment by rmbleeker** [comment]
Looks like the same issue as #2435, they should probably be merged.

**Comment by kisak-valve** [comment]
Hello @rmbleeker, indeed, I've transferred this issue report to https://github.com/ValveSoftware/Dota-2/issues/2435#issuecomment-1700105094.
