### ISSUE TITLE
DOTA 2 Mac OS not Opening

### ISSUE THREAD

**Issue by dotagoat** [ValveSoftware/Dota-2#2437]
#### Your system information

Computer Information:
Manufacturer: Apple
Model: MacBookPro11,4
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
CPU Family: 0x6
CPU Model: 0x46
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 2200 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
MacOS 10.13.6 (64 bit)
Video Card:
Driver: Intel Iris Pro
Driver Version Not Detected
OpenGL Version: 4.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x8086
DeviceID: 0xd26
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 19.96" x 11.22" (22.87" diag), 50.7cm x 28.5cm (58.1cm diag)
Primary VRAM: 1536 MB
Memory:
RAM: 16384 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: DVD
Total Hard Disk Space Available: 239172 MB
Largest Free Hard Disk Block: 25693 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Own a Mac OS
2. Open Steam
3. Open Dota
4. Attempts to open but no screen appears. You see the widget pop up to attempt to open the program but then disappears.

**Comment by ronaldborla** [comment]
Same here

**Comment by dotagoat** [comment]
every time new update for the last 3 years, without fail, mac users can not play the game for few days - half week. really annoying honestly

**Comment by Loloner** [comment]
every time after update we have this problems and valve dont give a f 
wierd
mine is keep crashing and i have map issue

**Comment by danginsburg** [comment]
Closing in favor of duplicate #2438 which has more information.
