### ISSUE TITLE
MoltenVK crash bug on macOS 10.14 Mojave after the last update

### ISSUE THREAD

**Issue by Romanzavodskii** [ValveSoftware/Dota-2#2438]
#### Your system information
Mac Pro 6.1
12 core Xeon
64 Gb RAM
D300 dual GPUs
macOS 10.14 Mojave

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Got this error message after the last update:

Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libtier0.dylib, got 0x7fd0928047d0
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libfilesystem_stdio.dylib, got 0x7fd0641109d0
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libinputsystem.dylib, got 0x7fd061f14930
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/liblocalize.dylib, got 0x7fd09281c150
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/librendersystemvulkan.dylib, got 0x7fd0928168f0
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libresourcesystem.dylib, got 0x7fd09282c050
Loaded /Users/CatPro/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libschemasystem.dylib, got 0x7fd09282c7d0
[mvk-info] MoltenVK version 1.2.5, supporting Vulkan version 1.2.261.
	The following 86 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_deferred_host_operations v4
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_incremental_present v2
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_map_memory2 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_non_semantic_info v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_pipeline_creation_feedback v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_subgroup_ballot v1
		VK_EXT_shader_subgroup_vote v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: AMD Radeon HD - FirePro D300
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x6810
		pipelineCacheUUID: FD418AA7-0000-2715-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
		macOS Read-Write Texture Tier 2
[mvk-info] GPU device:
		model: AMD Radeon HD - FirePro D300
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x6810
		pipelineCacheUUID: FD418AA7-0000-2715-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
		macOS Read-Write Texture Tier 2
[mvk-warn] Extension VK_MVK_moltenvk is deprecated. For access to Metal objects, use extension VK_EXT_metal_objects. For MoltenVK configuration, use the global vkGetMoltenVKConfigurationMVK() and vkSetMoltenVKConfigurationMVK() functions.
[mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 4 Vulkan extensions enabled:
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_surface v25
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
2023-08-31 14:20:09.344 dota2[34750:13062847] -[BronzeMtlDevice sampleTimestamps:gpuTimestamp:]: unrecognized selector sent to instance 0x7fd098010000
2023-08-31 14:20:09.344 dota2[34750:13062847] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[BronzeMtlDevice sampleTimestamps:gpuTimestamp:]: unrecognized selector sent to instance 0x7fd098010000'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4752a191 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff710483c6 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff475a4a16 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff474cbc68 ___forwarding___ + 1478
	4   CoreFoundation                      0x00007fff474cb618 _CF_forwarding_prep_0 + 120
	5   libMoltenVK.dylib                   0x000000008b0e7b4e mvkMTLResourceOptions + 71486
	6   libMoltenVK.dylib                   0x000000008b0835c4 vkGetPhysicalDeviceProperties + 52
	7   librendersystemvulkan.dylib         0x000000008a878539 BinaryProperties_GetValue + 626409
	8   libengine2.dylib                    0x0000000080addd17 pcre_free_study + 27207
	9   libengine2.dylib                    0x0000000080adea01 pcre_free_study + 30513
	10  libengine2.dylib                    0x00000000808eaf1b Source2Main + 872427
	11  libengine2.dylib                    0x00000000808eacdf Source2Main + 871855
	12  libengine2.dylib                    0x0000000080813c68 BinaryProperties_GetValue + 383624
	13  libengine2.dylib                    0x000000008081605e Source2Main + 302
	14  dota2                               0x00000000082a3d10 dota2 + 15632
	15  dota2                               0x00000000082a3c79 dota2 + 15481
	16  libdyld.dylib                       0x00007fff7280f3d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

#### Steps for reproducing this issue:

1. Use macOS 10.14 Mojave
2. Open Dota 2

**Comment by Romanzavodskii** [comment]
[crash_20230831143639_1.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/12483727/crash_20230831143639_1.dmp.zip)

**Comment by danginsburg** [comment]
This looks like a regression in MoltenVK, I will work on getting a fix today.

**Comment by danginsburg** [comment]
I have a fix for this, it should be fixed in the next client update.  If you want to try it before the update ships, you can try unzipping this copy of libMoltenVK.dylib over the top of the one in `~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64`

[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/12486613/libMoltenVK.dylib.zip)

**Comment by danginsburg** [comment]
This should be fixed now.

**Comment by Romanzavodskii** [comment]
> This should be fixed now.

Tested, game is now working! 

Thank You, sir!
