### ISSUE TITLE
[Linux]No fonts in Reborn

### ISSUE THREAD

**Issue by DeepDlueIV** [ValveSoftware/Dota-2#244]
I see white squares on every word in the game. But main menu UI is fine.
Regular D2 is ok everything.
And sometimes i can see different glitches in the game (reborn)
Most i need is working fonts. How i can do it?

Ubuntu 14.04 x64 
intel gma graphics

**Comment by SuperFlick** [comment]
I had same problem and fixed this with upgrading mesa till 10.6
but now i need an option to fix it w\o upgrading my 10.3 mesa. Because with upgraded mesa come upgraded drivers and after reboot some windows (including steam and chrome) just freeze after start. maybe it freezes because of another reason, but 100% after upgrade mesa and drivers

**Comment by gdrewb-valve** [comment]
@DeepDlueIV, can you post full system specs?

**Comment by DeepDlueIV** [comment]
SuperFlick can you tell me how can i upgrade to 10.6?Canot find anyway to do it in trusty. 10.6 that's for virvid as i know.
Btw here they are valve:
http://pastebin.com/PRSpsNed
Log is too big. And sorry, i don't know GitHub syntaxes

**Comment by SuperFlick** [comment]
DeepDlueIV
i do it via Synaptic with xorg-edgers ppa. but since it works pretty bad  for me, i dont think i am doing it right.
some users say: add xorg-edgers ppa via terminal, then update and upgrade (apt-get update && apt-get upgrade). but this option doesnt upgrade mesa, only drivers

**Comment by DeepDlueIV** [comment]
That's it. Already have xorg ppa, but synaptic does not seeing mesa.
https://launchpad.net/~xorg-edgers/+archive/ubuntu/ppa But here it is

**Comment by SuperFlick** [comment]
look for lib****-mesa
![2015-07-22 12 36 15](https://cloud.githubusercontent.com/assets/13034633/8819447/e57bfbee-3065-11e5-9421-d9b18dbcba8c.png)
Better wait for aswer by developers. Because i'm tired reinstall ubuntu 5 times per day =)

**Comment by DeepDlueIV** [comment]
This is Xorg-edgers ppa. No any mesa there
![no mesa](https://cloud.githubusercontent.com/assets/13434539/8820288/ad8e321c-3086-11e5-88e8-c277da228e96.png)
But this  is canonicals rep which have a lot of different mesas.  Which one i need?
![mesa](https://cloud.githubusercontent.com/assets/13434539/8820329/0d319df8-3087-11e5-998a-0815d7ecfb22.png)
btw тут их просто дохрена. На скрине видно в том числе и 10.7

**Comment by SuperFlick** [comment]
DeepDlueIV
because you have oibaf's ppa with latest mesa 10.7 and it replaces 10.6 in the list.

**Comment by hrzhu** [comment]
Just FYI, to use xorg-edgers ppa, you need to do dist-upgrade not just upgrade. It will upgrade your x server, mesa(to 10.6.2) and drivers. If in the future you want to upgrade your Ubuntu to a new release, you need to purge this ppa first.

**Comment by SuperFlick** [comment]
hrzhu

didn't work in my case. still 10.3
and why libgbm1 conflicts with itself?  i cant update this pack
![2015-07-23 10 07 59](https://cloud.githubusercontent.com/assets/13034633/8842966/a662883c-311a-11e5-8cb2-b525a76d22ee.png)

**Comment by DeepDlueIV** [comment]
sudo apt-get dist-upgrade
[sudo] password for deepdlueiv: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-headers-3.16.0-44 linux-headers-3.16.0-44-generic
  linux-image-3.16.0-44-generic linux-image-extra-3.16.0-44-generic
The following packages have been kept back:
  libgbm1
The following packages will be upgraded:
  i965-va-driver intel-gpu-tools libcairo-gobject2 libcairo2
  libmysqlclient18:i386 libva1 libwayland-client0 libwayland-cursor0
  libwayland-server0 linux-generic-lts-utopic linux-headers-generic-lts-utopic
  linux-image-generic-lts-utopic linux-libc-dev mesa-common-dev mysql-common
  va-driver-all
16 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 66.8 MB of archives.
After this operation, 280 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
WARNING: The following packages cannot be authenticated!
  libva1 i965-va-driver libcairo2 libcairo-gobject2 intel-gpu-tools
  va-driver-all
Install these packages without verification? [y/N] 
E: Some packages could not be authenticated

**Comment by hrzhu** [comment]
^
This is a [bug](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1431714).
I manually remove some package and install it again to solve the conflict, I forget which specific package though.

**Comment by SuperFlick** [comment]
after all i've installed 15.04 with mesa 10.5 and now reborn works fine. but 15.04 is not lts, so i'm waiting for more bugs=\

**Comment by DeepDlueIV** [comment]
I can't solve this problem on 14.04 but i'm realy afraid to install 15.04. Last time it lives for a 2 day and then broke down my Boot loader

**Comment by DeepDlueIV** [comment]
Valve! Were are you?

**Comment by gdrewb-valve** [comment]
@DeepDlueIV, can you confirm which version of mesa you're using?  If you are using an older version with known issues upgrading is the best option.

**Comment by SuperFlick** [comment]
@gdrewb-valve mesa 10.3
we got the same problem with similar sys specs (intel hd 3000)

**Comment by DeepDlueIV** [comment]
mesa10.3 default trusty 14.04

**Comment by danginsburg** [comment]
So it seems those who have been able to update to mesa 10.6/10.7 are running successfully.  Closing this out as it is a driver issue.
