### ISSUE TITLE
Dota2 crash a lot after todays update

### ISSUE THREAD

**Issue by naturligasteg** [ValveSoftware/Dota-2#2443]
#### Your system information

Mac Studio M1

#### Steps for reproducing this issue:

1. Start Dota2 from the desktop - crash 50% of the time in the intro loading, 25% in the main menu. vUpold crash it will freeze on the screen and can only be closed down by force closing Steam client.
2. If you are lucky to start Dota 2, start a game, I only dare unranked at the moment.
3. After the game is over Dota2 will completely lockup int the after game statistics screen and will be unable to force close down unless the steamclient is closed.

**Comment by stow1x** [comment]
I have the same issue. I can't actually buy Collector's Cache)

**Comment by ChrisLauinger77** [comment]
Same here on Linux - it does not really start - it flickers and shows the dota 2 logo before entering main menu.
I am not able to enter the menu

**Comment by danginsburg** [comment]
> I have the same issue. I can't actually buy Collector's Cache)

This bug should be fixed with the latest update, same issue as #2449.  Tracking that bug there, please re-test and let us know if it works.

**Comment by naturligasteg** [comment]
Seems to work better for me. One crash in after game in three games.
