### ISSUE TITLE
Dota2 crashes when trying to purchase collectors cache

### ISSUE THREAD

**Issue by legcan** [ValveSoftware/Dota-2#2449]
* System information from steam in a [gist](https://gist.github.com/legcan/c85297b9ebcc225bea2eef9c4fb611c0): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Game crashes when trying to purchase treasure

#### Steps for reproducing this issue:

Uploaded screen recording [here](https://1drv.ms/v/s!AjGXVzekDHBboYkpsYL7BQ-PtoO3hQ?e=UYLFHZ)

**Comment by danginsburg** [comment]
The latest Dota 2 client update (just shipped) contains a fix for this.  Please try again.

**Comment by legcan** [comment]
@danginsburg works now. Thank you.
