### ISSUE TITLE
Gameplay graphic bugs in macOS (graphic is not rendering the map properly)

### ISSUE THREAD

**Issue by rizadwiandhika** [ValveSoftware/Dota-2#2451]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a gist: [Click here for my system specification (in a gist)](https://gist.github.com/rizadwiandhika/103817cc6e322348b7e29956b62f89a2)
* Have you checked for system updates?: **Yes**
* Are you using the latest stable video driver available for your system? **Yes**
* Have you verified the game files?: **Yes**

#### Please describe your issue in as much detail as possible:

When i play the match, the **graphic is not rendering the map properly**. It is impossible to play the game like this. Here is the screenshot. There is also an opened issue that discuss about this (check this out: https://github.com/ValveSoftware/Dota2-Gameplay/issues/11171).

![image](https://github.com/ValveSoftware/Dota-2/assets/68406409/b93c8294-f8ea-4208-8676-79afba3b9922)

#### Steps for reproducing this issue:

1. Open dota 
2. Finding normal match
3. When the game starts, the graphic is not properly rendered

**Comment by Vodi4kaa** [comment]
The same in a competitive mode with bots -ok 
I don’t any think about this but still wait info from boys and valve …..

**Comment by kisak-valve** [comment]
Hello @rizadwiandhika, this issue is already being tracked at #2445. Closing as a duplicate.

**Comment by 4erepaxen** [comment]
#2457
