### ISSUE TITLE
[OS X] Low fps in game with Intel 6100 GPU

### ISSUE THREAD

**Issue by materemias** [ValveSoftware/Dota-2#246]
Hi, 

as previously discussed in https://github.com/ValveSoftware/Dota-2-Reborn/issues/4 OS X reborn has way lower fps than S1. Based on the technical demo it should be improved much on such integrated GPU-s.

My device is a MacBook Pro 13" retina 2015:

Model Identifier: MacBookPro12,1
Processor Name: Intel Core i5
Processor Speed: 2,7 GHz
Number of Processors: 1
Total Number of Cores: 2
Memory: 16 GB

Chipset Model:  Intel Iris Graphics 6100
  Type: GPU
  Bus:  Built-In
  VRAM (Dynamic, Max):  1536 MB

Menu is around 90fps, super smooth, frame rates drop drastically if i start a game or if a hero model is loaded (like browsing heroes in the main menu).

in-game:
on 1440x900 and low setting (everything off) I see fps ranging 20-45 usually around 35.
going to the next preset detail setting (med-low) it drops to 25fps ranging 10-30.

i got around 35 fps in s1 on 1600x900 medium settings.

please let me know if you need further details,

rm

**Comment by gdrewb-valve** [comment]
Hopefully the same issue as #245 but keeping this open for 5000 vs. 6100.

**Comment by danginsburg** [comment]
@materemias Can you try the 7/28 update and report back on your in-game perf numbers at low and medium-low settings?  It includes several performance optimizations, I would like to know if it improved things on your configuration.

**Comment by materemias** [comment]
@danginsburg here my results:
in menu the heroes sub menu (displaying 3 heroes side by side): drops to 25-30fps from 70
1440x900, low settings: 40-45 fps (much improved, but still doesn't seem like 40fps, with small stops and laggs pretty often)
1440x900, med-low: 20-25 fps (also some improvement here, graphics is on playable level here)
1440x900, med-high: 16-19 fps
1440x900, high: 15-18 fps

**Comment by manicmouse** [comment]
So still kinda unplayable... :(

I was really hoping source 2 would increase performance on lower end machines.

**Comment by materemias** [comment]
with all settings off and texture level mid it could be playable at 40-60fps, so if that could be reached that would be an achivement

**Comment by manicmouse** [comment]
But not really any better than source 1, probably slightly worse - despite being native open GL, 64 bit and on a newer "more efficient" engine.

Like I said, it's disappointing.  This update was supposed to improve performance on lower end machines.  The Mac version should see even more improvement since source 1 was basically emulating direct X rather than being native OpenGL.  Hopefully things improve.

**Comment by hyw** [comment]
just wanted to add that there is a definite improvement with the latest 7/28 patch but the performance is still not up to par with source 1. Right now with source 1 settings, I'm able to achieve around 25 fps which is decently playable (before 7/28 update was around 15 fps), but source 1 runs somewhere around 40-60 fps so the difference is still significant. I also remember reading that someone had reported something that felt like input lag and wanted to note that it still exists. but the menus and everything outside of an actual game is very very smooth even the hero browser (but not hero demo).

my machine specs:
13-inch MacBook Air Early 2015 Model
2.2 GHz Intel Core i7
8 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB

**Comment by danginsburg** [comment]
We are aware that there are performance issues on OSX on HD 5000/6000/6100 and that HD 3000 is unplayable. The issues appear to be driver problems.  On HD 3000, we have narrowed it down to continuous recompiling of shaders in the driver.  We have filed a Radar and are awaiting response from Apple.  The problem on HD 5000/6000/6100 appears to be that we are GPU limited (the framerate is highly impacted by resolution).  I suspect perhaps issues in the shader compiler in the driver, but at this point that is just conjecture.

@manicmouse I understand your frustrations, we are doing what we can to improve performance on the Intel GPUs with driver issues.

**Comment by manicmouse** [comment]
Oh no don't worry - I know you guys are working hard.  Despite the lower performance I prefer playing in Reborn at this point because it is actually far more stable for me.  Source 1 DOTA crashes nearly every game for me, Reborn hasn't crashed in my last 5!  So in that respect source 2 is much better.

In terms of driver issues - any plans to make us of metal in El Cap?  Or will Vulcan be on the horizon and make a difference?

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
