### ISSUE TITLE
player perspective camera in live

### ISSUE THREAD

**Issue by snssb** [ValveSoftware/Dota-2#2461]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

The player perspective camera in live should work correctly, or it shouldn't be there if it's intentionally broken

#### Steps for reproducing this issue:

1. spectate for live game
2. click player perspective camera
3. be frozen in the midle

**Comment by kisak-valve** [comment]
Hello @snssb, this issue tracker is limited to issues with the Mac and Linux client of Dota 2.

Your issue is not OS-specific and was transferred to https://github.com/ValveSoftware/Dota2-Gameplay/issues/11466.

Closing as a duplicate.
