### ISSUE TITLE
"The Emerald Abyss" map visual glitches.

### ISSUE THREAD

**Issue by MathiasSven** [ValveSoftware/Dota-2#2465]
#### Your system information

* System information: [gist](https://gist.github.com/MathiasSven/9f25751c52f7c2fa7f2461ed13b104f3): 
* Have you checked for system updates?: **Yes**
* Are you using the latest stable video driver available for your system? **Yes**
* Have you verified the game files?: **Yes**

#### Please describe your issue in as much detail as possible:
The map has visual glitches regardless of weather effect.

![Screenshot_20230906_145253](https://github.com/ValveSoftware/Dota-2/assets/24759037/427ef5a1-0f6a-4b84-b167-ea664f846e5a)
![20230906123354_1](https://github.com/ValveSoftware/Dota-2/assets/24759037/27365d85-dcf0-4276-805c-20e024b38b2b)
![20230906123400_1](https://github.com/ValveSoftware/Dota-2/assets/24759037/2eb4d35b-91e0-4658-838a-845d8fce315e)
![20230906145255_1](https://github.com/ValveSoftware/Dota-2/assets/24759037/4b576c51-39a4-49e8-97bf-9973c72f62f4)

**Comment by danginsburg** [comment]
Thanks for the report.  This bug happens on Windows as well so I'm going to close this out here as this is just for Linux/macOS specific issues.  However, the bug has been passed along to the team and we will take a look at it.
