### ISSUE TITLE
Game crashes during overwatch case replay decompression.

### ISSUE THREAD

**Issue by Steamvoker** [ValveSoftware/Dota-2#2468]
System information from steam: [gist](https://gist.github.com/Steamvoker/866880b64a6395d27dcea9f7814a3164)
The system is up to date.
Latest video driver.
I have verified game's integrity.

Steps for reproducing this issue:

1. Open the game.
2. Select "Review Case".
3. Press "Download Replay".
4. Wait for the download to finish and change to decompression.

I can review the downloaded case after relaunching the game despite it crashing during (or i guess after) replay decompression.

**Comment by Steamvoker** [comment]
Closing the issue as it doesn't happen to me anymore.

**Comment by ChrisLauinger77** [comment]
It happens to me again - on linux
https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb
