### ISSUE TITLE
[Linux] Dota Live Streaming Beta won't work in-game

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#247]
The recently introduced Live Streaming service won't work in-game, citing the same issue as trying to watch it from an unsupported browser (e.g. Firefox):
 "_Your web browser does not support the minimum set of features required to watch this broadcast._"

![Example image](http://i.imgur.com/CZTdKw0.png)

It also won't work within the Steam Overlay, while it tries to load it, it says
 "_Updating Steam_"
 and when it fails, will display the following text:
 "_Failed to apply a Steam update that is required to watch this broadcast._"

Specs:

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x2a
>     CPU Stepping:  0x7
>     CPU Type:  0x0
>     Speed:  3800 Mhz
>     8 logical processors
>     4 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     "Arch Linux" (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.0.6-1-ARCH
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11702000
>     X Window Manager:  <Unknown>
>     Steam Runtime Version:  steam-runtime-release_2015-01-06
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce 8400GS/PCIe/SSE2
> 
>    Driver Version:  3.3.0 NVIDIA 340.76
>      OpenGL Version: 3.3
>      Desktop Color Depth: 24 bits per pixel
>      Monitor Refresh Rate: 60 Hz
>      VendorID:  0x10de
>      DeviceID:  0x10c3
>      Number of Monitors:  1
>      Number of Logical Video Cards:  1
>      Primary Display Resolution:  1920 x 1080
>      Desktop Resolution: 1920 x 1080
>      Primary Display Size: 20.91" x 11.77"  (23.98" diag)
>                                              53.1cm x 29.9cm  (60.9cm diag)
>      Primary Bus: PCI Express 16x
>      Primary VRAM: 128 MB
>      Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Realtek ALC889
> 
> Memory:
>     RAM:  7946 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  1511771 Mb
>     Largest Free Hard Disk Block:  164864 Mb
> 
> Installed software:
> 
> Recent Failure Reports:
> Tue Jul 21 14:50:59 2015 GMT: file ''/tmp/dumps/assert_20150721165054_6.dmp'', upload yes: ''CrashID=bp-805d8d91-293f-423e-b815-f21f22150721''
> Tue Jul 21 15:01:15 2015 GMT: file ''/tmp/dumps/assert_20150721170027_6.dmp'', upload yes: ''CrashID=bp-8c98c878-7bef-42f8-b2c1-113902150721''

**Comment by gdrewb-valve** [comment]
Are you running the Steam client beta?  If not can you opt into that and see if it works better?

**Comment by ghost** [comment]
I were running the Normal Update branch.
I've enabled the Steam Beta Update.
As of _1437423524_ , It'll play the stream through the Steam Overlay. 
However it still fails to open the stream in-game.
Moreover, it disables the `Steam` Icon and the `Fullscreen` Button.

**Comment by gdrewb-valve** [comment]
That's good that updating Steam fixes the underlying issue.  As for Reborn there's still work going on to get things ironed out.  That's not Mac/Linux specific so it won't be tracked here.
