### ISSUE TITLE
Game fails to launch after latest update

### ISSUE THREAD

**Issue by ca1f** [ValveSoftware/Dota-2#2474]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
  * https://gist.github.com/ca1f/29ada623ad02df65ed3aeb105cb4ed48
* Have you checked for system updates?: [Yes/No]
  * Yes, no updates available.
* Are you using the latest stable video driver available for your system? [Yes/No]
  * Yes
* Have you verified the game files?: [Yes/No]
  * Yes, the problem persists.

#### Please describe your issue in as much detail as possible:
Trying to launch the game fails immediately. The terminal from which steam was launched reports the following problem:
```
Loaded libengine2.so, got (nil)
 failed to dlopen libengine2.so error=/mnt/data/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so: undefined symbol: SteamAPI_Init
 failed to dlopen "libengine2.so" error=/mnt/data/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so: undefined symbol: SteamAPI_Init
Launcher Error: Unable to load module "engine2"

Error: (0x0000000c) [Failed To Resolve Error Code.]
Uploaded AppInterfaceStats to Steam
```

**Comment by kuramayouko** [comment]
yeap same here libengine2.so error

**Comment by kisak-valve** [comment]
Hello @ca1f . this issue is already being tracked at #2472. Closing as a duplicate.

**Comment by ca1f** [comment]
Fair enough, someone beat me to reporting it. Sorry for the duplicate.
