### ISSUE TITLE
[Mac] V-sync greatly degrades performance in fullscreen mode

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#248]
This is on a 27" iMac 3.5 GHz i7, geforce GTX 775M, OS X 10.9.5, with everything set to max 
Without V-Sync I get 68 fps, with V-sync I get ~30-35 fps in either exclusive fullscreen and desktop-friendly fullscreen. It seems that the frame rate is most of the time limited to 30. Everything gets jerky, including the menus. 
In borderless window mode, same resolution (2540x1440), I get 60 fps and everything becomes way smoother once I switch to this mode. 
Lowering the resolution to 1344*756 or disabling certain settings in fullscreen mode restores the 60 fps, but at the cost of graphical quality.

**Comment by gdrewb-valve** [comment]
It's possible that with enough frame variability there are enough frames that don't make the vsync interval that vsync will really drag things down even if it averages out to higher than the vsync interval.

**Comment by jeanlain** [comment]
Maybe, but why would it only occur in fullscreen mode and not in borderless window mode, even though they show the same performance with Vsync off?
And this didn't happen before the 07/20 update. Before, I played a few (bot) matches at 60 fps most of the time, now it's mostly capped at  30. 
Before, Vsync didn't use to degrade performance. Frame rate could be around 50 fps with Vsync on, basically the same as with Vsync off.

**Comment by gdrewb-valve** [comment]
I was just theorizing, it could definitely be something else.

**Comment by jeanlain** [comment]
Were you able to repro this issue? Because it's very real on my Mac and wouldn't go away after several restarts and tests with Quartz Debug. Right now I can't play the game at full display resolution. I'm either having frame rate issue in fullscreen mode, or the menu bar masking part of the game (namely the hero colors) in windowed mode.

**Comment by gdrewb-valve** [comment]
The odd thing is that desktop-friendly fullscreen is identical to what a monitor-sized borderless window was, yet you see a vsync issue with desktop-friendly fullscreen but you didn't with a borderless window.  That makes this a very strange issue.

That's aside from whether vsync is causing issues in exclusive fullscreen, which ideally it shouldn't.

**Comment by gdrewb-valve** [comment]
As for a repro I have one of our low-end test Macs, an old Mac Mini, so my numbers may not be meaningful.  I ran at exclusive fullscreen 1280x800 no vsync and averaged about 35fps.  Turning on vsync dropped my perf to about 27fps, which is expected since perfectly hitting the vsync'ed frame times would be 30fps and we have enough variability that we do not perfectly hit the frame times all of the time.  Switching to a 1280x800 borderless window I got the same 27fps average, which was a little surprising as I would have expected the desktop to be flipping at 60fps but I don't know that for sure.

**Comment by jeanlain** [comment]
This is different from what I'm seeing. I've tested precisely again with the 07/23 update, on the hero demo map, using Legion Commander and monitoring fps while the game is paused, the little pool at the bottom left being visible. With everything on except ambiant occlusion and V-Sync, I get 70+ fps in borderless window mode at native monitor resolution. With V-Sync on I get 60 fps. Once I switch to full screen mode, I get 30-35. I get the same 70+ fps without V-Sync. It's as if the screen refresh rate was most of the time (but not always) set to 30 in full screen mode. 
I even recorded a video of the issue, but I would take some tome to upload given my internet connection.

**Comment by gdrewb-valve** [comment]
I think the text description is sufficient for now.  Dan might have more luck with a repro.

**Comment by danginsburg** [comment]
I have been able to repro this on Macbook Pro Mid 2012 2.7GHz NVIDIA GT650M.  Unfortunately, I don't have a fix yet other than to suggest disabling vsync.  From what I can see from profiling, once we go Exclusive Fullscreen it seems that we are getting extremely long irregular waits inside of SDL_GL_SwapWindow (from 30-80ms).  I believe this is NSOpenGLContext flushBuffer that is taking the time.  SDL appears to correctly set NSOpenGLCPSwapInterval to 1 to enable vsync.  I'm not sure what else we can do.  It feels like an OS issue and I don't see a clear way around it.  As long as you don't start the game in exclusive fullscreen I don't see this behavior in the other modes.  So I think if you start in Desktop-Friendly fullscreen with VSYNC on it is OK.

**Comment by jeanlain** [comment]
As I recall, the issue appears in desktop-frieldy fullscreen as well, but it may no longer be the case since the fullscreen mode has changed (it now uses its own space). I cannot test right now. 
I could still use a borderless window and hide the menu bar (possible in 10.11).

**Comment by gdrewb-valve** [comment]
Is there still an active Dota issue here?  It sounds like investigation has shown it to be a problem on Apple's side?
