### ISSUE TITLE
Fullscreen mode still rapidly switches between monitors

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/Dota-2#2482]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Newbytee/7f4dd300c32e80b199680fcace991ffd (I have Steam set to Swedish, sorry)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

The behaviour is exactly the same as what's described in https://github.com/ValveSoftware/Dota-2/issues/2435. However, I'm still experiencing this with the latest version of Dota 2. I don't know what I could be doing wrong. Disabling one of my monitors while Dota starts up works around the issue and I can play just fine.

#### Steps for reproducing this issue:

Same as https://github.com/ValveSoftware/Dota-2/issues/2435

**Comment by vncfrrll** [comment]
This bug is back for me after the 2023 Compendium Update.

**Comment by tfhavingfun** [comment]
Can confirm.

**Comment by SamanthaClarke1** [comment]
Back for me as well, post-2023 compendium update.

**Comment by 914the914** [comment]
I am encountering the same issue when running GNOME Wayland on a dual-screen setup, with both screens at 4K resolution and operating at 144 fps, using AMD Mesa drivers.

To launch the game, I have to use the launch options -sw -w 3800 -h 2000.

Additionally, there's a risk of the game client freezing when attempting to access the 'Settings' menu within Dota.

**Comment by Jusix** [comment]
Same problem. Launches on main monitor. Minimize, maximize with Alt + Tab gets moved to second monitor. Minimize, maximize with dedicated minimize keybinding lets the game toggle between the two screens like crazy after maximizing again.

**Comment by rmbleeker** [comment]
I would like to add that if I add `-sw -w 1920 -h 1080` to my launch options and then go back to full screen at my monitor's native resolution while in game, I'm not having any issues. So as long as this is ongoing I'm using that as a work-around

**Comment by ReDTerraN** [comment]
Same issue for me, using the work-around meanwhile until this is fixed.

**Comment by kshammer** [comment]
Same issue here
System configuration
https://gist.github.com/kshammer/628dcc1856146f7388b6f6075316b6c8

**Comment by jfdsmit** [comment]
Can confirm this also happens to me, I'm using the same launch options as @rmbleeker to start, and then switch to Borderless Window.

In addition, when I switch to Desktop-friendly Fullscreen in Settings, the Dota client becomes unresponsive and I have to `kill -9`; I have to use Borderless Window to play fullscreen. Not sure if related.

**Comment by nur-akazikulov** [comment]
Still happens, ubuntu 22.04, dual monitors setup, latest patch atm

**Comment by yogaxpto** [comment]
The workaround for me is to use the "Borderless Window".
But now I'm presented with a lot of game freezes for a few seconds after changing scenarios (picking hero, entering game, opening map).

**Comment by Newbytee** [comment]
> But now I'm presented with a lot of game freezes for a few seconds after changing scenarios (picking hero, entering game, opening map).

This is likely because of shader compilation stutter. Regardless, this is unrelated to the problem discussed in this issue.

**Comment by rmbleeker** [comment]
@danginsburg is there any movement on this issue? It's been almost 2 months now since this popped up again, and it seems to be a regression from an older issue (#2435) that was reported a month before that. 

edit: just tested to make sure the issue still occurs and unfortunately it does

**Comment by madezent** [comment]
This issue occurs for me too.

**Comment by andrei-kozel** [comment]
Same here: [https://www.youtube.com/watch?v=HV2xjM9A4zA](https://www.youtube.com/watch?v=HV2xjM9A4zA)
gist: [https://gist.github.com/andrei-kozel/4e9fcefe35947cbbf82f09443272f634](https://gist.github.com/andrei-kozel/4e9fcefe35947cbbf82f09443272f634)

**Comment by madezent** [comment]
I have found a workaround to get it working in full screen. I disable one monitor, start Dota 2, then enable the monitor again. Then it stays fullscreen on one and I can play.

**Comment by Newbytee** [comment]
> I have found a workaround to get it working in full screen. I disable one monitor, start Dota 2, then enable the monitor again. Then it stays fullscreen on one and I can play.

Did you read the issue description? :sweat_smile:

**Comment by troll-os** [comment]
Almost the same issue for me on up to date Pop_OS, Gnome, X11, AMD GPU.

Issue happens on CS 2 aswell. I can actually launch both games but if I alt-tab the fiesta starts and its a mess to get an actual focus back. 

Issue was supposedly gone for a few updates but it came back.

Already reported to the CS2 feedback mail box.

Also if I don't Alt Tab, sometimes the games quickly loses focus back and forth for a few seconds, making team fights random...

**Comment by andrei-kozel** [comment]
One more workaround is to enable Mirror mode in display settings -> Start a game -> Wait till you see main game screen -> Enable Join mode back. 
Works with Ubuntu 23.10

**Comment by magynhard** [comment]
One more workaround that worked for me, was to enable "advanced settings" and remove the tick on the checkbox "user friendly full screen mode minimizes game on focus lose". That features seems to produce this problem on GNOME.

**Comment by rmbleeker** [comment]
> One more workaround that worked for me, was to enable "advanced settings" and remove the tick on the checkbox "user friendly full screen mode minimizes game on focus lose". That features seems to produce this problem on GNOME.

Sorry, can not confirm. This checkbox has been off for ages on my end, but I'm still experiencing the issue. I'm running Pop!_OS with the default desktop environment which is based on Gnome.

**Comment by Jusix** [comment]
My current workaround is running Dota 2 through gamescope.
With `gamescope -f -W 3840 -H 2160 -r 60 -- %command% -novid` everything works fine.

**Comment by rmbleeker** [comment]
> My current workaround is running Dota 2 through gamescope. With `gamescope -f -W 3840 -H 2160 -r 60 -- %command% -novid` everything works fine.

Sounds like a nice work-around but gamescope is not in the Pop!_OS repositories and I read some horror stories about compiling it yourself, so I'll pass on this for now. I'm just hoping it will get addressed soon as it seems to be a regression from an earlier issue that only manifests on dual-screen setups where both screens share at least their resolution and possible refresh rate.

**Comment by robertpro** [comment]
> > My current workaround is running Dota 2 through gamescope. With `gamescope -f -W 3840 -H 2160 -r 60 -- %command% -novid` everything works fine.
> 
> Sounds like a nice work-around but gamescope is not in the Pop!_OS repositories and I read some horror stories about compiling it yourself, so I'll pass on this for now. I'm just hoping it will get addressed soon as it seems to be a regression from an earlier issue that only manifests on dual-screen setups where both screens share at least their resolution and possible refresh rate.

I also tried this with flatpak, but it won't work because gamescope needs to be present

**Comment by duartec3000** [comment]
> One more workaround that worked for me, was to enable "advanced settings" and remove the tick on the checkbox "user friendly full screen mode minimizes game on focus lose". That features seems to produce this problem on GNOME.

I have it unchecked and it was producing the issue. Tried to check it and uncheck it and the issue goes away but after another Launch it comes back as the game automatically goes from "Use advanced settings" to "Use my monitor's current resolution" when launching. If we could force the game to stay at "Use advanced settings" with "Desktop-friendly fullscreen minimizes on focus loss" un-checked we would be golden.

**Comment by kshammer** [comment]
This was fixed for me in the latest update.

**Comment by Newbytee** [comment]
Seems to be fixed for me as well. Great!

**Comment by rmbleeker** [comment]
I just tested and it was definitely **not** fixed for me, although there seems to be less flickering Dota still does not behave normally, the viewport still switches between monitors when I try to move the mouse and I could not move the cursor or click on anything in the interface. I had to stop the game by switching to the Steam window and clicking the button there that force-closes the game.

Please re-open this issue.

**Comment by Newbytee** [comment]
I can't really tell if what you're describing is the same issue, but I'll reopen until we get more reports then.

**Comment by rmbleeker** [comment]
Visually and behaviorally it looks like the same issue I had before, just that the flickering is less pronounced. Something definitely changed, improved even, but whatever is it they've messed up is certainly not fixed.

I just wish there was something we could do. Test specific settings, upload a log or screen capture or whatever, but Valve's been pretty silent on this issue for a long time.

**Comment by troll-os** [comment]
Issue seems to be fixed **for now** , same as for CS2, for which I had the exact same problem https://github.com/ValveSoftware/csgo-osx-linux/issues/3268

Though it was fixed once for CS2 during a few days/weeks and broke again after a small update...

Wait and see that it's fixed for everyone

@rmbleeker, I'm also on Pop_OS and it does seem to be working, are you on NVIDIA or AMD ? 

edit : typo

**Comment by Zomtir** [comment]
Some issues persist. The rapid switching without any user input seems to be fixed. However the game still switches when the mouse enters the desktop friendly fullscreen.

1. Start the game. Game will start on Monitor 1. However the last remembered screen from last session should be Monitor 2 (closed while being on Monitor 2).
2. Have the mouse pointer on Monitor 2.
3. Enter the Monitor 1 area. Game will flicker to Monitor 2.
4. Enter the Monitor 2 area. Game will flicker to Monitor 1.
5. Open the Ubuntu settings -> Display settings -> Change from Extend to Mirror -> Apply -> Revert
6. Mouse can enter the game UI without the game flickering to a different screen

This issue seems to be related to multi-screen indexing. The game may think the monitor order is [2,1] while the OS has [1,2]. In my case I have three screens, default order is [1,3,2] and I change it to [1,2,3] (though real world arrangement may not update the indexing, because the could be arbitrarily aligned).

1. Game tells OS to display on screen index 0 (which is Monitor 2). OS displays it on Monitor 1.
2. OS tells game that mouse event is triggered on Monitor 2, game figures out something is wrong and tries to move to Monitor 2, but does not fix the monitor order.
3. Resetting all Monitors to show the same screen will reinitialize the indices and temporally fix the issue.

Hardware:
```
sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:0b:00.0
       logical name: /dev/fb0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=amdgpu latency=0 resolution=1920,1080
       resources: irq:117 memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:e000(size=256) memory:fcd00000-fcd7ffff memory:fcd80000-fcd9ffff
```

**Comment by rmbleeker** [comment]
@troll-os I'm on Nvidia

The issue I'm currently experiencing is indeed the same as @Zomtir describes it.

**Comment by light-on-shadow** [comment]
Is this even being worked on?
Only workaround for me is to start on second screen : -sdl_displayindex 1

**Comment by mdumitrean** [comment]
I'm still experiencing this in DOTA w/ Ubuntu 22.04. How do we get this resolved?

**Comment by light-on-shadow** [comment]
May, still happening.

**Comment by mdumitrean** [comment]
Can we get this fixed? DOTA 2 still flashing between monitors.  Have to unplug second monitor to start dota.  please fix. @kisak-valve

**Comment by rmbleeker** [comment]
I recently tested this again, removing the launch options that start Dota 2 in a smaller window which I used as a work around for this issue. However it seems to have been silently fixed, at least the issue isn't appearing anymore at my end. Can anyone re-test and confirm?

**Comment by Zomtir** [comment]
The flickering is gone. I just retested on Ubuntu 24.04 with Vulkan. This issue is solved.

However the display index on close is not saved for the next session. The game always starts on index 1. Therefore I'll keep the "-sdl_displayindex 2" launch option.

**Comment by Newbytee** [comment]
I'll close this again then. I don't really play Dota 2 any more, so I don't feel like reinstalling just to test this.
