### ISSUE TITLE
Steam Updates

### ISSUE THREAD

**Issue by killdrm** [ValveSoftware/Dota-2#2484]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Your system information

    System information from steam (Steam -> Help -> System Information) in a [gist](https://gist.github.com/):
    Computer Information:
    Manufacturer: Micro-Star International Co., Ltd.
    Model: MS-16J6
    Form Factor: Laptop
    No Touch Input Detected
    Processor Information:
    CPU Vendor: GenuineIntel
    CPU Brand: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    CPU Family: 0x6
    CPU Model: 0x5e
    CPU Stepping: 0x3
    CPU Type: 0x0
    Speed: 3200 MHz
    4 logical processors
    4 physical processors
    Hyper-threading: Unsupported
    FCMOV: Supported
    SSE2: Supported
    SSE3: Supported
    SSSE3: Supported
    SSE4a: Unsupported
    SSE41: Supported
    SSE42: Supported
    AES: Supported
    AVX: Supported
    AVX2: Supported
    AVX512F: Unsupported
    AVX512PF: Unsupported
    AVX512ER: Unsupported
    AVX512CD: Unsupported
    AVX512VNNI: Unsupported
    SHA: Unsupported
    CMPXCHG16B: Supported
    LAHF/SAHF: Supported
    PrefetchW: Unsupported
    Operating System Version:
    Ubuntu 22.04.3 LTS (64 bit)
    Kernel Name: Linux
    Kernel Version: 6.2.0-32-generic
    X Server Vendor: The X.Org Foundation
    X Server Release: 12101004
    X Window Manager: GNOME Shell
    Steam Runtime Version: steam-runtime_0.20230801.56012
    Video Card:
    Driver: NVIDIA Corporation NVIDIA GeForce 940MX/PCIe/SSE2
    Driver Version: 4.6.0 NVIDIA 535.86.05
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID: 0x8086
    DeviceID: 0x191b
    Revision Not Detected
    Number of Monitors: 1
    Number of Logical Video Cards: 1
    Primary Display Resolution: 1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13.54" x 7.64" (15.51" diag), 34.4cm x 19.4cm (39.4cm diag)
    Primary VRAM: 2048 MB
    Sound card:
    Audio device: Realtek ALC892
    Memory:
    RAM: 7844 Mb
    VR Hardware:
    VR Headset: None detected
    Miscellaneous:
    UI Language: English
    LANG: en_US.UTF-8
    Total Hard Disk Space Available: 899707 MB
    Largest Free Hard Disk Block: 688583 MB
    Storage:
    Number of SSDs: 1
    SSD sizes: 960G
    Number of HDDs: 0
    Number of removable drives: 0
    Have you checked for system updates?: Yes
    Are you using the latest stable video driver available for your system? [Yes/No]
    Have you verified the game files?: Yes
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. 
2. 
The console shows the next message:
steam.sh[11495]: Running Steam on ubuntu 22.04 64-bit
steam.sh[11495]: STEAM_RUNTIME is enabled automatically
setup.sh[12225]: Steam runtime environment up-to-date!
steam.sh[11495]: Steam client's requirements are satisfied
[2023-09-23 19:11:27] Startup - updater built Sep 11 2023 20:48:54
[2023-09-23 19:11:27] Startup - Steam Client launched with: '/home/andres/.local/share/Steam/ubuntu12_32/steam'
09/23 19:11:27 Init: Installing breakpad exception handler for appid(steam)/version(1694466342)/tid(12295)
[2023-09-23 19:11:27] Loading cached metrics from disk (/home/andres/.local/share/Steam/package/steam_client_metrics.bin)
[2023-09-23 19:11:27] Using the following download hosts for Public, Realm steamglobal
[2023-09-23 19:11:27] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-09-23 19:11:27] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-09-23 19:11:27] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-09-23 19:11:27] Verifying installation...
[2023-09-23 19:11:28] Verification complete

Steam logging initialized: directory: /home/andres/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xed00f370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xed00dcc0
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
steamwebhelper.sh[12323]: Runtime for steamwebhelper: defaulting to /home/andres/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[12323]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 252 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 12427
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam

**Comment by kisak-valve** [comment]
Hello @killdrm, you haven't described a coherent issue here and nothing is obviously wrong.

**Comment by killdrm** [comment]
The issue is that Steam is not updating

**Comment by killdrm** [comment]
And because of that Cannot upload an image to my team. When finding a match in Dota 2
