### ISSUE TITLE
commends cannot be updated

### ISSUE THREAD

**Issue by MRvirusIR** [ValveSoftware/Dota-2#2486]
#### Linux / ubuntu 22.04

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

# Description
Hello, I have a problem that has been around for about 2-3 weeks now, and my problem has not been solved, and no matter how much I searched on Google, I did not get anywhere.
My problem is that as far as I understand, the numbers of Commands and Match MVP variables do not change, even though I am much more than these numbers and these numbers are not updated, what should I do to solve the problem?

## For Example

before
<img src="https://camo.githubusercontent.com/b81b1577f2d6bd44ec2fcb2e4d0e50ea22a9247e831e9181a22d7b15c71c117d/68747470733a2f2f73362e7575706c6f61642e69722f66696c65732f73637265656e73686f745f66726f6d5f323032332d30392d32305f30312d30392d34305f727166342e706e67" /> 

after
<img src="https://s6.uupload.ir/files/screenshot_from_2023-09-24_12-15-14_5ean.png" />

Now, in these 8 matches that happened from 295 to 303, I received more than 10 commends, but none of them were received for me.

**Comment by kisak-valve** [comment]
Hello @MRvirusIR, it looks like there's several issue reports on the Dota2-Gameplay issue tracker indicating this is not an OS specific issue.

Closing in favor of https://github.com/ValveSoftware/Dota2-Gameplay/issues/11278.

**Comment by MRvirusIR** [comment]
> Hello @MRvirusIR, it looks like there's several issue reports on the Dota2-Gameplay issue tracker indicating this is not an OS specific issue.
> 
> Closing in favor of [ValveSoftware/Dota2-Gameplay#11278](https://github.com/ValveSoftware/Dota2-Gameplay/issues/11278).

The problem is that no support answers the reports, is this normal?
