### ISSUE TITLE
[Linux/Steam Deck] Dota 2 freezes on opening Stats tab in profile

### ISSUE THREAD

**Issue by INNKCake** [ValveSoftware/Dota-2#2487]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/INNKCake/1ce71798d1a9355003c34e6871d38bd2): Steam Deck, docked with Valve dock, with external monitor, desktop mode
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Dota started freezing on opening Stats tab in profile. All the other tabs work fine. The only way to close Dota after is to kill the process in terminal. Issue have been around for me for about a month or so.

#### Steps for reproducing this issue:

1.  Launch Dota2
2.  Try to open Stats in your profile
3. Game freezes completely

**Comment by kisak-valve** [comment]
Possible duplicate of #2464.

**Comment by INNKCake** [comment]
@kisak-valve oh, yes, it is. Never thought it was about Mangohud in the first place. Closing this one.
