### ISSUE TITLE
Oversized Resolution on Mac Client (Reborn)

### ISSUE THREAD

**Issue by bloodbender** [ValveSoftware/Dota-2#249]
Prior to the last update, the Reborn client worked almost perfectly on my mac - occasionally my minimal was oversized, but that problem quickly fixed itself. However, after the most recent update (where they released ranked matchmaking), the Reborn client is unplayable. Every image in the client is blown up by 200% so that I am only able to see the top right portion of the screen (the settings button, picture of Mirana, heroes tab, etc.)

Also, since everything is blown up so much, I can't even access the full settings screen and adjust my resolution settings (not sure if that would even fix the problem). Is anyone else having this problem and, if so, do you know if there is a solution?
<img width="501" alt="screen shot 2015-07-21 at 3 06 21 pm" src="https://cloud.githubusercontent.com/assets/13440063/8810034/2ef354d6-2fba-11e5-9d70-41fa75cd683a.png">

**Comment by gdrewb-valve** [comment]
Put "-sw -w 1280 -h 720" in your launch options and that should force a smaller size.  Then pick your preferred settings from the video settings and see if things work after that.

**Comment by bloodbender** [comment]
Thank you so much! I entered those commands and it worked exactly like you said. Unfortunately, the game doesn't save my settings, so it seems I have to reconfigure the resolution each time I load up. Also, sometimes I have to click multiple times for a mouse-click (occasionally it doesn't register the click on first try). Do you think the client will be updated so that I can remove the command from the launch options eventually?

**Comment by gdrewb-valve** [comment]
There definitely sounds like a bug here that we'll fix if we can find it.

What video settings are you using?

**Comment by bloodbender** [comment]
Sorry, I'm really tech illiterate. I'm not exactly sure what you are referring to with video settings. This is some information that may be relevant lol...

Graphic Card: Intel Iris Pro 1536 MB
Resolution: 16:10
Model: Macbook Retina Display; Mid 2014

If there is different information you are asking for, please let me know how to find it! Thanks again for your help.

**Comment by gdrewb-valve** [comment]
If you click on the gear icon on the upper left to get to settings there's a tab to control your video settings.  What are your settings currently at?  If they aren't "use my current resolution" click that, then apply.  Exit and restart and see if that helps.

**Comment by bloodbender** [comment]
Ahh - thats easy. Okay, when I start up the game with the commands you gave me, the video settings are: 

"Use Advanced Settings"
16:9
1280x720
Display Mode: Windowed

I have never manually selected any of these settings, not even for the source 1 Dota client - so I have no idea how they got there. I changed the settings to "use my monitor's current resolution" and it works fine afterwards (so thanks for the temporary fix!) but the problem is that when I close Dota and reopen it, the original settings are back in place! If you find a fix, that's awesome - if not, I REALLY appreciate working with me to make it playable. Thanks again.

**Comment by gdrewb-valve** [comment]
If you fix the settings, exit Reborn, remove the launch options and then restart are your settings still lost?

**Comment by bloodbender** [comment]
I feel so silly. It's fixed! I removed the original commands and now it boots up fine. Thanks for everything, you're the best!

**Comment by gdrewb-valve** [comment]
Thanks.  Is there anything unresolved?  Does this need to stay open?

**Comment by bloodbender** [comment]
No, I don't have any other problems currently. This can be closed.
