### ISSUE TITLE
Completely broken on new Sonoma

### ISSUE THREAD

**Issue by bushaev-denis** [ValveSoftware/Dota-2#2490]
#### Your system information

* [System information](https://gist.github.com/dez64ru/f38ccffc1b68e7c2e35bd3f3d1120259)
* Have you checked for system updates?: Yes, the latest macos, steam, and dota
* Are you using the latest stable video driver available for your system? Not applicable
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

```shell
$ cd /path/to/dota/
$ ./dota.sh
```

### Log

```shell
Loaded /Users/denis/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libengine2.dylib, got 0x1b016b0
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/Users/denis/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
```

**Comment by dez64ru** [comment]
Ok, after a few restarts, it was running normally, can be closed.

**Comment by bushaev-denis** [comment]
Ok, after a few restarts, it was running normally, can be closed.
