### ISSUE TITLE
Fullscreen jumps from screen to screen

### ISSUE THREAD

**Issue by mastir** [ValveSoftware/Dota-2#2492]
#### Your system information

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: Z370-A PRO (MS-7B48)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
CPU Family: 0x6
CPU Model: 0x9e
CPU Stepping: 0xa
CPU Type: 0x0
Speed: 4100 MHz
6 logical processors
6 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu 22.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.2.0-33-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230801.56012
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 525.125.06
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1b84
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.90" x 10.63" (21.65" diag), 48.0cm x 27.0cm (55.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 3072 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC892
Memory:
RAM: 64236 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 393991 MB
Largest Free Hard Disk Block: 166728 MB
Storage:
Number of SSDs: 2
SSD sizes: 640G,120G
Number of HDDs: 0
Number of removable drives: 0

#### Please describe your issue in as much detail as possible:
After update dota jumps from screen to screen. See short video:  https://youtu.be/YkplZQg0v3s?si=2qVg-t9thQzzA8Sr
Disabled one of the displays, dota started, but has no sound.  I see microphone bar jumps when i talk, but no sound output, tried all my sound devices. In pulse settings, dota is not shown as a program with sound output.

#### Steps for reproducing this issue:

1. Launch Dota 2 after update 28.09.2023

**Comment by kisak-valve** [comment]
Hello @mastir, this issue is already being tracked at #2482. Closing as a duplicate.
