### ISSUE TITLE
LINUX dota AUDIO NOT WORKING!!!! recent patch

### ISSUE THREAD

**Issue by polpokpol** [ValveSoftware/Dota-2#2493]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No] 
yes
* Are you using the latest stable video driver available for your system? [Yes/No]
yes
* Have you verified the game files?: [Yes/No]
yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
I am using bluetooth earphones.
It does not detect it.
All sound in dota 2 plays on my laptop not on earphones.
All other sound on my computer, plays on my earphones.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by mfzha** [comment]
Duplicate of https://github.com/ValveSoftware/Dota-2/issues/2491

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
