### ISSUE TITLE
In-game 2D components render on top when console is open

### ISSUE THREAD

**Issue by ananace** [ValveSoftware/Dota-2#25]
When you open the console then any in-game 2D component - health bars, text, etc - will render on top of everything, obscuring the console text as well as the menu.
![Image example](http://i.imgur.com/LwvVwhl.png)

**Comment by ArnaudAndre** [comment]
It does that on the windows build too. Though that's the windows build running on wine (nvidia driver). Moving the hero kind

**Comment by gdrewb-valve** [comment]
This is currently expected behavior.  Eventually the console will be updated to more like the main UI and the issue will be fixed then.

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux issue it won't get tracked here.
