### ISSUE TITLE
[Linux] Becomes unresponsive when clicking on Settings button

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#250]
After the last big update, when I click on settings (not random, happens every time):

The whole Dota window darkens and becomes unresponsive.
At the same moment Steam closes by itself.
Music still playing.
After about a minute Dota window closes too.

(tried to switch to fullscreen mode, because after update it starts in window-maximized mode, leaving Ubuntu panels around)

Can select other tabs like "Custom games", "Heroes", etc.

Ubuntu 15.04, GTX 760.

P. S. I see Steam update arriving. It will probably help.
P. P. S. It didn't help.

**Comment by gdrewb-valve** [comment]
If you look in your Steam system info does it have failure reports that correspond to the times Steam exited?  I can pass those on to the Steam team.

**Comment by VelorumS** [comment]
Several managed to be uploaded, as I understand:
bp-a4a4bd78-ff79-40c4-9b43-5c6502150721
bp-91bd3f21-8046-4196-8341-f9b4a2150721
bp-7fea9859-474a-4965-a42a-0a9122150721
bp-7b909a3f-6682-4f61-83c4-6d7262150721

**Comment by gdrewb-valve** [comment]
Thanks, those did come through.  As this is a crash in Steam this won't be tracked here, but I'll hold it open for a bit in case the Steam team has some immediate questions or feedback.

**Comment by VelorumS** [comment]
Fixed.
