### ISSUE TITLE
Game crashes when opening Profile History page

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota-2#2504]
The new update introduces the new profile, and add capabilities to customize the profile, however, it also comes with a bug that if you try to open the History page, it will crash

Manjaro (Arch Linux) Kernel 6.5
Intel i3-8100
NVIDIA RTX 2060

Steam Runtime Diagnostic: https://gist.github.com/deanrih/3fba864d6cc0da2087925c4f355e0b8b

Step to replicate:

1. Open Dota 2
2. Go to profile
3. Click History
4. Game crash

## Expected outcome
History page can be viewed

## Actual outcome
Game crash

**Comment by kisak-valve** [comment]
Hello @deanrih, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by deanrih** [comment]
> Hello @deanrih, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Ah, apologize for not including it, here's the link to the gist, I also updated the original comment/report

https://gist.github.com/deanrih/3fba864d6cc0da2087925c4f355e0b8b

**Comment by kisak-valve** [comment]
Thanks, since MangoHUD is in the list of Vulkan layers, that makes this the same issue as #2464. Closing as a duplicate.

**Comment by deanrih** [comment]
Ah I see, it's weird that it occurs/crash now because before the new profile update, I was able to access the page just fine, also I can confirm that running Dota 2 without MangoHud won't trigger the crash
