### ISSUE TITLE
Dota 2 segfaults at startup after Fedora 38 update

### ISSUE THREAD

**Issue by stevenschlansker** [ValveSoftware/Dota-2#2505]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/stevenschlansker/64f1224cfdb6df661e27bc9dadb88f5d
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Situation: After running system update (glibc, mesa, x11-drv, nvidia-drv) Dota 2 crashes at launch.
Expected: I can play my favorite game
Actual: crash in linuxsteamrt64 / glibc

#### Steps for reproducing this issue:

1. Run Fedora 38 with latest updates
2. Launch Dota 2
3. Sadness

I did manage to collect a backtrace with some info:

```
[ 4466.946656] dota2[103878]: segfault at 7f09b4021be1 ip 00007f0a53edb530 sp 00007fffc063d938 error 4 in libc.so.6[7f0a53da6000+15d000] likely on CPU 1 (core 1, socket 0)
[ 4466.946672] Code: c5 fe 6f 56 40 c5 fe 6f 5e 60 c5 fe 6f a6 00 10 00 00 c5 fe 6f ae 20 10 00 00 c5 fe 6f b6 40 10 00 00 c5 fe 6f be 60 10 00 00 <c5> 7e 6f 86 00 20 00 00 c5 7e 6f 8e 20 20 00 00 c5 7e 6f 96 40 20

Module /run/host/usr/lib64/libvulkan_intel.so from rpm mesa-23.1.8-1.fc38.
Module /run/host/usr/lib64/libvulkan_lvp.so from rpm mesa-23.1.8-1.fc38.
Module /run/host/usr/lib64/libvulkan_radeon.so from rpm mesa-23.1.8-1.fc38.
Module /run/host/usr/lib64/libvulkan_intel_hasvk.so from rpm mesa-23.1.8-1.fc38.
Module /run/host/usr/lib64/libedit.so.0.0.70 from rpm libedit-3.1-45.20221030cvs.fc38.
Module /run/host/usr/lib64/libvulkan.so.1.3.243 from rpm vulkan-loader-1.3.243.0-1.fc38.
Module /run/host/usr/lib64/libVkLayer_MESA_device_select.so from rpm mesa-23.1.8-1.fc38.
Module /run/host/usr/lib64/libxcb-glx.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libelf-0.189.so from rpm elfutils-0.189-3.fc38.
Module /run/host/usr/lib64/libdrm_amdgpu.so.1.0.0 from rpm libdrm-2.4.114-2.fc38.
Module /run/host/usr/lib64/libffi.so.8.1.2 from rpm libffi-3.4.4-2.fc38.
Module /run/host/usr/lib64/libexpat.so.1.8.10 from rpm expat-2.5.0-2.fc38.
Module /run/host/usr/lib64/libxcb-randr.so.0.1.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libzstd.so.1.5.5 from rpm zstd-1.5.5-1.fc38.
Module /run/host/usr/lib64/libxshmfence.so.1.0.0 from rpm libxshmfence-1.3-12.fc38.
Module /run/host/usr/lib64/libz.so.1.2.13 from rpm zlib-1.2.13-3.fc38.
Module /run/host/usr/lib64/libwayland-client.so.0.22.0 from rpm wayland-1.22.0-1.fc38.
Module /run/host/usr/lib64/libdrm.so.2.4.0 from rpm libdrm-2.4.114-2.fc38.
Module /run/host/usr/lib64/libxcb-shm.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libxcb-sync.so.1.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libxcb-xfixes.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libxcb-present.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libX11-xcb.so.1.0.0 from rpm libX11-1.8.6-1.fc38.
Module /run/host/usr/lib64/libxcb-dri3.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.
Module /run/host/usr/lib64/libXau.so.6.0.0 from rpm libXau-1.0.11-2.fc38.
Module /run/host/usr/lib64/libGLdispatch.so.0.0.0 from rpm libglvnd-1.6.0-2.fc38.
Module /run/host/usr/lib64/libXext.so.6.4.0 from rpm libXext-1.3.5-2.fc38.
Module /run/host/usr/lib64/libX11.so.6.4.0 from rpm libX11-1.8.6-1.fc38.
Module /run/host/usr/lib64/libGLX.so.0.0.0 from rpm libglvnd-1.6.0-2.fc38.
Module /run/host/usr/lib64/libGL.so.1.7.0 from rpm libglvnd-1.6.0-2.fc38.
Module /run/host/usr/lib64/libXfixes.so.3.1.0 from rpm libXfixes-6.0.0-5.fc38.

Stack trace of thread 103878:
#0  0x00007f0a53edb530 __memmove_avx_unaligned_erms (/run/host/usr/lib64/libc.so.6 + 0x15b530)
#1  0x00007f0a51d30edc n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x130edc)
#2  0x00007f0a51d31a3e n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x131a3e)
#3  0x00007f0a51d74988 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x174988)
#4  0x00007f0a1d749636 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x149636)
#5  0x00007f0a1d74aeec n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x14aeec)
#6  0x00007f0a1d795fba n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x195fba)
#7  0x00007f0a1d76c878 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x16c878)
#8  0x00007f0a5065ca65 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25ca65)
#9  0x00007f0a1d76fe42 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x16fe42)
#10 0x00007f0a50828c9a n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x428c9a)
#11 0x00007f0a50829b3d n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x429b3d)
#12 0x00007f0a5065d362 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25d362)
#13 0x00007f0a5065d7f0 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25d7f0)
#14 0x00007f0a50592487 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x192487)
#15 0x00007f0a5059291f n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x19291f)
#16 0x000055e4fcc13e30 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3e30)
#17 0x000055e4fcc13903 n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3903)
#18 0x00007f0a53da7b8a __libc_start_call_main (/run/host/usr/lib64/libc.so.6 + 0x27b8a)
#19 0x00007f0a53da7c4b __libc_start_main_impl (/run/host/usr/lib64/libc.so.6 + 0x27c4b)
#20 0x000055e4fcc13d4a n/a (/home/steven/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3d4a)
ELF object binary architecture: AMD x86-64
```

Possibly related to #2442, but I am not sure.

**Comment by Slothinger** [comment]
Im also using an up to date fedora 38 and my game is crashing while playing:

`Oct  2 18:02:29 anon-pc steam[57531]: crash_20231002180229_2.dmp[57531]: Uploading dump (out-of-process)
Oct  2 18:02:29 anon-pc steam[57531]: /tmp/dumps/crash_20231002180229_2.dmp
Oct  2 18:02:29 anon-pc kernel: dota2[53441]: segfault at cb4 ip 00007fceb0d90729 sp 00007ffe66cca720 error 4 in libclient.so[7fceafaa3000+2f5f000] likely on CPU 18 (core 8, socket 0)
Oct  2 18:02:29 anon-pc kernel: Code: 80 70 08 00 00 48 39 f0 0f 85 e3 01 00 00 4c 8d af f0 0a 00 00 48 8d 15 2d 16 34 03 31 c9 48 8d 35 ac 79 34 03 e8 37 a0 d1 fe <83> b8 b4 0c 00 00 02 48 89 c7 0f 84 57 ff 
ff ff e8 92 e6 5b 01 49
Oct  2 18:02:29 anon-pc audit[53441]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=53441 comm="dota2" exe=2F686F6D652F6D616E75656C2F2E6C6F63616C2
F73686172652F537465616D2F737465616D617070732F636F6D6D6F6E2F646F7461203220626574612F67616D652F62696E2F6C696E7578737465616D727436342F646F746132 sig=11 res=1
Oct  2 18:02:29 anon-pc audit: BPF prog-id=95 op=LOAD
Oct  2 18:02:29 anon-pc audit: BPF prog-id=96 op=LOAD
Oct  2 18:02:29 anon-pc audit: BPF prog-id=97 op=LOAD
Oct  2 18:02:29 anon-pc systemd[1]: Started systemd-coredump@2-57532-0.service - Process Core Dump (PID 57532/UID 0).
Oct  2 18:02:29 anon-pc audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-57532-0 comm="systemd" exe="/usr/lib/systemd/systemd" h
ostname=? addr=? terminal=? res=success'
Oct  2 18:02:31 anon-pc steam[57531]: crash_20231002180229_2.dmp[57531]: Finished uploading minidump (out-of-process): success = yes
Oct  2 18:02:31 anon-pc steam[57531]: crash_20231002180229_2.dmp[57531]: response: CrashID=bp-711a2256-9dda-458e-a80f-c6f762231002
Oct  2 18:02:31 anon-pc steam[57531]: crash_20231002180229_2.dmp[57531]: file ''/tmp/dumps/crash_20231002180229_2.dmp'', upload yes: ''CrashID=bp-711a2256-9dda-458e-a80f-c6f762231002''
Oct  2 18:02:31 anon-pc steam[57531]: pid 57531 != 57530, skipping destruction (fork without exec?)`

**Comment by ondrejkolin** [comment]
IT seems as that there is a workaround: https://steamcommunity.com/app/730/discussions/0/3881597531960176788/

Setting execute options to: 
` WAYLAND_DISPLAY= %command% -vulkan`
Should fix the issue

**Comment by stevenschlansker** [comment]
Thank you for the idea, but unfortunately that doesn't help me. The linked issue has a stack trace beginning with:
`#0 0x00007f75044309a8 n/a (/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.4600.2 + 0x79a8)`
so maybe this is a different issue. :(

**Comment by stevenschlansker** [comment]
Is there any additional information or support I can provide to get this bug fixed? I still cannot launch Dota and it makes me very sad :(

**Comment by stevenschlansker** [comment]
I updated to Fedora 39, same problem unfortunately.

Here's a minidump in case it's helpful:
[crash_20231112161520_2.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/13329547/crash_20231112161520_2.dmp.zip)

**Comment by stevenschlansker** [comment]
It is 2024 now and I still cannot play dota in my favorite OS, which worked fine for many, many years 😭

**Comment by rowlin** [comment]
I have same problem on ubuntu ..
and i found solution : no dota - no problem .. think about )

**Comment by stevenschlansker** [comment]
Fixed now - thank you Dota2 Janitor
