### ISSUE TITLE
match_time displayed instead of the actual time spend searching

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#251]
hi,
I just had to restart dota 2 reborn while our stack was searching the next match. After I get back into the main menu the search options are overwritten with match_time. (bottom right corner)

Screenshot: 
![dota_2_reborn_bug](https://cloud.githubusercontent.com/assets/5174562/8813983/ff65906e-3007-11e5-92ec-161506a88bba.png)

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue but I'll pass it on to the larger team.
