### ISSUE TITLE
bluetooth audio problems in dota 2 and cs2

### ISSUE THREAD

**Issue by tipu** [ValveSoftware/Dota-2#2510]
#### Your system information
https://gist.github.com/tipu/33e5303842ddc29952d31285bbca8ad9

#### Please describe your issue in as much detail as possible:
No audio using bluetooth in both cs2 and dota2.

**Big Hint**: When I load cs2/dota2, the game freezes for a minute or more. During this time if I disconnect my bluetooth headset, it immediately loads the game. It's clearly locked due to something bluetooth/audio. I did this multiple times and disconnected it at various times while it was frozen (after a few seconds of being frozen vs 30 seconds of being frozen) and the game consistently loads immediately after the bluetooth disconnect.

I also tried this with two different bluetooth headsets (pixel buds and a sony pair, though this information is likely irrelevant).

Note that audio works everywhere else.

#### Steps for reproducing this issue:

1 Connect bluetooth headset
2. Open cs2/dota2
3. Experience maximum freeze

**Comment by dts-1990** [comment]
Confirmed the same issue. 
Also, cannot switch audio device, if I try to switch audio device in game, the game hangs.

**Comment by Unkindled1996** [comment]
Same problem with wired headset.
When headset loose connection and I reconnect it, dota2 will not switch audio device automatically, if I change output device in dota2 config，process will stuck and I must kill it with process manager.

**Comment by dts-1990** [comment]
Seems like fixed with latest update

**Comment by hegerj** [comment]
Same issue, Win10. Sound device is not same as rest of the system (when using bluetooth headset), cannot find the dota2 process in Volume mixer and game hangs when trying to quit (has to be killed by Task manager).

**Comment by ofotache** [comment]
Fix for windows:

Disable for both mic and speakers:   "Allow applications to take exclusive control of this device " and "Give exclusive mode applications priority"

**Comment by kisak-valve** [comment]
Closing per @dts-1504's comment.

Hello @hegerj, @ofotache, the way the OS handles Bluetooth on Windows and Linux do not resemble each other. This issue report was tracking a Linux specific audio issue. If you're still having trouble with your headset, please open a new issue report in the [Dota2-Gameplay](https://github.com/ValveSoftware/Dota2-Gameplay/issues) issue tracker for the larger Dota 2 team to ponder.
