### ISSUE TITLE
The "about" for this repo suggests going to dev.dota2.com to report general issues...

### ISSUE THREAD

**Issue by StingyJack** [ValveSoftware/Dota-2#2513]
... but there is also a repo here on GH for the same that could be mentioned too. 

https://github.com/ValveSoftware/Dota2-Gameplay/issues

**Comment by kisak-valve** [comment]
Hello @StingyJack, this is a historical artifact. https://dev.dota2.com redirects to that issue tracker so there isn't a functional problem here.
