### ISSUE TITLE
Constant Freezes/Crashes after Compendium Update

### ISSUE THREAD

**Issue by lfarinha** [ValveSoftware/Dota-2#2514]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 

Computer Information:
Manufacturer: MSI
Model: B250 GAMING M3 (MS-7A62)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU Family: 0x6
CPU Model: 0x9e
CPU Stepping: 0x9
CPU Type: 0x0
Speed: 4500 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Manjaro Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.1.53-1-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230801.56012
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.104.05
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 144 Hz
VendorID: 0x10de
DeviceID: 0x2206
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 27.48" x 15.47" (31.54" diag), 69.8cm x 39.3cm (80.1cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 10240 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC1220
Memory:
RAM: 32065 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 468058 MB
Largest Free Hard Disk Block: 368423 MB
Storage:
Number of SSDs: 3
SSD sizes: 2000G,1000G,500G
Number of HDDs: 0
Number of removable drives: 0

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When playing dota (no matter how much time you have spent in-game) the game will crash. It will take a long time to close the dota 2 window, it will take longer to release the mouse cursor. I noticed the problem is increases whenever I switch virtual desktops (I'm using Manjaro GNOME). Most of the time dota 2 window will not release the cursor to move to a different desktop environmnet. This was not a problem before the compendium patch and my video settings are on Desktop Friendly Full Screen and deactivated the option "Desktop Screen minimizes on focus loss".

The journal is displaying the following issue after the game crashes:

Oct 01 13:05:45 manjaro-msi systemd-coredump[12413]: [🡕] Process 11816 (dota2) of user 1000 dumped core.
                                                     
                                                     Stack trace of thread 11816:
                                                     #0  0x00007f2f411ce414 n/a (libclient.so + 0x4bce414)
                                                     #1  0x00007f2f41194a15 n/a (libclient.so + 0x4b94a15)
                                                     #2  0x00007f2f41198bc0 n/a (libclient.so + 0x4b98bc0)
                                                     #3  0x00007f2f40e03dec n/a (libclient.so + 0x4803dec)
                                                     #4  0x00007f2f41024380 n/a (libclient.so + 0x4a24380)
                                                     #5  0x00007f2f40ed9425 n/a (libclient.so + 0x48d9425)
                                                     #6  0x00007f2f3fcd1865 n/a (libclient.so + 0x36d1865)
                                                     #7  0x00007f2f411b6a17 n/a (libclient.so + 0x4bb6a17)
                                                     #8  0x00007f2f410be3a4 n/a (libclient.so + 0x4abe3a4)
                                                     #9  0x00007f2f40f9e639 n/a (libclient.so + 0x499e639)
                                                     #10 0x00007f2fee5aed22 n/a (libengine2.so + 0x1aed22)
                                                     #11 0x00007f2fee5aed22 n/a (libengine2.so + 0x1aed22)
                                                     #12 0x00007f2fee5b3d1d n/a (libengine2.so + 0x1b3d1d)
                                                     #13 0x00007f2fee5987c9 n/a (libengine2.so + 0x1987c9)
                                                     #14 0x00007f2fee598ba5 n/a (libengine2.so + 0x198ba5)
                                                     #15 0x00007f2fee58cca3 n/a (libengine2.so + 0x18cca3)
                                                     #16 0x00007f2fee592652 n/a (libengine2.so + 0x192652)
                                                     #17 0x00007f2fee59291f Source2Main (libengine2.so + 0x19291f)
                                                     #18 0x000055b909da4e30 n/a (dota2 + 0x3e30)
                                                     #19 0x000055b909da4903 n/a (dota2 + 0x3903)
                                                     #20 0x00007f2ff1c27cd0 n/a (/run/host/usr/lib/libc.so.6 + 0x27cd0)
                                                     ELF object binary architecture: AMD x86-64

#### Steps for reproducing this issue:

1. Open the game
2. Queue for a game
3. After the game lobby is confirmed try to switch between virtual desktops and go back to the game.
4. At some point during the game it will crash

**Comment by kisak-valve** [comment]
Hello @lfarinha, this issue is already being tracked at #2499. Closing as a duplicate.
