### ISSUE TITLE
Match ready sound doesn't work if client doesn't have focus

### ISSUE THREAD

**Issue by rykugur** [ValveSoftware/Dota-2#2515]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [system info](https://gist.github.com/rykugur/9207368bdfe119748891a294fb571069)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

I'm not getting the match ready sound. This started around the same time as the audio issues for the compendium update (where `-sdlaudiodriver pipewire` launch option workaround was required for a few days).

That bug has since been fixed and I've removed the launch option, but I'm still not getting any audio when the match pops if the DOTA2 client doesn't have focus.

As a side note - I did switch from i3wm to bspwm during the same time frame as the `sdlaudiodriver` bug, so am not sure which is causing the problem. I don't think this is the problem, however, as all other audio from the DOTA2 client works fine when out-of-focus; it's _just_ the match ready sound.

As another side note - the match rady notification still shows up fine (via `dunst`), but I don't always see it.

#### Steps for reproducing this issue:

1. Open DOTA2 on a workspace (5 for me)
2. Queue for a match
3. Move to a different workspace
4. Wait for match to be ready
5. No "match ready" audio

**Comment by kisak-valve** [comment]
Hello @rykugur, this issue is already being tracked at #2419. Closing as a duplicate.
