### ISSUE TITLE
Unable to see full game interface when set resolution to the max , macbook pro

### ISSUE THREAD

**Issue by videni** [ValveSoftware/Dota-2#252]
macbook pro, change resolution to max , then the display can only show display part of the game interface, there is no way to set the resolution back for  it is impossible to set the apply button anymore,.

**Comment by ravirahulj** [comment]
I had the same problem on mac book air running reborn beta. After reborn beta loads, go to settings>video>Desktop-friendly fullscreen>apply. It's a chore i have to do everytime to get rid of the issue.

**Comment by gdrewb-valve** [comment]
The next update should fix this.

**Comment by gdrewb-valve** [comment]
Do you still have the problem with the 7/23 update?

**Comment by videni** [comment]
no, it solved , but another problem shows up.I will create another issue.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
