### ISSUE TITLE
Game fails to launch with Wayland sessions

### ISSUE THREAD

**Issue by ca1f** [ValveSoftware/Dota-2#2522]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
  * https://gist.github.com/ca1f/29ada623ad02df65ed3aeb105cb4ed48
* Have you checked for system updates?: [Yes/No]
  * Yes, no updates available.
* Are you using the latest stable video driver available for your system? [Yes/No]
  * Yes, mesa 23.2.1-1 for arch linux
* Have you verified the game files?: [Yes/No]
  * Yes, the problem persists.

#### Please describe your issue in as much detail as possible:
Game client fails to launch after latest update. `CrashID=bp-047f5495-dce2-4d78-9362-3f1112231004`

**Comment by alexeysvrv** [comment]
For me as well. Although if you switch SDL_VIDEO_DRIVER = x11, then everything starts normally. Have you enabled Wayland by default? Finally!!! Just let it start normally, otherwise nothing happens on the screen

**Comment by ca1f** [comment]
> For me as well. Although if you switch SDL_VIDEO_DRIVER = x11, then everything starts normally. Have you enabled Wayland by default? Finally!!! Just let it start normally, otherwise nothing happens on the screen

Yea, launching it with `SDL_VIDEO_DRIVER=x11 %command%` allows the client to start normally. Seems like it's a wayland specific issue then.

**Comment by nsneck** [comment]
ping @icculus seems like SDL3 got updated and the game no longer starts unless explicitly launching with x11, could this be a SDL regression?

**Comment by rpenido** [comment]
Same here. Happened after a Dota 2 update, not a system update.

**Comment by Zer0-One** [comment]
`[ 1302.313677] dota2[23761]: segfault at 0 ip 00007f9e78a33d1b sp 00007fff2771aef0 error 4 in libc.so.6[7f9e78a10000+158000] likely on CPU 15 (core 15, socket 0)`

`[ 1429.728651] cs2[25965]: segfault at 0 ip 00007fd3ea3c1d1b sp 00007ffc86658810 error 4 in libc.so.6[7fd3ea39e000+158000] likely on CPU 11 (core 11, socket 0)`

Segfault occurs for both dota2 and cs2, so it's probably an engine update that broke things.

**Comment by mysticlizard** [comment]
Experiencing this issue as well on Arch linux with Wayland. Running the X11 launch option above seems to workaround the problem for now, thanks for that!

**Comment by denisoct** [comment]
> For me as well. Although if you switch SDL_VIDEO_DRIVER = x11, then everything starts normally. Have you enabled Wayland by default? Finally!!! Just let it start normally, otherwise nothing happens on the screen

Where do I put this `SDL_VIDEO_DRIVER=x11`? I put it in the launch options of dota 2 but the problem still persists

**Comment by gesperon** [comment]
> Where do I put this `SDL_VIDEO_DRIVER=x11`? I put it in the launch options of dota 2 but the problem still persists

you can either launch steam from cmd line, ex: `$ SDL_VIDEO_DRIVER=x11 steam`, then launch Dota normally. Or you can set Dota's "Launch Options" to `SDL_VIDEO_DRIVER=x11 %command%` in steam.

**Comment by sirix123** [comment]
Having the same issue `$ SDL_VIDEO_DRIVER=x11 steam,` worked for me

my system specs:
```
[System]
OS:              Nobara Linux 38 Thirty Eight
Arch:            x86_64
Kernel:          6.5.3-200.fsync.fc38.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           13th Gen Intel(R) Core(TM) i7-13620H
Physical cores:  10
Logical cores:   16

[Memory]
RAM:             15.3 GB
Swap:            16.8 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Graphics (RPL-P)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.8
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.8
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.8
Vulkan Version:  1.3.261
Vulkan Drivers:  Intel(R) Graphics (RPL-P) (1.3.261), NVIDIA GeForce RTX 4060 Laptop GPU (1.3.242)
```

**Comment by icculus** [comment]
> ping @icculus seems like SDL3 got updated and the game no longer starts unless explicitly launching with x11, could this be a SDL regression?

I think it's likely it was eventually using your system's SDL2 library with Wayland support, but this isn't happening now that SDL3 is in place. I'm surprised it isn't at least falling back to XWayland, though.

SDL3 supports Wayland, it's just the build that's shipping with DOTA2 currently doesn't have Wayland support compiled in.

**Comment by alexeysvrv** [comment]
@danginsburg Any idea what's going on?

**Comment by Forage** [comment]
FYI: The same thing occurs when using Steam through Flatpak.

**Comment by pvlopez00** [comment]
Same problem in Debian 12 Bookworm with Wayland session. Workaround works for me as well.

**Comment by mediocretwo** [comment]
Welp, same issue for me on debian 12 w/ Gnome and Wayland. Game tries to launch and crashes. Applying the X11 launch option mentioned above fixed it. Hope its not too big of a problem.

**Comment by jecs** [comment]
Ubuntu 23.04 using Gnome, Wayland, and Nvidia 535 drivers. Confirming that X11 launch options fix the issue. Specifically, I set the Launch Options of Dota 2 to `SDL_VIDEO_DRIVER=x11 %command%` .

**Comment by pchmykh** [comment]
arch, intel cpu, no discrete graphics card, refuses to launch too. Wayland.

**Comment by arturius453** [comment]
Arch today update
Amd gpu 
While launching in wayland window doesnt appear visually, but only in KDE taskbar for a few seconds
`SDL_VIDEO_DRIVER=x11 ` makes window appear and let's me play the game

**Comment by DSDV** [comment]
Can confirm. 
i find it pretty troubling especially since the x11 legacy software is starting to getting removed from modern distros (like eg fedora)

**Comment by pollux78** [comment]
> Can confirm. 
> i find it pretty troubling especially since the x11 legacy software is starting to getting removed from modern distros (like eg fedora) 

Yeah if this keeps happening new users who come over from windows will be very confused of what's going on and will instantly switch back to windows because they think Linux is garbage over a game not launching when they were using Wayland as default but they wouldn't know what that is

**Comment by DSDV** [comment]
i agree :/ 
to be fair windows had / has the same problems when it comes to being blamed (but the advantage that folks don't switch away). 
<sub><sup>[remember when windows had to close its kernel cause everyone blamed them for xp blue screening but it was all the "antiviruses" or same thing with nvidia drivers or printer stuff?`XD ]</sub></sup>

**Comment by Xinayder** [comment]
Can someone confirm if this was fixed on the latest update? Yesterday I couldn't run both CS2 and Dota 2, and now I can play Dota 2.

This is my build info retrieved from `sys_info` console command:

`Build: 9834 (revision 8398282`

**Comment by DSDV** [comment]
Can confirm that it works on wayland again (at least for me) with the latest version as of posting this comment

**Comment by eeyrjmr** [comment]
> Can confirm that it works on wayland again (at least for me) with the latest version as of posting this comment

Same, starting fine here.

**Comment by ca1f** [comment]
Can confirm, the dota2 game client launches just fine again in a wayland session with explicitly setting `SDL_VIDEO_DRIVER=wayland %command%`. Thank you very much for restoring this functionality.

**Comment by alexeysvrv** [comment]
@icculus @kisak-valve @Plagman 
The problem was solved by the developers, using a few small lines of text in an executable bash startup script. Namely, by adding a hardcoded variable SDL_VIDEO_DRIVER=x11. You can see for yourself. Therefore, the variable in the game launch parameters will simply be ignored. I think that as a short-term solution, it is quite reasonable. But I would like not to use crutches, but full-fledged Wayland support. Let the stable branch of the game and the engine be on X for now, and the one being developed can already be transferred to Wayland and provided for testing to ordinary users. It would be just great!
Please, let's develop also in technical terms, and not only in gameplay
![изображение](https://github.com/ValveSoftware/Dota-2/assets/15014747/0723510e-e6ba-400d-8623-a003697e637d)

**Comment by icculus** [comment]
> I think that as a short-term solution, it is quite reasonable. But I would like not to use crutches, but full-fledged Wayland support.

(I'm not a Valve employee, I just work on SDL, but) I 100% agree with this.

**Comment by DSDV** [comment]
> Namely, by adding a hardcoded variable SDL_VIDEO_DRIVER=x11

i hope this is only a workaround. 

Otherwise ill quote myself:
> X11legacy software is starting to getting removed from modern distros (like eg fedora)

**Comment by ca1f** [comment]
> Replying to https://github.com/ValveSoftware/Dota-2/issues/2522#issuecomment-1751101712

This is quite the dirty trick. At least could have done something like 
```bash
export SDL_VIDEO_DRIVER="${SDL_VIDEO_DRIVER:-x11}"
```

**Comment by vuongtuha** [comment]
Is that mean Dota2 anti Wayland? I have multiple DE on the same machine, and i can make game run on X11 easily. But then Wayland...zzz is that reality?

**Comment by pollux78** [comment]
> Is that mean Dota2 anti Wayland? I have multiple DE on the same machine, and i can make game run on X11 easily. But then Wayland...zzz is that reality?

i doubt that very much, they might have problems with sdl under wayland or they dont have the time right now as they focus on bigger things for the game
