### ISSUE TITLE
Crash when clicking on profile history tab

### ISSUE THREAD

**Issue by Xinayder** [ValveSoftware/Dota-2#2530]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Xinayder/9d064f9843d4e1d9e39143983fcde0b2
* Runtime diagnostics: https://gist.github.com/Xinayder/347f96a3ceeef7c74b4e952c5c85acac
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
The game crashes when you open the history tab on your profile to check your match history.

#### Steps for reproducing this issue:

1. Launch game
2. Click on your profile
3. Click on the History tab

This is what I get in dmesg:
```log
[ 3029.625404] traps: dota2[5792] general protection fault ip:7fe5f42b8b17 sp:7ffcbbcee0e0 error:0 in libc.so.6[7fe5f4244000+15a000]
[ 3214.022876] dota2[10279]: segfault at 0 ip 00007fbb7aab8b17 sp 00007ffc58cc8fe0 error 6 in libc.so.6[7fbb7aa44000+15a000] likely on CPU 10 (core 5, socket 0)
[ 3214.022887] Code: df 48 89 74 24 10 48 89 54 24 08 e8 73 eb fe ff 48 8b 74 24 10 48 8b 54 24 08 eb 90 0f 1f 80 00 00 00 00 b9 01 00 00 00 89 e8 <f0> 0f b1 0b 0f 85 d8 00 00 00 48 89 df e8 07 fc ff ff 31 c0 87 03
```
I have a coredump but it's 400MB, where can I upload it?

```
❯ sudo coredumpctl dump dota2 --output coredump.txt
           PID: 11891 (dota2)
           UID: 1000 (alex)
           GID: 1000 (alex)
        Signal: 6 (ABRT)
     Timestamp: Fri 2023-10-06 23:10:41 CEST (6min ago)
  Command Line: $'/MX500/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2' +@panorama_min_comp_layer_dimension 0 -prewarm_panorama +dota_disable_controller_support 1 -vulkan -nojoy -novid -lang english
    Executable: /MX500/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-steam-4ff77cb2be3541f69768de2b8d7768d5.scope
          Unit: user@1000.service
     User Unit: app-steam-4ff77cb2be3541f69768de2b8d7768d5.scope
         Slice: user-1000.slice
     Owner UID: 1000 (alex)
       Boot ID: c9c0022206e6445888e6c036f0b6b61a
    Machine ID: 689a2c9fb99247019c3417df6107b4ac
      Hostname: alexpc
       Storage: /var/lib/systemd/coredump/core.dota2.1000.c9c0022206e6445888e6c036f0b6b61a.11891.1696626641000000.zst (present)
  Size on Disk: 420.0M
       Message: Process 11891 (dota2) of user 1000 dumped core.
                
                Stack trace of thread 11891:
                #0  0x00007fdbf20ac83c n/a (/run/host/usr/lib/libc.so.6 + 0x8e83c)
                ELF object binary architecture: AMD x86-64
```

**Comment by kisak-valve** [comment]
Hello @Xinayder, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Xinayder** [comment]
Here you go: https://gist.github.com/Xinayder/347f96a3ceeef7c74b4e952c5c85acac

**Comment by kisak-valve** [comment]
Thanks, since MangoHUD is in the list of Vulkan layers, that makes this the same issue as #2464. Closing as a duplicate.
