### ISSUE TITLE
Dota 2 grabs audio device directly in Linux ALSA setup

### ISSUE THREAD

**Issue by shadowless388** [ValveSoftware/Dota-2#2537]
* System information from steam: [https://gist.github.com/shadowless388/c92c76eeb430000954fef72d1cd8836c](url)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Starting with the release of this year's Compedium (the initial patch for it), the game grabs the audio device directly, and does not release control of it until the game is closed. This prevents other applications from playing audio while the game is running. Or... if other application is playing audio while the game is started, the game itself will not have audio. In either case, the in-game browser's audio does not work (cannot watch short film contest entries in client).

Steps to reproduce:
1) Open Dota 2 on a linux system with ALSA audio setup
2) Open a browser
3) Attempt to play audio in browser
4) Observe terminal output from browser failing to play audio:
`[4758:4758:1008/012644.343167:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,Device or resource busy`

**Comment by sethdusek** [comment]
Do you have pulseaudio or pipewire installed? 

You can try using one of the following by appending it to your launch options:
-sdlaudiodriver pulse
or:
-sdlaudiodriver pipewire

If you have pipewire installed both will probably work. But I've had issues with the pipewire audio driver (when my game crashes I hear a crackling sound and I can't hear anything else until I kill dota2)

**Comment by shadowless388** [comment]
I would prefer not to install pulseaudio or pipewire. Both of these choices are not replacements for ALSA, but instead add an "ease of use" layer on top of it (I don't understand that selling point honestly - the amount of times I've seen people complain about broken audio specifically from pulse or pipewire in the last few years is crazy). Pulse and pipewire also add latency to audio output. Either of those would be tolerable if I only used the machine to watch youtube or play video games. I play and record guitar, so audio latency is fairly important to me.

**Comment by sethdusek** [comment]
I'm fairly certain you can get acceptable latency with Pipewire (maybe even better than ALSA) since one of the goals of pipewire was to provide low-latency audio (and replace JACK which is used by most professionals)

Anyways you seem to have had this issue ever since the compendium update which pretty much broke audio for everyone on Linux. Those issues have been fixed but your setup seems to be kind of niche so I don't know how long it will take/if it will get fixed. So I guess all I can do is just thumbs-up this issue

**Comment by sylware** [comment]
@shadowless388 you are perfectly right about alsa, it is the only API games should care about as software mixers are hidden behind the alsa-lib via a plugin (jack/pulseaudio1/pulseaudio2/esound/any future or ABI modified software mixer...)

They did deploy a SDL3 alpha build which breaks alsa on dota2/cs2. I don't know why.

I did provide a fix (I have sound with dota2/cs2 with my fixed SDL3) and I am about to improve multi-channel dmix support in SDL3 (I am currently dealing with some xkb stuff, and IRL stuff too).

https://github.com/libsdl-org/SDL/issues/8577

But now dota2/cs2 input is compeletly broken on my system, I have only the left button working. All the other games work.

**Comment by sylware** [comment]
The input bug was an SDL3 bug related to some specific mice.

You can check the SDL issue above I "finished" my code contribution to SDL3 audio alsa support. I have been playing dota2 (and cs2) with alsa dmix multi-channel (aka sharing the audio hardware device among applications, I did a bit of testing setting dmix default up to 8 channels, the max of SDL3 audio).

SDL3 devs have to review/merge/test/publish my code before valve can pick it up.

**Comment by shadowless388** [comment]
I had interest in pursuing this myself previously, however I never found the time. I did end up switching to pipewire to fit the needs of another system. The proper place for this issue would be with SDL anyways.
