### ISSUE TITLE
Scroll wheel way too sensitive

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#254]
I'm not sure if this really fits here and maybe it's just me, but Reborn is completely unplayable for me due to one fact: the scroll wheel which zooms into the scene is way to sensitive.
I use the MMB a lot to drag around the viewport which worked fine in the old Dota2. But with the beta I always zoom into the scene accidentally dramatically reducing my sight and action range. This gets me killed in nearly every team fight.
I looked for an option to turn the zoom feature off entirely, but I couldn't find one. I don't need it. It's a gimmick, not a gameplay feature. But a gimmick that interferes with my viewport navigation a lot.
Sure, I also use edge panning, but in general pressing MMB and dragging is a lot more accurate.
Could the sensitivity please be changed to how it was before Reborn or could you introduce an option for turning off zoom entirely?

EDIT:
After some more research I found the option dota_camera_disable_zoom "1" which I added to my autoexec.cfg. Works around the issue for mre, but maybe a GUI option would still be good. Maybe some more users could state how they experience the new scroll wheel sensitivity. If not, this may be closed.

**Comment by gdrewb-valve** [comment]
Is this still active?

**Comment by gdrewb-valve** [comment]
Closing pending a response that this is still happening.

**Comment by phoerious** [comment]
Hi and sorry for not responding. I got too many mails from this bug tracker over the last few days.
I just tested it and it seems to be fixed. I think you can still end up zooming in when you don't want to, but it's not like that even looking at your scroll wheel does that anymore. I need to turn it at least two or three steps in order to perform a zoom

But honestly, after I reported this bug I simply kept dota_camera_disable_zoom "1" and lived happily ever after. Never thought of this bug again and never missed the zoom feature. And I think I will keep that setting even if the uber-sensitivity issue has been fixed.

**Comment by gdrewb-valve** [comment]
OK, thanks, sounds like this can stay closed.
