### ISSUE TITLE
[Linux] Decode() array index out of range, when spectating

### ISSUE THREAD

**Issue by pfent** [ValveSoftware/Dota-2#255]
The reborn client crashed seemingly random while spectating a game with the in game client

Detailed crash message (as in attached screenshot): 

```
Decode():
CFlattenedSerializer::Decode array index 0 out of range 0 for field C_DOTA_BaseNPC_Creep_Neutral::m_hMyWearables [72]
```

Match in question: (I can provide a match id later on)
![screenshot from 2015-07-22 15-39-05](https://cloud.githubusercontent.com/assets/5686284/8826629/326c6d36-3088-11e5-9e11-8e7d4bda221c.png)

Crash message:
![screenshot from 2015-07-22 15-12-51](https://cloud.githubusercontent.com/assets/5686284/8826237/52a59ef4-3085-11e5-806d-8debafa25a22.png)

Running the reborn client under ArchLinux x64, Gnome 3, Kernel 4.1.2, Nvidia 352.21 on a GTX 750 Ti

A similar bug has been reported on dev.dota2.com: http://dev.dota2.com/showthread.php?t=171472

**Comment by gdrewb-valve** [comment]
Likely not a Mac/Linux issue.

**Comment by pfent** [comment]
Match ID was 1652379188

**Comment by gdrewb-valve** [comment]
Confirmed this on Windows and I've passed this on to the larger team.

**Comment by AllanD** [comment]
I just recieved this message a few moments ago. ( Non-beta Fully Released Reborn )

**Comment by MrFine1** [comment]
Just encountered this problem as well while spectating game 2 of NaVi vs OG in the Manila Major
