### ISSUE TITLE
[Linux] Shading issue with Ember Spirit's fire remnants

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#256]
Ember Spirit's fire remnants look pretty ugly in Reborn. I don't think they're meant to be purple, blue or plain white. To me they look much like there is a calculation error in the fragment shader and color values are clamped at some point.

Here are a few examples:

![Fire Remnant 1](https://cloud.githubusercontent.com/assets/911270/8830906/2ee91256-309f-11e5-84e8-ba133ee15103.png)
![Fire Remnant 2](https://cloud.githubusercontent.com/assets/911270/8830911/33dbea90-309f-11e5-80ba-241bfbb43008.png)
![Fire Remnant 3](https://cloud.githubusercontent.com/assets/911270/8830915/37d01e8c-309f-11e5-95d0-7998c8ece24f.png)

System information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xfc6
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  16006 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2815730 Mb

Installed software:

Recent Failure Reports:

**Comment by danginsburg** [comment]
This is confirmed and is an OpenGL-specific issue.  Investigating.

**Comment by danginsburg** [comment]
This has been fixed.  The fix will be in the next update.

**Comment by danginsburg** [comment]
Confirmed fixed in 7/28 update.  Closing.
