### ISSUE TITLE
[OS X][suggestion] Hosting game autostarted

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#257]
Hi,

I am always hosting a game, and the issue is the game will always auto started without me as Host
intention, I dont think this is good for many reason. One of it is when some troll entering your host and waste your time there or when you want to arrange something, or maybe someone with bad connection that most of the time crash the host.

1.Maybe have a toggle Start Game, where we turned on will auto start while if not even the lobby full will still need host to start the game.
2. Allow banning specific user from entering your lobby from the lobby list.

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux issue you're probably better off raising this on the regular forums.

**Comment by gdrewb-valve** [comment]
Closing non-Mac/Linux issue.
