### ISSUE TITLE
Sound settings don't work

### ISSUE THREAD

**Issue by gluttonyGit** [ValveSoftware/Dota-2#258]
I have really big problem with sound in Dota 2 Reborn.
I have several sound settings like as "Master Sound", "Game Sounds", "Music", "Voice" and "Unit speech".
I don't like music in dota 2 and tried to switch off it by "Music" setting. But this setting doesn't work! I can switch off music using "Game Sounds" setting and after that can't hear important sounds like sound when game search is ready. 

Thx dota 2 developers for second 30 min ban per twenty-four hours in game search. Love u. 

OS X Yosemite 10.10.4

**Comment by budimanjojo** [comment]
This issue are reported in Windows version too so I think this will not be tracked here by Valve

**Comment by gdrewb-valve** [comment]
Yes, this sounds like #239.  The larger team is aware of the issue.
