### ISSUE TITLE
Dead heroes in groups

### ISSUE THREAD

**Issue by teddybee-r** [ValveSoftware/Dota-2#2580]
Fedora Kinoite, Ryzen 2600, RX570 8G, Flatpak Steam

October 6, 2023
*  Fixed several issues with Illusions and hotkeys and control groups

This has fixed my groups not having the correct unit/illusion.  
This has not fixed groups having dead heroes selected inside of them!
**Every game** I have groups filled with dead heroes

Demo mode example 1: Lone Druid.
In my group of LD + Bear I have 4 bears in it. And every bear has a different level when I cycle through them
![image](https://github.com/ValveSoftware/Dota-2/assets/15222466/9891c49b-b72f-4edd-8406-4c1c2095a3f6)
![image](https://github.com/ValveSoftware/Dota-2/assets/15222466/d27155c7-fb85-4ee0-b6ae-2f069fbb70d8)
![image](https://github.com/ValveSoftware/Dota-2/assets/15222466/7f6a5dbc-1540-422c-8baf-98556b966093)
![image](https://github.com/ValveSoftware/Dota-2/assets/15222466/4a0ca01f-e418-4681-8626-d434dc532f54)

Most of the time I cannot reproduce group bugs in demo mode (Naga Siren works perfectly fine in demo mode). Every game is like this groups have dead heroes. I have to rebind them during the game for them to work in that single game. This never saves and always repeats.

This makes me not play heroes like Brood where I have groups for all the possible combos of spiders and brood. I have to rebind on level 20 Naga to include the new illusion. I have to rebind manta illusions to not have dead heroes in them.

I do not use anything to select my hero/creeps outside of groups.
Configuration for 90% of heroes: 
Groups 1-5: 1-5
Groups 6-10: F1-F5
Group 1: Courier
Group 2: Hero
Group 3: Manta + Illusion rune
Group 4: Hero + Manta + Illusion rune
Group 6: Manta Style

The courier is always fine. Everything else is bugged.

Not reproducible in demo mode:
![image](https://github.com/ValveSoftware/Dota-2/assets/15222466/8d3ac3af-e369-4576-8d6c-6cb6ab5e10ab)
This is me pressing 2 in a real game. This happens every time and I can reproduce it every game.

This has been since the compendium Update.

**Comment by bu4ak** [comment]
same issue

**Comment by teddybee-r** [comment]
I think this got fixed? I haven't had dead heroes for 1 or two days now.
