### ISSUE TITLE
[OS X] Desktop-friendly Fullscreen mode does not behave as proper fullscreen app

### ISSUE THREAD

**Issue by mfilej** [ValveSoftware/Dota-2#259]
With the default _Desktop-friendly Fullscreen_ mode, when cmd-tabbing away the game gets minimized to the dock. This is a somewhat cumbersome behaviour for OS X apps (minimizing windows is very unusual).

I don't know if this behaviour is intended or a bug. In case it is intended please take this issue as a suggestion.

In my opinion fullscreen games should work as regular OS X fullscreen apps. In this mode the games get their own Spaces in Mission Control and switching away from them just brings you back to one of your regular Spaces.

I find that games that work as regular fullscreen apps on OS X are more friendly to use and make app switching easier.

**Comment by jeanlain** [comment]
Add me to those who would like to see this issue solved. Prior to the 07/20 update, fullscreen mode behaved properly.

**Comment by gdrewb-valve** [comment]
The behavior of desktop-friendly fullscreen is by-design (and a future update will offer control over the minimization behavior).  You can use exclusive fullscreen mode if you want Reborn to run in true fullscreen.  If you use exclusive fullscreen are you getting the behavior you want?

**Comment by davidef** [comment]
@gdrewb-valve 
Before the last upgrade it was working just fine.
Now no setting works like the fullscreen setting of the old client and reborn earlier beta. 
The game should have it's own space so you can swipe with trackpad/mouse/ctrl+arrow between game / desktop / other fullscreen app.
Or you can use expose (I think apple now call this mission control) and see the fullscreen app on top

**Comment by gdrewb-valve** [comment]
We had to turn off spaces because of a couple of bugs we hit (filed against SDL, #3066).  Otherwise exclusive fullscreen is the same as the old fullscreen.

**Comment by mfilej** [comment]
> You can use exclusive fullscreen mode if you want Reborn to run in true fullscreen. If you use exclusive fullscreen are you getting the behavior you want?

Exclusive fullscreen doesn't let you switch away from the game in any way (that I could find; except for quitting the game altogether).

> We had to turn off spaces because of a couple of bugs we hit (filed against SDL, #3066).

Ok, hoping that it will be able to be brought back at some point. :smile: Thanks for sharing the details!

**Comment by gdrewb-valve** [comment]
Reborn doesn't have control over the Cmd+Tab behavior in exclusive fullscreen (from discussions with the SDL devs apparently the basic event loop is different) so unfortunately that behavior is not going to change any time soon as far as I know.

**Comment by gdrewb-valve** [comment]
Cmd+Tab is covered by #6 and the lack of spaces is covered by #237.  Does this issue still need to be open?

**Comment by mfilej** [comment]
I'm not completely sure what #237 describes, does it cover spaces switching?

If that's the case then I'm happy to wait until upstream bugs get resolved.

**Comment by gdrewb-valve** [comment]
Yes, #237's original issue was the loss of space switching.  Closing.
