### ISSUE TITLE
fantasy rewqards not given?!

### ISSUE THREAD

**Issue by gruianovac** [ValveSoftware/Dota-2#2590]
why havent fantasy rewards been given? the roster will be locked soon ?! 
those levels and rerolls are very important to get immediately, and it is not immediate, it has been a WQEEK

**Comment by kisak-valve** [comment]
Hello @gruianovac, please stop intentionally posting general Dota 2 feedback on Dota-2 issue tracker. This issue tracker (ValveSoftware/Dota-2) is limited to issues that affect the Mac and Linux client of Dota 2, as noted in the first line of the [README.md](https://github.com/ValveSoftware/Dota-2/), and not general game play issues and issues that affect all players. You can use the ValveSoftware/Dota2-Gameplay issue tracker to report those issues.

I will no longer be transferring your issue reports to that issue tracker.

Closing as invalid.
