### ISSUE TITLE
Dota 2 won't launch (Failed to create VKSurfaceKHR.)

### ISSUE THREAD

**Issue by lewisdiamond** [ValveSoftware/Dota-2#2602]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
 https://gist.github.com/lewisdiamond/7b83117f9a1f6681980c208c69200fab
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Launch Dota 2
2. A popup appears reading: CreateSwapChain(): Failed to create VKSurfaceKHR

**Comment by Ori-Pixel** [comment]
Same issue on same Arch Linux kernel. Seems to have happened alongside a dota update around 10pm EST/6Pm PST on 11/15. 

System Gist: https://gist.github.com/Ori-Pixel/68edd1c18aee85db482474f4d2703844

Gist of console output: https://gist.github.com/Ori-Pixel/b86f23bdd542744ef5ee582abffbcc45

Not sure where the dmp file is. If I knew I would throw that in as well

**Comment by polpokpol** [comment]
Me too. Are you using Nvidia? I am guessing it is NVIDIA version 545 recent update.

**Comment by robertkirkman** [comment]
> Me too. Are you using Nvidia? I am guessing it is NVIDIA version 545 recent update.

I have Gentoo GNU/Linux amdgpu amd64 and I have the same exact error after updating game client at 8:00 PM CST

**Comment by stryan** [comment]
Same issue here on AMD cpu/gpu and OpenSUSE Tumbleweed. System spec: https://gist.github.com/stryan/cdd0824f05c34ec52b61d9c8d4e9f49a

**Comment by VladislavNekto** [comment]
Same issue gere, Fedora, AMD cpu/gpu

**Comment by pure-bliss** [comment]
Hopefully some useful information

![2023-11-16_08-12](https://github.com/ValveSoftware/Dota-2/assets/83361786/14412ab1-3736-4426-8120-a2e632ba5eaf)

Not 100% sure that this is same as https://github.com/ValveSoftware/Dota-2/issues/2603, because the message differs

<details>
  <summary>Steam System information</summary>

```
Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: B550M PRO-VDH WIFI (MS-7C95)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4426 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.1.62-1-lts
X Server Vendor: The X.Org Foundation
X Server Release: 12101009
X Window Manager: i3
Steam Runtime Version: steam-runtime_0.20231024.64411
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.49, 6.1.62-1-lts)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77" (23.98" diag), 53.1cm x 29.9cm (60.9cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 15915 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 217026 MB
Largest Free Hard Disk Block: 30916 MB
Storage:
Number of SSDs: 3
SSD sizes: 500G,250G,128G
Number of HDDs: 0
Number of removable drives: 0
```

</details>

<details>
  <summary>journal after clicking "OK" on the dialog:</summary>
  
```
Nov 16 08:10:20 harczos kernel: dota2[4637]: segfault at 0 ip 00007fc7fc577526 sp 00007fffe1d978b0 error 6 in libtier0.so[7fc7fc4bf000+2f3000] likely on CPU 13 (core 5, socket 0)
Nov 16 08:10:20 harczos kernel: Code: 2d c6 f3 24 00 31 db 0f 1f 44 00 00 49 8b 74 dc 08 48 85 f6 74 0a 4c 89 ef 31 c0 e8 84 d8 f4 ff 48 83 c3 01 41 39 1c 24 7f e2 <c7> 04 25 00 00 00 00 00 00 00 00 0f 0b c7 04 25 00 00 00 00 00 00
Nov 16 08:10:20 harczos systemd[1]: Started Process Core Dump (PID 4714/UID 0).
Nov 16 08:10:21 harczos systemd-coredump[4716]: [🡕] Process 4637 (dota2) of user 1000 dumped core.
                                                
                                                Stack trace of thread 4637:
                                                #0  0x00007fc7fc577526 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x177526)
                                                #1  0x00007fc7fc579bd2 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x179bd2)
                                                #2  0x00007fc7fc57a0b0 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x17a0b0)
                                                #3  0x00007fc7d5b90b8a n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x190b8a)
                                                #4  0x00007fc7d5b919c0 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1919c0)
                                                #5  0x00007fc7fae5b8cc n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25b8cc)
                                                #6  0x00007fc7fae5c0dd n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25c0dd)
                                                #7  0x00007fc7d5b6fe42 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x16fe42)
                                                #8  0x00007fc7fb028dda n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x428dda)
                                                #9  0x00007fc7fb029c7d n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x429c7d)
                                                #10 0x00007fc7fae5d382 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25d382)
                                                #11 0x00007fc7fae5d810 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x25d810)
                                                #12 0x00007fc7fad92427 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x192427)
                                                #13 0x00007fc7fad928bf n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so + 0x1928bf)
                                                #14 0x00005600dcfcbe30 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3e30)
                                                #15 0x00005600dcfcb903 n/a (/home/pure_bliss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 + 0x3903)
                                                #16 0x00007fc7fe47dcd0 n/a (/run/host/usr/lib/libc.so.6 + 0x27cd0)
                                                ELF object binary architecture: AMD x86-64
Nov 16 08:10:21 harczos systemd[1]: systemd-coredump@3-4714-0.service: Deactivated successfully.
```

</details>

**Comment by Mozeur** [comment]
Same issus on linux ubuntu 

https://gist.github.com/Mozeur/d875ef53a06c19d56f46746c4ba274c3

**Comment by maulwurst** [comment]
Same issue on Ubuntu studio


https://gist.github.com/maulwurst/68b2601cec9b4df7c13e6e28bbddffcf

**Comment by hinrek** [comment]
Same problem on Fedora 39
https://gist.github.com/hinrek/240d2d540fa3d8bb07cf855c6afa3069
Tried launching from bash to see if anything i could debug
```
...
zenity: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
crash_20231116194919_2.dmp[58819]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231116194919_2.dmp
./dota.sh: line 122: 58773 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20231116194919_2.dmp[58819]: Finished uploading minidump (out-of-process): success = yes
crash_20231116194919_2.dmp[58819]: response: CrashID=bp-5e78ed60-6d41-4875-9300-41f6b2231116
crash_20231116194919_2.dmp[58819]: file ''/tmp/dumps/crash_20231116194919_2.dmp'', upload yes: ''CrashID=bp-5e78ed60-6d41-4875-9300-41f6b2231116''
```
The dump should be uploaded automatically.

**Comment by rmrfchik** [comment]
Same. Debian, NVidia
https://gist.github.com/rmrfchik/6d89142fd7ed89cf30ec2c2f58ad21cc

**Comment by Ghost173** [comment]
same for Ubuntu 23.10

**Comment by hinrek** [comment]
There is a workaround in the other thread that works for me https://github.com/ValveSoftware/Dota-2/issues/2603#issuecomment-1814538522

**Comment by BloodyIron** [comment]
> There is a workaround in the other thread that works for me [#2603 (comment)](https://github.com/ValveSoftware/Dota-2/issues/2603#issuecomment-1814538522)

This appears to have worked for me too.

Ubuntu 23.10
RTX 3060 ti + Driver Blob 545.29.02
Ryzen 5800x

**Comment by Ori-Pixel** [comment]
> There is a workaround in the other thread that works for me [#2603 (comment)](https://github.com/ValveSoftware/Dota-2/issues/2603#issuecomment-1814538522)

Worked for me on flatpak. For those eon flatpak, the directory to CD into is (replace {name} with system name):

cd "/home/{name}/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/"

**Comment by robertkirkman** [comment]
I received [this update](https://steamdb.info/patchnotes/12727035/) at 11:55 PM CST and now the issue is *resolved for me without needing to reapply the workaround*. *Thank you very much Valve for rapid response to this issue!*

**Comment by cdonatom** [comment]
> I received [this update](https://steamdb.info/patchnotes/12727035/) at 11:55 PM CST and now the issue is _resolved for me without needing to reapply the workaround_. _Thank you very much Valve for rapid response to this issue!_

Please, stop saying that, the issue is perhaps resolved for you but not _everyone_
Fedora 39 here, KDE 5.27.9, Vega 56 - Same issue as reported
Steam Deck - SteamOS 3.5.5 - Same issue

**Comment by BloodyIron** [comment]
> > I received [this update](https://steamdb.info/patchnotes/12727035/) at 11:55 PM CST and now the issue is _resolved for me without needing to reapply the workaround_. _Thank you very much Valve for rapid response to this issue!_
> 
> Please, stop saying that, the issue is perhaps resolved for you but not _everyone_ Fedora 39 here, KDE 5.27.9, Vega 56 - Same issue as reported Steam Deck - SteamOS 3.5.5 - Same issue

The text you quoted explicitly says "resolved FOR ME". So they already make the distinction you ask for. 🙄

**Comment by Ghost173** [comment]
> I received [this update](https://steamdb.info/patchnotes/12727035/) at 11:55 PM CST and now the issue is _resolved for me without needing to reapply the workaround_. _Thank you very much Valve for rapid response to this issue!_

after the update its works for me

**Comment by kisak-valve** [comment]
Closing as fixed.
