### ISSUE TITLE
[dota2+steam overlay] input system broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#2605]
Many buttons in the steam overlay cannot be clicked anymore.

Same in dota2, for instance once you picked a hero, the mini-shop icons (wards/tangos/etc) won't respond to clicks. Luckily my game was safe to leave...

**Comment by kisak-valve** [comment]
Possibly related to https://github.com/ValveSoftware/csgo-osx-linux/issues/3567.

**Comment by sylware** [comment]
I have only the left mouse button which seems to work as expected, all the other buttons are ignored, at best weird, and if I use the keyboard for some commands dota2 will randomly crash, like even starting the overlay.

In the mini-shop after hero selection, I have to right click on a item, maintain it, then left click to buy it.

The game is broken, seems input related (original libSDL3 with alsa bug restored via file integrity check)

Nothing were changed on my system before the game breaks.

**Comment by tilman3** [comment]
I believe this is caused by https://github.com/libsdl-org/SDL/issues/8611. Running dota2 with a patched libSDL3 fixes the problem.

**Comment by sylware** [comment]
@tilman3

Thx, I'll have a look into that but a bit later. But it seems that my keyboard is alsa spitting tons of things confusing SDL3 too.

**Comment by tilman3** [comment]
If you are seeing this problem with X11, then switching from  xorg-input-evdev to xorg-input-libinput may fix the problem as well.

**Comment by tilman3** [comment]
Finally, one more workaround for the referenced SDL issue, which may or may not help with this one:
ensure the X11 atom "Abs Pressure" exists before dota2 starts. One low-tech way to do so is to run the following C program ;)

```
#include <stdlib.h>
#include <X11/Xlib.h>

int main(int argc, char **argv)
{
	Display *disp = XOpenDisplay(getenv("DISPLAY"));
	XInternAtom(disp, "Abs Pressure", False);
}
```

**Comment by sylware** [comment]
Got your fix code straight from git SDL3.

It seems fixed. THX!

I will play some dota2 later for more testing (I am currently doing a bit of debugging of some fixes and improvement of sdl audio alsa code).

I don't think expecting the specific filtering/device aggregation of libinput to have SDL3 input to work on x11 is reasonable. I think the xserver does this mouse/keyboard device aggregation with its virtual(core?)mouse/keyboard. Without that, some (a lot?/a few?) keyboard/mouse out there will break. In the end, for those reasons I don't think libinput would fix anything.

**Comment by sylware** [comment]
Played a game without input issue (and with sound on alsa[dmix])

I guess once the next dota2/cs2 SDL3 update is done from git, we can close this one.

**Comment by sylware** [comment]
I have been playing dota2 with alsa multi-channel dmix using my code (modulo a critical "pressure-vessel" bug, is this open source? can I fix that bug myself? Cannot find source code anywhere). Waiting for SDL3 devs to review/test and merge it in git SDL3.

**Comment by ToxinG** [comment]
Yes, I have the same problem =(

BUT 

You can use the Tab key to select buttons consequently and then Enter to "press" the desired one ;)

**Comment by kisak-valve** [comment]
Per the note at https://github.com/ValveSoftware/csgo-osx-linux/issues/3567#issuecomment-1832215414, please opt into Steam's client beta and retest.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-11-29](https://store.steampowered.com/news/app/593110/view/3895113407856183761) Steam client update.
