### ISSUE TITLE
Can not buy dota plus, buttons not working in steam overlay

### ISSUE THREAD

**Issue by lazarcf** [ValveSoftware/Dota-2#2606]
#### Your system information

Computer Information:
Manufacturer: LENOVO
Model: 20N2000RRI
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU Family: 0x6
CPU Model: 0x8e
CPU Stepping: 0xc
CPU Type: 0x0
Speed: 4600 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.6.1-arch1-1
X Server Vendor: The X.Org Foundation
X Server Release: 12101009
X Window Manager: i3
Steam Runtime Version: steam-runtime_0.20231024.64411
Video Card:
Driver: Intel Mesa Intel(R) UHD Graphics 620 (WHL GT2)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 49 Hz
VendorID: 0x8086
DeviceID: 0x3ea0
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3440 x 1440
Primary Display Size: 31.50" x 13.39" (34.21" diag), 80.0cm x 34.0cm (86.9cm diag)
Primary VRAM Not Detected
Sound card:
Audio device: Realtek ALC257
Memory:
RAM: 15653 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 236899 MB
Largest Free Hard Disk Block: 9874 MB
Storage:
Number of SSDs: 1
SSD sizes: 256G
Number of HDDs: 0
Number of removable drives: 0

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

When I go to buy Dota Plus I can't click any buttons in the steam overlay and I can't buy it outside the client as far as I can see.

**Comment by pchmykh** [comment]
Same here, Fedora linux, flatpak steam. Can't buy items too.

**Comment by kisak-valve** [comment]
Hello @lazarcf, this issue is already being tracked at #2605. Closing as a duplicate.
