### ISSUE TITLE
dota 2 is not runing at all in my windows 11

### ISSUE THREAD

**Issue by Hos3ein3** [ValveSoftware/Dota-2#2611]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* https://gist.github.com/Hos3ein3/a393846bf89dc2b14053b4c9c65c8a1e
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Dota 2 is not runing at all from last time, and show me this error : an error occurred while running Dota2.exe and direct me to this github 
I already search the github for an answer  but couldnt find anything.

**Comment by kisak-valve** [comment]
Hello @Hos3ein3, this issue tracker is limited to issues with the Mac and Linux client of Dota 2.

Your previous issue report was transferred to https://github.com/ValveSoftware/Dota2-Gameplay/issues/13655 for the larger Dota 2 team to ponder.

Closing as a duplicate.
