### ISSUE TITLE
[LINUX] borderless window doesn't lock cursor (Wayland - kWin)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#2612]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/RickStanley/4bfa034814adbb49ca0fab31072e87f3
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I'm trying to play the game in window borderless mode, on KDE Plasma - Wayland session.

![grafik](https://github.com/ValveSoftware/Proton/assets/142456149/0ded1ee8-39a8-467b-95fe-28b5a3559f07)

The top bar is shown and the mouse's cursor is not trapped inside the window. The panel is not hidden, but if the cursor could be locked inside the game's window, I could easily hide the panel from its settings and let it be.

There was a similar issue reported here: https://github.com/ValveSoftware/Dota-2/issues/1056, but I think that the conclusion were that the was running on Wayland and at the time Wayland didn't have a protocol for pointer constraint. I made a quick research and I found out that now it has a standard protocol, and the major environments implement it: https://wayland.app/protocols/pointer-constraints-unstable-v1#zwp_pointer_constraints_v1:request:lock_pointer

I'm:

- using the native version;
- using 1 monitor;

<details>
<summary>System</summary>

    Operating System: EndeavourOS 
    KDE Plasma Version: 5.27.9
    KDE Frameworks Version: 5.112.0
    Qt Version: 5.15.11
    Kernel Version: 6.6.1-arch1-1-g14 (64-bit)
    Graphics Platform: Wayland
    Processors: 16 × AMD Ryzen 9 6900HS with Radeon Graphics
    Graphics Processor: AMD Radeon Graphics
    Dedicated GPU: NVIDIA RTX 3060
</details>

#### Steps for reproducing this issue:

1. Launch Dota 2;
2. go to settings -> graphics;
3. select borderless window;
4. apply;
5. see panel (any Plasma panel) on top of the game's window;
6. move cursor out of window;
7. see pointer/cursor hover the top bar.

**Comment by sylware** [comment]
To let an application decides to lock on itself the mouse cursor is not meant for wayland core for obvious reasons.

It means that SDL3 has to query for the wayland interface and has to tell the application code (dota2/cs2/etc) if that's not possible in order to let it tell its user: "I walk on all your other GUI applications and keep mouse the cursor for myself" (this is humor, no personal offense intended).

The SDL3 guys need to be told about this to ensure their "pointer grab" API, if any, can let the application code know.

**Comment by sylware** [comment]
https://github.com/libsdl-org/SDL/issues/8594

**Comment by YoyPa** [comment]
The game correctly lock the pointer inside the window for me (kwin wayland / dota xwayland). Have you tried in "demo hero" mode? The game only lock cursor if you are in game, it's expected to have free cursor on the main menu.

**Comment by ghost** [comment]
@YoyPa

Thanks for the suggestion, I just tried it, and learned a few things:

![grafik](https://github.com/ValveSoftware/Dota-2/assets/142456149/0ba203e8-59eb-497d-9e35-c77139372550)

You can see the cursor on the top-right corner, hovering over a panel action and closing in to a hot corner. I have hot corners set up in KDE, so any attempt to move the cursor the corners, trigger the action.

In this instance, the game was launched with: `gamemoderun %command% -novid`.

Now, removing `gamemoderun %command%` and leaving only `-novid`, in borderless window mode, traps the cursor in-game.

But the problem is, is that the top panel takes the space and the game window is moved down, rendering in-game pan to bottom with the game's cursor impossible, unless you use the directional arrows from the keyboard.

Next, I tried to hide the panel through Plasma settings, but somehow the cursor escapes from within the game's window and calls the panel back to reveal: 

![grafik](https://github.com/ValveSoftware/Dota-2/assets/142456149/866fe371-5005-47f9-bfa6-e14b97b327f6)

and now pan to top not possible.

Then, I tried to put Plasma's panel back to its original position, but the cursor, again, escapes:

![grafik](https://github.com/ValveSoftware/Dota-2/assets/142456149/7a672144-f9f6-4952-a3bc-fd81f8046a2b)

And finally, I tried to reduce the resolution a bit, but the cursor once more escapes from the bottom of the window.


You say that it's running xWayland for you, and I've seen somewhere between the issues of this repository that the game indeed launches with the SDL option to run with x11, but my game doesn't not show when I issue the `xlsclients` command in the terminal, only steam shows up, event with `gamemoderun` removed. (Actually, I don't remember why I put `gamemode` there, but I'm going to remove it anyway.)

**Comment by YoyPa** [comment]
If you put the game in windowed mode your panel will get over it like any window. Why not fullscreen mode (could help with hot corner too)?
If you want your panel above/below your dota window, you can get a specific size with options ```-h``` and ```-w``` like ```gamemoderun %command% -novid -h 1080 -w 2560``` (you can get panel exact pixel size when editing it).
Tip: you can see more of the game left and right by changing ratio like 21:9 or 32:9, view can get stupidly huge ^^.

**Comment by ghost** [comment]
>  If you want your panel above/below your dota window, you can get a specific size with options -h and -w like gamemoderun %command% -novid -h 1080 -w 2560 (you can get panel exact pixel size when editing it).

Thanks, I'll try it. 

> If you put the game in windowed mode your panel will get over it like any window.

I didn't know that this behaviour is to be expected.

> Why not fullscreen mode [...]?

There are 2 issues that I just don't bother to report:

1. for some reason, when I alt+tab, the top panel stays on top of the game, it doesn't happen **that** often but happens, the only way to fix is to relaunch the game;
2. also for some reason, fullscreen stutters from time to time, this may be a product of: kWin + Nvidia + Wayland, I can not say for sure;

Both of these are not game breaking for me, fortunately. I found out that by playing in windowed mode the stutters disappears, and I expected the top panel to be behind the game window (too much Windows OS in my past, heh).

**Comment by ghost** [comment]
I'm inclined to close this. It doesn't seem to be a Dota 2 problem specifically.

**Comment by YoyPa** [comment]
Expected behaviour by default*
![Screenshot_20231121_192315](https://github.com/ValveSoftware/Dota-2/assets/29115747/52211582-0196-4028-93d8-c1bacf891a1c)

**Comment by ghost** [comment]
Oh my, I missed this: you can assign a shortcut to enter fullscreen mode, in KDE Plasma, by going to `System settings` -> `Shortcuts` -> `KWin` (or search for fullscreen). I assigned my to Alt + F11 and now borderless fullscreen behaviour like Windows.

One another note: indeed, the settings doesn't explicitly say that it's going to be borderless **fullscreen**, I didn't pay attention to this. Some games have some kind of hint like "(fullscreen)" to indicate that the game will request it.
