### ISSUE TITLE
[Linux] Cannot launch Dota 2 on Ubuntu 23.10

### ISSUE THREAD

**Issue by kwaark** [ValveSoftware/Dota-2#2645]
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
https://gist.github.com/kwaark/2f328288abc7b9348957fb8e9edc44f8

https://gist.github.com/kwaark/0ffe369d95030111a01e32f918e385a7

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:

Trying to open dota 2 and get this error:
https://gist.github.com/kwaark/b4909eef6cc9d010ce66ac2dbd484a28

- Yesterday i play normally

#### Steps for reproducing this issue:

1. Open Steam
2. Start the game Dota 2
3. The game doesn't open or nothing happens when I try to run it.

**Comment by kisak-valve** [comment]
Hello @kwaark, this is the same issue as https://github.com/ValveSoftware/steam-runtime/issues/640. Closing as a duplicate.
