### ISSUE TITLE
Every time i start steam it downloads same update

### ISSUE THREAD

**Issue by Blu3cr0ss** [ValveSoftware/Dota-2#2646]
#### Your system information

* [System information from steam](https://gist.github.com/Blu3cr0ss/e30e8909b28144392b0a4cb9bc3f0183)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Every time i start steam it tries to download same 1.4gb update
Possibly its because i start steam with -udpforce option (Because of [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/10297))
![image](https://github.com/ValveSoftware/Dota-2/assets/49835293/33228409-e795-4732-8d29-3f5578514df5)
#### Steps for reproducing this issue:
1. run `steam -udpforce`

**Comment by kisak-valve** [comment]
Hello @Blu3cr0ss, this is an issue with the Steam client, not the Dota 2 client, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8076 / https://github.com/ValveSoftware/steam-for-linux/issues/10285.

Closing as a duplicate.
