### ISSUE TITLE
[Linux] Game will not launch (Dota logo flickers)

### ISSUE THREAD

**Issue by PHLAK** [ValveSoftware/Dota-2#2654]
#### Your system information

* System information from steam: https://gist.github.com/PHLAK/bf24d7f77c3c5d9b939bce8c0ecd65c9
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When attempting to run the game the Dota logo appears then it just flickers and nothing else happens until I forcefully kill the process.

[Here are logs for a failed run](https://gist.github.com/PHLAK/c58c34e1307d4ac13d7013550aca743e)

#### Steps for reproducing this issue:

1. Install [Steam](https://archlinux.org/packages/multilib/x86_64/steam/) via the Arch repositories
2. Install Dota 2
3. Attempt to run Dota 2 (native, not with Proton)

**Comment by fanzfan** [comment]
Same issue on Mac.

**Comment by jn64** [comment]
FWIW it's working with Fedora 38 / X11. Here's my system info in case it helps find the difference. https://gist.github.com/jn64/58c5fd0aba2fe0a3deb79b703a87e194

**Comment by PHLAK** [comment]
I was able to get it working by adding `-vulkan` to the launch options.

However, I'm still getting occasional crashes, particularly when I <kbd>Alt</kbd> + <kbd>Tab</kbd> away and refocus the game.
