### ISSUE TITLE
[linux] fullscreen reverts to windowed when switching to another desktop

### ISSUE THREAD

**Issue by jakeprobst** [ValveSoftware/Dota-2#2656]
#### Your system information

* System information from steam: https://gist.github.com/jakeprobst/5f50201b6858db92f9c7aae0dea53ae6
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When switching to another desktop from full screen dota, and then back, it becomes windowed.
This applies to both borderless window and desktop-friendly fullscreen.
This worked fine before the dragon's gift update.
Going back into settings and reapplying the video settings will return it to fullscreen (until I leave it again).

#### Steps for reproducing this issue:

1. Open dota
2. switch to another desktop
3. switch back to dota
4. dota is now in windowed mode

**Comment by jakeprobst** [comment]
I put `+map_enable_background_maps 0` in my launch options and it seems to have fixed this problem.
Alternatively, an update rolled out that I didn't notice that fixed this and my putting that in the config was a coincidence.

either way this is fixed.

**Comment by jakeprobst** [comment]
Well it seems that upon trying to play dota again, this problem is back.
Either the previous time that it worked was a total fluke or there was another update that broke it again.

**Comment by jakeprobst** [comment]
I was hoping the fix mentioned in https://github.com/ValveSoftware/Dota-2/issues/2657#issuecomment-1958447672 would solve this, but does not seem to be the case.

**Comment by jakeprobst** [comment]
crownfall patch has fixed this

**Comment by icculus** [comment]
Hey, so this is something that, if it were to pop up again, we would deal with in [SDL](https://github.com/libsdl-org/SDL/issues), since DOTA2 doesn't deal with these sort of issues directly, but rather uses SDL to isolate itself from them. Come see us over there if the problem pops up again!

**Comment by jakeprobst** [comment]
good to know!
