### ISSUE TITLE
[Fedora Gnome] Alt-tab crashes the game since Dragon's Hoard update.

### ISSUE THREAD

**Issue by richterlevania3** [ValveSoftware/Dota-2#2657]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
* Computer Information:
```
Manufacturer: ASUSTeK COMPUTER INC.
Model: TUF GAMING X570-PLUS_BR
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5800X 8-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4850 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Fedora Linux 39 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.7.3-200.fc39.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12302004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20240123.75011
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.7.3-200.fc39.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.3.5
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 74 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1080
Desktop Resolution: 2560 x 1080
Primary Display Size: 31.50" x 13.39" (34.21" diag), 80.0cm x 34.0cm (86.9cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 15889 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 236922 MB
Largest Free Hard Disk Block: 181393 MB
Storage:
Number of SSDs: 4
SSD sizes: 4000G,2000G,250G,0B
Number of HDDs: 0
Number of removable drives: 0
```

```
Too long to post here. If asked I will get a pastebin.

```
* Have you checked for system updates?: [Yes/No] YES
* Are you using the latest stable video driver available for your system? [Yes/No] YES
* Have you verified the game files?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:

Since the last update, the game crashes when Alt-tabbing. Running the game through Gamescope fixes it, but the top-bar from Gnome is visible, so it's not a good solution. Running the game using Proton with Directx11 fixes it, but the game sometimes won't register the Accept Match button, causing me to gain an abandon status and matching disabled.

#### Steps for reproducing this issue:

1. Launch Dota 2 through Steam using native linux version, no Gamescope or other additional arguments.
2. Alt-tab to another window. The game will freeze at this point
3. Alt-tab back to Dota 2. The game will close after some seconds.

**Comment by reDBo0n** [comment]
Can confirm, happens also on Arch with Gnome Desktop

**Comment by pchmykh** [comment]
Can confirm on Fedora, crashes every time D:

**Comment by richterlevania3** [comment]
Just an addendum: the game doesn't crash when in windowed mode.

**Comment by danisztls** [comment]
This started occurring after the Dragon's Gift update. I don't think Alt+Tab matters at least not for me. I'm on Arch Linux and Gnome Shell. I confirm that switching to windowed mode and relaunching the game works.

**Comment by danisztls** [comment]
Also this doesn't happen with GNOME on Xorg, it  appears to be exclusive to Wayland (_again the gift keeps on giving_).

**Comment by sethdusek** [comment]
> Also this doesn't happen with GNOME on Xorg, it appears to be exclusive to Wayland (_again the gift keeps on giving_).

This happens to me on KDE plasma on X.org as well, anything that causes application to lose focus seems to crash the game, including alt-tabbing, getting steam notifications with overlay disabled, or even volume controllers.

I will try launching the game in nested mode using gamescope, that might prevent this. I'll comment here if that works as a fix

**Comment by danisztls** [comment]
> > Also this doesn't happen with GNOME on Xorg, it appears to be exclusive to Wayland (_again the gift keeps on giving_).
> 
> This happens to me on KDE plasma on X.org as well, anything that causes application to lose focus seems to crash the game, including alt-tabbing, getting steam notifications with overlay disabled, or even volume controllers.
> 
> I will try launching the game in nested mode using gamescope, that might prevent this. I'll comment here if that works as a fix

Interesting. So we have two different issues causing crashes on similar systems and with somewhat similar workarounds. I wonder how related they are.

**Comment by danisztls** [comment]
For comparison, where I experience #2659 but not this one:

[steam-hardware-report.txt](https://github.com/ValveSoftware/Dota-2/files/14229367/steam-hardware-report.txt)
[steam-native.txt](https://github.com/ValveSoftware/Dota-2/files/14229389/steam-native.txt)

**Comment by AngryPenguinPL** [comment]
> Also this doesn't happen with GNOME on Xorg, it appears to be exclusive to Wayland (_again the gift keeps on giving_).

Nah, crashing for me on Gnome Xorg on OpenMandriva.

**Comment by light-on-shadow** [comment]
It is extremely annoying, no matter the window mode.

**Comment by pchmykh** [comment]
Not actually annoying here, just make gaming impossible, a short (hopefully short) brake from DOTA? :)

**Comment by lostpolaris** [comment]
+1 KDE Wayland on Endeavour

**Comment by ArabDuckDuck** [comment]
Have same problem.
System info: 
### Computer Information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: B650M AORUS ELITE AX ICE
Form Factor: Desktop
No Touch Input Detected
### Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 7700 8-Core Processor
CPU Family: 0x19
CPU Model: 0x61
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 5389 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
### Operating System Version:
Fedora Linux 39 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.7.4-200.fc39.x86_64
X Server Vendor: The X.Org Foundation
(echo $XDG_SESSION_TYPE
wayland)
X Server Release: 12302004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20231127.68515
### Video Card:
Driver: AMD AMD Radeon RX 6600 (radeonsi, navi23, LLVM 17.0.6, DRM 3.57, 6.7.4-200.fc39.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.3.5
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 164 Hz
VendorID: 0x1002
DeviceID: 0x73ff
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3000 x 1920
Primary Display Size: 23.62" x 12.99" (26.93" diag), 60.0cm x 33.0cm (68.4cm diag)
Primary VRAM: 8192 MB
### Memory:
RAM: 31825 Mb
### Dmesg message after crash:
`dota2[20547] general protection fault ip:7ff5191cb570 sp:7ffd5392e800 error:0 in libvulkan_radeon.so[7ff519085000+46a000]`

**Comment by pchmykh** [comment]
Anyone have some workarounds? It's already passed a week impossible to play.

**Comment by Qustio** [comment]
Archlinux zen-kernel gnome on wayland same problem
```
Computer Information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: B360M H
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
CPU Family: 0x6
CPU Model: 0x9e
CPU Stepping: 0xa
CPU Type: 0x0
Speed: 4000 MHz
6 logical processors
6 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.7.4-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12302004
X Window Manager: GNOME Shell
Steam Runtime Version: <Runtime disabled>
Video Card:
Driver: AMD AMD Radeon RX 6600 (radeonsi, navi23, LLVM 16.0.6, DRM 3.57, 6.7.4-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.3.5-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73ff
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 23.62" x 13.39" (27.13" diag), 60.0cm x 34.0cm (68.9cm diag)
Primary VRAM: 8192 MB
Sound card:
Audio device: Realtek ALC887-VD
Memory:
RAM: 15924 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: ru_RU.UTF-8
Total Hard Disk Space Available: 468231 MB
Largest Free Hard Disk Block: 171183 MB
Storage:
Number of SSDs: 3
SSD sizes: 500G,500G,240G
Number of HDDs: 0
Number of removable drives: 0

```

**Comment by Qustio** [comment]
Found workaround: after switching from MESA to AMDVLK driver, game stops crashing.
Can someone reproduce this bug on AMDVLK?

**Comment by pchmykh** [comment]
> Found workaround: after switching from MESA to AMDVLK driver, game stops crashing. Can someone reproduce this bug on AMDVLK?

I am plaiying without discrete GPU at all, is there some workaround in my case?

**Comment by reDBo0n** [comment]
> Found workaround: after switching from MESA to AMDVLK driver, game stops crashing. Can someone reproduce this bug on AMDVLK?

Can confirm, I couldn't reproduce the ALT-TAB crash after installing the AMDVLK package.

**Comment by reDBo0n** [comment]
Right now came a mesa update on Arch, and the crash seems to be fixed

**Comment by formidabilus** [comment]
same here(the problem, not the fix) with Fedora 39, Wayland and Nvidia, when changing focus from dota2, game crashes at random times.

**Comment by pchmykh** [comment]
> > Found workaround: after switching from MESA to AMDVLK driver, game stops crashing. Can someone reproduce this bug on AMDVLK?
> 
> Can confirm, I couldn't reproduce the ALT-TAB crash after installing the AMDVLK package.

How to install one?

**Comment by n0rc** [comment]
> Right now came a mesa update on Arch, and the crash seems to be fixed

@formidabilus Which Mesa version in Arch fixed the crashes for you – v24.0.1? And which version did you use when it crashed?

I see many people reporting crashes with Mesa v23.3.5 right now but I'm still running v23.1.9. and don't have any crashes at all (with Wayland and RADV on NixOS).

**Comment by richterlevania3** [comment]
Tested with 23.3.5, 23.3.1 and 24.0.1. 24.0.1 admittedly crashes less, but it still happens.

Also, I noticed my GPU fan spins up when it crashes and the GPU temp goes up, too, suggesting some kind of overload.

**Comment by reDBo0n** [comment]
> > Right now came a mesa update on Arch, and the crash seems to be fixed
> 
> @formidabilus Which Mesa version in Arch fixed the crashes for you – v24.0.1? And which version did you use when it crashed?
> 
> I see many people reporting crashes with Mesa v23.3.5 right now but I'm still running v23.1.9. and don't have any crashes at all (with Wayland and RADV on NixOS).

Updated to 24.0.1 and got not crashes so far, but to be fair I've only played a bit of a private bot lobby, because the crashes only happened after I ALT-TABed during the game, which didn't happened anymore

**Comment by formidabilus** [comment]
> Which Mesa version

I was referring on the problem "same here", not on the fix, I'm having Fedora 39 with Wayland and Nvidia, not Intel, the problem persists for me.

**Comment by pchmykh** [comment]
Is there some way to make it visible to devs? More than week unplayable :(

**Comment by danginsburg** [comment]
> Is there some way to make it visible to devs? More than week unplayable :(

Sorry for the lack of response.  I was having difficulty reproducing this last week on Wayland or X on my dev machines.  I shipped a speculative fix on Friday, but it appears it didn't work.  I setup a new box with Fedora 39 and am now able to repro it.  I'll aim to get it fixed on Monday.  As pointed out in another thread, it appears we are sending an invalid VkSemaphore after the swapchain goes out-of-date.  I'm not sure how that's happening yet, but I'll figure it out.  Vulkan WSI is fun.

**Comment by rezad1393** [comment]
I have steam flatpak with wayland kde on archlinux and since the last update (the girly costumes for Chinese new year) I have the same issue.

hardware:
DE: KDE Plasma 5.27.10
WM: KWin (Wayland)
CPU: AMD Ryzen 7 5700U (16) @ 4.37 GHz
GPU: AMD Radeon R9 M275


another hint :
 before that update, when I alt-tab from dota in full-screen then **sometimes** it would no longer be full-screen 
 and  other apps are could be raised over dota screen and I would had to go to video option in dota and click apply again so that dota would be correctly full screen again and other apps won't be raised over it.

after that update that happens everytime.

**Comment by kompolompo** [comment]
Same problem constant freeze when alt+tab /minimize using flatpak steam for a week, moved away yesterday from flatpak. Works better now with amdvlk, thanks for writing a somewhat workaround.

<details><summary>Computer Information:</summary>

```
Manufacturer: Gigabyte Technology Co., Ltd.
Model: B550M DS3H
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4950 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"CachyOS" (64 bit)
Kernel Name: Linux
Kernel Version: 6.7.5-2-cachyos
X Server Vendor: The X.Org Foundation
X Server Release: 12302004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20231127.68515
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 16.0.6, DRM 3.57, 6.7.5-2-cachyos)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.1-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.62" x 13.39" (27.13" diag), 60.0cm x 34.0cm (68.9cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 31988 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 976454 MB
Largest Free Hard Disk Block: 413642 MB
Storage:
Number of SSDs: 4
SSD sizes: 300G,240G,0B,0B
Number of HDDs: 0
Number of removable drives: 0
```

</details>

**Comment by danginsburg** [comment]
I've checked in a fix for the ALT-TAB crash.  It will be fixed in the next Dota 2 client update.  Again, sorry for the delay, I needed to setup a new system to reproduce it (it only happened if WSI returned VK_SUBOPTIMAL_KHR on ALT-TAB).

**Comment by richterlevania3** [comment]
> I've checked in a fix for the ALT-TAB crash. It will be fixed in the next Dota 2 client update. Again, sorry for the delay, I needed to setup a new system to reproduce it (it only happened if WSI returned VK_SUBOPTIMAL_KHR on ALT-TAB).

Do you have an ETA for this update?

**Comment by reDBo0n** [comment]
> I've checked in a fix for the ALT-TAB crash. It will be fixed in the next Dota 2 client update. Again, sorry for the delay, I needed to setup a new system to reproduce it (it only happened if WSI returned VK_SUBOPTIMAL_KHR on ALT-TAB).

Interesting to hear what the real culprit is.

Let's hope the update runs smoothly

**Comment by pchmykh** [comment]
> I've checked in a fix for the ALT-TAB crash. It will be fixed in the next Dota 2 client update. Again, sorry for the delay, I needed to setup a new system to reproduce it (it only happened if WSI returned VK_SUBOPTIMAL_KHR on ALT-TAB).

Bless you dear sir! :)

**Comment by richterlevania3** [comment]
Just a heads-up, the bug is still present.

**Comment by n0rc** [comment]
> Just a heads-up, the bug is still present.

Of course, because the client update isn't live yet, is it?

**Comment by mozolam** [comment]
I can confirm that it doesn't crash anymore since last patch.

**Comment by richterlevania3** [comment]
> I can confirm that it doesn't crash anymore since last patch.

Which update? There has been two or three, but it hasn't solved it for me.

**Comment by mozolam** [comment]
At about half an hour ago.

**Comment by danginsburg** [comment]
Yes, we just shipped the update with the fix.

**Comment by richterlevania3** [comment]
I was in-game when it deployed. It looks like it's fixed. Need to play a match to be sure.

**Comment by richterlevania3** [comment]
> I was in-game when it deployed. It looks like it's fixed. Need to play a match to be sure.

Looks like it was fixed. I will close the issue now. Thank you, Valve.
