### ISSUE TITLE
[linux][alsa] pcm and card setting

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#266]
With alsa, for sound output, for a card, we should be able to select the pcm.
For instance the "default" pcm for card 0 (should replace 0 with the full name), or surround51 for card 1, etc.

**Comment by gdrewb-valve** [comment]
Reborn uses SDL so we show whatever SDL enumerates.

**Comment by sylware** [comment]
It seems SDL2 should combine all PCMs with card/subdev and let games enumerate all those combinations (with the default PCM as the prefered/first choice).

**Comment by gdrewb-valve** [comment]
I'll check with the SDL devs.

**Comment by gdrewb-valve** [comment]
The current release should enumerate many more ALSA options, is that working for you?

**Comment by sylware** [comment]
Tons of alsa options, indeed (Alsa dev nodes are set in "pulse" unix group, then I had to add the steam user to pulse unix group).
Is this code going into the steam client for steam voice?

**Comment by gdrewb-valve** [comment]
The Steam client doesn't use SDL so the work doesn't directly translate.  You can open a feature request in the steam-for-linux repo.
