### ISSUE TITLE
Dota crashes at start when using Wayland

### ISSUE THREAD

**Issue by LostinSpacetime** [ValveSoftware/Dota-2#2663]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
[https://gist.github.com/LostinSpacetime/389f411bef77ee2f1ea3c88dc0af73da]( https://gist.github.com/LostinSpacetime/389f411bef77ee2f1ea3c88dc0af73da)

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Start a Wayland session on Linux (Fedora 39)
2. Start Dota
3. After a few seconds, Dota crashes (most of the time)

When using a Xorg session, Dota starts as expected.

**Comment by DashieTM** [comment]
Does that also happen when commenting out the forcing of the x11 sdl driver?
it's in .steam/steam/steamapps/common/dota/game/dota.sh

I had the same problem using the x11 sdl driver but uncommenting it seemed to make the game work.

Perhaps someone from valve can confirm whether or not that is ok to do. I don't want to "modify" game files, but I would assume using native technology should be fine?

**Comment by formidabilus** [comment]
same here with Fedora 39 and Wayland, it crashes at random times, when alt-tab back into games, sometimes at start, happened when I was watching matches, too.

**Comment by LostinSpacetime** [comment]
> Does that also happen when commenting out the forcing of the x11 sdl driver? it's in .steam/steam/steamapps/common/dota/game/dota.sh
> 
> I had the same problem using the x11 sdl driver but uncommenting it seemed to make the game work.
> 
> Perhaps someone from valve can confirm whether or not that is ok to do. I don't want to "modify" game files, but I would assume using native technology should be fine?

I tried commenting out "export SDL_VIDEO_DRIVER=x11" in dota.sh, but then the game crashes even faster.

**Comment by formidabilus** [comment]
It seems like a fix will be pushed soon, I think they are related: https://github.com/ValveSoftware/Dota-2/issues/2657#issuecomment-1952546246

**Comment by LostinSpacetime** [comment]
Fixed!
