### ISSUE TITLE
LoadSystemAndDependencies error in connect() GameUI011

### ISSUE THREAD

**Issue by ribbley** [ValveSoftware/Dota-2#267]
Hello, I updated the steam client (and loaded a reborn patch I think) and from yesterday on I get following error while launching through steam:
(small box appears after launching reborn->):
LoadSystemAndDependencies():
## AppSystemDict: Error in Connect() of interface: 'GameUI011'!

After that I started it from terminal to get a bit more information:

ribbley@saphira:~/.steam/steam/SteamApps/common/dota 2 beta/game$ ./dota.sh
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198006785585 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198006785585
Setting breakpad minidump AppID = 373300
Dongle firmware /home/ribbley/.local/share/Steam/linux64/../controller_base/d0ggle.bin loaded, version 1435869091.
Fontconfig warning: "/home/ribbley/.steam/steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/ribbley/.steam/steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
AppSystemDict: Error in Connect() of interface 'GameUI011'!

some specs about my setup (steam information):
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1086
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,78" x 10,55"  (21,54" diag)
                                        47,7cm x 26,8cm  (54,7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1280 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887

Memory:
    RAM:  7965 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  224527 Mb
    Largest Free Hard Disk Block:  32247 Mb

Installed software:

Recent Failure Reports:
## Steam API: v017 package versions:1437509903 (built 21 Jul. 2015)

sorry for the formatting and maybe too much irrelevant information .
checked integrity of game cache (dota2 - dont know if it checks reborn too)

**Comment by gdrewb-valve** [comment]
You're missing a dependency, which is odd since usually that occurs when people aren't using the Steam runtime.  Does regular dota2 work?

**Comment by gdrewb-valve** [comment]
#105 is a different example of this but in that case the Steam runtime wasn't getting used, just something to look at.

**Comment by ribbley** [comment]
I've checked previous issues and tried something from that, and yes normal dota2 works fine (playing @ the moment :D ). Steam is running normally. Can I check steam for errors in some way?

**Comment by gdrewb-valve** [comment]
The cache check you already did is the primary thing for Reborn.  For Steam itself you can do "steam --reset" in a terminal.

**Comment by ribbley** [comment]
wow! This did the trick for me! :) thanks a lot. reseted steam, downloaded 283 MB , and after 5 mins I ran reborn normally. Last time updating steam and ubuntu update ran side by side, so maybe it crashed this way somehow . Big thanks for that fast support.
