### ISSUE TITLE
[Linux] Dota 2 is downloading huge pre-cache/shaders every day

### ISSUE THREAD

**Issue by TDYK** [ValveSoftware/Dota-2#2672]
#### Your system information

* [System information from steam (`Steam` -> `Help` -> `System Information`) in a gist:](https://gist.github.com/TDYK/2f555de31e9f4736cc9e2224a774f74a)
* [If on Linux, please include Steam -> Help -> Steam Runtime Diagnostics in the gist.](https://gist.github.com/TDYK/fb3fce1a3df3965763a2d37546aae5b4)
* Have you checked for system updates?: [No matter]
* Are you using the latest stable video driver available for your system? [No matter]
* Have you verified the game files?: [No matter]

#### Please describe your issue in as much detail as possible:
Before several weeks ago all the Vulkan caches were compiled on the system, now every day when i start the steam - i have to download sharing pre-caching update 1.5GiB size. 
https://i.imgur.com/ydOpXEf.png

If you tell me what i need to check and this is not expected behavior - tell me please what additional data I can provide.

If this is an expected behavior - why? 'cause network speed can be low and connection can be metered. 

#### Steps for reproducing this issue:

1. Run steam on Debian GNU/Linux
2. Try run Dota 2
3. IDK other steps to reproduce 'cause i do not have other OS/machine

**Comment by kisak-valve** [comment]
Hello @TDYK, this is a Steam client issue instead of a game issue, and is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10285. Closing as a duplicate.
