### ISSUE TITLE
Game crash (full kernel panic!) on Mac unless in "exclusive fullscreen" mode

### ISSUE THREAD

**Issue by necrolytus** [ValveSoftware/Dota-2#2683]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [here](https://gist.github.com/necrolytus/a649ff640b278cf17ff4d3d3fc65234a)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Device: Mac M2

OS: Updated to the latest Mac OS Sonoma 14.4.1 (released after March 7).

A serious kernel panic occurs that causes a full computer reboot, which is far more severe than just a game crash (takes minutes to get back into the OS after recovery).

I've experimented with various console options and on default settings (when I use desktop-friendly fullscreen), what I see initially is some game screen tearing with the bottom 80% of the screen black and flickering. I can alt-tab and will see flickers of what is in that 80% black area show up for a brief moment. I can easily alt-tab in and out of Dota 2, IF I was quick to ensure I was alt-tab out when Dota 2 was starting up. Otherwise, if I just start Dota 2 normally without alt-tabbing, then the kernel panic occurs.

When -fullscreen is turned on, the game can run normally after starting up. There is no screen tearing/flickering or black showing on portions of the screen. However, a kernel panic does occur on alt-tab. This is instantaneous and does not allow for any form of recovery. Quitting Dota 2 normally via the "exit game" UI works normally.

This was not an issue on Mac OS Sonoma 14.3.1 I believe.

I have reported this issue to Apple as well through, with the kernel panic crash records.

#### Steps for reproducing this issue:

1. Start Dota 2 with `-fullscreen` mode in console
2. Alt-tab
3. Kernel panic

OR 

1. Start Dota 2 without `-fullscreen` mode (my default desktop-friendly fullscreen mode)
2. Bottom 80% of screen is black and top 20% is flickering
3. Kernel panic depending on whether I had focus on Dota 2 during startup

**Comment by necrolytus** [comment]
This potentially has been fixed after today's update. At least when -fullscreen mode is enabled, alt-tab no longer causes a crash/panic.

**Comment by necrolytus** [comment]
Actually it still happened once on alt-tab, but it was out of >10 times this was done.

**Comment by ethanholt1** [comment]
I run macOS 10.14 (Mojave) and haven't had this issue. It could've been introduced with Sonoma?

**Comment by necrolytus** [comment]
It wasn't an issue on Sonoma 14.3.1 so it was the minor version bump to 14.4 or 14.4.1 that caused it to emerge. I've also been reporting this to Apple in case the problem is theirs, but it could be that Dota graphical API calls needs to be updated if something changed here.

**Comment by necrolytus** [comment]
This no longer seems to be an issue and alt-tab can happen reliably without crashing. Mac OS remains unchanged at 14.4.1 so I assume some of the bug fixing work from Valve has fixed this. Thank you!!

**Comment by necrolytus** [comment]
Closing this issue to do my part to help clean this tracker up
