### ISSUE TITLE
When typing number on numpad area, numbers have additional symbol(s) added after them.

### ISSUE THREAD

**Issue by Memoframe** [ValveSoftware/Dota-2#2692]
Arch Linux, kernel 6.8.7-arch1-1, Wayland, Hyprland, using two keyboard layouts, both have this problem.
For number under function keys output is normal.

This is output for 0123456789/*-+ on numpad:
06Z?.y1t??2t??3t??4t??56Z?.y6t??7t??8t??9t??/?*?-t??+?

**Comment by Ori-Pixel** [comment]
Can confirm, Arch Linuc, 6.8.7-arch1-1, X11, with 2 keyboard layouts, both with the same result.
Gist of steam diagnostic
https://gist.github.com/Ori-Pixel/1865f51422a7c506d9925413cb47dfb6

**Comment by Memoframe** [comment]
It's also broken for letter keys except English layout.
On ru it's like this (from q to /, except \ symbol):
йG??цG??уG??кG??еG??нG??гG??шG??щG??зG??хG??ъG??фG??ыG??в?DNwаG??пG??рG??оG??л?DNwдG??жG??эG??яG??чG??сG??мG??иG??тG??ьG??бG??юG??.

**Comment by INNKCake** [comment]
Can confirm for some letters in non-English layout:
`йцук?'?е?'?нгшщл?@\р?@\п?@\а?'?`

**Comment by pchmykh** [comment]
Same here with non-english layout.

**Comment by tuzah22** [comment]
+1 for cyrillic layout, you can type letters once and after that it types with random symbols. Same issue with different keyboards, same issue under Wayland or X11.
[video.webm](https://github.com/ValveSoftware/Dota-2/assets/74722677/543b1f62-3b96-4020-8a4e-fdc9cba6fe55)
Linux archlinux 6.8.6-arch1-1, steam from main repo. nVIDIA mx130 with proprietary drivers.

**Comment by voltageeee** [comment]
same here with russian letters

**Comment by Captain-Cyborg** [comment]
ValveSoftware/Dota2-Gameplay#16895 same problem.

**Comment by shpinog** [comment]
same here with russian letters

**Comment by hamednasimi** [comment]
The same is happening on Arch Linux + KDE Plasma 6.0.4 using English letters.
Kernel version: 6.8.9-arch1-2 (64-bit)
Graphics platform: Wayland

**Comment by Memoframe** [comment]
Any news/workarounds?
Maybe additional info needed?
It's like few weeks already.

**Comment by justbelieveinmyself** [comment]
same problem. ex: "п???р???и???в???е???т???" instead of "привет". 
these characters changes periodically for example "?^?" "??@" etc
btw, everything is OK in the steam overlay

**Comment by MissPotato** [comment]
I too am having weird text whenever I type with the numpad, however I **only** have English.

**Comment by Memoframe** [comment]
Removing all launch options in Steam does nothing.
When Dota being launched and GUI is just loaded there is 1-2 seconds where input is correct but after that moment it becomes as described earlier.
After every launch additional symbols are different.

**Comment by borisovdev** [comment]
same here
Arch Linux x86_64
6.9.2-arch1-1

**Comment by borisovdev** [comment]
I had the problem fixed after the last update
Thanks devs!

**Comment by pchmykh** [comment]
Fixed here too. Thanks!

**Comment by Memoframe** [comment]
Fixed for me as well, thx!
