### ISSUE TITLE
Cant play online matches with proton experimental on linux system because of VAC

### ISSUE THREAD

**Issue by koreanfan** [ValveSoftware/Dota-2#2696]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): archlinux x86_64 6.6.30-1-lts
 steam 1.0.0.79-1
* Have you checked for system updates?: [Yes/No] yes
* Are you using the latest stable video driver available for your system? [Yes/No] yes
* Have you verified the game files?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
Launch dota 2 with proton and play online matches but got message connected with VAC and unable to play online matches.
Sometimes you cant play dota normally cuz you got problem with linux kernel, linux video drivers, with dota itself. And in this period dota with proton work without any issue but you cant play online matches. Fix this issue with VAC on proton

#### Steps for reproducing this issue:

1. launch steam
2. go to dota 2 properties
3. go to Compatibility tab
4. choose Force the use of a specific steam play compatibility tool
5. choose proton experimental
6. wait for download
7. launch dota
8. press play online matches
9. got message connected with VAC and unable to play online matches

**Comment by kisak-valve** [comment]
Hello @koreanfan, running Dota 2 with the Proton compatibility layer is not supported on this issue tracker.

You can use the compatibility report at https://github.com/ValveSoftware/Proton/issues/6631 to discuss how the game behaves in an unofficial capacity.
