### ISSUE TITLE
About Dota2 startup vulkan error.

### ISSUE THREAD

**Issue by Serious34** [ValveSoftware/Dota-2#2697]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
    [System & Runtime Informations](https://gist.github.com/Serious34/10cceb7f59b8daa9f057f7cfa2c981a4)
* Have you checked for system updates?: [Yes/No]  Yes
* Are you using the latest stable video driver available for your system? [Yes/No]  Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:
![Ekran Görüntüsü - 2024-05-06 15-29-30](https://github.com/ValveSoftware/Dota-2/assets/19777464/fca8929f-2efe-4ec0-9c26-cc0a525f6858)

1.  I upgraded my Fedora 39 to 40. After this, i cannot start Dota2. I got this error "Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan.

To disable Vulkan, remove -vulkan from your launch options.
If you chose Vulkan in the video settings, please add -safe_mode to your launch options to allow the game to start with the default rendersystem."

Could you freeze my Dota plus membership from the opening date of the case to the termination date?
I would also like to ask for your support in solving the problem.

**Comment by kisak-valve** [comment]
Hello @Serious34, Dota 2 is accurately telling you that Vulkan is broken in the environment you're running Steam and the game. Additionally, Steam is being forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

It's likely that you're using Steam inside Flatpak and the NVIDIA proprietary driver, recently updated the video driver, and haven't reconfigured Flatpak to account for the video driver change.

Refresh your Flatpak install / config. If that doesn't help, then report this issue to https://github.com/flathub/com.valvesoftware.Steam/issues.
