### ISSUE TITLE
[Linux] Custom Games: The lobby you specified no longer exists.

### ISSUE THREAD

**Issue by svms1** [ValveSoftware/Dota-2#27]
When I try to join a custom game lobby I get the "The lobby you specified no longer exists." error. This happens for any lobby, even if I have just refreshed the list.

However, I am able to create a lobby and people are able to join it. Most of them are filled within seconds and start automatically.

Edit: I just realized that maybe the issue is that the lobbies are filled too fast and thus don't exist any more. But I'm positive that I'm seeing some of the same lobbies after refreshing but can't join them.

**Comment by watbe** [comment]
I get the same issue. I can participate in custom lobby matchmaking just fine, start my own custom game lobby, but joining any game via the custom lobby browser gives me the "The lobby you specified no longer exists" error.

I have refreshed multiple times and joined really low player count lobbies but I always get the same message. It has (to-date) never worked at all.

**Comment by gdrewb-valve** [comment]
An upcoming release will fix this.

**Comment by gdrewb-valve** [comment]
Fixed in the 6/26 release.
