### ISSUE TITLE
PA Arcana kill markers missing

### ISSUE THREAD

**Issue by r3pek** [ValveSoftware/Dota-2#270]
Shows the "error" label instead...

**Comment by budimanjojo** [comment]
Not Linux/Mac specific issue I think

**Comment by gdrewb-valve** [comment]
This does occur on Windows also and the larger team is aware of it.

**Comment by gdrewb-valve** [comment]
Can you run the game in a terminal and post the game spew from that?  That'll help the larger team isolate the issue.

**Comment by r3pek** [comment]
Nothing shows up on the terminal aside from the normal loading of the game (neither from game nor steam). On the game console there is this, but I guess you already have this one.

ERROR: RESOURCE_TYPE_MODEL resource 'models/heroes/attachto_ghost/pa_gravestone_ghost.vmdl' (BE8B846A8E07D6E5) requested is not loaded and may have been deleted.

**Comment by gdrewb-valve** [comment]
Thanks, I've passed that on.

**Comment by r3pek** [comment]
It's fixed on today's update.
