### ISSUE TITLE
Dota always crashes instantly after updating to Fedora 40 (previously stable on 39)

### ISSUE THREAD

**Issue by konstantinblaesi** [ValveSoftware/Dota-2#2703]
#### Your system information

* [System information from steam](https://gist.github.com/konstantinblaesi/6a7c4c434f4409c91cecc72e522c59c5)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
1. Watch any game
2. Dota crashes (current scene freezes, then dota dies in less than 5 seconds)

#### Steps for reproducing this issue:

Start dota and try to watch a game

### Launch options
`SDL_VIDEO_DRIVER=x11 DRI_PRIME=1 %command%`

`SDL_VIDEO_DRIVER=wayland` survived a little longer but also crashes in the same way

### Systemd journal

<details>
Mai 13 00:26:38 konstantin-pc.fritz.box systemd-coredump[27934]: Process 27800 (dota2) of user 1000 dumped core.
                                                             
     Module /run/host/usr/lib64/libvdpau.so.1.0.0 from rpm libvdpau-1.5-6.fc40.x86_64
     Module /run/host/usr/lib64/libva.so.2.2100.0 from rpm libva-2.21.0-3.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_radeon.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libpowervr_rogue.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_panfrost.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_nouveau.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_lvp.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_intel.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_intel_hasvk.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_freedreno.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_broadcom.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libVkLayer_MESA_device_select.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libelf-0.191.so from rpm elfutils-0.191-4.fc40.x86_64
     Module /run/host/usr/lib64/libdrm_amdgpu.so.1.0.0 from rpm libdrm-2.4.120-3.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan_powervr_mesa.so from rpm mesa-24.0.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libedit.so.0.0.72 from rpm libedit-3.1-50.20230828cvs.fc40.x86_64
     Module /run/host/usr/lib64/libffi.so.8.1.2 from rpm libffi-3.4.4-7.fc40.x86_64
     Module /run/host/usr/lib64/libexpat.so.1.9.2 from rpm expat-2.6.2-1.fc40.x86_64
     Module /run/host/usr/lib64/libwayland-client.so.0.22.0 from rpm wayland-1.22.0-3.fc40.x86_64
     Module /run/host/usr/lib64/libxshmfence.so.1.0.0 from rpm libxshmfence-1.3.2-3.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-randr.so.0.1.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-sync.so.1.0.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libvulkan.so.1.3.280 from rpm vulkan-loader-1.3.280.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-xfixes.so.0.0.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libz.so.1.3.0.zlib-ng from rpm zlib-ng-2.1.6-2.fc40.x86_64
     Module /run/host/usr/lib64/libzstd.so.1.5.6 from rpm zstd-1.5.6-1.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-shm.so.0.0.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-present.so.0.0.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libxcb-dri3.so.0.1.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libX11-xcb.so.1.0.0 from rpm libX11-1.8.9-1.fc40.x86_64
     Module /run/host/usr/lib64/libudev.so.1.7.8 from rpm systemd-255.6-1.fc40.x86_64
     Module /run/host/usr/lib64/libdrm.so.2.4.0 from rpm libdrm-2.4.120-3.fc40.x86_64
     Module /run/host/usr/lib64/libcap.so.2.69 from rpm libcap-2.69-8.fc40.x86_64
     Module /run/host/usr/lib64/libXau.so.6.0.0 from rpm libXau-1.0.11-6.fc40.x86_64
     Module /run/host/usr/lib64/libxcb.so.1.1.0 from rpm libxcb-1.17.0-1.fc40.x86_64
     Module /run/host/usr/lib64/libGLdispatch.so.0.0.0 from rpm libglvnd-1.7.0-4.fc40.x86_64
     Module /run/host/usr/lib64/libXext.so.6.4.0 from rpm libXext-1.3.6-1.fc40.x86_64
     Module /run/host/usr/lib64/libX11.so.6.4.0 from rpm libX11-1.8.9-1.fc40.x86_64
     Module /run/host/usr/lib64/libGLX.so.0.0.0 from rpm libglvnd-1.7.0-4.fc40.x86_64
     Module /run/host/usr/lib64/libGL.so.1.7.0 from rpm libglvnd-1.7.0-4.fc40.x86_64
     Module /run/host/usr/lib64/libXfixes.so.3.1.0 from rpm libXfixes-6.0.1-3.fc40.x86_64
     Stack trace of thread 27830:
     #0  0x00007f9b2f507fca radv_UpdateDescriptorSetWithTemplate (/run/host/usr/lib64/libvulkan_radeon.so + 0x107fca)
     #1  0x00007f9b44f674fb n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1674fb)
     #2  0x00007f9b44f73a4d n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x173a4d)
     #3  0x00007f9b44fc6a58 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1c6a58)
     #4  0x00007f9b44fc7e7e n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1c7e7e)
     #5  0x00007f9b60b19c5d n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x119c5d)
     #6  0x00007f9b60b19da8 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x119da8)
     #7  0x00007f9b60b1b814 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x11b814)
     #8  0x00007f9b60bce3e3 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1ce3e3)
     #9  0x00007f9b60bcf707 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1cf707)
     #10 0x00007f9b62ab21b7 start_thread (/run/host/usr/lib64/libc.so.6 + 0x961b7)
     #11 0x00007f9b62b3439c __clone3 (/run/host/usr/lib64/libc.so.6 + 0x11839c)
     
     Stack trace of thread 27825:
     #0  0x00007f9b62b1ae5b __sched_yield (/run/host/usr/lib64/libc.so.6 + 0xfee5b)
     #1  0x00007f9b44fc90a5 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1c90a5)
     #2  0x00007f9b44fc8b3b n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x1c8b3b)
     #3  0x00007f9b44f0c896 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x10c896)
     #4  0x00007f9b44f0ccd8 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x10ccd8)
     #5  0x00007f9b44f8f0a9 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so + 0x18f0a9)
     #6  0x00007f9b60bcf707 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1cf707)
     #7  0x00007f9b62ab21b7 start_thread (/run/host/usr/lib64/libc.so.6 + 0x961b7)
     #8  0x00007f9b62b3439c __clone3 (/run/host/usr/lib64/libc.so.6 + 0x11839c)
     
     Stack trace of thread 27811:
     #0  0x00007f9b62aae919 __futex_abstimed_wait_common (/run/host/usr/lib64/libc.so.6 + 0x92919)
     #1  0x00007f9b62ab1652 pthread_cond_timedwait@@GLIBC_2.3.2 (/run/host/usr/lib64/libc.so.6 + 0x95652)
     #2  0x00007f9b60bc8376 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1c8376)
     #3  0x00007f9b4c65ce2d n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5ce2d)
     #4  0x00007f9b4c65d0f4 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5d0f4)
     #5  0x00007f9b60bce3e3 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1ce3e3)
     #6  0x00007f9b60bcf707 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1cf707)
     #7  0x00007f9b62ab21b7 start_thread (/run/host/usr/lib64/libc.so.6 + 0x961b7)
     #8  0x00007f9b62b3439c __clone3 (/run/host/usr/lib64/libc.so.6 + 0x11839c)
     
     Stack trace of thread 27803:
     #0  0x00007f9b62aae919 __futex_abstimed_wait_common (/run/host/usr/lib64/libc.so.6 + 0x92919)
     #1  0x00007f9b62ab1652 pthread_cond_timedwait@@GLIBC_2.3.2 (/run/host/usr/lib64/libc.so.6 + 0x95652)
     #2  0x00007f9b60bc8376 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1c8376)
     #3  0x00007f9b60b1b72d n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x11b72d)
     #4  0x00007f9b60b1b880 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x11b880)
     #5  0x00007f9b60bce3e3 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1ce3e3)
     #6  0x00007f9b60bcf707 n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so + 0x1cf707)
     #7  0x00007f9b62ab21b7 start_thread (/run/host/usr/lib64/libc.so.6 + 0x961b7)
     #8  0x00007f9b62b3439c __clone3 (/run/host/usr/lib64/libc.so.6 + 0x11839c)
     
     Stack trace of thread 27904:
     #0  0x00007f9b62aae919 __futex_abstimed_wait_common (/run/host/usr/lib64/libc.so.6 + 0x92919)
     #1  0x00007f9b62ab1652 pthread_cond_timedwait@@GLIBC_2.3.2 (/run/host/usr/lib64/libc.so.6 + 0x95652)
     #2  0x00007f9b2f57aa66 x11_manage_fifo_queues (/run/host/usr/lib64/libvulkan_radeon.so + 0x17aa66)
     #3  0x00007f9b62ab21b7 start_thread (/run/host/usr/lib64/libc.so.6 + 0x961b7)
     #4  0x00007f9b62b3439c __clone3 (/run/host/usr/lib64/libc.so.6 + 0x11839c)
     
     Stack trace of thread 27893:
     #0  0x00007f9b62aae919 __futex_abstimed_wait_common (/run/host/usr/lib64/libc.so.6 + 0x92919)
     #1  0x00007f9b62ab12e9 pthread_cond_wait@@GLIBC_2.3.2 (/run/host/usr/lib64/libc.so.6 + 0x952e9)
     #2  0x00007f9ab9f1ee3f n/a (/home/konstantinblaesi/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvideo.so + 0x11ee3f)
     ELF object binary architecture: AMD x86-64
</details>

**Comment by kisak-valve** [comment]
Hello @konstantinblaesi, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.

**Comment by konstantinblaesi** [comment]
Hello @kisak-valve, thanks for the quick feedback and suggested workaround. It looks like it works, no crashes so far!

Bad kernel: vmlinuz-6.8.9-300.fc40.x86_64
Good kernel: vmlinuz-6.8.5-301.fc40.x86_64

Steps to use different kernel
```
sudo dnf install kernel-6.8.5-301.fc40.x86_64


# after installation this version was already the default during boot, but if you want to switch the default, pick a suitable index, e.g.
➜  ~ sudo grubby --set-default-index=2
The default is /boot/loader/entries/bcb3ee31e38f439aa492bca773a5722d-6.8.5-301.fc40.x86_64.conf with index 2 and kernel /boot/vmlinuz-6.8.5-301.fc40.x86_64


# to restore the default/latest kernel
➜  ~ sudo grubby --set-default-index=0
The default is /boot/loader/entries/bcb3ee31e38f439aa492bca773a5722d-6.8.9-300.fc40.x86_64.conf with index 0 and kernel /boot/vmlinuz-6.8.9-300.fc40.x86_64
```

Issue seems resolved for now, the comments in the issue you linked sound like a fix is underway so I assume it will appear in Fedora 40 soonish.

**Comment by kisak-valve** [comment]
Thanks for checking, that makes this the same issue as #2694. Closing as a duplicate.
