### ISSUE TITLE
[Fedora Linux] Dota wont launch

### ISSUE THREAD

**Issue by DavanaVM** [ValveSoftware/Dota-2#2704]
[System Information](https://gist.github.com/DavanaVM/8677137d3204cc1b25eef4cf726dac95)
[Runtime Information](https://gist.github.com/DavanaVM/7cf889e1c94cb8000bb16423d6bd7390)

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Every time i launch Dota 2 i get 
```
crash_20240513235339_2.dmp[42378]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240513235339_2.dmp
/home/david/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 122: 42322 Bus error               (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20240513235339_2.dmp[42378]: Finished uploading minidump (out-of-process): success = yes
crash_20240513235339_2.dmp[42378]: response: CrashID=bp-e6f29342-e365-4e0a-ab81-787782240513
crash_20240513235339_2.dmp[42378]: file ''/tmp/dumps/crash_20240513235339_2.dmp'', upload yes: ''CrashID=bp-e6f29342-e365-4e0a-ab81-787782240513''
pid 42378 != 42377, skipping destruction (fork without exec?)

```
I am Fedora 40 and using Wayland, i have tried X11 as well and tried multiple Launch options i found online

#### Steps for reproducing this issue:

1.  Run Dota 2
2.  Dota 2 is loading
3.  Game doesnt launch and the button switches back to Play

**Comment by kisak-valve** [comment]
Hello @DavanaVM, this is a kernel regression which was tracked and resolved in https://gitlab.freedesktop.org/drm/amd/-/issues/3343. One way to workaround this issue is to reboot into an older kernel until the fix is backported upstream.

**Comment by DavanaVM** [comment]
thank you i also just tried running it with proton which also seems to work, i'll use it like that until the fix is backported
