### ISSUE TITLE
[Linux] crash freeze new patch 7.36

### ISSUE THREAD

**Issue by kompolompo** [ValveSoftware/Dota-2#2708]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
[* <script src="https://gist.github.com/kompolompo/503451a72378c7eaeba35121ca7a275b.js"></script>](https://gist.github.com/kompolompo/503451a72378c7eaeba35121ca7a275b)

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

when clicking on Act1 "Ripples In The Dark" The hole in he ground, last stage, that appears to be the last step in act1. After the dialogue when clicking x it will crash/freeze I think it might be like a video/cut scene to actII, not sure what is going to happen there since it is a new patch.

#### Steps for reproducing this issue:

1. updated system restarted
2. Attached the logs
3. Tried launch with no command launch parameters, crashed everytime no matter what I do. I have to forcefully close dota2.
[crash_20240523085235_2.dmp](https://github.com/ValveSoftware/Dota-2/files/15416170/crash_20240523085235_2.dmp)
[runtime information.txt](https://github.com/ValveSoftware/Dota-2/files/15416179/runtime.information.txt)
[terminal log crash-freeze.txt](https://github.com/ValveSoftware/Dota-2/files/15416231/terminal.log.crash-freeze.txt)

**Comment by konstantinblaesi** [comment]
Sounds kind of like #2703 (your gist suggests you are running 6.8.6?)
On fedora 40:

- 6.8.5: fine
- 6.8.9: broken
- 6.8.10: just updated, dota has not crashed yet

**Comment by zeparu** [comment]
can confirm exact same freeze, got scared for a second because it will play a loud buzzing sound for a couple seconds before the game crashes, this in on current arch linux with 6.9.1 kernel

**Comment by Vkim11** [comment]
> Sounds kind of like #2703 (your gist suggests you are running 6.8.6?) On fedora 40:
> 
> * 6.8.5: fine
> * 6.8.9: broken
> * 6.8.10: just updated, dota has not crashed yet

My game crashes on 6.8.10 sometimes when launching

**Comment by kompolompo** [comment]
tried change kernel to linux kernel 6.7 broken
6.8.7 broken
will see if I can try 6.8.10 tomorrow

**Comment by kompolompo** [comment]
tried 6.8.10 still crashing freeze at the exact same location
tried 6.9.0-rc4 still crashing freeze at the exact same location

**Comment by zeparu** [comment]
crash is still happening btw, i tried changing the audio backend, as suggested by #2707, as the audio tends to freak out after the freeze, but it didnt really help, maybe it helped with the audio not spasming out, but it certainly didnt help with the crash

**Comment by kompolompo** [comment]
Now it just works when I clicked the same spot, it did not crash/freeze. Looks solved.

Kernel: 6.8.11-xanmod1
DE: GNOME 46.2 (Wayland)
NixOS 24.05

**Comment by kisak-valve** [comment]
Possibly resolved by https://github.com/ValveSoftware/Dota-2/issues/2718#issuecomment-2136396699.

**Comment by zeparu** [comment]
tested it just now, clicking the cave in part 1 and exiting it now doesnt cause the crash anymore, fixed for me

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
