### ISSUE TITLE
[linux] cannot delete downloaded games

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#271]
I downloaded one of my game... cannot delete it. It does not appear.

**Comment by gdrewb-valve** [comment]
Which game?  If you download others does the same thing happen?

**Comment by sylware** [comment]
On Fri, Jul 24, 2015 at 11:29:34AM -0700, Drew Bliss wrote:

> Which game?  If you download others does the same thing happen?

One of my games. Have not tried to download other types of games, yet.

**Comment by gdrewb-valve** [comment]
Can you give me the specific name so that we know exactly which one it is?

**Comment by sylware** [comment]
I don't know how knowing my game id will help: 1653416671. I tried to download "friends" replays... that I was unable to do, yet, since they were all source 1 replays.

**Comment by gdrewb-valve** [comment]
Sorry, I thought you meant you had downloaded a custom game mode.

**Comment by gdrewb-valve** [comment]
Not a Mac/Linux issue, I've passed this on to the larger team.
