### ISSUE TITLE
[Linux] Dota2 launches on wrong monitor since 7.36

### ISSUE THREAD

**Issue by ruliane** [ValveSoftware/Dota-2#2712]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`): https://gist.github.com/ruliane/7e67f307d60bf2fbaf3ecbbe0029753f
Linux Mint 21.3 MATE with nvidia-driver-535

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Used : nvidia-driver-535. Recommended : nvidia-driver-535. Latest : nvidia-driver-545.
* Have you verified the game files?: No: check stuck at 0%. Probably unrelated issue.

#### Please describe your issue in as much detail as possible:
I have a dual screen setup. I use argument -phased_window_create to launch Dota on the primary monitor.
However, since patch 7.36, Dota launches on the wrong monitor.

#### Steps for reproducing this issue:
1. configure Dota with -phased_window_create arg
2. Launch Dota2

**Comment by kshammer** [comment]
Same issue with Pop-OS and Nvidia 550

**Comment by staticf0x** [comment]
Same issue, Fedora 40 (Gnome, Wayland), RX 6600 XT

**Comment by kompolompo** [comment]
Same issue, NixOS 23.11 (Gnome 45.5, Wayland), RX 6700 XT

Started when new patch came out

**Comment by OctavianOG** [comment]
Greetings, you can try to use launch option:
```ruby
-sdl_displayindex 0
```
Replace `0` with number of your display, e.g. if you want to display dota on your primary display use `0`. I run dota on my second screen and using `1` index

**Comment by kompolompo** [comment]
> Greetings, you can try to use launch option:
> 
> ```ruby
> -sdl_displayindex 0
> ```
> 
> Replace `0` with number of your display, e.g. if you want to display dota on your primary display use `0`. I run dota on my second screen and using `1` index

-sdl_displayindex 0
-sdl_displayindex 1

tried both options dota 2 started on my secondary screen.

**Comment by F0Rt04ka** [comment]
Same issue Ubuntu 22.04

**Comment by kshammer** [comment]
A work around for this issue is 

1. Turn off secondary monitor
2. Start dota 2
3. After dota is fully launched turn on secondary monitor 

Dota will stay on the primary monitor and remains in place even after alt-tab.

**Comment by ruliane** [comment]
Looks like issue is fixed today.
