### ISSUE TITLE
Overwatch replays stuck on loading screen.

### ISSUE THREAD

**Issue by yulnr** [ValveSoftware/Dota-2#2743]
#### Your system information

* System information from steam: [gist here](https://gist.github.com/joulei/816089c6f4ff3fff8b59bb89fada5aca)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
When downloading and reviewing an Overwatch replay, the game gets stuck in the loading screen, the replay controls won't work. The only available option is to quit the replay which then plays a random sound which seems like some spell usage that happened in the game.
This has been happening since 7.36.

**Comment by kisak-valve** [comment]
Hello @joulei, this is not an OS specific issue and is already being tracked in various issue reports (https://github.com/ValveSoftware/Dota2-Gameplay/issues?q=is%3Aissue+is%3Aopen+overwatch+stuck). Closing as a duplicate.
