### ISSUE TITLE
Upgrading from Linux kernel 6.6.23 and 6.6.30 crashes Dota 2 

### ISSUE THREAD

**Issue by joepatricio** [ValveSoftware/Dota-2#2745]
#### Your system information

* Steam System Report and Runtime Diagnosis: https://gist.github.com/joepatricio/f406007328f35fe5ca61e6783ca48176
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]
* Kernel config comparison: https://gist.github.com/joepatricio/4ba38c02584b1dde99516c9137e6b2ae

#### Please describe your issue in as much detail as possible:
Expectation: Dota 2 should be able to play a full match, online or offline, without crashing.
Result: Playing Dota 2 with Linux kernel 6.6.30 crashes upon attempting to start any match.
dmesg has the following output:
```
[    7.404344] (udev-worker) (637) used greatest stack depth: 11304 bytes left
[    7.881082] elogind-daemon[1210]: New session 1 of user joe.
[   12.244286] wlp5s0: authenticate with 6c:a4:d1:e8:b1:28
[   12.244297] wlp5s0: 80 MHz not supported, disabling VHT
[   12.254407] wlp5s0: send auth to 6c:a4:d1:e8:b1:28 (try 1/3)
[   12.255903] wlp5s0: authenticated
[   12.256040] wlp5s0: associate with 6c:a4:d1:e8:b1:28 (try 1/3)
[   12.259471] wlp5s0: RX AssocResp from 6c:a4:d1:e8:b1:28 (capab=0x411 status=0 aid=3)
[   12.259767] wlp5s0: associated
[   12.280813] X[1728]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set
```

#### Steps for reproducing this issue:

1. Execute Dota 2 from Steam.
2. Start a match.
3. The game will crash.

Attached: Dump file (tar.gz)
[dota2_dump.tar.gz](https://github.com/user-attachments/files/16031966/dota2_dump.tar.gz)

**Comment by kisak-valve** [comment]
Hello @joepatricio, the Linux 6.6.30 release has an AMDGPU regression that was tracked at https://gitlab.freedesktop.org/drm/amd/-/issues/3343. Use a different point release of the kernel.
