### ISSUE TITLE
[Linux] Game doesn't exit cleanly

### ISSUE THREAD

**Issue by MisterrrX** [ValveSoftware/Dota-2#2759]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/MisterrrX/b1ce4cc6ad82d3b058c18ae9c52055b6):

* Have you checked for system updates? Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files? Yes

#### Please describe your issue in as much detail as possible:
The game process doesn't end when closing Dota 2 from the exit button in the top right corner. Manually stopping the game via steam is required.

#### Steps for reproducing this issue:

1. Open Dota
2. Close Dota by clicking the exit button in the top right corner
--> Game process doesn't end on its own

**Comment by 13k** [comment]
Also crashes when entering `quit` in the console.

The issue, at face value, seems innocuous but causes several problems:

- Restarting the client will take a huge amount of time (in my case, almost 1min) waiting for crash dumps to be uploaded. So the restart + reconnect workflow to fix issues while in a game will directly affect gameplay, specially if the opposing team doesn't respect pauses (which is often the case)
- (Possibly related) Vulkan shaders get downloaded/recompiled again
- (Possibly related) Steam cloud configs get out of sync regularly
- OS crash handlers (like `abrt`) will get spammed with lots of crash dumps. Same goes for OS logs (like systemd's journal)

**Comment by MisterrrX** [comment]
This was fixed a while ago, thanks.

**Comment by 13k** [comment]
Did it get fixed? I'm still getting crashes. Fedora 40, kernel 6.11.8, amdgpu, KDE Plasma 6.2.3 (Wayland)
