### ISSUE TITLE
[MacOS] Game crashes when playing Dragon Chess encounter in Crownfall Act III

### ISSUE THREAD

**Issue by Taraki-8** [ValveSoftware/Dota-2#2763]
#### Your system information

* System information from steam: https://gist.github.com/Taraki-8/9eea9d9da4730a9f187ec92d2db2aab2
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Game instantly crashes when attempting to move the first jewel in Dragon Chess encounter in Crownfall Act III

#### Steps for reproducing this issue:
1. Click Dragon Chess encounter in Crownfall Act III
2. Wait for jewels to load
3. Move any jewel

**Comment by mknikoloza** [comment]
i have same problem just touch jewels and game crushing wtf to do idk

**Comment by MrRinsvind** [comment]
I have the same issue

**Comment by danginsburg** [comment]
This will be fixed in the next Dota client update.

**Comment by freedompride** [comment]
@danginsburg . when will the update be released?

**Comment by aj-archit** [comment]
it happens only on MAC

**Comment by tjuana** [comment]
14.5 (23F79) Apple M2 Pro same problem MacBook Pro when move first gem

**Comment by anurzhanuly** [comment]
same here, m3 pro

**Comment by anishkr92** [comment]
I am having the same problem

**Comment by danginsburg** [comment]
The update has shipped, please retest.

**Comment by Taraki-8** [comment]
The bug/issue is resolved. Thanks!

**Comment by LuckyStar1990** [comment]
i still have same issue, just disconnected 3 times, while playing dragon chess

**Comment by DaemonasTV** [comment]
Happens on PC as well.
