### ISSUE TITLE
[linux] often, messages are not received and/or sent

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#278]
In a party, or via steam (whisper), messages are not sent and/or received.

**Comment by gdrewb-valve** [comment]
Not a Mac/Linux issue.

**Comment by gdrewb-valve** [comment]
Is the "Mute all chat" button ever set?

**Comment by gdrewb-valve** [comment]
Everything worked fine for me with basic testing.  I created a lobby, had another person join it and all lobby chat messages worked fine.  Are there specific situations in which this occurs?

**Comment by sylware** [comment]
On Mon, Jul 27, 2015 at 04:13:11PM -0700, Drew Bliss wrote:

> Are there specific situations in which this occurs?

I could not identify any pattern.

**Comment by gdrewb-valve** [comment]
We'll have to try and find a repro.  As this doesn't appear to be a Mac/Linux issue that'll most likely be checked first by the larger team.

**Comment by sylware** [comment]
I use the big picture client. Then I have 3 places where the messages are to be displayed: the big picture client, the popup message box and reborn client... messages are not displayed in all places.

**Comment by gdrewb-valve** [comment]
Which place are you not seeing it, or is it all three?

**Comment by sylware** [comment]
On Mon, Aug 03, 2015 at 09:58:59AM -0700, Drew Bliss wrote:

> Which place are you not seeing it, or is it all three?

It's weird, have not identified any pattern. Sometimes even where
(bigpicture/reborn/popup) I write a message, once sent, it's not displayed.

**Comment by sylware** [comment]
On Tue, Aug 04, 2015 at 12:39:03PM +0000, sylvain.bertrand@gmail.com wrote:

> On Mon, Aug 03, 2015 at 09:58:59AM -0700, Drew Bliss wrote:
> 
> > Which place are you not seeing it, or is it all three?
> 
> It's weird, have not identified any pattern. Sometimes even where
> (bigpicture/reborn/popup) I write a message, once sent, it's not displayed.

what is the inter-process communication protocol used for broacasting the
messages to consumer software components? Valve internal? Or is there an
external third party dependency?

**Comment by gdrewb-valve** [comment]
The chat messaging should be all Valve-internal processing.

**Comment by sylware** [comment]
On Tue, Aug 04, 2015 at 12:06:49PM -0700, Drew Bliss wrote:

> The chat messaging should be all Valve-internal processing.

Then I do not miss anything on my system to make it work properly, I guess. Was checking to be sure.
I think it happens in the past but it was fixed if I recall properly.

**Comment by sylware** [comment]
seems to be fixed.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
