### ISSUE TITLE
[Mac OS M1] Game crashes after successfully accepting match

### ISSUE THREAD

**Issue by Taraki-8** [ValveSoftware/Dota-2#2789]
#### Your system information

* System information from steam: https://gist.github.com/Taraki-8/9eea9d9da4730a9f187ec92d2db2aab2
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Game instantly crashes after successfully accepting a match and shows error below:

<img width="337" alt="360725026-aac0c3cb-07a1-4c04-bc81-29bc0f86aded" src="https://github.com/user-attachments/assets/daa18e88-b35e-4ae7-b9b6-6a77e548366f">

#### Steps for reproducing this issue:

1. Open Dota 2
2. Queue for a game and wait for match
3. Accept Match
4. Game crashes

**Comment by kisak-valve** [comment]
Hello @Taraki-8, this issue is already being tracked at #2784. Closing as a duplicate.
