### ISSUE TITLE
[linux] emoticons are gone

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#279]
today, my emoticons are gone (regression).

**Comment by gdrewb-valve** [comment]
Reborn had no updates since Friday.  What about your system changed, or have you not tried emoticons recently?

**Comment by Scias** [comment]
Had the same issue today (now fixed) but it has nothing to do with Reborn or the Linux client. It happens when the Dota network is offline (You "lose" all your items during that time).
