### ISSUE TITLE
Dota2 crash after couple of seconds

### ISSUE THREAD

**Issue by xabbtk17** [ValveSoftware/Dota-2#2790]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

https://gist.github.com/xabbtk17/08c8f8b93dfed03643e31cc52e36576f
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I expect to be able to play but the game crashed.

#### Steps for reproducing this issue:

1. Run steam
2. Run dota2
3. Wait couple of minute once in the main screen or click in the heroes page

I tried with `-autoconfig` and `-safe` without any success.

In advance thank you.

**Comment by xabbtk17** [comment]
Crash dump:
```
crash_20240823175219_2.dmp[1656073]: Finished uploading minidump (out-of-process): success = yes
crash_20240823175219_2.dmp[1656073]: response: CrashID=bp-141e8ce9-d5c6-4472-a245-85ce62240823
crash_20240823175219_2.dmp[1656073]: file ''/tmp/dumps/crash_20240823175219_2.dmp'', upload yes: ''CrashID=bp-141e8ce9-d5c6-4472-a245-85ce62240823''
pid 1656073 != 1656072, skipping destruction (fork without exec?)

```

**Comment by xabbtk17** [comment]
It works if I use: `-vulkan_disable_pipeline_cache`

**Comment by CantTouchDis** [comment]
Maybe it provides more context to this issue:

I started `dota.sh` from the console to see if I get more information. I noticed that it crashed when trying to load `libcurl.so` with the message of file not found:
```
...
crash_20240823175606_2.dmp[23115]: error: libcurl.so: cannot open shared object file: No such file or directory
...
```

after that I tried it again with my system libcurl:
```
...
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libcurl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
...
```

Not sure why it is trying to load a 32 bit libcurl on my system...

**Comment by gostapit** [comment]
Same here, 

> -vulkan_disable_pipeline_cache

gives same result

```
Missing interface adapter for STEAMTIMELINE_INTERFACE_V002 
double free or corruption (fasttop)
double free or corruption (fasttop)
crash_20240823190244_2.dmp[26957]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240823190244_2.dmp
Adding process 26956 for gameID 570
crash_20240823190244_2.dmp[26957]: Finished uploading minidump (out-of-process): success = yes
crash_20240823190244_2.dmp[26957]: response: CrashID=bp-b17f6527-b8db-464e-a2a4-5124d2240823
crash_20240823190244_2.dmp[26957]: file ''/tmp/dumps/crash_20240823190244_2.dmp'', upload yes: ''CrashID=bp-b17f6527-b8db-464e-a2a4-5124d2240823''
pid 26957 != 26956, skipping destruction (fork without exec?)

```

**Comment by tje3d** [comment]
Running the Dota 2 binary directly, instead of through Steam, will fix the problem, and you won't experience crashes.

**Comment by gostapit** [comment]
> Running the Dota 2 binary directly, instead of through Steam, will fix the problem, and you won't experience crashes.

.../SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh

Displays "game files missing or corrupted"

**Comment by Hursofid** [comment]
Same here, attaching detailed report from other issue
https://github.com/ValveSoftware/Dota2-Gameplay/issues/21141#issuecomment-2306881608

**Comment by theflockers** [comment]
Same here. As usual after a big update Linux is fully broken. [https://gist.github.com/theflockers/6ee89f38a12122c263659eccea5c78d0](https://gist.github.com/theflockers/6ee89f38a12122c263659eccea5c78d0)
```
Missing interface adapter for STEAMTIMELINE_INTERFACE_V002 
Loaded /home/leandro/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxste
 failed to dlopen "/home/leandro/.steam/steam/steamapps/common/dota 2 beta/game/
Loaded librenderdoc.so, got (nil)
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared ob
double free or corruption (fasttop)
double free or corruption (fasttop)
crash_20240825125043_2.dmp[3942899]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240825125043_2.dmp
Adding process 3942898 for gameID 570
/home/leandro/.steam/steam/steamapps/common/dota 2 beta/game/dota.sh: line 122: 3942237 Aborted                 ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20240825125043_2.dmp[3942899]: Finished uploading minidump (out-of-process): success = yes
crash_20240825125043_2.dmp[3942899]: response: CrashID=bp-63be28d8-5a7c-47f6-8a2d-56c7e2240825
crash_20240825125043_2.dmp[3942899]: file ''/tmp/dumps/crash_20240825125043_2.dmp'', upload yes: ''CrashID=bp-63be28d8-5a7c-47f6-8a2d-56c7e2240825''

```

**Comment by cafir** [comment]
![image](https://github.com/user-attachments/assets/0de07328-68b1-4b30-a584-517ad6095dde)
this is what i found when try running it on binary

**Comment by Hursofid** [comment]
With regards and respect to assistance in resolving issues in past, I'd like to ask @kisak-valve to give a chance to have a look into this problem. I've just checked - game is still crashing and no one seems to be acknowledging

**Comment by theflockers** [comment]
Should we just let it go and move to Proton? (Not a rhetorical question...)

**Comment by Hursofid** [comment]
> Should we just let it go and move to Proton? (Not a rhetorical question...)

Well you should give it a try. I wasn't successful at trying that, had some windows-like directx11 related error message with two randomly selected proton versions.

**Comment by xabbtk17** [comment]
I updated my nvidia drivers to 535.183.01 and it works (full vulkain reprocessing).

**Comment by xabbtk17** [comment]
Sorry for the noise.

**Comment by Hursofid** [comment]
I guess I will have to create a separate issue...

**Comment by theflockers** [comment]
Indeed. Tried now thinking this was closed because the issue is fixed, but no. Same crap for a entire week, and 0 feedback to users.

**Comment by Hursofid** [comment]
I work in IT and I'm tired already. I just want to play this shit. But now I see it just generates more work for me. I guess Valve did the thing I couldn't do for past 10 years – stop wasting time in this stupid retarded game community. Congratulations Valve! Enjoy cashless zoomers. I'm bailing out.

**Comment by gostapit** [comment]
Well 550.107.02 nvidia drivers solved issue for me

**Comment by theflockers** [comment]
Unfortunately Nvidia drivers won't drive my RX 570.
