### ISSUE TITLE
MacOS game crash when accepting games

### ISSUE THREAD

**Issue by sdrobov** [ValveSoftware/Dota-2#2794]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/sdrobov/1704ff0bd4fda806f4d34ccd8b775306):
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Dota constantly crashing when accepting ranked games, can't reconnect after restart, got penalty

1.  Find ranked match
2. Accept

![image](https://github.com/user-attachments/assets/801f1158-cbc1-4df0-a5e2-13a44e0d9c07)

**Comment by kisak-valve** [comment]
Hello @sdrobov, this issue is already being tracked at #2784. Closing as a duplicate.
