### ISSUE TITLE
OS X - Crash on launch

### ISSUE THREAD

**Issue by gu3st** [ValveSoftware/Dota-2#28]
After installing Reborn, it launched once and then crashed once I went to view a replay.  Upon relaunch, I get an instant crash when beginning to render the UI. I have tried with "Automatic Graphics Switching" Enabled and Disabled with the same result.  Also of note, I am running OS X 10.11

System specs are: 
![screenshot 2015-06-23 02 22 40](https://cloud.githubusercontent.com/assets/375232/8302896/c8e551fc-194e-11e5-935e-3cecd3e63186.png)

Example crash dump: 

http://pastebin.com/GkpBXa98

http://pastebin.com/W3c8eTne

**Comment by gu3st** [comment]
Whoops, Dupe of #15, but contains another crash dump for reference

**Comment by gu3st** [comment]
Reading the crash dump further (at least one of mine) appears to be in the thread relating to sound.

**Comment by suhaaktas** [comment]
similar to linux version crash issues #3

**Comment by gdrewb-valve** [comment]
These El Capitan crashes are all the same, closing duplicate.
