### ISSUE TITLE
[Linux?] (Custom games) Wrong host displayed in Lobby List

### ISSUE THREAD

**Issue by Scias** [ValveSoftware/Dota-2#280]
Hello,
I'm not sure if this is a Linux-specific issue but I failed to reproduce it on Windows (could be just bad luck tho).
So basically sometimes when joining a custom game lobby, the displayed Host won't be hosting after everyone presses accept and I will be hosting the game instead even if I wasn't the lobby host in the first place.
Managed to catch this on video : https://www.youtube.com/watch?v=ec5gx-gspm8 , so at the start you can see I'm not supposed to be the host but apparently become it after everyone accepted. (I cut the insanely long waiting parts)

Or maybe it's some host autoswitching feature I've not heard of ?

System Information : 

> Processor Information:
> Vendor:  AuthenticAMD
>  CPU Family:  0x15
>  CPU Model:  0x1
>  CPU Stepping:  0x2
>     CPU Type:  0x0
>     Speed:  3300 Mhz
>     6 logical processors
>     6 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Supported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     Linux (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.1.2-2-ARCH
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11702000
>     X Window Manager:  KWin
>     Steam Runtime Version:  steam-runtime-release_2015-06-12
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GTX 550 Ti/PCIe/SSE2
> 
>    Driver Version:  4.5.0 NVIDIA 352.21
>     OpenGL Version: 4.5
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     VendorID:  0x10de
>     DeviceID:  0x1244
>     Number of Monitors:  2
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 3200 x 1080
>     Primary Display Size: 20,08" x 11,42"  (23,07" diag)
>                                             51,0cm x 29,0cm  (58,6cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 1024 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Realtek ALC887-VD
> 
> Memory:
>     RAM:  7935 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  fr_FR.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  113959 Mb
>     Largest Free Hard Disk Block:  84799 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
This apparently can happen on Windows also, I've passed this on to the larger team.
