### ISSUE TITLE
Dota 2 Mac OS Sonoma fog of war BUG

### ISSUE THREAD

**Issue by Morfey** [ValveSoftware/Dota-2#2801]
Has anyone found a proper solution to the fog of war issue on macOS Sonoma? Lowering the resolution to the minimum works, but there should have been something else by now after all these months. Did Valve just decide to ignore adapting the game?

Эта проблема: https://github.com/ValveSoftware/Dota2-Gameplay/issues/7203

**Comment by kisak-valve** [comment]
Hello @Morfey, this issue is already being tracked at #2027. Closing as a duplicate.

**Comment by murat-gezer** [comment]
is there any solution for this bug?
