### ISSUE TITLE
[Linux] Uncategorized Armory really slow FPS

### ISSUE THREAD

**Issue by r3pek** [ValveSoftware/Dota-2#281]
When viewing the armory and deselecting the "category view" I get a really low (3-10) FPS while on every other place on the game I have really good (300 with vsync turned off) FPS.

I have a GTX770 4GB with proprietary drivers.

**Comment by danginsburg** [comment]
@r3pek Can you post a screenshot?  I am not able to repro this, but I wonder if you have a large number of items you are displaying?

**Comment by r3pek** [comment]
Here are the screenshots:

![image](https://cloud.githubusercontent.com/assets/3050556/8913558/2de1a682-3489-11e5-9401-be2d0380d03e.png)
![image](https://cloud.githubusercontent.com/assets/3050556/8913562/36b01e2e-3489-11e5-98ba-7dbbe09fc87b.png)

I have a total of 764 items

**Comment by gdrewb-valve** [comment]
This is a problem on Windows also and we've passed it on to the larger team.  They're looking into it and it won't be tracked here.
