### ISSUE TITLE
[Ubuntu] Random game updates in Steam

### ISSUE THREAD

**Issue by udithishara** [ValveSoftware/Dota-2#2818]
#### Your system information

* System information from steam:
  * [System Information](https://gist.github.com/udithishara/60556f69ee83ba81d8f86c9111d5479c)
  * [System Runtime Diagnostics](https://gist.github.com/udithishara/2b93efa4655bd0d92ce224ed99f74e31)
* Have you checked for system updates?: **Yes**
* Are you using the latest stable video driver available for your system?: **Yes**
* Have you verified the game files?: **Yes**

#### Issue:
Random `1.1/1.3 GB` updates are being shown up for Dota2, Sometimes If the game is already opened and I click on "Find Match" and there are no updates and able to search for a match, but if i close the game and try to open it again this would come up, friends in the party using Windows aren't getting these updates so they're definitely a Linux client issue

Sometimes multiple times during the day this would show up as available update and start downloading, I've already removed all the workshop content in-case it was causing this, but still happening (as I'm typing this restarted steam and Voila, it's downloading again)

#### Screenshot
![Screenshot from 2024-09-14 09-35-41](https://github.com/user-attachments/assets/9056a52a-55a0-4e8b-811d-fa305885c3e2)

**Comment by kisak-valve** [comment]
Hello @udithishara, you're showing Steam pulling in a shader pre-cache update for the game. You can verify this by reading the mouse tooltip when you hover over the ⓘ symbol beside the game's name.
