### ISSUE TITLE
mac os sequoia fog of war problem

### ISSUE THREAD

**Issue by petarivanov198** [ValveSoftware/Dota-2#2820]
#### Your system information

* System information from steam : MacBook Pro 15-inch, 2018 Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?:Yes

I updated my Macbook to latest Mac OS Sequoia and i started getting strange behavior with fog of war. Randomly my map becomes dark. I found solution to lower resolution to 1024x640, but in that way the game is almost unplayable.. Do we have any fix for that?

**Comment by kisak-valve** [comment]
Hello @petarivanov198, this issue is already being tracked at #2027. Closing as a duplicate.
