### ISSUE TITLE
[Linux] GameStateIntegration sends no data

### ISSUE THREAD

**Issue by Ricaz** [ValveSoftware/Dota-2#2826]
I made the config file in `~/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/cfg/gamestate_integration_dotahelper.cfg`:
```
"dotahelper"
{
    "uri"          "http://localhost:3100/"
    "timeout"      "5.0"
    "buffer"       "0.1"
    "throttle"     "0.1"
    "heartbeat"    "10.0"
    "data"
    {
        "auth"            "1"
        "provider"        "1"
        "map"             "1"
        "player"          "1"
        "hero"            "1"
        "abilities"       "1"
        "items"           "1"
        "events"          "1"
        "buildings"       "1"
        "league"          "1"
        "draft"           "1"
        "wearables"       "1"
        "minimap"         "1"
        "roshan"          "1"
        "couriers"        "1"
        "neutralitems"    "1"
    }
}
```

I'm sure it's the correct dir, as I can see files are written to when Dota opens/closes.

Then I made a test web server:
```
const express = require('express')
const app = express()
const port = 3100

app.post('/', (req, res) => {
  console.log(req.body)
  res.send('pong')
})

app.listen(port, () => {
  console.log(`Listening on port ${port}`)
})
```
I tested it with `curl -X POST http://localhost:3100` and it responds.

I added `-gamestateintegration` launch parameter and started a game. No traffic.
I tried different ports, checked Dota logs, but nothing shows up.

Am I doing something wrong?
Can anyone confirm this even works on Linux?

Thanks!

**Comment by kisak-valve** [comment]
Hello @Ricaz, this issue is already being tracked at #2333. Closing as a duplicate.
