### ISSUE TITLE
[linux][alsa] buffer underrun

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#283]
In each dota2 reborn session, after a while playing the game, I get often an alsa buffer underrun then rainy audio.
The alsa log message is spamed in the steam client log.
I could not find any pattern in order to reproduce.

**Comment by sylware** [comment]
I confirm, it happens quite consistenly. I just need to play for a while and it happens most of the time. I use an USB audio device.

**Comment by davidw-valve** [comment]
Can you paste the exact error message you get from alsa?

How long does it take before it happens?

Have you tried using pulse audio and seeing if the problem goes away?

**Comment by sylware** [comment]
"ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred"

There are no time pattern I could see.

I don't have pulseaudio.

**Comment by sylware** [comment]
My usb audio output device is fried.
I switched to the internal sound chip on my mainboard.
Still get sometimes the alsa underrun messages, but
it seems to recover. The sound is ok and 
not crackling anymore.
