### ISSUE TITLE
Exiting Dota2 will generate a lot of logs with warning "kwin_wayland_drm: atomic commit failed: Invalid argument"

### ISSUE THREAD

**Issue by 1nj0k** [ValveSoftware/Dota-2#2845]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in  
[System Information](https://gist.github.com/1nj0k/a75a7a174e076e72b863a0d8e35edd8f):
[Steam Runtime Diagnostics](https://gist.github.com/1nj0k/d68f3af37b8486d7a48bd8d334a205a5)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Exiting Dota2 generates a lot of logs with message "kwin_wayland_drm: atomic commit failed: Invalid argument". These messages are taking up a lot of my storage.

[logs](https://gist.github.com/1nj0k/2c826a24ac7a7cce32f3817f259f5d0a).

#### Steps for reproducing this issue:

1. Launch dota2
2. Exit it and check logs

**Comment by kisak-valve** [comment]
Hello @1nj0k, I expect that kwin is generating these messages, not the game.

This issue should be reported to the KDE dev(s).

**Comment by Zamundaaa** [comment]
Yeah, please make a bug report about this at https://bugs.kde.org/enter_bug.cgi?product=kwin, for the component platform-drm.

Most likely this is caused by the GPU driver doing something weird, but we can investigate that further in the kde bug report.

**Comment by 1nj0k** [comment]
Thanks, I will report it. [495843](https://bugs.kde.org/show_bug.cgi?id=495843)

I just played Dota2 and it generated 30w warning logs. It is insane.

**Comment by 1nj0k** [comment]
It is fixed in kwin 6.2.4.
