### ISSUE TITLE
Mouse Click Dont Work New Update

### ISSUE THREAD

**Issue by sakmalh** [ValveSoftware/Dota-2#2848]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. New Kez Update on Linux
Dota is not responsive. My mouse clicks dont work. I was able to "Esc" out of the Kez Initial Screen. The rest I cant do anything cause of mouse click does not work

**Comment by AlienJust** [comment]
Do you use multi monitor setup? I had the same issue. Then I moved Dota window to another monitor and mouse became responsible. Then in Dota settings  I selected another monitor and moved window to my primary monitor :-)

**Comment by gostapit** [comment]
Same here, i have dual monitor setup.  Windowed mode (launch option '-sw' ) works fine, though.

**Comment by stiandel** [comment]
Same here, dual monitor, Hyprland, has anyone encounter the way to fix this? or maybe is a wayland problem?

**Comment by sakmalh** [comment]
Try adding -autoconfig in launch options it worked for me

**Comment by stiandel** [comment]
> Try adding -autoconfig in launch options it worked for me
> 

Could you elaborate a little more please, add where? When you start "Steam"?

**Comment by sakmalh** [comment]
> > Try adding -autoconfig in launch options it worked for me
> 
> Could you elaborate a little more please, add where? When you start "Steam"?

Steam -> Library -> Right Click Dota -> Properties -> General -> Launch Options 

In Launch Options copy and paste the below 

` -autoconfig`
