### ISSUE TITLE
[OS X] Crashing after quick fast-forwarding a replay

### ISSUE THREAD

**Issue by michaelkclements** [ValveSoftware/Dota-2#285]
There's a bug that crashes Dota when you watch a replay and press the 10s forward button over and over.

I know it's a pretty harsh one but I was trying to find the time of an event in the game I was watching and it crashed after pressing it again and again.

I've tried it several times and pressing it quickly gets it to crash quicker it looks like.

Here's a pastebin of the crash log http://pastebin.com/5p6tU7sf

**Comment by gdrewb-valve** [comment]
Confirmed on Windows, passing to the larger team.
