### ISSUE TITLE
( Linux ) Spoon Man Mini game error

### ISSUE THREAD

**Issue by OrangeTomato-1** [ValveSoftware/Dota-2#2851]
MOUSE ISSUE

1. Played the mini game as I was queueing for a game.

2. Accepted the game while the mini game is running. 

3.  Hero selection, and is where error persisted:

-  Mouse did not show and did not work
( but refreshing showed the mouse, and it works perfectly outside dota 2) 

- Could not select my hero, even with enter.

**Comment by slavietes** [comment]
This is fixed for the next patch.
