### ISSUE TITLE
The final game "Nest of thorns" crash on Mac

### ISSUE THREAD

**Issue by Spoonychopin** [ValveSoftware/Dota-2#2853]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

The final game "Nest of thorns" keep crashing on Mac, can't play
 
<img width="2560" alt="Screenshot 2024-11-09 at 22 43 32" src="https://github.com/user-attachments/assets/cbdb771a-a997-4ca5-b81d-57fb178a0e55">
<img width="305" alt="Screenshot 2024-11-09 at 22 46 44" src="https://github.com/user-attachments/assets/c8876918-82f4-4371-a1f0-0b12d855c580">

**Comment by blondi126** [comment]
have the same problem

**Comment by robikudor** [comment]
I have a different mac configuration but the same error. Any idea when will this be fixex? 
<img width="277" alt="Screenshot 2024-11-11 at 11 10 39" src="https://github.com/user-attachments/assets/f31a8cc0-25dc-421c-b88d-9f2f05b3b68e">

**Comment by deveshXm** [comment]
facing the same issue

**Comment by avigavin** [comment]
Same issue

**Comment by danginsburg** [comment]
We shipped a fix for this in the update yesterday, please give it a try again.  Thanks for the reports!

**Comment by deveshXm** [comment]
i'm playing from sea region and I've updated the game. yet it is still crashing @danginsburg 

Error:
`game/client/dota/panorama/crownfall/survivors/dota_survivors_player.cpp (1370) : Assertion Failed in function void CSurvivorsPlayer::LevelUpPowerUp(SurvivorsPowerUpID_t, const CSurvivorsUpgradeDefinition &)():
fnCreateInstance
`

**Comment by Spoonychopin** [comment]
> We shipped a fix for this in the update yesterday, please give it a try again. Thanks for the reports!

Thanks for the help! But it still crash with the error message before it start @danginsburg

**Comment by robikudor** [comment]
Same here @danginsburg. Game still crashes with the error.

**Comment by vladik1337228pro** [comment]
still the same problem

**Comment by YaroslavBoyev** [comment]
small indie dev company... Not enough money to buy 1 Mac and test the game... Still not working

**Comment by DeniKhadzhiev** [comment]
That's hilarious how they can't just test their own game after the update

**Comment by danginsburg** [comment]
Sorry, there was a similar bug on Windows and I thought the fix for that would fix this problem.  It turned out to be a macOS-specific problem.  We have a fix, should be in the next update.

**Comment by Spoonychopin** [comment]
HI just want to report that the game finally can run successfully now and there is no lag, thanks for your help!!!!! @danginsburg
