### ISSUE TITLE
Queen Imperia Minigame Freezes/Crashes Game

### ISSUE THREAD

**Issue by avigavin** [ValveSoftware/Dota-2#2855]
#### Your system information

* System Info - (https://gist.github.com/avigavin/0d8634b1ec713a1ce5d1146c56363398)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Expectation: 

Launch the final queen imperia minigame.

What Happens:

The game freezes and the following error message is put on the screen.
game/client/dota/panorama/crownfall/survivors/dota_survivors_player.cpp (1370) : Assertion Failed in function void CSurvivorsPlayer::LevelUpPowerUp(SurvivorsPowerUpID_t, const CSurvivorsUpgradeDefinition &)():

fnCreateInstance

#### Steps for reproducing this issue:

1. Launch crownfall minigame
2. Go through loading screen and hit play
3. Game freezes and crashes

**Comment by kisak-valve** [comment]
Hello @avigavin, this issue may be fixed in the Dota 2 7.37e update. Please retest.

**Comment by kisak-valve** [comment]
Closing pending feedback.
