### ISSUE TITLE
Processing SDL events took 50.1ms

### ISSUE THREAD

**Issue by sethdusek** [ValveSoftware/Dota-2#2857]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/SethDusek/fb546be727e6b24cef08b9bdbc9ad73a
Steam Runtime Diagnostics: https://gist.github.com/SethDusek/03737a5f2d36509fb1999a566a01aaba
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Every game after 20-30 minutes, some bug occurs where suddenly my mouse movements lag the game. I get this message in console "Processing SDL events took 50.1ms" and whenever I move my mouse I get huge frame-time spikes. This problem persists even if I disconnect and reconnect. The only way to solve it is to restart the game. Once this problem occurs, it also happens in main menu/all other screens as well

I have not played dota 2 much for the past few months, so I'm not sure how long this issue has been in the game but it's *atleast* since before the Kez update. I also have a 2000Hz mouse but it was not an issue on my old system (ryzen 5 2600) and it shouldn't be one on my new one either (Ryzen 7 7800x3d)
![image](https://github.com/user-attachments/assets/55f43118-fe22-43a3-a271-259ad49c722b)

#### Steps for reproducing this issue:

1. Play a match for 20-30 minutes, not sure how else to reproduce it

**Comment by kisak-valve** [comment]
Hello @SethDusek, you've described the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446. Closing in favor of the older issue report.
