### ISSUE TITLE
Nov 8 (Kez) update Vulkan fps drops in half game stutters after 25-30 min of gameplay

### ISSUE THREAD

**Issue by dejvuspec** [ValveSoftware/Dota-2#2862]
#### Your system information

System information: [gist](https://gist.github.com/dejvuspec/182fee31bf22235a9afb0a30984df5fb)
Steam Runtime Diagnostics: https://gist.github.com/dejvuspec/627d66e8137e7128630b92fde096a680
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After recent update Nov 8 (Kez update) after playing for 25-30 mins game fps drops in half and it starts to stutter non stop.
Before that update Dota 2 was running perfectly fine for over 6 months (had similar issue before but it was patched by game).
Restarting game fixes problem but is not accepted solution.
This is recurring bug from before and it's 100% Dota 2 fault.
I don't have any issues with running other games under vulkan being it native or over proton. 

#### Steps for reproducing this issue:

1. Play game for 25-30 mins using Vulkan
2. Fps drops in half and game starts to stutter non stop

**Comment by kisak-valve** [comment]
Hello @dejvuspec, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11446. Closing as a duplicate.
