### ISSUE TITLE
Mouse and keyboard suddenly out of control

### ISSUE THREAD

**Issue by Spoonychopin** [ValveSoftware/Dota-2#2869]
<img width="1059" alt="Screenshot 2024-12-05 at 10 15 53" src="https://github.com/user-attachments/assets/403f5a3c-d440-4840-a918-cbd7e7294dae">
<img width="273" alt="Screenshot 2024-12-05 at 10 16 14" src="https://github.com/user-attachments/assets/1dc78b30-1e99-4658-80dd-9f52211b6aa9">

There has been a problem since the updates this week; I have had to abandon games since yesterday.
Starting the game, the mouse and keyboard are not working smoothly; it is hard to describe like sometimes, the mouse will continue to move in a direction can't move, or they key board suddenly can't use until enemy kill me. This is not happens on the DEMO hero mode.

I wonder if you also have this problem, it never happens previouly. I have no idea which setting is wrong but I can't play now.

**Comment by Spoonychopin** [comment]
@danginsburg

**Comment by xrisk** [comment]
I have this exact same problem. Not sure if it’s something to do with my setup, but this never happens outside of Dota.
