### ISSUE TITLE
[Regression] After the latest update (July 28), watching games from the watch tab doesn't work anymore

### ISSUE THREAD

**Issue by shaddow2k** [ValveSoftware/Dota-2#287]
As stated in the title, watching games from the watch tab in the main menu doesn't work anymore.

Not sure if Linux specific, as I have no Windows installation, but it worked before. Judging from the 0 spectators for the top ten games I guess it is a general problem though.

Note: Watching games via rightclicking a friends name still works.

**Comment by gdrewb-valve** [comment]
Are you watching live games?  I just tried it and there were people spectating on the live games page.  Were you trying to download a replay?

**Comment by shaddow2k** [comment]
I can confirm that it is today working as intended.

Sorry for my sparse description of the problem. Yesterday I tried to spectate live games. The list of games was there on the left, but when I clicked one game, the middle pane (player names, map) stayed empty, so I couldn't click the watch game button.

I guess it was a server issue then? Feel free to close the issue :smile:

**Comment by gdrewb-valve** [comment]
Thanks, we'll close and see if it comes up again.
