### ISSUE TITLE
Left Alt Button not working on auto-cast

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#288]
Tried playing Clinkz and used Alt+W to auto cast the second skill, it didn't work. Source 1 works.

**Comment by gdrewb-valve** [comment]
Do you mean toggling auto-cast on and off?  Does this happen in the hero demo?  I just tried a quick test with Clinkz demo, levelled up and selected the second skill and was able to toggle auto-cast.

There are a couple of other bugs in here about people with environments where Alt is meaningful to the window manager, does it mean anything on your system?

**Comment by budimanjojo** [comment]
I tried it in Bot Match. I'm using 3 environments, this happened on Cinnamon. Will try kde and xfce when I have time. But Source 1 works though, so I don't think this is DE issue.

**Comment by budimanjojo** [comment]
Weird, I tried it again on a Bot Match and now it works. I was pretty sure it didn't work earlier. Closing this for now.

**Comment by sasa1024** [comment]
This is still happening for me and some of my friends (where "alt+cast" doesn't switch auto-cast on and off). It only happens in some sessions of the client (it's broken in all the games until I restart the client or my pc) and none of us have any idea when it happens.
I can still right-click on the level for switching auto-cast when the "alt+cast" is broken.
