### ISSUE TITLE
dota 2 reborn just not start, ubuntu 15.04   64 bit, overriden libstdc6

### ISSUE THREAD

**Issue by danil149** [ValveSoftware/Dota-2#289]
Dongle firmware /home/igma/.steam/linux64/../controller_base/d0ggle.bin loaded, version 1435869091.
and nothing happened, source1 dota work well

**Comment by danil149** [comment]
maybe the reason is using system  libstdc6.so.6, without this steam not working

**Comment by budimanjojo** [comment]
Run using steam-runtime.

**Comment by crisim** [comment]
i had the same issue, i resolved using this http://askubuntu.com/questions/614422/problem-with-installing-steam-on-ubuntu-15-04/652566#652566

**Comment by RenwarKarim** [comment]
what is steam-runtime and how do i use it?

**Comment by gdrewb-valve** [comment]
It's a binary compatibility layer provided by Steam and used automatically by default when launching from Steam.  It can be overridden in various ways but generally if you haven't specifically done something and you are launching from Steam on Linux you'll be using the Steam runtime.

**Comment by gdrewb-valve** [comment]
@danil149 do you get any console output if you run from a terminal?

This looks more like a Steam runtime compatibility issue than a Reborn issue so I'm wondering whether to close this.
