### ISSUE TITLE
[Linux] Unable to join games when partied with another Linux user and/or while on the same network.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/Dota-2#29]
While grouped with another Linux user on the same network, connecting to games fails to load one of the users. Console repeatedly attempts to reconnect, then fails after 30 retries.

Worth mentioning as well is a seemingly identical issue started happening in CSGO a short while ago, and is reported at [bug #389](https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/389).

[System info](https://gist.github.com/ramma/925cc19fb6fd7805979e)

**Comment by gdrewb-valve** [comment]
This happens on Windows too and so is outside of the scope of this tracker but the larger team says that something related to this will be in the next update.
