### ISSUE TITLE
[linux] global loadout lost

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#290]
Each time I play a game, I have to set my global loadout again (music pack/ward/courrier...)

**Comment by gdrewb-valve** [comment]
I don't think this is all hooked up yet.

**Comment by sylware** [comment]
On Sun, Aug 02, 2015 at 09:05:32AM -0700, Drew Bliss wrote:

> I don't think this is all hooked up yet.

A recent update resets the loadout each time I start a game.
It was keeping my loadout settings a 1 or 2 weeks ago.

**Comment by gdrewb-valve** [comment]
Looks like it happens on Windows also, I've passed this on to the larger team.
