### ISSUE TITLE
[linux] On focus change, game crashes

### ISSUE THREAD

**Issue by diegogmx** [ValveSoftware/Dota-2#292]
Plasma 5
nvidia 352.30
spanish kbd

on focus change (alt tab, changing volume [hence showing the volume indicator]) will crash dota, this only happens in game and if focus changes in the current monitor, if i open the main menu on a game and click on my second display it works ok.

i got this stack trace running steam from bash, the fact that inmediately before the crash the library architecture issue appears seems quite strange to me, maybe it has some relation despite the fact that many of those appear during steam execution causing failure

ERROR: ld.so: object '/home/diego/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
assert_20150803065052_1.dmp[30819]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150803065052_1.dmp
/home/diego/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 98: 30769 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 30769 
assert_20150803065052_1.dmp[30819]: Finished uploading minidump (out-of-process): success = yes
assert_20150803065052_1.dmp[30819]: response: CrashID=bp-65c3d38c-990c-490e-8d38-76e5d2150803
assert_20150803065052_1.dmp[30819]: file ''/tmp/dumps/assert_20150803065052_1.dmp'', upload yes: ''CrashID=bp-65c3d38c-990c-490e-8d38-76e5d2150803''
pid 30819 != 30817, skipping destruction (fork without exec?)

**Comment by gdrewb-valve** [comment]
The crash reported is in the NVIDIA driver so you may want to report this to NVIDIA also.

I tried starting a bot game and I was able to alt+tab away and back without a problem.  What resolution and video mode are you running at (I was using my monitor settings so desktop-friendly fullscreen).  If you're running desktop-friendly do you have the minimize-on-focus-loss checkbox selected or not (I tried both ways, no difference)?

**Comment by diegogmx** [comment]
this one appearently got fixed with the new driver build, updated today and its working fine
