### ISSUE TITLE
Fortify button click area

### ISSUE THREAD

**Issue by diegogmx** [ValveSoftware/Dota-2#293]
only the upper portion of the fortify button is responsive, the rest seems to work as if clicking off screen, quite troublesome some times, dont know if its linux specific

**Comment by gdrewb-valve** [comment]
I was not able to repro this on Windows or Linux.  What resolution and video mode are you running at (I was using 1920x1200 borderless window).

**Comment by diegogmx** [comment]
in my case 1600x900 df fullscreen,
in the attached pictures you can see what's happening exactly
![snapshot2](https://cloud.githubusercontent.com/assets/4988994/9050582/8e25593e-3a25-11e5-8ecc-e078b0b4a0a1.png)
![snapshot3](https://cloud.githubusercontent.com/assets/4988994/9050583/8e262c42-3a25-11e5-815c-f92f5300901a.png)

in the first one the pointer is out of bounds, you can easily realize about that as it is the system pointer
in the second one the pointer is inside bounds as its the dota pointer, if you click on the icon in the first situation it wont react, btw i have 2 displays if that helps

**Comment by gdrewb-valve** [comment]
If you use a borderless window instead of df fullscreen does that change the cursor behavior?

**Comment by diegogmx** [comment]
no it doesnt, now however thanks to your question i realized whats causing this, kde screen edge functions, appearently they have higher priority than a fullscreen window, so if you have any function assigned to the bottom right edge it will override dota in the lower right part, idk if this can be work around

**Comment by gdrewb-valve** [comment]
Great, thanks for pinning down the issue.  I don't know what can be done but we'll investigate further in the future.

**Comment by gdrewb-valve** [comment]
After discussion with the SDL devs there doesn't appear much that SDL can do. The window is decorated as a fullscreen window and after that it's up to the window manager as to whether it allows WM behaviors or not. Closing this as it's not a Reborn issue.
