### ISSUE TITLE
Certain particles an effects are visible through objects

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#295]
Similar to https://github.com/ValveSoftware/Dota-2-Reborn/issues/207
This issue was fixed, but some particles and light effect are still not blocked by objects. See screenshots. 
![capture d ecran 2015-08-03 a 18 39 55](https://cloud.githubusercontent.com/assets/4463576/9042583/f92851c0-3a0f-11e5-9fec-31ad5150ba62.jpg)
Here some sphere produced by the ancient is visible through the broken arch.

![capture d ecran 2015-08-03 a 18 55 15](https://cloud.githubusercontent.com/assets/4463576/9042771/479d30a4-3a11-11e5-9e6f-537e0d426145.jpg)
Here some light particules produced where creeps appear are visible through the barrack. 
This is on an iMac with gtx 775M, OS X 10.9.5, highest settings.

**Comment by danginsburg** [comment]
This occurs on Windows/DX9 so is not specific to the Mac/Linux version.

**Comment by gdrewb-valve** [comment]
I've forwarded this to the larger team and it won't be tracked here.
