### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by r3pek** [ValveSoftware/Dota-2#3]
First, there's no "Play reborn" button on the source 1 client.

If I try to launch it directly from Steam, I get a error message saying it didn't find the executable. Looking at the game/ directory inside the dota dir, it's actually missing the binaries.

**Comment by Plagman** [comment]
The "play reborn" button has now been enabled on the regular client, this will be fixed with its next update.

After you opted-in to the Reborn DLC in the game properties, use the 'verify game files' functionality from Steam to get the binaries.

**Comment by suhaaktas** [comment]
i cant launch the game as well. the game crashes on the inital loading screen. trying verifying the game files. will post the result asap.

**Comment by r3pek** [comment]
OK, I used Verify Files again and it works now. (It started in borderless windowed mode but after changing it in settings, all is fine now)

**Comment by gdrewb-valve** [comment]
Closing as this is resolved.
