### ISSUE TITLE
[linux] Can't indicate position on the minimap during pick phase

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#300]
At the beginning of a game, during the pick phase, i can't indicate on the minimap where i intend to go (bot, mid, top, jungle) by clicking on the minimap.
When i click on the minimap, nothing happens (the picture of my selected hero doesn't appear on the minimap).

**Comment by gdrewb-valve** [comment]
This happens on all platforms and the larger team is aware.

**Comment by ghost** [comment]
Ok thanks.
