### ISSUE TITLE
[Linux] Health font too large, enemy names in low quality font

### ISSUE THREAD

**Issue by tiburcillo** [ValveSoftware/Dota-2#301]
Hi Valve, great work on the Reborn linux client. I've noticed that the hp label text is too large in the linux client. 
![screenshot from 2015-08-08 10 21 46](https://cloud.githubusercontent.com/assets/13047647/9149735/b39bf25a-3db7-11e5-8268-972dbb3514d7.png)

Is this as designed or rather related to my system? Here's my system info:
System:    Host: calcus Kernel: 4.1.4-040104-generic x86_64 (64 bit) 
           Desktop: Cinnamon 2.6.13  Distro: Linux Mint 17.2 Rafaela
Machine:   Mobo: ASRock model: 990FX Extreme3 Bios: American Megatrends version: P1.70 date: 10/03/2013
CPU:       Octa core AMD FX-8350 Eight-Core (-MCP-) cache: 16384 KB flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) 
           Clock Speeds: 1: 1400.00 MHz 2: 2100.00 MHz 3: 1400.00 MHz 4: 2800.00 MHz 5: 1400.00 MHz 6: 2100.00 MHz 7: 4000.00 MHz 8: 1400.00 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280] 
           X.Org: 1.15.1 drivers: ati,radeon (unloaded: fbdev,vesa) Resolution: 1920x1200@60.0hz 
           GLX Renderer: Gallium 0.4 on AMD TAHITI GLX Version: 3.0 Mesa 10.6.3
Audio:     Card-1: Advanced Micro Devices [AMD/ATI] Tahiti XT HDMI Audio [Radeon HD 7970 Series] driver: snd_hda_intel 
           Card-2: Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA) driver: snd_hda_intel 
           Card-3: Plantronics driver: USB Audio 
           Sound: Advanced Linux Sound Architecture ver: k4.1.4-040104-generic
Network:   Card: Broadcom NetLink BCM57781 Gigabit Ethernet PCIe driver: tg3 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 00:25:22:fb:06:97
Drives:    HDD Total Size: 256.1GB (0.0% used) 1: id: /dev/sda model: KINGSTON_SV200S3 size: 256.1GB 
Partition: ID: / size: 359G used: 38G (12%) fs: ext4 ID: /boot size: 91M used: 57M (67%) fs: ext4 
           ID: swap-1 size: 8.70GB used: 0.00GB (0%) fs: swap 
RAID:      No RAID devices detected - /proc/mdstat and md_mod kernel raid module present
Sensors:   System Temperatures: cpu: 28.8C mobo: N/A gpu: 60.0 
           Fan Speeds (in rpm): cpu: N/A 
Info:      Processes: 247 Uptime: 23 min Memory: 2867.3/7939.2MB Client: Shell (bash) inxi: 1.9.4

I also have noticed this on my laptop:
System:    Host: latrogestabilis Kernel: 4.0.4-040004-generic x86_64 (64 bit) Desktop: Gnome Distro: Linux Mint 17.1 Rebecca
Machine:   System: TOSHIBA product: SATELLITE L50-B version: PSKT4E-06F008DU
           Mobo: Type2 - Board Vendor Name1 model: Type2 - Board Product Name1 version: Type2 - Board Version
           Bios: INSYDE version: 1.90 date: 10/08/2014
CPU:       Dual core Intel Core i5-4210U CPU (-HT-MCP-) cache: 3072 KB flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) 
           Clock Speeds: 1: 2312.250 MHz 2: 1712.062 MHz 3: 1753.218 MHz 4: 1700.062 MHz
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller 
           X.Org: 1.15.1 drivers: intel (unloaded: fbdev,vesa) Resolution: 1366x768@60.0hz 
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 10.7.0-devel (git-101a738 2015-06-25 trusty-oibaf-ppa)
Audio:     Card-1: Intel Lynx Point-LP HD Audio Controller driver: snd_hda_intel Sound: ALSA ver: k4.0.4-040004-generic
           Card-2: Intel Haswell-ULT HD Audio Controller driver: snd_hda_intel
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: c4:54:44:e3:fb:b6
           Card-2: Intel Wireless 3160 driver: iwlwifi 
           IF: wlan0 state: up mac: 34:de:1a:19:2f:80
Drives:    HDD Total Size: 256.1GB (45.9% used) 1: id: /dev/sda model: M4 size: 256.1GB 
Partition: ID: / size: 231G used: 110G (51%) fs: ext4 ID: swap-1 size: 4.21GB used: 0.21GB (5%) fs: swap 
RAID:      No RAID devices detected - /proc/mdstat and md_mod kernel raid module present
Sensors:   System Temperatures: cpu: 57.0C mobo: N/A 
           Fan Speeds (in rpm): cpu: N/A 
Info:      Processes: 192 Uptime: 15:54 Memory: 623.8/3872.1MB Client: Shell inxi: 1.8.4

**Comment by tiburcillo** [comment]
If I may add an update: It seems this is related to the Mesa version. I have updated to Mesa 11 devel, now the fonts appear even larger. Let me know if I can give any more information.
![screenshot from 2015-08-10 17 33 26](https://cloud.githubusercontent.com/assets/13047647/9199907/7cef0e8c-4045-11e5-8776-672e8a643734.png)

**Comment by engywook** [comment]
![health](https://cloud.githubusercontent.com/assets/921388/9234256/10181e68-4138-11e5-9e3b-d9d35d8e7b11.png)
That is trying to display healthbars, names doesn't work for me at all.

https://gist.github.com/engywook/7679f344473b2095ce2d#file-gistfile1-txt

**Comment by gdrewb-valve** [comment]
@engywook, take a look at #120 and see if that applies to you.

**Comment by engywook** [comment]
@gdrewb-valve Yeah, installing ttf-liberation worked, cheers.

**Comment by danginsburg** [comment]
We are still working on trying to repro this one.  I haven't been able to repro it yet.

**Comment by tiburcillo** [comment]
Hi all, I have noticed that I have the same behavior in the Source 1 Dota client on linux. I think it's the liberation fonts that are just a bit bigger than Arial. Probably also distro dependant (using Linux Mint). 
It's not gamebreaking anyways, maybe it gets fixed with Vulkan. :smile:

**Comment by chrylis** [comment]
I have the same problem with Mesa 10.6.4 on Arch, Liberation installed.

**Comment by rcagantas** [comment]
I'm on a Mac and the fonts are also larger than it should be. Any workarounds?

**Comment by gdrewb-valve** [comment]
You're the first person that has reported an issue on a Mac, it's hard to say what might be going on or how to work around it.  Do you have any modified resolution scaling or DPI options?

Also, what are you comparing against when the fonts look too large?  The Windows version?

**Comment by rcagantas** [comment]
![2016-02-12_00004](https://cloud.githubusercontent.com/assets/1592525/12994951/c828eaf8-d15e-11e5-9cf4-ddab6554af8e.jpg)

This is what I see (Forgive the name. I just found the longest name I could see and spectated). I'm comparing against what I assume to be the Windows version when I watch a Dota 2 Youtube clip. What I normally see is a the player name font to be a about the height of the health and mana bar combined. Here, it's much larger. 

On the video settings I use "Use my monitor's current resolution" and "Desktop-friendly fullscreen"

```
Processor Information:
    Model:  iMac13,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GTX 675MX

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x11a2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.46" x 13.19"  (26.89" diag)
                                            59.6cm x 33.5cm  (68.3cm diag)
    Primary VRAM: 1024 MB

Memory:
    RAM:  8192 Mb
```

**Comment by gdrewb-valve** [comment]
That's definitely not right.  :-)  Do you have any non-default OSX (not Reborn) resolution or DPI settings?  Reborn just asks CoreText for a font with a given size and that appears to work on most Macs, no idea why it would be different for you.  Reopening.

**Comment by rcagantas** [comment]
Resolution is just maxed. Didn't change anything. Should be at the bottom of my post. 
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440

**Comment by rcagantas** [comment]
Playing on a Macbook Air 2011 (Intel HD Graphics 5000) yields the same results. The only thing common between them is they are both running on Yosemite.

**Comment by gdrewb-valve** [comment]
Did the fonts change after the March 24 updates?

**Comment by rcagantas** [comment]
It did. But I don't think this was the intended effect. They are now quite fat. Of course, maybe this is how it's supposed to be and I'm just not used to it. At least it's not as wide and as tall as it used to be. 
![20160328001358_1](https://cloud.githubusercontent.com/assets/1592525/14066384/974a0a36-f47a-11e5-979a-2526cb17ee7e.jpg)

**Comment by gdrewb-valve** [comment]
They are supposed to be bold and the screenshot looks fairly correct.

**Comment by rcagantas** [comment]
Good news then. I think you might want to close the bug when we hear from the Linux guys.

**Comment by gdrewb-valve** [comment]
Seems like there are no new complaints so closing.

**Comment by chrylis** [comment]
I've been trying to figure out whether it still applies. I'm not _noticing_ anything amiss, so yeah, it seems fixed.
