### ISSUE TITLE
"Attack" on the minimap moves the camera to the target

### ISSUE THREAD

**Issue by lewisdiamond** [ValveSoftware/Dota-2#302]
On linux Arch, when I press the Attack key and click on the minimap (more often for shift queuing) instead of just dispatching the attack command to the location, it moves the camera to the location.

This is different from Dota 2 6.84 where "Attack" on the minimap keeps your camera at the same place but issues the attack command to the correct position.

Windows users told me they did not see this issue.

**Comment by gdrewb-valve** [comment]
I can't reproduce this on Linux (Ubuntu in my case).  What key do you have bound for attack?  Are you doing a single click in the minimap or multiple?

**Comment by lewisdiamond** [comment]
Found the problem. I had "quick attack" activated. (new feature in Reborn?)
