### ISSUE TITLE
Range spells display Bug

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#303]
Check video, hard to describe bug.

Caution weak English!

How to reproduce bug:
1. Pick bloodseeker, on 1 lvl take 2 skill.
2. Press 2 skill and try to change your current view area with mouse (while 2 skill is pressed and you have blue area displaying spell range).
3. Then rapidly try to take mouse from edge. Check video on 1:08 that's why i'm reporting this bug.
4. Engoy.

P.S. may be not OpenGL specific.
Video: http://youtu.be/DPlRe0F_WQE

**Comment by gdrewb-valve** [comment]
I was not able to repro this.

Can you post your system information from Steam?

**Comment by Pharmasolin** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-39-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Desktop x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.0.0-devel (git-7e5d563 2015-08-10 vivid-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x102
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 14,80" x 11,85"  (18,94" diag)
                                        37,6cm x 30,1cm  (48,1cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  3424 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  296317 Mb
    Largest Free Hard Disk Block:  120977 Mb

Installed software:

Recent Failure Reports:

**Comment by Pharmasolin** [comment]
Pick bloodseeker, press 2 skill (to see spell area) and then with this enabled skill try to change your view range, and then quickly take mouse from edge.

**Comment by gdrewb-valve** [comment]
That worked fine for me.

**Comment by Pharmasolin** [comment]
I will update mesa and will try again, also i have low graphics settings on.

**Comment by Pharmasolin** [comment]
# Still can reproduce bug, video

# http://youtu.be/A0q9lTS5m9M

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-39-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Desktop x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.0.0-devel (git-3c04a90 2015-08-11 vivid-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x102
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 14,80" x 11,85"  (18,94" diag)
                                        37,6cm x 30,1cm  (48,1cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  3424 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  296317 Mb
    Largest Free Hard Disk Block:  120769 Mb

Installed software:

Recent Failure Reports:
    Tue Aug 11 20:06:53 2015 GMT: file ''/tmp/dumps/assert_20150811230037_1.dmp'', upload yes: ''CrashID=bp-721e0006-c0e5-4e3e-a910-674c92150811''
    Tue Aug 11 20:07:02 2015 GMT: file ''/tmp/dumps/crash_20150811230653_10.dmp'', upload yes: ''Discarded=1''

**Comment by Pharmasolin** [comment]
By the way, my friend send me this photo: https://pp.vk.me/c622321/v622321191/487ec/YZRh-XLNcqc.jpg she were trying to open dota 2 beta, but received error, yesterday we were playing it and all was ok. She is using windows 7

AND

When i were in new dota (beta) i send her invite while she weren't in game, only online in steam, she accepted it and steam open for her old dota 2 (not beta).

**Comment by gdrewb-valve** [comment]
The new video is private, I wasn't able to watch it.

The networksystem issue is a known problem that will be fixed in the next update.

You'll want to report the invite issue in the regular Dota forums at dev.dota2.com.

**Comment by Pharmasolin** [comment]
Fixed here
https://www.youtube.com/watch?v=A0q9lTS5m9M

**Comment by gdrewb-valve** [comment]
Thanks, we'll check into it.

**Comment by gdrewb-valve** [comment]
Is the ranged spell issue still happening?

**Comment by gdrewb-valve** [comment]
Closing as this appears inactive.
