### ISSUE TITLE
[Linux] Cannot load into games anymore

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#306]
Since the last update I have a very serious issue when loading into games. Let me describe what happens in detail:
1. I click find match and accept
2. Dota shows the loading screen with the Dota logo for a longer time than normal
3. finally I load into the screen which shows which players have loaded up already, usually I'm last
4. I hear the compendium pings, but with longer pauses in between while the timer doesn't count down smoothly
5. timer reaches 0:00 after a time that is way too long, other people are already in the picking screen
6. the player list at the right goes blank
7. I'm stuck at that screen and have to disconnect
8. upon reconnecting I get into the picking screen and can pick a hero, but get no visual feedback, i.e. for me it looks like I still haven't picked
9. after another reconnect I'm into the game, but can't move. Everything looks like it's paused (i.e. heroes make their walking cycles, but don't move)
10. I get a little red message that I lost connection and will be disconnected in a few seconds
11. repeatedly reconnecting doesn't change anything. Sometimes I can see heroes move for a bit, but then everything stands still again
12. if someone pauses while I reconnect, I see the game paused when I come back, but can't unpause and also don't see the unpause when someone else does it

The same happens when I watch a match. I had this issue last night for the first time, right after dowloading a Dota2 update. After I abandoned the game, I could play another game flawlessly. I had the same issue again just now and now I'm in low priority and ruined my win rates on certain heroes.

**Comment by phoerious** [comment]
(I know, this is heavy off-topic, but I just lost the most infuriating low prio game ever because of this. With people who are just flaming all game and buying 11 brown boots. This needs to be fixed)

**Comment by gdrewb-valve** [comment]
Do you see any spew in a terminal, in particular anything about reliable sequence mismatches?  If so this is a known issue that affects all platforms.

**Comment by phoerious** [comment]
I can't tell and I don't want to try because I may have to abandon the game again. I still have to play two more low-prio matches and I really don't want to get any more of those. Last game was as bad as the first one with a void just buying a shadow amulet and sitting afk on the map all game.

**Comment by gdrewb-valve** [comment]
It's likely to be the same thing so the larger team will address this.

**Comment by phoerious** [comment]
Okay. Will there be a notice in the change log so that I know when I can play Reborn again?

**Comment by gdrewb-valve** [comment]
There'll definitely be a note when the reliable messaging is fixed and then hopefully that'll address everybody's issues.  There are numerous reports on dev.dota2.com and you can watch the discussion there also to see how it's going.

**Comment by micaelbergeron** [comment]
I have the same problem on ArchLinux.
Been playing the game until yesterday, where it all began.

I cannot load into games, the countdown are slowed down.
My ping soars up (like to 4000-6000) then I finally get kicked out of the pick screen.

I would like to give you my console output, but I can't find the file created by "condump".
Briefly, I have multiple network related errors, like "Weird GameRouterReply", "Received packet without an active session". Keep in mind that these come from the top of my head.

I can watch games without any problem.

Thank you for your support as usual.

**Comment by gdrewb-valve** [comment]
The larger team is looking at a set of networking issues and fixes will be coming in future updates.  Hopefully those will correct the problems you're seeing.

**Comment by phoerious** [comment]
I read through some of the reports in the dev forums. It looks like it is the exact same problem.
One more symptom to add maybe: when clicking the Reconnect button while you're affected by the bug, it first appears to do nothing, and then loads back into the game after quite a delay. I also had a problem with the find match button not doing anything, not sure if that is connected to this issue, though.

**Comment by gdrewb-valve** [comment]
A workaround for some issues has been made on Valve servers that may help here.  More complete fixes are in the works.

**Comment by zeroedout** [comment]
Thank you! It appeared to help in my last game, though I did encounter a sync issue a couple times. In that, it got a little laggy, then jumped to where the game really was. It did this literally three or four times in a 40 minute match. But it was perfect the rest of the time. I had ~33ms lag as shown by -ping.

**Comment by her001** [comment]
Looks like it fixed it for me and a few others who were also experiencing the issue. Thank you!

**Comment by gdrewb-valve** [comment]
The 8/13 update should fix the other cause of this.  If anybody is still seeing problems after updating please post here.

**Comment by rodlorric** [comment]
In my case, the game takes a very long time to join a match if I create it via a lobby (US East for example), but it does load after a while. In Windows the game loads much faster. (both are installed on a SSD).

Additionally I am unable to spectate games, at least reliably, most of the time the game will not load, it gets stuck loading.

I didn't try to join a matchmaking game.

Upon bringing down the console, this is what a I get:
![Console](http://i.imgur.com/9wMxsdy.jpg)

System Specs:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2668 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,98" x 12,28"  (24,29" diag)
                                            53,3cm x 31,2cm  (61,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  5958 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  100564 Mb
    Largest Free Hard Disk Block:  26705 Mb
```

**Comment by rodlorric** [comment]
Reporting back after the last patch (August 14):

I can watch games on DotaTV now and joining a match created via a lobby is pretty fast now.

No more messages in the console.

**Comment by gdrewb-valve** [comment]
Is anybody else having problems after the 8/14 update?

**Comment by artemklevtsov** [comment]
After 8/15 update I have disconnects anytime in the Overthrow.

**Comment by gdrewb-valve** [comment]
The Overthrow problem is a separate issue that occurs on all platforms and won't be tracked here.

http://dev.dota2.com/showthread.php?t=176861

If nobody is having non-Overthrow problems I'll close this.

**Comment by gdrewb-valve** [comment]
Closing.
