### ISSUE TITLE
[OS X Yosemite] Using skill on hero harder than dota 2

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#308]
Hi,

After many games, I can confirm that, there is something wrong when targeting hero.
Its harder and most of the time to miss skilling/attacking an hero, its like the hero area of target is too small.
This make you need to target/ hover your mouse precisely on the hero area of selection.

Its more harder to target hero that can easily escape as example Storm Spirit. Even the cursor changed to target cursor, clicking skill and clicking on it sometimes miss.

This doent happen on Dota 2, at first I thought because of my own issue, but trying it on both game can really feel the different. 

If any of you feels the same, please commend on this issue.

**Comment by Pharmasolin** [comment]
In beta default camera acceleration speed and camera speed is a bit different between default in old dota, as i think, but can be only personal feelings, about hero target area, i don't noticed it, may be you have different resolution in both dotas?

**Comment by rained23** [comment]
@Pharmasolin I have same resolution. at first I think its personal feelings too. But when I try it many times in both client, yes I can tell the targeting hero is easily miss. Sometimes I need to multiple times to cast a spell on hero and this never happen in old client.

**Comment by Pharmasolin** [comment]
How much you playing new dota?

**Comment by rained23** [comment]
is that relevant ? I do play many times that I think suitable to open an issue, I started Reborn from 
the beta rolled out. I just play MMR games on old client because of this issue.

**Comment by gdrewb-valve** [comment]
I doubt this is a Linux/Mac issue but we'll hold this open to see what people say.

**Comment by Pharmasolin** [comment]
At first when i were playing first hours in new dota, i have feeling that mid area in river where creeps have their routs (between coast), were bigger distance between coasts, but now it is ok, i dont play old dota and don't see any problem at all.

With using skill on enemy hero i don't have any problem too.

**Comment by tiburcillo** [comment]
I do have to admit that certain objects are harder to click in Reborn (Linux user here). I noticed this on the Gyro rocket for example and a few times where i wanted to right click a Windrunner to attack but  ground-moved instead. I'll to to get some more detailed information and a reproducible scenario.

**Comment by gdrewb-valve** [comment]
I've seen other reports of similar things on the regular forums (no reported platform but presumably Windows) so you aren't alone.  I'll pass this on to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team is aware of the issue and has made some changes.  As Reborn is running on a very different engine it isn't expected that things will match perfectly but major problems can be raised in the regular forums.
