### ISSUE TITLE
[Mac] Screen goes black(ish) when hero is dead

### ISSUE THREAD

**Issue by zbstof** [ValveSoftware/Dota-2#309]
In the regular dota2 client, when my hero becomes dead, the colors become somewhat bleak, but I can still see everything clearly
In the Reborn client, if I die I cannot see anything - terrain becomes too dark to see. My guess that contrast is all wrong:
![2015-08-14_00008](https://cloud.githubusercontent.com/assets/1374723/9269360/7fc7db92-4271-11e5-8cf2-11b45a0c1481.jpg)
Compare to screenshot from original client:
![2015-08-14_00019](https://cloud.githubusercontent.com/assets/1374723/9269449/85f8a2ac-4272-11e5-9380-554b091b381a.jpg)
My machine:
$ uname -a
Darwin Stas-MBP 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by danginsburg** [comment]
I have not been able to repro this, can you post your full system specs?

**Comment by zbstof** [comment]
<img width="1440" alt="screen shot 2015-08-20 at 07 36 55" src="https://cloud.githubusercontent.com/assets/1374723/9375924/2b64167c-470f-11e5-9d78-f7b609494d3c.png">
<img width="1440" alt="screen shot 2015-08-20 at 07 40 53" src="https://cloud.githubusercontent.com/assets/1374723/9375925/2b66f50e-470f-11e5-9fa1-a874fcdf93d7.png">

**Comment by zbstof** [comment]
Retina Display is in medium-detailed resolution configuration

**Comment by rained23** [comment]
happen to me too, when dead its so dark you cant see anything.

**Comment by dphildebrandt** [comment]
I noticed this only happens on the 2 highest basic video settings.

```
Processor Information:
    Model:  MacBookPro11,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel Iris

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xa2e
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.22" x 7.05"  (13.23" diag)
                                            28.5cm x 17.9cm  (33.6cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  16384 Mb
```

**Comment by MS90D3V** [comment]
Annoying as hell. I like to control courier when I'm dead to pick up items at secret shop, but I cannot see a thing and I'm afraid that my lovely courier gets killed. Please fix!

```
Modelnaam:  MacBook Pro
  Modelaanduiding:  MacBookPro11,2
  Processornaam:    Intel Core i7
  Processorsnelheid:    2 GHz
  Aantal processors:    1
  Totale aantal cores:  4
  L2-cache (per core):  256 KB
  L3-cache: 6 MB
  Geheugen: 8 GB

Intel Iris Pro:
  Chipsetmodel: Intel Iris Pro
  Type: GPU
  Bus:  Ingebouwd
  VRAM (dynamisch, max.):   1536 MB
  Fabrikant:    Intel (0x8086)
  Apparaatcode: 0x0d26
  Revisiecode:  0x0008
```

**Comment by danginsburg** [comment]
Thanks the tip about it only being at the highest video settings helped me repro it.  So I've got this repro'd on Intel HD 4000 (and clearly from reports it is also happening on Iris/Iris Pro).  It does not happen on NVIDIA GTX 650M on same Mac.  I'll see what I can do.

**Comment by danginsburg** [comment]
A temporary workaround: disable anti-aliasing, it is the setting that is causing the problem.  I am still looking into why.

**Comment by filipminev** [comment]
+1 have the same bug. (Disabling antialiasing fixes it for me too)

**Comment by zbstof** [comment]
Can confirm that disabling antialiasing fixes the issue for now

**Comment by danginsburg** [comment]
I have checked in a fix for this, it will be in the next release of dota.  The problem was that we were reading from/writing to the same texture when playing the death effect which can result in undefined behavior according to the OpenGL specification.  We were also sampling that texture as LINEAR and writing it as sRGB which was problematic.  I reworked things to use a ping-pong buffer approach and it works now with/without FXAA enabled.

**Comment by danginsburg** [comment]
My fix actually caused some regressions so it won't make it into the next update.  I'm still working on a fix that takes care of the regression.  The problem is well understood it's just tricky to fix without introducing any additional performance cost.

**Comment by danginsburg** [comment]
This is fixed, will be in the next update.

**Comment by danginsburg** [comment]
Fixed in 9/16 update.
