### ISSUE TITLE
Scoreboard not showing, keyboard layout issue? (ubuntu 15.04, plasma5, nvidia 352.21)

### ISSUE THREAD

**Issue by diegogmx** [ValveSoftware/Dota-2#31]
Scoreboard wont show when pressing º, the default key was `, tested it and changed it but didn't show up anyway, keyboard layout issues maybe?

**Comment by gdrewb-valve** [comment]
What keyboard layout are you using?  Do you have multiple layouts installed and switch between them?

**Comment by diegogmx** [comment]
spanish, usually switching to english

**Comment by gdrewb-valve** [comment]
What do you boot with?  If you do not change your keyboard layout after boot are you able to bind and use the key you want?

**Comment by gdrewb-valve** [comment]
Any luck when not switching the keyboard layout?

**Comment by gdrewb-valve** [comment]
Did you bind the key with one layout and try to use it in a different layout?

**Comment by diegogmx** [comment]
rebound it with this build, it works properly now.

2015-07-16 4:36 GMT-03:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
Thanks, closing.
