### ISSUE TITLE
[Mac] When taking screenshots on mac, they have wrong orientation

### ISSUE THREAD

**Issue by zbstof** [ValveSoftware/Dota-2#310]
When pressing F12, the result looks something like this:
![2015-08-14_00002](https://cloud.githubusercontent.com/assets/1374723/9269517/32e2d712-4273-11e5-9323-519b92e72d25.jpg)
My machine:
$ uname -a
Darwin Stas-MBP 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by gdrewb-valve** [comment]
This appears to be a Steam issue and not a Reborn issue (for example https://steamcommunity.com/discussions/forum/2/611696927910752291/) but we're talking to the Steam team about it.

**Comment by zbstof** [comment]
Well, in the old client screenshots are fine, so I would say, its reborn-specific.

**Comment by gdrewb-valve** [comment]
Except that in the link I posted there are users complaining about upside-down screenshots on Mac and they aren't using Reborn.

**Comment by danginsburg** [comment]
I have checked in a fix for this issue.  The fix will be in a future update to Steam (note Steam, not Dota 2 Reborn).  The issue impacts OSX games using OpenGL Core Profile.
