### ISSUE TITLE
[Mac] Swiping with 3 fingers to switch windows doesn't work inside client

### ISSUE THREAD

**Issue by zbstof** [ValveSoftware/Dota-2#311]
I works on old client.
see: "Swipe between full screen apps and spaces" under https://support.apple.com/en-us/HT204895
My machine:
$ uname -a
Darwin Stas-MBP 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by davidw-valve** [comment]
Do you have your video settings set to desktop friendly fullscreen, or exclusive fullscreen?

In exclusive fullscreen this would be expected.

**Comment by gdrewb-valve** [comment]
Closing pending more information.
