### ISSUE TITLE
[Linux]screenshots tell it all

### ISSUE THREAD

**Issue by suhaaktas** [ValveSoftware/Dota-2#312]
![](http://i.imgur.com/ILfn1uc.png)

![](http://i.imgur.com/5FLloWG.jpg)

detailed sysinfo : https://gist.github.com/suhaaktas/2943f098145c8df8cf0e#file-gistfile1-txt
Ubuntu 14.04 x86_64
Unity
Radeon HD6770 (fglrx) AMD closed source drivers

**Comment by danginsburg** [comment]
I suspect unfortunately an incompatibility with the Catalyst 15.3 driver in the fglrx package.  Can you either install Catalyst 15.7 (http://support.amd.com/en-us/download/desktop?os=Ubuntu%20x86%2064) or use the RadeonSI driver?  Both should work.

**Comment by suhaaktas** [comment]
currently there are some issues with 15.7 on ubuntu. tried to install it many times and failed every single time. and radeonSI is only for newer cards. is there any workarounds with 15.3?
fglrx and fglrx-updates packages both use 15.3 i guess?
http://www.ubuntuupdates.org/package_metas?exact_match=1&q=fglrx
http://www.ubuntuupdates.org/package_metas?exact_match=1&q=fglrx-updates

**Comment by computerquip** [comment]
Your card will work fine with the Radeon drivers.

**Comment by danginsburg** [comment]
I believe this is just a case of out-of-date AMD Catalyst drivers so I will close the issue.  If you disagree you can reopen it.

**Comment by zaktas15** [comment]
i have to reopen this issue since it turns out 15.20.1013 is actually 15.7 and since there is no way to play dota with source1.
http://askubuntu.com/questions/646436/catalyst-15-7-could-it-run-on-ubuntu-15-04

now i am using ubuntu 15.04 with fglrx-updates (amd catalyst 15.7).

**Comment by suhaaktas** [comment]
i have to reopen this issue since it turns out 15.20.1013 is actually 15.7 and since there is no way to play dota with source1.
http://askubuntu.com/questions/646436/catalyst-15-7-could-it-run-on-ubuntu-15-04

now i am using ubuntu 15.04 with fglrx-updates (amd catalyst 15.7)
