### ISSUE TITLE
[Linux] Keyboard key dont work

### ISSUE THREAD

**Issue by vacuumhdl** [ValveSoftware/Dota-2#313]
Key "q, w, e, r, t, y" and other char don't bind, but numbers "1, 2, 3" and spase work.
Keyboard Language - Russian and English.

Linux version 3.19.0-25-generic (buildd@lgw01-07) (gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) ) #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 (Ubuntu 3.19.0-25.26-generic 3.19.8-ckt2)

In dota2 not reborn this keys work.

**Comment by gdrewb-valve** [comment]
What kind of keyboard do you have?  What language do you boot in?  Do you switch your keyboard layout at any time?

**Comment by vacuumhdl** [comment]
install kubuntu - all work.

**Comment by gdrewb-valve** [comment]
Do you want to leave this open?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this should stay open.
