### ISSUE TITLE
[OS X Yosemite] Copy-Paste not working corretly

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#314]
Hi,

There is an issue when doing copy and paste in the chatbox. Copying text work using right click, but when using cmd+c or cmd+v are not working properly sometimes the copy paste mimic windows copy paste Ctrl + C or Ctrl + v. 

Copying text from outside of client not gonna work. But I think it works in Windows client.

**Comment by gdrewb-valve** [comment]
This worked properly for me.  I highlighted some text in a terminal, copied it, started Reborn, clicked in the chat box and did Command+V with no issue.  Does that work for you?

**Comment by rained23** [comment]
@gdrewb-valve Its work now, before it didnt work, maybe the latest 50 MB update fix this issue.
