### ISSUE TITLE
[Mac] Latency Spikes + Input Lag (when fps < 60, network fine)

### ISSUE THREAD

**Issue by vikrantpogula** [ValveSoftware/Dota-2#315]
Reborn Mac client seems to spike to 150-300ms latency (normal 60ms)  with lot of input delay. My network is fine for the entire duration. 

The input delay is not because of latency (150ms is playable).. its just input delay. 

Tested and discovered it occurs in a specific case whenever fps drops below 60.
- fps > 60 => `50-60ms`
- fps <= 60 => `150-300ms + input delay`

Tech Specs

```
MacBook Pro (first gen)
Intel Core i7 - 2.3 GHz
Nvidia GeForce GT 650M
OSX Yosemite (10.10)

Resolution : desktop-friendly fullscreen
VSYNC: off
```

I used to normally run High Textures quality at 75% render quality to get a good 50-60fps, but now have to use Low Textures with 50%. ( Issue doesn't occur since fps is around 90 now )

**Comment by gdrewb-valve** [comment]
Did this change with the latest updates?

**Comment by vikrantpogula** [comment]
@gdrewb-valve thanks !.. yes it seems to be fixed with the latest update. I will report back if it reoccurs

**Comment by gdrewb-valve** [comment]
Thanks, closing for now.
