### ISSUE TITLE
[Linux] [Windows] Ingame UI talk icon rendering artifact

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#316]
Noticed a semitransparent triangle every time when voice icon was shown in game.

It was in "Horde Mode" custom game.

Ubuntu 15.04, GTX 760 (faster edition), nvidia-352.

![2015-08-15 18 39 48](https://cloud.githubusercontent.com/assets/5393579/9289882/fbb4b5ba-437d-11e5-8950-dbcc1ff03dc1.png)

**Comment by gdrewb-valve** [comment]
Same as #221, but that did not reproduce.  Does this happen even when you exit Reborn and restart it?

**Comment by budimanjojo** [comment]
Mine happened in a matchmaking game, seems like it's a only happens when something is triggered bug

**Comment by VelorumS** [comment]
Now it's not happening.

Yes, something is triggering it and it's stuck like that at least till the end of the game. (don't know if it bugs from the start of the game, don't know if entering the new match clears it)

**Comment by danginsburg** [comment]
I have tried, but have been unable to repro this so far.  If anyone figures out a reliable repro, please post details.

**Comment by budimanjojo** [comment]
I just had it again yesterday, with shadow fiend. Happened mid game, it was the second game of that day. Watched a replay before the game.

**Comment by gdrewb-valve** [comment]
We'll see if we can find a consistent repro to investigate.

**Comment by rodlorric** [comment]
I just had this issue (weird triangle on the slot when broadcaster talks)  spectating a tournament game (Match ID 1781681086), I can confirm is not Linux specific since I had it on Windows, so I presume it is OpenGL related.

**Comment by rodlorric** [comment]
I got this again today, couple of things: after restarting the game it dissapears and so far it happens only spectating games, as soon as the commentator speaks.
Here is a screenshot, you can see that the triangle is not always the same size:

![Weird triangle](http://i.imgur.com/bGbMwAN.jpg)

**Comment by VelorumS** [comment]
Noticed in random video on YouTube:
https://www.youtube.com/watch?v=CcBZObf8ZHY
(Silly Builds || Speedy Silencer || Vol. 17 by JimBenDoto)

On 1:11, 6:23 etc.

**Comment by jazztickets** [comment]
Saw this bug last night

https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/eb7f152fa02cb41ada436fad6d0dbaaaa9149e81/gistfile1.txt

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Linux or Mac issue and we've passed it on to the larger team.
