### ISSUE TITLE
Bug in hero selection tab Dota Reborn

### ISSUE THREAD

**Issue by mmm0nky** [ValveSoftware/Dota-2#318]
The cursor just scrolls through all the heroes on screen. No matter which view I select, it just scrolls through all the heroes at speed. I hope that was an adequate description as I really don't know how else to explain it. Any help would be greatly appreciated. Thanks in advance.

**Comment by gdrewb-valve** [comment]
Can you post your Steam system information?

**Comment by mmm0nky** [comment]
Thanks for replying, Here is my system info:

Processor Information:
    Model:  MacBookPro11,3
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel Iris Pro

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0xd26
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                        33.1cm x 20.6cm  (38.9cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  953030 Mb
    Largest Free Hard Disk Block:  278887 Mb

**Comment by gdrewb-valve** [comment]
I just tried this on my Mac and it worked fine.  I started a bot game and hero selection worked as expected.  Are there any more specifics to the repro?  Does it happen for you with a bot game?  Does it happen every time?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this still happens.

**Comment by mmm0nky** [comment]
Thanks for the prompt reply, I apologize for not being more specific in my initial post. I tried the bot game and that selection worked fine. The non stop scrolling occurs when I click on the heroes tab when just starting up data reborn.

**Comment by mmm0nky** [comment]
Is there a way I can post up a quick video of the issue here?

**Comment by gdrewb-valve** [comment]
You can but I think text is fine for this unless there's something subtle you're doing.  The repro is just to start Reborn, click on the Heroes tab and go to the grid?  I just tried that and it worked fine so if that's the repro we'll need to try and figure out how to make it happen.

What display mode and resolution are you using?  Do you have anything other than a regular keyboard and mouse hooked up?

**Comment by mmm0nky** [comment]
Ok cool. My resolution is 2880x1800 and i have a logitech g700 and a g13 connected to my laptop

**Comment by gdrewb-valve** [comment]
Thanks.  It'll probably be a while before there's more info on this, unfortunately.

**Comment by bklooster** [comment]
Could this be related to #174 where there is are inputs being detected by a connected joystick/gamepad?

**Comment by gdrewb-valve** [comment]
Yes, that's why I asked about other connected devices.

**Comment by gdrewb-valve** [comment]
Thanks for putting in the issue reference.

**Comment by hatunike** [comment]
I too am having this issue (have had it since reborn came out). It happens every single time on the heroes tab of the main client UI. It's actually not really a big deal, except I can't browse heroes when not in a game. Everything in game works great.

**Comment by hatunike** [comment]
Oh, and I too use a Logitech G13 (that has a joystick). However the issue persists even when the joystick isn't plugged in and after i've restarted.

**Comment by hatunike** [comment]
Fixed it finally. I opened the Logitech G13 software and noticed I had my joystick assigned to non joystick keys. I reset the joystick back to default joystick mode. Then i went back into dota and the heroes tab. After using the joystick the hero scrolling stopped! This is the first time i've seen it not scroll since reborn came out. It looks to be acting normally now.

**Comment by mmm0nky** [comment]
Thank you hatunike! The default for the joystick is actually wasd but a simple right-click 'assign joystick' fixed this issue. How do i private message you on this thing?

**Comment by gdrewb-valve** [comment]
It sounds like with the configuration change this is no longer an issue?

**Comment by hatunike** [comment]
Yes. I've had a few times where i've needed to unplug and replug in and tinker around with the joystick, but this certainly is the trick.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
