### ISSUE TITLE
Keybord input with non-English language

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#319]
More from #313
1. Change language to Russian/other non-English.
2. When choosing hero - you can't search hero with writing hero name (video shows how it works http://youtu.be/QsaYgRHd0S0 )
3. While in game you can't use spells (q, w, e, r, etc) till you will change language from Russian to English, i guess there will be the same problem if you use Chinese language, etc.

Ubuntu 15.04, Unity DE (default)

**Comment by gdrewb-valve** [comment]
You are changing the system language / keyboard layout, correct?  There are some SDL issues in this area.  The next update might help.

**Comment by Pharmasolin** [comment]
Yes, in video i'm changing system language (alt+shift). When English
language is choosen i can use hotkeys in game, when Russian - i can't.
17.08.2015 20:53 пользователь "Drew Bliss" notifications@github.com
написал:

**Comment by gdrewb-valve** [comment]
Bindings are keyboard-layout-specific (which I assume is affected by changing the language) so this isn't supposed to work.  #143 is open covering changing this but there are no planned updates.

I think that leaves the hero name lookup, which should in theory work but is perhaps getting confused.

**Comment by zhestkov** [comment]
i confirmed this issue on mac

**Comment by gdrewb-valve** [comment]
An update added the -input_button_code_is_scan_code launch option which changes Reborn to work more like Source 1 Dota 2 where key bindings are not sensitive to keyboard layout.  Does that work more like what you are expecting?

**Comment by Pharmasolin** [comment]
I will test it right now.

**Comment by Pharmasolin** [comment]
Yes, tested with Russian layout, it worked as i expect. Will this be available later without launch option?

**Comment by gdrewb-valve** [comment]
It's likely this will get UI in settings but that's up to the larger team as this isn't a Linux or Mac issue.

**Comment by Pharmasolin** [comment]
Ok, thanks for this launch option anyway, i'm as a user from no EN_US/UK etc layout want this by default, for example i want to write something in chat in Russian and then use spell i need change layout. Or if i will bind Russian layout, and in team will be some one who understand only English, i need change layout again this is very uncomfortable.

**Comment by gdrewb-valve** [comment]
The Oct. 16th makes this a UI option.  In the Advanced section of key binding settings you can choose to have bindings be positional.  Give it a try.

**Comment by Pharmasolin** [comment]
Updating

**Comment by gdrewb-valve** [comment]
Closing pending a response that this is still happening.

**Comment by Pharmasolin** [comment]
I updated, this check-box works perfectly.

**Comment by Iaotle-OrangeMason** [comment]
This is still an issue tbh, hero search with russian layout should use the latin layout when running the game in english

**Comment by Iaotle** [comment]
This is still an issue tbh, hero search with russian layout should use the latin layout when running the game in english
