### ISSUE TITLE
error C3008: unknown layout specifier 'row_major'

### ISSUE THREAD

**Issue by xiansu** [ValveSoftware/Dota-2#32]
Using dual monitors with nvidia-304-updates

Loads dota2 reborn into a black screen with music. I have a console up and the last thing it says before a bunch of errors is:

CL: Receiving uncompressed update from server
CL: CL_ProcessPacketEntities: frame window too big (>=128)
CL: Signon traffic "client": incoming 35.943 KB [8 pkts], outgoing 1.270 KB [9 pkts]
Compilation failed: no code produced. Log string from driver:
0(7): error C3008: unknown layout specifier 'row_major'
... (same error with 0(8), 0(9), 0(10), 0(43)
0(75): error C3008: unknown layout specifier 'row_major'
## Vertex info

spams errors over and over

**Comment by xiansu** [comment]
It looks like besides the screen being black, it works. I can click the quit button by guessing it was around the same place. Then it made a popup sound, guessing that's the confirmation box, and I guessed correctly where the quit button was and it exited properly.

**Comment by danginsburg** [comment]
This looks like a driver issue with compiling the GLSL in the older NVIDIA driver.  Please update to a newer NVIDIA driver from: http://www.geforce.com/drivers and report back if the problem persists.

**Comment by Tele42** [comment]
@xiansu nvidia-drivers-304.xx is the extended support version for Geforce 6xxx-7xxx cards, nvidia-drivers-340.xx is the extended support version for Geforce 8xxx-9xxx,1xx-3xx cards. If you have a card newer than these, then any new version currently released will work. It's generally considered bad to directly install video drivers on linux, there should be guides or community help to help you update via your distro's package manager.

**Comment by gdrewb-valve** [comment]
Closing as this is understood.
