### ISSUE TITLE
[linux] cannot add a friend

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#320]
I'm using the big picture steam client.
Adding a friend does not work. I tried with the contextual menu and the friend id.

**Comment by gdrewb-valve** [comment]
You're not using Reborn to do it?  If this is Steam only please file a bug in the Steam forums.

**Comment by sylware** [comment]
On Sun, Aug 16, 2015 at 12:16:18PM -0700, Drew Bliss wrote:

> You're not using Reborn to do it?  If this is Steam only please file a bug in the Steam forums.

I do use reborn: In reborn, I cannot add a friend whatever way I use (contextual menu...).

**Comment by rained23** [comment]
@gdrewb-valve how can we add friend from reborn using friend ID ?

**Comment by sylware** [comment]
On Mon, Aug 17, 2015 at 02:25:37AM -0700, rained23 wrote:

> @gdrewb-valve how can we add friend from reborn using friend ID ?

You have the add friend icon in the reborn friend window (top right if I recall properly)
where you can add a friend using its id.
I did try this way too. Did not work (I use the big picture client and overlay).

**Comment by gdrewb-valve** [comment]
What happened when you tried?  What ID were you trying, was it 120939?

**Comment by budimanjojo** [comment]
Can you add friend using source 1 Dota? Have you ever tried adding friend before? As far as I know you have to buy at least one item using steam wallet before you can add friends.

**Comment by gdrewb-valve** [comment]
The 8/18 update fixed some things in this area, closing as I expect the behavior here to be different.

**Comment by gaohuazuo** [comment]
I have the same issue. Nothing happens after I click on the add friend button or context menu.

**Comment by gdrewb-valve** [comment]
@gaohuazuo you should open a new issue.  Please put your full system info from Steam in the report.
