### ISSUE TITLE
[MAC OS] CMD key now works as ALT in game since last update.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#321]
So the CMD key in game now works as ALT and you cant bind it to anything anymore, any combination of cmd+something is displayed as ALT + something now. ALT still works normally as well. IF this was intended, can we at least get an option to toggle it off or on, because I do not want it to have the alt functionality for example.

**Comment by gdrewb-valve** [comment]
Using Command for Alt was deliberate but we can consider changing it back.

**Comment by Vuccappella** [comment]
In source 1, I was really put out by the fact that I cant use cmd as a modifier and that cmd + q would quit my game as I wanted to use that  binding in game, however I adapted and I'm quite used to the alt and cmd set up and I use cmd as a binding rather than a modifier. However I do understand the change, the thing that bothers me though is that both keys act the same now, so they are both effectively alt keys, this means that I cant bind cmd + z and alt + z since they're the same now. Maybe an option to make cmd it's own modifier or have alt take and cmd just swap places so alt becomes cmd as well would be nice, that way there will be no overlap, cmd will be alt in a more comfortable position and alt will be cmd so you can still bind that and have desktop shortcuts. Maybe an option to turn this behaviour on or off.

**Comment by gdrewb-valve** [comment]
Reborn (and original Dota) only use Alt as a binding modifier so it's really only a question of whether Command means Alt also or not.

**Comment by Vuccappella** [comment]
But with a config file you could add extra modifiers, does that mean that the development team do not want to add more modifiers officially since dota hasn't been like that trough out history?

**Comment by gdrewb-valve** [comment]
There's no code in Dota to look at any modifiers other than alt (and ctrl in a few specific situations, but not for keybinds).  The larger dev team could add such code at any time but that's beyond the scope of this issue.

**Comment by Vuccappella** [comment]
I see, thanks for your time. Anyway, an on or off option for this might be nice in the future.

**Comment by gdrewb-valve** [comment]
I think we're just going to roll back the Command-as-alt change and reserve it as a possible future modifier key.  That does mean you lose the ability to bind the Command key itself but it will be consistent with ctrl, shift, alt and the handling of the Windows key on Windows.

**Comment by Vuccappella** [comment]
I'm not familiar with windows but can't you bind the windows key on windows ? After all in source one, binding cmd was displayed as WIN key in the options. So does this mean cmd won't function at all until it's made  as a separate modifier key or does this mean the change would be reverted and I would be able to bind CMD for now as in source 1 but in the future it would be reworked to be another modifier key, excuse my ignorance.

**Comment by gdrewb-valve** [comment]
You can't bind the Windows key as a key in Windows on Source 1 Dota 2 (I just tried it and it pops the Windows Start menu and cancels the bind).

The change will be to stop treating Command as Alt and handle it like the Windows key so you will not be able to bind it.  That prevents interference with system keys and allows it to be used as a modifier key in the future, but that's speculative.  We'll fiddle with things more if necessary, although so far we haven't gotten a lot of complaints about the current behavior so it doesn't seem like a lot of people are binding the Command key.  On the other hand there was a request to allow binding the Windows key on Windows, so there are definitely people that like using all of their keyboard keys.

**Comment by gdrewb-valve** [comment]
Note also #325.  When the reversion of the command-as-alt behavior goes out I'll probably close this and 325 will remain as the feature request for "let me bind Windows/Command".

**Comment by gdrewb-valve** [comment]
Actually today's (8/18) update should turn off command-as-alt.

**Comment by Vuccappella** [comment]
Yeah, just tested it, cmd is not bindable although I share the opinions from the other issue thread that it would help if it was either bindable or a different modifier as currently it isn't used for anything and it's one of the really more accessible keys(I use it for the shop key, dozens of time every game). I hope you guys look in to it in the future updates, so the key has some usability. For now I'll probably post in the other issue page as this is solved.

**Comment by gdrewb-valve** [comment]
Thanks, closing and keeping #325.
