### ISSUE TITLE
Anti aliasing does not enable

### ISSUE THREAD

**Issue by JenniferPylko** [ValveSoftware/Dota-2#322]
The checkbox in the settings menu has no effect

Below is my system information. However, it is not entirely accurate. I'm running the game through primusrun on a nvidia geforce gtx 960m with driver version 352.30.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.6.3
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x416
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 15.04" x 8.46"  (17.24" diag)
                                            38.2cm x 21.5cm  (43.8cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15969 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  593917 Mb
    Largest Free Hard Disk Block:  114593 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
Do you mean the setting doesn't stay set or that there is no visual change?

**Comment by JenniferPylko** [comment]
No visual change.

**Comment by danginsburg** [comment]
Can you try bringing up the console with \ and typing "toggle r_dota_fxaa" and post before and after screenshots?  The FXAA effect is somewhat subtle.  I've tried it here and it is working just fine.

**Comment by gdrewb-valve** [comment]
Just noting that it works properly on my Linux box also.  I only have a single GPU, I don't have a dual-graphics setup to test on.

**Comment by JenniferPylko** [comment]
`toggle r_dota_fxaa` does nothing, nor do `r_dota_fxaa 1` or `r_dota_fxaa 0`

**Comment by JenniferPylko** [comment]
Here's my .nvidia-settings-rc:

```
#
# /home/benjamin/.nvidia-settings-rc
#
# Configuration file for nvidia-settings - the NVIDIA X Server Settings utility
# Generated on Mon Aug 17 15:29:16 2015
#

# ConfigProperties:

RcFileLocale = C
ToolTips = Yes
DisplayStatusBar = Yes
SliderTextEntries = Yes
IncludeDisplayNameInConfigFile = No
ShowQuitDialog = No
UpdateRulesOnProfileNameChange = Yes
Timer = PowerMizer_Monitor_(GPU_0),Yes,1000
Timer = Thermal_Monitor_(GPU_0),Yes,1000
Timer = Memory_Used_(GPU_0),Yes,3000

# Attributes:

0/LogAniso=0
0/FSAA=0
0/TextureSharpen=0
0/TextureClamping=1
0/FXAA=1
0/FSAAAppControlled=1
0/LogAnisoAppControlled=1
0/OpenGLImageSettings=0
0/FSAAAppEnhanced=0
```

I've tried toggling the FXAA setting within nvidia-settings, and it updates the file, but does not change the image in game.

**Comment by danginsburg** [comment]
Please post before-and-after screenshots with toggling Anti-Aliasing in-game.  The effect is quite subtle so I wonder if you are just not noticing it.  If you are running with this:

0/FXAA=1

You are having the driver already do FXAA so it probably becomes even more subtle.  I have tried this on several machines, including Ubuntu 15.04 x86_64 with NVIDIA 346.59 and it is working fine.

**Comment by JenniferPylko** [comment]
I too was initially confused about the 0/FXAA option. All that does is allow FXAA to be used, and since 0/FFSAAAppControlled is 1 and 0/FSAAAppEnhanced is 0, it's up to the program. It's _definitely_ not enabling, but I will post screenshots.

**Comment by JenniferPylko** [comment]
Before (`r_dota_fxaa 0`):
![screenshot from 2015-08-17 16-22-14](https://cloud.githubusercontent.com/assets/3450413/9321275/3d11b3ea-4532-11e5-81e0-870f5affc76d.png)
After (`r_dota_fxaa 1`):
![screenshot from 2015-08-17 16-22-22](https://cloud.githubusercontent.com/assets/3450413/9321273/381224ba-4532-11e5-84da-062a88819a95.png)

**Comment by danginsburg** [comment]
FXAA is not enabled in the menu system, only in-game.

**Comment by JenniferPylko** [comment]
But it should (even if currently intentionally not) be enabled for all 3d assets, right? Even ones in the menu?

**Comment by danginsburg** [comment]
I will pass this along as a feature request to the team, but it is not currently the designed behavior.  Closing this here since I believe FXAA is performing as designed.
