### ISSUE TITLE
[Linux] Information: DOTA Loves MATE DE (fixing FPS)

### ISSUE THREAD

**Issue by presianbg** [ValveSoftware/Dota-2#324]
Dear All,

I found that running DOTA 2 Reborn under MATE Desktop Environment making huge difference. For an example:
My primary DE is Cinnamon and running:

```
 vblank_mode=0 primusrun glxspheres64
```

results in 150-180 fps. Yesterday I installed MATE. The benchmark gives 300 - 320 fps. So far so good. But decided to give it a try with Dota 2 Reborn. Guess what? No more fps drops, no more glitches, no more bad performance. Even with maxed effects + weather effect (rain) it's constant 60 fps, smoother than ever. In my opinion this is HUGE. I will be happy if more players test and confirm my discover.

I'm on Asus G551JM with optimus technology:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 22 (Twenty Two)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-200.fc22.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11702000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 

    Driver Version:  3.0 Mesa 10.6.3 (git-ccef890)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x416
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  11459 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  105040 Mb
    Largest Free Hard Disk Block:  20044 Mb

Installed software:

Recent Failure Reports:

```

Cheers! 

Best Regards,
presianbg

**Comment by gdrewb-valve** [comment]
Do you think there's a Reborn issue or are you just posting this as information for other people?

**Comment by presianbg** [comment]
Just posting it for the players with fps issues. It's a hint  for them to try other DE which can solve their problems.  Otherwise you will have a lot of work debugging someone else work :)  Today I will contact cinnamon devs and see what will they say. If it's possible keep this issue opened until someone confirms that some DEs are bottlenecks to Linux gaming. 

Thank you in advance.

**Comment by gdrewb-valve** [comment]
Yes, we can leave this open.

**Comment by tiburcillo** [comment]
Hi, I'm also a Cinnamon user. I do notice the stutters (especially when a graphics intensive spell is being cast for the first time) regularly. I'll give MATE a try tonight and report back.

Edit: Installed MATE, i do have my framerate capped at 60 FPS by the way. I only played two games with not that visual-effect demanding heroes and I have to say I did not encouter any stutter indeed.
Will post specs when I'm back home.

**Comment by presianbg** [comment]
Hmmm... The guys at Cinnamon said to try "Disable compositing for full-screen widows" in general section (System Settings). I played one game in Overtrhow and looks like It's OK (capped at 60 FPS without shuttering). Can you test that by your side ?

**Comment by gdrewb-valve** [comment]
What would you like us to test?  It would be expected that enabling the compositor would slow things down.

**Comment by presianbg** [comment]
@gdrewb-valve I was talking to @tiburcillo  :) I didn't know about this compositor option at all. I will do some more tests today and post back. You can close the issue if you want.

**Comment by tiburcillo** [comment]
Hi Presian, I'll try that one tonight. Thanks for the tip.

**Comment by presianbg** [comment]
Just played ranked in reborn and have to say that `Disable compositing for full-screen widows` doesn't make a difference for me :( So still Cinnamon is bad choice to play DOTA.

**Comment by gdrewb-valve** [comment]
Closing as I think this has served its purpose.
