### ISSUE TITLE
[Linux] Windows(Super) key can't be binded to action 

### ISSUE THREAD

**Issue by XANi** [ValveSoftware/Dota-2#325]
In Dota 2 Win key was bindable to any action (I used that for quickbuy).

In current version of Reborn I can't bind it to anything (in one of previous ones it worked like Alt key on bindings screen but if I remember correctly didn't work at all in match).

It would be nice to have it back as it is very convenient key to use and it doesn't (usually) have any use in Linux

**Comment by gdrewb-valve** [comment]
It's deliberate that you can't bind that key on its own (or ctrl or shift or alt).  I'll leave this open as an enhancement request but I don't know if it'll change.

**Comment by XANi** [comment]
Yes but it also can't be used as a modifier, which makes it a bit useless. IMO it should be either available as separate modifier key (as it is supposed to be in Linux as most DE can use it as modifier) or "just another key" (like in old client)

**Comment by gdrewb-valve** [comment]
It is true that it can't be used as a modifier now but that may not always be true in the future.  It also performs system actions when the game is running in a window.  Just as a data point neither version of Dota has allowed the Windows key to be bound on Windows even though it can't be used as a modifier.

Your request is reasonable but it isn't a simple thing to switch over.

**Comment by XANi** [comment]
I just don't really get a point of blocking arbitrary keys on keyboard while allowing others. 

Sure, in windows, windows key will always be used for some common windows shortcut.

But in Linux in varies depending on desktop environment and some default desktop shortcuts can already be binded to same keys in Dota (like alt+insert for a new workspace in xfce or alt+F2 for command menu)

**Comment by budimanjojo** [comment]
I don't see a reason why Linux version should be different from Windows version. And I don't think we need windows key to be used, but I think an option to change the Ctrl or alt key to windows key is a better way to go rather than what you want it to be.

**Comment by Tele42** [comment]
As a side note, most major DEs that have alt + key keybinding have a system option to switch it to the super (windows) key.

**Comment by Vuccappella** [comment]
I don't really agree that Linux or Mac Version should not be different from the Windows version, after all they are different keyboard layouts and the keys function slightly differently. The WIN key isn't the same as the CMD key etc..  
On the flipside, people probably wouldn't mind WIN being bindable or a modifier on Windows (at the end of the day, they have an extra key to use) so instead of bringing parity of Linux and Mac versions to the Windows version, maybe bringing parity to Windows from Linux and Mac would be better.
Other than that, I support the idea of being able to change the Alt key to CMD key in the menu option. (If the CMD key does not work as a modifier in the future that is ) .

**Comment by gdrewb-valve** [comment]
We're considering adding an option to let Windows / Command be bindable as a key.  Whether we can actually make this work properly in all cases on Windows is unclear but we'll see.

**Comment by Vuccappella** [comment]
Sounds great, thanks for your work.

**Comment by gdrewb-valve** [comment]
The Sep. 1 update has an "Allow Windows / Command key to be bound" option in the advanced hotkey section.

**Comment by gdrewb-valve** [comment]
Closing as the update should have addressed this.
