### ISSUE TITLE
(Enhancement) Friend request notifications

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#326]
Just wanna know if there's any friend request notification when people add me in Reborn because I can't find it anywhere except from the steam client.

**Comment by budimanjojo** [comment]
EDIT: In source 1 Dota there is a pending friend request list inside the friend list box

**Comment by gdrewb-valve** [comment]
Checking with the larger team...

**Comment by gdrewb-valve** [comment]
According to the larger team pending friend requests will show in one of the categories in the friends menu. If you're not seeing anything anywhere I can let them know before closing this out.

**Comment by budimanjojo** [comment]
I don't know but as I remember correctly it wasn't there. I'll look into it
again later

**Comment by budimanjojo** [comment]
I can confirm that there is no friend requests list in reborn.
![2015-08-25_00001](https://cloud.githubusercontent.com/assets/13085918/9461955/7a0e25fc-4b3c-11e5-94be-1799cad89247.jpg)
There are 2 friends requests in steam client:
![screenshot_2015-08-25_14-59-25](https://cloud.githubusercontent.com/assets/13085918/9461964/8ad65e18-4b3c-11e5-898d-83c24873c5bd.png)

**Comment by gdrewb-valve** [comment]
I've passed this on and the larger team will take a look.

**Comment by gdrewb-valve** [comment]
I heard back that the problem had been identified so a fix should be coming in a future update.

**Comment by budimanjojo** [comment]
Ok, thanks gdrewb

**Comment by budimanjojo** [comment]
When will the update come?

**Comment by gdrewb-valve** [comment]
It's up to the larger team so I can't give a specific timeframe, sorry.

**Comment by gdrewb-valve** [comment]
The update is out now.

**Comment by budimanjojo** [comment]
Okay, I'll try again after updating before closing this issue, thanks.

**Comment by budimanjojo** [comment]
This is fixed now, thanks
