### ISSUE TITLE
[Linux] Issues rendering water when using experimental Mesa drivers

### ISSUE THREAD

**Issue by vhda** [ValveSoftware/Dota-2#327]
I'm experiencing some issues rendering water, in particular in the river margins of middle lane, when using the Mesa drivers available in Debian Experimental repository. This version now includes support for OpenGL 4.1, so I assume that this may be related and that one of the following is happening:
1. There are bugs in the implementation of OpenGL 4.0/4.1 extensions.
2. Dota is using some OpenGL 4.2 to 4.5 extensions without confirming their existence.

The screenshot is shown below:

![2015-08-22_00001](https://cloud.githubusercontent.com/assets/606876/9421583/d8459f8c-486d-11e5-8cfd-e55669220225.jpg)

Take into account that there are similar issues near the runes and that Storm Spirit's Ball Lightning is also corrupted.

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.7.0)
    Driver Version:  3.0 Mesa 11.0.0-devel
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16.14" x 10.08"  (19.02" diag)
                                            41.0cm x 25.6cm  (48.3cm diag)
    Primary VRAM Not Detected

**Comment by Tele42** [comment]
This issue should also be reported to the mesa devs, if it has not been already.

**Comment by vhda** [comment]
This was due to a bug in llvm-3.7. After an update of this package everything is correct now.
