### ISSUE TITLE
Customs game bug [EDITED]

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#328]
Were playing few times this mod http://steamcommunity.com/sharedfiles/filedetails/?id=483720948 (and after few games Dota starts to eat a lot memory donno why, may be mod bug, you can test it by yourself, dota eats memory even after game in menu).

But about bug report, i ended game, quit from it in main menu and received this:
![2015-08-24 04 16 51](https://cloud.githubusercontent.com/assets/13041082/9431346/fc3346c8-4a17-11e5-9727-e80d3a85d170.png)
![2015-08-24 04 17 05](https://cloud.githubusercontent.com/assets/13041082/9431347/fc33762a-4a17-11e5-8b75-ca3fdac5034c.png)
![2015-08-24 04 17 42](https://cloud.githubusercontent.com/assets/13041082/9431348/fc339ef2-4a17-11e5-827c-42a7f87ca9aa.png)
![2015-08-24 04 17 49](https://cloud.githubusercontent.com/assets/13041082/9431349/fc3755ec-4a17-11e5-8522-0f76f675fed8.png)
![2015-08-24 04 18 22](https://cloud.githubusercontent.com/assets/13041082/9431350/fc377ff4-4a17-11e5-8738-edd38c4ffbba.png)
![2015-08-24 04 18 44](https://cloud.githubusercontent.com/assets/13041082/9431351/fc37a9de-4a17-11e5-8d0b-cdcbdb52ecef.png)

In words:
1. Ended game.
2. Want to find new game but i can't, because for dota i'm in that old lobby.
3. There is no button to leave lobby.
4. I can't play normal dota game (i'm in low priority) so i can't play all random.
(5. When i'm not host and waiting to host to create game while all people accept game (custom game) there are no leave lobby button. So i can't leave lobby while "host is loading" and if host is bugged i need to restart dota to be able play new customs game.

**Comment by Pharmasolin** [comment]
I were leaving dota 2, and were closing Steam, this didn't help me.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
Question from the team: how did you end the game in step #1?  Does this happen repeatedly?  If so there are some console commands we can have you turn on to gather extra information (open console, do 'developer 1' and then 'dota_lobby_debug' after step #1).

**Comment by Pharmasolin** [comment]
I remember that some one were host, we successfully played till end, and then i press "close" button to exit game we just ended, but this bug were randomly i think, i'm playing custom games 2nd day only, and have seen this 1st time, i need to write this commands if i will get this bug again?

**Comment by gdrewb-valve** [comment]
Thanks for the info.  If you do see this from a consistent set of steps please let us know to help pinpoint the issue.

**Comment by Pharmasolin** [comment]
Okay if i will face this issue again i will enter commands you gave me and write how i can cause this.

My guess is, we were playing in late night 4 a.m. and Host may be shutdown dota or even shutdown PC before i press "close" button to exit that game we just played. And this caused problem i have later, but shit is only my guess.

**Comment by gdrewb-valve** [comment]
If the host shuts down without exiting the game, such as if the computer hosting the game shuts down, that will prevent the game host from notifying the rest of the people connected that the host has gone down.  There's then a timeout (I believe a minute) before the other people's games would realize the host was gone and take them out of the game.  That may or may not have happened to you, it's just something to keep in mind.

**Comment by Pharmasolin** [comment]
I'm back
For some reason copy don't work from console
check screens 
![2015-08-26 12 12 33](https://cloud.githubusercontent.com/assets/13041082/9489770/28a3efd4-4bec-11e5-84d5-4cf647e518d8.png)
![2015-08-26 12 14 37](https://cloud.githubusercontent.com/assets/13041082/9489772/28ac1786-4bec-11e5-9301-ea4c8e2dc855.png)
![2015-08-26 12 14 54](https://cloud.githubusercontent.com/assets/13041082/9489771/28a5b3fa-4bec-11e5-955c-71276243d180.png)
Last game i were playing last night, about 10 hours ago, and i'm still in lobby. I don't remember were i host or not. We played it till end, then i closed dota i think.

**Comment by Pharmasolin** [comment]
After i log in, it closed this lobby i think in 1-5 minutes while i were writing this report.

**Comment by gdrewb-valve** [comment]
Thanks for the info, I've passed this on.

**Comment by ghost** [comment]
This issue not solved. Can't leave Dota 2 Custom games lobby 1-2 times a week. For example, Overthrow game.

**Comment by gdrewb-valve** [comment]
Note that the issue here was closed because it is not a Mac/Linux bug, not because it was solved.

**Comment by AndrejSchaefer** [comment]
Open Console
Write force_leave_game_button 1
Leave the game via Button
Worked for me with the same problem
Source: https://www.reddit.com/r/DotA2/comments/4jef2m/im_stuck_in_a_hidden_lobby_i_cant_leave/d362wd5
Credit goes to SeQuenSe
Good luck!
