### ISSUE TITLE
[OSX] - Spikes of low FPS after latest update (NVIDIA GeForce GT 650M)

### ISSUE THREAD

**Issue by mjmetts** [ValveSoftware/Dota-2#329]
I know this used to be an issue, but until recently, I had no problems with Reborn lagging. In fact, it was more responsive than the main client. The most recent patch seems to have reintroduced sporadic drops in FPS for me. Here are my system details:

![macbook](https://cloud.githubusercontent.com/assets/4855576/9448779/16581384-4a64-11e5-9b28-89acbbd0267d.png)

I'll be humming along at 90-110 FPS, then it'll drop to 0-10 for a second or two. This is especially prone to happen during a team fight.

**Comment by gdrewb-valve** [comment]
I believe this is also being reported on Windows and may not be handled here.

**Comment by danginsburg** [comment]
I have not been able to repro this on a very similarly configured Macbook Pro with GT650M.

**Comment by gdrewb-valve** [comment]
@mjmetts, is this issue still active?

**Comment by mjmetts** [comment]
No longer an issue for me!
