### ISSUE TITLE
Linux: Borderless Window and multiple monitors makes mouse track over to a different monitor.

### ISSUE THREAD

**Issue by gyaru** [ValveSoftware/Dota-2#33]
Kinda similar to #11 

Using Borderless Window and more than one monitor makes the cursor go to a different monitor instead of being bound to the dota window itself. (The regular client did not have this issue)

Switching to fullscreen mode seems to "fix" this because it doesn't have the same issue.
Starting the client with fullscreen seems to suffer the same issue though.

**Comment by nixi-awoo** [comment]
For me this was the case even with the original client. I always had to use fullscreen to make the cursor stay in the window. Perhaps it may be a specific driver or Xorg version issue.

**Comment by Eryla** [comment]
I guess I'll chime in with my speccs too.

*Xorg 1.17.2
*4.0.5-2-ck x86_64 Arch Linux
*Nvidia 352.09
*using BSPWM as my WM.

**Comment by fasmat** [comment]
Can confirm. Using a border-less Window in Linux with a dual monitor setup will lead to frustration when you try to edge pan. The mouse just moves to the other monitor if moved too far to the side.

**Comment by gdrewb-valve** [comment]
Are you using windows the same size as the monitor?  We've removed the fullscreen option and a monitor-sized borderless window should behave like fullscreen used to.

Does this happen even on windows smaller than the monitor?

**Comment by nixi-awoo** [comment]
The mouse cursor gets captured ingame now and not in menus. This is the cursor behaviour I was expecting. It works in both "full-screen" resolution and a small window. 

Although, the window minimizes upon losing focus if it is set to screen resolution, but not if it is smaller. 
Is this intentional?

**Comment by gdrewb-valve** [comment]
The minimize behavior is expected, see #182.  You can apparently set SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 to turn it off.

I'll close this shortly unless somebody else is still seeing problems.

**Comment by gyaru** [comment]
I'd say it works for me at least now, created a quick private game and tried to pan around and my mouse didn't escape from the in-game window. 

Resolution set on "Use my monitor's current resolution" and the Dota 2 window set to Fullscreen in my WM (bspwm).

I'll personally close this because I opened the issue and it seems to be fixed for me, feel free to open it again if it wasn't fixed.

**Comment by artemklevtsov** [comment]
Not solved with kwin 5.3.2. I tried fullscreen and borderless modes.
![screen4](https://cloud.githubusercontent.com/assets/603798/9149559/d90d54ce-3dd1-11e5-990e-459838ec7616.png)

**Comment by Ed1s0nIsCoding** [comment]
After todays update (Battlepass Update) im having this issue (again). It happens on all three window modes (windowed, borderless, desktop-friendly fullscreen). Gist with systeminfo: [https://gist.githubusercontent.com/Ed1s0nIsCoding/6d012217a77372de16b667ade78b19e4/raw/e02beb6a6e702b6eaa380e93d5c3b851eb687c05/gistfile1.txt](https://gist.githubusercontent.com/Ed1s0nIsCoding/6d012217a77372de16b667ade78b19e4/raw/e02beb6a6e702b6eaa380e93d5c3b851eb687c05/gistfile1.txt)

**Comment by MiriJ15** [comment]
Same issue here after bp update.

**Comment by srsgores** [comment]
Yep, same issue on Manjaro linux wayland

**Comment by MiriJ15** [comment]
Fixed in latest update.
