### ISSUE TITLE
White(ish) screen with very few things rendered in game

### ISSUE THREAD

**Issue by mmdeas** [ValveSoftware/Dota-2#330]
Loaded into game to find that most things were not rendered. Effect is a mostly white screen (bar the HUD which was rendered without problems).
Things which can be seen:
- health/mana bars
- "miss" symbols
- names of allies when hovering over them
- blood effects on attack
- ring around feet of selected hero (where not occluded by another object regardless of whether or not that object was rendered)
- fire
- lights in Visage model
- electricity in Razor model
- fountain regen aura
- ranged creep projectiles
- fountain projectiles

The game rendered normally with cursor hovering over enemy heroes and other times where I haven't been able to determine a definite pattern.

Running OSX 10.10.5 on MacBookPro7,1. 
EDIT:
![dsc_0107](https://cloud.githubusercontent.com/assets/4593108/9452171/b7ce39e6-4aaa-11e5-975e-f2b89fb6bc42.JPG)

System Information:

```
Processor Information:
    Model:  MacBookPro7,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2400 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce 320M

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x8a0
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 18.82" x 10.55"  (21.57" diag)
                                            47.8cm x 26.8cm  (54.8cm diag)
    Primary VRAM: 256 MB

Memory:
    RAM:  4096 Mb
```

**Comment by gdrewb-valve** [comment]
Once we know your GPU we can determine whether this is one of the open issues or not.

**Comment by mmdeas** [comment]
Sorry for the delay. I edited my system information into the original post and added a photo (screenshot didn't work). As it now says above, my GPU is NVIDIA GeForce 320M.
EDIT:
Would it help if I were to try playing in the Reborn Windows client? I switched to playing in OS X because I have WiFi issues on Windows but I could sit next to the router for a while if it would help to check whether it only happens on OS X.

**Comment by danginsburg** [comment]
@mmdeas Out of curiosity, does the corruption go away if you add -gl_force_sm30 to the command-line (you can set it in Launch Options in Steam)?  I'm trying to repro on a similar Mac here with GT330M and so far can't get it to happen.  I'm about to update to 10.10.5 to see if it happens.  Also, do you have the standard NVIDIA driver that comes with OS X or the web driver installed?  I have only tested with the standard NVIDIA drivers.

**Comment by danginsburg** [comment]
@mmdeas Updated to OS X 10.10.5, still not repro'ing.  I also tried installing the 346.02.03f01 web driver (http://www.nvidia.com/download/driverResults.aspx/89538/en-us) and it does not repro with that either.

**Comment by mmdeas** [comment]
I only tested in "Demo Hero" mode (where the corruption was present before) but there is no corruption having added -gl_force_sm30. Can I keep this as a long-term fix or are there any problems it might cause?
I have not changed my drivers from the ones which come with OS X since updating to Yosemite.

**Comment by danginsburg** [comment]
@mmdeas Thanks for trying that.  I have checked in GPU detect code that will default to forcing SM30 shaders on the Geforce 320M.  It will be in the next Dota 2 Reborn update.  It will do the same thing as having -gl_force_sm30 on your command-line so feel free to keep it.  Closing.

**Comment by mmdeas** [comment]
I played a real game today and had the same issue again (with the launch option still there). Went back to the "Demo Hero" mode and managed to reproduce again although it seems harder to trigger than it used to be - I'll try to spend more time figuring out when it does and doesn't occur tomorrow.
