### ISSUE TITLE
Custom games HUD bug (dota issue 100%)

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#331]
Check picture, as you can see there is bug with displaying spells HUD. THIS IS ALSO IN Overthrow MOD, but i didn't make screenshot.
![2015-08-24 22 14 58](https://cloud.githubusercontent.com/assets/13041082/9450550/fe9589b8-4ab1-11e5-8431-d1966e99ef58.png)
How i gain it:
1. Played http://steamcommunity.com/sharedfiles/filedetails/?id=483720948 mod while were host, then i left game while it were in progress.
2. Then find new game in new mode, Overthrow, i have the same issue as in the picture + when "Storm Spirit" took loot in this mod, it is show in monitor who took it, it were written "Mini Actor" take bla-bla-bla. Storm Spirit named "Mini Actor" in Petri mod, but he also were named Mini Actor in Overthrow mod.
Only relog in Dota helps, may be dota make some cache for customs mods and don't clean it properly.
May be thats why Dota consume so much memory when playing a bit customs games #328 
Don't know if this also in WIN or not so reporting here.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.
