### ISSUE TITLE
[OSX] Multiple rapid inputs slow to process

### ISSUE THREAD

**Issue by dphildebrandt** [ValveSoftware/Dota-2#332]
Exact same as #85

Lots of ingame inputs (this doesn't seem to affect UI interactions, only unit commands and camera movements) result in later inputs taking longer to be expressed compared to earlier inputs. Allowing the game time to catch up "resets" the input lag but subsequent random inputs will start out responsive and get progressively laggier until the game is allowed some time to catch up again.

Noticed this is happening in the Main client as well. ValveSoftware/Dota-2#1839

```
Processor Information:
    Model:  MacBookPro11,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel Iris

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xa2e
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.22" x 7.05"  (13.23" diag)
                                            28.5cm x 17.9cm  (33.6cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  16384 Mb
```

**Comment by gdrewb-valve** [comment]
This is going to be difficult to isolate as we don't have a repro and our other known case of this was fixed, but we'll see what we can find.

**Comment by dphildebrandt** [comment]
Any kind of logs or anything I can give you to help?

**Comment by dphildebrandt** [comment]
It seems to have been introduced in both clients when Reborn was introduced.

**Comment by gdrewb-valve** [comment]
I don't know of anything simple but I'll check.  There are reports of lag across all platforms also so this may be handled by the larger team.

**Comment by gdrewb-valve** [comment]
Does this occur in a Reborn bot match?

**Comment by dphildebrandt** [comment]
It does.

**Comment by gdrewb-valve** [comment]
I was thinking your lag might be similar to others that people have seen connected to networking, which does not occur in bot games, but you apparently have a different issue.  We'll see if we can cause it to happen.

**Comment by dphildebrandt** [comment]
Seems to be some improvements with the new update.

The lag still happens but it resolves much more quickly now. Whereas before a few right clicks or camera movements wouldnt respond for several seconds (lets say 2-3), it now seems to resolve itself in 1 second or less.

**Comment by gdrewb-valve** [comment]
Thanks, at least it's going in the right direction.

**Comment by gdrewb-valve** [comment]
The larger tower is actively investigating the camera movement and input lag.

**Comment by dphildebrandt** [comment]
Exciting, I'll note maybe I was optimistic after the last update but it seems just a bad as it was before, now that i've played several games.

**Comment by dphildebrandt** [comment]
Happy to report latest update has seemed to fix it completely. Had a whole bot game with no lag. Going to try a regular game later today.

**Comment by dphildebrandt** [comment]
Played a game of 10v10 and overthrow, seems to be fixed. Thanks guys!

**Comment by dphildebrandt** [comment]
There seems to have been a bit of this persisting ever since the patch that 'fixed' it. The last few updates though, it's back to levels that are just as bad as before.

**Comment by gdrewb-valve** [comment]
How is it nowadays?

**Comment by gdrewb-valve** [comment]
Closing pending more information.

**Comment by dphildebrandt** [comment]
Yeah this hasn't been an issue for a long time, thanks!
