### ISSUE TITLE
[OSX] Hang when trying to spectate live game

### ISSUE THREAD

**Issue by jakehilton** [ValveSoftware/Dota-2#333]
When trying to spectate a game I get the loading screen and it just hangs at that point. I've not tried joining a game for fear the same thing will occur.

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro11,5
  Processor Name:   Intel Core i7
  Processor Speed:  2.5 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB
  Boot ROM Version: MBP114.0172.B04

Video card:
Chipset Model:  AMD Radeon R9 M370X
  Type: GPU
  Bus:  PCIe
  PCIe Lane Width:  x8
  VRAM (Total): 2048 MB
  Vendor:   ATI (0x1002)

Running game on my Thunderbolt Cinema display.

**Comment by gdrewb-valve** [comment]
This happens on Windows also, I've passed it on to the larger team.

**Comment by jakehilton** [comment]
Thanks Drew.
