### ISSUE TITLE
Launch options being ignored in linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by jaredmcateer** [ValveSoftware/Dota-2#334]
I have a dual monitor setup that has one screen which is a 19" 4:3 and a 27" 16:10, the Unity launcher is on my smaller monitor but I want the game to open on my larger monitor. 

I have the following launch options so that the game will launch in a borderless window on my second screen (this currently works on the standard Dota 2 client)

```
-h 1179 -w 1920 -x 1280 -y 0 -noborder
```

(note: `-h 1179` is due to the borderless windows inability to cover the menu bar at the top and `-x 1280` pushes the window over to my larger monitor)

Unfortunately the game wants to start in full screen on my smaller monitor, if I go into the game options and switch the display mode to borderless window the game will launch on my larger monitor, however, it will default to 1280x1024 and even if I switch it to 16:10 it won't give me an option larger than 1280x800. I'm guessing that the game is deducing my max size from my "primary" monitor and not the monitor I want to have the game set to.

**Comment by Tele42** [comment]
Per #13, -sdl_displayindex is the override for which display the game starts.

**Comment by jaredmcateer** [comment]
Ah I think I tried that one on the legacy client and it did not work. I'll give it a shot for reborn.

**Comment by Tele42** [comment]
Dota 2 and Dota 2 Reborn do not run on the same game engine, it's expected that there would be different launch options.

**Comment by gdrewb-valve** [comment]
As noted this is expected behavior.  Eventually the multimon support will be updated to behave better when the window is moved between monitors (which is what the -x is doing in this case although it doesn't seem like it) and such.
