### ISSUE TITLE
[OSX] Moving the camera is jerky

### ISSUE THREAD

**Issue by zhestkov** [ValveSoftware/Dota-2#337]
Specs:
<img width="578" alt="screen shot 2015-08-30 at 14 34 30" src="https://cloud.githubusercontent.com/assets/801717/9568255/e54a2136-4f4c-11e5-8e4e-6a575a37bb8b.png">

I set 1280x800, best rendering quality and low textures, without any other features.
Then i have around 55 fps in Reborn and it's great, but moving the camera is jerky.
Though, in the main client it's smoothly with the same settings.

**Comment by gdrewb-valve** [comment]
Likely the same input lag issue as #332.  We don't have a repro at the moment.

**Comment by gdrewb-valve** [comment]
Have you changed any camera settings in the main client or used convars like dota_camera_accelerate?

**Comment by jeanlain** [comment]
I have the same issue. The fps counter shows 40-50, which should be reasonably fluid, but camera movements look more like 15-20 fps. This is on a 2006 Mac Pro with radeon 7950, OS X 10.9.5. 
This may have been introduced by some particular update because the first betas didn't have the issue. 

EDIT: this is not related the the number of inputs. Camera movement is jerky from the start.

**Comment by zhestkov** [comment]
> Have you changed any camera settings in the main client or used convars like dota_camera_accelerate?

Actually, i use these setting for camera in both clients:
dota_camera_accelerate "50" 
dota_camera_speed "4000"
(likely default camera settings)
I have tried play w/o them in Reborn, but there are no improves.

EDIT: by the way, its better if i choose lower rendering quality. Seems like GPU couldn’t keep up with the CPU.
There was a similar fix for DX9 in 20/06 patch:
"Fixed input lag in DX9 in cases where the GPU couldn’t keep up with the CPU."

**Comment by jeanlain** [comment]
In my case the CPU (xeon 5150) is much slower than the GPU.
I have been regularly experiencing the issue with the main client. It came and went with game updates.

**Comment by zhestkov** [comment]
It looks better after 09/01 patch

**Comment by codycurley** [comment]
Same here, but only happens when I pan over a tower. Frame rate drops from 100 to 20.

It happens at 1920 x 1080 resolution in desktop friendly and exclusive fullscreen modes. Changing rendering quality has no affect on it. If I switch to 1600 x 900 and go into exclusive fullscreen, it works fine. If I switch to desktop friendly fullscreen it has the frame drop issue.

**Comment by zhestkov** [comment]
Hm, yes, fps value is definitely more stable with Excl.Fullscreen

**Comment by gdrewb-valve** [comment]
It's expected that exclusive fullscreen will help out since then OSX is out of the way, but it's odd that a tower would cause such a large FPS drop.  I've asked the larger team if there's something that would trigger a hitch.

**Comment by codycurley** [comment]
@gdrewb-valve and to clarify, if the camera is positioned over a tower, the FPS is fine. It's only when edge padding over them. I haven't been able to find other sections of the map where it happens, but I also haven't played many full games do to the hiccups.

**Comment by gdrewb-valve** [comment]
The larger tower is actively investigating the camera movement and input lag.

**Comment by jeanlain** [comment]
Good to know that a tier-one tower is investigating the issue. ;-)
But my personal issue appears to be fixed. Not by the latest update, but by somehow playing the main client and back to reborn. I had an issue with low fps (visibly lower than what the fps counter showed), which was mostly visible during camera movement, linked to yellow error messages filling the console. Now everything's good. Fps may decease a bit when panning over towers, but not that much.

**Comment by dphildebrandt** [comment]
Seems to be fixed with latest update.

**Comment by codycurley** [comment]
@dphildebrandt still issues here.

**Comment by codycurley** [comment]
A little update on this. I've been trying to replicate it around the map and I've figured out that it's not actually the mid tower.

The frame rate drops when I edge pan to the bottom. It's fine for the first half a second, then it will hiccup down to 15–20 FPS and then back up to normal.

**Comment by gdrewb-valve** [comment]
Has this changed at all since the last post?

**Comment by codycurley** [comment]
@gdrewb-valve All good! Haven't experienced it recently.

**Comment by gdrewb-valve** [comment]
OK, hopefully everybody else is OK also, closing.
