### ISSUE TITLE
[linux] the game will suffer severe performance loss with recent linux kernels

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#338]
see https://bugzilla.kernel.org/show_bug.cgi?id=103781
Scheduler issue, same issue for source-1 games.

**Comment by davidw-valve** [comment]
Which kernel versions are you talking about specifically? Is this something you are experiencing now? What kind of performance loss are you experiencing?

**Comment by sylware** [comment]
Basically a patch related to the "full dynamic tick" scheduler went into nearly
all linux kernels from the 6th of may of this year, which makes the games run
significantly slower.

I did notice the loss of performance once I updated my linux kernel a few day
ago, it was obvious with dota2 reborn and source-1 games (portal2/CS GO/dota2):
The games do stutter a lot and the loss of fps is obvious.

I "bisected" and found the culprit. 

All the information is on the linux kernel bugzilla. The author of the patch
"indirectly" thinks it's an issue with the multicore load balancers of the games.

I configured a linux kernel with a "no dynamic tick" scheduler and games were
smooth again. But nearly all desktop distros out there will ship with a full
dynamic tick scheduler.

**Comment by gdrewb-valve** [comment]
Is there something further that can be done here?  The bugzilla reference mentions some kernel options which don't necessarily make sense but nothing more that I can see about whether there's some kernel change that should happen or not.

**Comment by sylware** [comment]
On Thu, Feb 25, 2016 at 02:14:40PM -0800, Drew Bliss wrote:

> Is there something further that can be done here?  The bugzilla reference
> mentions some kernel options which don't necessarily make sense but nothing
> more that I can see about whether there's some kernel change that should
> happen or not.

That was ages ago. Right now, I cannot test anything anymore (namely recent
kernel versions) as I'm trying not to end up an homeless person.

## 

Sylvain

**Comment by gdrewb-valve** [comment]
Well I hope that things work out for you!  I'm going to close this until we know if there's a specific thing that Reborn should do.

**Comment by sylware** [comment]
On Thu, Feb 25, 2016 at 09:55:19PM -0800, Drew Bliss wrote:

> Well I hope that things work out for you! 

Hope you will be right... but it's turning _really_ bad.
Just a few months left before the street becomes my home.

## 

Sylvain
