### ISSUE TITLE
[Linux] Reborn loads indefinitely when launching steam from terminal

### ISSUE THREAD

**Issue by beheh** [ValveSoftware/Dota-2#339]
I am unable to launch Reborn from Steam launched from a terminal in order to get a Dota log for other issues I'd like to report. Running Steam from Gnome Shell works as expected.

Additionally, when launching the old Dota 2 Client from a Terminal, the initial "Valve" video does not load and the game hangs on a black scrfeen until pressing Enter to skip the video, immediately showing the Dota loading screen and loading into the menu soon after.

Steps to reproduce:
- Launch Steam with either `steam` or `/usr/bin/steam` from terminal (tested with bash and fish - [env output](https://gist.githubusercontent.com/beheh/25afac382b8e3a67effb/raw/57963872bc5ae93a0b990bf5d88aaca31e4736cc/gistfile1.txt))
- Launch Dota 2, select Reborn
- Observe a black screen, followed by the Dota pointer and Dota logo after a few seconds
- Observe nothing further happening, and Gnome Shell reporting "Application does not respond"

Running on Arch Linux with Linux 4.1.6-1-ck with Gnome Shell, NVIDIA proprietary drivers on a GTX670. [Steam System information](https://gist.githubusercontent.com/beheh/6b362d92ab5774fefeb4/raw/0c41aa16d2b7d1cbf66fe89a4f6176adb5ed64e0/gistfile1.txt).

Log up until the hang:

```
Game update: AppID 570 "Dota 2", ProcID 6385, IP 0.0.0.0:0
ERROR: ld.so: object '/home/benedict/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/benedict/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:6253): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

<-- Lots of repeated LIBDBUSMENU-GLIB-WARNING -->

(steam:6253): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

pid 6387 != 6386, skipping destruction (fork without exec?)

(steam:6253): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

<-- Lots of repeated LIBDBUSMENU-GLIB-WARNING -->

(steam:6253): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/benedict/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/benedict/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198007195959 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198007195959
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20150819112831)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/benedict/.local/share/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/benedict/.local/share/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
```

**Comment by budimanjojo** [comment]
You may need to launch steam using steam libraries. What's your Linux distribution? They don't support launching steam using native libraries from your distro.

**Comment by beheh** [comment]
I am running Arch Linux. Yes, in the past I've had issues running programs with the Steam runtime, so whenever any issue pops up most of times removing the Steam runtime libraries corrects this problem. On the other hand I've never had problems running with my native libraries instead of the Steam ones.

Thanks for your comment, but I fail to understand how native libraries can have an effect on whether I launch from a terminal or directly from my DE. It's not like I usually run Steam from a terminal, I reported this issue because unable to get a Dota log for another issue (#340).

**Comment by budimanjojo** [comment]
It shouldn't give any problem when you launch it using steam runtime on any game I think, bacause most of the games are built using steam libraries to make it compatible with steam os. Regarding your question about why native libraries can affect the game, because distributions built those libraries using some modifications and options those are different between each distribution (I think). And version difference can also be the culprit. Like Arch Linux is using latest libraries, but Debian (which steamOS based on) is still using older libraries. Packages those are required to run also difference between distribution, some needed to be installed manually. Btw I had this problem too and I reported here. You can look at it #173

**Comment by ArnaudAndre** [comment]
There's really no intrinsic difference between getting launched from a terminal and the desktop.

In all likelihood steam needs some environment tweaks to start on arch, the arch maintainer put those in the launcher but you're not reproducing them in your console.
To figure it you'll want to look into your steam.desktop. I don't know how to access the underlying .desktop in gnome shell but in most other desktops you can right click a launcher to get an option to duplicate it on the desktop folder where you can freely look at its innards.

Also, you should be able to get access to steam's output even when launched from the DE at : `/tmp/dumps/${USER}_stdout.txt`

**Comment by beheh** [comment]
Great, that's enough for me.
