### ISSUE TITLE
[Linux] Game is crashing after loading screen

### ISSUE THREAD

**Issue by SexyFlanders** [ValveSoftware/Dota-2#34]
Hello,
The reborn client itself is running well, but if I want to start a game (online or against bots) the game is crashing after loading screen.
Here my systeminformation:
https://gist.github.com/SexyFlanders/22d8bcb02d1ef981ec65

Here is the crashfile dump:
https://drive.google.com/file/d/0BxgzxCaqJxflOWFWd1NITmFsZUE/view?usp=sharing

I hope you can use it?

**Comment by PaoloRotolo** [comment]
Same for me. I'm on Ubuntu 15.04 with an AMD 7790.

**Comment by Gab0** [comment]
Same here. up to date Arch Linux, nvidia proprietary driver.

**Comment by khill** [comment]
Looks like a similar issue as #10 and #14

**Comment by Tehmal** [comment]
I agreee.
When  load screen game crash to desktop (autoclose)

http://wklej.to/hDczB

**Comment by gdrewb-valve** [comment]
@SexyFlanders , your posted crashfile dump is the same issue as #10, namely that source2 is using SSSE3 instructions when it shouldn't.  That'll be fixed in an upcoming update.

@Tehmal and @Gab0 , if you have AMD processors without SSSE3 support your issue is the same thing.

**Comment by Okoyl** [comment]
same here. crashing after loading a game and hearing "All Pick".
Running Ubuntu 15.04 (3.19.0-15-generic) x64
Intel E5200 Dual Core CPU
HD5450 with fglrx-updates version 15.20. 

I was able to run reborn before without fglrx and it worked fine.

**Comment by gdrewb-valve** [comment]
@Okoyl you look like you have a different issue so please open a new one.  Dump files will be in /tmp/dumps.

**Comment by Tehmal** [comment]
@gdrewb-valve true i havent - when to be repaired??

Not all living in Western Europe/USA/Oceania/KR/JA and have cash for better CPUs

**Comment by gdrewb-valve** [comment]
The next release should be out soon and it will have the SSSE3 fix.

**Comment by genX75** [comment]
The game still crashes for me when loading into a real game. I can watch a game just fine, load into the hero preview map and play on that as well. I am on amd phenom hardware.

**Comment by gdrewb-valve** [comment]
Can you try with the 6/30 update?

**Comment by computerfr33k** [comment]
works for me with the new update.

**Comment by SexyFlanders** [comment]
I only tried very shortly this morning. It seems to work now. Thank you very much, you are doing a great job!  I hope valve will continue to support Linux even though playerbase is so small.

**Comment by genX75** [comment]
I was able to play a custom game! I can't commit to a full game yet but I'd assume the issues where related. Nice job and thanks! :-)
