### ISSUE TITLE
[Linux] Dashboard missing content

### ISSUE THREAD

**Issue by beheh** [ValveSoftware/Dota-2#340]
My dashboard is missing any content, not only after startup but also whenever revisiting it:

![Dashboard](http://i.imgur.com/McrQvjj.png)

Steps to reproduce:
- Start Dota 2, select Reborn
- Observe broken Dashboard
- Navigate around and back, observe Dashboard still broken

Running on Arch Linux with Linux 4.1.6-1-ck with Gnome Shell, NVIDIA proprietary drivers on a GTX670. [Steam System information](https://gist.githubusercontent.com/beheh/6b362d92ab5774fefeb4/raw/0c41aa16d2b7d1cbf66fe89a4f6176adb5ed64e0/gistfile1.txt).

I was unable to get a log due to #339. Is there a possibility to log the game output to a file via console options?

**Comment by gdrewb-valve** [comment]
This happens on all platforms (for example http://dev.dota2.com/showthread.php?t=173795) so the issue won't be tracked here.
