### ISSUE TITLE
Accept Button in Hero Customization Won't Exit

### ISSUE THREAD

**Issue by dphildebrandt** [ValveSoftware/Dota-2#341]
Under the Heroes Tab, when you look at a heroe's loadout and hit Cutomize on the bottom near centre.

After customizing, hitting Accept does not close the cutomization area. If you switch away another view, like your armory, and switch back to hero loadout the changes have taken affect.

**Comment by gdrewb-valve** [comment]
I couldn't repro this on Windows or Linux.  Do you have the Sep. 1 update?

**Comment by dphildebrandt** [comment]
I do, maybe it's OSX bug only?

**Comment by gdrewb-valve** [comment]
I don't see it on OSX either.  Does it always happen for you?  Does it matter what hero or item?  If you just hit accept without changing anything does that work?

**Comment by dphildebrandt** [comment]
Seem to always happen. Doesn't matter which hero or item. Accept without a change has the same issue.

The cancel button, when it is clicked, does at least depress. The accept button doesnt even have a noticeable change when you click it.

**Comment by gdrewb-valve** [comment]
OK, we'll have to see if somebody here can find a repro.

**Comment by dphildebrandt** [comment]
Fixed in the newest update.
