### ISSUE TITLE
[OSX] Screen Darkens unecessarily upon death

### ISSUE THREAD

**Issue by dphildebrandt** [ValveSoftware/Dota-2#344]
Can barely see anything its so dark!

I think it gets darker each time.

**Comment by dphildebrandt** [comment]
Seems to only happen on the 3rd and 4th highest graphic settings.

**Comment by gdrewb-valve** [comment]
Duplicate of #309?

**Comment by dphildebrandt** [comment]
Ah yes, my bad!
