### ISSUE TITLE
LINUX Reborn crashing after loading to start menu

### ISSUE THREAD

**Issue by subclavianGroove** [ValveSoftware/Dota-2#346]
Like in title game crashes any time after getting to start menu for 5-10 seconds. In that time I can select game search options but can't go to the game options menu. Has been happening sine beta first came out and I hoped at some point an update would fix it but now I'm not so sure. Here's the system info, I'm not sure where to find my crash reports.  

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x12
    CPU Model:  0x1
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2897 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-26-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6550D

```
Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1046
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6758
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,74" x 10,55"  (21,50" diag)
                                        47,6cm x 26,8cm  (54,6cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  7470 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  741544 Mb
    Largest Free Hard Disk Block:  629872 Mb

Installed software:

Recent Failure Reports:
    Wed Sep  2 07:01:39 2015 GMT: file ''/tmp/dumps/crash_20150902090021_1.dmp'', upload yes: ''Discarded=1''
    Wed Sep  2 07:14:52 2015 GMT: file ''/tmp/dumps/crash_20150902091434_1.dmp'', upload yes: ''Discarded=1''

**Comment by gdrewb-valve** [comment]
Do the failure report times correspond to the times the game crashed?  If so you can get the dump files mentioned in the messages and put them on a file sharing site and we can look.

**Comment by subclavianGroove** [comment]
It seems the times match up. Here is my dump file, thanks for your time

https://www.mediafire.com/folder/e181qcrforj99/dumps

**Comment by gdrewb-valve** [comment]
I took a look at the dump and it's crashing deep inside fglrx, the AMD graphics driver.  There aren't a lot of further concrete steps.  You might try a different driver if you can find one.  We'll keep this open for now but it likely will eventually be closed as outside of Valve's scope.

**Comment by subclavianGroove** [comment]
Thanks for doing what you can. I tried switching to the other driver and now I can't even open steam haha.

**Comment by gdrewb-valve** [comment]
Were you able to make more progress on this?  Should it stay open as a Reborn issue?

**Comment by gdrewb-valve** [comment]
Closing pending a response that this is still happening.
