### ISSUE TITLE
[OSX] Crash in OpenGL driver on HD 3000 when Shadow Fiend Ultimates

### ISSUE THREAD

**Issue by danginsburg** [ValveSoftware/Dota-2#348]
As reported in comments in #9, there is a crash inside the OpenGL driver on HD 3000 Mac OS X 10.10.5 during Ultimates with heroes such as Shadow Fiend.  Repo steps:
1. Select Heroes tab
2. Select Shadow Fiend
3. Click Level to Max
4. Perform Requiem of Souls

System info:
Processor Information:
    Model:  MacBookPro8,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 3000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x126
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.22" x 7.01"  (13.23" diag)
                                        28.5cm x 17.8cm  (33.6cm diag)
Primary VRAM: 451 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  714230 Mb
    Largest Free Hard Disk Block:  663189 Mb

Installed software:
    Accessibility Inspector
    App Store
    Application Loader
    Automator
    Calendar
    Contacts
    Dota 2
    FaceTime
    FileMerge
    Game Center
    iBooks
    Icon Composer
    Image Capture
    Instruments
    Junos Pulse
    Launchpad
    Maps
    Messages
    MiniTerm
    Mission Control
    Notes
    OpenGL Driver Monitor
    OpenGL Profiler
    OpenGL Shader Builder
    Photos
    Pixie
    Quartz Composer
    Quartz Composer Visualizer
    Quartz Debug
    Reminders
    SteamBeta
    Stickies
    Xcode

**Comment by danginsburg** [comment]
I have a fix for this issue, the fix will be in the next update.  The ultimates were using a vertex shader that caused us to use more than 16 total samplers/textures.  I don't believe this should have been a problem (HD 3000 advertises 48 GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, many more than needed), but it was crashing inside the OpenGL driver.  I worked around it by reducing the number of textures by one so we stay under 16.

**Comment by dayvough** [comment]
Played a couple of rounds on Overthrow earlier and an SF demo, it's working now. Thanks guys!

**Comment by danginsburg** [comment]
Closing.
