### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#349]
Open friend's account info and it is showing my setting (wins, commends), all other is good.

![2015-09-02 16 41 57](https://cloud.githubusercontent.com/assets/13041082/9632732/a20550de-5191-11e5-9963-fd837de98169.png)
![2015-09-02 16 24 10](https://cloud.githubusercontent.com/assets/13041082/9632734/a3f93554-5191-11e5-9d4e-559b0daa9ee1.png)

**Comment by gdrewb-valve** [comment]
Not a Mac/Linux issue.
