### ISSUE TITLE
[Linux] Alt-tabing couses sounds to be queued

### ISSUE THREAD

**Issue by MaikuMori** [ValveSoftware/Dota-2#351]
While testing other issues I noticed that if I alt-tab bot match and tab back some time later it will just play all the sounds that happened in background instantly. It results in a lot of sounds being played right as I tab back into the game.

**Comment by gdrewb-valve** [comment]
Is this still active?

**Comment by MaikuMori** [comment]
Seems to be fixed.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
