### ISSUE TITLE
[Linux] HUD is with green boxes

### ISSUE THREAD

**Issue by hexvalid** [ValveSoftware/Dota-2#352]
The game looks exactly as follows. Map does not appear at all.
![2015-09-03 00-12-00 ekran goruntusu](https://cloud.githubusercontent.com/assets/4836149/9644765/90e66768-51d0-11e5-852b-469ed89d7d59.png)

Operating System Version:

> Linux 3.10 (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.14.51-1-lts
>    X Server Vendor:  The X.Org Foundation
>    X Server Release:  11702000
>    X Window Manager:  GNOME Shell
>    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:

>    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
>    Driver Version:  3.0 Mesa 10.6.4
>    OpenGL Version: 3.0
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x1002
>    DeviceID:  0x6840
>    Number of Monitors:  1
>    Number of Logical Video Cards:  2
>    Primary Display Resolution:  1366 x 768

**Comment by danginsburg** [comment]
I have tried to repro this on mesa 10.6.4 (built from source) on Haswell and have had no luck so far.  A couple of questions: does the corruption disappear if you add -gl_force_sm30 to your command-line?  I see that you have a custom HUD skin, does it occur with the default skin?  My best guess so far is a mesa issue with the IvyBridge backend.  It looks similar to a bug we had with scaleform when GL_CLIP_DISTANCE0 was not disabled by the engine, but that fix went in a while ago.  All of the corruption is with scaleform based on the screenshot.  Are you able to upgrade to a more recent version of mesa to test (either 10.6.5 or latest git)?

**Comment by hexvalid** [comment]
I tried add ( %command% -gl_force_sm30 ) as launch options with the latest version mesa (10.6.5). No changes. such again: 
![2015-09-04 12-49-27 ekran goruntusu](https://cloud.githubusercontent.com/assets/4836149/9681054/d5f3bcc8-5303-11e5-82f3-569a0b8bbe25.png)

**Comment by gemakochi** [comment]
same here.
![2015-09-06 13 53 27 ekran goruntusu](https://cloud.githubusercontent.com/assets/581848/9704016/e324dd0e-549e-11e5-8849-855f3bf720fa.png)

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4013 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Operating System Version:
    Debian GNU/Linux 8.1 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660 Ti/PCIe/SSE2
    Driver Version:  4.4.0 NVIDIA 340.65
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1183
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 53,1cm x 29,9cm  (60,9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC898

Memory:
    RAM:  7740 Mb

Miscellaneous:
    UI Language:  English
    LANG:  tr_TR.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  119086 Mb
    Largest Free Hard Disk Block:  59716 Mb
```

**Comment by ecylmz** [comment]
I'm using Ubuntu 15.04, I installed latest graphics-drivers with ppa:oibaf/graphics-drivers.

Same here.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.1.0-devel (git-3e9df0e 2015-09-09 vivid-oibaf-ppa)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0xa16
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13,54" x 7,60"  (15,51" diag)
                                            34,4cm x 19,3cm  (39,4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  5856 Mb

Miscellaneous:
    UI Language:  English
    LANG:  tr_TR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  108625 Mb
    Largest Free Hard Disk Block:  26264 Mb

Installed software:

Recent Failure Reports:

```

**Comment by eke2152** [comment]
Same issue with ARCH Linux (Linux 4.1.6.1-ck)
Intel i5-4200M
GTX760M

Tried with both Intel & Nvidia cards.

**Comment by danginsburg** [comment]
So, from what I am hearing this is not GPU or driver-specific because we have it reported on @ecylmz Haswell mesa 11.1.0-devel, @gemakochi NVIDIA 360.45 GTX 660 @ErkanMDR IvyBridge mesa 10.6.4, and @eke2152 does not specify drivers but also Intel and NVIDIA.  The problem is, I have not been able to repro this.  @ErkanMDR you have a HUD skin, do others of you have a HUD skin?  Can you narrow down any further what might be the common cause?

**Comment by ecylmz** [comment]
@danginsburg i've tried this command "-gl_force_sm30" on "launch options"  but not working. I've switched default HUD but the problem still continues. Also i can't clicking on minimap.

`LANG:  tr_TR.UTF-8`

Is this considered as a common cause? just a guess.

screenshots as follows:

![reborn_default_hud](https://cloud.githubusercontent.com/assets/248267/9773090/fbe81c82-5748-11e5-9e11-733364ad3135.png)

![reborn_pick_screen](https://cloud.githubusercontent.com/assets/248267/9773099/083d461a-5749-11e5-9e53-2ed9d7d73cfa.png)

**Comment by ecylmz** [comment]
@danginsburg: EUREKA! This is locale problem. I changed my system locale from `tr_TR.UTF-8` to `en_US.UTF-8`. This problem fixed for me.

screenshot as follows:

![reborn_fix](https://cloud.githubusercontent.com/assets/248267/9774072/f5534990-574e-11e5-80fd-e9f20ef2602b.png)

**Comment by hexvalid** [comment]
Hahahah ! so thanks @ecylmz . I solved the problem by starting this way:

> LC_ALL=EN steam

Not need for change fully system locale. Problem is in Turkish language.
screenshot:
![2015-09-10_00001](https://cloud.githubusercontent.com/assets/4836149/9774249/ee9ef4d6-574f-11e5-9e3b-2fd94dc0d7fe.jpg)

**Comment by eke2152** [comment]
Yep LC_ALL=EN steam solved the problem. I'm also using TR language.

**Comment by suhaaktas** [comment]
https://github.com/ValveSoftware/Dota-2/issues/3 this was similar and got fixed.
https://github.com/ValveSoftware/Dota-2/issues/312 and this is similar too.
Edit:
I am also using TR language.
i tried LC_ALL=EN steam and everthing seems fine except the fps drop(fastest settings). is this because i am running steam from console?
are there any more optimizations on the way that could help at least reach to source1 fps levels ?

**Comment by gemakochi** [comment]
thanks @ecylmz, i modified launcher at  _~/.local/share/applications/steam.desktop_ to run without console.

```
-Exec=/usr/games/steam %U
+Exec=env LC_ALL=EN /usr/games/steam %U
```

**Comment by danginsburg** [comment]
Thanks everyone for the help in narrowing down the problem, I was able to reproduce and fix it.  The fix will be in the next update to Dota 2.

**Comment by hexvalid** [comment]
Now fixed in new update. Thanks @danginsburg and everyone
![2015-09-12_00001](https://cloud.githubusercontent.com/assets/4836149/9830453/5b4b6752-5937-11e5-8d34-9476b477ccfc.jpg)
