### ISSUE TITLE
[Linux] Severe flickering on latest update

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#355]
To check the latest version, I played a jungle Nature's Prophet. Right after I got three treants, at about 2:30, the engine started flickering extremely badly, apparently drawing entire black or very dark frames (starting midway through the screen, then wrapping to the next one) at rates varying from 2-5Hz. The flickering was intermittent and didn't seem to be related to the number of items on-screen or whether a Clarity was active. The actual game time didn't stutter, just the output.

I'm running KWin 4.11.22 on Arch, with Mesa 10.6.4 and Linux 3.17.6.

**Comment by chrylis** [comment]
This appears to be related specifically to the Radiant medium creep camp with vision of the bottom rune; I've only seen it there (and haven't played Dire), but it shows up reliably when I take Treants there around 3min. Upgrading to Linux 4.1.6 for a fix for a GPU issue I had elsewhere did not help.

**Comment by danginsburg** [comment]
@chrylis Can you post your full system information from Steam?  It is not clear from the description what GPU you have. Does the bug still occur if you change video settings (i.e. turning off Ambient Occlusion, Anti-Aliasing, Shadows)?  Can you post a match ID we can use to repro?

**Comment by chrylis** [comment]
That was mostly happening on bot matches, though I had something kinda similar-but-not-exactly in another match, and I'll see if I can figure out how to dig up the ID for it. I don't have AA turned on (strangely, it drops the frame rate by 50%, but I can't tell a visual difference with it disabled), and I didn't know what other particular settings to change. I'll try with occlusion and shadows.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.6.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0xd26
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 2560 x 1600
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: VIA VT1802

Memory:
    RAM:  15972 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  128885 Mb
    Largest Free Hard Disk Block:  39221 Mb

Installed software:

Recent Failure Reports:
    Thu Sep  3 08:46:15 2015 GMT: file ''/tmp/dumps/crash_20150903021743_1.dmp'', upload yes: ''Discarded=1''
```

**Comment by danginsburg** [comment]
@chrylis I have never been able to repro this bug.  If this is still happening and you can provide repro steps, I will reopen this.
