### ISSUE TITLE
Autoexec.cfg?

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#357]
I read the changelog of 1/9 listed that autoexec is supported, but mine is still not working. I put in fps_max "300" and the ingame fps is still 120.

**Comment by gdrewb-valve** [comment]
I just tried it and it worked OK.  Where did you put the file?  What exact filename did you use?  It should be autoexec.cfg in the cfg subdir of <wherever you have Reborn>/game/dota.

**Comment by budimanjojo** [comment]
Yes it is. Source 1 Dota worked but Reborn gives me 120 fps. I'll try other command to see if it only happens on fps_max later

**Comment by gdrewb-valve** [comment]
Just to be clear, you have two then, the one you're using for Source 1 and the one you're using for Reborn since they're in different places?

**Comment by budimanjojo** [comment]
Wait, so where is the one for reborn located? I don't know they have 2 different locations.

**Comment by gdrewb-valve** [comment]
Source 1 is steamapps/common/dota 2/dota/cfg.  Reborn is steamapps/common/dota 2/game/dota/cfg.  Note the extra 'game' dir in there.

**Comment by budimanjojo** [comment]
Ok, I'll check later.

**Comment by budimanjojo** [comment]
Found it, closing. Thanks gdrewb
