### ISSUE TITLE
[Linux] RadeonSI flickering overlay

### ISSUE THREAD

**Issue by dietrmat** [ValveSoftware/Dota-2#358]
When the overlay is opened the screen flickers. Running AMD open source drivers (RadeonSI) on Kernel 4.1 and Mesa 10.6.5.

As this is NOT an issue on Dota2 with Source 1 engine but with Source 2 engine. So it seems an issue with Reborn.
## If you need more information feel free to comment here.

Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x3c
    CPU-Stepping: 0x3
    CPU-Typ: 0x0
    Geschwindigkeit: 3600 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerkinformationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "Manjaro Linux" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.1.6-1-MANJARO
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11702000
    X-Fenstermanager: KWin
    Steam-Runtime-Version: steam-runtime-release_2015-06-12

Grafikkarte:
    Treiber: X.Org Gallium 0.4 on AMD PITCAIRN

```
Treiberversion: 3.0 Mesa 10.6.5
OpenGL-Version: 3.0
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 60 Hz
Anbieterkennung: 0x1002
Gerätekennung: 0x6810
Anzahl der Monitore: 1
Anzahl der logischen Grafikkarten: 1
Prim. Anzeigeauflösung: 1920 x 1080
Desktopauflösung: 1920 x 1080
Prim. Anzeigegröße: 47,7 cm x 26,8 cm (54,7 cm diag.)

Kein prim. VRAM entdeckt
```

Soundkarte:
    Audiogerät: Realtek ALC662 rev1

Speicher:
    RAM: 7927 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 930713 MB
    Größter freier Festplattenspeicherblock: 458384 MB

Installierte Software:

Neueste Fehlerberichte:

**Comment by gdrewb-valve** [comment]
You mean the Steam overlay, correct?  You'll want to report that to the Steam team.  It likely won't be handled here.

**Comment by dietrmat** [comment]
But its only an issue on Dota 2 Reborn. Still a Steam team bug?

**Comment by gdrewb-valve** [comment]
Reborn works fine except when the overlay is up, correct?  That would suggest it's an overlay problem and not a Reborn problem.

**Comment by dietrmat** [comment]
Exactly, how to move the bug to steam team?

**Comment by gdrewb-valve** [comment]
The steam-for-linux repo here is the place to copy-and-paste your report into.

**Comment by danginsburg** [comment]
I am able to repro this on AMD 7950 mesa 10.5.9 Ubuntu 15.04.  I'll take a look at the issue.  It doesn't happen in Catalyst 15.7.

**Comment by gdrewb-valve** [comment]
dietrmat also opened 4002 in steam-for-linux if you find a resolution.

**Comment by dietrmat** [comment]
Dear Valve developers, I really like your Linux efforts. Thx for your fast and competent support!
Btw., Dota 2 Reborn runs great on open source drivers. You rock, keep up the great work.

**Comment by danginsburg** [comment]
This was a bug in the Steam Overlay with not disabling GL_CLIP_DISTANCE0.  I have checked in a fix, it will be in a future Steam update (NOTE: Steam, not Dota 2 Reborn).  I'll close out this bug.
