### ISSUE TITLE
[MAC] √ Mute All Chat settings does not reset.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#361]
I'm not sure if this is Mac specific but I'm running mac  and I have a strange problem. Every game I join by default the √ Mute All Chat setting is selected. This means that at the start of the game or even during loading in the lobby I can not see anything, then once the game starts I could untick that setting and I can see what everyone says but once I leave the game the setting isn't saved and the next game it's the same story. I've tested this only with custom games, haven't played normal dota on reborn yet.

EDIT: I just played a normal game of dota and de-muted at the start, after the game was finished I hosted a private lobby and the setting was saved. I think it might be fixed, so in short the issue might be with custom games not remembering your setting even after you've deselected them in game.

EDIT2: Just did some testing with custom games. So it appears in fact that the option you select does not carry out to your next custom lobby game or normal game. If you had √ Mute All Chat de-selected prior to the game then join a custom game, mute it in game and then leave and join a new custom game, the option isn't ticked. The same goes for the reverse scenario. If you had √ Mute All Chat enabled from normal games previously or what not, then went in to a Custom Game, de selected it after you were given the choice to do so, left the game and then joined a new custom lobby, the de selection is invalid and your √ Mute All Chat setting is still on, even though you de-selected it last game.

**Comment by gdrewb-valve** [comment]
This isn't a Mac-specific issue.  I've passed it on to the larger team.
