### ISSUE TITLE
[Mac] Game crashes when watching replay.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#362]
Report https://gist.github.com/Vuccappella/5c391b0df24499cc75e0

It crashed 3-4 times. Usually when I fast forward manually with the mouse at a particular time of the replay or when fast forwarding by speed.

**Comment by danginsburg** [comment]
This issue is not Mac-specific so we won't track this here.  It has been reported on the Windows client as well (http://dev.dota2.com/showthread.php?t=177744).  It has been passed along to the larger team.
