### ISSUE TITLE
[OSX] Fullscreen, App Alert Issues

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#363]
Can we have an option to enable native osx fullscreen which is to use a separate space. I would really like to have my dota running in a different window/space rather than minimizing to the dock.

Secondly, can we also have the old app bounce warning for resume/matchmaking alerts back?

**Comment by Vuccappella** [comment]
I like the new notification which is global and makes a sound,  the bouncing icon as well would be nice.

In terms of fullscreen to a separate space, I have no idea but there might be a issue since the game is a port ? For example, I tried streaming dota with OBS but OBS does not recognise dota2 as an application so you can't allocate a special screen for it in OBS, I guess due to the fact that it's not a native application and OS can't allocate it as such. I might be totally wrong though but it might not be as easy as it sounds.

**Comment by gxgani** [comment]
@Vuccappella I do like the notification too, but I happen to have my notification center in DnD most of the time. It also bounces when the game resumes or someone in party chat has replied.

Regarding the OBS, You'll have to inject with syphon in order to capture dota2. 
![](http://i.imgur.com/OWrDj6o.png)

By launching it into separate space, the brightness of the game wouldn't conflict with OSX's window but with current configuration, it conflicts a lot and I really like to swap between my spaces with 4-finger gesture rather than having to use keyboard shortcuts every time.

**Comment by dphildebrandt** [comment]
Yeah the OSX full screen in a different space, like the old client, was perfect. Also the current notification popup image has a terminal picture instead of, perhaps, the Dota2 symbol.

**Comment by espadolini** [comment]
As a workaround, you can run it in "desktop-friendly fullscreen", disable "minimize when the window loses focus" and just drag the window onto a new space from Mission Control.

As an aside, how about supporting 16:9 resolutions with letterboxing?

**Comment by danginsburg** [comment]
The problem we have right now is if we allow "Desktop Friendly Fullscreen" to use a separate space there is bug #176.  The issue there is that when going from "Desktop Friendly Fullscreen" -> "Exclusive Fullscreen" -> "Windowed" we end up with a window in its own space which users objected to.  This may be a bug in SDL, we need to investigate it further.

**Comment by gxgani** [comment]
Can we have the "Bounce to Alert" back? Since the latest update, I've stopped getting notifications from the game, sound alert as well (Desktop sound alert has been enabled". 

Got 2, 24HRS BAN due to this and longer matchmaking time issue.

**Comment by danginsburg** [comment]
Duplicate of #237 which as I noted in that bug has been fixed and will be in a future Dota 2 update.  You will be able to switch spaces in Desktop Friendly Fullscreen mode with that update.

**Comment by gxgani** [comment]
By future you mean not the update I received now of 50MB size?

**Comment by danginsburg** [comment]
No, the fix has not shipped yet.

**Comment by danginsburg** [comment]
Fix has been released.
