### ISSUE TITLE
[Mac] Nothing happen after preparing to launch dota 2 reborn

### ISSUE THREAD

**Issue by ezracb** [ValveSoftware/Dota-2#365]
I have installed Dota 2 Reborn on mac and when I press play and select Dota 2 Reborn beta, it says preparing to launch but it doesnt launch and nothing opens. What happen with this dots 2 reborn? Where is it wrong?

**Comment by gramathy** [comment]
If you try to launch it again does it give you a "app already running" error? I fixed this by restarting Steam.

**Comment by ezracb** [comment]
No, nothing message I have got...
It is nothing happened after relaunch till many times..

**Comment by danginsburg** [comment]
@ezracb Can you please add -con_logfile to your Launch Options and then post your console.log from the dota2 directory on this bug?

**Comment by madhavan10** [comment]
I added -con_logfile to my launch options and tried to run dota. No console.log file was subsequently created. I tried running the dota 2 executable directly from the osx64 folder and the terminal reported a segmentation fault.

**Comment by danginsburg** [comment]
The file should be written to ~/Library/Application Support/Steam/steamapps/common/dota 2/game/dota/console.log  .  If you try to run directly from the terminal, first do export DYLD_LIBRARY_PATH=$(pwd) from the osx64 folder.

**Comment by ezracb** [comment]
I didn't find any console.log after i put that launch options
now dots 2 has merge with dots 2 reborn, so now i'm stuck here… i cannot play..

**Comment by ezracb** [comment]
okay, what is the requirements of dots 2 reborn on mac?

**Comment by madhavan10** [comment]
I also cannot even play after latest patch. Please revert immediately, this is absurd.

In addition, no console.log in the directory you specified @danginsburg and also my directory structure is common/dota 2 beta/ not common/dota 2/

**Comment by eNormt** [comment]
I have been experiencing the same problem for two days. Please revert!

I have tried every troubleshoot, contacting steam support and followed every advice from every thread by other users experiencing the same problem, without luck.

**Comment by eNormt** [comment]
Anyone find a fix that worked? Or just waiting for steam/dota update?

**Comment by eNormt** [comment]
Updated to yosemite, and the game is working again!
so to conclude: The new update makes it impossible to play dota 2 on mac with version 10.8.5

to anyone who hasn't updated yet, do it :)

**Comment by danginsburg** [comment]
@eNormt Yes, that is right, OS X 10.9 is the new minimum.  We updated the Steam page to reflect this.  Closing this one out.
