### ISSUE TITLE
[Linux] Sound settings do not really matter any more

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#366]
With latest update, sound settings are strange.
Sound changes from  loud to quiet during game (I am also in teamspeak) - the sound when you commend a player is REALLY LOUD. The ingame music is to loud (in menu) and in game it changes level.

---

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux stable-updates (sid) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 340.76
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1184
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                        53,1cm x 29,9cm  (60,9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia GPU 40 HDMI/DP

Memory:
    RAM:  7954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  53884 Mb
    Largest Free Hard Disk Block:  23940 Mb

Installed software:

Recent Failure Reports:

**Comment by davidw-valve** [comment]
When you adjust the audio master volume does it affect the volume of the sounds? Are all sounds in-game very quiet? (Music / sound effects / etc?)

I am afraid I cannot reproduce this so far.

**Comment by budimanjojo** [comment]
I can confirm commending/reporting sounds are louder than everything else in the game. My music sound is on the 15% (because I always listen to music while playing) and my master sound is on 50%. All sounds like announcers and kills are normal except commending and reporting, in game music is good on me though.

**Comment by ChrisLauinger77** [comment]
It improved in the last update - but the commenting/reporting sounds are still really LOUD.

**Comment by gdrewb-valve** [comment]
A recent update should have fixed the commendation sound, are you still hearing issues?

**Comment by ChrisLauinger77** [comment]
nope - its actually better now

**Comment by gdrewb-valve** [comment]
Thanks, closing.
