### ISSUE TITLE
[Linux] Chat wheel is broken

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#368]
Chat wheel does work but when it opens I only can select the right entry (3 o'clock).
It also scrolls to the right when I open chatwheel. (i use mouse5 to open it and mousenav to select in old  client)

**Comment by danginsburg** [comment]
This appears to be a duplicate of #286 and #198, correct?  Or is this something different?

**Comment by ChrisLauinger77** [comment]
Correct same as #198

**Comment by gdrewb-valve** [comment]
I have reopened #198, closing this duplicate.
