### ISSUE TITLE
Mac crash after opening reborn client

### ISSUE THREAD

**Issue by davidbograd** [ValveSoftware/Dota-2#369]
My MacBook Pro (Retina, 15-inch, early 2013) with OS X Yosemite v 10.10.4 crashes everytime I open the Dota 2 Reborn Client.

I get to run the software, see the initial UI (top bar and plat button in the bottom) - rest is black. Then Dota 2 Reborn crashes. It is like this everytime.

**Comment by danginsburg** [comment]
@davidbograd Could you please share a minidump so we can investigate the crash?  You can find the location of the most recent minidump by going to Steam -> Help -> System Information.  Please also post your system information on the bug.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
