### ISSUE TITLE
[Linux] Only black screen with Intel Iris Graphics 5100

### ISSUE THREAD

**Issue by hadim** [ValveSoftware/Dota-2#37]
While the Dota 2 original works fine.

My system : Linux Mint 17.2 on Asus Zenbook UX301LA (Intel Iris Graphics 5100).

``` sh
$ uname -a
Linux boromir 3.19.0-18-generic #18~14.04.1-Ubuntu SMP Wed May 20 09:38:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ glxinfo  |grep Mesa
client glx vendor string: Mesa Project and SGI
OpenGL renderer string: Mesa DRI Intel(R) Haswell 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL version string: 3.0 Mesa 10.1.3
```

Thank you !

**Comment by danginsburg** [comment]
Can you upgrade to a more recent build of mesa?  I believe the minimum required is 10.2 because 10.1 is missing ARB_separate_shader_objects.  We should do a better job of reporting the missing functionality.  I am testing here on Iris Graphics 5200 using mesa 10.3.2 and 10.5.8.

**Comment by hadim** [comment]
Thanks !

```sh
$ sudo apt-get install ppa-purge
$ sudo ppa-purge ppa:oibaf/graphics-drivers
$ sudo apt-get update
$ sudo apt-get dist-uprade
```

did the trick and now it works !

**Comment by danginsburg** [comment]
I also did update the code to check for the presence of GL_ARB_separate_shader_objects and it will now fail at startup with the error: 

Required OpenGL extension "GL_ARB_separate_shader_objects" is not supported.  Please update your OpenGL driver.
