### ISSUE TITLE
[Linux] Spectator fog setting resets after switching away

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#370]
When switching away from a spectated game and back to it, the fog setting resets to whatever it was on game load.

**Comment by danginsburg** [comment]
@chrylis I'm having trouble repro'ing this.  Can you provide specific repro instructions?  I have tried toggling Atmospheric Fog on/off during a replay and I don't see the setting reverting.

**Comment by chrylis** [comment]
I don't mean Atmospheric Fog, I mean the spectator setting for which team's fog is applied.

**Comment by danginsburg** [comment]
@chrylis Thanks, I have repro'd the bug and passed it along to the larger team.  It is not specific to Linux (happens on Windows too) so we will not track it any further here.
