### ISSUE TITLE
Open mic in party stops working randomly

### ISSUE THREAD

**Issue by lakerkid** [ValveSoftware/Dota-2#371]
Open mic while in party works sometimes and other times I can hear the other person and they cannot hear me.

**Comment by davidw-valve** [comment]
What operating system are you on? Do you still see the mic icon when the person is talking?

**Comment by lakerkid** [comment]
I'm on Mac. Sometimes the bubble shows other times the bubble doesn't show. He's on PC if that has anything to do with it?

**Comment by gdrewb-valve** [comment]
This probably isn't a Linux or Mac specific issue.  I've passed this on to the larger team and this won't be tracked here.
