### ISSUE TITLE
[Linux] first blood awarded on second kill in bot match

### ISSUE THREAD

**Issue by rmbleeker** [ValveSoftware/Dota-2#373]
It has happened twice now in a bot match that the first blood announcement played on the second kill in the match. I'm not sure if the extra gold was also awarded or if that indeed went to the bot who made the actual first kill.

Playing on the Radiant side in a 5v5 match with hard bots on Ubuntu 14.04 LTS

**Comment by ArnaudAndre** [comment]
First blood is only awarded if a hero gets credit for the kill. It's possible that one team gets credit for an enemy hero kill while none of their heroes does. Possible scenarios include :
- enemy hero dies alone to creeps / tower
- enemy hero dies to a creep/tower last hit while 2 or more friendly heroes are susceptible to get an assist (they both get an assist, none gets the kill)

Note that outside of first blood the rules for getting credit for kills and getting gold/XP for them are mostly disconnected.

**Comment by rmbleeker** [comment]
Hm that might be what was going on indeed, Dota bots are notoriously stupid when it comes to taking creep/tower damage. Closing this issue.
