### ISSUE TITLE
[OS X] Game causes hard crash of computer

### ISSUE THREAD

**Issue by gramathy** [ValveSoftware/Dota-2#374]
Bear with me, this one's weird and I don't expect a quick resolution.

This has been happening, as far as I can tell for me, since Reborn started. At first I chalked it up to my video card unseating itself or overheating, but having just gotten an extra pair of fans to keep air moving and a backplate for the card, this has basically been ruled out (though I'm considering swapping it to a different PCI slot to see if that changes anything). Keep in mind this only ever happens in reborn and even running the Valley benchmark (which gives me higher temps than Reborn does) for several minutes doesn't cause this, so I no longer think it's a hardware issue.

What happens is my computer completely locks up, screen goes black, whatever sound sample was playing finishes playing, and then nothing. No mouse, no video or audio, but technically i haven't checked if the machine still responds to ping. I guess I'll do that next time it happens.

Then the weird part, which i honestly have no explanation for and don't expect a resolution of, I just thought it was interesting enough to mention:

If I reset the computer via the actual reset button, my video card is no longer recognized. I have to power the machine down, remove the card, power up the machine, shut down the machine, then reinstall the card, and THEN it will work.

If I hard down the machine via the power button, it starts up normally (or as normally as a hackintosh ever does)

Generally speaking, this happens after some time has passed in game (generally more than 20 minutes, but since the most recent update I can't watch my old replays to confirm)

I have a couple replay numbers where this has happened to me:

1780063707, I'm SK, disconnect after 20 minutes right as I respawn (from my perspective)

1775440885, I'm timber, disconnect much later in the game (I don't remember when and I can't access the replay to check.

I don't remember any others, and it's not every game, so best I can do is add more as I encounter the issue. Is there a potential crash log location I could pick out and send to you guys for further investigation?

<script src="https://gist.github.com/gramathy/5996562.js">System Specs</script>

I recall something similar happening long ago in the early OS X days of Source 1 dota, but I don't know how related it might be and I don't remember doing anything about a bug report, but S1 dota no longer does it.

**Comment by gramathy** [comment]
Side note: haven't played since most recent patch, might not occur anymore?

**Comment by davidw-valve** [comment]
If it is causing your computer to completely lock up and require a reboot then it is almost certainly a problem with your hardware (or OS software) and there is little we can do to resolve it.

**Comment by gramathy** [comment]
I'll see what happens on the next driver refresh, but I can say for sure it doesn't do this in any other program, including heavy use benchmarks like Valley and it also seems to happen when a particle effect pops in (drawn but not necessarily first time) due to a spell cast.

**Comment by luntik2012** [comment]
still have the same on ubuntu 15.10 with latest updates

**Comment by gdrewb-valve** [comment]
What is still active here?  The original report was on Mac and possibly doesn't happen any more?  Then luntik2012 reported a crash on Linux which would be a completely separate thing.  As davidw-valve said both are driver errors and not Reborn problems, but before I close this I want to see if anything has changed.

**Comment by gdrewb-valve** [comment]
Closing pending more information.
