### ISSUE TITLE
[OSX] Framerate low on Treasury Tab on HD 4000

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#375]
The frame rates drop drastically at Treasury Tab, Featured heros and in game aswell. 

Intel HD ~~3000~~4000
Yosemite 10.10.5

**Comment by danginsburg** [comment]
I just tried on my Macbook Pro (13-inch, Early 2011) OS X 10.10.5 HD 3000 384MB and the Treasury tab at 1280x800 runs at 37fps (run with -console +cl_showfps 2).  What framerate are you seeing?

**Comment by gxgani** [comment]
Sorry I have a HD4000(MBPro 2012) and wow 37fps on a 3000?

![](http://i.imgur.com/W4cLnCC.png)

![](http://i.imgur.com/4TJPXJG.png)

PS: Featured tab never stuttered before update when I refreshed.

**Comment by gxgani** [comment]
Secondly, is the game window processing even when it's not in focus/minimized? I noticed that when there's a graphic intensive content running in the client such as set preview even main menu with Source1 client, osx stutters. But with Source 2, OS Stuttering doesn't seem happen when I am at the main menu, but at treasury or featured tab it does.

**Comment by danginsburg** [comment]
@gxgani OK, thanks for the screenshots, I thought you meant the main Treasury page.  Yes, I am seeing closer to 10fps now on HD 3000.

**Comment by gdrewb-valve** [comment]
Has this changed since September?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
