### ISSUE TITLE
[OSX] Desktop Friendly Full Screen Setting Not Saved

### ISSUE THREAD

**Issue by xylein** [ValveSoftware/Dota-2#376]
Everytime I start Reborn, I have to change my video setting to Desktop Friendly FullScreen from Exclusive FullScreen because Cmd+Tab doesn't work. How can I save this setting?

OSX 10.9.5

**Comment by danginsburg** [comment]
I just tried this and am unable to repro.  If I set it to "Desktop Friendly Fullscreen" at 1440x900 (my desktop resolution), quit, and come back in then it does set "Use my monitor's current resolution", but that's because Desktop Friendly Fullscreen is the equivalent of that setting.  If I set "Desktop Friendly Fullscreen" at a non-desktop resolution then it keeps the setting between exits.  Please post details on how to repro this (i.e. what is your monitor resolution, what setting to do you choose, and what setting do you see when you go back in the game).

**Comment by xylein** [comment]
My setting was at "Use advanced settings" and it was set at 1440*900, 16:10 and Exclusive Full Screen when I started Reborn, as far as I can remember. To try out some scenarios I switched to "Use my monitor's current resolution" which seemed to work exactly as I want(and wanted with Desktop Friendly Fullscreen as I mentioned). However, now when I restarted Reborn I have a whole different issue with the game loading on some weird resolution(on Fullscreen). I can't quit or Cmd Tab from it and only Cmd Alt Esc helps.
http://imgur.com/3IoQ4Lj

Relevant system info:
http://imgur.com/w741ngq
http://imgur.com/w741ngq

**Comment by xylein** [comment]
I rebooted, tried again. Same problem. I tried to switch through the 5 resolutions provided in MAC. All of them give the same result.

**Comment by danginsburg** [comment]
What resolution is your desktop set at?  Can you try to provide a resolution setting both for your desktop and the application that causes the issue or some other repro steps?  I'm not able to repro this yet from your description.  I've tried setting various exclusive full screen and desktop friendly resolutions and exit and restart and have not seen this issue.

**Comment by xylein** [comment]
Sorry I didn't copy paste accurately.
http://imgur.com/gfeI4R6
I am not able to see the in game settings now.
The game loads up like this: http://imgur.com/3IoQ4Lj

And the game went into Reborn only mode :(

**Comment by danginsburg** [comment]
OK, I am still trying to reproduce it.  In the meantime, you can use some command-line options to get the game up at a resolution that works for you.  -sw will launch in windowed mode.  You can specify resolution with -w XXXX -h YYYY which gives the resolution you want. Should at least get you unstuck.

**Comment by xylein** [comment]
I am running it right now using -sw in the launch option and then re-setting the video configuration to "Use my monitor's current resolution".

This is what the settings panel opens to: http://imgur.com/9reVJId in case that is any help.

**Comment by facupedrazzini** [comment]
Im using 1440x900 in OS X 10.10.5, and every time I restart the dota 2 I have to set Desktop Friendly fullscreen again... is the only option that isn't saved..

**Comment by danginsburg** [comment]
@facupedrazzini What is your command-line (i.e. do you have Launch Options set?)

**Comment by facupedrazzini** [comment]
I didn't know about that, I have: "-fullscreen"

**Comment by danginsburg** [comment]
Can you try removing -fullscreen and see if it still resets?  I think that is likely the problem.

**Comment by facupedrazzini** [comment]
Works! but is ok that by default comes with that?

**Comment by danginsburg** [comment]
@facupedrazzini That the default Launch Options comes with "-fullscreen"?  It doesn't.  You must have added it at some point and forgotten.  Or, perhaps you had it for Dota 2 Source 1.  The same Launch Options were used in Steam so it would have carried over.

**Comment by facupedrazzini** [comment]
Its a possibility that I forgget it, thanks for the help!

**Comment by xylein** [comment]
Hey @danginsburg I had been using -sw to open Dota2 till now. Today I removed it and tried, and it is working. I don't know if I was doing something stupid earlier or some of the many updates solved it, but it seems to be working fine. I have no command in the launch options and the game opens perfectly in "Use my monitor's current resolution". I think you can close the issue if you feel so. 
PS: I don't know if you were involved in the Reborn development but you certainly are in the improvements. Either way, great work. Reborn is a significant improvement for me specially in the load time and the in-game video quality which I can afford for numerous consecutive games(without having my laptop turn into a frying pan). With all the hate Reddit throws at Reborn, I thought you guys might need some appreciation :laughing:

**Comment by danginsburg** [comment]
@facupedrazzini @xylein Thanks for checking and thanks for the kind words!  I will close out this bug.
