### ISSUE TITLE
Bought items from suggestion list do not get checkmark when bought

### ISSUE THREAD

**Issue by mfonville** [ValveSoftware/Dota-2#377]
In Dota 2 Reborn Linux build from 9th of September 2015 there are no checkmarks anymore that indicate if you have bought something from the suggested itemlist.

**Comment by tfhavingfun** [comment]
I can confirm this issue.

**Comment by Despruk** [comment]
+1

**Comment by gdrewb-valve** [comment]
This apparently also happens on Windows, passing along to the larger team.

**Comment by gdrewb-valve** [comment]
This is supposed to be fixed now, closing.
