### ISSUE TITLE
Reborn Spectating game, Linux

### ISSUE THREAD

**Issue by fwsGonzo** [ValveSoftware/Dota-2#379]
Upon connecting to Live tournament game (The Defense returns) most likely pre-game phase:
`CFlattenedSerializer: Decode array index 4 out of range 4 for field C_DOTATeam::m_aPlayers [1]`

Couldn't find any crash files.. where are they?

**Comment by davidw-valve** [comment]
Can you reproduce this consistently on your machine?

**Comment by fwsGonzo** [comment]
Live viewing tournament game into hero selection:
1: First connect: everything worked fine (spectating the game)
2: Crash to desktop (waited for steam userid to "leave" server, although I do feel like new spectator should kick old spectator)

Downloaded replay:
`Connected fine _every time_ (I tried 8 times)`

Back to live viewing, game still in hero selection:
3: First connect: fine, spectating live as expected
4: Crash to desktop

Game is out of pregame/hero selection:
Connected and left game 6 times in a row without crashing

Never saw the error message again, although I never connected to another game in pre-game stage.. Also the crashes only happened _for me_ while the game was in captains mode hero selection, and finally once the game was being played it stopped crashing

Linux 3.19 x86_64 (ubuntu 15.04), prop. nvidia gtx 970, 24gb ram
I can see you guys built your own toolchains and everything, so not gonna bother with that

**Comment by gdrewb-valve** [comment]
Is this still happening or can this issue be closed, pending a solid repro?

**Comment by fwsGonzo** [comment]
I clicked watch on a game with time -1:26, game immediately exited

So, I guess its still happening?

**Comment by gdrewb-valve** [comment]
Was it a public match that we can try out here?

**Comment by fwsGonzo** [comment]
I opened dota again and during watch tab loading it exited. I tried GAME_DEBUGGER="strace..." but it seems like an outdated or internal build thing

So, I can't seem to get into the watch tab. Game exited 3/3 times right now

**Comment by gdrewb-valve** [comment]
Watch does seem broken in general, see also #561.

**Comment by gdrewb-valve** [comment]
The Oct. 16th update might fix this, are you still seeing it?

**Comment by fwsGonzo** [comment]
It worked for a while with many games both pre-game and late. So I reopened Dota and it just exited on a -1:26 game. Not sure if the players were loaded yet so I'm trying to replicate. The watch tab is no longer crashing the game. I could spectate the game that exited on me after I reopened the client again.

EDIT: Ok, I purposely loaded a -1:53 game with no players loaded, and it exited. Note that all these exits are before entering watch, so its always during loading.
And I can more or less confirm it doesn't crash on any started games.

**Comment by gdrewb-valve** [comment]
I believe the fix only applies to new games recorded after the fix.  It sounds like things are working for all newer games, is that correct?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by Yabk** [comment]
Hi, I'm experiencing the same thing after i upgraded to ubuntu 16.04.
I had 14.04 before and this never happened to me.
When i try to spectate a game that is in picking or pre-game phase it crashes dota while loading.
If the picking phase is over it doesn't crash.

**Comment by Tele42** [comment]
Hello @Yabk, you most likely are encountering the newer regression being tracked at #922.
