### ISSUE TITLE
AZERTY keyboard keys 1(&)/2(é)/3(")/.../0(à) trouble

### ISSUE THREAD

**Issue by alois-git** [ValveSoftware/Dota-2#38]
Hi,

Keys are not working properly because they bind it to the special character associated with the key but not all special character works. 

For example : "2" associated with "é" doesn't work, I can't bind any action on it. This is a bit annoying because I guess many people use it as Item shortcut. 

Ubuntu 15.04, AZERTY keyboard (French layout)

**Comment by davidw-valve** [comment]
Is this behavior different to in Source1 Dota2?

**Comment by MaelRL** [comment]
I'm also using an azerty keyboard and I have the same problem (Fedora 22), but I don't have any issue setting and using any keybind in source 1 dota 2.

There was a similar issue on Windows' Reborn, and the changelog of the 22nd said something about non-qwerty keyboards, but I haven't tested if it fixed the issue on Windows.

**Comment by alokhan** [comment]
The behavior in Source1 Dota2 was binding to the number of these keys (actually it was seeing my keyboard as a QWERTY keyboard)

**Comment by alokhan** [comment]
It is now solve in the new version of june 26

**Comment by gdrewb-valve** [comment]
Thanks, closing.
