### ISSUE TITLE
[Linux] Push to talk doesn't pick up audio.

### ISSUE THREAD

**Issue by danslo** [ValveSoftware/Dota-2#384]
When I go to audio settings I see recording level going up and down so it seems to be picking it up there just fine. Ingame it shows a cross.

**Comment by danslo** [comment]
Worked fine before reborn. 

Using puleaudio and sound device is set to default.

**Comment by danslo** [comment]
When going to Steam Voice Settings I can test my microphone and it works.

**Comment by danslo** [comment]
Streamlined PTT on/off doesn't seem to make a difference.

**Comment by davidw-valve** [comment]
Are you sure that your push to talk button is correctly bound? Do you see the mic icon when you press it and no audio, or do you not see the mic icon at all?

Note that reborn has a change to have party push to talk which is different to team push to talk.

**Comment by danslo** [comment]
Yeah just using typical G press. 
![2015-09-09_00002](https://cloud.githubusercontent.com/assets/743661/9773646/c0ed0976-5743-11e5-8315-67773a330df4.jpg)

Here are my audio settings, "Current Recording Level" fluctuates when I talk into the mic.
![2015-09-09_00003](https://cloud.githubusercontent.com/assets/743661/9773657/d7e67586-5743-11e5-8ffa-74191dafb37b.jpg)

**Comment by danslo** [comment]
![2015-09-09_00006](https://cloud.githubusercontent.com/assets/743661/9773693/0f1ec8aa-5744-11e5-8f88-ec20395efc6c.jpg)

Steam Voice settings for good measure, although I don't think it matters.

**Comment by danslo** [comment]
Nevermind, it appears that G is now the default setting for party talk instead of team talk? At least I didn't change that.
