### ISSUE TITLE
{Ubuntu} Steam Client not found

### ISSUE THREAD

**Issue by mwic** [ValveSoftware/Dota-2#388]
Launching on Ubuntu just now I got a message (right after the logo) saying "Steam client not found. Steam is required"
I did launch this through steam. The only unusual thing in my setup is that my OS & /home are on a solid state hard drive, while all the games are on a USB hard drive (library is set up to use a directory on this drive). This setup has always worked in the past.

**Comment by davidw-valve** [comment]
Have you tried restarting Steam or perhaps restarting your OS?

**Comment by mwic** [comment]
Yes, I restarted all.
Full output from the terminal as this happens is: 

Game update: AppID 570 "Dota 2", ProcID 5341, IP 0.0.0.0:0
ERROR: ld.so: object '/home/hack/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hack/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 5344 != 5343, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/hack/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hack/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198056713524 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198056713524
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 560 Ti/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Installing breakpad exception handler for appid(gameoverlayui)/version(20150604103636)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/mnt/tb/sgames/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/mnt/tb/sgames/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 12: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 21: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 30: bad alias
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Game removed: AppID 570 "Dota 2", ProcID 5346

**Comment by roman-holovin** [comment]
Same here, steam installed on btrfs filesystem, which can be a cause of the problem. When I'm launching steam, it verifies itself and I see that every link under .steam directory became valid, but as soon I'm trying to lauch Dota in steam, all links became broken.

Output when links are valid

```
ls -lash .steam
total 48K
   0 drwxr-xr-x 1 dantix users  180 Sep 23 02:53 .
   0 drwxr-xr-x 1 dantix users 1.1K Sep 23 02:53 ..
4.0K lrwxrwxrwx 1 dantix users   26 Sep 23 02:53 bin -> /home/dantix//.steam/bin32
4.0K lrwxrwxrwx 1 dantix users   43 Sep 23 02:53 bin32 -> /home/dantix/.local/share/Steam/ubuntu12_32
4.0K lrwxrwxrwx 1 dantix users   43 Sep 23 02:53 bin64 -> /home/dantix/.local/share/Steam/ubuntu12_64
4.0K -rw-r--r-- 1 dantix users  872 Sep 23 02:53 registry.vdf
4.0K lrwxrwxrwx 1 dantix users   31 Sep 23 02:53 root -> /home/dantix/.local/share/Steam
4.0K lrwxrwxrwx 1 dantix users   39 Sep 23 02:53 sdk32 -> /home/dantix/.local/share/Steam/linux32
4.0K lrwxrwxrwx 1 dantix users   39 Sep 23 02:53 sdk64 -> /home/dantix/.local/share/Steam/linux64
4.0K lrwxrwxrwx 1 dantix users   31 Sep 23 02:53 steam -> /home/dantix/.local/share/Steam
 12K -rw------- 1 dantix users 8.7K Sep 19 16:09 steam_install_agreement.txt
4.0K -rw-r--r-- 1 dantix users    6 Sep 23 02:53 steam.pid
   0 prw------- 1 dantix users    0 Sep 23 02:53 steam.pipe
```

Output when links became broken

```
ls -lash .steam
total 48K
   0 drwxr-xr-x 1 dantix users  196 Sep 23 02:55 .
   0 drwxr-xr-x 1 dantix users 1.1K Sep 23 02:55 ..
4.0K lrwxrwxrwx 1 dantix users   26 Sep 23 02:55 bin -> /home/dantix//.steam/bin32
4.0K lrwxrwxrwx 1 dantix users   36 Sep 23 02:55 bin32 -> /home/dantix/.steam/root/ubuntu12_32
4.0K lrwxrwxrwx 1 dantix users   36 Sep 23 02:55 bin64 -> /home/dantix/.steam/root/ubuntu12_64
4.0K -rw-r--r-- 1 dantix users  876 Sep 23 02:55 registry.vdf
4.0K lrwxrwxrwx 1 dantix users   24 Sep 23 02:55 root -> /home/dantix/.steam/root
4.0K lrwxrwxrwx 1 dantix users   32 Sep 23 02:55 sdk32 -> /home/dantix/.steam/root/linux32
4.0K lrwxrwxrwx 1 dantix users   32 Sep 23 02:55 sdk64 -> /home/dantix/.steam/root/linux64
   0 -rw-r--r-- 1 dantix users    0 Sep 23 02:55 starting
4.0K lrwxrwxrwx 1 dantix users   24 Sep 23 02:55 steam -> /home/dantix/.steam/root
 12K -rw------- 1 dantix users 8.7K Sep 19 16:09 steam_install_agreement.txt
4.0K -rw-r--r-- 1 dantix users    6 Sep 23 02:55 steam.pid
   0 prw------- 1 dantix users    0 Sep 23 02:53 steam.pipe
```

**Update**
I blocked .steam folder with immutable flag (chattr +i .steam) and steam client was not able to break itself _sensible chuckle_

Waiting for patch with such hack

**Comment by gdrewb-valve** [comment]
If I understand correctly the problem is in Steam itself and not in Reborn?  Have you reported this on a Steam forum?

**Comment by roman-holovin** [comment]
It's hard to say, since Dota is only game that causes this, but modifications of steam files attributes fixes a problem, so it probably a steam related problem, but I'm not 100% sure. I will try to reproduce on latest steam and Dota clients, there were a few updates to both. I will be back with results.

**Comment by gdrewb-valve** [comment]
Closing pending info that this is a Reborn issue.
