### ISSUE TITLE
[Linux] Voids/Chasms not being cleared properly

### ISSUE THREAD

**Issue by ananace** [ValveSoftware/Dota-2#39]
This is only really noticeable on the hero testing map and - most likely - any custom games that use chasms.

Here's a picture from my GTX 570 desktop:
![Desktop image](http://i.imgur.com/lSKP79S.jpg)
And here's my Intel HD Graphics 4400 laptop:
![Laptop image](http://i.imgur.com/qoe81Vy.jpg)

Using Mesa 10.5.6 on my laptop, Nvidia 346.45 blob driver on desktop.
Here's the glxinfo from my laptop, if needed; [pastebin](http://pastebin.com/hYSW8ZKT)

**Comment by chaserhkj** [comment]
confirmed same issue with my discrete graphic card GeForce 610M, using Bumblebee 3.2.1, primus git version, Linux 3.17.6 and Nvidia proprietary driver version 352.09.

But issue occurs only when I am using the most basic video effect configs, when switching to level-2 video setup in the settings, this issue disappears

**Comment by ace13** [comment]
Ah, didn't even think to test the video details myself. Wonder which setting in particular it is that breaks the rendering.

**Comment by ace13** [comment]
After some more testing I've found that the settings that solve the problem are:
- Additive Light Pass
- Ambient Occlusion
- Specular
- High Quality Water
- Shadows

Enabling any of them seems to solve the issue.

**Comment by danginsburg** [comment]
I have this repro'd here.  Happens on all platforms including Windows DX9.  Will investigate.

**Comment by EPadronU** [comment]
Same issue here. 

- Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
- "Manjaro Linux" (64 bit)
- Kernel Version:  3.19.8.1-1-MANJARO
- Driver Version:  3.0 Mesa 10.5.7

**Comment by gdrewb-valve** [comment]
The next update will fix this.

**Comment by gdrewb-valve** [comment]
Fixed in 6/26 update.
