### ISSUE TITLE
"Lobby not found" when using "Watch" button

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#391]
For a few days now, any attempt to spectate a game using the "Watch" button on a friend's party results in a "Lobby not found" error dialog. Watching the game from the friend's icon directly works.

**Comment by davidw-valve** [comment]
What OS are you using?

**Comment by chrylis** [comment]
I forgot to tag this one. Arch Linux.

**Comment by dayvough** [comment]
This is happening to me as well on Mac 10.10 on a Mid-2012 15" MBPr. Right click-ing finds the correct game.

But there's another bug that crashes the app when viewing friends games. (I've still yet to find an issue in the issues before creating a new one.)

**Comment by gdrewb-valve** [comment]
Likely not Linux / Mac specific, but I can check with the larger team.  Is this issue still active?

**Comment by chrylis** [comment]
Intermittent, and far less frequent recently.

**Comment by gdrewb-valve** [comment]
OK, I've passed this on and the larger team has it on its list.

**Comment by Hdz** [comment]
Windows 10, still happens when there's > than 10k people on a lobby. any game I tried to watch where there is this much people on it goes "Lobby not found" and the lobby disappear while the game is still being disputed.
