### ISSUE TITLE
[Linux] [Reborn] Incorrect mapping of physical keys

### ISSUE THREAD

**Issue by SchrodingerEquation** [ValveSoftware/Dota-2#396]
When I press the physical key 1 it is recognized as RETURN in the key bindings as well as the enter key. Some keys like 2 5 etc doesn't seem to be recognized at all. Many keys get mapped to the same value even if they are different. I usually use the numeric keys for item slots but now I cant since they map to enter which bring my chat or are not recognized at all. 
I've had this bug for quite some time but I just didn't use reborn and everything was fine in the main client.
Now I cant play the game.

This behaviour doesn't seem to be affected by changing the keyboard input.

**Comment by davidw-valve** [comment]
What locale are you using? What kind of keyboard do you have?

**Comment by SchrodingerEquation** [comment]
My laptop has normal qwerty keyboard and I am using en_US.UTF-8 locale. Also I am playing on Ubuntu 14.04 with LXDE.
This problem is very strange because I've never noticed thing like that in other application except the reborn client.

Also some of the keys that cannot be bound like 5 can be typed correctly in the chat while others like 1 close the chat (because they are recognized the same as Enter) and 2 closes the chat but is not recognized as enter.If i just press 2 nothing happens. If I press 1 then the chat opens. If i keep pressing one it opens and closes the chat adding a string of ones to the input. I really don't know how to make sense of this behaviour.

**Comment by magist3r** [comment]
I can confirm this. 
And I found a workaround: try to press volume keys in game and this bug disappears. Anyway it is very annoying.

KDE 4.14 on openSUSE 13.2 64-bit, ru_RU.UTF-8 locale

**Comment by amfg** [comment]
Mine might be a similar issue. 
I am unable to assign keys which are right above qwerty line on laptop keyboard (numbers).
Locale is en_US.UTF-8, however I am using 'sk' keyboard layout, which has these keys mapped: +ľščťžýáíé and numbers are reached with shift. 
This was not an issue in original dota2 client, which reported the keys as numbers (preffered behaviour, better than special symbols). 
Note that **switching keyboard layout to 'us' fixes this**.

Output from xev after pressing 1 and 2:

KeyRelease event, serial 48, synthetic NO, window 0x3200001,
    root 0x2b8, subw 0x0, time 1508276, (377,508), root:(378,937),
    state 0x0, keycode 10 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

KeyPress event, serial 48, synthetic NO, window 0x3200001,
    root 0x2b8, subw 0x0, time 1508925, (377,508), root:(378,937),
    state 0x0, keycode 11 (keysym 0x1b5, lcaron), same_screen YES,
    XLookupString gives 2 bytes: (c4 be) "ľ"
    XmbLookupString gives 2 bytes: (c4 be) "ľ"
    XFilterEvent returns: False

**Comment by z81** [comment]
Locale ru_RU.UTF-8 - not working q,w,e,r,...
Locale en_US.UTF-8 - not working 1,5,space
Fix it pls.

**Comment by youaresofunny** [comment]
+
UTF-8 not working at public and ranked matches
Intresting that all is ok in custom maps and bot matches

**Comment by nixi-awoo** [comment]
My keybindings work when I use a US keymap. If I switch the keymap to CZ qwerty and start the game, it does not recognize numbers 1 to 0 (as far as I am aware). When I start the game with a US keymap and switch to CZ afterwards, the bindings (usually) work.

**Comment by gdrewb-valve** [comment]
Key bindings are layout-specific by design right now.  If you add -input_button_code_is_scan_code to your launch options things will work more like Source 1.  Does that help?

**Comment by neko-kai** [comment]
@gdrewb-valve 

> If you add -input_button_code_is_scan_code to your launch options things will work more like Source 1. Does that help?

It doesn't affect main menu bindings (ctrl-c, ctrl-v)

> Key bindings are layout-specific by design right now.

Now that is is a very questionable design decision, I might even call it pants-on-head fucking retarded.

**Comment by gdrewb-valve** [comment]
For people having problems can you add -input_message_spew and -console to your launch options, then open the console in the main menu and press keys that aren't working? You should get some spew about the key going down and up that'll tell more about what those keys are showing up as.

**Comment by gdrewb-valve** [comment]
Closing pending more info on what keys are not working and the spew for them.

**Comment by gdrewb-valve** [comment]
See also #453.
