### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by diguliu** [ValveSoftware/Dota-2#398]
Hello,

I have a Debian 8.0 (Jessie) system with Steam and Dota2 installed. I play Dota2 on this for about 8 months and Dota2 Reborn since the beginning without any problem. After the last update, in which the option to choose between Dota2 and Reborn was removed and you can only play Reborn the problem started.

I can enter the game normally and find matches. But when I choose a hero, the problem begins to show. The hero sprite does not appear although the game reacts as if I indeed selected the hero. The game doesn't crashes or freezes, it keeps working just as fine besides the fact that the hero is not displayed (with some glitches on the screen). After the pick phase, when I press the button to enter the match, it enters but the map is not displayed. It keeps displaying the screen to select the heroes but the hud, chat, health bars, mouse pointer and select boxes (those green ones to select multiple units) are displayed. Even though these things are displayed, they also have a "Solitary-like" cascade effect when they move. Chat message also do not disappear. Check out the screenshots below:

![captura de tela de 2015-09-10 13-25-39](https://cloud.githubusercontent.com/assets/114025/9794868/fceacb2c-57c3-11e5-8503-98faeaaf925c.png)

![captura de tela de 2015-09-10 13-25-46](https://cloud.githubusercontent.com/assets/114025/9794870/02c347a4-57c4-11e5-8966-3372d603b31e.png)

![captura de tela de 2015-09-10 13-25-49](https://cloud.githubusercontent.com/assets/114025/9794874/07579b6c-57c4-11e5-83d0-04f33bcb8fdc.png)

![captura de tela de 2015-09-10 13-26-14](https://cloud.githubusercontent.com/assets/114025/9794883/1458cc28-57c4-11e5-8cbe-948ed7304a7a.png)

I've tried closing and opening the game a few times and it still do not work.

The problem happens in any kind of match including bots.

Another problem that started after this update is that the sound stopped working as well. Don't know if it's related to this problem.

Can I provide any other useful information to describe the problem?

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?  The graphics errors suggest something is broken in OpenGL, but it's hard to say.

**Comment by diguliu** [comment]
I discovered that I had some broken packages and dependencies that were forbidding a system upgrade. I reinstalled my SO, and now with debian testing things are working properly. I think the problem was happening due to outdated libraries or packages in conflict.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
