### ISSUE TITLE
[Linux] [Reborn] Older AMD64 not supported (Illegal instruction on startup)

### ISSUE THREAD

**Issue by jamieguinan** [ValveSoftware/Dota-2#400]
Start steam from an xterm.
Dota2, Play Game...
...
/home/guinan/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 99:  6255 Illegal instruction     ${Steam_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

For kicks, I tried running it under GDB,

$ gdb "/home/guinan/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2" 
..
(gdb) run
Starting program: /home/guinan/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Using breakpad crash handler

Program received signal SIGILL, Illegal instruction.
0x00007ffff3a1bd2f in ?? () from /home/guinan/Steam/linux64/steamclient.so
(gdb) 

(gdb) layout asm
0x7ffff3a1bd2f  lock cmpxchg16b 0x0(%rbp)

My old AMD64 X2 4200+ doesn't support cmpxchg16b. Note the lack of "cx16" flag,

$ grep flags /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt lm 3dnowext 3dnow rep_good nopl pni lahf_lm cmp_legacy

$ uname -a
Linux sully 3.14.0 #6 SMP PREEMPT Sat Jul 19 22:03:02 EDT 2014 x86_64 AMD Athlon(tm) 64 X2 Dual Core Processor 4200+ AuthenticAMD GNU/Linux

I guess its time to upgrade my system (built in 2005, updated to GeForce GTX 460 in 2011, was able to run Dota2 before Reborn). But there might be a few other users out there that get bitten by this, so I figured it was worth reporting.

A few extra things,

$ ls -l /home/guinan/Steam/linux64/steamclient.so
-rwxr-xr-x 1 guinan users 18798052 Aug 19 16:39 /home/guinan/Steam/linux64/steamclient.so

$ md5sum /home/guinan/Steam/linux64/steamclient.so
b9ed3f7d96a644dd3b684ce9000e2874  /home/guinan/Steam/linux64/steamclient.so

**Comment by davidw-valve** [comment]
Unfortunately I don't think you will be able to play any 64 bit games on Steam using this CPU, and Dota on Linux is now 64 bit.

Thank you for your detailed report of this issue.

**Comment by jamieguinan** [comment]
Thanks for the reply, davidw. Good excuse to build myself a new machine. I'll close the issue.
