### ISSUE TITLE
[OSX 10.10.5] Dota 2 Bot Match Settings

### ISSUE THREAD

**Issue by carlosingles** [ValveSoftware/Dota-2#404]
When I select Practice With Bots from the Play menu it remembers all my settings except my team. When I select Random for team, leave/finish the game and return to the menu, the team defaults to whatever team was picked at random in the previous game.

**Comment by gdrewb-valve** [comment]
Probably not Linux / Mac specific.

**Comment by gdrewb-valve** [comment]
Confirmed with the larger team that this happens on all platforms so it won't be tracked here.
