### ISSUE TITLE
[Linux] Dota 2 Reborn doesn't start: s3tc not supported (Fedora 22)

### ISSUE THREAD

**Issue by jsynacek** [ValveSoftware/Dota-2#407]
With:

```
CheckGLExtensions():
Required OpenGL extension "GL_EXT_texture_compression_s3tc" is not supported. Please install S3TC support
```

$ rpm -q libtxc_dxtn
libtxc_dxtn-1.0.0-4.fc22.i686

$ uname -a
Linux jsynacek-ntb-work 4.1.6-200.fc22.x86_64 #1 SMP Mon Aug 17 19:54:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.3 (git-ccef890)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.3 (git-ccef890)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.6.3 (git-ccef890)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by danginsburg** [comment]
Do you maybe need an x86_64 variant of libtxc_dxtn?  Can you try installing that?

**Comment by jsynacek** [comment]
Ok, now I feel stupid... I was under the impression that since Steam needs a lot of .i686 dependencies from rpmfusion, the library shouldn't be any exception. Installing its 64bit version resolves this issue.

**Comment by jsynacek** [comment]
Forgot to add... Thank you for the quick response!
