### ISSUE TITLE
[macos 10.8.5] - Can't start dota 2

### ISSUE THREAD

**Issue by kirqe** [ValveSoftware/Dota-2#408]
After dota2 updated itself a few days ago I just can't start the game. 

When I click on Dota2 in my library, the game starts and my Steam status changes to in game. But in a few seconds(1-2s) the status changes back from in game to online and nothing happens.

macos 10.8.5
gtx460se

It used to work fine before update. Fix this plz...

![screen shot 2015-09-11 at 4 26 54 pm](https://cloud.githubusercontent.com/assets/5272402/9814868/3509a59c-589a-11e5-89dd-e2b6de3dd4eb.png)

I checked it both on the OSX Default Graphics driver and Nvidia Web driver - same result.

**Comment by eNormt** [comment]
I am having the same problem, and have tried everything to fix it, but nothing works.
I really hope they have someone trying to fix this.

If you however find a way to make it work again, be sure to post :)

**Comment by danginsburg** [comment]
Are you able to update to OS X 10.9 or 10.10?

**Comment by kirqe** [comment]
@danginsburg I don't think so. I'm happy with 10.8.5 and most of the apps that I need work just fine. 

Should I update only for dota? :stuck_out_tongue_closed_eyes:

**Comment by eNormt** [comment]
I am also using 10.8.5, because updating decreases system performances.
I decided however to upgrade to yosemite, and I am downloading it now.
I will report back once updated and tell you if it works or not.

**Comment by eNormt** [comment]
Updated to Yosemite, and the game is working again!
so to conclude: The new update makes it impossible to play dota 2 on mac with version 10.8.5

**Comment by danginsburg** [comment]
Yes, sorry, OS X 10.9 is the minimum.  We are going to update the Steam page with this info.  Closing.
