### ISSUE TITLE
[Linux] [Reborn] Keys don't work in non-English layouts

### ISSUE THREAD

**Issue by neko-kai** [ValveSoftware/Dota-2#409]
Switching to russian layout causes letter binds to longer work. Trying to bind a key in options results in an empty bind that doesn't work in game.

Note, that this bug was fixed a few weeks after Reborn was released for Linux, but was reintroduced again at some point.

OS: Ubuntu 14.04 LTS

**Comment by magist3r** [comment]
same as #396

**Comment by gdrewb-valve** [comment]
Closing duplicate.
