### ISSUE TITLE
Unable to connect to games and epic frame lag

### ISSUE THREAD

**Issue by hummer463** [ValveSoftware/Dota-2#411]
My client opens perfectly fine and is fully responsive. When I attempt find a game it will say "connecting" at the bottom right corner after which it will change to a "reconnect" and "leave game" button indicating i have been disconnected from game. It takes multiple tries before it even attempts to reconnect and sometime just sits in loading screen for +-10 min. The second issue is that even when i do successfully connect/reconnect to a game my fps constantly drops to 10-20 every second or so making the game stutter to a point of being unplayable. This will continue constantly throughout the game. Often i will also be disconnected from the server through automatic disconnections(auto dc's). The auto dc timer will tick down from 25 but keep freezing every few seconds causing me to take easily 1-2 minutes to disconnect to the main menu. I know none of these issues are being caused by a low quality internet line as my ping in-game remains 5 and i have a constant 400kbps download rate. I also know that this is not being caused by my computer's performance as i have a very strong gaming rig that can handle games way more graphically challenging than this. I recently had an incident where I was auto dc'd from a game but even after being returned to the main menu the auto dc'ing counter was still present and i could clearly hear my team-mates speaking over microphone to one another in-game!! This leaves no doubt in my mind that these issues with connecting to game's servers, the frame lag and the constant disconnections are all problems associated with the Reborn client, and that they are more than likely interlinked in some way. I would very much appreciate if some one could look into this problem and find a solution soon.

**Comment by ArnaudAndre** [comment]
You didn't tell anything about your setup and (perhaps more importantly) your ISP and modem/router.

**Comment by hummer463** [comment]
Im with Axess and am running a 4mb line. My computers specs are:
 Processor: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, 3500 Mhz, 4 Core(s), 8 Logical Processor(s)
16GB RAM. 1TB storage. Router is a  N300 NETGEAR Wireless adsl2+ Modem router 
model dgn2200v3

**Comment by hummer463** [comment]
Im with Axess and am running a 4mb line. My computers specs are:
 Processor: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, 3500 Mhz, 4 Core(s), 8 Logical Processor(s)
16GB RAM. 1TB storage. Router is a  N300 NETGEAR Wireless adsl2+ Modem router 
model dgn2200v3

**Comment by ArnaudAndre** [comment]
I'm assuming axess in holland not south africa ? Connecting to your modem through wifi or ethernet ? Also, your OS/version may be relevant.
You can enable "_Display Network Information_" in dota2 settings, _options_, _network_ group. I suspect it would show significant packet loss.

**Comment by hummer463** [comment]
Im in South Africa and using the axess based here. Im using windows 10 and am connected with ethernet. After the last major patch the ability to connect and reconnect to games has been fixed but there is still a strange issue with the packet loss. I'm usually on team-speak 3 with my friends but the second i join a game my packet loss spikes to 70% and my ping goes easily over 500. The same goes for spectating. I think this may be the cause of all the stuttering but I'm not sure what is causing the packet loss and ping. When i go to my resource manager my line is doing 200 to 300 kbps just to run dota when im ingame. Do you have any idea why dota is using so much bandwidth just to run?

**Comment by gdrewb-valve** [comment]
This bug tracker is only for Linux / Mac specific issues.  I've passed your question on to the larger team but there won't be tracking here.

**Comment by gdrewb-valve** [comment]
The larger team suggested two things:
1. Add +net_showudp 1 -condebug to your launch options and post a gist of the console.log from the dota folder after encountering the problem.
2. Add +net_filelogging 1 to your launch options and gist the dota\networking*.\* folder.  This will generate large files so you may want to clean them out.
