### ISSUE TITLE
Dota 2 Korean Character problem 

### ISSUE THREAD

**Issue by appleparan** [ValveSoftware/Dota-2#412]
I'm using Macbook Air 2012 and OSX 10.10.5
1. Dota 2 reborn has a big problem with Korean. I can't see any Korean character .
2. I can't type korean character neither. For 2nd problem, same problem is occurred in windows ver.

**Comment by danginsburg** [comment]
Problem 1 has been fixed and will roll out in a future update, see #392 which also includes a temporary workaround until the update rolls out.

**Comment by appleparan** [comment]
One more thing, When you type korean, I need trailing whitespace to type correctly. WIthout trailing whitespace, last word will be printed at new sentence. For example, "안녕하세요" (meaning 'Hello') without trailing whitespace will be print like this.

```
> 안녕하세요
> 요
```

I found this issue several weeks earlier (at that time typing korean is worked I remember), but I thought it will be fixed later. However, I think it didn't fixed even though you have Problem 1 & 2. This issue is also exist on windows ver.
