### ISSUE TITLE
LoadSystemAndDependencies error in connect() GameUI011

### ISSUE THREAD

**Issue by Nikitafromdota** [ValveSoftware/Dota-2#413]
Pls help me! I am from Estonia and my english is bad. When i started dota 2 reborn.(Windows 8.1)
AppSystemDict: Error in Connect() of interface: 'GameUI011'!
help pls.

**Comment by davidw-valve** [comment]
Has Dota worked for you previously? When did it stop working specifically?

**Comment by Nikitafromdota** [comment]
Last week i downoloaded dota 2 reborn and first time i play custom games, the next day i wanted to play  dota 2 reborn but this problem AppSystemDict: Error in Connect() of interface: 'GameUI011'! i went play dota 2 not reborn and now need dota 2 reborn but... sry for my english)

**Comment by Nikitafromdota** [comment]
Can smb help me?

**Comment by vitaliy-evsyukov** [comment]
I have same problem. Symlink (which can be found in internet) didn't helped me.

**Comment by vitaliy-evsyukov** [comment]
Nobody gives a fuck. Very well.

**Comment by davidw-valve** [comment]
Have you tried verifying your game cache? These kinds of errors often mean that the local copies of your files are somehow corrupted.

**Comment by vitaliy-evsyukov** [comment]
Yes, I also reboot my PC and unplug network cable.
You can find similar problem for Arch Linux, for example, in related forums topics.

**Comment by gdrewb-valve** [comment]
Check out #105 and #35 and see if those suggestions help.

**Comment by gdrewb-valve** [comment]
Closing as this should be covered by other issues.

**Comment by vitaliy-evsyukov** [comment]
Nothing helped. Nice work, valve.
