### ISSUE TITLE
[OSX] - Have to double click everything; mouse edge pan not working; game unplayable

### ISSUE THREAD

**Issue by headcased** [ValveSoftware/Dota-2#414]
I've had no problems running/playing Dota 2 previously on a MAC (Yosemite), but after installing Reborn, this game is unplayable at the moment. 

The first major problem is that I have to double click on everything (and most of the time even double clicks won't register). This happens in-game as well (e.g. it takes me a good minute to succeed in double clicking on the SHOP for instance, or even to up a skill). 

The 2nd major problem that I've encountered is that edge panning via mouse simply doesn't work in game.... As a result, I've had to abandon 2 games and so I'm not sure what more problems there are running reborn on a MAC as I could not even finish a game without quitting.

EDIT: Also, I forgot to note another problem - which is that I cannot TYPE anything (e.g. I cannot type to select my hero before the match starts; also, I could not type in chat (and couldn't do voice chat))

**Comment by davidw-valve** [comment]
When you say you have to 'double click' do you mean some clicks are simply missed?

Which Display Mode do you have selected in video settings? (Fullscreen vs Windowed etc)

Do you mean edge pan isn't working at all? Have you checked that the "Edge Pan" option is checked in the Options menu under Camera?

**Comment by headcased** [comment]
Hi -

I have to double-click on EVERYTHING for clicks to register throughout the game. For instance, even at the home page when in game, I have to double-click to switch "tabs" (e.g. between the main page, "Heroes" tab, "WATCH" tab, CUSTOM GAMES tab, etc. etc.). When going to find a match, I have to double click (or sometimes furiously multi click)  to click "FIND A MATCH" and then furiously double click to choose the game mode (all-pick, limited, random etc..) and so forth. In-game, I could not open the SHOP, without furiously clicking on the "SHOP" button and it took me forever to open that up. And I could not up my first skill until after furiously clicking for a couple minutes. 

My display mode is in FULLSCREEN.

And yes - I checked the settings (which I have to double-click on to go to that page as well) and EDGE PAN was enabled as normal. But in game - the edge pan wasn't responding at all. 

And I added an "edit" to the original post, but I forgot to mention I couldn't type at all. (I could not type to find my hero before the game; also, I tried to chat to my teammates but I could not open the chat via "ENTER" at all (although I could read the chat). 

I am probably in the very small minority encountering these major problems, and so should I simply reinstall REBORN ?

**Comment by ghost** [comment]
I'm having the same problem. I need to click twice on everything for anything to happen. 
Examples: double clicking the settings button to open settings, double clicking on play dota to open the play dota interface.

Happens with both the touchpad and a 3rd party mouse.

**Comment by headcased** [comment]
I just restarted my steam + computer and tried to play another game. Things ran more smoothly but the problems remain the same. 

1) Have to double click for anything to register. 

2) Edge pan doesn't work 

3) Cannot type at all. (Cannot use my skills/hotkeys, cannot chat)

**Comment by xubihang** [comment]
Same here! I've try every display mode and restart both steam and dota2 for several times. But the problem is still there.

**Comment by l3eamel2** [comment]
Me too!! 
yesterday, restart steam was worked, but today i cant do anything for this problem.

**Comment by headcased** [comment]
Found a solution for those having the same problems as I did....

Simply press CMD + H and then go back into the game..... It was as simple as that and everything ran smoothly thereafter.

**Comment by ghost** [comment]
headcased, that worked for me. Thanks!

**Comment by Vuccappella** [comment]
I experienced something simillar when I tried changing my resolution from native (2560x1440)  to lower, once i restored to native it was fixed , it might be related.

**Comment by gramathy** [comment]
This seems related to the focus on launch issue #238 which results in the behavior described by headcased. Try cmd-H and then going back to the game to see if it recaptures focus.

**Comment by onlinecco** [comment]
Same problem here. Restarting the client sometimes fixes it.

**Comment by chreesp** [comment]
For all of you having double click problem. When gem starts just press CMD+H to hide game, open it again from dock and it will restore focus so you wont have to double click. 

You're welcome.

**Comment by danginsburg** [comment]
We have a fix for this issue, it will ship in a future update to Dota2.

**Comment by danginsburg** [comment]
Fix for this has been released, closing.
