### ISSUE TITLE
Inconsistent behavior with shop hotkeys in dotakeys_personal.lst

### ISSUE THREAD

**Issue by woctezuma** [ValveSoftware/Dota-2#415]
I mention the problem here: http://gaming.stackexchange.com/q/236112/3921

It might not be specific to Linux or MacOSX.

Bascially, if I want to edit the shop hotkeys, I have to resort to editing a text file called dotakeys_personal.lst in userdata. I can rebind the hotkeys for the columns, going from QWERTY to AZERTY, like this for the first column:

```
    "ShopTabConsumables"
{
    "Name"      "ShopTabConsumables"
    "Action"        "shop_nav_to_tab 0"
    "Key"       "a"
    "Description"       "#DOTA_Shop_Hotkey_Consumables"
    "Version"       "2"
}
```

However, the behavior is inconsistent for rows. Indeed, if I keep the default hotkeys (1 2 3 ... 0 - =), all the rows, except for the 11th row, work with the keys placed at the same position on my AZERTY keyboard (& é " ' ( - è _ ç à ) =).

So the default hotkeys seem to be weirdly mapped to the keyboard instead of the keys.

```
    "ShopSlot10"
{
    "Name"      "ShopTabSecret"
    "Action"        "shop_select_itemrow 10"
    "Key"       "0"
    "Version"       "2"
}
"ShopSlot11"
{
    "Name"      "ShopTabSecret"
    "Action"        "shop_select_itemrow 11"
    "Key"       "-"
    "Version"       "2"
}
"ShopSlot12"
{
    "Name"      "ShopTabSecret"
    "Action"        "shop_select_itemrow 12"
    "Key"       "="
    "Version"       "1"
}
```

I would be okay with this weird behavior (remap the column hotkeys, keep the default row hotkeys) if the 11th row were working fine. For some reasons, the "-" key is not recognized and I cannot buy any item on the 11th row if I do not rebind the key to a letter or keypad keys such as KP_MINUS.

Why is the behavior for rows inconsistent?

What is the problem specifically with the minus key?

**Comment by gdrewb-valve** [comment]
Key bindings are keyboard-layout-specific by default.  Try adding -input_button_code_is_scan_code to your launch options.  Do things then work more like what you expect?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by woctezuma** [comment]
Thank you, it works fine now.

I have seen the issue mentioned on Reddit and it is a decent number of people who were impacted.

https://www.reddit.com/r/DotA2/comments/3y2zi1/til_if_youre_having_troubles_with_specific/
