### ISSUE TITLE
[OSX] Dota 2 Doesn't start up after merging with source 2

### ISSUE THREAD

**Issue by basedfelix21** [ValveSoftware/Dota-2#416]
Opening dota 2 doesn't open up after clicking play. Has been happening with reborn before merge, now can't even open dota 2.
Specs:
Mid 2011 mac 21.5"
2.5 GHz Intel Core i5
Graphics  AMD Radeon HD 6750M 512 MB
Memory  4 GB 1333 MHz DDR3
Software  Mac OS X Lion 10.7.5 (11G63)
MiniDump:
Information:
    Model:  iMac12,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.7.5 (64 bit)

Video Card:
    Driver:  AMD Radeon HD 6750M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x1002
DeviceID:  0x6741
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.62" x 10.47"  (21.34" diag)
                                        47.3cm x 26.6cm  (54.2cm diag)
Primary VRAM: 512 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  476120 Mb
    Largest Free Hard Disk Block:  270400 Mb

**Comment by kirqe** [comment]
There's no dota 2 anymore. And reborn only works on 10.9 and higher.

**Comment by danginsburg** [comment]
Your system is supported, but you will need to update to OS X 10.9 or greater.  After that, it should work.  Closing.
