### ISSUE TITLE
Japanese text does not render correctly in game

### ISSUE THREAD

**Issue by hssm** [ValveSoftware/Dota-2#418]
This is a problem that carried over from the source 1 client. It may in fact be the exact same issue as https://github.com/ValveSoftware/Dota-2/issues/392 but for Japanese instead.

I am on Ubuntu 15.04 and start the game with the launch option `-language japanese`. Most text in game appears as white boxes:
![reborn_jap2](https://cloud.githubusercontent.com/assets/789082/9829741/b1dfea2a-5955-11e5-93f6-179e5f432940.jpeg)

Outside of the game, the UI seems to render correctly:
![reborn_jap1](https://cloud.githubusercontent.com/assets/789082/9829747/240ff70c-5956-11e5-9515-2afc5fb91523.jpeg)

**Comment by appleparan** [comment]
Korean has a same problem. It is font problem. They use Windows' font which isn't exist in Mac & Linux. See #392 and there is a temporary solution (copy fonts from Windows)

They have a huge problem in supporting CJK language (even in Windows Ver.),  I don't know why they removed 'Beta' flag in Dota 2 Reborn

**Comment by appleparan** [comment]
Is this fixed? Korean langauge is showing well today.

**Comment by danginsburg** [comment]
This appears to be a different issue than what we already fixed for Korean language.  I have this repro'd on Ubuntu 15.04 x64.  Investigating.

**Comment by danginsburg** [comment]
I have a fix for this.  This problem occurred on both Linux and OSX.  Fix will be in the next release.

**Comment by danginsburg** [comment]
Fixed in 9/16 update on Linux/OSX.
