### ISSUE TITLE
[Linux] game uses over 300% cpu

### ISSUE THREAD

**Issue by gensss** [ValveSoftware/Dota-2#42]
a big part on mutex spinlocks/calls

cpu: amd fx 8320
gpu: nvidia 465, 352.21

linux 4.1, 64bit
glibc 2.21

i can provide perf data or anything else if needed

**Comment by presianbg** [comment]
Can confirm that It's eating a lot of CPU time Core i7 4710 HQ

**Comment by imirkin** [comment]
Same issue here, Core i7-920, linux 4.0.5, GF108, nouveau nvc0 driver -- 1.5-2 cpu cores at all times, in-game or not.

**Comment by lightning18** [comment]
This may be related to #7

**Comment by imirkin** [comment]
Ah yeah. I had even seen that bug, but didn't make the connection. I also saw high ksoftirqd use. I noticed the game makes use of glBufferStorage coherent buffers, which at least for nouveau, forces the relevant buffers into GART (i.e. system memory accessible by the GPU). But I haven't looked in great detail.

**Comment by gensss** [comment]
yes, top shows ksoftirqd like in the other bug report
sry for the duplicate

**Comment by danginsburg** [comment]
@imirkin You can disable persistently mapped buffers with -gl_disable_buffer_storage if you want to try isolating that as an issue.

**Comment by gdrewb-valve** [comment]
The game is multithreaded and will use multiple cores, but we do have some CPU usage fixes coming in future updates.

**Comment by gensss** [comment]
wrong button

well, might as well close it if you want
the ksoftirqd one is the same problem (spinlocks)

**Comment by mattyy1hp** [comment]
This happens to me as well. Is it a bug or everything is ok? All these ksoftirqd processes disappear when I close the game.
![dota2-ksoft](https://cloud.githubusercontent.com/assets/3092320/8331063/5e728a90-1a86-11e5-8856-cc6f3e003fde.png)
i5 4210H + GTX 860M (340.76) + Debian Unstable 64bit
