### ISSUE TITLE
Macbook keyboard does not work in DOTA 2 reborn

### ISSUE THREAD

**Issue by Punzx** [ValveSoftware/Dota-2#421]
My macbook keyboard and other macbook (my friend's) did not work while playing the game; this problem includes skill spelling, voice talking (G), shop opening and etc. which relates to keyboard function in game. However, the chat can type normally after pressing 'enter'.

Do you have any suggestion to solve this keyboard problem? (macbook)

Please resolve this problem as soon as you notice this issue, to whom it may concern

**Comment by vvorlov** [comment]
@Punzx, I change the keyboard layout (language) every time when keyboard is not working. It's odd, but helps for a while. 

Seems to be keyboard doesn't work after death and you should do this trick again.

**Comment by headcased** [comment]
I've been having this problem for a while, but it seems to be source to a dock issue?? 

I solved the problem by simply pressing "CMD+H" while in-game, and then simply going back to dota afterwards.

**Comment by Vuccappella** [comment]
I had this while swapping languages. Make sure you're using english.

**Comment by vvorlov** [comment]
"CMD+H" isn't working for me

**Comment by magist3r** [comment]
Same as #396

**Comment by danginsburg** [comment]
Does adding -input_button_code_is_scan_code to the command-line resolve the issue?

**Comment by danginsburg** [comment]
Possible duplicate as #473

**Comment by gdrewb-valve** [comment]
Closing in favor of #473.
