### ISSUE TITLE
[Linux] Game crashes in Demo Hero mode when you click Spawn Enemy

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#422]
System Info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/e5332271c7c37021cb5ba867b0bbeb38288d577b/gistfile1.txt

**Comment by nbaztec** [comment]
Same happens to me, except when you click to spawn at Limited Heroes selection. Game will then crash for atleast once more while reconnecting. Can reproduce this 100% of the time.

Will attach crahshlog and dump the next time I play (and it crashes)

**Comment by danginsburg** [comment]
Maybe I am not trying to repro this correctly, but I go to "Demo Hero" mode and then click "Spawn -> Enemy" and thus far have not seen a crash.  Are those the correct steps?  Can you upload your minidump?  So far unable to repro.

**Comment by nbaztec** [comment]
Okay, here's the dump. It's a segfault on hero select, then another segfault when I restart+reconnect.
https://www.dropbox.com/sh/c3iotxeprmd9os4/AAANMpugUEN1N8iYLpUNzzrla?dl=0

Steps:
Limited Heroes (on SEA server not that it matters)
Select Hero (occasionally it won't show the model when I lock it)
Click button to spawn/start game > Crash.

**Comment by jazztickets** [comment]
dmp file:
https://drive.google.com/file/d/0B0F0CKVMavH7S3BpWE1rWUVYdlk/view

This isn't related to limited heroes mode. This is just "Demo Hero".

**Comment by nishb** [comment]
Oh my bad, @danginsburg do I keep this as is or create a new issue?

**Comment by nbaztec** [comment]
Oh my bad, @danginsburg do I keep this as is or create a new issue?

**Comment by jazztickets** [comment]
Fixed
