### ISSUE TITLE
[linux] Dota 2 Graphics glitch (then segfault)

### ISSUE THREAD

**Issue by nbaztec** [ValveSoftware/Dota-2#424]
Graphics get glitched usually within 5 minutes of launching Dota 2. All icons (settings, close, etc) get bugged. Minimap and health bars get bugged.

Eventually the game segfaults (also happens at hero selection).

![screenshot from 2015-09-12 16 01 27](https://cloud.githubusercontent.com/assets/1564843/9831190/4aa92898-596a-11e5-8819-dcf1411ac19c.png)

Crash logs and dump.
https://www.dropbox.com/sh/2wqzlkih5pkd2ou/AACEZIh6yErrMUQn3ty7EtVja?dl=0

**Comment by ruliane** [comment]
Hello,
Having same issue here. (Linux Mint 17.1, Radeon HD 6870)

**Comment by Pharmasolin** [comment]
is this wiht mesa?

**Comment by nbaztec** [comment]
Without mesa.

**Comment by nbaztec** [comment]
Adding to this issue - if I navigate to Armory/Store, basically anywhere which isn't "Play DOTA" button/sidemenu, the glitches will start occurring almost instantaneously. Closely followed by a segfault crash.

**Comment by nbaztec** [comment]
Adding consolidated system information as per guidelines
https://gist.github.com/nbaztec/d78ebed411a60c432f15

**Comment by Tele42** [comment]
This should also be reported to the video driver vendor.
From the provided minidump:

```
Operating system: Linux
                  0.0.0 Linux 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64
CPU: amd64
     family 16 model 10 stepping 0
     6 CPUs

Crash reason:  SIGSEGV
Crash address: 0x30

Thread 9 (crashed)
 0  fglrx_dri.so + 0xeb056a
    rbx = 0x00007f8c10d55650   r12 = 0x00007f8c3b0b6c00
    r13 = 0x0000000000000000   r14 = 0x00007f8c10d54000
    r15 = 0x0000000000000001   rip = 0x00007f8c039a556a
    rsp = 0x00007f8bffd065c0   rbp = 0x0000000000000004
    Found by: given as instruction pointer in context
 1  fglrx_dri.so + 0x1520118
    rip = 0x00007f8c04015118   rsp = 0x00007f8bffd06640
    Found by: stack scanning
 2  fglrx_dri.so + 0x157e300
    rip = 0x00007f8c04073300   rsp = 0x00007f8bffd066c0
    Found by: stack scanning
 3  fglrx_dri.so + 0xcbab47
    rip = 0x00007f8c037afb47   rsp = 0x00007f8bffd06700
    Found by: stack scanning
 4  fglrx_dri.so + 0x404430
    rip = 0x00007f8c02ef9430   rsp = 0x00007f8bffd06720
    Found by: stack scanning
 5  fglrx_dri.so + 0xedb1d0
    rip = 0x00007f8c039d01d0   rsp = 0x00007f8bffd06740
    Found by: stack scanning
 6  fglrx_dri.so + 0xecb999
    rip = 0x00007f8c039c0999   rsp = 0x00007f8bffd06800
    Found by: stack scanning
 7  fglrx_dri.so + 0xcba3da
    rip = 0x00007f8c037af3da   rsp = 0x00007f8bffd068c0
    Found by: stack scanning
```

**Comment by nbaztec** [comment]
I purged old fglrx packages and reinstalled again, the crash dump with latest stable driver is 
https://www.dropbox.com/s/djr5xnbge5u0m8p/crash_20150915185538_1.dmp?dl=0

If you could let me know the decoded stacktrace to file a bug report to the vendor (AMD?), it'd be helpful.

Thanks.

**Comment by Tele42** [comment]
@nisheeth-barthwal yes, the new minidump still indicates a driver issue:

```
Operating system: Linux
                  0.0.0 Linux 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64
CPU: amd64
     family 16 model 10 stepping 0
     6 CPUs

Crash reason:  SIGSEGV
Crash address: 0x30

Thread 9 (crashed)
 0  fglrx_dri.so + 0xeb056a
    rbx = 0x00007f8ee8c71650   r12 = 0x00007f8f0b031000
    r13 = 0x0000000000000000   r14 = 0x00007f8ee8c70000
    r15 = 0x0000000000000001   rip = 0x00007f8eda19756a
    rsp = 0x00007f8ed64f85c0   rbp = 0x0000000000000004
    Found by: given as instruction pointer in context
 1  fglrx_dri.so + 0x1520118
    rip = 0x00007f8eda807118   rsp = 0x00007f8ed64f8640
    Found by: stack scanning
 2  fglrx_dri.so + 0x157e300
    rip = 0x00007f8eda865300   rsp = 0x00007f8ed64f86c0
    Found by: stack scanning
 3  fglrx_dri.so + 0xcbab47
    rip = 0x00007f8ed9fa1b47   rsp = 0x00007f8ed64f8700
    Found by: stack scanning
 4  fglrx_dri.so + 0xedb1d0
    rip = 0x00007f8eda1c21d0   rsp = 0x00007f8ed64f8740
    Found by: stack scanning
 5  fglrx_dri.so + 0xecb999
    rip = 0x00007f8eda1b2999   rsp = 0x00007f8ed64f8800
    Found by: stack scanning
 6  fglrx_dri.so + 0xcba3da
    rip = 0x00007f8ed9fa13da   rsp = 0x00007f8ed64f88c0
    Found by: stack scanning
```

**Comment by danginsburg** [comment]
AMD just released Catalyst 15.9 for Linux: http://support.amd.com/en-us/download/desktop?os=Linux+x86 .  Please give that a try and let us know if it fixes the issue.

**Comment by nbaztec** [comment]
Awesome, the new driver fglrx-15.201.1151 runs it smooth without any crash.
Closing.

**Comment by simplystic** [comment]
Can confirm. Had same problems as mentioned here, installed new drivers on my Ubuntu 15.04 at it fixed EVERYTHING for me.
