### ISSUE TITLE
Problem with input in Korean Language

### ISSUE THREAD

**Issue by appleparan** [ValveSoftware/Dota-2#425]
I'm using MAC OSX 10.10.5

If I entered korean language in chat, Last word is not showing. For example, Enter "안녕하세요" , then I can see only "안녕하세" only 4 characters.

Actually, Windows Ver. has similar bug, but it duplicates last word (little bit different), for example, "안녕하세요" becomes "안녕하세요" "요" like this

```
> 안녕하세요
> 요
```

Temporal solution is add a space after input such as "안녕하세요 "
I think Dota 2 reborn has a huge misunderstanding with unicode character (especially CJK character).

**Comment by gdrewb-valve** [comment]
As this isn't Mac-specific I've passed it on to the larger team.

**Comment by gdrewb-valve** [comment]
They're going to take a look.
