### ISSUE TITLE
[Linux] [Reborn] No brightness slider

### ISSUE THREAD

**Issue by e1usion** [ValveSoftware/Dota-2#428]
In Windows, upon choosing "Exclusive fullscreen" option in Video tab, brightness slider appear.
There is no "Exclusive fullscreen" option in Linux client, thus there is no brightness slider. Choosing any other video option doesn't solve that problem.

OS: Archlinux x86-64
GPU: Nvidia GTX 750

**Comment by gdrewb-valve** [comment]
Duplicate of #63.
