### ISSUE TITLE
[Linux] GUI bug after server crash

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#429]
1. Play game
2. Server crashing, you are disconnected
3. You receive bug forever (until you will close and open game again) (right top corner)

Screens:
![2015-09-12 22 50 32](https://cloud.githubusercontent.com/assets/13041082/9833713/68709b82-59aa-11e5-83e3-669055e3b5c7.png)
![2015-09-12 22 51 08](https://cloud.githubusercontent.com/assets/13041082/9833714/6871cf3e-59aa-11e5-9057-01d5c978fd00.png)

P.S: We were playing MMR game, server just crashed, were trying reconnect, but it closed game itself (on server) we should win but we not because of this.

I want offer enhancement, if dota crashing on server side in MMR, both teams should have their +mmr, because it is very frustrating.

**Comment by gdrewb-valve** [comment]
This issue occurs on Windows also, the larger team may have addressed this.  This will get closed regardless but is it still occurring?

**Comment by Pharmasolin** [comment]
I cant test it right now.

**Comment by gdrewb-valve** [comment]
Any luck?

**Comment by Pharmasolin** [comment]
Yes, i reproduce this and i have this warning in main menu with 0.0 sec when i disconnected from server, but when i press connect and it connected this red warning dissipated.

**Comment by gdrewb-valve** [comment]
OK, I've passed this on to the larger team.
