### ISSUE TITLE
[Windows] can't put multiple comments in "Match Discussion" panel

### ISSUE THREAD

**Issue by PhyFrancis** [ValveSoftware/Dota-2#431]
Description:
1. clicke on any of my recent match
2. write something in the "Match Discussion" panel, and post it.
3. write something again and post.

Expect: I have two comments in the panel
Real: The second commented is not posted.

**Comment by davidw-valve** [comment]
The number of comments you can make is rate limited so you cannot spam with too many comments. We will most likely add a message box to communicate this better in future.
