### ISSUE TITLE
[Linux] GUI main menu right courner animation hitches when carousel changes

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/Dota-2#432]
Right bottom corner, when searching game there is some animation, it is freezing when main slider changes picture (may be because i have HD 2000 intel and it is not enough for this, anyway reporting)
https://youtu.be/IcGbJRtfFIE?t=5
+
After i accepted offer to play, we were in lobby, but 1 don't loaded, it start to search new game and animation changed, check video below, for me it is hard to reproduce (i write how i were u can try by yourself, make one don't load in game, so it will start searching game again, you should see animation "breaks"
https://youtu.be/IGhrMn2BJwc?t=6

Driver Version:  3.0 Mesa 11.1.0-devel (git-2e7e3fe 2015-09-12 vivid-oibaf-ppa)

**Comment by Pharmasolin** [comment]
Today i have same steps and in the result i received broken animation again.

**Comment by gdrewb-valve** [comment]
Is this still happening?  Some hitch would be expected because the main menu info update will require some work.  Also it should occur on all platforms.

**Comment by Pharmasolin** [comment]
May be i will test it later and write result

**Comment by gdrewb-valve** [comment]
Did you get a chance to try this?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
