### ISSUE TITLE
[OS X] All is blue.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#433]
Happens in many mods.

http://i.imgur.com/ftpZTRd.png

MacBook Pro (Retina, Mid 2012)
Yosemite up-to-date.
NVIDIA GeForce GT 650M 1024 MB

**Comment by danginsburg** [comment]
Does it happen in the regular game or just in a mod?  If it is a mod, can you give an example of which one this occurs on?  Also, you can make sure you are running on NVIDIA 650M using gfxCardStatus https://gfx.io/ .  I'd be curious if this happens when you switch to HD 4000 which is also on that machine.

**Comment by p-groarke** [comment]
Well its gone now (#ofcourse).

It happened in every mod I tested (Epic boss fights, dota strikers, bash wars). Pinging and selecting things sometimes flashed to the correct view. Dota strikers had the blue overlayed on top so it is was least playable.

Yes I am running on the 650M. If it ever happens again I'll test with the intel 4000.

**Comment by danginsburg** [comment]
So that exact problem does happen on HD 4000 for which we punt to SM30 shaders based on GPU detect.  It is due to a GL driver bug on the OS X GL driver for HD 4000.  The GPU detect does the equivalent of running with -gl_force_sm30.  I can't think of any way that the GPU detection could fail.  If you see it again and have any other info on what might have been different, please reopen it.  I'll close for now.

**Comment by p-groarke** [comment]
False alarm, it is still happening. It seems I was luck on my solo mod lobby.

Tested both 650M and Intel 4000, it happens using both :/

edit: I will set my preferences to always use discrete graphics. If that fixes the issue then the game is most likely not detecting GPUs correctly.

**Comment by danginsburg** [comment]
If you can figure out what conditions under which it happens or does not, it would be a big help.  I have this exact machine and have not seen this.

**Comment by danginsburg** [comment]
Also, try -gl_force_sm30 on the Launch Options and see if that makes a difference.

**Comment by p-groarke** [comment]
I think I have a culprit. Setting always use discrete graphics crashes reborn all the time. A little friend called mumble overlay pops his unhappy head :)

So, when I tested earlier (and it was working), I wasn't on mumbel. So that would seem to be the problem. I only recently started using mumble overlay for Eve, oh well.

Process:               dota2 [5731]
Path:                  /Users/USER/Library/Application Support/Steam/*/dota2
Identifier:            dota2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [5728]
Responsible:           steam_osx [5556]
User ID:               501

Date/Time:             2015-09-13 20:10:49.839 -0400
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        7FB7401D-CACC-B0E4-83E7-07E82A294D71

Sleep/Wake UUID:       BDF02AB8-814D-4A4A-9C7F-977FC7C57C1E

Time Awake Since Boot: 23000 seconds
Time Since Wake:       3600 seconds

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
/Library/ScriptingAdditions/MumbleOverlay.osax/Contents/MacOS/libmumbleoverlay.dylib
Assertion failed: ((_(long_)&island->instructions[0]) == kIslandTemplate[0]), function freeBranchIsland, file ../mach-override-src/mach_override.c, line 458.

Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff88da1286 **pthread_kill + 10
1   libsystem_c.dylib               0x00007fff91d919b3 abort + 129
2   libsystem_c.dylib               0x00007fff91d59a99 __assert_rtn + 321
3   libmumbleoverlay.dylib          0x00000000b8b2c5f6 freeBranchIsland + 150
4   libmumbleoverlay.dylib          0x00000000b8b2c312 mach_override_ptr + 1506
5   libmumbleoverlay.dylib          0x00000000b8b2babc MumbleOverlayEntryPoint + 1852
6   dyld                            0x00007fff64769d0b ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
7   dyld                            0x00007fff64769e98 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
8   dyld                            0x00007fff64766891 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
9   dyld                            0x00007fff64766718 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 138
10  dyld                            0x00007fff64766989 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
11  dyld                            0x00007fff6475c0ca dyld::runInitializers(ImageLoader_) + 89
12  dyld                            0x00007fff647631f1 dlopen + 578
13  libdyld.dylib                   0x00007fff91c2e857 dlopen + 59
14  net.sourceforge.mumble.OverlayScriptingAddition 0x000000009994ae8f MumbleOverlayEventHandler + 79
15  com.apple.openscripting         0x00007fff92a2a965 EventHandlerThunk(AEDesc const_, AEDesc_, void_) + 108
16  com.apple.AE                    0x00007fff8bd5143c aeDispatchAppleEvent(AEDesc const_, AEDesc_, unsigned int, unsigned char_) + 531
17  com.apple.AE                    0x00007fff8bd511b9 dispatchEventAndSendReply(AEDesc const_, AEDesc*) + 31
18  com.apple.AE                    0x00007fff8bd510c3 aeProcessAppleEvent + 295
19  com.apple.HIToolbox             0x00007fff8fc0ac6e AEProcessAppleEvent + 56
20  com.apple.AppKit                0x00007fff904c0da2 _DPSNextEvent + 2249
21  com.apple.AppKit                0x00007fff904bfe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
22  libSDL2-2.0.0.dylib             0x00000000808c9705 Cocoa_PumpEvents + 277
23  libSDL2-2.0.0.dylib             0x0000000080803e10 SDL_PumpEvents_REAL + 48
24  libSDL2-2.0.0.dylib             0x0000000080803ea8 SDL_WaitEventTimeout_REAL + 56
25  libSDL2-2.0.0.dylib             0x00000000807ef7aa SDL_WaitEventTimeout + 42
26  libinputsystem.dylib            0x000000008943b09e CInputSystem::SleepUntilInput(int) + 254
27  libengine2.dylib                0x000000000e8252d3 CEngineServiceMgr::_MainLoop(double, double) + 451
28  libengine2.dylib                0x000000000e8250df CEngineServiceMgr::MainLoop(double, double) + 15
29  libengine2.dylib                0x000000000e81c850 MainLoop(SwapChainHandle_t**_, PlatWindow_t___, InputContextHandle_t___) + 384
30  libengine2.dylib                0x000000000e81ce51 Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 817
31  libengine2.dylib                0x000000000e81d0b0 Source2Main + 208
32  dota2                           0x000000000e6d5d57 main + 535
33  libdyld.dylib                   0x00007fff91c2f5c9 start + 1

**Comment by danginsburg** [comment]
Indeed, the crash looks to be in libmumbleoverlay.dylib.  Please file a bug with them, thanks for tracking it down.  Closing.

**Comment by danginsburg** [comment]
By the way, for the corruption on HD 4000 (i.e. when it doesn't crash but you see blue screen), my best guess is that the Muble overlay is not restoring GL state.  If I had to wager a bet, they are disabling GL_CLIP_DISTANCE0 and not re-enabling it, but that's just a guess.  I don't know about mumble, but usually those tools work by hooking swapbuffers and injecting GL calls, which is prone to having problems with GL state interactions.

**Comment by p-groarke** [comment]
That's pretty interesting :) I may have a look at it, since its open-source anyways. Thanks for taking the time to give feedback/help. You guys are outdoing yourselves for Reborn! :D
