### ISSUE TITLE
[Linux] Fullscreen panel interference restricts edge-panning

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#435]
When running Linux in Desktop-friendly fullscreen or Borderless window at my monitors native resolution, I notice that when moving the cursor to the bottom of the screen, my panel (taskbar) gets priority over Dota 2, this results in me being unable to interact with the bottom of the screen and makes it impossible for me to play Dota 2 at my native resolution(fullscreen) as I rely on edge-panning. Some information about my system:
Kernel: 3.16.0-38-generic x86_64 (64 bit) 
Desktop: KDE 4.14.2 
Distro: Linux Mint 17.2 Rafaela
Graphics:
    Card: NVIDIA GM107 [GeForce GTX 750] 
    X.Org: 1.15.1 drivers: nvidia (unloaded: fbdev,vesa,nouveau) Resolution: 1920x1080@60.0hz 
    GLX Renderer: GeForce GTX 750/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 346.72

**Comment by budimanjojo** [comment]
Try running this in terminal "kcmshell5 kwincompositing" and Untick "suspend compositor for fullscreen windows", then try again (in very doubt, restart "kwin_x11 --replace &")

**Comment by ghost** [comment]
<code>No command 'kcmshell5' found, did you mean:
Command 'kcmshell4' from package 'kde-runtime' (universe)
kcmshell5: command not found
</code>
So after running kcmshell4 kwincompositing and unchecking the similar option in the Advanced tab, the issue was still not fixed.
![image](https://cloud.githubusercontent.com/assets/14020084/9837427/b33e1f9c-5a3e-11e5-80f1-acf5f8d9e15a.png)

**Comment by budimanjojo** [comment]
Yeah, kcmshell5 is for kde 5.
Okay maybe you should wait for the respond from the Valve devs then, I only know desktop effects on fullscreen windows can cause a lot of problems on games. Good luck :)

**Comment by ghost** [comment]
Some folks over at reddit.com/r/DotA2 helped me realise that the issue was the fact that I had my panel set to auto-hide (which is ofcourse my preference). It seems that for now I will most likely be changing this every time that I start/close Dota 2 as a temporary fix until I can find a better solution.
