### ISSUE TITLE
[Linux] "Cooldown" and timer text truncated on Glyph of Fortification popup

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#438]
Says "Cooldow" and is missing timer.
http://i.imgur.com/04udCmn.jpg

System info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/e5332271c7c37021cb5ba867b0bbeb38288d577b/gistfile1.txt

**Comment by ArnaudAndre** [comment]
[old bug](https://www.reddit.com/r/DotA2/comments/251lje/volvo_please_fix_the_cooldow/)

**Comment by jazztickets** [comment]
Which was never fixed for linux.

**Comment by ArnaudAndre** [comment]
you mean never fixed at all
(those kind of things are never platform specific and this one even predates reborn)

**Comment by jazztickets** [comment]
Nah, it was fixed in windows a while back:
http://i.imgur.com/zN45jhO.jpg

**Comment by ArnaudAndre** [comment]
My bad then. Is it correct in reborn on windows though ?

**Comment by jazztickets** [comment]
No prob. Yep, both of those screenshots were taken today.

**Comment by gdrewb-valve** [comment]
This isn't really platform-specific, it's just luck that it's working on Windows.  A fix will come in an upcoming update.
