### ISSUE TITLE
Linux Mint x32 . Missing exucatable!

### ISSUE THREAD

**Issue by OlegPinchuk** [ValveSoftware/Dota-2#439]
In the log i have this  - 
"[2015-09-13 21:48:05] Failed running app 570 (missing executable "/home/oleg/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/win32/dota2.exe")" .
.exe this is something strange, isn't?

**Comment by danginsburg** [comment]
We can look at fixing up the error message, but dota 2 is now only supported on 64-bit variants of Linux.

**Comment by davidw-valve** [comment]
Dota2 is now only supported on 64 bit Linux, so I will close this. We are looking at making a clearer error message.
