### ISSUE TITLE
Mac: Crash In-game.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#44]
https://gist.github.com/Vuccappella/4cde71b4b264b29575c1 . Crashed while playing custom lobby.

**Comment by gdrewb-valve** [comment]
Have you seen this since you first filed it?  We haven't been able to repro.

**Comment by Vuccappella** [comment]
I haven't. I will report if it happens again and under what circumstances it did, if it repeats itself. Only time so far the new client has crashed on me.

**Comment by gdrewb-valve** [comment]
OK, closing for now.
