### ISSUE TITLE
WIN 7 64 BITS (VMWARE)

### ISSUE THREAD

**Issue by echer** [ValveSoftware/Dota-2#440]
I have intel core i5 460m w/ intel graphics hd running in vmware windows 7 64 bits, but not able to run dota 2 reborn because im was getting "Unable to find a valid Direct 3D device", but i have a "VMware SVGA 3D" video adapter, where i go to add this video graphic to the list of devices?

**Comment by Vuccappella** [comment]
I think this is mainly an issue with vmware and not the dota2 client, I'm not sure if people can help you, and when you are running dota2 on vmware you're running the windows client for which there is the (dev.dota) forums. Running dota on vmware(or any other virtual machine) isn't officially supported from valve so I doubt they can help you, try checking in on some vmware forums or support.

**Comment by danginsburg** [comment]
As @Vuccappella says, this is not a Linux/OSX issue, so you are best off posting on VMware forums or if you want to try it, dev.dota2.com.
