### ISSUE TITLE
[Linux][Reborn]Legion Commander's biography empty

### ISSUE THREAD

**Issue by Srogozins** [ValveSoftware/Dota-2#443]
On other heroes' About pages you see an intro paragraph, Roles section and Biography. But for Legion Commander the Biography section contains no text, only the section title.

System info: https://gist.github.com/Srogozins/93792fe50ade441130f7
Spotted this a couple weeks ago. After performing a cursory survey, this seems to occur on other Arches as well, but not on Windows machines.

![screenshot from 2015-09-14 23-51-32](https://cloud.githubusercontent.com/assets/6780626/9861609/f00bdfb0-5b3b-11e5-9a4b-7371a953a8ac.png)

**Comment by Srogozins** [comment]
Just discovered that Omniknight has got the same issue. Not sure for how long this has been so either.

**Comment by Srogozins** [comment]
Ditto for Oracle and Shadow Demon.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by Srogozins** [comment]
Yes.

**Comment by gdrewb-valve** [comment]
I think we found the problem, a fix will be coming in a future update.

**Comment by gdrewb-valve** [comment]
I believe this was fixed in the Oct. 16th update, are you still seeing it?

**Comment by Srogozins** [comment]
Seems to be fixed now.
