### ISSUE TITLE
[OS X] Mouse lock not acquired if game is unfocused during game start

### ISSUE THREAD

**Issue by sgentle** [ValveSoftware/Dota-2#444]
Might be related to #212. I'm using Friendly Fullscreen on 10.10.4, and it seems the game doesn't acquire a mouse lock if it's unfocused when the lock would normally be acquired (eg during game start if the game starts while I'm alt-tabbed).

This may be by design - maybe OS X doesn't allow you to, or maybe it does something weird like snap the cursor back into the window - if so I think the appropriate behaviour would be to re-acquire the lock when the game gains focus again.

You can work around it currently by opening and closing the menu, which re-acquires the lock.

**Comment by gramathy** [comment]
Related to #238 I think, any "unfocus-refocus" of the application fixes it, correct?

**Comment by sgentle** [comment]
Afraid not. Un/refocus doesn't fix it, only going to the menu and back. When it's working, un/refocus also has no effect (ie it doesn't break it either).

**Comment by gdrewb-valve** [comment]
Is this still happening?  A fix for focus issues went out a bit ago.

**Comment by sgentle** [comment]
Seems to be fixed now. Thanks!
