### ISSUE TITLE
very low fps (Ivybridge mesa 10.5.9 + oibaf-ppa)

### ISSUE THREAD

**Issue by TRiedling** [ValveSoftware/Dota-2#446]
Dota reborn has very low fps. Before reborn everything was ok. Now I have 20-30fps at the start of the game. But when some action is going on it drops to 4-10 fps. Sometimes freezing for 10 or more sec when playing  matchmaking. The drop in fps also happens in local lobby or bot games.

Here my specs:
Processor Information:
Vendor: GenuineIntel
CPU Family: 0x6
CPU Model: 0x3a
CPU Stepping: 0x9
CPU Type: 0x0
Speed: 3200 Mhz
4 logical processors
2 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed:

Operating System Version:
Ubuntu 15.04 (64 bit)
Kernel Name: Linux
Kernel Version: 3.19.0-28-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11701000
X Window Manager: Compiz
Steam Runtime Version: steam-runtime-release_2015-06-12

Video Card:
Driver: Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

Driver Version:  3.0 Mesa 10.5.9
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x682f
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 13,54" x 7,64"  (15,51" diag)
                                        34,4cm x 19,4cm  (39,4cm diag)
Primary VRAM Not Detected
Sound card:
Audio device: Intel PantherPoint HDMI

Memory:
RAM: 7853 Mb

Miscellaneous:
UI Language: English
LANG: de_DE.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 366735 Mb
Largest Free Hard Disk Block: 331329 Mb

Installed software:

Recent Failure Reports:

**Comment by edwinksl** [comment]
Have you tried upgrading your GPU driver using either the oibaf PPA or xorg-edgers PPA?

I am also running Ubuntu 15.04 using the latest GPU driver from the oibaf PPA but my FPS dips to 5 (from 60) periodically. I am curious if upgrading your driver helps you since it didn't really help me.

**Comment by TRiedling** [comment]
I installed my whole system (ubuntu 15.04) new, but it didnt change anything. I will have a look in the drivers.

**Comment by Pharmasolin** [comment]
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-apt update
sudo apt-get dist-upgrade

Try this then reboot pc and write if it will help you.

If it will make your game worth, use:

sudo apt-get install ppa-purge
sudo ppa-purge ppa:oibaf/graphics-drivers

You will restore default mesa from Ubuntu

**Comment by TRiedling** [comment]
i tried the oibaf ppa. I dont think it changed something for me. Maybe the drop of the fps is less often. Fps is still droping in Bot Games, when there is a lot of hero action going on to 8-10fps.

**Comment by edwinksl** [comment]
Yeah, so I guess you are in the same situation as me then. Tough luck.

**Comment by admshao** [comment]
Running on default nvidia-346 from Ubuntu 15.04 ppa i have a stable fps now

I tried the oiabf and xorg-edgers up to 355 and either i had high fps drops
on tema fights, camera moviments and spells casts or it blow my X-server at
all. Infinite login black screen loop that i had to go down to recovery
mode and revert to proprietary.

2015-09-15 18:46 GMT-03:00 Edwin Khoo notifications@github.com:

**Comment by edwinksl** [comment]
Well, OP has a Intel GPU, so I am not sure if what you did for your Nvidia GPU is directly applicable.

**Comment by admshao** [comment]
Yeah. Not directly. Just a chance that he might have some driver version
issue somehow. I thought it worthed a try

**Comment by edwinksl** [comment]
Yeah, I was hoping it was a driver version issue but it doesn't seem like it is the case for Intel GPUs on Ubuntu. I am hoping Valve will at least give us some hints and tips on what we can try. We are basically their beta testers for the Linux client at this point.

**Comment by danginsburg** [comment]
@TRiedling What are your video settings?  8-10fps sounds quite low for your config.  You can post game/dota/cfg/video.txt

**Comment by TRiedling** [comment]
here my settings:
There is no difference if I change the resolution.

"video.cfg"
{
    "VendorID"      "4098"
    "DeviceID"      "26671"
    "setting.cpu_level"     "0"
    "setting.mem_level"     "2"
    "setting.gpu_mem_level"     "2"
    "setting.defaultres"        "1280"
    "setting.defaultresheight"      "720"
    "setting.gpu_level"     "2"
    "setting.version"       "1"
    "setting.knowndevice"       "1"
    "setting.fullscreen"        "0"
    "setting.coop_fullscreen"       "1"
    "setting.nowindowborder"        "0"
    "setting.mat_vsync"     "0"
    "setting.fullscreen_min_on_focus_loss"      "1"
    "setting.dota_cheap_water"      "1"
    "setting.r_deferred_height_fog"     "0"
    "setting.r_deferred_simple_light"       "0"
    "setting.r_ssao"        "0"
    "setting.cl_globallight_shadow_mode"        "0"
    "setting.r_dota_fxaa"       "0"
    "setting.r_deferred_additive_pass"      "0"
    "setting.dota_portrait_animate"     "0"
    "setting.r_deferred_specular_bloom"     "0"
    "setting.r_deferred_specular"       "0"
    "setting.dota_ambient_creatures"        "0"
    "setting.r_texture_stream_mip_bias"     "2"
    "setting.r_dota_normal_maps"        "0"
    "setting.r_dashboard_render_quality"        "0"
    "setting.shaderquality"     "0"
    "setting.recommendedheight"     "600"
    "setting.mat_viewportscale"     "0.515789"
    "setting.r_fullscreen_gamma"        "2.200000"

**Comment by danginsburg** [comment]
You perfis definitely way below what it should be given your settings and system spec.   Can you make sure that your clock frequency isn't getting scaled?  Try for example:

#!/bin/bash

set -x

cpufreq-set -c 0 -r -g performance
cpufreq-set -c 1 -r -g performance
cpufreq-set -c 2 -r -g performance
cpufreq-set -c 3 -r -g performance
cpufreq-set -c 4 -r -g performance
cpufreq-set -c 5 -r -g performance
cpufreq-set -c 6 -r -g performance
cpufreq-set -c 7 -r -g performance

mount -t debugfs none /sys/kernel/debug > /dev/null 2&>1 || true
MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
bash -c "echo $MAXCLOCK > /sys/kernel/debug/dri/0/i915_min_freq"

rmmod intel_powerclamp x86_pkg_temp_thermal

Then I do this to watch the clock rates:

gnome-terminal -e 'watch -n1 "cat /proc/cpuinfo | grep MHz"'
gnome-terminal -e 'watch "sudo sensors -f"

**Comment by TRiedling** [comment]
I wrote all of your commands into the terminal.

After that I got a window with 4 frequencies, which where fluctuating between 1500 and  3200MHz.

I'm not shure if I did everything right. So here ist the output of my terminal:

torsten@Schroedinger:~$ #!/bin/bash
torsten@Schroedinger:~$ set -x
torsten@Schroedinger:~$ cpufreq -c 0 -r -g performance
- cpufreq -c 0 -r -g performance
- '[' -x /usr/lib/command-not-found ']'
- /usr/lib/command-not-found -- cpufreq
  Der Befehl »cpufreq« wurde nicht gefunden, meinten Sie vielleicht:
  Befehl »cpufreqd« aus dem Paket »cpufreqd« (universe)
  cpufreq: Befehl nicht gefunden.
- return 127
  torsten@Schroedinger:~$ cpufreq-set -c 0 -r -g performance
- cpufreq-set -c 0 -r -g performance
- '[' -x /usr/lib/command-not-found ']'
- /usr/lib/command-not-found -- cpufreq-set
  Die Anwendung »cpufreq-set« ist momentan nicht installiert. Sie können sie durch folgende Eingabe installieren:
  sudo apt-get install cpufrequtils
- return 127
  torsten@Schroedinger:~$ sudo apt-get install cpufrequtils
- sudo apt-get install cpufrequtils
  [sudo] password for torsten: 
  Paketlisten werden gelesen... Fertig
  Abhängigkeitsbaum wird aufgebaut.  
  Statusinformationen werden eingelesen.... Fertig
  Die folgenden zusätzlichen Pakete werden installiert:
  libcpufreq0
  Die folgenden NEUEN Pakete werden installiert:
  cpufrequtils libcpufreq0
  0 aktualisiert, 2 neu installiert, 0 zu entfernen und 12 nicht aktualisiert.
  Es müssen 52,9 kB an Archiven heruntergeladen werden.
  Nach dieser Operation werden 300 kB Plattenplatz zusätzlich benutzt.
  Möchten Sie fortfahren? [J/n] j
  Holen: 1 http://de.archive.ubuntu.com/ubuntu/ vivid/universe libcpufreq0 amd64 008-1 [13,7 kB]
  Holen: 2 http://de.archive.ubuntu.com/ubuntu/ vivid/universe cpufrequtils amd64 008-1 [39,2 kB]
  Es wurden 52,9 kB in 0 s geholt (192 kB/s).
  Vorkonfiguration der Pakete ...
  Vormals nicht ausgewähltes Paket libcpufreq0 wird gewählt.
  (Lese Datenbank ... 207112 Dateien und Verzeichnisse sind derzeit installiert.)
  Vorbereitung zum Entpacken von .../libcpufreq0_008-1_amd64.deb ...
  Entpacken von libcpufreq0 (008-1) ...
  Vormals nicht ausgewähltes Paket cpufrequtils wird gewählt.
  Vorbereitung zum Entpacken von .../cpufrequtils_008-1_amd64.deb ...
  Entpacken von cpufrequtils (008-1) ...
  Trigger für man-db (2.7.0.2-5) werden verarbeitet ...
  Trigger für systemd (219-7ubuntu6) werden verarbeitet ...
  Trigger für ureadahead (0.100.0-19) werden verarbeitet ...
  ureadahead will be reprofiled on next reboot
  libcpufreq0 (008-1) wird eingerichtet ...
  cpufrequtils (008-1) wird eingerichtet ...
  update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
  update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
  Trigger für libc-bin (2.21-0ubuntu4) werden verarbeitet ...
  Trigger für systemd (219-7ubuntu6) werden verarbeitet ...
  Trigger für ureadahead (0.100.0-19) werden verarbeitet ...
  torsten@Schroedinger:~$ cpufreq-set -c 0 -r -g performance
- cpufreq-set -c 0 -r -g performance
  Beim Einstellen ist ein Fehler aufgetreten. Typische Fehlerquellen sind:
- nicht ausreichende Rechte (Administrator)
- der Regler ist nicht verfügbar bzw. nicht geladen
- die angegebene Taktik ist inkorrekt
- eine spezifische Frequenz wurde angegeben, aber der Regler 'userspace'
  kann entweder hardwarebedingt nicht genutzt werden oder ist nicht geladen
  torsten@Schroedinger:~$ sudo cpufreq-set -c 0 -r -g performance
- sudo cpufreq-set -c 0 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 1 -r -g performance
- sudo cpufreq-set -c 1 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 2 -r -g performance
- sudo cpufreq-set -c 2 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 3 -r -g performance
- sudo cpufreq-set -c 3 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 4 -r -g performance
- sudo cpufreq-set -c 4 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 5 -r -g performance
- sudo cpufreq-set -c 5 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 6 -r -g performance
- sudo cpufreq-set -c 6 -r -g performance
  torsten@Schroedinger:~$ sudo cpufreq-set -c 7 -r -g performance
- sudo cpufreq-set -c 7 -r -g performance
  torsten@Schroedinger:~$ mount -t debugfs none /sys/kernel/debug>/dev/null 2&>1||true
- mount -t debugfs none /sys/kernel/debug 2
- true
  torsten@Schroedinger:~$ MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
- MAXCLOCK=cat
- /sys/kernel/debug/dri/0/i915_max_freq
  bash: /sys/kernel/debug/dri/0/i915_max_freq: Keine Berechtigung
  torsten@Schroedinger:~$ sudo MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
- sudo MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
  sudo: /sys/kernel/debug/dri/0/i915_max_freq: command not found
  torsten@Schroedinger:~$ sudo MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
- sudo MAXCLOCK=cat /sys/kernel/debug/dri/0/i915_max_freq
  sudo: /sys/kernel/debug/dri/0/i915_max_freq: command not found
  torsten@Schroedinger:~$ sudo MAXCLOCK=cat/sys/kernel/debug/dri/0/i915_max_freq
- sudo MAXCLOCK=cat/sys/kernel/debug/dri/0/i915_max_freq
  usage: sudo -h | -K | -k | -V
  usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
  usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
          [command]
  usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
          prompt] [-u user] [VAR=value] [-i|-s] [<command>]
  usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
          prompt] [-u user] file ...
  torsten@Schroedinger:~$ MAXCLOCK=cat/sys/kernel/debug/dri/0/i915_max_freq
- MAXCLOCK=cat/sys/kernel/debug/dri/0/i915_max_freq
  torsten@Schroedinger:~$ bash -c "echo $MAXCLOCK > /sys/kernel/debug/dri/0/i915_min_freq"
- bash -c 'echo cat/sys/kernel/debug/dri/0/i915_max_freq > /sys/kernel/debug/dri/0/i915_min_freq'
  bash: /sys/kernel/debug/dri/0/i915_min_freq: Keine Berechtigung
  torsten@Schroedinger:~$ rmmod intel_powerclamp x86_pkg_temp_thermal
- rmmod intel_powerclamp x86_pkg_temp_thermal
  rmmod: ERROR: ../libkmod/libkmod-module.c:777 kmod_module_remove_module() could not remove 'intel_powerclamp': Operation not permitted
  rmmod: ERROR: could not remove module intel_powerclamp: Operation not permitted
  rmmod: ERROR: ../libkmod/libkmod-module.c:777 kmod_module_remove_module() could not remove 'x86_pkg_temp_thermal': Operation not permitted
  rmmod: ERROR: could not remove module x86_pkg_temp_thermal: Operation not permitted
  torsten@Schroedinger:~$ gnome-terminal -e 'watch -n1 "cat /proc/cpuinfo | grep MHz"'
- gnome-terminal -e 'watch -n1 "cat /proc/cpuinfo | grep MHz"'
  torsten@Schroedinger:~$ gnome-terminal -e 'watch "sudo sensors -f"
  > 

Thanks!!!

**Comment by danginsburg** [comment]
I think you need to install cpufrequtils:

sudo apt-get install cpufrequtils

**Comment by TRiedling** [comment]
I did already.
You can see it at the 9th point of my terminal output.

**Comment by longdt** [comment]
I have same issue with Intel Graphic HD3000 mesa from xorg-edgers PPA

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
