### ISSUE TITLE
huge latency

### ISSUE THREAD

**Issue by SuperFlick** [ValveSoftware/Dota-2#449]
I have my regular ping in reborn 110-140. but there is a huge latency like 0.7-1.5 sec. no matter if i use wifi or lan, with skype and browser or w\o.
in source1 i had low latency, but now i just cant play at all
 linux ubuntu studio x64

**Comment by ArnaudAndre** [comment]
Does that also happen if you play a local bot game ? Also, how are you getting those ping readings ? (there's at least 4 different ways to get pings and they mostly disagree with each other)

**Comment by gdrewb-valve** [comment]
Closing pending more info.
