### ISSUE TITLE
[Linux] Player models and towers replaced with error when rejoining a crashed game

### ISSUE THREAD

**Issue by Xaue** [ValveSoftware/Dota-2#45]
When rejoining a game after crashing, no assets will load, meaning certain heros are unable to target the errors, because they don't seem to be actually clickable either.

![Image of Error](http://images.akamai.steamusercontent.com/ugc/37501219154886379/B57B5F9D765E3BE766C0495E3236A74D415950B2/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to=*,*|2048:1152&background-color=black)
Using propreitry nvidia drivers with a GTX 680 4GB and AMD Fx-6100

**Comment by gdrewb-valve** [comment]
Did the game completely exit after crashing?

**Comment by Xaue** [comment]
No, upon crashing the game froze and I had to alt+F4 out of the game. I should also note every player in the game was crashing multiple times.

**Comment by gdrewb-valve** [comment]
Have you seen this recently?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by Xaue** [comment]
Hello, no this hasn't happened again. Seems like an early fluke bug/ glitch
