### ISSUE TITLE
[Linux] Keybinding Space doesn't work (most of the time).

### ISSUE THREAD

**Issue by MaikuMori** [ValveSoftware/Dota-2#453]
When I keybind space to quickcast it doesn't work.

When I try to keybind space the button turns blank (like there is no keybind) and ingame the keybind text is " " (blank square).

Sometimes after patches I can keybind space and it works and the text is "SPACE", but at some point it just stops working. I try to rebind it and it then is :" " and still doesn't work.

The only idea I have is that maybe it's affected by me using 2 input languages in on my Linux. I tried to swap languages and rebind, but it didn't work. Either way the character code should be the same.

Other keybinds don't have this issue. I'm using MOUSE4 for quickcast and it works fine.

**Comment by gdrewb-valve** [comment]
Key bindings are keyboard-layout-specific so changing layouts can affect bindings.  If you add -input_button_code_is_scan_code to your launch options does it work as you expect (changing this option may require you to reset your bindings)?

**Comment by MaikuMori** [comment]
Using this launch option + rebinding the key (It still shows as  blank square in options instead of "SPACE") fixes the issue.

I find it strange that the space has different code between these two layouts. My main layout is English, but the other one is Latvian. Key layout is almost the same, it only ads special handling for inputting `ā/č/š` via `right ALT + A/C/S` and so on.

**Comment by gdrewb-valve** [comment]
I agree it's strange that it would be different, but it may be some other interaction with keyboard layouts.  Regardless, if it works that's progress.  There'll likely be a UI setting for this instead of requiring the launch option.

It's also strange that you don't get the name SPACE, which suggests somehow the key isn't actually space underneath or something bizarre like that.

**Comment by gdrewb-valve** [comment]
Can you add -input_message_spew and -console to your launch options, then open the console in the main menu and press space?  You should get some spew about the key going down and up that'll tell more about what space is showing up as.  Can you try that with and without -input_button_code_is_scan_code so that I can see the difference?

**Comment by MaikuMori** [comment]
With `-input_button_code_is_scan_code`:

```
SDL:  got SDL_KEYDOWN
KEYDOWN (scan): sdlkeycode=1073741824 sdlscancode=44 SDL_GetKeyName='' buttoncode=66 buttonname='SPACE' ButtonCode_GetLocalKeyNameUTF8=''
SDL:  got SDL_TEXTINPUT
TEXTINPUT ' '
SDL:  got SDL_KEYUP
KEYUP (scan) 66 (SPACE)
```

Without `-input_button_code_is_scan_code`:

```
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=1073741824 sdlscancode=44 SDL_GetKeyName='' buttoncode=0 buttonname='' ButtonCode_GetLocalKeyNameUTF8=''
SDL:  got SDL_TEXTINPUT
TEXTINPUT ' '
SDL:  got SDL_KEYUP
KEYUP (keyc) 0 ()
```

Seems like it fails to get proper `buttoncode`.

Also while now using `-input_button_code_is_scan_code` I still don't get text "SPACE" in options it does show up in-game over the inventory slot.

**Comment by gdrewb-valve** [comment]
SDL itself isn't recognizing your space key as space. SDLK_SPACE is 32 so the sdlkeycode here should be 32, but instead it's SDLK_SCANCODE_MASK | SDL_SCANCODE_UNKNOWN.  That lack of information prevents Reborn from recognizing it as space.  I'll pass this on to the SDL devs and see what they say.

**Comment by gdrewb-valve** [comment]
Can you post your Steam system info so that we have your specs here?

**Comment by MaikuMori** [comment]
Sure:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CAYMAN (DRM 2.43.0, LLVM 3.7.0)

    Driver Version:  3.0 Mesa 11.0.3
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x6718
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  24100 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  228811 Mb
    Largest Free Hard Disk Block:  109720 Mb

Installed software:

Recent Failure Reports:
...snip...
```

VRAM detection doesn't work because of ValveSoftware/steam-for-linux#3734. It's ATI 6970 2GB.

This is my input configuration in Gnome. I guess screenshot is fine, I don't feel like digging into gnome settings db to get exact values.

![screenshot from 2015-10-15 22-08-01](https://cloud.githubusercontent.com/assets/28470/10524627/39aeaf52-7389-11e5-857c-f455d7d27c43.png)

**Comment by gdrewb-valve** [comment]
SDL bug 3153.

**Comment by magist3r** [comment]
Some more info. Load Dota 2 with 'ru' keymap and press '1':

With -input_button_code_is_scan_code:

```
SDL:  got SDL_KEYDOWN
KEYDOWN (scan): sdlkeycode=13 sdlscancode=30 SDL_GetKeyName='Return' buttoncode=2 buttonname='1' ButtonCode_GetLocalKeyNameUTF8='Return'
SDL:  got SDL_TEXTINPUT
TEXTINPUT '1'
] 1
SDL:  got SDL_KEYUP
KEYUP (scan) 2 (1)
```

Without -input_button_code_is_scan_code:

```
KEYDOWN (keyc): sdlkeycode=13 sdlscancode=30 SDL_GetKeyName='Return' buttoncode=65 buttonname='ENTER' ButtonCode_GetLocalKeyNameUTF8='Return'
SDL:  got SDL_TEXTINPUT
TEXTINPUT '1'
] 1
SDL:  got SDL_KEYUP
KEYUP (keyc) 65 (ENTER)
```

With 'en' keymap all works fine.

Some system info:

```
openSUSE 13.2 (Harlequin) (x86_64) 3.16.7-24-desktop
The X.Org Foundation 11601000 KWin
steam-runtime-release_2015-06-12
```

**Comment by magist3r** [comment]
Example with 'en' keymap:

```
KEYDOWN (scan): sdlkeycode=49 sdlscancode=30 SDL_GetKeyName='1' buttoncode=2 buttonname='1' ButtonCode_GetLocalKeyNameUTF8='1'
SDL:  got SDL_TEXTINPUT
TEXTINPUT '1'
SDL:  got SDL_KEYUP
KEYUP (scan) 2 (1)
```

**Comment by gdrewb-valve** [comment]
Thanks, that does look like the same SDL bug where it isn't recognizing keys properly.

**Comment by icculus** [comment]
Hey, can those that are still seeing this bug run "xev >log.txt", press NOTHING but the problem key on the keyboard, then close the window without touching the keyboard? I want to see what something that's not SDL thinks it sees from the keyboard on your machine. Attach the log file here.

Thanks!

**Comment by gdrewb-valve** [comment]
Anybody having this problem, please post the information per rcgordon's comment.  We need more information to make progress.

**Comment by magist3r** [comment]
Here is my logs. I pressed button '1' after starting command with en and ru locales.
[log_en.txt](https://github.com/ValveSoftware/Dota-2/files/159842/log_en.txt)
[log_ru.txt](https://github.com/ValveSoftware/Dota-2/files/159843/log_ru.txt)

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by magist3r** [comment]
Yes, bug is still here :(

**Comment by bioxz** [comment]
Same problem here with SDL 2.0.4 (is there an update that should fix the problem? I haven't tried the mercurial version so far, only stable.). "1"-Key and "Space"-Key are broken. With "Bind keys based on keyboard position" disabled, i cannot bind "Space" (nothing happens). With that option enabled, i can bind "Space" (but there is no description in the game for that binding, just a blank field.). When i disable the option again, i can see the description "Space" i assigned before. Keyboard layout is english international altgr dead keys.

Some logs are following. Do you need any more information? Or is there already a patch to test?
- xev log:

```
KeyPress event, serial 40, synthetic NO, window 0x8400001,
    root 0xd5, subw 0x0, time 5018291, (533,491), root:(533,518),
    state 0x2010, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x8400001,
    root 0xd5, subw 0x0, time 5018371, (533,491), root:(533,518),
    state 0x2010, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False
```
- Dota 2 console without "Bind keys based on keyboard position"

```
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=1073741824 sdlscancode=44 SDL_GetKeyName='' buttoncode=0 buttonname='' ButtonCode_GetLocalKeyNameUTF8=''
SDL:  got SDL_TEXTINPUT
TEXTINPUT ' '
SDL:  got SDL_KEYUP
KEYUP (keyc) sdlkeycode=1073741824 sdlscancode=44 buttoncode=0 buttonname=''

```
- Dota 2 console with "Bind keys based on keyboard position"

```
SDL:  got SDL_KEYDOWN
KEYDOWN (scan): sdlkeycode=1073741824 sdlscancode=44 SDL_GetKeyName='' buttoncode=66 buttonname='SPACE' ButtonCode_GetLocalKeyNameUTF8=''
SDL:  got SDL_TEXTINPUT
TEXTINPUT ' '
SDL:  got SDL_KEYUP
KEYUP (scan) sdlkeycode=1073741824 sdlscancode=44 buttoncode=66 buttonname='SPACE'

```
- Screenshot of "Space" binding with "Bind keys based on keyboard position" enabled (Item slot six)
  ![20160430004224_1](https://cloud.githubusercontent.com/assets/1084262/14931543/a8985796-0e6c-11e6-8f36-75bf8be344a7.jpg)

**Comment by gdrewb-valve** [comment]
We're waiting on the SDL devs.  When something happens we'll update this issue.

**Comment by gdrewb-valve** [comment]
We have updated SDL with some keyboard fixes.  Is this still an issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by artemjackson** [comment]
Still have the issue

**Comment by artemjackson** [comment]
Just noticed a tread https://github.com/ValveSoftware/Dota-2/issues/473

> In the Advanced section of key binding settings you can choose to have bindings be positional.

Solved the issue

**Comment by gdrewb-valve** [comment]
That's the same situation as the original poster here.  Positional keybinds work but space isn't being recognized properly as space.  We'll leave this open assigned to the SDL dev.

**Comment by gdrewb-valve** [comment]
We've shipped a new SDL which had some changes in this area, are people still having this problem with the space key?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this is active.
