### ISSUE TITLE
Korean Chat Input Bug

### ISSUE THREAD

**Issue by MisterTaxman** [ValveSoftware/Dota-2#455]
There seems to be a problem with Korean chat input wherein whenever I want to delete a single chat letter, the whole character BEFORE it (along with the character it is on) gets deleted instead. For example:

> 안녕히 (and I want to delete ㅣ)
> 안 (after pressing backspace)

If it wasn't bug it should show "안녕ㅎ" instead.

Thanks

**Comment by Tele42** [comment]
Duplicate of #425.
Please add your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information to that issue report.

**Comment by MisterTaxman** [comment]
Dear Mods,

I have seen bug report #425 prior to submitting this one as I believe that this is an entirely different problem. This problem occurs during input (typing) while the other problem occurs during sending (hitting enter to send chat). This problem is like if I typed "This is a sentenca" and pressed backspace, the result would be "This is a" being seen on the chatbox. Note that the message hasn't been sent yet as it is still in the chatbox.

I hope this would be open for reconsideration.

Thanks!

System Info:
Windows 8.1
i5 4590
8GB RAM
MSI GTX970

**Comment by appleparan** [comment]
Actually this issue tracker is only for mac & linux ver.

**Comment by gdrewb-valve** [comment]
As mentioned this bug tracker isn't for Windows issues.  I've passed this report on to the larger team and this will end up getting closed.

**Comment by gdrewb-valve** [comment]
The larger team is taking a look.
