### ISSUE TITLE
[LINUX] Dota2 dont start, xubuntu 14.04.3(64 bit)

### ISSUE THREAD

**Issue by headinthebag** [ValveSoftware/Dota-2#456]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x27
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2400 Mhz
    1 logical processor
    1 physical processor
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Operating System Version:
    Ubuntu 14.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-53-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 355.11
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 69 Hz
    VendorID:  0x10de
    DeviceID:  0xfc6
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 17,48" x 10,94"  (20,59" diag)
                                            44,4cm x 27,8cm  (52,3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 42 HDMI/DP

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  146285 Mb
    Largest Free Hard Disk Block:  75939 Mb

dump here
http://pastebin.com/raw.php?i=aPJfWG70

**Comment by vitaliy-evsyukov** [comment]
Start from console. Same problem? https://github.com/ValveSoftware/Dota-2/issues/413

**Comment by headinthebag** [comment]
Game update: AppID 570 "Dota 2", ProcID 14544, IP 0.0.0.0:0
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 14547 != 14546, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
/home/alex/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: строка 98: 14549 Недопустимая инструкция (подготовлен дамп ядра) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

**Comment by danginsburg** [comment]
@headinthebag Can you please try doing "Verify Local Game Cache..." in Steam?  If that does not fix it, can you run with -con_logfile on the command-line and post the contents of game/dota/console.log.  Also, if it is crashing, it should write a minidump file, you can see the last one written in Steam -> Help -> System Information.  It would be helpful to post the minidump.

**Comment by headinthebag** [comment]
@danginsburg dump here http://pastebin.com/raw.php?i=aPJfWG70
i do "Verify cash', its not fix. I reinstall steam with all games, i delete all config files and its not fix it.

thats dota2 errors:
Game update: AppID 570 "Dota 2", ProcID 8752, IP 0.0.0.0:0
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 8755 != 8754, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
/home/alex/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: строка 98:  8757 Недопустимая инструкция (подготовлен дамп ядра) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 8752 
Generating new string page texture 112: 256x256, total string texture memory is 2,82 MB

**Comment by Tele42** [comment]
@headinthebag the pastebin you provided is a console log, not a dump. @danginsburg is asking for a corresponding SteamID from Steam -> Help -> System Information or a .dmp posted somewhere.

**Comment by headinthebag** [comment]
@Tele42 "Recent Failure Reports" is empty. SteamID: STEAM_0:0:44565242

 File from /var/log/steam here 
https://drive.google.com/file/d/0Bz2SJdz29kBXUy1KcDExb1FhakE/view?usp=sharing

**Comment by demaseme** [comment]
I have the same error, using Radeon R7 graphics in brand new Ubuntu 15.04 64Bit installation.

**Comment by gdrewb-valve** [comment]
If you have no failure reports that means the crash came before Steam and the game really had a chance to run.  That is often an issue with video drivers not working properly.  If you are familiar with using gdb you can run under gdb and see if you can get a backtrace to at least see what component is having a problem.

**Comment by gdrewb-valve** [comment]
Were you able to get any more information on this?

**Comment by headinthebag** [comment]
@gdrewb-valve the problem was non-standard cursor system, back to default and everything worked

**Comment by gdrewb-valve** [comment]
Thanks, closing.
