### ISSUE TITLE
LINUX OpenGL failed "createContext()"

### ISSUE THREAD

**Issue by Nostra6amus** [ValveSoftware/Dota-2#458]
Hi,

When I run Dota Reborn it just show:

"CreateContext():
Failed to create a OpenGL context."

Quad 6400
4GB ram

Linux diver 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) G41
OpenGL version string: 2.1 Mesa 11.1.0-devel (git-47e18a5 2015-09-16 trusty-oibaf-ppa)
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.1.0-devel (git-47e18a5 2015-09-16 trusty-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

This is the screen:
"ExecSteamURL: "steam://open/downloads"
Generating new string page texture 603: 64x256, total string texture memory is 1,18 MB
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Game update: AppID 570 "Dota 2", ProcID 3962, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nostra/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nostra/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 3965 != 3964, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/nostra/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nostra/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID: Caching Steam ID: 76561198091445368 [API loaded yes]
Steam_SetMinidumpSteamID: Setting Steam ID: 76561198091445368
Setting breakpad minidump AppID = 373300
Failed to create an OpenGL context.
Dongle firmware /home/nostra/.local/share/Steam/linux64/../controller_base/d0ggle.bin loaded, version 1435869091.
Attempting to create OpenGL context: v3.3 (Core profile)...failed.
Attempting to create OpenGL context: v3.1 (Core profile)...failed."

Is it Reborn not compatible with OpenGL v2.1?
Why Reborn dont attempt to create context on v2.1?

**Comment by danginsburg** [comment]
Indeed, the minimum Intel GPU that supports OpenGL v3.1 on mesa is Sandybridge (i.e. HD 3000-class).  Source 2 requires that as a minimum so unfortunately your hardware is not supported.  You didn't actually provide your system information, but from the brief description I think you have Intel GMA X4500 which is below minspec.  This is listed in the minimum requirements on the Steam page for Dota 2 on Steam OS + Linux.

**Comment by Nostra6amus** [comment]
ty
