### ISSUE TITLE
debian linux text display / font bug

### ISSUE THREAD

**Issue by Dexterlab1986** [ValveSoftware/Dota-2#459]
![instantanea1](https://cloud.githubusercontent.com/assets/14339690/9949616/be4b304e-5d74-11e5-979d-54f01cc0c8d7.png)
desde que instale reborn  tengo el siguiente problema ,  no se aprecian los nombres; de los items, heroes , el chat sale solo rayas,  el reloj tambien se ve afectado. No se a que se deba , espero su ayuda gracias

**Comment by davidw-valve** [comment]
What locale are you using? If you set the game to use English does this problem still occur?

**Comment by Dexterlab1986** [comment]
Hi  @davidw-valve  le puse  todo el entorno de steam y  del juego en inglés, pero presenta el mismo, error, sigue lo mismo

**Comment by Dexterlab1986** [comment]
please need any solution please

Att:

ING. JUAN ZAMORA
CHIEF LEADER
-ROCARELI
-PLUS FINCA
Telf: 062833944
Cel: 0985494086
ECUADOR

Date: Fri, 18 Sep 2015 11:17:42 -0700

**Comment by Tele42** [comment]
@Dexterlab1986 it would help if you answered the question @davidw-valve asked you, your locale is a system-wide setting, not in steam. What happens if you close steam, in a terminal run `LANG=C steam` and try to run the game?

**Comment by Dexterlab1986** [comment]
yes i change  the locale , i put usa utf 8 , then all my system change , but the  problem persist,

Att:

ING. JUAN ZAMORA
CHIEF LEADER
-ROCARELI
-PLUS FINCA
Telf: 062833944
Cel: 0985494086
ECUADOR

Date: Fri, 25 Sep 2015 06:45:19 -0700

**Comment by Dexterlab1986** [comment]
need help  wiht this  problem
Att:

ING. JUAN ZAMORA
CHIEF LEADER
-ROCARELI
-PLUS FINCA
Telf: 062833944
Cel: 0985494086
ECUADOR

Date: Fri, 18 Sep 2015 11:17:42 -0700

**Comment by Dexterlab1986** [comment]
![instantanea1](https://cloud.githubusercontent.com/assets/14339690/10119794/fb3114f8-6466-11e5-8b81-d9ad7ed9854b.png)

pero el problema continua

**Comment by stefanbesler** [comment]
did you run locale-gen afterwards?

**Comment by Dexterlab1986** [comment]
Then .i do all necessary but . what is the problem whith it 

Date: Wed, 30 Sep 2015 03:29:53 -0700

**Comment by Dexterlab1986** [comment]
hi

Date: Wed, 30 Sep 2015 03:29:53 -0700

**Comment by Dexterlab1986** [comment]
![shalalalalal1](https://cloud.githubusercontent.com/assets/14339690/10199950/31a0c3d0-6769-11e5-8bf7-473e8f7dd851.png)
el problema continua

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?  This looks like a problem that was reported with certain older graphics drivers.

**Comment by gdrewb-valve** [comment]
Also look at issues like #485.

**Comment by daya-prac** [comment]
My Debian 8 also has this question

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?  As I mentioned above this looks like a known problem with older graphics drivers.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
