### ISSUE TITLE
Lina Skills Damage?

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#460]
The damage dealt by Lina's skills are displayed incorrectly. Screenshot tells everything.
![2015-09-17_00001](https://cloud.githubusercontent.com/assets/13085918/9954775/ec5a000e-5e15-11e5-89e1-aa4d396de240.jpg)

**Comment by edwinksl** [comment]
Did you have illusions?

**Comment by budimanjojo** [comment]
Yeah, I got the rune then they ganked me there

**Comment by edwinksl** [comment]
That would explain it: the damage shown includes the damage done to illusions. This has always been the case as far as I know. Not sure if it is a bug or a feature to be honest.

**Comment by budimanjojo** [comment]
Ok, if that's a feature then the devs can feel free to close this issue :)
