### ISSUE TITLE
ran out of networkable entities

### ISSUE THREAD

**Issue by poiuty** [ValveSoftware/Dota-2#461]
<img src="https://poiuty.com/img/97b7e45abb758cebcfd54521a071.png">

**Comment by Tele42** [comment]
@poiuty that's a really neat screenshot, please try to be more verbose with your issue report as requested at https://github.com/ValveSoftware/Dota-2#reporting-issues.

**Comment by gdrewb-valve** [comment]
We'll need more information, such as what you were doing when this came up, whether it happens repeatedly, your system information and so on.  Closing pending more info.
