### ISSUE TITLE
mouse button 8, 9 and 12 mapping not working on dota 2 game

### ISSUE THREAD

**Issue by RichardAnthoyFalzini** [ValveSoftware/Dota-2#464]
I'm trying to get my RAT 5 mice working with custom actions associated to buttons 8,9 and 12.
Specifically, I would like to use these buttons in order to emulate some keyboards keys (x,c and z) in
Dota 2, I've tried two methods:
1) using xdotools (launched by xbindkeys) i launch xbindkeys with this .xbindkeysrc config file:

```
"xdotool key --clearmodifiers z"
    b:8
"xdotool key --clearmodifiers x"
    b:9
"xdotool key --clearmodifiers c"
    b:12

```

2) using imwheel whit this config file:
this is my startup.conf located in /etc/X11/imwheel

```
IMWHEEL_START=1
IMWHEEL_PARAMS='-b "0 0 0 0 8 9 0 0 12"'
```

and my imwheelrc located in /etc/X11/imwheel

```
".*"
None, Thumb1, z
None, Thumb2, x
None, ExtBt9, c
```

in both cases it works on all systems applications and in the main Dota page and in the settings,(in this case i used the mouse button to set c on item 3)
![2015-09-19_00001](https://cloud.githubusercontent.com/assets/7059594/9975509/b9a7eb5e-5ebe-11e5-907b-12c8a4c1b5b5.jpg)
but not in the game match if i try to press the mouse button nothing appens.
![2015-09-19_00002](https://cloud.githubusercontent.com/assets/7059594/9975510/bf9423ca-5ebe-11e5-8ccd-80af8dec323a.jpg)

P.S. the same configuration work perfectly on team fortress 2

system info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  4100 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series  

    Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x679a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3286 x 1080
    Primary Display Size: 20,51" x 11,54"  (23,50" diag)
                                            52,1cm x 29,3cm  (59,7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7925 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  76876 Mb
    Largest Free Hard Disk Block:  45186 Mb

Installed software:

Recent Failure Reports:



```

**Comment by gdrewb-valve** [comment]
Reborn only supports bindings for five mouse buttons (left, middle, right and mouse4/5).

**Comment by MaikuMori** [comment]
I have this issue as well (RAT9). I did the same debug steps as OP a while ago with similar results.

Overall I feel Dota's keybinding options are very limited in terms of mouse buttons and modifier keys. It would be nice improvement to at least have couple more mouse buttons.

**Comment by RichardAnthoyFalzini** [comment]
i know that dota only support mouse 4 & 5 but on my case, end i think that i'm not the only one. i need to use more button. 
I just need to know how dota take the imput from the keyboard.
i need help to find the reason that make  my configuration work on the menu and not in game,(there is some special process or thread that handle  input during game?).

**Comment by gdrewb-valve** [comment]
Reborn uses SDL for its input, so you can read over the SDL source code if you want to see specifically what it's doing.

**Comment by zeronote** [comment]
It will be useful to know which SDL version Reborn actually use in order to get the right source code and hopefully propose a patch.

**Comment by Tele42** [comment]
@zeronote Dota 2 should be using a pre-release of 2.0.4, just use git master as it should be very close, besides, the fix would go into SDL2 proper, not a fork.

**Comment by gdrewb-valve** [comment]
Note also that there is a limitation in Reborn itself as it doesn't have any handling beyond the five buttons I mentioned.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Mac/Linux issue.
