### ISSUE TITLE
Button does not work "cmd" and "alt" on MAC.

### ISSUE THREAD

**Issue by PUPAS** [ValveSoftware/Dota-2#465]
Hello friends. I'm sorry for the mistakes immediately, writing through Google translator.

Button does not work "cmd" and "alt" on MAC.

I always use the buttons in the game. DotA 2 everything was fine. After the reborn they simply are not working. I saw people complaining. But to solve the problem could not find.

Many buttons on mac just stopped working. Sometimes people play with Apple computers. Please help fix this error.

**Comment by PUPAS** [comment]
may have similar topics with the decision ...

**Comment by PUPAS** [comment]
:(

**Comment by danginsburg** [comment]
Is this in Exclusive Fullscreen?  Does it work in Desktop Friendly Fullscreen?

**Comment by PUPAS** [comment]
I'm sorry, I did not understand your answer. The buttons"fn", "ctrl", "alt", "cmd" do not work in any mode. As if they do not exist.

**Comment by gdrewb-valve** [comment]
Do not work for key bindings or do not work for any purpose?  You can't bind the Command key unless you enable that in the Advanced tab of the hotkey settings.  You can't bind Ctrl and Alt on their own.

**Comment by PUPAS** [comment]
I shot a video to show the essence.

https://www.youtube.com/watch?v=xsg3JIz5U4w

Before, I could use the CMD key and ALT in the inventory.

Now, when pressed, nothing happens. Neither the Russian nor English. Mac does not see them.

I hope you understand me)

**Comment by PUPAS** [comment]
> 12 окт. 2015 г., в 20:42, Drew Bliss <notifications@github.com> написал(а):
> 
> Do not work for key bindings or do not work for any purpose? You can't bind the Command key unless you enable that in the Advanced tab of the hotkey settings. You can't bind Ctrl and Alt on their own.


I shot a video to show the essence.

https://www.youtube.com/watch?v=xsg3JIz5U4w <https://www.youtube.com/watch?v=xsg3JIz5U4w>
Before, I could use the CMD key and ALT in the inventory.

Now, when pressed, nothing happens. Neither the Russian nor English. Mac does not see them.

I hope you understand me)


https://github.com/ValveSoftware/Dota-2/issues/465#issuecomment-146552690

**Comment by gdrewb-valve** [comment]
Ctrl and Alt cannot be bound on their own, that's by-design.

You can bind the Command key if you enable that in the Advanced page of the hotkey settings.

**Comment by PUPAS** [comment]
Please tell me how to press CMD.

I will add a shortcut to the settings. But it can only add to the Steam. Separately on a program DotA 2 is impossible. Promptness keys in the game is not working.

That's what is written on the apple:
"If the app you want to select doesn’t appear in the list, choose Other, then locate it using the Open dialog. Some apps may not allow you to set keyboard shortcuts.".

My printskrin

http://s017.radikal.ru/i418/1510/ae/6053479006f9.png

http://s013.radikal.ru/i323/1510/69/878662dcc312.png

Now use the keyboard shortcut for a program DotA 2 is impossible.
http://i056.radikal.ru/1510/3e/b359b15ee8f7.png

Previously, these buttons work. Why it can not be done in the Reborn.
It is a pity there is no old dota :(

**Comment by PUPAS** [comment]
closed topic .. but the question is not solved ..

**Comment by gdrewb-valve** [comment]
Can you be more specific?  Ctrl and Alt cannot be bound so the issue wouldn't stay open for that.  Command can be bound, as I mentioned above, so that seems to cover the original issue's question about binding keys?

**Comment by PUPAS** [comment]
I will be determined.
We have to work the button CMD. I tried to tie it, but it's impossible. I posted a screen shot on the screen.
Please tell me how to knit.
that's how it was before...

http://s019.radikal.ru/i604/1510/2c/1fc28df21d7d.png

**Comment by PUPAS** [comment]
0=)

**Comment by gdrewb-valve** [comment]
As I mentioned before: you can bind the Command key if you enable that in the Advanced page of the hotkey settings.

**Comment by PUPAS** [comment]
friend, you tried to do that? you have it work?
I put a photo in my post above. button enables to link only to Steam, but not for DOTA 2.

**Comment by gdrewb-valve** [comment]
Yes, it works fine for me.  You're sure you set the "Allow Windows / Command key to be bound" option in the Advanced section?

**Comment by Tele42** [comment]
@PUPAS The advanced section mentioned is in-game, not some OSX-specific window.
