### ISSUE TITLE
segfault when spawning

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#466]
hi,
After the update yesterday I and a friend of mine crashed the moment we joined the map after picking was over.

dmesg has to say the following:
[365855.036089] dota2[11514]: segfault at 7ffee3ac5573 ip 00007f934995e44a sp 00007ffee3abd5a8 error 4 in libc-2.20.so[7f93498db000+18d000]

**Comment by gxgani** [comment]
Same bug, https://github.com/ValveSoftware/Dota-2/issues/463

**Comment by danginsburg** [comment]
Should have been fixed by 9/19 update, duplicate of #463.  Closing.
