### ISSUE TITLE
[Mac] OS X: Game shortcuts doesn't work in another language

### ISSUE THREAD

**Issue by Shchvova** [ValveSoftware/Dota-2#467]
None of the abilities or other shortcuts work if keyboard layout is in other than english layout. This make game practically unplayable if you trying to chat in other than English. Potentially clone of #421

**Comment by danginsburg** [comment]
Duplicate of #473?  Does -input_button_code_is_scan_code on the command-line resolve the issue?

**Comment by gdrewb-valve** [comment]
Definitely a duplicate, closing.

**Comment by Shchvova** [comment]
Thanks @danginsburg. It works. Pity you have to do some magic for a game to work. Ty!
