### ISSUE TITLE
[OSX} Storm Spirit Permanent Lightining Form

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#468]
http://webm.host/06dcd/vid.webm

**Comment by Turmfalke2** [comment]
I have the same issue with linux.

**Comment by gxgani** [comment]
I've also observed pugna's "Life Drain" visual on Nightstalker permanently.

**Comment by gdrewb-valve** [comment]
This happens on Windows also and won't be tracked here.
