### ISSUE TITLE
[OS X] Game crashes on start.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#469]
This is the error message. Much sadness was had :(

Error
void CVfxStaticComboData::Unserialize(CUtlBuffer &, const CVfxProgramData *, VfxProgram_t, uint64, IRuntimeShaderCreateCallbacks *, ICompiletimeShaderCreateCallbacks *, bool)():
Expecting compressed combo data

**Comment by p-groarke** [comment]
Verifiying integrity of cache fixes this.

**Comment by danginsburg** [comment]
Glad to hear that fixed it, closing.
