### ISSUE TITLE
[OS X] Multiple Monitor Support

### ISSUE THREAD

**Issue by andrebower** [ValveSoftware/Dota-2#472]
In the old Dota 2 client it was possible to use one screen for gaming and the other screen for browsing etc. Now the game is minimized when switching to other screen OR if you disable the desktop friendly mode, the mouse can leave the game area even when focused (not playable with this setting). 

PLEASE fix that asap. Most annoying new "feature" of the new client.

**Comment by ArnaudAndre** [comment]
Have you already unchecked the "Desktop-friendly fullscreen minimizes on focus loss" option ?

Also, at least on linux, you can force dota to grab the cursor by clicking the top-left arrow to go to the menu then again to go back ingame.

**Comment by Tele42** [comment]
On linux, it's possible to set this launch option `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to override this behavior as well with any SDL2-based game.

**Comment by danginsburg** [comment]
@andrebower Are you seeing the mouse leave the game area during actual play or just on the main menu? I only see it leave the game area when in the main menu.  From my testing on a dual monitor Mac, if you set "Desktop Friendly Fullscreen" and then disable "Desktop friendly minimizes on focus lost" it gives you the behavior you would want.  The mouse is captured when in game and you can CMD-Tab and then use the other screen without the game minimizing.

![2015-09-21_00001](https://cloud.githubusercontent.com/assets/375707/9992438/24c53900-6040-11e5-8d97-4cf8c6d16791.jpg)

**Comment by andrebower** [comment]
i will verfiy my setting later that day and let you know!

**Comment by andrebower** [comment]
Well it does work with these settings but only if I apply them in an actual game! Configuring while in main menu did not work for both (menu and game)

**Comment by danginsburg** [comment]
Can you please provide exact repro instructions?  I am not seeing this behavior.

**Comment by andrebower** [comment]
Every time i start dota2 i have to apply the settings you mentioned while in a match to  prevent the mouse from leaving the monitor with the game. Maybe this is because after pressing apply and close+reopen settings the toggle button goes back to "Use monitors current resolution" ??

**Comment by andrebower** [comment]
Fixed with the latest patch! Thank you!!

**Comment by 7urkm3n** [comment]
Has anyone got a chance to make it ? I have been struggling almost 2-3yrs. Always turning off the 2nd mon...

**Comment by cerireyhan** [comment]
@danginsburg The mouse leaves the game area during the actual play. It's really annoying not being able to use the external monitor. Does anyone has a solution for this rather than mirroring screens and turning brightness off...

**Comment by 7urkm3n** [comment]
> @danginsburg The mouse leaves the game area during the actual play. It's really annoying not being able to use the external monitor. Does anyone has a solution for this rather than mirroring screens and turning brightness off...

@cerireyhan
if you find a solution, please share it :D.

**Comment by anthonyjdella** [comment]
I also have the same problem. This issue has been around for years :(
