### ISSUE TITLE
Keyboard problems on Dota 2 Reborn Linux version.

### ISSUE THREAD

**Issue by RSevumyan** [ValveSoftware/Dota-2#473]
Hello. I have some problems in Dota 2 Reborn. When i launch dota 2 in russian language, keyboard does not works except for numbers, space, return and other specific buttons. When i launch dota with english keyboard, Space button does not works, button 1 works as RETURN. It is serios problem for me, because i use 1 2 3 4 for spels. I have waiting for some patсh for two month, but it seams patch will not come. I really hope, you will help me. Thank you.
System info: OS Arch Linux
Linux kernel 4.1;
Xorg 1.17;
AMD Radeon 7670m.
P.S. On Dota 2 Source 1 everything works fine.

**Comment by lithiumcool** [comment]
Same problem here, but on MacOS Yosemite
Unable to use keyboard for spells when language is set to russian.
Have to change language to english and then it works fine.

Dota 2 Source 1 worked like a charm.

**Comment by Bugscz** [comment]
Same problem - Ubuntu 15.04 64bit. When I use Czech (QWERTZ) keyboard I cannot set up nor use number keys 123456789 below F keys on keyboard. Only 1 (+) key can be binded... When I switch to EN keyboard, number keys works great. This issue is since Dota 2 Reborn Linux client was released. Dota 2 Source 1 was working without this glitch.

**Comment by Asm0d3us** [comment]
Same problem on Arch Linux ( Linux 4.1)
Sometimes all keys except "Enter" no longer work until restart dota.

**Comment by Yunoo** [comment]
The same problem here. 
Keys are not working, except number ones. Even the language is not set to Russian, it still does not work. 

Debian GNU/Linux 8.2 (jessie)
Nvidia GeForce 560 Ti

Dota 2 Source worked before.

**Comment by Yunoo** [comment]
Any updates?

**Comment by Gordon01** [comment]
Same problem for me, and this is very serious.
Plz, fix!

**Comment by danginsburg** [comment]
Please try adding the following to your command-line and let me know if this fixes it for you: -input_button_code_is_scan_code

**Comment by lithiumcool** [comment]
@ danginsburg

I've added string you provided to Dota launch option command line and it fixed my problem.
Macbook Air 13^ El Capitan

Thank you!

**Comment by danginsburg** [comment]
OK, we will work on a better fix that automatically enables this mode, but for now please use this as a workaround.

**Comment by Gordon01** [comment]
OK, this workaround works for me perfectly, thank you, Valve :)

**Comment by Yunoo** [comment]
Gonna test it soon and write back. 
Thank you for your response!

UPDATE
Haven't had any problems afterwards. Shortcuts are working.

**Comment by gdrewb-valve** [comment]
The Oct. 16th makes this a UI option. In the Advanced section of key binding settings you can choose to have bindings be positional. Give it a try and if things are OK I'll close this out.

**Comment by Gordon01** [comment]
For me it worked, thank you.

**Comment by magist3r** [comment]
I reinstalled Dota2 from scratch yesterday. Now I have this bug again when loading game with non-US layout:( But now pressing '1' recognizes by game as RETURN in every chat (not only in game chat like before). -input_button_code_is_scan_code or enabling checkbox in settings doesn't change anything.

It is completely fresh install (with Steam reinstalled too).

"openSUSE Leap 42.1 (x86_64)" 
kernel 4.1.15-8-default
Xorg 11702000
X Window System: KWin
steam-runtime-release_2015-06-12
NVIDIA Corporation GeForce GTX 660 Ti/PCIe/SSE2, driver 4.5.0 NVIDIA 361.28

Please reopen.

**Comment by gdrewb-valve** [comment]
#453 is already open for key misrecognition. There's a request there from an SDL dev for more info so if you can post there that'd help.

**Comment by Third-Jaruda** [comment]
I have found a work around on this. I'm using PoL on Arch,

1.) Open Dota2 via steam (keyboard shouldn't work as expected).
2.) Return to desktop e.g. alt+tab. (I'm on gnome so prefer using the super key for this)
3.) Return to Dota2 e.g. by clicking on the running icon (I have plank so I click the wine icon there)
the keyboard should work from there (at least for me)

if you experience issues like the panel showing up after returning to Dota2, just click apply on the settings under ther video tab.

**Comment by ArnaudAndre** [comment]
Wait, you're running the windows version of dota 2 through wine ? That's not what this bug tracker is about at all. This bug is about the native linux build of the game.

**Comment by Lex4hex** [comment]
Same here. Ubuntu 16.04. input_button_code_is_scan_code works.

**Comment by Br1ght0ne** [comment]
Fedora 24, -input_button_code_is_scan_code worked for me too. Thanks!

**Comment by nickarchd** [comment]
same problem here. when i press  right shift or T or Y  the game crashes to desktop
i tried to remove my game and download again. still same problem though

Debian 8 Jessie

RAM: 8gb
X Window System: KDE
Kernel: 3.16
VGA: Geforce GTX 660 2gb

**Comment by kisak-valve** [comment]
Hello @ryonagana, the recent regression is being tracked at #1198, please use the open issue report.

**Comment by eelgaev** [comment]
Same here, Arch Linux, Latest Nvidia drivers.
KDE

**Comment by Arshavirus** [comment]
@danginsburg tx, it works for me, 10.12.6 sierra iMac mid 011

**Comment by ImanMh** [comment]
@danginsburg Thank you for the solution but it doesn't exactly fix the problem. 

Scenario: 
1.  Lunch the game with -input_button_code_is_scan_code flag and "Persian" language active in Ubuntu 18.
2.  Demo a hero, and you are going to see Persian characters on hero spell shortcuts (which is OK for me until this step. I'm talking about Q, W, E and ... shortcuts that are written at the corner of each spell icon).
3.  Change the language to the English and you can see that spell shortcuts are yet in Persian, but I expect them to be in English (How ever pressing Q, W, E and ... works correctly). 

PO. User Story
As a Linux Dota 2 user, I want key bindings and shortcut helpers to be change when ever I change my OS language input so I don't need to restart Dota 2 every time I lunch it with other inputs.
