### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by titeo1998** [ValveSoftware/Dota-2#474]
Please help me to fix this bug
Some skills and effects don't display as fully as usual. Such as: Bloodseeker 2nd skill, Pugna, Eye of Skadi effect, Phoenix,.. I am using Intel HD Graphics 4000

**Comment by titeo1998** [comment]
Here is the picture of this bug: http://postimg.org/image/dw1t5cp6n/
It was normal in the old Dota 2

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information.

**Comment by danginsburg** [comment]
As @Tele42 says, we are going to need more info to repro.  Please post your system information.

**Comment by titeo1998** [comment]
It was fixed when I updated my PC to Windows 10. Thank you!
