### ISSUE TITLE
[Linux] Game starts always on the right screen in multimonitor setup

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#475]
Dota 2 reborn always starts on the right screen (which is the primary in my setup) even when Steam Client is on the left screen.  And then it minimizes after the start.  Maximize will put it again on the right screen and I need to manually move it to the left. 
I use Debian stretch. Gnome-Shell 3.16. 
Dota 2 classic did always start on the screen where the steamclient was opended.

**Comment by danginsburg** [comment]
You can use -sdl_displayindex 1 to have it open on the other screen.

**Comment by ChrisLauinger77** [comment]
-sdl_displayindex 2 did the job - ty !

**Comment by danginsburg** [comment]
Great, closing.
