### ISSUE TITLE
[Linux] Please build SDL2 with IME supports

### ISSUE THREAD

**Issue by timxx** [ValveSoftware/Dota-2#476]
Since dota 2 reborn upgrade SDL2 to **2.0.4**, it should supports input method for **IBus**.
Just install the ibus dev and dbus dev headers, and run autogen.sh && configure, if all goes fine, you should see **Using ibus : YES**

I made a patch supports both fcitx and ibus: https://github.com/timxx/SDL-fcitx, (fcitx dev headers is needed).

P.S. There are some bugs on typing Chinese chars, sometimes it make the game window blinks. (I'm using fcitx)

**Comment by rcano** [comment]
fwiw, I'd love this too.

**Comment by timxx** [comment]
Hello, is any offical developer ever have a look at my post...
[Here is the one I built from ubuntu 12.04 x64 box](https://www.dropbox.com/s/md4uztomwdfeqmf/libSDL2-2.0.so.0?dl=0) (ibus, fcitx both enabled, set _SDL_IM_MODULE=fcitx_ to use fcitx), it works perfectly on ArchLinux (no screen flicker), the only problem is the input window can't following the cursor.
I hope you guys could have a test on it. Or building from my [SDL fork](https://github.com/timxx/SDL-fcitx) if you prefer.

**Comment by gdrewb-valve** [comment]
The lack of IME support is covered already by #50, closing this duplicate.

Note that Reborn needs substantially more work to get IMEs working than just turning them on in SDL, unfortunately.

**Comment by sunlinyao** [comment]
你成功了吗？是怎么编译的？
我使用
./configure
make && make install 
并且把生成的so文件拷贝到dota2和steam对应的目录，却没有效果。我用的是fcitx输入法，ubuntu14.4
我把网上别人编译好的，拷贝到dota2目录中，替换掉原来的，却进不了游戏
http://forum.ubuntu.org.cn/viewtopic.php?f=34&t=472753

**Comment by timxx** [comment]
@sunlinyao 
已经好久没玩dota2了额。。进入不了游戏的话，可能需要更新sdl2的代码了，你可以fork分支同步下上游代码重新编译一个试试；你发的链接那个也是我之前编译好上传的。。。
PS，编译需要安装fcitx开发头文件；运行加上SDL_IM_MODULE=fcitx才能用fcitx（默认是ibus）

**Comment by sunlinyao** [comment]
@timxx 我使用./configure --help 并没有--enable-fcitx，有一个--enable-ibus，所以我以为默认就支持，而且再configure的时候，没用提示find fcitx之类的，
另外。我发现每次我替换～/.steam/ubuntu12_32/libSDL2-2.0.so.0
这个文件，重新打开steam的时候就给我还原了，我也不知道steam启动是要校验libSDL2-2.0.so.0这个的版本还是md5值，所以就算支持fcitx也没用，
我尝试替换dota2目录下的libSDL2-2.0.so.0文件，但是发现使用你编译的 出现你这个帖子：http://forum.ubuntu.org.cn/viewtopic.php?f=34&t=472753中3L的那个提示。我自己编译的替换进去，启动过程中卡住，只能移动鼠标，最后没办法，切换控制台kill掉进程

**Comment by timxx** [comment]
@sunlinyao 
先跑./autogen.sh，需要出现**Using fcitx : YES**才能支持fcitx输入法。
至于卡的问题，就像前面说的，一般是dota2那边的sdl2更新了，我fork的那个分支没更新导致的；
只能替换dota2里面的，不能替换steam的，不然会自动还原。
话说在这里码中文不会给吐槽吧。。

**Comment by sunlinyao** [comment]
@timxx  没事，反正看这个帖子的大多数都懂中文，哈哈
那如果重新改的话，要改那些地方呢，或者大概是要改什么？

**Comment by planktonzp** [comment]
@timxx 快来拯救我于水火吧2333 现在Dota2的libSDL貌似吧一些零散的模块相关都整合进去了，编译的时候有什么要注意的么？或者怎么修改才好

**Comment by timxx** [comment]
@ruizhipeng 不好意思，目前没有dota2环境，不能帮上忙了。。
