### ISSUE TITLE
segfault when watching a replay

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#477]
hi,
I just opened a replay from my last match and the game directly crashed.

dmesg:
dota2[9083]: segfault at 128 ip 00007f8a47832241 sp 00007ffd84bdc150 error 4 in libengine2.so[7f8a4748c000+b01000]

**Comment by Turmfalke2** [comment]
The bug still exists, just had the crash again:
dota2[10042]: segfault at 128 ip 00007fad87d11241 sp 00007ffda3dcf3b0 error 4 in libengine2.so[7fad8796b000+b01000]

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information, in particular any relevant CrashIDs.

**Comment by gdrewb-valve** [comment]
Not Linux / Mac specific.  The larger team is aware of several replay crashes, they won't be tracked here.
