### ISSUE TITLE
segfault when changing ttys

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#478]
hi,
Every time I change to another tty (ctrl+alt+f2) and back again (ctrl+alt+f7) the game crashes.

dmesg:
[617507.189978] dota2[9992]: segfault at 7f4d5d9fe000 ip 00007f4d5360bf0d sp 00007fffa77f8200 error 6 in libparticles.so[7f4d53382000+4e9000]

Is there anyway I can help you with locating all these segfaults?

**Comment by Plagman** [comment]
Are you using the NVIDIA binary driver? There is a known issue with that driver, where buffers will get discarded on VT-switch and mode-switch, and pointers to previously-mapped buffers become invalid. I recommend reporting that bug on their forum instead.

**Comment by Turmfalke2** [comment]
Yes, I am using the nvidia binary driver, going to look into reporting that to them.

**Comment by danginsburg** [comment]
You can also try running with -gl_disable_buffer_storage in the Launch Options which disables the engine's use of persistently mapped buffers to see if it works around the issue.  As @Plagman said this is a driver issue though so I am going to close this issue.

**Comment by Tele42** [comment]
nVidia has been aware of this for a very long time. If my memory is correct (please check), nVidia's blob has no way to track or influence the various generic framebuffers available to drive a VT. As far as I know, there is no fix coming. nVidia would need to implement a framebuffer for the VT which shared information with the blob driving the gui and convinced people to exclusively using it with their blob (and potentially negating the reasons why users need VTs in their workflow. Last I heard nvidia was not planning on doing this.
