### ISSUE TITLE
[Mac] Graphical errors in game and menu, no audio, or sound

### ISSUE THREAD

**Issue by NotUrien** [ValveSoftware/Dota-2#481]
Visual effects appearing as checkered error boxes instead (even those in the menu/UI outside of the game). In one game Sand King (and placed observer wards) appeared to me as a bunch of orange letters that I couldn't click on. There isn't any specific thing I am doing the game just appears this way to me.

Controls aren't as responsive I have to order my hero 2-3 times for them to respond.

![5fhl08](https://cloud.githubusercontent.com/assets/14768840/10017978/82dcc99e-613b-11e5-8727-1e979af4b010.jpg)

You see that checkered box in the top left corner? It replaces all particle/visual effects (from spells or even the weather). Then there is the wireframes and those floating orange error text.

iMac OS X Yosemite (10.10.5)
3.2 GHz Intel Core i5
8 GB 1600 MHz DDR3
NVIDIA GeForce GTX 675MX 1024 MB

For the record, DotA 2 ran flawlessly before Reborn on the same exact system.

**Comment by danginsburg** [comment]
@NotUrien These symptoms strongly suggest a corrupt game cache.  The red wireframe is our error shader which loads when a .vcs file fails to open.  Please try doing Verify Local Game Cache from Steam.  If that does not fix it, please run with -con_logfile and post the contents of game/dota/console.log.

**Comment by NotUrien** [comment]
I verified game cache and just had my first reborn game, and it was completely bug free and ran perfectly. My hero <3

**Comment by danginsburg** [comment]
Great, closing.
