### ISSUE TITLE
[bug][linux][ubuntu 14.04][2015sep24]dota2 bot training hero skill level up may stuck guided notice window

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/Dota-2#484]
[bug][linux][ubuntu 14.04][2015sep24]dota2 bot training hero skill level up may stuck guided notice window.

platform: ubuntu 14.04 LTS 64bit latest.
steam: steam for linux stable version(non-beta) latest for linux. 64bit.

game: dota 2 for linux. latest update through steam client.

language: english.

=-=-==-=-=-=-=-=-=-=-=-=-=-=
how to reproduce the bug.

play dota 2 linux ver. with reborn DLC.( source 2 of course)

go "Learn " mode.

play guided hero play. now there are 3 heroes you can choose.

first 1 is Luna, 2nd is Sven, 3rd is fire mage girl Lina.

play Lina.

into the game, follow the in-game instruction. to the lower lane to fight your way...

then, you 'd get some in-game hero experience points through killing enemy Dire-faction normal mobs...

and your hero lina would level-up.

now here comes the issue.

when you level-up, if you click your mouse very quickly, you may encounter such an issue:
1. due to level-up your hero Lina would get one yellow button above the hero portrait... for your hero skill level-up +1 !
2. due to you clicking very fast, so you done that you clicked the skill up +1 button, and your mouse icon would becoming a "yellow cross" alike, for you to click a hero skill, to level up that skill. BUT, JUST AT THAT VERY TIME, YOU HAVE NOT CLICKED THAT SKILL ICON FOR SKILL LEVEL-UP YET.
3. AT THE SAME TIME, IF YOUR HERO TRIGGERED A IN-GAME GUIDED EVENT, which may cause your hero become invulnerable , and pause the game, and a prompt-up window would show up, and show some in-game teaching/ guidance info ,

in normal way, this in-game guidance window, would show with a "continue" button bottom right there, so you can click that button and go on your game...

BUT, in this special situation, due to you already clicked the Hero Level-up button, and going to level-up a hero skill, so in this special situation, the in-game guidance window would prompt-up and Pause the game! BUT, it would show WITHOUT a "continue" button bottom right there!

so, that means, in such way, due to you clicked the level-up button and going to level-up, and triggered an in-game guidance window event, then pause the game, the game pause would go PERMANENT, you cannot cancel this PERMANENT game pause, you have to terminate your game, and give up all your previous efforts... and retry from the game very beginning...

very frustrating though....

hope this bug would be fixed soon!

that is due to, in our country, the dota 2 community is not that "kind" or "tolerent" ...

guys scolding each other with very dirty words, just due to very very small trifles, e.g. team member muffs when onslaught...

so we have to practise a lot with bots 1st to get familiar with the game  ... but... looks like now new Dota 2 Reborn, its LEARN mode is not that good enough now ....

**Comment by gdrewb-valve** [comment]
Not a Mac / Linux specific issue, I'll pass this on to the larger team.

**Comment by gdrewb-valve** [comment]
This isn't Mac / Linux specific but I'll pass it on to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team says this should be fixed already or soon.
