### ISSUE TITLE
Font not displayed

### ISSUE THREAD

**Issue by sebyx07** [ValveSoftware/Dota-2#485]
I don't have the text displayed in console and the player names above the heroes. I have lubuntu 15.04 and nvidia driver: 346.59

**Comment by danginsburg** [comment]
Please try installing ttf-liberation font package.

**Comment by sebyx07** [comment]
yeah, now dota is broken http://i.imgur.com/dPVItWG.jpg
can't even pick. I purged the package but still broken

**Comment by danginsburg** [comment]
I am unable to repro this bug currently.

**Comment by gdrewb-valve** [comment]
@sebyx07, is this issue still active?

**Comment by sebyx07** [comment]
i reinstalled lubuntu, now it works

**Comment by gdrewb-valve** [comment]
Thanks, closing.
