### ISSUE TITLE
Notification when game ready and unpause

### ISSUE THREAD

**Issue by oxycoder** [ValveSoftware/Dota-2#487]
Their is no notification when another gamer un-pause the game.Also, in earlier version, the icon of dota2 will bouncing everytime match start or game unpause

**Comment by Vuccappella** [comment]
Notification does not make sound after last update and the icon does not bounce, it's really hard to tell you're in a game, only notification you get is in top right corner.

**Comment by gxgani** [comment]
Just a reminder that this enhancement is still not ported from source 1.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Mac/Linux issue.
