### ISSUE TITLE
[Linux] Custom game start button does nothing after initial mod install

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#49]
Started Dota.
Changed to fullscreen (maybe it is not important).
Downloaded the Overthrow mod.
The Overthrow start-match button became active, but submode choice buttons didn't appear.

Had to restart Dota to be able to enter an Overthrow match.

**Comment by gdrewb-valve** [comment]
I didn't have any problems doing this.  Have you tried other custom games?  Does it happen with all of them?

Can you post your system information?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
