### ISSUE TITLE
Crash on linux while watching live game

### ISSUE THREAD

**Issue by danslo** [ValveSoftware/Dota-2#490]
Gave the following, then crashed to desktop:

![screenshot from 2015-09-26 06-48-27](https://cloud.githubusercontent.com/assets/743661/10115887/b383f77a-641a-11e5-886d-7eb5b638097d.png)

**Comment by danginsburg** [comment]
@danslo Were you spectating directly connected?  How long were you in the game?  Any chance you were running with -con_logfile and could send game/dota/console.log.  Any additional details you have here would be helpful to us to try to repro this.

**Comment by Tele42** [comment]
For ease of lookup: CFlattenedSerializer::Decode array index out of range

**Comment by gdrewb-valve** [comment]
This isn't Mac / Linux specific so it won't be tracked here.
