### ISSUE TITLE
Dota 2 screen frozen on loading screen!!!!!!

### ISSUE THREAD

**Issue by nipunanoob** [ValveSoftware/Dota-2#492]
Platform: Mac
I have been facing this issue for weeks where i cant even get past loading screen on the new dota 2 reborn client when i was successful in doing so b4 but with severe fps drop in gameplay and menu screen compared to the old dota 2 client. I assume this might be the issue with my intel graphics card. i cant even cmd tab out of the client and have to reboot my computer 
Steps to reproduce this issue:-
1. Open dota 2 reborn client from your steam acc.
2. Stuck in loading screen.
MacBook Pro (13-inch, Late 2011)
processer: 2.4 GHz Intel Core i5
memory: 8 GB 1333 MHz DDR3
graphics card: intel HD Graphics 3000 512 MB
Please give me a solution to this problem at the earliest

**Comment by danginsburg** [comment]
Please post Steam -> Help -> System Information.  Your system is supported (in fact, it is one of the configs I test on here).  There have been a number of OpenGL driver bugs in previous versions of OS X.  Especially for your config I would recommend you update to OS X 10.10.5.  My guess is you are hitting one of the OpenGL driver crashes on HD 3000 we have encountered on OS X 10.9.x.

**Comment by gdrewb-valve** [comment]
@DeadlyGhast, is this issue still active?

**Comment by nipunanoob** [comment]
yes i still have this problem and my os is updated to 10.10.5. I tried
redownloading but to no avail

**Comment by gdrewb-valve** [comment]
OK, thanks for the update.  We don't have a repro for your issue here at Valve but we'll try and find one.  If you could post your full Steam system info that would give us a little more info.

**Comment by gdrewb-valve** [comment]
Checking in again to see if anything has changed.

**Comment by nipunanoob** [comment]
fixed

**Comment by gdrewb-valve** [comment]
Thanks, closing.
