### ISSUE TITLE
[LINUX]Empty boxes when hovering over heroes

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#493]
Arch 64 bit XFCE Compton.

When hovering over a hero the grey information box is empty with no text in it.  I will try to grab a screenshot later and post it.

Am I missing some dependencies?

**Comment by tilman2** [comment]
Can confirm. I'm seeing this with heroes I put in my profile "showcase".

Linux with AMD graphics card and Mesa driver here.

Actually this seems to be a duplicate of issue #54.

**Comment by danginsburg** [comment]
This is most likely a missing font package.  Is there a ttf-liberation package for your distro?  Try installing that and see if it fixes the issue.

**Comment by ghost** [comment]
Thanks! Installing ttf-liberation  resolves the issue. Closing and marking as resolved.

**Comment by milovanderlinden** [comment]
Confirmed. ttf-liberation does the trick. Thank you for the solution!
