### ISSUE TITLE
[Mac] Insane frame drops since latest patch

### ISSUE THREAD

**Issue by NotUrien** [ValveSoftware/Dota-2#495]
I'm not referring to 6.85, rather to the new that was released a few hours ago. 3 games so far, i would end up being practically frozen for minutes at time, and the longer the game progressed the longer the freezes. 

iMac OS X Yosemite (10.10.5)
3.2 GHz Intel Core i5
8 GB 1600 MHz DDR3
NVIDIA GeForce GTX 675MX 1024 MB

**Comment by danginsburg** [comment]
If you could run with -con_logfile and post game/dota/console.log from when this problem occurs there might be something in there we could use to track this down.  Also, please post full system specs from Steam -> Help -> System Information.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
