### ISSUE TITLE
[Linux] Alt not working after alt+tab

### ISSUE THREAD

**Issue by shnipsergey** [ValveSoftware/Dota-2#496]
Hi. My alt key stop to work in dota after alt-tab (not exactly first time I alt-tab from dota).
I use it for highlights on map and other stuff. Such things like Alt+Mouse1 stop to work, at the same time, alt+ctrl+MOUSE1 works well (it shows X on map).
I need to relaunch to dota to get Alt working as expected.

**Comment by glubsy** [comment]
I've started experiencing this bug since a few weeks ago... It didn't happen before.

The alt+mouse1 combo still works fine on the minimap, however it just doesn't work in the main view port.
