### ISSUE TITLE
(MAC OS) My Dota 2 wont launch!!!!! At all... Please help 

### ISSUE THREAD

**Issue by ingrid3dx** [ValveSoftware/Dota-2#497]
Hello guys!
Well, Im having this issue that my mac wont start the latest update from Dota 2, first it was preparing but no new window or whatever, then i update my mac to YOSEMITE now the Dota 2 window start but its all black and after few seconds this image pop up:

Error
bool
CAppSystemDict::LoadSystemAndDependencies(CUtlVectorCAppSystemDict::AppSystemRequest_t &,ErrorResponse_t)():
AppSystemDict: Error in Connect() of interface
'GameUI0011'!

ADDS
- I already did VERIFY INTEGRITY GAME CACHE countless times
- Already delete and reinstall Dota 2

Keep getting this message after all.

Please help me cause i dont know what to do!! :(((((((((

**Comment by ArnaudAndre** [comment]
The last patch was a few hours ago. What are you calling the "latest update" ? 6.85 ? the reborn switch ?
Your system specs may help (steam -> help -> system information).

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by ingrid3dx** [comment]
Sorry for delay, im without internet and using in my phone, cause dont have at home now ç_ç
But i was talking about the Reborn Switch.
I solved the problem in a weird way.
While not working for no reason i was trying to check everything so i notice the launch options, then i asked my friend what was about and he told me about those commands so i had the thinking "Im already on the shit so roll on it a bit more wont make any difference"
Here the commands i used exactly in the following order:
1-dx9(i think i put it twice)
2-dx11
3-high
Somehow it worked. I really dont know why and this was the first time using Launch Options.
At least i have the game back

**Comment by gdrewb-valve** [comment]
It's good that you have things working, but it's unclear why.  DX9 and DX11 don't exist on a Mac so those options won't do anything.

**Comment by ingrid3dx** [comment]
I know, for me was very weird but I was trying everything to make it work so I even cared if Mac has DX9/11. I was choosing commands randomly and checking
Either when Valve released Dota 2 Reborn Beta i could never experience cause was not even opening, then i update my Mac to OS X Yosemite 10.10.5, the window opened all black but was failing without entering to the menu. 
Just after setting those launch options(not touching any update in computer or downloading any new app that could cause problem) i could have Dota again and finally experience Reborn 

I have Macbook Pro (mid 2012), 
Processor 2.3GHz Intel Core i7
Memory 4GB 1600 MHz DDR3
Graphics NVIDIA GeForce GT 650M 512MB

In fact I'm very happy again joined my friends and training to don't be noob anymore hahahah
But its very weird the whole thing still!!!!
