### ISSUE TITLE
[OS X] Crash on first hit.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#498]
Happened at the very beginning, someone hit me. Playing Hardcore Ninja (jugg vs jugg).

2012 retina MBP, 650M

Process:               dota2 [4624]
Path:                  /Users/USER/Library/Application Support/Steam/*/dota2
Identifier:            dota2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [4621]
Responsible:           steam_osx [4064]
User ID:               501

Date/Time:             2015-09-27 03:08:08.836 -0400
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        7FB7401D-CACC-B0E4-83E7-07E82A294D71

Sleep/Wake UUID:       D81BF296-C2FE-469E-8642-ED1E39C574A9

Time Awake Since Boot: 82000 seconds
Time Since Wake:       26000 seconds

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 000000000b54e000-000000000b54f000 [    4K] r-x/rwx SM=COW  /Users/USER/Library/Application Support/Steam/*

Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libclient.dylib                 0x00000000a1d1f310 CSkeletonInstance::CalcWorldSpaceBones(ModelSkeletonData_t::BoneFlags_t) + 368
1   libclient.dylib                 0x00000000a1d1fbb3 CSkeletonInstance::CalcWorldSpaceAttachments() + 179
2   libclient.dylib                 0x00000000a1d07221 CSkeletonInstance::GetAttachment(unsigned char, matrix3x4_t&) const + 113
3   libclient.dylib                 0x00000000a1e88d3c CParticlesLibHost_Client::CalculateControlPointOrientation(CWeakHandle<InfoForResourceTypeIParticleSystemDefinition>, ParticleControlPoint_t const_, bool, ParticleControlPointOrientation_t_) const + 348
4   libclient.dylib                 0x00000000a2c2528e CParticleProperty::UpdateControlPoint(ParticleEffectList_t_, int, bool) + 334
5   libclient.dylib                 0x00000000a2c2432f CParticleProperty::AddControlPoint(CNewParticleEffect_, int, PARTICLE_EHANDLE___, ParticleAttachment_t, char const_, Vector, matrix3x4_t_, Vector) + 431
6   libclient.dylib                 0x00000000a2152c48 CDOTA_ParticleManager::SetParticleControlEnt(int, int, C_BaseEntity_, int, char const_, Vector, bool) + 584
7   libclient.dylib                 0x00000000a219782b CDOTA_ParticleManager::RunQueuedParticleManagerUpdateEnt(CDOTAUserMsg_ParticleManager_t const&) + 299
8   libclient.dylib                 0x00000000a21979d9 CDOTA_ParticleManager::RunQueuedMessages() + 377
9   libclient.dylib                 0x00000000a20bd24c C_DOTAGamerules::ProcessMessageQueue() + 284
10  libclient.dylib                 0x00000000a20bc38c C_DOTAGamerules::Update(EventClientUpdate_t const&) + 444
11  libclient.dylib                 0x00000000a1b76491 IGameSystem::DispatchEventInternal(int, void (IGameSystem::_)(GameSystemGenericEventType_t const&), GameSystemGenericEventType_t const&) + 129
12  libclient.dylib                 0x00000000a1d2915b void IGameSystem::DispatchEvent<EventClientUpdate_t>(EventClientUpdate_t const&) + 155
13  libclient.dylib                 0x00000000a1d0a584 CLoopModeGame::OnClientSimulate(EventClientSimulate_t const&) + 100
14  libengine2.dylib                0x000000000b6af5de CEvent_Dispatch<CEventIDManager_Default, EventClientSimulate_t, 1>::DispatchEvent(EventClientSimulate_t const&, bool, ISchemaBinding const_) + 174
15  libengine2.dylib                0x000000000b6af5de CEvent_Dispatch<CEventIDManager_Default, EventClientSimulate_t, 1>::DispatchEvent(EventClientSimulate_t const&, bool, ISchemaBinding const_) + 174
16  libengine2.dylib                0x000000000b6a9a9e CLoopTypeClientServer::Update(EngineLoopState_t const&, double, double) + 5518
17  libengine2.dylib                0x000000000b69ea64 CEngineServiceMgr::_MainLoop(double, double) + 1108
18  libengine2.dylib                0x000000000b69e5df CEngineServiceMgr::MainLoop(double, double) + 15
19  libengine2.dylib                0x000000000b695d40 MainLoop(SwapChainHandle_t___, PlatWindow_t___, InputContextHandle_t___) + 384
20  libengine2.dylib                0x000000000b696343 Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 819
21  libengine2.dylib                0x000000000b6965a0 Source2Main + 208
22  dota2                           0x000000000b54ed57 main + 535
23  libdyld.dylib                   0x00007fff8fe735c9 start + 1

**Comment by gdrewb-valve** [comment]
This isn't platform-specific, I've passed it on to the larger team.
