### ISSUE TITLE
[Linux] Game minimizes after start

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#499]
When I start the game it shows the loading screen - and after its loaded it just minimizes.
Need to ALT-TAB to bring it on top.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux testing-updates (sid) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.0-2-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 340.93
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1184
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                        53,1cm x 29,9cm  (60,9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: AV200

Memory:
    RAM:  7954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  53884 Mb
    Largest Free Hard Disk Block:  23859 Mb

Installed software:

Recent Failure Reports:
    Sun Sep 27 12:48:37 2015 GMT: file ''/tmp/dumps/crash_20150927143442_1.dmp'', upload yes: ''Discarded=1''

**Comment by bkacjios** [comment]
Yeah, this happens to me too. Usually after a little pop-up saying the game is unresponsive during the initial startup.

**Comment by ChrisLauinger77** [comment]
Yep - the inresponsive I have as well.

**Comment by Tele42** [comment]
If something is popping up and taking focus, then SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS's default behavior will minimize the game. Add `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to your launch options in the game properties to override

**Comment by danginsburg** [comment]
In addition to @Tele42's suggestion, you should also be able to uncheck "Desktop-friendly fullscreen minimizes on focus lost" as shown in the screenshot:

![2015-09-28_00001](https://cloud.githubusercontent.com/assets/375707/10136410/62cea75e-65c2-11e5-97e3-aa937afa027e.jpg)

**Comment by ChrisLauinger77** [comment]
the suggestion from @danginsburg was enough.
unchecking the "Desktop-friendly fullscreen minimizes on focus lost" brought the behaviour.
thx

**Comment by danginsburg** [comment]
Closing.
