### ISSUE TITLE
Mac: Spectating games is not possible.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#5]
http://i.imgur.com/oHwVufT.png

Not able to spectate games trough the Watch>Live menu tabs. Dota is stuck on Waiting For Game Data and there is no option to spectate the game.

Configuration: http://i.imgur.com/DJgP8tu.png

**Comment by computerquip** [comment]
I can confirm this to be the same for Linux.

**Comment by kon14** [comment]
Same on Linux

**Comment by radriaanse** [comment]
Here too on Linux. The match info does not load and there isn't a button to watch the match.

**Comment by gdrewb-valve** [comment]
This will be fixed in the next release.

**Comment by gdrewb-valve** [comment]
This should be resolved in the 6/25 update.

**Comment by radriaanse** [comment]
I can confirm this is working now.
