### ISSUE TITLE
MAC OS - Dota 2: Performance Warning after pressing "Play" on steam.

### ISSUE THREAD

**Issue by soleneedshelp** [ValveSoftware/Dota-2#500]
Having issues launching dota 2... "Performance Warning" message pops up after pressing play through steam. Error message: "Your system does not meet one or more of Dota 2's system recommendations for CPU, Memory or Video Card.

My system is.. 2.5Ghz, 4.0 GB, AMD Radeon HD 6750M.

It worked previously.. but ever since the change to REBORN, it stopped working.
I have done all the troubleshooting I could find through google search, reinstall, update mac, verify the cache etc....

Am I the only one with this issue? PLEASE HELP. 

Random Samoan guy. P.s "The Rocks Cousin" lol

**Comment by gear4s** [comment]
Do you perhaps use a 2011/2012 Macbook pro ?

**Comment by danginsburg** [comment]
What version of OS X are you on?  Your system spec looks fine.  Can you please post Steam -> Help -> System Information.  You will need OS X 10.9+ for Dota 2 Reborn

**Comment by gdrewb-valve** [comment]
Closing pending more info.
