### ISSUE TITLE
[Linux/Windows] Crashing using multiple system software

### ISSUE THREAD

**Issue by gear4s** [ValveSoftware/Dota-2#501]
I've tried this on specific and different system software (Gentoo Stage 3 Hardened (24/09) 64bit, Ubuntu 14.04 64bit, Debian 8 64bit, Arch 01/09 ; Windows 7 64bit, 8.1 64bit, 10 64bit) and they all crash while (waiting to load), during (waiting on other players) or before loading into the match. Currently not known how to reproduce, and happenes non-frequently (I don't reformat to test this, just have multiple different systems in seperate partitions)

All the Linux systems use kernel release 4.2.1 and were compiled locally (on their own partition, in their own session and with the default, downloadable compilers)

I'll post my specs as soon as I get onto one of my Linux systems as my BSD has pretty much nothing to get information with (I've stripped that ability)

I have no idea if this affects Mac/book users but if it affects you and you use a Mac/book then post here and I'll change the title to include it.

**Comment by danginsburg** [comment]
@gear4s If you could post a crashdump from one of these cases that would be helpful in narrowing it down.

**Comment by Tele42** [comment]
This is potentially a black hole of unrelated crashes. It is discouraged to have multiple users combine their issue reports unless the details are an exact match. Just typing it crashed without further detail is not a match.

It's interesting that you have so many OS installs on the same system, and might hint at an OS-independent hardware quirk that needs to be worked around, or not.

**Comment by gear4s** [comment]
Well, it hasn't crashed since the latest update (Windows) but on Linux I get significant frame drop times when doing some things (using abilities, blinking, sometimes just standing their watching a fight)

If any more crashes do occur I'll post the crashdump.

here's a gist of my BIOS, baseboard, processor, memory, cache and GPU information:
https://gist.github.com/gear4s/1cf4b2032500f411de4c

**Comment by danginsburg** [comment]
Glad to hear the crash is fixed.  For the frame drop issues on Linux, please try using Catalyst 15.9 on Linux if you are not already.  I'm going to close this one out since the original issue sounds like it is resolved.

**Comment by gear4s** [comment]
I just had a crash on Linux (Ubuntu), no access violation log today or the past month-ish, nor entry in debug.log
