### ISSUE TITLE
Missing hero portrait images in main interface

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#502]
The tile on the front page that shows stats about my last match is missing the hero portrait. It shows the hero name, stats and item icons, but the box where the hero image is supposed to be is empty.
The same issue can be seen when I go to my profile and click on the "All-hero challenge" tab. Stats are shown correctly, but the hero portrait for the current hero is just a black box (all other hero portraits below are shown though).

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  nds_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2486111 Mb

Installed software:

Recent Failure Reports:
    Mon Sep 28 10:31:49 2015 GMT: file ''/tmp/dumps/crash_20150928123020_1.dmp'', upload yes: ''Discarded=1''
    Mon Sep 28 10:32:37 2015 GMT: file ''/tmp/dumps/crash_20150928123157_1.dmp'', upload yes: ''Discarded=1''

**Comment by danginsburg** [comment]
Duplicate of #54?  Or is this something else?

**Comment by phoerious** [comment]
Not sure, but it definitely is a duplicate of issue #491 which is linked to that issue but which for some reason I couldn't find via the search function.

**Comment by danginsburg** [comment]
Thanks, closing as duplicate of #491.
