### ISSUE TITLE
[Linux] Incorrect timeleft on penalty

### ISSUE THREAD

**Issue by loisgomez** [ValveSoftware/Dota-2#504]
Linux version of the game is showing wrong timeleft when a match is not accepted. Its showing 2+ hours intead of the real penalty which is 10 min.

![captura de pantalla de 2015-09-29 10 24 14](https://cloud.githubusercontent.com/assets/3087254/10161538/19f86338-66a5-11e5-9dca-e34c224659be.png)

**Comment by gdrewb-valve** [comment]
This isn't platform-specific and will be handled by the larger team (it may have been fixed already), closing.
