### ISSUE TITLE
[Linux] Accepting match while watching not working 

### ISSUE THREAD

**Issue by loisgomez** [ValveSoftware/Dota-2#505]
Scenario:
Watching a game while searching for a game. 

Issue:
Accepting a game match while watching doesnt work. Have to go back to the main menu to really accept the match.

**Comment by chrylis** [comment]
Confirmed. I note that the dialog that pops up is the _old_ accept/reject dialog, with the 3D buttons, rather than the new one with the flat colored buttons. This is particularly nasty since clicking "accept" dismisses the dialog, and you can still get penalized for FTR.

**Comment by gdrewb-valve** [comment]
This isn't Mac/Linux specific and has been passed on to the larger team.
