### ISSUE TITLE
Mac: Crashes while watching replays/spectating in game.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#506]
Game just crashes randomly when spectating/watching replays, this is the error I get https://i.imgur.com/XZELcV7.png after which I have to terminate the application. This isn't new, happened in the last few patches as well I just didn't get the error, either I was too slow so I couldn't clip it or it didn't show . iMac OSX , late 2012.

**Comment by Tele42** [comment]
Possibly related to #490.

**Comment by danginsburg** [comment]
This is a duplicate of #490.  Could you get us a match ID where this occurred?  We are still working to repro this.

**Comment by Vuccappella** [comment]
Sure, Match 1830314782

**Comment by danginsburg** [comment]
Thanks, attempting to repro now on the replay.  We are definitely looking into this and know it is an issue.

**Comment by gdrewb-valve** [comment]
This isn't platform-specific and won't be tracked here, but the larger team believes this has been fixed.
