### ISSUE TITLE
[Mac]Cannot change display resolution in Desktop-Friendly Fullscreen Mode

### ISSUE THREAD

**Issue by VoZZZup** [ValveSoftware/Dota-2#507]
I play DotA 2 on MacBook Pro with Retina-display and using resolution 1280x800 for better performance. But in Desktop-Friendly Fullscreen I cannot set any resolution but 2560x1600. I can use 1280x800 in Exclusive Fullscreen but cannot switch between apps using it. Please, fix Desktop-Friendly Fullscreen Mode, at Source 1 it works perfectly.

**Comment by danginsburg** [comment]
When you say that you "cannot set any resolution but 2560x1600", can you be more specific?  Is that the only resolution you are seeing available in any of the dropdown boxes?  Or, are you having some problem when you set the resolution?  What is your actual desktop resolution set to?

**Comment by VoZZZup** [comment]
@danginsburg After every time when I'm trying to choose "use advanced settings" and applying changes, nothing changes and next time radio button is in "current resolution" again. 
<img width="546" alt="screenshot 2015-10-01 17 51 45" src="https://cloud.githubusercontent.com/assets/14901399/10224182/7b7be85c-6865-11e5-9166-960e93348ff9.png">

**Comment by gdrewb-valve** [comment]
Can you show what the settings look like just before you hit apply?  This may be something related to the Retina pixel doubling where the game thinks that 1280x800 is the monitor resolution.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
