### ISSUE TITLE
[Linux] Frame drops using same system as Windows install

### ISSUE THREAD

**Issue by gear4s** [ValveSoftware/Dota-2#509]
(related: [issues/501](https://github.com/ValveSoftware/Dota-2/issues/501))

I've been experiencing heavy frame drops ever since 6.85 dropped. I'm using the 15.20.3 driver package (no problems since pre-6.85 besides the crashing)

**Comment by gdrewb-valve** [comment]
How are things running these days?

**Comment by gear4s** [comment]
seems to run fine (no frame drops) but it just crashes while loading in now (reconnecting doesn't crash)

**Comment by gdrewb-valve** [comment]
Is there already an issue open for that?  If not you should open one with whatever crash information you have (failure report IDs from Steam system info, console output, whatever you have).  I'm going to close this since the frame drops no longer happen.
