### ISSUE TITLE
Wrong team icons on replay summary

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#510]
When looking at the summary screen of a tournament match and then at the summary of a normal pub match, the teams get the team icons of the tournament parties.

Steps to reproduce:
1. Go to Watch->Replays and click on one of the popular tournament matches
2. Go back and click on any of your friend matches or search for a pub match ID

Result:
When looking at the pub game, the two factions get the team icons of whatever tournament match your looked at before (e.g. Vega Squadron and Alliance).

**Comment by gdrewb-valve** [comment]
This isn't platform-specific, I passed it on to the larger team.  They've already looked and think they have a fix.
