### ISSUE TITLE
Linux (Ubuntu 14) In-game text not rendering properly (white boxes)

### ISSUE THREAD

**Issue by kemosabe73** [ValveSoftware/Dota-2#511]
Upon updating to the reborn client my in-game font is only white boxes, should I just wait for an update or is there already a fix for this?

P.S. I've already installed Liberation package and it is still not rendering properly.

**Comment by danginsburg** [comment]
Please post your full system information Steam -> Help -> System Information.  My guess would be you have an old version of mesa as there was a bug that would cause that, but without seeing your system details or a screenshot I can't be sure.

**Comment by kemosabe73** [comment]
Thanks for your reply. Here is the link to my screenshot.

https://goo.gl/photos/YE9kFHNXwJi5y7Ls5

**Comment by danginsburg** [comment]
You are on mesa 10.3.2 and this is a known issue there.  You can update to a newer version of mesa using the xorg-edgers ppa or oibaf ppa if you are more daring.  Please see the comments in issue #417 for further info on how to install from xorg-edgers.  Closing this one as a duplicate.
