### ISSUE TITLE
Color clamping while stepping back in paused replays (minor)

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#513]
This is surely just a cosmetic issue, but should also be easy to fix.
When pausing a replay and then using the 10s back button to skip back in time several times, screen colors are added up so effects get blown out until almost everything is white. When continuing playback, colors revert back to normal.

![dota2-replay-clamp](https://cloud.githubusercontent.com/assets/911270/10224844/3900268c-6860-11e5-8ca2-dc315652b0cc.jpeg)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  nds_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2320151 Mb

Installed software:

Recent Failure Reports:
    Thu Oct  1 10:24:50 2015 GMT: file ''/tmp/dumps/crash_20151001112016_1.dmp'', upload yes: ''Discarded=1''

**Comment by danginsburg** [comment]
I haven't been able to repro this bug.  Still happening with the latest version of Dota 2?  If so, could you post a match ID and a time to pause at and 10s skip at that reproduces the bug.  It also might help if you post your game/dota/cfg/video.txt.

**Comment by phoerious** [comment]
I can reproduce it with every replay at every position.
The important thing is that you must not continue playback in between
steps as that resets colors to normal.
When you step back quickly, Dota continues playback automatically. So
you have to do it slowly so that the game stays paused at all times.
After two or three steps you'll notice that spell effects get blown out.
The extreme example above is like 10-15 steps back or so (a bit
academic, but just for demonstration purposes).

I don't know on which system you tried to reproduce this issue, by maybe
it's an OpenGL-only issue (testing on Chakra Linux).

My video.cfg:

"video.cfg"
{
        "VendorID"              "4318"
        "DeviceID"              "5121"
        "setting.cpu_level"             "1"
        "setting.mem_level"             "2"
        "setting.gpu_mem_level"         "2"
        "setting.defaultres"            "2560"
        "setting.defaultresheight"              "1440"
        "setting.gpu_level"             "3"
        "setting.version"               "1"
        "setting.knowndevice"           "1"
        "setting.fullscreen"            "0"
        "setting.coop_fullscreen"               "0"
        "setting.nowindowborder"                "1"
        "setting.mat_vsync"             "1"
        "setting.fullscreen_min_on_focus_loss"          "1"
        "setting.dota_cheap_water"              "0"
        "setting.r_deferred_height_fog"         "1"
        "setting.r_deferred_simple_light"               "1"
        "setting.r_ssao"                "1"
        "setting.cl_globallight_shadow_mode"            "2"
        "setting.r_dota_fxaa"           "1"
        "setting.r_deferred_additive_pass"              "1"
        "setting.dota_portrait_animate"         "1"
        "setting.r_deferred_specular_bloom"             "1"
        "setting.r_deferred_specular"           "1"
        "setting.dota_ambient_creatures"                "1"
        "setting.r_texture_stream_mip_bias"             "0"
        "setting.r_dota_normal_maps"            "1"
        "setting.r_dashboard_render_quality"            "1"
        "setting.shaderquality"         "1"
        "setting.recommendedheight"             "2160"
        "setting.mat_viewportscale"             "1.000000"
        "setting.r_fullscreen_gamma"            "2.200000"
        "setting.useadvanced"           "0"
        "setting.aspectratiomode"               "1"
}

**Comment by danginsburg** [comment]
@Manko10 Is this still happening?  I never had any luck repro'ing the issue.

**Comment by phoerious** [comment]
Right now I can't reproduce it anymore. But I can reproduce another funny issue instead. When skipping back in 10s steps while the game is paused, the green selection rings around heroes stay on the map. So after several iterations the map is cluttered with green rings. It's not as easy to reproduce, though, because skipping back very often resumes playback for some reason, which redraws the map and therefore gets rid of the green rings.

**Comment by danginsburg** [comment]
The issue with selection rings has been reported to the larger team.  This is not a Linux/Mac issue so closing it out here.
