### ISSUE TITLE
Opening Dota 2 from Gnome shows "not responding"

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#516]
I always get a window not responding on Gnome when opening Dota 2.
It happens all the time since Dota 2 Source 1. Any idea about whether it's Gnome or Dota 2 issue? Filed a bug in gnome bug tracker already:
https://bugzilla.gnome.org/show_bug.cgi?id=755979

**Comment by budimanjojo** [comment]
They just responded that Dota 2 should do something about _NET_WM_PING. You guys should read the 3rd comment. https://bugzilla.gnome.org/show_bug.cgi?id=755979#c3

**Comment by Tele42** [comment]
Related to #499.

**Comment by budimanjojo** [comment]
I don't think so. That bug is about the not responding window overlaping Dota 2, but not about what causing the window to come out. Maybe devs from Valve can do the fix the Gnome team shows in the link?

**Comment by Tele42** [comment]
Right, I didn't claim this was a duplicate, just related.

**Comment by MaikuMori** [comment]
I'm having this very same issue. I'm also using Gnome 3. When I start the game **every time** there is "Not responding" dialog showing up. The game itself transitions from the black screen to start screen just about right after the Gnome dialog comes up. If you just dismiss the dialog the game is working fine.

As mentioned previously this seems to be the game client not sending/responding to window events fast enough while loading assets which causes Gnome to think that it's unresponsive.

**Comment by gdrewb-valve** [comment]
Reborn uses SDL and doesn't directly respond nor implement any XWM stuff, but I can pass this on to the SDL devs.

**Comment by MaikuMori** [comment]
I was looking trough logs for another issue, but I stumbled on this:

```
Oct 12 21:05:37 Archpc gnome-session[976]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400217 (Dota 2)
```

I bet this is the problem.

**Comment by gdrewb-valve** [comment]
Were those general logs?  Those come up for the Steam client itself.

**Comment by MaikuMori** [comment]
Those are `gnome-session` logs from `journalctl --user`. If you look at the very end it says `(Dota 2)` so it must be Dota 2 window generating it.

**Comment by gdrewb-valve** [comment]
OK, SDL must have the same problem as the Steam client.

**Comment by MaikuMori** [comment]
Maybe it's not related. Just noticed it's `_NET_ACTIVE_WINDOW` instead of `_NET_WM_PING` which was mentioned before. When I posted I taught it was the same event/message name.

**Comment by budimanjojo** [comment]
So should I post a bug report on SDL or they already know it?

**Comment by gdrewb-valve** [comment]
I've already started a conversation with them.

**Comment by budimanjojo** [comment]
Nice, would like to have some news updates from you later :)

**Comment by gdrewb-valve** [comment]
A future update will opt out of _NET_WM_PING so that these notifications should go away (the app will still hitch on startup, it's just turning off the notifications).

**Comment by budimanjojo** [comment]
That's good enough for me. Thanks gdrewb

**Comment by budimanjojo** [comment]
It's still happening after the latest 16/10 update

**Comment by gdrewb-valve** [comment]
The change didn't make the Oct. 16th update, it'll come in the next one.

**Comment by budimanjojo** [comment]
Confirmed it's not showing the notification again after the latest update. Closing, thanks gdrewb.
