### ISSUE TITLE
double output in the console

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#518]
hi,
I have noticed that pretty much everything printed to the console is printed twice:

![double_console](https://cloud.githubusercontent.com/assets/5174562/10262289/7ed147fa-69c2-11e5-8566-adc8e93ea5cb.png)

**Comment by gdrewb-valve** [comment]
Can you post your Steam system info? Does this happen every time?  When does it start happening?

I just tried this on my Linux machine and up through starting a bot match I didn't see any doubling of output.

**Comment by Turmfalke2** [comment]
hi,
here is the steam system information: http://pastebin.com/6Rvbtywj  my window manager is herbstluftwm, I think it is only claiming to be compiz for java compatibility.

Right now I am unable to reproduce this bug (steam/dota is down) I will try again later.

**Comment by gdrewb-valve** [comment]
Closing until we have a repro.

**Comment by Turmfalke2** [comment]
@gdrewb-valve It happened again, played a few games of solo ranked and at the end found that I once again triggered the bug.

The only new information is that the bug temporally fixed it self when I started spectating a game.

Any idea how we could get a better repo than "play a few games"?

**Comment by gdrewb-valve** [comment]
Other than specifically experimenting with playing games and seeing when it happens I don't have a lot of concrete suggestions.

**Comment by Turmfalke2** [comment]
ok, I just reproduced it again.
1. started dota
2. checked, console is not bugged
3. started searching for a ranked match
4. checked console is not bugged
5. accepted and waited for rest to load in
6. console is bugged and outputs twice

**Comment by gdrewb-valve** [comment]
Thanks, I'm also checking with the larger team.

**Comment by Turmfalke2** [comment]
@gdrewb-valve found something that is likely related to it. If I start dota and type and incorrect command in the console such as "sdf" there is no response. If however the bugged already triggered I get "unknown command: sdf" twice.
Maybe that helps with figuring where the error is located.

**Comment by gdrewb-valve** [comment]
Interesting, I've passed this on.

**Comment by gdrewb-valve** [comment]
I think I found the underlying problem and a fix will be in a future update.

**Comment by Turmfalke2** [comment]
todays update did not fix this

**Comment by gdrewb-valve** [comment]
I'll post when it makes it out.

**Comment by gdrewb-valve** [comment]
I believe the update just went out.

**Comment by Turmfalke2** [comment]
hi @gdrewb-valve ,
I can confirm the bug is mostly fixed, the only thing that is a bit strange is that in the main menu I still get no response for issuing a wrong command, but when I am in a game I get the "unknown command" message.
No idea what expected behaviour for this is.

**Comment by gdrewb-valve** [comment]
It's expected that you won't get any message when there is no game active.  It's a little strange but in that case the commands have nowhere to go so they are simply ignored.  I believe that's the way it has been for a very long time and I don't think the larger team is considering changing it
