### ISSUE TITLE
Dota 2  on linux

### ISSUE THREAD

**Issue by Mathiasbang** [ValveSoftware/Dota-2#520]
I have already downloaded it, but whenever I go to start it it says "Check GLExtensions(): Required OpenGL extension 'GL_ARD_separate_shader_objects' is not supported. Please update your OpenGL driver". I can't find anything online on how to update my GL driver and have tried to use the Linux registry to do it but it isnt in there. Anyone know what I can do?

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.2 Rafaela (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-38-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Broadwell x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x1616
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Broadwell HDMI

Memory:
    RAM:  7888 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  231764 Mb
    Largest Free Hard Disk Block:  199830 Mb

**Comment by schoening** [comment]
I had the same issue with my amd radeon chip. So I switched to the proprietary drivers. Perhaps that can help you.

**Comment by Tele42** [comment]
Proprietary drivers do not exist for Intel graphics, making that suggestion irrelevent.  Separate shader objects got added to mesa in 10.2.0, which was released June 6, 2014. As for update instructions, look for instructions for Ubuntu 14.04, which is what Linux Mint 17 is based on.

**Comment by Mathiasbang** [comment]
Ty for the answers. I would love to update my gl drivers but i cannot figure out how to do so. It all seems gibberish to me. 
Can anyone link something to me, so i can do it? I duno how to update mesa and i dunno which mesa i should be gettin:-/

**Comment by danginsburg** [comment]
I don't personally run Linux Mint so I'm not sure what the best update procedure is.  You could try the xorg-edgers PPA http://www.ubuntuupdates.org/ppa/xorg-edgers or the Intel Graphics Installer for Linux https://01.org/linuxgraphics/downloads/intel-graphics-installer-linux-1.2.0.  I would recommend mesa 10.6+.  I'm going to close this out since it is a driver update issue, but people can feel free to continue to comment to give mesa update advice for Linux Mint.
