### ISSUE TITLE
stuck at loading screen dota 2 reborn

### ISSUE THREAD

**Issue by felipinho-lima** [ValveSoftware/Dota-2#521]
I have this problem after upgrade the 01/10/2015.
I can't see the match and don't play anyone mode.
Pls help.

**Comment by danginsburg** [comment]
There is not enough information here for us to help you.  Can you post Steam -> Help -> System Information?  It also would be helpful if you run with -con_logfile and post the contents of game/dota/console.log.

**Comment by felipinho-lima** [comment]
Ok. My bad. I forgeted the post it.
Followed the log.

In the network 162.254.XXX.XXX i can play but the ping it's very high more our less 203ms in the network 208.78.XXX.XXX i have the problem "high packet loss detected flow incoming".

---

CreateDevice: Requested DX level 110, clamped to DX level 97

## PIX was NOT detected.

Path ID:             File Path:
ADDONS               "E:\Steam\steamapps\common\dota 2 beta\game\dota_addons\" 
CONTENT              "E:\Steam\steamapps\common\dota 2 beta\content\dota_brazilian\" 
CONTENT              "E:\Steam\steamapps\common\dota 2 beta\content\dota\" 
CONTENT              "E:\Steam\steamapps\common\dota 2 beta\content\core\" 
CONTENTADDONS        "E:\Steam\steamapps\common\dota 2 beta\content\dota_addons\" 
CONTENTROOT          "E:\Steam\steamapps\common\dota 2 beta\content\" 
DEFAULT_WRITE_PATH   "E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
DEFAULT_WRITE_PATH   "E:\Steam\steamapps\common\dota 2 beta\game\dota\" 
EXECUTABLE_PATH      "E:\Steam\steamapps\common\dota 2 beta\game\bin\win64\" 
EXECUTABLE_PATH      "e:\steam\steamapps\common\dota 2 beta\game\bin\" 
GAME                 "E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
GAME                 "E:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk" (vpk) E:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk
GAME                 "E:\Steam\steamapps\common\dota 2 beta\game\dota_brazilian\" 
GAME                 "E:\Steam\steamapps\common\dota 2 beta\game\dota\" 
GAME                 "E:\Steam\steamapps\common\dota 2 beta\game\core\" 
GAMEBIN              "E:\Steam\steamapps\common\dota 2 beta\game\dota\bin\win64\" 
GAMEBIN              "E:\Steam\steamapps\common\dota 2 beta\game\dota\bin\" 
GAMEBIN              "E:\Steam\steamapps\common\dota 2 beta\game\core\bin\win64\" 
GAMEBIN              "E:\Steam\steamapps\common\dota 2 beta\game\core\bin\" 
GAMEROOT             "E:\Steam\steamapps\common\dota 2 beta\game\" 
MOD                  "E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) E:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
MOD                  "E:\Steam\steamapps\common\dota 2 beta\game\dota\" 
PLATFORM             "E:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk" (vpk) E:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk
PLATFORM             "E:\Steam\steamapps\common\dota 2 beta\game\core\" 
SHADER_SOURCE        "E:\Steam\steamapps\common\dota 2 beta\src\shaders\dota\" 
SHADER_SOURCE        "E:\Steam\steamapps\common\dota 2 beta\src\shaders\core\" 
SHADER_SOURCE        "E:\Steam\steamapps\common\dota 2 beta\src\shaders\dota_addons\" 
SHADER_SOURCE        "E:\Steam\steamapps\common\dota 2 beta\src\shaders\dota_core\" 
SHADER_SOURCE_MOD    "E:\Steam\steamapps\common\dota 2 beta\src\shaders\dota\" 
SHADER_SOURCE_ROOT   "E:\Steam\steamapps\common\dota 2 beta\src\shaders\" 
command line arguments:
-steam -novid -con_logfile
Physics Console Communications is not initialized
Game supporting (2) split screen players
Sound Initialization: Finish, Sampling Rate: 44100
ILocalize::AddFile() failed to load file "resource/keybindings_brazilian.txt".
ILocalize::AddFile() failed to load file "resource/vgui_brazilian.txt".
Failed to load localization file for language brazilian, ignoring
ILocalize::AddFile() failed to load file "resource/vgui_brazilian.txt".
CEntitySystem::BuildEntityNetworking (parallel build of server) took 290.276 msecs for 613 out of 630 classes
Requesting page 1 of items
Requesting page 1 of items
CEntitySystem::BuildEntityNetworking (parallel build of client) took 353.004 msecs for 619 out of 638 classes
Checking AUTO DLC
Could not load file resource/gamemenu.res. Using empty GameMenu keyvalues.
File error loading resource header "panorama/images/textures/startup_background_logo.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_music.vsndevts_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_stingers.vsndevts_c" (Error: ERROR_FILEOPEN)
No valid vcs file found for shader ssao_convert_depth.vfx

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_convert_depth.vfx for material materials/dev/ssao_convert_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_convert_depth.vfx for material materials/dev/ssao_convert_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_convert_depth.vfx for material materials/dev/ssao_convert_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_convert_depth.vfx for material materials/dev/ssao_convert_depth.vmat!
No valid vcs file found for shader ssao_downsample_depth.vfx

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_downsample_depth.vfx for material materials/dev/ssao_downsample_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_downsample_depth.vfx for material materials/dev/ssao_downsample_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_downsample_depth.vfx for material materials/dev/ssao_downsample_depth.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_downsample_depth.vfx for material materials/dev/ssao_downsample_depth.vmat!
No valid vcs file found for shader ssao_scalable_ambient_obscurance.vfx

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_scalable_ambient_obscurance.vfx for material materials/dev/ssao_scalable_ao.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_scalable_ambient_obscurance.vfx for material materials/dev/ssao_scalable_ao.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_scalable_ambient_obscurance.vfx for material materials/dev/ssao_scalable_ao.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_scalable_ambient_obscurance.vfx for material materials/dev/ssao_scalable_ao.vmat!
No valid vcs file found for shader ssao_bilateral_blur.vfx

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_bilateral_blur.vfx for material materials/dev/ssao_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_bilateral_blur.vfx for material materials/dev/ssao_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_bilateral_blur.vfx for material materials/dev/ssao_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader ssao_bilateral_blur.vfx for material materials/dev/ssao_blur.vmat!
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_strong.vmat!
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_med.vmat!
No valid vcs file found for shader gaussian_bloom_blur.vfx

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!
config file 'cfg/game_convars.vcfg' is overriding an archived convar 'snd_ducktovolume' with value '1'. User will not be able to change this value!
SwitchToLoop levelload requested:  id [1] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
Idle (levelload)
Allocating new transform texture!
Writing configuration for slot 0
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [1] addons []
name[ 0 ] changing from 'unnamed' to 'FelipinhO'
name[ 0 ] changing from 'FelipinhO' to 'FelipinhO'
Loaded default network config file.  Loaded revision 25 OK
Loaded cached network config file.  Data contains revision 25, not newer than current revision 25; ignoring.
SV:  maxplayers set to 1
Initializing script VM...
...done
Network configuration revision changed 0 -> 25
CL:  Adding Prequisite CWaitForGameServerStartupPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
Got network config from CDN.  Data contains revision 25, not newer than current revision 25; ignoring.
SV:  Spawn Server: <empty>
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  PS_SATISFIED CWaitForGameServerStartupPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  Sending connect to loopback
***\* Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
***\* Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
SV:  Sending S2C_CHALLENGE [2344710574 auth 2] to loopback
CL:  Received S2C_CHALLENGE [2344710574 auth 2] from loopback
CL:  Sending C2S_CONNECT [42 protocol 2344710574 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 42 2344710574 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'FelipinhO' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 6914
Server Number: 1
Initializing script VM...
...done
Mismatch between client C_DOTAPlayer and server CDOTAPlayer
warning: (root)::m_vecClientQuickBuyState exists only in client
CL:  PS_SATISFIED CLoadStartupResourcePrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CLoadSpawnGroupsPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CFinalizeConnectionPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  OnStatusFinished for CGameClientConnectPrerequisite
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
Failed to load grid nav data, file 'maps/<empty>.gnv' not found!
SV:  Sending full update to client FelipinhO (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 33.217 KB [8 pkts], outgoing 1.272 KB [9 pkts]
Failed to communicate with routing cluster 'icn'.
Failed to communicate with routing cluster 'del'.
Ping measurement complete.
Writing configuration for slot 0
Network socket 'client' opened on port -1
Writing configuration for slot 0
Detected lobby in state RUN, connecting to 205.185.194.27:27072
SwitchToLoop remoteconnect requested:  id [2] addons []
CL:  IGameSystem::LoopDeactivateAllSystems
CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/dashboard_parallax_test) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
SV:  IGameSystem::LoopDeactivateAllSystems
HO:  IGameSystem::LoopDeactivateAllSystems
SV:  Disconnect client 'FelipinhO' from server(1): NETWORK_DISCONNECT_SHUTDOWN
Network socket 'client' opened on port -1
CL:  Sending connect to 205.185.194.27:27072
CL:  Sending connect to 205.185.194.27:27072
CL:  Received S2C_CHALLENGE [3206300372 auth 3] from 205.185.194.27:27072
CL:  Sending C2S_CONNECT [42 protocol 3206300372 auth 3] to 205.185.194.27:27072
CL:  Received S2C_CONNECTION from 205.185.194.27:27072 [addons:'']
CL:  Connected to '205.185.194.27:27072'
CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
SwitchToLoop levelload requested:  id [2] addons []
Failed to load image for cursor from resource\cursor\valve\ti5\cursor_inivisible.bmp: Couldn't open resource\cursor\valve\ti5\cursor_inivisible.bmp
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [2] addons []
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  CNetworkGameClient already exists for connection to '205.185.194.27:27072'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  connection to '205.185.194.27:27072' already started
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
      client  205.185.194.27:27072[0]:  split packet seq #1 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #6 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #10 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #12 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  split packet seq #13 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #15 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  split packet seq #16 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #18 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  split packet seq #19 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #21 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #23 restarting, just received packet 62
Communications with routing cluster 'icn' established.
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #26 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     3/    6 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #28 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #30 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #33 restarting, just received packet 62
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  high packet loss detected flow incoming:    0ms latency,     2/    4 dropped (50.0%)
      client  205.185.194.27:27072[0]:  split packet seq #41 restarting, just received packet 62
Allocating new transform texture!
Discarding pending request 'Remote Connect (205.185.194.27:27072), 2'
Disconnection during connection phase. Sign-on state: 2. Disconnect reason: 59.
CL:  Disconnecting from server: #GameUI_Disconnect_ExitingEngine
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME

**Comment by felipinho-lima** [comment]
Follow the tracert of Networks.

OBS: My DNS it Google Public (8.8.8.8 and 8.8.4.4)

First test it's the server in the West EUA. It's work for me.

C:\Users\FelipinhO>tracert 162.254.199.170

Rastreando a rota para 162-254-199-170.valve.net [162.254.199.170]
com no máximo 30 saltos:

  1     2 ms     3 ms     3 ms  192.168.0.1
  2     3 ms     4 ms     3 ms  10.168.80.1
  3    13 ms    75 ms    24 ms  138.99.69.1
  4   123 ms     5 ms    38 ms  49.13.186.200.sta.impsat.net.br [200.186.13.49]

  5   118 ms   114 ms   116 ms  po2.ar3.MIA2.gblx.net [67.17.68.234]
  6   106 ms   106 ms   107 ms  ae5.edge2.miami2.level3.net [4.68.111.121]
  7     \*        \*        \*     Esgotado o tempo limite do pedido.
  8   119 ms   117 ms   118 ms  4.16.61.198
  9   118 ms   118 ms   118 ms  162-254-199-170.valve.net [162.254.199.170]

Rastreamento concluído.

Second i think the server it's East Of Eua i don't know work's in Brasil server.

C:\Users\FelipinhO>tracert 205.185.194.27

Rastreando a rota para 205.185.194.27 com no máximo 30 saltos

  1     3 ms     3 ms     3 ms  192.168.0.1
  2     3 ms     3 ms     3 ms  10.168.80.1
  3     6 ms     3 ms     4 ms  138.99.69.1
  4    45 ms     3 ms     3 ms  49.13.186.200.sta.impsat.net.br [200.186.13.49]

  5    17 ms    11 ms    13 ms  po3-40G.asr1.GRU1.gblx.net [67.16.139.166]
  6    12 ms    11 ms    13 ms  204.245.39.122
  7     \*        \*        \*     Esgotado o tempo limite do pedido.
  8     \*        \*        \*     Esgotado o tempo limite do pedido.
  9     \*        \*        \*     Esgotado o tempo limite do pedido.
 10     \*        \*        \*     Esgotado o tempo limite do pedido.
 11     \*        \*        \*     Esgotado o tempo limite do pedido.
 12     \*        \*        \*     Esgotado o tempo limite do pedido.
 13     \*        \*        \*     Esgotado o tempo limite do pedido.
 14     \*        \*        \*     Esgotado o tempo limite do pedido.
 15     \*        \*        \*     Esgotado o tempo limite do pedido.
 16     \*        \*        \*     Esgotado o tempo limite do pedido.
 17     \*        \*        \*     Esgotado o tempo limite do pedido.
 18     \*        \*        \*     Esgotado o tempo limite do pedido.
 19     \*        \*        \*     Esgotado o tempo limite do pedido.
 20     \*        \*        \*     Esgotado o tempo limite do pedido.
 21     \*        \*        \*     Esgotado o tempo limite do pedido.
 22     \*        \*        \*     Esgotado o tempo limite do pedido.
 23     \*        \*        \*     Esgotado o tempo limite do pedido.
 24     \*        \*        \*     Esgotado o tempo limite do pedido.
 25     \*        \*        \*     Esgotado o tempo limite do pedido.
 26     \*        \*        \*     Esgotado o tempo limite do pedido.
 27     \*        \*        \*     Esgotado o tempo limite do pedido.
 28     \*        \*        \*     Esgotado o tempo limite do pedido.
 29     \*        \*        \*     Esgotado o tempo limite do pedido.
 30     \*        \*        \*     Esgotado o tempo limite do pedido.

Rastreamento concluído.

**Comment by ghost** [comment]
I'm stuck on the loading screen as well. Unable to connect to a created lobby or spectate games; I'm able to play bot matches.

System information:
https://gist.github.com/jonesz/f6551b3ea0ee8c2b932d

console.log
https://gist.github.com/jonesz/bc4b82bd408e144739c1

thanks.

edit: gist'd log file.

**Comment by gdrewb-valve** [comment]
Can you add +net_showudp 1 and +net_showsplits 1 to your launch options, retry and put up a new console log?

**Comment by felipinho-lima** [comment]
Ok.

The log with UDP active generates much lines because the type protocol it's diferents with TCP.
But i print inside the dota 2,.

Follow the logs.

Console_log.txt
https://github.com/felipinho-lima/Dota-2/issues/3

Server_log.txt
https://github.com/felipinho-lima/Dota-2/issues/2

Log console with inside DOTA 2
https://github.com/felipinho-lima/Dota-2/issues/1

**Comment by gdrewb-valve** [comment]
Thanks for the logs.  Can you add +net_maxroutable 800 to your launch options and see if things work better?

**Comment by felipinho-lima** [comment]
I don't know how i don't know if have changes in my network but i can PLAY AGAIN.
I create lobby using Brasil server it' works
I find new match in Brasil Server and work's

I love this GAME it's my distraction out my job.

Thank You so much.

**Comment by gdrewb-valve** [comment]
That's great.

Did you add +net_maxroutable 800 to your launch options?

@jonesz, are things still not working for you?  Can you try the maxroutable option?

**Comment by felipinho-lima** [comment]
Yes. I think this option limited the packet.
I play now :+1: :)

**Comment by gdrewb-valve** [comment]
If you have some extra time can you try it again with values between 800 and 1200, possibly by increments of 50?  At some point the game should stop working and we're curious to know where it is.

What internet service are you using?  You're in Brazil (or Peru from your name)?

**Comment by felipinho-lima** [comment]
In Brasil.
During the week i can try and i can tell in here or another place my experience.

**Comment by ghost** [comment]
@gdrewb-valve I fiddled around with some of my network settings and managed to get it working a few days ago. apparently a certain set of ips dhcp gives me doesn't like to work with dota2.

**Comment by Tele42** [comment]
For reference, @felipinho-lima's IP address belongs to Prymus Serviços Em Telecomunicações Ltda, Please remove your IP as there is always a risk of trouble when associating any IP address with a user.

**Comment by felipinho-lima** [comment]
Done

**Comment by gdrewb-valve** [comment]
Any luck trying different sizes?

**Comment by felipinho-lima** [comment]
Sorry for delay. I try now

**Comment by felipinho-lima** [comment]
Only works set 800 at 950 ... 1000 dont't work. Always same you say 50 and 50 .. i create lobby can test for it.
Thanks

**Comment by gdrewb-valve** [comment]
Did you try 850 and 900?  Those might be interesting, but it's not critical.  Thank you for the info.

**Comment by felipinho-lima** [comment]
Yes .. 800 .. 850 .. 900 and 950 its works ... more no

**Comment by gdrewb-valve** [comment]
OK, thanks.

**Comment by gdrewb-valve** [comment]
In the interest of finding out more concrete information can you try the instructions at http://www.dslreports.com/faq/5793 to find out your MTU size?

There's also this article in Portuguese https://forum.zwame.pt/threads/achar-o-mtu-da-ligacao-adsl.212830/ I don't read Portuguese and the Google translate result was a little iffy so hopefully that page is readable.

**Comment by felipinho-lima** [comment]
Ok. I read more in my house after job. But now i can tell you i had problem recently (more or less 4 months) i could not send image in whatsapp after change solved the problem and i continuous play dota normally without problem. I don't remember the exact number but i think set 1500.

**Comment by gdrewb-valve** [comment]
Thank you for the extra information.  It sounds like everything is OK so I'm closing this out.

**Comment by felipinho-lima** [comment]
No problem. Thank you for help and solve my problem. All for community Dota 2 and developers.
