### ISSUE TITLE
[OSX] FPS Drops 

### ISSUE THREAD

**Issue by cyrilvoynov** [ValveSoftware/Dota-2#522]
I have huge fps drops since 2th October. It looks like game performance shut down to the half of itself. Instead of 60-70 fps that i had before the regular Dota 2 update, now I have 25-35 fps only in the better case and it's actually unplayble. 

There're some system information. Hope it will helps: 

Processor Information:
    Model:  MacBookAir5,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  1800 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114544 Mb
    Largest Free Hard Disk Block:  84090 Mb

**Comment by Tele42** [comment]
Screenshots of text are not searchable, Here's the key details to help others who are searching:

```
Model: MacBookAir5,2
MacOS 10.11.0 (64 bit)
Driver: Intel HD Graphics 4000
```

**Comment by gramathy** [comment]
Also getting a lot of performance issues, framerate sub-40 on an i5 3750K@4.2GHz and a 980.

System Software Overview:

  System Version:   OS X 10.10.5 (14E46)
  Kernel Version:   Darwin 14.5.0
  Boot Volume:  Holmes
  Boot Mode:    Normal
  Computer Name:    BakerSt
  User Name:    *******
  Secure Virtual Memory:    Enabled
  Time since boot:  19:48

Hardware:

```
Hardware Overview:

Model Name: iMac
Model Identifier:   iMac13,2
Processor Name: Intel Core i5
Processor Speed:    4.2 GHz
Number of Processors:   1
Total Number of Cores:  4
L2 Cache (per Core):    256 KB
L3 Cache:   6 MB
Memory: 16 GB
Processor Interconnect Speed:   400 MT/s
Boot ROM Version:   IM131.010A.B05
```

Graphics/Displays:

```
NVIDIA GeForce GTX 980:

  Chipset Model: NVIDIA GeForce GTX 980
  Type: GPU
  Bus: PCIe
  PCIe Lane Width: x16
  VRAM (Total): 4095 MB
  Vendor: NVIDIA (0x10de)
  Driver version: 346.02.03f01
  Device ID: 0x13c0
  Revision ID: 0x00a1
  ROM Revision: VBIOS 84.04.31.00.80
  Displays:
    DELL U2412M:
      Resolution: 1920 x 1200
      Pixel Depth: 32-Bit Color (ARGB8888)
      Display Serial Number: YMYH142H1C8S
      Mirror: Off
      Online: Yes
      Rotation: Supported
    DELL U2412M:
      Resolution: 1920 x 1200
      Pixel Depth: 32-Bit Color (ARGB8888)
      Display Serial Number: YMYH132E1G7S
      Main Display: Yes
      Mirror: Off
      Online: Yes
      Rotation: Supported
      Connection Type: DisplayPort
```

Memory:

```
Memory Slots:

  ECC: Disabled
  Upgradeable Memory: Yes

    BANK 0/ChannelA-DIMM0:

      Size: Empty
      Type: Empty
      Speed: Empty
      Status: Empty
      Manufacturer: Empty
      Part Number: Empty

    BANK 1/ChannelA-DIMM1:

      Size: 8 GB
      Type: DDR3
      Speed: 1867 MHz
      Status: OK
      Manufacturer: Corsair
      Part Number: CMZ16GX3M2A1866C10

    BANK 2/ChannelB-DIMM0:

      Size: Empty
      Type: Empty
      Speed: Empty
      Status: Empty
      Manufacturer: Empty
      Part Number: Empty

    BANK 3/ChannelB-DIMM1:

      Size: 8 GB
      Type: DDR3
      Speed: 1867 MHz
      Status: OK
      Manufacturer: Corsair
      Part Number: CMZ16GX3M2A1866C10
```

**Comment by gdrewb-valve** [comment]
Has your performance changed with the recent updates?

**Comment by cyrilvoynov** [comment]
Yes, its comfortable to play right now. Perfomance isn't the best (I mean its not 50-70 fps anymore, but smth about 40-60), but it doesnt have a big influence to gameplay, even in competitive matches.

**Comment by gdrewb-valve** [comment]
OK, we'll leave this open since the perf still isn't what it was.

**Comment by gramathy** [comment]
One thing I'm noticing is that the CPU usage for Dota is 150%+ even on the main menu, which seems pretty high to me considering ingame hovers around 200%. I did notice a slight boost in the last patch but I can't hit 60 unless half or more of the graphics options are turned off or reduced.

**Comment by gdrewb-valve** [comment]
The UI is fairly complex and graphics-heavy (plus web fetching, video decoding and more) so it's definitely going to take a bunch of CPU, but clearly something bad is happening to make the frame rate poor.  Fixing one might help with the other.

**Comment by gramathy** [comment]
Doing some experimentation it seems weather effects are hitting me the hardest with about 30% FPS drop with effects on. By comparison going from high to Ultra shadows is maybe 10% fps loss. Is that an expected amount of performance loss?

**Comment by cyrilvoynov** [comment]
Same to me. Somehow it takes about 100-150% of CPU even in the main menu. As I noticed, it's not really influence to FPS. But, yea. Fact is a fact. 
![screen shot 2016-01-31 at 12 57 49 pm](https://cloud.githubusercontent.com/assets/14957336/12700973/96aac84a-c81a-11e5-9dd2-7a2105464e80.png)

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
