### ISSUE TITLE
Commentary sound missing in replays

### ISSUE THREAD

**Issue by prudnicki** [ValveSoftware/Dota-2#525]
Commentary is missing while watching tournament replays - 100% of the time.
Sound is there while watching live.

Many people are reporting same problem:
https://steamcommunity.com/app/570/discussions/0/523897277925162399/
http://dev.dota2.com/showthread.php?t=180602
https://steamcommunity.com/app/570/discussions/0/523898291496538133/

**Comment by danginsburg** [comment]
This bug tracker is for Linux/OSX-specific issues.  The dev.dota2.com forum is the appropriate place for other issues.
