### ISSUE TITLE
Mac: Game Is ready sound not working with external audio card.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#527]
2 updates back or so the game is ready sound stopped working at all. I'm using an external audio card and before the sound didn't work properly because it came from the built in output instead of the external audio card input (as all other sound do) but after the last couple of updates there's no sound even trough the built in speakers when you select your external audio card.

**Comment by gdrewb-valve** [comment]
Can you post your system information so that it's here with the issue?

**Comment by gdrewb-valve** [comment]
Closing as we'll need full system info to try and determine what might be happening.
