### ISSUE TITLE
[MAC] Can't change or preview announcer

### ISSUE THREAD

**Issue by LinoleumRipper** [ValveSoftware/Dota-2#530]
Hi!

In the game (menu or in-game) i can't use other announcers. I can hear only the defaults. When someone shares an announcer in-game, i can't use them. When i try to select one after closing the panel it changes back to the defaults. I tried to preview one of my announcers in armoury it was completely silent... It seems the game can't find those sound files.
I tried many announcers none of them works only defaults. 

Thank you for helping!

MY SYSTEM INFORMATION

Processor Information:
    Model:  Macmini7,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  Intel Iris

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xa2e
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.82" x 10.55"  (21.57" diag)
                                        47.8cm x 26.8cm  (54.8cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  952704 Mb
    Largest Free Hard Disk Block:  780053 Mb

**Comment by gdrewb-valve** [comment]
This isn't Mac-specific, the larger team will get this working but it won't be tracked here.
