### ISSUE TITLE
Downloading Fall Compendium is very slow

### ISSUE THREAD

**Issue by nellh** [ValveSoftware/Dota-2#533]
It takes 30-60 seconds to open the Fall Major Compendium after each client start. That is pretty slow compared to how compendiums worked in the original client.

**Comment by MrTheSoulz** [comment]
Mine wont even open, stuck downloading at 100%

**Comment by gdrewb-valve** [comment]
These issues happen on Windows also and won't be tracked here.  The regular forums at dev.dota2.com have multiple reports that you can watch.
