### ISSUE TITLE
[linux] Disconnecting from server immediately after connecting

### ISSUE THREAD

**Issue by magist3r** [ValveSoftware/Dota-2#535]
Today (10/6) I can't play Dota2 at all. Nor MMR neither custom games. After every attempt to reconnect I get the main menu again ((.

Regions EU RU
Thx for LP valve...

**Comment by danginsburg** [comment]
There is not enough info here for us to repro.  Can you post Steam -> Help -> System Information as well as run with -con_logfile and post game/dota/console.log?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
