### ISSUE TITLE
General protection error

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#536]
hi,
I just had the game crash at the main menu screen. For a moment I could see the missing game coordinator message.

[559690.527189] traps: dota2[29812] general protection ip:7fe93e686bc8 sp:7ffd09446120 error:0 in libpanorama.so[7fe93e551000+52d000]

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information, especially any relevant CrashIDs.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
