### ISSUE TITLE
[MAC] Continued poor performance on Iris GPU

### ISSUE THREAD

**Issue by manicmouse** [ValveSoftware/Dota-2#538]
I'm sorry to bring this up again, as it has already been brought up and supposedly addressed, however performance on Mac with Iris GPUs is still sub-par.

Playing with medium settings (textures and shadow at medium, with only normal maps, ambient creatures, normal maps, additive light pass and world lighting on) I am struggling to hit 30fps in Reborn.  This is without antialiasing, without high quality water, without v-sync, without ambient occlusion, without light blooms.

I'm on a 13" MBP with 2.4Ghz i5, 8Gb RAM, Intel Iris 5000 and on El Capitan.  Not a monster, but certainly something that should be able to play DOTA Reborn at medium settings at a decent framerate.

Having watched the kind of performance people with worse intel GPUs are getting it's a little disheartening like in this video:

https://www.youtube.com/watch?v=oS3vs-39tPA

The Iris I have in my machine is, supposedly, nearly twice as fast as that HD4000 yet that person is getting nearly double the frame rates I am at medium settings (I get 25-30, he's getting 37-45).

Honestly at the same settings I'm using I should really be getting 60fps if the HD4000 can hit 45.  The game is just barely playable at medium setting on the Iris 5000, and many people would say 25-30fps is unplayable.  There is definitely something going awry when a HD4000 outperforms an Iris 5000 significantly.

**Comment by danginsburg** [comment]
We are aware of the performance issues on Iris on OS X.  We have an open Radar with Apple and are trying to get help in improving this.  I have spent a ton of time tuning performance on OS X Intel and we are running into OpenGL driver performance issues that we are awaiting help from Apple/Intel to resolve.  Duplicate of #245 and #246.

**Comment by rhysm94** [comment]
Just wondering - and I know it's a longshot that it'll be answered here - is there any chance Source 2 will be ported to Metal, or is the more likely situation waiting to see if Vulkan can be released on OS X?

**Comment by ghost** [comment]
something went even more south with the "[Frankfurt Major is now LIve](http://store.steampowered.com/news/19296/)" update on Nov. 12th – overall FPS went from 50-60 to 30-40, plus FPS drops down to 5-10 for every single spell with AOE effect. Had _never_ happened before.

(Related?) for windows there is `-nod3d9ex` and `-dx11`, but how do i turn that improved alt-tabbing off on a mac?

**Comment by gdrewb-valve** [comment]
There is no alternate mode on the Mac, D3D9 and D3D9Ex are Windows-specific.

Have the recent updates changed anything for you?

**Comment by ghost** [comment]
> Have the recent updates changed anything for you?

not sure if it was one of ~50 updates over the last 3 weeks, or just the fact i de_dust'ed my cpu cooler (mac mini 2011), but now it can steady hold at 50-60 fps at lowest graphic settings, which is all i could ask for.

except during bursty lategame teamfights with 9 ults and 5 invoker spells flying out at once – a 0.5 FPS slideshow for about 4-10 sec, as if watching a lifestream from china.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
