### ISSUE TITLE
[Ubuntu] Bad text and number.

### ISSUE THREAD

**Issue by thegunner2401** [ValveSoftware/Dota-2#539]
http://imgur.com/hvzeQq4
http://imgur.com/mc2k4pe
I've tried to reinstall ubuntu and dota 2 but the problem still persists.

**Comment by danginsburg** [comment]
Please post Steam -> Help -> System Information.  This looks exactly like a known bug in mesa that will be fixed by updating to a newer version of mesa.

**Comment by danginsburg** [comment]
Duplicate of #417.
