### ISSUE TITLE
Hero portraits are not displayed on Players profile Trophy Case

### ISSUE THREAD

**Issue by rodlorric** [ValveSoftware/Dota-2#54]
You can see on this screenshot that the hero portrait is not being displayed:
![Trophy Case](http://imgur.com/25vZG5D.jpg)

Additionally, on the Heroes Tab / All Heroes option, none of the hero portraits are animated, just still images on mouse hover.

*Edit:
On the draft screen when you enter a game, say All Pick, the portraits are animated.

I verified the game's cache with the same results.

**Comment by gdrewb-valve** [comment]
Can you post your system information?

**Comment by sphexing** [comment]
Yeah sure, my bad...
System info:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2668 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,98" x 12,28"  (24,29" diag)
                                            53,3cm x 31,2cm  (61,7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1200
    
Memory:
    RAM:  5958 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  100564 Mb
    Largest Free Hard Disk Block:  26705 Mb
```

**Comment by gdrewb-valve** [comment]
It turns out that playing the hero movies is still under construction for Linux and Mac.  This will be finished in an upcoming release but I don't have a specific date.

**Comment by MrTheSoulz** [comment]
Any news on this?
How come "the hero movies is still under construction for Linux and Mac" but while in match selecting a hero does have "movies".

**Comment by gdrewb-valve** [comment]
This has been considered low priority as it only impacts a couple of specific points in the UI.  Is it causing you an issue playing the game?

**Comment by MrTheSoulz** [comment]
True, it does not affect  in-game. 
But it does look "bad" and causes empty boxes like the last played match on main UI.

**Comment by literallyunplayable** [comment]
Is there any chance that the empty space in "your last match" and in the trophy case can be replaced with static images as placeholders. I dont see why an issue like this can persist for 5 months in the first place.

**Comment by gdrewb-valve** [comment]
Dev time has been going to higher-priority issues.  The assumption has been that this doesn't interfere with anybody playing the game or using the UI so it is pretty low on the list.  Is this preventing you from doing something in Reborn?

**Comment by ramma** [comment]
It is purely cosmetic as far as I can tell. No impact on actual game play.

**Comment by jaccarmac** [comment]
This issue also appears to affect the hero portraits in the new Winter Battle Pass's daily challenge.

I'm observing no portrait or animation in the quests tab on my machine running Ubuntu devel repositories. System information is below. I'm using the latest graphics drivers (NVIDIA 361.18) and Unity.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Xenial Xerus (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.0-7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11703000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 750M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.18
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0xfe4
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.58" x 7.64"  (15.55" diag)
                                            34.5cm x 19.4cm  (39.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: 

Memory:
    RAM:  15994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  922194 Mb
    Largest Free Hard Disk Block:  773452 Mb

Installed software:

Recent Failure Reports:
```

**Comment by ramma** [comment]
I don't see what you're referring to. From what I can see, hero images will appear when you complete quests in each path. Do you have a screenshot of where they seem to be missing?

**Comment by jaccarmac** [comment]
Not those, the daily challenge card near the bottom of the screen. I'm not on my Linux box at the moment, but I'll screenshot it and add it to this thread when I am.

**Comment by gdrewb-valve** [comment]
There's no real need for screenshots, hero movies won't work in any part of the UI until we get the underlying playback working.

**Comment by jaccarmac** [comment]
Thanks @gdrewb-valve. Feared as much.

**Comment by zor1984qq** [comment]
One more question please is mentioned here "underlying playback" is related somehow to new "Panorama" framework? Is these piece of great new software and removing Autodesk Scaleform traces are responsible for losing whole game menu portraits animation?
[https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama:ru](url)

And if it is, the only thing that needed to be done is convert old PNG content or develop a new HTML5 based resources content for game menu HUD as it is already done by such sites like youtube?
Thanks.
P.S.>Its not critical but ruin whole appearance of the game from the start point and its wished likely to be fixed ASAP for most Linux players affected by these missing content.

**Comment by gdrewb-valve** [comment]
Things have been moving along here and I believe we have all of the missing parts in place.  I believe in the next week or this this will go out with a Reborn update.

**Comment by Cabanur** [comment]
I can only hope this upcoming update wll bring the new HUD we've been expecting :D

**Comment by zor1984qq** [comment]
Is there any info on the next big updates appear?

**Comment by Cabanur** [comment]
I don't think so, Valve dislikes anticipating stuff until it's out.

**Comment by gdrewb-valve** [comment]
The 2/17 update should have the fix.

**Comment by rodlorric** [comment]
I tried on Ubuntu and now it is working. Thanks!

**Comment by gdrewb-valve** [comment]
Thanks, closing.
