### ISSUE TITLE
[Ubuntu] Locking the screen when using alt + tab command

### ISSUE THREAD

**Issue by Anderson-Juhasc** [ValveSoftware/Dota-2#543]
The game works perfectly, but when I use the alt + tab often the game freezes and have to restart your computer.

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information.

**Comment by Anderson-Juhasc** [comment]
OS: Ubuntu 15.04
Processor: INTEL CORE I7 HASWELL - 4710MQ 2.5 GHZ, 6MB CACHE (3.50 GHZ)
Video: NVIDIA GEFORCE 840M GPU (2GB)
Drive: NVIDIA version 346.96 nvidia-346-updates

**Comment by gdrewb-valve** [comment]
You can't switch away or start another tty or anything?  The machine is completely locked up?  That would most likely be a driver issue.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
