### ISSUE TITLE
Not all teammates are displayed in menu if sixth player coaches.

### ISSUE THREAD

**Issue by mjstahlberg** [ValveSoftware/Dota-2#545]
When a sixth player (who wasn't the sixth to join the group) becomes a coach, only five players are displayed in both the upper and lower team listing visible in the main menu. The players displayed differ, with a different player missing in each listing. See the image for the exact listings. The numbers in the image are chosen according to the order in the upper listing. This is on the linux client.

![bug](https://cloud.githubusercontent.com/assets/3780206/10397411/e521abc8-6ea7-11e5-842a-5f495b55f012.jpg)

**Comment by gdrewb-valve** [comment]
Probably not Linux-specific.

**Comment by gdrewb-valve** [comment]
Confirmed with the larger team that this isn't expected to work at the moment.  It'll get fixed at some point but it won't be tracked here.

**Comment by mjstahlberg** [comment]
For my next report: What's the appropriate way to report bugs that look platform-independent?

**Comment by gdrewb-valve** [comment]
The regular forums are at dev.dota2.com
