### ISSUE TITLE
Command Tab'in doesn't restore focus to Dota 2

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#546]
Firstly, thank you for fixing the desktop space! Now to the issue, I am unable to restore focus on desktop space using command+tab.

Secondly, Is "Exclusive Full-screen" supposed to be unresponsive to command+tab keys? What I assumed was **Exclusive Full-screen** should be using the Desktop space and **Desktop Friendly Full-screen** to minimize upon losing focus.

OSX 10.11
Intel HD4000

**Comment by Enigma7ic** [comment]
Yup, having the same issue. Have to restart the client every time I accidentally Alt-Tab (force of habit). 

Really annoying!

This is on El Capitan

**Comment by danfmaia** [comment]
Same here. Can't restore focus on client after command+tabbing out of it. I'm on El Capitan also. But this bug is happening only since yesterday, after a bugfixing patch.

**Comment by Maixy** [comment]
Same issue on El Capitan!  Would love to see this resolved

**Comment by jamorton** [comment]
Also having this issue on El Capitan.

For now, I found a temporary fix that doesn't require restarting dota:  maximimize another window so it slides over into a new workspace. Then, alt-tab back into Dota 2 and it should appear.

**Comment by Wusch** [comment]
I have the same problem if press alt + tab and want to go back i hear the dota sound and see the dota cursor. But nothing else.

**Comment by gdrewb-valve** [comment]
Exclusive full screen should ignore Cmd+Tab, at least that's what the SDL devs said a while back.  Are you all using exclusive or desktop-friendly or windowed?

**Comment by gxgani** [comment]
@gdrewb-valve currently desktop-friendly. May I know what actually exclusive full screen is meant to do? Is it suppose to cut off the gpu processing of desktop and utilize it completely for the game?

**Comment by gdrewb-valve** [comment]
Exclusive fullscreen basically means "devote my computer to running the game".  It will do things like change resolutions and such that make switching away from the game slower and harder.  Generally operating systems do get out of the way in that case and you can get a little more perf, particularly if you are using a resolution lower than the desktop resolution.

**Comment by gxgani** [comment]
I just compared both the display mode and I was getting around 65-70fps with nothing enabled and having set the rendering to 70% (1280x800) on Intel HD4000. But is it really necessary to have Command+Tab disabled during the exclusive screen mode? I believe source 1 was running on exclusive screen mode since it had it's own brightness settings enabled but I feel there wouldn't be a drop in performance if we jump out of exclusive mode/multi task.

I also did a intel power data analysis of having a browser window opened with multiple page including a youtube video paused and then switched to dota 2 and tried comparing the frames in both the modes, I still was getting in similar range.

**Comment by gdrewb-valve** [comment]
From what I've heard from the SDL devs when SDL uses exclusive fullscreen it doesn't run certain portions of code that make it cooperate better with the desktop and that includes the Cmd+Tab support.  That should have been true in SDL always, though, and should affect Source 1 Dota 2 also.

**Comment by danginsburg** [comment]
Are you able to get back into the game by using CTRL->RIGHT to switch spaces?  I am seeing that in OS X El Capitan when you CMD-TAB out and then CMD-TAB back the dock hides and it doesn't switch to the space with dota running.  You can get back to the space with CTRL->RIGHT though.  I don't see this behavior in OS X 10.10.

**Comment by gxgani** [comment]
Yes, also using four-finger swipe.

**Comment by danginsburg** [comment]
Just want to follow up that we have looked into this.  The issue only happens in OS X 10.11.  We are discussing this issue with the SDL devs.  Basically what is happening is that for a reason we don't yet understand in OS X 10.11 it does not switch to the space the fullscreen window was created in when it becomes active.  In OS X 10.10 it did switch automatically.  The workaround for now is just to switch spaces when you CMD-TAB back to the app.

**Comment by gxgani** [comment]
I'll like to also add that "bring dota2 foreground on matchmaking found" is affected by this. What happens is after a match is found, I switch space(dota2) but I am reverted back to my original space, thus have to switch space again.

**Comment by ghost** [comment]
You can switch back to the screen by 3 finger swiping the trackpad. Thats what works for me if cmd tab doesn't work

**Comment by danginsburg** [comment]
I filed SDL bug #3152 to track this issue: https://bugzilla.libsdl.org/show_bug.cgi?id=3152  This bug impacts any SDL app that uses SDL_WINDOW_FULLSCREEN_DESKTOP on OS X 10.11 (although not previous versions of OS X).

**Comment by danginsburg** [comment]
We patched SDL and have a fix for this issue.  It will go out in a future Dota 2 update.

**Comment by danginsburg** [comment]
Fixed in 10/22 update.

**Comment by gluttonyGit** [comment]
I have this problem on my os x. I am unable to restore focus on desktop space using command+tab. But i can do this using cmd+H.
OS X 10.11.1
Intel HD Graphics 4000
Current on 1.11.2015
