### ISSUE TITLE
[linux] Key press are not handled if game was launched with non-US keyboard layout

### ISSUE THREAD

**Issue by barkovv** [ValveSoftware/Dota-2#547]
So, if I launch game with non-US keyboard layout, spells can't be casted by using keybord, but writing chat messages is still avaible in this case.

**Comment by barkovv** [comment]
Some info if you need it:
Archlinux (KDE5)
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Desktop x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.0.2
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x152
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,74" x 10,55"  (21,50" diag)
                                        47,6cm x 26,8cm  (54,6cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3832 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  159505 Mb
    Largest Free Hard Disk Block:  97974 Mb

**Comment by leg0las-devel** [comment]
I confirm it, abilities/items not work, but shop/courier work fine. Gentoo x86_64, KDE 4.14.8, locale ru_RU.UTF8.

**Comment by Yunoo** [comment]
Try to add -input_button_code_is_scan_code to the command-line while starting Dota.

**Comment by barkovv** [comment]
Thank you. -input_button_code_is_scan_code CLI option fixes the problem.

**Comment by Tele42** [comment]
Okay, so that makes this a duplicate of #473. (for reference)
