### ISSUE TITLE
[OSX] Dota 2 Hero Menu Constantly Shuffling

### ISSUE THREAD

**Issue by griffin144** [ValveSoftware/Dota-2#548]
On the hero menu, I am not able to select any hero because the game is always shuffling them, I have no idea how to fix this. Also when I click of my friends list the scroll bar scrolls all the way down and then I can't scroll back up, it is a very frustrating glitch, has anyone had the same issue?

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?

Do you have any kind of joystick, controller or extra input device plugged in beyond a mouse and keyboard?  Are your mouse and keyboard completely standard or special gaming models?

**Comment by gdrewb-valve** [comment]
See also #318 for something somewhat related.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
