### ISSUE TITLE
Reborn client crash, dynamic_cast error

### ISSUE THREAD

**Issue by pradeeproark** [ValveSoftware/Dota-2#551]
The client crashes after clicking Accept to join a match, Trying reconnect keeps throwing the following error in console

```
11/10/2015 18:08:08.968 dota2[1297]: dynamic_cast error 2: One or more of the following type_info's        has hidden visibility.  They should all have public visibility.   6ConVar, 24CBoundedCvar_InterpRatio, 20ConVar_ServerBounded.
```

MBP, OSX Yosemite.

In the abandon Q now because of this.

**Comment by pradeeproark** [comment]
Processor Information:
    Model:  MacBookPro11,3
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel Iris Pro

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0xd26
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                        33.1cm x 20.6cm  (38.9cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475936 Mb
    Largest Free Hard Disk Block:  211066 Mb

**Comment by gdrewb-valve** [comment]
This apparently happened with Source 1 Dota 2 also.  The larger team is taking a look.

**Comment by gdrewb-valve** [comment]
The larger team thinks they might know what's going on, but this won't be tracked here as it's not a Linux / Mac issue.
