### ISSUE TITLE
Dota 2 after reborn update has some terrible pathfinding issues.

### ISSUE THREAD

**Issue by DARKTHUNDER** [ValveSoftware/Dota-2#554]
Scenario 1: While we move the screen towards some direction ( while moving the fps is 2x the fps that we are playing at and after we stop the frame rate reduces to playing rate ( must not happen )

Scenario 2: While using courier at shift queuing like Fetch items and Transfer items : the courier goes to the fountain ( a minor delay in getting the items into the courier ) then the courier (invariably where the hero is ) starts initially downwards from the fountain ( after 2 steps finds the path to the hero and then changes its course )

Scenario 3: while casting any spell ( the arrow mark from the hero to the spell destination is drawn ( this is weird ) We mostly do not need this to delay the frame-rate. Here what i find is camera lag. When we use town portal or blink to a destination. After the hero lands. 1 sec delay in getting the next direction we click. Seriously after blink stun there is a lag which decreases frame-rate.

Scenario 4: when multiple heroes engage in a fight sudden lag ( i hope this is due to the arrow overlapping since every hero uses spell at the same instance ). Seriously we understand that the update wants us to enjoy the game but do not bug us with features that are non important in a time intensive game and the lag is terrible when multiple heroes clash!

Please support Nvidia 860m and 960m mobile gpu cards ( my 860m used to get 110 fps at mid - high settings at 1080p resolution. Now it is getting fairly 18 - 24 fps. I hope you guys will make dota playable and enjoyable as it was. 

Fix these soon and we do not need an arrow to denote where we click. we have a mouse pointer at the location ( do not mess the lag free game which it was with these features and say it as updated engine )

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?

**Comment by DARKTHUNDER** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2494 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 860M  

```
DirectX Driver Name:  nvumdshim.dll
Driver Version:  9.18.13.3250
DirectX Driver Version:  9.18.13.3250
Driver Date: 24 Jan 2014
OpenGL Version: 4.4
DirectX Card: NVIDIA GeForce GTX 860M  
VendorID:  0x10de
DeviceID:  0x1392
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 26.65" x 15.00"  (30.55" diag)
                                        67.7cm x 38.1cm  (77.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2047 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Speakers (3- 4Gamers Official U

Memory:
    RAM:  8108 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  953865 Mb
    Largest Free Hard Disk Block:  274709 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected

Installed software:
    3DMark 11 Demo
    Android USB Driver
    Assassins Creed IV Black Flag
    Avast Free Antivirus
    Combined Community Codec Pack 2014-07-13
    ConvertPro
    Display Pilot
    DivX Setup
    Dolby Home Theater v4
    Dota 2
    EAGetMail Mail Component (remove only)
    Futuremark SystemInfo
    Google Chrome
    Google Update Helper
    Intel® Trusted Connect Service Client
    Intel(R) Management Engine Components
    Intel(R) Processor Graphics
    Intel(R) USB 3.0 eXtensible Host Controller Driver
    K-Lite Mega Codec Pack 11.2.8
    Lenovo_Wireless_Driver
    Media Player Codec Pack 4.3.7
    Microsoft .NET Framework 4 Client Profile
    Microsoft .NET Framework 4 Extended
    Microsoft Access MUI (English) 2013
    Microsoft Access Setup Metadata MUI (English) 2013
    Microsoft DCF MUI (English) 2013
    Microsoft Excel MUI (English) 2013
    Microsoft Groove MUI (English) 2013
    Microsoft InfoPath MUI (English) 2013
    Microsoft Lync MUI (English) 2013
    Microsoft Office 32-bit Components 2013
    Microsoft Office OSM MUI (English) 2013
    Microsoft Office OSM UX MUI (English) 2013
    Microsoft Office Professional Plus 2013
    Microsoft Office Proofing (English) 2013
    Microsoft Office Proofing Tools 2013 - English
    Microsoft Office Proofing Tools 2013 - Español
    Microsoft Office Shared 32-bit MUI (English) 2013
    Microsoft Office Shared MUI (English) 2013
    Microsoft Office Shared Setup Metadata MUI (English) 2013
    Microsoft OneNote MUI (English) 2013
    Microsoft Outlook MUI (English) 2013
    Microsoft PowerPoint MUI (English) 2013
    Microsoft Publisher MUI (English) 2013
    Microsoft Visual C++ 2005 Redistributable
    Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
    Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219
    Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
    Microsoft Word MUI (English) 2013
    nubia NX505J Updater V2.0.0
    NVIDIA Control Panel 332.50
    NVIDIA Graphics Driver 332.50
    NVIDIA Install Application
    NVIDIA Network Service
    NVIDIA Optimus Update 11.10.11
    NVIDIA PhysX
    NVIDIA PhysX System Software 9.13.0927
    NVIDIA Update 11.10.11
    NVIDIA Update Core
    NVIDIA Virtual Audio 1.2.20
    Outils de vérification linguistique 2013 de Microsoft Office - Français
    Pivot Pro Plugin
    Realtek Card Reader
    Realtek Ethernet Controller Driver
    Realtek High Definition Audio Driver
    SDK
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2604121)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2656351)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2729449)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2736428)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2737019)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2742595)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2789642)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2840628v2)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2858302v2)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2894842v2)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2972106)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2972215)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2978125)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB2979575v2)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB3023221)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB3032662)
    Security Update for Microsoft .NET Framework 4 Client Profile (KB3037578)
    Security Update for Microsoft .NET Framework 4 Extended (KB2487367)
    Security Update for Microsoft .NET Framework 4 Extended (KB2656351)
    Security Update for Microsoft .NET Framework 4 Extended (KB2736428)
    Security Update for Microsoft .NET Framework 4 Extended (KB2742595)
    Security Update for Microsoft .NET Framework 4 Extended (KB2858302v2)
    Security Update for Microsoft .NET Framework 4 Extended (KB2894842v2)
    Security Update for Microsoft .NET Framework 4 Extended (KB3037578)
    Steam
    Update for Microsoft .NET Framework 4 Client Profile (KB2836939v3)
    Update for Microsoft .NET Framework 4 Extended (KB2836939v3)
    Uplay
    VC80CRTRedist - 8.0.50727.6195
    VLC Codec Pack 2.0.5
    VLC media player
    Windows 7 Codec Pack 4.1.3
    WinRAR 5.21 (32-bit)
    Xvid Video Codec
    Youtube Downloader HD v. 2.9.9.23
    YTD Video Downloader 4.9.2

**Comment by gdrewb-valve** [comment]
This issue tracker is for problems that only occur on Linux and Mac.  I've passed your report on to the larger team and you can also post on the regular Reborn forums (dev.dota2.com).

**Comment by gdrewb-valve** [comment]
The larger team mentioned that you can control the display of the range finder in the Options tab of settings.  Do you have it enabled?  There was also a convar in Source 1 Dota 2 but Reborn doesn't use that, instead the UI controls it.

**Comment by DARKTHUNDER** [comment]
Hi , I just installed ubuntu 14.04 in my system and backed up my dota 2 game from steam and installed in it. Installed nvidia 340 drivers and i get 120 fps at 1080p full best looking resolution, While in-game i get fairly >80fps. That is some great news but my account has only games listed till 15-1-2015 and my mmr is nearly 700 points lower. My 8 months progress is lost ( including immortal items and sets ). Can you help and fix it !?

**Comment by gdrewb-valve** [comment]
Unfortunately no, this is just for Mac and Linux bugs.  You'll need to open a support ticket or post on the regular forums.

**Comment by DARKTHUNDER** [comment]
I have moved from windows to ubuntu 14.04 now. I am playing in linux. After installing the game in linux only i am unable to view my past records. My matches played till 05-01-2015 are only shown in the dota 2 history ( which is in linux now ). You can help with this in linux bugs, is it not ?

**Comment by gdrewb-valve** [comment]
Sorry, I thought you were asking to have your MMR adjusted.  I'll check with the larger team about whether switching between systems should have any effect.  You're logging in with exactly the same Steam account, correct?

**Comment by DARKTHUNDER** [comment]
I am playing with the same steam account. sorry for the date notation i have said is wrong. My dota 2 progress inbetween 01-05-2015 to 14-10-2015 is gone and the history with mmr it shows is terribly wrong. I started dota 2 with 2050 mmr ( after TBD matches) and then i always have been to the lowest of 1620 ( never below but the history shows i have alwaz been playing 1400 mmr matches) . I had about 8 immortal items and 7+ hero sets during the internationals with my compendium ( they are missing now ). I am using the same account only. Please help !!   My steam account name is darkmitashi

**Comment by gdrewb-valve** [comment]
I'll pass this on to the larger team.

**Comment by DARKTHUNDER** [comment]
Hi there. Thanks for the support.  steam in Linux works great for me. I will check with my account details if anything is wrong. Really appreciate your quick responses. Keep up the good work.

**Comment by DARKTHUNDER** [comment]
I am terribly sorry. My steam account which i used is wrong. It is an old one. I got the new login credentials and i have all my items in that account without any loss. MMR is also fine. Thanks once again. My happy dota days are gonna be back.. FPS is pretty high in linux. Thank You.

**Comment by gdrewb-valve** [comment]
No problem, glad you found what the problem was.
