### ISSUE TITLE
Dota freezes right after loading screen in xmonad and herbstluftwm

### ISSUE THREAD

**Issue by wintermelons** [ValveSoftware/Dota-2#555]
Dota was working fine before yesterday's patch. 

Using Arch Linux (latest), 64 bit, with 32-bit steam over current latest proprietary NVIDIA driver. Window manager is Xmonad.

**Comment by danginsburg** [comment]
Possible duplicate of #359.  Can you try running with -sw on the command-line?  We have previously seen that dota loads just a black screen in fullscreen mode on xmonad.

**Comment by wintermelons** [comment]
It seems that the issue lies with xmonad. I too, have switched to i3 and got it to work. Thanks for the help.

**Comment by engywook** [comment]
I have this too,. It happened after last nights patch(Sunday CEST). I'm on herbstluftwm though and not xmonad. I've found that it works if I fullscreen it. I usually play windowed and it has worked great until yesterday. 

It hangs just after it starts showing the main menu. I still see the dota2 logo but the party stuff in the lower left corner is visible.

**Comment by wintermelons** [comment]
Oh yes, I saw the exact same thing as you. It seems that it isn't X server, NVIDIA or Dota though, but relates to how the window manager handles window/fullscreen. Even when Xmonad was working for me, I had issues with the window floating (not tiled) where sometimes the I lose a few pixels on the bottom and right borders and I won't be able to move the camera down or right in game.

**Comment by buhman** [comment]
+1, can confirm.

> Can you try running with -sw on the command-line?

No change in behavior.

**Comment by danginsburg** [comment]
So to make sure I am clear on the problem here, we freeze on loading screen in xmonad (known from #359) and also herbstluftwm (new in this bug).  Is that right?

**Comment by buhman** [comment]
> we freeze on loading screen in xmonad

[right here](https://cloud.githubusercontent.com/assets/728108/10531602/8cd3387a-7379-11e5-8cb8-e78796b34740.png) to be precise.

I've played around a bit:

If I tell dota (after starting it successfully in another WM) to do anything other than 'borderless window' (then quit), it restarts fine in xmonad. If I start dota in xmonad (successfully) then switch to borderless window (possibly telling xmonad to re-tile the dota window), dota appears to stop accepting input and no longer redraws the window.

Easy to reproduce.

**Comment by engywook** [comment]
My issue seems to be with Borderless Window. Fullscreen works fine in herbstluftwm.

**Comment by salcin** [comment]
Ho my god after two day suffering I can finally running dota2 on my Debian with xmonad + radeon driver (and not the cursed driver fglrx).

I use the -fullscreen option with the video options in the game "use the current resolution of my screen".

[I use this xmonad config as base](https://github.com/jelly/Dotfiles/blob/master/.xmonad/xmonad.hs)

**Comment by gdrewb-valve** [comment]
This doesn't appear to be a Reborn issue, as was decided for #359.  Is there a reason this should stay open?

**Comment by buhman** [comment]
This looks like a duplicate of #359; if we feel like this is entirely xmonad's fault, then this should be closed I think.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't seem to be a Reborn issue.

**Comment by engywook** [comment]
@gdrewb-valve @danginsburg since you closed this. Any hints what the issue might be with the Window Manager, xorg, whatever if I get the time/itch to take a look at herbstluftwm myself? The patch released at 11 Oct made this issue appear for me. It may also have been caused by some Arch Linux update though. It has been too long to recall. I am also affected by #360 which makes dota kind of annoying to play currently.

**Comment by gdrewb-valve** [comment]
It's hard to say what the problem might be as we only suspect that it's the WM at fault since things work fine on many other WMs.  It could be the same underlying issue as #360 so if you're familiar with gdb looking at whether things are hanging in SDL would be a good thing to check.

**Comment by engywook** [comment]
bt dota thread:
https://gist.github.com/engywook/60e4e2d5002864a9da0caa42545a8ea5

info threads:
https://gist.github.com/engywook/df95e7c2f4a06b97d710b40cbc10413a

bt of some locked threads & SDLAudio:
https://gist.github.com/engywook/7c9c4395327fa64f0ad276436506b4f4

Anything useful? It's kinda hard without debug symbols. ;-)

**Comment by gdrewb-valve** [comment]
It doesn't appear to be stuck in SDL like it would show for #360.  That makes it much harder since it's unclear if any threads are misbehaving or not.  There are a couple of threads waiting in the OpenGL renderer, which may be totally normal.  Dan, does anything jump out at you?  We probably won't be able to get any more without actually reproing it here at Valve, which will be a long while off.

**Comment by engywook** [comment]
And like I mentioned earlier this used to work before Oct 12.
