### ISSUE TITLE
[Linux] game freeze when I try get to menu when play match (after latest patch)

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#557]
Hi.

After latest patch I get many Dota 2 issues. One biggest is freezing game when I play match and try look at menu (I dead and want to check to main menu for chat or etc). When I click on icon menu (this is left up corner) game instant freeze. I cant anythink, game not response. I cant alt+tab, I cant alt+f4, all is freeze only mouse coursor and music works.
Only hope is killing xserver or press alt+f4 and next press F1, F2 to go into tty and going back to graphic enviroment F1,or F2. Now I see desktop with window (dota2 no response, close it?) somethink like that. I say yes, and game is closing. Now I can start it again.

Also game crash in many times, eg. when I reconnect to game after this freeze, game crash few times. But in main case work, I play 5-6 match and get two crash.

My steam PC spec:
https://gist.github.com/xpris/a9c05d39418dfd7c689b

**Comment by gdrewb-valve** [comment]
Having the whole system lock up suggests that the video driver may not be working properly, you may want to try different AMD drivers.

**Comment by AngryPenguinPL** [comment]
Maybe, but before latest patch dota2 reborn work fine. Only now I have this issues.

BTW. I use latest Catalyst 15.9 driver.

**Comment by gdrewb-valve** [comment]
Changes in Reborn could be triggering new code paths in the drivers.  Generally operating systems aren't supposed to allow applications to lock up the system even if the applications aren't well-behaved, but it's also possible it's something unusual that Reborn is doing.

**Comment by munraqnb** [comment]
Same here, running debian jessie and nvidia prop. drivers.

**Comment by ghost** [comment]
Can confirm that too, but running nvidia prop with Debian testing. It's the same kind of lag/hang  described in #558.

**Comment by gdrewb-valve** [comment]
If I read it correctly the original report here is a system hang that does not go away.  A multi-second delay would be a different thing.

**Comment by ghost** [comment]
Don't know exactly. The author isn't mentioning waiting for it to come back. I didn't tried alt+tabing, but I will next time. Maybe we need some more informations on the authors side.

**Comment by Eignar17** [comment]
is game instant freeze my sistem ubuntu 15.04 is new update is slow in menu is fps 5-10 in game good in menu is problem is slow. my video card intel i5  and You navigate the menu closes suddenly @triage-valve

**Comment by AngryPenguinPL** [comment]
Hey.

I apologize for not accuracy. English is not my native language and expressed myself very imprecise.

Short and to the point:
1. Game hangs when I try to enter the menu.
2. System is not hangs, because I can go to tty (ALT + CTRL + F1 or F2) and come back to desktop and close the game or kill the Xserver and log in again.

Maybe I can make video?

**Comment by gdrewb-valve** [comment]
I think that description is fine, a video isn't necessary.  We'll see if we can get the same behavior.

**Comment by presianbg** [comment]
Some freezes here on Fedora 22 (nvidia optimus technology). It happens for 5-10  sec and then it's ok. It was ok before latest patch.

**Comment by khill** [comment]
I can reproduce this consistently as well.  When I am playing a game (bot game or online) the application freezes when I click the "return to dota 2 home screen" button in the top left.  The video freezes but the sound continues.

The only way I can get it working again is to switch to a different virtual desktop and then switch back to dota2.  At that point, it unfreezes.  Switching between an in-process game and the dota2 home screen causes this every time and switching desktops fixes it.  I did have to kill -9 the process once but didn't have to restart X or reboot.

System info is here: https://gist.github.com/khill/38683fbee5a77e8b9d03

**Comment by Eignar17** [comment]
is bugs

File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)

/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1933):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!

File error loading resource header "panorama/images/textures/startup_background_logo.vtex_c" (Error: ERROR_FILEOPEN)

No valid vcs file found for shader gaussian_bloom_blur.vfx

**Comment by gdrewb-valve** [comment]
The resource error messages are interesting, they may point to a different issue.  Removing the drivers marking for now.

**Comment by gdrewb-valve** [comment]
Does the Oct. 16th update help?

**Comment by drewferagen** [comment]
I just tested this with the new update and this issue seems to still be happening for me.

To test it, I created a local bot game, whenever I hit the upper left button to go to the main UI. Now it will eventually go to the dashboard. However it completely seizes up besides mouse and sound for 11-35 seconds. 

The last thing in the log is:
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_DASHBOARD

This feels related to the issue where the game does the same kind of freeze up when it loads the scoreboard as well as when I scroll through my items in the armory.

Anyway, let me know if you want some logs or where they can be found, or other info you want.

Edit: I don't know if it is relevant but I have and AMD cpu fx-8350.

**Comment by gdrewb-valve** [comment]
Thanks for trying it.  We have another slowdown issue with switching to the main menu and I wanted to confirm that it's still present.

**Comment by Eignar17** [comment]
is parcial patch is create complete patch in linux @gdrewb-valve 

File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)
/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1933):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!
File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)
/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1933):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!
PNG load error Interlace handling should be turned on when using png_read_image
PNG load error Interlace handling should be turned on when using png_read_image

**Comment by gdrewb-valve** [comment]
I believe that's actually an old error, I don't think it's causing new problems.

**Comment by khill** [comment]
I'm still seeing the issue after today's patch.  My screen freezes up any time I switch between a game and the main menu screen.  The music/sound doesn't freeze and my mouse cursor still moves.  However, all video just freezes up for 5-20 seconds.

**Comment by Eignar17** [comment]
@gdrewb-valve  bug is big will require more than 3 patches

**Comment by ghost** [comment]
I'm glad to see that this issue has already been reported and is receiving attention as I am getting it as well. I can also confirm it happens with both the proprietary AMD drivers and the RadeonSI drivers.

**Comment by Eignar17** [comment]
is bug loading game and menu is big bugs

**Comment by tiburcillo** [comment]
Hi, I also have the same issue. Once you're in game and you try to get back to the menu by clicking the button in the top left corner then entire game freezes for 10-20 seconds. 
Issue was introduced a week ago and the recent soaring cache patch did not solve the issue.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.2 Rafaela (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2-3.dmz.1-liquorix-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.6.2)

```
Driver Version:  3.0 Mesa 11.1.0-devel (git-afff809 2015-10-16 trusty-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7946 Mb

**Comment by jacobcraner** [comment]
I am having a similar experience, trying to change tabs in the menu or entering the menu from a match freezes the game for about 20 seconds. When online, this disconnects the user from the match. This happens on all my machines, running Ubuntu 14.04 with either AMD and Nvidia cards in them and different drivers provide no change.

**Comment by danginsburg** [comment]
We are working on a fix for this and are definitely aware of the problem.

**Comment by danginsburg** [comment]
We have a fix for this, it will be in the next Dota 2 update.

**Comment by khill** [comment]
Awesome.  Thanks!

**Comment by danginsburg** [comment]
Fixed in Oct. 21st update.
