### ISSUE TITLE
[Linux] When game is end and should see score game very laggly from fewer seconds (after latest patch)

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#558]
Hi.

After latest patch I get many laggly in dota2. In many case after we win or lose and main building is destroing. I should see score window or compendium window I get big lag. Music works, coursor works but game is freeze and after 5-15 seconds game lag is gone.

This issues I have also in other game parts. I play and I get this big lags (this is strange). This look like all game freeze, but after few second working fine.

My Steam PC Spec:
https://gist.github.com/xpris/a9c05d39418dfd7c689b

**Comment by munraqnb** [comment]
Same here, running debian jessie on nvidia prop. drivers.

**Comment by ghost** [comment]
Can confirm that one too. I have it when I try to enter the menu from a game too, hangs for multiple seconds then.

Debian testing on Nvidia 340.93.

**Comment by Eignar17** [comment]
is problem in my ubuntu 15.04 and intel i5 drivers

**Comment by drewferagen** [comment]
Same here. Ubuntu 15.04 with Nvidia 355.11

I've noticed that the Armory is also very laggy when I try to scroll through, which started happening about the same time. before it was smooth as butter.

**Comment by khill** [comment]
Same thing here.  See comments in #557 and #567.

Specs: https://gist.github.com/khill/38683fbee5a77e8b9d03

**Comment by bykbpa** [comment]
I have same issue on ubuntu 14.04 with flgrx driver. Also, I have lag and freezes when I click on tabs on main menu and also sometimes dota crash.

**Comment by presianbg** [comment]
same here, on Fedora 22 with optimus (nvidia). It was ok before the last patch.

**Comment by Eignar17** [comment]
is parcial patch is create complete patch in linux 

File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)
/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1933):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!
File error loading resource header "panorama/images/heroes/selection/npc_dota_hero_default_png.vtex_c" (Error: ERROR_FILEOPEN)
/home/buildbot/buildslave/source2_dota_rel_linuxsteamrt64/build/src/rendersystem/texturebase.cpp(1933):ResourceHandleToData( panorama/images/heroes/selection/npc_dota_hero_default_png.vtex ) failed! Falling back to error texture!
PNG load error Interlace handling should be turned on when using png_read_image
PNG load error Interlace handling should be turned on when using png_read_image

**Comment by AngryPenguinPL** [comment]
This issues is fixed now on my Linux rig. Looks like you fixed it in same time as this issue https://github.com/ValveSoftware/Dota-2/issues/557

**Comment by gdrewb-valve** [comment]
Anybody else still having problems?

**Comment by khill** [comment]
No, I'm good.  This last patch fixed all my issues.  Thanks.

**Comment by bykbpa** [comment]
Now everything works fine.

**Comment by gdrewb-valve** [comment]
Thanks all, closing.
