### ISSUE TITLE
[Linux] Big ping in all servers and huge internet usage when I start game 

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#559]
Hi.

When I play in Dota2 (source1) on EU servers I get 50-60 ping.
Now in reborn I have 90-120 pings/

But after I start game, I get ping in all servers about 500-800ms. I show on internet usage and I get 100% download use.  When I close game, this download use drop to 0%. When I start it agin, ping still is huge.
This is some in game, because this high ping I get from few min and next it gone.
If I start game when I get this huge ping I get laggs from 2-3 minuts and next lags gone.

My Steam PC spec:
https://gist.github.com/xpris/a9c05d39418dfd7c689b

**Comment by gdrewb-valve** [comment]
Can you get a network capture or some other information that might help pin down what's going on with your network?

**Comment by AngryPenguinPL** [comment]
Tomorrow I'll try to use a net capture, but I'm not expert on the subject :)

For now I try doto in my second computer - old notebook with Ubuntu 15.04 and looks like is the same :/  Here also my Steam Spec from this notebook: https://gist.github.com/xpris/ec9868d59d5357a9fdfd

I recorded small video from this issues on my notebook:
https://youtu.be/lihCc-j-qls

**Comment by gdrewb-valve** [comment]
Thanks for trying, there shouldn't be the steady 250KB/s usage you're seeing and the larger team would like to try and figure out what's going on.

**Comment by Eignar17** [comment]
is my ubuntu 15.04 is lag and close ip the steady 600KB/s

**Comment by gdrewb-valve** [comment]
Was anybody able to get a net capture of the net traffic?

**Comment by AngryPenguinPL** [comment]
What apps I should use for this?

Maybe terminal tcpdump (default in Ubuntu) and save output to txt file?

**Comment by gdrewb-valve** [comment]
tcpdump is a good place to start.  Wait until the main menu has reached a steady state (a minute?) and then capture ten seconds or so.  With nothing else running to use net traffic hopefully the capture won't be too enormous.

**Comment by AngryPenguinPL** [comment]
I upload output as txt file here:

http://speedy.sh/s9gAR/output.txt

I start capture about one minute after start dota.

**Comment by gdrewb-valve** [comment]
Thanks, the larger team is looking at the trace now.

**Comment by gdrewb-valve** [comment]
The tcpdump information was useful but not completely conclusive as to what is happening.  It looks like some localized text files may be getting downloaded too often and the team has added some more console spew that will catch that.  The next update will have the spew, then you can try it again and see if you see console spew about repeated downloads.

**Comment by gdrewb-valve** [comment]
The Oct. 16th update has the new spew so if you can try it again and post the console spew that should help us make progress.

**Comment by AngryPenguinPL** [comment]
Ok, I trying DOta2 now and looks like this issues is gone. When I start dota2 i see main menu and my internet usage go to 80-90% and after 2 seconds drop to very small usage about 0-5%.  Look at this screenshot with my net usage:
![zrzut ekranu z 2015-10-18 16 49 03](https://cloud.githubusercontent.com/assets/3121142/10564565/15d60396-75b9-11e5-83bc-7f44424adb52.png)

So looks like now woking fine, and my ping now is about 90 ms.

Thanks :)

**Comment by gdrewb-valve** [comment]
Thanks for the update.  Is anybody else seeing continuing large net usage (there will be a small amount) at the main menu?

**Comment by gdrewb-valve** [comment]
Closing as this appears to be addressed.
