### ISSUE TITLE
[Linux] Chat wheel bug when used with keybinding with modifier key.

### ISSUE THREAD

**Issue by MaikuMori** [ValveSoftware/Dota-2#560]
> I'm almost 100% sure I've reported this before, but I couldn't find it in open/closed issues.

If you have chat wheel bound to something like `ALT-MOUSE4` when you bring up chat wheel and then release ALT/modifier key before releasing mouse key the chat wheel stays on the screen even after releaseing mouse.

Steps:
- Press ALT-MOUSE4 together.
- Release ALT, hold MOUSE4.

This is quite annoying since your mouse gets locked to the chat wheel and prevents you from other actions. The only way to get rid of the chat wheel is to press `ALT-MOUSE4` again and make sure to release the keys in the right order.

This is probably not limited to Linux client.

**Comment by gdrewb-valve** [comment]
You're correct, this does happen on Windows too.

**Comment by gdrewb-valve** [comment]
This also happens in Source 1 Dota 2.  The larger team never fixed it there so who knows when it'll get fixed, but I've passed it on.
