### ISSUE TITLE
Dota segfaults after switching to the watch tab

### ISSUE THREAD

**Issue by ArnaudAndre** [ValveSoftware/Dota-2#561]
Around 1 second after switching to watch tab the game crashes.
Happens 100% of the time.
Recent regression. I'm pretty sure i used the watch tab this week end.
Rest of game is perfectly fine afaik.

[console log](https://gist.github.com/ArnaudAndre/1742e9b4a955beccc668) doesn't show anything interesting but has a crash id
[system specs](https://gist.github.com/ArnaudAndre/12d5204c9347ccc3e94b)

**Comment by neko-kai** [comment]
Happens for me too.

**Comment by superoraculus** [comment]
Originally posted here: http://dev.dota2.com/showthread.php?t=183178

"
Me too. Only when I click Watch tab (from what I've seen so far).

uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux

dmesg:
[11666.629627] dota2[4740]: segfault at 7f800000000a ip 00007f81377b395e sp 00007fffbb4f3950 error 4 in libtcmalloc_minimal.so.0[7f813779e000+21000]

Dota version:

Version: 1114
Gameplay Version: 6.850000
"

**Comment by danginsburg** [comment]
We have this confirmed and repro'd.  We are working on a fix.

**Comment by Leproide** [comment]
Ops, sorry i see now this post...

OS: Fedora 22
WM: GNOME Shell
Kernel: x86_64 Linux 4.1.10-200.fc22.x86_64
CPU: Intel Core i7-2600K CPU @ 3.8GHz
GPU: AMD/ATI Barts XT [Radeon HD 6870]

Console log when the client starts:
http://leprechaun.tk/zerobin/?8448452ad4484a3a#lfHx7Rw73bY+A8jb47EWfW+u1dpuMgxJmmc303W9MI4=

lsusb (only pertinent):
Logitech, Inc. G930
ROCCAT Kone+ Mouse
Genesys Logic, Inc. Logitech G110 Hub
Logitech, Inc. Gaming Keyboard G110 G-keys
Logitech, Inc. Gaming Keyboard G110

(https://github.com/ValveSoftware/Dota-2/issues/563)

Dump file:
https://anonfiles.com/file/e58046a8044bdc8cea74f8bfa260f40f

I check the game files from steam and are validated

**Comment by m1kc** [comment]
Same problem. My system info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.51-1-lts
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.6.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 11,54" x 6,46"  (13,19" diag)
                                            29,3cm x 16,4cm  (33,5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  5859 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  48594 Mb
    Largest Free Hard Disk Block:  3012 Mb

Installed software:

Recent Failure Reports:
    Mon Oct  5 23:44:37 2015 GMT: file ''/tmp/dumps/assert_20151006024433_91.dmp'', upload yes: ''CrashID=bp-a8bcbbe5-786d-407a-bb35-6623d2151005''
    Mon Oct  5 23:44:37 2015 GMT: file ''/tmp/dumps/assert_20151006024431_3.dmp'', upload yes: ''Discarded=1''
    Fri Oct  9 10:42:41 2015 GMT: file ''/tmp/dumps/crash_20151009130058_2.dmp'', upload yes: ''Discarded=1''
    Fri Oct  9 10:42:42 2015 GMT: file ''/tmp/dumps/crash_20151009121735_2.dmp'', upload yes: ''Discarded=1''
    Fri Oct  9 10:42:59 2015 GMT: file ''/tmp/dumps/crash_20151009134258_2.dmp'', upload yes: ''Discarded=1''
    Fri Oct  9 10:43:02 2015 GMT: file ''/tmp/dumps/crash_20151009134250_3.dmp'', upload yes: ''Discarded=1''
    Tue Oct 13 22:56:16 2015 GMT: file ''/tmp/dumps/crash_20151014015308_1.dmp'', upload yes: ''Discarded=1''
    Tue Oct 13 22:57:40 2015 GMT: file ''/tmp/dumps/crash_20151014015714_1.dmp'', upload yes: ''Discarded=1''
    Tue Oct 13 23:01:03 2015 GMT: file ''/tmp/dumps/crash_20151014015959_1.dmp'', upload yes: ''Discarded=1''

```

**Comment by ghost** [comment]
Same here: http://pastebin.com/E35WzjGJ .

**Comment by antekone** [comment]
Same here, http://pastebin.com/wniEdxZ4

**Comment by gavindi** [comment]
I played a few games and then went to watch and it worked! I then exited the Dota 2 client and re-ran the client and went to the watch tab and it crashed again. It seems to work if you play a game first but only sometimes.

**Comment by dietrmat** [comment]
Same here: http://pastebin.com/9XRpHdfv

**Comment by superoraculus** [comment]
Just a pointer: No need for "same here" posts. Valve is working on a fix already, as per below:

"danginsburg commented 2 days ago
We have this confirmed and repro'd. We are working on a fix."

BTW Valve, that must be a hell of a bug huh, and just when major tournaments are in progress.. Sigh :/

**Comment by danginsburg** [comment]
We have a fix for this issue, it will be in the next update.

**Comment by sagarkarira** [comment]
When will the next update be out. I wanted to watch the MLG. It is starting in 15 minutes.

**Comment by danginsburg** [comment]
The fix has been released.  Closing bug.

**Comment by tvvignesh** [comment]
@danginsburg It was working fine for me till today. But I get this bug for last 2 to 3 days. 
Running DOTA 2 on Lubuntu 17.10 (Intel Core i5 processor with Intel graphic card, 8gb ram)

**Comment by kisak-valve** [comment]
Hello @tvvignesh, given the years separation, your issue is most likely unrelated to the issue that was tracked here.

Please open a new issue report with your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in that issue report, any related CrashIDs or minidumps (commonly found in /tmp/dumps) related to your issue, and the console log from Dota 2 (add -con_logfile to the game's launch options, reproduce the issue, and include <dota 2 install dir>/game/dota/console.log in the issue report).
