### ISSUE TITLE
[Mac] Crash on loading screen nearly every game and on hero pick screen occasionally

### ISSUE THREAD

**Issue by Nocswary** [ValveSoftware/Dota-2#565]
When loading into the game it loads quickly and then during the time when other players load the game crashes at some point unless they load quickly enough before it happens. Generally occurs at 2:45 left to 2:00 left for players to load but can be lower. I can usually reconnect fast enough but if players still have not loaded by the time I get in the crash can occur again.
The client will automatically close and a crash log is displayed saying "dota 2 osx has quit unexpectedly".

System specs:
Macbook pro retina Early 2015 
Processor:    2.7 GHz Intel Core i5
RAM:            8 GB 1867 MHz DDR3
Graphics:     Intel Iris Graphics 6100 1536 MB

Unfortunately I cannot attach one of the crash logs as "Something went really wrong, and we can't process that file" comes up every time I try and upload a txt or docx file so I had to upload it to file-upload: http://en.file-upload.net/download-10971981/dota2_2015-10-13-215725.txt.html

**Comment by gdrewb-valve** [comment]
The GPU is hanging and resetting.  This could be an Apple OpenGL driver problem or something weird that Reborn is doing.

Application Specific Signatures:
Graphics hardware encountered an error and was reset: 0x00008813

Thread 9 Crashed:
0   libsystem_kernel.dylib              0x00007fff988fa0ae __pthread_kill + 10
1   libsystem_pthread.dylib             0x00007fff89f22500 pthread_kill + 90
2   libsystem_c.dylib                   0x00007fff9978b37b abort + 129
3   libGPUSupportMercury.dylib          0x00007fff8d91be5c gpusGenerateCrashLog + 158
4   com.apple.driver.AppleIntelBDWGraphicsGLDriver      0x00000000890cc5ac gpusKillClientExt + 9
5   libGPUSupportMercury.dylib          0x00007fff8d91d361 gpusSubmitDataBuffers + 511
6   com.apple.driver.AppleIntelBDWGraphicsGLDriver      0x0000000088c322ba IntelCommandBuffer::getNew(GLDContextRec*) + 48
7   com.apple.driver.AppleIntelBDWGraphicsGLDriver      0x0000000088d0cae1 intelSubmitCommands + 171
8   libGPUSupportMercury.dylib          0x00007fff8d921674 gldFlushObject + 112
9   GLEngine                            0x0000000088b964d3 gleEvaluateTextureImageChange + 396
10  GLEngine                            0x0000000088a60097 glTexImage2D_Exec + 728
11  libGL.dylib                         0x00007fff9a90846d glTexImage2D + 77
12  libscaleformui_4_gl.dylib           0x00000000924d7ac3 Scaleform::Render::GL::Texture::Upload(unsigned int, unsigned int, Scaleform::Render::Imag

**Comment by danginsburg** [comment]
I don't have access to the Macbook pro retina Early 2015.  Can anyone else out there confirm this GPU hang?  If I get at least another confirmation this is not an issue specific to your system I'll open a Radar with Apple.

**Comment by danginsburg** [comment]
Interestingly, this callstack is similar to bug #534 in that it is coming from the scaleform texture upload, although it is a completely different driver (Intel BDW in this case, NVIDIA in bug #534).

**Comment by danginsburg** [comment]
I mentioned this issue in the same Radar filed for bug #534.  I will update if we hear anything from Apple.  Other users: please post if you encounter the same issue with your system specs.  Closing for now.
