### ISSUE TITLE
[Linux] voice chat cuts off when window loses focus

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#566]
Whenever I switch away from the game window, any voice chat (apparently both directions) is cut off. I have desktop sound enabled, and the rest of the sounds keep playing.

I'm running KDE on Arch, compositing disabled; the disparate behavior of music and voice seems to indicate a specific bug in the handling of the voice streams.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.

**Comment by chrylis** [comment]
@gdrewb-valve This might be related to #360 if loss of focus is somehow disabling the network thread. I haven't heard from any Windows users about either of these, so they do look like they may be Linux-specific.

**Comment by gdrewb-valve** [comment]
The loss of focus shouldn't affect networking in Reborn.  If there's something specific to Linux that shuts things off without focus it could be OS-specific but that would be very strange.

Regardless the larger team has it on their list to investigate.
