### ISSUE TITLE
[Linux] keyboard works weird with non-US layout

### ISSUE THREAD

**Issue by kvblinov** [ValveSoftware/Dota-2#569]
ive seen instructions telling to add "input_button_code_is_scan_code" to launch options but it doesnt work for me. specifically problem is not recognizing space bar and mistaking '1' for 'RETURN'
I have ubuntu 14.04 LTS

**Comment by gdrewb-valve** [comment]
What language are you running in?  What keyboard layout are you using?  Are you changing keyboard layouts at any time?

**Comment by kvblinov** [comment]
I have an English-Russian keyboard, changing layouts doesnt affect anything

**Comment by gdrewb-valve** [comment]
What language are you running in, English or Russian?  Do you switch languages?  Does the '1' key work properly in chat?

**Comment by kvblinov** [comment]
Running in English or Russian has no effect on the problem, I tried both. '1' key acts as return but doesnt close input form and sometimes doesnt remove whats written.

**Comment by gdrewb-valve** [comment]
So the '1' key acts as return even when typing in chat?  That usually means that the character returned from the OS is not '1' so Reborn doesn't have any way of knowing it's supposed to be '1'.  Do you have issues in any other programs?

**Comment by kvblinov** [comment]
I guess I explained badly. In almost every dota chat (party chat, game chat etc) I press '1', it shows up as I would entered 1. Then I press '1' key the second time and dota thinks I pressed 'RETURN' so it prints out my message which is '1'. But input form is still up and it contains the string '1'. Concerning space - it works in chats but when I try to bind it it just shows blank space and that binding doesnt work. (I have no issues anywerhe else)

**Comment by kvblinov** [comment]
Ok, I now figured that adding input_button_code_is_scan_code makes dota not see even a,b,c... keys

**Comment by gdrewb-valve** [comment]
Can you add -input_message_spew and -console to your launch options, then open the console when in the menu and press keys like space, 1, a and b and then copy in the spew here?

For example, here's the spew I get when I press those keys on a regular US English keyboard:
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=32 sdlscancode=44 SDL_GetKeyName='Space' buttoncode=66 buttonname='SPACE' ButtonCode_GetLocalKeyNameUTF8='Space'
SDL:  got SDL_TEXTINPUT
TEXTINPUT ' '
SDL:  got SDL_KEYUP
KEYUP (keyc) 66 (SPACE)
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=49 sdlscancode=30 SDL_GetKeyName='1' buttoncode=2 buttonname='1' ButtonCode_GetLocalKeyNameUTF8='1'
SDL:  got SDL_TEXTINPUT
TEXTINPUT '1'
SDL:  got SDL_KEYUP
KEYUP (keyc) 2 (1)
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=97 sdlscancode=4 SDL_GetKeyName='A' buttoncode=11 buttonname='a' ButtonCode_GetLocalKeyNameUTF8='A'
SDL:  got SDL_TEXTINPUT
TEXTINPUT 'a'
SDL:  got SDL_KEYUP
KEYUP (keyc) 11 (a)

**Comment by gdrewb-valve** [comment]
Closing pending more info.
