### ISSUE TITLE
Menu/dashboard slowdown/bug(?)

### ISSUE THREAD

**Issue by Gab0** [ValveSoftware/Dota-2#571]
Last updade broke the menu/dashboard of the game on my system. I start the game and it's ok, choose a game to watch, the map is loaded and I can spectate flawlessly. But if I fallback to the menus while the game is happening, it takes 30 full secs to load the dashboard/dota's social network, and suddenly everything is unstable and laggy... returning to the game also takes forever, but ingame fps is intact.
I use latest nvidia proprietary drivers. Before the update everything was fine.

**Comment by YauhenVasileusky** [comment]
I experience the same issue + everything freezes when I switch to different tabs in main menu(Heroes/Watch/Learn/etc.)

My configuration:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-30-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 355.11
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x13c0
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 21.77" x 12.24"  (24.96" diag)
                                        55.3cm x 31.1cm  (63.4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  32045 Mb

**Comment by Staban9** [comment]
Hi there bro, I encountered similar problems after downloading the last update which was released 16/10/15, everything became unresponsive like when clicking the heroes, watch, armory, treasury, play, everything became laggy. It's totally unplayable - the pub and practice with bots match. I already did everything including verifying cache, even reinstalling DOTA. It always takes long to load up, and takes a while to proceed from the dota loading screen to the dashboard. And like what you said, the mouse style changes as well. Then after that it freezes. My FPS has been so unstable dropping as low as 1FPS then 10 then 40 then 30 then 50 then 1 again, and so on. Have you got any information about this? Thanks!!
My computer specs
Processor: Intel(R) Core(TM) i7-4510U CPU@2.00GHz 2.60GHz RAM: 8GB System Type: 64-bit OS x 64-based processor

**Comment by gdrewb-valve** [comment]
@Gab0, your issue sounds like #557, is that correct?

@YauhenVasileusky, you appear to have a different issue and may want to open a separate item.

**Comment by Gab0** [comment]
Basically it is #557, but while he plays 5-7 games, my DOTA freezes right on.

**Comment by gdrewb-valve** [comment]
There's definitely an issue with switching from the game to the main menu and it can occur right away, it's being investigated right now so #557 is sufficient.  Closing this.
