### ISSUE TITLE
Cannot leave local chat

### ISSUE THREAD

**Issue by zbstof** [ValveSoftware/Dota-2#572]
I cannot leave location-specific groupchat ('Kiev' in my case)
Clicking 'leave' only moves focus to the chat to the right (or first, if I leave rightmost chat)
The chat contains no people.
See attached screenshot
![2015-10-14_00001](https://cloud.githubusercontent.com/assets/1374723/10508238/76aac450-732e-11e5-8c45-f5a77cbadddc.jpg)
My guess it's a relic from buggy days of reborn.
System info:
zbstof@Stas-MacBook-Pro:~$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27
zbstof@Stas-MacBook-Pro:~$ uname -a
Darwin Stas-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by gdrewb-valve** [comment]
Probably not Linux / Mac specific.

**Comment by gdrewb-valve** [comment]
You're not supposed to have two Kiev channels either, the larger team is going to take a look. They also suggested that as a workaround you could try clicking the down caret next to Kiev and then clicking the X to close the tab.

As this isn't a Mac issue it won't be tracked here.  However if this happens regularly and you have consistent repro steps please post them and I'll pass them on.

**Comment by QuiteSeriousGuy** [comment]
This issue is still standing. I have over 10 tabs with the same region, can't exit because I'm the last one as my colleagues have said. 

![image](https://user-images.githubusercontent.com/3491904/28746475-bc334f12-74bf-11e7-9915-5cb03b5c5b54.png)
