### ISSUE TITLE
My display suddenly became cropped and zoomed in, I can't change it. Cant see "Apply" button

### ISSUE THREAD

**Issue by jirupu** [ValveSoftware/Dota-2#573]
Here's what I'm talking about

![screen shot 2015-10-15 at 8 49 12 pm copy](https://cloud.githubusercontent.com/assets/15142384/10515134/8554ca0e-7384-11e5-86e6-843348955292.jpg)

It won't allow me to change the resolution as i can't click on APPLY!! 

AND !!

I can't Alt+tab back in to the game even it's set on Desktop-friendly monitor. :'( It's just blank always. PLEASE HELP!!

I'm a mac user, MBP mid 2012, i5 16gb RAM, 500gb hdd.OSX El Capitan

my email is jerpbremmsangalang@gmail.com please somebody help.. I'm low prio right now because of this!! T_T

**Comment by jirupu** [comment]
![image](https://cloud.githubusercontent.com/assets/15142384/10515054/1ec433ec-7384-11e5-8b1e-ac10e4dee1df.png)

**Comment by ArnaudAndre** [comment]
Not clue what's happening on your comp but as a temporary fix you can force a specific size of the game's window with command line parameters.
In steam, right click dota, _properties_, the _general_ tab as a _set launch options_ button : type `-w 1920 -h 1080` (tweaked to your monitor's dimensions).

edit : thinking about it, do you have a retina display ?

**Comment by jirupu** [comment]
YOU SIR HAVE SAVED MY LIFE!!! THANK YOU SO MUCH @ArnaudAndre !!! <3 

![screen shot 2015-10-15 at 11 59 52 pm](https://cloud.githubusercontent.com/assets/15142384/10519564/dd5d80d8-7398-11e5-95f3-0ba7a444df06.png)

The only prob now is that i can't cmd+tab unlike before, unless i swpe 4 fingers to switch screens. But it's all good as long as I can play! THANK YOU AGAIN!! <3

**Comment by gdrewb-valve** [comment]
Probably related to #546.

**Comment by danginsburg** [comment]
I have tried everything I can think of to repro this, but no luck yet.  If anyone has any detailed repro instructions please post them.

**Comment by gdrewb-valve** [comment]
Is this still happening?
