### ISSUE TITLE
Cant resume dota 2 after apple-tab.

### ISSUE THREAD

**Issue by streamfx** [ValveSoftware/Dota-2#574]
I often apple-tab to different apps while playing and come back to dota2.  Now when I leave dota2 and goto finder or any other app I cannot get back to dota2.  I hear the sound and cursor but nothing else.  NO graphics, etc.

I have to force quit dota2 and re-launch.

MacBook pro 15" 2015.  OSX 10.11

AMD Radeon R9 M370X 2048Mb

**Comment by ghost** [comment]
3 finger swiping right or left to get back works for me in this instance

**Comment by gdrewb-valve** [comment]
Is this different from #546?

**Comment by streamfx** [comment]
nope.. same thing :)

**Comment by gdrewb-valve** [comment]
Closing duplicate.
