### ISSUE TITLE
Dota 2, weird in-game problem

### ISSUE THREAD

**Issue by manolos69** [ValveSoftware/Dota-2#575]
If you watch this video https://youtu.be/ZKoAvv1M0_o youll see that there are no names and numbers on top of the characters. Also i cannot see anything in the console. Trying to go to the menu while i play makes me lag or disconnects me and when I click WATCH, the game closes.

Fresh install Arch Linux x86_64 4.2.3-1
latest nvidia 355.11-1 gtx 750ti 2gb
steam beta xfce

Please help. Thank you for your time.

EDIT: Running steam and dota from terminal http://justpaste.it/ocii (crash after clicking WATCH). Tried to verify and/or delete everything, including config files of steam in .local

steam system info http://justpaste.it/ocki

**Comment by danginsburg** [comment]
Try installing the ttf-liberation font package.

**Comment by manolos69** [comment]
Thank you. That fixed the empty console the the numbers-names on top of the characters. Two issues remaining.

When i press \ for the console to show up i still get black boxes on my stats, items etc but its a small issue cause i dont use console much.
The second and more serious problem is that i cannot watch games from the WATCH tab and that i cannot safely open the menu during the game cause most of the time it will crash.

**Comment by danginsburg** [comment]
The watch tab issue is known and is covered in #561.  We have a fix coming in the next update.  Closing out this issue.

**Comment by manolos69** [comment]
Ok thank you very much

**Comment by manolos69** [comment]
Everything is ok now after the update!
