### ISSUE TITLE
Watch tab / live games no longer sorted by MMR

### ISSUE THREAD

**Issue by vith** [ValveSoftware/Dota-2#577]
The live games in the watch tab used to be at least somewhat sorted by MMR. I used to see 5-6k average MMR games listed there. Now it's 1.5-3k average MMR games.

Could this be a regression caused by the fix for #561?

![screenshot from 2015-10-16 16-13-11](https://cloud.githubusercontent.com/assets/3265539/10553518/ff218100-7420-11e5-8c6f-8a16437be11c.png)

System info: https://gist.github.com/vith/dc3a41a0af6637bfb863

**Comment by gdrewb-valve** [comment]
This wasn't intentional and is supposedly fixed, are you still seeing it?

**Comment by vith** [comment]
It's good now. Thanks :thumbsup:
