### ISSUE TITLE
[Linux] After patch, must re-validate 4000+ files before I can find dota 2 game coordinator

### ISSUE THREAD

**Issue by b-jam** [ValveSoftware/Dota-2#578]
Just started playing again yesterday, couldn't find game coordinator, hit "validate game cache" , ~4600 invalid files, had to redownload GBs of data.

New patch today,  exactly the same deal.

Never had this issue previously (1month ago+)

**Comment by gdrewb-valve** [comment]
I'll pass this on to the Steam folks.

**Comment by gdrewb-valve** [comment]
Can you post your Steam system information?

Can you put up a gist of your Steam content_log.txt?  If you have a standard Steam install it'll be something like ~/.local/share/Steam/logs/content_log.txt

**Comment by gdrewb-valve** [comment]
Closing for now as we'll need the logs to make progress.
