### ISSUE TITLE
[Linux]Cannot paste string in game

### ISSUE THREAD

**Issue by monororo** [ValveSoftware/Dota-2#579]
Linux distribution:arch linux
Window manager:openbox
Graphics card:NVIDIA GEFORCE GT 645M

During DOTA source 1 engine, I can input words from other programs (such as leafpad) and select & paste in the game to communicate with others because of failed input Chinese in game. But in Source 2, this way can be done in main menu. If is in a match, pressing ctrl+v gets nothing.

**Comment by ArnaudAndre** [comment]
Yeah it was fixed after #494 but a recent update broke it again.

**Comment by gdrewb-valve** [comment]
I don't think this ever worked (the fix in #494 was for the console, not in-game chat).  A future update will fix it.

**Comment by gdrewb-valve** [comment]
I believe the fix just went out.
