### ISSUE TITLE
[OS X] client crashes instantly on startup if dx11 parameter is set.

### ISSUE THREAD

**Issue by elwl** [ValveSoftware/Dota-2#58]
if dx11 parameter is supplied it should be ignored, but instead it tries to do something.
interesting, as the parameter has no effect in the old client on OS X.

**Comment by davidw-valve** [comment]
I take it this only occurs if the dx11 parameter is supplied and otherwise it's fine? I modified the bug title to be a little clearer.

**Comment by elwl** [comment]
yeah. it'll open the client, black screen, and one second later close.

**Comment by Vuccappella** [comment]
Same here.

**Comment by elwl** [comment]
seems to still handle the param even after today's(june 24) patch

**Comment by gdrewb-valve** [comment]
The crash no longer occurs though, correct?  The game just fails to start?  I'm not sure that's bad behavior since the game can't do what you asked for.

**Comment by elwl** [comment]
no idea what you're talking about by "The game just fails to start". there is no dialogue, just runs the same as before. steam should automatically pull updates for dota 2 reborn right?
launching it from command line returns
```
asdf:game asdf$ ./dota.sh -console -nexon -dx11
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Applications/Steam.app/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198040641046 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198040641046
SteamID:  76561198040641046, universe Public
Setting breakpad minidump AppID = 373300
SteamID:  0, universe Public
Fontconfig warning: "/Users/asdf/Library/Application Support/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/Users/asdf/Library/Application Support/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
AppSystemDict: Error in Connect() of interface 'GameUI011'!
Error: bool CAppSystemDict::LoadSystemAndDependencies(CUtlVector<CAppSystemDict::AppSystemRequest_t> &)():
AppSystemDict: Error in Connect() of interface 'GameUI011'!

asdf:game asdf$ 
```

**Comment by Tele42** [comment]
@elwl I just wanted to check; do you know that dx11 is short for (microsoft) directx 11? This is only available on windows 7 and newer. Dota 2 Source 1 does not react to this launch option because source 1 does not support directx 11 at all.

**Comment by elwl** [comment]
dude i know. the point is that it the param shouldn't even be handled (as it is not on the non-reborn client).

**Comment by elwl** [comment]
yeah you're right, i just failed really hard. i think i was trying to say the other client as in the source 2 beta when i tried it on windows.
