### ISSUE TITLE
[Linux] X.org crash when running DotA 2 with nvidia drivers on Ubuntu 14.04

### ISSUE THREAD

**Issue by Rovanion** [ValveSoftware/Dota-2#580]
As described on [Launchpad](https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-346-updates/+bug/1507113).

Multiple times now I've had graphical glitches leading into a complete system lock of Ubuntu when running DotA 2 with the proprietary nvidia drivers on Ubuntu 14.04. The same thing doesn't happen when running Windows 10. I've also tried with the nouveau drivers from xorg-edgers but couldn't reproduce the bug, but then again it didn't clock up the graphics card from 100MHz and produced about 1fps.

Attached is the nvidia-report-bug-zip produced just after the crash by ssh:ing into the machine and using their tool. I'm also attaching the plain xorg.log for one of the crashes.

When the crash happens the machine becomes completely unresponsive to mouse and keyboard input, ctrl-alt-f1 doesn't have any effect which it usually does. When ssh:ing into the machine I can with htop see that Xorg is consuming all the cpu cycles of one core. I'm also unable to sudo pkill -9 X, it stays running and eventually the whole OS crashes.

**Comment by gdrewb-valve** [comment]
You'll want to report this to NVIDIA also.

**Comment by Rovanion** [comment]
Already by email, but thanks for the pointer. Maximum exposure!

**Comment by Rovanion** [comment]
Updated the BIOS version on my mother board and played two more games, have yet to crash again. Will report back in two weeks with more info.

**Comment by gdrewb-valve** [comment]
OK, closing for now.

**Comment by admshao** [comment]
I'll try that for #515 since it's seems very similar issue.

2015-10-21 13:29 GMT-02:00 Drew Bliss notifications@github.com:
