### ISSUE TITLE
Not exactly a bug: Disconnecting from game caused me to unable to talk to party

### ISSUE THREAD

**Issue by minecraft2048** [ValveSoftware/Dota-2#581]
Lets say I'm playing with 5 stack party, and we communicate through ingame voice chat, this means that we use party voice chat instead of team voice chat. Then lets say my dota crashed, and then when I reconnect, I got kicked out from the party, with me forming a 1 player party. This means that if I use party open mic, they cannot hear me, and I cannot hear them. If I use team voice chat, they can hear me but I cannot hear them.

Solution: When disconnecting and reconnecting in a middle of a game, automatically join me to previously joined party. This should make us can talk to each other after crashing

**Comment by gdrewb-valve** [comment]
As this isn't a Mac or Linux issue it won't be tracked here, I'll pass it on to the larger team.
