### ISSUE TITLE
[Linux] Memory leak at dashboard?

### ISSUE THREAD

**Issue by vith** [ValveSoftware/Dota-2#583]
I accidentally left Dota 2 running last night after playing some custom games. This morning I immediately noticed my system was almost out of memory. Dota 2 has a virtual size of 11.1G and resident size of 9024M according to htop (text dump from htop: https://gist.github.com/vith/cb7acba65d8b0bd1588f).

After restarting the game, loading the 3 custom maps I played yesterday, and going back to the dashboard, memory use is only at 4235M virtual and 1886M resident.

Not sure how best to help you find the leak, so here's the output of `pmap 17373`: https://gist.github.com/vith/28f4716247211a8185a8

I also saved a core dump with `gcore 17373`, it's pretty large of course:

```
❯ xz -T0 -v core.17373
core.17373 (1/1)
  100 %        561.7 MiB / 10.4 GiB = 0.053    31 MiB/s       5:44     
```

but I can upload it somewhere if it would help.

This is the screen I left dota on overnight:
![screenshot from 2015-10-17 12-56-12](https://cloud.githubusercontent.com/assets/3265539/10560352/80ba5702-74ce-11e5-95c7-ffb183a37c1f.png)
The chat channel for that custom game is constantly flooded with messages. Maybe old messages aren't being freed? Just a random guess.

Dota 2 version: 1,123

System info: https://gist.github.com/vith/e3889f87ce626e5acc35

**Comment by gdrewb-valve** [comment]
Likely not Mac or Linux specific.

**Comment by gdrewb-valve** [comment]
Confirmed that it also happens on Windows so I've passed this on to the larger team.
