### ISSUE TITLE
[Linux] Keeper of the Light's illuminate spell doesn't show running horses model

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#586]
Happening since the last big update. Only a particle effect shows up.

System info:
https://gist.github.com/jazztickets/ec290c38deb7fa8db404

![2015-10-18_00001](https://cloud.githubusercontent.com/assets/425930/10567052/2caa03fa-75b5-11e5-8878-9d5f7fc4b140.jpg)

**Comment by gdrewb-valve** [comment]
Probably not Linux-specific.

**Comment by gdrewb-valve** [comment]
The larger team has taken a look and believes they have a fix.
