### ISSUE TITLE
Spetre Phasma Phasmatis set portrait bug

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#590]
Hi there,

The other day I played a game and got killed by a Spectre. The **"Killed By" window** shows the portrait of the hero. However, this showed the "grids" (I don't know its specific name) of the cosmetics as well.

![screenshot from 2015-10-18 20 02 49](https://cloud.githubusercontent.com/assets/7419656/10581678/41394068-7684-11e5-8582-5f4f2b3cab08.png)

The basic model did NOT show the grids. Also, the regular portrait of Spectre (shown at the bottom of the screen when the hero is selected) did NOT have this issue.

**Comment by gdrewb-valve** [comment]
Presumably not a Linux / Mac specific issue.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.
