### ISSUE TITLE
[OSX] Draggable Fullscreen Window?

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#591]
https://cobalt60.xyz/shared/Screen-Recording-2015-10-19-22-21-59.mp4

OSX 10.11
Intel HD4000

**Comment by gdrewb-valve** [comment]
I can pass this on to SDL to verify if they do anything to try and prevent dragging.

Is this desktop-friendly fullscreen?

**Comment by Staban9** [comment]
@gdrewb-valve I already posted my steam system info. please check it out.

**Comment by gxgani** [comment]
Yes. And I also notice a micro-freeze when I switch from game to menu and cursor moves to a different position.

**Comment by gdrewb-valve** [comment]
The desktop-friendly window is still just a window so unless SDL specifically prevents it I think the window will be draggable.  Confirming with SDL.

There'll definitely be a small lag switching from game to menu as all of the menu resources are evicted when playing the game to give the game maximum space.  There's an open issue, #557, about huge lags on switching that we're looking at but a small hitch will always be there.

**Comment by gxgani** [comment]
@gdrewb-valve is it not possible to unify them into a single entity?

**Comment by gdrewb-valve** [comment]
I'm not sure what you mean.  Unify what into what kind of entity?

**Comment by gxgani** [comment]
It almost seems like the game part is being run in a different resource and menu in another since you said that the resource are evicted. Or the development of upcoming In-game UI would actually bridge these resources?

**Comment by gdrewb-valve** [comment]
The UI takes GPU memory for its images and such.  Those all get discarded when running the game so that the game gets the whole GPU.  Then when you switch to the menu things need to get reloaded so there's a hitch (that's a bit oversimplified but gives you the idea).

**Comment by gxgani** [comment]
Just an update on the micro freezes when switching from game to menu, they seem to been extended to almost-a-second freeze.

**Comment by icculus** [comment]
Hey, I'm trying to reproduce the window dragging bug you posted a video of. Was there any magic to make that happen ("start the game, switch to windowed mode and back, alt-tab then drag around", or whatever)? Does it happen reliably? I can't get it to happen here on Mac OS X 10.11 with an Intel HD 4000, but maybe I'm doing it wrong.

**Comment by gdrewb-valve** [comment]
Closing pending further info.
