### ISSUE TITLE
Cannot open game on Imac

### ISSUE THREAD

**Issue by Urubaen** [ValveSoftware/Dota-2#592]
For the last week I've been unable to play Dota. Can't really recall if it started after an update, but since there have been more since, I guess the problem is elsewhere. 

Basically I start the game from Steam, got to the loading screen with the Dota2 image... and that's it. Never goes any farther. The screen is blocked, most of the time I can't even forcequit and have to restart the computer. Gaming was fine a week ago. 

Anyone familiar with this problem and having a solution to it?

**Comment by gdrewb-valve** [comment]
Can you post your Steam system information?

**Comment by Urubaen** [comment]
Processor Information:
    Model:  iMac10,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  3060 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  ATI Radeon HD 4670

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x1002
DeviceID:  0x9488
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.46" x 13.19"  (26.89" diag)
                                        59.6cm x 33.5cm  (68.3cm diag)
Primary VRAM: 256 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  953049 Mb
    Largest Free Hard Disk Block:  612023 Mb

**Comment by mickyjb81** [comment]
I have exactly the same problem.  Happened out of the blue just hangs on the red square load screen.  Have to force quit to exit.  I have the exact same 4670 Radeon vid card that the poster has.

**Comment by danginsburg** [comment]
I just tried on a very similar system spec and it is working just fine.  I am about to try upgrading from 10.9.5 to 10.11.  Is your machine hung?  If you run in windowed mode with -sw -w 1280 -h 720 on the command-line is the entire system frozen?

Processor Information:
    Model:  iMac11,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3060 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.9.5 (64 bit)

Video Card:
    Driver:  ATI Radeon HD 4670

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x1002
DeviceID:  0x9488
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.62" x 10.47"  (21.34" diag)
                                        47.3cm x 26.6cm  (54.2cm diag)
Primary VRAM: 256 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475134 Mb
    Largest Free Hard Disk Block:  191400 Mb

**Comment by Urubaen** [comment]
Mine is not in a very good shape (it's from 2009), I used to play Dota 2 with pretty much every option on "low" but it never bothered me, I don't really play for graphics, as long as the game works... Which it doesn't anymore. 

I updated to 10.1.11 just yesterday, had the same problem with the previous version of the OS. 

"If you run in windowed mode with -sw -w 1280 -h 720 on the command-line is the entire system frozen?"

I have no idea how to try this, could you tell me how to change the command-line? 

Thanks for the help

**Comment by danginsburg** [comment]
I just tried this on the iMac11,2 on OS X 10.11 and I can not repro this bug.  Can you guys also run with -con_logfile on the command-line and post the contents of game/dota/console.log?  Can you also try doing Verify Integrity of Game Cache in the Steam Properties?

@Urubaen You can see this clicking on Dota 2 in Steam -> Properties -> Set Launch Options...

**Comment by Urubaen** [comment]
Fantastic, it worked modifying the Launch options ! Crazy since I actually had modified them twice following some advice on another forum... 

Game launches perfectly and I can switch back to full screen once I'm in. 

Thanks a lot man, appreciate it

**Comment by danginsburg** [comment]
@mickyjb81 Does the same fix work for you?

**Comment by danginsburg** [comment]
Closing pending additional info from @mickyjb81
