### ISSUE TITLE
Bug/Glitch caused by 16.10.15 update? Any Progress or Action being done?

### ISSUE THREAD

**Issue by Staban9** [ValveSoftware/Dota-2#595]
After this update, I can't anymore play dota. All buttons are not responding quickly and games are unplayable since my fps drops from time to time. I haven't heard anything whether it's being fixed or not. Do we still have hope? I thought the semi update today has the solution for it, but there wasn't!! Please to those who have knowledge about this, tell us if this is known by valve, taking actions regarding it and trying to fix it or not. I've spent thousands of dollars on this game then one day, it just didn't let me play!! THANKS

**Comment by gdrewb-valve** [comment]
The team is actively working on a lot of bugs.  It's hard to know if they're what you report or not but perf issues are definitely being looked at.  However, this bug tracker is for Linux and Mac issues so you'll want to go check out dev.dota2.com.
