### ISSUE TITLE
Wierd UI language problem [OSX elcapitan]

### ISSUE THREAD

**Issue by sinamiandashti** [ValveSoftware/Dota-2#596]
In recent update

look at the screen shots
<img width="1440" alt="screen shot 2015-10-21 at 10 22 50 pm" src="https://cloud.githubusercontent.com/assets/195868/10646864/758aa40a-7842-11e5-8acf-021cbc54ec7f.png">
<img width="1440" alt="screen shot 2015-10-21 at 10 23 35 pm" src="https://cloud.githubusercontent.com/assets/195868/10646865/768dd246-7842-11e5-84d3-1f3f5ca5cd4c.png">

**Comment by sinamiandashti** [comment]
i cant even play the game ... cant lockin my hero
a lot of texts change to underlined placeholders

plz fix this ... game is unplayable

**Comment by gdrewb-valve** [comment]
You appear to be missing files, try validating your local files from Steam.

Also this wouldn't be specific to Linux or Mac so this won't end up staying open.

**Comment by sinamiandashti** [comment]
how can i validate @gdrewb-valve

**Comment by gdrewb-valve** [comment]
In Steam right-click on the game, select Properties, then the Local Files tab, then click on "Verify integrity of game cache."  That'll take a while to run.

**Comment by sinamiandashti** [comment]
Fixed
thanks
