### ISSUE TITLE
Steam for linux doesn't know of dota2's logo

### ISSUE THREAD

**Issue by ArnaudAndre** [ValveSoftware/Dota-2#597]
When creating a .desktop shortcut (in steam, right-click on dota 2, _Create Destkop Shortcut_ ) the resulting shortcut uses the generic steam icon rather than the dota 2 logo it would use on windows. Same happens for _Create start menu shortcut_ during game installation.

As per [steam for linux #989](/ValveSoftware/steam-for-linux/issues/989) steam doesn't try to generate icons for linux from the windows' .ico file and providing a set of desktop icons for linux is the responsibility of each individual game's studio.

Same issue existed in source 1 dota2 for linux but since that tracker got deleted I'm making a new one.

**Comment by Tele42** [comment]
As a side note, @Plagman communicated via another method that the source 1 dota 2 issue tracker has been made private to valve, it is not deleted, just not public.

**Comment by AngryPenguinPL** [comment]
Same here, I can only get default steam icon. This same is in most Linux games from Steam but if I not running it often, this is not problem. But in game like Dota2 (i try play in it every day) should be a good icon.

**Comment by u00101010** [comment]
When running, Unity displays for me the the default "no icon", the grey box with a question mark in it.

**Comment by gdrewb-valve** [comment]
Reborn is calling SDL_SetWindowIcon so it should have something appropriate when running, I'll check with the SDL devs.

Once that's resolved the Steam issue should be reported to the Steam team and this will be closed out.

**Comment by ArnaudAndre** [comment]
It's already been reported to the steam team almost three years ago in bug 989 I linked in the OP and [their response](https://github.com/ValveSoftware/steam-for-linux/issues/989#issuecomment-12836269) was :

> These are Game issues, not Steam.

Each studio making their game available on linux has to properly configure their repository and the steam team doesn't want to fix it for you.

**Comment by gdrewb-valve** [comment]
Sorry, I misread your original post, thanks for the corrrection.

**Comment by gdrewb-valve** [comment]
There should be an icon registered for Linux now, can you try this again?

**Comment by AngryPenguinPL** [comment]
For me (Ubuntu 15.10 x64) working now fine :)

**Comment by ArnaudAndre** [comment]
Yes ! It's woking now ! Thank you.
