### ISSUE TITLE
Killed by box not showing the correct image

### ISSUE THREAD

**Issue by Eignar17** [ValveSoftware/Dota-2#598]
![pantallazo-8](https://cloud.githubusercontent.com/assets/8561550/10656912/093ee2ae-784a-11e5-8627-6d96c465f6de.png)

**Comment by Tele42** [comment]
@Eignar17 Please be more verbose with your issue reports, images are not searchable on github.

**Comment by gdrewb-valve** [comment]
I believe this happens on Windows also, I've passed it on to the larger team.
