### ISSUE TITLE
Game is ready desktop notification doesn't use the dota logo

### ISSUE THREAD

**Issue by ArnaudAndre** [ValveSoftware/Dota-2#599]
Former dota 2 used to put the dota 2 logo in the game-found notification. In reborn the notification only has text. If you can't hear the game-found sound it's not immediately obvious what the popup is for.

In #69 Drew mentions that dota displays the message with the `notify-send` command.
`notify-send` has a `--icon` option which can be either a path or the name of a known icon (i.e. something in /usr/share/icons/ or ~/.local/share/icons/).

**Comment by CalMlynarczyk** [comment]
I don't remember this EVER using the Dota 2 icon, even with the Source 1 version. Same goes for the app icon; it has always been the Steam logo.

**Comment by ArnaudAndre** [comment]
see http://i.imgur.com/Oy8DQ0E.png
also I'm not sure what's wrong with your window manager but both source 1 and reborn have always been using the logo for their icon
![dota2_in_taskbar](https://cloud.githubusercontent.com/assets/4991072/11429631/071ab3e8-947b-11e5-853d-025c0df915b2.png)

**Comment by FeatheredSerpent** [comment]
I can confirm this bug:
![Screenshot](https://i.imgur.com/bZtWSRH.png)

Desktop environment is MATE 1.8.1, window manager is Marco 1.8.3, pop-up notifications theme is Slider.

Source 1 Dota 2 did show the icon.

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3411 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-95-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.63
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 13.31" x 10.63"  (17.01" diag)
                                            33.8cm x 27.0cm  (43.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  929320 Mb
    Largest Free Hard Disk Block:  12538 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
Jan. 11th's update should add the icon.

**Comment by gdrewb-valve** [comment]
Assuming this is working, closing.
