### ISSUE TITLE
Mac: Fullscreen Mode Disables Global Shortcuts

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#6]
Accessing dota trough fullscreen disables the ability to navigate between programs (CMD+TAB) or to take Screenshots (CMD+SHIFT+4) and possibly disables any global shortcuts assigned to the CMD key or any other key. I'm not sure if this is intended behaviour or if it's a bug, since this isn't how it functioned on the main client. However, this is a feature other games have but usually they come with an option to disable or enable global shortcuts and there is none in Dota Reborn. 

Config: http://i.imgur.com/DJgP8tu.png

**Comment by Vuccappella** [comment]
As a side note, CMD+H works as sort of a CMD+TAB Alternative, it gets you out of dota, However if you use that method you can't hear the game is ready sound when you're out of dota.

**Comment by gdrewb-valve** [comment]
A note for people hitting this: if you're running at monitor resolution switch to borderless fullscreen instead as a workaround.

**Comment by gdrewb-valve** [comment]
It doesn't appear that Cmd+Tab is expected to work in true fullscreen, but I'm not 100% sure of that.  The right thing to do here is to use a borderless window.  However that does mean you can't run at a resolution lower than your monitor so I've switched this to an enhancement request to support a scaling mode.  Then the actual window would be a borderless monitor-sized window and you'd get global hotkeys but the UI itself would render smaller and be somewhat less taxing.

**Comment by alkore** [comment]
Sadly using borderless windowed disables you the brightness setting. Only fullscreen has this and not windowed unlike the original Dota2 client.

**Comment by gdrewb-valve** [comment]
You can only adjust the brightness in true fullscreen as that's the only time Reborn owns the display.  In all other settings Reborn is just a window and changing the brightness would also affect the desktop (and the other way around too so regular brightness adjustments will affect Reborn).

**Comment by gdrewb-valve** [comment]
With the 7/23 update you should be able to choose arbitrary resolutions with desktop-friendly fullscreen and use that as an exclusive fullscreen replacement.  I believe that's the only route to supporting Cmd+Tab with fullscreen that we have available.  Let me know if this works reasonably well.

**Comment by gdrewb-valve** [comment]
Closing as there is no current way of adding the enhancement of Cmd+Tab in fullscreen.
