### ISSUE TITLE
[Reborn] Missing dependency on Fedora 21

### ISSUE THREAD

**Issue by Densaugeo** [ValveSoftware/Dota-2#60]
After downloading, reborn failed to start and gave errors related to not having support of s3tc compression. It was not able to start until after I install an s3tc library (libtxc_dxtn) from the rpmfusion repo.

I am running on Fedora 21, with HD7850 GPU and open source radeon drivers.

**Comment by danginsburg** [comment]
Source2 requires GL_EXT_texture_compression_s3tc support.  If installing libtxc_dxtn enables the driver to expose GL_EXT_texture_compression_s3tc then I don't think this is a bug, although it's useful information for others that run into the issue.  I will close this, if you disagree with my assessment feel free to comment and we can re-open it.

**Comment by Densaugeo** [comment]
Ideally, installing Dota should not require the user to look through terminal output to find missing dependencies and install them manually. I don't know how Steam's packaging works, but if there's a way for the installer to check for missing feature support and install it automatically it'd be appreciated.

**Comment by HarlemSquirrel** [comment]
I ran into the same issue on Fedora 21. Interestingly, `libtxc_dxtn.i686` was already installed and I had to install `libtxc_dxtn.x86_64` and then Dota 2 reborn started right up!

**Comment by Tele42** [comment]
@Densaugeo steam is run as the normal, unprivileged user, it does not have the rights to install system libraries, nor should it, as this is a poor excuse elevating privileges. The individual distro's packaging for steam should resolve the necessary system dependencies needed for smooth integration.
