### ISSUE TITLE
No HealthBars, no minimap

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#600]
![file](https://cloud.githubusercontent.com/assets/5942127/10684832/2bd9e972-7952-11e5-96d5-57fb6d5f12c8.png)
As you can see, health/mana bars and minimap are not showing up. Common threads on the issue have not helped as nothing relevant could be found. The running system is archlinux. The card is a 780GTX with nvidia proprietary drivers. I've tried various things like 'hud_sf_reload dota_sf_hud_actionpanel' or 'record demo|stop|' on the console, but of course it'd not work. There seems to be no simple fix to this. 

Here is additional system information.
I've got no Desktop Env. I just use a window manager which is [i3](https://i3wm.org).
The kernel version is 4.2.3-1-ARCH. The nvidia driver is more recent than 340xx and of course, the kernel is 64bits.

This simply prevents me from playing the game. Please help.

**Comment by izemmouri** [comment]
Here is additional system information.
I've got no Desktop Env. I just use a window manager which is [i3](https://i3wm.org).
The kernel version is 4.2.3-1-ARCH. The nvidia driver is more recent than 340xx and of course, the kernel is 64bits.

Best regards.

**Comment by danginsburg** [comment]
Can you post your system specs from Steam -> Help -> System Information?  Also, what resolution is your monitor and what mode are you running the game in (Desktop Friendly Fullscreen, Exclusive Fullscreen, Windowed, Borderless Windowed)?  Does running in windowed vs. fullscreen make a difference?  I suspect this is some kind of issue related to running in i3 and maybe resize events, but that is a guess.  If you can try a different window manager please let us know if that works.

**Comment by ghost** [comment]
Hi, reinstalling the game effectively fixed the problem. I had indeed tried all modes and resolutions and i3 used to do just well with dota2 before reborn. Well, anyways, I appreciate your swift reply.
Thank you.

**Comment by danginsburg** [comment]
OK, glad to hear.  Closing.
