### ISSUE TITLE
Unable to download updates

### ISSUE THREAD

**Issue by sgardn** [ValveSoftware/Dota-2#601]
I'm on a mac, yosemite OS. When there is an update queued I tell it to download and it shows me this:

![unresponsive](https://cloud.githubusercontent.com/assets/1424950/10695128/0e06c212-7970-11e5-8925-5a49436b544d.gif)

After a minute or two, it shows me:

<img width="438" alt="screen shot 2015-10-23 at 10 23 20 am" src="https://cloud.githubusercontent.com/assets/1424950/10695139/22f2d8f0-7970-11e5-8d2d-d4ea8c5d7a14.png">

**Comment by gdrewb-valve** [comment]
You'll want to post this in a Steam forum so that the Steam team seems it.

Does any other downloading in Steam work?  Do you have other Mac games?  If so and you have a small one can you delete its local content and try redownloading it?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
