### ISSUE TITLE
[Linux] Freeze / Not Responding when quiting client

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#603]
Hi,

The client freeze/ not responding when I try to quit. I need to force kill it manually.

Below is my system specs 

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.2 Rafaela (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-38-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV770 (DRM 2.39.0, LLVM 3.6.2)

    Driver Version:  3.0 Mesa 11.1.0-devel (git-70b06fb 2015-10-23 trusty-oibaf-ppa)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x9442
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 19.49" x 11.46"  (22.60" diag)
                                            49.5cm x 29.1cm  (57.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3945 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461635 Mb
    Largest Free Hard Disk Block:  400610 Mb

Installed software:

Recent Failure Reports:

```

**Comment by gdrewb-valve** [comment]
Has this always happened?  If not did this start happening after a Reborn update or after a Steam client update?

**Comment by rained23** [comment]
Most of the times, even without any update it still occurred.

**Comment by vonclutch** [comment]
hey,

Same for me, this happen since reborn, i need to force kill it.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  1870 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 440/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.41
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 75 Hz
    VendorID:  0x10de
    DeviceID:  0xde0
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 14,96" x 11,81"  (19,06" diag)
                                            38,0cm x 30,0cm  (48,4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3951 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  296294 Mb
    Largest Free Hard Disk Block:  231314 Mb

Installed software:

Recent Failure Reports:


```

**Comment by gdrewb-valve** [comment]
Does this happen every time?  I just tried starting the game, getting to the main menu and immediately exiting and it worked fine on my Ubuntu system.  Does it hang for you even with a simple startup/shutdown like that?

**Comment by gdrewb-valve** [comment]
Are you using the stable Steam client or the beta Steam client?

**Comment by vonclutch** [comment]
Thanks for your reply,

This happens generaly after 3 or 4 games. Before 3 games i can leave Dota withtou problems.

**Comment by gdrewb-valve** [comment]
Thanks for the clarification.  What Steam client are you using?

**Comment by vonclutch** [comment]
No problem ^^

I used the normal one i think ( i don't participate to the beta )

**Comment by rained23** [comment]
I suspected there is memory leak on the client, try host any custom game (self host),
and play the game longer than 50 min, when I check the RAM, reborn took 60% of my RAM causing high ram usage(client only not including steam and any helper), even after you end hosting the custom game.

Comparing before game and after game, show the RAM not cleared after usage, I think this might be the reason of the client become zombie process.

**Comment by vonclutch** [comment]
Yep, this exactly what happens to me.
When i launch dota, it used 0.8Gb RAM after 3 games it almost used 2.9Gb Ram (almost 75% of my RAM). I restart dota every 3 game or i've got a leak in the performance game ( freeze, lags, sometimes client don't even respond ... )

**Comment by gear4s** [comment]
happens to me too, no lags or anything but dota becomes zombie after clicking _quit_.

**Comment by vonclutch** [comment]
Hey,

Seems to be fix in the last update.

**Comment by gdrewb-valve** [comment]
Thanks for the update.  Is anybody else still seeing problems?

**Comment by vonclutch** [comment]
Hey in fact no, the problem is still here after 6 games.

**Comment by Eignar17** [comment]
@gdrewb-valve  is problem logo loading is slow dota 2 rebon and freeze

**Comment by gdrewb-valve** [comment]
OK, this will stay open.

**Comment by Niandu** [comment]
I have the same problem, it's very annoying

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3500 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    elementary OS Freya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-33-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Mutter(Gala)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 355.11
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 17,09" x 10,63"  (20,12" diag)
                                            43,4cm x 27,0cm  (51,1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  3934 Mb

Miscellaneous:
    UI Language:  English
    LANG:  es_PY.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  372296 Mb
    Largest Free Hard Disk Block:  316094 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
Has the memory usage changed with the recent updates?

**Comment by vonclutch** [comment]
Yope,

Nothing change, it looks like it's getting worse .... after 2 games now the game need to be force killed.

**Comment by gdrewb-valve** [comment]
OK, thanks.

**Comment by gear4s** [comment]
it's definitely worse for me too ..

**Comment by gdrewb-valve** [comment]
Recent updates have made yet more memory changes, has this changed?

**Comment by gear4s** [comment]
no, same problem for me. happened just last night

**Comment by vonclutch** [comment]
In fact each update are worst, i have to force kill dota everygame cause of high ram usage due to the memory leak ( ui lag (menu/game), mini freeze, ... )

**Comment by gdrewb-valve** [comment]
For people who are hitting issues have you updated your video drivers recently?

**Comment by vonclutch** [comment]
nope, sould i ? 

my version -> 352.63 
new one -> 361.28

**Comment by gdrewb-valve** [comment]
It's just to gather more info, I have no idea if it'll make any difference at all.  If you have time and feel like it go ahead, otherwise don't worry about it.

**Comment by vonclutch** [comment]
Kk, i'll try.
And i'll give you my feedback

**Comment by gear4s** [comment]
yep, I issued an update 3 days do

**Comment by vonclutch** [comment]
So i update my video driver, and clearly it's better. Don't know why but now the game has no more lags ( menu/ui but still freezing in game) and the game close after 3 games and not after 4. 

Voilà!

**Comment by gdrewb-valve** [comment]
Thanks.  We'll wait a bit to hear from the OP.

**Comment by gdrewb-valve** [comment]
Closing pending more information.

**Comment by vonclutch** [comment]
Up ! 
@gdrewb-valve  Any news about this bug ? rly annoying to force close everytime ....

**Comment by gdrewb-valve** [comment]
@vonclutch , your last post here was that it was fixed.  The issue has been closed for months, nobody has been looking.  Issue #793, which sounds like the same thing, is currently being looked at but as before Valve has no repro.

**Comment by vonclutch** [comment]
Oups sry if you don't understand what i means, I only said it was better not fixed.

**Comment by Turbid** [comment]
I confirm this at Ubuntu 16.04 with GTX650Ti

p.s. and Ubuntu 20.04 with GeForce GTX 1650

**Comment by gdrewb-valve** [comment]
Check #793 for status from the SDL devs.

**Comment by B1aZer** [comment]
Confirm on Ubuntu 14.04. [system Info](https://gist.github.com/B1aZer/e6046917a64dafdc110da9cad0dc4ff1). Happens once in 2-3 games.

**Comment by leodutra** [comment]
Still happens on Ubuntu 16.04 GTX 560.

**Comment by u00101010** [comment]
Can confirm that this is still a thing.

**Comment by crnisamuraj** [comment]
This is still an issue. Any fix?

**Comment by jcnils** [comment]
Same thing here, when I confirm I want to quit the game freezes and I have to kill it from terminal.
