### ISSUE TITLE
the console does not work

### ISSUE THREAD

**Issue by ilyuhin-s** [ValveSoftware/Dota-2#604]
when you open the console. in it nothing is displayed and nelsa to write in it. Button does not work.
OS Deepin Linux

**Comment by Tele42** [comment]
Without more information, https://github.com/ValveSoftware/Dota-2/issues/120#issuecomment-118086863 most likely can help you get past this issue. Missing system fonts would be a distro packaging issue.

**Comment by gdrewb-valve** [comment]
There is also #169 which is similar.

**Comment by ilyuhin-s** [comment]
помогла установка пакета "ttf-liberation"

**Comment by ilyuhin-s** [comment]
has helped to install the package "ttf-liberation"
