### ISSUE TITLE
[MAC] In game friend UI does not work.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#605]
https://i.imgur.com/4lDOTbW.jpg

As you can see in my friend list i have a friend invite. Right clicking that name and selecting accept friend invite does not work. Going to this person's profile and clicking accept friend request at the top right corner does not work either. The only way I could accept the friend request was through steam. I think same behaviour is observed when trying to add people in game as well.

iMac (27-inch, Late 2012)
3.2 GHz Intel Core i5
24 GB 1600 MHz DDR3
NVIDIA GeForce GTX 680MX 2048 MB

**Comment by gdrewb-valve** [comment]
Likely not Mac/Linux specific.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.
