### ISSUE TITLE
[Linux] Dota 2: Reborn crashes

### ISSUE THREAD

**Issue by John23Anthony** [ValveSoftware/Dota-2#606]
Dota 2: Reborn crashes on logo screen. Been trying to resolve it now for sometime, but nothing has worked so far. Although while typing this, I've tried again, this time it didn't crash, but just froze. Had to reload my DM to exit it though, and upon doing that I got the following error when steam tried to load up. I'm running DeepinOS 2014.3 which is based on Ubuntu 14.04

"OpenGL GLX context is not using direct rendering which may cause performance problems."

Anyway, that may or may not be significant, but here is my terminal whatnot about the issue:

```
"Running Steam on deepin 2014.3 64-bit
STEAM_RUNTIME has been set by the user to: /home/tony/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/tony/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Game update: AppID 570 "Dota 2", ProcID 4963, IP 0.0.0.0:0
ERROR: ld.so: object '/home/tony/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/tony/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 4966 != 4965, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/tony/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/tony/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198065431052 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198065431052
Setting breakpad minidump AppID = 373300
Fontconfig warning: "/home/tony/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/tony/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x600006
  Serial number of failed request:  89
  Current serial number in output stream:  89
GetHud called with NULL g_pHudGameSystem!Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GT 750M/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Game removed: AppID 570 "Dota 2", ProcID 4968 "
```

_System specs are as follows:_

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2401 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Deepin 2014.3 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-66-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 750M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 355.11
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xfe4
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 12.17" x 6.81"  (13.94" diag)
                                            30.9cm x 17.3cm  (35.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15930 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  224711 Mb
    Largest Free Hard Disk Block:  186875 Mb

Installed software:

Recent Failure Reports:
    Sat Oct 24 22:10:48 2015 GMT: file ''/tmp/dumps/crash_20151025001036_1.dmp'', upload yes: ''Discarded=1''
```

I've also tried using -fullscreen and -sw, but to no avail. Same with reinstalling steam, dota 2 and even trying to rectify each error manually, though it doesn't help as steam just replaces the edited files.

Let me know if you need any info, and sorry for the mess... I'm not sure how to put it in neat blocks.

**Comment by Tele42** [comment]
@Wolfie5493 github formatting can be found at https://help.github.com/articles/github-flavored-markdown/, what you have now is pretty legible.

**Comment by John23Anthony** [comment]
Noted and subsequently updated. Thanks!

**Comment by Tele42** [comment]
@Wolfie5493, I just noticed your specs hint that you might have an Optimus system, if that is true, than that is the root of the issue. What method are you using to use the nvidia card? https://github.com/ValveSoftware/portal2/issues/219#issuecomment-46381697 hints that using Primus via optirun may increase you chances of success.
I am not an Optimus user, so I don't have first hand experience with this, good luck.

**Comment by John23Anthony** [comment]
I do indeed have an optimus system. My integrated graphics (intel) isn't supported with dota or most other games so i have to activate my Dedicated GPU to play them. I use Bumblebee, and run most graphic intensive programs with optirun [application]. Without this steam doesn't even let me start most games

**Comment by gear4s** [comment]
try posting the output of this:

> ldd ~/.steam/steam/ubuntu12_32/steamui.so | grep GL

also it looks like you're running 32bit Steam on a 64bit PC, and missing a few 32bit dependencies:

> ERROR: ld.so: object '/home/tony/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by John23Anthony** [comment]
Forgive my lack of knowledge here, but the output of the first command creates a file, how do i open/view/attach it?

and yes, I suspected my steam to be 32 bit. how would i install a 64 bit steam client or fix the 32-bit dependency errors?

**Comment by Tele42** [comment]
ldd outputs to stdout (regular text), and grep is a filter. Steam is only available in 32 bit, but this an irrelevant detail. As for gameoverlayrenderer.so, steam always tries to preload a 32 bit and 64 bit overlay library, one is always expected to non-fatally fail as an application can not be 32 bit and 64 bit at the same time.

**Comment by John23Anthony** [comment]
The output is as follows for the ldd command.

```
libGL.so.1 => /usr/lib/i386-linux-gnu/mesa/libGL.so.1 (0xf6184000)
```

**Comment by Tele42** [comment]
@Wolfie5493 I'm guessing here, but I think you need to run ldd the same way you run steam (with the optimus-enabling command) to get a valid result.

**Comment by gear4s** [comment]
yes you do. I don't use nvidia though (amd); it'll help to get specifics

https://asciinema.org/ seems good for "sharing" what your commands do

also please share the output of this command:

> ldconfig -p | grep libGL.so.1

I know this would be a lot to paste but I know for a fact that it has to do with your opengl libraries being symlinked to the incorrect library files. also try using Primus on Linux (it's a lot better on Arch at least, for performance)

**Comment by John23Anthony** [comment]
okay I did as you suggested:

```
optirun ldd ~/.steam/steam/ubuntu12_32/steamui.so | grep GL
    libGL.so.1 => /usr/lib32/nvidia-355/libGL.so.1 (0xf60da000)

ldconfig -p | grep libGL.so.1
    libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/mesa/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib/libGL.so.1

optirun ldconfig -p | grep libGL.so.1
    libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/mesa/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib/libGL.so.1

```

**Comment by gear4s** [comment]
the steamui is linking to nvidia's 64bit libGL, but the ldconfig is linking to the default libGL (which would load when dota's running)

try this:
to make optirun work on dota 2, right-click on DotA 2 in the sidebar, go to Properties and click Set Launch Options

put this in the launch options:

> LD_PRELOAD=/usr/lib32/nvidia-355/libGL.so.1 optirun %command%

(copy it exactly, including the "%command%")

**Comment by Tele42** [comment]
Dota 2 is 64 bit, you need to preload the 64 bit variant to have any effect.

**Comment by gear4s** [comment]
then try preloading the 64bit variant, I only see the default libGL being loaded though

why did you install 32bit nvidia on a 64bit system anyway ?

**Comment by John23Anthony** [comment]
Yes yes yes! it works, thanks gear4s heh.

Btw, the proprietary drivers i use are from the proprietary PPA. It didn't have an option for 64-bit and the .deb package from Nvidia's website gives issues. If there is a way for me to get 64-bit nvidia, would you be able to guide me on how to get them? I would prefer to be using the correct drivers.

Thanks for the assist folks, i appreciate it

**Comment by gear4s** [comment]
enable the x86_64 "branch" of the PPA, and then install it. usually it's "install package_name:amd64" or something (I use archlinux so it's a lot easier :/)

**Comment by John23Anthony** [comment]
okay forgive me for being an idiot here. the PPA i got the drivers from is the ppa:graphics-drivers/ppa and i have no idea how to enable the x86_64 branch, if it even has it. thanks again for the help gear4s

**Comment by gear4s** [comment]
If my tests on my Ubuntu VM are right it should go like so:

> dpkg --add-architecture amd64
> apt-get update
> apt-get install nvidia-graphics-drivers-355:amd64

note: they have to be run as root (add "sudo" before every command or run as root user)

you can add "-Vs" to the install command, which allows verbose imulation (you can see what packages will be installed or removed)

no problem btw, I used to use that wreck of a "distro" before I switched over to ArchLinux/Gentoo. honestly it feels so much better and it's surprisingly easier to use :)

**Comment by gdrewb-valve** [comment]
It sounds like this issue is resolved, should I close it out?

**Comment by gear4s** [comment]
sure, if it works. he can use IRC or email me if he has other problems

**Comment by gdrewb-valve** [comment]
OK, closing for now.
