### ISSUE TITLE
[OSX] Avatar issue in "Your last match" section

### ISSUE THREAD

**Issue by gluttonyGit** [ValveSoftware/Dota-2#608]
OS X version: 10.11.1

Main page has problem with hero avatar in "Your last match" section.

![2015-10-25 20 38 57](https://cloud.githubusercontent.com/assets/9007635/10716893/9fee68c6-7b58-11e5-93d8-c66f8c698d73.png)

**Comment by gdrewb-valve** [comment]
Likely not Mac/Linux specific.

**Comment by fumazu** [comment]
Portrait is working fine in my Windows client, but I have the same issue when using the Linux client under Ubuntu 15.10.

**Comment by gdrewb-valve** [comment]
Which issue do you mean?  Do you mean the hero isn't displayed or that the little hero movie doesn't play?  The movie is a known issue.

**Comment by fumazu** [comment]
The movie is missing in the Linux client. Sorry for the dupe. :-/

**Comment by gdrewb-valve** [comment]
@gluttonyGit, is your issue also that the movie is missing?  I had assumed you meant more with the screenshot.  If this is about the movie not playing the underlying issue is covered in #54.

**Comment by gluttonyGit** [comment]
@gdrewb-valve i mean the hero movie is missing.

**Comment by gdrewb-valve** [comment]
OK, closing this as a duplicate.
