### ISSUE TITLE
[Linux] Question: Does Dota 2 use OpenGL 4.2 extensions, or it won't use anything above 4.1?

### ISSUE THREAD

**Issue by kolobos** [ValveSoftware/Dota-2#609]
Not an issue, but questions are usually allowed on GitHub and I can't find that information through Google.

Thinking about trying LLVM 3.8-devel branch and Mesa Git branch on RadeonSI drivers and AMD Bonaire graphics card.
I know that minimal requirements are OpenGL 3.3, my open-source driver supports 4.1 at the moment.

Will OpenGL 4.2 extensions support in the drivers benefit Dota 2 performance? What about 4.3-4.5 extensions, are they currently used?

**Comment by danginsburg** [comment]
The extensions beyond OpenGL v4.1 that benefit Dota 2 include the following:
- GL_ARB_texture_storage (OpenGL v4.2) - all application textures are allocated with immutable texture storage.  This enables the driver to do less validation at draw time.
- GL_ARB_shader_image_load_store (OpenGL v4.2) - memory barrier functionality is used to emulate read-only depth stencil
- GL_ARB_vertex_attrib_binding (OpenGL v4.3) - provides a more efficient path for updating vertex bindings. 
- GL_ARB_copy_image (OpenGL v4.3) - provides a memory savings by allowing the application to delete backing store for static textures
- GL_ARB_buffer_storage (OpenGL v4.4) - used for persistently mapped coherent buffers to store dynamic vertex, index, and uniform buffers.  This allows the application to update VB/IB/UBOs from multiple threads which is typically a good performance win in CPU-limited situations

Also:
- GL_EXT_direct_state_access - more efficient texture binding

**Comment by Tele42** [comment]
@danginsburg is fglrx the reason why EXT_dsa is used instead of ARB_dsa? Last I heard, EXT_dsa will not be coming to mesa any time soon.

**Comment by danginsburg** [comment]
@Tele42 At the time I wrote it, EXT_dsa was more widely supported.  That includes fglrx as well as Haswell/Broadwell on Windows.  In other words, last time I looked drivers supporting ARB_dsa were a subset of those supporting EXT_dsa.  It would not be hard to add ARB_dsa support though.
