### ISSUE TITLE
[OS X] Minimap "invisible" after changing resolution.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#61]
I have everything set quite low (lowest actually). I took a screenshot but it is all black (probably because of fullscreen). The minimap is transparent with overlaid health bars in it. I will try screenshots again :/ Happened after changing resolution with fullscreen enabled.

2012 Retina macbook pro, everything up-to-date.

**Comment by Socapex** [comment]
Allright, so it happens when you set resolution to 1024x640: http://i.imgur.com/cgChTFP.jpg

Then, setting it back to 1440x900 (or other resolutions), makes minimap dissapear: http://i.imgur.com/qi8atVr.jpg

BTW, great to see you are trying to keep these bugs updated/assigned etc. A bit of transparency is nice for us users :) ty

**Comment by danginsburg** [comment]
Can you please post your full system configuration info for your 2012 MBPr?  I have tried to repro this on two Macs so far and haven't been able to make it happen.  I have tried setting those resolutions both in fullscreen and borderless window when in game (and switching to various other resolutions) and did not see that happen to the minimap.

**Comment by Socapex** [comment]
Sure thing, it may be related to my graphics settings? Here they are anyways: http://i.imgur.com/Y8zPldB.png <http://i.imgur.com/Y8zPldB.png>
I also have Draw Hero Icons on MiniMap enabled, maybe that is it? I'll do more testing if you can't reproduce it.
Have a great day!

OSX Yosemite 10.10.3
MacBook Pro (Retina, Mid 2012)
2.6GHz Intel Core i7
16GB 1600 DDR3
NVIDIA GeForce GT 650M 1024MB
Intel HD 4000 graphics too.

**Comment by danginsburg** [comment]
I've got this repro'd here.  Investigating.

**Comment by danginsburg** [comment]
I have fixed this issue and it will be in the next update.  There were actually two issues here.  One was that when resolution changed we would not always setup scaleform with the correct resolution causing UI rendering to get cropped.  The second issue with the minimap was that we were reporting resolutions that were not actually supported which would cause the minimap to render with the wrong size.  1024x640 is not actually a supported resolution and now we properly enumerate them.

**Comment by danginsburg** [comment]
This has been fixed by the 6/30 update.

**Comment by p-groarke** [comment]
Haven't had time to respond. Ty for the follow-up and information! Curiosity == satisfied :D Hopefully I get to test out the new client soon. Have a great day.

**Comment by p-groarke** [comment]
Hmmm, maybe this should be re-opened? Or would you prefer I create a new bug report?

http://i.imgur.com/8KPlRM1.jpg

**Comment by gdrewb-valve** [comment]
We'll reopen.

**Comment by danginsburg** [comment]
I am unable to repro this in the 7/20 update.  @Socapex can you please provide repro instructions?  The original repro instructions with the bug I fixed do not apply anymore because 1024x640 is not offered as a resolution anymore.

**Comment by p-groarke** [comment]
I am sorry to waste your time on this issue. I haven't been able to reproduce it since the screenshot I posted. It might have been a "first-launch-after-update" thing, as it seems common (and it is to be expected while all the kinks get fixed). I will post more information here if I ever get a reproducible use-case. It is up to you whether you prefer to keep this bug open or not, either way it is still here if I can help out in the futur.

**Comment by gdrewb-valve** [comment]
Thanks for the update.  We'll close this for now and if you find a repro case we will reopen.
