### ISSUE TITLE
[Mac] Game Freezes upon selecting courier  (game breaking)

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#610]
Seems to be a problem with this particular game/courier model or something but basically http://www.dotabuff.com/matches/1893081811 here's the match. Whenever I selected the courier the game would freeze for 4 seconds completely until it went back to normal. This only happened if I only selected the courier after I've had another unit selected first (like my hero). This happened both with manually selecting it or using a key binding. After the game I tried making a private lobby and testing selecting the courier ( i didn't have any couriers equipped) and this did not happen. My guess is, it has to do with that courier model. I tried restarting steam and dota while i was in game did not fix. I was forced to play without a courier or to simply freeze for 4 seconds every time.

EDIT: forgot to mention, I'm the QoP on dire.

**Comment by gdrewb-valve** [comment]
Likely not Mac/Linux specific.

**Comment by Vuccappella** [comment]
@gdrewb-valve no one in the game had that problem, so I'm not too sure, I asked my team mates they said it was fine, most likely they were running windows.

**Comment by gdrewb-valve** [comment]
Can you post specifically which courier you were using here so that it's in the log?  I haven't tried to figure out which one it was yet, but some quick tests with the standard courier were OK.

**Comment by Vuccappella** [comment]
normal courier is perfectly fine. The courier that caused this is the on in the replay on the dire side (the first courier and last spawned by the dire,) I don;t have the replay and I don't know the name of it so I can't really say exactly which one it is.

**Comment by gdrewb-valve** [comment]
We'll see if we can repro.

**Comment by gdrewb-valve** [comment]
Courier selection problems do occur on all platforms.  One source of these problems was fixed in yesterday's update.  I believe there's another update coming which will fix a second problem.

**Comment by gdrewb-valve** [comment]
Closing as this isn't Mac-specific.
