### ISSUE TITLE
Endless dialog loop DOTA_ReplayDownload_Error

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#611]
Sometimes downloading replays fails for unknown reasons. When that happens, the client shows a dialog with the title "DOTA_ReplayDownload" and the overly verbose and detailed error message "DOTA_ReplayDownload_Error".

When I click OK, the same dialog appears again and again. In most cases I need to force-close Dota to get rid of it.

The last time this happened was when downloading the replay 1894270475. However, after force-closing Dota, I could redownload it without any problems. In fact, I never had any download errors that couldn't be solved by redownloading. Only the error dialog doesn't let you do that until you restart Dota.

**Comment by gdrewb-valve** [comment]
Likely not Linux or Mac specific.

Can you post your Steam system specs here?

**Comment by phoerious** [comment]
Sure. I don't think that it's even system/hardware specific, but here you go. :-)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2205327 Mb

Installed software:

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.  They don't know why this would keep popping up but they're aware of it now.

**Comment by gdrewb-valve** [comment]
The larger team says they might have found the issue and a future update will have a fix.

**Comment by phoerious** [comment]
Wow, that was fast. Very cool. Thanks.

**Comment by phoerious** [comment]
I couldn't find an entry in the changelog, but the issue seems to be fixed.
However, I still have to restart Dota in order to re-download because after an error, the client refuses to show the download button again.
Generally, download errors occur quite often (approx. every 5-10. download fails). Maybe that's a bug, too?

**Comment by phoerious** [comment]
Additional information: downloads that are about to fail tend to take a very long time. When a download of a normal replay (non-tournament replay without audio contents) takes longer than 10-15 seconds, it will probably fail after 20-30 seconds.

**Comment by gdrewb-valve** [comment]
I passed this on.
