### ISSUE TITLE
Micro Freezes when dying or grabbing runes

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#612]
Since about when Reborn became the new stable client I'm suffering from little micro freezes during the game. These freezes are about .5 to 1 seconds. Most of the time, they are not really game breaking, but really annoying.

These freezes happen mostly when dying (especially in team fights), but also sometimes when grabbing runes.  In the process of writing this report I tried reproducing it in a lobby by repeatedly suiciding against bots and towers, but wasn't able to do so.

The freezes occur randomly. Sometimes I have games without any, sometimes they occur several times a game. Whether these happen might be related to how many spells were used before the hero died. Freezes seem to happen more often in heavy team fights. But that is just a wild guess and doesn't explain why I also experience them sometimes at other actions such as grabbing runes.

I googled and found lots of other people having the same issue on Reddit. But according to their information, they are caused by Windows Defender which I can rule out on a Linux system.
There are also some reports on the dev forums, but they are from 2011-2014. The most recent is from 2015 (http://dev.dota2.com/showthread.php?t=181084) but that user is reporting freezes every few seconds which isn't the case here.

My system information:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2205325 Mb

Installed software:

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
As you mention there are many reports of hitches.  The larger team is investigating so there won't be a direct Linux-specific effort until that is done, but I can post back if anything new is found.

**Comment by phoerious** [comment]
That'd be nice. Thanks.

**Comment by phoerious** [comment]
Just played another game and had some really random micro freezes without any specific preceding action.

**Comment by gdrewb-valve** [comment]
Has this changed at all in the last couple of months?

**Comment by phoerious** [comment]
I haven't played in over two weeks, but I can't remember that I had
freezing issues before anymore.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
