### ISSUE TITLE
(OSX El Capitan) Weird Resolution Settings issue

### ISSUE THREAD

**Issue by Enigma7ic** [ValveSoftware/Dota-2#614]
Whenever I launch Dota 2, the client won't let me Alt-Tab out of the game (or switch spaces) unless I go in the Video settings and select the "Use my monitor's current resolution" option first.

I have to select that Every. Single. Time. I launch the game client. It's incredibly annoying.

Please note that this is not related to the recent bug that wouldn't let you Alt-Tab back into the game (which was fixed last patch for me).

**Comment by danginsburg** [comment]
Can you add -con_logfile to your Launch Options and post game/dota/console.log.  Or check if maybe you have something on your command-line already that is forcing Exclusive Fullscreen?  That would be my guess as to what is going wrong.

**Comment by Enigma7ic** [comment]
Oh god, -fullscreen was enabled in the launch options. I feel so dumb.

Thanks for the help!
