### ISSUE TITLE
[OSX] Crash when typing Cyrillic 'x'

### ISSUE THREAD

**Issue by alek-beloff** [ValveSoftware/Dota-2#615]
1. When one switches to Russian (PC) layout - Dota hotkeys (Q,W,E,R, etc.) are no longer available. I.e. hotkeys now depend on the language you type on
2. Although, if Russian (PC) layout is switched on you still can write a comment in cyrillic. Everything but ONE letter! This button corresponds to cyrillic letter 'х' - the international marking will be '{ [' (keycode: 219, ASCII keycode: 91). Entering this letter the game crushes. Pushing this button with the US layout makes normal reaction.

**Comment by cyrilvoynov** [comment]
Same to me. It's pretty annoying when you need to quick chat someone during the game and after it you have no one hotkeys are working properly. So you need to switch up your language.

**Comment by gdrewb-valve** [comment]
The hotkey behavior can be changed in the Advanced part of the hotkey settings.  Choose positional hotkeys and they won't change when you switch your language.

Keeping this open for the crash.

**Comment by cyrilvoynov** [comment]
Yeah, it works. Thank you.

**Comment by gdrewb-valve** [comment]
Does this crash still happen?

**Comment by alek-beloff** [comment]
No, everything is ok, thanks

четверг, 14 января 2016 г. пользователь Drew Bliss написал:

**Comment by gdrewb-valve** [comment]
Closing, thanks.
