### ISSUE TITLE
Sometimes Dota 2 won't close in dock (Mac OSX 10.10.5)

### ISSUE THREAD

**Issue by Sebby91** [ValveSoftware/Dota-2#618]
Honestly no clue when, but some days it won't happen, and some days it will. When you close Dota 2, the icon is still active in the dock, despite it won't show up in activity monitor (i.e i am not running Dota 2). This forces you in shutting down your computer while holding the on and off button, since the computer can't close it neither when you try to shut your computer down. When you start up dota, it will show you two icons:

![screen shot 2015-10-28 at 15 55 19](https://cloud.githubusercontent.com/assets/15364034/10792298/6cf3f234-7d8c-11e5-8f85-64d9fa837d4b.png)

**Comment by Sebby91** [comment]
Oops, forgot to add system info:

iMac 21.5 inch 2.7 GHz intel core i5.

**Comment by gdrewb-valve** [comment]
Probably the same as #603, which doesn't seem platform-specific (I believe there are reports for Windows too).

**Comment by Sebby91** [comment]
It will close down like usually tho, but the icon won't disappear. So I'm not sure if it is linked.

Edit: I even doubt whether it is running at all at that point, since it won't show up in the console/activity monitor.

**Comment by gdrewb-valve** [comment]
That would be an OSX bug then?  If Reborn isn't running but OSX is still showing it that's something weird in OSX.

However I think it's more likely that Reborn is lingering in a partially-shut-down state.

**Comment by Sebby91** [comment]
Would there be any way to check it right now? I haven't restarted yet so it's still showing its logo while not running.

I do know that on a different Mac (my girlfriends, but exactly the same model) this problem occurs too. I just can't tell how to reproduce it.

**Comment by gdrewb-valve** [comment]
In a terminal you should be able to do "ps -A | grep dota2" and see if there are any dota2 processes sitting around.

**Comment by Sebby91** [comment]
![screen shot 2015-10-28 at 22 41 30](https://cloud.githubusercontent.com/assets/15364034/10803919/0a8a5168-7dc5-11e5-93dd-15d0affd90e9.png)
Shows me this.

**Comment by gdrewb-valve** [comment]
Reborn isn't running then, so I have no idea why OSX would have two dock icons.  We'll have to try and repro.

**Comment by Sebby91** [comment]
I know it sounds stupid, but just starting up and closing it might do it. I will try to figure out these upcoming days if I do something special in Reborn what might trigger it, but in overall I spectate and play during one session. 

Edit: thank you for your time.

**Comment by gdrewb-valve** [comment]
I just tried it and it exited fine for me.  Are you running the stable Steam client or the beta Steam client?  If you aren't using the beta try opting into it and seeing if that helps you (I'm running the beta).

**Comment by Sebby91** [comment]
I was not using the beta Steam client. Will use it now. Will let you know if it still gives me trouble.

**Comment by Sebby91** [comment]
Okay, using the beta Steam now. After spectating one whole game (+ some alt-tabs in-between) and closing dota, the icon will not disappear again. Thus it might have something to do with either alt-tabbing or with spectating a game.

**Comment by gdrewb-valve** [comment]
OK, we'll try and find a repro.

**Comment by viettrung9012** [comment]
It could be a Mac's problem.
**References**:
http://apple.stackexchange.com/questions/176270/app-crashes-dock-icon-remains-cant-reboot-yet-no-process-in-ps-aux-to-kill?lq=1
I tried this and it works for me:

> `sudo killall launchservicesd`
> `sudo killall Dock`

**Comment by gdrewb-valve** [comment]
@Sebby91 does viettrung9012's approach work for you?  This doesn't appear to be a Reborn issue.

**Comment by Sebby91** [comment]
Haven't had this issue in more than a month I think, thought you guys solved it honestly. If it appears again I will try that fix.

**Comment by gdrewb-valve** [comment]
OK, closing.

**Comment by TrentBartlem** [comment]
Just started happening for me, but @viettrung9012's solution worked.

**Comment by gdrewb-valve** [comment]
Thanks, that reinforces that it looks to be on the OSX side.

**Comment by Sebby91** [comment]
Yeah I got it again for the first time in a long time. @viettrung9012 solution worked for me aswel.
