### ISSUE TITLE
[Mac El Capitan] Dota 2 Does Not Start

### ISSUE THREAD

**Issue by BirdInTheCity** [ValveSoftware/Dota-2#619]
So this is weird—I got a brand new 2015 iMac and have been playing Dota for a few days now at full-5k resolution with no issues.  Now for some reason, the game is no longer booting up for me.

The last time it launched successfully, I was attempting to lower the resolution:
Launched game
Settings > Changed resolution from 5120x2880 to 2560x1440 (cause of that damn small cursor!)
Clicked Apply

The screen went black, and never showed another image.  I tried escaping out, toggling to another app, Cmd + Alt + Esc.  Nothing worked.  So, I did a hard reboot.

Upon reboot, I opened Steam and launched Dota, but nothing happens.  There is no icon in the dock for Dota, but there is a CPU task for dota2 showing up in Activity Monitor.  

If I try to relaunch the game, it says "app already running".  
If I try to close Steam, it says "Please close Dota 2 before exiting Steam"
I've tried restarting, relaunching steam, setting -h 5120 -w 2880  launch parameters and I'm still not getting anything.  Any ideas?

Processor Information:
    Model:  iMac17,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.1 (64 bit)

Video Card:
    Driver:  AMD Radeon R9 M395X

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x1002
DeviceID:  0x6920
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.58" x 13.39"  (27.09" diag)
                                        59.9cm x 34.0cm  (68.8cm diag)
Primary VRAM: 2047 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  2970567 Mb
    Largest Free Hard Disk Block:  1439718 Mb

Installed software:
    1Password 5
    Accessibility Inspector
    Acrobat Distiller
    Adobe Acrobat
    Adobe After Effects CC 2015
    Adobe After Effects Render Engine
    Adobe Character Animator (Preview)
    Adobe Help
    Adobe Illustrator CC 2015
    Adobe InDesign CC 2015
    Adobe Media Encoder CC 2015
    Adobe Photoshop CC 2015
    Analyze Documents
    App Store
    Application Loader
    Automator
    Calendar
    Chrome Remote Desktop
    CINEMA 4D Lite
    CINEMA 4D QT Agent
    CineWare
    Contact Sheets
    Contacts
    Dropbox
    Elite Dangerous Launcher
    Export Flash Animation
    FaceTime
    FileMerge
    Game Center
    Gmail
    Google Chrome
    Google Drive
    Google Search
    iBooks
    Image Capture
    Instruments
    IntelliJ IDEA 14
    Keynote
    Kindle Cloud Reader
    Launchpad
    Make Calendar
    Maps
    Messages
    MiniTerm
    Mission Control
    mocha AE CC
    Notes
    Numbers
    Pages
    Photos
    Reminders
    SA Color Finesse 3 UI
    Steam
    Stickies
    Web Gallery
    Xcode
    YouTube

**Comment by gdrewb-valve** [comment]
Similar to #584.

**Comment by BirdInTheCity** [comment]
Can confirm.  `-fullscreen` fixes the issue.

**Comment by danginsburg** [comment]
If I'm understanding the bug report, things were working fine at 5120x2880 Desktop Friendly Fullscreen and when you switched to 2560x1440 Desktop Friendly Fullscreen the machine became unresponsive.  After that, it would not startup at all, until you set -fullscreen which would have changed the mode to Exclusive Fullscreen.  

I've been trying to repro this on some machines here but have not had any luck (I don't have your exact iMac config).  If you see it again, it might be helpful to run with -con_logfile and post game/dota/console.log.  As is, I'm not sure what could be going on here because I can't repro it.

**Comment by BirdInTheCity** [comment]
I'll see if it'll repro, and if so, I'll post the steps/logfile accordingly.

**Comment by gdrewb-valve** [comment]
Closing pending a repro.
