### ISSUE TITLE
[Win] 64-bit client crashes on hero grid

### ISSUE THREAD

**Issue by adityavm** [ValveSoftware/Dota-2#62]
When switching from other tabs to hero tab, then clicking on 'View Grid', the client crashes after a short while.

**Comment by r3pek** [comment]
You should report this on dev.dota2.com. This issue tracker is just for Linux/Mac.

**Comment by gdrewb-valve** [comment]
The larger team is aware of this, although I don't know more details than that.  Closing this out.
