### ISSUE TITLE
[OSX] Inventory Graphics Glitching

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#621]
This used to happen in DotA 2 source 1, when the support was ended. There were screen tearing and artifacts appearing in game and at the menu. I noticed similar artifacts but with Inventory/Items Graphics.

In the below image, the last item is a power thread.

![](https://cobalt60.xyz/shared/Screen-Shot-2015-10-29-at-3.13.20-PM.png)

OSX 10.11/Macbook Pro
Intel HD4000

**Comment by gdrewb-valve** [comment]
Does this happen all of the time?  Does it happen right when you start the game or after some series of actions?  If you demo a hero in Reborn and buy certain things does it show up?  If you know of a concrete repro that would make it easy for us to try out at Valve.

**Comment by gxgani** [comment]
If you look at the image again, I had safe play hour turned on and it
happened around 3rd hr mark. Was playing all pick ranked match. Around 5th
hour I noticed few more icons getting glitched. I guess it was helm/aegis.

**Comment by gxgani** [comment]
A side note, it wasn't happening to my inventory.

**Comment by danginsburg** [comment]
As @gdrewb-valve says, it would be very helpful to have clear repro steps.  Can you repro it in Demo Hero mode?

**Comment by gxgani** [comment]
Right now away from my desk. I'll get back to this issue tomorrow ASAP.

**Comment by gdrewb-valve** [comment]
Closing pending a repro.
