### ISSUE TITLE
[Linux] unable to report fellow players

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#623]
hi,
I just had a game in which unfortunately fellow player decided to ruin the game for us. To my surprise I found that both the report and commend function don't work. If I try to open the respective window from the context menu in the player or end screen it fails to do so.
There was no error message in the console.

**Comment by Turmfalke2** [comment]
update: apparently this is not always the case. After restarting due to the dc bug I was able to open the commend/report window. Maybe it is related to having played custom games prior to that?
I have noticed some information from custom maps like hero names persists until the game is restarted.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team to see what they say.

**Comment by Turmfalke2** [comment]
I was unable to reproduce it, I hope it is not something that can be triggered by a player.

**Comment by gdrewb-valve** [comment]
Nobody knew of anything specific.  If you see a consistent repro let us know, otherwise I'll close this waiting for a more clear sign.
