### ISSUE TITLE
[Linux] Got a new video card to improve frame & video, didn't help 

### ISSUE THREAD

**Issue by mwic** [ValveSoftware/Dota-2#624]
My GeForce GT 610 (2GB) arrived today, and I hoped I could play dota now, but it doesn't seem to have improved. 

The dashboard looks and runs okay, but the background is weird polygons similar to this:
https://i.imgur.com/RGGd0Rq.jpg
When I actually start a game, mouse keyboard response drops to zero, frame rate is basically zero, and the whole game looks like those polygons. It takes about 5 minutes to move the mouse onto the exit buttons

Notes:
Package 1:xorg-x11-drv-nvidia-libs-319.60-1.fc18.x86_64 already installed and latest version
Package 1:akmod-nvidia-319.60-3.fc18.x86_64 already installed and latest version
CPU is an AMD FX 8120 8-core, 8GB RAM

So the machine and GPU are definitely powerful enough, but I have a settings issue. 

Is there a guide to what settings should be tweaked in Lunux? For example, google keeps bringing up "Vsync" but nvidia-settings control panel doesn't seem to have an option for this. Unless "Sync to VBlank" is the same as "Vsync" ?

**Comment by Tele42** [comment]
As noted on https://github.com/ValveSoftware/Dota-2, nvidia drivers 340 or newer is needed to run Dota 2. That aside, a GT 610 is the weakest of the 6xx lineup that is still a discrete card (and is also a rebranded GT 520).

In general any nVidia card which is lower than x40 is considered entry level or low end graphics and is not suitable for general gaming, but who knows ... your substantial vram might let it work out.

Sync to Vblank removes the tearing commonly associated with having vsync off, without limited applications to the refresh rate of the display.

**Comment by mwic** [comment]
Apologies, somehow I read "340" as "304" before posting. Anyway, I upgraded fedora and got nvidia driver 352, and now steam is segfaulting : https://github.com/ValveSoftware/steam-for-linux/issues/4099

**Comment by gdrewb-valve** [comment]
We'll close this for now until you Steam gets updated and you can try again.  You might try opting into the Steam beta client if you haven't already.
