### ISSUE TITLE
[OSX 10.11] Custom Games: The lobby you specified no longer exists. *on certain maps*

### ISSUE THREAD

**Issue by jungelbobo** [ValveSoftware/Dota-2#625]
Basically same as this issue https://github.com/ValveSoftware/Dota-2/issues/27,
I was only able to join some of the lobby in custom map from the lobby list. The majority of other lobby, after clicking join lobby, shows me this message "The lobby you specified no longer exists".

**Comment by gdrewb-valve** [comment]
Likely not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
Confirmed that this is seen on Windows also, passing to the larger team.
