### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Figureantu** [ValveSoftware/Dota-2#626]
So i finished dwl the new update and the game crash..i mean i can open the game but if i press custom game the game autoclose and look at this image..
http://postimg.org/image/wn6636l4f/

**Comment by gdrewb-valve** [comment]
The downloaded does not appear to be have worked fully, trying validating your local file cache in the Steam client.

**Comment by gdrewb-valve** [comment]
Also if problems persist can you post your Steam system info?

**Comment by Figureantu** [comment]
I validated the cache and is working ty
