### ISSUE TITLE
[LINUX] Push to talk causes short system freeze

### ISSUE THREAD

**Issue by daveh86** [ValveSoftware/Dota-2#630]
System is an up to date ArchLinux system with XFCE window manager.

Sound is managed through pulse audio.

Microphone in question is a Webcam Microphone from a Logitech C525.

When using PTT in Dota2, the client will hang when initially using the mic. Subsequent uses within the next minute will not cause a hang. Any use outside 1min from last use will cause a new hang.

Hangs are typically 1-2 seconds in duration where the whole game appears to freeze and become unresponsive. No audio spoken during the freeze is heard by other users.

Check of dmesg shows that dota is triggering a full device reset every time this freeze occurs, likely the client waiting for the device to reset is the cause of the delays:

```
[ 4120.815343] usb 3-9: reset high-speed USB device number 5 using xhci_hcd
[ 4165.728009] usb 3-9: reset high-speed USB device number 5 using xhci_hcd
[ 4280.118817] usb 3-9: reset high-speed USB device number 5 using xhci_hcd
[ 4291.185116] usb 3-9: reset high-speed USB device number 5 using xhci_hcd
[ 4418.274143] usb 3-9: reset high-speed USB device number 5 using xhci_hcd
```

These resets were confirmed to be DOTA2 with simple, alt-tab and dmesg in console.

lsusb and lspci were used to confirm the device in question is indeed the microphone.

Other PTT audio products such as teamspeak do not trigger this behaviour, only Dota2

Initially, this was suspected to be related to a particular chipset and USB3 driver, but changing port had no impact.

**Comment by gdrewb-valve** [comment]
Reborn uses SDL for audio and so does nothing directly with audio devices itself.  I'll check with the SDL devs.

**Comment by gdrewb-valve** [comment]
This apparently may be a Steam interaction.  If you set the "Streamlined push to talk" option in the audio options page does that help?

**Comment by daveh86** [comment]
Yep. That seems to have done the trick. Tested in a local lobby, will hang without option set; no hangs without.

Thanks!
