### ISSUE TITLE
[Linux] RadeonSi / Mesa - Water rendering broken

### ISSUE THREAD

**Issue by dietrmat** [ValveSoftware/Dota-2#633]
Dear Devs,
since begin of november an update broke the water rendering on Mesa 11.0.4 and RadeonSi. Below are my system specs. Feel free to contact me if you need further information:

Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x3c
    CPU-Stepping: 0x3
    CPU-Typ: 0x0
    Geschwindigkeit: 3600 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerkinformationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "Manjaro Linux" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.2.5-1-MANJARO
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11704000
    X-Fenstermanager: GNOME Shell
    Steam-Runtime-Version: steam-runtime-release_2015-06-12

Grafikkarte:
    Treiber: X.Org Gallium 0.4 on AMD PITCAIRN (DRM 2.43.0, LLVM 3.7.0)

```
Treiberversion: 3.0 Mesa 11.0.4
OpenGL-Version: 3.0
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 60 Hz
Anbieterkennung: 0x1002
Gerätekennung: 0x6810
Anzahl der Monitore: 1
Anzahl der logischen Grafikkarten: 1
Prim. Anzeigeauflösung: 1920 x 1080
Desktopauflösung: 1920 x 1080
Prim. Anzeigegröße: 47,7 cm x 26,8 cm (54,7 cm diag.)

Kein prim. VRAM entdeckt
```

Soundkarte:
    Audiogerät: Realtek ALC662 rev1

Speicher:
    RAM: 7927 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 930713 MB
    Größter freier Festplattenspeicherblock: 408718 MB

Installierte Software:

Neueste Fehlerberichte:

![2015-11-05_00001](https://cloud.githubusercontent.com/assets/1543169/10978113/7957e476-83f5-11e5-890b-65c13fd09b6b.jpg)

**Comment by kolobos** [comment]
I don't have that issue on Mesa 11.1.0-devel Git master version (haven't tried Mesa 11.0.4 in November) on AMD Bonaire card, 4.3.0 kernel.

**Comment by danginsburg** [comment]
@dietrmat Are you able to test with mesa 11.1.0-devel git to confirm this issue has been fixed?  If not, we should file a bug with the mesa radeonsi devs.

**Comment by danginsburg** [comment]
Actually, this looks like an application bug when -gl_force_sm30 is turned on (which I'm guessing it is for your GPU because you have only 16 samplers).  I'm looking into it.

**Comment by danginsburg** [comment]
I have checked in a fix for this.  The fix will be in the next Dota 2 update.

**Comment by danginsburg** [comment]
This should be fixed in the Nov. 12th Dota 2 Update.  Please post here if you still see the bug.  I did not test the fix on radeonsi, but I saw the bug on several other drivers using -gl_force_sm30 so hopefully it should fix it there.
