### ISSUE TITLE
No teleport and blink effects on my compendium

### ISSUE THREAD

**Issue by caloyski34** [ValveSoftware/Dota-2#637]
I bought level 25 compendium last month but still there is no teleport/blink effects included to my compendium. i hope you can help me with this.

**Comment by gdrewb-valve** [comment]
Probably not a Mac/Linux issue.  Can you post your system specs from Steam?

**Comment by Tele42** [comment]
So there isn't confusion, this issue tracker is explicitly designated for issues with the mac and linux client of Dota 2. Issues that do not fit this criteria need to be addressed by the other existing communication methods (steam support and forums).
