### ISSUE TITLE
[Linux] Keyboard input bug

### ISSUE THREAD

**Issue by kpatient** [ValveSoftware/Dota-2#638]
### Behavior

When I press "1" on keyboard (not numpad) the chat box opens automatically with a 1 char inserted.
If I press 1 again, it will send the message to chat. 
This repeats if I keep pressing 1, but each time with more 1's in the chat box. 
(This behavior happens in game and in main menu with chat channels)

When this is happening I'm unable to use keyboard to activate any spells and inventory. However I can still type to chat with every key, except "1" obviously.
### When

It just seems to happen randomly. During matches. During sitting in the main menu. Around once a day. I've only noticed this in the last month, and I've been using reborn pretty much from day 1.

The only way I can remove this is by restarting X server. It stays if I just restart steam/dota.
### System

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"

**Comment by gdrewb-valve** [comment]
Looks the same as #453?  Down in the comments there's another user that has the '1' key interpreted as Enter.

Please also post here what system language or languages you're using and whether you're switching between languages or keyboard layouts.

**Comment by kpatient** [comment]
Yes you're right. I can now recreate this behavior if I launch Dota with `at, German (Austrian)` as keyboard layout. 

However If I launch with `gb, English (UK)` it works as normal, and I'm able to switch between layouts without this '1' bug appearing.

Note: "1" acts like enter but each time it pastes more 1's into the search box. So if you were to repeatidly press one it would look like this:
![screenshot from 2015-11-11 12 44 19](https://cloud.githubusercontent.com/assets/1618414/11090413/f4cbed84-8871-11e5-9c30-a7f77473dea3.png)
This resets back to "11" if you leave it for 15 or so seconds.

### System info

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2667 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.59
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 27,87" x 15,67"  (31,97" diag)
                                            70,8cm x 39,8cm  (81,2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7975 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  225218 Mb
    Largest Free Hard Disk Block:  78744 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment]
Thanks, closing in favor of previous issue.
