### ISSUE TITLE
The startmovie command does not record anything. 

### ISSUE THREAD

**Issue by TimotheeJeannin** [ValveSoftware/Dota-2#64]
From the http://www.dota2.com/reborn/part3 we can read that [SFM](http://www.sourcefilmmaker.com/) allows to render MP4 video of source2 games:

> When your creation is complete, render directly to MP4 video 
> with H.264/AAC encoding for the best quality settings for online viewing.

From the [valve documentation on video recording](https://developer.valvesoftware.com/wiki/Demo_Video_Creation) it looks like there is a command to record source games. 

```
startmovie %videoname% h264; playdemo %demoname%
```

Is this command available in Dota2 Reborn ? Is there any way I can record Dota2 from the command line ?

**Comment by gdrewb-valve** [comment]
startmovie is not currently supported in Source 2 (on any platform, this is not a Linux/Mac issue).  Keeping this open as a request to support it, but I can't say anything about if or when that will happen.

**Comment by gdrewb-valve** [comment]
Actually closing this as this has been passed on to the larger team and won't be tracked here.

**Comment by TimotheeJeannin** [comment]
Hi @gdrewb-valve, 

How can I check the status on this issue ? Is there any bug tracker for the larger team ? It would be great to have this command working ... 

Tim

**Comment by gdrewb-valve** [comment]
I believe the regular forums are at dev.dota2.com.

**Comment by RylanSchaeffer** [comment]
@gdrewb-valve any updates?
