### ISSUE TITLE
crash in main menu

### ISSUE THREAD

**Issue by m-rap** [ValveSoftware/Dota-2#642]
Hi, I was playing Dota 2 using my laptop and it always crashed in main menu. My OS is Archlinux and Windows 10, but it only happens when I run it using Nvidia GT 630m graphics card in both OS. It runs well if I use the onboard graphics card, Intel HD4000. here's my laptop spec:
Dell Inspiron 14R 5420
- Processor: Intel Core i5-3210M 2.5GHz
- Video card:
  - Nvidia GT 630M 1GB DDR3, driver ver 355.11-4
  - Intel HD4000
- RAM: 8GB
- OS: Archlinux 64-bit with Openbox WM and Windows 10 64-bit

I also attach the console output when I run the program using command `GAME_DEBUGGER="strace -o /dev/null" primusrun ./dota.sh > console.txt`. I'm not sure if it's a hardware issue because I can run other game like Robocraft using the Nvidia without issues.

Thanks

[console.txt](https://github.com/ValveSoftware/Dota-2/files/34845/console.txt)

**Comment by gdrewb-valve** [comment]
Looks like a possible video driver issue.  The same thing happens on Windows 10 also?  Are you forcing OpenGL mode on Windows 10?

**Comment by m-rap** [comment]
Yes, it also happens in Windows 10. I didn't use the OpenGL mode in Windows. When I run it in Windows, message "Display driver stopped responding and has recovered.." appeared.

**Comment by danginsburg** [comment]
The console log from Linux indicates a GPU hang (we are spinning waiting for a event query to respond and it never does).  That it happens on Windows 10 as well under DX9 (presumably) is curious.  It points to it not being a Linux/Mac issue but something either specific to your hardware or system config.

**Comment by m-rap** [comment]
i just updated primus and finally it hasnt crashed anymore, so apparently it was primus issue. but the issue that happened in windows is still mystery. thanks for your help. you guys have done a great job
