### ISSUE TITLE
Server should poll for x amount of minutes, and every player before poor network conditions error is thrown.

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#643]
I don't know how poor network conditions currently works, but it doesn't seem it's reliable or make any real sense. I've had games where every single person is lagging and poor network conditions aren't detected.

And I just recently had a game, where 2 people dropped and poor network conditions was thrown, meanwhile nobody was lagging. 

Can't see how complicated it would be to record ping, packet loss, through the match, and if things go above their averages, for ALL PLAYERS after X amount of time, say 5-10 minutes, then activate poor network conditions.

**Comment by gdrewb-valve** [comment]
This tracker is for Mac and Linux specific bugs so I'm closing this but I've passed your feedback on to the larger team.
