### ISSUE TITLE
Frankfurt Major Live Stream can't go fullscreen

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#644]
The new in-game live stream can't be made fullscreen. Clicking the fullscreen button only crops a few pixels around the borders, but the video does not go fullscreen.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Chakra" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.4-1-CHAKRA
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  2193620 Mb

Installed software:

Recent Failure Reports:

**Comment by phoerious** [comment]
The "Watch in Browser" button is also not opening the browser.

**Comment by gdrewb-valve** [comment]
The client is just going to do an xdg-open on a URL to show something in browser, is that available and working on your system?

**Comment by phoerious** [comment]
Yes, it is. It should open google-chrome.

**Comment by gdrewb-valve** [comment]
I'm not sure what's going on, then, this'll need more investigation.

**Comment by Tele42** [comment]
Last I heard, steam does not change (back) env variables before calling xdg-open, so if system-installed chrome can not run with libraries from the steam runtime, then it will fail.

**Comment by phoerious** [comment]
Steam is 32-bit, isn't it? My Chrome is 64-bit.

**Comment by phoerious** [comment]
Yip, that might be the issue. .xsession-errors reports:

```
ERROR: ld.so: object '/home/janek/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/janek/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/janek/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
kde-open5: /home/janek/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/libQt5Core.so.5)
kde-open5: /home/janek/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libQt5DBus.so.5)
kde-open5: /home/janek/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/libicui18n.so.53)
kde-open5: /home/janek/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/libicuuc.so.53)
kde-open5: /home/janek/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /usr/lib/libgcrypt.so.20)
```

That explains why the browser doesn't open, but it does not explain why fullscreen isn't working (no errors reported here).

**Comment by gdrewb-valve** [comment]
I'll fix the Steam runtime conflict.  Exactly which fullscreen button are you using?  The box-and-arrow button next to the "Watch in-game" button on the main menu launches a browser on my Windows box.  If you go in-game first then fullscreen would be done from video settings like usual.

**Comment by phoerious** [comment]
The one that's in the lower right corner of the video. Right next to the quality setting.

**Comment by gdrewb-valve** [comment]
I assume from the name this only happens with the Frankfurt major where it shows in-line on the main menu?  If you go to Watch -> Live and pick a game there you get different options, correct?

**Comment by phoerious** [comment]
Yes, I mean the one on the main page.
When I go to Watch->Live, then I only have the option, to watch in-game, not via "video" live stream. There is a second button that says "Fullscreen" but that one is grayed out (in fact, it has always been since the watch feature was introduced to Reborn, never understood what it was supposed to do).

**Comment by justSQL** [comment]
Can confirm, on Windows 10. The Frankfurt livestream on main page doesn't go fullscreen if i click on the fullscreen button on the lower right corner, next to the quality options.

Whenever clicking on the fullscreen button it almost like freezes for a little while, and after that the fullscreen-button moves a bit and looks like fullscreen is selected (At least that's what i assume it means). I took some bad screenshots that aren't aligned with each other, but you can see how the fullscreen button looks like it's enabled.

Screenshot taken before clicking the fullscreen button: https://i.imgur.com/tfu6KI3.jpg
Screenshot taken after clicking the fullscreen button: https://i.imgur.com/YvqfqVD.jpg

**Comment by jonglae** [comment]
oh my god
this is very curious

2015-11-18 23:45 GMT+09:00 justSQL notifications@github.com:

**Comment by phoerious** [comment]
@justSQL Looks like it's not a Linux-only issue then. I also notice that the video pane loses a few pixels of padding when attempting to go fullscreen. To me that looks pretty much like the fullscreen option just maximizes the video pane size to the size of the parent frame element instead of the whole screen.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.  Once the Linux-specific open-in-browser issue update goes out I'll close this.

**Comment by Tele42** [comment]
The xdg-open issue is also being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/3985.

**Comment by gdrewb-valve** [comment]
The latest update should fix the xdg-open problem, do you still have issues launching in a external browser?

**Comment by phoerious** [comment]
Hard to tell because there is no live stream panel anymore.

**Comment by gdrewb-valve** [comment]
OK, closing until we can verify if there's still an issue.

**Comment by kunalsinha** [comment]
I am facing the same issue with Shanghai major live stream. Full screen not working.

**Comment by gdrewb-valve** [comment]
Fullscreen not working is not a platform-specific thing so you'll want to report it at dev.dota2.com
