### ISSUE TITLE
[Linux] Missing characters in console / ugly font

### ISSUE THREAD

**Issue by presianbg** [ValveSoftware/Dota-2#645]
Hi,

This is how my console looks like:
![screenshot from 2015-11-16 13-27-14](https://cloud.githubusercontent.com/assets/2163486/11180797/3344fa2c-8c66-11e5-8e88-18fa618276ee.png)

My specs:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 23 (Twenty Three)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-300.fc23.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11800000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 

    Driver Version:  3.0 Mesa 11.1.0-devel
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x416
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  11459 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  105040 Mb
    Largest Free Hard Disk Block:  32413 Mb

Installed software:

Recent Failure Reports:

```

I'm on Fedora 22 with Optimus technology enabled + Mesa 11 git and latest nvidia-352.

Should be some kind of font related issue but can't track it down.

Best Regards,
presianbg

**Comment by Tele42** [comment]
Per #120, is ttf-mscorefonts installed on your system?

**Comment by presianbg** [comment]
Sorry for the duplicated issue.

**Comment by presianbg** [comment]
After some thoughts I'm wondering why ttf-mscorefonts are mandatory? In CS:GO console is readable and good looking (without  ttf-mscorefonts). Even after installing ttf-mscorefonts Dota 2 Reborn console is ugly (badly formatted). Why those fonts are hard codded?

**Comment by gdrewb-valve** [comment]
The problem comes because Reborn uses a limited fontconfig fonts.conf in order to have better control over the main menu rendering.  That spills over to the console but not really intentionally, it's just that the console is an older piece of code that is going to be replaced so it hasn't gotten much attention.

There are other issues here covering replacing the console so I'm closing this out.  For now installing ttf-mscorefonts is the best workaround.
