### ISSUE TITLE
[OS X El Capitan] 30 FPS on OS X, but 60 FPS on Windows 10 with the same configuration

### ISSUE THREAD

**Issue by icarus-schleg** [ValveSoftware/Dota-2#646]
Hello there. I have Bootcamp installed on my iMac (late 2013) and I see that on Windows I have 60 fps, but when i boot from OS X, I get 30 fps. Is this only for me? Need more feedback.

Configuration:
GeForce GTX 780M 4096MB
Core i7 3.5 GHz
32 GB RAM

**Comment by gdrewb-valve** [comment]
There are known perf problems in OpenGL on OSX that we are working on with Apple, you are probably running into some of those.

**Comment by danginsburg** [comment]
Does the NVIDIA web driver improve anything for you: http://www.nvidia.com/download/driverResults.aspx/92173/en-us ?  If not, can you please provide the following details: Steam -> Help -> System Information, your in-game video settings, and what resolution you are running on.  Also it sounds like you maybe have vsync on, can you see if it runs any better with vsync off or in exclusive fullscreen vs desktop-friendly fullscreen?

**Comment by jeanlain** [comment]
With that Mac, you should get at least 60 fps on OS X, at max settings. I get 60 fps with a  geforce 775m with every video effect enabled.

You may be running into that issue: https://github.com/ValveSoftware/Dota-2/issues/248
(edit: follow Dan's recommendation about fullscreen mode)

**Comment by danginsburg** [comment]
As @jeanlain points out if you have vsync on please try either turning it off or using Desktop-Friendly Fullscreen.  I am going to close this bug pending more information (i.e. System info, resolution/mode you are running at, video settings).
