### ISSUE TITLE
Server timed out while viewing or playing in game

### ISSUE THREAD

**Issue by nemoo2** [ValveSoftware/Dota-2#647]
I'm on openSuse 13.2, and I noticed an issue that just started recently, after update to Version 1,170. After doing some debugging myself, I'm convinced it is a client issue. 

It seems that when some packets are dropped (high latency?) due to my connection, the game cannot recover and continues to Auto-disconnect after 30 seconds of inactivity. I had a parallel terminal where I pinged the server below and the ping seems normal, except for a couple of fairly large lag spikes.

64 bytes from 192.69.96.35: icmp_seq=133 ttl=56 time=79.6 ms
64 bytes from 192.69.96.35: icmp_seq=134 ttl=56 time=77.8 ms
64 bytes from 192.69.96.35: icmp_seq=135 ttl=56 time=166 ms
64 bytes from 192.69.96.35: icmp_seq=136 ttl=56 time=106 ms
64 bytes from 192.69.96.35: icmp_seq=137 ttl=56 time=234 ms
64 bytes from 192.69.96.35: icmp_seq=138 ttl=56 time=381 ms
64 bytes from 192.69.96.35: icmp_seq=139 ttl=56 time=76.9 ms
64 bytes from 192.69.96.35: icmp_seq=141 ttl=56 time=72.9 ms
64 bytes from 192.69.96.35: icmp_seq=142 ttl=56 time=72.2 ms

==In game console log==
      client    192.69.96.35:28085[0]:  split packet seq #990 restarting, just received packet 0
      client    192.69.96.35:28085[0]:  split packet seq #1266 restarting, just received packet 0
CL:  WARNING:  Connection Problem, requesting uncompressed update
      client    192.69.96.35:28085[0]:  incoming timing out, last received 168.614899 [9.08 seconds ago]
      client    192.69.96.35:28085[0]:  incoming timing out, last received 168.614899 [19.11 seconds ago]
      client    192.69.96.35:28085[0]:  incoming timing out, last received 168.614899 [29.13 seconds ago]
Server connection timed out.
CL:  Server disconnected: #GameUI_ClientConnectionTimedOut
==End console log==

Is there anything I can do to get further logs / debugging information? Game is obviously unplayable for me in this state.

**Comment by gdrewb-valve** [comment]
The game works correctly and you can play normally up to this point, or does it never start?  Are you in the middle of playing when it happens or did you do something like switch out of the client when it occurs?

**Comment by gdrewb-valve** [comment]
Also set your launch options to this:

-profile 1 -condebug +net_maxroutable 576 +net_showsplits 1 +net_showudp 1

And post a gist of the "console.log" file the Reborn folder.

**Comment by gdrewb-valve** [comment]
Another thing to try in your other terminal is "traceroute --mtu |ipaddress|" to see how the routing is working.

**Comment by nemoo2** [comment]
The game works correctly and I can play normally upto that point. 

I will collect the log traces and post them this evening.

Interesting point about the traceroute. I don't see how the route itself would affect the client but not the ping, but I'll let you know this as well in the evening.

**Comment by gdrewb-valve** [comment]
The traceroute is to check the supported MTU size on the route.  Reborn assumes a particular MTU size and if the route doesn't support it you'll get packet splitting and problems.  The +net_maxroutable controls this and sets it lower so if that makes things work that's another suggestion that it's an MTU size issue.

**Comment by nemoo2** [comment]
I did not get DCed today. Either something was fixed server side, or my internet was good today. Will keep trying and post logs whenever the issue recurs. You can suspend/freeze the issue till I get the logs.

**Comment by gdrewb-valve** [comment]
OK, I'll close for now and we can reopen later.

**Comment by nemoo2** [comment]
Request to reopen this issue. Tracepath shows an MTU of 1500 between my machine and the Valve servers. The game still disconnects frequently despite restricting it to an MTU of 576. Below is a snipped of the console.log

179.3871 /    672.52:  CGameResourceService::BuildResourceManifest(start)
179.3872 /      0.17:  CGameResourceService::BuildResourceManifest(finish)
<-- [client] split packet seq #2023 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2023 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2023 packet    2/   3 size  272 mtu  576 from 208.78.164.221:28138
179.6144 /    227.20:  CGameResourceService::BuildResourceManifest(start)
179.6145 /      0.12:  CGameResourceService::BuildResourceManifest(finish)
<-- [client] split packet seq #2024 packet    0/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    1/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    2/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    3/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    4/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    5/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2024 packet    6/   7 size  159 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2025 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2025 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2025 packet    2/   3 size  167 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2026 packet    0/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2026 packet    1/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2026 packet    2/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2026 packet    3/   4 size  250 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2027 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2027 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2027 packet    2/   3 size  547 mtu  576 from 208.78.164.221:28138
179.9332 /    318.63:  CGameResourceService::BuildResourceManifest(start)
179.9333 /      0.17:  CGameResourceService::BuildResourceManifest(finish)
179.9349 /      1.53:  CGameResourceService::BuildResourceManifest(start)
179.9349 /      0.06:  CGameResourceService::BuildResourceManifest(finish)
<-- [client] split packet seq #2028 packet    0/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2028 packet    1/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2028 packet    2/   4 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2028 packet    3/   4 size   20 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2032 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2032 packet    1/   2 size  472 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2033 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2033 packet    1/   2 size  433 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2034 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2034 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2034 packet    2/   3 size  288 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2035 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2035 packet    1/   2 size   47 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2036 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2036 packet    1/   2 size   33 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2037 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2037 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2037 packet    2/   3 size  265 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2038 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2038 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2038 packet    2/   3 size   72 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2039 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2039 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2039 packet    2/   3 size  164 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2040 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2040 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2040 packet    2/   3 size  268 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2041 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2041 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2041 packet    2/   3 size  361 mtu  576 from 208.78.164.221:28138
180.8428 /    907.90:  CGameResourceService::BuildResourceManifest(start)
180.8429 /      0.09:  CGameResourceService::BuildResourceManifest(finish)
<-- [client] split packet seq #2042 packet    0/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    1/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    2/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    3/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    4/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    5/   7 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2042 packet    6/   7 size  366 mtu  576 from 208.78.164.221:28138
180.9393 /     96.34:  CGameResourceService::BuildResourceManifest(start)
180.9394 /      0.11:  CGameResourceService::BuildResourceManifest(finish)
180.9407 /      1.36:  CGameResourceService::BuildResourceManifest(start)
180.9408 /      0.06:  CGameResourceService::BuildResourceManifest(finish)
180.9414 /      0.60:  CGameResourceService::BuildResourceManifest(start)
180.9414 /      0.05:  CGameResourceService::BuildResourceManifest(finish)
<-- [client] split packet seq #2043 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2043 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2043 packet    2/   3 size  158 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2044 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2044 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2044 packet    2/   3 size   22 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2045 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2045 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2045 packet    2/   3 size   89 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2046 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2046 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2046 packet    2/   3 size  317 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2047 packet    0/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2047 packet    1/   3 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2047 packet    2/   3 size  157 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2048 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2048 packet    1/   2 size  228 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2049 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2049 packet    1/   2 size   98 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2050 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2050 packet    1/   2 size  479 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2051 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2051 packet    1/   2 size  373 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2052 packet    0/   2 size  558 mtu  576 from 208.78.164.221:28138
<-- [client] split packet seq #2052 packet    1/   2 size  172 mtu  576 from 208.78.164.221:28138
CL:  WARNING:  Connection Problem, requesting uncompressed update
      client  208.78.164.221:28138[0]:  incoming timing out, last received 168.963608 [9.79 seconds ago]
      client  208.78.164.221:28138[0]:  incoming timing out, last received 168.963608 [19.83 seconds ago]
      client  208.78.164.221:28138[0]:  incoming timing out, last received 168.963608 [29.83 seconds ago]
CL:  Server disconnected: #GameUI_ClientConnectionTimedOut
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
CL:  Disconnecting from server: #GameUI_Disconnect_TimedOut

**Comment by gdrewb-valve** [comment]
It's unlikely your issue is related to Linux, you'll want to post at dev.dota2.com

**Comment by nemoo2** [comment]
Ok. Thanks for the quick reply.

On December 20, 2015 8:28:02 PM EST, Drew Bliss notifications@github.com wrote:

> It's unlikely your issue is related to Linux, you'll want to post at
> dev.dota2.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ValveSoftware/Dota-2/issues/647#issuecomment-166171240

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
