### ISSUE TITLE
Cosmetic item styles don't display in demo mode.

### ISSUE THREAD

**Issue by nellh** [ValveSoftware/Dota-2#648]
If I load into demo mode, no particles on the Axe cape:
![Demo mode](http://images.akamai.steamusercontent.com/ugc/583575429755470743/3B52CB244A3289FFD93DD3C3F6F918569528BF02/)

I do have the effect unlocked.

If I load into a single player bot game I get particles:
![Bot game](http://images.akamai.steamusercontent.com/ugc/583575429755471422/EDCABF53BE4993D4099D0C04211082D83D15778F/)

[System info](https://gist.github.com/NellH/bb6e5e694626598c3005)

**Comment by gdrewb-valve** [comment]
Probably not Linux-specific.

**Comment by gdrewb-valve** [comment]
The larger team mentioned that you need to select the style in the loadout screen in order to see it on your hero in demo mode.  If you try that does it work?

**Comment by nellh** [comment]
@gdrewb-valve I do have the style selected in both modes despite what it looks like in the first screenshot. It is displayed incorrectly in demo mode, both for the actual effect and the UI showing equipped items. A real matchmaking or bot game, the selected style works as expected.

**Comment by gdrewb-valve** [comment]
Do you have the item equipped?  Apparently if you equip it you'll get style 1in this case, which is why the game is showing that you have style 1 selected.  Can you list the exact steps you're doing for the demo starting from selecting Axe?

**Comment by nellh** [comment]
@gdrewb-valve Here's a video of exactly what I'm doing. https://www.youtube.com/watch?v=7p42-5k2EIY

**Comment by gdrewb-valve** [comment]
Thanks, the larger team was able to repro and they'll be taking a look.
