### ISSUE TITLE
Weird in-game UI after lag/fps drop in Linux.

### ISSUE THREAD

**Issue by TheBatman** [ValveSoftware/Dota-2#649]
In the middle of a game i get some weird FPS drop or lag?  and after the Drop or lag the UI gets weird.
srry for the bad english :(.

PC specs:
Processor: AMD A8-6410 APU with AMD Radeon R5 graphics x4
RAM: 8GB DDR3
Graphics: AMD Radeon R5 1GB of Vram
![2015-11-17_00001](https://cloud.githubusercontent.com/assets/13712357/11261111/18002eda-8e37-11e5-8864-ed162840015c.jpg)

thats a pic of the problem.

**Comment by danginsburg** [comment]
Can you please post your full system specs from Steam -> Help -> System Information.

**Comment by TheBatman** [comment]
@danginsburg  Here 
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x16
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-33-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon(TM) R5 Graphics        

```
Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9851
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  6848 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461830 Mb
    Largest Free Hard Disk Block:  367794 Mb

Installed software:

Recent Failure Reports:

**Comment by danginsburg** [comment]
OK, your driver (Catalyst 15.3) has known issues and is below the recommended driver.  Please update to latest Catalyst 15.9 driver for Linux: http://support.amd.com/en-us/download/desktop?os=Linux%20x86_64

**Comment by TheBatman** [comment]
I updated to the lastest AMD Catalyst 15.9 driver do you want me to post the System info?.

**Comment by danginsburg** [comment]
Did it fix the corruption?

**Comment by TheBatman** [comment]
Yeah there's no more UI corruption, i tested TF2 and DoD:Source  the console spams this:
"IDirect3DQuery9::GetData(): Occlusion query flush took 9.544ms!" the numbers change.

**Comment by danginsburg** [comment]
Thanks for the update, closing. You can file TF2 bugs here: https://github.com/ValveSoftware/Source-1-Games/issues

**Comment by TheBatman** [comment]
Thank you! :D
