### ISSUE TITLE
starting to load a custom game while spectating live game crushes the client

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#651]
was waiting too long for that custom game lobby to be filled, so i started to watch some live game from the majors. after i clicked "Accept" and 10/10 were there – the game crushed to desktop.
was still able to restart in time and load into current lobby normally.

tested out two more times – same happens only with live-games, not replays.

not sure if its a mac-only issue, but i have no way to test it on windows.

**Comment by gdrewb-valve** [comment]
Not a platform-specific issue (there have been others like this, such as #153) and the larger team has already been notified.
