### ISSUE TITLE
Timedemo not displaying benchmark information

### ISSUE THREAD

**Issue by egeexyz** [ValveSoftware/Dota-2#652]
According to the Valve Developer Community Wiki, users can use the 'record' feature to record demos, and then use the 'timedemo' function to playback the demo along with benchmark information (fps, etc). This method works well with HL2, TF2, Portal, and L4D2. It does not work with Dota2.

It appears that recording and playing back a demo using 'timedemo' does the _exact_ same thing is 'playdemo'.

Steps To Reproduce:
1. In Dota2, create a sample demo (I used the initial tutorial)
2. From the Dota2 main screen, use the 'timedemo' function to replay the video

Expected Result: Benchmark information should be presented

Actual Result: No benchmark information is displayed at all

It should be noted once again that 'timedemo' works perfectly with all other Source games I tested. Dota2 does not work for some reason.

Reference - https://developer.valvesoftware.com/wiki/Demo_Recording_Tools

**Comment by ArnaudAndre** [comment]
> Dota2 does not work for some reason.

Since the reborn update dota 2 isn't running on the source engine but on source 2. Any doc written for source should be treated as potentially obsolete.
I don't know if there's a replacement for timedemo benchmarks though. Vconsole2 may have some stuff but it isn't included in the linux build.

**Comment by danginsburg** [comment]
Source 2 does support writing benchmark information to disk.  When you run a timedemo a new line will be added to game/dota/Source2Bench.csv.  The columns in the CSV file are:

demofile,frame data csv,fps,fps variability,total sec,width,height,numframes,dxlevel,backbuffer,cmdline,driver,vendor id,device 

If you are looking to grab the FPS average over a timedemo, it is the third column.

**Comment by egeexyz** [comment]
> Source 2 does support writing benchmark information to disk.

Interesting, that is news to me. Is this documented somewhere? Can somebody (perhaps me?) add this to the Developer wiki?

> If you are looking to grab the FPS average over a timedemo, it is the third column.

That's pretty cool. I'll check it out later this evening.

**Comment by egeexyz** [comment]
I've confirmed this work. Documentation needs to be updated but other than that, timedemo works as expected.
