### ISSUE TITLE
[Linux] Dota does not recognize hotkeys

### ISSUE THREAD

**Issue by Myppomeu** [ValveSoftware/Dota-2#654]
Debian 8 x64, KDE 4.
Nvidia GeForce GTX560 with 340.65-2 blob drivers.
Steam for linux and Dota 2 Reborn with latest updates.

Dota does not recognize if I press any hotkey. If I try to change hotkey, Dota will display empty hotkey.
There is no specific output in terminal. Problem appears after 26 october (this is last day until today I played Dota, and 26 october everything works correct).

**Comment by gdrewb-valve** [comment]
Can you add -input_message_spew and -console to your Reborn launch options, then open the console in the main menu and press the keys that you care about?  Post the Reborn console spew back here so that we can see what key info is being received.

**Comment by Myppomeu** [comment]
If I add this options... Dota recognizes hotkeys correctly.
Also it works fine if I switch to xfce or cinnamon.
Don't know what is it, but solution (adding this options or switching to another DE) is satisfy me.
Thanks for quickly answer!

**Comment by gdrewb-valve** [comment]
Those options don't really change anything about the input processing so it's odd that they would fix the behavior.  I guess we'll close this one for now and see if a pattern develops at some future point.

**Comment by Ace5040** [comment]
my config is: archlinux x64 with lxde on amd fx6300 + gtx750ti
I've managed to reproduce this bug. It is happened when dota started with russian keyboard layout selected. Iv'e added "-input_message_spew" to launch options and then try to bind 'q' for the first spell key. Here is what I got in output:
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=1081 sdlscancode=20 SDL_GetKeyName='9' buttoncode=0 buttonname='' ButtonCode_GetLocalKeyNameUTF8=''
SDL:  got SDL_TEXTINPUT
TEXTINPUT 'q'
SDL:  got SDL_KEYUP
KEYUP (keyc) sdlkeycode=1081 sdlscancode=20 buttoncode=0 buttonname=''

The only way to fix this in game that i have found is to restart dota with english keyboard layout. but some times its not helping though and some games were ruined...

P.S.: sorry for my english)

**Comment by gdrewb-valve** [comment]
If you go to the Advanced section of the key bindings section and check the positional bindings option how does that change things?

**Comment by Ace5040** [comment]
hotkeys->advanced->positional bindings
fixes problem right in the game. thanks for pointing out. but all key bindings in hotkeys options changes to russian. its better then restarting though)

**Comment by gdrewb-valve** [comment]
When you choose positional bindings the binding will be for specific key placements on the keyboard, not named keys.  In the default mode it is by named key.  In other words by default if you bind to English 'E' it's triggered by 'E'.  If you change keyboard layouts it's still 'E', wherever that is.  If you use positional keys then it's the physical key, not 'E', and doesn't change when you switch layouts.  The UI shows you whatever happens to be mapped to that key so that's why things switch to Russian when you change layouts.  That's all expected behavior.

**Comment by GTRONICK** [comment]
I have a similar problem on Archlinux x64 with XFCE. If I change the keyboard layout on game, the hotkeys for select courier and deliver items are not detected, even if I change the layout again. I must restart Dota in English layout to make it work properly. I will take a look on the advanced options to select the positional bindings and will report what happens next. Thanks.

**Comment by vladimirivanoviliev** [comment]
I think positional binding should be enabled by default as in some distros when you start the game with different than EN layout, and than switch to EN the game does not recognize it.

**Comment by alex3kov** [comment]
I agree that it should be enabled by default. Played several games without hotkeys before figuring this out.

**Comment by xakepp35** [comment]
WTF linux is real GOD of developement (I am C/++ dev, 4ever I've used colsole with alt+F*, gcc, make, cmake maybe), but X.Org and same - real WET SUXXX in the gaming world.. UNCODE YOUR X.Shit back! IMMEDIATELY!!!111 I am burning, i cant install-play dota, as i could on windows! Thanks, @gdrewb-valve, he could post something vital
