### ISSUE TITLE
[Solved/worked around] CapsLock hotkey broken for several months

### ISSUE THREAD

**Issue by dubslow** [ValveSoftware/Dota-2#656]
Since shortly before the old client died, my CapsLock hotkey in reborn hasn't worked. It worked fine for the first month or two of reborn, but for several months now it hasn't worked, and it's the primary reason I've mostly switched to CSGO

This is on Mint Debian with all updates installed (Cinammon 2.8, `uname -a
Linux Gravemind 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux`). More specs can be provided upon request/instruction

**Comment by dubslow** [comment]
I just had a brainwave. A couple of years ago I had disabled CapsLock on an OS level so that I could use it as a hotkey and still type normally. Some change some months ago in Reborn must have involved a change in the Linux keyboard input mechanism, for as I just tested now, re-enabling the CapsLock on an OS level re-enabled the hotkey.

![screenshot from 2015-11-26 05 40 11](https://cloud.githubusercontent.com/assets/6127392/11422268/2e368b1c-9400-11e5-9132-077ca4211609.png)

(Screenshot is of the disabled option I previously had it on, in order to use the hotkey in Dota I now have to set it to "enabled". None of the other options are tested)

Obviously, since it had worked for multiple years in Source 1 and Source 2, the option doesn't disable the key entirely, just the capitalization effect. Unfortunately whatever change in the Linux backend for keyboard input is now overridden by the OS option it would seem. I would still consider this a bug, as whenever I play, I'll now have to be careful with my capitalization...

**Comment by gdrewb-valve** [comment]
Can you add -input_message_spew and -console to your launch options, then open the in-game console and press caps lock?  That should generate some keyup and keydown spew in the console which you can post here.  Trying it both when it works and when it doesn't would be useful.

Also in the Advanced section of the Reborn key bindings settings you can select positional key bindings and that make fix things / make them work more like Source 1.

**Comment by gdrewb-valve** [comment]
I just double-checked this on my Ubuntu 12.04 system and had no problem binding caps lock.

**Comment by dubslow** [comment]
Sure, I'll do the former within a day or two.

What does positional key bindings mean? (Maybe I'll figure it out when I actually look at the option)

**Comment by gdrewb-valve** [comment]
By default Reborn binds keys based on the keycap name -- binding the 'A' key means that it's whatever key has 'A' on it and so moves when keyboard layouts change -- and positional bindings means that they key is bound by its position on the keyboard instead (and so doesn't change with keyboard layout).  If your caps lock behavior change is something like a keyboard layout change then it might be affected by this.

**Comment by dubslow** [comment]
With CapsLock disabled on OS keyboard options, default reborn settings: http://pastebin.com/v51ZWhxy and I cannot set CapsLock as a hotkey.

With CapsLock disabled, and bindings on keyboard position instead of keyboard name: http://pastebin.com/PEtcQ5MC and still unable to set CapsLock as a hotkey.

At this point, when I re-enabled CapsLock in the OS and went back into Dota to view the settings, suddenly the CapsLock name appeared on the correct hotkey, even though I didn't try to set anything. Since I hadn't disabled key position binding, maybe that does allow me to set the hotkey, but it just doesn't show the name in the UI. Testing with a bot match...

Okay yes, enabling position-based keyboard input fixes the problem with CapsLock disabled, but the hotkey UI doesn't show the CapsLock name, even though pressing the key does set the hotkey, which was a bit confusing. Strangely enough, "CapsLock" still does show up in the in-game UI though (with postional input and OS CapsLock disabled). So with positional input enabled, the only bug is that the hotkey UI doesn't work, even though the ingame UI does.

**Comment by dubslow** [comment]
I guess I could maybe have left this open since the UI doesn't work, but you should have the info you need now.

**Comment by gdrewb-valve** [comment]
Thanks, this is probably similar to the other bugs in SDL dealing with keys (the SDL_GetKeyName='' means SDL doesn't have a name for the key even though it should).

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this is active.

**Comment by dubslow** [comment]
The workaround we implemented remains in effect, or at least, I haven't ever messed with the settings since then. As of a month ago, it still worked. If you want I'm willing to do further testing.
