### ISSUE TITLE
[Linux] Game freezes when match ready 

### ISSUE THREAD

**Issue by dracorl** [ValveSoftware/Dota-2#657]
Game freezes when match ready and I can't click.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  <Unknown>
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xdf4
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13,54" x 7,60"  (15,51" diag)
                                            34,4cm x 19,3cm  (39,4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  3862 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  596825 Mb
    Largest Free Hard Disk Block:  543415 Mb

Installed software:

Recent Failure Reports:

```

**Comment by gdrewb-valve** [comment]
Probably not a Linux-specific issue.

**Comment by nooscraft** [comment]
Seems like you have a notebook with on-board Intel VGA. So the freezing might cause because of your hardware is not supporting well with Dota2 (can @gdrewb-valve confirm this?)

Anyhow have you tried with lowest graphics settings?

**Comment by dracorl** [comment]
I am using nvidia-358 and bumblebee on dota2. My graphic card is bad so i already use low graphics. sometimes freezes sometimes not.

**Comment by nooscraft** [comment]
@dracorlll Try installing a nvidia open source driver for Ubuntu. Use this ppa http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu

**Comment by dracorl** [comment]
ok thank you

**Comment by gdrewb-valve** [comment]
Reborn on Linux uses OpenGL and support is primarily about good OpenGL drivers.  With a good driver and reasonable hardware Reborn should run fine.  Unfortunately OpenGL driver support on Linux varies tremendously in quality and often vendors don't bother trying to support older hardware, plus then there are open-source variants for many pieces of hardware.  Valve doesn't attempt to track what works on what.

**Comment by ab5trakkt** [comment]
I've been hitting this issue every single time I start a match since this past
weekend. Sometimes the dota UI doesn't even load. I'm running this on a GTX 680, and I've tried it with both the 310 and 352.63 drivers. 

[dumps.zip](https://github.com/ValveSoftware/Dota-2/files/62015/dumps.zip)

**Comment by gdrewb-valve** [comment]
Is this still happening with the latest drivers and Reborn updates?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation this is still active.
