### ISSUE TITLE
Low priority mechanics should be changed.

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#658]
I know this isn't for issues for general Dota, but maybe you can forward it to the team. I haven't been in low priority in months, but the current set up that everyone has to be present to count the game as a win is very harsh.

It can take you 10 games, just to finish a 3 game low priority due to people leaving and abandoning which happens very often in these types of games. 

Low priority should be reverted to the old design, where even if someone leaves, if you finish the game it should count. 

Thanks

**Comment by gdrewb-valve** [comment]
I've passed this on.
