### ISSUE TITLE
[Linux] Auto-disconnect message does not go away after disconnection

### ISSUE THREAD

**Issue by daniele-salvagni** [ValveSoftware/Dota-2#66]
The red "WARNING: Connection Problems. Auto-disconnect in ..." message does not go away after disconnecting from a game. In my case I was disconnected from a custom game, but I think it could happen also in normal ones. The message is static, the timer does not decrease.

![Screenshot](http://i.imgur.com/2WUMANE.jpg)

Liux distro based on Ubuntu 14.04 LTS, nvidia-346 with bumblebee and primus.

**Comment by blendi-93** [comment]
confirm

**Comment by r3pek** [comment]
Had it too yesterday (ArchLinux + nvidia fully updated)

**Comment by gdrewb-valve** [comment]
This isn't Linux/Mac-specific so we won't get tracking here but the larger team says that it should be fixed.

**Comment by Turmfalke2** [comment]
@gdrewb-valve this isn't the case, even going into a new game (hero demo mode) won't fix it.

![dc_bug](https://cloud.githubusercontent.com/assets/5174562/10848763/bd88c7d2-7f1d-11e5-9b84-978e6250c1b2.png)

If it is fixed on windows, maybe this thread should be reopened?

**Comment by gdrewb-valve** [comment]
If it's not working it wouldn't be specific to Linux.  I'll check with the larger team again.
