### ISSUE TITLE
Poor performance with external display on Macbook

### ISSUE THREAD

**Issue by NekR** [ValveSoftware/Dota-2#662]
I am trying to play Dota 2 Macbook Pro 15'' 2015 with external display connected via HDMI and I am getting 10-20 fps there on low settings. Monitor is 22'' 1920x1080.

Without external monitor, on Macbook's own Retina display I get 120 fps with disable VSync even on close so high-quality settings. however resolution there is 1280. Is the problem here in monitor resolution or maybe because it's connected via HDMI?

I tried with lid closed (external monitor only detected by the system) and with lid opened (mirrored displays). Same results.

**Comment by NekR** [comment]
```
Processor Information:
    Model:  MacBookPro11,4
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.1 (64 bit)

Video Card:
    Driver:  Intel Iris Pro

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0xd26
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.82" x 10.55"  (21.57" diag)
                                            47.8cm x 26.8cm  (54.8cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  16384 Mb
```

**Comment by NekR** [comment]
Just downloaded StarCraft 2 and tested on external display. It shows 30fps when VSync is **on** and 80fps when VSync is **off**.

I am not sure why it thinks that monitor's refresh rate is 30 Hz, but at least it can produce 80fps without VSync. Dota 2 always produces 10-20 fps (cannot get stable value, always jumps).

**Comment by danginsburg** [comment]
So if you do not use an external monitor and set your resolution to 1920x1080, do you still see the performance problem?  Are you in Exclusive Fullscreen or Desktop Fullscreen?

**Comment by NekR** [comment]
@danginsburg I had those results in both Exclusive Fullscreen and Desktop Fullscreen, but now I have different results:
- Open laptop lid, disable external monitor
- Run Stream, run Dota 2
- Set resolution to ~1600 width Exclusive Fullscreen
- Start bot match -- 60fps VSync **on**
- Exit bot match, set resolution to ~2800 width, Exclusive Fullscreen
- Start new bot match -- 30fps VSync **on**, disable VSync -- 40fps
- Exit Dota 2
- Connect external display, close laptop lid (external display is primary and since display now)
- Launch Dota 2, set resolution to monitor's native (1920x1080), Exclusive Fullscreen.
- Start bot match -- 30fps VSync **on**, disable VSync -- 80fps
- Exit Dota 2 (do not check VSync back before it)
- Exit Stream
- Launch Stream, Launch Dota 2
- Start bot match -- 80fps VSync **off**
- Enable VSync -- **60fps**

I do not get how it works anymore...

P.S. All visual settings are unchecked (Shadow, Light, etc). Textures are set to "High". Only VSync value was changed during tests. I also have weather "Rain" effect enabled.

**Comment by budimanjojo** [comment]
Because the larger the resolution of the monitor the lower the fps, that's how it should work. You can't just put in a big monitor with Intel graphic, that's why people invest on Nvidia or AMD cards. I think it's normal to have 40 fps on a 2800 width resolution.

**Comment by NekR** [comment]
@budimanjojo hah, I didn't bought it for playing, if I would, I rather get very good gaming PC for the same price as Macbook.

Anyway, just played a game on external monitor with VSync on and had 60fps and sometimes 30fps during game. Like randomly getting wrong refresh rate, but I believe it's that know problem with Inter graphic cards on OS X.

**Comment by gdrewb-valve** [comment]
NekR, your last comment sounds like, other than the refresh rate you mention is a known system bug, things were mostly working?  Is this issue still active?

**Comment by NekR** [comment]
@gdrewb-valve I wasn't playing in Dota for a while now. Not sure if issue persists. I probably worth checking by someone with macOS Sierra + Dota 2 7.00. If this matters, you may close this and if something I'll report it again.

**Comment by gdrewb-valve** [comment]
OK, I'll close this for now.

**Comment by auraz** [comment]
Same issues, 60 fps internal display, 20 fps external.
