### ISSUE TITLE
[MAC] When spectating game and accepting queue request, the new reborn accept message still displays if going to main menu.

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#664]
If you currently spectate a game and click on accept game, the new dota reborn accept/decline still shows in the main menu.

Also, I remember a few times when even accepting the game through the accept/decline while spectating the game, if you didn't go to the main menu and accept the game there, you would fail to match make. 

If spectating a game the accept/decline should only appear there, not in two places. 

Same exact issue as in Linux #505

**Comment by gdrewb-valve** [comment]
Closing duplicate.  None of this is platform-specific and won't be tracked here.
