### ISSUE TITLE
Weird graphical bugs/glitches

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#665]
Firstly I have a black screen instead of the dota 2 loading screen when starting and I the "Genuine DAC 2015 Chaos Knight" cursor looks weird(have some screenshots but the cursor is not shown on the saved screenshots).

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon (TM) R9 380 Series 

```
Driver Version:  4.5.13416 Compatibility Profile Context 15.30.1025
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6939
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                        53,1cm x 29,9cm  (60,9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7965 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  938767 Mb
    Largest Free Hard Disk Block:  802803 Mb

Installed software:

Recent Failure Reports:

**Comment by danginsburg** [comment]
I have fixed the black loading screen bug.  It will be in a future Dota 2 update.

**Comment by danginsburg** [comment]
Fixed in December 3rd update.

**Comment by ghost** [comment]
Now the loading screen is grey - I even verified the game files
