### ISSUE TITLE
[Mac] error statistics challenge of all heroes

### ISSUE THREAD

**Issue by seethersan** [ValveSoftware/Dota-2#666]
The challenge of all heroes get stuck on a hero despite already having won a game with the hero currently assigned.

The game 1969536476 was considered abandonment even though I do not disconnect at any time or was away from the keyboard.

![desafio](https://cloud.githubusercontent.com/assets/6700347/11522687/157aca66-9888-11e5-8efa-3ca4ba083da8.jpg)
![partida 1](https://cloud.githubusercontent.com/assets/6700347/11522688/15c0edd4-9888-11e5-9e54-4b118e92546b.jpg)
![partida techies ganada](https://cloud.githubusercontent.com/assets/6700347/11522689/15c4ba5e-9888-11e5-910a-98a0156462d5.jpg)

**Comment by gdrewb-valve** [comment]
These aren't Mac-specific issues so you'll want to report them in the regular forums (dev.dota2.com).
