### ISSUE TITLE
How can i change a custom  screen resolution?

### ISSUE THREAD

**Issue by Amet13** [ValveSoftware/Dota-2#668]
``` bash
amet13@mint-17 ~ $ xrandr
Screen 0: minimum 8 x 8, current 2806 x 900, maximum 32767 x 32767
LVDS1 connected primary 1366x768+1440+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1366x768       60.0*+
   1360x768       59.8     60.0  
   1280x720       60.0  
   1024x768       60.0  
   1024x576       60.0  
   960x540        60.0  
   800x600        60.3     56.2  
   864x486        60.0  
   640x480        59.9  
   720x405        60.0  
   680x384        60.0  
   640x360        60.0  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
VGA1 connected 1440x900+0+0 (normal left inverted right x axis y axis) 408mm x 255mm
   1440x900       59.9*+   75.0  
   1280x1024      75.0     60.0  
   1280x960       60.0  
   1280x800       74.9     59.8  
   1152x864       75.0  
   1024x768       75.1     70.1     60.0  
   832x624        74.6  
   800x600        72.2     75.0     60.3     56.2  
   640x480        75.0     72.8     66.7     60.0  
   720x400        70.1  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

I have no resolution 1440x900 in list.
![screenshot-dota 2](https://cloud.githubusercontent.com/assets/5184847/11584744/85a0a55e-9a77-11e5-8802-15f19c04b247.png)

Driver:

``` bash
amet13@mint-17 ~ $ glxinfo | grep OpenGL | head -3
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.0-devel (git-2e7e3fe 2015-09-12 trusty-oibaf-ppa)
```

**Comment by budimanjojo** [comment]
You need to choose 16:10 for the aspect ratio instead of 16:9 because 1440x900 is 16:10

**Comment by Amet13** [comment]
![screenshot-dota 2](https://cloud.githubusercontent.com/assets/5184847/11590838/32ceec6e-9aa4-11e5-90f4-9c4e1645b5da.png)

**Comment by Amet13** [comment]
I'm using additional monitor for my laptop.
Linux Mint 17.3 x64
![screenshot-monitor preferences](https://cloud.githubusercontent.com/assets/5184847/11591280/95588a90-9aa7-11e5-924f-d134e95c0cb3.png)

**Comment by Tele42** [comment]
@Amet13 did you try the -h and -w launch option settings? http://dota2.gamepedia.com/Launch_Options

I don't know if they have been checked since the source 1 -> source 2 transition.

**Comment by budimanjojo** [comment]
I think it's because you're using windowed mode. Maybe you should try changing it to fullscreen mode, because windowed mode can not go full monitor resolution as the panel and window decoration are taking space. You may also add sdl_display_index 0 in the launch option if Dota 2 launches in your laptop monitor instead of your external monitor

**Comment by Amet13** [comment]
```
-language russian -w 1140 -h 900
```

![screenshot-dota 2-1](https://cloud.githubusercontent.com/assets/5184847/11597898/bd03eb20-9acf-11e5-948d-188dfb1711d0.png)
I have no problems on source 1

**Comment by danginsburg** [comment]
Try -sdl_displayindex 1.  I suspect what is happening here is that 1440x900 isn't shown because your primary monitor only goes to 1336x768.  I think if you use -sdl_displayindex 1 it will query the supported resolutions from your other monitor and it should show up.

**Comment by Amet13** [comment]
@danginsburg i'm trying launch with this options:

```
-language russian -w 1140 -h 900 -sdl_displayindex 1
```

First launch i look like 1152x864, but if i change 16:10 tab, i see my resolution.
![screenshot-dota 2](https://cloud.githubusercontent.com/assets/5184847/11599395/bface504-9ad7-11e5-81be-f506f645ff70.png)
So i solved my problem, but can i launch dota already with 16:10 resolution?

**Comment by Amet13** [comment]
Sorry, 1440x900, all ok.
It works:

```
-w 1440 -h 900 -sdl_displayindex 1
```
