### ISSUE TITLE
[Linux] massive memory leak

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#669]
hi,
I found that if I have dota2 running in the main menu for several hours it starts to consume all available memory. Frequently it ends up using more than 6GB, while effectively doing nothing. At that point the only way for me to close dota2 is with kill -9.
I have no idea what is causing this, maybe it is related to #360 ?

Old similar issues: #583 (presumably fixed)

**Comment by gdrewb-valve** [comment]
I found one fairly significant leak so this will improve with a future update.

**Comment by Turmfalke2** [comment]
@gdrewb-valve nice to hear. I will make sure to test for this again as soon as the update is deployed.

**Comment by gdrewb-valve** [comment]
This should be fixed in the latest update.

**Comment by Turmfalke2** [comment]
I can confirm that it is fixed.
