### ISSUE TITLE
[Linux] Dota 2 crash every match (from latest two or three patch)

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#670]
Hi.

I have issues with Dota 2 on my PC with Linux.

This issue persist from latest two or three latest patch (before all work fine!).
Now Dota2 crash (quit to desktop) every match (about half time match something like in 20 min/30min/40min).

Quick info:
AMD Radeon HD5850 with Catalyst 15.9
AMD Phenom II X6
4 GB RAM

I paste my Steam System info here:

https://gist.github.com/xpris/a7a512c225645496f280

**Comment by Tele42** [comment]
If you can find a CrashID that corresponds to the crashes, that would help, otherwise upload one or more dump files somewhere and link them here.

**Comment by AngryPenguinPL** [comment]
Noob question but where I can find crash log or crash id for dota2 in Linux? :P

**Comment by Tele42** [comment]
CrashIDs can be found in console spew by closing steam, then opening steam from a terminal (and making the crash occur), or the bottom of the System Information. Dump files can be found in /tmp/dumps.

**Comment by AngryPenguinPL** [comment]
Ok, I have it. Today two crash in one match :/

I uploaded this two crash file and also file x_log.txt and x_stdout.txt.

http://speedy.sh/uaKHF/crash-20151206165306-1.dmp
http://speedy.sh/QTVUp/crash-20151206173739-1.dmp
http://speedy.sh/ysdgZ/x-log.txt
http://speedy.sh/BJEj5/x-stdout.txt

This is all or I need give some other?

**Comment by gdrewb-valve** [comment]
The dump files are fine and gave us the information for your crashes.  Unfortunately the two crashes are different so there may be more than one problem.  Also the dumps don't immediately point out why the crashes are occurring so we'll have to try and repro.  Finally, we have crash reports of the same kind of crashes on Windows too so these will be handled by the larger team.

Valve notes:
One crash is in scaleform UpdateBundleEntry.  This happens on all platforms.
One crash is in animationsystem BlendLerpedSimulationToRenderState.  This happens on all platforms.

**Comment by AngryPenguinPL** [comment]
Today again I have crash.

Maybe this can help:

http://speedy.sh/r2bqx/crash-20151208141031-1.dmp
http://speedy.sh/3eGFz/crash-20151208152055-1.dmp
http://speedy.sh/DXRpu/x-log.txt
http://speedy.sh/vcSZQ/x-stdout.txt

**Comment by gdrewb-valve** [comment]
Thanks.  The first one is another Scaleform crash and SpeedyShare wouldn't let me download the second but I assume it's similar.  That's enough info for now.

**Comment by Tele42** [comment]
Second dump is a SIGSEGV in libscenesystem.so.

**Comment by pfwb** [comment]
Hi. Maybe this also helps. 
''CrashID=bp-a1b153ef-c048-4e76-b172-bbddf2151208''

**Comment by gdrewb-valve** [comment]
Thank you but we have enough info in this issue right now.  We don't want this issue to become filled with everybody's crash reports as there are many different reasons for crashes.  Also, if you don't see "Discarded=1" in the crash report status it was sent to Valve and we already have it.

**Comment by gdrewb-valve** [comment]
@xpris, are you still getting regular crashes?

**Comment by AngryPenguinPL** [comment]
For few last games I not see any crash. Thanks.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
