### ISSUE TITLE
[Linux] Steam and Dota2 can't input Chinese, and Chinese ID can not be displayed in Dota2

### ISSUE THREAD

**Issue by sunlinyao** [ValveSoftware/Dota-2#671]
Steam和Dota2聊天不能输入中文，我用的是fcitx输入法。而且在游戏中，中文名字不能显示出来，其它地方中文显示没问题。我相信很多人和我遇到的问题一样。我尝试重新编译libSDL2-2.0.so.0，但是没效果。
最主要的还是聊天不能输入中文。

sly@fskj-u-sly:~$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l
sly@fskj-u-sly:~$ uname -a
Linux fskj-u-sly 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I hope you can fix it as soon as possible. thx

**Comment by gdrewb-valve** [comment]
Duplicate of #50.
