### ISSUE TITLE
Linux: Unplayable low FPS, very lagged menu

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#673]
Hello. I have been playing Dota 2 on Linux for a while with no problems, but I had to switch to Windows for some time (a week) and now that I'm back the game is unplayable.

In the main menu I get 5~10 FPS, CPU usage goes to 60~70% which is 'okay', I guess. I have tried watching live games (though it took more than one minute to move the mouse around the screen) and the FPS is the same but the game crashes.

My computer specs:
- i5-4460
- GTX 970
- B85-D3PH

Info as requested:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  VMware, Inc. Gallium 0.4 on llvmpipe (LLVM 3.7, 256 bits)

```
Driver Version:  3.0 Mesa 11.0.6
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 50 Hz
VendorID:  0x10de
DeviceID:  0x13c2
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 27.48" x 15.43"  (31.50" diag)
                                        69.8cm x 39.2cm  (80.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: 

Memory:
    RAM:  7837 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  930805 Mb
    Largest Free Hard Disk Block:  784957 Mb

Installed software:

Recent Failure Reports:

My system is Antergos (Arch-based) 

I am using this command to run steam
~: LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1' steam

as running just "steam" on a terminal gives me this:
Installing breakpad exception handler for appid(steam)/version(1447125378)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

I have been searching for a while but can't seem to find any other people with the same problem.

Thanks for reading and taking the time to help.
Any help is appreciated.

**Comment by davidw-valve** [comment]
It sounds like you are using Gallium drivers and are on a virtual machine. We recommend running Dota2 natively, with the NVidia drivers.

**Comment by ghost** [comment]
I am not using a VM, though. I am running both Dota 2 and Steam natively.

**Comment by davidw-valve** [comment]
You are using Gallium drivers though: "Driver: VMware, Inc. Gallium 0.4 on llvmpipe (LLVM 3.7, 256 bits)" -- we recommend using the NVidia proprietary drivers. You will not get very good performance using Gallium drivers.

**Comment by ghost** [comment]
Well, I fixed it. It's been a while now, I was testing till now.

If someone ever comes across the same problem:
- Make sure NVIDIA/ATI drivers are installed and Nouveau blacklisted;
- Install lib32-nvidia-utils and lib32-nvidia-libgl

These simple steps apparently fixed my problem, they might just fix yours.
