### ISSUE TITLE
[Linux] Default Device does not output to correct pcm

### ISSUE THREAD

**Issue by Enzime** [ValveSoftware/Dota-2#674]
Distro: Arch Linux
Window Manager: i3

When I run Dota 2 I get this output, it is also output for when changing between the two sound devices in the Reborn menu: Default Device and System audio output device

```
ALSA lib timer_hw.c:342:(_snd_timer_hw_open) Unexpected field hint
ALSA lib timer_hw.c:342:(_snd_timer_hw_open) Unexpected field hint
ALSA lib pcm_direct.c:1118:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=1,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1095:(snd_pcm_dmix_open) unable to initialize poll_fd
```

When I do the `Help -> System Information` in Steam it only shows the first card

```
Sound card:
    Audio device: Loopback Mixer
```

when there are actually 3 cards (shown by `cat /proc/asound/cards`)

```
 0 [Loopback       ]: Loopback - Loopback
                      Loopback 1
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xfbd20000 irq 46
 2 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xfbc40000 irq 47
```

It appears that Dota is attempting to output to the correct sound card, but I believe it is attempting to initialize it incorrectly. I have defined on my system an `.asoundrc` file which specifies the default pcm (the one Dota should output to) but instead I believe it is trying to open the soundcard exclusively which does not work with the rest of my programs. I believe for Default Device in the Dota 2 menu it should attempt to output to the default PCM when running ALSA, and I believe there should be a way to specify a specific PCM to output to.

**Comment by gdrewb-valve** [comment]
Reborn uses SDL for sound handling and doesn't do anything on its own directly with ALSA.  Reborn shows the outputs that SDL enumerates, so if SDL does not include the specific output you are interested in there is no way for Reborn to offer it.

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by Enzime** [comment]
It appears to be fixed :) Nice to see a lot more ALSA outputs enumerated, I don't know if this is possible with SDL, but hopefully one day I would love to see Dota including an option for specifying the PCM to output to with ALSA :)

**Comment by gdrewb-valve** [comment]
You can file a request in the SDL forums and we'll see.
