### ISSUE TITLE
Dota 2 Reborn not installing

### ISSUE THREAD

**Issue by derfs** [ValveSoftware/Dota-2#677]
So i stopped playing dota 2 awhile back. I never actually fully downloaded the reborn beta way back when it was released. Now it says that it is installed on my game, however it clearly isn't. When i go to launch dota 2 it says 'syncing' then stops and nothing happens. Ive looked through multiple threads, uninstalled the game and installed it many times. I cannot get into the actual game, so i cannot actually install the beta. I don't know what else i can do to try and make this thing work?

**Comment by gdrewb-valve** [comment]
When you launch is the syncing dialog from Steam (it sounds like it)?  What is your system info?

**Comment by derfs** [comment]
A message comes up beside dota 2 that says 'syncing' for about half a second then nothing happens. It says the reborn was 'installed' and acquired on 69-12-31. Clearly this is a bug since there's no such date.

Currently using a MacBook Air, which used to run dota just fine until downloading the reborn beta glitched and won't install now.

I've gone to lots of forums trying lots of different things trying to get it to work but for some reason it just won't.

**Comment by gdrewb-valve** [comment]
I'll pass this on to the Steam team.

**Comment by gdrewb-valve** [comment]
Closing as this isn't being handled by the Reborn team.
