### ISSUE TITLE
2d ui corruption

### ISSUE THREAD

**Issue by strattonbrazil** [ValveSoftware/Dota-2#678]
Since the Dota 2 reborn, I've seen the 2D part of the UI like the map and the health bars over the characters get corrupted (see attached).  This happens occasionally for the killed-by image, but I don't know if that's related.  It happened frequently after reborn was released, but has been happening less and less over the last few months.  When encountered, I usually just restart the application without leaving the game.  At this point is usually happens only every few games, but seems easier to reproduce if I browse through the heroes before starting the game.  Also, once in this state it seems to quickly get worse and worse until all the 2D portions of the game are in this state.  

![corrupted_map](https://cloud.githubusercontent.com/assets/786471/11717971/73b27008-9f08-11e5-8967-7a098f93b3fe.jpg)
![corrupted_kill](https://cloud.githubusercontent.com/assets/786471/11717972/73b5435a-9f08-11e5-94d8-13cbbe023ea2.jpg)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3401 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-68-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series 

```
Driver Version:  4.4.13374 Compatibility Profile Context 13.35.1005
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                        59.8cm x 33.6cm  (68.5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7872 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  216782 Mb
    Largest Free Hard Disk Block:  56101 Mb

Installed software:

Recent Failure Reports:
    Thu Dec 10 05:29:53 2015 GMT: file ''/tmp/dumps/crash_20151209205919_1.dmp'', upload yes: ''Discarded=1''
    Thu Dec 10 07:08:33 2015 GMT: file ''/tmp/dumps/crash_20151209230833_6.dmp'', upload yes: ''Discarded=1''
    Thu Dec 10 07:08:34 2015 GMT: file ''/tmp/dumps/assert_20151209230833_2.dmp'', upload yes: ''Discarded=1''
    Thu Dec 10 07:08:34 2015 GMT: file ''/tmp/dumps/crash_20151209230834_102.dmp'', upload yes: ''CrashID=bp-5324072a-be80-4b54-81d9-339302151209''
    Thu Dec 10 07:08:35 2015 GMT: file ''/tmp/dumps/assert_20151206200835_1.dmp'', upload yes: ''CrashID=bp-ffd572f7-f5ca-4b15-bd06-f295d2151209''

**Comment by danginsburg** [comment]
You are running an old AMD Catalyst driver (v14.3).  I would recommend a minimum of Catalyst v15.7 (this is listed in the System Requirements on the Steam page for Dota 2).  If you are upgrading you might as well get the latest AMD Crimson driver Catalyst v15.9: http://support.amd.com/en-us/download
