### ISSUE TITLE
Regression with Linux kernel 4.4rc4 and amdgpu

### ISSUE THREAD

**Issue by HarlemSquirrel** [ValveSoftware/Dota-2#679]
I am using Arch Linux and things go really well with the open source amdgpu driver on linux 4.3 but I built 4.4rc4 today and the Dota 2 UI is REALLY slow to the point of not usable. Left 4 Dead 2 works fine. 

Here is the console output when running steam from CLI...

<pre>
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[1210/174656:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
[1210/174656:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151109182310)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447093390)
[1210/174656:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
[1210/174656:ERROR:nss_util.cc(1007)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151109182310)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447125378)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Wireless receiver firmware /home/hs/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1442256398.
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
FillInMachineIDInfo took a total of 0 milliseconds

** (steam:2363): WARNING **: Unknown device type 14

** (steam:2363): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Installing breakpad exception handler for appid(steam)/version(1447125378)

** (steam:2363): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:2363): WARNING **: Ignoring invalid property 'secondaries'

** (steam:2363): WARNING **: Ignoring invalid property 'route-data'

** (steam:2363): WARNING **: Ignoring invalid property 'address-data'

** (steam:2363): WARNING **: Ignoring invalid property 'route-data'

** (steam:2363): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
local (potentially out of sync) copy of roaming config loaded - 3292 bytes.
roaming config store loaded successfully - 3292 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1447125378)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/hs/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1447125378)
System startup time: 4.13 seconds
[1210/174700:ERROR:renderer_main.cc(200)] Running without renderer sandbox
/home/hs/.steam/root/steam.sh: line 161: VERSION_ID: unbound variable
Generating new string page texture 73: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 76: 64x256, total string texture memory is 1.56 MB
Generating new string page texture 77: 8x256, total string texture memory is 1.56 MB
Generating new string page texture 78: 32x256, total string texture memory is 1.60 MB
/home/hs/.steam/root/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
STEAM_RUNTIME has been set by the user to: /home/hs/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/hs/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 85: 128x256, total string texture memory is 1.73 MB
Generating new string page texture 87: 256x256, total string texture memory is 1.99 MB
Generating new string page texture 91: 128x256, total string texture memory is 2.12 MB
Game update: AppID 570 "Dota 2", ProcID 2491, IP 0.0.0.0:0
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 2493 != 2492, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197979947142 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197979947142
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20151109182348)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
warning: The VAD has been replaced by a hack pending a complete rewrite
Installing breakpad exception handler for appid(steam)/version(1447125378)
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD FIJI (DRM 3.1.0, LLVM 3.7.0)
DumpContextInfo: Using OpenGL context version 4.1
DumpContextInfo: Context supports GLSL version 4.10
Game removed: AppID 570 "Dota 2", ProcID 2495 
Generating new string page texture 414: 24x256, total string texture memory is 2.15 MB
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
[2015-12-10 17:46:55] Startup - updater built Nov  9 2015 18:23:22
[2015-12-10 17:46:55] Verifying installation...
[2015-12-10 17:46:55] Verification complete
[2015-12-10 17:48:38] Shutdown
</pre>

**Comment by gdrewb-valve** [comment]
Do you believe this is a Reborn issue for some reason?  You're using the same Reborn binaries that were working fine and the only thing that changed is the kernel?

**Comment by HarlemSquirrel** [comment]
Well I think it is because it works fine with Dota 2 and my GNOME desktop. There are no errors in my dmesg. 

Running well with the 4.3 kernel I get this...

<pre>
$ steam
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
/home/hs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[1210/201430:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
[1210/201430:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151210113755)
Installing breakpad exception handler for appid(steamwebhelper)/version(1449747475)
[1210/201430:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20151210113755)
Installing breakpad exception handler for appid(steamwebhelper)/version(1449778863)
Installing breakpad exception handler for appid(steamwebhelper)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
Created shared memory when not owner SteamController_Shared_mem
Wireless receiver firmware /home/hs/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1442256398.
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
** (steam:2287): WARNING **: Unknown device type 14
** (steam:2287): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Installing breakpad exception handler for appid(steam)/version(1449778863)
** (steam:2287): WARNING **: Ignoring invalid property 'autoconnect-priority'
** (steam:2287): WARNING **: Ignoring invalid property 'secondaries'
** (steam:2287): WARNING **: Ignoring invalid property 'route-data'
** (steam:2287): WARNING **: Ignoring invalid property 'address-data'
** (steam:2287): WARNING **: Ignoring invalid property 'route-data'
** (steam:2287): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1449778863)
Installing breakpad exception handler for appid(steam)/version(1449778863)
local (potentially out of sync) copy of roaming config loaded - 3292 bytes.
roaming config store loaded successfully - 3292 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1449778863)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/hs/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1449778863)
System startup time: 4.11 seconds
/home/hs/.steam/root/steam.sh: line 161: VERSION_ID: unbound variable
Generating new string page texture 73: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 76: 64x256, total string texture memory is 1.56 MB
Generating new string page texture 77: 8x256, total string texture memory is 1.56 MB
Generating new string page texture 78: 32x256, total string texture memory is 1.60 MB
/home/hs/.steam/root/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
STEAM_RUNTIME has been set by the user to: /home/hs/.local/share/Steam/ubuntu12_32/steam-runtime
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 88: 128x256, total string texture memory is 1.73 MB
Generating new string page texture 90: 256x256, total string texture memory is 1.99 MB
ExecCommandLine: "/home/hs/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 95: 128x256, total string texture memory is 2.12 MB
Generating new string page texture 122: 384x256, total string texture memory is 2.51 MB
Game update: AppID 570 "Dota 2", ProcID 2414, IP 0.0.0.0:0
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 2416 != 2415, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197979947142 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197979947142
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20151210113820)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/hs/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
warning: The VAD has been replaced by a hack pending a complete rewrite
Installing breakpad exception handler for appid(steam)/version(1449778863)
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor X.Org
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD FIJI (DRM 3.1.0, LLVM 3.7.0)
DumpContextInfo: Using OpenGL context version 4.1
DumpContextInfo: Context supports GLSL version 4.10
Game removed: AppID 570 "Dota 2", ProcID 2418 
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
(steam:2287): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 523: 24x256, total string texture memory is 2.54 MB
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
[2015-12-10 20:14:29] Startup - updater built Dec 10 2015 11:38:07
[2015-12-10 20:14:29] Verifying installation...
[2015-12-10 20:14:29] Verification complete
[2015-12-10 20:15:02] Shutdown
</pre>

**Comment by gdrewb-valve** [comment]
When things go from working to not working is there a Reborn change or is only the kernel changing?

**Comment by HarlemSquirrel** [comment]
Only the kernel changes. 

I noticed that with kernel 4.4rc4 I get `[1210/174656:ERROR:nss_util.cc(1007)] Failed to load NSS libraries.` but I don't get this with kernel 4.3

**Comment by gdrewb-valve** [comment]
It's possible that Reborn is doing something incorrectly and somehow 4.3 wasn't affected by it, but somebody with Linux kernel knowledge will need to figure out what it is.

The nss message is coming from CEF/WebKit and isn't likely to be too important.

**Comment by HarlemSquirrel** [comment]
OK. I know that amdgpu is really new and still in the works. I just wanted to give a heads up in case there was anything you guys could do. Thanks for the quick reply!

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Reborn issue.
