### ISSUE TITLE
[Linux] Have dota2 sound in desktop although I have `play sound in desktop` unchecked

### ISSUE THREAD

**Issue by hrzhu** [ValveSoftware/Dota-2#68]
System info:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  3003 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-41-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11600000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.21
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1284
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 13.27" x 10.63"  (16.97" diag)
                                        33.7cm x 27.0cm  (43.1cm diag)
Primary Bus: PCI Express 8x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  3952 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  288380 Mb
    Largest Free Hard Disk Block:  238422 Mb

Installed software:

Recent Failure Reports:

**Comment by mkocs** [comment]
I'm experiencing the same problem.

**Comment by davidw-valve** [comment]
This will be fixed in the next update.

**Comment by gdrewb-valve** [comment]
Fixed in the 6/26 update.
