### ISSUE TITLE
game freeze

### ISSUE THREAD

**Issue by mrzonin** [ValveSoftware/Dota-2#681]
after selecting a hero game freeze right when another player picks a character. Have to do hard restart. graphics all teared and pixelated but can still hear the sound.
same crash happens rarely at random in-game also. 
having this problem since reborn. 

I have tried everything to fix it: drivers, reinstall, verify, change settings and so on.

Processor Information:
Model: MacBookPro5,3
Vendor: GenuineIntel
CPU Family: 0x6
CPU Model: 0x17
CPU Stepping: 0xa
CPU Type: 0x0
Speed: 2660 Mhz
2 logical processors
2 physical processors
HyperThreading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Unsupported

Network Information:
Network Speed: 

Operating System Version:
MacOS 10.11.2 (64 bit)

Video Card:
Driver: NVIDIA GeForce 9600M GT

Driver Version: 1.2
Driver Date: 0 0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID: 0x10de
DeviceID: 0x647
Number of Monitors: 1
Number of Logical Video Cards: 2
Primary Display Resolution: 1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 12.95" x 8.15" (15.28" diag)
32.9cm x 20.7cm (38.8cm diag)
Primary VRAM: 256 MB

Memory:
RAM: 4096 Mb

Miscellaneous:
UI Language: English
Microphone: Not set
Media Type: DVD
Total Hard Disk Space Available: 304425 Mb
Largest Free Hard Disk Block: 263774 Mb

Installed software:
Agent
App Store
Automator
Battle.net
Battle.net-Setup-enGB
Beskeder
Billedoverførsel
Blizzard Error
Dota 2
FaceTime
Fotos
Game Center
Gmail
Google Chrome
Google Drev
Google-søgning
Hearthstone
Hearthstone Beta Launcher
Huskesedler
iBooks
Kalender
Kontakter
Kort
Launchpad
Memory Clean
MiniTerm
Mission Control
Noter
Påmindelser
PokerStarsDK
Razer Synapse
Steam
YouTube

**Comment by gdrewb-valve** [comment]
The first suspect would be the graphics driver.  You mention you've tried different drivers, can you give more specifics on that?

**Comment by danginsburg** [comment]
Also, can you try -gl_force_sm30 on the command-line to see if it helps?  If not, can you run with -con_logfile and post the contents of game/dota/console.log.

**Comment by Mattele** [comment]
This sounds very similar to the freezes I experience in #667 

OP, try to restart your Mac just before playing, tell me if that fix this issue, it works for me

**Comment by mrzonin** [comment]
i tried the nvidia web driver - no luck.
restarting before playing doesn't help.
will test gl_force_sm30 and return

**Comment by mrzonin** [comment]
-gl_force_sm30 didn't help.

Here is the log after reproducing the crash:

CreateDevice: Requested DX level 110, clamped to DX level 100
Unable to open GL shader cache TOC /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/shadercache/gl/shaders.toc file - might not exist yet.
GPU reports 237MB available memory which is too low, using 300 MB
PERF WARNING: Texture pool size set to more than 80% of total GPU memory.PERF WARNING: Texture pool size set to more than 80% of total GPU memory.ERROR: HangWatchdogInternal_BeginScope() - Hang watchdog not implemented for this platform!

## ERROR: HangWatchdogInternal_EndScope() - Hang watchdog not implemented for this platform!

Path ID:             File Path:
ADDONS               "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota_addons/" 
CONTENT              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/content/dota/" 
CONTENT              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/content/core/" 
CONTENTADDONS        "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/content/dota_addons/" 
CONTENTROOT          "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/content/" 
DEFAULT_WRITE_PATH   "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk
DEFAULT_WRITE_PATH   "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/" 
EXECUTABLE_PATH      "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/" 
GAME                 "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk
GAME                 "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/pak01.vpk" (vpk) /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/pak01.vpk
GAME                 "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/" 
GAME                 "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/" 
GAMEBIN              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/bin/osx64/" 
GAMEBIN              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/bin/" 
GAMEBIN              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/bin/osx64/" 
GAMEBIN              "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/bin/" 
GAMEROOT             "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/" 
MOD                  "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/pak01.vpk
MOD                  "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/" 
PLATFORM             "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/pak01.vpk" (vpk) /Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/pak01.vpk
PLATFORM             "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/" 
SHADER_SOURCE        "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/dota/" 
SHADER_SOURCE        "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/core/" 
SHADER_SOURCE        "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/dota_addons/" 
SHADER_SOURCE        "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/dota_core/" 
SHADER_SOURCE_MOD    "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/dota/" 
SHADER_SOURCE_ROOT   "/Users/martinnaundrup/Library/Application Support/Steam/steamapps/common/dota 2 beta/src/shaders/" 
command line arguments:
-novid -con_logfile
Physics Console Communications is not initialized
Game supporting (2) split screen players
Sound Initialization: Finish, Sampling Rate: 44100
AssociateNetMessageWithChannelCategoryAbstract: Trying to use an unregistered netchannel category!
AssociateNetMessageWithChannelCategoryAbstract: Trying to use an unregistered netchannel category!
Couldn't find custom font file 'vgui/resource/marlett.ttf'
Load a scaleform font provider?
CEntitySystem::BuildEntityNetworking (parallel build of server) took 418.604 msecs for 615 out of 633 classes
SV:  parsing 'scripts/items/items_game.txt' took 1940.718 msec
Requesting page 1 of items
Requesting page 1 of items
ReadSteamRemoteStorageFile( bufOut, "cfg/dotakeys_personal.lst" ) -> 0.015220 seconds
CEntitySystem::BuildEntityNetworking (parallel build of client) took 411.340 msecs for 621 out of 641 classes
CL:  parsing 'scripts/items/items_game.txt' took 1494.883 msec
ReadSteamRemoteStorageFile( bufOut, "cfg/dota_player_loadout_shuffle.txt" ) -> 0.011100 seconds
Telling Steam it is safe to udpate the app
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_strong.vmat!
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_med.vmat!
No valid vcs file found for shader gaussian_bloom_blur.vfx

/Users/buildbot/buildslave/source2_dota_rel_osx64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/Users/buildbot/buildslave/source2_dota_rel_osx64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/Users/buildbot/buildslave/source2_dota_rel_osx64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

/Users/buildbot/buildslave/source2_dota_rel_osx64/build/src/materialsystem2/material2.cpp(849): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!
File error loading resource header "panorama/images/textures/startup_background_logo.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/soundevents_dota_customgames.vsndevts_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_music.vsndevts_c" (Error: ERROR_FILEOPEN)
File error loading resource header "soundevents/music/deadmau5_01/soundevents_stingers.vsndevts_c" (Error: ERROR_FILEOPEN)
config file 'cfg/game_convars.vcfg' is overriding an archived convar 'snd_ducktovolume' with value '1'. User will not be able to change this value!
SwitchToLoop levelload requested:  id [1] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
Idle (levelload)
ReadSteamRemoteStorageFile( bufOut, "cfg/chat.cfg" ) -> 0.011866 seconds
Allocating new transform texture!
Writing configuration for slot 0
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [1] addons []
name[ 0 ] changing from 'unnamed' to 'MrZonin'
name[ 0 ] changing from 'MrZonin' to 'MrZonin'
Loaded default network config file.  Loaded revision 25 OK
Loaded cached network config file.  Loaded revision 30 OK
SV:  maxplayers set to 1
Network configuration revision changed 0 -> 30
Initializing script VM...
...done
CL:  Adding Prequisite CWaitForGameServerStartupPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
Failed to load inventory scratchpad information file "cfg/dota_player_scratchpad.txt"!
Got network config from CDN.  Data contains revision 30, not newer than current revision 30; ignoring.
ReadSteamRemoteStorageFile( bufOut, "scripts/clientstorage.txt" ) -> 0.029767 seconds
SV:  Spawn Server: <empty>
***\* Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
***\* Panel MapPreview has fill-parent-flow for width, but isn't in a flowing right layout
Ping measurement complete.
Slow image load - http://cdn.dota2.com/apps/dota2/images/blogfiles/shanghai_major.jpg (dimensions 810x550, took 40 msec)
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  PS_SATISFIED CWaitForGameServerStartupPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  Sending connect to loopback
SV:  Sending S2C_CHALLENGE [3087109481 auth 2] to loopback
CL:  Received S2C_CHALLENGE [3087109481 auth 2] from loopback
CL:  Sending C2S_CONNECT [43 protocol 3087109481 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 43 3087109481 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'MrZonin' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 6958
Server Number: 1
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.011512 seconds
CL:  PS_SATISFIED CLoadStartupResourcePrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CLoadSpawnGroupsPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CFinalizeConnectionPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  OnStatusFinished for CGameClientConnectPrerequisite
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.005778 seconds
Failed to load grid nav data, file 'maps/<empty>.gnv' not found!
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
SV:  Sending full update to client MrZonin (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 33.449 KB [10 pkts], outgoing 1.299 KB [9 pkts]
Ping measurement complete.
Allocating new transform texture!
Writing configuration for slot 0
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
SwitchToLoop levelload requested:  id [2] addons []
CL:  IGameSystem::LoopDeactivateAllSystems
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 41.948
CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/dashboard_parallax_test) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/play_searching) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
SV:  IGameSystem::LoopDeactivateAllSystems
HO:  IGameSystem::LoopDeactivateAllSystems
SV:  Disconnect client 'MrZonin' from server(1): NETWORK_DISCONNECT_SHUTDOWN
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 42.092
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 42.250
CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 42.251
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [2] addons []
Network socket 'server' opened on port 27015
SV:  maxplayers set to 64
Initializing script VM...
...done
SV:  Executing listen server config file
S:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
SV:  CGameRulesGameSystem::GameInit installed game rules
CL:  Adding Prequisite CWaitForGameServerStartupPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
exec: couldn't exec listenserver.cfg
UnserializeDMX: Unable to open file "0"
UnserializeDMX: Unable to open file "0"
ERROR: CParticleSnapshot::Unserialize - could not load file 0!
File error loading resource header "particles/econ/events/fall_major_2015/compendium_points_fall_ambient_2015_magic.vpcf_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/models/props_gameplay/dota_ar_frame/dota_ar_frame.vmat_c" (Error: ERROR_FILEOPEN)
SV:  Spawn Server: dota
SV:  Connection to Steam servers successful.
SV:  VAC secure mode is activated.
GC Connection established for server version 1192
File error loading resource header "materials/effects/fog_world_00.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/effects/fow_clouds_00.vtex_c" (Error: ERROR_FILEOPEN)
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  PS_SATISFIED CWaitForGameServerStartupPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  Sending connect to loopback
SV:  Sending S2C_CHALLENGE [2184825552 auth 3] to loopback
CL:  Received S2C_CHALLENGE [2184825552 auth 3] from loopback
CL:  Sending C2S_CONNECT [43 protocol 2184825552 auth 3] to loopback
SV:  Receiving C2S_CONNECT [protocol 43 2184825552 auth 3] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'MrZonin' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
Game: "Dota 2"
Map: "dota"
Players: 1 (0 bots) / 64 humans
Build: 6958
Server Number: 2
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
CL:  CGameRulesGameSystem::GameInit installed game rules
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.010824 seconds
SV:  "MrZonin<1><[U:1:118513177]><>" STEAM USERID validated
CL:  PS_SATISFIED CLoadStartupResourcePrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CLoadSpawnGroupsPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CFinalizeConnectionPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  OnStatusFinished for CGameClientConnectPrerequisite
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
Grid nav allocation size: 3244800
SV:  64 player server started
CL:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.024406 seconds
Changelevel (dota)
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
S:Gamerules: entering state 'DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP'
S:Gamerules: entering state 'DOTA_GAMERULES_STATE_HERO_SELECTION'
SV:  Sending full update to client MrZonin (reason:  initial update)
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 96.558 KB [124 pkts], outgoing 6.577 KB [125 pkts]
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_HERO_SELECTION'
CDOTA_SF_HTML disabled in Source 2
CDOTA_PlayerResource: Adding player SteamID 76561198078778905 to slot 0 FakeClient=0 preferred slot = -1
PR:OnFullyJoinedServer 0:[U:1:118513177]
PR:SetLeaverStatus 0:[U:1:118513177] DOTA_LEAVER_NONE
PR:SetConnectionState 0:[U:1:118513177] DOTA_CONNECTION_STATE_CONNECTED NETWORK_DISCONNECT_INVALID
Requesting account 118513177 resources without rank.
CDOTA_PlayerResource: Adding player SteamID 90071996842377216 to slot 1 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377217 to slot 2 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377218 to slot 3 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377219 to slot 4 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377220 to slot 5 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377221 to slot 6 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377222 to slot 7 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377223 to slot 8 FakeClient=1 preferred slot = -1
CDOTA_PlayerResource: Adding player SteamID 90071996842377224 to slot 9 FakeClient=1 preferred slot = -1
CGCJobRequestBatchPlayerResourcesResponse: Received 1 account resources.
PR:SetTextChatBanned 0:[U:1:118513177] false
PR:SetVoiceChatBanned 0:[U:1:118513177] false
PR:SetLowPriority 0:[U:1:118513177] false
PR:SetPossibleHeroSelection 0:[U:1:118513177] npc_dota_hero_abaddon(102)
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 25 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 26 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 27 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 28 iterations without a present event.
PR:SetPossibleHeroSelection 0:[U:1:118513177] npc_dota_hero_slark(93)
PR:SetPlayerReservedState 0:[U:1:118513177] true
PR:SetSelectedHero 0:[U:1:118513177] npc_dota_hero_slark(93)
PR:SetSelectedHero 0:[U:1:118513177] npc_dota_hero_slark(93)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 25 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 26 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 27 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 28 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 29 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 30 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 31 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 32 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 33 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 34 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 35 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 36 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 37 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 38 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 39 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 40 iterations without a present event.

**Comment by mrzonin** [comment]
Anyone?

**Comment by gdrewb-valve** [comment]
The most likely explanation is still that this is a graphics driver problem.  Valve won't be able to get any more info unless we can repro it here and so far I don't believe we have.  This may take a long while to pin down.

**Comment by gdrewb-valve** [comment]
Was this affected by the latest updates?

**Comment by gdrewb-valve** [comment]
Closing pending confirmation that this is still active.
