### ISSUE TITLE
Benchmark mode

### ISSUE THREAD

**Issue by vhda** [ValveSoftware/Dota-2#682]
This ticket is to request a benchmark mode for Dota 2.
Below I'm adding a list of requirements that can be re-edited and updated according any comments added to this ticket.
- [ ] Command line enabled benchmark mode.
- [ ] Allow command line selection of video quality level.
- [ ] Demo game used in benchmark should include situations that are graphically intensive.

**Comment by danginsburg** [comment]
This is all already possible.  
- You can use +timedemo <demo_name> on the command-line.  The results will be written to game/dota/Source2Bench.csv.  The values in each column are described in the first line of the csv.
- The settings for each video quality level are described in game/dota/cfg/video_defaults_[0..3].txt and can be specified on the command-line
- What I usually do for a timedemo is download a match replay and then use a command-line such as the following to benchmark an intensive portion of a match.  For example, something like this:

dota2 +cl_showfps 2 +fps_max 0 -novconsole -w [resolutionX] -h [resolutionY]  +timedemo_start 40000 +timedemo_end 41000 +timedemo 115788802

**Comment by vhda** [comment]
Nice!
Thanks Dan.

**Comment by vhda** [comment]
One question: do all replays exist in the server forever?

**Comment by vhda** [comment]
Tried it as `steam -applaunch 570 +cl_showfps 2 +fps_max 0 -novconsole -w 1920 -h 1080 +timedemo_start 40000 +timedemo_end 41000 +timedemo 115788802` but it didn't work.

**Comment by danginsburg** [comment]
You need to actually download a match.  You can do that from the "Watch" tab in-game.  It will put a replay in game/dota/replays/match_id.dem.  Copy the file to game/dota and then you do +timedemo match_id.  You can pick one of the popular tournaments for example.
