### ISSUE TITLE
[Linux] Arc Warden and Zeus portraits not animating

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#686]
Hi there,

The new portraits which have been added to the client with the recent update (Arc Warden's and Zeus') do not animate in pickscreen. (In-game HUD portraits work properly.)

 ![Example](http://i.imgur.com/s6sftRu.jpg)

They are also really bad quality. (Sorry I don't have a gif)

They don't animate on the Dashboard Menu's "Heroes" screen either, but neither does any other portrait so that's not directly related to this issue.

**Comment by danginsburg** [comment]
We have a fix for this.  It impacted OS X as well as Linux.  Fix will be in the next update.

**Comment by u00101010** [comment]
It is now fixed, thank you! :blush:

(The "Heroes" screen still does not work, but this issue has been fixed.)
