### ISSUE TITLE
[Linux] game freeze when I try exit (close game) [from latest two patch]

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#687]
Hi.

When I try quit from game (close it) game instant freeze. So I can't propertly exit game, I need manually destroy dota2 process in system task manager :/

This bug is every I try close game.

I tested it on two computers:

Desktop PC with Linux Mageia 5x64 KDE
- gist: https://gist.github.com/xpris/b898150e756cd1b085f8

Notebook PC with Ubuntu 15.10 x64 Unity
- gist: I upload later, because Im not now in this notebook.

Quick info:
This bug persist from last two patch
In both computer I use AMD GPU with Catalyst driver (first catalyst 15.9, second radeon crimson 15.11)
both have AMD CPU - Phenom II

**Comment by gdrewb-valve** [comment]
This seems like a duplicate of #603, does that issue cover your case?

**Comment by AngryPenguinPL** [comment]
Look very smillar but in this topic this issues persist from few weeks and I have it only from last two update.

Today Is another update, I check it, maybe it fix this.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by AngryPenguinPL** [comment]
No, bug gone. Thanks.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
