### ISSUE TITLE
[MAC] DOTA2 force mac to restart

### ISSUE THREAD

**Issue by linrj123** [ValveSoftware/Dota-2#688]
Since the latest update, my mac crash down every time when i open dota2, and it force it to restart.

**Comment by ackFacu** [comment]
You will need more information... System information, and everything you can give... They are not gurus

**Comment by w1ld0g** [comment]
Hello there,
I'm also encountering the same issue on my macbook.
After the first big update of 6.86, the Dota menu opens, and then the Mac restarts one second later.

Mac specifications:
MacBook Pro (15-inch, Mid 2010)
OSX 10.10.5 (14F1509)
2.66 GHz Intel Core i7
8 GB 1067 MHz DDR3
NVIDIA GeForce GT 330M 512 MB
on SSD.

I really want to send you more information about the crash, but i simply doesn't find where are the dump and log files of Dota2 on the OSX. (i can't even find my GPU driver version on OSX.... i just don't know how)

Can someone, maybe ,direct me to the place that i could find a the specific information? 
(tried to check for a folder named 'dumps' on steam folder, tried to check in \library\logs)

Thank you in advanced.

**Comment by gdrewb-valve** [comment]
In the Steam client there's a System Information option in the menus.  That'll show a bunch of information that you can post here.  The Failure Reports section will have logged crash dumps.

However, any problem that causes the Mac to restart is a system issue (by definition since it is a violation of privilege for a normal process to kill the entire machine) and won't be handled directly in this forum.  It's possible that you won't get any relevant failures in the Steam reports section since the machine dying will prevent any kind of failure reporting even if Steam is actually getting a chance to record it.  The most likely cause of this is a bug in the Apple OpenGL driver.

**Comment by linrj123** [comment]
same model 

Mac specifications:
MacBook Pro (15-inch, Mid 2010)
OSX 10.11.2 
2.53 GHz Intel Core i5
8 GB 1067 MHz DDR3
NVIDIA GeForce GT 330M 256 MB
on SSD

MacBook Pro (15-inch, Mid 2010)
MacBook Pro (17-inch, Mid 2010)
NVIDIA Geforce GT 330M  openGL version 3.3  
openCL version 1.0

**Comment by gdrewb-valve** [comment]
Can you post the Steam system information, as mentioned above?

**Comment by linrj123** [comment]
Processor Information:
    Model:  MacBookPro6,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2530 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.2 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 330M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xa29
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 12.95" x 8.15"  (15.28" diag)
                                        32.9cm x 20.7cm  (38.8cm diag)
Primary VRAM: 256 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  228115 Mb
    Largest Free Hard Disk Block:  4081 Mb

Installed software:
    人人桌面
    Accessibility Inspector
    acis3dt_xchg
    Adobe Photoshop CC 2015
    AliWangwang
    Analog Efex Pro
    Analog Efex Pro 2
    App Store
    Application Loader
    Automator
    Calendar
    Capture NX 2
    Capture NX 2 Uninstall
    Capture NX-D
    cd to
    Coda
    Color Efex Pro 4
    COMSOL Multiphysics
    COMSOL Multiphysics Server
    COMSOL Update
    COMSOL with MATLAB
    Contacts
    Dfine2
    Dota 2
    DZH
    Eclipse
    Equation Editor
    EuDic
    FaceTime
    FileMerge
    Frhelper
    Game Center
    gedit
    Git Gui
    Google Chrome
    Google Drive
    Google Photos Backup
    Google+ Auto Backup
    HDR Efex Pro 2
    hexin
    iBooks
    ICBC UsbKeyTools-Tendyron
    Image Capture
    Instruments
    Keynote
    Launchpad
    LensFlares
    LTspice
    MAMP
    MAMP PRO
    MAMP PRO Uninstaller
    Maps
    MenuTab for Facebook
    Messages
    Microsoft Alerts Daemon
    Microsoft Chart Converter
    Microsoft Clip Gallery
    Microsoft Database Daemon
    Microsoft Database Utility
    Microsoft Document Connection
    Microsoft Excel
    Microsoft Graph
    Microsoft Office Reminders
    Microsoft Office Setup Assistant
    Microsoft Outlook
    Microsoft PowerPoint
    Microsoft Upload Center
    Microsoft Word
    MiniTerm
    Mission Control
    MPlayerX
    MxVPN
    My Day
    Nikon Message Center 2
    Nikon Message Center 2 Uninstaller
    Nikon Movie Editor
    Nikon Transfer 2
    Notes
    Numbers
    OBS
    Office365Service
    Open XML for Excel
    org.eclipse.equinox
    Pages
    Photos
    Picasa
    Picture Control Utility 2
    Picture Control Utility 2 Uninstaller
    Pokemon Trading Card Game Online
    QQ
    QQMacMgr
    Refresher
    Reminders
    Remote Desktop Connection
    scilab-5.5.1
    Sequel Pro
    Sharpener Pro 3 Output Sharpening
    Sharpener Pro 3 Raw Presharpening
    Silver Efex Pro 2
    Solver
    Steam
    Stickies
    StuffIt Archive Manager
    StuffIt Destinations
    Sublime Text 2
    SyncServicesAgent
    SyphonInject
    Thunder
    Trim Enabler
    Uninstaller
    ViewNX 2
    ViewNX 2 Uninstaller
    Viveza 2
    WeChat
    Xcode

**Comment by linrj123** [comment]
problem still exists, i just installed dota2 under windows with the same computer, when i launch it the screen turns black. The good news is it didn't force my mac to restart, and it shows nvidia windows kernel driver is forced closed. so i think the problem is that the updated game is not compatible with GT330m, because i've just updated my video card drive before the installation.  
btw, openGL under windows is v3.3.

**Comment by w1ld0g** [comment]
Strangely, I can confirm that "Dota 2 test" still works and do not restart at launch. (6.86 patch also)
What can I conclude from that? Im really puzzled.....

P.S
@linrj123 can you please confirm that "Dota 2 test" also works on your system?

P.S2
My system information:

Processor Information:
    Model:  MacBookPro6,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2660 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 330M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xa29
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 12.95" x 8.15"  (15.28" diag)
                                        32.9cm x 20.7cm  (38.8cm diag)
Primary VRAM: 512 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  704728 Mb
    Largest Free Hard Disk Block:  68036 Mb

Installed software:
    Accessibility On-Screen Keyboard
    Accessibility shortcut keys
    Alarm Clock Radio
    Altitude
    App Store
    Automator
    Beamer
    Braid Demo
    Calendar
    Character Map
    Clip Organizer
    Connect to a Network Projector
    Contacts
    Deluge
    DigiTest
    Disk Space Cleanup Manager for Windows
    Display Switch
    Dota 2
    Estranged Act I
    Executable for Chess Game
    Executable for FreeCell Game
    Executable for Hearts Game
    Executable for Mahjong Titans Game
    Executable for Minesweeper Game
    Executable for Purble Place Game
    Executable for Solitaire Game
    Executable for Spider Solitaire Game
    FaceTime
    Fcheck
    Final Cut Pro
    Football Manager 2015
    Game Center
    Google Chrome
    Google Search
    iBooks
    Image Capture
    imf_disp
    Install Adobe Flash Player
    Internet Backgammon
    Internet Checkers
    Internet Explorer
    Internet Spades
    Launchpad
    License Transfer Utility(English)
    License Transfer Utility(Japanese)
    License Transfer Utility(Simplified Chinese)
    LMU
    LTU
    Maps
    Math Input Panel Accessory
    Maya
    Messages
    Microsoft® Disk Defragmenter
    Microsoft® Windows® Operating System
    Microsoft® Windows Repair Disc
    Microsoft® Windows System Restore
    Microsoft  Windows Fax and Scan
    Microsoft Access
    Microsoft Excel
    Microsoft iSCSI Initiator Configuration Tool
    Microsoft Office 2010
    Microsoft Office 2010 component
    Microsoft Office 2010 component [1]
    Microsoft Office Help Viewer
    Microsoft PowerPoint
    Microsoft Publisher
    Microsoft Screen Magnifier
    Microsoft Sync Center
    Microsoft Word
    MiniTerm
    Mission Control
    Narrator
    Notepad
    Notes
    ODBC Administrator
    Only If
    Paint
    Paint X Lite
    Parallels Access
    Parallels Desktop
    Parallels Link
    Parallels Mounter
    Personalize Handwriting Recognition UI
    Photos
    Plex Media Server
    Popcorn-Time
    PopcornTime
    Private Character Editor
    Pro Tools
    qbittorrent
    Reminders
    Remote Desktop Connection
    Resource and Performance Monitor
    Skype
    Slender The Arrival
    Snipping Tool
    SoftwareUpdater
    Speech Recognition
    Steam
    Stickies
    Sticky Notes
    System Configuration Utility
    System Information
    Tablet PC Input Panel Accessory
    TeamSpeak 3 Client
    TeamViewer
    TerraTech Demo
    The Plan
    Timeless
    TorrenTV
    uTorrent
    VLC
    Windows Calculator
    Windows Command Processor
    Windows Control Panel
    Windows Desktop Gadgets
    Windows DVD Maker
    Windows Easy Transfer Application
    Windows Easy Transfer Post Migration Application
    Windows Explorer
    Windows Features
Windows host process (Rundll32)
    Windows Journal
    Windows Media Center
    Windows Media Player
    Windows Memory Diagnostics Tool
    Windows Mobility Center
    Windows Movie Maker
    Windows PowerShell
    Windows PowerShell ISE
    Windows Remote Assistance
    Windows Shell Common Dll
    Windows Sound Recorder
    Windows Task Manager
    Windows Update Application Launcher
    Windows VM Applications
    Windows Wordpad Application
    XPS Viewer

**Comment by ackFacu** [comment]
How I can able dota2 test? I have a similar problem (#667)

**Comment by w1ld0g** [comment]
@elnll002  Doesn't dota 2 test just appear on your library when you install dota?
anyways... just get to: https://steamdb.info/app/205790/ (it's the app on steam db)
you should get an install link from there. (aka steam://install/205790)

P.S
I read #667, and personally, i don't think it's the same problem (for us, me and Lin, Dota 2 doesn't work at all) 
But i really don't know, so forget it :)

**Comment by linrj123** [comment]
@w1ld0g just checked dota2 test under windows because i dont have enough space under osx. It turns out the same problem.

**Comment by gdrewb-valve** [comment]
Given that you're seeing the same issue under Windows it's possible you may have a hardware problem.  It's unlikely we'll get much farther from our end and as this isn't a Linux or Mac issue it's not something that will be tracked here but I'll hold it open for a bit.

**Comment by linrj123** [comment]
@gdrewb-valve  hey, this is absolutely not a hardware problem. there's a time (about 3 days ago under osx, but still after the first crash down) i can play when i change my using language of steam to english instead of Simplified Chinese. However this problem comes back after the update followed. i don't think i gotta have a hardware problem depends on the updates. i test under windows only because i'm tired of pushing my mac restart time and time again. if i would have a hardware problem, that could probably cause it. btw @w1ld0g is always following this topic and i can also take some space from my mac and reinstall it.

**Comment by gdrewb-valve** [comment]
The reason I mentioned a hardware issue is that there's something wrong in the system itself (software or hardware) if the machine is rebooting.  It's odd that the same thing would happen under entirely different OS's, so the cause may be lower down.  A Reborn update could have changed to something that triggers the problem, so having it occur from an update is possible.

As I mentioned it's only a possibility and it may very well be something else entirely.

**Comment by curtsywithanger** [comment]
I've been getting crashes now on my iMac for that last week or so. Sometimes it will play a whole match and be fine, other times, like just recently, it will crash when I'm simply trying to load a bot match. I cannot restart my computer until I unplug it from the wall and plug it back in. Upon restart there is no error message given like there would be from a kernel panic crash. Without an error message, I have no clue what to start searching for.

Thinking it might be something hardware related, I booted up in Apple Diagnostic mode and ran through that. It turned up nothing—everything was fine. Considering my computer crashes only when playing Dota, I think that is the cause. Please see the attached zipped file for my computer specs.

[iMac.zip](https://github.com/ValveSoftware/Dota-2/files/75094/iMac.zip)

**Comment by gdrewb-valve** [comment]
Reborn can't cause a machine to lock up like that even if it wanted to, that's a system / hardware / driver problem.

**Comment by curtsywithanger** [comment]
After doing more research on my particular issue, I'm inclined to agree that Reborn isn't causing the issue, but is a catalyst for it with my particular machine. It seems what I'm experiencing is more a defect in this batch of iMacs than with any software, the shut downs just happen more frequently and in sequence while playing Dota.

For anyone else with a late 2012 iMac, you may actually be experiencing this:
https://discussions.apple.com/thread/6176570?tstart=0

**Comment by w1ld0g** [comment]
hello @curtsywithanger , and welcome.
The different random crashes on Mac @Dota2 aren't so rare, i had them alot before (sometimes more, sometimes less)
Many people complained this, in many versions of the game, but we don't want address that issue here.
We opened this bug about: "restart upon every single start of the Dota 2 application (or after few seconds)" (after patch 6.68), Not the random crashes issue.

Plus, you have different generation GPU (GeForce 6), hence, different hardware problems.

Anyway, @linrj123 , in the next days i will try to install dota2+dota2test on MacBook+windows and see what the results are, the result should point if it's a hardware issue or not.

@gdrewb-valve , in your opinion, If it is really a GPU hardware issue, Does installing a different GPU (like 770m or other supported one) should solve this "startup restart" issue?
thank you in advanced.

P.S
important to note - All my other games are working great: L4D2, Unity games, all source related games. 
(is there any game besides Dota2 that i can test the source2 engine?)
@linrj123 , did you test other games\apps on your machine? (GPU related apps)

**Comment by gdrewb-valve** [comment]
I don't know exactly what the problem is so it's hard to speculate on whether switching GPUs would help or not.  I don't think it's worth going out and buying a new one just to experiment as it could very easily be something else.  I'm guessing on no information, though, as we have no repro here to look at.

**Comment by linrj123** [comment]
@w1ld0g , hello, i play games everyday and nothing wrong except dota2. I'm in college dormitory so i don't have other machines to test. There aren't many complains till right now, so i think dota2 reborn runs well on the others. As i mentioned under windows, there is a warning says 'nvidia windows kernel driver is forced to quit' every time when i launch dota2, i bet the problem probably is the game doesn't fit the GPU.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Reborn problem.
