### ISSUE TITLE
Hero screen is freaking out

### ISSUE THREAD

**Issue by MeioJo** [ValveSoftware/Dota-2#689]
Hero screen is scrolling thru heros non-stop both in the hero screen and the customize hero (single hero) screen..

I can't look at any heros...

perma next on the heros and it looks random too...

**Comment by MeioJo** [comment]
https://www.youtube.com/watch?v=C6NVSckEGnk

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information, in particular, any controllers that might be connected. This looks like a game controller is connected and has an uncalibrated analog stick.

**Comment by MeioJo** [comment]
Ya sorry .. home for the holidays so it's my Moms computer ;)

os x 10.9.5.

3.2g i5

8gb ram ddr3

**Comment by MeioJo** [comment]
Oh ya I have a G13 but the analog stick is set to f1, y, g, alt

**Comment by MeioJo** [comment]
The Logitech G13 soft/version is 8.60.313

**Comment by MeioJo** [comment]
Unplugged the g13 > start DotA and it still is happening...

**Comment by vadi2** [comment]
Switch to the grid mode, allows you to pick a hero. I get it every now and then as well playing on Ubuntu with mouse and keyboard.

**Comment by MeioJo** [comment]
@ vadi2  Did you watch the video?

Already in grid mode.. or am i missing something?

**Comment by gdrewb-valve** [comment]
Seems like a duplicate of #174, did you see that one?  It also involves bad input with a G13.

**Comment by MeioJo** [comment]
Yes I would have to say it is a match :)

however unplugging the G13 and then starting Reborn does not stop the issue from happening.

**Comment by gdrewb-valve** [comment]
Closing in favor of #174.
