### ISSUE TITLE
[Mac]: add notify support (match ready)

### ISSUE THREAD

**Issue by suptimal** [ValveSoftware/Dota-2#69]
can we have to notification support again as in dota 2

**Comment by KuriKai** [comment]
I would also like this, very very useful

**Comment by kon14** [comment]
That feature was extremely useful, especially for everyone disabling music in desktop and headphone users

**Comment by gdrewb-valve** [comment]
This will be fixed in the next update.

**Comment by gdrewb-valve** [comment]
Linux notifications should be working in the 6/26 update.

**Comment by blendi-93** [comment]
noooo, u killed it ;) pls readd the next release label ;)

**Comment by gdrewb-valve** [comment]
Linux notifications should be working.  Mac notifications are farther out so I removed the label.

**Comment by blendi-93** [comment]
i just played a game and got no notification.

  - arch linux
  - libnotify 0.7.7-1
  - dunst 1.1.0-1

**Comment by gdrewb-valve** [comment]
You have the 6/30 update?  Do you get a sound at the point you want the notification?  Does your system have the notify-send utility?  That's currently the only mechanism it's using right now.

**Comment by blendi-93** [comment]
i get the game rdy sound, is notifi-send called by custom games?

    # notify-send --version
    notify-send 0.7.6

**Comment by gdrewb-valve** [comment]
I believe it's only hooked up in one place in matchmaking so it may not be enabled for yours.  Can you list specifically when you'd like to get a notification?

**Comment by gdrewb-valve** [comment]
Note also that I don't believe many places are hooked up on Windows either.  If you know of a place that notifies on Windows but does not on Linux those would be of particular interest here.

**Comment by blendi-93** [comment]
thx,

i want a notification

    Dota 2
    ur game is ready

for example. everytime a game custom; ranked or normal is ready.

**Comment by blendi-93** [comment]
tested it, searching for custom game skillshot wars (great mod btw):

![aplay triggert](http://i.imgur.com/9A5Lytx.png)
aplay triggert by dota2 but no notification (shuld be top right)

![gam is rdy](http://i.imgur.com/fygrwRJ.jpg)
y my (custom) game is rdy.

**Comment by computerquip** [comment]
Notification for normal match making doesn't appear to work either.

**Comment by gdrewb-valve** [comment]
There's a fix coming for the normal notification.

**Comment by suptimal** [comment]
yey notifications working on linux now, thx. now i can use my accept script in reborn too ;)

**Comment by suptimal** [comment]
sry markdown didnt work in title :D

**Comment by vhda** [comment]
Working perfectly! :)

**Comment by gdrewb-valve** [comment]
SDL issue #3075 discusses adding system notification support to SDL itself, which we could potentially switch to.

**Comment by gdrewb-valve** [comment]
We have a fix/workaround coming for OSX that will allow notifications to work there also.

**Comment by gdrewb-valve** [comment]
The Sep. 1 update should have notifications on OSX now.

**Comment by gramathy** [comment]
This is not working properly on OS X, Dota was registering notifications as if it were a different application (for some reason, WJoy+) and when I removed that application due to not using it, notifications ceased to work entirely.

I can't test it further because I've been locked out of matchmaking for a day twice in a row. I'll try reinstalling the game to see if it registers itself properly but I won't be able to see if that worked until tomorrow. Maybe minimizing desktop-friendly causes notifications to not go through?

**Comment by gramathy** [comment]
Confirmed notifications are not working for me. It's not even showing up in the list of applications using notifications.

**Comment by gdrewb-valve** [comment]
The Oct. 16th update should change the dota2 packaging a bit.  Notifications should be working, can you retry?

**Comment by gramathy** [comment]
I can confirm notifications have been working after clearing out notification center database and it hasn't screwed up on my again. This is probably okay? I'll keep an eye on it long term, I just got my machine working again yesterday so I haven't had much opportunity to keep track.

**Comment by gdrewb-valve** [comment]
Thanks for checking.

**Comment by KuriKai** [comment]
This seems to have broken in ubuntu. How can i go about debugging it?

**Comment by gdrewb-valve** [comment]
There's not a lot you can do.  See if notify-send works when you run it manually.  If so then see if Reborn is trying to run notify-send.

As far as I know nothing has changed in Reborn's code to launch the notify.
