### ISSUE TITLE
Cannot launch Dota2

### ISSUE THREAD

**Issue by KaanK95** [ValveSoftware/Dota-2#690]
Ever since wednesday, I can't start up Dota since it keeps on crashing and saying "Dota 2 has quit unexpectedly." I can't seem to find an answer for it since I've been searching the net for a while and nothing has helped me. Any suggestions or ideas that actually work? Thanks. :)

**Comment by ackFacu** [comment]
They will need system information and if possible, some log, or anything you can give to help to understand whats is the problem

**Comment by gdrewb-valve** [comment]
Let's start with the system information from Steam.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
