### ISSUE TITLE
Offline Friends Scroll issue

### ISSUE THREAD

**Issue by MeioJo** [ValveSoftware/Dota-2#691]
Main Page > Friends > Offline the system will not let me scroll thru my offline friends... it keeps forcing the scroll to be above the offline level.

https://www.youtube.com/watch?v=xDtiJ2b_RKM

os x 10.9.5

3.2 g i5

8 gb ddr3

G13 game pad soft/v. 8.60.313

**Comment by gdrewb-valve** [comment]
This doesn't appear to be platform-specific and I've passed it on to the larger team.
