### ISSUE TITLE
Massive FPS drop on macintosh after 6.86 and 6.86b

### ISSUE THREAD

**Issue by mrdvc** [ValveSoftware/Dota-2#692]
Hi Valve,

I am using MacBook Pro mid 2012 with dedicated graphics (NVIDIA GeForce GT 650M 512 MB). Before 6.86 I was having stable 60-70 FPS, in teamfights it was going down to 55fps. 

After the update I changed the graphics to the lowest possible and I still have 30 stable, 20-25 in teamfights. The game is unplayable on Mac currently. With previous graphics settings I was getting 20stable 10 in teamfights. 

My full specs:

MacBook Pro 2012
8GB Ram
2.3 GHz Intel Core i7
NVIDIA GeForce GT 650M 512 MB

**Comment by danginsburg** [comment]
I test on this same Macbook Pro and have not seen this fps drop.  Can you provide a bit more information here?  What resolution are you running at?  Is it Exclusive Fullscreen or Desktop-Friendly fullscreen?  Is vsync on?  Please try desktop-friendly fullscreen with no vsync.  Also, it may be helpful if you run with -con_logfile and post game/dota/console.log.

**Comment by danginsburg** [comment]
Also, post full system specs from Help -> Steam -> System Information.

**Comment by danginsburg** [comment]
Another thing to check: make sure you are actually running on the Geforce GT 650M and not the HD 4000.  You can use gfxcardstatus to force it on: https://gfx.io/

**Comment by mrdvc** [comment]
TY for the fast responce. Yes i have GFX enabled and I have NVIDIA running. 

I am playing at this moment with 30 FPS. 

Here is the video settings -> http://i.imgur.com/Zk9pcAZ.png

When i say lowest, i mean lowest graphics possible :D 

I am trying to find  Help -> Steam -> System Information. will post soon

**Comment by mrdvc** [comment]
Processor Information:
    Model:  MacBookPro9,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.0 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 650M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xfd5
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 12.95" x 8.15"  (15.28" diag)
                                        32.9cm x 20.7cm  (38.8cm diag)
Primary VRAM: 512 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  227792 Mb
    Largest Free Hard Disk Block:  19441 Mb

**Comment by mrdvc** [comment]
I am still running Yosemite 10.10.0 though. Because once i went from Mavericks to Yosemite Dota was super laggy, but you fixed it for Yosemite and I stayed on that OS since.

**Comment by danginsburg** [comment]
Hmm...I am not aware of any reason that 10.10.0 would be running that slow.  That being said, I am running on the same Macbook Pro with 10.11.2 and with the video setting you posted it runs at about 112fps in a local botmatch.  Can you please put -con_logfile in your Launch Options and then post game/dota/console.log.  Maybe there will be a clue what is going on.

**Comment by mrdvc** [comment]
I am lost on that one. Can u guide me a bit.

I set -con_logfile in Launch Options -> http://i.imgur.com/MjN1DHP.png

Steamapps folder is on desktop (not sure why) and from there I go Desktop/steamapps/common/dota 2 beta/game/dota/ but there is no console.log file. I also started a bot game just to make sure "-con_logfile" took place.

**Comment by mrdvc** [comment]
Here's the folder -> http://i.imgur.com/OorenEy.png

**Comment by mrdvc** [comment]
I also tried completely restarting steam, and starting a bot match still no console.log file. 

I even searched the whole steamapps directory

**Comment by mrdvc** [comment]
Here is a screenshot from GFX just in case -> http://i.imgur.com/PuS6rO9.png . It says its running the NVIDIA, should i change from "dynamic switching" to "discrete only"?

**Comment by danginsburg** [comment]
You set the command-line option correctly.  For me, the console.log is located in:

/Users/username/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/console.log

I suppose you can try doing something like find ~ -iname "console.log" to see where it is being written.  I don't think you need to force it to discrete only, but you can try.

**Comment by mrdvc** [comment]
Ah yes, I made a desktop backup cause I wanted to reinstall steam. Ok i got the file. 

Meanwhile i upgraded to 10.10.5, and I will to El Capitan later today. 

http://kula9.com/console.log -> here is the file, i uploaded to my server

**Comment by mrdvc** [comment]
Updated to El Capitan, fps is about the same. Tipping 30 as stable, 20 and less in fights

**Comment by danginsburg** [comment]
Unfortunately, I am not seeing anything in your console.log that indicates what the performance problem could be.  Please report back if 10.11.2 helps things at all.

**Comment by danginsburg** [comment]
You can try the NVIDIA El Capitan web driver: http://www.nvidia.com/download/driverResults.aspx/92173/en-us . You may also want to try Intel Power Gadget to see if perhaps your CPU is being throttled: https://software.intel.com/en-us/articles/intel-power-gadget-20

**Comment by mrdvc** [comment]
I installed NVIDIA driver but i wasnt able to instal the Intel Power Gadget. The DMG starts but without results. I checked widgets and dashboard area couldnt find the Power Gadget. 

With the new drivers there is no result still low fps.

Here is what I snapped from Activity Monitor about CPU usage:

http://i.imgur.com/kb3ffbu.png

If you can suggest me anything else I am open to anything, if not i would like to keep this thread/issue opened if possible because I will try and I might find a solution.

One thing I forgot, I have a funky battery on this laptop which may be cause for downgrade of the performances. I will replace it around the first half of January.

However, as a daily doto player I noticed this FPS drop after 6.86 and 6.86b. It wasnt like this before. But at the end it might be multiple things from my and your side causing the issue. 

I was tweaking the "Game Screen Render Quallity" slider in video options and I noted that even on 100% (with all checkboxes disabled, such as vsync etc), I get the same FPS.

**Comment by mrdvc** [comment]
Today it got better, I dont know if these changes I did affected the performance, but I have around 55 stable tipping 60, and 40 in teamfights which is totally fine for me comparable to what I have few days ago

**Comment by gxgani** [comment]
I would like to add that this started happening before 6.86 was released. I noticed it especially during the hot-fixes prior to 6.86.

Intel HD4000

**Comment by danginsburg** [comment]
@mrdvc I am going to  close out this bug given the performance has improved for you.  It is unfortunate that we don't know what was causing the performance degradation.  I am not aware of anything we changed in the engine over this time period that would have caused this, but glad to hear it's improved.

**Comment by leonnardo** [comment]
Ok, I'm having issues like @mrdvc after changing monitor (using now an external monitor..)
And while I was playing in source 1 with 60fps with 1080p res, now in 1080p i got like 15fps..
