### ISSUE TITLE
Cannot remap window properly

### ISSUE THREAD

**Issue by weltensturm** [ValveSoftware/Dota-2#694]
Some window managers break Dota, presumably because the game can't handle un- and remapping the window.
Example with the window manager "i3": Start Dota 2, wait for the window to appear, switch to a different workspace, switch back to the workspace holding the game. Now the picture is frozen and the game is unusable.

OS: Arch Linux 4.2.5-1
Window manager: i3 (Probably happens on every WM that unmaps windows at some point, at least also broken for my custom wm)
Graphics driver: nvidia 358.16-2.1
GPU: GTX 970
Due to the steam servers dying due to the sale I couldn't login again to get the info through steam.

**Comment by gdrewb-valve** [comment]
Highly likely to be the same thing as #360.

**Comment by weltensturm** [comment]
It doesn't say anything about video breaking, but maybe. It happens in all display modes for me though. It doesn't happen in CS:GO (any video mode), are you using the same SDL version (if even) there? I assume at least windowed mode should work then.

**Comment by gdrewb-valve** [comment]
The SDL in Reborn is not always in sync with the one in CS:GO, plus the applications use SDL differently.  We really need to get the SDL team to investigate but so far we haven't had any luck.

**Comment by weltensturm** [comment]
It doesn't seem to happen with dwm (which I copied), I'll try to figure out what it is

**Comment by weltensturm** [comment]
Fixed it for my WM :) Apparently it didn't send Configure events on a ConfigureRequest, instead it just did XMoveResizeWindow. Still applies to i3, but that may be a bug on their part. Now I have the same problems as in #360 though

Update: This happens any time the window is resized to something different than the ingame resolution, even if the window is resized to the proper values instantly after that. Window managers taking max/min size hints into consideration are unaffected, but you might consider looking into it for the ones that don't. Perhaps something to do with framebuffers getting invalidated on resize?

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by weltensturm** [comment]
Works! Thank you.
