### ISSUE TITLE
Enemy units not taking any damage from Riki's new ulti on Linux

### ISSUE THREAD

**Issue by tfhavingfun** [ValveSoftware/Dota-2#696]
Just tried out the latest patch 6.86, and played a riki game, but it seems that enemy units are not taking any damage from his new ulti, Tricks of the trade. The channeling animation works, but no attacking animation.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.1.0
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0xa16
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3286 x 1080
Primary Display Size: 18.74" x 10.51"  (21.46" diag)
                                        47.6cm x 26.7cm  (54.5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: 

Memory:
    RAM:  7893 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  444124 Mb
    Largest Free Hard Disk Block:  260695 Mb

Installed software:

Recent Failure Reports:

[screencast.m4v.zip](https://github.com/ValveSoftware/Dota-2/files/71125/screencast.m4v.zip)

**Comment by Plagman** [comment]
Hi,

For general gameplay issues that are not specific to the Mac/Linux versions, please use the dev forums instead. In addition to that, Tricks of the Trade only affects hero units as of the latest update.
