### ISSUE TITLE
Problem with binding numbers on the top of the keyboard in Linux

### ISSUE THREAD

**Issue by fkonecny** [ValveSoftware/Dota-2#699]
The problem occurs only when I am using a different keyboard layout than english one. If I want to map keys to the control groups which are usually 1, 2, 3, 4, 5, 6 I cannot do so with other layout than english or rather to say that has a different system bindings for these keys on the keyboard.

E. g.
english keyboard layout has on the top bindings 1, 2, 3, 4, 5, etc.
slovak keyboard layout has on the top bindings +, ľ, š, č, ť, etc.
The odd thing is does not cause any kind of problem on windows, where + is actually mapped as 1 in game, ľ as 2 and so on, but on Linux this behavior does not happen (+ is +).

**Comment by gdrewb-valve** [comment]
Key bindings are layout-specific by default.  Go to the Advanced section of the key binding settings page and select the checkbox for positional bindings.  Do things work as you expect then?

**Comment by fkonecny** [comment]
That worked, thank you very much. Sorry for the trouble with my lack of digging around.
