### ISSUE TITLE
Linux: High ksoftirqd

### ISSUE THREAD

**Issue by xfalcox** [ValveSoftware/Dota-2#7]
After launching the client the game runs really fine, but I'm getting a relatively high load on ksoftirqd for each core on my machine:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                              
 7595 falco     20   0 4843460 2,125g 303332 S 129,7 13,6  34:55.64 dota2                                
    3 root      20   0       0      0      0 R  17,6  0,0   7:56.04 ksoftirqd/0                          
   15 root      20   0       0      0      0 S  17,3  0,0   8:00.68 ksoftirqd/1                          
   22 root      20   0       0      0      0 S  17,3  0,0   8:03.13 ksoftirqd/2                          
   29 root      20   0       0      0      0 S  16,6  0,0   8:07.24 ksoftirqd/3                          
  821 root      20   0  230216 107904  60756 R   6,7  0,7   6:05.25 Xorg         
```

Is this expected?

**Comment by gdrewb-valve** [comment]
source2 isn't doing anything directly that would cause this, but it could be stressing your system.  Were you running a network match?  Various web pages mention that high network traffic could cause it.

**Comment by computerquip** [comment]
This isn't an issue with DotA 2. If anything, it would be a driver issue. However, I think this is within normal bounds.

**Comment by lightning18** [comment]
This also happens to my Arch+NVIDIA(proprietary)
```
  PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND                                   
 1624 lightni+   6   0 4015.9m 1.768g 171.5 22.7  36:58.30 R dota2                                     
   19 root       2   0    0.0m   0.0m  14.6  0.0   2:06.03 S ksoftirqd/2                               
    3 root       1   0    0.0m   0.0m  13.9  0.0   2:05.97 S ksoftirqd/0                               
   14 root       1   0    0.0m   0.0m  13.9  0.0   2:05.93 S ksoftirqd/1                               
   24 root       4   0    0.0m   0.0m  13.9  0.0   2:05.92 S ksoftirqd/3                               
  977 lightni+   1 -11  549.5m  12.3m   1.3  0.2   0:07.89 S pulseaudio                                
  925 root       1   0  189.3m  68.9m   0.7  0.9   0:43.78 S Xorg
```

The gameplay is fine but the audio is stuttering uniformly from the dashboard to the game.

**Comment by xfalcox** [comment]
This happens just after opening the game and stays till closing, through UI, bot games offline, custom games online etc. Tried nvidia closed 340.x and 352.x and it's the same thing. I'm on latest kubuntu, ssd only setup, 16gb ram and i5 processor so my system isn't stressed at all.

On dota 2 source 1 this doesn't happen.

**Comment by presianbg** [comment]
Hi.
Why It's closed ?

**Comment by xfalcox** [comment]
@presianbg It isn't closed, as you can see in the top of the page. Only the referenced issue #42 was closed because was a duplicate of this one.

**Comment by gdrewb-valve** [comment]
Does the 6/24 update make a difference?

**Comment by xfalcox** [comment]
@gdrewb-valve Yeah! Thanks a lot!

**Comment by imirkin** [comment]
Confirming that the super-high interrupt rate is gone, ksoftirqd is silent, and the game usage seems reasonable.

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by lightning18** [comment]
I can also confirm that this is fixed and dota2 binary does not go over 150 now but I still have audio stuttering. Should I open a new issue?

**Comment by computerquip** [comment]
lightning18, yes.
