### ISSUE TITLE
[Linux] Dota 2 consumes all my CPU every match at midgame

### ISSUE THREAD

**Issue by dssouza-ti** [ValveSoftware/Dota-2#700]
Hello! I'm having a issue with my dota2 client for linux.
Around 20~30min of every match, my cpu goes crazy and gets 100% on the four cores. So I can't play or use my pc, even the alt+tab function takes a lot of time. When I manage to kill the dota2 process, exit steam, and enter the game again, I can reconnect to the match and play normally until the 20~30 minute mark of the next match, when it happens all over again.

**Comment by ArnaudAndre** [comment]
I wonder if your problem may be caused by your CPU getting throttled to low performance levels due to say, high temperatures. In any case your system infos may help (steam main window -> help -> system informations).

**Comment by dssouza-ti** [comment]
Hi, I did have problems with high temperature before, it causes my pc to shutdown when it goes high enough. I fixed this already, and my pc is at normal temperature all the time. I wonder if there's another reason that could cause my CPU to get throttled to low performance as you say.

anyway, this is my system information, let me know if you need something else.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.3 Rosa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.5.9
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x116
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12,17" x 6,81"  (13,94" diag)
                                        30,9cm x 17,3cm  (35,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  3847 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  137353 Mb
    Largest Free Hard Disk Block:  75155 Mb

Installed software:

Recent Failure Reports:

**Comment by gdrewb-valve** [comment]
I don't believe anybody at Valve has seen behavior like that, we'll see if we can repro.

**Comment by dssouza-ti** [comment]
OK. Thank you very much. If I notice any change of behaviour or if I somehow manage to find what is causing this problem, I'll reply to this post.

**Comment by gdrewb-valve** [comment]
Is this still happening after the latest updates?

**Comment by dssouza-ti** [comment]
hey, I just played it today all afternoon and it didn't happen again. I believe the updates fixed it.

my only problem now is low performance with my intel integrated GPU, but that is a completely different thing, so you can close this issue report.

Thank you for your attention.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
