### ISSUE TITLE
Soul Assumption indicator bars are missing sometimes

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#701]
Hi there,

I gues this might not be a Linux-specific issue, although at least I get some feedback here that you at least got the report and read it.

So the Soul Assumption indicator bars that normally appear above Visage's head when the ability is learned sometimes simply disappear. I've read reports on dev.dota about the bars disappearing, however, those were all related to the Visage player disconnecting. In my cases (because this happened multiple times) neither me nor any of the other players have disconnected at all during the entirety of the game. It simply disappeared and I had to guess how many charges I may have for a couple of minutes. Then it came back all of a sudden. I personally can't see a pattern between the bars appearing or disappearing.

![Missing bars](http://i.imgur.com/KA8V7PX.jpg)

These might help:

Match IDs, in which this happened: 2033716901 and 2029237012 (not 100% sure about the 2nd one)
[A Gist with my system information](https://gist.github.com/helix42/895352598fb5cef94952)

**Comment by gdrewb-valve** [comment]
Unlikely to be a Linux/Mac issue, I'll let the larger team know.

**Comment by gdrewb-valve** [comment]
Passed on to the larger team.
