### ISSUE TITLE
[MAC] Repick doesn't work after random

### ISSUE THREAD

**Issue by anilanar** [ValveSoftware/Dota-2#703]
How to reproduce: 

1) Start normal/ranked all pick match (doesn't work in bot matches)
2) Wait until hero selection screen
2) Click on "Random Hero"
3) Click on "Repick"

What happens:
1) Hero is not repicked
2) Text that shows remaining time goes up in the layout (its vertical position changes)

**Comment by gdrewb-valve** [comment]
Unlikely to be a Mac/Linux issue.

**Comment by gdrewb-valve** [comment]
This isn't platform-specific and I've passed it on to the larger team.
