### ISSUE TITLE
Bounty Gold Wrong

### ISSUE THREAD

**Issue by dbag2** [ValveSoftware/Dota-2#705]
I started a lobby and entered the game.  I created a bot and killed it before the timer reached 0:00.  I received 458 gold.  I checked the calculation on http://dota2.gamepedia.com/Gold and i can't find a way to get that number.  (I tried multiple combinations of the bot killing me and buying the exact same items as the bot to ensure the net worth was identical -- either way 458 gold.)  Is the information on the wiki wrong or is 458 gold a miscalculation?

**Comment by gdrewb-valve** [comment]
This issue tracker is for Mac and Linux issues, but I'll pass this on to the larger team.

**Comment by dbag2** [comment]
thank you :)

**Comment by gdrewb-valve** [comment]
I haven't gotten any answer so far.  I'm closing this but if they respond I'll post back here.
