### ISSUE TITLE
Core Dump on Minimize (Alt+Tab, Ctrl+Alt+D)

### ISSUE THREAD

**Issue by 14droplets** [ValveSoftware/Dota-2#706]
### Bug details:

Sometimes (quite often actually) dota 2 process right after a minimize event starts consuming all the memory it can find and than crashes.
### Clues:

OS journal contains stack trace of dota 2 process: https://gist.github.com/Snork2/3f95f57f456cf8e31c53
There is several core dumps, I did not knew which one is needed, so I uploaded all of them here: https://drive.google.com/folderview?id=0BwFUZdsGglbhTEpxZnR6T1hxZ0k&usp=sharing
### System info:

Operating system and distro - Arch Linux
Window manager - xfwm4

From steam help:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1201
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 2704 x 1111
    Primary Display Size: 17,05" x 10,67"  (20,08" diag)
                                            43,3cm x 27,1cm  (51,0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: 

Memory:
    RAM:  7944 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  282600 Mb
    Largest Free Hard Disk Block:  87355 Mb

Installed software:
```

**Comment by gdrewb-valve** [comment]
I was unable to repro any problems on my Linux system.  Your stack trace shows an abort inside of the NVIDIA OpenGL driver so this may be a driver issue.  If you look on the steam-for-linux repo there are some known issues with the 358 drivers.

**Comment by gdrewb-valve** [comment]
Is this still happening with the latest Reborn and NVIDIA drivers?

**Comment by 14droplets** [comment]
I wanted to write about it just today, but forgot.
Yes, it seems that problem is gone with latest nvidia driver updates and the dota 2 itself. TY for your work, I'm closing issue.
