### ISSUE TITLE
Dota 2 wont launch on mac

### ISSUE THREAD

**Issue by Zay-Afk** [ValveSoftware/Dota-2#707]
after installing dota on my imac i could not launch it. At first I got an error message saying i didnt meet the graphics card requirement but now i dont even get an error message. I click play it says syncing and then nothing happens. Any tips or explanations?

Specs:
AMD Radeon HD 6750M 512 MB

 Mac OS X Lion 10.7.5 (11G63)

4 GB 1333 MHz DDR3

**Comment by Zay-Afk** [comment]
tried the whole verifying files and reinstalling tricks already btw

**Comment by danginsburg** [comment]
Minimum requirement is 10.9.  You will need to upgrade OS X.

**Comment by Zay-Afk** [comment]
thanks appreciate the quick reply love dota 2 keep up the good work
