### ISSUE TITLE
dota_shop_recommended_open doesn't work

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#708]
Can't set the option so the suggested popup doesn't appear. I've reported this a long time ago, but still no resolution :/

**Comment by gdrewb-valve** [comment]
Where did you report it?  This forum is only for Mac and Linux specific issues so this isn't really the right place.

**Comment by p-groarke** [comment]
Well I can't test on windows, I report all my bugs here. Maybe you could make sure its in your bug tracker?

Here was the original thread, little less than a year ago http://dev.dota2.com/showthread.php?t=159045

edit: Before Reborn.

**Comment by gdrewb-valve** [comment]
dev.dota2.com is the right place and it looks like you've bumped that thread so everything's good on that front.

**Comment by p-groarke** [comment]
Alright, thank you :)
