### ISSUE TITLE
Dota browser not closing

### ISSUE THREAD

**Issue by tarriel** [ValveSoftware/Dota-2#709]
If I go to the watch tab, bring up the tournaments, click view, in the view box click on the tournament website link.  wait for it to load, click reload, wait for it to load,  after this you are locked in a loop and can't bring up the tournaments or watch etc, swapping to shop, heroes, learn etc doesn't break the loop, clicking the X to close the browser doesn't break the loop.  Every time you return to the tournament tab it has the browser in front.  

The only way out is to hit the back button.  in my case a lot of times

This is different behaviour to what happens if there is no refresh.

**Comment by gdrewb-valve** [comment]
Not platform-specific, I've passed this on to the larger team.

**Comment by tarriel** [comment]
I run Mint linux, but I have since had this verified by someone running windows.

**Comment by gdrewb-valve** [comment]
Verified meaning they verified the problem also happens on Windows?

**Comment by tarriel** [comment]
Yes,  meaning that they could reproduce the same behaviour under Windows, Not sure which version of Windows they run though.

**Comment by gdrewb-valve** [comment]
OK, thanks for the confirmation.
