### ISSUE TITLE
SDLAudioDev2 thread high CPU usage - poll() loop

### ISSUE THREAD

**Issue by rgehlen** [ValveSoftware/Dota-2#711]
When I launch dota2 the CPU usage even in idle is not as expected. In htop I can see SDLAudioDev2 thread bouncing around between 80-100% CPU usage. When tracing the thread it just does poll() a lot. 

Note that I use pulseaudios networking features (module-native-protocol-tcp) so this could be related but I'm not sure.

**Comment by gdrewb-valve** [comment]
This thread is from SDL and not Reborn but I can pass this on to the SDL devs.

**Comment by rgehlen** [comment]
I noticed that in dota2 process the environment for SDL_AUDIODRIVER was alsa, I changed dota.sh to export SDL_AUDIODRIVER=pulse on a hunch and it solved the problem.

**Comment by rgehlen** [comment]
Simply unsetting SDL_AUDIODRIVER also works since it doesnt default to alsa by default apparently.

**Comment by gdrewb-valve** [comment]
The SDL devs have identified this as a problem in ALSA itself so you'll want to follow up with that project.
