### ISSUE TITLE
[Linux] Items missing from my inventory!

### ISSUE THREAD

**Issue by FalconBR** [ValveSoftware/Dota-2#712]
I was about one year, maybe more, without playing dota 2, and this week I was back and I couldn´t find my keys on my inventory!
What can we do about it?

**Comment by Tele42** [comment]
@FalconBR This issue tracker is for technical issues with the mac and linux client of Dota 2, not account management.

**Comment by FalconBR** [comment]
So, missing items from inventory is not a Linux bug?

**Comment by gdrewb-valve** [comment]
I believe Tele42 was thinking you were asking about getting your inventory fixed, in which case this is not the place.  If you're just reporting the bug that's fine but there's no reason to believe it's Linux-specific so you would be better off reporting it in the regular dev forums dev.dota2.com.
