### ISSUE TITLE
[Linux] Keyboard input does not work as intended

### ISSUE THREAD

**Issue by ivanradanov** [ValveSoftware/Dota-2#714]
I use the i3 window manager on Debian testing linux. I use the setxkbmap command to enable a Bulgarian keyboard layout:

```
setxkbmap -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle -option caps:escape
```

When I start Dota 2 while on the English layout, input works as intended, however, if I start the game while on the Bulgarian layout (switching to English in game does not fix this):

What does NOT work:
- q,w,e,r (casting spells)
- z,x,c,v,b,n (using items)
- attack command (a button)
- stop command (s button)
- bring up the scoreboard using `
- Ctrl - 1 opens the chat and writes 1s to it somehow
- the rest of the numbers pressed with control do nothing

What does work:
- F1, F2 and F3 for hero and courier
- alt clicking on stuff
- shift clicking items in the store
- writing in chat

**Comment by gdrewb-valve** [comment]
This is by-design.  Go to the Advanced section of the key bindings settings page and select positional bindings and then things will work as you expect.
