### ISSUE TITLE
Random crashes/freezing with amdgpu and Fury X

### ISSUE THREAD

**Issue by HarlemSquirrel** [ValveSoftware/Dota-2#717]
So I am using a Sapphire R9 Fury X with Antergos and the open source amdgpu driver. I am currently running the 4.4rc8 kernel and am getting random freezes or crashes about once per hour or so. 
Software versions:
    4.4.0-rc8-g02006f7a
    OpenGL version string: 3.0 Mesa 11.1.0

GPU hardware:
    OpenGL renderer string: Gallium 0.4 on AMD FIJI (DRM 3.1.0, LLVM 3.7.0)
    01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Fiji XT [Radeon R9 FURY X] [1002:7300](rev c8)

CPU hardware:
    x86_64
    AMD FX-8370 Eight-Core Processor

Attached is the output of dmesg after a crash:
[dmesg.txt](https://github.com/ValveSoftware/Dota-2/files/83912/dmesg.txt)

**Comment by Tele42** [comment]
This should also be reported to the mesa devs, also please include any CrashIDs related to the crash here for a valve dev to see where it is crashing.

**Comment by Plagman** [comment]
Looks like the graphics driver is mis-programming the hardware and causing GPU faults and system freezes; this tracker is for issues with Dota2 itself, not third-party drivers.

**Comment by HarlemSquirrel** [comment]
OK, thanks guys, sorry for the confusion.
