### ISSUE TITLE
[Windows & Linux (OSX too if i remenber correctly)] No Taskbar icon

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#718]
This in incredible, that's still not fixed in all of your games

Please do it asap that's really frustrating

**Comment by Tele42** [comment]
Dota 2 has an appropriate icon in the taskbar when I alt-tab away from the game here on Gentoo Linux with KDE 4.

**Comment by gdrewb-valve** [comment]
This repo is for Mac-and Linux-only bugs in Dota 2 Reborn so this isn't the right place to report the issue.  Also Reborn has a proper taskbar icon on Windows and Mac.  Whether it works on Linux depends on your window manager but, as Tele42 mentions, it definitely does work when it can.

**Comment by ghost** [comment]
On windows 8.1 the icon appear once, then disapear when i alt-tab and i switch back in the game by clicking in the taskbar icon

It's the right place cause i have the issue also on Ubuntu 16.04 x64, the icon is merged with steam icon group

cf: https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/510

I have no idea why you closed the issue, since the issue i have also affect linux as mentioned in the title

**Comment by ghost** [comment]
Here is a screenshot in case you don't believe me:

![Screenshot](http://i.imgur.com/UE2gZFQ.png)
http://i.imgur.com/UE2gZFQ.png

**Comment by gdrewb-valve** [comment]
As I mentioned this repo is for Mac-ONLY and Linux-ONLY bugs.  Bugs which occur on all platforms (they happen on Windows and Mac and Linux) are handled by the larger team.  That forum is at dev.dota2.com

**Comment by ghost** [comment]
Ohh ok i got it! well sorry for the inconvenience then, i'll post it on the forum you mentioned
