### ISSUE TITLE
[Mac] Dota makes trackpad unfunctional until system restart

### ISSUE THREAD

**Issue by mikonium** [ValveSoftware/Dota-2#719]
After I close dota, my trackpad can no longer hold the down state or register the hover state -- I can click but I can't drag or hover. It makes the trackpad fairly worthless until I restart my computer to reset the trackpad. 

I've noticed this problem only occurs if I move the trackpad during gameplay (which is hard to avoid since my wrist usually ends up brushing it while I press buttons furiously). 

I am running El Capitan but I've had this issue in both Mavericks and Yosemite. I can't believe it's not fixed yet.

**Comment by gdrewb-valve** [comment]
The problem persists even after you've completely exited Reborn?  You should report this to Apple also.

**Comment by mikonium** [comment]
Yes, it persists until I restart.

**Comment by tiagoln** [comment]
I also have this problem since Mavericks. I noticed that it does not require a full restart to make the trackpad work properly again, if you logoff from the current osx user and login again the trackpad restore it’s functionality. It’s a really annoying bug since I have to do this every time I play Dota2.

**Comment by mikonium** [comment]
That's true -- it is fixable by logging on and off. I tried to find a Terminal command that would reboot just the trackpad driver, (so I could make a script to run it whenever dota closes) but I've found no such command.

**Comment by gdrewb-valve** [comment]
I would again encourage you to report this to Apple since that's the most likely way that this will get addressed.  Valve is probably not going to discover what the trackpad problem is since we don't have any visibility into the system code handling the trackpad.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Reborn issue.

**Comment by tiagoln** [comment]
Just an update on the issue, I've done a clean install of the osx some time ago and reinstalled steam and dota 2 from scratch, the trackpad issue seems to be gone since then. So, anyone with this issue should give it a try.
