### ISSUE TITLE
Dota 2 Reborn increases Linux kernel CPU usage

### ISSUE THREAD

**Issue by minecraft2048** [ValveSoftware/Dota-2#72]
So I'm curious with Dota 2 Reborn CPU and memory requirements, so I SSH to my laptop and I use htop. Then I that the CPU bar have more red bar than usual. I suspect Dota 2 Reborn is causing this, so I tried to isolate it. 

Here is the screenshot of my desktop with all running programs:

![screenshot_2015-06-24_20-39-26](https://cloud.githubusercontent.com/assets/2445636/8331589/6278defa-1ab3-11e5-817e-387a91298c48.png)
![screenshot_2015-06-24-20-40-03](https://cloud.githubusercontent.com/assets/2445636/8331595/6a9ce45a-1ab3-11e5-88db-82d624fa2cfb.png)

and here is the same laptop with normal Dota 2 running in main menu:

![screenshot_2015-06-24-20-41-29](https://cloud.githubusercontent.com/assets/2445636/8331610/7a3a00be-1ab3-11e5-9355-12a7e8b1e788.png)
with some low priority process that normal Dota 2 spawns

and here is the same laptop with Dota 2 Reborn running in main menu:

![screenshot_2015-06-24-20-42-17](https://cloud.githubusercontent.com/assets/2445636/8331637/97f94e20-1ab3-11e5-8f35-8610609a37a2.png)

Here is htop help page:

![screenshot_2015-06-24_20-44-47](https://cloud.githubusercontent.com/assets/2445636/8331648/a616f778-1ab3-11e5-8f08-d36ea567c0c1.png)

As you can see, Dota 2 Reborn increases Linux kernel CPU usage significantly. I still cannot think of any other application/game that makes the kernel work really hard, so I put it here. Is it intended?

Steam system information:

[code]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630M/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xde9
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12,17" x 6,85"  (13,94" diag)
                                        30,9cm x 17,4cm  (35,4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3838 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  156888 Mb
    Largest Free Hard Disk Block:  69068 Mb

Installed software:

Recent Failure Reports:

[/code]

**Comment by r3pek** [comment]
I have to say that i should be normal to have higher CPU usage because Source 2 is more multi-threading friendly. Just don't know how much would be "too much"

**Comment by gensss** [comment]
see bug #7

**Comment by davidw-valve** [comment]
We do have some improvements to CPU usage coming out in the next update. Hopefully it will mitigate this.

However it is normal for an intensive application such as a game to increase kernel CPU usage in some instances.

**Comment by gdrewb-valve** [comment]
Does the 6/24 update make a difference?  Usage should still be high, that is expected, but it should improve from the original release.

**Comment by gdrewb-valve** [comment]
Closing as other people have reported improvements.

**Comment by AlynxZhou** [comment]
I get the same problem on my archlinux.
