### ISSUE TITLE
dota 2 launch problems 

### ISSUE THREAD

**Issue by ahmadaltayeh2001** [ValveSoftware/Dota-2#720]
iam trying to launch dota 2 on linux ubuntu 14.04 and it says missing executable , i tried everything on steam support but it didnt work

**Comment by ArnaudAndre** [comment]
Are you maybe using the 32 bit version of ubuntu ? Did you just install dota or dit it ever work on this computer ?

**Comment by Tele42** [comment]
It should be noted that Dota 2 is 64 bit only since switching to Source 2.

**Comment by gdrewb-valve** [comment]
Closing pending more info that this is actually a problem.
