### ISSUE TITLE
[Linux] Game randomly crashes when mini/maximizing

### ISSUE THREAD

**Issue by fumazu** [ValveSoftware/Dota-2#721]
Maybe related to #706

No reliable repro for this but sth like:
1. Open Dota 2
2. Use Alt+Tab to minimize the game or bring it back into focus
3. Game crashes from time to time

Happened 2 times today, see _Recent Failure Reports_ below.

**System information:**

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.63
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1086
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 2960 x 1050
    Primary Display Size: 18,66" x 11,65"  (21,97" diag)
                                            47,4cm x 29,6cm  (55,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1280 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: CMI8786

Memory:
    RAM:  7960 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1262825 Mb
    Largest Free Hard Disk Block:  963715 Mb

Installed software:

Recent Failure Reports:
    Wed Jan 13 20:32:19 2016 GMT: file ''/tmp/dumps/crash_20160113202355_1.dmp'', upload yes: ''Discarded=1''
    Wed Jan 13 22:52:10 2016 GMT: file ''/tmp/dumps/crash_20160113225746_1.dmp'', upload yes: ''Discarded=1''
```

**Comment by gdrewb-valve** [comment]
Unfortunately the report were discarded so we don't have them here.  If you get one that has an ID instead we can take a look at it.  Also if you find a solid repro we can look into it as we don't have a repro here.

What video mode are you running Reborn in?

**Comment by fumazu** [comment]
Those files were still in my /tmp/dumps/, so here you go: https://drive.google.com/folderview?id=0BzG05wyuCPL7NW5Sb1FONmwzdkk&usp=sharing

Video Mode: Desktop-friendly fullscreen

**Comment by gdrewb-valve** [comment]
Both of those crashes are in the NVIDIA OpenGL driver and are likely NVIDIA issues, but if we can repro we can try and confirm.

**Comment by gdrewb-valve** [comment]
Is this still happening with the latest Reborn and NVIDIA drivers?

**Comment by fumazu** [comment]
Frequency decreased by a lot. I'm still using NVIDIA driver version 352.63 though.

Edit: Game just crashed again while I was watching the Shanghai-Major. https://drive.google.com/open?id=0BzG05wyuCPL7c045WmJGMG5LSEU

**Comment by gdrewb-valve** [comment]
That dump also is a crash in the NVIDIA driver.

**Comment by gdrewb-valve** [comment]
I would recommend upgrading your NVIDIA driver if you can and seeing if that helps.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear to be a Reborn problem.
