### ISSUE TITLE
(MAC) Dota 2 fails to launch

### ISSUE THREAD

**Issue by trooblaz** [ValveSoftware/Dota-2#722]
Been playing Dota 2 just fine up until the Reborn beta hit/updating my OS. I've been trying various fixes — running with -autoconfig, -novid, -safe launch options, reinstalling both Dota 2 and Steam, restarting — on my Mac OS X 10.11.2 El Capitan, to no avail. I've also verified the game cache files. Zippo. I am by no means a computer expert, so I will just list as much info as I can here.

My system specs are up to snuff (4GB 1600mhz RAM, Intel HD 4000 graphics, 2.3 ghz Intel Core i7 processor, plenty of storage on 500GB hard drive), so I doubt that's the issue.

When I launch Dota, the icon will appear in the dock. The program will try to launch, and I'll get the black Dota 2 screen w/logo for a few seconds, then the game will crash. The following appears in the error report:

Crashed Thread: 0 MainThrd Dispatch queue: com.apple.main-thread

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: (index >= 0) && (index < [_itemArray count])'
terminating with uncaught exception of type NSException
abort() called

And later...

Thread 0 crashed with X86 Thread State (64-bit):
rax: 0x0000000000000000 rbx: 0x0000000000000006 rcx: 0x00007fff50d30528 rdx: 0x0000000000000000
rdi: 0x000000000000050f rsi: 0x0000000000000006 rbp: 0x00007fff50d30550 rsp: 0x00007fff50d30528
r8: 0x0000000000000003 r9: 0x00007fff96970a7c r10: 0x0000000008000000 r11: 0x0000000000000206
r12: 0x00007fff50d306b0 r13: 0x00007fff9be114c0 r14: 0x00007fff7b3c2000 r15: 0x00007fff50d30590
rip: 0x00007fff9fd49002 rfl: 0x0000000000000206 cr2: 0x00007fff7d2a9008

Logical CPU: 0
Error Code: 0x02000148
Trap Number: 133

Is there something I'm missing?

**Comment by gdrewb-valve** [comment]
Are you using Mumble?  Check issue #433.  If not can you post the stack information that comes after the 'Thread 0 crashed' bit (example in issue 433)?

**Comment by trooblaz** [comment]
Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff9fd49002 **pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff922bc5c5 pthread_kill + 90
2   libsystem_c.dylib               0x00007fff9b3f66e7 abort + 129
3   libc++abi.dylib                 0x00007fff96949f81 abort_message + 257
4   libc++abi.dylib                 0x00007fff9696fa47 default_terminate_handler() + 267
5   libobjc.A.dylib                 0x00007fff9be26491 _objc_terminate() + 103
6   libc++abi.dylib                 0x00007fff9696d19e std::__terminate(void (_)()) + 8
7   libc++abi.dylib                 0x00007fff9696cc12 __cxa_throw + 121
8   libobjc.A.dylib                 0x00007fff9be22877 objc_exception_throw + 363
9   com.apple.CoreFoundation        0x00007fff953258ba +[NSException raise:format:arguments:] + 106
10  com.apple.Foundation            0x00007fff8c94b88c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
11  com.apple.AppKit                0x00007fff925910b4 -[NSMenu itemAtIndex:] + 178
12  com.myownapp.MenuAndDockless    0x00000000ae715982 -[Menuless insertMenu] + 17298
13  com.myownapp.MenuAndDockless    0x00000000ae716565 +[Menuless load] + 181
14  libobjc.A.dylib                 0x00007fff9be1767f call_load_methods + 731
15  libobjc.A.dylib                 0x00007fff9be16fea load_images + 123
16  dyld                            0x00007fff69c56de1 dyld::notifySingle(dyld_image_states, ImageLoader const_) + 221
17  dyld                            0x00007fff69c646ca ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 286
18  dyld                            0x00007fff69c64563 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 127
19  dyld                            0x00007fff69c647d3 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
20  dyld                            0x00007fff69c59eb0 dyld::runInitializers(ImageLoader_) + 89
21  dyld                            0x00007fff69c61128 dlopen + 555
22  libdyld.dylib                   0x00007fff9db8879c dlopen + 59
23  com.apple.CoreFoundation        0x00007fff9524d119 _CFBundleDlfcnLoadBundle + 153
24  com.apple.CoreFoundation        0x00007fff9524c8e8 _CFBundleLoadExecutableAndReturnError + 520
25  com.apple.Foundation            0x00007fff8c8d67c3 _NSBundleLoadCode + 512
26  com.apple.Foundation            0x00007fff8c8d619b -[NSBundle loadAndReturnError:] + 229
27  com.apple.Foundation            0x00007fff8c932d70 -[NSBundle principalClass] + 44
28  net.culater.SIMBL.osax          0x00000000ad6bb69b +[SIMBL loadBundle:] + 99
29  net.culater.SIMBL.osax          0x00000000ad6bb5a6 +[SIMBL installPlugins] + 426
30  net.culater.SIMBL.osax          0x00000000ad6ba3cf InjectEventHandler + 96
31  com.apple.openscripting         0x00007fff8cf30f17 EventHandlerThunk(AEDesc const_, AEDesc_, void_) + 108
32  com.apple.AE                    0x00007fff8c392231 aeDispatchAppleEvent(AEDesc const_, AEDesc_, unsigned int, unsigned char_) + 531
33  com.apple.AE                    0x00007fff8c391fb8 dispatchEventAndSendReply(AEDesc const_, AEDesc*) + 31
34  com.apple.AE                    0x00007fff8c391ed4 aeProcessAppleEvent + 288
35  com.apple.HIToolbox             0x00007fff95cd2af9 AEProcessAppleEvent + 55
36  com.apple.AppKit                0x00007fff92597588 _DPSNextEvent + 2245
37  com.apple.AppKit                0x00007fff92963943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
38  libSDL2-2.0.0.dylib             0x00000000809043f5 Cocoa_PumpEvents + 277
39  libSDL2-2.0.0.dylib             0x000000008083ea00 SDL_PumpEvents_REAL + 48
40  libSDL2-2.0.0.dylib             0x000000008083ea98 SDL_WaitEventTimeout_REAL + 56
41  libSDL2-2.0.0.dylib             0x000000008082a39a SDL_WaitEventTimeout + 42
42  libinputsystem.dylib            0x000000008925a967 CInputSystem::SleepUntilInput(int) + 263
43  libengine2.dylib                0x000000000f21348a CEngineServiceMgr::_MainLoop(double, double) + 522
44  libengine2.dylib                0x000000000f21324f CEngineServiceMgr::MainLoop(double, double) + 15
45  libengine2.dylib                0x000000000f20a860 MainLoop(SwapChainHandle_t**_, PlatWindow_t___, InputContextHandle_t___) + 384
46  libengine2.dylib                0x000000000f20ae63 Source2MainInternal(void_, void_, char const_, int, char const_, char const_) + 819
47  libengine2.dylib                0x000000000f20b07d Source2Main + 141
48  com.dota2                       0x000000000eed7d57 main + 535
49  libdyld.dylib                   0x00007fff9db895ad start + 1

**Comment by trooblaz** [comment]
Also, thanks for the speedy response!

**Comment by gdrewb-valve** [comment]
Your problem appears to be MenuAndDockless.  If you turn that off do things work?

**Comment by trooblaz** [comment]
How do I disable that?

**Comment by gdrewb-valve** [comment]
No idea, I've never used it and don't know anything about it. I only found it doing a web search on com.myownapp.MenuAndDockless from the crash report you posted.

**Comment by trooblaz** [comment]
Eradicated every MenuAndDockless file in my Library, and the game actually boots! Thanks so much.

**Comment by gdrewb-valve** [comment]
Great, closing.
