### ISSUE TITLE
Since last patch all effects are missing in Linux Intel HD 4000

### ISSUE THREAD

**Issue by felipec** [ValveSoftware/Dota-2#723]
Pretty much the title. The game is pretty much unplayable without actually seeing what's happening. This started to happen since the patch rolled out today, not before.

**Comment by danginsburg** [comment]
Can you please post system information from Steam -> Help -> System Information?  A screenshot would be helpful as well.

**Comment by gdrewb-valve** [comment]
This occurs on all platforms and the larger team is fixing it, closing.
