### ISSUE TITLE
Can't reconnect to server, game match vanished

### ISSUE THREAD

**Issue by labpaw** [ValveSoftware/Dota-2#726]
Today I was playing ranked matchmaking match and somewhere around 20-30 game minute I lost connection to server (The game started around 18:00 UTC+3:00 time). I made few attempts to reconnect to the server but after sometime game match just ended (I also checked my internet connection and it was ok). This match didn't appeared in game statistics and dotabuff won't display it too.
Later on, I added some guy from this game to friends and he said that he lost connection too and that seems everyone on server lost connection. Maybe this happened due to some bug? I'm willing to send my Steam profile and other player profiles if you need this kind of information but I want to keep them private. Is there are some place for it? If you need any more information just ask I'll try to provide as much as I can.

**Comment by gdrewb-valve** [comment]
This is unlikely to be platform-specific and probably won't be handled here, but first can you post your system information from Steam?

**Comment by labpaw** [comment]
Here it is: https://gist.github.com/Adaptivity/4e4f48e114cec82bb4aa

**Comment by gdrewb-valve** [comment]
This isn't the place to report Windows/general issues (that would be dev.dota2.com) so I'm closing this but if anything comes back from the larger team I'll post it here.

**Comment by labpaw** [comment]
So, should I try to report this to dev.dota2.com?

**Comment by gdrewb-valve** [comment]
Yes, that'll give the larger team an extra chance to see it.
