### ISSUE TITLE
Dota 2 false launches in Ubuntu 15.10 64 bits

### ISSUE THREAD

**Issue by Paypapeecee** [ValveSoftware/Dota-2#728]
Hello

Yesterday i downloaded Dota 2 in my Ubuntu 64 machine and when i launched it i saw the text ''preparing to launch dota'' appeared then dissapeared and the game remained unresponsive, I can see my dekstop and all but the game ''launches'' shows its ''ready'' shows me that i am ''ingame'' but i see nothing, it keeps unresponsive. So i am very worried about this since i verified the integrity of the game a lot of times and 4k files always fail to download, yesterday was the fourth attempt in trying to solve those 4k but they persist.

**Comment by gdrewb-valve** [comment]
In your Steam install directory there should be a logs subdirectory, and you put content_log.txt up as a gist?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
