### ISSUE TITLE
Ubuntu low fps (Nvidia 555M)

### ISSUE THREAD

**Issue by jmgirven** [ValveSoftware/Dota-2#731]
On the highest video settings down to the second lowest I am getting an average about 25 fps (worse in fights). If I change down to the lowest video settings, some of the time I get 90 fps, but when there are a couple of heroes on the screen I get 25 fps again. The drop in fps also happens in a local lobby or bot game. A friend on a similar laptop, except using Windows, is getting consistently 60-70 fps. I read somewhere that DOTA 2 on linux at the moment can get higher fps though. Is the fps I am seeing normal for a laptop like mine or is there something wrong:

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x2a
>     CPU Stepping:  0x7
>     CPU Type:  0x0
>     Speed:  3100 Mhz
>     8 logical processors
>     4 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     Ubuntu 15.10 (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.2.0-23-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11702000
>     X Window Manager:  Compiz
>     Steam Runtime Version:  steam-runtime-release_2015-06-12
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GT 555M/PCIe/SSE2
> 
> ```
> Driver Version:  4.5.0 NVIDIA 352.63
> OpenGL Version: 4.5
> Desktop Color Depth: 24 bits per pixel
> Monitor Refresh Rate: 60 Hz
> VendorID:  0x10de
> DeviceID:  0x124d
> Number of Monitors:  1
> Number of Logical Video Cards:  2
> Primary Display Resolution:  1920 x 1080
> Desktop Resolution: 1920 x 1080
> Primary Display Size: 23.54" x 13.23"  (26.97" diag)
>                                         59.8cm x 33.6cm  (68.5cm diag)
> Primary Bus: PCI Express 16x
> Primary VRAM: 3072 MB
> Supported MSAA Modes:  2x 4x 8x 16x 
> ```
> 
> Sound card:
>     Audio device: Intel CougarPoint HDMI
> 
> Memory:
>     RAM:  7877 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_GB.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  226646 Mb
>     Largest Free Hard Disk Block:  21870 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

I have tried updating the OS, drives, all other packages. Only changing to the lowest video setting as mentioned seems to have any effect.

**Comment by AngryPenguinPL** [comment]
You have two graphics adapter right? Maybe not Geforce gpu is using to game but integrated in Intel cpu?

**Comment by Tele42** [comment]
This sounds like the expected performance from optirun with virtualgl. If this is true, you should be trying to use optirun -b primus.
NOTE: I am not an optimus user, and this is based on speculation.

**Comment by jmgirven** [comment]
In my nvidia-settings -> PRIME Profiles, I have NVIDIA (Performance Mode) selected. It was my impression that everything went through the nvidia card because of nvidia-prime. Maybe I misunderstood. I tried installing Bumblebee / optirun this evening and managed to kill my laptop for several hours. I will read about it more carefully and try again if that is the best solution.

**Comment by jmgirven** [comment]
My NVIDIA card is definitely being used to some extent. On this laptop the HDMI port is directly linked to the NVIDIA card and so if the card isn't working, an external monitor won't work either. I am using an external monitor over HDMI right now.

Just for interest I tried switching to the Intel card using NVIDIA prime and played a bot match on the lowest graphics setting (and using the inbuilt screen). I was averaging about 40 fps with lows of 10 fps (compare with 90 and 25 fps above).

I wondered if the video resolution in DOTA might have an effect, but changing to 720p from 1080p, and switching between full screen and borderless window, nothing seems to have a significant impact.

**Comment by gdrewb-valve** [comment]
Has this changed after the recent updates?

**Comment by jmgirven** [comment]
Hi @gdrewb-valve, thanks for the interest. I only played one bot match so far, highest video settings, and maybe it was marginally more stable in the fights, but still averaging about 25-30 fps. So similar to before.

Since I last wrote I have been trying out the NVIDIA 361.18 driver from the graphics-drivers ppa. I don't think that has made a significant difference either. Any suggestions of other things to try? Thanks.

**Comment by gdrewb-valve** [comment]
Unfortunately no, I don't have any extra suggestions.  We don't have a configuration similar to yours to test here but we'll keep seeing if some problem pops up.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
