### ISSUE TITLE
[Ubuntu] Mouse is not locked in when co-Casting insde Lobby

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#733]
I have no issues with mouse locking when playing or just spectating games casually but yesterday i wasn't able to move my camera properly. Mouse was always escaping to the other screen when spanning the camera towards the other monitor.

Happened yesterday when casting Dota Cinema's Captains Draft Season 3 (first time casting on linux, I used to do that on Windows before)

I haven't notice anything else weird.

I use Ubuntu 15.10 with (classic) Gnome 1.17.1 and lightdm

**Comment by gdrewb-valve** [comment]
This appears to occur on all platforms and has been passed on to the larger team.

**Comment by admshao** [comment]
Not affected by Spring Cleanup update. It's been painfull to proper control the camera.
Please consider giving this another look.

**Comment by gdrewb-valve** [comment]
You'll want to report this at dev.dota2.com, this repo is for bugs that only happen on Mac and Linux.

**Comment by admshao** [comment]
Just to let you guys know that this has been fixed. Today i casted the major qualifiers and it's all good now!

Thx
