### ISSUE TITLE
[Ubuntu-Probably all plataforms] Mixed Cameras on Caster and Co-caster inside Lobby

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#735]
Related with #733 

Today again when casting Dota Cinema's Captains Draft Season 3 i was on the co-caster spot and clicked to be the camera man on our language. Quickly afterwards i clicked again to deselect because He was on the stream and not me. Funny thing is. The Camera for him was showing MY hero selections.. it was displayed for him and inside DotaTV

I just don`t know what happened.

VOD -> http://www.twitch.tv/nomadtv/v/36977564
Caster finds out the bug 16:05 minutes in. 

If further details is need for reproduction. I could transcript the video part about the bug. Or you guys can ask for Carlos (brazilian) help! He would recognize the caster! lol

I use Ubuntu 15.10 with (classic) Gnome 1.17.1 and lightdm

**Comment by gdrewb-valve** [comment]
This appears to occur on all platforms and has been passed on to the larger team.
