### ISSUE TITLE
Dota does not launch, output is a window only containing a broken font.

### ISSUE THREAD

**Issue by tmplt** [ValveSoftware/Dota-2#737]
**System Information**
- Arch Linux 64-bit
- bspwm (no specific rule for Dota, has worked before)
- AMD R9 290, on mesa drivers

When I start Dota from Steam, the following box appears:
![Error box](https://i.imgur.com/WAR3LrQ.png)

The following appears in the terminal when `dota.sh` is run:

```
$ ./dota.sh
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198041190165 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198041190165
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
```

Validating the game files did not help; none were missing nor invalid.

**Comment by gdrewb-valve** [comment]
That's a new one, we'll have to see if there's some kind of pattern among people hitting it.

**Comment by tmplt** [comment]
I forgot completely that I was running the `mesa-git` drivers.
Replacing it with `mesa` resolved the issue

**Comment by gdrewb-valve** [comment]
Thanks, closing.
