### ISSUE TITLE
Client randomly minimizes and crashes

### ISSUE THREAD

**Issue by D2Banish** [ValveSoftware/Dota-2#739]
Bug: Client randomly minimizes and crashes.
In Game Time: Random
Short description of issue: During game, client will minimize. Sound will be heard and game play is heard but screen will not return. It has happened since reborn and happens at least once a game, forcing a restart. Have tried all console codes, launch options, integrity checks and clean installation.

Processor Information:
Vendor: GenuineIntel
CPU Family: 0x6
CPU Model: 0x2c
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 3333 Mhz
12 logical processors
6 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed: 

Operating System Version:
Windows 7 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0

Video Card:
Driver: NVIDIA GeForce GTX 560M 

DirectX Driver Name: nvd3dum.dll
Driver Version: 9.18.13.3523
DirectX Driver Version: 9.18.13.3523
Driver Date: 4 Mar 2014
OpenGL Version: 4.4
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: NVIDIA GeForce GTX 560M 
VendorID: 0x10de
DeviceID: 0x1251
Number of Monitors: 1
Number of Logical Video Cards: 1
No SLI or Crossfire Detected
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 26.65" x 15.00" (30.55" diag)
67.7cm x 38.1cm (77.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1536 MB
Supported MSAA Modes: 2x 4x 8x 

Sound card:
Audio device: Speakers (Realtek High Definiti

Memory:
RAM: 6135 Mb

Miscellaneous:
UI Language: English
Microphone: Not set
Media Type: DVD
Total Hard Disk Space Available: 686693 Mb
Largest Free Hard Disk Block: 371294 Mb
OS Install Date: Dec 31 1969
Game Controller: None detected

Installed software:
7-Zip 9.20
Adobe Flash Player 12 ActiveX
Adobe Flash Player 12 Plugin
Adobe Reader XI (11.0.12)
Adobe Refresh Manager
Battle.net
BisonCam
BIT.TRIP RUNNER
CCleaner
Core Temp 1.0 RC6
Counter-Strike: Global Offensive
DAEMON Tools Lite
Defraggler
Dota 2
Driver Talent
ESET Smart Security
Fraps (remove only)
GOM Player
GOMTV Streamer
Google Chrome
Google Toolbar for Internet Explorer
Google Update Helper
Hotkey 3.3002
Intel® Matrix Storage Manager
Intel® PROSet/Wireless Software
Intel® PROSet/Wireless WiFi Software
Intel(R) PROSet/Wireless for Bluetooth(R) + High Speed
Intel(R) PROSet/Wireless WiFi Software Driver
ITECIR
Itibiti RTC
Java 8 Update 51
Java 8 Update 51 (64-bit)
Java Auto Updater
Java(TM) 6 Update 22
Java(TM) 6 Update 29
JavaFX 2.1.0
JMicron Ethernet Adapter NDIS Driver
JMicron Flash Media Controller Driver
Junk Mail filter update
K-Lite Codec Pack 9.7.0 (Basic)
Logitech Gaming Software
Microsoft .NET Framework 4.5.2
Microsoft Application Error Reporting
Microsoft ASP.NET MVC 4 Runtime
Microsoft Choice Guard
Microsoft Office 365 - en-us
Microsoft Silverlight
Microsoft SQL Server 2005 Compact Edition [ENU]
Microsoft Sync Framework Runtime Native v1.0 (x86)
Microsoft Sync Framework Services Native v1.0 (x86)
Microsoft Visual C++ 2005 Redistributable
Microsoft Visual C++ 2005 Redistributable (x64)
Microsoft Visual C++ 2008 Redistributable - x64 9.0.21022
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30411
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219
Microsoft Visual C++ 2010 x86 Redistributable - 10.0.40219
Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030
Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030
Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030
Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030
Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.21005
Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005
Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)
Microsoft XNA Framework Redistributable 3.1
Microsoft XNA Framework Redistributable 4.0 Refresh
MKVToolNix 6.8.0 (64bit)
MPC-HC 1.6.5.6366
MSVCRT
MSXML 4.0 SP2 (KB954430)
MSXML 4.0 SP2 (KB973688)
Network+ 2011 Book Sample
NVIDIA 3D Vision Driver 335.23
NVIDIA Control Panel 335.23
NVIDIA GeForce Experience 2.9.1.22
NVIDIA GeForce Experience Service
NVIDIA Graphics Driver 335.23
NVIDIA HD Audio Driver 1.3.34.4
NVIDIA Install Application
NVIDIA LED Visualizer 1.0
NVIDIA Network Service
NVIDIA PhysX
NVIDIA PhysX System Software 9.15.0428
NVIDIA ShadowPlay 2.9.1.22
NVIDIA Stereoscopic 3D Driver
NVIDIA Update 2.9.1.22
NVIDIA Update Core
NVIDIA Virtual Audio 1.2.34
Office 15 Click-to-Run Extensibility Component
Office 15 Click-to-Run Licensing Component
Office 15 Click-to-Run Localization Component
OpenAL
Pando Media Booster
PDFCreator
Protector Suite 2009
PunkBuster Services
Python 2.7.2
Python 3.2.2 (64-bit)
Realtek High Definition Audio Driver
Renesas Electronics USB 3.0 Host Controller Driver
Security Update for Microsoft .NET Framework 4.5.2 (KB3023224)
Security Update for Microsoft .NET Framework 4.5.2 (KB3035490)
Security Update for Microsoft .NET Framework 4.5.2 (KB3037581)
Security Update for Microsoft .NET Framework 4.5.2 (KB3074230)
Security Update for Microsoft .NET Framework 4.5.2 (KB3074550)
Security Update for Microsoft .NET Framework 4.5.2 (KB3097996)
Security Update for Microsoft .NET Framework 4.5.2 (KB3098781)
SHIELD Streaming
SHIELD Wireless Controller Driver
Steam
SteelSeries Engine 3.6.2
Synaptics Pointing Device Driver
System Requirements Lab Detection
System Requirements Lab for Intel
TeamSpeak 3 Client
Tixati
Uninstall Helper
Verizon Wireless Software Upgrade Assistant - Samsung(ar)
Verizon Wireless Software Utility Application for Android - Samsung
VLC media player
VVVVVV
Windows Live Call
Windows Live Communications Platform
Windows Live Essentials
Windows Live Family Safety
Windows Live Mail
Windows Live Messenger
Windows Live Movie Maker
Windows Live Photo Gallery
Windows Live Sync
Windows Live Upload Tool
Windows Live Writer

Thank you for your assistance

**Comment by gdrewb-valve** [comment]
This repo is solely for Mac- and Linux-specific bugs.  You'll want to report this at dev.dota2.com
