### ISSUE TITLE
linux - Map scroll down not working

### ISSUE THREAD

**Issue by milovanderlinden** [ValveSoftware/Dota-2#74]
In borderless window mode on Linux, moving the mouse to the bottom of the screen won't scroll the map down while in game when screen resolution equals the chosen resolution (in my case 1920x1080 monitor, 1920x1080 resolution picked)

I use gnome that takes up the top bar and maybe pushes the Dota Reborn window down a bit leaving the area to move the map just out of reach, because when I select a lower resolution where the bottom border is clearly visible, it works fine.
## Map Scroll not working:

![screenshot from 2015-06-24 20-53-42](https://cloud.githubusercontent.com/assets/106038/8338746/255e8a6a-1ab3-11e5-95a1-7b102f1fc8de.png)
## Map Scroll OK:

![screenshot from 2015-06-24 20-52-49](https://cloud.githubusercontent.com/assets/106038/8338758/421f34b0-1ab3-11e5-871e-6a1b0f4b5055.png)

**Comment by gdrewb-valve** [comment]
This is expected as mouse scroll only works at the edges of the window.  If the edge of the window is off the screen you can't reach it.  I would assume if you dragged your window half off the right or left side of the screen you wouldn't be able to edge-scroll on those hidden edges also.

**Comment by gdrewb-valve** [comment]
Leaving open as an enhancement request, although I'm not sure what would be done here other than preventing you from picking a window size that doesn't fit on your monitor.

**Comment by milovanderlinden** [comment]
I agree that it is expected behaviour. But I am unable to pick a resolution
that leaves room for the top bar or move the window to fit

2015-06-24 21:11 GMT+02:00 Drew Bliss <notifications@github.com>:

> Leaving open as an enhancement request, although I'm not sure what would
> be done here other than preventing you from picking a window size that
> doesn't fit on your monitor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/Dota-2-Reborn/issues/74#issuecomment-114983871>
> .
>



-- 
 [image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Comment by davidw-valve** [comment]
You can specify any resolution you want by setting Dota2's launch options in Steam to e.g. -w 1920 -h 1000

**Comment by gdrewb-valve** [comment]
The next update will change things so that the game will take up the whole screen when choosing a borderless window that fills your monitor, so in this case the menu bar will go away and you'll be able to see the whole game window, thus scrolling will work.

**Comment by milovanderlinden** [comment]
That would be great! Thanks for responding.

2015-06-25 19:54 GMT+02:00 Drew Bliss <notifications@github.com>:

> The next update will change things so that the game will take up the whole
> screen when choosing a borderless window that fills your monitor, so in
> this case the menu bar will go away and you'll be able to see the whole
> game window, thus scrolling will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/Dota-2-Reborn/issues/74#issuecomment-115344012>
> .
>



-- 
 [image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Comment by gdrewb-valve** [comment]
Does the 6/26 update work better?  Should this stay open?

**Comment by milovanderlinden** [comment]
6/26 works great! scrolls perfectly and interaction with my desktop is a big enhancement compared to the regular client. Closing. Thanks!

**Comment by AlbertClo** [comment]
I have the same problem on Linux Mint Cinnamon.

**Comment by MasterSergius** [comment]
Still have the same issue with scrolling - on borderless it shows menu status bar and can scroll any direction but down. Xubuntu 16.04

**Comment by gdrewb-valve** [comment]
That's expected with borderless windows, does it cover the menu bar if you use fullscreen?

**Comment by MasterSergius** [comment]
Oh, sorry. Yes, it works perfectly on fullscreen.
