### ISSUE TITLE
[Linux] High GPU usage on treasure chest set previews

### ISSUE THREAD

**Issue by 0xe4524ffe** [ValveSoftware/Dota-2#740]
I use Archlinux x86_64 with latest propiretary nvidia drivers(I have gtx 560Ti).

Always high GPU usage on treasure chest set previews,
Sometimes kernel panic.

**Comment by gdrewb-valve** [comment]
A kernel panic would indicate some kind of driver problem so you'll probably want to report this to NVIDIA also.

**Comment by gdrewb-valve** [comment]
Is this issue still active?
