### ISSUE TITLE
Game loads 3 times slower since newest patch.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#741]
Mac
24 GB 1600 MHz DDR3
3.2 GHz Intel Core i5
NVIDIA GeForce GTX 680MX 2048 MB

Ever since newest update loading in to the game takes 3 times as much time or more. Previously, since reborn was released loading time was hugely improved for MacOS, now when you accept a game or even try hero demo mode, it sits on the loading screen for a minute. Not sure why.

**Comment by gdrewb-valve** [comment]
Is it the same every time?  The update changed some things which would require a one-time startup cost but then future starts should not be that slow.

Can you post your console log also?

**Comment by Vuccappella** [comment]
Ok, I see what's happening. This is the console log upon loading. Initially it took me around 45 - 50seconds to load in a custom hosted lobby.
 http://pastebin.com/iXqwEQPk

But  after disconnecting from the lobby and rehosting a game with the same lobby settings I loaded in for about 10 seconds, twice in a roll so that is definitely working as intended. The future games load faster If I haven't closed the client.

Not sure if anything was changed since yesterday because there was an update since then I've installed but this wasn't the case yesterday as I basically did the same thing, I loaded in to a game it took about 50 seconds, then I checked to see if it was a one time thing immediately after the game by hosting a custom lobby and trying to demo a hero and even the consequent times it took about 50 seconds to load, so it might of been just a one time case or something might of been updated regarding that but I can confirm that if that's the intention it's definitely working now, slower load on first game but 5x faster on consecutive  loads.

**Comment by Turmfalke2** [comment]
I can confirm the same issue on linux, from what I can tell the console output is not helpful.

**Comment by gdrewb-valve** [comment]
Has the pattern changed any or is it just the first start after some updates that are slow?  Are things repeatedly slow for anybody?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
