### ISSUE TITLE
Extremely low fps after the last update

### ISSUE THREAD

**Issue by Mattele** [ValveSoftware/Dota-2#742]
Hello!

After the update with the Winter Pass, game is running horribly. Previously it was between 35-50 fps, now it's between 10-16 fps.

It's Macbook Pro 2012 with GT 650M. Around the same time I installed 10.11.3 update for OS X, so it might be also connected.

**Comment by Mattele** [comment]
If you'd ask me, its like the game uses integrated graphic card, instead of the dedicated one. I checked it against gfx card status, and it does enable dedicated card while playing a game, but seeing this performance I assume it still uses the integrated one.

Whats more: after lowering all settings I get 40-50 fps, with some drops during certain spells (like chronosphere), then it drops to 25 for a second.

**Comment by danginsburg** [comment]
One of my test configs is a Macbook Pro (Retina, Mid 2012) 2.7 Ghz Intel Core i7 NVIDIA GT 650M at 10.11.3.  It definitely sounds to me like you are getting the HD 4000.  If I run at max settings @ 1920x1200 resolution and go into a solo botmatch I get ~30.6fps (+cl_showfps 2 +fps_max 0).  If I crank the settings down, I can easily go above 60fps.  Please try forcing discrete graphics before you launch Steam using gfxcardstatus and see if it makes a difference.  There was nothing in the most recent update that should have dropped perf as you are seeing.  Here is my full system info.

Processor Information:
    Model:  MacBookPro10,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.3 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 12.99" x 8.15"  (15.31" diag)
                                        33.0cm x 20.7cm  (38.9cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  6437010 Mb
    Largest Free Hard Disk Block:  5485157 Mb

**Comment by JimmieCrackCorn** [comment]
I'm on Linux and after the latest winter pass update I have had a big decrease in performance. Instead of being maxed out at 120 my frames drop during fights sometimes to 60 - 80 ish and during playback of replays they are around 40 - 60. 

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4401 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-77-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 361.18
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1381
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  7937 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  930067 Mb
    Largest Free Hard Disk Block:  529366 Mb

Installed software:

Recent Failure Reports:

**Comment by Mattele** [comment]
It somehow works. I booted dota and it seems like it works now, and I havent changed anything.

I guess the case is closed for now. Thank you for your support!

**Comment by danginsburg** [comment]
Thanks for the update.  Closing.
