### ISSUE TITLE
Tabbing to Morph's Replicate doesn't work.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#743]
Mac OS El Capitan10.11.2

I've tested this multiple times now as I was trying to see what's happening. Posting this here, since all of my friends who play on Windows do not encounter this bug and only I do but there's a chance this isn't OS related.

Steps to reproduce:
1. Pick Morphling In a Custom Lobby Dota 2 Game  ( do not demo hero mode, read additional notes )
2. Create a Replicate illusion of a hero (ally or foe)
3. Try and Control Group Tab to your replicate using your key binding - Doesn't Select your replicate.

Additional Notes:
1. Changing your Control Group Tab binding doesn't fix the problem . I usually use X for that binding but I changed it to TAB to see if the default key would work, that didn't fix the issue.
2. Control Group Tab worked for illusion runes and manta but It just didn't tab to the replicate, 
   t̶h̶e̶r̶e̶'̶s̶ ̶p̶o̶s̶s̶i̶b̶l̶y̶ ̶o̶t̶h̶e̶r̶ ̶c̶a̶s̶e̶s̶ ̶w̶h̶e̶r̶e̶ ̶i̶t̶ ̶m̶a̶y̶ ̶n̶o̶t̶ ̶w̶o̶r̶k̶,̶ ̶h̶a̶v̶e̶n̶'̶t̶ ̶t̶e̶s̶t̶e̶d̶ ̶E̶T̶'̶s̶ ̶S̶p̶i̶r̶i̶t̶ ̶f̶o̶r̶ ̶e̶x̶a̶m̶p̶l̶e̶ ̶o̶r̶ ̶S̶h̶a̶d̶o̶w̶ ̶D̶e̶m̶o̶n̶'̶s̶ ̶D̶i̶s̶t̶r̶u̶p̶t̶i̶o̶n̶ ̶o̶r̶ ̶P̶L̶ ̶i̶l̶l̶u̶s̶i̶o̶n̶s̶ ̶e̶t̶c̶.̶.̶ 
3. Controlling the replicate with a Custom Group Binding works on any hotkey, TAB , X or anything else.
4. If you try this same example in Demo Hero mode and you select morphling, tabbing to the replicate works as intended so it is not working for me only in the actual dota maps.

EDIT: Tried this with SD,PL,ELDER TITAN,Prophet,BM and I could select summons/units with Tab Control Group so I'm assuming it's just an issue with replicate

**Comment by gdrewb-valve** [comment]
Since this only fails in one specific instance it's more likely it's a game issue than a platform issue, I'm going to pass by the larger team.

**Comment by gdrewb-valve** [comment]
The larger team thinks they have found the problem and a future update (don't have any specific timeframe) will have a fix.

**Comment by Vuccappella** [comment]
Thanks for the notification, was it a OS related issue as my friends on Windows didn't experience this ?

**Comment by gdrewb-valve** [comment]
No, it was a game code issue that could in theory affect any platform.

**Comment by Vuccappella** [comment]
Ok , thanks!
