### ISSUE TITLE
cl_dota_alt_unit_movetodirection "1" Don't work fine

### ISSUE THREAD

**Issue by ZenoNiQ** [ValveSoftware/Dota-2#749]
Can't cast spell while ALT holding 

i even try it with

```
dota_remap_alt_key "F13"
bind "ALT" "+toggle_alt_remap"
alias +toggle_alt_remap "dota_remap_alt_key ALT; +dota_unit_movetodirection"
alias -toggle_alt_remap "dota_remap_alt_key F13; -dota_unit_movetodirection"
```

but with this, all fine
`bind z +dota_unit_movetodirection`

**Comment by gdrewb-valve** [comment]
The title has the cl prefix but the text does not, which are you using (Reborn has the cl prefix)?

This also probably isn't platform-specific.

**Comment by ZenoNiQ** [comment]
Yes this is command of console ingame that valve add in october 2015 `cl_dota_alt_unit_movetodirection "1"`

**Comment by gdrewb-valve** [comment]
Right, so which one are you using?  Your scripts show the old command that Reborn doesn't support.

**Comment by ZenoNiQ** [comment]
I try all of this scripts, and if i bind on z by `bind z +dota_unit_movetodirection`, all fine i can hold "Z" and cast spells, but by this command i can't bind on ALT.

**Comment by gdrewb-valve** [comment]
This repo doesn't handle general bugs, you'll want to post at dev.dota2.com.  I'm going to close this out.
