### ISSUE TITLE
[ linux ] can't chosse dota2 reborn option to lauch

### ISSUE THREAD

**Issue by chiconcota** [ValveSoftware/Dota-2#75]
i has installed dota2 reborn, but when i click play button in steam, it don't show option window to choose dota2 reborn. when right click dota i don't see dota2 reborn option. what should i do to play dota2 reborn?
![screenshot from 2015-06-25 01 12 30](https://cloud.githubusercontent.com/assets/13038146/8338779/4647ef62-1add-11e5-8922-134085916eea.png)

**Comment by davidw-valve** [comment]
If you click Play it should bring up a dialog asking you whether you want to play Reborn. Did you try that?

And you also have Reborn selected from the DLC tab in the game's properties? Have you tried restarting Steam?

**Comment by chiconcota** [comment]
1st when i click Play it doesn't bring up a dialog asking me whether i want to play Reborn, it just play dota2,
2nd i also have Reborn selected from the DLC tab in the game's properties
3rd i not only restart the steam, but also restart my computer 
I use ubuntu 14.04 lts 
![screenshot from 2015-06-25 02 22 57](https://cloud.githubusercontent.com/assets/13038146/8339576/9a754fd0-1ae2-11e5-9a01-c09474138af0.png)
![screenshot from 2015-06-25 02 31 16](https://cloud.githubusercontent.com/assets/13038146/8339577/9a7a843c-1ae2-11e5-97a1-590584a6c252.png)

**Comment by Pharmasolin** [comment]
Don't press right click on Dota 2 in list and "Play game.." Just press blue button "Play" and you will see frame with beta dota 2.

**Comment by chiconcota** [comment]
i use 32bit OS, what should i do?

**Comment by Pharmasolin** [comment]
@chiconcota devs wrote that dota 2 reborn will be most likely without 32 support. So you will need install 64bit OS if your CPU support it.

I think this should be closed now.

**Comment by chiconcota** [comment]
Thank
