### ISSUE TITLE
Dota2 CRASH since Update 01-28, Steam Update 02-02, Yosemite 10.10.5 Security Update 2016-001, GTX970

### ISSUE THREAD

**Issue by Multisaft** [ValveSoftware/Dota-2#751]
Hi,
as mentioned in the other topics, I was asked to open my own topic for my problem.

So here again:

Mac PRO X58, Xeon X5660 at 3.4 GHz, 24Gig RAM, SSDs, GTX 970 - never any issues within the last years. I can play other games, Lightroom, Photoshop, Video Editing not a single problem. No RAM defect, Ive tested a lot within the last couple of days.
Software/Drivers: Yosemite 10.10.5, newest Security Update 2016-001, Graphics Driver: 346.02.03f05 (for the Security Update needed - just this dumb hash-sum of the Yosemite build - how stupid this is from Nvidia and Apple), Dota 2 Reborn Build: 956755, newest Steam Version.

10on10 is loading without any problems.
every other normal dota2 game - mmr, all pick, single draft, whatever, fails to load. 

Console.log output, Is it the **missing GL shader** in the first line?:

[console copy first start single draft.log.zip](https://github.com/ValveSoftware/Dota-2/files/117175/console.copy.first.start.single.draft.log.zip)

Before the last Steam Update from 02-02 I had almost the same crash report as the guy in this topic:
https://github.com/ValveSoftware/Dota-2/issues/730
Now, Dota2 just crashes without this report.

**Comment by danginsburg** [comment]
Can you please post the crash report so we can take a look?

**Comment by danginsburg** [comment]
The error "No valid vcs file found for shader gaussian_bloom_blur.vfx" is not the source of the problem, that is normal.

**Comment by Multisaft** [comment]
you have seen mit console log attachment right? or do you mean something else when you ask for the crash report?

**Comment by danginsburg** [comment]
@Multisaft Yes, you said that your crash report looked like #730.  Please post a similar crash report.  I don't see anything obvious in the log as to why it is crashing.

**Comment by Multisaft** [comment]
i dont get a crash report anymore since the last steam update from 02-02 (see my fist post below).

or is there a way to display the crash report as it is generated but not shown up?

**Comment by Multisaft** [comment]
once more the question: how can i tell dota2 to create a dumb file when it is closed out of some exception???

**Comment by Multisaft** [comment]
I have found some diagnostic Reports in /Library/Logs/DiagnosticReports/

but no actual one since the steam 02-02 update. therefore only some dota2 reports from january this year. see the examples attached, in addition some gameoverlayui, i think they are thrown by yosemite during dota2 problems? i looks lie.

[DiagnosticReports Yosemite Dota2 GTX970.zip](https://github.com/ValveSoftware/Dota-2/files/119520/DiagnosticReports.Yosemite.Dota2.GTX970.zip)

**Comment by gdrewb-valve** [comment]
The dota2 failure report from 1/28 in your zip file shows a timeout, so apparently OSX thought Reborn was hung and killed it.  There isn't enough other information to know what happened there.

If you aren't getting any other reports since 2/2 the problem most likely lies outside of Reborn.  We can't say for sure since there's no information at all but normal crashes within Reborn are caught by Reborn.  As your console logs don't show anything specific it's a mystery at this point, we'll have to see if we can repro the issue to make any progress.

**Comment by Multisaft** [comment]
Update of Dota today. I test it in some hours.

**Comment by Multisaft** [comment]
I have read in the http://dev.dota2.com/showthread.php?t=189581 thread what I maybe should provide you with:
[VCFG and VIDEO.txt Yosemite GTX970 Dota2.zip](https://github.com/ValveSoftware/Dota-2/files/120274/VCFG.and.VIDEO.txt.Yosemite.GTX970.Dota2.zip)

here is my system info from the steam client:
[Steam Client System Info.txt](https://github.com/ValveSoftware/Dota-2/files/120275/Steam.Client.System.Info.txt)

what I see: Graphics GTX970 with 2GIG Ram is wrong (4GB is correct).

I will downgrade my graphics driver to the previous version before the apple yosemite security update 2016-001. 

maybe that will help to get into matches again.
still I don't undestand why I am able to load every random 10on10 without any issues - ok I had one complete shutdown of dota2 within one 10on10 match without a dumb report, but still. not the behaviour of the normal dota2 matchmaking routine.

ah btw, under windows 10 no problems at all with any of the following game titles: dota2, cs source, dirty rally, far cry 4

**Comment by gdrewb-valve** [comment]
Thanks.  I don't see anything surprising in your information and it doesn't show any Steam failure reports so Reborn is not catching any problems itself.

**Comment by Multisaft** [comment]
sorry but that frustrates me. how can valve accept to deploy such a buggy game to one of the biggest communities in the game industry? I mean, didnt valve test their releases before each update? since month of reborn, the problems are getting worse and worse under mac os x. 

what is wrong here. and why do i need to play some sort of test rabbit which is trying to connect to new matchmaking games when I know that I'm getting banned each and every fucking time? and why can no valve crewmember reset my account when such a topic like this one is online where it is clearly visible, that THIS is not my faulT??! can anyone give a satisfying answer to this questions? I bet not!

I'm really pissed off!

**Comment by Multisaft** [comment]
and here we go, next 24h ban cause I tried to connect to a single draft with the new dota2 update from yesterday. man guys, that is not working this way. I can help you testing with my environment to sort out problems on mac os x yosemite as well as 10.11. if you ask me to, but I don't accept this matchmaking bans any longer. Can you plz address this to someone responsible for dota2 accounts in your house?!

**Comment by gdrewb-valve** [comment]
I'm sorry that you're frustrated, I know it sucks having things fail like this.  As I mentioned previously you do not need to risk bans at all, you can wait for Valve to figure things out.  This problem doesn't occur at Valve so gathering information from users helps us out but that doesn't mean you are responsible for accumulating bans to move things forward.

**Comment by Multisaft** [comment]
like Matthew I can load into my first single draft within the last weeks with his workaround leaving steam overlay in the foreground while loading a game

https://github.com/ValveSoftware/Dota-2/issues/745#issuecomment-181784609

**Comment by gdrewb-valve** [comment]
Thanks for trying it, I'm not exactly sure how we'll track down why that works but at least it gives us something to look at.

**Comment by gdrewb-valve** [comment]
Is this still happening with 7.00?
