### ISSUE TITLE
[Linux] Panorama UI fails to use localized time format

### ISSUE THREAD

**Issue by fumazu** [ValveSoftware/Dota-2#752]
In the Linux client all dates and times shown in the Panorama UI are not properly localized. I noticed this in my German version of the game but I guess it's true for all other languages. 

Dates either appear completely in the US format (mm/dd/yyyy) or are rearranged according to the translation from the Steam Translation Server, yet the months are still in English (03. February 2016). In the Windows client it's all in German as it should be.

Also all clocks are in the 12h format, whereas in the German Windows client they appear in the 24h format. Please compare the 2 Screenshots below. The first one is from Linux and the second one is from Windows.

![linux_screen](https://cloud.githubusercontent.com/assets/12823243/12836304/da6171c4-cbb7-11e5-838e-d1d57fc61824.jpg)
![win_screen](https://cloud.githubusercontent.com/assets/12823243/12836462/717ca21c-cbb9-11e5-9509-1181bb5c37c6.jpg)

**Comment by gdrewb-valve** [comment]
Is German your system locale?  If you add -set_locale_disable to your launch options does it work?

**Comment by fumazu** [comment]
That fixes it.

I'm running Ubuntu 15.10 (64 bit). My locale is:
LANG=de_DE.UTF-8
LANGUAGE=de_DE

**Comment by gdrewb-valve** [comment]
Reborn currently forces the locale to en_US to avoid some bugs on languages like Turkish so we have a bit of a conflict here.  We'll see what we can do but I don't think we'll have a fix in the short term.

**Comment by gdrewb-valve** [comment]
You're welcome to keep using -set_locale_disable if you want, and if you see any problems with it let me know here.

**Comment by fumazu** [comment]
Alright, then I will do this. Thanks for your help.

**Comment by gdrewb-valve** [comment]
Is this still a problem if you remove -set_locale_disable?

**Comment by fumazu** [comment]
Problem is still there without the launch option. 

But I just noticed that even though -set_locale_disable changes the time format from 12:00 AM/PM to 24:00, the date format remains MM/DD/YYYY instead of DD.MM.YYYY. Also, the decimal mark should be changed to a comma and digit grouping mark to a point (e.g. 7.000,56) for most european countries in the main menu and the new in-game HUD.

PS: The date format in the recent games tab that is, in the activity feed it works just fine.

**Comment by gdrewb-valve** [comment]
Thanks for trying it.

**Comment by gdrewb-valve** [comment]
The latest update should have fixed the date and time display, are you seeing any changes?

Decimal and grouping separators will not be affected (and aren't localized on any platform).

**Comment by fumazu** [comment]
Did indeed solve it. Maybe the number issue could be resolved by complying with [ISO 31-0](https://en.wikipedia.org/wiki/ISO_31-0#Numbers)? 

Anyway, thanks for putting more effort into l10n lately. :-)

**Comment by gdrewb-valve** [comment]
Number format localization should also be present in the latest updates.  Closing since the original issue is resolved.
