### ISSUE TITLE
Considering failure of the game when the game will not let you reconnect

### ISSUE THREAD

**Issue by seethersan** [ValveSoftware/Dota-2#754]
Is it too difficult to know that a player is trying to reconnect a game and THE GAME  will not let you reconnect no matter how many times you try? It's stupid to put you in low priority when the game which disconnects you from the game and not let you reconnect

**Comment by gdrewb-valve** [comment]
This repo is solely for Linux and Mac bugs.  You'll want to report this at dev.dota2.com.
