### ISSUE TITLE
[OSX] Error at launching

### ISSUE THREAD

**Issue by diegovelasquez1** [ValveSoftware/Dota-2#755]
I have this problem that after installing dota 2 and clicking on play it doesn't launch because it says this:
Error
void CTier1AppSystemDict::SetModPath(const char *)():
Application unable to load gameinfo.gi file from directory "/Users/DiegoVLibrary/Application Support/Steam/steamapps/common/dota 2 beta/game/dota"!

I'd deleted all the local content more than once but it does not fix this.

**Comment by gdrewb-valve** [comment]
Your install is corrupt, as you have guessed.  Have you validated the local content from Steam?

You should have a content_log.txt in the logs subdirectory of your Steam install (usually ~/Library/Application Support/Steam/logs), can you gist it here?

**Comment by diegovelasquez1** [comment]
Yes I'd vaidated that. Shall you make that log_txt process step by step pls? I am new on mac.

**Comment by gdrewb-valve** [comment]
Activate the Finder.
In the 'Go' menu select 'Go to Folder...'
In the location type ~/Library/Application Support/Steam/logs
That should open a folder with a bunch of text files. content_log.txt should be one of them.

Alternately in GitHub on the machine you can click on the 'Gist' option on the top of the page.  Use ~/Library/Application Support/Steam/logs/content_log.txt as the filename and create a new gist, then post the reference.

**Comment by diegovelasquez1** [comment]
https://gist.github.com/diegovelasquez1/070237b6dbddb8190035

**Comment by gdrewb-valve** [comment]
Thanks, I've passed this on to the Steam team.

**Comment by diegovelasquez1** [comment]
Thank you sir, one last question when I will have my solution or answer to this problem and where? Like a reference time and in this same link?

**Comment by gdrewb-valve** [comment]
I don't know when (or even if) the Steam team will be able to resolve your problem.  I would guess it would not be immediate.

This repo is for Dota 2 Reborn problems and this isn't a problem with Reborn itself, it's a problem with Steam not properly installing Reborn on your system.  The Steam team will take a look but at that point I no longer have visibility into it.  I'll keep this open for a bit in case the Steam team has something to say.

**Comment by gdrewb-valve** [comment]
The Steam team doesn't have anything immediate, so closing.
