### ISSUE TITLE
[Linux]Missing basic OpenGL 1.0 -> 2.0 required opengl functionality

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#756]
Hi there,

Since the latest driver update (NVIDIA) to 361.28, I can no longer launch Dota on Arch. 

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.1-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.28
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT2020

Memory:
    RAM:  7947 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  48966 Mb
    Largest Free Hard Disk Block:  19757 Mb

Installed software:

Recent Failure Reports:

```

```
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198012562328 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198012562328
Setting breakpad minidump AppID = 373300
Could not find required OpenGL entry point 'glGetError'!
Could not find required OpenGL entry point 'glActiveTexture'!
Could not find required OpenGL entry point 'glAlphaFunc'!
Could not find required OpenGL entry point 'glAttachShader'!
Could not find required OpenGL entry point 'glBegin'!
Could not find required OpenGL entry point 'glBeginQuery'!
Could not find required OpenGL entry point 'glBindAttribLocation'!
Could not find required OpenGL entry point 'glBindBuffer'!
Could not find required OpenGL entry point 'glBindTexture'!
Could not find required OpenGL entry point 'glBlendColor'!
Could not find required OpenGL entry point 'glBlendEquation'!
Could not find required OpenGL entry point 'glBlendEquationSeparate'!
Could not find required OpenGL entry point 'glBlendFunc'!
Could not find required OpenGL entry point 'glBlendFuncSeparate'!
Could not find required OpenGL entry point 'glBufferData'!
Could not find required OpenGL entry point 'glBufferSubData'!
Could not find required OpenGL entry point 'glClear'!
Could not find required OpenGL entry point 'glClearColor'!
Could not find required OpenGL entry point 'glClearDepth'!
Could not find required OpenGL entry point 'glClearStencil'!
Could not find required OpenGL entry point 'glClipPlane'!
Could not find required OpenGL entry point 'glColorMask'!
Could not find required OpenGL entry point 'glCompileShader'!
Could not find required OpenGL entry point 'glCompressedTexImage2D'!
Could not find required OpenGL entry point 'glCompressedTexSubImage2D'!
Could not find required OpenGL entry point 'glCompressedTexImage3D'!
Could not find required OpenGL entry point 'glCreateProgram'!
Could not find required OpenGL entry point 'glCreateShader'!
Could not find required OpenGL entry point 'glDeleteBuffers'!
Could not find required OpenGL entry point 'glDeleteProgram'!
Could not find required OpenGL entry point 'glDeleteQueries'!
Could not find required OpenGL entry point 'glDeleteShader'!
Could not find required OpenGL entry point 'glDeleteTextures'!
Could not find required OpenGL entry point 'glDepthFunc'!
Could not find required OpenGL entry point 'glDepthMask'!
Could not find required OpenGL entry point 'glDepthRange'!
Could not find required OpenGL entry point 'glDetachShader'!
Could not find required OpenGL entry point 'glDisable'!
Could not find required OpenGL entry point 'glDisableVertexAttribArray'!
Could not find required OpenGL entry point 'glDrawArrays'!
Could not find required OpenGL entry point 'glDrawBuffer'!
Could not find required OpenGL entry point 'glDrawBuffers'!
Could not find required OpenGL entry point 'glDrawRangeElements'!
Could not find required OpenGL entry point 'glDrawRangeElementsBaseVertex'!
Could not find required OpenGL entry point 'glDrawArraysInstanced'!
Could not find required OpenGL entry point 'glEnable'!
Could not find required OpenGL entry point 'glEnableVertexAttribArray'!
Could not find required OpenGL entry point 'glEnd'!
Could not find required OpenGL entry point 'glEndQuery'!
Could not find required OpenGL entry point 'glFinish'!
Could not find required OpenGL entry point 'glFlush'!
Could not find required OpenGL entry point 'glFrontFace'!
Could not find required OpenGL entry point 'glGenBuffers'!
Could not find required OpenGL entry point 'glGenQueries'!
Could not find required OpenGL entry point 'glGenTextures'!
Could not find required OpenGL entry point 'glGetActiveUniform'!
Could not find required OpenGL entry point 'glGetBooleanv'!
Could not find required OpenGL entry point 'glGetCompressedTexImage'!
Could not find required OpenGL entry point 'glGetDoublev'!
Could not find required OpenGL entry point 'glGetFloatv'!
Could not find required OpenGL entry point 'glGetIntegerv'!
Could not find required OpenGL entry point 'glGetStringi'!
Could not find required OpenGL entry point 'glGetProgramInfoLog'!
Could not find required OpenGL entry point 'glGetProgramiv'!
Could not find required OpenGL entry point 'glGetQueryiv'!
Could not find required OpenGL entry point 'glGetQueryObjectiv'!
Could not find required OpenGL entry point 'glGetQueryObjectuiv'!
Could not find required OpenGL entry point 'glGetShaderInfoLog'!
Could not find required OpenGL entry point 'glGetShaderiv'!
Could not find required OpenGL entry point 'glGetString'!
Could not find required OpenGL entry point 'glGetTexImage'!
Could not find required OpenGL entry point 'glGetUniformLocation'!
Could not find required OpenGL entry point 'glIsEnabled'!
Could not find required OpenGL entry point 'glIsTexture'!
Could not find required OpenGL entry point 'glLinkProgram'!
Could not find required OpenGL entry point 'glMapBuffer'!
Could not find required OpenGL entry point 'glOrtho'!
Could not find required OpenGL entry point 'glPixelStorei'!
Could not find required OpenGL entry point 'glPolygonMode'!
Could not find required OpenGL entry point 'glPolygonOffset'!
Could not find required OpenGL entry point 'glPopAttrib'!
Could not find required OpenGL entry point 'glPopClientAttrib'!
Could not find required OpenGL entry point 'glPushAttrib'!
Could not find required OpenGL entry point 'glPushClientAttrib'!
Could not find required OpenGL entry point 'glReadBuffer'!
Could not find required OpenGL entry point 'glScissor'!
Could not find required OpenGL entry point 'glShaderSource'!
Could not find required OpenGL entry point 'glStencilFunc'!
Could not find required OpenGL entry point 'glStencilMask'!
Could not find required OpenGL entry point 'glStencilOp'!
Could not find required OpenGL entry point 'glTexCoord2f'!
Could not find required OpenGL entry point 'glTexImage2D'!
Could not find required OpenGL entry point 'glTexImage3D'!
Could not find required OpenGL entry point 'glTexParameterfv'!
Could not find required OpenGL entry point 'glTexParameteri'!
Could not find required OpenGL entry point 'glTexSubImage2D'!
Could not find required OpenGL entry point 'glTexSubImage3D'!
Could not find required OpenGL entry point 'glUniform1f'!
Could not find required OpenGL entry point 'glUniform1i'!
Could not find required OpenGL entry point 'glUniform4fv'!
Could not find required OpenGL entry point 'glUnmapBuffer'!
Could not find required OpenGL entry point 'glUseProgram'!
Could not find required OpenGL entry point 'glVertex3f'!
Could not find required OpenGL entry point 'glVertexAttribPointer'!
Could not find required OpenGL entry point 'glViewport'!
Could not find required OpenGL entry point 'glEnableClientState'!
Could not find required OpenGL entry point 'glDisableClientState'!
Could not find required OpenGL entry point 'glClientActiveTexture'!
Could not find required OpenGL entry point 'glVertexPointer'!
Could not find required OpenGL entry point 'glTexCoordPointer'!
Could not find required OpenGL entry point 'glColor4sv'!
Could not find required OpenGL entry point 'glStencilOpSeparate'!
Could not find required OpenGL entry point 'glStencilFuncSeparate'!
Could not find required OpenGL entry point 'glGetTexLevelParameteriv'!
Could not find required OpenGL entry point 'glColor4f'!
Could not find required OpenGL entry point 'glBindVertexArray'!
Could not find required OpenGL entry point 'glColorMaski'!
Could not find required OpenGL entry point 'glGenVertexArrays'!
Could not find required OpenGL entry point 'glGetBooleani_v'!
Could not find required OpenGL entry point 'glGetIntegeri_v'!
Could not find required OpenGL entry point 'glDeleteVertexArrays'!
Could not find required OpenGL entry point 'glVertexAttribIPointer'!
Could not find required OpenGL entry point 'glClearBufferiv'!
Could not find required OpenGL entry point 'glClearBufferuiv'!
Could not find required OpenGL entry point 'glClearBufferfv'!
Could not find required OpenGL entry point 'glClearBufferfi'!
Could not find required OpenGL entry point 'glBindFramebuffer'!
Could not find required OpenGL entry point 'glBindRenderbuffer'!
Could not find required OpenGL entry point 'glBlitFramebuffer'!
Could not find required OpenGL entry point 'glCheckFramebufferStatus'!
Could not find required OpenGL entry point 'glDeleteFramebuffers'!
Could not find required OpenGL entry point 'glDeleteRenderbuffers'!
Could not find required OpenGL entry point 'glFramebufferRenderbuffer'!
Could not find required OpenGL entry point 'glFramebufferTexture2D'!
Could not find required OpenGL entry point 'glFramebufferTexture3D'!
Could not find required OpenGL entry point 'glFramebufferTextureLayer'!
Could not find required OpenGL entry point 'glGenerateMipmap'!
Could not find required OpenGL entry point 'glGenFramebuffers'!
Could not find required OpenGL entry point 'glGenRenderbuffers'!
Could not find required OpenGL entry point 'glGetFramebufferAttachmentParameteriv'!
Could not find required OpenGL entry point 'glRenderbufferStorage'!
Could not find required OpenGL entry point 'glRenderbufferStorageMultisample'!
Could not find required OpenGL entry point 'glMapBufferRange'!
Could not find required OpenGL entry point 'glFlushMappedBufferRange'!
Could not find required OpenGL entry point 'glCopyBufferSubData'!
Could not find required OpenGL entry point 'glDrawElementsInstancedBaseVertex'!
Could not find required OpenGL entry point 'glBindBufferBase'!
Could not find required OpenGL entry point 'glBindBufferRange'!
Could not find required OpenGL entry point 'glUniformBlockBinding'!
Could not find required OpenGL entry point 'glGetActiveUniformBlockName'!
Could not find required OpenGL entry point 'glGetUniformBlockIndex'!
Could not find required OpenGL entry point 'glGetActiveUniformsiv'!
Could not find required OpenGL entry point 'glGetUniformIndices'!
Could not find required OpenGL entry point 'glClientWaitSync'!
Could not find required OpenGL entry point 'glDeleteSync'!
Could not find required OpenGL entry point 'glFenceSync'!
Could not find required OpenGL entry point 'glGetSynciv'!
Could not find required OpenGL entry point 'glWaitSync'!
Could not find required OpenGL entry point 'glTexImage2DMultisample'!
Could not find required OpenGL entry point 'glTexImage3DMultisample'!
Could not find required OpenGL entry point 'glGetMultisamplefv'!
Could not find required OpenGL entry point 'glSampleMaski'!
Could not find required OpenGL entry point 'glBindSampler'!
Could not find required OpenGL entry point 'glDeleteSamplers'!
Could not find required OpenGL entry point 'glGenSamplers'!
Could not find required OpenGL entry point 'glGetQueryObjectui64v'!
Could not find required OpenGL entry point 'glQueryCounter'!
Could not find required OpenGL entry point 'glSamplerParameteri'!
Could not find required OpenGL entry point 'glSamplerParameterf'!
Could not find required OpenGL entry point 'glSamplerParameterfv'!
Could not find required OpenGL entry point 'glVertexAttribDivisor'!
Could not find required OpenGL entry point 'glUseProgramStages'!
Could not find required OpenGL entry point 'glActiveShaderProgram'!
Could not find required OpenGL entry point 'glCreateShaderProgramv'!
Could not find required OpenGL entry point 'glBindProgramPipeline'!
Could not find required OpenGL entry point 'glDeleteProgramPipelines'!
Could not find required OpenGL entry point 'glGenProgramPipelines'!
Could not find required OpenGL entry point 'glIsProgramPipeline'!
Could not find required OpenGL entry point 'glProgramParameteri'!
Could not find required OpenGL entry point 'glGetProgramPipelineiv'!
Could not find required OpenGL entry point 'glProgramUniform1i'!
Could not find required OpenGL entry point 'glProgramUniform2i'!
Could not find required OpenGL entry point 'glProgramUniform3i'!
Could not find required OpenGL entry point 'glProgramUniform4i'!
Could not find required OpenGL entry point 'glProgramUniform1ui'!
Could not find required OpenGL entry point 'glProgramUniform2ui'!
Could not find required OpenGL entry point 'glProgramUniform3ui'!
Could not find required OpenGL entry point 'glProgramUniform4ui'!
Could not find required OpenGL entry point 'glProgramUniform1f'!
Could not find required OpenGL entry point 'glProgramUniform2f'!
Could not find required OpenGL entry point 'glProgramUniform3f'!
Could not find required OpenGL entry point 'glProgramUniform4f'!
Could not find required OpenGL entry point 'glProgramUniform1d'!
Could not find required OpenGL entry point 'glProgramUniform2d'!
Could not find required OpenGL entry point 'glProgramUniform3d'!
Could not find required OpenGL entry point 'glProgramUniform4d'!
Could not find required OpenGL entry point 'glProgramUniform1iv'!
Could not find required OpenGL entry point 'glProgramUniform2iv'!
Could not find required OpenGL entry point 'glProgramUniform3iv'!
Could not find required OpenGL entry point 'glProgramUniform4iv'!
Could not find required OpenGL entry point 'glProgramUniform1uiv'!
Could not find required OpenGL entry point 'glProgramUniform2uiv'!
Could not find required OpenGL entry point 'glProgramUniform3uiv'!
Could not find required OpenGL entry point 'glProgramUniform4uiv'!
Could not find required OpenGL entry point 'glProgramUniform1fv'!
Could not find required OpenGL entry point 'glProgramUniform2fv'!
Could not find required OpenGL entry point 'glProgramUniform3fv'!
Could not find required OpenGL entry point 'glProgramUniform4fv'!
Could not find required OpenGL entry point 'glProgramUniform1dv'!
Could not find required OpenGL entry point 'glProgramUniform2dv'!
Could not find required OpenGL entry point 'glProgramUniform3dv'!
Could not find required OpenGL entry point 'glProgramUniform4dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2x3fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3x2fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2x4fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4x2fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3x4fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4x3fv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2x3dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3x2dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix2x4dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4x2dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix3x4dv'!
Could not find required OpenGL entry point 'glProgramUniformMatrix4x3dv'!
Could not find required OpenGL entry point 'glValidateProgramPipeline'!
Could not find required OpenGL entry point 'glGetProgramPipelineInfoLog'!
Could not find required OpenGL entry point 'glGetProgramBinary'!
Could not find required OpenGL entry point 'glProgramBinary'!
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Game removed: AppID 570 "Dota 2", ProcID 2543 
```

**Comment by gdrewb-valve** [comment]
The driver update has apparently messed up your OpenGL installation, you'll need to fix that before Reborn will run.

**Comment by zeroedout** [comment]
No it hasn't (but I can see why it looks like that)! Uncomment line 41 in dota.sh `#export __GL_THREADED_OPTIMIZATIONS=1` and bam it runs. Thanks to [/u/404AnonymousNotFound](https://www.reddit.com/r/linux_gaming/comments/44xtof/nvidia_drivers_36128_released/czuax75) for pointing it out.

**Comment by gdrewb-valve** [comment]
__GL_THREADED_OPTIMIZATIONS is checked by the driver, not Reborn.  It's odd that it makes the OpenGL exports change but that's up to the driver, there still isn't something Reborn can change about this.

**Comment by sinatosk** [comment]
They (arch linux) updated the package so that it makes use of

https://github.com/NVIDIA/libglvnd

line 41 in dota.sh for me is already uncommented but when I comment it, works

portal 2 (same result with team fortress 2 except I had to uncomment it) runs fine for me, but doesn't when "export __GL_THREADED_OPTIMIZATIONS=1" is set and errors when run

> Game
> update: AppID 620 "Portal 2", ProcID 8092, IP 0.0.0.0:0
> ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> pid 8094 != 8093, skipping destruction (fork without exec?)
> ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> SDL video target is 'x11'
> 
> SDL failed to create GL compatibility profile (whichProfile=0!
> 
> PROBLEM: You appear to have OpenGL 0.0.0, but we need at least 2.0.0!
> Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated.
> 
> Game removed: AppID 620 "Portal 2", ProcID 8092

I think this is a bug with nvidia, not reborn or arch linux because as gdrewb-valve stated... this is checked by the driver

**Comment by sinatosk** [comment]
based on what is discussed here

https://devtalk.nvidia.com/default/topic/915789/linux/-solved-361-28-gtx-580-steam-several-games-don-t-start-up/1

it sounds like you need to update your code to take into consideration for people who are using libglvnd

I've tried another application (unigine-valley) that makes use opengl with or without that environment variable set and works fine

when using the command "glxinfo" with the environment variable set... it seg faults.. but with it unset, it shows the full output so now I'm thinking you do need to update (so does glxinfo) your code

something is changing but your code doesn't know about (unigine-valley does for some reason) and boom... that's when it fail... but yes it's strange for the driver to change symbol info based on that...

I'm still thinking this is an issue with nvidia but just requires you to update your code ( not workarounds ) to work with libglvnd

**Comment by ghost** [comment]
nvidia guy on arch forum for this bug. looks like app needs to be updated.

> As a workaround for these games, threaded optimizations can be disabled in their .sh launcher:
> export __GL_THREADED_OPTIMIZATIONS=0
> 
> Alternatively, the environment variable __GLVND_DISALLOW_PATCHING will work too (and also appears to fix issues in a few other games that don't work with libglvnd yet).
> __GLVND_DISALLOW_PATCHING=1
> 
> ## 
> 
> A. Huillet
> NVIDIA Linux graphics

see also

Multiple GLX client libraries in the NVIDIA Linux driver installer package

https://devtalk.nvidia.com/default/topic/915640/unix-graphics-announcements-and-news/multiple-glx-client-libraries-in-the-nvidia-linux-driver-installer-package/

im no expert but it doesn't seem this is to be fixed at driver or os, it can be but long term its not a good idea. again, not an expert, but just what it looks like.

**Comment by timjp87** [comment]
I think what we need is confirmation from NVIDIA if __GL_THREADED_OPTIMIZATIONS will work with both non-glvnd and glvnd GLX libraries in the future. I used the 361.16 and 361.18 drivers which also had glvnd enabled by default and it didn't cause any issues with games that rely on __GL_THREADED_OPTIMIZATIONS. It only affected Civ V and KOTOR2, because these apps used OpenGL in a wrong way which was tolerated in earlier driver versions, but not anymore.

**Comment by danginsburg** [comment]
I have reached out to NVIDIA on this issue.  I will post more info once I get a response. Thanks for all the reports.

**Comment by danginsburg** [comment]
We have heard back from NVIDIA.  They have confirmed this is a driver bug impacting the libglvnd-enabled driver (nobody but Archlinux at the moment).  The driver bug will be fixed in a future release.  For now, they recommend setting __GLVND_DISALLOW_PATCHING=1 as a workaround, although also setting __GL_THREADED_OPTIMIZATIONS=0 will work (although potentially more perf impact).

**Comment by ghost** [comment]
cheers dan. nice to have an official work around until its fixed.

**Comment by fpeterschmitt** [comment]
Gentoo here, nvidia driver v361.28. __GL_THREADED_OPTIMIZATIONS=0 works so yup, nvidia's bug.

**Comment by asavah** [comment]
Can confirm this on Ubuntu 16.04 with drivers from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa (libGL seems to have glvnd symbols)  it also fails as described by the OP.
Commenting out export  __GL_THREADED_OPTIMIZATIONS=1 or adding __GLVND_DISALLOW_PATCHING=1  as @danginsburg suggested indeed fixes the issue.

**Comment by LeoVerto** [comment]
The [Arch wiki](https://wiki.archlinux.org/index.php/Steam#Issues_with_nvidia_361.28) suggests running the game with the launch option 
`__GLVND_DISALLOW_PATCHING=1 %command%`, which worked for me and seems like a more elegant solution.

**Comment by ghost** [comment]
many many thanks guys. added __GLVND_DISALLOW_PATCHING=1 %command% to launch options and can play just fine.

**Comment by martinrotter** [comment]
@Bednar87  @LeoVerto  The workaround works on my Arch box too. But I have impression that now affected games take a bit longer to start. Specifically CS:GO. But in-game performance seems to be unaffected.

**Comment by copacetic** [comment]
This fix also worked for me on 64 bit Arch. Thanks so much :+1:

**Comment by spider623** [comment]
ubuntu 16.04 with the **361.28** `__GLVND_DISALLOW_PATCHING=1 %command%` does fix it for now

**Comment by barkovv** [comment]
glad to read it. Thanks for fix.

**Comment by marcobr92** [comment]
where can i find the dota.sh and use the __GLVND_DISALLOW_PATCHING=1 %command% ?
Ubuntu 15.10 and 361.28 here

**Comment by ghost** [comment]
@marcobr92 hey, its in the same place regardless of distro really.
1. right click on dota 2. 
2. select properties.
3. local files tab.
4. browse local files.
5. game folder.
6. open dota.sh with a text editor and your good to go.

**Comment by Tele42** [comment]
really?
3. Click Select Launch Options...
4. Paste `__GLVND_DISALLOW_PATCHING=1 %command%` in the box.

**Comment by zor1984qq** [comment]
Thank you that works.

**Comment by phoerious** [comment]
I just installed a kernel update to version 4.5.0 and all of a sudden none of the suggested workarounds appear to work anymore. Can you confirm this? I'm not able to launch Dota2 anymore despite having set the suggested launch options. Also using Arch Linux.

**Comment by admshao** [comment]
Check your driver instalation again. I'm using latest kernel, i update
every sunday, and so far so good. Ofc. Using proper launch options

**Comment by phoerious** [comment]
Driver installation was okay (361.28). Reverted back to 358.16 with kernel 4.3.3 for the time being. Other games also seem to have issues with the new nvidia drivers so I archived a working driver/kernel set a while ago.

**Comment by hrzhu** [comment]
Just installed the newly released Nvidia-364, now I can start dota2 without the workaround. Don't know it's Nvidia or Valve that solves the problem though.

**Comment by Tele42** [comment]
@hrzhu the issue was with libglvnd bundled with nvidia 361.28, that hasn't changed...

**Comment by zor1984qq** [comment]
yes its fixed probably in the new beta driver so called 364 but...still it is beta and it does not exists for my Sabayon or Gentoo package base and if I trying to mix entropy packages with portage I get more problems then benefits. Thats it I just prefer to stay with Sabayon 16.04 weekly repo branch and stay out of trying to update nvidia-drivers from portage gentoo or via nvidia sh package. Cause these in most cases causes inconsistency and problems in any Linux distribution when your distro is upgraded you basicly can get no X and no desktop experience, I was not suppose to go through this again cause I am already restoring my entropy client.conf back to the normal state as I have to fix some sort of things which I edit in there to do mixing entropy and gentoo portage stuff for my Sabayon distro as it's described on their sabayon.wiki pages but it goes into crashes and problems only through one minor upgrade procedure. So I reverted back to the normal entropy stuff and never thinking of again to use any ppa, or third party repo or sh installers stuff on any Linux distribution cause it makes a lot of pain in the ass to recover whole things after you trying to do not like current distro designed to be. Anyway these new libglvnd should be more tested against for any particullary taken distribution. And Wayland session is simply not ready for daily usage, it is great that they do first beta of these driver which implements such features set like wayland and vulkan and fix few more bugs but I still have to wait their next LTS branch and when these new LTS driver dropped out to shipped in my Sabayon entropy repository. Cheers. At least we know that these mess was fixed in beta and since I am not currently use new libglvnd model I just wait for when it comes to entropy ;D

23.03.2016, 05:15, "Hairong Zhu" notifications@github.com:

**Comment by Storm-Engineer** [comment]
I just ran into this today after not launching Dota for a long time. Freshly upgraded Arch Linux, still with nvidia driver 361.28-4.

As stated above, launch option "__GLVND_DISALLOW_PATCHING=1 %command%" solved it.

I assume Arch will update to the new nvidia soon.

**Comment by gdrewb-valve** [comment]
Is there a Dota issue here?  It sounds like it's an NVIDIA issue that they've addressed?

**Comment by Tele42** [comment]
@gdrewb-valve no Dota 2 issue here, it is explicitly limited to nvidia 361.28, any distro that uses it.

**Comment by buhman** [comment]
^ Arch Linux has 364.19, which works with no intervention.

This issue should be closed, because it was fixed upstream.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
