### ISSUE TITLE
[Linux] SwitchToLoop(): Attempted to switch to unknown loop ""! (Using timedemoquit)

### ISSUE THREAD

**Issue by michaellarabel** [ValveSoftware/Dota-2#757]
Hi, I've been trying many combinations with Dota 2 to get timedemoquit working but have been blocked by this bug... Whenever using "timedemoquit" rather than "timedemo", when the test finishes I get a message box with "SwitchToLoop(): Attempted to switch to unknown loop ""!"

This is with the latest Dota 2 on Ubuntu Linux as of today, have launched the game directly via steam -applaunch, dota.sh, etc. This issue only happens when using timedemoquit but timedemo works fine and timedemoquit is still working fine seemingly in other games. Also, even if trying to run timedemoquit with a demo from the in-game console, the issue still happens at the end of the demo run.

Any ideas?

Thanks,
Michael

**Comment by gdrewb-valve** [comment]
Likely not a platform-specific issue.

**Comment by danginsburg** [comment]
If you want to automate quitting after running a demo, you can use +demo_quitafterplayback 1.  For example, I usually do something like this for a demo:
1. Grab a .dem file from a match
2. Playback a portion of the match, using a command-line such as 
   `./dota2 +fps_max 0 +cl_showfps 2 -novconsole +timedemo_start 40000 +timedemo_end 41000 +timedemo <demoname> +demo_quitafterplayback 1`

You can use timedemo_start/timedemo_end to set which portions of the demo to playback.  The results of the demo will be appended to the file game/dota/Source2Bench.csv.

**Comment by michaellarabel** [comment]
Thanks Dan, will give demo_quitafterplayback a try.

**Comment by michaellarabel** [comment]
Gave it a try with demo_quitafterplayback... At first I was getting the same "switch to unknown loop" message box as well, but I wasn't using the timedemo_start/timedemo_end arguments as I was using a short demo. However, after using timedemo_start/timedemo_end, then it began behaving correctly without this message box. So it seems the issue only happens when playing back an entire demo.

**Comment by gdrewb-valve** [comment]
This isn't platform-specific, I've passed it on to the larger team.

**Comment by gdrewb-valve** [comment]
There's apparently a fix coming for this in a future update (no specific timeframe, unfortunately).
