### ISSUE TITLE
[Linux] Play style  pentagon fails to update

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#758]
hi,
Sometimes the play style pentagon fails to update when watching different profiles.
How to reproduce:
start the game, open your profile by clicking on your name, note the shape of your play style pentagon, using the bottom left corner view a friend's profile, note the shape of his play style pentagon.
Now when you use the page back button in the top left corner you will see your own profile again, but with the pentagon from your friend. In order to see your own pentagon again you need to mouse over it.

**Comment by gdrewb-valve** [comment]
This isn't platform-specific, I've passed it on to the larger team.
