### ISSUE TITLE
Getting disconnected from US Servers

### ISSUE THREAD

**Issue by Am1rr3zA** [ValveSoftware/Dota-2#759]
recently I have problem during certain hours of time playing game, I got disconnected repeatedly from the servers and my steam goes to offline mode. I have tried to followed this instruction https://support.steampowered.com/kb_article.php?ref=1452-HCVB-6984 but it seems it's for windows user. what should I do on my mac to figure out the source of the problem?
<a href='http://postimg.org/image/grkmwj2lh/' target='_blank'><img src='http://s2.postimg.org/grkmwj2lh/Screen_Shot_2016_02_12_at_5_59_48_PM.jpg' border='0' alt="Screen Shot 2016 02 12 at 5 59 48 PM" /></a>
<a href='http://postimg.org/image/scqpf5uhn/' target='_blank'><img src='http://s9.postimg.org/scqpf5uhn/Screen_Shot_2016_02_12_at_6_01_31_PM.jpg' border='0' alt="Screen Shot 2016 02 12 at 6 01 31 PM" /></a>
<a href='http://postimg.org/image/cgwcp0zgd/' target='_blank'><img src='http://s22.postimg.org/cgwcp0zgd/Screen_Shot_2016_02_12_at_6_01_38_PM.jpg' border='0' alt="Screen Shot 2016 02 12 at 6 01 38 PM" /></a>

**Comment by gdrewb-valve** [comment]
These usually aren't platform-specific problems, I think most of that article applies to Macs also.

Post a gist of your console log here and I can pass it on to the networking guys.

**Comment by Am1rr3zA** [comment]
How can I do that?

**Comment by gdrewb-valve** [comment]
If you don't run from a console you can add -con_logfile to your launch options. That'll create a file called console.log in your Reborn install under game/dota.  On this web page click on 'Gist' at the top and then navigate to your Reborn install and the log file.

**Comment by gdrewb-valve** [comment]
We'll need more information to make progress on this.

**Comment by Am1rr3zA** [comment]
Again I need the instruction how to do it for MAC OSX?
1- how can I add -con_logfile in my launch option
2- when I go to Application/Dota 2 in terminal where should I expect to see this log file?

**Comment by gdrewb-valve** [comment]
In the Steam client open the app properties.  In the General tab there's a button with 'Set launch options...'  Click that and add -con_logfile.

The console.log file will be in the game/dota subdirectory in your Reborn files.  You can navigate there from the Steam client by again going to the app properties, selecting the Local Files tab and then clicking on 'Browse Local Files...'  Then select the game and then dota subdirectories and you should find console.log.

**Comment by Am1rr3zA** [comment]
I will upload it on Sunday after playing some games

**Comment by Am1rr3zA** [comment]
Here is the gist link to my console.log https://gist.github.com/Am1rr3zA/21986bead5d6a65ff934.

I attached the screenshot of my internet connection when I encountered this issue again.
<a href='http://postimg.org/image/ls0620wu7/' target='_blank'><img src='http://s11.postimg.org/ls0620wu7/Screen_Shot_2016_02_20_at_6_53_57_PM.jpg' border='0' alt="Screen Shot 2016 02 20 at 6 53 57 PM" /></a>

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
How many games did you try to connect in the log?  There appear to be multiple with many different reasons for disconnection.

**Comment by Am1rr3zA** [comment]
As far as I remembered this log should be generated for two games, first one was normal, second game I had connection problem.

**Comment by Am1rr3zA** [comment]
but I should mention during second game I had to disconnect reconnect many times maybe that's why it shows many different games

**Comment by gdrewb-valve** [comment]
The log shows that the user disconnected several times and shut down the game at least once so the larger team didn't see any info on actual problems that might be preventing things from working.  I'll hold this open for a bit in case they have more questions but this issue has pass out of the scope of this repro.

**Comment by Am1rr3zA** [comment]
that's exactly my problem, DOTA 2 kicked me out of game several time (because if time out) and didn't let me connect for couple of minutes then I reconnect and then kicked out again and this cycle continues. 

that's why I created this issue here because I wanna know what's wrong with USA servers. 
How or where should I contact to see what's my problem and how can I fix it?

**Comment by gdrewb-valve** [comment]
The logs do not show the game kicking, they show user actions leading to the game transitions, thus they don't help to narrow down the issue.

dev.dota2.com is the place for general bug reports.

**Comment by gdrewb-valve** [comment]
Closing as the larger team is still looking and has no immediate fix or questions.
