### ISSUE TITLE
[Linux| Console is flooded with this message

### ISSUE THREAD

**Issue by presianbg** [ValveSoftware/Dota-2#760]
My info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 23 (Twenty Three)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.5-300.fc23.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11800000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 

    Driver Version:  3.0 Mesa 11.2.0-devel
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x416
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  11459 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  105040 Mb
    Largest Free Hard Disk Block:  27022 Mb

Installed software:

Recent Failure Reports:
```

When I'm waiting for a match (loading screen, pre match) console is flooded with this yellow message
`
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2015):ResourceHandleToData(  ) failed! Falling back to error texture!
`

**Comment by gdrewb-valve** [comment]
Can you gist all of the console output prior to that message?  Also once you've done that can you verify your local installation files?

**Comment by presianbg** [comment]
@gdrewb-valve Is there a way to redirect console output to a file? As I said it's flooded and I can't see prior that message. I already verified the local files before opening this issue.

**Comment by justSQL** [comment]
Add -con_logfile to your launch options. That'll create a file called console.log in your Reborn install under game/dota.

**Comment by presianbg** [comment]
Thanks.

gist - https://gist.github.com/presianbg/8eee079f4c1d717da8a3

**Comment by gdrewb-valve** [comment]
Unfortunately the log doesn't indicate what the problem might be, we'll have to try and find a repro.

**Comment by gdrewb-valve** [comment]
Do you have shadows disabled?  Does enabling them turn off the spew?

**Comment by presianbg** [comment]
Yes, I do have shadows disabled.  Yes, enabling them seems to fix this message flood.

**Comment by gdrewb-valve** [comment]
This affects all platforms and has been fixed in the 2/23 updates.
