### ISSUE TITLE
[Ubuntu] Terrible Dota 2 Performance After Saturday 02/13

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#761]
I often stream Dota 2 with OBS and Since Saturday, with no Update in Ubuntu, Nvidia or OBS but Dota 2 only.

After those 3 minor updates.IIRC. The Game is OK while not streaming but if i start OBS the game goes ladder down in performance. Lagg. Stutter and all. From 120 steady to 80-70 fps. Usually stream with 110+ just fine and no lag.

I posted in OBS forum and i`m just checking here to see if any change was made regarding OpenGL or some paths. 

Thanks

**Comment by gdrewb-valve** [comment]
I don't believe any substantial changes have been made recently.

**Comment by admshao** [comment]
I would like to investigate a little bit more before closing this.
Thanks for fast response!

**Comment by admshao** [comment]
Ok. I still don`t know why or what triggered it between saturday and today but i`ve found those 2 links:

https://bugs.freedesktop.org/show_bug.cgi?id=92907#c6
https://obsproject.com/mantis/view.php?id=403

Gonna close this since it appears not to be Dota related but OpenGL<->OBS issue.
Thanks.
