### ISSUE TITLE
[Linux] Start Dota 2 on Vulkan API

### ISSUE THREAD

**Issue by mrdeathman** [ValveSoftware/Dota-2#764]
# 
# VULKAN INFO

Vulkan API Version: 1.0.3

NVIDIA 355.00.27

Ubuntu 15.10

LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011' !

failed to dlopen "librendersystemvulkan.so" error=librendersystemvulkan.so: cannot open shared object file: No such file or directory

**Comment by Tele42** [comment]
Duplicate of #763, the vulkan backend is not yet publically available.
