### ISSUE TITLE
[OS X] 5k resolution is unplayable

### ISSUE THREAD

**Issue by Mosher23** [ValveSoftware/Dota-2#765]
Hello,

tried to play on 5k(5120x2880) Resolution on my iMac, but because of cursor size its unplayable.
Cursor moves extremely slow and is extremely small.

im using:
iMac 27 5k 2015
i7 6700k 32Gb DDR3
AMD 395X 4gb
OS X 10.11.3

**Comment by vadi2** [comment]
Is it the same with 4k as well? This'll affect my decision to upgrade to 4k.

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
