### ISSUE TITLE
[OS X] keyboard issue

### ISSUE THREAD

**Issue by Mosher23** [ValveSoftware/Dota-2#766]
Hello again,

i have English and Ukrainian layouts on my keyboard. If in Dota 2 its switched on Ukrainian, no input will be registered in game! So its playable only if its english. Previous Dota 2 not Reborn worked fine.

pls fix this

**Comment by gdrewb-valve** [comment]
Did you select positional keybinds in the Advanced section of the bindings settings?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
