### ISSUE TITLE
[linux] exhausted memory allocator

### ISSUE THREAD

**Issue by sinatosk** [ValveSoftware/Dota-2#767]
this error has only happened once but reporting it because I have plenty of free memory

`AllocInternal();

CUtilLinkedList overflow! (exhausted memory allocator)`

this error popped up while I was watching a game

at the time dota 2 was using 1.7gb memory and 4.4gb virtual size and shared memory useage is 298.8

I have a total of 16gb ( 15.5 due to os and uefi )

machine info http://pastebin.com/yRcL5KsU

**Comment by gdrewb-valve** [comment]
We'll need to try and get a repro to determine why this is happening.

**Comment by sinatosk** [comment]
I'm not able to reproduce it either and that's including watching the same game again after restarting dota 2

**Comment by gdrewb-valve** [comment]
OK, closing for now.
