### ISSUE TITLE
Unable to launch since update, can't load module filesystem_stdio

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#768]
Had Dota open when it asked me to quit and update. Updated, now it can't launch with CAppSystemDict:Unable to load module filesystem_stdio (Dependency of application), error 2.

I've verified and re-verified the local game cache, deleted filesystem_stdio.so, nothing helps.

``````
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  4301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-78-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.63
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1080
    Primary Display Size: 20.47" x 11.42"  (23.43" diag)
                                            52.0cm x 29.0cm  (59.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7968 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104566 Mb
    Largest Free Hard Disk Block:  11574 Mb

Installed software:

Recent Failure Reports:
    ```
``````

**Comment by jazztickets** [comment]
Same.

System info: https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/91e96043413aee2db2ced46cd723c5f1c0b4ea28/gistfile1.txt

**Comment by jarcode-foss** [comment]
OSX users encountering the same issue, and so am I (arch linux user).

**Comment by Ziggitz** [comment]
After running the steam client from terminal this is what the error I'm getting on Ubuntu 14.04:

Game update: AppID 570 "Dota 2", ProcID 3695, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ziggitz/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ziggitz/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 3698 != 3697, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/ziggitz/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ziggitz/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970886956 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197970886956
Setting breakpad minidump AppID = 373300
 failed to dlopen "/home/ziggitz/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so" error=/home/ziggitz/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so: undefined symbol: g_Telemetry

**Comment by buhman** [comment]
Looks like another update was released a few minutes ago that fixed this.

**Comment by gdrewb-valve** [comment]
This should be fixed on both Mac and Linux now.
