### ISSUE TITLE
Dota client keeps crashing after latest update (Feb 24 2016)

### ISSUE THREAD

**Issue by ThiemNguyen** [ValveSoftware/Dota-2#769]
After upgrading to the latest version today, I'm unable to play because the client keeps crashing after loading screen.
No crash reports were created.

System information:
Mac OSX El Capitan
OS version: 10.11.3 (15D21)

![screen shot 2016-02-24 at 11 36 00 am](https://cloud.githubusercontent.com/assets/883217/13275756/d5cfe2d4-daea-11e5-8e08-d2567649454b.png)

**Comment by eric-sofisoftwarellc** [comment]
Same. Dozens of reports on reddit of crash on launch both osx and linux clients.

**Comment by Gabrielmtn** [comment]
![image](https://cloud.githubusercontent.com/assets/1121921/13275935/46d917b0-da88-11e5-98a6-fd6e5ce0ff5f.png)

![image](https://cloud.githubusercontent.com/assets/1121921/13275945/5d7096ec-da88-11e5-8d60-ee58d268a4ef.png)

**Comment by baizhima** [comment]
me 2!

**Comment by mrdeathman** [comment]
I confirm.
OS: Ubuntu 15.10 x64

**Comment by erween** [comment]
In my mac crash too..
How to fix it ???

![screen shot 2016-02-24 at 12 12 59 pm](https://cloud.githubusercontent.com/assets/3007014/13276281/4382ccba-daf0-11e5-970e-0daf2f735dcf.png)

**Comment by lianguage** [comment]
I updated recently and can't start the game.
On ubuntu 14.04, I get the following error messages before the game even starts:
![dota2error1](https://cloud.githubusercontent.com/assets/8604697/13276345/6fdf1eea-db12-11e5-869a-5473ca4e6c4d.png)
![dota2error2](https://cloud.githubusercontent.com/assets/8604697/13276347/735de524-db12-11e5-87e0-0f6164aca2a9.png)

I follow the first message's advice and it doesn't help

**Comment by mrdeathman** [comment]
fixed

**Comment by gdrewb-valve** [comment]
This should be fixed on both Mac and Linux now.
