### ISSUE TITLE
Matchmaking does not complete on us-east and us-west

### ISSUE THREAD

**Issue by jakgregg** [ValveSoftware/Dota-2#770]
Game wait times are growing exceedingly long, and many people on Reddit are expressing the same issues as wait times are infinite and matches cannot be found.

I believe this is affecting Windows systems, as all the Mac and Linux clients are crashing before startup.

Could you please look into this? I think no one can matchmake right now.

Edit: I noticed that the most recent changes to the win64 packages was that these two lines changed (acquired from https://steamdb.info/depot/373303/history/):

> game/dota/bin/win64/client.dll
> game/dota/bin/win64/server.dll

Would this be where the issue is coming from?

**Comment by gdrewb-valve** [comment]
This should be fixed.

For the future you'll want to post general issues at dev.dota2.com.
