### ISSUE TITLE
how can i fix it . please suggest me about play Dota2 on Mac

### ISSUE THREAD

**Issue by maziyahu** [ValveSoftware/Dota-2#771]
i found this happen ,as a photo attached, when i finished download Dota2 from steam.
what can i do with it
please feel i free to contract me back anytime. Please inform me anything i need to do solve the problem

Thank you
this is my email : j.santatiwut@gmail.com
![12242965_1146531828698871_1027478584_o](https://cloud.githubusercontent.com/assets/17453329/13286955/f6a60aaa-db36-11e5-824a-5801c333292b.jpg)

**Comment by gdrewb-valve** [comment]
Have you verified your local file cache from Steam?  From the App properties in Steam look in Local Files and there's a button to verify.

**Comment by maziyahu** [comment]
Thank you for your suggest
 i can resolve it now

**Comment by gdrewb-valve** [comment]
This should be fixed by today's update.
