### ISSUE TITLE
Can't Watch Secret x CDEC.

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#772]
I`m able to watch any other dota tv game. Even EHOME x MVP was just fine both games...But can`t watch any of secret x cdec games.

gist of console.log -> https://gist.github.com/admshao/fe08b4e93d2fd921b921

**Comment by gdrewb-valve** [comment]
Unlikely to be platform-specific, I've asked the larger team about this.

**Comment by gdrewb-valve** [comment]
The larger team didn't have any suggestions.  Have you had problems watching any other matches?

**Comment by gdrewb-valve** [comment]
Closing pending more information.
