### ISSUE TITLE
[OS X] SUPER DUPER LOW FPS

### ISSUE THREAD

**Issue by az789456** [ValveSoftware/Dota-2#774]
**The Problem**: Start the game, everything is fine and dandy client runs smoothly. Start of the match getting about 100 FPS or so ~ 2 mins into the game, get about 60 FPS then a team fight rolls around say 15-20 mins later and all sh*t breaks loose, everything is choppy, blocky animations. Now getting about 12 FPS. (literally unplayable) Then after the team fight I'm getting maximum 30-35 FPS at best and it stays that way throughout until I close the client. Nothing but Dota 2 running. This is a reoccurring problem but hasn't been this bad. Normally I would be able to play with ~40 FPS but the team fights just takes it down considerably.

_No external devices plugged in except a laptop mice and headphones plus the power supply._

**My Computer Specifications**: 
- MacBook Pro (Retina, 15-inch, Early 2013) running OS X El Capitan (Version 10.11.3)
- 2.4 GHz Intel Core i7
- 8 GB 1600 MHz DDR3
- NVIDIA GeForce GT 650M 1024 MB
- 250GB Flash Storage with ~ 110GB Free

**My Dota 2 Settings**: "-console -gl -high" <--- in my launch options
![screen shot 2016-02-28 at 1 34 02 am](https://cloud.githubusercontent.com/assets/8680453/13377915/1a70614a-ddbe-11e5-819d-13bbba2ca872.png)

Thanks for reading guys. Looking forward to the responses!

**Comment by NekR** [comment]
@az789456 it's common problem. I mean, all games on OS X get FPS drops in one or another situation. Even on latest Macbook Pro.

**Comment by ghost** [comment]
Same here

I just stopped to play on OSX, i only play on my linux partition for now, i hope this will be fixed asap

OSX 10.11.4
NVIDIA GTX 960 - Web Driver - 346.03.06b01

**Comment by lurgoyf** [comment]
Hi, I am experiencing the same problem. It was fine 2 days ago until yesterday. 
Gameplay is choppy even when watching other ppl's game. It is unplayable especially during team fights. 
however my fps remains 60-80fps at all times but its so lagging. All I see is frame by frame.

*running on iMac 2011
Mac Os El Capitan

**Comment by ghost** [comment]
Ok i tested again today, things looks a bit better compared to last time i tested (1-2 weeks ago)

But it's still not how it was before, FPS isn't stable, i tested with and without vsync, with all settings, and with minimal one

There are some fps drop from 100 down to 40 in few seconds for no reason, there is something wrong

Displaying the big menu from ingame makes the game to freeze for few seconds (1-3)

I hope you are not using scaleform for your UI, it was always buggy in every games i played that used it

**Comment by danginsburg** [comment]
Would one of you mind trying Intel Power Gadget (https://software.intel.com/en-us/articles/intel-power-gadget-20) and reporting back if the clock frequency is correlated with framerate drops?

**Comment by az789456** [comment]
First of all, thanks for everyone taking the time to respond and giving me feedback.

@danginsburg I could do that certainly. I've installed the app, but the "Log" is not showing onto my selected destination folder (Save logs to).

**Comment by az789456** [comment]
I think it might actually be the dedicated graphics card on the macbook that might be causing the problem.

I was playing Dota 2 with only my integrated graphics card using a program called, **_gfxCardstatus_** I was getting a good stable 60 FPS but with render quality set to 40%(lowest). I also had a program called **_smcFanControl_** (fan settings at maximum) running in the background.

PS. integrated graphics is called: Intel HD Graphics 4000
PPS. running the game on the dedicated graphics card gives me the same problem as posted ~ 30FPS (same settings)
PPPS. regarding the dedicated graphics card, it might have something to do with the PSU

**Comment by az789456** [comment]
@danginsburg Indeed it is. After experimenting with the program. I am now fully aware my computer can run dota 2. The fact of the matter is after some time, "Power" graph starts to decrease and as a result frequency decreases. Do you have a fix to this?

<img width="1440" alt="screen shot 2016-03-06 at 9 36 50 am" src="https://cloud.githubusercontent.com/assets/8680453/13554829/f0ba3caa-e37f-11e5-8ec3-e24a5bc98dd9.png">

**Comment by az789456** [comment]
For anyone having the same problems as me, this forum post gave me some insight to my problem. Although not entirely the same specs, the exact same problems. 

http://forum.notebookreview.com/threads/macbook-pro-retina-m370x-throttling-fixed.783317/

**Comment by gdrewb-valve** [comment]
Interesting and unfortunate that you're hitting thermal throttling.  As this isn't a Reborn issue we'll probably end up closing this out.

**Comment by danginsburg** [comment]
@az789456 Thanks for investigating, this is what I guessed the problem was.  Unfortunately, as @gdrewb-valve said we don't have any control over this.  In Linux you can use things like cpufreq-utils and disabling of x86_pkg_temp_thermal to disable clock frequency throttling.  I do this when I'm doing Dota 2 performance work to get stable framerates.  I've never found a way to force this on Mac OS X though.  Sorry we don't have a better answer.
