### ISSUE TITLE
game client always disconnect  offline mode 

### ISSUE THREAD

**Issue by lynx29** [ValveSoftware/Dota-2#777]
When playing the game client always disconnect offline mode then would reconnect again to game coordinator making ping spikes and game lag. 
this is my console log.
[console.log.zip](https://github.com/ValveSoftware/Dota-2/files/163112/console.log.zip)

[system information.zip](https://github.com/ValveSoftware/Dota-2/files/163110/system.information.zip)

**Comment by gdrewb-valve** [comment]
You mean that Steam itself is going into offline mode?  The logs do appear to show that your logon state is toggling back and forth.  You'll want to report this on steam-for-linux here instead of Reborn.

**Comment by lynx29** [comment]
Thank you for your quick reply. It is only the dota 2 reborn game client, I am  looking at when this happen it goes offline mode then reconnecting to game coordinator. As you said that my logon state keep toggling back and forth. I would reset steam. I try to report this to steam on linux as it seem the problem is not on reborn client.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
