### ISSUE TITLE
[Linux] Fails to connect to game, shows connecting.

### ISSUE THREAD

**Issue by rdpascua** [ValveSoftware/Dota-2#778]
Whenever we play party queue using the same os which is (Ubuntu 14.04.01) , we encounter this weird issue that shows connecting during the loading time. 

Let me know how can I help or what should I do to debug

**Comment by karlimlengco** [comment]
+1

**Comment by gdrewb-valve** [comment]
Please post your console logs.  Also did this just start happening or has it always happened?  What things changed on your system when it started happening?

**Comment by rdpascua** [comment]
I don't remember when exactly this happens, but from time to time like 50/50 chance of getting this issue. I don't encounter this issue during the reborn patch. I think this issue happened after the reborn patch.

let me get a log, how can I dump the log anyway?

**Comment by gdrewb-valve** [comment]
Add -con_logfile to your launch options.  That'll put console output into <Reborn install>/game/dota/console.log

Click on the 'Gist' option above to add that file here without a bug copy/paste.

**Comment by rdpascua** [comment]
heres the log:
https://gist.github.com/rdpascua/1a1c29711f7f85420d50

**Comment by gdrewb-valve** [comment]
Your log shows what appear to be random networking errors on your machine.  For example:

Invalid JSON data on line 1: Unexpected character 0x3c ('<')
Failed to fetch network config from CDN.  Steam datagram service will not be available!
Check your Internet connection, and make sure your browser can access the following URL:
   http://media.steampowered.com/apps/sdr/network_config.json

This is a regular http request that isn't working.  It's hard to say what's going on with your system that's causing the issue so I don't have much specific advice beyond check your networking.  Also you'll want to verify your local files via the Steam client app properties for Reborn in case networking errors during downloading left bad files on your disk.

This doesn't appear to be a Linux/Mac problem.  We'll hold it open for a while but I don't know that there's much more the porting team can do in this situation.

**Comment by rdpascua** [comment]
In attempt to resolve the issue , I tried emulating the server response seems working. , hovewer there is no cache data for network config json, i've read that this file is cached each time the client launches.
