### ISSUE TITLE
[Linux] Profile activity feed tab is empty

### ISSUE THREAD

**Issue by fumazu** [ValveSoftware/Dota-2#779]
**OS:** Ubuntu 15.10
**Client language:** German

**Problem:** The activity feed tab in the profile doesn't display any messages even though the feed preview on the home screen shows feed activity.
**Expected behavior:** Feed tab in the profile shows all feed messages while the home screen preview displays the three most recent.

![feed_home](https://cloud.githubusercontent.com/assets/12823243/13655072/0c5be582-e65d-11e5-93f5-1e509df96392.jpg)
![profile_feed](https://cloud.githubusercontent.com/assets/12823243/13655073/0f199dfa-e65d-11e5-9291-fe73fd870b1c.jpg)

**Comment by gdrewb-valve** [comment]
I think this happens on Windows also, checking with the larger team.

**Comment by gdrewb-valve** [comment]
The response from the larger team is that they two areas show slightly different information (one is only you and one has yours friends too) so what you're seeing is expected.

**Comment by fumazu** [comment]
Oh I see, thanks. I guess my Dota life is not very interesting then. ;-)
