### ISSUE TITLE
[Linux] After today update, Dota 2 quit to desktop just after start

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#780]
[edit] OK. It  working now. I verified files dota, and some were wrong. Steam downloaded several files. I run dota2 and it crash again. I verified again and again bad files. Downloaded files again. Now it starts well.

Topic for close.

Like in title. After today patch, my Dota 2 start fine but after few seconds (I see only dota2 logo) game quit to desktop.

I have steam logs:

 Thu Mar 10 12:46:49 2016 GMT: file ''/tmp/dumps/crash_20160310134628_1.dmp'', upload yes: ''CrashID=bp-c70e3b87-6309-4081-aab2-6d5cf2160310''
    Thu Mar 10 12:48:21 2016 GMT: file ''/tmp/dumps/crash_20160310134811_1.dmp'', upload yes: ''Discarded=1''

Log from crash:
https://www.dropbox.com/s/r8d83v289culnzg/crash_20160310134628_1.dmp?dl=0
https://www.dropbox.com/s/djglvetz4c8xx79/crash_20160310134811_1.dmp?dl=0
https://www.dropbox.com/s/88rj1wmrx89ifdu/crash_20160310134916_1.dmp?dl=0

My steam spec: https://gist.github.com/xpris/a049e89a6dab694b08f2

Quick info:
Yesterday, game work fine.
Today after this patch, quit to desktop after I see dota2 logo
I use Linux Mageia 5 x64 KDE - later this day I try on my notebook with Ubuntu 15.10
I use Radeon HD 5850 with Catalyst 15.9/fglrx

EDIT: I start steam in console and next run dota2. I get error in console log:

"/media/win_e/Steam/steamapps/common/dota 2 beta/game/dota.sh: linia 104:  8344 Naruszenie ochrony pamięci   ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@""

Full log from console: http://paste.ubuntu.com/15341058/

**Comment by gdrewb-valve** [comment]
Thanks, closing.
