### ISSUE TITLE
Cannot start game from within Steam

### ISSUE THREAD

**Issue by insunaa** [ValveSoftware/Dota-2#781]
I can't start DotA 2 from the steam GUI. Same as Borderlands 2. When I hit "Play" in Steam, my status changes for a fraction of a second to "In Game[...]" and then switches back. The console spits out tons of libgl / LD_PRELOAD errors.
When I start the dota2 binary from console however, everything works just fine.
I'm running Arch Linux: x86_64 Linux 4.4.3-1-ARCH and I'm using the latest MESA drivers
This problem does not exist, when I play Counter Strike: Global Offensive. CS:GO works (almost) flawlessly.

**Comment by insunaa** [comment]
Here's the entire log from the console

> Game update: AppID 570 "Dota 2", ProcID 7946, IP 0.0.0.0:0
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> pid 7948 != 7947, skipping destruction (fork without exec?)
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Using breakpad crash handler
> Setting breakpad minidump AppID = 570
> Forcing breakpad minidump interfaces to load
> Looking up breakpad interfaces from steamclient
> Calling BreakpadMiniDumpSystemInit
> Looking up breakpad interfaces from steamclient
> Calling BreakpadMiniDumpSystemInit
> Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198020147165 [API loaded yes]
> Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198020147165
> Setting breakpad minidump AppID = 373300
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/tls/radeonsi_dri.so
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/radeonsi_dri.so
> libGL: dlopen /usr/lib32/xorg/modules/dri/radeonsi_dri.so failed (/usr/lib32/xorg/modules/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS32)
> libGL error: unable to load driver: radeonsi_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: radeonsi
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/tls/swrast_dri.so
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/swrast_dri.so
> libGL: dlopen /usr/lib32/xorg/modules/dri/swrast_dri.so failed (/usr/lib32/xorg/modules/dri/swrast_dri.so: wrong ELF class: ELFCLASS32)
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> crash_20160310190108_1.dmp[7957]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20160310190108_1.dmp
> /home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104:  7950 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
> Game removed: AppID 570 "Dota 2", ProcID 7950 
> crash_20160310190108_1.dmp[7957]: Finished uploading minidump (out-of-process): success = yes
> crash_20160310190108_1.dmp[7957]: response: Discarded=1
> crash_20160310190108_1.dmp[7957]: file ''/tmp/dumps/crash_20160310190108_1.dmp'', upload yes: ''Discarded=1''
> pid 7957 != 7956, skipping destruction (fork without exec?)

**Comment by insunaa** [comment]
And here, for contrast, how it looks when I start the game from console and then close the game from it's GUI:

> Using breakpad crash handler
> Setting breakpad minidump AppID = 570
> Forcing breakpad minidump interfaces to load
> Looking up breakpad interfaces from steamclient
> Calling BreakpadMiniDumpSystemInit
> Looking up breakpad interfaces from steamclient
> Calling BreakpadMiniDumpSystemInit
> Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198020147165 [API loaded yes]
> Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198020147165
> Setting breakpad minidump AppID = 373300
> Attempting to create OpenGL context: v3.3 (Core profile)...success.
> Attempting to create OpenGL context: v3.3 (Core profile)...success.
> DumpContextInfo: OpenGL vendor X.Org
> DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD HAWAII (DRM 2.43.0, LLVM 3.7.1)
> DumpContextInfo: Using OpenGL context version 4.1
> DumpContextInfo: Context supports GLSL version 4.10
> Fontconfig warning: "/home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
> Fontconfig warning: "/home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
> Video playback error (1): Failed to initialize manifest
> Video playback error (1): Failed to initialize manifest
> ../common/video/videoplayermanager.cpp (208) : Assertion Failed: m_vecAllPlayers.Count() == 0
> ../common/video/videoplayermanager.cpp (208) : Assertion Failed: m_vecAllPlayers.Count() == 0

**Comment by Tele42** [comment]
the key detail here is: 

```
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
```

You have some workarounds for 32 bit opengl, but not 64 bit opengl. Go take a look at https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues again and apply what you need for the steam runtime to not interfere with 64 bit mesa.

**Comment by insunaa** [comment]
I know these and I've tried using both workarounds and neither is working.

**Comment by gdrewb-valve** [comment]
This is a Steam runtime issue, you'll want to post this in steam-for-linux.
