### ISSUE TITLE
Casting overpower on Ursa causes attack speed to display bogus number

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#783]
Does not happen on windows.

![20160310171425_1](https://cloud.githubusercontent.com/assets/425930/13690021/5df4996a-e6ea-11e5-8908-b17bf5caf650.jpg)

System info: https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/cf6df6481fb5df0cb8485f1a502772fa74ecb643/gistfile1.txt

**Comment by gdrewb-valve** [comment]
This turned out to not be platform-related but a fix will be coming in a future update.

**Comment by gdrewb-valve** [comment]
This is fixed in the Spring Cleaning update.
