### ISSUE TITLE
Dota Ubuntu 14.04 LoadSystemDependencies(): AppSystemDict: Error in Connect() of interface 'GameUI011'!

### ISSUE THREAD

**Issue by traflaw26** [ValveSoftware/Dota-2#784]
Hello, i faced same problem like thread before this in here https://github.com/ValveSoftware/Dota-2/issues/267 but i tried to do same way to fix that issue using 'steam -- reset' but it doesnt work, please help :( i newbie too at ubuntu so please show me detail to do

sorry for my bad english

![screenshot from 2016-03-12 17 47 07](https://cloud.githubusercontent.com/assets/17796911/13722527/430107f0-e87b-11e5-9748-86a10d19ced3.png)

edit: So it's done after took a while xD, what i did is edit my steam conf at 'sudo nano /etc/ld.so.conf.d/steam.conf' and you put line inside like this

> /usr/lib32
> /usr/lib/i386-linux-gnu/mesa

and then save using ctrl+o then exit after that use this command 'sudo ldconfig' after that update/upgrade your ubuntu using this 'sudo apt-get update && sudo apt-get -y upgrade' then i typed 'sudo apt-get dist-upgrade' and then i 'sudo steam -- reset' then my whole steam resetting including my Dota and i highly recommended you install Dota 2 through downloading rather than restore and voila! my Dota running well now

But now i have issue like this

> OpenGL GLX context is not using direct rendering, which may cause performance problems.
> For more information visit https://support.steampowered.com/kb_article.php?ref=9938-EYZB-7457.

i got this solution in here http://steamcommunity.com/app/221410/discussions/5/828939163894026239?l=german post number 4 

Thank You ! hope this post can help you

**Comment by gdrewb-valve** [comment]
Check through the steam-for-linux repo and you'll see a number of similar things about OpenGL.

**Comment by traflaw26** [comment]
@gdrewb-valve but i face same problem again, after i rebooted and problem show up again can you help me?

**Comment by gdrewb-valve** [comment]
Did you read through the steam-for-linux repo?  Go there and search for "direct rendering".

**Comment by traflaw26** [comment]
@gdrewb-valve not that problem, i mean with first problem the " LoadSystemDependencies(): AppSystemDict: Error in Connect() of interface 'GameUI011'! "

**Comment by gdrewb-valve** [comment]
That means your system is not set up to run Dota 2.  If you do search here you'll find several issues covering the same thing.

**Comment by traflaw26** [comment]
@gdrewb-valve what do you mean by 'my system is not set up'? can you show how to set up? because i already tried many ways to make dota work fine, but not even single thing was worked for me :(

**Comment by gdrewb-valve** [comment]
Try reading some of the similar issues here, like #35, #105 and #267.

This repo is for reporting bugs only so there isn't a large community of people here to help with system configuration advice.  You might have more luck in a different forum, like reddit or such.

**Comment by Tele42** [comment]
@traflaw26, how about filling in some missing details by including your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information. As this report stands, there is nothing actionable due to lack of information. Also, please include the terminal output from starting Dota 2, which you can get by closing steam, then running steam from a terminal, or open a terminal and running `tail -f /tmp/dumps/<username>_stdout.txt`.

**Comment by gdrewb-valve** [comment]
Were you able to get things running?
