### ISSUE TITLE
[OSX] Game crashes when match is ready

### ISSUE THREAD

**Issue by pomali** [ValveSoftware/Dota-2#785]
How to reproduce:
Start finding match, cmd+tab out of Dota2 (to Chrome/Steam/Spotify), when match is found, notification is created but game crashes. It results in failing to ready up (or it automatically declines match). 
(It does not happen every time, but I experienced it already 2 times in 6 games and it is annoying to lose ~5 minutes of life because of bug in game)

Expected behaviour:
When match is found, user gets notified and game doesn't crash.

MacBook Pro Mid 2009, OS X Yosemite 10.10.5

**Comment by Tele42** [comment]
If you are able, attach a relevant crash report to this issue. If you are copy and pasting it in, please use <a href="https://gist.github.com/">gist</a>.

**Comment by pomali** [comment]
Where can I get crash report? 

Only thing I found was 

```
12/03/16 15:26:50,000 kernel[0]: Sandbox: dota2(88717) System Policy: deny file-write-unlink /Users/pom/Library/Saved Application State/com.dota2.savedState/restorecount.plist
```

in Utilities/Console.app

**Comment by gdrewb-valve** [comment]
There may be some listed in the Steam system information.

**Comment by gdrewb-valve** [comment]
Did you find any failure reports in the Steam information, or anywhere else?

**Comment by pomali** [comment]
It didn't happen since and there is nothing in Steam System Information. If it will happen again I will post logs here.

**Comment by gdrewb-valve** [comment]
Thanks, closing for now.
