### ISSUE TITLE
Over CPU usage Macbook Air

### ISSUE THREAD

**Issue by tell10glu** [ValveSoftware/Dota-2#786]
I am having trouble playing Dota 2 on macbook air. In game sometimes spike happens and ping goes around 1k or more, after that ping stays between at 300-500. When i look ram and cpu usage on activity monitor , Cpu usage is more than %100 and gameoverlayui is not responding as the image shown below. 
[http://s23.postimg.org/7oq4ds297/Screen_Shot_2016_03_14_at_00_32_36.png](url)
System Overview :
Operating System : OSX el capitan
Processor : 1,3 GHz Intel Core i5
Memory : 4 GB 1600 MHz DDR3
Graphics : Intel HD Graphics 5000 1536 MB

**Comment by NekR** [comment]
Dota 2 on OS X has fps drops in some places of a map. So far I know only
one such place -- fountain. Dota literally its your Mac then you are
staying at fountain, fans working at max, fps drops, etc.

Where on a map you had those problems?

**Comment by tell10glu** [comment]
Not some places, it happens after almost 30 mins in game. Fps drop is not problem actually, ping goes crazy then stays at 300-500 range.

**Comment by gdrewb-valve** [comment]
The image link didn't work, but if you're sure that gameoverlayui is having problems you'll want to post in the steam-for-linux repo as that's injected by Steam for the Steam overlay.  You can also try disabling the community overlay in Steam and see if that helps.

**Comment by gdrewb-valve** [comment]
Did changing your overlay settings help?

**Comment by tell10glu** [comment]
No changing overlay settings didn't help. I am not sure what the problem is but when i see process in activity monitor, gameoverlayui is not responding.For example if i see activity monitor right now dota 2 takes %130 CPU and gameoverlayui is not responding and takes %1.4 CPU as well. I also set my startup configurations as -novid -high -console but i am not sure it helps or not.
