### ISSUE TITLE
Mouse Issue

### ISSUE THREAD

**Issue by whysoseo** [ValveSoftware/Dota-2#787]
I am currently on OS X El Capitan 10.11.3 using a 27 inch iMac from Late 2013. My specs are: 3.2 GHz Intel Core i5, 8GB of DDR3, and NVIDIA GeForce GT 755M 1024 MB, along with the integrated video card from the i5.
I have an issue with Dota 2 and my mouse, and just about any other Valve game. I have to double click for anything I do, and many times even the double click doesn't work. From what I've been observing, clicking once moves the mouse location to the point, and clicking once more does the actual action of clicking. This happens in the menu and in-game. What can I do to fix it? So far, I've tried CMD + H, and ALT-TAB, and tried all display modes. Mouse works perfectly fine in Overlay and outside of Dota 2/CSGO.

**Comment by gdrewb-valve** [comment]
We had some reports of this a while back but nothing recently and we don't have any repro so we don't have a way to make progress.  We'll keep this open and see if we can get more info.

**Comment by whysoseo** [comment]
This issue was fixed after the most recent update, thank you.
