### ISSUE TITLE
[Linux/radeonsi] Ingame gui only renders on half of the screen

### ISSUE THREAD

**Issue by DarkDefender** [ValveSoftware/Dota-2#79]
Todays (Jun 25) update solved the radeonsi main menu rendering problems for me on my 290x.
However, with mesa from git (checkout from Jun 25, 02:10 CEST) the ingame GUI is not correctly rendered:
![2015-06-25-030304_1920x1200_scrot](https://cloud.githubusercontent.com/assets/312503/8344877/7ce950ba-1ae7-11e5-941d-12b083e9d4c8.png)
![2015-06-25-030335_1920x1200_scrot](https://cloud.githubusercontent.com/assets/312503/8344878/7ceb702a-1ae7-11e5-9ff9-7b3f75e069ce.png)

There seems to be some z fighting issue with some of the ground terrain textures also as they flicker.

I had this problem before the reborn update today, but I thought that it were related to the main menu stuff #1. Because it's still a problem now, I guess this was not the case. 

I don't see anything suspicious being printed to the terminal either. Is there anything I can do to provide better debug info?

@sarnex do you also have this issue?

**Comment by danginsburg** [comment]
I tested on Radeon 7950 this morning with mesa 10.3.2 and did not see any of these issues.  @imirkin what about you, are you seeing this issue?

**Comment by imirkin** [comment]
@danginsburg nope, just testing today's update on a GF108 here with nouveau... with GL 4.1 enabled. Tried various quality levels, all seems to render fine [note that I don't normally play the game, but nothing _obviously_ broken]. Although I'm a bit surprised that it looks the same with GL4.1 (i.e. with tess) and without -- perhaps tess doesn't really get used.

As another caveat to my testing, the GF108 is slow to begin with, and nouveau can't reclock, so it's double-slow, so I've mostly been playing on the lowest quality setting which nets me playable speeds.

This could be a SI (7950) vs CIK (290x) difference though. But again, I'm just a nouveau guy :)

**Comment by kcazyz** [comment]
I am having a similar issue, which was marked as closed incorrectly I believe. The thread with more details is ValveSoftware/Dota-2#1791

**Comment by sarnex** [comment]
@DarkDefender Hi, I don't experience this issue. I'm using mesa git.

Sorry I can't be of more help.

**Comment by DarkDefender** [comment]
Because this seems to be a driver issue, I have filed a bugticket here:
https://bugs.freedesktop.org/show_bug.cgi?id=91107

**Comment by ChristophHaag** [comment]
For me the right side is broken, but everything flickers, latest mesa git too.

Video: https://www.youtube.com/watch?v=vPxaC_pFD-o

apitrace: http://haagch.frickel.club/files/dota2.trace.xz

The trace seems to be problematic judging by the messages glretrace spits out, but it renders fine on intel and is broken on radeonsi.

```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wimbledon XT [Radeon HD 7970M] (rev ff)
```

**Comment by danginsburg** [comment]
I have this repro'd on mesa 10.3.2 Radeon HD 7950 Ubuntu 14.10 x86_64.  The fact that the apitrace plays correctly on intel but not radeonsi definitely points to a driver bug.  @ChristophHaag Can you please add your trace file with your additional information to https://bugs.freedesktop.org/show_bug.cgi?id=91107  .  This should give them a very easy way to repro.  Thanks.

**Comment by danginsburg** [comment]
This bug is fixed by the same resolution as #4.  It was a problem with relying on undefined behavior when GL_CLIP_DISTANCE0 is enabled and the shader does not write gl_ClipDistance[0].  Fix will be in the next update.

**Comment by DarkDefender** [comment]
The GUI issues seems to be gone after the recent update. But I still have flickering on the mini map. If I enable normals in the video settings, some parts of the ground also flickers.

To demonstrate the issue I have uploaded two avi files here:
https://github.com/DarkDefender/dota2_reborn_issue
Notice that the mini map flickers in both cases. I have tried to disable every video option to see if that helps, but it does not.

I also had the health bars above units flicker and become corrupted sometimes.

Should I open a new issue or shall we continue in this one?

**Comment by HarlemSquirrel** [comment]
The half rendering issue is fixed for me too!

**Comment by gdrewb-valve** [comment]
Please open a new issue for the minimap flickering just to keep things clear.

**Comment by ChristophHaag** [comment]
The ingame UI works now, but the steam overlay still has this problem.

**Comment by gdrewb-valve** [comment]
@ChristophHaag, you should report that on the Steam forums.
