### ISSUE TITLE
[MAC] Disconnected from server/timed out after about a minute after hero picks load ingame 

### ISSUE THREAD

**Issue by okamid** [ValveSoftware/Dota-2#790]
Note: Recurring problem since the original Reborn update was officially ported. Ping is always ~50, fps  ~50, and 0% packet loss during the time in server. Game stutters before disconnecting. Game stutters in both local host servers (even with 0 ping and fps ~60) and regular servers. 

System Information
Processor Information:
    Model:  MacBookPro9,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.2 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.22" x 7.01"  (13.23" diag)
                                        28.5cm x 17.8cm  (33.6cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  4096 Mb

Console Log

Writing configuration for slot 0
Saving lobby data to disk.
WriteSteamRemoteStorageFileAsync( "scripts/dota_local_disk_lobby_data.txt" ) -> at 163.088
Telling Steam not to update the app for the next 900 seconds
LOBBY STATE RUN: lobby 24462368505515704: Player AccountID 126013601 connecting to MatchID 2225225559 at ServerID [A:1:1297744903:6511] =[A:1:1297744903:6511]
SwitchToLoop remoteconnect requested:  id [2] addons []
CAsyncWriteInProgress::OnComplete( "scripts/dota_local_disk_lobby_data.txt" ) -> Success at 164.981
CL:  IGameSystem::LoopDeactivateAllSystems
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 165.014
CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/play_searching) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/ui_tier_max) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/campaign_winter2016_header) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/dashboard_parallax_test) no such group
SV:  IGameSystem::LoopDeactivateAllSystems
HO:  IGameSystem::LoopDeactivateAllSystems
SV:  Disconnect client 'Okami' from server(1): NETWORK_DISCONNECT_SHUTDOWN
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 165.186
Network socket 'client' opened on port -1
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( remoteconnect : success )
CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 165.534
CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 165.534
CL:  Sending connect to =[A:1:1297744903:6511]
Attempting connection to service in data center 'iad'
Requesting session from ord#32 (162.254.193.70:27046).  Ping = 35+14=49 (front+back=total).
Selected ord#32 (162.254.193.70:27046) as primary, session 0572867f.  [Ping = 35+14=49 (front+back=total).]
Requesting session from iad#43 (162.254.192.71:27021).  Ping = 48+0=48 (front+back=total).
Selecting iad#43 (162.254.192.71:27021) as backup #1, session 1d1c1d0e.  Ping = 48+0=48 (front+back=total).
CL:  Sending connect to =[A:1:1297744903:6511]
CL:  Received S2C_CHALLENGE [3276322531 auth 3] from =[A:1:1297744903:6511]
CL:  Sending C2S_CONNECT [43 protocol 3276322531 auth 3] to =[A:1:1297744903:6511]
CL:  Received S2C_CONNECTION from =[A:1:1297744903:6511] [addons:'']
CL:  Connected to '=[A:1:1297744903:6511]'
CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
SwitchToLoop levelload requested:  id [2] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( levelload : success )
CL:  Permit INetchannel::Transmit()
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [2] addons []
CL:  CNetworkGameClient already exists for connection to '=[A:1:1297744903:6511]'
CL:  connection to '=[A:1:1297744903:6511]' already started
Game: "Dota 2"
Map: "dota"
Players: 1 (1 bots) / 64 humans
Build: 7062 (revision 3346903)
Server Number: 2
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
CL:  CGameRulesGameSystem::GameInit installed game rules
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000560 seconds
UnserializeDMX: Unable to open file "0"
UnserializeDMX: Unable to open file "0"
ERROR: CParticleSnapshot::Unserialize - could not load file 0!
File error loading resource header "materials/effects/fog_world_00.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/effects/fow_clouds_00.vtex_c" (Error: ERROR_FILEOPEN)
Switched to backup #1 iad#43 (162.254.192.71:27021) as primary, session 1d1c1d0e.  Ping = 48+0=48 (front+back=total).  [Previous primary ord#32 (162.254.193.70:27046): Ping = 43+14=57 (front+back=total).]
Selecting ord#32 (162.254.193.70:27046) as backup #1, session 0572867f.  Ping = 43+14=57 (front+back=total).
File error loading resource header "particles/econ/events/fall_major_2015/compendium_points_fall_ambient_2015_magic.vpcf_c" (Error: ERROR_FILEOPEN)
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
CL:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.022588 seconds
Remote Connect (=[A:1:1297744903:6511])
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
Telling Steam not to update the app for the next 900 seconds
CDOTA_SF_HTML disabled in Source 2
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 97.839 KB [112 pkts], outgoing 93.057 KB [2046 pkts]
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD'
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_HERO_SELECTION'
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
MarkInterpolationLatchFlagsDirty:  C_BaseEntity::IsLatchedPermissible() == false
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_PRE_GAME'
Allocating new transform texture!
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
Telling Steam not to update the app for the next 900 seconds
Unknown command: dota_all_vision_enable
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS'
Telling Steam not to update the app for the next 900 seconds
CL:  CL_ProcessPacketEntities: frame window too big (>=128)
CL:  Receiving uncompressed update from server
CL:  Server disconnected: #GameUI_Disconnect_TimedOut
CL:  Disconnecting from server: #GameUI_Disconnect_Request_HSIdle
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/play_searching) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/ui_tier_max) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/campaign_winter2016_header) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/dashboard_parallax_test) no such group
SwitchToLoop levelload requested:  id [3] addons []
CL:  IGameSystem::LoopDeactivateAllSystems
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 358.682
HO:  IGameSystem::LoopDeactivateAllSystems
Unloading custom UI:
CL:  CGameRulesGameSystem::GameShutdown uninstalled game rules
CL:  CGameRules::CGameRules destructed
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 358.898
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
Idle (levelload)
CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 358.929
CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 358.929
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [3] addons []
SV:  maxplayers set to 1
Initializing script VM...
...done
SV:  Spawn Server: <empty>
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  Sending connect to loopback
SV:  Sending S2C_CHALLENGE [4059781794 auth 2] to loopback
CL:  Received S2C_CHALLENGE [4059781794 auth 2] from loopback
CL:  Sending C2S_CONNECT [43 protocol 4059781794 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 43 4059781794 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'Okami' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 7061 (revision 3346903)
Server Number: 2
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.042404 seconds
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.018743 seconds
Failed to load grid nav data, file 'maps/<empty>.gnv' not found!
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
SV:  Sending full update to client Okami (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 33.761 KB [9 pkts], outgoing 1.305 KB [10 pkts]
Received Stats from iad#43 (162.254.192.71:27021) when we thought we didn't have a session.  Marking session as active.
Deleting lobby data from disk.
Telling Steam it is safe to udpate the app
WriteSteamRemoteStorageFileAsync( "cfg/chat.cfg" ) -> at 385.795
CAsyncWriteInProgress::OnComplete( "cfg/chat.cfg" ) -> Success at 385.831
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
Discarding inactive session on iad#43 (162.254.192.71:27021).  session_inactivity_timeout
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 25 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 26 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 27 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 28 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 25 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 26 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 27 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 28 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 29 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 30 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 31 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 32 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 33 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 34 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 35 iterations without a present event.

**Comment by gdrewb-valve** [comment]
Likely not a Mac problem.

**Comment by Kadunzera** [comment]
Hello, I'm having the same problem. I get disconnected right after hero picks and game starts.

`Informações do computador:
    Fabricante: Apple
    Modelo: MacBookPro8,2
    Tipo: Laptop
    Sem entrada de toque

Informações do processador:
    Fabricante da CPU: GenuineIntel
    Família do processador: 0x6
    Modelo do processador: 0x2a
    Stepping do processador: 0x7
    Tipo do processador: 0x0
    Velocidade: 2200 MHz
    8 processadores lógicos
    4 processadores físicos
    HyperThreading: Suportado
    FCMOV: Suportado
    SSE2: Suportado
    SSE3: Suportado
    SSSE3: Suportado
    SSE4a: Não suportado
    SSE41: Suportado
    SSE42: Suportado
    AES: Suportado
    AVX: Suportado
    CMPXCHG16B: Suportado
    LAHF/SAHF: Suportado
    PrefetchW: Não suportado

Informações da rede:
    Velocidade da rede: 

Versão do sistema operacional:
    MacOS 10.11.3 (64-bit)

Placa de vídeo:
    Driver: AMD Radeon HD 6750M

```
Versão do driver: 1.2
Data do driver: 0 de  de 0
Versão do OpenGL: 2.1
Profundidade de cor da área de trabalho: 32 bits por pixel
Taxa de atualização do monitor: 0 Hz
VendorID: 0x1002
DeviceID: 0x6741
Número de monitores: 1
Número de placas de vídeo lógicas: 2
Resolução do monitor primário: 1440 x 900
Resolução da área de trabalho: 1440 x 900
Tamanho do monitor primário: 12.95" x 8.15" (15.28" diag)
       32.9cm x 20.7cm (38.8cm diag)
VRAM primária: 0 MB
```

Memória:
    RAM: 4096 Mb

Outros:
    Idioma da interface: Português (Brasil)
    Microfone: Not set
    Tipo de mídia: DVD
    Total de espaço disponível em disco: 475766 Mb
    Maior bloco livre do disco rígido: 202774 Mb
    Headset de RV: Nenhum encontrado

`

**Comment by markfinst** [comment]
Getting exactly the same problem. On iMac 2013.

I've found on dev.dota2 similar discussions with the same problem:
- http://dev.dota2.com/showthread.php?t=190868
- http://dev.dota2.com/showthread.php?t=192664

Both are on Mac.

Also, for some reason I always load into the game one of the last, even though specs are quite good:

```
Processor
3.2GHz quad-core Intel Core i5 processor

Memory
8GB (two 4GB) of 1600MHz DDR3 memory;

Graphics
NVIDIA GeForce GT 755M graphics processor with 1GB of GDDR5 memory
```

... again, reading discussions on dev.dota2, it seems to happen only on Mac since Reborn.

**Comment by gdrewb-valve** [comment]
This happens on all platforms.  The larger team has been looking at it.  There are multiple reports on Mac to be sure and we'll keep this open.

**Comment by gdrewb-valve** [comment]
Closing as this isn't Mac-specific.  dev.dota2.com is the place for information, although I don't believe the larger team has any fixes yet.
