### ISSUE TITLE
[Linux] Panorama Crash

### ISSUE THREAD

**Issue by ash47** [ValveSoftware/Dota-2#791]
Panorama is crashing in Legends of Dota when using Linux, while it is fine in Windows.

Someone has opened the following issue: https://github.com/ash47/LegendsOfDota/issues/200

It reads as follows:

> After the major update and change to skill select interface, my game crashes every time I open the 'find skill' menu. My System Log shows the same error each time:
> 
> kernel: [1497178.490686] dota2[23540]: segfault at 7fff00000048 ip 00007fdffcc2acb1 sp 00007fffa37331e0 error 4 in libpanorama.so[7fdffc9c1000+519000]
> 
> If I wait until hero/skill select is over, I can reconnect and continue play. If I attempt to connect before the hero/skill select has finished, the game immediately crashes. I have tried verifying the integrity of the game cache with no change.
> 
> Any ideas if this is specific to me or is it a Linux related issue?

I have created an issue on the forums:
http://dev.dota2.com/showthread.php?t=192895

I have an open issue on the LoD repo:
https://github.com/ash47/LegendsOfDota/issues/200

I will try to fix myself, but, the issue should really be fixed on valve's end.

**Comment by Tele42** [comment]
A valve dev needs a minidump or CrashID to look into this. Also, it would be nice if the system information as requested at https://github.com/ValveSoftware/Dota-2#system-information was also provided.

**Comment by ash47** [comment]
Propagandalf: https://drive.google.com/file/d/0B8nRx0-0ymUeaDh2X2Juc2F5enM/view?usp=sharing
Propagandalf: Here is a crashdump for your thread with valve. I am not sure, that it is the right error (I did not found the word "panorama" in it)
Propagandalf: Also here my system specs: Debian 8.3 64 bit, window manager I3, graphics card: MSI Nvidia GTX 660,  driver version: Nvidia proprietary 4.4.0 340.96, system language: english, intel i5-4690 CPU
Propagandalf: ah and my Linux Kernel Version: 3.16.0-4-amd64

**Comment by gdrewb-valve** [comment]
Thanks, that was what we needed.  We'll have a fix in an upcoming update.

**Comment by rudmint** [comment]
Here is my info,

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-34-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.63
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1380
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.08" x 11.30"  (23.03" diag)
                                        51.0cm x 28.7cm  (58.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  16007 Mb

Here is the crash dump:
https://drive.google.com/file/d/0B65ebUqEuzvGNVFJdzRCcXlLSHM/view?usp=sharing

**Comment by gdrewb-valve** [comment]
@rudmint I was not able to get any information out of the file you shared so it's not clear if you have a different issue or the same as the original.

**Comment by rudmint** [comment]
Argh - please try this: 
https://drive.google.com/file/d/0B65ebUqEuzvGNVFJdzRCcXlLSHM/view?usp=sharing

**Comment by gdrewb-valve** [comment]
No luck with that one either.  The file will be a binary file, not a .txt file.

**Comment by rudmint** [comment]
https://drive.google.com/file/d/0B65ebUqEuzvGcVNxaUFURWpJUG8/view?usp=sharing

... ?

**Comment by gdrewb-valve** [comment]
That one doesn't come up as valid either.  If you look in the Steam client System Information do you have failure report IDs?

**Comment by rudmint** [comment]
Recent Failure Reports:
    Wed Mar 16 02:38:13 2016 GMT: file ''/tmp/dumps/crash_20160315223750_1.dmp'', upload yes: ''Discarded=1''
    Sun Mar 20 21:34:57 2016 GMT: file ''/tmp/dumps/crash_20160320173026_1.dmp'', upload yes: ''Discarded=1''

The file I've attempted to share is the second one.

**Comment by gdrewb-valve** [comment]
Sorry yet again but when the report is discarded (Discarded=1) it isn't kept at Valve so I can't look at them.  If you can cause it to crash again and see if you have a new failure report that has an ID I can look it up by ID.

**Comment by rudmint** [comment]
```
Tue Mar 22 16:48:24 2016 GMT: file ''/tmp/dumps/crash_20160322124416_1.dmp'', upload yes: ''CrashID=bp-db0aac8b-8046-42d4-a4d1-dab5f2160322''
```

**Comment by gdrewb-valve** [comment]
Thanks, I was able to look at that and you have the same crash as ash47.

**Comment by rudmint** [comment]
Thanks.

**Comment by ash47** [comment]
You guys are really quite dedicated, it's very impressive. For the record,
the information I have only forwarded information on behalf of other users,
I don't actually play Dota on Linux.

**Comment by rudmint** [comment]
Just curious, will this be fixed with the Spring Cleaning 2016 update or will it be in a separate update?

**Comment by Tele42** [comment]
@gdrewb-valve or another dev will report on this issue report if they have a fix lined up that they know is for this issue.

**Comment by gdrewb-valve** [comment]
Yes, the fix will be in the Spring Cleaning update.

**Comment by gdrewb-valve** [comment]
The update with the fix is out, are you still having the problem?
