### ISSUE TITLE
Client crash when launched with '-console' startup flag after SPRING CLEANING update

### ISSUE THREAD

**Issue by literallyunplayable** [ValveSoftware/Dota-2#795]
EDIT: The below is misleading, the client crashes when the console is opened in any way, either through the -console flag or through using the settings menu to assign a hotkey and pressing that key.

--- old post ----
When you launch the game with the '-console' flag, the client will crash on startup.

What should happen: -console option overrides existing setting, and client does not crash.

Workaround: Remove -console from startup flag, and enable the console from the settings menu.

This behaviour started after the spring cleaning update.

A pretty minor issue but I'm making this report so that people know what is causing their crash. It confused me for a while until I realized I had the flag enabled.

I am using ubuntu-gnome 15.10
--- end old post ---

Whenever the i try to open the console, the client crashes before it can appear. 

SYSTEM INFO:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-17-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 420/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.63
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xde2
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  3933 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  115798 Mb
    Largest Free Hard Disk Block:  49957 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
A fix is on the way.

**Comment by literallyunplayable** [comment]
thanks!

**Comment by KaiSforza** [comment]
Just came in to see if this was being worked on and to report that the workaround does not work on my system. Not sure if this changes the fix at all, but I cannot open the console, regardless of the launch flag or option in the game itself.

**Comment by Jubilant-Lancer** [comment]
I myself am unable to open console at all. I can get in game and all settings I have in my autoexec work fine but my console will not open. Ubuntu 14.04

**Comment by Enigma7ic** [comment]
Yup still happens to me every 5 secs even after installing like 3 patched tonight. WTF? Did nobody test this!?

**Comment by gdrewb-valve** [comment]
Is any non-Mac user still seeing problems?

**Comment by gdrewb-valve** [comment]
The major fixes are out.  There will be other crashes but the really frequent and startup crashes should be resolved.
