### ISSUE TITLE
[Linux] Impossible to launch DotA 2

### ISSUE THREAD

**Issue by abobier** [ValveSoftware/Dota-2#796]
The crash arrives after the DotA 2 logo on Ubuntu 15.10

dmesg
`[ 5633.132188] dota2[5245]: segfault at 0 ip 00007f2e412613f1 sp 00007ffeaf677570 error 4 in libmaterialsystem2.so[7f2e41200000+178000]`

uname -a
`Linux pcabo 4.5.0-040500-generic #201603140130 SMP Mon Mar 14 05:32:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

lspci | grep VGA
`01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)`

glxinfo | grep NVIDIA

```
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
OpenGL core profile version string: 4.4.0 NVIDIA 364.12
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.5.0 NVIDIA 364.12
OpenGL shading language version string: 4.50 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 364.12
```

**Comment by abobier** [comment]
-console in launch properties

EDIT: that works without -console

**Comment by dannytaylor** [comment]
Able to launch after removing -console, but crashes almost immediately when you load your hero into the game. I'd advise not playing to avoid abandons/lost mmr.

Ubuntu 15.10
4.2.0-34-generic
NVIDIA Corporation GM107 [GeForce GTX 750]

dmesg
`[772464.707325] dota2[3742]: segfault at 0 ip 00007f4d251bc3f1 sp 00007fff2a301100 error 4 in libmaterialsystem2.so[7f4d2515b000+178000]
`

**Comment by gdrewb-valve** [comment]
A fix is on the way.

**Comment by samuelclark** [comment]
@gdrewb-valve is there a fix for the mac issue -- absolutely unplayable, have received 2 abandons.

**Comment by Shenglai** [comment]
@gdrewb-valve crash only when playing games (eg. hero demo, lobby bot game, and any kinds of matching). It's fine to stay at main page, browse the store. From OSX 10.11.2

**Comment by onedr0p** [comment]
The game is crashing anytime there's dust being used. I'm on OSX 10.11.2

**Comment by glajchs** [comment]
I had the segfault on linux on startup just like the original poster, and found that after a steam restart (about 3 hours ago) to apply a steam update, it fixed itself.  About 1-2 hours after that, there was a dota update.  So I think in this case the steam update has resolved this.  Maybe @abobier can confirm as well.

**Comment by inikiforovski** [comment]
Having the same issue on OSX 10.10.5. The main menu, store, lobby are all good. It either crashes right when loading into a game or intermittently after. It seems like panning around the map a bunch increases the likelihood of a crash. I would say it's happening pretty consistently about 15 seconds to a minute once I get back into the game.

Edit: wanted to mention that I don't have -console enabled.

**Comment by ChemicalWonders** [comment]
I have this issue while running on OSX 10.11.3. Is it affecting all OSX clients? After multiple restarts and verifying game caches, the issue keeps popping up. :(

**Comment by gdrewb-valve** [comment]
An update is just coming out which should help with at least some of this.

**Comment by ramverma92** [comment]
I got the new update, but still crashing overtime :(

**Comment by gdrewb-valve** [comment]
Is any non-Mac user still seeing problems?

**Comment by juston-li** [comment]
@gdrewb-valve Linux user here, was seg faulting earlier today every 2-5 minutes in a match.
Currently I can't seem to reproduce though so far I've only tried in spectating and bot games. Queuing for a match now.

Linux asus-m51ac 4.5.0-CUSTOM-00006-g9ceb4e9 #1 SMP PREEMPT Sun Mar 13 22:09:14 PDT 2016 x86_64 GNU/Linux
GTX 970
OpenGL core profile version string: 4.5.0 NVIDIA 364.12

EDIT: No issues playing match

**Comment by mamuchao** [comment]
works on linux

**Comment by inikiforovski** [comment]
Looks like the crashes are gone now, was able to play overthrow and dota 10v10 without crashing once (OSX 10.10.5). Thanks!

**Comment by gdrewb-valve** [comment]
The major fixes are out.  There will be other crashes but the really frequent and startup crashes should be resolved.
