### ISSUE TITLE
Linux: Steam overlay flickering

### ISSUE THREAD

**Issue by gankbanger** [ValveSoftware/Dota-2#8]
Shift-tabbing into steam overlay is making the whole screen flicker, going from white, gray, blue to green and probably other colors. You can make out some of the icons, and the border of the windows between flashes, but it is mostly unusable

The bug is only happening when shift-tabbing in the menu screens BEFORE loading a game. After I demoed a hero the issue went away. I could access steam overlay while demoing the hero, and again without issues from the menu screens after quitting the demo. (I can reproduce this behavior systematically)

I caught a screenshot: http://i.imgur.com/tvgklaM.jpg

I am running Linux Mint 17.1 Cinnamon.
NVidia GTX570 331.113 drivers
Dota 2 Reborn on fullscreen.

**Comment by ramma** [comment]
Pretty sure this is an issue with Nvidia 331.113. Upgrading to 346 from Xorg Edgers fixed all my overlay and in game issues.

**Comment by vadi2** [comment]
This issue doesn't happen on normal dota, but does happen on reborn.

**Comment by gankbanger** [comment]
The issue went away after upgrading the Nvidia drivers from 331.113 to 352. It also corrected the HUD bug (reported by someone else) which I was also experiencing.

Thanks for the tip @ramma 

If anyone else has the same issue, you can get the latest drivers in Linux Mint with these commands:

```
$ sudo add-apt-repository ppa:xorg-edgers/ppa
$ sudo apt-get update
$ sudo apt-get install nvidia-352
```

**Comment by gdrewb-valve** [comment]
Tentatively marking this as a driver issue.

**Comment by vadi2** [comment]
I upgraded from 331.113 to 352 and the overlay was fixed.

**Comment by gdrewb-valve** [comment]
Closing as this sounds resolved.
