### ISSUE TITLE
El Capitan crash 30 seconds after entering game

### ISSUE THREAD

**Issue by tobiashagge** [ValveSoftware/Dota-2#801]
Game exits to desktop about 30 seconds after entering game as a player or in spectator mode. Does not produce a crashlog or dialog box. No launch options set, problem persists after reinstalling the game.

Some system information:

OS X El Capitan (10.11.4)
Mac Pro (Early 2008)
6 GB RAM
NVIDIA GeForce GTX 650 Ti BOOST 2048 MB

Some output from Console:

3/24/16 10:42:51.398 PM WindowServer[197]: disable_update_timeout: UI updates were forcibly disabled by application "Dota 2" for over 1.00 seconds. Server has re-enabled them.
3/24/16 10:42:54.056 PM dota2[822]: 22:42:54.055 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
3/24/16 10:43:05.399 PM WindowServer[197]: disable_update_likely_unbalanced: UI updates still disabled by application "Dota 2" after 15.00 seconds (server forcibly re-enabled them after 1.00 seconds). Likely an unbalanced disableUpdate call.
3/24/16 10:43:05.488 PM dota2[822]: void CGSUpdateManager::log() const: conn 0x23d63 token 0x1ffffffffffe85
3/24/16 10:43:05.492 PM dota2[822]: Backtrace (at 1531.95):
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff8e475b98 CGSDisableUpdateToken + 155
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff88c7c524 ___disable_updates_sync_block_invoke_2 + 17
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x00007fff98e4240b _dispatch_client_callout + 8
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x00007fff98e439f2 _dispatch_barrier_sync_f_invoke + 74
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  4   AppKit                              0x00007fff88c7c3f2 NSCGSDisableUpdates + 213
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  5   AppKit                              0x00007fff88c7c228 NSCGSTransactionRunPreCommitActionsForOrder_ + 156
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  6   AppKit                              0x00007fff88c7c16f NSCGSTransactionRunPreCommitActions_ + 21
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  7   AppKit                              0x00007fff8942ad84 -[_NSCGSTransaction synchronize] + 33
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  8   AppKit                              0x00007fff8942aff9 NSCGSTransactionSynchronize + 76
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  9   AppKit                              0x00007fff89216065 -[NSSurface syncSurfaceWantsExtendedDynamicRange] + 150
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  10  AppKit                              0x00007fff88d4e3d1 -[NSSurface _createSurface] + 677
3/24/16 10:43:05.492 PM dota2[822]: void CGSUpdateManager::log() const:  11  AppKit                              0x00007fff88d4dd2c -[NSSurface setFrame:] + 785
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  12  AppKit                              0x00007fff8921616b __38-[NSSurface syncToViewUnconditionally]_block_invoke + 154
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  13  AppKit                              0x00007fff88c6b429 NSPerformVisuallyAtomicChange + 147
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  14  AppKit                              0x00007fff88d4d650 -[NSSurface syncToViewUnconditionally] + 100
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  15  AppKit                              0x00007fff89216204 __37-[NSSurface orderSurface:relativeTo:]_block_invoke + 44
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  16  AppKit                              0x00007fff88c6b429 NSPerformVisuallyAtomicChange + 147
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  17  AppKit                              0x00007fff88d4d523 -[NSSurface orderSurface:relativeTo:] + 160
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  18  AppKit                              0x00007fff88e40f22 NSOpenGLContextAttachOnScreenViewSurface + 183
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  19  AppKit                              0x00007fff8916d767 __27-[NSOpenGLContext setView:]_block_invoke + 192
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  20  AppKit                              0x00007fff88c6b429 NSPerformVisuallyAtomicChange + 147
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  21  AppKit                              0x00007fff88e2dcd9 -[NSOpenGLContext setView:] + 119
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  22  libSDL2-2.0.0.dylib                 0x000000008523d5ca -[SDLOpenGLContext setWindow:] + 426
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  23  libSDL2-2.0.0.dylib                 0x000000008523e3b6 Cocoa_GL_MakeCurrent + 118
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  24  libSDL2-2.0.0.dylib                 0x000000008523e066 Cocoa_GL_CreateContext + 2118
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  25  libSDL2-2.0.0.dylib                 0x00000000852340d6 SDL_GL_CreateContext_REAL + 214
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  26  libSDL2-2.0.0.dylib                 0x0000000085161ac4 SDL_GL_CreateContext + 36
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  27  librendersystemgl.dylib             0x0000000088c1433d VoidFnPtrLookup_Tier0 + 32653
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  28  librendersystemgl.dylib             0x0000000088c160d3 VoidFnPtrLookup_Tier0 + 40227
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  29  librendersystemgl.dylib             0x0000000088bdc2c8 BinaryProperties_GetValue + 215656
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  30  libtier0.dylib                      0x0000000009c7e618 CreateSimpleThread + 584
3/24/16 10:43:05.493 PM dota2[822]: void CGSUpdateManager::log() const:  31  libsystem_pthread.dylib             0x00007fff898e699d _pthread_body + 131
3/24/16 10:43:07.053 PM dota2[822]: 22:43:07.052 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
3/24/16 10:45:17.208 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.
3/24/16 10:45:17.208 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.
3/24/16 10:45:17.208 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.
3/24/16 10:45:17.208 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.
3/24/16 10:45:21.006 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.
3/24/16 10:45:28.783 PM dota2[822]: dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N6google8protobuf11MessageLiteE, 42CMsgFillBrushCollection_AnimationFrameData, N6google8protobuf7MessageE.

**Comment by omartan** [comment]
Thank goodness I didn't tried reinstalling the game as it's the patch that broke it

**Comment by gxgani** [comment]
OS: OSX 10.11.4
Intel HD 4000

Seems to be working fine here(tested spectate + bot match). I did get a 25MB sized update few hours ago.

**Comment by ghost** [comment]
I didn't get a 24MB sized update :(

**Comment by haidaoxiaofei** [comment]
seems `-threads 0` can work

**Comment by tobiashagge** [comment]
-threads 0 seems to work.

**Comment by leungandrew** [comment]
Can confirm setting `-threads 0` in launch options has worked around the immediate crashing

**Comment by danginsburg** [comment]
Duplicate of #794.  We are working on a fix.
