### ISSUE TITLE
Make OSX/Linux DotA 2 Test Client available?

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#802]
I mean this is not the first time these issues have occurred, got myself into Low priority for nothing in the previous patches. By having test client just like the windows users will let us test the game and let the devs know about issues prior to the patch/update release.

Thanks!

**Comment by u00101010** [comment]
There is one! Those who played during the beta **have** the Test Client, which is the same as the Windows one.

I don't think there is a way to obtain the test client nowadays, though...  :worried:

**Comment by gxgani** [comment]
![](https://cobalt60.xyz/shared/Screen-Shot-2016-03-25-12-27-08.png)

I thought the test client was supposed to be an addon.

PS: If that is the test client, than it's available to all. Just checked with my alternative accounts.

**Comment by gdrewb-valve** [comment]
As mentioned the test client should be available on all platforms.
