### ISSUE TITLE
[OS X El Capitan] Mini-Map Bug

### ISSUE THREAD

**Issue by chrissisura** [ValveSoftware/Dota-2#804]
![bildschirmfoto 2016-03-25 um 08 53 42](https://cloud.githubusercontent.com/assets/18066580/14040398/259d6654-f267-11e5-8c29-9fcea7a692b0.png)
![bildschirmfoto 2016-03-25 um 08 53 56](https://cloud.githubusercontent.com/assets/18066580/14040401/2c617e76-f267-11e5-986f-4a769298f40b.png)

In Certain parts of the Map the Minimap blackes out. 
MacBook Pro (Retina, 13 Zoll, Early 2015)
Prossesor 2,9 GHz Intel Core i5
8 GB 1867 MHz DDR3
Intel Iris Graphics 6100 1536 MB

**Comment by danginsburg** [comment]
What resolution are you running at?  Does this always happen right from the start?  Please post Steam -> Help -> System Information as well.  Thanks.

**Comment by chrissisura** [comment]
Right from the start yes! 1280x800

Processor Information:
    Model:  MacBookPro12,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.3 (64 bit)

Video Card:
    Driver:  Intel Iris Graphics 6100

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x162b
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.26" x 7.05"  (13.27" diag)
                                        28.6cm x 17.9cm  (33.7cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475928 Mb
    Largest Free Hard Disk Block:  230133 Mb
    VR Headset: None detected

Installed software:
    Accessibility Inspector
    Alerts Daemon
    Anki
    App Store
    Application Loader
    Automator
    Digitale Bilder
    Dolphin
    Equation Editor
    Erinnerungen
    FaceTime
    FileMerge
    Firefox
    Fotos
    Game Center
    Google Chrome
    Google Drive
    Google Mail
    Google-Suche
    iBooks
    Install Spotify
    Instruments
    Kalender
    Karten
    Kontakte
    Launchpad
    Microsoft Cert Manager
    Microsoft Chart Converter
    Microsoft Clip Gallery
    Microsoft Database Daemon
    Microsoft Database Utility
    Microsoft Document Connection
    Microsoft Entourage
    Microsoft Excel
    Microsoft Graph
    Microsoft Messenger
    Microsoft Office 2008-Setup-Assistent
    Microsoft Office-Erinnerungen
    Microsoft PowerPoint
    Microsoft Project Gallery
    Microsoft Word
    Microsoft-Synchronisierungsdienste
    MiniTerm
    Mission Control
    My Day
    Nachrichten
    Notizen
    Notizzettel
    Organigramm
    Remove Office
    Skype
    Spotify
    Steam
    TeamSpeak 3 Client
    The Unarchiver
    VLC
    Xcode
    YouTube

**Comment by anyuzer** [comment]
Noticed this as well, on mine it seems to black out only over the river.

Added a video link to make it more obvious: 
https://youtu.be/6STs3dR3gT0

**Comment by chrissisura** [comment]
Same for me! Only on certain parts of the map (close to the river) the map blacks out

**Comment by danginsburg** [comment]
I'm having a bit of trouble repro'ing this so far.  @anyuzer  and @chrissisura, are you also on Intel Iris Graphics 6100?  Could one of you who is seeing this either take a screenshot of your video options or post the contents of game/dota/cfg/video.txt?  It would also be helpful to know what resolution your desktop is in.  Thanks.

**Comment by danginsburg** [comment]
Looking at the video it very strongly looks like stencil buffer or stencil state corruption.  Somehow the stencil for the water is masking off the minimap.  Does disabling High Quality Water workaround the corruption?

**Comment by esmaxwill** [comment]
I'm also on the Iris 6100 and have the same issue.  It's not just the water that does it, if you move your view so the minimap covers a hero you will see a "shadow" of the hero you're obscuring.  

I attached my video.txt and a picture showing an example of this from a Queen of Pain game I just played.
![vnuvm1h](https://cloud.githubusercontent.com/assets/436282/14088846/4a4ecdd4-f4f7-11e5-81a3-eeda0001f3c8.png)
[video.txt](https://github.com/ValveSoftware/Dota-2/files/192411/video.txt)
<img width="590" alt="screen shot 2016-03-28 at 3 12 57 pm" src="https://cloud.githubusercontent.com/assets/436282/14088907/af469456-f4f7-11e5-9d48-6df56ff8c970.png">

**Comment by chrissisura** [comment]
![bildschirmfoto 2016-03-29 um 13 04 59](https://cloud.githubusercontent.com/assets/18066580/14105964/f4c911a4-f5ae-11e5-93a4-5d1825018140.png)
I am also playing on Intel Iris Graphics 6100 1536 MB

**Comment by chrissisura** [comment]
I just tried to switch to high quality Water, but i doesnt change anything.

**Comment by chrissisura** [comment]
I also tried some different video settings but the dont change the fact that the black parts on the mini-map keep coming up. I am not sure but it feels like with different setting the black parts slightly change but i am not sure about that.

**Comment by xrisk** [comment]
Can confirm. Same Iris 6100, and the black patches when a unit moves "underneath" the minimap.

**Comment by danginsburg** [comment]
Thanks for the reports.  Unfortunately this looks like an OpenGL driver bug on the OS X Broadwell driver.  I have filed a Radar with Apple (25440145).  Hopefully they can take a look at it.  What I believe is happening is that the stencil test is misconfigured when drawing the minimap, but I don't have any workaround from our side yet. @anyuzer Please leave the video up, I referenced it in the Radar.

**Comment by Dendim0n** [comment]
2014 Mid MBPr 15" with nVIDIA GT750M   everything seems fine.

**Comment by xrisk** [comment]
Here I got a screencap as well.

![20160330185753_1](https://cloud.githubusercontent.com/assets/10669859/14181326/1bae2bfc-f784-11e5-86a2-fe293121cd30.jpg)

**Comment by ericorr** [comment]
Want to confirm I have the same problem with the iris 6100 macbook

**Comment by PizzaPino** [comment]
I have this same problem and I think it happens, when heroes walk in front of the minimap, too. Left clicking on the black spots remove them.

**Comment by chinoythegreat** [comment]
Happens to me as well. Mac OSX El Capitan 10.11 here.

![20160402201721_1](https://cloud.githubusercontent.com/assets/17286618/14226426/4cbf3664-f914-11e5-8d10-6b399bb6fbf5.jpg)

**Comment by gdrewb-valve** [comment]
Is this still happening after the April 5 update?

**Comment by tksafrit** [comment]
Yes. Another Iris 6100 user reporting in.

![20160406115319_1](https://cloud.githubusercontent.com/assets/5273385/14323353/35af7aba-fbee-11e5-9d33-eea8c320fc0a.jpg)

**Comment by gdrewb-valve** [comment]
Too bad, now we'll have to wait and hopefully Apple will get back to us.

**Comment by anyuzer** [comment]
Got back from out of town. Problem still occurs for me as well, though seems fairly well documented at this point.

![system](https://cloud.githubusercontent.com/assets/195924/14339568/5e71e0c8-fc34-11e5-97d2-1079ab765a42.png)

**Comment by chinoythegreat** [comment]
Will this ever be fixed? Still bugged for me. Well done Valve.

**Comment by gdrewb-valve** [comment]
We haven't heard anything from Apple so we've put in another experimental change in the April 12 update.  Are things any different after updating?

**Comment by anyuzer** [comment]
Did a really quick check, and it looks fixed to me! Unfortunately, now I will have nothing to blame my terrible playing on :-D

**Comment by gu3st** [comment]
0/10 for map awareness.

**Comment by xrisk** [comment]
Yes, I haven't noticed the bug for some time. I believe it is fixed for me.

**Comment by danginsburg** [comment]
Great, sounds like our workaround did the trick.  Closing.
