### ISSUE TITLE
Dota 2 Crashes upon startup

### ISSUE THREAD

**Issue by algb3** [ValveSoftware/Dota-2#808]
![screen shot 2016-03-25 at 12 45 01 pm](https://cloud.githubusercontent.com/assets/18075017/14050612/85709160-f293-11e5-86d6-cec10f43fcf4.png)

**Comment by danginsburg** [comment]
Usually this points to a failure loading a required .dylib.  Please try Dota 2 -> Properties -> Local Files -> Verify Integrity of Game Cache.  If it still happens after that, add -con_logfile to your launch options and post the contents of game/dota/console.log.  It would also be helpful if you posted Steam -> Help -> System Information.

**Comment by kolobos** [comment]
I had a similar problem with an incorrectly configured Xmonad window manager ("setWMName 'LG3D'" workaround for a Java menu bug prevents Dota 2 UI from working), in case you recently changed something in your system.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
