### ISSUE TITLE
Settings menu not supporting 1280x1024 resolution

### ISSUE THREAD

**Issue by DimasDSF** [ValveSoftware/Dota-2#810]
After "The Spring Cleaning" update Half the settings menu "is sent off the screen" hiding half of "Advanced Settings"
![20160326023857_1](https://cloud.githubusercontent.com/assets/10863746/14056477/98639654-f2fd-11e5-9d8c-108d8da53220.jpg)
![20160326023852_1](https://cloud.githubusercontent.com/assets/10863746/14056480/9a4277e2-f2fd-11e5-9cab-4fda1664994c.jpg)

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue, the larger team will be looking into it.  I believe it has already been reported at dev.dota2.com.

**Comment by DimasDSF** [comment]
Oh, sorry, I didnt understand it was only linux/mac section, anyway thank you for the answer
