### ISSUE TITLE
Empty players in lobby

### ISSUE THREAD

**Issue by insunaa** [ValveSoftware/Dota-2#813]
Sometimes, when in a lobby for a custom game, it happens that an empty player will appear in the unassigned players list, there's no name and only a dark grey half transparent portrait. This player cannot be assigned to any teams and can thus block the start of a game. The lobby has to be disbanded and reformed when this happens.
I've noticed this most often in the Pimp My Peon custom game, but this is matchmaking problem, not a custom game problem.

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue so we'll pass this on to the larger team.

**Comment by gdrewb-valve** [comment]
Closing as this has been passed on to the larger team and won't be tracked here.
