### ISSUE TITLE
Game crashing while watching replay.

### ISSUE THREAD

**Issue by hjeannin** [ValveSoftware/Dota-2#814]
When I watch the replay of the match **2237637460** the game suddenly crashes just after the tick **77600**, around **38:50**.

You can download the replay on google drive at the following link:
https://drive.google.com/file/d/0B0Miyca54g5ta19KQWJRakcxOTQ/view?usp=sharing

You can download crash dumps here:
https://drive.google.com/file/d/0B0Miyca54g5tSUU4blUyNzd4bVE/view?usp=sharing

**Comment by danginsburg** [comment]
Thanks for the excellent bug report.  This crash happens on all platforms.  I've passed this along to the larger team and they will take a look at it.  I'll close out the bug here since it is not Linux/OSX-specific.
