### ISSUE TITLE
[Linux] -sdl_displayindex 2 launch option is not working any more

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/Dota-2#815]
the spring update broke the launch option "-sdl_displayindex 2".
now dota is always starting on my right screen (screen 1 is right, 2 is left) but I want it on my left one.

**Comment by gdrewb-valve** [comment]
This is covered under issue #556.  Note that screens start at 0 so if you have two screens they are 0 and 1.  Using 2 in that situation is referencing a non-existent screen and was never supposed to do anything.

**Comment by ChrisLauinger77** [comment]
But it used to work. Before the spring cleaning update it was fine.

**Comment by gdrewb-valve** [comment]
Right, the fact that it did anything was a bug as there is no screen #2 on a two-screen system.  I understand that you've lost a workaround but the problem is the problem from #556, not that -sdl_displayindex 2 was a proper fix/workaround.
