### ISSUE TITLE
Attack command is treated as move command

### ISSUE THREAD

**Issue by NekR** [ValveSoftware/Dota-2#816]
This is most likely not a platform specific problem, but if so, then it had to be notice earlier. Thing is, sometimes when a do `A + Click somewhere`, instead of issue attack command character just moves to that position. This may look like internet problems or packet loss, but there is 0 loss and I have ping 40 most of the time, plus nothing is laggy at that moment--all other characters move just fine and mine character do, just with wrong command.

Never had this before Spring update. I am on a OS X.
Sys info: https://gist.github.com/NekR/9c863bee9d25ee0b24a8

**Comment by NekR** [comment]
May this be related to "bug-fixed" `Auto-Attack`? My option is set to `standard`. Maybe when creep/enemy isn't in some "rage" then character just moved to issued position. By "range' I mean some weird range, because at those moment enemies are in my attach range (at least from position to where command was issue).

**Comment by gdrewb-valve** [comment]
This isn't platform-specific so the larger team will handle it.  Check out dev.dota.com for the general game forums.

**Comment by NekR** [comment]
Thanks for info. Should I repost there?

**Comment by gdrewb-valve** [comment]
I think it's already there, but it wouldn't hurt to check.

**Comment by NekR** [comment]
Okay, poster there too. Thanks.
