### ISSUE TITLE
Massive Input Lags

### ISSUE THREAD

**Issue by somecolors** [ValveSoftware/Dota-2#819]
Hi dev Team,

I am using:
  Modellname:   iMac
  Modell-Identifizierung:   iMac17,1
  Prozessortyp: Intel Core i5
  Prozessorgeschwindigkeit: 3,2 GHz
  Anzahl der Prozessoren:   1
  Gesamtanzahl der Kerne:   4
  L2-Cache (pro Kern):  256 KB
  L3-Cache: 6 MB
  Speicher: 8 GB
  Boot-ROM-Version: IM171.0105.B05
  SMC-Version (System): 2.33f10
  Seriennummer (System):    C02QMDUEGG7L
  Hardware-UUID:    8EAB7EEB-6F42-5EF6-870B-5147D149E0A3

The problem is, when i am creeping or try to attack heros with the a for attack hotkey, the heros very often finish his movement and after this he "lags" before he attack.

My ping is pretty good and its no packetloss, its happen after the spring update.

can you help me?

Best regards,

Stefan

**Comment by NekR** [comment]
See this: https://github.com/ValveSoftware/Dota-2/issues/816

Also today they issued an update, which claims to fix "mouse left click some times ignored".

Hope that they meant this bug.

**Comment by somecolors** [comment]
ah ok, thanks man!
