### ISSUE TITLE
Mac: Heroes> Global items, menu does not work.

### ISSUE THREAD

**Issue by Vuccappella** [ValveSoftware/Dota-2#82]
I tried disabling my weather effects from the menu Heroes>Global Items>World but upon clicking world everything is greyed out Wards,Effigies,Weather Effects, same with the menu Companions>Pets or Companions>Couriers. or both the Interface and Audio menus and sub menus.  http://i.imgur.com/qsIRDy0.jpg example. I have many items that fit these categories.

**Comment by gdrewb-valve** [comment]
This isn't a Linux/Mac issue as the Global Items just is not completely implemented and is non-functional on all platforms.  This is in the dev queue but it won't be tracked here.
