### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by omarloren** [ValveSoftware/Dota-2#820]
Hi, 
The game keeps crashing, I know that there is already a patch for it but somehow my game is messed up. I already tried to reinstall it and nothing, this is my computer information:

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro9,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.4 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.22" x 7.01"  (13.23" diag)
                                        28.5cm x 17.8cm  (33.6cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  417383 Mb
    Largest Free Hard Disk Block:  222543 Mb
    VR Headset: None detected

**Comment by danginsburg** [comment]
Can you please run with "-con_logfile" in your Launch Options and post the contents of game/dota/console.log after it crashes.  Ideally we need a crashdump file or crashdump ID to be able to repro.

**Comment by omarloren** [comment]
Here you have my [console.log file](https://gist.github.com/omarloren/34b14b8accc62519a54cec616409c8b0), I am not getting any errors it just crashes without further notice.

**Comment by gdrewb-valve** [comment]
Is this still happening? If you look in your Steam system information do you have any failure reports?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
