### ISSUE TITLE
Key release as well as press triggers item cast

### ISSUE THREAD

**Issue by davmac314** [ValveSoftware/Dota-2#821]
I have "quickcast on key down" OFF (so: quick cast should trigger on key up) and quickcast keys bound for all item slots. If I use a non-targetable item (phase boots, drum of endurance) the item triggers on key DOWN and then seemingly again on key UP (which causes a "Recharging..." notification and clock tick sound). Remarkably the item does NOT trigger on key up if its cooldown has expired, i.e. it seems that the cooldown check is done before the "active on key up?" check.

Eg:
- phase boots bound to key X. Press and immediately release X. Phase boots trigger, and "Recharging..."+tick noise triggers.
- phase boots bound to key X. Press X and wait. Phase boots trigger. Wait for cooldown to expire. Release X; nothing happens.

This happens for every non-targetable item I tested: phase boots, drum of endurance, smoke of deceit, shiva's guard.

Arguably the items shouldn't trigger on key down at all, since the option in the configuration is for quick-cast on key UP, but I figure that for non-targetable items it does make sense to activate on key down. However, it shouldn't then also trigger again on key up.

This is purely an annoyance and in no way game-breaking, but it is a significant distraction to hear the clock tick (and occasional annoyed hero "not yet!" response) every time I activate phase boots. Not sure if this problem is Linux specific but I see no mention of it elsewhere.

System info, though I doubt it's relevant:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4001 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.0
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11802000
    X Window Manager:  Fluxbox
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BONAIRE (DRM 2.43.0, LLVM 3.6.2)

    Driver Version:  3.0 Mesa 11.0.3
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                            50.9cm x 28.6cm  (58.3cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  7889 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU
    Microphone:  Not set
    Total Hard Disk Space Available:  509309 Mb
    Largest Free Hard Disk Block:  108902 Mb
    VR Headset: None detected

```

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team as it's very likely not Linux-specific.

**Comment by gdrewb-valve** [comment]
The larger team found the problem and they'll take care of it in an upcoming update.  It won't be tracked here.

**Comment by davmac314** [comment]
Ok, thanks for forwarding it.

**Comment by davmac314** [comment]
And I see it's now fixed. Thanks again.
