### ISSUE TITLE
Can't run DOTA 2 on MacOs - ElCapitan

### ISSUE THREAD

**Issue by Portosthedevil** [ValveSoftware/Dota-2#822]
Hello there,

can anybody help me solve my issue ? I try to run DOTA 2  on MacbookPro 15 Retina display early 2013.

When I click on ''START'' button nothing happens ...

**Comment by Dendim0n** [comment]
Everything seems fine...15" Retina 2014 Mid

**Comment by gdrewb-valve** [comment]
What version of OSX are you running?  10.9 is required.

Have you verified the local installation files?  Right-click on the app in the Steam client, go to Properties -> Local Files and click the button there.

**Comment by Portosthedevil** [comment]
10.11

**Comment by gdrewb-valve** [comment]
After verifying your local files try running the game from a terminal window (there's a dota.sh that'll launch it) or add -con_logfile to your startup options, then post the terminal output or contents of console.log.

**Comment by gdrewb-valve** [comment]
Closing as we can't do more without additional information.
