### ISSUE TITLE
Menu is missing 3 panels on Linux

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#825]
Hi there!

Only the last match and the store sale panels work on the Dashboard.

![dasherror](https://cloud.githubusercontent.com/assets/7419656/14226263/7819e5c0-f8dd-11e5-94f0-62a458f22fe6.png)

This doesn't seem to be a computer-specific issue to me, but [here's a gist with my system information](https://gist.github.com/helix42/263e9e672868f05aca1a389e1b3db2ec) anyways.

**Comment by u00101010** [comment]
UPDATE: Now the shop's gone, too.

![20160403170156_1](https://cloud.githubusercontent.com/assets/7419656/14233568/c9111e22-f9cc-11e5-9886-d7244c3420c8.jpg)

**Comment by budimanjojo** [comment]
I can confirm this on my system too

**Comment by gdrewb-valve** [comment]
This happens on all platforms.

**Comment by gdrewb-valve** [comment]
The larger team fixed this in the April 27th update, I believe.

**Comment by vith** [comment]
Confirming it's fixed for me on Arch Linux.

**Comment by budimanjojo** [comment]
Thanks, gdrewb!
