### ISSUE TITLE
[Linux] Poor performance with GTX970

### ISSUE THREAD

**Issue by lucianjon** [ValveSoftware/Dota-2#826]
Have been having issues with the performance with the linux client. On windows with the opengl
renderer it sits at a solid 120 fps (where it's capped) most of the time, it sometimes drops to 90s or so. However when playing on linux it frequently drops to the 30s and under. It does seem to generally correspond with stuff going on, typically team fights are the worst. Have tried disabling the steam overlay but it didn't seem to help at all. I don't boot into linux all too often so it's hard to say if this recently started happening or not.

This is running on Ubuntu 16.04 (unity) with the performance governor over ondemand. Hardware wise it's a Intel 2600k @ 4.1Ghz and a GTX970 on the Nvidia 364.12 drivers.

And the full system info:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  4101 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Xenial Xerus (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11801000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 364.12
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  9982 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_NZ.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  234602 Mb
    Largest Free Hard Disk Block:  101554 Mb
    VR Headset: None detected
```

**Comment by bkconrad** [comment]
Same card, same distro, same problem. It affects pretty much every steam Linux game I play. Best solution I've found so far is to dump Unity for a WM that lets you disable compositing (even though you really should be able to get 60fps with compositing enabled...). I use XFCE then disable compositing in the system settings.

Other suggestions are to play in "fullscreen" rather than "windowed fullscreen" or similar.

I don't think this is a Dota-specific issue, really just something shitty with Unity.

**Comment by lucianjon** [comment]
Using something other than unity really makes that much of a difference for you? Can you get solid 60+ on something like XFCE? I'd understand a few fps difference but not the significant drops I've been getting.

**Comment by ghost** [comment]
Noticed poor performance with unity on gtx 760, all ok witih xfce. But after switching to 980 gtx I got const 60 on unity.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
