### ISSUE TITLE
Support missing for 'select all other units' after spring cleaning update

### ISSUE THREAD

**Issue by literallyunplayable** [ValveSoftware/Dota-2#829]
Support for "dota_select_all_others" was removed from the UI after the spring cleaning update. This command is nessicary to quickly and accuratley use Witch Doctor's ward as well as easily command broodlings. Please return support to the settings UI.

**Comment by gdrewb-valve** [comment]
This repo is for Mac and Linux bugs and we don't handle general issues.  I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
It's in the advanced page of key bindings, there's a "Select All Other Units" binding there.
