### ISSUE TITLE
[Linux] Net worth hotkey does not work while spectating

### ISSUE THREAD

**Issue by Kirov123** [ValveSoftware/Dota-2#83]
I have tried mapping it to other keys which still doesnt work, and mapping other game stat hotkeys to the key I would use for net worth, and they work fine. Whenever I press the keybind for net worth, it closes the same stats panel if it is open, and does nothing if closed.

**Comment by gdrewb-valve** [comment]
This doesn't appear to be Mac/Linux specific so I've passed it on to the larger team.
