### ISSUE TITLE
[Linux] Prevented from matchmaking timer counts up instead of counting down

### ISSUE THREAD

**Issue by ashmew2** [ValveSoftware/Dota-2#830]
Details:

If you fail to ready up for a match , you are prevented from matchmaking for 10 minutes.
## Expected Behaviour :

You are prevented from matchmaking due to failing to ready up for 9 minute 59 seconds (Timer counts down).
## Actual Behaviour :

You are prevented from matchmaking due to failing to ready up for 8 hours 50 minutes 51 seconds (Timer counts up to 9 hours).

Steps to Reproduce on Linux:

Find a match
When ACCEPT button appears, decline it.
Press PLAY DOTA button on lower right.
See the timer.

**Comment by gdrewb-valve** [comment]
This happens on all platforms so the larger team will handle it.
