### ISSUE TITLE
Unable to connect to dota 2 servers

### ISSUE THREAD

**Issue by Sathish59** [ValveSoftware/Dota-2#833]
I've been having this problem for about a week. I'm unable to connect to any dota servers. I can find games but then a connection cannot be establisghed with the server and I end up getting a matchmaking ban. Firewall or antivirus doesn't seem to be the problem. I'm using a cable connection., so no router issues. Tried the solution -net_maxroutable 800 but didn't work.
This I what the console says when I open the game.

CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 33.986 KB [8 pkts], outgoing 1.175 KB [7 pkts]
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/play_searching) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/ui_tier_max) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/campaign_winter2016_header) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
Writing configuration for slot 0
Failed to communicate with routing cluster 'lux'.
Failed to communicate with routing cluster 'lhr'.
Failed to communicate with routing cluster 'lax'.
Failed to communicate with routing cluster 'iad'.
Failed to communicate with routing cluster 'hkg'.
Failed to communicate with routing cluster 'gru'.
Failed to communicate with routing cluster 'fra'.
Failed to communicate with routing cluster 'eat'.
Failed to communicate with routing cluster 'dxb'.
Failed to communicate with routing cluster 'atl'.
Unable to communicate with ANY Steam Datagram routing cluster.  Possible problem with local internet connection?
Failed to communicate with routing cluster 'sgp'.
Failed to communicate with routing cluster 'sto'.
Failed to communicate with routing cluster 'tuk'.
Failed to communicate with routing cluster 'tyo'.
Failed to communicate with routing cluster 'vie'.
Failed to communicate with routing cluster 'bom'.
Failed to communicate with routing cluster 'cpt'.
Failed to communicate with routing cluster 'lim'.
Failed to communicate with routing cluster 'scl'.
Failed to communicate with routing cluster 'sea'.
Failed to communicate with routing cluster 'ord'.
Failed to communicate with routing cluster 'syd'.
Slow image load -  (dimensions 32x32, took 49 msec)
Ping measurement complete.

I would appreciate any solution to the problem. Please inform me if I have to give any extra information.
Also I am able to ping the servers from my Windows console.

**Comment by gdrewb-valve** [comment]
This forum is for bugs that only occur on Mac and Linux, you'll want to post at dev.dota2.com

**Comment by gdrewb-valve** [comment]
One pointer to round this out: the particular ports used to communicate to the routing clusters are 27015-27050.  The traffic is UDP, so check that your networking setup allows UDP traffic through on those ports.

**Comment by h4k4s4m** [comment]
God damn you, I needed the answer to this. I hate a mod that closes a legit question for bureaucracy's sake.
