### ISSUE TITLE
cursor big error

### ISSUE THREAD

**Issue by Eignar17** [ValveSoftware/Dota-2#834]
new error is new update

**Comment by justSQL** [comment]
See issue #347 the last few comments already address this issue.

**Comment by gdrewb-valve** [comment]
This happens on Windows too and the larger team is already looking at it.  The current workaround is to add -cursor_scale_percent 100 to your launch options.

For data gathering can you post here with your desktop resolution and physical monitor diagonal size, whether you have any DPI/UI scaling options set in your system plus the video mode and size you're running at?  At the main menu can you bring up the console and try "check_dpi" and post what it says?

**Comment by buhman** [comment]
| key | value |
| --- | --- |
| resolution | 2880x1620 |
| diagonal | 389.5mm |
| scaling options | xft/fontconfig is manually set to 212dpi |
| video mode | borderless window; 2880x1620 |
| `check_dpi` | `SDL reports current DPI as 215.490631 (horz 215.152939, vert 216.568420)` |

---

Here I thought a ridiculously large cursor was a new feature.

> `-cursor_scale_percent 100`

Without this, the cursor goes from normal size to ~4x larger.

**Comment by gdrewb-valve** [comment]
Is this still happening if you remove -cursor_scale_percent?  The larger team tweaked the auto-scaling but I don't think there are any further changes coming.

**Comment by buhman** [comment]
> Is this still happening if you remove -cursor_scale_percent? 

Yes.

**Comment by gdrewb-valve** [comment]
@buhman, it's expected that it'll scale at 215DPI.

**Comment by gdrewb-valve** [comment]
Closing pending somebody using low DPI posting here.
