### ISSUE TITLE
SteamDatagram_InitClient()  failed to initialize steam datagram network config

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#836]
After the recent update, I am unable to run Dota

OS : Ubuntu 16.04

System Information

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 364.15
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                            50.9cm x 28.6cm  (58.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  6968 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  431676 Mb
    Largest Free Hard Disk Block:  375183 Mb
    VR Headset: None detected


```

**Comment by lordtiva** [comment]
I have the same error

**Comment by pdrocaldeira** [comment]
Same here.

**Comment by rained23** [comment]
It keep validating the game file, Is this Steam problems ?

**Comment by gu3st** [comment]
Same here. 14.04 Ubuntu

**Comment by rained23** [comment]
Are you all running Steam Beta ?

**Comment by pdrocaldeira** [comment]
I'm not.

**Comment by rained23** [comment]
Okay, I tried reverting to non beta Steam to check if its Dota2 or Steam bug.

**Comment by ericp1337** [comment]
It's a Dota 2 bug. I was playing just fine earlier today before the patch

**Comment by rained23** [comment]
Okay tested on both Beta and Non Beta. Dota2 bug indeed.

**Comment by pcactr** [comment]
It re-downloads the patch every time dota2 is launched.


The file steam is tee'ing out to has this data:

`Game update: AppID 570 "Dota 2", ProcID 29484, IP 0.0.0.0:0
ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 29486 != 29485, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197961027579 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197961027579
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20160328200724)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/home/Drax/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/username/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Video playback error (1): Failed to initialize manifest
Failed to initialize steam datagram network config.  Install is corrupted.Attempting to create OpenGL context: v3.3 (Core profile)...success.
Create window 'Dota 2' at 0,0 - 1920,1080, flags 0x16
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 570/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Game removed: AppID 570 "Dota 2", ProcID 29488 
No cached sticky mapping in ActivateActionSet.`

**Comment by cmoang** [comment]
I confirm. The problem is real! :)

**Comment by dmashuda** [comment]
Ubuntu 14.04:
Uninstalled and reinstalling now: ill update if it fixes the issue

Update:
 Uninstalling and reinstalling does not fix the issue

**Comment by DyXel** [comment]
Valve broke the game with that patch! Hopefully they will fix it anytime soon (I am afraid that this will not happen until tomorrow)

Edit:
OS: Debian Stretch/Sid x64 bits

**Comment by astroty** [comment]
Confirmed for me too
manjaro 64

**Comment by Zera99** [comment]
+1. Same thing

**Comment by gtg903w** [comment]
Ubuntu 14.04 also confirming bug. No extra information to add.

**Comment by ghost** [comment]
+1. Tried to verify local files few times but that doesn't fix issue.

**Comment by Dotarp** [comment]
+1 - Same as everyone else is saying.

**Comment by matheo** [comment]
Oh well, I was having some fun then BOOM :( broken update for my ubuntu 14.04

**Comment by gu3st** [comment]
@gdrewb-valve

**Comment by klarkc** [comment]
+1 Ubuntu 14.04 64bits.

Terminal Log:

```
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Game update: AppID 570 "Dota 2", ProcID 6507, IP 0.0.0.0:0
ERROR: ld.so: object '/home/walker/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/walker/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6510 != 6509, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/walker/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/walker/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198054521531 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198054521531
Setting breakpad minidump AppID = 373300
Installing breakpad exception handler for appid(gameoverlayui)/version(20160331191130)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "/mnt/games/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/mnt/games/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Video playback error (1): Failed to initialize manifest
Failed to initialize steam datagram network config.  Install is corrupted.
```

**Comment by ipeterov** [comment]
+1 Ubuntu 15.10 64 bit. Hope this will be fixed soon!

**Comment by bitfade** [comment]
Ubuntu 14.04 64
same ... how that's even possible for bugs like this to go unnoticed before realeasing a patch is beyond me

**Comment by ebetica** [comment]
+1 on Arch 64 bit

**Comment by 0re5ama** [comment]
same here

**Comment by klarkc** [comment]
@bitfade I know right? There is not tests for this? It seems to be occurring with everyone who use Linux.

**Comment by zentrification** [comment]
+1 Ubuntu 14.04 64bit

**Comment by brandonw** [comment]
+1 Arch 64

**Comment by ghost** [comment]
@bitfade I guess they don't check if game runs fine on Linux...

**Comment by nowylie** [comment]
+1 Arch 64

**Comment by pdrocaldeira** [comment]
@HereComesTheRainAgain Now we're sure. haha

**Comment by ghost** [comment]
@pdrocaldeira So annoying... I don't know if reinstalling whole game can change anything? I suppose error will remain... Anyone tried that?

**Comment by pfwb** [comment]
+1 openSUSE tumbleweed x86_64, AMD Radeon 7750 (radeonsi)

**Comment by ze12augusto** [comment]
+1 fedora 23 x86_x64

**Comment by pdrocaldeira** [comment]
@HereComesTheRainAgain @dmashuda is trying that but I doubt it will work. :(

**Comment by Mat9999** [comment]
+1 gentoo x86_64

**Comment by paulo-erichsen** [comment]
+1 same here

```
~ $ uname -a
Linux Daemon 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

**Comment by dmashuda** [comment]
I tried reinstalling. It did not work :(

**Comment by DyXel** [comment]
@bitfade 
"Linux is the future of Gaming" -Gabe Newell

And they do not even check if the game runs on Linux...

**Comment by dsimmie** [comment]
+1 Ubuntu 14.04 64bit

**Comment by ghost** [comment]
@DyXel They probably assume that Linux is perfect and everything will run just fine. xD

**Comment by Storm-Engineer** [comment]
+1 on both normal and beta. So far nothing I tried worked.

Arch Linux 64 bit

**Comment by chadq** [comment]
instead of 6.87 we get a broken client.

**Comment by pdrocaldeira** [comment]
"They don't care about us"

JACKSON, Michael

**Comment by DyXel** [comment]
@HereComesTheRainAgain I am pretty sure that the problem is not Linux, they are probably wondering what is happening. Do you guys think that this affects Valve servers? Because most of the servers runs on Linux nowadays...

**Comment by EncodedBird** [comment]
@DyXel Its just the Linux client most likely, I doubt it does affect the server, else the windows version would have issues as a result.
also +1 archlinux 64 bit

**Comment by ghost** [comment]
@DyXel I guess that servers are fine because Windows users can play Dota... My friend updated the game and launched it normally. I updated the game, verified cache, and error occured...

**Comment by klarkc** [comment]
Do you think they will make a hotfix still today?

**Comment by AbuShawarib** [comment]
Ok guys it's confirmed. Just wait till someone sends the patch for the game.

**Comment by klarkc** [comment]
The best is to hear "Just Install windows motherfuc$%#@" from my friends who are waiting me to join party xD. That's your fault Mr. Newell.

**Comment by nelsongc** [comment]
same problem in Elementary OS
Linux LinuxDev 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ghost** [comment]
@klarkc Probably, this wasn't major update, so I think that it couldn't cause big issue... But who knows... Hope that fix will come soon.

**Comment by immortal-tofu** [comment]
Same here on Linux Mint.
![image](https://cloud.githubusercontent.com/assets/1384478/14578118/db8e4dd8-037f-11e6-8c31-0b24ff57cb7a.png)

**Comment by Storm-Engineer** [comment]
@AbuShawarib I don't call it confirmed until I see a valve employee posting that they are aware and working on it. Until that keep blowing the horns and hitting the drums. Breaking their own most hyped game on a whole platform is kind of a major fail.

**Comment by ghost** [comment]
Ditto; Ubuntu 15.10

**Comment by pyarmak** [comment]
Same result here Arch linux x64.

**Comment by kaioduarte** [comment]
Same thing here Fedora 23 x64

**Comment by habibiefaried** [comment]
Same here bro. 
It's weekend, nice moment to play dota. aand
.
.
.
.
.
.
.
Now, I can't run dota >.<
I hope valve fix this bug as soon as possible

-Cheers from ubuntu 14.04

**Comment by iomtt94** [comment]
i have same problem on ubuntu 15.10(x64)

**Comment by soriac** [comment]
Same error, Manjaro 15.12 x64

**Comment by iomtt94** [comment]
ty vovlo

**Comment by ysfalo** [comment]
same error , ubuntu 14.04

**Comment by Storm-Engineer** [comment]
CRITICAL!
@danginsburg @gdrewb-valve @triage-valve

**Comment by ghost** [comment]
What do you guys think about posting this issue on their official fb page or somewhere they can see it?

**Comment by Storm-Engineer** [comment]
Don't tell me they are not looking at the bug tracker after an update...

**Comment by ghost** [comment]
It could be the case, maybe they didn't tested this minor update on Linux...

**Comment by ze12augusto** [comment]
This error is caused by wrong file path.
Dota is looking for file in '~/.local/share/steam/steamapps/common/dota 2 beta/game/core/cfg/network_config.json' but that file not exists.
I fix this bug creating a link for the correct file to wrong dota path.
'ln -s ~/.steam/steam/steamapps/common/dota\ 2\ beta/game/core/cfg/network_config.cached.json ~/.local/share/steam/steamapps/common/dota 2 beta/game/core/cfg/network_config.json'
Same thing for cache file

**Comment by habibiefaried** [comment]
@ze12augusto where is the cache file?

**Comment by pcactr** [comment]
My install has network_config.json in the right spot -- still doesn't work.

**Comment by habibiefaried** [comment]
same as @pcactr

**Comment by Plagman** [comment]
We're looking into this now, I'll update the bug when there's news, thanks!

**Comment by klarkc** [comment]
@ze12augusto For me, the file exists, but still the error persists.

How do you know where Dota is looking for files?

**Comment by Nadhum** [comment]
Let's hope Valve learns a lesson from this.

**Comment by bitfade** [comment]
the problem is the case, just symlink 

steam/steamapps to Steam/SteamApps

and it works.

**Comment by Plagman** [comment]
We just deployed a hotfix to the game depot; can people that are affected by the issue download the update and try again?

**Comment by pcactr** [comment]
Yeah, confirmed on the case-sensitivity.

from strace:

`31294 open("/home/username/.local/share/steam/steamapps/common/dota 2 beta/game/core/cfg/network_config.json", O_RDONLY <unfinished ...>
31294 <... open resumed> )              = -1 ENOENT (No such file or directory)
31294 open("/home/username/.local/share/steam/steamapps/common/dota 2 beta/game/core/cfg/network_config.cached.json", O_RDONLY <unfinished ...>`

**Comment by aresch** [comment]
Just updated, but still experiencing the issue.

**Comment by pyarmak** [comment]
Same, downloaded, same issue.

**Comment by perrymacneill** [comment]
It's fixed for me now on Ubuntu 15.10

**Comment by ghost** [comment]
@Plagman Fixed on Ubuntu 14.10

**Comment by juston-li** [comment]
Works fine on Arch now, thanks!

**Comment by pcactr** [comment]
Hotfix did nothing on Fedora.

@ze12augusto was missing case-sensitivity in his post, but he was pretty close.

If you symlink `Steam/steamapps/common/dota\ 2\ beta/game/core/cfg/network_config.json` to `steam/steamapps/common/dota\ 2\ beta/game/core/cfg/network_config.json` it will launch without an error, but will not properly go into fullscreen.

**Comment by dsimmie** [comment]
Fixed on Ubuntu 14.0.4

**Comment by jasontduncan** [comment]
@Plagman I'm running Ubuntu 14.04x64 Downloaded the hotfix, and the game loads. Thanks!

**Comment by pyarmak** [comment]
Arch = fixed

**Comment by gu3st** [comment]
@Plagman Works for me now.  14.04x64

**Comment by klarkc** [comment]
I don't know if I've downloaded the right update (It was a "validating" download). But still not working.

The @bitfade workaround did not fixed here.

**Comment by aresch** [comment]
Downloaded another update and it works now for me.

**Comment by DyXel** [comment]
Debian 8 Stretch/Sid x64 = Fixed!

Thank for the hotfix. Please test the patches everytime! Specially on the future platform of gaming!

**Comment by pcactr** [comment]
Now I have an alternate issue with xfce panels on top of Dota2 when set to "Borderless Window"

**Comment by f-hipolito** [comment]
The hotfix solved. Thanks.

**Comment by Mat9999** [comment]
fixed on Gentoo Linux x86_64. Thanks

**Comment by nh2** [comment]
> I don't know if I've downloaded the right update (It was a "validating" download). But still not working.

@klarkc No, `validating` is not a real update. You should see a real download, roughly under 1 MB.

**Comment by dmashuda** [comment]
Ubuntu 14.04 Fixed. Thanks for the quick response Valve!

**Comment by astroty** [comment]
Manjaro = fixed

**Comment by Plagman** [comment]
Thanks for confirming, I'll close this issue now; please open other issues as needed for any issues related to fullscreen, etc.

**Comment by nh2** [comment]
@Plagman If I may ask (out of interest), did you notice that problem before you commented, or did it really only take 8 minutes between the start of the investigation and the rollout of the hotfix?

Admittedly, having a community of thousands of gamers who are all pressing F5 on a Github issue AND know what `strace` is probably makes it a bit easier, but still, 8 minutes would be pretty impressive.

**Comment by klarkc** [comment]
Fixed here (Ubuntu 14.04) after the update.

**Comment by Storm-Engineer** [comment]
Thank you!

But next time please check before pushing patch. :3

**Comment by ghost** [comment]
Fix confirmed

**Comment by nelsongc** [comment]
it works after update, thank you!!!!
