### ISSUE TITLE
[OSX 10.11.4] Artifacting again 

### ISSUE THREAD

**Issue by gxgani** [ValveSoftware/Dota-2#837]
This used to happen with the previous source engine and this happened again when I launched the game, switched my space to desktop. Focused window on iTunes/Firefox and then back to game.

Here's the screenrecord:
https://cobalt60.xyz/shared/Screen-Recording-2016-04-16-16-09-55.mp4

**Comment by danginsburg** [comment]
The only thing I can think of here that could be us is that we use client texture storage and perhaps there is memory corruption and when the OpenGL driver tries to restore textures from our memory it is corrupted.  Does it still happen if you run with +gl_texclientstorage 0 on your command line?  Can you also please post Steam -> Help -> System Information so we can try to repro?

**Comment by gxgani** [comment]
I could not replicate it (almost opened dota a lot many times after this mishap). But it was totally random. Usually list the spec out but forgotten it this time.

Macbook Pro / OS X 10.11.4
i7/Intel HD4000 
8GB RAM

**Comment by danginsburg** [comment]
So you are saying it does not repro with +gl_texclientstorage 0 or simply that it happens very randomly and you can't repro it in general?  I do have an HD 4000 so I will try to repro it myself.

To be honest, this seems very likely to be an OS X driver issue.  I'm a bit grasping at straws, but the only thing I can think of with regard to texture memory that we control is for the textures backed with client texture storage enabled.

**Comment by gxgani** [comment]
It never happened after moving to Source Engine 2. This is the first time, but I'll keep a lookout without having the argument being passed to see if it's reproducible.

**Comment by danginsburg** [comment]
OK, be aware the game will use more system memory with that option

**Comment by gxgani** [comment]
When at the all pick screen, If I move to a different space (ctrl+arrows), I either notice a micro freeze or a freeze followed by a CTD or this which happened out of no where (https://gfycat.com/DirectInfiniteBluetickcoonhound)

PS: I am running the same configuration with no changes in the settings.

**Comment by gdrewb-valve** [comment]
Is this still active?
