### ISSUE TITLE
[Linux]If console is opened while in a game, it cannot be closed, and game buttons cannot be pressed, requiring a force close of the game

### ISSUE THREAD

**Issue by Kirov123** [ValveSoftware/Dota-2#84]
The close button for the console does not work, and the console is on top of every game element, and so no game buttons can be pressed either.

**Comment by gdrewb-valve** [comment]
Can you type in the console?  As a workaround 'toggleconsole' should close the console.

**Comment by jeifour** [comment]
Same problem I always have with Csgo, grown accustomed to using toggleconsole by now.

**Comment by Kirov123** [comment]
Using toggleconsole does work to get around that.

**Comment by gdrewb-valve** [comment]
The console is going to get updated to the new UI style so not much work is going into it right now.

**Comment by gdrewb-valve** [comment]
Does this still happen?

**Comment by gdrewb-valve** [comment]
Closing as the console behavior is not platform-specific.
