### ISSUE TITLE
Create list of libraries that we need to have

### ISSUE THREAD

**Issue by Cynede** [ValveSoftware/Dota-2#841]
For example I just googled this one https://github.com/ValveSoftware/Dota-2/issues/108

`libtxc_dxtn`

but it will be nice to have them all in one place, I can't find such list for now

**Comment by danginsburg** [comment]
libtxc_dxtn is a driver-specific requirement for mesa on certain Linux distros.  There should otherwise not be external dependencies outside of the steamruntime.

**Comment by Cynede** [comment]
@danginsburg ... honestly I'm not agreed with closing this
Even when it's driver-specific everything should be clear
Users should not google for error message like I did
