### ISSUE TITLE
Dota 2 won't start since today

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#842]
Yesterday Dota 2 was working fine, I've made no updates since yesterday (means state of my machine has not changed one bit), yet since today Dota 2 doesn't work. Was there some minor update or something?

This is the error I get :
`libGL error: unable to load driver: i965_dri.so`

Details:
https://gist.github.com/gutigen/26ae45864d3b2585dd44606d8d405a02

Running up to date Arch on Intel 4400:
https://gist.github.com/gutigen/029471ee2596650b5ef11af2a2e425da

I've tried with Steam Runtime OFF, but then I get `pangotf2-1.0.so` missing error (which I have installed for 64 and 32 bit, even tried preloading it, no go).

**Comment by Phidelux** [comment]
Same here. And yes, there was a minor update and after this it tells me that the Dota2 Reborn client is running, but the client doesn't show up. Getting the same error on Arch with Intel graphics. Output of "LIBGL_DEBUG=verbose steam":

```
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/i965_dri.so
libGL: dlopen /usr/lib/xorg/modules/dri/i965_dri.so failed (/usr/lib/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/swrast_dri.so
libGL: dlopen /usr/lib/xorg/modules/dri/swrast_dri.so failed (/home/awilhelm/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/xorg/modules/dri/swrast_dri.so))
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

This seems to be a compatibility issue as Steam includes libstdc++ (the C++ standard library), but has a version that is incompatible with the mesa driver. So maybe a downgrade would fix this issue?

**Comment by LiranV** [comment]
Same problem here (Arch + AMD R9 290).

**Comment by todorovbg** [comment]
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Arch - Nvidia540m

**Comment by Tele42** [comment]
This sounds like fallout from arch updating from libgcrypt 1.6.5 -> 1.7.0, which would make this related to https://github.com/ValveSoftware/steam-for-linux/issues/4410.

**Comment by todorovbg** [comment]
Downgrading to libgcrypt 1.6.5 seems to fix the issue for now. Thanks

**Comment by danginsburg** [comment]
@gutigen Can you confirm the problem you have is also with libgcrypt (see ValveSoftware/steam-for-linux#4410)?  If not, please post your bug on the steam-for-linux tracker as the issue is not specific to Dota 2.

**Comment by LiranV** [comment]
Also working here after downgrading to libgcrypt 1.6.5

**Comment by blzq** [comment]
Adding '/usr/$LIB/libgpg-error.so' to LD_PRELOAD for steam instead of downgrading also fixed it for me (Arch).

**Comment by Phidelux** [comment]
@blzq Adding LD_PRELOAD=/usr/$LIB/libgpg-error.so also worked for me. Now the Exec section of my steam desktop file looks like this:

`Exec=env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam %U`

**Comment by ghost** [comment]
@danginsburg Yes, I can confirm that downgrading libgcrypt solves the issue.

**Comment by satyarth** [comment]
Downgrading libgcrypt fixed the problem for me too. Thanks!

**Comment by danginsburg** [comment]
OK, I will close this bug here, the right place to track this is ValveSoftware/steam-for-linux#4410
