### ISSUE TITLE
OSX graphic slow as hell after update.

### ISSUE THREAD

**Issue by crapthings** [ValveSoftware/Dota-2#843]
fps drops

MacBook Pro (Retina, 15-inch, Mid 2015)
AMD Radeon R9 M370X 2048 MB

**Comment by abacuscode** [comment]
same here. single-digit fps while playing last night

MacBook Pro (Retina, 15-inch, Early 2013)
NVIDIA GeForce GT 650M 1024 MB

**Comment by danginsburg** [comment]
There is not enough information here for me to repro the problem.  I just tried on the latest version of Dota 2 on my GT650M MBPr Mid 2012 running a botmatch at 1440x900 highest quality settings Desktop Friendly Fullscreen and it is running at ~50fps solidly.  Can either of you provide more detailed repro instructions?

**Comment by abacuscode** [comment]
I was playing in a bot match with 2 other people.

I forgot to add additional hardware...
Dell P2715Q Monitor
Logitech G502 wired mouse
Apple Wireless Keyboard

Additional programs running: Skype

I can double-check the screen resolution and video settings later when I am able to take a look.

**Comment by crapthings** [comment]
there're four fullscreen modes, the first one fix for me.

**Comment by danginsburg** [comment]
I think you are suggesting going from Desktop Friendly Fullscreen to Exclusive Fullscreen fixed the issue for you.  That's good, but I'm unable to repro this.  If someone can provide repro instructions feel free to comment and I'll reopen, but closing for now.

**Comment by abacuscode** [comment]
I will try the different full screen modes. Mine is at Desktop Friendly Fullscreen as well. Changing my video settings to "fastest" improved the frame rate to about 20-30. Thanks!

**Comment by crapthings** [comment]
after 6.8.7 update

frame rate drops, switched each options, with lowest settings

still slow as hell
