### ISSUE TITLE
Dota 2 Mac Start Up 

### ISSUE THREAD

**Issue by EmersonSnow** [ValveSoftware/Dota-2#846]
Basically, after the latest update whenever I start Dota 2 I get the following error dialogue - Source 2 Warning - Only one instance of the game can be running at one time.

**Comment by EmersonSnow** [comment]
I'm no longer getting this issue after I updated my Mac, this was either fixed in another update or is version specific.

**Comment by gdrewb-valve** [comment]
OK, closing.  This may be an instance of #793 where a previous run of Dota didn't exit.  When you restarted your Mac that would have gone away.
