### ISSUE TITLE
Dota does not start since the 6.87 update

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#848]
hi,
I am having an issue with dota no starting at all. When I launch it from the steam library tab it shows the logo for a moment and then just this:
https://ibin.co/2f6MoNW59ReV.png
The blue frame and everything around it is from my window manager and at the bottom there is half of dmenu visible, the slightly shifted grey plane is from dota2.
While in this state, the only way to close dota2 is a sigkill, sigterm is not enough.
Sofa I have tried to verify the game cache. I am not sure it found any mistakes but it queued a 0 Byte update (it still took a few seconds to download). Unfortunately this did not fix it.
I am now looking into updating libraries used by dota2, did anything in that regard change with the 6.87 update?

E: updating glibc did nothing.

E2: what I found so far
librendersystemgl.so:
libudev.so.0 => not found
libsoundemittersystem.so:
libtier0.so => not found
libvstdlib.so => not found

I currently have libudev 215 installed, libtier0.so and libvstdlib.so are located in bin/linuxsteamrt64 so I assume it is doing some preload magic for them.
When I run ./dota.sh is directly complains about libudev.so.0 "
"librendersystemgl.so" error=libudev.so.0: cannot open shared object file: No such file or directory"

E3:
Ok, for some reason ./dota.sh does not use the steam runtime and the steam runtime is necessary for libudev.so.0.

E4:
If I start steam from the terminal it decides to use the steam runtime and then fails horribly when it is trying to use LD_PRELOAD with 32bit libraries on a 64bit system.
ERROR: ld.so: object '/home/turmfalke/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

E5:
Ok for some reason steam keep insisting that:
STEAM_RUNTIME has been set by the user to: /home/turmfalke/.local/share/Steam/ubuntu12_32/steam-runtime
even if I start steam with STEAM_RUNTIME=1.
I have tried forcing it to use  ubuntu12_64 by changing the script and then making it immutable to prevent the self integrity check from succeeding. Unfortunately it than claims to not have enough space to unpack the runtime - even when that is clearly not the case.

E6:
Thought I would give reinstalling steam an attempt instead of just using steam --reset. I assumed I would be able to prevent downloading everything by keeping the SteamApps folder. Unfortunately Steam has a hard time deciding whether the folder should be called SteamApps or steamapps. I have no symlinked steamapps to SteamApps, but for some reason Steam has deleted about 4k files from my dota installation. Redownloading these now.

E7:
Had another look at the steam.sh script, apparently the 64bit steam runtime is hiding in the ubuntu12_32 directory and does not as the name would suggest gets downloaded into ubuntu12_64.  LD_LIBRARY_PATH then contains all runtimes in the hope that the correct one is one of them. So failing when loading a 32bit library is intended behaviour and it is expected to find the 64bit one after that.
Now the best indication on what is going wrong is a warning from Fontconfig:
Fontconfig warning: "/home/turmfalke/.local/share/Steam/SteamApps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
followed by an error from fontconfig (which I assume should not be terminal):
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element

and the very generic:
Video playback error (1): Failed to initialize manifest

E8:
Ok, the fontconfig error comes from the fact that the fontconfig in the runtime is ancient and can't handle the newer features used in my systems default config.

**Comment by jordanlm** [comment]
I'm having the same problem, except my game looks like this:
https://ibin.co/2f8QJjtNte4U.jpg

**Comment by danginsburg** [comment]
The libudev.so.0 would have prevented things from running, but the fontconfig and video playback errors should not be causing a problem.  Can you please run with -con_logfile and post game/dota/console.log?  Could you also post Steam -> Help -> System Information.  I haven't been able to repro this here.

**Comment by Turmfalke2** [comment]
hi @danginsburg
I noticed that I had an old nvidia driver pinned and decided to update it first. This is my System information now: http://pastebin.com/Yx3DEthN
I am using 4.5.0 NVIDIA 361.28 now and when I try to start dota 2 I get:
"Missing basic OpenGL v1.0 -> v2.0 required OpenGL functionality."

E2:
Ok, I can work around the Missing basic OpenGL bug with exporting __GLVND_DISALLOW_PATCHING=1
After that I encounter the old bug again, console.log: http://cxg.de/_7b2268.htm

**Comment by danginsburg** [comment]
So the part with __GLVND_DISALLOW_PATCHING=1 is a duplicate of #756.  There is nothing in the console log to suggest a problem, can you provide a callstack of the crash from gdb or a crashdump?

**Comment by Turmfalke2** [comment]
@danginsburg 
As expected, I don't have debug symbols:
http://cxg.de/_11c964.htm

E2:
Also there is no 'crash' it just gets stuck while starting.

E3:
All the threads:
http://cxg.de/_547789.htm

E4(Mo 2. Mai 22:55:06 CEST 2016):
small update, if I open dota2 and the moment the window appears switch to another tag (so it isn't visible) I get to hear a few sound effects from the main screen/lobby. If I then try to switch bag it fails to render anything.

**Comment by Turmfalke2** [comment]
@danginsburg Breakthrough!
Given that my window manager is probably the most exotic program I use with dota2 I decided to test it with a more common one. For that installed i3 and to my amazement dota2 started just fine.
Now it turns out it isn't actually my window managers fault, but that fact that I usually don't launch programs as full screen.
So what ever is causing this issue is related to resizing the window. If I tell my wm to turn it full screen while the dota2 logo is still visible the game launches fine, if at any point later I decide bring it back into windowed mode the game freeze/locks up. For now I am going to add a rule to my window manager to always start dota 2 in full screen, but I would appreciate a fix for this issue. It used to work just fine in windowed mode.

**Comment by danginsburg** [comment]
What window manager were you using prior to i3?  If you were using xmonad this is a duplicate of #552.

**Comment by Turmfalke2** [comment]
@danginsburg herbstluftwm and it does not appear to be directly related to the wm, but rather to not running it as fullscreen.
E: https://github.com/herbstluftwm/herbstluftwm

**Comment by gdrewb-valve** [comment]
Assigning an SDL dev as this sounds similar to the other issues here where things have trouble with window changes.

**Comment by Turmfalke2** [comment]
closing, has been fixed for a long time
