### ISSUE TITLE
[Mac] Multiple rapid inputs slow to process

### ISSUE THREAD

**Issue by gramathy** [ValveSoftware/Dota-2#85]
Lots of ingame inputs (this doesn't seem to affect UI interactions, only unit commands and camera movements) result in later inputs taking longer to be expressed compared to earlier inputs. Allowing the game time to catch up "resets" the input lag but subsequent random inputs will start out responsive and get progressively laggier until the game is allowed some time to catch up again.

**Comment by gdrewb-valve** [comment]
Can you post your system info?

**Comment by gramathy** [comment]
I'm not sure it doesn't affect UI inputs actually, it seems to sorta do the same thing if you rapidly move the cursor around the Heroes screen on the main menu but it's harder to tell.



System specs:


```
Processor Information:
    Model:  MacPro3,1
    Vendor:  GenuineIntel
    Speed: 4.30 Ghz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    MacOS 10.10.3 (14D136)
    
Video Card:
    Driver:  NVIDIA GeForce GTX 980

(actual driver version: 346.01.02f04, current updated web driver)

    Driver Version:  1.2
    Driver Date: 0  0
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x1183
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary VRAM: 4095 MB
    
Memory:
    RAM:  16384 Mb
    
    
Installed software:
    
```

**Comment by gramathy** [comment]
Link to video of bug:

https://www.dropbox.com/s/c8vsaqunukizdph/2015-06-24%2019-58-24.mp4?dl=0

**Comment by bklooster** [comment]
I can also report very laggy inputs on my mac as well and it seems to get worse as the client remains in use. The best situations that I found to show how laggy it can be is to enable camera panning with mouse (my middle mouse button) and moving. You can see significant delay and latency there as you're moving. I also see it when trying to select creeps or trees especially. 

My hardware: https://gist.github.com/bklooster/6026046

**Comment by gramathy** [comment]
This is fixed for me in most recent patch.

**Comment by gramathy** [comment]
Any luck tracking this down? It seems like it's forcing each input to "finish" before processing the next. or something.

**Comment by gdrewb-valve** [comment]
Unfortunately no.  This appears to not be a Linux/Mac issue as there are complaints on Windows also about laggy input so the investigation has moved into the larger team.

**Comment by gramathy** [comment]
I messed around a little more and this seems to also happen with just normal mouse movements - the hardware cursor is where it should be but each individual mouse movement is delayed progressively more as more inputs are added to the stack. Can replicate this part of it by going to heroes tab and moving mouse in a circle on the empty space to the left, then moving the mouse into the area with the hero portraits - the first portrait popup is delayed relative to how long you were moving the mouse around.and then the bug is evident as before.

**Comment by gdrewb-valve** [comment]
The August 3 update had a change to try and throttle things a bit to avoid input getting too delayed.  It's not a fix but hopefully would tighten things up a bit, did it make any difference for you?

**Comment by gramathy** [comment]
I'm at TI so I don't have my Mac until I'm back. Trying to recreate this over teamviewer isn't really possible unfortunately due to limitations on how it sends input to the far end (I've tried). So I'll be able to tell you Sunday.

**Comment by gdrewb-valve** [comment]
No rush, thanks for giving it a try.

**Comment by gramathy** [comment]
Still doing it :( the change doesn't seem to have made any difference that I can tell.

**Comment by gdrewb-valve** [comment]
That's unfortunate, thanks for trying it out.

**Comment by gramathy** [comment]
Seems to be working ok now with the 8/13 patch, did you guys change something?

**Comment by gdrewb-valve** [comment]
It's possible the change I was thinking of didn't actually make the previous update, but I'm not sure that's the answer.  I don't know of another specific change in this area, so we'll have to wait and see if it keeps working and if so I'll close this out.

**Comment by gdrewb-valve** [comment]
I assume there haven't been any further problems?  Closing this.

**Comment by dphildebrandt** [comment]
I'm having a similar issue, seems to happen in both the Reborn and Main client.

```
Processor Information:
    Model:  MacBookPro11,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel Iris

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0xa2e
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.22" x 7.05"  (13.23" diag)
                                            28.5cm x 17.9cm  (33.6cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  16384 Mb
```
