### ISSUE TITLE
Custom Hotkeys not allowed

### ISSUE THREAD

**Issue by SuperFlick** [ValveSoftware/Dota-2#850]
Cant set custom hoykeys on linux (xubuntu 15.04). This thing with skills just doesnt appear
![2016-04-30 14 12 41](https://cloud.githubusercontent.com/assets/13034633/14934794/3d37e2b0-0ede-11e6-9998-d1fca01bdcff.png)
![2016-04-30 14 12 45](https://cloud.githubusercontent.com/assets/13034633/14934793/3d37cc08-0ede-11e6-8979-661db3cf3e0e.png)
![2016-04-30 14 12 48](https://cloud.githubusercontent.com/assets/13034633/14934795/3d38487c-0ede-11e6-8eef-6eabe731b215.png)

**Comment by danginsburg** [comment]
This is fixed in the latest update.  Please comment if you are still seeing the bug and I can reopen.

**Comment by SuperFlick** [comment]
I didnt played dota last month, so mb it was fixed. but now i see this checkbox does nothing. Still doesnt work in my case.
