### ISSUE TITLE
In the Itemshop rightclicks sometimes are not recognized correctly.

### ISSUE THREAD

**Issue by hipunk** [ValveSoftware/Dota-2#851]
Hi,

I am experiencing an issue since a few patches (I think it got introduced in one of the later versions of 6.86), where right clicking an item in the item shop sometimes gets not recognized. I feel/see, that this issue is somewhat related to the lagging/unclean animation that is being made when opening up the shop (the shop slides in from the left of the screen so that it becomes accessible).
It also may be somewhat related to moving into shop range, because this happens most of the time I approach a secret or a side shop, the button becomes/is about to become active, but I already clicked the shop on the map (!) to open it up. Then immediately after right clicking an item, it doesn't recognize the click sometimes and you either have to click twice or fail. 

It's quite annoying because when you run from people, wish to save the cash by running to the side shop and you actually made it all happen correctly, but the damn client bugged again and you lose the money.

**Comment by gdrewb-valve** [comment]
You didn't post system information but this has been reported on all platforms and will be handled by the larger team.
