### ISSUE TITLE
[Linux] Dota hidden?

### ISSUE THREAD

**Issue by Azura-Soren-Yuuki** [ValveSoftware/Dota-2#852]
A note of forewarning: I have not run into many errors, and not done too much servaying, so if you need something, try asking me (and telling me what to do), as I may be slow to catch on, and do not know what exactly is needed. Sorry in advance, and thank you~!

I recently updated my computer to Ubuntu Gnome 16.04 and since then the game has an error. I startup the game, in expectation of seeing the splash, and no window displays.  When I check my steam status (IE friends list playing) it says I am playing Dota. I figured this was an install error, and verified the cache. Upon it's not working the second time, I reinstalled.  I open terminal and run pgrep dota, and the process is running.  Upon killing the process, steam no longer says I am playing Dota.  I am unsure as to what I should do, as the game is apparently running, but not displaying its window, or GUI.

(small edit in here)
I followed the path to
~/.steam/steam/steamapps/common/dota\ 2\ beta/game/dota.sh
and ran it.  Upon running I recieved the error:
LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011'!

(second edit)
I did a bit of research, and all of them were leading towards the steam runtime/bootstrap being missing?  Is this still a pertinent issue?

Thanks again!
      --Azura

**Comment by codetorex** [comment]
Try downgrading libgcrypt and lib32-libgcrypt to v1.6.5 or something. In ubuntu I think you can do that with `sudo apt-get install libgcrypt20=1.6.5-2` but I didn't tested though, hope it helps :)

**Comment by Azura-Soren-Yuuki** [comment]
my libgcrypt was already that version. Thanks though...
I think the error has to do with the bootstrap, because most of the errors that I have been running into other people having have the symptom of `steam --restart` returning "couldn't find bootstrap, it's not safe to restart steam"... Which returns the same here, but all the "fixes" that I have encountered do not work? O.o?

**Comment by codetorex** [comment]
https://wiki.archlinux.org/index.php/Steam/Troubleshooting there is section for 'Deleting the runtime libraries' which may help.

**Comment by Azura-Soren-Yuuki** [comment]
Thanks soo much! This got it for me (for future reference for anyone):
`find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete`

If there were +points I would give them <3
You are a lifesaver, thanks!

**Comment by codetorex** [comment]
Glad it did work! By the way don't forget you might have to do it again when steam updates :)
