### ISSUE TITLE
[Linux] Dota 2/Steam crash and key binding issues

### ISSUE THREAD

**Issue by codeInTheShell** [ValveSoftware/Dota-2#853]
Every time I try to customize my game settings Dota crashes including steam. I could partially apply a few settings at the first game launch and now every once in a while maybe 1 out of 100 attempts or more. I thought maybe it's a bug related to Skylake so I installed kernels from the repo and compiled a few by hand but without resolving the issue ( 3.19.0-32, 4.4.0-18, 4.4.0-21).

Then I thought I could configure this by hand but it appears that none of the configs in 
$HOME/.steam/steam/steamapps/common/dota 2 beta/game/dota/cfg
contain any type of configuration done by the user/me which is really awesome because manually changing them doesn't change any state (the game not crashing or functions being bound to different keys) nor can you reuse Windows configurations without making the game fail to launch at all (besides Window using a different config style).

Then I had a look at your logs and found an exception which was raised as soon as Dota panicked and killed Steam with it:
../common/pipes.cpp (765) : Fatal assert failed: ../common/pipes.cpp, line 765.  Application exiting.
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:765

And some segfault in the syslog:
May  1 09:25:56 kernel: [34047.459921] CIPCServer::Thr[2842]: segfault at 0 ip 00000000f74a8770 sp 00000000ee706088 error 4 in libc-2.19.so[f7375000+1a8000]

And some more in dmesg:
[34139.849713] CIPCServer::Thr[23226]: segfault at 0 ip 00000000f73c0770 sp 00000000ee61e088 error 4 in libc-2.19.so[f728d000+1a8000]

And in between I wanted to look at things from a different perspective, with different launch parameter options, then the full screen option was gone as well and since the rest doesn't work it's also not reconfigurable. 
Reinstalling steam or the Dota did not help, which is why I end up here as I am out of ideas.

Oh and besides having this issue, which anger me a lot, I also can't bind quick purchase to an alternative key and other keys such as ^ binding to score board, meaning that the basic functionality of the settings don't work independent of the application crapping itself. I tested these functions with another keyboard from a different manufacturer, so it's not a driver related problem as the issues still persist.

**Comment by danginsburg** [comment]
Are you able to provide a crashdump or crashdump ID?  If you could provide specific steps to repro that would help too.

**Comment by codeInTheShell** [comment]
Reproduction is just clicking the gear icon for the game settings inside Dota 2.
Since I can't upload for unknown reasons here is the ID:
CrashID=bp-3b00fa8d-a693-4fb7-9d39-f42602160504

I also noticed that the time zone is incorrect and not configured as on the local host which should be CEST or if GMT it should be GMT+2.

Wed May  4 20:05:46 2016 GMT: file ''/tmp/dumps/assert_20160504220446_1.dmp'', upload yes: ''CrashID=bp-3b00fa8d-a693-4fb7-9d39-f42602160504''
$date
Wed May  4 22:07:42 CEST 2016

And if hardware specs are necessary it's a NUC6i5SYK.

`
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x4e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  1801 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17.3 Rosa (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Skylake ULT GT3 x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.5.9
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x1926
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,08" x 11,30"  (23,03" diag)
                                        51,0cm x 28,7cm  (58,5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Skylake HDMI

Memory:
    RAM:  14994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  218337 Mb
    Largest Free Hard Disk Block:  124827 Mb
    VR Headset: None detected  
`

**Comment by danginsburg** [comment]
Thanks I found the crash dump.  It seems the crash is inside of OpenAL initializing your microphone.  We will look into it.

**Comment by codeInTheShell** [comment]
Now that you mention it I did make use of the "Test microphone" function in the settings. The default device is "Pulseaudio Default" which leads to an instant crash of steam.
Out of all options the only one that didn't lead to Steam crashing was with input device set to "HDA Intel PCH [ALC283 Analog](hw:0,0) via ALSA"
Seems like the audio jack in the front is only recognized via ALSA.

I should also mention that I have had the issue with stable release and the beta of Steam.

Besides you investigating this, and me having a workaround for the time being, there are still key bindings which do not work or don't work properly.
- scoreboard does not stay visible as long as the configured key is pressed 
- ^ is nowhere accepted
- sticky quick purchase does not work no matter what key is set
- the configuration files in the cfg folder do not contain the user configuration but default settings (at least regarding key bindings)

**Comment by gdrewb-valve** [comment]
You should open different entries for different issues.  However some of your key binding issues appear to be the same as #268 and don't need a new entry.  Some of the configuration issues are not Linux/Mac-specific too so things may be covered.

**Comment by gdrewb-valve** [comment]
For the audio crash it's in the Steam voice support so we've passed this on to the Steam team.
