### ISSUE TITLE
[LINUX] Unable to close the MVP VOTE RESULTS window

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#854]
Hi there,

I cannot close the  MVP VOTE RESULTS window by clicking X. The button gives the impression of being pressed but nothing happens and I have to kill the process and restart the game.

System info:

> Computer Information:
>     Manufacturer:  Unknown
>     Model:  Unknown
>     Form Factor: Desktop
>     No Touch Input Detected
> 
> Processor Information:
>     CPU Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x3a
>     CPU Stepping:  0x9
>     CPU Type:  0x0
>     Speed:  3800 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
>     AES:  Supported
>     AVX:  Supported
>     CMPXCHG16B:  Supported
>     LAHF/SAHF:  Supported
>     PrefetchW:  Unsupported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     "Arch Linux" (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.5.1-1-ARCH
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11803000
>     X Window Manager:  Xfwm4
>     Steam Runtime Version:  steam-runtime-release_2016-02-23
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
>     Driver Version:  4.5.0 NVIDIA 364.19
>     OpenGL Version: 4.5
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 59 Hz
>     VendorID:  0x10de
>     DeviceID:  0x13c2
>     Number of Monitors:  1
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1200
>     Desktop Resolution: 1920 x 1200
>     Primary Display Size: 20.39" x 12.76"  (24.02" diag)
>                                             51.8cm x 32.4cm  (61.0cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 4096 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: VIA VT2020
> 
> Memory:
>     RAM:  11976 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_GB.utf8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  48966 Mb
>     Largest Free Hard Disk Block:  19515 Mb
>     VR Headset: None detected

**Comment by danginsburg** [comment]
Thanks, this issue is not platform specific, but I have passed it along to the larger team.  This tracker is for Linux/OS X-specific issues.
