### ISSUE TITLE
[Linux] No response after choosing best player after watch dotatv ingame.

### ISSUE THREAD

**Issue by Tungzzz** [ValveSoftware/Dota-2#855]
No response after choosed best player/ Looks like menu controls didn't  response on clicks.
Only killing app is helpfull.
![2016-05-03 17-38-56](https://cloud.githubusercontent.com/assets/13603284/14986861/9aed58a4-115e-11e6-8771-ac0d25d28e64.png)
![2016-05-03 17-35-45](https://cloud.githubusercontent.com/assets/13603284/14986867/a922492a-115e-11e6-8d5d-609e28ae9763.png)

**Comment by Tele42** [comment]
Possible duplicate of #854.

**Comment by Tungzzz** [comment]
Yup the same issue.
