### ISSUE TITLE
Spectate - MVP result does not close

### ISSUE THREAD

**Issue by renjithis** [ValveSoftware/Dota-2#856]
After spectating a match, MVP screen comes. The close button clicks and there is an audio effect, but does nothing. The MVP screen stays there with no change in animation and the close button is still clickable (and the effect is same).

Ubuntu 16.04 
Cinnamon 3.0.1-1
Core i5 2500K

**Comment by danginsburg** [comment]
This problem is not Linux/OS X-specific.  The larger team is working on a fix for this.
