### ISSUE TITLE
Text on top of the Healthbar gets very small during game.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#857]
Just like the title says, during the game the text on top of the healthbar(Player name, Hero name and lvl) gets smaller and smaller during the curse of the game. Goes away when you restart the game but then it happens again. I reinstalled the game and the problem it's still there.
Any solution/cause for this? Thx

Screenshot: in 1920*1080
http://imgur.com/EKs3bHM

**Comment by danginsburg** [comment]
Please post Steam -> Help -> System Information.  It is not clear from the bug description which platform you are on.

**Comment by ghost** [comment]
Here it is:

Computer Information:
    Manufacturer:  ASUS
    Model:  All Series
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3398 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  AMD Radeon HD 6800 Series

```
DirectX Driver Name:  aticfx32.dll
Driver Version:  15.301.1901.0
DirectX Driver Version:  8.17.10.1433
Driver Date: 23 Feb 2016
OpenGL Version: 4.5
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: AMD Radeon HD 6800 Series
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus Type Not Detected
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Altavoces (Realtek High Definit

Memory:
    RAM:  8130 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  953315 Mb
    Largest Free Hard Disk Block:  36436 Mb
    OS Install Date: dic. 31 1969
    Game Controller: None detected
    VR Headset: None detected

**Comment by danginsburg** [comment]
Thanks for the info.  It looks like you are on Windows 10.  This tracker is for Linux/OSX issues.  You can report your issue at dev.dota2.com.  I will also pass it along to the larger team.
