### ISSUE TITLE
[Linux] The inspect hero UI while spectating does not show equipped cosmetics

### ISSUE THREAD

**Issue by Kirov123** [ValveSoftware/Dota-2#86]
The magnifying glass icon in the hero portrait opens a small windows in the side thats shows the hero as shwn in the loadout screen, but does not display equipped items in their boxes.

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue but I've passed it on to the larger team.  We don't necessarily get updates back but a future update should fix this.
