### ISSUE TITLE
[Mac] Dota 2 crashes multiple times while in a match (May 4 update)

### ISSUE THREAD

**Issue by Feydragon** [ValveSoftware/Dota-2#860]
Hello,

Today's small update (May 4) seems to have caused an issue with my ability to run the game. Played several matches before the update and all was well, but after updating, I played one match and the game crashed about 4 times during that match. The first two times, the game crashed on it's own, booting me back to desktop with no error message or crash report. The third time it just became unresponsive so I killed the process. Fourth time, the game minimized itself before crashing and this time, fortunately, I did receive an error message. The text of the error message was as follows:

`Error`
`void`
`CSchemaNonConstructibleClassBindingBase::ReportClassError(const char *) const():`
`Cannot deallocate abstract class:`
`CBodyComponentPoint`

My system:
MacBook Pro (15-inch, Mid 2009)
OSX 10.11.4 (El Capitan)
Processor: 2.8 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3
Graphics: NVIDIA GeForce 9600M GT 512 MB

Please let me know if there is any other information I can provide, such as details about the match in question, etc.

Many thanks,
Fey

**Comment by danginsburg** [comment]
If you are able to provide a crash ID or crash dump that would be very helpful.  Please also post Steam -> Help -> System Information.

**Comment by gdrewb-valve** [comment]
Do you have any other information?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
