### ISSUE TITLE
[Mac] Combined sents and obs wards cooldown bugged

### ISSUE THREAD

**Issue by hipunk** [ValveSoftware/Dota-2#861]
When combining the two ward types together (sentries and observers), you get one item now.

However, if you use up all the charges of one kind of a ward in that item, you have suddenly no cooldown instead of the 1 second cd that is generally intended.

Very nice to see in Match ID 2340578409, gametime 43:42, Jakiro is about to ward the Sentinel ancient camp, but accidentally places three of them, as there was no cooldown (which then lead to the misinterpretation of the player that no ward got placed, as the eyes glanced somewhere else already).

Mac OS X 10.11.4
Steam stable (latest)
Dota 2 stable client (latest)

**Comment by danginsburg** [comment]
This is likely not OS X specific so I have forwarded it on to the larger team.
