### ISSUE TITLE
FPS drops when selecting smeevil couriers.

### ISSUE THREAD

**Issue by mcgruber22** [ValveSoftware/Dota-2#863]
So I'm not sure how to say this. Whenever I select a smeevil courier my FPS drops tremendously (sometimes stuttering the game completely) and it only happens when it's a smeevil. It started with the most recent update (6.87). I have a MBP late 2013 and I'm running El Capitan.

The weird thing is sometimes the FPS drops won't occur. I'll be able to select the courier multiple times in a row and there's no stuttering or performance issues, but more often than not it'll result in a massive drop in FPS.

**Comment by danginsburg** [comment]
@mcgruber22 I tried to repro this but I don't see any FPS difference with smeevil versus other couriers.  I would guess the framerate drop might be something else.  Can you provide exact repro instructions, the magnitude of the fps drop (you can see with +cl_showfps), and your system info (Steam -> Help -> System Information).

**Comment by MasterZapple** [comment]
I'm also getting a massive fps drop whenever selecting it.
Simply ingame select it (or use the courier hotkey). Does not matter if you are looking at it or not. Can bypass by using the courier deliver button.
I have only tried it with my genuine Smeevil using the last style (Purple Smeevil and Dyed Crab). I have only noticed it in matchmaking (I had it in shuffle). Just now tried it in 'Demo Courier' and everything is fine.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
