### ISSUE TITLE
Spectate - Crash when spectating live matches when they are in pick screen (drafting)

### ISSUE THREAD

**Issue by renjithis** [ValveSoftware/Dota-2#865]
Crash does not occur always, sometimes I am able to watch the draft, but half the time it crashes to desktop. Doesn't happen if I wait for the draft to complete. 
Edit : Loading screen appears and crashes.
Attaching /tmp/dumps/<username>_stdout.txt (Can you add the location and instructions for getting logs to the README.md-Reporting Issue section?)

[renjith_stdout.txt](https://github.com/ValveSoftware/Dota-2/files/253905/renjith_stdout.txt)

**Comment by renjithis** [comment]
Also happens when changing watching game. i.e. Watch 1 game, click top left minimize button, select another game to watch which is in its drafting stage : Loading screen appears and crashes

[renjith_log.txt](https://github.com/ValveSoftware/Dota-2/files/253933/renjith_log.txt)
[renjith_stdout.txt](https://github.com/ValveSoftware/Dota-2/files/253934/renjith_stdout.txt)

**Comment by danginsburg** [comment]
Thanks, the crash ID you gave us bp-caa88cd7-25f2-44f1-b4c6-03e7f2160508 shows it is inside of scaleform video decoding.  We will look into it and see if we can repro.

**Comment by gdrewb-valve** [comment]
This crash occurs on all platforms so we the larger team is taking a look and we won't get direct status updates here.

**Comment by gdrewb-valve** [comment]
The larger team is actively investigating so closing.
