### ISSUE TITLE
[All platforms] Quickbuy buy order broken with multiple items queued

### ISSUE THREAD

**Issue by telegram-error** [ValveSoftware/Dota-2#866]
Quickbuy bug when adding multiple items which share components: Components are removed in a LIFO order instead of FIFO order:

Here is a [video illustrating the issue](https://gfycat.com/TautIcyBlackandtancoonhound). As you can see each time a component is bought it is removed from the second deadalus instead of the first deadalus and thus the order in which items are bought is just **wrong**. This happens once you queue up 2 or more items which share at least 1 component in their buildup.

Many items share components and this bug makes using quickbuy with multiple items frustrating to use. I am also pretty sure this is an issue which can be fixed pretty quickly (in the code).

![Uploading quickbuy_bug.gif…](gif file of the video above)

**Comment by gdrewb-valve** [comment]
dev.dota2.com is the place to report general bugs, this is only for bugs specific to Mac and Linux.  I've passed this on to the larger team.

**Comment by telegram-error** [comment]
I am well aware that dev.dota2.com is the place for bug reports. I made a thread but it seems to get ignored. I wish I could look at the source code for quickbuy related functions and just fix it myself..
