### ISSUE TITLE
Watch tab has matches stuck on last watched game's player names

### ISSUE THREAD

**Issue by renjithis** [ValveSoftware/Dota-2#867]
Watched a game being played by a pro and after that, all the games in the watch tab has that match's player names. PFA.
Have to quit and open Dota2 again for this to show real names.

![20160512221504_1](https://cloud.githubusercontent.com/assets/1526467/15222931/88287e46-188f-11e6-8c93-85906e70eb5e.jpg)
![20160512221506_1](https://cloud.githubusercontent.com/assets/1526467/15222933/888bb164-188f-11e6-9700-1ef5a4c60929.jpg)
![20160512221518_1](https://cloud.githubusercontent.com/assets/1526467/15222934/88905afc-188f-11e6-983b-1efe6a6f1fa0.jpg)
![20160512221525_1](https://cloud.githubusercontent.com/assets/1526467/15222932/885cfa54-188f-11e6-94e9-f12e5d2e4b82.jpg)
![20160512221527_1](https://cloud.githubusercontent.com/assets/1526467/15222935/88948a50-188f-11e6-9bcc-6728094245cd.jpg)
![20160512221529_1](https://cloud.githubusercontent.com/assets/1526467/15222936/889afa8e-188f-11e6-8715-9ba13e3b13f4.jpg)

**Comment by gdrewb-valve** [comment]
This isn't specific to Mac/Linux so I've passed it on to the larger team.
