### ISSUE TITLE
Game crashing on load into game

### ISSUE THREAD

**Issue by gramathy** [ValveSoftware/Dota-2#868]
Happens for both games and spectating, consistently. Menus are fine but loading into game results in a crash right about when the game would start being displayed. Persists through reboot and reinstall of game. Seems to be new within the last couple days.

Dota console output:

https://gist.github.com/gramathy/26b089283c625c457e523149ed39be14

https://gist.github.com/gramathy/7e8924e3d6072b36c13cf1eea9fe5311

System:

https://gist.github.com/gramathy/97512f446c3ed10b4b60

**Comment by gdrewb-valve** [comment]
Is that system info recent?  Do you have any corresponding failure reports in Steam system info (nothing appears in the one you posted)?  Have you done any video driver or system updates recently?

**Comment by gramathy** [comment]
System info was pulled earlier today as there had been some changes since previous. I haven't updated anything recently, and Steam itself didn't seem to be affected by these crashes (though Steam itself has also been unstable lately)

**Comment by gdrewb-valve** [comment]
There's nothing that looks too problematic in the console output and no failure reports to go on so there's not an obvious investigative path.  We'll have to see if it happens to more people so that we can isolate the problem.

You might want to verify your local installation, there were a couple of errors that suggest the on-disk content might have problems.

**Comment by gramathy** [comment]
I saw those and thought that might be it, but since Dota was broken and I
was procrastinating on it anyway, I just installed El Cap and it's working
fine now, so it wasn't anything on disk. It was just so weird that it was
crashing with no error or console output.

On Sat, May 14, 2016 at 6:38 AM, Drew Bliss notifications@github.com
wrote:

> There's nothing that looks too problematic in the console output and no
> failure reports to go on so there's not an obvious investigative path.
> We'll have to see if it happens to more people so that we can isolate the
> problem.
> 
> You might want to verify your local installation, there were a couple of
> errors that suggest the on-disk content might have problems.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ValveSoftware/Dota-2/issues/868#issuecomment-219220868

## 

Graham Alldredge

"Try not. Do, or do not. There is no try."
– _A wise man_

**Comment by gdrewb-valve** [comment]
OK, it's likely it was an OpenGL driver issue, closing for now.
