### ISSUE TITLE
[Linux]Game stuck at connecting

### ISSUE THREAD

**Issue by 0re5ama** [ValveSoftware/Dota-2#869]
After accepting a match, most of the times, my dota gets stuck at connecting and the console says

> CL:  Sending connect to =[A:1:3020375045:6820]
> Trying to send a packet via steam datagram when no network configuration is available.

But when my friend on windows gets stuck on connecting, which occurs at the same time as mine, after restarting dota and reconnecting, he is easily able to reconnect. While mine on linux shows the above error.

**Comment by gdrewb-valve** [comment]
As you point out the underlying connection problem crosses all platforms and won't be handled here.  The lack of a network configuration is likely a Linux-specific issue with reading the local configuration file but it also indicates a networking problem as there's a separate attempt to read the config from the cloud.  We'll fix the local file access but it may only be a partial fix.

**Comment by gdrewb-valve** [comment]
The May 16 update should fix the issue with you not having a network configuration, do you still see that message?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by 0re5ama** [comment]
thanks, it got solved
