### ISSUE TITLE
[Linux] Huge FPS drop during sand storm in Manjaro Linux x86_64 (Valve's runtime)

### ISSUE THREAD

**Issue by EPadronU** [ValveSoftware/Dota-2#87]
### Description

During `Sand King`'s `Sand Storm` I'm getting a **huge FPS drop from ~44 to ~19**.
### Machine's specs

`uname -a`

```
Linux sophy 3.19.8.1-1-MANJARO #1 SMP PREEMPT Sat May 30 07:43:25 UTC 2015 x86_64 GNU/Linux
```

`lspci -vv`

```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
        DeviceName:  Onboard IGD
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 10c0
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 26
        Region 0: Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
        Region 2: Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Region 4: I/O ports at f000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915
```

`mhwd -lh -d`

```
08: PCI 02.0: 0300 VGA compatible controller (VGA)
  SysFS ID: /devices/pci0000:00/0000:00:02.0
  SysFS BusID: 0000:00:02.0
  Hardware Class: graphics card
  Device Name: "Onboard IGD"
  Model: "Intel 3rd Gen Core processor Graphics Controller"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x0166 "3rd Gen Core processor Graphics Controller"
  SubVendor: pci 0x1462 "Micro-Star International Co., Ltd."
  SubDevice: pci 0x10c0 
  Revision: 0x09
  Driver: "i915"
  Driver Modules: "drm"
  Memory Range: 0xf7800000-0xf7bfffff (rw,non-prefetchable)
  Memory Range: 0xe0000000-0xefffffff (ro,non-prefetchable)
  I/O Ports: 0xf000-0xf03f (rw)
  IRQ: 26 (2273976 events)
  I/O Ports: 0x3c0-0x3df (rw)
  Module Alias: "pci:v00008086d00000166sv00001462sd000010C0bc03sc00i00"
  Driver Info #0:
    Driver Status: i915 is active
    Driver Activation Cmd: "modprobe i915"
```

`Help -> System Information`

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.8.1-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Enlightenment
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.5.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 12.17" x 6.85"  (13.94" diag)
                                            30.9cm x 17.4cm  (35.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3854 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  272848 Mb
    Largest Free Hard Disk Block:  176951 Mb

Installed software:

Recent Failure Reports:

```

**Comment by gdrewb-valve** [comment]
Did the 6/26 update improve this?

**Comment by EPadronU** [comment]
No it didn't

**Comment by gekkey** [comment]
I also noticed substantial fps drops (on arch 4.0.6) during chronospere and windrun.

**Comment by gekkey** [comment]
Also Midnight pulse and static remnant. I would guess it has something to do with transparency.

**Comment by blendi-93** [comment]
confirmed on arch linux 64bit

**Comment by computerquip** [comment]
I can confirm that I do *not* have this issue. 

>Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
>Network Information:
    Network Speed:  
    
>Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.7-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
>Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

>    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1184
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                            59.8cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
>Sound card:
    Audio device: Realtek ALC887-VD
    
>Memory:
    RAM:  32127 Mb
    
>Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  214659 Mb
    Largest Free Hard Disk Block:  177423 Mb

**Comment by Ape** [comment]
Sand Storm also drops FPS quite a bit on my system. I usually have stable 80-150 fps that never drops below 60, but Sand Storm takes it down to around 45. With vsync enabled this is just simply stable 60 fps, or 30 with Sand Storm. There may be others effects that drop the FPS, but usually it stays above 60 even in fights.

```
CPU: Intel i5-4670K
GPU: GeForce GTX 285 2GB (proprietary drivers 340.76)
Memory: 16 GB DDR3, 1600 Mhz
OS: Arch Linux 64-bit
```

**Comment by ghost** [comment]
I start the match with normal FPS (60 VSync stable), but after 5 minutes or so it's down to 25 even lower.
Got this from the console (btw Copy and Paste don't work):

```
BuildBoneMergeWork: Tried to bone merge an entity that has no model or no parent model. (spammed a lot)
Failed to allocate space for morph.
```

After a while the FPS goes back again, but the BuildBoneMergeWork message always corelates with new FPS drops.

```
CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
GPU: nVidia(R) GeForce GT 730M (352.30 drivers)
Memory: 8 GB DDR3, 1333 Mhz
OS: Manjaro 64-bit (3.18 kernel)
```

On Ubuntu I used to have ~100 FPS in Reborn.
Well I hope this information can help you.

**Comment by danginsburg** [comment]
I can confirm a performance drop when sandstorm is running, but I don't measure any significant difference in performance drop between it in OpenGL vs. DirectX9.  We will pass this along to the larger team.

**Comment by gdrewb-valve** [comment]
I've forwarded this to the larger team and it will no longer be tracked here.

**Comment by ssrebelious** [comment]
Seems that it is an old thread, but the issue with 75% FPS drop during sand storm persists on Linux and makes some fights unplayable T_T.  Where is the continuation thread for this issue?

**Comment by joao-amendola** [comment]
My Arch Linux with Nvidia proprietary drivers is affected by this bug as well. When I have a match with SK I have to quickly reboot to Windows or I simply can't play due to the fps drop.

**Comment by voronind** [comment]
Very annoying bug. My videocard is GeForce GTS 250.
During Sand Storm FPS drops from 110 to 10.
It was started after Diretide 2020.

**Comment by ghost** [comment]
FPS drops from 130+ to 30 with sand storm in any Nvidia driver above 470 (470 works fine). Using linux mint, GTX 1070

**Comment by danslo** [comment]
I can also confirm this issue. Ubuntu 21.10 with latest Nvidia drivers. FPS drops from 120 to ~50 when sandstorm is activated. Could you please reopen this one @kisak-valve ?

**Comment by kisak-valve** [comment]
Hello @danslo, it sounds like you're looking for https://github.com/ValveSoftware/Dota-2-Vulkan/issues/402 and not this issue reported in 2015. No, I will not be re-opening this issue report.

**Comment by danslo** [comment]
@kisak-valve Thanks for linking, I didn't realize there was a different repo for vulkan issues!

**Comment by voronind** [comment]
> Hello @danslo, it sounds like you're looking for [ValveSoftware/Dota-2-Vulkan#402](https://github.com/ValveSoftware/Dota-2-Vulkan/issues/402) and not this issue reported in 2015. No, I will not be re-opening this issue report.

This bug raises on OpenGL too.

**Comment by ssrebelious** [comment]
> This bug raises on OpenGL too.

Yes, this is about OpenGL, I do not use Vulkan (quality of the picture is pretty bad) and FPS drop is experienced using OpenGL. Please reopen this issue.
