### ISSUE TITLE
MAC Problem: Dota crash after starts without any error - seems like all macs have it

### ISSUE THREAD

**Issue by somecolors** [ValveSoftware/Dota-2#870]
hi dev team,

as descripted in title

best regrads,
stef

**Comment by samuelclark** [comment]
+1

**Comment by Segflow** [comment]
Same thing for me, crash after start.

**Comment by tembra** [comment]
+1
Same is happening here. Crash without any error (just ends) very shortly after startup.
I just update the game today (last match was 3 days ago) and also apply today OS X El Capitain 10.11.5 update through AppStore (https://support.apple.com/kb/HT206230).

OS X El Capitain
Version 10.11.5 (15F34)
MacBook Pro (13-inch, Mid 2012)
2,5 GHz Intel Core i5
16 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB
SSD Samsung 840 PRO 256 GB

**Comment by zanderzhng** [comment]
same here. crash in 30s after game start.

**Comment by adamrisser** [comment]
+1

10.11.4
MBP Retina Mid 2014
2.2.ghz Intel i7
16bm ddr3
Graphics Intent Iris Pro

Edit: DYING to buy compendium, if you need any more info, let us know

**Comment by ethandbrand** [comment]
+1 Worked yesterday, before the patch, now the game client crashes at random very shortly after startup.

**Comment by blackkingbra** [comment]
+1, was party with friends and did the update just now. And now it sucks, crash after login 5secs for no reason! With Capitain Mac

**Comment by welkinlan** [comment]
+1
MacBook Pro (Retina, 15-inch, Early 2013)

**Comment by gdrewb-valve** [comment]
If you add

```
-gtpoolstacksize 1048576
```

to your launch options does that help?

**Comment by Segflow** [comment]
@gdrewb-valve no

**Comment by blackkingbra** [comment]
@gdrewb-valve  it doesn't work, man!

**Comment by nuttyness** [comment]
I'm having the same problem...

Macbook pro, retina, late 2013

**Comment by gdrewb-valve** [comment]
We're investigating, we don't need any more +1's at the moment.

**Comment by cesargog** [comment]
@gdrewb-valve no, with that command now it works for 30 seconds and then crash again.

**Comment by nuttyness** [comment]
Just an update. Dota stays on until I use the mouse. Mouse movement causes crash... even using trackpad. Hope this helps

**Comment by blackkingbra** [comment]
@nuttyness That is right, something wrong with mouse

**Comment by Segflow** [comment]
yeah no crash if we don't use the mouse (or trackpad)

**Comment by monolyth-studio** [comment]
@gdrewb-valve Stayed in client longer the first time I launched with these settings. Crashes  < 1 minute of being in client.

EDIT: I can stay in client until I move my mouse / trackpad

iMac (Retina 5K, 27-inch, Late 2015)
4 GHz Intel Core i7
8 GB 1867 MHz DDR3
AMD Radeon R9 M395X 4096 MB

**Comment by blackkingbra** [comment]
a new update came, but seems still not work.

**Comment by jfosback** [comment]
Still crashing for me after the patch.  

MacBook Pro (Retina, 15-inch, Mid 2014)
27" Thunderbolt Display

**Comment by tembra** [comment]
@nuttyness seems to be right.

@gdrewb-valve this config doesnt help. 

if you stay moving the mouse after open the crash occurs early then before.
if you didnt move the mouse at all the crash doesnt occurs. after some minutes of no crash and no mouse move, if you move the mouse a little the crash is almost instantly.

EDIT: tested after the new patch and with -gtpoolstacksize 1048576

**Comment by gdrewb-valve** [comment]
We'll comment here when we believe we have a fix.

**Comment by hilmanzainuri** [comment]
+1

**Comment by morty200000** [comment]
the  patch  not  work

**Comment by majorvin** [comment]
(thumbsup)

**Comment by zanderzhng** [comment]
gtpoolstacksize option can make it stick longer.

**Comment by ruchernchong** [comment]
Is this some sort of memory leak?

**Comment by sassanh** [comment]
I guess you need a pool of computers with Windows XP, 7, 8, 10, etc and OS X Yosemite, El Capitan, etc on different types of hardware and a software that updates dota on these machines and simulates a game on each one and report issues to you before you release an update. This system can improve over time to test different functionalities and features of the game.

**Comment by xiay1** [comment]
Hi, after the most recent update, game still crash after a few seconds. El Capitan 10.11.4. iMac 27-inch late 2012 user here

**Comment by daviluisgf** [comment]
Win10 and the same prob

**Comment by ruchernchong** [comment]
An update was pushed and seemed to have fixed the problem.

Edit: Didn't fix for me. Weird the client actually stayed longer than I expected. First crash led to subsequent crashes.

**Comment by teletubo** [comment]
It didn't fix for me! Still Crashes after last update. 
El capitan, 10.11.3
MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by gdrewb-valve** [comment]
@daviluisgf you have a separate problem as the issue here is Mac-specific.  You'll want to post in dev.dota2.com.

**Comment by tiagoln** [comment]
I found the following message in the console after the crash:
"16/05/16 22:34:31,884 WindowServer[167]: disable_update_likely_unbalanced: UI updates still disabled by application "Dota 2" after 15.00 seconds (server forcibly re-enabled them after 1.00 seconds). Likely an unbalanced disableUpdate call."

Don't know if it can be of any help.

**Comment by ealvesss** [comment]
fresh update rigth now!!

**Comment by ealvesss** [comment]
Still Crashing =(

**Comment by blackkingbra** [comment]
delate "-gtpoolstacksize 1048576" in the console if you tried to fix before, and the new update seems fixed the problem.
I will test it again

**Comment by blackkingbra** [comment]
well. still crash.

**Comment by abacuscode** [comment]
There was an update about an hour ago that fixed it for me. There's a newer update that just got pushed and it's crashing on moving the mouse again.

**Comment by mkim** [comment]
I no longer immediately crash upon opening Dota 2, but mouse movements still crash and Cmd + H crash the app.

MacBook Pro Mid 2012
El Capitan 10.11.4
6 GB Ram

**Comment by blackkingbra** [comment]
The new update looks like make me stay in dota2 longer, but still crash after several stamps of movements and clicking

**Comment by ealvesss** [comment]
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
found breakpad via in process memory: '/Applications/Steam.app/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
Uploading pending dumps
Uploaded 1 pending dumps
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197982664765 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197982664765
SteamID:  76561197982664765, universe Public
Setting breakpad minidump AppID = 373300
2016-05-16 22:46:50.061 crash_report_sender[1960:147112] Failed to obtain sandbox extension for path=/var/empty/Library/Caches/com.Breakpad.crash_report_sender. Errno:2
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL vendor NVIDIA Corporation
void COpenGLDriverEntryPoints::DumpContextInfo(): OpenGL renderer NVIDIA GeForce GT 650M OpenGL Engine
void COpenGLDriverEntryPoints::DumpContextInfo(): Using OpenGL context version 4.1
void COpenGLDriverEntryPoints::DumpContextInfo(): Context supports GLSL version 4.10
2016-05-16 22:46:52.092 dota2[1958:147104] 22:46:52.092 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Fontconfig warning: "/Users/eltonalves/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/Users/eltonalves/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: ignoring UTF-8: not a valid region tag
2016-05-16 22:46:58.025 dota2[1958:147104] 22:46:58.025 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by goller** [comment]
From the console for me:

``` sh
5/16/16 8:51:48.683 PM dota2[75054]: 20:51:48.682 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
5/16/16 8:51:57.287 PM WindowServer[186]: disable_update_likely_unbalanced: UI updates still disabled by application "Dota 2" after 15.00 seconds (server forcibly re-enabled them after 1.00 seconds). Likely an unbalanced disableUpdate call.
5/16/16 8:51:57.295 PM dota2[75054]: void CGSUpdateManager::log() const: conn 0x1574b token 0x1ffffffffffe85
5/16/16 8:51:57.297 PM dota2[75054]: Backtrace (at 1.75128e+06):
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff8efb8a99 CGSDisableUpdateToken + 210
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff9c9f3524 ___disable_updates_sync_block_invoke_2 + 17
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x00007fff9520a40b _dispatch_client_callout + 8
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x00007fff9520b9f2 _dispatch_barrier_sync_f_invoke + 74
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  4   AppKit                              0x00007fff9c9f33f2 NSCGSDisableUpdates + 213
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  5   AppKit                              0x00007fff9c9f3228 NSCGSTransactionRunPreCommitActionsForOrder_ + 156
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  6   AppKit                              0x00007fff9c9f316f NSCGSTransactionRunPreCommitActions_ + 21
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  7   AppKit                              0x00007fff9d1a1d84 -[_NSCGSTransaction synchronize] + 33
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  8   AppKit                              0x00007fff9d1a1ff9 NSCGSTransactionSynchronize + 76
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  9   AppKit                              0x00007fff9cf8d065 -[NSSurface syncSurfaceWantsExtendedDynamicRange] + 150
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  10  AppKit                              0x00007fff9cac53d1 -[NSSurface _createSurface] + 677
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  11  AppKit                              0x00007fff9cac4d2c -[NSSurface setFrame:] + 785
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  12  AppKit                              0x00007fff9cf8d16b __38-[NSSurface syncToViewUnconditionally]_block_invoke + 154
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  13  AppKit                              0x00007fff9c9e2429 NSPerformVisuallyAtomicChange + 147
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  14  AppKit                              0x00007fff9cac4650 -[NSSurface syncToViewUnconditionally] + 100
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  15  AppKit                              0x00007fff9cf8d204 __37-[NSSurface orderSurface:relativeTo:]_block_invoke + 44
5/16/16 8:51:57.297 PM dota2[75054]: void CGSUpdateManager::log() const:  16  AppKit                              0x00007fff9c9e2429 NSPerformVisuallyAtomicChange + 147
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  17  AppKit                              0x00007fff9cac4523 -[NSSurface orderSurface:relativeTo:] + 160
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  18  AppKit                              0x00007fff9cbb7f22 NSOpenGLContextAttachOnScreenViewSurface + 183
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  19  AppKit                              0x00007fff9cee4767 __27-[NSOpenGLContext setView:]_block_invoke + 192
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  20  AppKit                              0x00007fff9c9e2429 NSPerformVisuallyAtomicChange + 147
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  21  AppKit                              0x00007fff9cba4cd9 -[NSOpenGLContext setView:] + 119
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  22  libSDL2-2.0.0.dylib                 0x000000008486d56a -[SDLOpenGLContext setWindow:] + 426
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  23  libSDL2-2.0.0.dylib                 0x000000008486e356 Cocoa_GL_MakeCurrent + 118
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  24  libSDL2-2.0.0.dylib                 0x000000008486e006 Cocoa_GL_CreateContext + 2118
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  25  libSDL2-2.0.0.dylib                 0x0000000084864056 SDL_GL_CreateContext_REAL + 214
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  26  libSDL2-2.0.0.dylib                 0x00000000847919c4 SDL_GL_CreateContext + 36
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  27  librendersystemgl.dylib             0x000000008890301d VoidFnPtrLookup_Tier0 + 32653
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  28  librendersystemgl.dylib             0x0000000088904db3 VoidFnPtrLookup_Tier0 + 40227
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  29  librendersystemgl.dylib             0x00000000888cb058 BinaryProperties_GetValue + 217032
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  30  libtier0.dylib                      0x000000000444455f CreateSimpleThread + 735
5/16/16 8:51:57.298 PM dota2[75054]: void CGSUpdateManager::log() const:  31  libsystem_pthread.dylib             0x00007fff9402399d _pthread_body + 131
```

**Comment by sassanh** [comment]
I found a fix that seems to be working for me: start the game, don't move the mouse or touch anything for 3 minutes, then use it normally. I just played a game right now with no problem using this method, but then it said there's no update, I relaunched and it crashed again, relaunched it and waited 3 minutes and now I'm finding a new game. (It used to crash immediately without using this method.)

**Comment by ruchernchong** [comment]
I wonder if the crash has to do with the Game Coordinator.

**Comment by kaelwu** [comment]
+1

**Comment by rachidcalazans** [comment]
Add the config -autoconfig. Solved my problem on OSX

**Comment by ruchernchong** [comment]
@rachidcalazans what does it do?

**Comment by xxfunbelievablexx** [comment]
Also, within the span of 30 seconds if you start spectating a game and do not move the mouse, you can spectate for as long as you like.

**Comment by morty200000** [comment]
new update

**Comment by zanderzhng** [comment]
@sassanh  I waited long enough and it crashed as long as I touch my mouse.
@rachidcalazans It changes desktop friendly fullscreen to beardless fullscreen but didn't fix the crash.

**Comment by ruchernchong** [comment]
New update! Hype!

**Comment by ghost** [comment]
New update seems like the bug is being fixed!

**Comment by ruchernchong** [comment]
Seemed like the bug is fixed.

**Comment by xxfunbelievablexx** [comment]
@rachidcalazans yeah seems to work, changed it from border less to desk friendly in game after launching with -autoconfig. Did not crash and still working.
Mac Book pro , retina 13 inch, 11.4

**Comment by zanderzhng** [comment]
newest update seems to fix it.

**Comment by xxfunbelievablexx** [comment]
oh cool

**Comment by ghost** [comment]
I did not used -autoconfig, and windows was reset to default, border window.

**Comment by ruchernchong** [comment]
Okay, it seemed to be fixed now. Case closed! :D

**Comment by mkim** [comment]
I no longer crash!

Chat, Cmd+H, clicking/moving mouse early all do not crash. Seems fixed!

**Comment by gdrewb-valve** [comment]
As people have already noticed we have shipped an update with a fix to the SDL problem that was causing this.  I'm closing this issue, open new ones for new crashes.

**Comment by ruchernchong** [comment]
@mkim What is CMD+H?

**Comment by ghost** [comment]
CMG + H is like alt+tab but it complete hide you the current window

**Comment by blackkingbra** [comment]
works now

**Comment by iLevye** [comment]
it's happening again.

**Comment by kisak-valve** [comment]
Hello @iLevye, please open a new issue report with a copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) in a [gist](https://gist.github.com/).

**Comment by elieandraos** [comment]
It's happening again ! 
Manufacturer:  Apple
    Model:  MacBookPro11,2
    Form Factor: Laptop
    No Touch Input Detected

**Comment by kisak-valve** [comment]
Hello @elieandraos, the current regression is being tracked at #1375 and the Dota 2 devs are aware of the issue.

There's no benefit in mentioning new regressions on closed issue reports, but feel free to add a thumbs up reaction to the current issue report to show your support.
