### ISSUE TITLE
Dota 2 cursor still too on 16:10

### ISSUE THREAD

**Issue by zhestkov** [ValveSoftware/Dota-2#873]
I tried -cursor_scale_percent 100 (or smaller) with 1440x900 resolution -- no difference there.
But when i tried it again with 1920x1080 then all was OK, except resolution.
P.S. using bootcamp win10
Computer Information:
    Manufacturer:  Apple Inc.
    Model:  MacBookPro12,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  Intel(R) Iris(TM) Graphics 6100

```
DirectX Driver Name:  igdumdim32.dll
Driver Version:  20.19.15.4444
DirectX Driver Version:  20.19.15.4444
Driver Date: 22 Apr 2016
OpenGL Version: 4.4
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 59 Hz
DirectX Card: Intel(R) Iris(TM) Graphics 6100
VendorID:  0x8086
DeviceID:  0x162b
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 11.26" x 7.05"  (13.27" diag)
                                        28.6cm x 17.9cm  (33.7cm diag)
Primary Bus Type Not Detected
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Headphones (Cirrus Logic CS4208

Memory:
    RAM:  8094 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  238551 Mb
    Largest Free Hard Disk Block:  18015 Mb
    OS Install Date: ??? 01 1970
    Game Controller: None detected
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
This forum does not handle Windows bugs, but we can gather some info first.  Can you add -console to your launch options, run the game, open the console and use 'check_dpi' with the video mode where you think the cursor is too big?

Note also that you can't scale the cursor below what Windows says is the expected cursor size, so if you have any Windows settings that would have Windows using larger UI elements that will put a floor on how small the cursor can get.

**Comment by zhestkov** [comment]
> Note also that you can't scale the cursor below what Windows says is the expected cursor size, so if you have any Windows settings that would have Windows using larger UI elements that will put a floor on how small the cursor can get.

That is! I had 200% Windows scaling, otherwise all UI elements are too small on 4k. When i rescaled it to lower value then cursor is OK, except Windows ui :) (btw, signing out required).
Thanks!

**Comment by gdrewb-valve** [comment]
OK, closing.
