### ISSUE TITLE
LINUX Game update corrupt wont finish

### ISSUE THREAD

**Issue by 420git** [ValveSoftware/Dota-2#874]
I woke up about 1 hour ago and there was a new update 50.9MB, it never finishes and keeps pausing randmly every 5 secs. If i press resume repeatedly it gets stuck at 27.1MB no further. I clearded my downloading folder and restarted update still same issue. Always says download is corrupt.

**Comment by gdrewb-valve** [comment]
You'll want to file this in the steam-for-linux section.
