### ISSUE TITLE
[Linux] Keyboard not responding 

### ISSUE THREAD

**Issue by jacksondeng** [ValveSoftware/Dota-2#875]
After the recent update ,my keyboard will not stop to respond if the [ user online ] notification shows up. Game still runs smoothly , but I can't use keyboard in game. Have no idea why this is happening.

**Comment by gdrewb-valve** [comment]
If you switch to another window/app and back does the keyboard start working again?

**Comment by gdrewb-valve** [comment]
We'll also need your system information from Steam.  As it is we can't really investigate so closing.

**Comment by jacksondeng** [comment]
At first I thought i was the [user online] notification causing the problem, but the problem actually occurs after I pressed alt. So I think it is actually my mandarin input method's causing problem, I will follow this lead and searching for the answer.
Sorry for taking your time. Regards.
