### ISSUE TITLE
[suggestion] control volume on out of focus window

### ISSUE THREAD

**Issue by sinatosk** [ValveSoftware/Dota-2#876]
when waiting to join a game while the window is not focused ( using application outside of dota ) the volume to let me know there is a game ready is loud... like maximum volume.

I would like to see an option to control the volume when client is out of focus... I don't want it to be silent

thanks

**Comment by gdrewb-valve** [comment]
This forum is only for Linux/Mac bugs, you'll want to post this at dev.dota2.com.
