### ISSUE TITLE
FPS drop new update

### ISSUE THREAD

**Issue by sinamiandashti** [ValveSoftware/Dota-2#879]
Hi

i have heavy FPS drop in latest update (battlepass) 
it drops from 70 to 50 when moving hero

**Comment by gdrewb-valve** [comment]
It's unlikely this is a Mac/Linux problem as people at dev.dota2.com are reporting it very generally, but can you post your system information from Steam?

**Comment by sinamiandashti** [comment]
`Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro10,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 650M

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x10de
DeviceID:  0xfd5
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                        33.1cm x 20.6cm  (38.9cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475928 Mb
    Largest Free Hard Disk Block:  183801 Mb
    VR Headset: None detected

`

**Comment by sinatosk** [comment]
discard mine, it's related to vulkan, opengl still good for me, sorry

**Comment by crapthings** [comment]
Model Name: MacBook Pro
  Model Identifier: MacBookPro11,5
  Processor Name:   Intel Core i7
  Processor Speed:  2.5 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB

**Comment by crapthings** [comment]
Chipset Model:  AMD Radeon R9 M370X
  Type: GPU
  Bus:  PCIe
  PCIe Lane Width:  x8
  VRAM (Total): 2048 MB
  Vendor:   ATI (0x1002)
  Device ID:    0x6821
  Revision ID:  0x0083
  ROM Revision: 113-C5670E-777
  gMux Version: 4.0.20 [3.2.8]
  EFI Driver Version:   01.00.777
  Displays:
Color LCD:
  Display Type: Retina LCD
  Resolution:   2880 x 1800 Retina
  Retina:   Yes
  Pixel Depth:  32-Bit Color (ARGB8888)
  Main Display: Yes
  Mirror:   Off
  Online:   Yes
  Built-In: Yes

**Comment by ghost** [comment]
Same here on OSX 10.11.6 Public Beta 1

GTX 960 - Web Driver: 346.03.10f01

I'm forced to boot to my Winshit partition to play :'(

Also it would be cool if saved settings are platform independent

Steam cloud setting for PC/OSX/Linux in separate place

EDIT:

Do you think if you implement a Metal renderer for OSX it'll be better than OpenGL ? Is this already planned?

**Comment by ghost** [comment]
Any new on this?

It's hard to keep 60FPS even when every setting is disabled and everything on LOW ..

**Comment by sinamiandashti** [comment]
volvo plz fix

**Comment by sinamiandashti** [comment]
@gdrewb-valve

**Comment by ghost** [comment]
1 month later still unplayable on OSX

**Comment by sinamiandashti** [comment]
@Scellow litter better now .... but not as good as always

**Comment by ghost** [comment]
@sinamiandashti yes a bit better, but its still not acceptable for a AAA game, this is not early access game

**Comment by ghost** [comment]
Ok, recent updates completely solved my performance issue, thanks guys

**Comment by gdrewb-valve** [comment]
@sinamiandashti, has your perf changed?  Also @crapthings and any others watching this?

**Comment by crapthings** [comment]
on my imac 27" 2011 it works fine for me

i will try my macbook pro 15 2015

**Comment by sinamiandashti** [comment]
mine fixed too <3  @gdrewb-valve
