### ISSUE TITLE
[Linux][Layout] [Minor] `Duration` column name under the `Recent Games` view is not correctly aligned

### ISSUE THREAD

**Issue by EPadronU** [ValveSoftware/Dota-2#88]
### Screenshot

![2015-06-24_00005](https://cloud.githubusercontent.com/assets/829947/8345931/7eaaa782-1abf-11e5-9143-efb0b1e9e770.jpg)
### Notes

Let me know if you need my machine's specs for this one.

**Comment by gdrewb-valve** [comment]
Are you still seeing this?  I tried this out and everything looked fine to me.

What resolution are you running at?

**Comment by EPadronU** [comment]
Yes, it still happens (I just tried). 1366x768 (16:9) borderless window.

**Comment by gdrewb-valve** [comment]
OK, changing my resolution to 1366x768 showed it.  This isn't a Linux/Mac issue so I'll pass it on to the larger team and it won't be tracked here.
