### ISSUE TITLE
high load server bug

### ISSUE THREAD

**Issue by HunKfTw** [ValveSoftware/Dota-2#880]
i played 2 games international ranked match
1st venomancer
2nd mirana
due to high load servers it wasn't updated
after sometime when i checked in recent games it only shows mirana as recent game nothing else
venomancer's game is missing and my quest which i completed in that too.. :/ help me plz...

**Comment by gdrewb-valve** [comment]
This doesn't seem to be a Mac/Linux bug, but can you post your system info?

**Comment by gdrewb-valve** [comment]
Also any details on the match so that we can look it up?

**Comment by HunKfTw** [comment]
it was international ranked match (Ti6)
with me their was a guy whom i added later, even his recent games is not updated yet, its been more than 2 hrs.

**Comment by gdrewb-valve** [comment]
Can you post your system info?

**Comment by gdrewb-valve** [comment]
As this isn't platform-specific the larger team is investigating.
