### ISSUE TITLE
Shadowing flickering in new Terrain around edge of screen

### ISSUE THREAD

**Issue by gu3st** [ValveSoftware/Dota-2#881]
I don't have a Windows machine to compare this with, but I noticed that there are some weird shadow errors with the new terrain, which could be linked to Linux/OpenGL specifically

You can see them at the right side of the screenshots.

![screenshot from 2016-05-20 17 58 29](https://cloud.githubusercontent.com/assets/375232/15445522/e80ae3e6-1eb4-11e6-9b73-b3595c3a1200.png)
![screenshot from 2016-05-20 17 58 18](https://cloud.githubusercontent.com/assets/375232/15445523/e80e64b2-1eb4-11e6-9498-88bc24be66a9.png)

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?

**Comment by gu3st** [comment]
`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-71-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 355.11
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x13c2
Revision Not Detected
Number of Monitors:  3
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 5760 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15986 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  919997 Mb
    Largest Free Hard Disk Block:  499935 Mb
    VR Headset: None detected

```
Mon May 16 04:11:57 2016 GMT: file ''/tmp/dumps/crash_20160515143030_1.dmp'', upload yes: ''Discarded=1''
Sat May 21 00:56:30 2016 GMT: file ''/tmp/dumps/crash_20160520175536_1.dmp'', upload yes: ''Discarded=1''
Sat May 21 00:56:44 2016 GMT: file ''/tmp/dumps/crash_20160520175633_1.dmp'', upload yes: ''Discarded=1''
Sat May 21 00:57:18 2016 GMT: file ''/tmp/dumps/crash_20160520175648_1.dmp'', upload yes: ''Discarded=1''
```

`

**Comment by danginsburg** [comment]
Thanks, we have repro'd this bug here.  It is not platform specific so I'm going to close it out here, but the larger team is looking into it.  It is actually related to the weather and not the specific terrain.
