### ISSUE TITLE
Dota 2 Crashes during loading screen

### ISSUE THREAD

**Issue by skoehler** [ValveSoftware/Dota-2#883]
When starting Dota 2, I see the red dota logo on the black background, and then Dota crashes.
This didn't happen yesterday evening (about 10 hours ago) but now it does.

When I start steam in a console window and then start dota, I find the following error that might be related:
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 497: elf_machine_rela_relative: Assertion `((reloc->r_info) & 0xffffffff) == 8' failed!

**Comment by skoehler** [comment]
I had to perform "verify integrity of game cache" and then some file failed verification and was redownloaded. After that, the game starts successfully.

**Comment by Tele42** [comment]
@skoehler go ahead and close the issue report if you believe it is resolved.
