### ISSUE TITLE
Question regarding issues with cosmetics reports.

### ISSUE THREAD

**Issue by randomdota** [ValveSoftware/Dota-2#884]
Hi there, I was wondering if there is any reliable ways to get a cosmetic bug report reviewed & fixed as I am currently experiencing an issue http://dev.dota2.com/showthread.php?t=193936 but have exhausted many methods but is still unable to get the attention of a developer. I have provided as much information as possible such as values in the item schema and full reproduction steps. I have been frequently bumping that specific thread for approximately 2 months but from what I can observe there is no developer that is assigned for that specific sub-forum, previously BrandonReinhart/GreenMarine would review bugs there but he seems to have moved on to other projects.

It would be great if I could know where/how I could get a developer specialized in this specific area to review it as continuously bumping a thread seems to be not effective.

Thanks!

**Comment by gdrewb-valve** [comment]
dev.dota2.com is the right place, even if it doesn't seem like it.  This forum is for Linux/Mac bugs only so we don't investigate problems like what you're reporting.  I've sent this on to the larger team.
