### ISSUE TITLE
Ubuntu 14.04 Keyboard stops working and closing the game freezes PC

### ISSUE THREAD

**Issue by Moosli** [ValveSoftware/Dota-2#885]
Dota 2 reborn had been working fine for weeks and suddenly this bug occurs. Seems like the May 23rd Patch may have caused it.

So, randomly when I'm in the client (Dota 2 reborn), this includes in-game or in-menu, the keyboard will stop working (all buttons). I can't even alt-tab, use the superkey, ctrl + alt +del, etc. When I try to exit the game with the mouse, the computer freezes and so my only option is to use the power button. This makes the game somewhat unplayable (unless you want to click everything).

This will also occur (100% of the time) if I alt-tab away from the game and then alt-tab back in.

Anybody experienced anything similar?

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information.

In general, user applications should not be capable of crashing the system, so this is most likely a driver issue or overheating hardware. It would be a good idea to read up on `REISUB` (http://blog.kember.net/articles/reisub-the-gentle-linux-restart/) as a last-ditch effort to stop the system.

**Comment by Moosli** [comment]
Sorry, here is the info:

Computer Information:
    Manufacturer: Acer
    Model:  Aspire V5-573G
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2401 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-87-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.3.0-devel (git-74e71cb 2016-05-23 trusty-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x8086
DeviceID:  0xa16
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.58" x 7.64"  (15.55" diag)
                                        34.5cm x 19.4cm  (39.5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  11897 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  492025 Mb
    Largest Free Hard Disk Block:  130679 Mb
    VR Headset: None detected

Cheers

**Comment by Tele42** [comment]
Yeah, this should also be reported to the mesa devs at freedesktop.org if there isn't a bug report already reported for this issue.

**Comment by Moosli** [comment]
OK, I'll go and have a look, thanks.

**Comment by Moosli** [comment]
So, I tested with CS:GO (another steam game) and the same thing occurred. Would this indicate a hardware failure or some kind of software issue?

**Comment by Tele42** [comment]
Personally, I'd monitor the cpu/gpu temperature from a ssh session, if it goes above 100C, then that should be considered a critical temp and may be a hardware issue, otherwise it is most likely a driver issue.

**Comment by gdrewb-valve** [comment]
Closing as this appears to be a driver issue and not a Dota issue.
