### ISSUE TITLE
Every other game fails to start (linux)

### ISSUE THREAD

**Issue by felipec** [ValveSoftware/Dota-2#886]
After finishing a match I can't start another game, first, the error messages says that the game cannot be started, then I close, reopen, and I get a message that another player in my party isn't allowing the game to start, but I am soloing. The second time I restart it seems to work.

This happens after **every** game.

**Comment by gdrewb-valve** [comment]
This happens on all platforms, the larger team is looking at it.

**Comment by felipec** [comment]
What's the point of reporting bugs if you are going to close them without resolving them? Where is the duplicate?

**Comment by Tele42** [comment]
@felipec this issue tracker is explicitly limited to mac and linux client issues of Dota 2. If an issue affects all platforms, like this one, it's handled by a larger team of devs as @gdrewb-valve typed. The issue report was closed to make it clear there was not going to be any follow up information.

**Comment by felipec** [comment]
Good thing you closed this issue. Two months later, and this issue is still present. So good to hear "the larger team is looking at it".
