### ISSUE TITLE
[Linux] MATE/Cinnamon issues with Mouse clicks

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#887]
HeyGuys,

I tend to click left and right mouse buttons a lot at the same time and i never noticed that but now that i switched to MATE 1.12 (tested with 1.14 too) i'm having issues with my mouse in Dota 2. I've been playing like that since ever though. The same issue is valid on Cinnamon 3.x

dota_camera_disable_zoom is set to 1

I'm on Ubuntu 16.04 LTS (64-bit), kernel: 4.6.0-040600-generic, X: 1.18.3, WM: Metacity (Marco) with compositor off (on results in the same)

I've been using Gnome (3.18 and 3.20) with no problems at all and even Unity behave as i expected that is Dota registering both actions ingame. Now tho, not only dota doesn't dispatch a left click nor a right click per say, but it drags the camera like if i 've pressed middle button. If i go to Option -> Advanced -> and check "Use Left button to drag the camera" It stops to hangle both left+right clicks and a drag event. But still doesn't behave as normal clicks at the same time.

Let me know if and how can i provide any other lib version or even xorg.conf files. I'm clueless here.

**Comment by gdrewb-valve** [comment]
If I understand you correctly you're having a problem only with MATE and Cinnamon?  Gnome and Unity work properly?  You might get more information asking in MATE/Cinnamon forums.

**Comment by admshao** [comment]
Yes, exactly. I tried Gnome (flashback) and it works just ok. I was hoping it could have something to do with maybe SDL. Gonna check there into those forums. Thx!

**Comment by Tele42** [comment]
In cinnamon, check System Settings -> Mouse and Touchpad and make sure 'Emulate middle click by clicking both left and right buttons' is set to off. MATE has a simular setting somewhere.
