### ISSUE TITLE
The Second Time About Chinese Input 

### ISSUE THREAD

**Issue by planktonzp** [ValveSoftware/Dota-2#888]
Maybe i will make you and your team boring but there are so many chinese player on linux waited for so long ，please fix it ,thank you

**Comment by gdrewb-valve** [comment]
Duplicate of #50.  Unfortunately I have no new news for you.

**Comment by gdrewb-valve** [comment]
If only one input method was supported which one would you vote for?

**Comment by queenmedley** [comment]
I also have been waiting for korean input.
I don't play dota2 until it is available.
Is is so hard to fix it as waiting for several years?

**Comment by planktonzp** [comment]
Maybe the answer is YES ，and probably the problem is not caused by them. @queenmedley
