### ISSUE TITLE
[Mac] Key bindings

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#89]
It seems that not only the app switch (Command+Tab) is incorrectly bound to Command+H. Many other functions are bound to wrong combinations. Right now I find copy and paste are bound to Ctrl+C and Ctrl+P (should be Command+C and Command+P). I believe there might also are other key binding issues.

Also, is there any way to use the Dota IME on Mac? Like the IME that is built in Dota on Windows.

**Comment by gdrewb-valve** [comment]
There's no IME support on Mac right now.

**Comment by SsnL** [comment]
Sad to hear that @gdrewb-valve . 

Okay I just realized Cmd+Tab is actually working. Cmd+H, while it should not, works as well.

On a unrelated issue, Mac steam in-app web browser constantly freezes, and sometimes after quitting dota Enter doesn't send message in the steam chat window. Do you have any idea where I can report these bugs?

**Comment by SsnL** [comment]
Ctrl+A (select all) is another wrong binding.

**Comment by gdrewb-valve** [comment]
You can report bugs on the regular Steam forums.  I'll pass these two on to the Steam team.

**Comment by SsnL** [comment]
Thanks! @gdrewb-valve

**Comment by SsnL** [comment]
Update: Cmd+Tab doesn't work in latest update. @gdrewb-valve

**Comment by gdrewb-valve** [comment]
For copy and paste (you meant Cmd+V for paste and not Cmd+P, right?) the next update will add Cmd key processing for all of the usual shortcuts (A, C, V, X, Y, Z).

The Cmd+Tab issue is already captured in #6.  Once copy and paste are fixed I think then this issue can be closed?

**Comment by gdrewb-valve** [comment]
Can you try the 6/30 update and see if copy and paste work as expected?

**Comment by gdrewb-valve** [comment]
No confirmation that this is still a problem so closing.

**Comment by ssnl** [comment]
Yes, the problem is fixed... But I imagined I shouldn't be able to use Ctrl+C/V/A/etc shortcuts...

**Comment by gdrewb-valve** [comment]
That's actually expected as it comes from cross-platform code and seems pretty harmless.
