### ISSUE TITLE
Unplayable visual after installing Vulkan.

### ISSUE THREAD

**Issue by khairullah** [ValveSoftware/Dota-2#890]
![20160526211237_1](https://cloud.githubusercontent.com/assets/19559326/15575957/049257c4-2388-11e6-8460-18706d2e0bb1.jpg)

I installed Vulkan, then this happened. Then I found out that my GPU doesn't support Vulkan. So I uninstalled it, and this problem still happened, I tried reinstalling Dota 2, and the problem didn't go away.

Manufacturer:  ASUSTeK COMPUTER INC.
Model:  X555LD
Form Factor: Laptop
Windows 10 (64 bit)
Driver:  NVIDIA GeForce 820M
RAM:  8075 Mb
CPU Vendor:  GenuineIntel
CPU Family:  0x6
CPU Model:  0x45
CPU Stepping:  0x1
CPU Type:  0x0
Speed:  2394 Mhz
 4 logical processors
2 physical processors

**Comment by gdrewb-valve** [comment]
This area is for Mac/Linux bugs only, plus this seems like a system issue and not a dota issue.  You'll want to double-check your video driver, such as removing the NVIDIA driver entirely and then reinstalling.  After that contact NVIDIA.
