### ISSUE TITLE
[Linux] Alt pinging doesn't work

### ISSUE THREAD

**Issue by EmmanuelPerezP** [ValveSoftware/Dota-2#891]
Hello, i have this issue that i cant alt ping or control-alt ping on the ground, i can do it in the minimap but not in the game, i tried rebinding alt modifier in settings to another key in this case "k" and it didnt work either with "k", i also tried others and it didnt work so i dont think its a problem with binding, because it works on the minimap...

i think this started happening like 2-3 updates ago,  it worked fine before...

im running arch linux with bspwm and sxhkd

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  BSPWM
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 364.19
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.74" x 10.55"  (21.50" diag)
                                            47.6cm x 26.8cm  (54.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7935 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  93882 Mb
    Largest Free Hard Disk Block:  51684 Mb
    VR Headset: None detected
```

**Comment by gdrewb-valve** [comment]
Several people have reported this and it doesn't appear to be a Linux problem so the larger team will look at it.

This thread says that resetting your hotkeys will fix it.
https://www.reddit.com/r/DotA2/comments/4lcre5/unable_to_ping_map_after_5252016_patch/

**Comment by Tele42** [comment]
If that does not help, I'm mildly curious if bspwm has an alt + left click default keybinding, which is a relatively common keybinding for move window. That still does not explain why control + alt + left click does not work though.

**Comment by EmmanuelPerezP** [comment]
what gdrewb-valve linked worked i just reseted the hotkeys and worked again! thanks! it may be something to do with people who imported the hotkeys from the old client to reborn

**Comment by tgharib** [comment]
I had the same issue as the OP. Switching to OpenGL mode didn't help. Nor did resetting my dota 2 settings. I had to disable the alt+left click window drag behavior in KDE Plasma to fix the issue.
