### ISSUE TITLE
Vulkan XFCE cannot ALT+TAB when in the game

### ISSUE THREAD

**Issue by Krogash86** [ValveSoftware/Dota-2#892]
Hi i cannot alt+tab while using vulkan and XFCE desktop while in game and fullscreen

**Comment by Tele42** [comment]
Dota 2 Vulkan issues are being tracked over at https://github.com/ValveSoftware/Dota-2-Vulkan.

**Comment by gdrewb-valve** [comment]
Closing as per Tele42's comment.
