### ISSUE TITLE
No end-of-match scoreboard in Steam Offline Mode bot-only match

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/Dota-2#893]
Hi there,

The game works great, the only thing being that at the end of a bot-only match in Steam's Offline Mode, no scoreboard appears. It's not a big deal, but it would be nice if it did. I'm pretty sure it used to appear at the end of offline matches before.

Thanks!

System specifications:
Ubuntu 16.04 LTS (64-bit)
Asus M4A78LT-M LE Motherboard
AMD Athlon II X4 645, 3.10 GHz
Mushkin 8 GB PC3 Blackline RAM (2 x 4 GB)
500 GB Hard Disk
Qualcomm Atheros AR928X Wireless Network Adapter (PCI-Express)
Nvidia GeForce GTX 750 Ti 2 GB GDDR5
Nvidia Driver Version 340.96

**Comment by gdrewb-valve** [comment]
Probably not a Linux issue so this will likely go to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team is going to take a look.
