### ISSUE TITLE
Hero 'About' writeup not updating

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/Dota-2#894]
![dota-2-hero-about-not-updating](https://cloud.githubusercontent.com/assets/1007764/15628650/00473e1a-24cc-11e6-93f2-817ccf1044c1.jpg)

Hello,

While playing Dota 2 recently, I noticed a small glitch. It's when you go into the 'Heroes' tab at the top, select a Hero, select another Hero, and after the third Hero you select, their short writeup under the 'About' tab will not update. It will be stuck on the first Hero you selected.

Have a look in the screenshot attached. The Hero I'm on is Windranger, but under 'About' the writeup is for Vengeful Spirit (whom I had viewed first, followed by Death Prophet).

I don't know if this just occurs in Steam Offline Mode, which I often play lately due to Internet connection issues at my house. But I can definitely reproduce it in Offline Mode.

Thanks!

System specifications:
Ubuntu 16.04 LTS (64-bit)
Asus M4A78LT-M LE Motherboard
AMD Athlon II X4 645, 3.10 GHz
Mushkin 8 GB PC3 Blackline RAM (2 x 4 GB)
500 GB Hard Disk
Qualcomm Atheros AR928X Wireless Network Adapter (PCI-Express)
Nvidia GeForce GTX 750 Ti 2 GB GDDR5
Nvidia Driver Version 340.96

**Comment by gdrewb-valve** [comment]
Probably not a Linux issue so this will likely go to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team is going to look.

**Comment by gdrewb-valve** [comment]
Does this happen every time for you?  If so the larger team asked for your console output from starting the game until you've hit the problem.

**Comment by sunnybubblegum** [comment]
Yes, it happens every time. At least when I'm in Steam's Offline Mode; haven't tested Online Mode. What I've found though is that it happens after I do 'Demo Hero'. It seems like the first Hero I demo, that is the Hero whose 'About' writeup gets stuck.

In the session below, I first viewed Vengeful Spirit, Death Prophet, then Windranger, but the issue still wasn't happening. So I demoed Windranger, returned, then viewed Drow Ranger. This time the 'About' writeup was stuck on Windranger. I proceeded to view Luna, and the text was still on Windranger.

Hope this helps. Let me know if you need anything more.

`nicholas@Nicholas:~$ steam
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1461972496)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0531/072019:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0531/072019:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461968294)
[0531/072019:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442.37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 11: 8x256, total string texture memory is 516.10 KB
Generating new string page texture 12: 16x256, total string texture memory is 532.48 KB
Generating new string page texture 13: 24x256, total string texture memory is 557.06 KB
Generating new string page texture 14: 32x256, total string texture memory is 589.82 KB
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Generating new string page texture 16: 384x256, total string texture memory is 983.04 KB
roaming config store loaded successfully - 6657 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1461972496)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/nicholas/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1461972496)
System startup time: 20.04 seconds
Opening joystick XInput Controller
Installing breakpad exception handler for appid(steam)/version(1461972496)
Generating new string page texture 84: 128x256, total string texture memory is 131.07 KB
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/nicholas/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/nicholas/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 98: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 99: 256x256, total string texture memory is 442.37 KB
process 8579: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
[2016-05-31 07:20:18] Startup - updater built Apr 29 2016 22:18:33
[2016-05-31 07:20:18] Verifying installation...
[2016-05-31 07:20:18] Verification complete
[2016-05-31 07:21:00] Shutdown
Restarting Steam by request...
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/nicholas/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1461972496)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0531/072103:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0531/072103:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461968294)
[0531/072103:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442.37 KB
roaming config store loaded successfully - 6657 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/nicholas/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1461972496)
System startup time: 2.49 seconds
Installing breakpad exception handler for appid(steam)/version(1461972496)
Opening joystick XInput Controller
Generating new string page texture 72: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 73: 128x256, total string texture memory is 573.44 KB
Generating new string page texture 74: 256x256, total string texture memory is 835.58 KB
Generating new string page texture 75: 24x256, total string texture memory is 860.16 KB
Generating new string page texture 76: 64x256, total string texture memory is 925.70 KB
Generating new string page texture 77: 32x256, total string texture memory is 958.46 KB
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/nicholas/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/nicholas/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 91: 8x256, total string texture memory is 966.66 KB
Game update: AppID 570 "Dota 2", ProcID 9024, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nicholas/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nicholas/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 9027 != 9026, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/nicholas/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nicholas/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
Setting breakpad minidump AppID = 373300
Fontconfig warning: "/home/nicholas/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/nicholas/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(20160429221935)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Setting breakpad minidump AppID = 570
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
Setting breakpad minidump AppID = 373300
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042026480 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042026480
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 750 Ti/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Game removed: AppID 570 "Dota 2", ProcID 9029 
No cached sticky mapping in ActivateActionSet.process 8858: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
[2016-05-31 07:21:02] Startup - updater built Apr 29 2016 22:18:33
[2016-05-31 07:21:03] Verifying installation...
[2016-05-31 07:21:03] Verification complete
[2016-05-31 07:27:52] Shutdown
nicholas@Nicholas:~$ 
`

**Comment by sunnybubblegum** [comment]
P.S. I'm sure you'll notice, but I've reverted to Ubuntu 14.04. (My WiFi network adapter wasn't supported in 16.04.) But, as you can see, I still experience the issue.

**Comment by gdrewb-valve** [comment]
Thanks, I've passed this on.
