### ISSUE TITLE
[OS X] Constant crashing since the May 25th update. 

### ISSUE THREAD

**Issue by Panhead360** [ValveSoftware/Dota-2#895]
In all game modes I would receive a drop in frames, which is usually followed by a crash. 

Unlike a lot of users on dev.dota2 I am able to start a match without hanging during startup. But during team fights or an event that may be considered resource intensive, I will crash. 

Prior to the update on the 25th everything was running fine. If I could find the crash reports I would post it here, but since I haven't gotten a notification from OS X on the crash I haven't been able to find it.

**Comment by gdrewb-valve** [comment]
Is this still happening with 7.00?
