### ISSUE TITLE
Dota2 crashing

### ISSUE THREAD

**Issue by odhrnac** [ValveSoftware/Dota-2#898]
Hi, i am using arch linux.

how could i found out why, or some reports.

pls help.

**Comment by gdrewb-valve** [comment]
Go to your Steam client and in the Help menu pick System Information.  Copy that text and paste it here.  That'll help us get an idea of what you have and it may contain crash information.

**Comment by odhrnac** [comment]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  6300 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 364.19
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1189
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20.08" x 11.42"  (23.07" diag)
                                        51.0cm x 29.0cm  (58.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7944 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  27991 Mb
    Largest Free Hard Disk Block:  12863 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
Unfortunately you don't have any crash information caught by Dota.  That often means it's a video driver crash, although that's not always the case.  Can you update to the latest NVIDIA drivers?

**Comment by Tele42** [comment]
@odhrnac if you are able to collect any CrashIDs or crash dumps, please include them in this report.

**Comment by odhrnac** [comment]
@Tele42 if you will tell me how to do that next time it crashes i will post it.
edit: i did find this file "core.dota2.1000.d1... .lz4" but it is 699 MiB. in # /var/lib/systemd/coredump/
@gdrewb-valve i have all drivers upto date. that was the first thing that i did check.

**Comment by Tele42** [comment]
@odhrnac on linux systems, crash dumps are stored locally in /tmp/dumps/ until the next reboot.

**Comment by gdrewb-valve** [comment]
According to NVIDIA the latest Linux 64-bit drivers are 367.18.

**Comment by odhrnac** [comment]
Thx gyus for help. for now it didnt crash but did only play game from that time. the problem probably was hardware because one time it did crash all core where rly high at tempature around 80 C. So i cleaned up the hardware.
@gdrewb-valve yeah that is newest that current one that i am using but its also beta. i had problems with beta drivers in the past. 
if it crashes, i will post the crash dumps here. thx again

**Comment by gdrewb-valve** [comment]
OK, closing for now.
