### ISSUE TITLE
Steam crashed

### ISSUE THREAD

**Issue by Sergiy98** [ValveSoftware/Dota-2#899]
I linux user and I had a mistake Steam, then gave me a 24-hour ban Search match, Fix and remove the ban !!!

**Comment by Tele42** [comment]
This issue tracker is explicitly limited to mac and linux client issues of Dota 2. Account stuff is not done here.

**Comment by gdrewb-valve** [comment]
If you have information on your crash or even system information please post it.

As Tele42 mentions we can't do anything about your account, you can post at dev.dota2.com.

**Comment by gdrewb-valve** [comment]
Closing pending more info.
