### ISSUE TITLE
Cannot start DoTA2 - fatal stalled cross-thread pipe

### ISSUE THREAD

**Issue by GregPK** [ValveSoftware/Dota-2#901]
Came back from holiday and after an update I cannot run DoTA. Starting from steam leads to about 30 seconds of waiting with no result. Starting from console gives this output:

``` bash
user@comp .../dota 2 beta/game $ ./dota.sh
Using breakpad crash handler
../common/pipes.cpp (769) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (769) : Fatal assert failed: ../common/pipes.cpp, line 769.  Application exiting.

Assert( Assertion Failed: fatal stalled cross-thread pipe ):../common/pipes.cpp:769

crash_20160606142628_2.dmp[15493]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160606142628_2.dmp
_ExitOnFatalAssert
```

Attached are the system information - crash dumps should be uploaded.

[system-info.txt](https://github.com/ValveSoftware/Dota-2/files/300386/system-info.txt)

**Comment by gdrewb-valve** [comment]
Does this happen every time?  If you restart Steam does it still happen?  If you restart your computer does it still happen?

**Comment by GregPK** [comment]
Restarting Steam didn't help.
Restarting the system did.

Thanks!

**Comment by gdrewb-valve** [comment]
If you consistently get stuck in this state you'll want to open an issue in the steam-for-Linux section.
