### ISSUE TITLE
No Steam Logon

### ISSUE THREAD

**Issue by menixator** [ValveSoftware/Dota-2#903]
Today I played Terrorblade, which was the worst decision of the day since every time I used reflection, the client freezes up for a second and I get a loss spike(possibly related) and me being the idiot I am, I restarted my router twice to get rid of the loss and then I got the classic "No Steam Logon" error when I am clearly logged in. I have experienced the "No Steam Logon" error multiple times in the past, and it actually has got me into low prio once or twice. It usually happens if I dc and restart the router too much. But in a lot of cases restarting the router isn't a choice. Volvo fix pls :heart: 

EDIT: I forgot to mention that the client shows the red ribbon on the top saying "Connecting to the Dota 2 game coordinator" whenever this happens.

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/Dota-2#system-information.

Restarting a router closes all NAT-forwarded ports, so steam losing connection is makes sense, and it is normal for existing network connections to be dropped. The fact your workaround does anything at all is due to luck more than anything.

**Comment by gdrewb-valve** [comment]
I'm not sure there's much Dota can do about this.

**Comment by Tele42** [comment]
@gdrewb-valve, there's nothing that can be done about users who decide to restart their router midgame, removing that there still is a possible client stall/slow path related to Terrorblade's reflection, but most likely it's a shader that's getting compiled on demand.

**Comment by gdrewb-valve** [comment]
I should have been more clear, by 'this' I meant the post title of No Steam Logon.  I was going to have a quick conversation with some Steam people but likely this will be closed out.

The Terrorblade hitch is a possible problem but it would not be Linux/Mac specific and wouldn't be handled here.

**Comment by gdrewb-valve** [comment]
The Steam team feels that this behavior is expected due to the network interruptions, closing.
