### ISSUE TITLE
Stuck at Match selection menu after receiving abandoned punishment

### ISSUE THREAD

**Issue by truboxl** [ValveSoftware/Dota-2#904]
Now undergoing redownload and reinstall... _sigh_

Fedora 23
MATE Desktop - macro WM
Nvidia GF 820M - Bumblebee with proprietary driver

So I received abandoned punishment (kudos to Dota2 team :-1: ), now I stuck with choosing only Single Draft mode. However, even if I choose to (select only SD mode), it still says I can only pick Single Draft even though I already picked...

Even with all options blank out, the button "Play Dota" can still pushed with that same error appear...
Thank you Dota2 team, I still like the old time out punishment better with low priority team. With this implement, I totally stuck at this infinite blocking...

**Comment by gdrewb-valve** [comment]
This isn't a Linux issue, I'll pass it on to the larger team.

**Comment by gdrewb-valve** [comment]
The regular team suggested starting with -console and in the console entering "dota_match_game_modes 0" and seeing if that helps.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Mac/Linux issue.

**Comment by truboxl** [comment]
seem fixed now...
