### ISSUE TITLE
[OS X 10.11.5] Dota 2 unplayable since 10 june 2016 patch

### ISSUE THREAD

**Issue by AndreasAakesson** [ValveSoftware/Dota-2#906]
[Current patch](http://dota2.gamepedia.com/June_10,_2016_Patch)

Played a game yesterday without problem on about 80-110 FPS. Today, FPS suddenly drops to about 40, and when a spell is cast, Dota 2 freeze for about a second and fps drops to 10-20. 

CPU usage:

```
PID  COMMAND      %CPU  TIME     #TH  #WQ  #POR MEM    PURG   CMPR PGRP PPID STATE
705  dota2        127.6 23:17.87 39   7    400  1628M  8268K  0B   361  702  sleepin
```

`steamoverlaygui` also stopped working all the time. Tried without but doesn't solve the problem.

After leaving a game, the menu GUI becomes very laggy as well.

Specs: 

```
Macbook Pro Retina 15" 2016
2,5 GHz Intel Core i7
16 GB 1600 MHz DDR3
AMD Radeon R9 M370X 2048MB
```

**Comment by gdrewb-valve** [comment]
There are numerous FPS issues open on all platforms, the larger team is currently taking a look.

**Comment by gdrewb-valve** [comment]
Also the June 10 patch was a minor update so it's unclear what exactly would have made a difference to Mac frame rate.

**Comment by gdrewb-valve** [comment]
Do you have any failure reports from the system or from the Steam client system information?

**Comment by tomekmarchi** [comment]
Same here crashes every few minutes.

**Comment by gdrewb-valve** [comment]
@tomekmarchi you're talking about a different problem, please open your own issue and post the full system information from the Steam client.

**Comment by AndreasAakesson** [comment]
> Do you have any failure reports from the system or from the Steam client system information?

Not sure how to retrieve a failure report. Here's what my Steam client system information says:

```
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro11,5
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.5 (64 bit)

Video Card:
    Driver:  AMD Radeon R9 M370X

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 100 Hz
    VendorID:  0x1002
    DeviceID:  0x6821
    Revision:  0x83
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.87" x 11.73"  (23.94" diag)
                                            53.0cm x 29.8cm  (60.8cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475936 Mb
    Largest Free Hard Disk Block:  417651 Mb
    VR Headset: None detected


```

**Comment by gdrewb-valve** [comment]
If Steam or Dota catch a problem they'll record a failure report in the Steam system information. You don't have any so that would suggest the overlay stopping isn't due to a crash, or at least not one that Steam/Dota is aware of.  We'll have to see if we can repro problems here.

**Comment by ghost** [comment]
Just drop OpenGL on osx and implement Metal renderer please

**Comment by gdrewb-valve** [comment]
Is this issue still active?

**Comment by AndreasAakesson** [comment]
I've been able to play Dota after the patch stated in the issue without experiencing freezes and bad fps. Not tried in 7.00 tho.

**Comment by gdrewb-valve** [comment]
OK, I'll close for now.
