### ISSUE TITLE
[Linux] Inotify message ‘Matchmaking is ready’ hangs in the message stack

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#907]
If an inotify message wasn’t dismissed _manually_, i.e. by clicking on it, it will still hang in the message stack until it’s cleared. The stack is not infinite. It allows only 20 messages or so, and when it’s full, inotify won’t allow any new messages to appear. So the notify-send should be called as

```
notify-send --hint int:transient:1 -t 2500  "DotA 2" "Matchmaking is ready!"
```

The transient hint tells inotify to automatically dismiss the message when it expires. 

NB `--expire-time` option of notify-send and tinynotify-send doesn’t actually dismiss the message from the stack, if it wasn’t closed by hand.

Also it would be good to have an option to now show that message, since there’s sound and I’m not deaf.

**Comment by gdrewb-valve** [comment]
We'll add these options.  As for disabling the notification entirely that isn't Linux-specific and you'll want to post that at dev.dota2.com.

**Comment by gdrewb-valve** [comment]
The June 16th update should have the fix for this.
