### ISSUE TITLE
[Linux] Cannot start game with -vulkan option

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#908]
I can run the game with no problem using default options but when passing -vulkan as argument I get

```
LoadSystemAndDependencies():
AppSystemDict: Error in Connect() of interface 'GameUI011'!
```

when trying to start the game. I'm on Fedora 22 with NVIDIA prop. drivers.

**Comment by ghost** [comment]
I'm a complete retard. I just noticed the "Dota 2 - Vulkan support checkbox". _facepalm through face_

**Comment by girng** [comment]
> I'm a complete retard.

😍
