### ISSUE TITLE
[Linux] Audio skipping

### ISSUE THREAD

**Issue by kevin-abiera** [ValveSoftware/Dota-2#91]
Audio (background music, unit speech, ui sound) is skipping thoughout the game (dashboard and in-game)

This may not be related but the mic level in the audio settings of the game is abnormally spiking to around 50%. There is no mic plugged in and no noise around for it to even move. Is there a way to disable mic from the game?

System:
Arch Linux
Audio device:

```
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
    DeviceName:  Onboard Audio
    Subsystem: ASUSTeK Computer Inc. Device 1ad3
    Flags: bus master, fast devsel, latency 0, IRQ 28
    Memory at df000000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: [50] Power Management version 2
    Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
    Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
    Capabilities: [100] Virtual Channel
    Capabilities: [130] Root Complex Link
    Kernel driver in use: snd_hda_intel
    Kernel modules: snd_hda_intel
```

EDIT: BTW, there is no lag/skipping visually.

**Comment by davidw-valve** [comment]
I have made a change which I hope will fix this, will be available in the next update.

**Comment by davidw-valve** [comment]
When the next update comes out please let us know if you are still experiencing this. We are unsure if it will fix it or not.

**Comment by lightning18** [comment]
The update fixed the issue. Thanks.
