### ISSUE TITLE
[OS X] Energy consumption eats battery with charger plugged in.

### ISSUE THREAD

**Issue by lolgear** [ValveSoftware/Dota-2#910]
Battery discharging. ( charger plugged in (85 wt) ).
Maybe it could be fixed by custom launch options.

Config:
OS X 10.10.5.
Steam latest.
Dota 2 latest.
Macbook Pro 15'' Late 2011.
AMD Radeon HD 6770M 1024 МБ
16 ГБ 1333 МГц DDR3

Another ( related ) behavior.
While observing dota 2 stream it still drains battery with plugged charger, but not too fast.

**Comment by Tele42** [comment]
You might be able to get Dota 2 to back off a bit by enabling vsync if it not already.

**Comment by gdrewb-valve** [comment]
I'm not sure of the intent here.  Is this a request for dota to go into a batter-saver mode or something?  I don't believe anything like that is going to happen.

**Comment by Tele42** [comment]
It looks like @lolgear does not need to extend the battery life, just get the overall system power usage below what the undersized ac adapter can provide to the laptop.

My thought is there's not much to be done as this is bad hardware design, beyond limiting the game's max fps, which might lower gpu usage and a bit of cpu usage.

**Comment by lolgear** [comment]
well, youtube videos are ok with power adapter, but steam streaming is not ok ( eats battery while charging ). ( I think that something happens in web-sockets or other related internet technology? )

ok, it doesn't happen, for example, in diablo 3. ( adapter charges ( or supports ) battery on high level ).

it is not a problem of hardware, it is a problem of high ( ? ) resources consumptions of current software.

And, last example, it doesn't happen in other valve games ( TF2 or L4D ).

**Comment by gdrewb-valve** [comment]
Dota 2 does not attempt to minimize energy usage / CPU usage and I don't believe that's going to change.  You can put in a feature request at dev.dota2.com but there's no Mac/Linux specific issue for that so I'm closing this out.

For Steam streaming you can post in the Steam forums.
