### ISSUE TITLE
Weird sounds when playing certain heroes?

### ISSUE THREAD

**Issue by shahnanigans** [ValveSoftware/Dota-2#911]
Im not sure if this is just me, but every time I play Jakiro I hear weird drum samples in the game. No, I don't have anything playing in background, and no, I don't listen to music. Can someone reproduce this? I can't use FRAPS to record because it makes the game laggy/unplayable. 

Edit: It happened with another hero but I can't remember who I was playing.

Edit #2: System specs added in third post, sorry about not attaching them in the initial post. Also, the drum sounds are akin to a breakbeat sample.

**Comment by gdrewb-valve** [comment]
Can you post your Steam system info?

**Comment by shahnanigans** [comment]
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookAir7,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  2200 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.4 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 6000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x1626
Revision:  0x9
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.39" x 11.46"  (23.39" diag)
                                        51.8cm x 29.1cm  (59.4cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114543 Mb
    Largest Free Hard Disk Block:  7334 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
Does this happen every time?  I just tried Jakiro both in a bot game and in Demo Hero on my Mac without an issue.

**Comment by shahnanigans** [comment]
No it happens randomly. I was thinking it was a Taunt item but as far as I know none exist for him.

I'll try to see if I can reproduce it in a bot match while recording it, and upload a video soon.

**Comment by gdrewb-valve** [comment]
OK, thanks.

**Comment by shahnanigans** [comment]
I think it is a taunt item that I keep hearing. I think we can close this.
