### ISSUE TITLE
Attempting to purge m_fencedResourceList.Count() = 1, m_pendingFencedResourceQueue.Count() = 0, nCurrentCmdBuffersAvailable = 0, nAllocatedCommandBuffers = 7785

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#912]
I am using Ubuntu 16.04 with a custom Kernel 4.7 RC3 with latest AMD GPU- PRO drivers with a 290X and the console it always prints

`Attempting to purge m_fencedResourceList.Count() = 1, m_pendingFencedResourceQueue.Count() = 0, nCurrentCmdBuffersAvailable = 0, nAllocatedCommandBuffers = 7785`

where nAllocatedCommandBuffers increases all the time. It prints extremely fast. (The game is in Vulkan mode of course)

I think maybe this could help you. Sadly the game always crashes after some minutes so it's currently unplayable with this setup although the performance isn't bad(~100FPS).

**Comment by gdrewb-valve** [comment]
For the future Vulkan bugs should be filed in the Vulkan section.

**Comment by ghost** [comment]
Thanks for the reply.
I switched to 4.7 RC4 now. Either choosing RC3 or RC4 in grub the performance for Dota 2 decreased by about 30-40%  in comparison to last week.
There is also another message that is printed between the masses of nAllocatedCommandBuffers - announcements in the console:
Bailing out of vkWaitForFences() after 0.000079 seconds

For future bugs - may I ask where to find the Vulkan section please?

**Comment by Tele42** [comment]
The Dota 2 Vulkan issue tracker is at https://github.com/ValveSoftware/Dota-2-Vulkan.

**Comment by ghost** [comment]
Thank you!

**Comment by ethan961** [comment]
I also have this problem, along with the segfault roughly 5 minutes into spectating a game.
Running Arch Linux, linux-ck 4.6.3. bspwm WM, R7 260X 2GB with AMDGPU-PRO 16.30.3.306809, Xorg 1.18.3. Problem also occurred with the previous AMDGPU-PRO release.

**Comment by gdrewb-valve** [comment]
Should this be closed in favor of the Dota-2-Vulkan issue?

**Comment by ethan961** [comment]
I forgot to post my findings here as well but I found this issue was the result of using the AMDGPU-PRO userspace driver without the supplied AMDGPU-PRO DKMS module (and instead using the unpatched upstream kernel driver). Since the DKMS module didn't easily build on newer kernels, people were ignoring the installation of that module. Essentially, an unsupported configuration that works partially out of luck. For that reason I would say both should be closed.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
