### ISSUE TITLE
[linux] random crashes during game

### ISSUE THREAD

**Issue by tpruzina** [ValveSoftware/Dota-2#913]
For about two weeks now I'm experiencing game seemingly random game crashes.
Generally they happen at random point during match, but quite often (but not 100%) the game crashes after the match.

> [34902.913009] dota2[13124]: segfault at 55a37d973ca0 ip 00007f8a60c04912 sp 00007fffe189e250 error 6 in libclient.so[7f8a5daa9000+4160000]
> [34910.073193] dota2[13869]: segfault at 0 ip 00007f813d053981 sp 00007fff067a7200 error 6 in libtier0.so[7f813d023000+64000]
> ...
> [40243.812813] dota2[14383]: segfault at 55cae91ee958 ip 00007f4199f4e912 sp 00007ffedc3b4710 error 6 in libclient.so[7f4196df3000+4160000]

<pre>Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4500 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.0-rc3-linus-master+
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.27
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 20.91" x 11.73"  (23.94" diag)
                                            53.1cm x 29.8cm  (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1150
    
Memory:
    RAM:  15976 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Total Hard Disk Space Available:  228804 Mb
    Largest Free Hard Disk Block:  80681 Mb
    VR Headset: None detected
    
    Sat Jun 18 13:04:59 2016 GMT: file ''/tmp/dumps/assert_20160618150457_9.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 19:29:58 2016 GMT: file ''/tmp/dumps/crash_20160618212012_2.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 20:04:04 2016 GMT: file ''/tmp/dumps/crash_20160618213100_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 20:21:55 2016 GMT: file ''/tmp/dumps/crash_20160618220405_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 20:55:11 2016 GMT: file ''/tmp/dumps/crash_20160618222156_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 21:05:40 2016 GMT: file ''/tmp/dumps/crash_20160618225512_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 21:09:02 2016 GMT: file ''/tmp/dumps/crash_20160618230541_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 21:34:09 2016 GMT: file ''/tmp/dumps/crash_20160618233408_6.dmp'', upload yes: ''CrashID=bp-a18e1530-a256-4468-ae92-73ee62160618''
    Sat Jun 18 21:34:09 2016 GMT: file ''/tmp/dumps/crash_20160618230934_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 21:34:11 2016 GMT: file ''/tmp/dumps/assert_20160618233410_8.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 22:03:25 2016 GMT: file ''/tmp/dumps/crash_20160618234115_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 22:03:31 2016 GMT: file ''/tmp/dumps/crash_20160619000326_1.dmp'', upload yes: ''Discarded=1''
    Sat Jun 18 23:32:26 2016 GMT: file ''/tmp/dumps/crash_20160619004501_1.dmp'', upload yes: ''CrashID=bp-b083133e-523d-44cc-84d6-40e072160618''
</pre>

Will try to checkout core dump in gdb shortly, but I thought I would create a ticket here meanwhile.

**Comment by gdrewb-valve** [comment]
I looked at the two crash reports but unfortunately they don't have enough information to exactly isolate the problem.  We'll have to see if we can get more from people to narrow things down.

**Comment by tpruzina** [comment]
Looked at it in gdb and couldn't get much out of it either, for the moment I downgraded to stable kernel (4.6) and older nvidia drivers (364.19) to see if that makes a difference.

Edit: It doesn't seem to have made any difference.
Edit2: Switched back to steam beta and the problem haven't appeared in third consecutive game (except for crashes after the game for which I filled separate bug).

**Comment by tpruzina** [comment]
Can't say for certain but it seems that crashes have disappeared in latest version of the game, also noticed that affected binary (libclient.so) has changed. Past few games I had no crashes.
If I don't see any crashes in upcoming days I will close the bug.

**Comment by gdrewb-valve** [comment]
OK, thanks.
