### ISSUE TITLE
HELP Dota2 refused to launch 

### ISSUE THREAD

**Issue by cumnatu** [ValveSoftware/Dota-2#914]
Hi all, 
Just changed my hdd to a new SSD , all good , fresh OS (El Capitan 10.8.5)
Installed steam and then dota2.
Now no matter what i'm doing dota2 will refuse to launch , just for a flash of a second the small window with "preparing to launch " appears and then nothing at all. I have zero errors , cheated the files and all good , tried with different set launch options as -novid , etc (basically what i could find online ) same problem. i tried to delete all files and install all over but the problem is still with me . 
this is the system i running on 
Processor Name: Intel Core i7
Processor Speed:    2.3 GHz
Number of Processors:   1
Total Number of Cores:  4
L2 Cache (per Core):    256 KB
L3 Cache:   6 MB
Memory: 8 GB
Intel HD Graphics 4000 (Built-in)
NVIDIA GeForce GT650m 512MB (PCIe)
Thank you guys and please feel free to guide me on this problem

**Comment by gdrewb-valve** [comment]
Dota requires OS X 10.9 or newer.
