### ISSUE TITLE
[OSX] Memory leak?

### ISSUE THREAD

**Issue by Sebby91** [ValveSoftware/Dota-2#915]
Dear problem-solvers,

The first time I noticed this (and maybe it was earlier) was during the Manila Major qualifiers, but it seems that dota 2 is causing some memory issues. When I try to spectate games, my iMac is becoming more and more slow after watching more and more games. This due to the kernel_task memory slowly increasing. For example today, I've watched Liquid - OG. Before the game starts, my kernal_task is around 300-400 MB (I don't have a screenshot of this but i can add it once i restarted the iMac once again). Then after game 1:

![screen shot 2016-06-19 at 11 34 20](https://cloud.githubusercontent.com/assets/15364034/16176859/30f8a494-361b-11e6-9dc4-9b1217eff7da.png)

And after game 2:
![screen shot 2016-06-19 at 12 36 11](https://cloud.githubusercontent.com/assets/15364034/16176861/3e2b5864-361b-11e6-8b3d-669e3989f759.png)
with the memory pressure:

![screen shot 2016-06-19 at 12 36 19](https://cloud.githubusercontent.com/assets/15364034/16176868/5a22cffc-361b-11e6-8b0b-fc1c824302e7.png)

Closing dota 2 will not bring the kernel_task down:
![screen shot 2016-06-19 at 12 37 45](https://cloud.githubusercontent.com/assets/15364034/16176869/605f715e-361b-11e6-8ce8-1aa32f7c74d3.png)

Memory pressure:
![screen shot 2016-06-19 at 12 37 50](https://cloud.githubusercontent.com/assets/15364034/16176870/66699a84-361b-11e6-88fd-3f856b2dfc01.png)

Watching more games will result in the forced restart iMac with the black screen (something along the lines your mac was forced to restart because of a problem - similar to the blue screen of windows). This usually happens during the pick phase when spectating games. I also noticed when I close down dota 2 its icon will stay in the dock, like I previously posted here. The problem of the icon in the dock is still resolved using the solution suggested in that topic, but I cannot restart my iMac on a normal manner. It will simply tell me that 1 program is running and it cannot be restarted while finder shows me only the finder is running. My specs:

![screen shot 2016-06-19 at 12 46 25](https://cloud.githubusercontent.com/assets/15364034/16176885/dbbb1e48-361b-11e6-897f-e0580c17e84b.png)

Also this problem is exactly the same on my other iMac (same specs).

Edit: after reboot and watching game 3:

![screen shot 2016-06-19 at 14 14 20](https://cloud.githubusercontent.com/assets/15364034/16177293/456e4944-3628-11e6-9155-45b718951f55.png)

Kind regards,
Sebby

**Comment by Sebby91** [comment]
I have to add: It feels to me this is a lesser problem when you are playing. But I can't confirm yet (have to play a couple of games in a row) and prolly won't be able in the coming couple of days (busy). It seems to occur during spectating, or at least occurs more severe.

**Comment by gdrewb-valve** [comment]
If you google for kernel_task you'll find a lot of posts about problems with memory usage so there may be an issue larger than Dota here.  In general anything that stays around after the process exits is the system's responsibility but we'll take a look.

**Comment by Sebby91** [comment]
But isn't it strange I've never had these issues until recently? I am a IT newbie so I have honestly no clue, but this was previously not there when playing/spectating dota2. I have it on two different machines as well, so I doubt the memory is broken in both of them. It could be OSX related but I can't remember updating it or whatsoever..

**Comment by gdrewb-valve** [comment]
Dota is provoking the issue but that doesn't mean it's a Dota problem.  It may very well be a Dota problem, but it's clear that if there's excessive memory usage when Dota isn't running that it isn't Dota that's at fault.

**Comment by gdrewb-valve** [comment]
I did some testing on my Mac and I didn't see anything like this.  We'll have to wait and see if other people hit it and we can find a pattern.

**Comment by Sebby91** [comment]
Just curious gdrew, are you using El Capitan?

**Comment by gdrewb-valve** [comment]
No, I'm running Yosemite.

**Comment by gdrewb-valve** [comment]
Is this still happening with 7.00?

**Comment by rafagonc** [comment]
Yes! My kernel_task keeps using 400% of my cpu
