### ISSUE TITLE
[linux] segfault post-game

### ISSUE THREAD

**Issue by tpruzina** [ValveSoftware/Dota-2#916]
Game often (~75% of the time crashes after I attempt to leave scoreboard for main menu).

gdb output (dota.sh GAMEDEBUGGER="gdb"):
https://gist.github.com/tpruzina/8e8bb7ee3b88dc164d25c97274b32148

pmaps showed me:
`7f1a47157000-7f1a4b2b7000 r-xp 00000000 08:03 1916036                    /home/tomas/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so`

0x7f1a4a2b2912 - 0x7f1a47157000 = 0x315B912
![screenpng](https://s32.postimg.org/6a97my1xx/screen.png)

registers:
![registers](https://s32.postimg.org/4g7orwt51/screen.png)

rax_8 => 0x800041f × 0x8 = 0x400020f8
rsi+ rax_8 => 0x56061f8c6000 + 0x400020f8 = 0x56065f8c80f8

`(gdb) x 0x56065f8c80f8
0x56065f8c80f8: Cannot access memory at address 0x56065f8c80f8`

Unfortunatedly I killed gdb as it was dumping memory from rsi upwards, but I won't have problem reproducing the bug so I will have another go at it soon(ish).

<pre>Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4500 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.0-linus-master
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 364.19
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 20.91" x 11.73"  (23.94" diag)
                                            53.1cm x 29.8cm  (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC1150
    
Memory:
    RAM:  15978 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Total Hard Disk Space Available:  228804 Mb
    Largest Free Hard Disk Block:  122141 Mb
    VR Headset: None detected
    
    Mon Jun 20 12:05:51 2016 GMT: file ''/tmp/dumps/crash_20160620140545_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 13:41:15 2016 GMT: file ''/tmp/dumps/assert_20160620140621_1.dmp'', upload yes: ''CrashID=bp-99f111f5-8528-4ba4-ba5b-e31742160620''
    
</pre>

**Comment by gdrewb-valve** [comment]
It's hard to say for sure but this looks very similar to a crash that occurs on all platforms.  The larger team was looking but I'm not sure if they've made any progress.

**Comment by tpruzina** [comment]
If you consider this a dupe of already existing bug then please close.

**Comment by gdrewb-valve** [comment]
We don't know for sure if it's a dup or not so we're leaving this open.

**Comment by gdrewb-valve** [comment]
If you run without gdb and let the crashes get processed do you end up with more uploaded failure reports with crash IDs?  The one you posted above is for the Steam client and not Dota.

**Comment by gdrewb-valve** [comment]
I'm not able to repro this problem.

**Comment by tpruzina** [comment]
I haven't ran into this problem in quite a while and unfortunatedly I can't pinpoint what fixed it (albeit I switched from beta to stable). Feel free to close the bug.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
