### ISSUE TITLE
Courir Bug

### ISSUE THREAD

**Issue by chrissisura** [ValveSoftware/Dota-2#919]
I just now played a game where i had massive lag everytime i used the courir. A friend of mine complainted about the same issue in the same game. Just wanted to let you know. If it goes on, i will give more information. Playing on OS X El Capitan

**Comment by Tele42** [comment]
Possible duplicate of #863.

**Comment by gdrewb-valve** [comment]
What type of courier was it?  Do you have a match ID or anything to look at?

We'll also need more specific system information, particularly RAM and GPU information.

**Comment by gdrewb-valve** [comment]
Closing until we get enough information to investigate.
