### ISSUE TITLE
[Mac] Top 10 custom game label

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#92]
![screenshot 2015-06-24 22 24 29](https://cloud.githubusercontent.com/assets/5674597/8347845/4b1473de-1ac0-11e5-859e-401041251ed9.png)
The 10th game's name has its bottom part cut.

**Comment by gdrewb-valve** [comment]
What resolution are you using?

**Comment by SsnL** [comment]
I will check when I get home. But I believe I was using 1900*1440 on a 15 inch retina mbp.

**Comment by SsnL** [comment]
I am using 1400*900 on a 15 inch retina MBP (2880*1800 display). @gdrewb-valve

**Comment by gdrewb-valve** [comment]
This isn't Mac/Linux specific.  I've passed it on to the larger team and it won't be tracked here.
