### ISSUE TITLE
Incredibly slow main menu

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#921]
hi,
I played the last time 5 days ago when everything was fine, today I started dota 2 (partly due to the immortal 2 being release and also to just enjoy a game) and I find the main menu to be incredibly slow. Switch from one tab to another (shop, heroes..) is a matter of minutes. I click on it and then I  can go and make tea and by the time I get back it might have switched.

E: While writing this I was closing the game, which apparently crashed and took the steam client with it.
http://pastebin.com/pXzbhC2a One line is German for some reason, it states: /home/turmfalke/.local/share/Steam/steam.sh: Line 753:  2218 Segmentation fault  $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

E2: System info http://pastebin.com/BheKcmkS and I using '__GLVND_DISALLOW_PATCHING=1 steam' to work around that nvidia/opengl bug.

**Comment by tpruzina** [comment]
I can confirm this, main menu UI is unusable since last patch (it doesn't freeze per say, but activating any UI element can take dozens of seconds).

**Comment by kolobos** [comment]
This man speaks truth.

First of all, here is the temporary solution:
Start Steam like this:

```
export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"
steam
```

Source: https://github.com/ValveSoftware/steam-for-linux/issues/4444

After the yesterday Immortals 2 update, Dota 2 is now more sensitive to the DBUS sessions shenanigans bug thingie, nothing of the following helps:
1. Opting out of Steam Beta and using the stable version
2. Switching from LLVM-9999 and Mesa-9999 to stable versions.
3. Validating game files.

It's suspicious that this issue only affects me and the honest gentlemen above.
What I know, is that I have an improperly installed PulseAudio (installed it to play Faeria), without properly configured Access Lists (I just have my user in the Audio group).
I also get these errors when starting Dota 2 from the command line.
Here is how I start Dota 2 to test (not sure if it's the right way, since I get a Dota cursor and a gray empty background): `.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /home/media/SteamLibrary/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2 &`

Here are the errors without DBUS session export:

```
DumpContextInfo: OpenGL renderer Gallium 0.4 on AMD BONAIRE (DRM 2.43.0 / 4.6.0-gentoo, LLVM 3.9.0)
DumpContextInfo: Using OpenGL context version 4.3
DumpContextInfo: Context supports GLSL version 4.30
Fontconfig warning: "/home/media/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/media/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/bin/pulseaudio)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecore-8.0.so)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecommon-8.0.so)
/usr/bin/pulseaudio: relocation error: /usr/bin/pulseaudio: symbol pa_sample_rate_valid, version PULSE_0 not defined in file libpulse.so.0 with link time reference
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/bin/pulseaudio)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecore-8.0.so)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecommon-8.0.so)
/usr/bin/pulseaudio: relocation error: /usr/bin/pulseaudio: symbol pa_sample_rate_valid, version PULSE_0 not defined in file libpulse.so.0 with link time reference
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/bin/pulseaudio)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecore-8.0.so)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecommon-8.0.so)
/usr/bin/pulseaudio: relocation error: /usr/bin/pulseaudio: symbol pa_sample_rate_valid, version PULSE_0 not defined in file libpulse.so.0 with link time reference
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/bin/pulseaudio)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecore-8.0.so)
/usr/bin/pulseaudio: /home/kolobos/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib64/pulseaudio/libpulsecommon-8.0.so)
/usr/bin/pulseaudio: relocation error: /usr/bin/pulseaudio: symbol pa_sample_rate_valid, version PULSE_0 not defined in file libpulse.so.0 with link time reference
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

fish: “.local/share/Steam/ubuntu12_32/…” terminated by signal SIGKILL (Forced quit)
```

Haven't looked into command line with the DBUS session export, PulseAudio problem is just my guess for now.

**Comment by Turmfalke2** [comment]
So it is dbus related? I am on Gentoo with -dbus in USE and am I am using pure pulse audio. So far I always thought steam is only using  pulseaudio for the microphone. 
For what does Steam/Dota need a dbus? It is perfectly normal for me not to have a dbus session running.

**Comment by tpruzina** [comment]
I can confirm that workaround in  third post works. It seems that dbus connection is timing out every time introducing heavy lagging in UI actions.

**Comment by kolobos** [comment]
So I tried to test again with DBUS session export, and I seem to be getting the same PulseAudio errors, so PulseAudio might be unrelated to this issue, or i'm not starting Dota 2 properly (Dota 2 not in the same DBUS session as Steam).
So what we know:
There is a bug (only affects Gentoo?) that was added to Dota 2 yesterday, and it's DBUS related.
Hopefully Dota 2 team can bisect and find an universal solution for all affected Steam games, not only Dota 2 (although I don't know any other games with this issue).

**Comment by tpruzina** [comment]
@Turmfalke2 Steam games ship with their own dbus drivers via steam runtime library, that said you will always have dbus installed in your /home/user/.local/share/steam directory.
It's possible that forcing usage of system dbus via LD_PRELOAD might work around the problem, but merely switching to stable version of steam _could_ also do the trick.
I'm gonna try that out and I'll also debug stuff with dbus monitor to see whats going on.

Bug is probably related to this error message from steam:
(steam:3960): libappindicator-WARNING **: Unable to get the session bus: Command line `dbus-laun-zero exit status 127: dbus-launch: /home/tomas/.local/share/Steam/ubuntu12_32/steam-runtime/anch)\ndbus-launch: /home/tomas/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-li relocation error: dbus-launch: symbol _dbus_strdup, version LIBDBUS_PRIVATE_1.10.8 not defined

Edit: LD_PRELOAD workaround works (force usage of system dbus):
`LD_PRELOAD="libdbus-1.so" steam`

It unfortunatedly introduce other steam linkage errors but it doesn't seem to be affecting anything as far as basic steam usage and dota2 is concerned.

**Comment by kolobos** [comment]
I've tested starting Dota 2 in the same DBUS session as Steam, and I stopped getting PulseAudio errors on the command line.
Which means this is likely to be PulseAudio related.
Do you guys have an improperly configured PulseAudio, same as me?
Here is how PulseAudio should be configured on Gentoo, using ConsoleKit: https://wiki.gentoo.org/wiki/PulseAudio#Configuration
I'm not using ConsoleKit and just have my user added to the Audio group.

**Comment by Turmfalke2** [comment]
I have no pulseaudio nor consolekit installed - so I am pretty sure it not improperly configured.

E:  @tpruzina wish we could do away with the steam runtime, it is doing all kinds of strange like preloading 32bit libraries and then depending on that the fail in a safe away. Unfortunately last time I tried that I found that steam depended on some really outdated libpng version that hasn't got any official updates in the last 5 years. Is valve maintaining their own version?

**Comment by catern** [comment]
I can confirm that kolobos's solution worked. I'm running xmonad and didn't have a dbus session set up, so sticking

```
export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"
```

into my .xinitrc caused a dbus session to be started on X launch, and made it accessible to Steam/DotA 2. As an added benefit, now that dbus is working properly again, I get notifications on match found.

**Comment by tpruzina** [comment]
@Turmfalke2  They still do use old version. I kinda get why they are doing it though, supporting all linux distros (at least unofficially) would be absolute pain and that's why they ship their own libraries much in the same way windows binaries are distributed.
While old libpng might not be a problem (they still use really old version). things like d-bus cause problems because they are incompatible with themselves. E.g. active dbus daemon that holds system bus listener might not work with older/newer client that tries to talk to it at that bus.

Unfortunatedly gentoo's ~amd64 glibc isn't even compatible with older glibc that steam ships, there are some nasty bugs when you try to use system libraries on top of valve compiled runtime.

It would be nice if valve could update libs regularly and test properly, but that would actually increase costs to make sure everything works. Most SW companies actually run obsolete stuff as long as it works, ignoring security updates and stuff.

Anyways, I'm going off topic, howg.

On gentoo  I actually use older dbus to see notification tray, current stable versions are too new for it to even display in tray bar of awesome WM (1.8.16 vs 1.10.1[6,8])

**Comment by Turmfalke2** [comment]
@tpruzina I know that issue, although in our case it not libpng, but ubuntu 12.04 for php 5.3.. (Please dear god let php die).
For dota2 I guess I am going to look into getting it a dbus. Did you find out what it is actually doing with dbus? Other than the match notification?

**Comment by gdrewb-valve** [comment]
The latest release of Dota enabled the SDL IME support which uses ibus.  That introduces new dbus usage and may be the core problem here.  I'm assigning to the SDL dev.

**Comment by vekin** [comment]
export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"
steam

Thank you for this.
I was having issues with chat bringing my fps down to sub 1fps and the characters drawing extremely slowly.

Also I had never seen the games notifications until now.

**Comment by Turmfalke2** [comment]
Still don't get any notifications, do they use libnotify? Don't really need them.

**Comment by bennofs** [comment]
I've got the same problem (very slow menus, like about 3 seconds of delay after hovering over a menu item takes effect), but the workaround does not work for me. Also, the game is very slow in general, in hero selection as well. Haven't been able to play a game yet to see if it is different in-game.

**Comment by kolobos** [comment]
@bennofs Make sure that you are using Bash shell, and setting DBUS_SESSION_BUS_ADDRESS variable in the same shell session.

**Comment by bennofs** [comment]
@kolobos I did that. In my session, DBUS_SESSION_BUS_ADDRESS is also already set, yet I'm still affected by this.

**Comment by Vylaern** [comment]
Hi,

I have the same problem in last week. Which solution (step by step) does it work?

BTW: I have similar problem (very slooow menu) with Total War Attila (Total War Empire works fine) and UFO, Enemy Unkown (used to be fine before).

I use Gentoo amd64 (stable)

UPDATE
This:
Start Steam like this:
export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"
steam

Solved my problem with all of my games!!!! :) Many thanks :)

**Comment by bennofs** [comment]
Oh, I found out why the workaround did not work for me. It is since on my system, steam is run in a chroot environment and not all environment variables are propagated to this environment (DBUS_SESSION_BUS_ADDRESS is not propagated). Sorry, my bad, fixing this makes steam work for me. So it is indeed related to dbus.

**Comment by clinew** [comment]
I ran into the exact same problem, too (I'm also running Gentoo on amd64). Adding `export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"` to my Steam launch script solved the problem for me.

**Comment by Myrl** [comment]
@bennofs Nixos bros. That aside, how did you fix it to make steam work for you?

Edit: Oh, I didn't realize the referenced commit.
Edit 2: How do I use that when I use nixpkgs-channels? Cherry-pick that specific commit?

**Comment by bennofs** [comment]
@Myrl yeah, cherry-pick the commit works for me.

**Comment by pseudonom** [comment]
New to Nixos here. What do I need to do once I have that commit in my `nixpkgs`? Not `nixos-rebuild switch`?

**Comment by Turmfalke2** [comment]
I actually have never heard of Nixos, sounds like you are looking for information on some distribution specific programs? Maybe try your distro's irc channel or documentation (if available).

**Comment by tjackson** [comment]
I can also confirm the third post fixes my issue on Slackware. Oddly it also fixed a segfault I was having on exiting the game:

    Failed: m_pInternalPipe->BRead( bufRet )

**Comment by joaormatos** [comment]
As I noted in https://github.com/ValveSoftware/steam-for-linux/issues/4444, you should use:  

```
dbus-run-session steam
```

instead of:

```
export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)"
steam
```

If you want the dbus-daemon process to be gone after you're done using Steam.

**Comment by AlonzoTG** [comment]
joaormatos is WRONG. His suggested command does not work, the export [blah blah blah] command does. 

So how do I select the Vulkan version and verify that is the version I'm playing?

**Comment by Turmfalke2** [comment]
Haven't tried dbus-run-session, but according to it's manage page it should work and assuming the dbus session persists through the forks it should be the preferred way of getting a session dbus.
Also what has vulkan to do with this issue?

**Comment by joaormatos** [comment]
@AlonzoTG `dbus-run-session` keeps the `dbus-daemon` alive for as long as the process you told it to start.
In my system (Debian), when I type `steam` in the terminal and Steam isn't already running, the command doesn't return until I close Steam.

However, it's possible that in your system the process launched by your `steam` command forks and returns immediately, in which case Steam itself outlives the `dbus-daemon`.

I'll try to look for a way to accommodate that scenario.

**Comment by bennofs** [comment]
To all NixOS users: to get this fix, you can use the following command:

```
$ nix-env -iA steam -f https://github.com/NixOS/nixpkgs/archive/20f009d56df9a0e5f224761ba48aa4142564753e.tar.gz
```

It will install a `steam` from `nixos-unstable` in your user environment, which has the fix. You can also just update to latest `nixos-unstable`.

**Comment by joaormatos** [comment]
I found another workaround, which works on my system for other games that have DBus-related issues.  
I didn't test with DOTA 2 since I don't currently have it installed, but it might work with it too.

No need to even start a DBus daemon for this one, just put some gibberish in DBUS_SESSION_BUS_ADDRESS, like so:

```
DBUS_SESSION_BUS_ADDRESS="gibberish" steam
```

I don't know why it works.  
(I imagine it might be making the dbus library give up its search for a session DBus daemon, preventing a recurring (and slow) lookup of its address through the X server, which I suspect is the cause for the slowdown.)

**Comment by fengshaun** [comment]
I can confirm that setting `DBUS_SESSION_BUS_ADDRESS` to any random string fixes the micro-stutter.

**Comment by Vylaern** [comment]
What do you think, to send this suggestion to Steam developers, so they could provide a sollution inside Steam engine (instead of putting command lines manually by our-self). There could be more people who cannot find a help, and this solution works for few other well known games.

**Comment by gdrewb-valve** [comment]
The root cause is in SDL so getting a fix in SDL would be the best solution.  The SDL developer is assigned the bug so hopefully they'll fix it.

**Comment by cybik** [comment]
@gdrewb-valve can you point us to the SDL-based issue?

**Comment by gdrewb-valve** [comment]
Do you mean something in their bugzilla?  I don't believe they've opened one, that's up to rcgordon.  As mentioned above the issue is that SDL started using dbus for ibus IME support and there's bad behavior when dbus doesn't initialize.

**Comment by cybik** [comment]
Ah, I didn't see that message. Sorry for the bother!

**Comment by Turmfalke2** [comment]
sdl issue is probably fixed by now.
