### ISSUE TITLE
Mouse not working after latest patch

### ISSUE THREAD

**Issue by simonvpe** [ValveSoftware/Dota-2#924]
My mouse Isn't working since the last patch. In the UI the mouse pointer moves around fine but it doesn't click where you would expect it to so I had to Alt+Tab out and kill the process in a terminal. The steam overlay seems to work fine tho.

I run vanilla Debian with 4.3 kernel and a not very recent AMD graphics card.

**Comment by bennofs** [comment]
Might this just be another instance of #921? The mouse is just moving incredibly slow, so you will see the action of the click, but you'll have to wait for ages.

**Comment by simonvpe** [comment]
Indeed it is. I didn't realize it was really slow. Anyhow, now it is fixed. Thank you
