### ISSUE TITLE
Trophy points don't work.

### ISSUE THREAD

**Issue by vekin** [ValveSoftware/Dota-2#925]
When I went from lvl 37 trophy to lvl 38 I am supposed to get over 1k trophy points?
My profile level doesn't reflect the earned points.

**Comment by gdrewb-valve** [comment]
This forum is for Mac and Linux only bugs.  You'll want to post at dev.dota2.com

**Comment by vekin** [comment]
I'm using the Linux client.

**Comment by gdrewb-valve** [comment]
Your issue isn't Linux-only, though, so you'll want to post at dev.dota2.com
