### ISSUE TITLE
[OS X 10.11.5] No GUI

### ISSUE THREAD

**Issue by lolgear** [ValveSoftware/Dota-2#927]
Latest update.
OS X 10.11.5

There is no gui after starting game.

System Monitor show dota2 process with 4.6mb memory usage, nearly zero cpu usage.
No dota 2 icon in dock.

Options tried so far:
Switch on/off steam overlay.
Add/Remove launch option -fullscreen.

**Comment by gdrewb-valve** [comment]
Has Dota ever worked for you?  If so when did this start?

**Comment by lolgear** [comment]
@gdrewb-valve 
well, it starts when I've downloaded update.

Last step I've done: restart steam.
Now everything fine. ( run with -fullscreen option works, alternative not tested. )

**Comment by gdrewb-valve** [comment]
OK, closing for now.
