### ISSUE TITLE
Linux client unplayable. Serious framerate/ping(?) issues

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#928]
I was ill for about a week about a week ago, so I'm not entirely sure when these issues cropped up, but it's been since 11 days ago (according DotABuff when I played my last match). I'm listing multiple issues here since it seems to me that they may all be related.

1st issue: Framerate on the main screen is horrible. I can't see what the actual framerate is, but I'm sure it's sub20.
2nd issue: Framerate issue (again) on the hero selection screen.
3rd issue: Along with these framerate issues trying to select something (like a hero for a match, changing settings in the Settings menu, accepting party invites, ect.) is HORRIBLY laggy. It seems like the client is registering a mouse over of an icon several seconds AFTER the mouse passes it, making it rather difficult to do anything.

Two additional ( and apparently related issues):

4th issue: Opening the chat text entry field in a game causes HORRIBLE FPS problems, whereas the FPS in game seems to be fine (unlike any other time). It seems like there is a huge lag spike upon opening the chat box along with a massive FPS drop for a second before the entire game turns into a slideshow at roughly 10FPS (normally I get 60-70).
5th issue: If the chat text entry field is opened, any text entered into it takes several seconds to appear after having been typed. This is kind of like the mouse over issue on the other screens, but I'm not sure if the time between typing and character appearing is near the time of moving a mouse over something and the client visually acknowledging the mouseover with a highlight.
6th issue: If I type something into the chat box and the message is too long (say more than ~20 characters, but I didn't test that extensively) then I get timed out and disconnected from the match.

Some other issues that may or may not be related:

7th issue: Sometimes when I try to close DotA, it won't close and I have to kill the process using SIGKILL. SIGTERM doesn't seem to affect it whatsoever in those cases.
8th issue: When DotA2 closes, it sometimes crashes Steam.

I've done pretty much everything I can think of to make sure the problem isn't on my end including upgrading and downgrading my nVidia driver (the proprietary driver. Currently running 367.18), rebooting my router, and changing settings in said driver. I also reinstalled both Steam and DotA2.

If some other information would be useful, let me know.

SYSTEM INFO:

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x12
    CPU Model:  0x1
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.13
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11704000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 620/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 367.18
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xf01
Revision Not Detected
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7965 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  151061 Mb
    Largest Free Hard Disk Block:  52984 Mb
    VR Headset: None detected

```
Mon Jun 27 02:56:43 2016 GMT: file ''/tmp/dumps/crash_20160626170807_1.dmp'', upload yes: ''CrashID=bp-fe218f89-b8f2-4fa0-ac9a-0c0882160626''
Mon Jun 27 02:56:44 2016 GMT: file ''/tmp/dumps/crash_20160626195643_6.dmp'', upload yes: ''Discarded=1''
Mon Jun 27 02:56:45 2016 GMT: file ''/tmp/dumps/assert_20160626195644_8.dmp'', upload yes: ''Discarded=1''
Tue Jun 28 19:02:11 2016 GMT: file ''/tmp/dumps/crash_20160626195648_1.dmp'', upload yes: ''CrashID=bp-d3b768bb-3cd8-4cae-a39a-eb4112160628''
Tue Jun 28 19:02:11 2016 GMT: file ''/tmp/dumps/crash_20160628120211_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 00:55:12 2016 GMT: file ''/tmp/dumps/crash_20160628175511_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 00:55:12 2016 GMT: file ''/tmp/dumps/crash_20160628120213_1.dmp'', upload yes: ''CrashID=bp-f6caae6f-97db-41e9-86c9-67f572160628''
Wed Jun 29 00:55:12 2016 GMT: file ''/tmp/dumps/assert_20160628175512_8.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 01:21:51 2016 GMT: file ''/tmp/dumps/crash_20160628181656_1.dmp'', upload yes: ''CrashID=bp-dcb1dce7-7da9-4a95-b20f-4a94d2160628''
Wed Jun 29 01:21:51 2016 GMT: file ''/tmp/dumps/crash_20160628182151_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:03:40 2016 GMT: file ''/tmp/dumps/crash_20160628182155_1.dmp'', upload yes: ''CrashID=bp-d73b002e-3070-4ef3-9d1a-21fbc2160628''
Wed Jun 29 02:03:41 2016 GMT: file ''/tmp/dumps/crash_20160628190340_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:12:00 2016 GMT: file ''/tmp/dumps/crash_20160628190357_1.dmp'', upload yes: ''CrashID=bp-d1e37637-4fc2-4547-9d47-b503e2160628''
Wed Jun 29 02:12:00 2016 GMT: file ''/tmp/dumps/assert_20160628191200_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:19:06 2016 GMT: file ''/tmp/dumps/crash_20160628191201_1.dmp'', upload yes: ''CrashID=bp-8bee9d8e-cbf8-49e4-9e0b-7194b2160628''
Wed Jun 29 02:19:06 2016 GMT: file ''/tmp/dumps/crash_20160628191905_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:19:07 2016 GMT: file ''/tmp/dumps/assert_20160628191907_8.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:40:13 2016 GMT: file ''/tmp/dumps/crash_20160628192309_1.dmp'', upload yes: ''CrashID=bp-b72a7203-0393-4dc9-919b-ddd022160628''
Wed Jun 29 02:40:13 2016 GMT: file ''/tmp/dumps/crash_20160628194013_6.dmp'', upload yes: ''Discarded=1''
Wed Jun 29 02:40:14 2016 GMT: file ''/tmp/dumps/assert_20160628194013_8.dmp'', upload yes: ''Discarded=1''
```

**Comment by ghost** [comment]
I was looking through the other bugs in the list and this one:

https://github.com/ValveSoftware/Dota-2/issues/921
has a workaround (export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --print-address --fork)") that /seems/ to work so far.

So far it seems like the main menu, character selection, and settings are no longer laggy. In addition, the chat box no longer causes massive FPS drops.

This seems like a problem with how DBus is being supported in DotA2 since it is having massive, massive effects if something goes wrong with DBus (or someone doesn't want to use dbus, such as I).

**Comment by gdrewb-valve** [comment]
As you've found the dbus issue causes major perf issues.  The SDL dev has been assigned that issue.

There's an open issue on the client not shutting down which also is assigned to the SDL dev.  The Steam client issue should be opened in steam-for-linux.  If you have other dota issues please open one entry per issue here.
