### ISSUE TITLE
Everyone in my last game lagged

### ISSUE THREAD

**Issue by chrissisura** [ValveSoftware/Dota-2#929]
http://www.dotabuff.com/matches/2471885985
This is the dotabuff of the game. Everyone had lagspikes thought the entire game it was almost unplayable but it still counted. Hope this wont happen again.

**Comment by gdrewb-valve** [comment]
The larger team is looking at perf issues so we won't have much status here.

**Comment by Arfik63** [comment]
Hello..I'm here for teleport effect 1 ti6 #878..but the discussion was closed already..same prob like the previous person..I already hit lvl 13 and supposed to have everything including the Tp effect 1..but I do receive all of them except the Tp effect....can you help me?

**Comment by gdrewb-valve** [comment]
This forum is for bugs specific to Mac and Linux.  You'll want to post at dev.dota2.com

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Mac/Linux specific issue.
