### ISSUE TITLE
[Mac] Anti-mage basher glitch

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#93]
![screenshot 2015-06-24 22 27 05](https://cloud.githubusercontent.com/assets/5674597/8347850/69fc07e4-1ac0-11e5-9d09-25d5e405d0fc.png)
There is an additional golden line.
Same for ordinary ones:
![screenshot 2015-06-24 22 35 13](https://cloud.githubusercontent.com/assets/5674597/8347917/56ee51ce-1ac1-11e5-8d4a-8b731e2dee90.png)

The basher bundle's icon is also incorrect. I don't own a golden basher bundle so I don't know if that one is correct.
![screenshot 2015-06-24 22 24 18](https://cloud.githubusercontent.com/assets/5674597/8347904/2dccb15a-1ac1-11e5-84bb-2151fb0502a7.png)
Also I don't if this is intended, the gems icons all look ugly. Seems that they shrinked in height.

**Comment by gdrewb-valve** [comment]
This is a general problem and not a Linux/Mac bug but I've passed it on.

**Comment by gdrewb-valve** [comment]
The larger team is tracking this in their internal bug list and there won't be updates here so closing.
