### ISSUE TITLE
Dota 2 very low fps after update.

### ISSUE THREAD

**Issue by ilyaboka** [ValveSoftware/Dota-2#930]
After yesterday update of dota, i can't play or even use menu, becouse of this. Another games work fine.
I'm exit from dota by "pkill -9 dota2"
I'm use arch linux. 
I'm launch steam with this command: `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' steam`
Radeon driver: xf86-video-ati
[lspci.txt](https://github.com/ValveSoftware/Dota-2/files/344612/lspci.txt)
[crash_20160702174604_6.dmp.zip](https://github.com/ValveSoftware/Dota-2/files/344611/crash_20160702174604_6.dmp.zip)
[log.txt](https://github.com/ValveSoftware/Dota-2/files/344607/log.txt)

**Comment by ilyaboka** [comment]
Cursor moves fine. But all related with cursor processes have long delay

**Comment by gdrewb-valve** [comment]
Check out #921, does the workaround there help you?

**Comment by ilyaboka** [comment]
It works!
Ty so much for fast answer :)

**Comment by gdrewb-valve** [comment]
Great, closing this out since it's a duplicate.
