### ISSUE TITLE
[Linux] Input bug renders game unplayable

### ISSUE THREAD

**Issue by t3rnary** [ValveSoftware/Dota-2#932]
In the past week when playing Dota I've encountered this bug. I'll start a match, and usually near the beginning of the match before runes spawn my keyboard stops working. I can still move my mouse cursor and the game client still accepts clicks, but absolutely no input is taken from the keyboard. When I first encountered this bug, I thought to try to fix it by restarting the client. However, upon clicking the arrow in the top left corner of the screen, clicks are no longer registered. In the disconnect menu my keyboard input and clicks are ignored, while I can still move the cursor. Alt + tabbing out doesn't work, I can't ctrl + alt + t to open a terminal, and even going to the virtual console by using ctrl + alt + f1 doesn't give me a command line like it normally does. I've had to "solve" this issue by doing a hard restart, which usually results in me coming back to a game that has already been unpaused for a few minutes so we are likely to lose, or I don't come back in time and I receive an abandon. On one occasion I reconnected only to have the same input issue start again less than a minute after reconnecting. This issue doesn't happen every game, so I'm not sure how to reproduce it. I have not observed this behavior in any other applications apart from Dota.

System info:
-Distribution: Ubuntu 16.04 LTS
-Desktop Manager: Unity 7.4.0
-Graphics: Intel HD Graphics 4000 (Driver i915)

**Comment by t3rnary** [comment]
After trying to replicate the issue I found that it seems to happen after pressing alt. However, it does not seem to be the same issue as the alt key being "stuck" because the map icons do not change and clicking doesn't ping. Dota just stops taking keyboard input. The strange part is that it doesn't always happen. I can get through an entire game with the alt key working correctly, then the first time I press it in the next match the keyboard stops working.

**Comment by gdrewb-valve** [comment]
Does Ctrl + Alt + F1 still not work?  That sounds more like a system issue since Dota has nothing to do with the switching to a virtual console.

**Comment by gdrewb-valve** [comment]
You might also want to look at #921 in case this is some sort of odd dbus interaction.

**Comment by t3rnary** [comment]
> Does Ctrl + Alt + F1 still not work? That sounds more like a system issue since Dota has nothing to do with the switching to a virtual console.

Apparently I just can't switch to a virtual console right now for some reason, regardless of whether or not Dota is running, so it seems that part is irrelevant now. 

The input issue is still a problem and I have no way to deal with it other than a hard restart. I'm not sure if this is some sort of dbus interaction or something else entirely. Is there any way I can get more info for you? I thought about running Dota from the console and seeing if anything of value shows up there, but I'm not sure how I'd get to that information when it's impossible to leave Dota without hard restarting when this bug occurs.

**Comment by gdrewb-valve** [comment]
I don't know that there's any spew from Dota that would help identify why input is blocked in the system outside of Dota.  However you can add -con_logfile to your launch options and Dota's spew will go to console.log in the <Steam Dota install>/game/dota directory and we can take a lok.

**Comment by t3rnary** [comment]
I'm not exactly sure what to look for in here so I'll just include the contents of the whole file (apologies for the length):
http://pastebin.com/HErzu3xK

Some context: I kept creating bot games and running them for a little while. If the bug didn't occur after the first ten minutes or so I closed the client and then created a new bot game after restarting the client. I finally ran into the bug in the last game listed in the log file (the tusk game). Hopefully something in there is useful.

**Comment by gdrewb-valve** [comment]
I didn't see anything unusual in the logs.  We'll have to see if other people hit the same thing to help us narrow it down.

**Comment by t3rnary** [comment]
Could the issue I'm having be related to https://github.com/ValveSoftware/Dota-2/issues/885?

This might just be a driver issue.

**Comment by gdrewb-valve** [comment]
There was never a final culprit found for #885 so it's hard to say (once it was clear it wasn't dota-specific I'm not sure the original poster would come back here).

**Comment by gdrewb-valve** [comment]
Is this issue still active?

**Comment by t3rnary** [comment]
I'm no longer playing Dota on Linux, so I can't say for sure. However, switching from Unity to Gnome was a workaround I discovered and used for several months with no problems. The issue was almost definitely caused by some bug in the version of Unity I was using at the time, rather than Dota. Might as well close this issue.

My apologies for not updating earlier.
