### ISSUE TITLE
[Linux] Crazy FPS drop from time to Time

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#934]
Since i disabled steam overlay. and only when disabled. Game seems to randomly drop from 120 to 40-60fps from nowhere.  And Video is very very laggy. Dunno whatelse to provide. 

Ubuntu 16.04. Gnome 3.20. Nvidia 367.27

https://gist.github.com/admshao/7309d67cc1ae447160b403c63a88d4f1

**Comment by gdrewb-valve** [comment]
It's hard to say what might be happening.  We'll have to see if other people have similar problems and there's a pattern between them.

**Comment by admshao** [comment]
Another behavior i've found. I watched 48 matches with no problem. Whenever
i play a game it randomly happens. Might be of some help

**Comment by konstantinblaesi** [comment]
If you're running Linux 4.6 (4.7 might have fixed this, idk) try disabling intel pstate by appending "intel_pstate=disabled" to your boot parameters. There seems to be a pstate regression, see

http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil
https://www.phoronix.com/scan.php?page=news_item&px=P-State-Possible-4.6-Regression

**Comment by admshao** [comment]
Thanks for the tip. I've been using 4.7 since release and no issues so far.
Can't say its fine to close this yet tho

On Jul 28, 2016 4:35 PM, "elxa" notifications@github.com wrote:

If you're running Linux 4.6 (or 4.7 maybe) try disabling intel pstate by
appending "intel_pstate=disabled" to your boot parameters. There seems to
be a pstate regression, see

http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil
https://www.phoronix.com/scan.php?page=news_item&px=P-State-Possible-4.6-Regression

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/ValveSoftware/Dota-2/issues/934#issuecomment-236001337,
or mute the thread

**Comment by gdrewb-valve** [comment]
Have you had any further problems?

**Comment by admshao** [comment]
A lot of Kernel, dota and gpu driver later, i never had this issue again. I
can say it`s fixed for me but no clue how.

2016-10-18 20:02 GMT-02:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
I close it.  As many things have changed since you last saw the problem it's probably worth a new issue if you have future slowdowns.
