### ISSUE TITLE
[OSX] Dota lags in game

### ISSUE THREAD

**Issue by techmaniack** [ValveSoftware/Dota-2#936]
The game lags every few seconds and this happens in most of the games. There have been games which run flawless but some games are just bad. Best I can describe the issue is that there are frame drops every 5 seconds or so which makes it very difficult in mid/late game. You are dead before you even know.

I have set the graphics to minimum possible.

Broadband is 50Mbps and works flawless.

Laptop: 

 Model Name:    MacBook Pro
  Model Identifier: MacBookPro12,1
  Processor Name:   Intel Core i5
  Processor Speed:  2.7 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache (per Core):  256 KB
  L3 Cache: 3 MB
  Memory:   8 GB
  Boot ROM Version: MBP121.0167.B16

Graphics:

  Chipset Model:    Intel Iris Graphics 6100
  Type: GPU
  Bus:  Built-In
  VRAM (Dynamic, Max):  1536 MB
  Vendor:   Intel (0x8086)
  Device ID:    0x162b
  Revision ID:  0x0009
  Displays:
Color LCD:
  Display Type: Retina LCD
  Resolution:   2560 x 1600 Retina
  Retina:   Yes
  Pixel Depth:  32-Bit Color (ARGB8888)
  Main Display: Yes
  Mirror:   Off
  Online:   Yes
  Built-In: Yes

**Comment by gdrewb-valve** [comment]
No repro for me on my Mac.  We'll have to see if enough people hit it that we can find a pattern.

**Comment by techmaniack** [comment]
Any logs where I should look into?

**Comment by gdrewb-valve** [comment]
Add -con_logfile to your launch options and a log will be saved at <Steam Dota install>/game/dota/console.log

**Comment by gdrewb-valve** [comment]
Can you give us some info on why you closed this?  Is it no longer happening?
