### ISSUE TITLE
Dota on debian 

### ISSUE THREAD

**Issue by lucas-estivam** [ValveSoftware/Dota-2#937]
Hey! I'm a totally newbie on Dota on Linux and at the first time that I'll play, that happens (http://i.imgur.com/uPHjhSf.png) I'm searching on google but none answers. Can someone help me?

*_I already deleted the files and downloaded again
*_I check the files throught the steam and everything is working

**Comment by gdrewb-valve** [comment]
You have a bad OpenGL driver.  I don't know what you're running but it's most likely some kind of Mesa and you'll need to get a newer version or install the direct driver from NVIDIA.

**Comment by lucas-estivam** [comment]
I tried this : 
sudo apt-get purge nvidia*
sudo apt-get install --reinstall xserver-xorg-video-intel  libgl1-mesa-glx libgl1-mesa-dri xserver-xorg-core
sudo dpkg-reconfigure xserver-xorg
sudo update-alternatives --remove gl_conf /usr/lib/nvidia-current/ld.so.conf
And nothing happened

**Comment by gdrewb-valve** [comment]
You'll want to check with your distro maintainers or the Mesa devs or NVIDIA to get more direct information.  As this is a Dota-related forum and your problem is not about Dota you won't necessarily get people here who know how to update your system.

**Comment by lucas-estivam** [comment]
I know, thank you anyway, i thought maybe someone had the same error before

**Comment by Doldge** [comment]
You need to restart the PC after changing the GFX drivers as well, in case that wasn't clear.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Dota issue.
