### ISSUE TITLE
Stuck in the loading screen

### ISSUE THREAD

**Issue by maxsize** [ValveSoftware/Dota-2#938]
I have been stucked in the loading screen for 3 times in a row, and the game consider me as abandoning!! Now I am banned for 24 hours! 
What is happening for me is I found match and start the game while 10 players are all ready, it goes to the loading screen and just stucked there, after couple of minutes it came back to main UI.
PLEASE FIX!!!!

**Comment by gdrewb-valve** [comment]
We'll need some information to actually be able to look at this, such as your full Steam system information and any console log you have (if you have it).

**Comment by maxsize** [comment]
I am using Mac OS 10.11.5 (15F34) and latest Steam and Dota2 client, I don't have the console log, if you can tell me how to get it I can try to find it.
The game didn't crash though, it just stuck in the loading screen and back to main UI, I can also watch games without any problem.

**Comment by gdrewb-valve** [comment]
Add -con_logfile to your launch options and Dota's console output will go to <Steam Dota install>/game/dota/console.log

You can gist that here, but of course you'll be risking more abandons to get it so you don't have to collect it.  There are reports of similar problems on all platforms and the larger team is taking a look. There won't be updates here from their investigation but if something comes out of it there'll be a post here.

**Comment by maxsize** [comment]
I just tried windows version after in jail for 24 hours and the same thing happens again to me, now I am in jail for another 24 hours. This is too bad...
I'll try to get log next time.

**Comment by gdrewb-valve** [comment]
Posting a log would be fine but just to be clear, as this isn't a Mac/Linux-specific bug it's not being actively investigated by the porting team (which reads this forum), it's the overall Dota team that's looking.

**Comment by sardetushar** [comment]
This is a bad bug, many players are facing this problem and banning the players for 24 hrs isn't the solution!
There must be some alternative until you resolve this bug

**Comment by gdrewb-valve** [comment]
Is this still happening with 7.00?

**Comment by sardetushar** [comment]
Hi, It's resolved now. It was problem with my network but problem i have noticed that even if i launch steam using -tcp launcher, i was still getting loading screen stuck issue. but for me its solved now.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
