### ISSUE TITLE
Dota 2 stuck on loading screen only for dx11

### ISSUE THREAD

**Issue by realmofchaos** [ValveSoftware/Dota-2#939]
It works fine with -dx9 launch options as well as -vulkan. But, it is stuck on loading screen with -dx11 launch option if i either spectate a game or join a game using find match.(I can play local bot games on -dx11.) 
Steam system info and console log file are below - 

**Steam System Info :**

Computer Information:
    Manufacturer:  Dell Inc.
    Model:  Inspiron 5437
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1596 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 8.1 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GT 740M

```
DirectX Driver Name:  nvumdshim.dll
Driver Version:  10.18.13.6510
DirectX Driver Version:  10.18.13.6510
Driver Date: 27 Apr 2016
OpenGL Version: 4.5
DirectX Card: NVIDIA GeForce GT 740M
VendorID:  0x10de
DeviceID:  0x1292
Revision:  0xa1
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12.17" x 6.81"  (13.94" diag)
                                        30.9cm x 17.3cm  (35.4cm diag)
Primary Bus: PCI Express 4x
Primary VRAM: 2047 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Speakers (Realtek High Definiti

Memory:
    RAM:  8096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  943422 Mb
    Largest Free Hard Disk Block:  403816 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected
    VR Headset: None detected

**Console Log file :** 

D3D9Ex activated.
## Loaded video settings config from 'cfg\video.txt'

Path ID:             File Path:
ADDONS               "D:\Steam\steamapps\common\dota 2 beta\game\dota_addons\" 
CONTENT              "D:\Steam\steamapps\common\dota 2 beta\content\dota\" 
CONTENT              "D:\Steam\steamapps\common\dota 2 beta\content\core\" 
CONTENTADDONS        "D:\Steam\steamapps\common\dota 2 beta\content\dota_addons\" 
CONTENTROOT          "D:\Steam\steamapps\common\dota 2 beta\content\" 
DEFAULT_WRITE_PATH   "D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
DEFAULT_WRITE_PATH   "D:\Steam\steamapps\common\dota 2 beta\game\dota\" 
EXECUTABLE_PATH      "D:\Steam\steamapps\common\dota 2 beta\game\bin\win64\" 
EXECUTABLE_PATH      "d:\steam\steamapps\common\dota 2 beta\game\bin\" 
GAME                 "D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
GAME                 "D:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk" (vpk) D:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk
GAME                 "D:\Steam\steamapps\common\dota 2 beta\game\dota\" 
GAME                 "D:\Steam\steamapps\common\dota 2 beta\game\core\" 
GAMEBIN              "D:\Steam\steamapps\common\dota 2 beta\game\dota\bin\win64\" 
GAMEBIN              "D:\Steam\steamapps\common\dota 2 beta\game\dota\bin\" 
GAMEBIN              "D:\Steam\steamapps\common\dota 2 beta\game\core\bin\win64\" 
GAMEBIN              "D:\Steam\steamapps\common\dota 2 beta\game\core\bin\" 
GAMEROOT             "D:\Steam\steamapps\common\dota 2 beta\game\" 
MOD                  "D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk" (vpk) D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk
MOD                  "D:\Steam\steamapps\common\dota 2 beta\game\dota\" 
PLATFORM             "D:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk" (vpk) D:\Steam\steamapps\common\dota 2 beta\game\core\pak01.vpk
PLATFORM             "D:\Steam\steamapps\common\dota 2 beta\game\core\" 
SHADER_SOURCE        "D:\Steam\steamapps\common\dota 2 beta\src\shaders\dota\" 
SHADER_SOURCE        "D:\Steam\steamapps\common\dota 2 beta\src\shaders\core\" 
SHADER_SOURCE        "D:\Steam\steamapps\common\dota 2 beta\src\shaders\dota_addons\" 
SHADER_SOURCE        "D:\Steam\steamapps\common\dota 2 beta\src\shaders\dota_core\" 
SHADER_SOURCE_MOD    "D:\Steam\steamapps\common\dota 2 beta\src\shaders\dota\" 
SHADER_SOURCE_ROOT   "D:\Steam\steamapps\common\dota 2 beta\src\shaders\" 
command line arguments:
-steam +r_overlap_scaleform 1 -dx11 -console -con_logfile
Network System Initialized
172.171.150.44: {224EB8B4-0E5E-4BC4-BA42-B544AF262EC7} Realtek PCIe FE Family Controller
No valid vcs file found for shader gaussian_bloom_blur.vfx

CMaterial2::LoadShadersAndSetupModes(863): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(863): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(863): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!

CMaterial2::LoadShadersAndSetupModes(863): Error creating shader gaussian_bloom_blur.vfx for material materials/dev/gaussian_bloom_blur.vmat!
Physics Console Communications is not initialized
Game supporting (2) split screen players
Sound Initialization: Finish, Sampling Rate: 44100
ConVarRef r_dota_force_forward doesn't point to an existing ConVar
CEntitySystem::BuildEntityNetworking (parallel build of server) took 467.869 msecs for 680 out of 699 classes
SV:  parsing 'scripts/items/items_game.txt' took 1045.450 msec
Requesting page 1 of items
Requesting page 1 of items
ReadSteamRemoteStorageFile( bufOut, "cfg/pending_replay_requests.lst" ) -> 0.000362 seconds
ReadSteamRemoteStorageFile( bufOut, "scripts/clientstorage.txt" ) -> 0.000370 seconds
ReadSteamRemoteStorageFile( bufOut, "cfg/dotakeys_personal.lst" ) -> 0.000736 seconds
CEntitySystem::BuildEntityNetworking (parallel build of client) took 427.771 msecs for 685 out of 706 classes
CL:  parsing 'scripts/items/items_game.txt' took 1076.096 msec
ReadSteamRemoteStorageFile( bufOut, "cfg/dota_player_loadout_shuffle.txt" ) -> 0.000466 seconds
Telling Steam it is safe to update the app
name[ 0 ] changing from 'unnamed' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
name[ 0 ] changing from 'Cha0ticGood' to 'Cha0ticGood'
SwitchToLoop levelload requested:  id [1] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_LOADING_SCREEN
File error loading resource header "panorama/layout/hud/dota_hud_projection_debug.vxml_c" (Error: ERROR_FILEOPEN)
ReadSteamRemoteStorageFile( bufOut, "scripts/lobby_settings.txt" ) -> 0.000371 seconds
ReadSteamRemoteStorageFile( bufOut, "scripts/dota_acknowledged_violators.txt" ) -> 0.000352 seconds
Idle (levelload)
ReadSteamRemoteStorageFile( bufOut, "cfg/chat.cfg" ) -> 0.000364 seconds
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 162 (1924 input number was)
Writing configuration for slot 0
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [1] addons []
Loaded default network config file.  Loaded revision 43 OK
Loaded cached network config file.  Data contains revision 43, not newer than current revision 43; ignoring.
SV:  maxplayers set to 1
Initializing script VM...
...done
Network configuration revision changed 0 -> 43
Got network config from CDN.  Data contains revision 43, not newer than current revision 43; ignoring.
File error loading resource header "panorama/images/iso_countryflags/_png.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "models/controllers/vr_controller.vmdl_c" (Error: ERROR_FILEOPEN)
SV:  Spawn Server: <empty>
Received weekend tourney schedule.
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  Sending connect to loopback
Failed to load inventory scratchpad information file "cfg/dota_player_scratchpad.txt"!
SV:  Sending S2C_CHALLENGE [2895510140 auth 2] to loopback
CL:  Received S2C_CHALLENGE [2895510140 auth 2] from loopback
CL:  Sending C2S_CONNECT [44 protocol 2895510140 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 44 2895510140 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
CL:  Connected to 'loopback'
SV:  Sending server info to client 'Cha0ticGood' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 7181 (revision 3528072)
Server Number: 1
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000627 seconds
Client missing networkable entity class CPointCommentaryNode
Client missing networkable entity class CVGuiScreen
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000439 seconds
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
SV:  Sending full update to client Cha0ticGood (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 34.013 KB [6 pkts], outgoing 1.201 KB [5 pkts]
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 346 (351 input number was)
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 969 (971 input number was)
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 1128 (1130 input number was)
Encountered entity that cannot be used in portrait maps - info_player_start_goodguys
Encountered entity that cannot be used in portrait maps - info_player_start_badguys
Encountered entity that cannot be used in portrait maps - ent_dota_game_events
File error loading resource header "materials/particle/ground/crack_growth_01_noadd.vmat_c" (Error: ERROR_FILEOPEN)
light has _fifty_percent_distance of 60.000000 but no zero_percent_distance
light has _fifty_percent_distance of 60.000000 but no zero_percent_distance
Auto selecting weekend tourney division 'se_asia' based on ping to best region of 86ms
Selected division changed to 'se_asia'
Ping measurement complete.
File error loading resource header "panorama/images/iso_countryflags/_png.vtex_c" (Error: ERROR_FILEOPEN)
StartWatchingGame request SteamID: [A:1:1418380294:7093], watching SteamID: [I:0:0]
Received CMsgWatchGameResponse result 7.
File error loading resource header "panorama/images/iso_countryflags/_png.vtex_c" (Error: ERROR_FILEOPEN)
StartWatchingGame request SteamID: [A:1:2224164866:7093], watching SteamID: [I:0:0]
Received CMsgWatchGameResponse result 0.
Received CMsgWatchGameResponse result 1.
StartWatchingGame: Sending console command: connect_hltv 185.25.183.22:28094
SwitchToLoop remoteconnect requested:  id [2] addons []
CL:  IGameSystem::LoopDeactivateAllSystems
WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 24.566
CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/hero_showcase_arcana_zeus) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/battlepass_ti6/twoflags) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/battlepass_ti6_header) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/battlepass_ti6/twoflags) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/home_button) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/play_searching) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(scenes/find_match_status) no such group
CL:  CPhysicsGameSystem::UnloadSpawnGroupPhysics(backgrounds/dashboard_parallax_ti6_initial) no such group
SV:  IGameSystem::LoopDeactivateAllSystems
HO:  IGameSystem::LoopDeactivateAllSystems
SV:  Disconnect client 'Cha0ticGood' from server(1): NETWORK_DISCONNECT_SHUTDOWN
WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 24.721
Network socket 'client' opened on port -1
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( remoteconnect : success )
CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 24.757
CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 24.757
CL:  Sending connect to 185.25.183.22:28094
CL:  Received S2C_CHALLENGE [3180210501 auth 3] from 185.25.183.22:28094
CL:  Sending C2S_CONNECT [44 protocol 3180210501 auth 3] to 185.25.183.22:28094
CL:  Received S2C_CONNECTION from 185.25.183.22:28094 [addons:'']
CL:  Connected to '185.25.183.22:28094'
CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
SwitchToLoop levelload requested:  id [2] addons []
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( levelload : success )
CL:  Permit INetchannel::Transmit()
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [2] addons []
CL:  CNetworkGameClient already exists for connection to '185.25.183.22:28094'
CL:  connection to '185.25.183.22:28094' already started
Game: "Dota 2"
Map: "dota"
Players: 11 (0 bots) / 64 humans
Build: 7182 (revision 3528072)
Server Number: 3
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
CL:  CGameRulesGameSystem::GameInit installed game rules
InstallChangeCallback ignoring duplicate change callback!!!
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000441 seconds
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 16
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 24
File error loading resource header "models/controllers/vr_controller.vmdl_c" (Error: ERROR_FILEOPEN)
UnserializeDMX: Unable to open file "0"
UnserializeDMX: Unable to open file "0"
ERROR: CParticleSnapshot::Unserialize - could not load file 0!
File error loading resource header "materials/effects/fog_world_00.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/effects/fow_clouds_00.vtex_c" (Error: ERROR_FILEOPEN)
Unknown net message 41!
Client missing networkable entity class CPointCommentaryNode
Client missing networkable entity class CVGuiScreen
File error loading resource header "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)
CNWaySequence::InitSequenceArray: "hoard_run" failed, "sequences" row 1, col 1, sequence "@hoard_run" not found on model: models/heroes/bounty_hunter/bounty_hunter.vmdl
stack traceback:
    [C]: in function 'CreateSequence'
    ...scripts\animation\heroes\bounty_hunter\bounty_hunter.lua:162: in main chunk
CNWaySequence::InitSequenceArray: "hoard_run_haste" failed, "sequences" row 1, col 1, sequence "@hoard_run_haste" not found on model: models/heroes/bounty_hunter/bounty_hunter.vmdl
stack traceback:
    [C]: in function 'CreateSequence'
    ...scripts\animation\heroes\bounty_hunter\bounty_hunter.lua:180: in main chunk
CNWaySequence::InitSequenceArray: "hoard_run_injured" failed, "sequences" row 1, col 1, sequence "@hoard_run_injured" not found on model: models/heroes/bounty_hunter/bounty_hunter.vmdl
stack traceback:
    [C]: in function 'CreateSequence'
    ...scripts\animation\heroes\bounty_hunter\bounty_hunter.lua:199: in main chunk
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 4
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 5
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 6
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 7
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 8
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 9
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 10
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 11
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 12
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 13
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 14
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 15
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 17
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 18
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 19
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 20
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 21
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 22
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 23
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 25
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 26
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 27
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 28
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 29
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 30
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 31
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 32
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 33
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 34
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 35
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 36
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 37
CL:  CLoadSpawnGroupsPrerequisite::UnloadInitialSpawnGroup unloaded spawn group 41
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
CL:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000643 seconds
Remote Connect (185.25.183.22:28094)
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME

**Comment by gdrewb-valve** [comment]
This forum is for bugs specific to Mac and Linux, you'll want to post at dev.dota2.com
