### ISSUE TITLE
[Mac] Browsing all custom games' selector & content inconsistency

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#94]
When I first entered the "browsing all custom games" page, the game client showed me
![screenshot 2015-06-24 22 25 12](https://cloud.githubusercontent.com/assets/5674597/8347866/b1dfeb02-1ac0-11e5-92c4-85ea9f2c8193.png)
Although the selector shows "Most popular (today)", the table content is actually "Most popular (this week)". Proved by:
![screenshot 2015-06-24 22 25 18](https://cloud.githubusercontent.com/assets/5674597/8347877/d3be36ac-1ac0-11e5-89db-e9b15efbbb4c.png)
![screenshot 2015-06-24 22 25 25](https://cloud.githubusercontent.com/assets/5674597/8347879/d615dff4-1ac0-11e5-8f0d-58149dd7c534.png)

The inconsistency also appears when I click on any particular game to view its details and then click the top left back button to return to the browsing page. The selector will have the value that I set it before, and the table will show "Most popular (this week)".

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue and won't get updates here but the larger team says that the next update will have a fix.
