### ISSUE TITLE
[Linux] Battle Pass/Quest

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#940]
hi,
It seems like every time I complete a hero specific quest the data for the quest completion of the chapter gets randomized.

![dota2_quest](https://cloud.githubusercontent.com/assets/5174562/16688568/e67d233c-451e-11e6-90dc-1a0ff75453cb.png)
Here it claims that I completed every quest as sniper, even the hero specific ones and the stars look a bit strange. Also the hero icon for the last quest, the one I just finished is completely missing.
The only known fix for me is to restart dota.

**Comment by gdrewb-valve** [comment]
This isn't Linux-specific, I've pass it on to the larger team.
