### ISSUE TITLE
[OSX] Main Menu > Heroes > My Stats graph is shifted.

### ISSUE THREAD

**Issue by lsnch** [ValveSoftware/Dota-2#944]
It seems that W(green)/L(red) buttons have a bit more space between them than points on the graph. This bug is present on every hero page.

OS X 10.11.5 1440x900.

![1](https://cloud.githubusercontent.com/assets/20382674/16829068/600efe4a-499e-11e6-8bfb-8c338441a08b.png)
![2](https://cloud.githubusercontent.com/assets/20382674/16829069/601038c8-499e-11e6-9874-d8e107ac3eed.png)

**Comment by gdrewb-valve** [comment]
Probably not related to Mac/Linux, I'll check with the larger team.

**Comment by gdrewb-valve** [comment]
Confirmed that this does happen on Windows.  The larger team is aware but this won't be tracked here.
