### ISSUE TITLE
[UI] corruption in bot match.

### ISSUE THREAD

**Issue by sabreshao** [ValveSoftware/Dota-2#945]
1. Set Launch option in Steam client as “-vulkan" and play Dota.
2. Start bot match -> Select the hero "ABADDON" -> Disconnect from bot match.
3. Start bot match again -> Select the hero "ALCHEMIST"

During animation of the hero "ALCHEMIST" coming out, "ABADDON" is rendered in a frame.
Application use an hero image which is rendered as previous hero in current hero animation.
I reproduced on Ubuntu16.04 with AMD gpu and Windows7 with NVIDIA gpu.
If this is first time to select hero, on AMD gpu it shows a corruption since the hero image is uninitialized.

**Comment by sabreshao** [comment]
![1](https://cloud.githubusercontent.com/assets/20459194/16842444/1618aae4-4a10-11e6-82c5-024e119a84d6.jpg)
![2](https://cloud.githubusercontent.com/assets/20459194/16842445/163ac84a-4a10-11e6-9b71-b5e2e0b80233.jpg)

**Comment by danginsburg** [comment]
This belongs in https://github.com/ValveSoftware/Dota-2-Vulkan/issues but I do have it repro'd and will take a look.  Thanks for the report.

**Comment by danginsburg** [comment]
It turns out this bug happens on Windows on Vulkan, GL, and DX.  I have passed this along to the larger team, but won't track it here.  Thanks.
