### ISSUE TITLE
Change fps_max default from 120 to 300

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#946]
Since the Source 2 update fps_max is now default at 120.

I think it should be back to the familiar 300 and those who wish to cap should either change it manually or use vertical synchronisation.

144 hz, 165 hz, 185 hz and 200 hz monitors are available, with 240 hz monitors coming later this year. I fail to understand why the default value is set at such a low setting.

If none of this is within interest, please provide a user friendly GUI setting to change this option.

**Comment by gdrewb-valve** [comment]
This forum is for Mac/Linux-specific bugs, you'll want to post this at dev.dota2.com

**Comment by fredddii** [comment]
I no longer known my account credentials on that website. When I try to register a new account I get the message:

"This steamID has already been associated with a forum account."

Would it be possible for you to assist me in fixing that?

**Comment by ghost** [comment]
I no longer known my account credentials on that website. When I try to register a new account I get the message:

"This steamID has already been associated with a forum account."

Would it be possible for you to assist me in fixing that?

**Comment by gdrewb-valve** [comment]
I believe if you go to this link http://dev.dota2.com/login.php?do=lostpw you can enter your email to have your username sent to you along with how to reset your password.

The current frame rate limit is to avoid frame rate variability as it will naturally vary depending on how many heroes you have on screen, what effects are running and so on.  If the limit is high it lets the frame rate go up higher when nothing is happening but then when things get complex it'll drop back down and things will seem choppy.  Having it limited smooths the experience overall so I don't think the default limit will be changed to be high.  Having a setting in the UI is doable, though, and the larger team is thinking about that.

**Comment by ghost** [comment]
The email I used is closed (it used to be a Google account). So I can not do that. I have tried contacting community staff before without receiving a response back.

I understand your reasoning but I do not find it reasonable. As I said, gaming monitors on the market come in ranges of 120 Hz to 240 Hz native refresh rates. You are capping it at the absolute minimum.

This is why I suggested for fps_max to be limited to a reasonable amount and those who wish to implement a cap can do so by enabling vertical synchronisation lock (will lock FPS to monitor Hz) in the graphics settings.

I just find it annoying that as somebody who has a 144 Hz native monitor (to be upgraded to 240 Hz later this year) have to go around and use launch parameters or input configuration variables in files to allow Dota 2 to use the extra 24 Hz properly.

**Comment by gdrewb-valve** [comment]
The team said that you should go to https://support.steampowered.com/ and open a Steam support ticket to have the dev.dota2.com account reset.  They need to know your Steam information plus that you  are actually the right person to own the forum account and that'll let them check your info.

I don't think the fps_max setting is going to change but you're certainly welcome to make a post on it.

**Comment by ghost** [comment]
Would you not agree that it is rather problematic that Dota 2 is locked to 120 FPS when a user has his system configured towards 144 Hz? Or 240 Hz?

I hope a user friendly solution to this is introduced some time. Thank you for the information and swift replies to my cry for change. ^^
