### ISSUE TITLE
[linux] Can't launched the game with nvidia [Unable to launch game (Unable to create dummy window for GLMDisplayDB)]

### ISSUE THREAD

**Issue by n1colius** [ValveSoftware/Dota-2#948]
I just can't lauch the game and it gives me this messages..
Unable to launch game (Unable to create dummy window for GLMDisplayDB)

i really want to play dota2 on linux rather then on windows..
my system is Ubuntu 16.04
i use nvidia-364 driver

my laptop have gpu Nvidia 940M and Intel HD 5200..

when i'm using intel driver, the game successfully launch, but when i used nvidia driver, it gives me that error messages.. i want to play the games with nvidia driver because when i play with intel driver, the game just lagged a lot even in the lowest setting..

i used this command to switch between intel and nvidia
`sudo prime-select nvidia`
`sudo prime-select intel`

hope you guys can give me some solution here
Thanks in advanced

**Comment by gdrewb-valve** [comment]
Your problem isn't with Dota, it's a system configuration issue, so this may not be the best place to get answers.  I'd first check in the steam-for-linux repo here and look at the issues with running Steam on 16.04.  There are Steam runtime incompatibilities which cause a variety of problems.

**Comment by n1colius** [comment]
okey, i will try to ask on steam-for-linux repo.
Thanks

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Dota issue and suggestions aren't coming in.
