### ISSUE TITLE
[LINUX] Arcana Vote

### ISSUE THREAD

**Issue by pdrocaldeira** [ValveSoftware/Dota-2#949]
I can't see arcana vote tab in the battle pass. It shows me this message: "FAILED TO LOAD ARCANA VOTE DATA. TRY AGAIN LATER."

**Comment by gdrewb-valve** [comment]
It works correctly for me on my Linux box.  Over what period of time have you tried it?

**Comment by pdrocaldeira** [comment]
I was trying since sunday. Well it works now, sorry for your time. Thanks!
