### ISSUE TITLE
[Mac] Home page sales display bug

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#95]
![screenshot 2015-06-24 23 21 25](https://cloud.githubusercontent.com/assets/5674597/8348396/cda77c36-1ac7-11e5-9578-e7b20ea10995.png)

The texts are overlapping each other.

**Comment by gdrewb-valve** [comment]
Not a Linux/Mac issue but I'll pass it on.

**Comment by gdrewb-valve** [comment]
The larger team says the next update will fix this.

**Comment by SsnL** [comment]
Not fixed.

**Comment by SsnL** [comment]
![screenshot 2015-06-27 12 29 55](https://cloud.githubusercontent.com/assets/5674597/8393530/3ce2a9c0-1cc8-11e5-90c2-dc6e9b1306f6.png)

**Comment by gdrewb-valve** [comment]
They say it'll be fixed soon but, as you can tell, we don't have good tracking from general bugs back to Mac/Linux issues so closing this out.
