### ISSUE TITLE
teleportation and other effects not working

### ISSUE THREAD

**Issue by deepakkeyal** [ValveSoftware/Dota-2#950]
Hi, I have battle pass level 240 but few of my effects are not working(fountain,teleportation) .

**Comment by gdrewb-valve** [comment]
Can you post your system information?

**Comment by deepakkeyal** [comment]
What all system information do you require?

**Comment by gdrewb-valve** [comment]
The system information from the Steam client's Help menu.

**Comment by deepakkeyal** [comment]
Computer Information:
    Manufacturer:  Alienware
    Model:  Alienware 15 R2
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2592 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
    
Video Card:
    Driver:  Intel(R) HD Graphics 530

    DirectX Driver Name:  nvd3dum.dll
    Driver Version:  20.19.15.4390
    DirectX Driver Version:  10.18.13.5940
    Driver Date: 18 Feb 2016
    OpenGL Version: 4.5
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 980M   
    VendorID:  0x10de
    DeviceID:  0x13d7
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1536 x 864
    Desktop Resolution: 1536 x 864
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary Bus: PCI Express 8x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 
    
Sound card:
    Audio device: Speakers (Sound Blaster Recon3D
    
Memory:
    RAM:  16283 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  1064121 Mb
    Largest Free Hard Disk Block:  853377 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
This forum is only for Mac and Linux porting bugs, you'll want to post at dev.dota2.com
