### ISSUE TITLE
[OS X] Alt and cmd ping reversed.

### ISSUE THREAD

**Issue by p-groarke** [ValveSoftware/Dota-2#951]
Since cmd and alt are reversed in OS X, would it be possible to add an option to map ping to cmd?

Ty

**Comment by gdrewb-valve** [comment]
If you go into the advanced section of the keybind page and opt to allow the Windows/Command key to be bound as a key, then in the advanced options you choose to bind alt as command does that do what you want?

**Comment by p-groarke** [comment]
Can we rebind the ping key? If so, then yes that would work.
I got to go sleep, i'll test tommorrow.

**Comment by gdrewb-valve** [comment]
You can rebind what key means alt so you can have command function the way alt does by default.

**Comment by p-groarke** [comment]
Oh man, thats exactly what I was looking for (bind windows + rebind alt)! Sorry to have wasted your time, huge thanks for the help.

Also great work on all the new key bindings (especially mouse up/down), wont need my EventTap thingy anymore. <3
