### ISSUE TITLE
Inventory miniview persistant bug

### ISSUE THREAD

**Issue by 420git** [ValveSoftware/Dota-2#952]
![2016-07-20-050359_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397789/16974121/14d38ca4-4e42-11e6-83db-f2b339a1aeb7.png)
Inventory miniview cant be minimized sometimes check image

**Comment by gdrewb-valve** [comment]
This isn't a Mac/Linux issue so the larger team will take a look.

**Comment by gdrewb-valve** [comment]
The larger team can't get this to occur and doesn't have a lead on this.  Do you have a set of steps which causes this to happen reliably?

**Comment by 420git** [comment]
From a fresh start nothing seems to happen.
However after hours of use (~4 matches) just like other bugs (ex:stuck at do you want to quit dota) if I press preview bundle forexample it happens.

**Comment by gdrewb-valve** [comment]
OK, thanks for the info.

**Comment by 420git** [comment]
Update: This bug started to appear more even on fresh starts upon trying to preview set bundles
and not only on linux it happened on win xp as well.

**Comment by gdrewb-valve** [comment]
I'll pass this on to the larger team.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Mac/Linux issue.
