### ISSUE TITLE
Help me with dota on Ubuntu 16

### ISSUE THREAD

**Issue by ThreadShakur** [ValveSoftware/Dota-2#954]
I have videocard Nvidia 9800 GT very old card, but on windows with directx 9 support my fps on medium settings is ~100, but when i come on linux and enable opengl support my fps is ~ 50 on my card opengl support - 2 and directx9 on forum i seen that dota needs opengl 2 on another forum i seen that i need opengl suppor 4... I can't buy new videocard and i want play on linux... maybe i can enable opengl 2 in dota settings?

**Comment by gdrewb-valve** [comment]
Dota requires OpenGL 3.1 these days.  Do you know what OpenGL driver you're using?  This isn't the best place to get advice on how to configure OpenGL for your system, but possibly you'll get some replies.

**Comment by ThreadShakur** [comment]
I use driver from nvidia, version 341, what obout opengl driver.. I dont know what driver i use< but if i will install driver version 2.1 how on my videocard fps will up? And 1 question : in future dota will support driver 2.1 ?

**Comment by gdrewb-valve** [comment]
It looks like your card is old enough that NVIDIA isn't doing new driver releases for it.  If you run glxinfo what does it say?

As for whether your FPS will increase with a different driver I have no idea, that'd be a question for NVIDIA.  As they don't seem to be doing driver updates there may not be a Linux solution for your card.

**Comment by ThreadShakur** [comment]
On windows i use driver 341 how on linux.. Business in opengl.. dota support directx 9 and my card support directx9 too... Question on opengl... Valve will make support for opengl 2.1? Or how now i can run dota 2 with support Opengl 2.1

**Comment by Tele42** [comment]
Hello @ThreadShakur, the Geforce 9800 GT is capable of OpenGL 3.3 and nvidia's 340 series is the long-term support series for this generation of card.

As a side note, the current iteration of Dota 2 used to be called Dota 2 Reborn, it's changed game engines from Source 1 to Source 2, which also bumped the minimum requirements.

**Comment by gdrewb-valve** [comment]
Just to be clear OpenGL 3.1 is the minimum requirement, there is no way to run Dota against OpenGL 2.1.

**Comment by gdrewb-valve** [comment]
Closing as this isn't a Dota problem.
