### ISSUE TITLE
Bad responsive GUI in 2560x1080

### ISSUE THREAD

**Issue by santiihoyos** [ValveSoftware/Dota-2#955]
Hi, i have this problem in Linux, Mac and Windows with the GUI...

my resolution is: 2560x1080

![bug1](https://cloud.githubusercontent.com/assets/10730150/17028042/8066b6ce-4f66-11e6-8ed4-83f1590f7f87.png)
![bug2](https://cloud.githubusercontent.com/assets/10730150/17028043/80688b84-4f66-11e6-8fb1-0b4f624646e8.png)

Thanks.

**Comment by gdrewb-valve** [comment]
This forum is for porting bugs that do not happen on Windows, you'll want to post this at dev.dota2.com

**Comment by santiihoyos** [comment]
The bug is in Linux and Mac but the bug is in windows also.
