### ISSUE TITLE
 [Ubuntu 16.04] GTX 960M low FPS 

### ISSUE THREAD

**Issue by s4iya** [ValveSoftware/Dota-2#956]
I had a lot of trouble trying to find the correct driver for my GTX 960M to be able to play Dota 2 on Steam correctly.
After having a lot of PC freezing issues with every drivers possible, probably due to bad installation, it seems that now it doesn't crash anymore. But I can't play correctly because of really bad FPS.
My laptop is an Acer V-Nitro17, which has IGP and GPU.

First of all : 
- I come from W10, in which I had a very hard time trying to find the correct Nvidia driver. I was updating driver through Nvidia GeForce experience, but with the latest drivers, the GPU was overheating (~70-80~°c) and the PC froze and crashed. I've read online that apparently the 960M freezes when it is more than 80°c.
  Finally I asked what driver I should use on Nvidia forums, and someone told me to never update the drivers **on laptops**, never use GeForce experience, and only use the driver provided by the manufacturer website. I did that, and never had any issues (on Dota 2, or any other games) since then. It was driver 359.xx if I remember.
- Now, I installed Ubuntu 16.04 from a fresh install, and of course I have issues with the GPU. I'm using nvidia-prime because of the IGP/GPU.
  As I said above, it seems that now the laptop doesn't freeze/crash anymore in game, and on the desktop (because certain driver, like 367 was making my laptop freeze after few minutes of utilisation on desktop, and when I mean freeze, there's nothing else to do except a force shutdown).
  I was glad that I was finally done with this issue, but when I tried playing games (Dota 2 for instance), I experienced a very low FPS, depending on the driver.

The two most stable are : 
367.35 is running at 30-40FPS on low quality. 10FPS on ultra quality. (~50°c)
358.xx is running at 120FPS on low quality. 30FPS on ultra quality etc.. (~60-70°c)

Same goes for every driver, some experience low FPS with decent temp, high FPS with high temp (->freez/crash), low FPS with high temp etc..

So yes, 358.xx (for example) is running at 120FPS in low quality, but my problem is that on W10, it was running at 120FPS on Ultra Quality, without over heating. So I'd like Ubuntu to do the same, if possible of course.
I've been looking everywhere online, and been on this for several days now, unfortunately nothing I found worked for me, or nobody had the exact same issue.

Is it a driver issue ? Over heating ? Compatibility with Linux ? Bad installation ? Or is my GPU too recent that ironically I can't play correctly ?

`OS: Linux Ubuntu 16.04 LTS x64bits`
`CPU: Intel Core i5-6300HQ CPU @2.30GHZ x4`
`GPU: Nvidia GeForce GTX 960M/PCIe/SSE2`
`IGP: Intel® HD Graphics 530 (Skylake GT2)`
`RAM: 8Gio (7.7Gio)`

I can provide more informations if needed.
I'm kind of lost and don't want to go back on W10, so I came here in hope for a possible solution.

**Comment by gdrewb-valve** [comment]
You may have more luck asking in areas that deal with your distro and GPU, but somebody might have some advice here.

**Comment by s4iya** [comment]
I asked the same question on AskUbuntu (StackExchange), unfortunately the only answer I received was that I should use Bumblebee or Nvidia-prime, which unfortunately wasn't exactly my problem. Nothing else online. I have no idea where I could ask this, so I came here.

**Comment by konstantinblaesi** [comment]
If you're running Linux 4.6 (4.7 might have fixed this, idk) try disabling intel pstate by appending "intel_pstate=disabled" to your boot parameters. There seems to be a pstate regression, see

http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil
https://www.phoronix.com/scan.php?page=news_item&px=P-State-Possible-4.6-Regression

**Comment by djnsu** [comment]
Have the same problem with nvidia 740m. GPU is obviously overheating when it working on Ubuntu 16.04, unlike when it starts on W10.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
