### ISSUE TITLE
21:9 Ultrawide Monitor 2560 x 1080 Mac

### ISSUE THREAD

**Issue by tomekmarchi** [ValveSoftware/Dota-2#957]
http://i.imgur.com/1Lg6hir.png

All that needs to be fixed is the HUD. Everything else is playable.

**Comment by tomekmarchi** [comment]
For over 2 years it's been like this without any fix or patch.

**Comment by gdrewb-valve** [comment]
This forum is for porting bugs specific to Mac and Linux.  This issue is not related to the platform, you'll want to post at dev.dota2.com
