### ISSUE TITLE
[MAC] Denying Creeps doesn't give XP

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#958]
I recently read a patch note that said denying creeps gives blah blah XP, up until this point I thought denying creeps and XP was removed from the game, because when playing on my MAC, if i deny a creep I don't see my XP meter go up. 

This is either a graphical glitch where it just doesn't show, or it's actually not calculating the XP.

**Comment by gdrewb-valve** [comment]
I heard back that it's XP given to the other side, not to the player denying.
