### ISSUE TITLE
System resources utilization

### ISSUE THREAD

**Issue by sultanahamer** [ValveSoftware/Dota-2#959]
Hi Team,

I am using mac book pro. 16Gig Ram, i7 2.5Ghz running OSX Yosemite. What I observe is dota takes a lot of cpu usage even if I just keep it open and do nothing. It takes up almost 70% of CPU usage. I stay at main menu and I loose my laptop battery. I understand if I start playing or spectating a game hitting 100% is okay. But just keeping it open, stay at main menu and loosing lot of battery is not ok. This might not be a priority issue but we can prioritize this at a later time. But I just wanted to bring this to your notice.

**Comment by gdrewb-valve** [comment]
This isn't a Mac-specific issue so you'll want to post at dev.dota2.com

There are no plans to try and reduce CPU usage of the main menu, so I don't believe this will change any time soon.
