### ISSUE TITLE
[Mac] Winter Wyvern courier armory display

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#96]
![screenshot 2015-06-24 23 25 08](https://cloud.githubusercontent.com/assets/5674597/8348451/531b42bc-1ac8-11e5-8f15-d458fc8a1347.png)

The courier's overview picture is missing.

**Comment by Tele42** [comment]
@SsnL Can you also type out your issue so that this report is searchable?

**Comment by SsnL** [comment]
Yeah I should've done that. I edited the report! Thanks @Tele42

**Comment by gdrewb-valve** [comment]
Probably not a Linux/Mac issue.

**Comment by gdrewb-valve** [comment]
Confirmed that this happens on Windows also so I've passed it on to the larger team.  It won't be tracked here.
