### ISSUE TITLE
[OSX] Sound stops working

### ISSUE THREAD

**Issue by jfabre** [ValveSoftware/Dota-2#960]
OSX 10.11.5
Macbook Pro Retina Mid 2012
Herman Kardon soundsticks wireless through **bluetooth**

Once in a while, the sound just stops working(only in dota) and to make it work again I have to:
1- go to audio config
2- toggle sound device from default to soundstick wireless or -sw- to default.
3- Sound comes back and it seems it plays all the sound effects I missed since at the same time.

**Comment by icculus** [comment]
Sorry for this super-late reply...we ended up replacing most of the Mac-specific audio code around October; do you happen to still be seeing this bug?

**Comment by jfabre** [comment]
Nope, it actually stopped occurring a couple months ago, probably in October.
I thought it was because of my bug report, oh well... 😃

**Comment by kisak-valve** [comment]
Thanks for the feedback @jfabre, closing.
