### ISSUE TITLE
[macOS]FPS much lower with macOS Sierra.

### ISSUE THREAD

**Issue by zanderzhng** [ValveSoftware/Dota-2#961]
Used to have 50 fps before upgrading to macOS Sierra, but now with 20 around, same settings.

**Comment by gdrewb-valve** [comment]
Did anything else change or did the FPS change solely because of the OS upgrade?  If it was only from the OS upgrade you'll want to report this to Apple as the change came from them and not Valve.

**Comment by gdrewb-valve** [comment]
Closing pending more info that this is a Dota issue.
