### ISSUE TITLE
[OSX] Game crash on match found pop-up

### ISSUE THREAD

**Issue by perezect** [ValveSoftware/Dota-2#964]
Dota2 crashes as a match is found consistently since Update #2, July 27 2016 for me; I somewhat suspect the recent changes to bring screen to front, however disabling the pop-up option does not fix it, nor does uninstalling and reinstalling.

System specs are:

```
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro10,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.26" x 7.05"  (13.27" diag)
                                            28.6cm x 17.9cm  (33.7cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114543 Mb
    Largest Free Hard Disk Block:  8360 Mb
    VR Headset: None detected

```

**Comment by gdrewb-valve** [comment]
If there are no failure entries in the Steam system information that often means the problem is on the system side and outside of Dota's error tracking.  Do you have any console logs (you can add -con_logfile to your launch options and the console logs will go into <Steam Dota>/game/dota/console.log) or other system error info?

If you validate your local install in the Steam client does that find any issues?

**Comment by perezect** [comment]
Validating doesn't find any issues.
Attached is the console.log, as well as the serverlog.txt (this spans back to my first game, but shows the past two days at the bottom). Ironically enough, OS X wasn't saving crashlogs, so I assumed the problem was steam specific. Thanks for that, wasn't sure how to save log files of the console. Are there any other tests I should run? [I've been following this dota.dev link](http://dev.dota2.com/showthread.php?t=189581) to the letter .
[server_log.txt](https://github.com/ValveSoftware/Dota-2/files/389787/server_log.txt)
[console.txt](https://github.com/ValveSoftware/Dota-2/files/389788/console.txt)

**Comment by gdrewb-valve** [comment]
The logs don't have anything unusual in them so it's unclear what's going on.  We'll have to see if more people are hitting it so that we can find a pattern and narrow down the cause.

**Comment by gdrewb-valve** [comment]
Does this still happen with 7.00?

**Comment by perezect** [comment]
Not to my knowledge, sorry for being unresponsive!
