### ISSUE TITLE
[Linux] Hotkeys not working in-game

### ISSUE THREAD

**Issue by AutoAwesome** [ValveSoftware/Dota-2#965]
Hi guys,

I just played a game and noticed in the beginning of the game that none of my hotkeys are working all of the sudden. Yesterday I played some games and everything was fine.

Surprisingly I could open the chat and even use the keys that would not work in the game - so I could at least tell my team why I am going to abandon :-)

I have tried a lot of things also "Bind keys based on keyboard position" but everything gives me weird results. For example I can bind keys in the hotkeys options, but the keys are completely different than the keys I choose. Still they don't work in-game.

I am playing on a gentoo linux box and I haven't updated my system for like 2 weeks. So I am pretty sure that is has nothing to do with my setup since I have played a lot of games after my last world update.

Things I have tried:
- Restart the game
- Check for updates
- Verify game integrity
- Verify that my keyboard really works (chat works in-game, hero hotkeys not)
- Verify my hotkeys in the Dota settings
- Verify that there is no key stuck (like the Alt-Key for example)
- Tried it with a different keyboard
- Submitted issue to Dota2 Bugtracker :-)

Is there anything else I could try or any other information I can provide to you?

**Comment by gdrewb-valve** [comment]
Add -input_message_spew to your launch options and you'll get extra console spew about key presses.  You can go to the settings, bind some keys and then go in-game and press those keys, then gist the console log here.

**Comment by AutoAwesome** [comment]
Hi Drew,
Thank you a lot for your response.
- In this gist I have tried is moving with my hero and hitting S to make him stop moving. It doesn't work.
  I also reassigned the S key in the dota to the same key (S) just to be sure.
  https://gist.github.com/AutoAwesome/b689e1cc5bd8f2f9028c0b6666ae1bc0
- And in this gist I have tried to go to the dota settings and rebind the hotkey Q.
  It also doesn't work. (Edit: Sorry I mean i can bind it, but it doesn't work ingame.)
  https://gist.github.com/AutoAwesome/4bdb19165b4ba644ee8260c6a8e07053

FYI: The # (hash) key opens the dev-console in my setup.

**Comment by gdrewb-valve** [comment]
SDL isn't recognizing your keypresses, so this appears to be the same thing as #453.  Assigning to the SDL dev.

**Comment by AutoAwesome** [comment]
After the ~400mb patch today, my hotkeys are working again. 

For the reference: I changed absolutely nothing on my setup. Just made a day dota break :)

Feel free to close this issue if there is nothing left to look at for your dev-team.
Thank you a lot.

**Comment by gdrewb-valve** [comment]
There probably isn't more the dev can get but I'll leave closing this to him.

**Comment by DarthBOR** [comment]
This happened to me when I've launched client with Russian layout enabled. When I've restarted it with En it worked just fine.

Hey @AutoAwesome! Which layouts do you have?

**Comment by Olosinsk-commits** [comment]
I have same problem every time when I (accidentally) launch a game after using Ru layout and I can't change layouts from Ru to Eng during the game. I have Ubuntu 14.04 LTS. Do you have suggestion how to resolve it? Thanks

**Comment by AutoAwesome** [comment]
@DarthBOR I have the german keyboard layout. But as I said, I really have changed nothing. It broke after an update and also fixed it self after the next update :-)

@ssinsk I did absolutely nothing. :-) Just noticed that it was broken after an update. But after the next update it worked again.

**Comment by gdrewb-valve** [comment]
Is this still an active issue?  Note that any situations involving changing the keyboard layout during play would be different from the issue here.

**Comment by AutoAwesome** [comment]
No it is not and was never an issue again. Everything works as expected.

**Comment by gmelikov** [comment]
It's still an issue for me, Ubuntu 20.4. Starting with russian layout enabled disables entirely keypresses until restart with english layout.

**Comment by kz159** [comment]
@gmelikov  thank you so much, you've literally saved my match

**Comment by magist3r** [comment]
@gmelikov @kz159 There is an option on the Advanced Hotkeys tab in settings called 'Bind keys based on keyboard position'. It solves the issue for me.
