### ISSUE TITLE
Buildings sometimes half or all the way in the ground

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#966]
A couple of days ago, I had a very weird game where all the buildings (towers, barracks, ancients, fountain) were half-way in the ground and at the wrong position. After restarting Dota, the effect was gone, but watching another game, I just had it again, so it is randomly reproducible. I attached a couple of screenshots to show what it looks like. I'm using the immortal gardens map skin.

Two other things I also noticed: runes weren't visible. Other people could see them, but I couldn't and therefore also couldn't pick them up, which screwed me up pretty much. I guess they were also underground.

Another weird effect was fog of war in our own fountain which was probably a result of the fountain cannon being in the wrong position.

![screenshot_20160728_024809](https://cloud.githubusercontent.com/assets/911270/17272587/9d8c9fb2-569a-11e6-967c-622a4ab7f825.png)
![screenshot_20160728_024856](https://cloud.githubusercontent.com/assets/911270/17272588/a08dd26c-569a-11e6-8373-20fab274c0bc.png)
![screenshot_20160728_025407](https://cloud.githubusercontent.com/assets/911270/17272589/a23027f0-569a-11e6-8d5d-1540eb66fbbe.png)
![screenshot_20160728_025647](https://cloud.githubusercontent.com/assets/911270/17272590/a3ca71ba-569a-11e6-9858-9ccf14d5e1d6.png)
![screenshot_20160728_030351](https://cloud.githubusercontent.com/assets/911270/17272592/a54002ee-569a-11e6-9eed-b2971334c728.png)
![screenshot_20160728_032630](https://cloud.githubusercontent.com/assets/911270/17272594/a8c5cbd8-569a-11e6-82a6-53f093a9c5ba.png)

System information:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 367.35
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1401
Revision Not Detected
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 5120 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  16000 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  6572061 Mb
    Largest Free Hard Disk Block:  1926633 Mb
    VR Headset: None detected

**Comment by gdrewb-valve** [comment]
Probably not platform-specific.

**Comment by phoerious** [comment]
Little side node: this bug also applies to hero demo mode which is not supported by the immortal gardens. So it's probably not a terrain skin issue.

**Comment by phoerious** [comment]
This bug is becoming really game-breaking. Neutral creeps are also often in the wrong position, but teleport to the correct location when using right clicks or abilities on them. Spell animations are rendered in the wrong places and even heroes randomly teleport over short distances. Something is seriously messed up with the coordinate systems of heroes, creeps, structures, spells and runes.
The only way to get rid of these issues is restarting Dota.

**Comment by gdrewb-valve** [comment]
This looks to be happening on all platforms and the larger team is looking, there won't be much status here.

**Comment by gdrewb-valve** [comment]
I haven't heard anything from the larger team but is this still happening?

**Comment by phoerious** [comment]
I haven't played much for 3 months and haven't had it in 7.00 yet. If it happens again, I'll let you know.

**Comment by gdrewb-valve** [comment]
OK, closing for now.

**Comment by VicPetrov** [comment]
I've just had this after rebooting from a thermal throttle on a win10 system.
Everything as mentioned above teleporting units buildings underground etc.
