### ISSUE TITLE
[Linux] Desktop friendly minimize when focus lost option reset after every update

### ISSUE THREAD

**Issue by vhda** [ValveSoftware/Dota-2#967]
Like the title says, this option value is reset every time there is an update (which is basically twice a day, nowadays). Would it be possible to include a fix for this in one of these frequent updates? ;)

**Comment by gdrewb-valve** [comment]
Do any of your settings get saved?  Is that the only one that doesn't work?

**Comment by gdrewb-valve** [comment]
Closing pending more info.

**Comment by vhda** [comment]
I somehow have missed your reply 3 days ago, I'm sorry.
As far as I can tell that's the only option that was being reset. I've just changed a bunch of video settings, so I can confirm this after tomorrow's update.

Note: I think that today's update did not reset the option. Is it possible this was fixed in the meanwhile?

**Comment by gdrewb-valve** [comment]
I don't believe anybody fixed anything in this area but I don't see every single change.  Regardless if you see it again we'll reopen this.

**Comment by vhda** [comment]
@gdrewb-valve I confirm that everything is working correctly now.
It is possible this fix was included in some other more important change.

Thanks for taking the time to review this issue.

**Comment by vhda** [comment]
Just understood what's happening: this configuration value is reset after using Phoronix Test Suite DOTA benchmark.

DOTA is called as following from the benchmark script:

```
dota.sh +con_logfile $LOG_FILE +timedemoquit dota2-pts-1971360796 +demo_quitafterplayback 1 +cl_showfps 2 +fps_max 0 -nosound -noassert -console -fullscreen +timedemo_start 50000 +timedemo_end 51000 -autoconfig_level 3 -testscript_inline \"Test_WaitForCheckPoint DemoPlaybackFinished\; quit\"
```

Which of these options enables desktop friendly minimize? Is there a way of avoiding this change from happening?

**Comment by gdrewb-valve** [comment]
It's the -fullscreen that's doing it, you'd need to remove that from the script.
