### ISSUE TITLE
[Linux] Fantasy Challenge score not working

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-2#968]
![2016-08-02-121650_1920x1080_scrot](https://cloud.githubusercontent.com/assets/425930/17340072/ea62388e-58ab-11e6-8a8f-59d1a87bb4b5.png)

System:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/163736a69492dfae99e2979adbdaf9c9d57fb65c/gistfile1.txt

**Comment by gdrewb-valve** [comment]
Unlikely to be Linux specific, checking with the larger team.

**Comment by gdrewb-valve** [comment]
The larger team confirms its a general issue and a fix is coming.
