### ISSUE TITLE
[Mac] Nyx carapace and OD's imprisonment 

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#97]
With OD casts imprisonment to a Nyx whose carapace is on, Nyx's model disappears but the carapace model remains floating in mid air.

**Comment by gdrewb-valve** [comment]
This isn't a Linux/Mac issue and apparently can occur in the Source 1 Dota 2 also.  I've passed it on but it definitely won't be tracked here, so closing.
