### ISSUE TITLE
Captain's mode is using place holder values during draft

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#972]
hi,
I always thought I already reported this one, but I couldn't find it using githubs search.
The issues is that is that when spectating or watching a replay the draft screen in captains mode games has 'TEXTFIELD' written for unpicked heroes and displays 5 'primary attribute strength' symbols.
![dota2bug_draft](https://cloud.githubusercontent.com/assets/5174562/17381453/488dea2c-59cc-11e6-8d74-7904a3bf62c8.png)

strace for failed open calls was overwhelming, including the inability to find 'scripts/talker/response_rules_abyssal_underlord.txt' :-)

Likely not related to the crashing issue, but for the sake of completeness it should be reported here. Especially given that I have never seen that issue on a twitch stream - who are probably using windows.

**Comment by Tele42** [comment]
There's a good chance you did, since the previous Dota-2 issue tracker was made private. The Dota-2-Reborn issue tracker was then moved to replace it back when we switched over to using Dota 2 Reborn as the main client. I can confirm this occurs on Gentoo Linux.

**Comment by danginsburg** [comment]
We have a fix for this, it will be in the next release.  It was a missing video file on the Linux/OSX version.

**Comment by Turmfalke2** [comment]
Nice, is there anyway for us to know which of all the missing files are actually required/we are supposed to have?

@danginsburg 
List of possible missing files from watching a a few minutes of a game yesterday
http://pastebin.com/raw/PCsw9Zwt
I guess the code for src made it in the release by accident, but what is the deal with the rest?

**Comment by gdrewb-valve** [comment]
The code can run in a variety of configurations so it'll check for various files.  There will always be requests for files that don't exist so that's not a good guide.

This particular file is a background video that covers the placeholders.

**Comment by gdrewb-valve** [comment]
After updating are you still seeing issues?

**Comment by Turmfalke2** [comment]
@gdrewb-valve I can confirm that the bug is fixed, the dota logos with the light behind them actually look pretty nice.
![dota2bug_draft_fixed](https://cloud.githubusercontent.com/assets/5174562/17455761/82d1517c-5bc2-11e6-84cf-00ceb2d18fad.png)
