### ISSUE TITLE
On the match overview all items cost buy_cost

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/Dota-2#978]
hi,
Not sure whether linux specific or not:
![dota2_buycost](https://cloud.githubusercontent.com/assets/5174562/17458728/347395e4-5c1c-11e6-8221-dafc5048dc54.png)

**Comment by gdrewb-valve** [comment]
I'll check with the larger team.

**Comment by gdrewb-valve** [comment]
Confirmed that this affects all platforms, the larger team is working on it.
