### ISSUE TITLE
[Ubuntu/Linux] Steam layer does not working

### ISSUE THREAD

**Issue by VitorVRS** [ValveSoftware/Dota-2#979]
Since the new chests (Lockless and Trove) i cant open steam layer (shift+tab) or everything that uses steam layer are not working properly like:
- Open player steam profile
- Buy on store
- Open steam friendslist
- Shift tab

**Comment by gdrewb-valve** [comment]
The Steam area here is steam-for-linux, you'll want to post there.  We'll leave this open for the moment, though.

**Comment by VitorVRS** [comment]
That's not happening anymore since a few updates.
