### ISSUE TITLE
[Linux] Crash when loading game or demoing hero

### ISSUE THREAD

**Issue by tiburcillo** [ValveSoftware/Dota-2#98]
Hi Valve,

When I try to load a game in the reborn client, after a few seconds the game crashes and I'm back on the desktop. All the other functionality seems to work fine (Armory, Interface browsing, ...).
My specs:
- Linux Mint 17.1 Cinnamon x64
- Processor: AMD Phenom X4
- OpenGL renderer string: Gallium 0.4 on AMD RV770
- OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.0

Dumps and stdout on http://files.strat3go.com/dota

Let me know if you need any other information. 

Edit: I just realised this might be the same as #10 and #41 . I indeed have and AMD Phenom X4 processor which does not support SSSE3.

**Comment by gdrewb-valve** [comment]
Yes, this would be the same SSSE3 issue, closing.

**Comment by Tracinha** [comment]
The update from 26/06 dont solve this problem!!!
