### ISSUE TITLE
[Ubuntu 16.04] dota.sh works fine, but I can't launch the game from steam client.

### ISSUE THREAD

**Issue by Loenl3** [ValveSoftware/Dota-2#980]
I can't launch the game from steam client (it will get stuck at "launching"), I changed libudev symlink from '..../dota 2 beta/game/bin/_whatever_/libudev.so....' to system library (64), now ./dota.sh is able to run the game.
guess I have to change some from ubuntu12_32/ too, which?

**Comment by gdrewb-valve** [comment]
Working around Steam runtime issues is outside the scope of this forum.  There are a bunch of posts in steam-for-linux which might be relevant and you might also want to ask in forums for your distro.

Also, if you post system information somebody reading this might comment so I'll leave this open for  bit.

**Comment by ramma** [comment]
I was having this after the most recent update. No console output upon trying to start the game, and restarting steam didn't help. Restarting lightdm finally resolved it.

**Comment by gdrewb-valve** [comment]
Closing now, hopefully something in steam-for-linux will cover the issue.
