### ISSUE TITLE
Item names incorrect

### ISSUE THREAD

**Issue by rudmint** [ValveSoftware/Dota-2#981]
Not sure if this issue Linux specific, but some items do not display the correct name when inspecting heroes.  It seems the item name field is instead populated by another equipped item's name.  See the two examples below.

![20160810180025_1](https://cloud.githubusercontent.com/assets/10488090/17573697/1d30ba40-5f2a-11e6-9300-d1ac066bd173.jpg)

![20160810180028_1](https://cloud.githubusercontent.com/assets/10488090/17573704/2535e5bc-5f2a-11e6-9a18-cc77d16b0e03.jpg)

I can't tell if the item above has a custom name or not, but it appears to.

My theory is it that has something to do with custom named items that have non-english (?) characters.  I tested this in a bot game, the item in question has a custom name, "上を向いて歩こう".  Instead it takes the name of the gloves item.

![20160810184533_1](https://cloud.githubusercontent.com/assets/10488090/17573839/157eb4f4-5f2b-11e6-9c4b-48526f00663b.jpg)

Can anyone confirm if this issue is Linux specific?

**Comment by gdrewb-valve** [comment]
I'll pass this by the larger team.

**Comment by ramma** [comment]
Just confirmed this in the match shown above. In case it's of use, the item name being displayed wrong is replaced by whatever item you last hovered over.

**Comment by gdrewb-valve** [comment]
The larger team has some thoughts on this but no fix as yet, they're going to keep looking.
