### ISSUE TITLE
[OSX] Naming issue in 2016 International Collector's Cache

### ISSUE THREAD

**Issue by Gabrielmtn** [ValveSoftware/Dota-2#983]
![image](https://cloud.githubusercontent.com/assets/1121921/17612770/ccc9b714-6023-11e6-9d3c-c54dfecae23f.png)

**Comment by Gabrielmtn** [comment]
Sysem info: 
![image](https://cloud.githubusercontent.com/assets/1121921/17612807/317a743c-6024-11e6-8544-98553c086dc4.png)

**Comment by gdrewb-valve** [comment]
This happens on all platforms so it won't be tracked here, I've passed this on to the larger team.

**Comment by Gabrielmtn** [comment]
👍
