### ISSUE TITLE
Black-is colors in ubuntu 16.04.1 

### ISSUE THREAD

**Issue by apolitech** [ValveSoftware/Dota-2#986]
what platform this is occuring on: Linux  (ubuntu unity 16.04.1, ubuntu mate 16.04.1)

[Video driver.txt](https://github.com/ValveSoftware/Dota-2/files/416815/Video.driver.txt)
[pc specs.txt](https://github.com/ValveSoftware/Dota-2/files/416816/pc.specs.txt)
![570_screenshots_20160814021707_1](https://cloud.githubusercontent.com/assets/14872517/17646194/818dfe62-61c8-11e6-8857-45a630a56e79.jpg)
![570_screenshots_20160814021601_1](https://cloud.githubusercontent.com/assets/14872517/17646195/82942840-61c8-11e6-8e1d-165bc16d4c07.jpg)

**Comment by gdrewb-valve** [comment]
Most likely a driver or configuration (gamma?) issue.

**Comment by ChristophHaag** [comment]
Mesa git: https://bugs.freedesktop.org/show_bug.cgi?id=97285

**Comment by gdrewb-valve** [comment]
As this is confirmed as a Mesa bug I'm closing.

**Comment by Tele42** [comment]
As a followup, [st/mesa: fix sRGB BlitFramebuffer regression](https://cgit.freedesktop.org/mesa/mesa/commit/?id=b662c70aeab6a92751514f30719c13a6de253b40) has landed in mesa git.
