### ISSUE TITLE
[Linux] Game not loading (needs executable)

### ISSUE THREAD

**Issue by HeavyHamster** [ValveSoftware/Dota-2#987]
Hello,
When I run Dota2 steam warns me that it can't find the executable.
First I've followed all the steps on the steam help with no luck, then I ran the script found under '/~/dota 2 beta/game/dota.sh' on a terminal and it outputs the following:

[edd@Fedora24 game]$ ./dota.sh
./dota.sh: línea 101: /home/edd/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: cannot execute binary file: Exec format error

Deleting the script and the exec and downloading it again doesn't fix it

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (32 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.5-300.fc24.i686+PAE
    X Server Vendor:  Fedora Project
    X Server Release:  11804000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 610/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 367.35
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x104a
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 17,05" x 13,66"  (21,81" diag)
                                        43,3cm x 34,7cm  (55,4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Analog Devices AD1984

Memory:
    RAM:  3969 Mb

Miscellaneous:
    UI Language:  English
    LANG:  es_ES.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  236038 Mb
    Largest Free Hard Disk Block:  143489 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by ramma** [comment]
My guess is 32-bit issue. As per the readme,

`The game requires a 64-bit capable CPU and distribution`

**Comment by HeavyHamster** [comment]
Yes, I've read that too and at first I thought it was for the DLC, but the game is 64-bit too. Silly question
