### ISSUE TITLE
Strange Bots behaviour in Dota Linux (on debian 8)

### ISSUE THREAD

**Issue by pozkaf** [ValveSoftware/Dota-2#988]
Hi,

In beginning of a training game, all bots (in difficult mode) run in the rune zone and are waiting for a rune to appear. It never appends to me when I used the dota 2 windows version.

Has anyone get the same behaviour in Linux ?

Thanks.

**Comment by ramma** [comment]
If I'm understanding correctly, you mean the bots are waiting for the first rune, but proceed to lane after it spawns? If so, that's because of some bot updates a few months back and is expected behavior.

**Comment by pozkaf** [comment]
Hi Ramma,

First, I effectively switch to Linux Dota a couple of month ago (May ?). And yes, absolutely all bots are standing in group around the first rune and then proceed to lane. It is surprising to me, but if you say it's the attended behavior, I will close this issue.

Thanks for your quick answer.
