### ISSUE TITLE
Miscalculation (or print bug) of item cost 

### ISSUE THREAD

**Issue by pozkaf** [ValveSoftware/Dota-2#989]
Hi,

In a training game, when I look in the shop for an advanced item for which I already have some component, I cannot see how much I need to pay to get it. Only the total cost appear, and a single "2" where I should see the amount left.

Thanks.
(debian 8)

**Comment by gdrewb-valve** [comment]
As this isn't a Mac/Linux bug I'll pass it along to the larger team and it won't be tracked here.
