### ISSUE TITLE
Crashes after Hero Pick (OS X)

### ISSUE THREAD

**Issue by jacobaughtab** [ValveSoftware/Dota-2#990]
At the start of the round my game will freeze and I have to Force Quit Dota 2 in order to relaunch it and reconnect. This is extremely frustrating because it makes it impossible to play in a party and troublesome to play in public matches because people will often quit the game or refuse to pause it while they wait for you. Any help would be appreciated.

Mac Information:
iMac (21.5in Late 2012)
Processor: 3.1GHz Intel Core i7
Memory: 8 GB 1600 MHz DDR3
Graphics: NVIDIA GeForce GT 650M 512 MB
Storage: 1TB Fusion Drive

**Comment by gdrewb-valve** [comment]
It's unclear what's going on.  We'll have to see if other people have similar issues and if there's some kind of pattern.

**Comment by hargiand** [comment]
This happenned to me too, but in my case i got kicked to main menu, then have to rc back to the game, happenned almost at the start of everygame.

MacBook Pro 13-Inch,mid 2012
Proc : 2.5Ghz Intel Core i5
Memory : 4GB 1600Mhz DDR3
Graphics : Intel HD Graphics 4000 1536 MB

**Comment by gdrewb-valve** [comment]
@hargiand you sound like you have a different problem.  Timing out waiting for a match is reported on all platforms, also #750 and #964 here are something like that.

**Comment by gdrewb-valve** [comment]
Does this still happen with 7.00?

**Comment by jacobaughtab** [comment]
Nope! The only issue now is texture crashes with grass and stairs from time to time, but after I disconnect and reconnect the problem is usually solved. Thanks for checking up!

**Comment by gdrewb-valve** [comment]
Can you open a new issue with specifics on the grass and stairs, plus and any CrashIDs from your Steam system information?

**Comment by jacobaughtab** [comment]
Sure thing, next time it happens I'll open an issue and include some screenshots and the CrashIDs.
