### ISSUE TITLE
Name missing in feed messages

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#991]
My friends name, `$11`, is missing from some messages on my feed:

![screenshot from 2016-08-17 18-38-06](https://cloud.githubusercontent.com/assets/110988/17729956/ebef01c8-64a9-11e6-8d2a-e2fcdd671fba.png)

**Comment by gdrewb-valve** [comment]
As this isn't platform-specific I'll pass this on to the larger team.
