### ISSUE TITLE
Incorrect kerning

### ISSUE THREAD

**Issue by u00101010** [ValveSoftware/Dota-2#992]
The "Finding Match" text has inappropriate kerning (A T).
![match](https://cloud.githubusercontent.com/assets/7419656/17745639/ec2d9fca-64ac-11e6-8422-84dfb5af775a.png)

**Comment by gdrewb-valve** [comment]
As this isn't platform-specific I'll pass this on to the larger team (in fact this would be in pango, the open-source text layout library, so it's not even a Valve issue).
