### ISSUE TITLE
Player loading screen very power consuming

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/Dota-2#993]
The loading screen where you see people's names. With rx480 and dota doing "nothing" the total pc consume is around 200wattage. The same amount is in gameplay and simply having a loading screen shouldnt consume thatkind of power. Even when you idle at main menu doesnt consume that much even it has some dynamic animation.

**Comment by gdrewb-valve** [comment]
This forum is for Mac and Linux-specific bugs, you'll want to post at dev.dota2.com
