### ISSUE TITLE
[Linux] Startup problem, Arch Linux

### ISSUE THREAD

**Issue by ruslansin** [ValveSoftware/Dota-2#997]
The game closes after dota 2 logo.
The problem appeared today, it worked yesterday
I get to following error after start:

[snql@snqlnote game]$ vblank_mode=0 primusrun ./dota.sh -vulkan -console -input_button_code_is_scan_code
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID: Caching Steam ID: 76561197989071965 [API loaded yes]
Steam_SetMinidumpSteamID: Setting Steam ID: 76561197989071965
Setting breakpad minidump AppID = 373300
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
DumpContextInfo: OpenGL vendor NVIDIA Corporation
DumpContextInfo: OpenGL renderer GeForce GTX 860M/PCIe/SSE2
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 3.30 NVIDIA via Cg compiler
Fontconfig warning: "/home/snql/C/Games/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/snql/C/Games/SteamLibrary/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
tcmalloc: large alloc 1412464640 bytes == 0x55b541329000 @ 
tcmalloc: large alloc 1945935872 bytes == 0x55b5958d1000 @ 
tcmalloc: large alloc 4238213120 bytes == 0x55b609c3b000 @ 
tcmalloc: large alloc 2650607616 bytes == 0x55b609c3b000 @ 
tcmalloc: large alloc 4245618688 bytes == 0x55b706e03000 @ 
/home/snql/C/Games/SteamLibrary/steamapps/common/dota 2 beta/game/dota.sh: line 104: 12645 Bus error (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

When trying to track down the problem, through the gdb debugger, I get the following information:

Network System Initialized
192.168.1.7: wlp5s0 
127.0.0.1: lo 
Physics Console Communications is not initialized
Game supporting (2) split screen players
[New Thread 0x7fffd19b1700 (LWP 14245)]
[New Thread 0x7fffc82b6700 (LWP 14246)]
[New Thread 0x7fffc0274700 (LWP 14247)]
Sound Initialization: Finish, Sampling Rate: 44100
[New Thread 0x7fffd19ad700 (LWP 14248)]
ConVarRef r_dota_force_forward doesn't point to an existing ConVar
AssociateNetMessageWithChannelCategoryAbstract: Trying to use an unregistered netchannel category!
AssociateNetMessageWithChannelCategoryAbstract: Trying to use an unregistered netchannel category!
ILocalize::AddFile() failed to load file "resource/keybindings_russian.txt".
Load a scaleform font provider?
WARNING: CDirWatcher not implemented

Thread 6 "GLRenderThread" received signal SIGBUS, Bus error.
[Switching to Thread 0x7fffebca6700 (LWP 14244)]
0x00007fffe6d01a79 in ?? ()
from /home/snql/C/Games/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so

Has anyone else encountered a similar problem?

Arch Linux, kernel 4.7
hwinfo: http://pastebin.com/GSnpwAQ1

**Comment by Tele42** [comment]
Hello @focusn1k, probably not the source of of your trouble, but `-vulcan` is not a valid command line option. You can try `-vulkan` instead.

There is a known scaleform crash being tracked at #922 which is possibly related, but I have a feeling this is more of an issue with primusrun. Another option to try is `optirun -b primus` instead of `primusrun`.

**Comment by ruslansin** [comment]
Hello @Tele42, thank you for your attention, I removed the option and brought it back with an mistake before. Unfortunately the problem is not solved when the following actions:
- Change the command primusrun to optirun -b primus
- Remove the -vulkan option

Yesterday I was playing dota. Perhaps the problem appeared after today's update

**Comment by gdrewb-valve** [comment]
The update was not likely to be the problem directly as it only had small gameplay-oriented changes.  Try validating your Dota install from the Steam client.

It does seem likely to be related to OpenGL somehow, but we'll see if other people hit it.

**Comment by Veske** [comment]
Crashes for me in main menu. Maybe related. Coredump below. Takes like 4 minutes to get to tty3 and close it.

![dota](https://cloud.githubusercontent.com/assets/5602603/17985216/7eb5218a-6b1d-11e6-9151-259f2a055192.png)

**Comment by gdrewb-valve** [comment]
@Veske your crash is in NVIDIA's Vulkan driver and should be reported to NVIDIA.

**Comment by Veske** [comment]
Allright, then it's because of the new update. Will let them know.

**Comment by ruslansin** [comment]
@gdrewb-valve The problem disappeared for me after a full reinstall of the game

**Comment by gdrewb-valve** [comment]
OK, closing since you're the original poster and your issue is resolved.
